table 'LD Reference'
	lineageTag: 9923127e-71af-4cc8-aefd-0617a07f4dcf

	column LDFlag
		dataType: int64
		formatString: 0
		lineageTag: 3c64a23b-170b-4169-a67a-765d3e62038b
		summarizeBy: none
		sourceColumn: LDFlag

		annotation SummarizationSetBy = Automatic

	column LDFlag_Description
		dataType: string
		lineageTag: 48aa20e9-0362-41cc-88fc-bb9b679f1de7
		summarizeBy: none
		sourceColumn: LDFlag_Description

		annotation SummarizationSetBy = Automatic

	partition 'LD Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQr0d1PwSU0sysvMS1dwySxOTMrMySypBDIT0/Pyi1NTlGJ1opUMgCr98hUIKM4sBismWm0sAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [LDFlag = _t, LDFlag_Description = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"LDFlag", Int64.Type}, {"LDFlag_Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

