table CDC
	lineageTag: ad831f4e-7848-483a-806f-965da93ad019

	column datasource
		dataType: string
		lineageTag: 5e3ac863-5ab5-4a15-8d67-7c8cbddfcdc2
		summarizeBy: none
		sourceColumn: datasource

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: 3ede5d76-aa04-4699-8b6a-4c946fac6b50
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column 'Unique Identifier'
		dataType: string
		lineageTag: 1c3beadd-d759-4d29-ad9f-88f12ce3df4e
		summarizeBy: none
		sourceColumn: Unique Identifier

		annotation SummarizationSetBy = Automatic

	column Treatment_Function_Code
		dataType: string
		lineageTag: 5dc1dfd4-a816-4202-af42-ab63b8675f6b
		summarizeBy: none
		sourceColumn: Treatment_Function_Code

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 520ba980-4f3d-48a1-b38d-8f2866897404
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: string
		lineageTag: 3937d2b2-27d5-48fb-a0d8-33a40572f6e6
		summarizeBy: none
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: a6ab753a-c269-4466-ad5e-34ef8e896a30
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: 395524ab-c661-4682-8229-0ec6a94f3e54
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Site_Code_of_Treatment
		dataType: string
		lineageTag: 497973f3-2bec-466b-976d-a003edcb19a5
		summarizeBy: none
		sourceColumn: Site_Code_of_Treatment

		annotation SummarizationSetBy = Automatic

	column POD
		dataType: string
		lineageTag: f9582c90-469a-4a2a-b48f-58ecfc1e5c51
		summarizeBy: none
		sourceColumn: POD

		annotation SummarizationSetBy = Automatic

	column Appointment_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 35178e75-cac1-44b6-a92e-26badcfba17c
		summarizeBy: none
		sourceColumn: Appointment_Date

		variation Variation
			isDefault
			relationship: a6b60287-0477-4e72-8d13-b9482b286761
			defaultHierarchy: LocalDateTable_07f5b619-9d98-4ab3-9e6a-55ae00168054.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Appointment_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 92ed07b2-385d-4520-b1bb-4ad512fe04af
		summarizeBy: none
		sourceColumn: Appointment_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Core_HRG
		dataType: string
		lineageTag: 5f5cfe5f-4848-48c8-a767-6732e2084c35
		summarizeBy: none
		sourceColumn: Core_HRG

		annotation SummarizationSetBy = Automatic

	column 'HRG Description'
		dataType: string
		lineageTag: 49ffdde5-10c8-47b4-916f-54d805b744cc
		summarizeBy: none
		sourceColumn: HRG Description

		annotation SummarizationSetBy = Automatic

	column Derived_Current_Unbundled_HRGs
		dataType: string
		lineageTag: 9ee84e43-58b4-40a2-9267-59156559879d
		summarizeBy: none
		sourceColumn: Derived_Current_Unbundled_HRGs

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		lineageTag: d4f2619c-94d1-48d5-bb76-80f97fcfdde2
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unbundled Price'
		dataType: double
		lineageTag: e1133cd8-5274-4fd7-a698-bc65c4bfff19
		summarizeBy: sum
		sourceColumn: Unbundled Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tariff
		dataType: string
		lineageTag: 19cd4282-d465-4129-a775-da0d0f46a729
		summarizeBy: none
		sourceColumn: Tariff

		annotation SummarizationSetBy = Automatic

	column 'Tariff no Uplift'
		dataType: double
		lineageTag: 9991f79a-42d3-4444-a4af-e6217745a2bc
		summarizeBy: sum
		sourceColumn: Tariff no Uplift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '25/26 MFF'
		dataType: double
		lineageTag: b077dff3-8e4f-42fd-a8aa-97c6635cae22
		summarizeBy: sum
		sourceColumn: 25/26 MFF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Plan
		dataType: int64
		formatString: 0
		lineageTag: 60fb989e-70db-4c79-a8f6-882c6e934476
		summarizeBy: sum
		sourceColumn: Plan

		annotation SummarizationSetBy = Automatic

	column 'Tariff + Uplift' = ```
			'CDC'[Tariff no Uplift]*'CDC'[25/26 MFF] 
			```
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: 431efa77-08b8-4792-bd2d-7d44fa84f770
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column Commissioner
		dataType: string
		lineageTag: 8b4f9e65-2f84-4616-88b2-5263e7bdbd73
		summarizeBy: none
		sourceColumn: Commissioner

		annotation SummarizationSetBy = Automatic

	column 'Outpatient Price'
		dataType: double
		lineageTag: 1f71cacf-38dc-4e9a-a25f-f05ba5e099c2
		summarizeBy: sum
		sourceColumn: Outpatient Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'HRG Code'
		dataType: string
		lineageTag: 6f92185d-a9d3-42a0-a82b-f9e05936106e
		summarizeBy: none
		sourceColumn: HRG Code

		annotation SummarizationSetBy = Automatic

	column 'HRG Code - Description'
		dataType: string
		lineageTag: b6a7c857-a53a-4e5b-aae1-3de4a5581e06
		summarizeBy: none
		sourceColumn: HRG Code - Description

		annotation SummarizationSetBy = Automatic

	hierarchy 'financial_year Hierarchy'
		lineageTag: f27238a7-2912-424b-baf2-1389555a438f

		level 'Financial Year'
			lineageTag: 86409340-e73b-4660-9adb-dfd124ac5099
			column: financial_year

		level financial_month
			lineageTag: 57a0b591-065f-44e5-aef6-7923c5a27259
			column: financial_month

		level month_name
			lineageTag: 0de017d5-b7ae-450e-b6bd-fff615f75a33
			column: month_name

	partition CDC = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Powerbi_reporting", [Query="SELECT * FROM [PowerBI_Reporting].[ContractMonitoring].[tbl03_CDCActivity]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Tariff no Uplift", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

