table 'Date Selection Tooltip Table'
	lineageTag: 02e3de64-0b48-46f0-82a0-213f0f3b7c14

	column Column1
		dataType: string
		lineageTag: 3995ce08-734f-4464-9fc0-12c4a0726788
		summarizeBy: none
		sourceColumn: Column1
		sortByColumn: Column2

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: int64
		formatString: 0
		lineageTag: 97f6be22-e915-4b33-a4da-cc161ac19c06
		summarizeBy: sum
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition 'Date Selection Tooltip Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8kksSS0uUfDNzyvJUNJRMlSK1QEJAoXMIILFQFEjhKihEULYGCzsXFpUlJpXohAZ4gIUM1GKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

