table 'GP Reference'
	lineageTag: 7e9eaaa0-60d6-4cf5-96a8-15e509a818da

	column Locality
		dataType: string
		lineageTag: 1c870bf8-d5c2-410d-a125-828973b48941
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: a2b6a344-c2b6-451c-a300-d5e0c3bfb572
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column GPLatitude
		dataType: string
		lineageTag: 28ee757a-2eba-4614-9c2f-ed30a34f7dc3
		summarizeBy: none
		sourceColumn: GPLatitude

		annotation SummarizationSetBy = Automatic

	column GPLongitude
		dataType: string
		lineageTag: a266298f-6f60-4dfd-95f4-e9322c5ffffc
		summarizeBy: none
		sourceColumn: GPLongitude

		annotation SummarizationSetBy = Automatic

	column ReportingOrganisationCode
		dataType: string
		lineageTag: e9e8f87f-f295-419f-b403-3e22cffa3058
		summarizeBy: none
		sourceColumn: ReportingOrganisationCode

		annotation SummarizationSetBy = Automatic

	column 'Practice Name'
		dataType: string
		lineageTag: a819f424-7f2e-44fd-8ca6-889f10d89f86
		summarizeBy: none
		sourceColumn: Practice Name

		annotation SummarizationSetBy = Automatic

	column OrganisationCode
		dataType: string
		lineageTag: 78cae6ad-3c4f-4ca5-8dd1-186c3fc87111
		summarizeBy: none
		sourceColumn: OrganisationCode

		annotation SummarizationSetBy = Automatic

	partition 'GP Reference' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "with t as (select case when locality='North Cotswolds' then 'Cotswolds' when locality='South Cotswolds' then 'Cotswolds' when locality='Tewkesbury Newent and Staunton' then 'Tewkesbury' when reportingorganisationname='West Cheltenham Medical' then 'Tewkesbury' else locality end as ""Locality"", case when reportingorganisationname='West Cheltenham Medical' then 'TWNS' when primarycarenetwork='Tewkesbury, Newent and Staunton and West Cheltenham Medical' then 'TWNS' else primarycarenetwork end as ""PrimaryCareNetwork"", organisationcode as ""OrganisationCode"", case when reportingorganisationcode='L84073' then 'L84075' when reportingorganisationcode='L84017' then 'L84018' else reportingorganisationcode end as ""ReportingOrganisationCode"", case when reportingorganisationname='Acorn Practice' then 'May Lane Surgery' when reportingorganisationname='Regent Street Surgery' then 'The Willow Tree Practice' when reportingorganisationname='Coleford Family Doctors' then 'Coleford Medical Practice' when reportingorganisationcode='L84052' then 'Severnside Medical Practice' else reportingorganisationname end as ""ReportingOrganisationName"" from icb_data_reference.vw_gppractice where commissioner ilike '11m%' and locality is not null) select t.*, c.gplatitude as ""GPLatitude"", c.gplongitude as ""GPLongitude"" from t left join (select distinct practice_code as gp_practice_code, gp_longitude as gplatitude, gp_latitude as gplongitude from db02_nopid.data_mart_primarycare.tbl01_gp_practice_populations where gp_latitude is not null) c on c.gp_practice_code=t.""ReportingOrganisationCode""", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"ReportingOrganisationName", "Practice Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

