table 'Date Reference'
	lineageTag: 5bebd5fe-016c-499d-96be-1b5f33123e61

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6822c1b8-b286-4466-bbe9-6276ef5745f9
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: a2057ad4-559f-4311-be7f-a24701cc4ce2
			defaultHierarchy: LocalDateTable_ab51ec34-42d1-41ea-84c6-9f0483db49b9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: 1b0fa62c-1c5a-4e2f-89b9-7981c6b25743
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 755a4aa6-d557-4545-bc41-8f5a73c3f529
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 334d05df-451e-4b0c-b387-09941df98b68
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 07c50f7a-4e51-46e1-9aa2-eda308ee8fea
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 87e80107-3e24-49bc-a0b0-b64bfa70fff9
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: a0b57202-328a-479e-a0eb-e9c3003f659b
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: a827746d-6d18-411f-8d7c-a92aba78d870
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 61c13545-250c-43e3-97d1-3ebb2361fef4
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: b18ae885-dd46-4fe6-9fec-b45ef7392bb8
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: fd458a36-9869-4e36-9368-a225989a11a3
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: 89d3485f-db38-42c3-ba96-339911ce27be
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: 3f8628ec-9dd5-4d7d-b92d-9d75df110551
		summarizeBy: sum
		sourceColumn: is_working_day

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 1261923c-bef4-4d6a-bd39-79ca13405e85
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: 9038bfe5-62b7-4cd5-9df8-f4af3b1471e7
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: c24f4db5-788b-4ecf-ab17-0196c65de382
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: f47852eb-fcd0-4d76-8dd9-c94a7cddb94d
		summarizeBy: sum
		sourceColumn: day_of_quarter

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d95cade4-7e17-461e-9be9-711338c9bdea
		summarizeBy: none
		sourceColumn: quarter_start_date

		variation Variation
			isDefault
			relationship: c812fc08-479b-477f-9fa0-9f9388559376
			defaultHierarchy: LocalDateTable_146a4ba0-b641-498b-a6a1-87edf4810e9e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a387f6c3-e738-4e05-bc19-708a127203b2
		summarizeBy: none
		sourceColumn: quarter_end_date

		variation Variation
			isDefault
			relationship: de86dc2a-db56-4586-b840-adfda36726b7
			defaultHierarchy: LocalDateTable_ae3c0d25-9478-4034-ad70-75debb3eb456.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: e2b74c69-c629-452f-a28f-136688e18bee
		summarizeBy: sum
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 0aa61797-527f-4c2b-97bf-45dd010ff537
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 72e75812-5d0c-4ea9-b666-3dd7777a7fa7
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: string
		lineageTag: 52f1300a-3f80-446e-a873-b15a4f62a10e
		summarizeBy: none
		sourceColumn: month_year

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 28c96cc6-c65c-42a7-ab3d-757506553c60
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 68b2198a-80d8-4f1f-a788-3938b5e97ecc
		summarizeBy: sum
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 5fcbc568-fdb6-494b-8fae-8e75fe62b0ce
		summarizeBy: sum
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 382b576c-50e3-44c5-acb5-c7078d0d60bc
		summarizeBy: sum
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: db9657b2-603d-47fb-9b86-275ef4aa550e
		summarizeBy: sum
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: 11a39fb8-960a-408d-b13f-250538ed0e9a
		summarizeBy: sum
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	partition 'Date Reference' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "DSCRO_NATIONAL_LOOKUPS", [Query="#(lf)/*===============================================================================================================#(lf)New Date Reference Script#(lf)Created by: Ben Adams#(lf)Created Date: 27/12/2023#(lf)===============================================================================================================*/#(lf) #(lf)IF OBJECT_ID('TEMPDB..#TEMP_DATE') IS NOT NULL DROP TABLE #TEMP_DATE#(lf);#(lf)#(lf)WITH MAX_DATE_CTE AS#(lf)(#(lf)SELECT [Max_Date] = MAX([Processing_Period_Date]) #(lf)#(lf)FROM [PowerBI_Processing].[dbo].[Prescribing_Dispensing_Output]#(lf))#(lf)SELECT [PDO].[Max_Date]#(lf)      ,[DATE].[Year_Month]#(lf)INTO #TEMP_DATE#(lf)FROM MAX_DATE_CTE AS [PDO]#(lf)LEFT JOIN (SELECT DISTINCT [Full_Date], [Year_Month] FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]) AS [DATE] ON CAST([DATE].[Full_Date] AS DATE) = [PDO].[Max_Date]#(lf);#(lf)#(lf)SELECT DISTINCT [date] = CAST([Full_Date] AS DATE)#(lf)               ,[day_month_year] = CONVERT(VARCHAR, [Full_Date], 103) --> 103 converts to DD/MM/YYYY format#(lf)#(tab)#(tab)#(tab)   ,[day] = [Day_Of_Fin_Year]#(lf)#(tab)#(tab)#(tab)   ,[weekday] = [Weekday_No]#(lf)#(tab)#(tab)#(tab)   ,[weekday_name] = [Weekday_Name]#(lf)#(tab)#(tab)#(tab)   ,[month] = [Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_name] = [Month_Short_Name]#(lf)#(tab)#(tab)#(tab)   ,[quarter] = [Cal_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[year_month] = [DSCRO].[Year_Month]#(lf)#(tab)#(tab)#(tab)   ,[is_weekend] = CASE WHEN [Weekday_No] IN (6,7) THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[is_holiday] = CASE WHEN [Bank_Holiday_Desc] IS NOT NULL THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[holiday_description] = [Bank_Holiday_Desc] --> Description of holiday type i.e., 'Bank Holiday'#(lf)#(tab)#(tab)#(tab)   ,[is_working_day] = [Working_Day_Calc]#(lf)#(tab)#(tab)#(tab)   ,[financial_week_of_year] = [Fin_Week_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_year] = REPLACE([Fin_Year_YYYY_dash_YY], ' - ', '/')#(lf)#(tab)#(tab)#(tab)   ,[financial_quarter] = [Fin_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[day_of_quarter] = [Day_Of_Quarter]#(lf)#(tab)#(tab)#(tab)   ,[quarter_start_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[quarter_end_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[month_day_no] = [Month_Day_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_month] = [Fin_Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_year_name] = CONCAT([Month_Short_Name], '-', LEFT([Date_112], 4))#(lf)#(tab)#(tab)#(tab)   ,[month_year] = [MonthYear_MMMM_YYYYY]#(lf)#(tab)#(tab)#(tab)   ,[ytd_flag] = CASE WHEN [Fin_Month_No] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([Fin_Month_No] AS INT)#(lf)                                           FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Full_Date] = [DATE].[Max_Date]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END --> Establishes whether the month is included in year to date calculations and reflects across all years#(lf)#(tab)#(tab)#(tab)   ,[latest_month_flag] = CASE WHEN [DSCRO].[Year_Month] = [DATE].[Year_Month]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_month_flag] = CASE WHEN [DSCRO].[Year_Month] IN#(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -2, [DATE].[Max_Date] ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The month before the latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[latest_12_months_flag] = CASE WHEN [DSCRO].[Year_Month] IN#(lf)#(tab)#(tab)#(tab)                             (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                              FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -12, [DATE].[Max_Date]  ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  AND EOMONTH ( DATEADD ( MONTH, -1, [DATE].[Max_Date]  ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      THEN 1 ELSE 0 END --> The latest 12 months within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_12_months_flag] = CASE WHEN [DSCRO].[Year_Month] IN#(lf)#(tab)#(tab)#(tab)                               (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                                FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -24, [DATE].[Max_Date]  ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)    AND EOMONTH ( DATEADD ( MONTH, -13, [DATE].[Max_Date]  ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        THEN 1 ELSE 0 END --> The 12 months before the latest 12 months within your date range - allows comparing current to previous#(lf)#(tab)#(tab)#(tab)   ,[same_month_last_year_flag] = CASE WHEN [DSCRO].[Year_Month] IN#(lf)#(tab)#(tab)#(tab)                                 (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -13, [DATE].[Max_Date]  ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END --> Same month last year as the latest month within the date range i.e., Nov-22 and Nov-23#(lf)#(lf)FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates] AS [DSCRO]#(lf)#(lf)LEFT JOIN #TEMP_DATE AS [DATE] ON [DATE].[Year_Month] = [DSCRO].[Year_Month]#(lf)#(lf)WHERE [Full_Date] BETWEEN '20200401' AND (SELECT [Max_Date] = MAX([Processing_Period_Date]) FROM [PowerBI_Processing].[dbo].[Prescribing_Dispensing_Output])#(lf)#(lf)ORDER BY CAST([Full_Date] AS DATE) ASC"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"financial_year", "Financial Year"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

