table 'PNG Descriptions'
	lineageTag: becd7b2e-863c-418a-941f-b3074c63bed2

	column 'Patient Needs Group'
		dataType: string
		lineageTag: 70362dc0-21e9-4537-856a-b034bcfaf800
		summarizeBy: none
		sourceColumn: Patient Needs Group

		annotation SummarizationSetBy = Automatic

	column Definition
		dataType: string
		lineageTag: ba3493d5-dc64-4d76-87ec-477f6643d245
		summarizeBy: none
		sourceColumn: Definition

		annotation SummarizationSetBy = Automatic

	column 'Patient Description'
		dataType: string
		lineageTag: 9791148d-bcc9-495e-ac02-156fdc27f4b7
		summarizeBy: none
		sourceColumn: Patient Description

		annotation SummarizationSetBy = Automatic

	column 'Month of data'
		dataType: string
		lineageTag: 9cdf225d-bc86-4105-b866-297466c48616
		summarizeBy: none
		sourceColumn: Month of data

		annotation SummarizationSetBy = Automatic

	column 'Patient NHS No1'
		dataType: string
		lineageTag: f67c7dd1-2784-4fca-b617-53e493ea74b0
		summarizeBy: none
		sourceColumn: Patient NHS No1

		annotation SummarizationSetBy = Automatic

	column 'Patient Description 2'
		dataType: string
		lineageTag: d553ee1a-9b5a-4dda-acce-e69172f268be
		summarizeBy: none
		sourceColumn: Patient Description 2

		annotation SummarizationSetBy = Automatic

	column 'Patient NHS No2'
		dataType: string
		lineageTag: 3c2e8ceb-cf9e-4011-b075-44b0a6f0f5ef
		summarizeBy: none
		sourceColumn: Patient NHS No2

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 73a83aac-4a8b-40b5-b0a0-b9a646ba3ef4
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 2a805462-35ec-481d-8215-a624a28a17e7
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	partition 'PNG Descriptions' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\Projects\Health Inequalities and PHM\Risk Stratification\ACG Group Descriptions for Dashboard.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sheet1_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Patient Needs Group", type text}, {"Definition", type text}, {"Patient Description", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

