table a&g_cinapsisarchive
	lineageTag: 654f578c-3e72-4d92-8b6c-b3abf3131acc

	measure 'A&G Activity' = (SUM('a&g_cinapsisarchive'[COUNTER]))
		formatString: 0
		lineageTag: 22cdf97d-8579-471f-be15-78a0de4e1390

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure 'A&G Activity PM' = CALCULATE([A&G Activity],DATEADD('date_table'[Date],-1,MONTH))
		formatString: 0
		lineageTag: 066fdfc1-61e1-4131-b60f-385e597dec99

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure 'A&G Activity Diff PM' = [A&G Activity] - [A&G Activity PM]
		formatString: 0
		lineageTag: 06e46f6d-18fb-4270-8e6f-7c53dd82c132

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure 'A&G Variance %' = DIVIDE([A&G Activity],[A&G Activity PM],BLANK()) - 1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 69ba3893-d1e3-475e-9592-418eeb8f6a3a

		annotation Format = <Format Format="Percentage" Accuracy="2" />

	measure 'A&G 2019/20 YTD Variance %' = DIVIDE([A&G YTD Activity],[A&G 2019/20 YTD Activity],BLANK()) - 1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0a712b75-ab85-4c16-9a12-7eab911bc6dd

		annotation Format = <Format Format="Percentage" Accuracy="2" />

	measure 'A&G 2019/20 Activity' = CALCULATE(SUM('a&g_cinapsisarchive'[COUNTER]),FILTER('date_table','date_table'[Financial Year]="2019/20"))
		formatString: 0
		lineageTag: c2ce590d-8ecf-4c88-8937-ceeafa88351f

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure 'A&G YTD Activity' = ```
			TOTALYTD(SUM('a&g_cinapsisarchive'[COUNTER]),'date_table'[Date])  
			```
		formatString: 0
		lineageTag: 0591ea7a-5181-4350-82ff-e493e02e8283

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure 'A&G 2019/20 YTD Activity' = CALCULATE('a&g_cinapsisarchive'[A&G Activity],DATESYTD('date_table'[Date]),FILTER('date_table','date_table'[Financial Year] = "2019/20"))
		formatString: 0
		lineageTag: 9a527090-d329-4843-ae25-ab72eee983a2

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	column Type
		dataType: string
		lineageTag: 694c99e2-40c7-4d26-99f5-b4dd4f01e65d
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Type

		annotation PBI_WasHiddenAtRefresh = False

	column 'Unique ID'
		dataType: string
		lineageTag: a6b8ec62-610e-4542-b208-bb667d4f2921
		summarizeBy: none
		sourceColumn: Unique ID

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Unique ID

		annotation PBI_WasHiddenAtRefresh = False

	column 'Request Date'
		dataType: dateTime
		formatString: dd mmmm yyyy
		lineageTag: aefcbd47-7190-49a4-86a5-9e6d1a4ef1fa
		summarizeBy: none
		sourceColumn: Request Date

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="LongDate" FormatString="dd MMMM yyyy" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = Request Date

		annotation PBI_WasHiddenAtRefresh = False

		annotation UnderlyingDateTimeDataType = Date

	column 'Request Year Month'
		dataType: string
		lineageTag: 199f7705-1a38-4bb1-a3a8-d8719eed5577
		summarizeBy: none
		sourceColumn: Request Year Month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Request Year Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Year'
		dataType: string
		lineageTag: fdf84b37-8f0d-4213-b71e-3e69b29a72ad
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Financial Year

		annotation PBI_WasHiddenAtRefresh = False

	column 'Month Name'
		dataType: string
		lineageTag: ff42ee6d-15fd-4898-bff2-4a5543d3d027
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Financial Month'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Month Name

		annotation PBI_WasHiddenAtRefresh = False

	column COUNTER
		dataType: int64
		formatString: 0
		lineageTag: 0729216b-5fdf-48b6-ad08-055f2ec7e0b6
		summarizeBy: sum
		sourceColumn: COUNTER

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = COUNTER

		annotation PBI_WasHiddenAtRefresh = False

	column 'Provider Name'
		dataType: string
		lineageTag: 34c6ea77-9917-4d97-ac14-be1525f0695f
		summarizeBy: none
		sourceColumn: Provider Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Provider Name

		annotation PBI_WasHiddenAtRefresh = False

	column 'Provider Group'
		dataType: string
		lineageTag: a0675222-b111-4fc0-a7ba-055b7896207b
		summarizeBy: none
		sourceColumn: Provider Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Provider Group

		annotation PBI_WasHiddenAtRefresh = False

	column Priority
		dataType: string
		lineageTag: 40f001db-511b-4353-93da-6ca0e11967d7
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Priority

		annotation PBI_WasHiddenAtRefresh = False

	column 'Practice Code'
		dataType: string
		lineageTag: da8afd03-f27f-4b29-89db-ac60c76cb723
		summarizeBy: none
		sourceColumn: Practice Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Practice Code

		annotation PBI_WasHiddenAtRefresh = False

	column 'Practice Name'
		dataType: string
		lineageTag: e1a1f3d2-ddd3-42f3-8f31-60e6ce612b36
		summarizeBy: none
		sourceColumn: Practice Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Practice Name

		annotation PBI_WasHiddenAtRefresh = False

	column Locality
		dataType: string
		lineageTag: c150afba-9269-400a-8d9d-241108efe381
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Locality

		annotation PBI_WasHiddenAtRefresh = False

	column 'Primary Care Network'
		dataType: string
		lineageTag: a2ab5167-1a5c-4322-b8f5-fd86444f8e42
		summarizeBy: none
		sourceColumn: Primary Care Network

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Primary Care Network

		annotation PBI_WasHiddenAtRefresh = False

	column 'Main Specialty Description'
		dataType: string
		lineageTag: dec1e9c2-7320-4846-8855-2949f3b98d9a
		summarizeBy: none
		sourceColumn: Main Specialty Description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Main Specialty Description

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Month'
		dataType: int64
		formatString: 0
		lineageTag: a02ed7cb-bd04-4d47-8f5f-438c3e38a463
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Financial Month

		annotation PBI_WasHiddenAtRefresh = False

	partition a&g_cinapsisarchive-f7c0772e-8d33-439f-be3f-ea7f88615239 = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "CCG_Current", [Query="/*=================================================================#(lf)ADVICE & GUIDANCE AND CINAPSIS DATA FLOW#(lf)=================================================================*/#(lf)-- The following script counts all calls to A&G and cinapsis ### including when there are multiple calls ####(lf)-- for the same patient case. This occurs often when additional infromation is required. #(lf)-- all referral data uses main specialty rather then TFC#(lf)#(lf)SELECT DISTINCT#(lf)     [Type] = 'A&G'#(lf)    ,[UBRN] [Unique ID]#(lf)#(tab),CAST([ActionDateTime] AS DATE) [Request Date]#(lf)#(tab),[Derived_ActionYearMonth] [Request Year Month]#(lf)#(tab),[D].[FinancialYear] [Financial Year]#(lf)    ,[D].[FinancialMonth] [Financial Month]#(lf)#(tab),LEFT([D].[MonthName],3) AS [Month Name]#(lf)#(tab),1 AS [COUNTER]#(lf)#(tab),[Derived_ProviderOrganisationDescription] [Provider Name]#(lf)    ,CASE WHEN [Derived_ProviderOrganisationCode] like 'RTE%' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)#(tab)      --WHEN [Derived_ProviderOrganisationCode] like 'RTH%' then 'Oxford University Hospitals NHS Foundation Trust'#(lf)#(tab)#(tab)  --WHEN [Derived_ProviderOrganisationCode] like 'RN3%' then 'Great Western Hospitals NHS Foundation Trust'#(lf)#(tab)#(tab)  --WHEN [Derived_ProviderOrganisationCode] like 'RVJ%' then 'North Bristol NHS Trust'#(lf)#(tab)#(tab)  WHEN [I].[OrganisationCode] IS NOT NULL THEN 'Independent Sector Provider'#(lf)#(tab)#(tab)  ELSE 'Other OOC Provider'#(lf)#(tab)      END AS [Provider Group]#(lf)#(tab),[Derived_PriorityDescription] [Priority]#(lf)#(tab),[GP].[OrganisationCode] [Practice Code]#(lf)#(tab),[GP].[ReportingOrganisationName] [Practice Name]#(lf)#(tab),[GP].[Locality]#(lf)    ,[GP].[PrimaryCareNetwork] [Primary Care Network]#(lf)#(tab)--,[ServiceName]#(lf)--#(tab),[Derived_MainSpecialtyCode] [Main Specialty Code]#(lf)#(tab),CASE WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '103' THEN 'Breast Surgery'#(lf)#(tab)      WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '303' THEN 'Haematology'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '330' THEN 'Dermatology'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '120' THEN 'ENT'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '301' THEN 'Gastroenterology'#(lf)#(tab)      WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '106' THEN 'Upper GI Surgery'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '502' THEN 'Gynaecology'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '420' THEN 'Paediatrics'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '340' THEN 'Respiratory Medicine'#(lf)#(tab)      WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '110' THEN 'Trauma & Orthopaedics'#(lf)#(tab)      WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '101' THEN 'Urology'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '400' THEN 'Neurology'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '007' THEN 'Unknown'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND [Derived_TreatmentFunctionCode] = '9901' THEN 'Unknown'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '9901' AND ([Derived_TreatmentFunctionCode] IS NULL OR [Derived_TreatmentFunctionCode] = 'Unknown') THEN 'Unknown'#(lf)#(tab)      WHEN [Derived_MainSpecialtyDescription] = 'Suspected Cancer' AND [ServiceName] LIKE '%2WW Suspected Bowel Cancer%' THEN 'Colorectal Surgery'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '103' THEN 'Breast Surgery'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '191' THEN 'Pain Management'#(lf)#(tab)#(tab)  WHEN [Derived_MainSpecialtyCode] = '340' THEN 'Respiratory Medicine'#(lf)#(tab)#(tab)  ELSE COALESCE([MS].[MainSpecialtyDescription], [Derived_MainSpecialtyDescription]) END AS [Main Specialty Description]#(lf)--#(tab),[Derived_TreatmentFunctionCode] [Treatment Function Code]#(lf)--#(tab),[Derived_TreatmentFunctionDescription] [Treatment Function Description]#(lf)#(lf)FROM [CCG_Current].[EReferrals].[vw_Events] [A]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_MainSpecialty] [MS] ON [A].[Derived_MainSpecialtyCode] = [MS].[MainSpecialtyCode]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] [D] ON CAST([A].[ActionDateTime] AS DATE) = [D].[Date]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_IndependentProvider] [I] ON [A].[Derived_ProviderOrganisationCode] = [I].[OrganisationCode]#(lf)LEFT JOIN(SELECT DISTINCT#(lf)#(tab)#(tab)#(tab)#(tab) [OrganisationCode],#(lf)#(tab)#(tab)#(tab)#(tab) [ReportingOrganisationName],#(lf)#(tab)#(tab)#(tab)#(tab) [Locality],#(lf)#(tab)#(tab)#(tab)#(tab) [PrimaryCareNetwork]#(lf)#(tab)#(tab)#(tab)#(tab) FROM [CCG_Reference].[Reference].[vw_GPPractice]#(lf)#(tab)#(tab)#(tab)#(tab) WHERE [Locality] IS NOT NULL#(lf)#(tab)#(tab)#(tab)#(tab) AND StatusDescription = 'ACTIVE') AS [GP]#(lf)#(tab)#(tab)#(tab)#(tab) ON [A].[Derived_ReferringOrganisationCode] = [GP].[OrganisationCode]#(lf)#(lf)WHERE Derived_ReferringOrganisationParentCode = '11M' -- Glos patients only #(lf)AND CAST([ActionDateTime] AS DATE) >= '20190401'#(lf)AND [ActionCode] = '1407'#(lf)#(lf)#(lf)UNION ALL#(lf)#(lf)--SELECT * FROM (#(lf)#(lf)SELECT DISTINCT #(lf)     [Type] = 'Cinapsis'#(lf)    ,[CaseID] [Unique ID]#(lf)#(tab),[DateofCallInitiated] [Request Date]#(lf)    ,[D].[YearMonth] [Request Year Month]#(lf)#(tab),[D].[FinancialYear] [Financial Year]#(lf)#(tab),[D].[FinancialMonth] [Financial Month]#(lf)#(tab),LEFT([D].[MonthName],3) AS [Month Name]#(lf)#(tab),1 AS [COUNTER]#(lf)#(tab),[Provider Name] =  'Gloucestershire Hospitals NHS Foundation Trust'#(lf)#(tab),[Provider Group] = 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)#(tab),[Priority] = 'Routine'#(lf)#(tab),[GP].[OrganisationCode] [Practice Code]#(lf)#(tab),[GP].[ReportingOrganisationName] [Practice Name]#(lf)#(tab),[GP].[Locality]#(lf)    ,[GP].[PrimaryCareNetwork] [Primary Care Network]#(lf)#(tab),[Service] [Main Specialty Description]#(lf)#(lf)FROM [CCG_Current].[Cinapsis].[vw_ReferralManagement] [A]  #(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] [D] ON [A].[DateofCallInitiated] = [D].[Date]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_OrganisationSite] [S] ON [A].[OrganisationCodeofCaller] = [S].[OrganisationCode]#(lf)LEFT JOIN (SELECT DISTINCT#(lf)#(tab)#(tab)#(tab)[OrganisationCode],#(lf)#(tab)#(tab)#(tab)[ReportingOrganisationName],#(lf)#(tab)#(tab)#(tab)[Locality],#(lf)#(tab)#(tab)#(tab)[PrimaryCareNetwork]#(lf)#(tab)#(tab)#(tab)FROM [CCG_Reference].[Reference].[vw_GPPractice]#(lf)#(tab)#(tab)#(tab)WHERE [Locality] IS NOT NULL#(lf)#(tab)#(tab)#(tab)AND StatusDescription = 'ACTIVE') AS [GP]#(lf)#(tab)#(tab)#(tab)ON [A].[OrganisationCodeofCaller] = [GP].[OrganisationCode]#(lf)#(lf) WHERE CAST([DateofCallInitiated] AS DATE) >= '20190401'#(lf) AND ([Service] = 'Dermatology')#(lf) OR ([Service] = 'Paediatrics e-Opinion')"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Financial Month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

