table ElectiveArchive
	lineageTag: 522a43ca-8f4e-4957-91c2-a3571ebf4f89

	measure 'Average Length of Stay old' = ```
			SUM('ElectiveArchive'[total_bed_days])/CALCULATE(SUM('ElectiveArchive'[counter]),'ElectiveArchive'[patient_classification] = "Inpatient Admission") 
			```
		lineageTag: 92bd19c7-9de0-4b9a-85e6-b05073fc0375

		annotation Format = <Format Format="General" />

	column source
		dataType: string
		lineageTag: b9f7ca7c-dbe0-4c67-a636-1f688944fad7
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = source

		annotation PBI_WasHiddenAtRefresh = False

	column financial_year
		dataType: string
		lineageTag: d7b544cb-b1c9-4759-b545-2103753f01ce
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = financial_year

		annotation PBI_WasHiddenAtRefresh = False

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 7d108967-a508-48d9-85fe-c573fffc6254
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = financial_month

		annotation PBI_WasHiddenAtRefresh = False

	column month_name
		dataType: string
		lineageTag: 0b26a04b-6540-4cde-8ce8-325d75dd515d
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = month_name

		annotation PBI_WasHiddenAtRefresh = False

	column year_month
		dataType: string
		lineageTag: c47f1554-46d5-42cb-9062-416d42666b47
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = year_month

		annotation PBI_WasHiddenAtRefresh = False

	column counter
		dataType: int64
		formatString: 0
		lineageTag: 1f400bde-e4d8-4be6-96dd-4bba6c65bd4e
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = counter

		annotation PBI_WasHiddenAtRefresh = False

	column practice_code
		dataType: string
		lineageTag: a6c66ca5-83b9-450a-aa9e-e3ac13c43ec5
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = practice_code

		annotation PBI_WasHiddenAtRefresh = False

	column practice_name
		dataType: string
		lineageTag: e4b7a588-4a21-46ba-846e-6c903fc6d098
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = practice_name

		annotation PBI_WasHiddenAtRefresh = False

	column locality
		dataType: string
		lineageTag: 62c5ae52-efb5-4cc2-84e5-48a1d3071fd2
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = locality

		annotation PBI_WasHiddenAtRefresh = False

	column primary_care_network
		dataType: string
		lineageTag: 574de8cb-5c42-43d5-9a1e-585187a1f989
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = primary_care_network

		annotation PBI_WasHiddenAtRefresh = False

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 463df516-ab0e-49ac-9758-776bd8a71c29
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: 89c8288f-88d5-483d-8542-cac038d9e0b1
			defaultHierarchy: LocalDateTable_135a3e76-778e-45ca-af51-b78631718306.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = start_date

		annotation PBI_WasHiddenAtRefresh = False

	column discharge_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 30945b1d-4ab8-4208-ad8a-1c56f4e984ea
		summarizeBy: none
		sourceColumn: discharge_date

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = discharge_date

		annotation PBI_WasHiddenAtRefresh = False

	column provider_code
		dataType: string
		lineageTag: 8a73a338-55eb-4ec2-90bb-9981b5f4ebba
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_code

		annotation PBI_WasHiddenAtRefresh = False

	column provider_name
		dataType: string
		lineageTag: 57700fe0-c447-44c9-ad44-81d388e88682
		summarizeBy: none
		sourceColumn: provider_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_name

		annotation PBI_WasHiddenAtRefresh = False

	column provider_group
		dataType: string
		lineageTag: 52786083-9cfc-4d40-8629-77969f627efb
		summarizeBy: none
		sourceColumn: provider_group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_group

		annotation PBI_WasHiddenAtRefresh = False

	column site_code
		dataType: string
		lineageTag: 69179149-45a2-42d1-bdfe-074a1c81703c
		summarizeBy: none
		sourceColumn: site_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = site_code

		annotation PBI_WasHiddenAtRefresh = False

	column site_name
		dataType: string
		lineageTag: 5a7980f3-ee54-4b66-a164-75c5a13549e7
		summarizeBy: none
		sourceColumn: site_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = site_name

		annotation PBI_WasHiddenAtRefresh = False

	column total_bed_days
		dataType: int64
		formatString: 0
		lineageTag: 1cde7713-aaf3-47f2-bd84-66fb2c3f197b
		summarizeBy: sum
		sourceColumn: total_bed_days

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = total_bed_days

		annotation PBI_WasHiddenAtRefresh = False

	column treatment_function_code
		dataType: string
		lineageTag: 133cd3f4-de85-4316-a251-4e87e08de306
		summarizeBy: none
		sourceColumn: treatment_function_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = treatment_function_code

		annotation PBI_WasHiddenAtRefresh = False

	column treatment_function_description
		dataType: string
		lineageTag: 654bd101-3896-4fea-a0d9-b992723be108
		summarizeBy: none
		sourceColumn: treatment_function_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = treatment_function_description

		annotation PBI_WasHiddenAtRefresh = False

	column hrg_code
		dataType: string
		lineageTag: a91385b6-13d4-4f52-9565-bf8ea9978049
		summarizeBy: none
		sourceColumn: hrg_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = hrg_code

		annotation PBI_WasHiddenAtRefresh = False

	column hrg_description
		dataType: string
		lineageTag: 0aacc988-bbe5-4557-b616-0dfafcde31c3
		summarizeBy: none
		sourceColumn: hrg_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = hrg_description

		annotation PBI_WasHiddenAtRefresh = False

	column hrg_sub_chapter_description
		dataType: string
		lineageTag: de9dc866-050f-42da-bf1a-09cad0465caa
		summarizeBy: none
		sourceColumn: hrg_sub_chapter_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = hrg_sub_chapter_description

		annotation PBI_WasHiddenAtRefresh = False

	column admission_method_code
		dataType: string
		lineageTag: f9be0ab3-4212-4227-9cb5-decd042c1444
		summarizeBy: none
		sourceColumn: admission_method_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = admission_method_code

		annotation PBI_WasHiddenAtRefresh = False

	column admission_method_description
		dataType: string
		lineageTag: 46e25d5e-b668-4f94-bab5-2bff9e722bd8
		summarizeBy: none
		sourceColumn: admission_method_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = admission_method_description

		annotation PBI_WasHiddenAtRefresh = False

	column readmission_flag
		dataType: int64
		formatString: 0
		lineageTag: 754d048f-9308-4943-9651-2a8c83658cfd
		summarizeBy: sum
		sourceColumn: readmission_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = readmission_flag

		annotation PBI_WasHiddenAtRefresh = False

	column patient_classification_code
		dataType: string
		lineageTag: 1306b8ed-71d9-49e4-b7d9-0eb1e519d26c
		summarizeBy: none
		sourceColumn: patient_classification_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = patient_classification_code

		annotation PBI_WasHiddenAtRefresh = False

	column patient_classification
		dataType: string
		lineageTag: cd81a8ee-d51b-4a66-a8fe-6378d61f567e
		summarizeBy: none
		sourceColumn: patient_classification

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = patient_classification

		annotation PBI_WasHiddenAtRefresh = False

	partition ElectiveArchive-8ba02957-f424-452d-a2df-51997f930402 = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "CCG_Current", [Query="/*=================================================================#(lf)Elective Admissions Local Flow#(lf)=================================================================*/#(lf)SELECT #(lf)[source] = 'GHFT (Gloucestershire Patients)',#(lf)[financial_year] = [D].[FinancialYear],#(lf)[financial_month] = [D].[FinancialMonth],#(lf)[month_name] = LEFT([D].[MonthName],3),#(lf)[year_month] = [D].[YearMonth],#(lf)1 AS [counter],#(lf)[practice_code] = [GP].[OrganisationCode],#(lf)[practice_name] = [GP].[ReportingOrganisationName],#(lf)[locality] = [GP].[Locality],#(lf)[primary_care_network] = [GP].[PrimaryCareNetwork],#(lf)[start_date] = CAST([Start_Date_Hospital_Provider_Spell] AS DATE),#(lf)[discharge_date] = CAST([Discharge_Date_Hospital_Provider_Spell] AS DATE),#(lf)[provider_code] = [Organisation_Code_Trust],#(lf)[provider_name] = [OT].[Name],#(lf)[provider_group] = CASE WHEN [Organisation_Code_Trust] like 'RTE%' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN [I].[OrganisationCode] IS NOT NULL THEN 'Independent Sector Provider'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE 'Other NHS Provider' END,#(lf)[site_code] = CASE WHEN [A].[admitting_ward] like '%CGH%' then 'RTE01'#(lf)                   WHEN [A].[admitting_ward] LIKE '%GRH%' THEN 'RTE03'#(lf)#(tab)#(tab)#(tab)#(tab)   ELSE NULL END,#(tab)#(tab)#(tab)   #(tab)#(tab)#(tab)#(tab)#(tab) #(lf)[site_name] = CASE WHEN [A].[admitting_ward] like '%CGH%' then 'Cheltenham General Hospital'#(lf)                   WHEN [A].[admitting_ward] LIKE '%GRH%' THEN 'Gloucester Royal Hosptial'#(lf)#(tab)#(tab)#(tab)#(tab)   ELSE NULL END,#(lf)[total_bed_days] = CASE WHEN DATEDIFF(dd,[START_DATE_HOSPITAL_PROVIDER_SPELL],[DISCHARGE_DATE_HOSPITAL_PROVIDER_SPELL]) < 0 THEN 0 ELSE DATEDIFF(dd,[START_DATE_HOSPITAL_PROVIDER_SPELL],[DISCHARGE_DATE_HOSPITAL_PROVIDER_SPELL]) END,#(lf)[treatment_function_code] = [A].[LOCAL_TREATMENT_FUNCTION_CODE_AT_ADMISSION],#(lf)[treatment_function_description] = [TFC].[TreatmentFunctionDescription],#(lf)[hrg_code] = [A].[DOMINANT_HRG_CODE],#(lf)[hrg_description] = [H].[HRGCodeDescription],#(lf)[hrg_sub_chapter_description] = [H].[HRG_SubChapter_Description],#(lf)[admission_method_code] = [ADMISSION_METHOD_HOSPITAL_PROVIDER_SPELL],#(lf)[admission_method_description] = [AM].[AdmissionMethodName],#(lf)[readmission_flag] = CASE WHEN [readmission_30_day] = 'N' THEN 0 ELSE 1 END,#(lf)--[MH Admission Flag] = case  WHEN [spellPDiag] LIKE 'F%'#(tab)#(tab) THEN 1 --- Mental Health chapter#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [spellPDiag] LIKE 'X[67]%'#(tab) THEN 1  --- Intentional Self Harm#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [spellPDiag] LIKE 'X8[01234]%' THEN 1 --- Intentional Self Harm#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [spellPDiag] LIKE 'X[67]%'#(tab) THEN 1  --- Intentional Self Harm     ------- These codes are usually coded in the secondary position#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [spellPDiag] LIKE 'X8[01234]%' THEN 1  --- Intentional Self Harm#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [spellPDiag] LIKE 'T3[6789]%'  THEN 1 --- Poisoning by drugs, medicaments and biological substances *as per PHE these last 3 codes are not recognised. This is a local definition.#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [spellPDiag] LIKE 'T4%'#(tab)#(tab) THEN 1 --- Poisoning by drugs, medicaments and biological substances *#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [spellPDiag] LIKE 'T50%'#(tab)#(tab) THEN 1 --- Poisoning by drugs, medicaments and biological substances *#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) ELSE 0 END,#(lf)[patient_classification_code] = [patient_classification],#(lf)[patient_classification] = CASE WHEN [patient_classification] = '1' THEN 'Inpatient Admission'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN [patient_classification] = '2' THEN 'Day Case Admission'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE 'Other' END#(lf)#(lf)FROM [CCG_Current].[GHFT].[vw_APC_Hospital_Provider_Spell] [A]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] [D] #(lf)       ON CAST([A].[DISCHARGE_DATE_HOSPITAL_PROVIDER_SPELL] AS DATE) = [D].[Date]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_TreatmentFunction] AS [TFC]#(lf)#(tab)   ON [A].[LOCAL_TREATMENT_FUNCTION_CODE_AT_ADMISSION] = [TFC].[TreatmentFunctionCode]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_AdmissionMethod] AS [AM]#(lf)#(tab)   ON [AM].[AdmissionMethodCode] = [A].[ADMISSION_METHOD_HOSPITAL_PROVIDER_SPELL]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_OrganisationTrust] AS [OT]#(lf)       ON [OT].[OrganisationCode] = LEFT([A].[ORGANISATION_CODE_TRUST],3)#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_IndependentProvider] AS [I] #(lf)       ON [A].[Organisation_Code_Trust] = [I].[OrganisationCode]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_HRG] [H] #(lf)   ON [A].[DOMINANT_HRG_CODE] = [H].[HRGCode]#(lf)#(lf)LEFT JOIN(SELECT DISTINCT#(lf)#(tab)#(tab)  [OrganisationCode],#(lf)#(tab)#(tab)  [ReportingOrganisationName],#(lf)#(tab)#(tab)  [Locality],#(lf)#(tab)#(tab)  [PrimaryCareNetwork]#(lf)#(tab)#(tab)  FROM [CCG_Reference].[Reference].[vw_GPPractice]#(lf)#(tab)#(tab)  WHERE [Locality] IS NOT NULL#(lf)#(tab)#(tab)  AND StatusDescription = 'ACTIVE') AS [GP]#(lf)#(tab)#(tab)  ON [A].[ORGANISATION_CODE_REGISTERED_GENERAL_MEDICAL_PRACTICE_AT_ADMISSION_DATE] = [GP].[OrganisationCode]#(lf)#(lf)#(lf)WHERE CAST([A].[DISCHARGE_DATE_HOSPITAL_PROVIDER_SPELL] AS DATE) >= '20190401'#(lf)AND [ORGANISATION_CODE_PCT_RESPONSIBLE_AT_ADMISSION_DATE] = '11M'#(lf)AND [A].[ADMISSION_METHOD_HOSPITAL_PROVIDER_SPELL] like '1%' --- All Elective Admissions#(lf)AND [spellHRG_TFC] NOT LIKE '%424%' --- Excludes well babies#(lf)#(lf)UNION ALL #(lf)#(lf)#(lf)/*=================================================================#(lf)Elective Admissions SEM Flow #(lf)#(lf)Excludes GHT activity#(lf)=================================================================*/#(lf)SELECT #(lf)[source] = 'National (Gloucestershire Patients)',#(lf)[financial_year] = [D].[FinancialYear],#(lf)[financial_month] = [D].[FinancialMonth],#(lf)[month_name] = LEFT([D].[MonthName],3),#(lf)[year_month] = [D].[YearMonth],#(lf)1 AS [counter],#(lf)[practice_code] = [GP].[OrganisationCode],#(lf)[practice_name] = [GP].[ReportingOrganisationName],#(lf)[locality] = [GP].[Locality],#(lf)[primary_care_network] = [GP].[PrimaryCareNetwork],#(lf)[start_date] = CAST([StartDate_HospitalProviderSpell] AS DATE),#(lf)[discharge_date] = CAST([DischargeDate_FromHospitalProviderSpell] AS DATE),#(lf)[provider_code] = [OrganisationCode_CodeOfProvider],#(lf)[provider_name] = COALESCE([OT].[Name], [I].[OrganisationName]),#(lf)[Provider_group] = CASE WHEN [OrganisationCode_CodeOfProvider] like 'RTE%' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN [I].[OrganisationCode] IS NOT NULL THEN 'Independent Sector Provider'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE 'Other NHS Provider' END,#(lf)[site_code] = [A].[SiteCode_ofTreatmentAtEpisodeStartDate],#(lf)[site_name] = COALESCE([OS].[Name],[IS].[Name]),#(lf)[total_bed_days] = CASE WHEN DATEDIFF(dd,[StartDate_HospitalProviderSpell],[DischargeDate_FromHospitalProviderSpell]) < 0 THEN 0 ELSE DATEDIFF(dd,[StartDate_HospitalProviderSpell],[DischargeDate_FromHospitalProviderSpell]) END,#(lf)[treatment_function_code] = [a].[TreatmentFunctionCode],#(lf)[treatment_function_description] = [TFC].[TreatmentFunctionDescription],#(lf)[hrg_code] = [A].[SpellCOREHRG],#(lf)[hrg_description] = [H].[HRGCodeDescription],#(lf)[hrg_sub_chapter_description] = [H].[HRG_SubChapter_Description],#(lf)[admission_method_code] = [AdmissionMethod_HospitalProviderSpell],#(lf)[admission_method_description] = [AM].[AdmissionMethodName],#(lf)[readmission_flag] = [Derived_Readmission_30_day],#(lf)--[MH_Admission_Flag] = CASE#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'F%'#(tab)#(tab) THEN 1 --- Mental Health chapter#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'X[67]%'#(tab) THEN 1  --- Intentional Self Harm#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'X8[01234]%' THEN 1 --- Intentional Self Harm#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'X[67]%'#(tab) THEN 1  --- Intentional Self Harm     ------- These codes are usually coded in the secondary position#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'X8[01234]%' THEN 1  --- Intentional Self Harm#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'T3[6789]%'  THEN 1 --- Poisoning by drugs, medicaments and biological substances *as per PHE these last 3 codes are not recognised. This is a local definition.#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'T4%'#(tab)#(tab) THEN 1 --- Poisoning by drugs, medicaments and biological substances *#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Derived_SEM_SpellPDiag] LIKE 'T50%'#(tab)#(tab) THEN 1 --- Poisoning by drugs, medicaments and biological substances *#(lf)--#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) ELSE 0 END,#(lf)[patient_classification_code] = [PatientClassification],#(lf)[patient_classification] = CASE WHEN [PatientClassification] = '1' THEN 'Inpatient Admission'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN [PatientClassification] = '2' THEN 'Day Case Admission'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE 'Other' END#(lf)#(lf)#(lf)FROM [CCG_Current].[SEM].[vw_HospitalProviderSpell] [A]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] [D] #(lf)       ON CAST([DischargeDate_FromHospitalProviderSpell] AS DATE) = [D].[Date]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_TreatmentFunction] [TFC] #(lf)       ON [A].[TreatmentFunctionCode] = [TFC].[TreatmentFunctionCode]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_AdmissionMethod] [AM]#(lf)#(tab)   ON [AM].[AdmissionMethodCode] = [A].[AdmissionMethod_HospitalProviderSpell]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_OrganisationTrust] [OT]#(lf)#(tab)   ON [OT].[OrganisationCode] = LEFT([A].[OrganisationCode_CodeOfProvider],3)#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_IndependentProviderSite] [OS] #(lf)       ON [A].[SiteCode_ofTreatmentAtEpisodeStartDate] = [OS].[OrganisationCode]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_IndependentProvider] [I]#(lf)    ON [I].[OrganisationCode] = LEFT([A].[OrganisationCode_CodeOfProvider],3)#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_IndependentProviderSite] [IS] #(lf)       ON [A].[SiteCode_ofTreatmentAtEpisodeStartDate] = [IS].[OrganisationCode]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_HRG] [H] #(lf)   ON [A].[SpellCOREHRG] = [H].[HRGCode]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)LEFT JOIN( SELECT DISTINCT#(lf)#(tab)#(tab)   [OrganisationCode],#(lf)#(tab)#(tab)   [ReportingOrganisationName],#(lf)#(tab)#(tab)   [Locality],#(lf)#(tab)#(tab)   [PrimaryCareNetwork]#(lf)#(tab)#(tab)   FROM [CCG_Reference].[Reference].[vw_GPPractice]#(lf)#(tab)#(tab)   WHERE [Locality] IS NOT NULL#(lf)#(tab)#(tab)   AND StatusDescription = 'ACTIVE') [GP]#(lf)#(tab)#(tab)   ON [A].[PracticeCodeOfRegisteredGP] = [GP].[OrganisationCode]#(lf)#(lf)WHERE CAST([A].[DischargeDate_FromHospitalProviderSpell] AS DATE) >= '20190401'#(lf)AND [A].[AdmissionMethod_HospitalProviderSpell] like '1%' --- All elective Admissions#(lf)AND [SpellCOREHRG] NOT LIKE '%424%' --- Excludes well babies#(lf)AND [OrganisationCode_CodeOfCommissioner] = '11M'#(lf)AND [OrganisationCode_CodeOfProvider] NOT LIKE 'RTE%'#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

