table Lower_Super_Output_Area_(LSOA)_IMD2019__(WGS84)
	lineageTag: 098f2ae1-07f9-4fee-a0a1-c20380f5f037

	column FID
		dataType: int64
		formatString: 0
		lineageTag: c2fca9ca-63a5-4613-b471-12527d0b7697
		summarizeBy: none
		sourceColumn: FID

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = FID

		annotation PBI_WasHiddenAtRefresh = False

	column lsoa11cd
		dataType: string
		lineageTag: c48f49fb-1165-42d4-8131-1cd9a2bb8e23
		summarizeBy: none
		sourceColumn: lsoa11cd

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = lsoa11cd

		annotation PBI_WasHiddenAtRefresh = False

	column lsoa11nm
		dataType: string
		lineageTag: 8ed9248e-005f-4a37-922c-189c202ceb94
		summarizeBy: none
		sourceColumn: lsoa11nm

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = lsoa11nm

		annotation PBI_WasHiddenAtRefresh = False

	column IMDRank
		dataType: int64
		formatString: 0
		lineageTag: 83314836-13a2-4dcd-8e72-6c63c4d27996
		summarizeBy: none
		sourceColumn: IMDRank

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = IMDRank

		annotation PBI_WasHiddenAtRefresh = False

	column IMDDecil
		dataType: int64
		formatString: 0
		lineageTag: 9bbe5efd-fb28-40c3-a983-f31756e6e7b4
		summarizeBy: none
		sourceColumn: IMDDecil

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = IMDDecil

		annotation PBI_WasHiddenAtRefresh = False

	column Shape__Area
		dataType: double
		lineageTag: 93c454b5-a89b-4fb5-a444-10741e84c824
		summarizeBy: none
		sourceColumn: Shape__Area

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Shape__Area

		annotation PBI_WasHiddenAtRefresh = False

	column Shape__Length
		dataType: double
		lineageTag: 26ed7cf5-8b77-4d57-8fac-95150afbd0b8
		summarizeBy: none
		sourceColumn: Shape__Length

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Shape__Length

		annotation PBI_WasHiddenAtRefresh = False

	column District
		dataType: string
		lineageTag: f1552f5c-893f-431c-a9d9-fa4458320492
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = District

		annotation PBI_WasHiddenAtRefresh = False

	column Formula
		dataType: string
		lineageTag: d01c39ed-5381-4e48-b10c-c17f8a8d8157
		summarizeBy: none
		sourceColumn: Formula

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Formula

		annotation PBI_WasHiddenAtRefresh = False

	partition Lower_Super_Output_Area_(LSOA)_IMD2019__(WGS84)-c212925b-5caa-4406-84f2-1d29332f2b81 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("M:\Info\Projects\Power BI\Map Shape Files\Lower_Super_Output_Area_(LSOA)_IMD2019__(WGS84).csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"FID", Int64.Type}, {"lsoa11cd", type text}, {"lsoa11nm", type text}, {"IMDRank", Int64.Type}, {"IMDDecil", Int64.Type}, {"Shape__Area", type number}, {"Shape__Length", type number}, {"District", type text}, {"Formula", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([District] = "Cheltenham " or [District] = "Cotswold " or [District] = "Forest of Dean " or [District] = "Gloucester " or [District] = "Stroud " or [District] = "Tewkesbury "))
				in
				    #"Filtered Rows"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

