table 'LTC Count Reference'
	lineageTag: f4aa4b20-2fc8-42ef-90f6-2157529abc25

	column 'Count of LTC'
		dataType: int64
		formatString: 0
		lineageTag: da99f4c9-9fa9-46aa-8c3b-81d1d4e86042
		summarizeBy: none
		sourceColumn: Count of LTC

		annotation SummarizationSetBy = Automatic

	column LTC
		dataType: int64
		formatString: 0
		lineageTag: 76a538f0-881c-460a-844e-823f113802db
		summarizeBy: none
		sourceColumn: LTC

		annotation SummarizationSetBy = Automatic

	partition 'LTC Count Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("TcbJCQAgDATAXvLVh4nxqiXYfxsui6CPgYmQIhl2DlFMOcOMq1jlHHOuYY3rWOcGNriJzcSuVy3f9bvd7wM=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Count of LTC" = _t, LTC = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Count of LTC", Int64.Type}, {"LTC", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

