table 'Month table'
	lineageTag: 8e36c92c-e7a2-41af-b3b8-c6bca525f022

	column 'Month Name'
		dataType: string
		lineageTag: 47ebdf7f-6ae0-498e-8e7b-478bcbe4b40f
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Financial Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Financial Month'
		dataType: double
		lineageTag: 8a4e1202-075c-40d5-85da-da9eba7c0e8c
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Current_month
		dataType: int64
		formatString: 0
		lineageTag: 2bfdcd68-2374-4b5a-8970-4f51ad9592d0
		summarizeBy: sum
		sourceColumn: Current_month

		annotation SummarizationSetBy = Automatic

	column Current_financial_month
		dataType: int64
		formatString: 0
		lineageTag: 63389d76-06b2-453e-a8fb-70529ad44c3d
		summarizeBy: sum
		sourceColumn: Current_financial_month

		annotation SummarizationSetBy = Automatic

	column 'YTD Flag'
		dataType: string
		lineageTag: 1276d149-bc65-4459-99c5-084daed8af5b
		summarizeBy: none
		sourceColumn: YTD Flag

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: string
		lineageTag: 4083a459-4327-4c8e-b7ff-148436e36768
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	partition 'Month table-da420742-0d71-43ef-9d3d-eac04e9053ef' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "powerbi_reporting", [Query="/****** Script for SelectTopNRows command from SSMS  ******/#(lf)#(lf)   #(lf) SET NOCOUNT ON#(lf)IF OBJECT_ID ('TEMPDB..#ytd') IS NOT NULL DROP TABLE #ytd#(lf)#(lf)#(lf)Select distinct#(lf) [YTD Flag] = #(lf)case when #(lf)dat.FinancialMonth#(lf)<#(lf)(select#(lf)MAX(cast(dat.FinancialMonth as int))#(lf)from  [CCG_Current].SEM.vw_OPAppointment  OP #(lf)left join ccg_reference.reference.vw_DateLookup dat on cast(OP.AppointmentDate as date) = dat.date#(lf)where dat.FinancialYear = (#(lf)select max(dat.financialyear) from  [CCG_Current].SEM.vw_OPAppointment  OP #(lf)left join ccg_reference.reference.vw_DateLookup dat on cast(OP.AppointmentDate as date) = dat.date#(lf))#(lf))#(lf)then 1#(lf)else 0 end#(lf),FinancialMonth#(lf)into #ytd#(lf)FROM CCG_CURRENT.SEM.vw_OPAppointment OP left join#(lf)ccg_reference.reference.vw_DateLookup dat on cast(OP.AppointmentDate as date) = dat.Date#(lf)#(lf) #(lf)#(lf)#(lf) Select #(lf)#(lf) [Month Name]#(lf) ,[Financial Month]#(lf) ,quarter#(lf) ,[Current_month] = datepart(month,getdate())#(lf)#(lf) ,[Current_financial_month] = case#(tab)when datepart(month,getdate()) like 1 then 10#(lf)#(tab)#(tab)when datepart(month,getdate()) like 2 then 11#(lf)#(tab)#(tab)when datepart(month,getdate()) like 3 then 12#(lf)#(tab)#(tab)when datepart(month,getdate()) like 4 then 1#(lf)#(tab)#(tab)when datepart(month,getdate()) like 5 then 2#(lf)#(tab)#(tab)when datepart(month,getdate()) like 6 then 3#(lf)#(tab)#(tab)when datepart(month,getdate()) like 7 then 4#(lf)#(tab)#(tab)when datepart(month,getdate()) like 8 then 5#(lf)#(tab)#(tab)when datepart(month,getdate()) like 9 then 6#(lf)#(tab)#(tab)when datepart(month,getdate()) like 10 then 7#(lf)#(tab)#(tab)when datepart(month,getdate()) like 11 then 8#(lf)#(tab)#(tab)when datepart(month,getdate()) like 12 then 9#(lf)#(tab)#(tab)END#(lf)#(lf),[YTD Flag]#(lf)#(lf)#(lf)#(lf)#(lf) from [PowerBI_Reporting].[dbo].[Ops_date_tbl]#(lf)#(lf) left join #ytd on #ytd.FinancialMonth = [PowerBI_Reporting].[dbo].[Ops_date_tbl].[Financial Month]#(lf)#(lf) order by [Financial Month]#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"YTD Flag", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

