table LSOA_Additional_Fields
	lineageTag: 0c691093-ee16-48fe-8f40-4a2a9d4462e8

	column LSOACode
		dataType: string
		lineageTag: 71131834-5b68-4ae8-bd7e-2fffab156e31
		summarizeBy: none
		sourceColumn: LSOACode

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: string
		lineageTag: 6708431a-de5a-4bbc-bedd-2552b0303d54
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column IndexOfMultipleDeprivation_Score
		dataType: string
		lineageTag: d7dcb42d-df64-4f04-93a8-610ccda60b0b
		summarizeBy: none
		sourceColumn: IndexOfMultipleDeprivation_Score

		annotation SummarizationSetBy = Automatic

	column IndexOfMultipleDeprivation_EnglandRank
		dataType: string
		lineageTag: c8a64947-1cc7-4f0c-9871-31af86f46481
		summarizeBy: none
		sourceColumn: IndexOfMultipleDeprivation_EnglandRank

		annotation SummarizationSetBy = Automatic

	column IndexOfMultipleDeprivation_EnglandDecile
		dataType: string
		lineageTag: 116fc309-54d0-493b-b7c2-f8ee73da350b
		summarizeBy: none
		sourceColumn: IndexOfMultipleDeprivation_EnglandDecile

		annotation SummarizationSetBy = Automatic

	column IncomeDeprivationDomain_Score
		dataType: string
		lineageTag: d473c3c3-af00-4444-8b33-f4997b1a2b02
		summarizeBy: none
		sourceColumn: IncomeDeprivationDomain_Score

		annotation SummarizationSetBy = Automatic

	column IncomeDeprivationDomain_EnglandRank
		dataType: string
		lineageTag: 74b979a1-8c8c-4abc-8fce-4bed2e2fe43a
		summarizeBy: none
		sourceColumn: IncomeDeprivationDomain_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Income Deprivation Decile'
		dataType: int64
		formatString: 0
		lineageTag: d65d4dc6-4d83-40e1-b1be-1025693a6f04
		summarizeBy: none
		sourceColumn: Income Deprivation Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column EmploymentDeprivationDomain_Score
		dataType: string
		lineageTag: a50cb706-28aa-4818-b82d-43649968e40d
		summarizeBy: none
		sourceColumn: EmploymentDeprivationDomain_Score

		annotation SummarizationSetBy = Automatic

	column EmploymentDeprivationDomain_EnglandRank
		dataType: string
		lineageTag: d57c500d-2c3c-443d-b44e-5deddf070bb9
		summarizeBy: none
		sourceColumn: EmploymentDeprivationDomain_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Employment Deprivation Decile'
		dataType: int64
		formatString: 0
		lineageTag: 7791f08f-6654-48e3-957a-7cbd876fded5
		summarizeBy: none
		sourceColumn: Employment Deprivation Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column EducationSkillsandTrainingDomain_Score
		dataType: string
		lineageTag: cf7a2d2a-bdfb-404e-a3c9-ffea8e0cbcf5
		summarizeBy: none
		sourceColumn: EducationSkillsandTrainingDomain_Score

		annotation SummarizationSetBy = Automatic

	column EducationSkillsandTrainingDomain_EnglandRank
		dataType: string
		lineageTag: ec70cf65-367d-4143-bcd1-18c73e90f9e0
		summarizeBy: none
		sourceColumn: EducationSkillsandTrainingDomain_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Education Skills and Training Decile'
		dataType: int64
		formatString: 0
		lineageTag: c5156e29-5b77-4508-a9ba-f0b9a5de42b0
		summarizeBy: none
		sourceColumn: Education Skills and Training Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column HealthDeprivationandDisabilityDomain_Score
		dataType: string
		lineageTag: 90ba3acd-c3ca-44b3-9627-e570a677ef35
		summarizeBy: none
		sourceColumn: HealthDeprivationandDisabilityDomain_Score

		annotation SummarizationSetBy = Automatic

	column HealthDeprivationandDisabilityDomain_EnglandRank
		dataType: string
		lineageTag: 72689055-568d-484d-b3d2-8ef355a2ce26
		summarizeBy: none
		sourceColumn: HealthDeprivationandDisabilityDomain_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Health Deprivation and Disability Decile'
		dataType: int64
		formatString: 0
		lineageTag: 83062bdb-2f45-452e-b61d-4da094ed0a12
		summarizeBy: none
		sourceColumn: Health Deprivation and Disability Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column CrimeDomain_Score
		dataType: string
		lineageTag: 7a8682db-2d74-4c89-98e5-9c0193f9b8f7
		summarizeBy: none
		sourceColumn: CrimeDomain_Score

		annotation SummarizationSetBy = Automatic

	column CrimeDomain_EnglandRank
		dataType: string
		lineageTag: c5246444-1f45-4448-baad-f9a78cdb5aa0
		summarizeBy: none
		sourceColumn: CrimeDomain_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Crime Decile'
		dataType: int64
		formatString: 0
		lineageTag: a352f372-cc70-4738-a6be-a59edcc6ccf7
		summarizeBy: none
		sourceColumn: Crime Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column BarrierstoHousingandServicesDomain_Score
		dataType: string
		lineageTag: c3be1814-fd46-478c-b2ae-baf944caf2a7
		summarizeBy: none
		sourceColumn: BarrierstoHousingandServicesDomain_Score

		annotation SummarizationSetBy = Automatic

	column BarrierstoHousingandServicesDomain_EnglandRank
		dataType: string
		lineageTag: b22693fc-fcdf-4205-a70b-ebd9489ad423
		summarizeBy: none
		sourceColumn: BarrierstoHousingandServicesDomain_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Barriers to Housing and Services Decile'
		dataType: int64
		formatString: 0
		lineageTag: 5e7548fb-35a7-4ef5-9f3b-46b4ac291c6a
		summarizeBy: none
		sourceColumn: Barriers to Housing and Services Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column LivingEnvironmentDeprivationDomain_Score
		dataType: string
		lineageTag: 51fce509-723f-4afc-9651-2a50f5ee6ae7
		summarizeBy: none
		sourceColumn: LivingEnvironmentDeprivationDomain_Score

		annotation SummarizationSetBy = Automatic

	column LivingEnvironmentDeprivationDomain_EnglandRank
		dataType: string
		lineageTag: b5c378ac-c2df-408b-a05e-99ab35164099
		summarizeBy: none
		sourceColumn: LivingEnvironmentDeprivationDomain_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Living Environment Deprivation Decile'
		dataType: int64
		formatString: 0
		lineageTag: 26751386-533d-4243-9734-26223002fc9b
		summarizeBy: none
		sourceColumn: Living Environment Deprivation Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column IncomeDeprivationAffectingChildrenIndex_Score
		dataType: string
		lineageTag: 5f67ceef-b6f2-4bb1-9565-48228f32396a
		summarizeBy: none
		sourceColumn: IncomeDeprivationAffectingChildrenIndex_Score

		annotation SummarizationSetBy = Automatic

	column IncomeDeprivationAffectingChildrenIndex_EnglandRank
		dataType: string
		lineageTag: d5adb2a1-e4d7-4f8c-a606-a1a39288f05d
		summarizeBy: none
		sourceColumn: IncomeDeprivationAffectingChildrenIndex_EnglandRank

		annotation SummarizationSetBy = Automatic

	column 'Income Deprivation Affecting Children Decile'
		dataType: int64
		formatString: 0
		lineageTag: 79297a09-5dbe-47fc-b801-0607faa0c39d
		summarizeBy: none
		sourceColumn: Income Deprivation Affecting Children Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column IncomeDeprivationAffectingOlderPeopleIndex_Score
		dataType: string
		lineageTag: a59d9f1e-87e0-45ad-87b8-ef83812b797a
		summarizeBy: none
		sourceColumn: IncomeDeprivationAffectingOlderPeopleIndex_Score

		annotation SummarizationSetBy = Automatic

	column IncomeDeprivationAffectingOlderPeopleIndex_EnlandRank
		dataType: string
		lineageTag: 93091ce1-dd30-40bc-8566-6afe7d076457
		summarizeBy: none
		sourceColumn: IncomeDeprivationAffectingOlderPeopleIndex_EnlandRank

		annotation SummarizationSetBy = Automatic

	column 'Income Deprivation Affecting Older People Decile'
		dataType: int64
		formatString: 0
		lineageTag: a1f80f01-c8c0-46db-bdbb-bceb8b52f9eb
		summarizeBy: none
		sourceColumn: Income Deprivation Affecting Older People Decile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Derived_IMDGloucestershireDecile
		dataType: string
		lineageTag: d8c65ae2-f96c-41ed-bea4-903a74e64b88
		summarizeBy: none
		sourceColumn: Derived_IMDGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_IncomeDeprivationDomainGloucestershireDecile
		dataType: string
		lineageTag: 3864f840-c207-4d6f-a536-c4d0b3418212
		summarizeBy: none
		sourceColumn: Derived_IncomeDeprivationDomainGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_EmploymentDeprivationDomainGloucestershireDecile
		dataType: string
		lineageTag: 144a930a-8d2a-4fa0-9a7b-6f81c276a77d
		summarizeBy: none
		sourceColumn: Derived_EmploymentDeprivationDomainGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_EducationSkillsandTrainingDomainGloucestershireDecile
		dataType: string
		lineageTag: 67a370a1-3136-42de-96d9-def2d82627ff
		summarizeBy: none
		sourceColumn: Derived_EducationSkillsandTrainingDomainGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_HealthDeprivationandDisabilityDomainGloucestershireDecile
		dataType: string
		lineageTag: e507dde3-b5cd-46df-a8ef-2f4c8d781054
		summarizeBy: none
		sourceColumn: Derived_HealthDeprivationandDisabilityDomainGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_CrimeDomainGloucestershireDecile
		dataType: string
		lineageTag: c98b76c7-0caa-4b78-ae4b-6832ac57c79c
		summarizeBy: none
		sourceColumn: Derived_CrimeDomainGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_BarrierstoHousingandServicesDomainGloucestershireDecile
		dataType: string
		lineageTag: d6b9237b-9588-4535-85f7-58aa7c7af00b
		summarizeBy: none
		sourceColumn: Derived_BarrierstoHousingandServicesDomainGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_LivingEnvironmentDeprivationDomainGloucestershireDecile
		dataType: string
		lineageTag: 509eeeef-d820-40ae-9761-f953357f738a
		summarizeBy: none
		sourceColumn: Derived_LivingEnvironmentDeprivationDomainGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_IncomeDeprivationAffectingChildrenIndexGloucestershireDecile
		dataType: string
		lineageTag: abc24890-3e1e-4d4e-9fde-8a3e2869e64f
		summarizeBy: none
		sourceColumn: Derived_IncomeDeprivationAffectingChildrenIndexGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	column Derived_IncomeDeprivationAffectingOlderPeopleIndexGloucestershireDecile
		dataType: string
		lineageTag: d65cc82c-c3d6-45f2-9c93-864e876cf713
		summarizeBy: none
		sourceColumn: Derived_IncomeDeprivationAffectingOlderPeopleIndexGloucestershireDecile

		annotation SummarizationSetBy = Automatic

	partition LSOA_Additional_Fields-8052af67-8f9d-4136-aff7-a9b19d755163 = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "CCG_REFERENCE", [Query="/****** Script for SelectTopNRows command from SSMS  ******/#(lf)SELECT *#(lf)  FROM [CCG_Reference].[Reference].[vw_LSOA_IMD]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"EmploymentDeprivationDomain_EnglandDecile", "Employment Deprivation Decile"}, {"IncomeDeprivationDomain_EnglandDecile", "Income Deprivation Decile"}, {"HealthDeprivationandDisabilityDomain_EnglandDecile", "Health Deprivation and Disability Decile"}, {"EducationSkillsandTrainingDomain_EnglandDecile", "Education Skills and Training Decile"}, {"CrimeDomain_EnglandDecile", "Crime Decile"}, {"BarrierstoHousingandServicesDomain_EnglandDecile", "Barriers to Housing and Services Decile"}, {"LivingEnvironmentDeprivationDomain_EnglandDecile", "Living Environment Deprivation Decile"}, {"IncomeDeprivationAffectingChildrenIndex_EnglandDecile", "Income Deprivation Affecting Children Decile"}, {"IncomeDeprivationAffectingOlderPeopleIndex_EnglandDecile", "Income Deprivation Affecting Older People Decile"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

