table 'BMI 25+'
	isHidden
	lineageTag: 450958ad-98b3-4740-b088-039c3b935a17

	measure 'Rate per 1,000' = DIVIDE(sum('BMI 25+'[counter]),sum('population'[counter])) * 1000
		isHidden
		lineageTag: 26f79c1a-e0e7-4ffd-9278-3dd2d3e96397

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NHS Number (Pseudo)'
		dataType: string
		isHidden
		lineageTag: d91090c4-014b-4549-884a-e17ca0ee6f19
		summarizeBy: none
		sourceColumn: NHS Number (Pseudo)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		isHidden
		lineageTag: 93c8dffd-bdb4-4d95-a35c-4b105db82cb0
		summarizeBy: none
		sourceColumn: Gender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e820b81e-ca50-4e8d-b548-1787c3209576
		summarizeBy: sum
		sourceColumn: Age

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgeBand5yr
		dataType: string
		isHidden
		lineageTag: ca097b44-8ff7-4311-9cd1-9d3cf72e6ba4
		summarizeBy: none
		sourceColumn: AgeBand5yr
		sortByColumn: 'Age Sort'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgeBand10yr
		dataType: string
		isHidden
		lineageTag: dc92aecc-784f-4fc5-a267-c97a53f4ac30
		summarizeBy: none
		sourceColumn: AgeBand10yr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Group'
		dataType: string
		isHidden
		lineageTag: 31f864c5-1ab0-422e-83ac-3f3586ba8cad
		summarizeBy: none
		sourceColumn: Ethnic Origin Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin - Detailed Group'
		dataType: string
		isHidden
		lineageTag: 56e3c5ad-2e62-47ea-88b0-745e1d52cd84
		summarizeBy: none
		sourceColumn: Ethnic Origin - Detailed Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Registered ICB'
		dataType: string
		isHidden
		lineageTag: 59938a3d-53d2-4354-a7a0-a40765005bb3
		summarizeBy: none
		sourceColumn: Registered ICB

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Residence ICB'
		dataType: string
		isHidden
		lineageTag: 1b3509f1-98a1-468f-882d-9c551c908eb9
		summarizeBy: none
		sourceColumn: Residence ICB

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'GP Practice Code'
		dataType: string
		isHidden
		lineageTag: 5582473c-cebc-4004-b946-71cd7cbb1b41
		summarizeBy: none
		sourceColumn: GP Practice Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'GP Practice Name'
		dataType: string
		isHidden
		lineageTag: e1c9da35-ee26-4f6f-a8bf-07965d11da22
		summarizeBy: none
		sourceColumn: GP Practice Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		isHidden
		lineageTag: 3031aae7-41cd-4854-8446-abe595686f08
		summarizeBy: none
		sourceColumn: Locality

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Primary Care Network'
		dataType: string
		isHidden
		lineageTag: d1d689a5-70a1-4b2f-8b5f-544006eb79f5
		summarizeBy: none
		sourceColumn: Primary Care Network

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'LSOA Code'
		dataType: string
		isHidden
		lineageTag: 9eca2af6-165b-4c55-92b5-df6ae4ed9090
		summarizeBy: none
		sourceColumn: LSOA Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ward Code'
		dataType: string
		isHidden
		lineageTag: 5f71ec6a-4e67-4cc0-aec4-e9548e6d3991
		summarizeBy: none
		sourceColumn: Ward Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ward Name'
		dataType: string
		isHidden
		lineageTag: 927a8fc6-f9e0-4deb-868d-51fdbcf9dcb3
		summarizeBy: none
		sourceColumn: Ward Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Local Authority'
		dataType: string
		isHidden
		lineageTag: 1268637e-bc71-4b26-962a-cd551bc5aa00
		summarizeBy: none
		sourceColumn: Local Authority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Deprivation Decile - Glos'
		dataType: string
		isHidden
		lineageTag: 1003287d-a336-4faa-a73b-19a0c77f120e
		summarizeBy: none
		sourceColumn: Deprivation Decile - Glos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Easting
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3405b339-5674-448c-8e05-b61df67c7229
		summarizeBy: sum
		sourceColumn: Easting

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Northing
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 88220746-827f-4819-9a80-2a6d1c2c7fa9
		summarizeBy: sum
		sourceColumn: Northing

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BMI
		dataType: double
		isHidden
		lineageTag: 38457188-b326-4e28-ab63-a08ee7995b2c
		summarizeBy: sum
		sourceColumn: BMI

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BMI Value Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 2b33c2af-f9e3-4297-85d1-5a112bac6695
		summarizeBy: none
		sourceColumn: BMI Value Date

		variation Variation
			isDefault
			relationship: d89ace45-8da8-4efd-ae56-c75c4b8b0613
			defaultHierarchy: LocalDateTable_9172aa35-2c28-4ea1-8223-a3dde336a7f0.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'BMI Group'
		dataType: string
		isHidden
		lineageTag: 419cd974-0a4e-49af-bb5d-43c923cf351e
		summarizeBy: none
		sourceColumn: BMI Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'BMI Group Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 49f307dd-6581-48e8-927d-039da643f583
		summarizeBy: none
		sourceColumn: BMI Group Date

		variation Variation
			isDefault
			relationship: 63b40f02-072f-46ab-a97d-454dfb78fd0e
			defaultHierarchy: LocalDateTable_accd292c-8d1b-45fe-b62e-255a1cecc459.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Referred to diet team'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 44cbce36-76c9-476e-8173-f21da49f643a
		summarizeBy: sum
		sourceColumn: Referred to diet team

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Referred to diet team - latest DATE'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 6190ca84-7744-4ec5-a350-4b09e82d30bb
		summarizeBy: none
		sourceColumn: Referred to diet team - latest DATE

		variation Variation
			isDefault
			relationship: 561d8ec6-78c2-48de-906d-a012b99d65c2
			defaultHierarchy: LocalDateTable_050204ed-062b-48a6-a5a8-409a65252d65.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Referred for exercise'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 817abfd0-8255-4aae-ae51-cac5748878e5
		summarizeBy: sum
		sourceColumn: Referred for exercise

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Referred for exercise - latest DATE'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 7e409912-c7fb-4777-9d9d-5c8902eed856
		summarizeBy: none
		sourceColumn: Referred for exercise - latest DATE

		variation Variation
			isDefault
			relationship: 70ea14d4-99aa-49ef-af4a-4351a801b628
			defaultHierarchy: LocalDateTable_46db2886-cf93-4795-b2e3-0803d87bd2ff.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Given diet advice'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bf65e2ba-90e3-4809-a121-e215af737645
		summarizeBy: sum
		sourceColumn: Given diet advice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Given diet advice - latest DATE'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: e15c4bcc-374c-465b-a904-124ade825892
		summarizeBy: none
		sourceColumn: Given diet advice - latest DATE

		variation Variation
			isDefault
			relationship: 6c4b5b59-4580-42f5-9fd4-86b12a1be80c
			defaultHierarchy: LocalDateTable_da55c611-5b7f-4766-817a-c7e4db4568bd.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Given exercise advice'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c586d67-60b3-420e-bb77-984183899001
		summarizeBy: sum
		sourceColumn: Given exercise advice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Given exercise advice - latest DATE'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 2f66306a-0ef4-43c4-881b-b382bcbf480e
		summarizeBy: none
		sourceColumn: Given exercise advice - latest DATE

		variation Variation
			isDefault
			relationship: 9c4deb42-70a2-4027-a363-1d2601c80cc4
			defaultHierarchy: LocalDateTable_ff46cf3d-a2b5-4d58-a1dc-b343a6f3126c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Referred for Weight Management'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 512c8009-0b85-4306-8fec-28996dd3fb6c
		summarizeBy: sum
		sourceColumn: Referred for Weight Management

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Referred for Weight Management - first DATE'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: dfcf4af2-f130-415d-87ab-674f58d8b10f
		summarizeBy: none
		sourceColumn: Referred for Weight Management - first DATE

		variation Variation
			isDefault
			relationship: c28a013f-6b42-443f-86a4-010037f1713a
			defaultHierarchy: LocalDateTable_399a137e-90b8-4011-8fc0-dd3f2cea844f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'BMI Group Adjusted'
		dataType: string
		isHidden
		lineageTag: a2bd7092-b4d0-401e-b3d4-51b108c920ce
		summarizeBy: none
		sourceColumn: BMI Group Adjusted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: f1e7ca3b-4dc3-495b-8bf7-f92390b85232
		summarizeBy: sum
		sourceColumn: counter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Age Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 912672d6-39a8-46b7-83d6-cc5fe2188c18
		summarizeBy: sum
		sourceColumn: Age Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Adjusted BMI Category'
		dataType: string
		isHidden
		lineageTag: 81a197f0-2092-482b-b96f-a1fa547faf3f
		summarizeBy: none
		sourceColumn: Adjusted BMI Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Overweight/Obese Flag'
		dataType: string
		isHidden
		lineageTag: 8ac9d0c6-d810-4d61-9476-5cd9be89958d
		summarizeBy: none
		sourceColumn: Overweight/Obese Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'BMI 25+' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "bireports", [Query="SELECT distinct 1 as [counter], *#(lf)#(lf),case when ([Ethnic Origin Group] not like 'white' or [Ethnic Origin Group] != null) and ([BMI] BETWEEN 23 AND 27.4999999999) THEN 'Overweight (25 - 30)'#(lf)#(tab)  when ([Ethnic Origin Group] not like 'white' or [Ethnic Origin Group] != null) and ([BMI] >= 27.5) THEN 'Obese (30+)'#(lf)#(tab)  else [BMI Group] END AS [BMI Group Adjusted]#(lf)#(lf),case when ([Ethnic Origin Group] not like 'white' or [Ethnic Origin Group] != null) and ([BMI] BETWEEN 27.5 AND 32.49999999) THEN 1#(lf)#(tab)  when ([Ethnic Origin Group] like 'white%' or [Ethnic Origin Group] is null) and ([BMI] BETWEEN 30 AND 34.99999999) THEN 1#(lf)#(tab)  else 0 end as [Obesity Class 1 - adjusted]#(lf)#(lf),case when ([Ethnic Origin Group] not like 'white' or [Ethnic Origin Group] != null) and ([BMI] BETWEEN 32.5 AND 37.49999999) THEN 1#(lf)#(tab)  when ([Ethnic Origin Group] like 'white%' or [Ethnic Origin Group] is null) and ([BMI] BETWEEN 35 AND 39.99999999) THEN 1#(lf)#(tab)  else 0 end as [Obesity Class 2 - adjusted]#(lf)#(lf),case when ([Ethnic Origin Group] not like 'white' or [Ethnic Origin Group] != null) and ([BMI] >= 37.5) THEN 1#(lf)#(tab)  when ([Ethnic Origin Group] like 'white%' or [Ethnic Origin Group] is null) and ([BMI] >= 40) THEN 1#(lf)#(tab)  else 0 end as [Obesity Class 3 - adjusted]#(lf)#(lf)#(lf)  FROM [BIReports].[dbo].[Obesity_Demographics_Activity]#(lf)  where [Registered ICB] = '11M'#(lf)  and (bmi is not null or [BMI Group] is not null)#(lf)  order by [Ethnic Origin Group], BMI#(lf)#(lf)#(lf)"]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([BMI Group Adjusted] = "Obese (30+)" or [BMI Group Adjusted] = "Overweight (25 - 30)")),
				    #"Added Conditional Column" = Table.AddColumn(#"Filtered Rows", "Age Sort", each if [AgeBand5yr] = "0-4" then 1 else if [AgeBand5yr] = "5-9" then 2 else if [AgeBand5yr] = "10-14" then 3 else if [AgeBand5yr] = "15-19" then 4 else if [AgeBand5yr] = "20-24" then 5 else if [AgeBand5yr] = "25-29" then 6 else if [AgeBand5yr] = "30-34" then 7 else if [AgeBand5yr] = "35-39" then 8 else if [AgeBand5yr] = "40-44" then 9 else if [AgeBand5yr] = "45-49" then 10 else if [AgeBand5yr] = "50-54" then 11 else if [AgeBand5yr] = "55-59" then 12 else if [AgeBand5yr] = "60-64" then 13 else if [AgeBand5yr] = "65-69" then 14 else if [AgeBand5yr] = "70-74" then 15 else if [AgeBand5yr] = "75-79" then 16 else if [AgeBand5yr] = "80-84" then 17 else if [AgeBand5yr] = "85+" then 18 else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{"Deprivation Decile - Glos", Int64.Type}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Age Sort", Int64.Type}, {"Deprivation Decile - Glos", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Obesity Class 1 - adjusted", "Obesity Class I"}, {"Obesity Class 2 - adjusted", "Obesity Class II"}, {"Obesity Class 3 - adjusted", "Obesity Class III"}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Renamed Columns", "Overweight", each if [BMI Group Adjusted] = "Overweight (25 - 30)" then 1 else 0),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Conditional Column1",{"counter", "NHS Number (Pseudo)", "Gender","Age", "AgeBand5yr", "AgeBand10yr", "Ethnic Origin Group", "Ethnic Origin - Detailed Group", "Registered ICB", "Residence ICB", "GP Practice Code", "GP Practice Name", "Locality", "Primary Care Network", "LSOA Code", "Ward Code", "Ward Name", "Local Authority", "Deprivation Decile - Glos", "Easting", "Northing", "BMI", "BMI Value Date", "BMI Group", "BMI Group Date", "Referred to diet team", "Referred to diet team - latest DATE", "Referred for exercise", "Referred for exercise - latest DATE", "Given diet advice", "Given diet advice - latest DATE", "Given exercise advice", "Given exercise advice - latest DATE", "Referred for Weight Management", "Referred for Weight Management - first DATE", "BMI Group Adjusted", "Obesity Class I", "Obesity Class II", "Obesity Class III", "Overweight", "Age Sort"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Reordered Columns",{{"Overweight", Int64.Type}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type2", {"counter", "NHS Number (Pseudo)", "Gender", "Age", "AgeBand5yr", "AgeBand10yr","Ethnic Origin Group", "Ethnic Origin - Detailed Group", "Registered ICB", "Residence ICB", "GP Practice Code", "GP Practice Name", "Locality", "Primary Care Network", "LSOA Code", "Ward Code", "Ward Name", "Local Authority", "Deprivation Decile - Glos", "Easting", "Northing", "BMI", "BMI Value Date", "BMI Group", "BMI Group Date", "Referred to diet team", "Referred to diet team - latest DATE", "Referred for exercise", "Referred for exercise - latest DATE", "Given diet advice", "Given diet advice - latest DATE", "Given exercise advice", "Given exercise advice - latest DATE", "Referred for Weight Management", "Referred for Weight Management - first DATE", "BMI Group Adjusted", "Age Sort"}, "Attribute", "Value"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns",{{"Value", "Overweight/Obese Flag"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns1", each ([#"Overweight/Obese Flag"] = 1)),
				    #"Renamed Columns2" = Table.RenameColumns(#"Filtered Rows1",{{"Attribute", "Adjusted BMI Category"}})
				in
				    #"Renamed Columns2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

