table Date
	lineageTag: 4342a7b4-86eb-4763-a4ae-b8db83cbcc1f
	dataCategory: Time

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 22f42be7-22a1-4362-a4cb-87c084508c60
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 9cfd1053-498c-4593-b4ea-cb621dff99ce
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column DayMonthYear
		dataType: string
		lineageTag: a9bbcc43-e1a6-46db-9804-7e47851d26ac
		summarizeBy: none
		sourceColumn: DayMonthYear

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 5dc8fa36-fd26-4738-b980-91f7e48aace7
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DaySuffix
		dataType: string
		lineageTag: a8f2cfe9-b13a-4834-8fa3-e0d8b3eaeec0
		summarizeBy: none
		sourceColumn: DaySuffix

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: int64
		formatString: 0
		lineageTag: 8b15fdb0-31f9-4104-bc5b-50f783541d97
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column WeekDayName
		dataType: string
		lineageTag: dbd51b7b-ef4e-46b4-9bbc-2cb55d607473
		summarizeBy: none
		sourceColumn: WeekDayName

		annotation SummarizationSetBy = Automatic

	column DayofWeekInMonth
		dataType: int64
		formatString: 0
		lineageTag: 319be45d-cef1-4596-b8c1-e80d33898301
		summarizeBy: none
		sourceColumn: DayofWeekInMonth

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: c4ec751f-a031-434a-8c69-940088b69824
		summarizeBy: none
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: ef3907d4-ee34-48c5-83d1-51a32d3a1b23
		summarizeBy: none
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: 17576904-904e-4c1f-80fb-d382dd3e2ef9
		summarizeBy: none
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: dccc6b53-6063-4b3a-b0d2-75fa99cb5e7b
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a9451b3e-ee80-4760-9970-1c3a88ec2dea
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: 'Sort Financial Year'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: bb4ef251-193a-4227-b0d0-f3cac83c36ac
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterName
		dataType: string
		lineageTag: 1774099e-69b0-473a-bfe6-cd2a84c3fa09
		summarizeBy: none
		sourceColumn: QuarterName

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fe83a58e-112a-4458-a981-4d359af92bd1
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		lineageTag: 2fb8c9e8-298b-4243-9aa1-4870294201de
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

	column MonthYearName
		dataType: string
		lineageTag: 19f30b22-22cf-4b23-a634-73f0c0390030
		summarizeBy: none
		sourceColumn: MonthYearName
		sortByColumn: MonthYear

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: string
		lineageTag: 7e4c464b-0471-4dd3-8f44-707d7447662f
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 062c0043-64b1-43ea-a5f7-a17310db8c03
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 61bc65f9-5c33-4743-a674-7e1530b6b051
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FinancialWeekofYear
		dataType: int64
		formatString: 0
		lineageTag: 6e48c842-3977-4431-bd45-31ad3fcf4c37
		summarizeBy: none
		sourceColumn: FinancialWeekofYear

		annotation SummarizationSetBy = Automatic

	column HolidayName
		dataType: string
		lineageTag: 0b0cb3f4-91fc-4430-ab5b-f34c3fd2bf19
		summarizeBy: none
		sourceColumn: HolidayName

		annotation SummarizationSetBy = Automatic

	column SpecialDays
		dataType: string
		lineageTag: b7761ba8-8a93-4623-8483-1a4ef77b48fe
		summarizeBy: none
		sourceColumn: SpecialDays

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 7f7b4452-d7c6-405a-a74c-9372c2f37d95
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FinancialQuarter
		dataType: int64
		formatString: 0
		lineageTag: 801443c4-dd53-4d2f-b305-7c0b55bf72c8
		summarizeBy: none
		sourceColumn: FinancialQuarter

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: string
		lineageTag: 93bedd53-6db5-42bb-ae5d-a841834256f6
		summarizeBy: none
		sourceColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

	column FirstDateofYear
		dataType: dateTime
		formatString: General Date
		lineageTag: 44b633fd-9fe4-4d21-a1d1-d7109d8cb055
		summarizeBy: none
		sourceColumn: FirstDateofYear

		annotation SummarizationSetBy = Automatic

	column LastDateofYear
		dataType: dateTime
		formatString: General Date
		lineageTag: d2079fd1-3386-44c7-ab65-a491a7cafb67
		summarizeBy: none
		sourceColumn: LastDateofYear

		annotation SummarizationSetBy = Automatic

	column FirstDateofQuater
		dataType: dateTime
		formatString: General Date
		lineageTag: 31644dd7-231c-4771-82fd-22b4412c488c
		summarizeBy: none
		sourceColumn: FirstDateofQuater

		annotation SummarizationSetBy = Automatic

	column LastDateofQuater
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c2ac8fb-b62c-4157-825c-fc792dd24bd5
		summarizeBy: none
		sourceColumn: LastDateofQuater

		annotation SummarizationSetBy = Automatic

	column FirstDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 44acadbe-b55c-4a8c-844c-c7cd970a5aeb
		summarizeBy: none
		sourceColumn: FirstDateofMonth

		annotation SummarizationSetBy = Automatic

	column LastDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: ec1c4b9b-63d0-4068-bb0b-9295050aaeb3
		summarizeBy: none
		sourceColumn: LastDateofMonth

		annotation SummarizationSetBy = Automatic

	column FirstDateofWeek
		dataType: dateTime
		formatString: General Date
		lineageTag: 410fa117-e4bb-44e5-bc51-a0c16963c178
		summarizeBy: none
		sourceColumn: FirstDateofWeek

		annotation SummarizationSetBy = Automatic

	column LastDateofWeek
		dataType: dateTime
		formatString: General Date
		lineageTag: 0336fbd5-79e6-4b27-8b40-39d2b19e11ab
		summarizeBy: none
		sourceColumn: LastDateofWeek

		annotation SummarizationSetBy = Automatic

	column WeekBand
		dataType: string
		lineageTag: 58ca47bf-02aa-40d5-ac90-20640290d7f3
		summarizeBy: none
		sourceColumn: WeekBand

		annotation SummarizationSetBy = Automatic

	column CurrentYear
		dataType: int64
		formatString: 0
		lineageTag: fe0bde40-d73f-4007-8bf6-c109d6e48f23
		summarizeBy: none
		sourceColumn: CurrentYear

		annotation SummarizationSetBy = Automatic

	column CurrentQuater
		dataType: int64
		formatString: 0
		lineageTag: 49e0bed7-d031-4c4e-af55-08fd6df9240b
		summarizeBy: none
		sourceColumn: CurrentQuater

		annotation SummarizationSetBy = Automatic

	column CurrentMonth
		dataType: int64
		formatString: 0
		lineageTag: 8d6b5b0b-e37e-4331-af2c-ce8dacb40c70
		summarizeBy: none
		sourceColumn: CurrentMonth

		annotation SummarizationSetBy = Automatic

	column CurrentWeek
		dataType: int64
		formatString: 0
		lineageTag: e904b3f4-e76c-4e5b-b0f8-e522c83907f0
		summarizeBy: none
		sourceColumn: CurrentWeek

		annotation SummarizationSetBy = Automatic

	column CurrentDay
		dataType: int64
		formatString: 0
		lineageTag: 6a55490e-b97d-4204-b870-d2ed3de1fcb4
		summarizeBy: none
		sourceColumn: CurrentDay

		annotation SummarizationSetBy = Automatic

	column 'Sort Financial Year' = ```
			
			 var _month = month('Date'[Date])
			 var _result = IF(_month > 3, _month-3, _month+9)
			 return
			 _result
			```
		formatString: 0
		lineageTag: 859c4eee-486d-4d45-b160-71b429a0cd84
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: string
		lineageTag: aebbcb71-e45a-4e2c-a635-7d22d9cfc2ea
		summarizeBy: none
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarMonth
		dataType: string
		lineageTag: 9be52a84-30d9-4192-b747-a85f817ad43a
		summarizeBy: none
		sourceColumn: CalendarMonth

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="select * from CCG_Reference.Reference.vw_DateLookup#(lf)where [Date] >= '01/04/2019'#(lf)#(lf)"]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Day] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

