table 'Ref - GP'
	lineageTag: 8b77480d-0d29-42bf-864c-c78f50e70e42

	column PracNameCurrent
		dataType: string
		lineageTag: f9d5f263-65d9-40ba-8b3b-3b2e11738bac
		summarizeBy: none
		sourceColumn: PracNameCurrent

		annotation SummarizationSetBy = Automatic

	column LocalityName
		dataType: string
		lineageTag: 258c96b4-5c99-4e87-badc-9c8048b5e9fd
		summarizeBy: none
		sourceColumn: LocalityName

		annotation SummarizationSetBy = Automatic

	column NetworkName
		dataType: string
		lineageTag: 778c4152-f79c-4b06-b62f-aab8e1b4cf06
		summarizeBy: none
		sourceColumn: NetworkName

		annotation SummarizationSetBy = Automatic

	partition 'Ref - GP' = m
		mode: import
		source =
				let
				    Source = #"Ref - Source Table",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"PracNameCurrent", "LocalityName", "NetworkName"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"PracNameCurrent"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

