table 'Test strips ePact Prescribing'
	lineageTag: ef7a9cf1-7c34-49be-9086-5a790d833917

	measure cgm_-_test_strips_saving_old = calculate('CGM ePact Prescribing'[Full_year_cost_-_rebate],'CGM ePact Prescribing'[FinancialYear] = "2023/24")-[test_strips_diff_previous_ytd_cost]
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: c2d2232d-581f-4583-9bab-4b7310a77282

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure Previous_YTD_Cost_test_strips = calculate(sum('Test strips ePact Prescribing'[Cost (£)]),datesytd(sameperiodlastyear(date_table[date]),"31/3"))
		lineageTag: baa63c89-4446-41a1-98e7-8445d50541c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure test_strips_ytd_cost = CALCULATE(sum('Test strips ePact Prescribing'[Cost (£)]), 'Test strips ePact Prescribing'[FinancialYear] = "2024/25")
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: 11523d0c-98f4-4b99-a479-633e6b8497a6

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure test_strips_2022_23_same_point_cost = calculate(sum('Test strips ePact Prescribing'[Cost (£)]),'Test strips ePact Prescribing'[FinancialYear] = "2022/23", 'Test strips ePact Prescribing'[ytd_months] = 1)
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: 887a65b7-23e7-4501-a62f-45ce63814b39

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure test_strips_diff_previous_ytd_cost = 'Test strips ePact Prescribing'[test_strips_2023_24_same_point_cost] - 'Test strips ePact Prescribing'[test_strips_ytd_cost]
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: 22ceeff0-a81b-418b-a6cf-e26ccf1b4a96

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure Test_Strips_Cost_per_1000 = (DIVIDE('Test strips ePact Prescribing'[test_strips_ytd_cost],'NDA Diabetic Population'[Diabetic Population])) * 1000
		lineageTag: 73acdce4-757f-4509-be81-f15fdfe98a45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure test_strips_2023_24_same_point_cost = calculate(sum('Test strips ePact Prescribing'[Cost (£)]),'Test strips ePact Prescribing'[FinancialYear] = "2023/24", 'Test strips ePact Prescribing'[ytd_months] = 1)
		lineageTag: b741a605-3e17-4eba-bc9d-484b3026a58f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure test_strips_2022_23_total_cost = calculate(sum('Test strips ePact Prescribing'[Cost (£)]),'Test strips ePact Prescribing'[FinancialYear] = "2022/23")
		lineageTag: 9c3c5c49-20ed-4885-b1bf-b96b3b7feed1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure test_strips_2021_22_total_cost = calculate(sum('Test strips ePact Prescribing'[Cost (£)]),'Test strips ePact Prescribing'[FinancialYear] = "2021/22")
		lineageTag: d5625e14-4bc3-4bd8-812b-375b3669a25d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 22_23_test_strips_savings = 'Test strips ePact Prescribing'[test_strips_2022_23_total_cost] - 'Test strips ePact Prescribing'[test_strips_2021_22_total_cost]
		lineageTag: 71103b54-2659-4c17-84e6-7692bef2d01d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure test_strips_2023_24_total_cost = calculate(sum('Test strips ePact Prescribing'[Cost (£)]),'Test strips ePact Prescribing'[FinancialYear] = "2023/24")
		lineageTag: 4ccd0f0d-4f09-4ec5-a650-0d498da83d2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 23_24_test_strip_savings = 'Test strips ePact Prescribing'[test_strips_2023_24_total_cost] - 'Test strips ePact Prescribing'[test_strips_2022_23_total_cost]
		lineageTag: f82d60b5-98ec-48ea-a7d3-e8a1e8344b84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure total_test_strip_savings_202204_onwards = 'Test strips ePact Prescribing'[22_23_test_strips_savings] + 'Test strips ePact Prescribing'[23_24_test_strip_savings] +'Test strips ePact Prescribing'[test_strips_diff_previous_ytd_cost]
		lineageTag: bd363755-10ea-41d3-8611-4412ce3f8447

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure total_cost = sum('Test strips ePact Prescribing'[Cost (£)])
		lineageTag: 7d656d17-8d93-4c51-8903-190171b3a64c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Test_strips_previous_year_diff = sum('Test strips ePact Prescribing'[Cost (£)]) - CALCULATE(SUM('Test strips ePact Prescribing'[Cost (£)]), SAMEPERIODLASTYEAR(date_table[date]))
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: c7cf50f6-3c50-4c59-a1e6-a9b35634364e

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure cgm_-_test_strips_saving = 'CGM ePact Prescribing'[Full_year_cost_-_rebate]+[Test_strips_previous_year_diff]
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: b396fe82-e547-4efb-a1d4-935d9d507c9d

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: f02e881f-638f-4c39-b4bf-d4f219815d4f
		summarizeBy: sum
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column LastDateofMonth
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 4d2a5560-78c7-4216-b558-37320d123d55
		summarizeBy: none
		sourceColumn: LastDateofMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column HSPracticeCode
		dataType: string
		lineageTag: 1e1a692a-b98d-48aa-a83a-592261b35fe6
		summarizeBy: none
		sourceColumn: HSPracticeCode

		annotation SummarizationSetBy = Automatic

	column HSPractice
		dataType: string
		lineageTag: 5944f6fd-ec27-42e3-af39-1f16472c3758
		summarizeBy: none
		sourceColumn: HSPractice

		annotation SummarizationSetBy = Automatic

	column BNFPresentationCode
		dataType: string
		lineageTag: 2bbe5fa9-a140-47e2-b7f2-b0c0b709a3c0
		summarizeBy: none
		sourceColumn: BNFPresentationCode

		annotation SummarizationSetBy = Automatic

	column 'BNF Product Name'
		dataType: string
		lineageTag: 8adab503-9518-4bec-8925-0441758ef516
		summarizeBy: none
		sourceColumn: BNF Product Name

		annotation SummarizationSetBy = Automatic

	column Items
		dataType: int64
		formatString: 0
		lineageTag: 874afa9c-4806-405f-868b-64b880b3446a
		summarizeBy: sum
		sourceColumn: Items

		annotation SummarizationSetBy = Automatic

	column 'Cost (£)'
		dataType: double
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: c3123b85-2bf3-4a06-8edb-e751e4d13eb1
		summarizeBy: sum
		sourceColumn: Cost (£)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column Quantity
		dataType: double
		lineageTag: 301c5187-2d50-4807-a7f6-6368b35c787b
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Age
		dataType: string
		lineageTag: a188e11e-7eb4-440d-8a8d-5986c7650461
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column OrganisationName
		dataType: string
		lineageTag: a2dce243-ce41-4ba5-b4fd-02be108826c6
		summarizeBy: none
		sourceColumn: OrganisationName

		annotation SummarizationSetBy = Automatic

	column 'Practice Name'
		dataType: string
		lineageTag: e2aa86fe-0f0f-4d98-88ee-3ac89d31bb1c
		summarizeBy: none
		sourceColumn: Practice Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 427db9e3-06d0-4e63-aa0f-52c512bcb52e
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 42bd1a9b-6ded-4c06-80de-66337d2c9e1f
		summarizeBy: sum
		sourceColumn: FinancialMonth

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column ytd_months
		dataType: int64
		formatString: 0
		lineageTag: cbf8fc95-ed68-477f-8f48-3c324f7e035e
		summarizeBy: sum
		sourceColumn: ytd_months

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 54bc2213-ca2e-4ba7-94bc-d3b5c88b10fe
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	partition 'Test strips ePact Prescribing' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Current", [Query="SET ANSI_NULLS ON#(lf)SET QUOTED_IDENTIFIER ON#(lf)set nocount on#(lf)set ansi_warnings off #(lf)#(lf)IF OBJECT_ID('tempdb..#temp_ytd') is not null#(lf)drop table #temp_ytd#(lf)#(lf)SELECT distinct [A].[YearMonth]#(lf)#(tab)  ,[D].[FinancialMonth]#(lf)into #temp_ytd#(lf)#(tab)  #(lf)#(lf)FROM [CCG_Current].[ePACT2].[vw_Extract] as [A]#(lf)#(lf)#(tab)#(tab)LEFT JOIN [CCG_Reference].[Reference].[vw_GPPractice] as [B]#(lf)#(tab)#(tab)ON [A].[HSPracticeCode] = [B].[OrganisationCode]#(lf)#(lf)#(tab)#(tab)left join [CCG_Reference].[Reference].[vw_DateLookup][D]#(lf)#(tab)#(tab)on [A].[YearMonth] = [D].[YearMonth]#(lf)#(lf)WHERE [BNFChemicalSubstanceCode] in ('0601060D0','0601060X0')#(lf)  AND [A].[YearMonth] >= '202404'#(lf)  and [HSCommissioner_or_ProviderCode] like '11M%'#(lf)  and [D].[Date] = [D].[LastDateofMonth]#(lf)#(lf)/*------------------------------------------------------------------------#(lf)------------------------------------------------------------------------*/#(lf)#(lf)SELECT [A].[YearMonth]#(lf)      ,[A].[Month]#(lf)#(tab)  ,[D].[LastDateofMonth]#(lf)#(tab)  ,[D].[FinancialMonth]#(lf)#(tab)  ,[D].[FinancialYear]#(lf)      ,[HSPracticeCode]#(lf)      ,[HSPractice]#(lf)      ,[BNFPresentationCode]#(lf)      ,[BNFPresentation]#(lf)      ,[Items] #(lf)      ,[ActualCost]#(lf)      ,[Quantity]#(lf)      ,[fiveyearsageband]#(lf)#(tab)  ,[B].[OrganisationName]#(lf)#(tab)  ,[B].[ReportingOrganisationName]#(lf)#(tab)  ,[B].[PrimaryCareNetwork]#(lf)#(tab)  ,[ytd_months] = case when [D].[financialmonth] in (select distinct [financialmonth] from #temp_ytd) then 1 else 0 end#(lf)#(tab)  #(lf)#(lf)FROM [CCG_Current].[ePACT2].[vw_Extract] as [A]#(lf)#(lf)#(tab)#(tab)LEFT JOIN [CCG_Reference].[Reference].[vw_GPPractice] as [B]#(lf)#(tab)#(tab)ON [A].[HSPracticeCode] = [B].[OrganisationCode]#(lf)#(lf)#(tab)#(tab)left join [CCG_Reference].[Reference].[vw_DateLookup][D]#(lf)#(tab)#(tab)on [A].[YearMonth] = [D].[YearMonth]#(lf)#(lf)WHERE [BNFChemicalSubstanceCode] in ('0601060D0','0601060X0')#(lf)  AND [A].[YearMonth] >= '201904'#(lf)  and [HSCommissioner_or_ProviderCode] like '11M%'#(lf)  and [D].[Date] = [D].[LastDateofMonth]#(lf)"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"ActualCost", "Cost (£)"}, {"BNFPresentation", "BNF Product Name"}, {"fiveyearsageband", "Age"}, {"ReportingOrganisationName", "Practice Name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Month"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"LastDateofMonth", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

