table 'Core20 Reference'
	lineageTag: b3b81b4e-cff0-4fa2-a103-05a39bf4d9de

	column Core20Flag
		dataType: int64
		formatString: 0
		lineageTag: e716b1f5-867c-4ebf-80ad-7deb62466f10
		summarizeBy: none
		sourceColumn: Core20Flag

		annotation SummarizationSetBy = Automatic

	column Core20
		dataType: string
		lineageTag: 741a090b-3a03-42df-8947-c2d2114de3f6
		summarizeBy: none
		sourceColumn: Core20

		annotation SummarizationSetBy = Automatic

	partition 'Core20 Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUYpMLVaK1YlWMgCy/fKVYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Core20Flag = _t, Core20 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Core20Flag", Int64.Type}, {"Core20", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

