table 'Population LTC'
	lineageTag: 9207f1fc-4f3c-47e7-8a1d-14b6c680c615

	column Attribute
		dataType: string
		lineageTag: b21c9b40-9135-4286-8f24-e7d78b47d9bb
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 40fb31d8-8c67-4129-b4d3-70a92cc0b564
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column PseudoNHSNumber
		dataType: string
		lineageTag: adcc2192-505d-4210-bc35-575069563058
		summarizeBy: none
		sourceColumn: PseudoNHSNumber

		annotation SummarizationSetBy = Automatic

	partition 'Population LTC' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select pseudonhsnumber as ""PseudoNHSNumber"", gender, derivedage as ""DerivedAge"", ageband5yr as ""AgeBand5yr"", ageband10yr as ""AgeBand10yr"", derivedethnicitygroup as ""DerivedEthnicityGroup"", practicecode as ""PracticeCode"", practicename as ""PracticeName"", living_alone as ""Living Alone"", living_in_a_care_home as ""Living in a Care Home"", core20flag as ""Core20Flag"", imdcountydecile as ""IMDcountyDecile"", locality as ""Locality"", primary_care_network as ""Primary Care Network"", ""rockwood catogory"" as ""Rockwood Catogory"", eficategoryderived as ""eFICategoryDerived"", ltccountderived as ""LTCCountDerived"", obesity as ""OBESITY"", smoker as ""SMOKER"", asthma as ""ASTHMA"", copd as ""COPD"", dementia as ""DEMENTIA"", depression as ""DEPRESSION"", diabetes as ""DIABETES"", palliativecare as ""PalliativeCare"", chronickidneydisease as ""ChronicKidneyDisease"", epilepsy as ""Epilepsy"", heartfailure as ""HeartFailure"", stroke as ""STROKE"", ""atrial fibrillation"" as ""ATRIAL FIBRILLATION"", cancer as ""CANCER"", ""coronary heart disease"" as ""CORONARY HEART DISEASE"", hypertension as ""HYPERTENSION"", ""learning disability"" as ""LEARNING DISABILITY"", ""mental health"" as ""MENTAL HEALTH"", bmigroup as ""BMIGroup"", acgpatientneedsgroup as ""ACGPatientNeedsGroup"", processeddate as ""ProcessedDate"" from data_mart_powerbi_community.tbl01_creativehealthpopulationltcref", null, [EnableFolding=true]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"gender", "DerivedAge", "AgeBand5yr", "AgeBand10yr", "DerivedEthnicityGroup", "PracticeCode", "PracticeName"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"PseudoNHSNumber", "OBESITY", "SMOKER", "ASTHMA", "COPD", "DEMENTIA", "DEPRESSION", "DIABETES", "PalliativeCare", "ChronicKidneyDisease", "Epilepsy", "HeartFailure", "STROKE", "ATRIAL FIBRILLATION", "CANCER", "CORONARY HEART DISEASE", "HYPERTENSION", "LEARNING DISABILITY", "MENTAL HEALTH"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"PseudoNHSNumber"}, "Attribute", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Other Columns", each ([Value] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

