table 'Frailty Reference'
	lineageTag: e3012aa3-ffcd-4a30-980f-37c6f1984e1a

	column 'Frailty Type'
		dataType: string
		lineageTag: e5aa5e02-fde1-4f33-b4dd-efce5be7a9a5
		summarizeBy: none
		sourceColumn: Frailty Type
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 8deb1722-4d3d-4b2e-af11-b5e88003e52b
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Frailty Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8svP03UrSszMUdJRMlSK1YlW8s3MSQFyjCCc/JTUosSSVKCAMVggOLUstQjENVGKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Frailty Type" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Frailty Type", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

