table 'Comparison Cohort'
	lineageTag: c093b782-8edc-43f3-9a83-4ad87c68e4d3

	measure '% MPI are Male' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Gender]),
				'Comparison Cohort'[Gender] IN { "M" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: eec68a3b-a77c-411b-b515-4bd8248302f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Children and Young People (0-17)' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Derived_Pseudo_NHS]),
				'Comparison Cohort'[AgeBand] IN { "Children and Young People (0-17)" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			
			```
		lineageTag: ea546ff1-f37b-45ad-90e7-185b13da4ca5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Core20' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[Core20Flag])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 5ea1f1ab-76d8-4bcb-bfaa-3c4462bd7e57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Female' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Gender]),
				'Comparison Cohort'[Gender] IN { "F" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 344ad3b2-2129-4350-9a00-b16739f46b4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Older Adults (65+)' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Derived_Pseudo_NHS]),
				'Comparison Cohort'[AgeBand] IN { "Older Adults (65+)" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 19a9b341-e254-4d59-9c72-196b8ea113d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Working Age Adults (18-64)' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Derived_Pseudo_NHS]),
				'Comparison Cohort'[AgeBand] IN { "Working Age Adults (18-64)" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 71f27413-b7d0-456e-b864-3c00db0ed69b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Age MPI' = AVERAGE('Comparison Cohort'[Derived_Age])
		lineageTag: 4cb46daf-0abd-4f9b-86ee-988d997fb50c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Asthma' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[AsthmaDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: e67629c7-b563-4d60-8428-a99607079b59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Cancer' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[CancerDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: d1a894ad-ab4d-4349-b268-0fd9f6cae879

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have CKD' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[ChronicKidneyDiseaseDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 98705664-fa56-44f7-960a-8ded8eb85c9c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have COPD' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[COPDDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 5f95a09d-7faa-4af7-8309-1085f99ec092

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have CHD' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[CoronaryHeartDiseaseDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: d1d4789a-59d7-4139-a61e-7c2af1c07a31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Dementia' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[DementiaDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 797146ac-635d-4ec0-9329-eb2700c5c9fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Depression' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[DepressionDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 6613ef50-5367-483c-9720-731dfcba4de5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Diabetes' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[DiabetesDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 704c544d-1e40-4eaf-9083-fa64eb71ed9c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Epilepsy' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[EpilepsyDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 714fc617-5f8f-44c5-a2a4-c453edb37512

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Heart Failure' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[HeartFailureDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: a1f6823a-cbd3-4f38-9500-4e64fec6f32e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Hypertension' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[HypertensionDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 7b11764e-b790-4c3f-b69e-8e783df81ad7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Hypothyroidism' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[HypothyroidismDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 8b88bd83-b8fc-43d2-bdc1-cedc137e36b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Learning Disability' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[LearningDisabilityDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 3a59f40a-2429-44e4-a9ee-d2ae78fdc473

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Mental Illness' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[MentalIllnessDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 3c49d7f5-0c35-4267-95ad-691de4948598

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Obesity' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[ObesityDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 0d50f9d0-dbfc-4658-85f6-aa9f3bdcdb53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Palliative Care' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[PalliativeCareDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 4671874d-a87c-41a3-a4cb-11c4f2bdc6f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Smoker' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[SmokerDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: d00e2f0a-63d8-4db6-a027-86153d71d068

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI have Stroke' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[StrokeDerived])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: eb235444-c847-4fc2-ba52-984bbc8677f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI rockwood mild' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[counter]),
				'Comparison Cohort'[Frailty_Type] IN { "Mild" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 00fe1d98-82d6-4801-955d-a8194afe1c21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI rockwood moderate' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[counter]),
				'Comparison Cohort'[Frailty_Type] IN { "Moderate" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 21ce772a-6cf8-4015-9c66-f80c1f11dc31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI rockwood severe' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[counter]),
				'Comparison Cohort'[Frailty_Type] IN { "Severe" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 936dd27f-571f-450e-ba99-5a4b3a359c11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI rockwood non-frail' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[counter]),
				'Comparison Cohort'[Frailty_Type] IN { "Non-Frail" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 249fd495-288e-4531-931a-8b6a53cff477

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI rockwood no frailty recorded' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[counter]),
				'Comparison Cohort'[Frailty_Type] IN { "No rockwood score recorded" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 709e8076-c600-49eb-b269-170172544399

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: a0554ba8-8b30-4014-bf08-d6f1e8883e4f
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 170bbc9b-f681-4840-81ee-b0134b00eb99
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Derived_Age
		dataType: int64
		formatString: 0
		lineageTag: b55954e1-ee99-4942-b387-8f50240800d6
		summarizeBy: none
		sourceColumn: Derived_Age

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: fbb5377f-c467-4918-a069-d4298a402637
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column EthnicOriginDescription
		dataType: string
		lineageTag: d8755482-1297-4faa-8179-f7d739dceb04
		summarizeBy: none
		sourceColumn: EthnicOriginDescription

		annotation SummarizationSetBy = Automatic

	column PracNameCurrent
		dataType: string
		lineageTag: 4dbe6748-178a-4975-ba78-b464cc541444
		summarizeBy: none
		sourceColumn: PracNameCurrent

		annotation SummarizationSetBy = Automatic

	column Core20Flag
		dataType: string
		lineageTag: 0424bccf-8d29-4f1e-ae64-06c17199a758
		summarizeBy: none
		sourceColumn: Core20Flag

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: double
		lineageTag: 3da4cd82-3bae-43ba-a412-eeb7ff2e3565
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ObesityDerived
		dataType: int64
		formatString: 0
		lineageTag: 6d80f195-e017-4b98-8f43-75ad650f3fd4
		summarizeBy: none
		sourceColumn: ObesityDerived

		annotation SummarizationSetBy = Automatic

	column SmokerDerived
		dataType: int64
		formatString: 0
		lineageTag: 611211a2-c7de-42b9-a370-aada16869a16
		summarizeBy: none
		sourceColumn: SmokerDerived

		annotation SummarizationSetBy = Automatic

	column AsthmaDerived
		dataType: int64
		formatString: 0
		lineageTag: ad89f3bb-1e9c-44cb-95bd-68f273173b11
		summarizeBy: none
		sourceColumn: AsthmaDerived

		annotation SummarizationSetBy = Automatic

	column COPDDerived
		dataType: int64
		formatString: 0
		lineageTag: 49e5250a-42ab-4ea1-bbbb-c17ab35379d4
		summarizeBy: none
		sourceColumn: COPDDerived

		annotation SummarizationSetBy = Automatic

	column DementiaDerived
		dataType: int64
		formatString: 0
		lineageTag: 88fc1e7e-b0a3-4bb9-9bb5-214a25525389
		summarizeBy: none
		sourceColumn: DementiaDerived

		annotation SummarizationSetBy = Automatic

	column DepressionDerived
		dataType: int64
		formatString: 0
		lineageTag: 20c81cf3-620a-4b6f-847a-43ebd50314be
		summarizeBy: none
		sourceColumn: DepressionDerived

		annotation SummarizationSetBy = Automatic

	column DiabetesDerived
		dataType: int64
		formatString: 0
		lineageTag: 4e21084c-1392-4054-a922-797804b4babf
		summarizeBy: none
		sourceColumn: DiabetesDerived

		annotation SummarizationSetBy = Automatic

	column PalliativeCareDerived
		dataType: int64
		formatString: 0
		lineageTag: 1f6c5d8b-eb7a-40c2-a3ed-a41f740c22ce
		summarizeBy: none
		sourceColumn: PalliativeCareDerived

		annotation SummarizationSetBy = Automatic

	column ChronicKidneyDiseaseDerived
		dataType: int64
		formatString: 0
		lineageTag: 66d02266-062b-4912-8ba8-f503f45828ba
		summarizeBy: none
		sourceColumn: ChronicKidneyDiseaseDerived

		annotation SummarizationSetBy = Automatic

	column EpilepsyDerived
		dataType: int64
		formatString: 0
		lineageTag: 75576af9-7d56-4cba-a4a7-a4d33f286203
		summarizeBy: none
		sourceColumn: EpilepsyDerived

		annotation SummarizationSetBy = Automatic

	column HeartFailureDerived
		dataType: int64
		formatString: 0
		lineageTag: 9ec3e54e-a1f9-41dd-92be-d320ea915610
		summarizeBy: none
		sourceColumn: HeartFailureDerived

		annotation SummarizationSetBy = Automatic

	column StrokeDerived
		dataType: int64
		formatString: 0
		lineageTag: dc3f6325-7478-422e-b53c-1f597f303ee5
		summarizeBy: none
		sourceColumn: StrokeDerived

		annotation SummarizationSetBy = Automatic

	column AtrialFibrillationDerived
		dataType: int64
		formatString: 0
		lineageTag: b1ebf361-b04f-4e29-befe-7d81e761b889
		summarizeBy: sum
		sourceColumn: AtrialFibrillationDerived

		annotation SummarizationSetBy = Automatic

	column CancerDerived
		dataType: int64
		formatString: 0
		lineageTag: 0bc95599-77a0-4be5-b5fa-5a3c5945f92b
		summarizeBy: none
		sourceColumn: CancerDerived

		annotation SummarizationSetBy = Automatic

	column CoronaryHeartDiseaseDerived
		dataType: int64
		formatString: 0
		lineageTag: d4ff523b-2e7e-4de0-8ba3-8f008daa94c8
		summarizeBy: none
		sourceColumn: CoronaryHeartDiseaseDerived

		annotation SummarizationSetBy = Automatic

	column HypertensionDerived
		dataType: int64
		formatString: 0
		lineageTag: 392b7483-5317-4b25-8aea-c9525828172b
		summarizeBy: none
		sourceColumn: HypertensionDerived

		annotation SummarizationSetBy = Automatic

	column HypothyroidismDerived
		dataType: int64
		formatString: 0
		lineageTag: 47e6c0a9-ea3d-40ae-881c-1e052ca1b7bb
		summarizeBy: none
		sourceColumn: HypothyroidismDerived

		annotation SummarizationSetBy = Automatic

	column LearningDisabilityDerived
		dataType: int64
		formatString: 0
		lineageTag: 8e9e8091-a430-4bba-a9fe-24e715a809a2
		summarizeBy: none
		sourceColumn: LearningDisabilityDerived

		annotation SummarizationSetBy = Automatic

	column MentalIllnessDerived
		dataType: int64
		formatString: 0
		lineageTag: 283ecb23-b9b3-49b6-8e46-6afa4ca4c5c7
		summarizeBy: none
		sourceColumn: MentalIllnessDerived

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: 71f60691-0f4d-4366-a5e7-7fb57c882fa1
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column Number_of_ED_attendances
		dataType: int64
		formatString: 0
		lineageTag: 847b3fa3-5654-440c-b0c6-4b66069ff958
		summarizeBy: sum
		sourceColumn: Number_of_ED_attendances

		annotation SummarizationSetBy = Automatic

	column number_of_PC_appointments
		dataType: int64
		formatString: 0
		lineageTag: e8ddd653-a43d-446f-9ee9-c84fc50bcc7a
		summarizeBy: sum
		sourceColumn: number_of_PC_appointments

		annotation SummarizationSetBy = Automatic

	column number_of_SWAST_calls
		dataType: int64
		formatString: 0
		lineageTag: 51a13734-9dd3-42b7-80cb-fb1d8e7ddbd9
		summarizeBy: sum
		sourceColumn: number_of_SWAST_calls

		annotation SummarizationSetBy = Automatic

	column number_of_111_calls
		dataType: int64
		formatString: 0
		lineageTag: 59a0fe0f-6c0b-4190-82e2-04ded9de37b2
		summarizeBy: sum
		sourceColumn: number_of_111_calls

		annotation SummarizationSetBy = Automatic

	column number_of_rapid_response
		dataType: int64
		formatString: 0
		lineageTag: eb7a19f6-392b-46f2-895f-511595ccde04
		summarizeBy: sum
		sourceColumn: number_of_rapid_response

		annotation SummarizationSetBy = Automatic

	column number_of_hospital_admissions
		dataType: int64
		formatString: 0
		lineageTag: 5a0d80aa-4ae4-4eae-b00c-43acbb3b33eb
		summarizeBy: sum
		sourceColumn: number_of_hospital_admissions

		annotation SummarizationSetBy = Automatic

	column number_of_MIU_attendances
		dataType: int64
		formatString: 0
		lineageTag: 9e036a35-e768-4405-b696-ca9f74611a3c
		summarizeBy: sum
		sourceColumn: number_of_MIU_attendances

		annotation SummarizationSetBy = Automatic

	column number_of_OOH_appointments
		dataType: int64
		formatString: 0
		lineageTag: fa88d6e1-4b15-4bf8-9926-d2b9b7b8992f
		summarizeBy: sum
		sourceColumn: number_of_OOH_appointments

		annotation SummarizationSetBy = Automatic

	column Frailty_Type
		dataType: string
		lineageTag: 1d849fe3-6790-4fde-85c3-b334305498ff
		summarizeBy: none
		sourceColumn: Frailty_Type

		annotation SummarizationSetBy = Automatic

	partition 'Comparison Cohort' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "BIReports", [Query="/****** Script for SelectTopNRows command from SSMS  ******/#(lf)#(lf)#(lf) #(lf)  ------------------#(lf)  --SWAST Calls#(lf)  ------------------#(lf)#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#SWAST') IS NOT NULL DROP TABLE #SWAST#(lf)#(lf)#(tab)SELECT#(lf)#(tab)[Derived_Pseudo_NHSNumber]#(lf)#(tab),[number_of_SWAST_calls] = sum(1)#(lf)#(lf)#(tab)INTO #SWAST#(lf)#(lf)#(tab)FROM [CCG_Current].[SWASFT].[vw_AmbulanceServicePatient]#(lf)#(lf)#(tab)WHERE [Time_Of_Incident] >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [Derived_Pseudo_NHSNumber]#(lf)#(lf) #(lf)#(tab)------------------#(lf)#(tab)--Rapid Response#(lf)#(tab)------------------#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#Rapid_Response') IS NOT NULL DROP TABLE #Rapid_Response#(lf)#(lf)#(tab)SELECT#(lf)#(tab)[r].[DerivedPseudoNHS]#(lf)#(tab),[number_of_rapid_response] = sum(1)#(lf)#(lf)#(tab)INTO #Rapid_Response#(lf)#(lf)#(tab)FROM [CCG_Current].[CSDS].[vw_301_Referral] as r#(lf) #(lf)#(tab)LEFT JOIN CCG_Reference.GHC.vw_Hierarchy as h on r.Current_CostCentre = h.Cost_Centre#(lf)#(lf)#(tab)WHERE OrgIDProvider in ('R1J','RTQ')#(lf)#(lf)#(tab)AND [ReferralRequestReceivedDate] >= '2022-09-01'#(lf)#(tab)#(lf)#(tab)AND h.Cost_Centre in ('G15503', --Rapid Response#(lf)#(tab)'G15503a', --Rapid Response - RR - ENDNS#(lf)#(tab)'G15503b')--Rapid Response - RR - District Nursing#(lf)#(tab)#(tab)#(lf)#(tab)AND [ReferralRequestReceivedDate] >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [DerivedPseudoNHS]#(lf)#(lf)#(tab)#(lf)#(tab)------------------#(lf)#(tab)--OOH#(lf)#(tab)------------------#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID('tempdb..#OOH') is not null drop table #OOH#(lf)#(lf)#(tab)SELECT #(lf)#(tab)[nhsnumber]#(lf)#(tab),[number_of_OOH_appointments] = SUM(1)#(lf)#(lf)#(tab)into #OOH#(lf)#(tab)FROM [CCG_Current].[CareUK].[vw_OutOfHours]#(lf)#(lf)#(tab)where ReceivedDateTime >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [nhsnumber]#(lf)#(lf)#(lf)#(tab)------------------------#(lf)#(tab)--Rockwood Frailty#(lf)#(tab)------------------------#(lf)#(lf)IF OBJECT_ID('TEMPDB..#TEMP_ROCKWOOD') IS NOT NULL DROP TABLE #TEMP_ROCKWOOD#(lf)IF OBJECT_ID('TEMPDB..#TEMP_ROCKWOOD_VALUE_FIXED') IS NOT NULL DROP TABLE #TEMP_ROCKWOOD_VALUE_FIXED#(lf);#(lf) #(lf)SELECT DISTINCT [PseudoNHSNumber]#(lf)#(tab)#(tab)#(tab)   ,[PracticeDescription]#(lf)#(tab)#(tab)#(tab)   ,[PracticeCode]#(lf)#(tab)#(tab)#(tab)   ,[EventDate]#(lf)#(tab)#(tab)#(tab)   ,[Event_Order] = ROW_NUMBER() OVER (PARTITION BY [PseudoNHSNumber] ORDER BY [EventDate] DESC)#(lf)#(tab)#(tab)#(tab)   ,[Value1]#(lf)#(tab)#(tab)#(tab)   ,[Value_Fix] = ISNUMERIC([Value1])#(lf) #(lf)INTO #TEMP_ROCKWOOD#(lf)FROM [CCG_Current].[PrimaryCare].[vw_Events]#(lf) #(lf)WHERE ([EventCode] COLLATE SQL_Latin1_General_CP1_CS_AS IN ('XaQik')#(lf)OR [SnomedCode] = '763264000')#(lf)AND [PseudoNHSNumber] IS NOT NULL#(lf);#(lf) #(lf)SELECT DISTINCT [PseudoNHSNumber]#(lf)#(tab)#(tab)#(tab)   ,[PracticeDescription]#(lf)#(tab)#(tab)#(tab)   ,[PracticeCode]#(lf)#(tab)#(tab)#(tab)   ,[EventDate]#(lf)#(tab)#(tab)#(tab)   ,[Event_Order]#(lf)#(tab)#(tab)#(tab)   ,[Value_1] = CAST([Value1] AS FLOAT)#(lf) #(lf)INTO #TEMP_ROCKWOOD_VALUE_FIXED#(lf)FROM #TEMP_ROCKWOOD#(lf) #(lf)WHERE [Value_Fix] = 1#(lf)AND [Event_Order] = 1#(lf);#(lf) #(lf)ALTER TABLE #TEMP_ROCKWOOD_VALUE_FIXED#(lf)ADD [Month_Date] VARCHAR (30)#(lf);#(lf) #(lf)#(lf) IF OBJECT_ID('TEMPDB..#rockwood') IS NOT NULL DROP TABLE #rockwood#(lf)#(lf)SELECT DISTINCT #(lf)[PseudoNHSNumber]#(lf),[Frailty_Type] =  CASE WHEN [Value_1] BETWEEN 1 AND 4 THEN 'Non-Frail'#(lf)#(tab)#(tab)#(tab)                           WHEN [Value_1] = 5 THEN 'Mild'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)   WHEN [Value_1] = 6 THEN 'Moderate'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)   WHEN [Value_1] BETWEEN 7 AND 9 THEN 'Severe'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)   ELSE 'Unknown' END#(lf)#(lf)INTO #rockwood#(lf) #(lf)FROM #TEMP_ROCKWOOD_VALUE_FIXED AS [RW]#(lf) #(lf)LEFT JOIN (SELECT DISTINCT [Derived_NHS_Number]#(lf)                          ,[PDS_Flag] = 1 #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  ,[Derived_Age]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  ,[Gender_Desc]#(lf) #(lf)#(tab)#(tab)   FROM [CCG_Reference].[Population].[vw_PDS_Current]) AS [PDS]#(lf)ON [PDS].[Derived_NHS_Number] = [RW].[PseudoNHSNumber]#(lf) #(lf)LEFT JOIN (SELECT DISTINCT [Age], [5YR_Age_Band] FROM [CCG_Reference].[Reference].[vw_AgeBand]) AS [AGE]#(lf)ON [AGE].[Age] = [PDS].[Derived_Age]#(lf) #(lf)WHERE [PDS_Flag] = 1#(lf)#(lf)#(lf)#(lf)#(tab)---------------------#(lf)#(tab)--Combined table#(lf)#(tab)---------------------#(lf)#(lf)SELECT #(lf)#(tab)[counter] = 1#(lf)#(tab),Core20Flag#(lf)#(tab),[M].[Derived_Pseudo_NHS]#(lf)#(tab),AgeBand#(lf)#(tab),EthnicOriginDescription#(lf)#(tab),Gender#(lf)#(tab),PracNameCurrent#(lf)#(tab),Derived_Age#(lf)#(tab),IMDcountyDecile#(lf)#(tab),[Number_of_ED_attendances] = edonlyaetotal #(lf)#(tab),[number_of_PC_appointments] = gpappttotal#(lf)#(tab),[number_of_SWAST_calls] = case when [number_of_SWAST_calls] is null then '0' else [number_of_SWAST_calls] END#(lf)#(tab),[number_of_111_calls] = [111Total]#(lf)#(tab),[number_of_rapid_response] = case when [number_of_rapid_response] is null then '0' else [number_of_rapid_response] END#(lf)#(tab),[number_of_hospital_admissions] = electiveadmtotal + emergencyadmtotal#(lf)#(tab),[number_of_MIU_attendances] = edonlymiutotal#(lf)#(tab),[number_of_OOH_appointments] = case when [number_of_OOH_appointments] is null then '0' else [number_of_OOH_appointments] END#(lf)#(tab)#(tab),[ObesityDerived]#(lf)    ,[SmokerDerived]#(lf)    ,[AsthmaDerived]#(lf)    ,[COPDDerived]#(lf)    ,[DementiaDerived]#(lf)    ,[DepressionDerived]#(lf)    ,[DiabetesDerived]#(lf)    ,[PalliativeCareDerived]#(lf)    ,[ChronicKidneyDiseaseDerived]#(lf)    ,[EpilepsyDerived]#(lf)    ,[HeartFailureDerived]#(lf)    ,[StrokeDerived]#(lf)    ,[AtrialFibrillationDerived]#(lf)    ,[CancerDerived]#(lf)    ,[CoronaryHeartDiseaseDerived]#(lf)    ,[HypertensionDerived]#(lf)    ,[HypothyroidismDerived]#(lf)    ,[LearningDisabilityDerived]#(lf)    ,[MentalIllnessDerived]#(lf)#(tab),Frailty_Type = CASE WHEN Frailty_Type IS NULL THEN 'No rockwood score recorded' else Frailty_Type END#(lf)#(lf)  FROM [BIReports].[MPI].[MPI_current] [M]#(lf)#(lf) #(lf)  LEFT JOIN #SWAST [S] ON [S].[Derived_Pseudo_NHSNumber] = [M].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #Rapid_Response [RR] ON [RR].[DerivedPseudoNHS] = [M].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #OOH [O] ON [O].[NHSNumber] = [M].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #rockwood [RW] ON [RW].[PseudoNHSNumber] = [M].[Derived_Pseudo_NHS]#(lf)#(lf)  ", CommandTimeout=#duration(41, 16, 0, 0)]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Derived_Age", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

