table 'Core20 Reference'
	lineageTag: a3d512ff-44c8-4f8a-b5de-ad96606d7088

	column 'Core20 description'
		dataType: string
		lineageTag: f9b20d3b-25b9-4ff8-be3a-1aa31632ce4e
		summarizeBy: none
		sourceColumn: Core20 description

		annotation SummarizationSetBy = Automatic

	column 'Core20 flag'
		dataType: int64
		formatString: 0
		lineageTag: b8bc96b4-88bb-4993-a0f2-4278593c95bd
		summarizeBy: none
		sourceColumn: Core20 flag

		annotation SummarizationSetBy = Automatic

	partition 'Core20 Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8ssvUXDOL0pVMDJQ0lEyUIrViVbyzEMSMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Core20 description" = _t, #"Core20 flag" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Core20 description", type text}, {"Core20 flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

