table 'Rockwood Frailty Reference'
	lineageTag: b99850d4-5cdb-4675-bc5a-236abb14c541

	column 'Frailty Status'
		dataType: string
		lineageTag: d310a30d-90f3-47bd-b332-78a709a6a2ad
		summarizeBy: none
		sourceColumn: Frailty Status
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: a372bd26-b54e-408c-bb99-d4037612221a
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Rockwood Frailty Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8stXKMpPzi7Pz09RKE7OL0pVKEoFUimpKUo6SqZKsTogJXm6bkWJmTlAEUOwiG9mDkjaCMLJT0ktSixJBQoYgwWCU8tSi0BcEzA3NC87L788D8g3U4qNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Frailty Status" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Frailty Status", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

