table date_table
	lineageTag: 9279430d-cc53-431d-b9c8-6825e4265501

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b4f50ec-a1c8-48a8-9f6d-1c42b8c6c7bf
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: c2f0bebb-9a0c-40e1-9df8-b893811fb861
			defaultHierarchy: LocalDateTable_fb86b470-4f5a-46d9-ac82-6e2307952d81.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: 80ba9e19-44f6-4c9f-986c-02b17c4de864
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: b163b590-3ee4-4f7d-b99f-0d53d270eec4
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 9c01977f-afde-4cee-a1e3-b4014c4ebe0c
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: e445cd6d-48be-4fb3-99c8-ede552ddbdc4
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 3c780e79-4edb-41fa-9113-b17753aa66cc
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: eb538693-753c-4299-b053-41821e04a94d
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: b30ef7eb-d3b1-4c74-a813-39129e7909f7
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 8d52bcb6-aa27-42b8-9755-a39b922a896e
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 0c1d31c7-a3ef-4c41-9d9c-8223961a261d
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 2c60dda0-05ce-4627-92dd-8ce6e34bc37c
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: b5de628d-b23e-4bfb-8d2a-5a2e2c33c810
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 5550225a-98bf-49bd-95cc-031eaeb4738d
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 0229824b-f9c4-407c-8f3e-2dcf455333b9
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 8a5a1bc7-82a7-4f01-9212-3c32f82c32d3
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_number =
			
			RANKX( ALL( 'date_table' ), 'date_table'[year_month], , ASC, Dense)
		formatString: 0
		lineageTag: 1ed908a3-ad67-4ae0-8bd4-3fad157646b7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Rolling_3_months
		dataType: int64
		formatString: 0
		lineageTag: 78c7170c-879d-444f-b7f6-0152f2876927
		summarizeBy: sum
		sourceColumn: Rolling_3_months

		annotation SummarizationSetBy = Automatic

	column Rolling_3_months_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 50b07d45-5349-4b24-9c30-b26edcf22892
		summarizeBy: none
		sourceColumn: Rolling_3_months_start_date

		variation Variation
			isDefault
			relationship: 3fe10e88-c6b6-4bb8-bb8a-3907ee102b50
			defaultHierarchy: LocalDateTable_94971b54-70f2-48bc-bb93-f73ddf16d664.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Rolling_3_months_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 582d7f69-0265-4088-9381-68680a0e5444
		summarizeBy: none
		sourceColumn: Rolling_3_months_end_date

		variation Variation
			isDefault
			relationship: ddf85aa2-98c3-47c1-9715-873bb560f976
			defaultHierarchy: LocalDateTable_7e91e12b-de09-4f5a-b822-2d8f7b0d612c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column First_Day_of_Month
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7a134c44-7462-463c-ae3f-48b5325173f7
		summarizeBy: none
		sourceColumn: First_Day_of_Month

		variation Variation
			isDefault
			relationship: 5c41887f-e3a6-4222-9ee0-db4fbdf3ab1c
			defaultHierarchy: LocalDateTable_dfc00bd5-2af8-4d9d-8b4b-841c565cec17.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Latest_Reporting_Month_up_to_flag
		dataType: int64
		formatString: 0
		lineageTag: 77717ccd-ac16-46c2-af4f-cfc95181633d
		summarizeBy: sum
		sourceColumn: Latest_Reporting_Month_up_to_flag

		annotation SummarizationSetBy = Automatic

	partition date_table-eeea32ab-ab3a-4823-99b3-a1040d4050ac = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="#(lf)---First part to obtain the date the report should go up to. Subject to data availability#(lf)#(lf)if object_id('tempdb..#date_end_ref') is not null#(lf)drop table #date_end_ref#(lf)#(lf)#(lf)set nocount on#(lf)#(lf)select *#(lf)into #date_end_ref#(lf)from CCG_Reference.Reference.vw_DateLookup as d#(lf)where Date =  EOMONTH(DATEADD(MONTH, -2, cast(getdate() as date))) #(lf)#(lf)declare @end_date as date#(lf)set @end_date = (select date from #date_end_ref)#(lf)#(lf)#(lf)declare @end_date_reporting_month as int#(lf)set @end_date_reporting_month = (select FinancialMonth from #date_end_ref)#(lf)#(lf)#(lf)select [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)#(tab)  ,[First_Day_of_Month] =  cast(DATEADD(MONTH, DATEDIFF(MONTH, 0, date), 0)  as date)#(lf)      ,[Month] [month]#(lf)      ,LEFT([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)#(tab)  ,[Rolling_3_months] = case when [Date] between dateadd(day,1,eomonth(dateadd(month, -5, getdate()))) and eomonth(dateadd(month, -2, getdate())) then 1 else 0 END  ---This is used for cinapsis #(lf)      ,[Rolling_3_months_start_date] = dateadd(day,1,eomonth(dateadd(month, -5, getdate())))#(lf)#(tab)  ,[Rolling_3_months_end_date] = eomonth(dateadd(month, -2, getdate()))#(lf)#(tab)  ,[Latest_Reporting_Month_up_to_flag] = case when cast(FinancialMonth as int) between 1 and @end_date_reporting_month then 1 else 0 end #(lf)#(lf) from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] between '20190401'  and @end_date#(lf)#(lf)--and eomonth(dateadd(month, -2, getdate()))#(lf)#(lf)#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

