table 'CQC Rating Order'
	lineageTag: 813e633b-784c-4c9f-9b62-d5f1bebbf5a6

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 8d10fcfc-058f-425b-ab72-2b3ed8e8a25e
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'CQC Rating'
		dataType: string
		lineageTag: 67d8da81-6260-44a3-98af-e8d8bb5a3b55
		summarizeBy: none
		sourceColumn: CQC Rating
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'CQC Rating Order' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfIvLSkuScxLycxLV4rViVYyAoq55+engDnGQE5QamFpZlFqsUJmbkFRfllqbmpeCVjSBCjpmZeYApRPLEkFC5kChZRiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Order = _t, #"CQC Rating" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Order", Int64.Type}, {"CQC Rating", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

