table 'Day of Week'
	lineageTag: a38f03cd-aa1e-4b1e-bc19-bbcbba3aa132

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 5e7ca833-9cb5-49fe-9b8d-782262c01234
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: 6c2ac861-c3f3-4d43-a1a4-4e5186796917
		summarizeBy: none
		sourceColumn: Day of Week
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Day of Week' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfLNz0tJrFSK1YlWMgJyQ0pTi2F8YyA/PDUlDyFiAlKRUVoEFzAFCrgVZcK4ZkBucGJJaRFMwBwkUAqxIRYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Order = _t, #"Day of Week" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Order", Int64.Type}, {"Day of Week", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

