table 'Hour of Day'
	lineageTag: 42e7cf10-0998-42d9-a628-12da8b41741b

	column 'Hour of Call'
		dataType: dateTime
		formatString: Short Time
		lineageTag: 552b0949-28c0-40bf-8ca9-0ff46b3759e5
		summarizeBy: none
		sourceColumn: Hour of Call
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 011363da-6d91-4c18-ad46-14d4c22b5b07
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Hour of Day' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("NdC5DcRAEAPBXMaWsaT+S2Wh/NPQYZoy22KBc9b4jVFLqZ5llgh3mFg7VmLr2Ii9YyeOjoM4O07i6riIu+PO6GD1MwQRhWAoDgFRJIKiWARG0QiO4hEgRSRIikmgFJVROSqj8vdNzonKqByV/6rnBQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Hour of Call" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Hour of Call", type text}, {"Order", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Hour of Call", type time}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

