table 'LSOA Reference'
	lineageTag: 5d37c008-1ded-4b21-9f13-9c304f28e2ef

	column FID
		dataType: int64
		formatString: 0
		lineageTag: 7f4d7f77-893a-47aa-8bdb-c061dee012cc
		summarizeBy: count
		sourceColumn: FID

		annotation SummarizationSetBy = Automatic

	column lsoa11cd
		dataType: string
		lineageTag: 4ee8c5b9-f21f-4665-a4c3-e50f7d75f594
		summarizeBy: none
		sourceColumn: lsoa11cd

		annotation SummarizationSetBy = Automatic

	column lsoa11nm
		dataType: string
		lineageTag: 59ab1a67-d45d-4cb1-a77f-02bf47934004
		summarizeBy: none
		sourceColumn: lsoa11nm

		annotation SummarizationSetBy = Automatic

	column IMDRank
		dataType: int64
		formatString: 0
		lineageTag: 27d91aff-9648-4077-a6f0-5c8cbb6f597e
		summarizeBy: sum
		sourceColumn: IMDRank

		annotation SummarizationSetBy = Automatic

	column IMDDecil
		dataType: int64
		formatString: 0
		lineageTag: 024d1ba5-85c0-4279-b950-06172503e0b3
		summarizeBy: sum
		sourceColumn: IMDDecil

		annotation SummarizationSetBy = Automatic

	column Shape__Area
		dataType: double
		lineageTag: f288e172-4143-4bc5-a4dc-a39997026233
		summarizeBy: sum
		sourceColumn: Shape__Area

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Shape__Length
		dataType: double
		lineageTag: dd75e5cf-e304-4b2e-b135-c78ce8ad3293
		summarizeBy: sum
		sourceColumn: Shape__Length

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column District
		dataType: string
		lineageTag: e70cfb95-068c-4a2f-a995-fb19ba5af871
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column Formula
		dataType: string
		lineageTag: 656c5b09-a676-4373-b311-2b3660386000
		summarizeBy: none
		sourceColumn: Formula

		annotation SummarizationSetBy = Automatic

	partition 'LSOA Reference-10dc03ae-29f2-4132-a6e5-f1ad5a43b068' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("M:\Info\Projects\Power BI\Map Shape Files\Lower_Super_Output_Area_(LSOA)_IMD2019__(WGS84).csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"FID", Int64.Type}, {"lsoa11cd", type text}, {"lsoa11nm", type text}, {"IMDRank", Int64.Type}, {"IMDDecil", Int64.Type}, {"Shape__Area", type number}, {"Shape__Length", type number}, {"District", type text}, {"Formula", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

