table 'Date Reference'
	lineageTag: 8bc0fae2-6712-486b-a7e3-11be5375a381

	measure 'Refreshed date' = TODAY()
		formatString: General Date
		lineageTag: 69549729-1da2-46ac-b1ba-664b5290cd7f

	measure Max_Date = MAX('Date Reference'[date])
		formatString: General Date
		lineageTag: d5fd86e2-5af1-4b66-bc0a-eae23a74d23f

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c5694347-3a3a-463e-a20d-10dbcc464802
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 7b3f4d30-4cd5-4f16-aaea-a316839615cb
			defaultHierarchy: LocalDateTable_b6704bf3-bf76-477c-9058-5df98bc06964.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: cc1d22e5-d5ad-4f3f-95ed-3b6586e4d978
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: d8644d28-86f5-4c7b-84ec-8184cb7f6811
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 3c2c79e8-a89c-496f-8956-6abcd49fdc9b
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 73e1d15d-56b0-43fe-99ce-b175c6a68a48
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 71c3f824-4995-4127-9bc1-4c53e2617cc1
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 87e7f333-6c76-4b97-8a22-7ccc09bd910c
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 86c08805-01d4-4796-9603-f2a905ad9a3d
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: cbd19188-5242-4dc7-9959-b71e64eefd8c
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 461abf2c-fc05-4012-823b-b0ce14b4e78d
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1af006c0-4c85-4660-9fd1-5e2ba70acb39
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c7b6a76d-0803-451e-a8ab-8c55f20f2d14
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: a4664428-74ab-46d3-b0c2-2a09ee4c14ef
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 5b1eea0e-5626-41c7-b3fb-bb88ec6e1b98
		summarizeBy: none
		sourceColumn: financial_year
		sortByColumn: Financial_year_order_column

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 50fc86ae-d7a1-4bd7-9b1c-38f8c0535e6f
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: ba81fdd2-c947-43e7-a835-e6341f17d483
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: df777d25-2b6d-4edf-9b7b-b315b71aa92c
		summarizeBy: none
		sourceColumn: month_year_name
		sortByColumn: year_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 260b8221-a8f6-4836-bb9c-032799e4f563
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column ytd_description
		dataType: string
		lineageTag: 6bd96429-c869-4faf-ad8a-e9ff3cd6e0f5
		summarizeBy: none
		sourceColumn: ytd_description

		annotation SummarizationSetBy = Automatic

	column Current_FY
		dataType: string
		lineageTag: 62bea876-05c6-4227-9317-49d1ae8a01f5
		summarizeBy: none
		sourceColumn: Current_FY

		annotation SummarizationSetBy = Automatic

	column Last_FY
		dataType: string
		lineageTag: ea9dd762-ba29-4c76-b472-2f34071034cd
		summarizeBy: none
		sourceColumn: Last_FY

		annotation SummarizationSetBy = Automatic

	column Current_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: 7f5a9205-b249-4c78-9cad-0236e14a9853
		summarizeBy: sum
		sourceColumn: Current_FY_Flag

		annotation SummarizationSetBy = Automatic

	column Last_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: 880e58a4-fdd1-4575-9a80-9289c9ae635c
		summarizeBy: sum
		sourceColumn: Last_FY_Flag

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 61799b9b-13b9-4e8b-b523-b4c06fdfe752
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column 'Max Local Dementia Data Date' = max('Practice Population'[dementia_date_one_month_prior])
		formatString: General Date
		lineageTag: c839e861-c742-4d8b-b3eb-43d9b3bb1026
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 1767bcfe-d844-4c44-beb0-bc29fc2cc263
			defaultHierarchy: LocalDateTable_2866f7fc-e5bf-403a-9a65-5a5899f3109e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: ab053b73-ac07-465d-af88-ac6003fd5ff8
		summarizeBy: none
		sourceColumn: LastDateofMonth

		variation Variation
			isDefault
			relationship: d2440174-2aaa-401c-aba8-9110bef3c28e
			defaultHierarchy: LocalDateTable_91b0b27a-4543-412c-820b-5d2dcddabc2f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Local data latest month flag' = IF('Date Reference'[LastDateofMonth] = 'Date Reference'[Max Local Dementia Data Date], 1, 0)
		formatString: 0
		lineageTag: 08e1ff09-2c9d-4d51-bea0-d55e3d1e6011
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Prior Month Max Local Dementia Data Date' = EOMONTH('Date Reference'[Max Local Dementia Data Date], -1)
		formatString: General Date
		lineageTag: 05516ce7-8126-47a3-b3fb-957d4218cb66
		summarizeBy: none

		variation Variation
			isDefault
			relationship: ec7eb47a-b492-489b-876a-8044317f465b
			defaultHierarchy: LocalDateTable_e8b64353-12fa-4381-ab40-147b27fc3ad1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Local data prior month flag' = IF('Date Reference'[LastDateofMonth] = 'Date Reference'[Prior Month Max Local Dementia Data Date], 1, 0)
		formatString: 0
		lineageTag: 48db14b0-6617-4f50-90f6-4799148b8969
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Financial_year_order_column
		dataType: int64
		formatString: 0
		lineageTag: e46d9017-6eb8-4df2-bd79-1807ce8759f0
		summarizeBy: sum
		sourceColumn: Financial_year_order_column

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Max data date' = MAX('New DDR'[ACH_DATE])
		formatString: mmmm yyyy
		lineageTag: ec83371a-f816-45ea-ace3-526a2f79517e
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 6a382beb-9896-41c6-afed-7edda983d800
			defaultHierarchy: LocalDateTable_11ad77ec-8757-4a83-9e96-4e08f2387f7a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Max MAS Date Flag' =
			
			
			VAR max_date = MAX('New Waiting List Table'[ReferralRequestReceivedDate])
			
			RETURN IF('Date Reference'[date] > max_date, "After max MAS date", "Before max MAS date")
		lineageTag: bc6576f1-6418-41fd-99ce-f9035c39f4ac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Day Counter' = 1
		formatString: 0
		lineageTag: 9a3d68ca-412f-45a4-bcff-3ce429d301f0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'financial_year Hierarchy'
		lineageTag: 1c4f5ead-ddec-4a87-b1e5-963117e86544

		level financial_year
			lineageTag: 8c8f510e-fbf0-451c-93ac-e97988ac22f7
			column: financial_year

		level month_name
			lineageTag: f97dbb71-401c-4f66-8bd5-a4616c1b3e66
			column: month_name

	partition 'Date Reference' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="#(lf)#(lf)SET ANSI_WARNINGS OFF#(lf)SET NOCOUNT ON#(lf)if object_id ('tempdb..#FY_flag') is not null drop table #FY_flag#(lf)#(lf)SELECT distinct#(lf)#(lf)[Financial_year_abridged] = SUBSTRING([FinancialYear], 1, 4)#(lf)#(lf),[Current_FY] = case when cast(getdate() as date) = date then FinancialYear END#(lf),financialyear#(lf)#(lf)INTO #FY_flag #(lf)#(lf)FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)#(lf)ORDER BY FinancialYear#(lf)#(lf)if object_id ('tempdb..#FY_flag_2') is not null drop table #FY_flag_2#(lf)#(lf)SELECT #(lf)#(lf)[Financial_year_abridged] #(lf),[Current_FY] #(lf),financialyear#(lf),[Last_FY]#(lf)#(lf)INTO #FY_flag_2#(lf)#(lf)FROM #FY_flag#(lf)#(lf)LEFT JOIN#(lf)(SELECT DISTINCT#(lf)[FY_abridged] = SUBSTRING([FinancialYear], 1, 4)#(lf),[Last_FY] = financialyear#(lf)FROM [CCG_Reference].[Reference].[vw_DateLookup]) AS [B] ON [FY_abridged] = [Financial_year_abridged] - 1#(lf)#(lf)WHERE [Current_FY] IS NOT NULL#(lf)#(lf)ORDER BY financialyear#(lf)#(lf)#(lf)SELECT [Date] [date]#(lf)#(tab)  ,[month_number] = DENSE_RANK() over(order by [YearMonth])#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[A].[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      ,[MonthYearName] [month_year_name]#(lf)#(lf)      ,[ytd_flag] = CASE WHEN [FinancialMonth] <= (#(lf)                                           SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)                                           WHERE [Date] = EOMONTH(DATEADD(MONTH, -2, GETDATE()))#(lf)                                           )#(lf)                                           THEN 1 ELSE 0 END#(lf)#(tab)      ,[ytd_description] = CASE WHEN [FinancialMonth] <= (#(lf)                                           SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)                                           WHERE [Date] = EOMONTH(DATEADD(MONTH, -2, GETDATE()))#(lf)                                           )#(lf)                                           THEN 'Year to Date' ELSE '' END#(lf)#(tab),[B].[Current_FY]#(lf)#(tab),[C].[Last_FY]#(lf)#(tab),[Current_FY_Flag] = case when [B].[Current_FY] = [A].[FinancialYear] then 1 else 0 END#(lf)#(tab),[Last_FY_Flag] = case when [C].[Last_FY] = [A].[FinancialYear] then 1 else 0 END#(lf)#(tab),[A].DateKey#(lf)#(tab),[A].LastDateofMonth#(lf)    ,[Financial_year_order_column] = LEFT(RIGHT([A].[FinancialYear], LEN([A].[FinancialYear]) - 2), 2)#(lf)#(lf)from [CCG_Reference].[Reference].[vw_DateLookup] [A]#(lf)#(lf)LEFT JOIN #FY_flag_2 [B] ON [A].[FinancialYear] = [B].[FinancialYear]#(lf)#(lf)LEFT JOIN #FY_flag_2 [C] ON [A].[FinancialYear] = [C].[Last_FY]#(lf)#(lf)where [Date] between '2021-04-01' and getdate()#(lf)#(lf)order by [Date] desc"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}, {"date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

