table 'YTD Reference'
	lineageTag: 936866fc-7f27-4c3b-839f-571f822ef76f

	column 'YTD Description'
		dataType: string
		lineageTag: af40ac01-d04c-4346-83ef-144a441a2e22
		summarizeBy: none
		sourceColumn: YTD Description

		annotation SummarizationSetBy = Automatic

	column 'YTD Flag'
		dataType: int64
		formatString: 0
		lineageTag: 62504ab2-5f8e-4d16-9546-3ab1ef381a35
		summarizeBy: sum
		sourceColumn: YTD Flag

		annotation SummarizationSetBy = Automatic

	partition 'YTD Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WikxNLFIoyVdwSSxJVdJRMlSK1YlW8ssvUUCTMFCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"YTD Description" = _t, #"YTD Flag" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"YTD Description", type text}, {"YTD Flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

