table 'Comparison Cohort'
	lineageTag: c093b782-8edc-43f3-9a83-4ad87c68e4d3

	measure '% MPI are Male' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Gender]),
				'Comparison Cohort'[Gender] IN { "M" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: eec68a3b-a77c-411b-b515-4bd8248302f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Children and Young People (0-17)' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Derived_Pseudo_NHS]),
				'Comparison Cohort'[AgeBand] IN { "Children and Young People (0-17)" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			
			```
		lineageTag: ea546ff1-f37b-45ad-90e7-185b13da4ca5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Core20' = ```
			
			CALCULATE(
				sum('Comparison Cohort'[Core20Flag])
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 5ea1f1ab-76d8-4bcb-bfaa-3c4462bd7e57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Female' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Gender]),
				'Comparison Cohort'[Gender] IN { "F" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 344ad3b2-2129-4350-9a00-b16739f46b4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Older Adults (65+)' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Derived_Pseudo_NHS]),
				'Comparison Cohort'[AgeBand] IN { "Older Adults (65+)" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 19a9b341-e254-4d59-9c72-196b8ea113d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MPI are Working Age Adults (18-64)' = ```
			
			CALCULATE(
				COUNT('Comparison Cohort'[Derived_Pseudo_NHS]),
				'Comparison Cohort'[AgeBand] IN { "Working Age Adults (18-64)" }
			) 
			/
			CALCULATE(
			    COUNT('Comparison Cohort'[Derived_Pseudo_NHS]))
			```
		lineageTag: 71f27413-b7d0-456e-b864-3c00db0ed69b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Age MPI' = AVERAGE('Comparison Cohort'[Derived_Age])
		lineageTag: 4cb46daf-0abd-4f9b-86ee-988d997fb50c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: a0554ba8-8b30-4014-bf08-d6f1e8883e4f
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 170bbc9b-f681-4840-81ee-b0134b00eb99
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Derived_Age
		dataType: int64
		formatString: 0
		lineageTag: b55954e1-ee99-4942-b387-8f50240800d6
		summarizeBy: none
		sourceColumn: Derived_Age

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: fbb5377f-c467-4918-a069-d4298a402637
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column EthnicOriginDescription
		dataType: string
		lineageTag: d8755482-1297-4faa-8179-f7d739dceb04
		summarizeBy: none
		sourceColumn: EthnicOriginDescription

		annotation SummarizationSetBy = Automatic

	column PracNameCurrent
		dataType: string
		lineageTag: 4dbe6748-178a-4975-ba78-b464cc541444
		summarizeBy: none
		sourceColumn: PracNameCurrent

		annotation SummarizationSetBy = Automatic

	column Core20Flag
		dataType: int64
		formatString: 0
		lineageTag: 0424bccf-8d29-4f1e-ae64-06c17199a758
		summarizeBy: none
		sourceColumn: Core20Flag

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: caeeeb54-4dba-4ec6-93ba-55c1ccfa82e1
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column Number_of_ED_attendances
		dataType: int64
		formatString: 0
		lineageTag: 0b2decbb-3ec8-40bf-836a-ab903e33939c
		summarizeBy: sum
		sourceColumn: Number_of_ED_attendances

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: double
		lineageTag: 3da4cd82-3bae-43ba-a412-eeb7ff2e3565
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column number_of_PC_appointments
		dataType: int64
		formatString: 0
		lineageTag: c7aa0d82-3203-4c3b-9c21-a26082977e62
		summarizeBy: sum
		sourceColumn: number_of_PC_appointments

		annotation SummarizationSetBy = Automatic

	column number_of_SWAST_calls
		dataType: int64
		formatString: 0
		lineageTag: 166b1b6a-cc37-4ea2-9f39-d07ff2399f5e
		summarizeBy: sum
		sourceColumn: number_of_SWAST_calls

		annotation SummarizationSetBy = Automatic

	column number_of_111_calls
		dataType: int64
		formatString: 0
		lineageTag: 3b77666a-994f-491e-86c3-eb0af71a17de
		summarizeBy: sum
		sourceColumn: number_of_111_calls

		annotation SummarizationSetBy = Automatic

	column number_of_rapid_response
		dataType: int64
		formatString: 0
		lineageTag: f06399d5-57d9-455b-86b1-24d4c0774dfb
		summarizeBy: sum
		sourceColumn: number_of_rapid_response

		annotation SummarizationSetBy = Automatic

	column number_of_hospital_admissions
		dataType: int64
		formatString: 0
		lineageTag: 66042d74-cb35-4666-9e4b-74db8dd64d71
		summarizeBy: sum
		sourceColumn: number_of_hospital_admissions

		annotation SummarizationSetBy = Automatic

	column number_of_MIU_attendances
		dataType: int64
		formatString: 0
		lineageTag: c907a634-f1c4-4c2b-ad2c-7737d999352b
		summarizeBy: sum
		sourceColumn: number_of_MIU_attendances

		annotation SummarizationSetBy = Automatic

	column number_of_OOH_appointments
		dataType: int64
		formatString: 0
		lineageTag: a19ef451-7c11-4c6d-a7d2-d8af253df6db
		summarizeBy: sum
		sourceColumn: number_of_OOH_appointments

		annotation SummarizationSetBy = Automatic

	partition 'Comparison Cohort' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "BIReports", [Query="/****** Script for SelectTopNRows command from SSMS  ******/#(lf)SET NOCOUNT ON#(lf)IF OBJECT_ID ('TEMPDB..#ED_attendances') IS NOT NULL DROP TABLE #ED_attendances#(lf)#(lf)SELECT #(lf)#(tab)[Number_of_ED_attendances] = sum(1),#(lf)#(tab)nhs_number#(lf)#(tab)#(lf)  INTO #ED_attendances#(lf)#(lf)  FROM [PowerBI_Reporting].[dbo].[ECDS_ED_Attendances]#(lf)#(lf)  where Arrival_Date >= '2022-09-01'#(lf)#(lf)  and provider_code like 'RTE'#(lf)#(lf)  GROUP BY nhs_number#(lf)#(lf)  ------------------#(lf)  --PC Appointments#(lf)  ------------------#(lf)#(lf)  IF OBJECT_ID ('TEMPDB..#PC_attendances') IS NOT NULL DROP TABLE #PC_attendances#(lf)#(lf)SELECT #(lf)#(lf)[Pseudo_NHS_Number]#(lf)#(lf),[number_of_PC_appointments] = sum(1)#(lf)#(lf)  INTO #PC_attendances#(lf)#(lf)  FROM [CCG_Current].[PrimaryCare].[vw_Appointments]#(lf)#(lf)  where #(lf)#(lf)#(tab)Appointment_Date >= '2022-09-01'#(lf)#(lf)  group by [Pseudo_NHS_Number]#(lf)#(lf)  ------------------#(lf)  --111 Calls#(lf)  ------------------#(lf)#(lf)    #(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#one') IS NOT NULL DROP TABLE #one#(lf)#(lf)#(tab)SELECT#(lf)#(tab)[PseudoNHSNumber]#(lf)#(tab),[number_of_111_calls] = SUM(1)#(lf)#(lf)#(tab)INTO #one#(lf)#(lf)#(tab)FROM [CCG_Current].[CareUK].[vw_111]#(lf)#(lf)#(tab)WHERE [DateOfCase] >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [PseudoNHSNumber]#(lf)#(lf)#(lf)  ------------------#(lf)  --SWAST Calls#(lf)  ------------------#(lf)#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#SWAST') IS NOT NULL DROP TABLE #SWAST#(lf)#(lf)#(tab)SELECT#(lf)#(tab)[Derived_Pseudo_NHSNumber]#(lf)#(tab),[number_of_SWAST_calls] = sum(1)#(lf)#(lf)#(tab)INTO #SWAST#(lf)#(lf)#(tab)FROM [CCG_Current].[SWASFT].[vw_AmbulanceServicePatient]#(lf)#(lf)#(tab)WHERE [Time_Of_Incident] >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [Derived_Pseudo_NHSNumber]#(lf)#(lf)  ------------------#(lf)  --MIU Attendances#(lf)  ------------------#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID('tempdb..#MIU_Attendances') is not null#(lf)#(tab)drop table #MIU_Attendances#(lf)#(lf)#(tab)SELECT #(lf)#(tab)[M].[nhs_number]#(lf)#(tab),[number_of_MIU_attendances] = SUM(1)#(lf)#(lf)#(tab)into #MIU_Attendances#(lf)#(tab)FROM [PowerBI_Reporting].[dbo].[ECDS_ED_Attendances] [M]#(lf)#(lf)#(tab)where [M].department_type = 'Minor Injury Unit'#(lf)#(tab)and code_of_commissioner = '11M'#(lf)#(tab)and arrival_date >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [M].[nhs_number]#(lf)#(lf)#(lf)#(tab)------------------#(lf)#(tab)--Rapid Response#(lf)#(tab)------------------#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#Rapid_Response') IS NOT NULL DROP TABLE #Rapid_Response#(lf)#(lf)#(tab)SELECT#(lf)#(tab)[R].[DerivedPseudoNHS]#(lf)#(tab),[number_of_rapid_response] = sum(1)#(lf)#(lf)#(tab)INTO #Rapid_Response#(lf)#(lf)#(tab)FROM [CCG_Current].[CSDS].[vw_301_Referral] as r#(lf) #(lf)#(tab)LEFT JOIN CCG_Reference.GHC.vw_Hierarchy as h on r.Current_CostCentre = H.Cost_Centre#(lf)#(lf)#(tab)WHERE OrgIDProvider in ('R1J','RTQ')#(lf)#(lf)#(tab)AND [ReferralRequestReceivedDate] >= '2022-09-01'#(lf)#(tab)#(lf)#(tab)AND h.Cost_Centre in ('G15503', --Rapid Response#(lf)#(tab)'G15503a', --Rapid Response - RR - ENDNS#(lf)#(tab)'G15503b')--Rapid Response - RR - District Nursing#(lf)#(tab)#(tab)#(lf)#(tab)AND [ReferralRequestReceivedDate] >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [DerivedPseudoNHS]#(lf)#(lf)#(tab)------------------#(lf)#(tab)--Hospital admissions#(lf)#(tab)------------------#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#hospital') IS NOT NULL DROP TABLE #hospital#(lf)#(lf)#(tab)SELECT#(lf)#(tab)[H].[Derived_Pseudo_NHS]#(lf)#(tab),[number_of_hospital_admissions] = sum(1)#(lf)#(lf)#(tab)INTO #hospital#(lf)#(lf)#(tab)FROM [CCG_Current].[SEM].vw_HospitalProviderSpell [H]#(lf)#(lf)#(tab)WHERE [DischargeDate_FromHospitalProviderSpell] >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [Derived_Pseudo_NHS]#(lf)#(lf)#(tab)------------------#(lf)#(tab)--OOH#(lf)#(tab)------------------#(lf)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID('tempdb..#OOH') is not null drop table #OOH#(lf)#(lf)#(tab)SELECT #(lf)#(tab)[nhsnumber]#(lf)#(tab),[number_of_OOH_appointments] = SUM(1)#(lf)#(lf)#(tab)into #OOH#(lf)#(tab)FROM [CCG_Current].[CareUK].[vw_OutOfHours]#(lf)#(lf)#(tab)where ReceivedDateTime >= '2022-09-01'#(lf)#(lf)#(tab)GROUP BY [nhsnumber]#(lf)#(lf)#(tab)---------------------#(lf)#(tab)--Combined table#(lf)#(tab)---------------------#(lf)#(lf)SELECT #(lf)#(tab)[counter] = 1#(lf)#(tab),Core20Flag#(lf)#(tab),[m].[Derived_Pseudo_NHS]#(lf)#(tab),AgeBand#(lf)#(tab),EthnicOriginDescription#(lf)#(tab),Gender#(lf)#(tab),PracNameCurrent#(lf)#(tab),Derived_Age#(lf)#(tab),IMDcountyDecile#(lf)#(tab),[Number_of_ED_attendances] = case when [Number_of_ED_attendances] is null then 0 else [Number_of_ED_attendances] END#(lf)#(tab),[number_of_PC_appointments] = case when [number_of_PC_appointments] is null then '0' else [number_of_PC_appointments] END#(lf)#(tab),[number_of_SWAST_calls] = case when [number_of_SWAST_calls] is null then '0' else [number_of_SWAST_calls] END#(lf)#(tab),[number_of_111_calls] = case when [number_of_111_calls] is null then '0' else [number_of_111_calls] END#(lf)#(tab),[number_of_rapid_response] = case when [number_of_rapid_response] is null then '0' else [number_of_rapid_response] END#(lf)#(tab),[number_of_hospital_admissions] = case when [number_of_hospital_admissions] is null then '0' else [number_of_hospital_admissions] END#(lf)#(tab),[number_of_MIU_attendances] = case when [number_of_MIU_attendances] is null then '0' else [number_of_MIU_attendances] END#(lf)#(tab),[number_of_OOH_appointments] = case when [number_of_OOH_appointments] is null then '0' else [number_of_OOH_appointments] END#(lf)#(lf)#(lf)  FROM [BIReports].[MPI].[MPI_current] [M]#(lf)#(lf)  LEFT JOIN #ED_attendances [E] on [E].nhs_number = [m].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #PC_attendances [P] ON [P].[Pseudo_NHS_Number] = [m].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #SWAST [S] ON [S].[Derived_Pseudo_NHSNumber] = [m].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #one [One] ON [One].[PseudoNHSNumber] = [m].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #Rapid_Response [RR] ON [RR].[DerivedPseudoNHS] = [m].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #hospital [H] ON [H].[Derived_Pseudo_NHS] = [m].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #MIU_Attendances [MI] ON [MI].[nhs_number] = [m].[Derived_Pseudo_NHS]#(lf)  LEFT JOIN #OOH [O] ON [O].[NHSNumber] = [m].[Derived_Pseudo_NHS]#(lf)#(lf)  "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Derived_Age", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

