table Table
	lineageTag: 22aafde2-abc5-48ab-ad1a-e51dfde31a86

	column 'Weeks Waiting Banding'
		dataType: string
		lineageTag: 9e9292c5-9d22-4ed8-a9f5-b77b6f52a102
		summarizeBy: none
		sourceColumn: Weeks Waiting Banding
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: b933de69-0729-426e-9d69-a200adab50c7
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Rc4xDoAgDIXhqzRdZShQwJs4AJNhcjTeX1LJc/2/pK+1slB7ROJJfqdjjOtmx567qzzDopBBwWiGRSqgaKQ4SCnA1GyGZeUfS0YFY14Ulr9HRDekwr2/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Weeks Waiting Banding" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Weeks Waiting Banding", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

