table Grouping_Reference
	lineageTag: 38fcfd86-94b7-4f8a-a8e7-4689f92ae796

	column Grouped_Name
		dataType: string
		lineageTag: 2b07daba-e637-4890-8527-8b37646b3387
		summarizeBy: none
		sourceColumn: Grouped_Name

		annotation SummarizationSetBy = Automatic

	column Old_Metric_Name
		dataType: string
		lineageTag: cfcb6f66-b644-456a-80d1-76d2a12c2182
		summarizeBy: none
		sourceColumn: Old_Metric_Name

		annotation SummarizationSetBy = Automatic

	column New_Grouping
		dataType: string
		lineageTag: eb1bd4ad-cdc7-42e6-85da-449b23619c18
		summarizeBy: none
		sourceColumn: New_Grouping

		annotation SummarizationSetBy = Automatic

	column New_Metric_Name
		dataType: string
		lineageTag: 010638c8-0259-4448-bce6-13e78cbb4b8b
		summarizeBy: none
		sourceColumn: New_Metric_Name

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: f42bd314-433e-4108-b77f-32148c1dba63
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column Data_Date
		dataType: string
		lineageTag: 7e05ebea-084b-4dbb-8b84-83645c8a213e
		summarizeBy: none
		sourceColumn: Data_Date

		annotation SummarizationSetBy = Automatic

	column Explanation
		dataType: string
		lineageTag: f620c63c-2f94-439a-9c42-7cc69497766d
		summarizeBy: none
		sourceColumn: Explanation

		annotation SummarizationSetBy = Automatic

	column Link_to_Data
		dataType: string
		lineageTag: 5483ffeb-88ef-469d-9d1c-373d235175d2
		summarizeBy: none
		sourceColumn: Link_to_Data

		annotation SummarizationSetBy = Automatic

	column Contact
		dataType: string
		lineageTag: e15aca1b-f3c6-4dda-a9f6-75c265052e39
		summarizeBy: none
		sourceColumn: Contact

		annotation SummarizationSetBy = Automatic

	partition Grouping_Reference = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\Projects\Primary Care Data\PCARP\PCARP Report - Backing Data.xlsx"), null, true),
				    Grouping_Reference_Sheet = Source{[Item="Grouping_Reference",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Grouping_Reference_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Grouped_Name", type text}, {"New_Metric_Name", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

