table Death_Date
	lineageTag: f3720a45-800d-46de-9891-f81b231955e0

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 085dfea1-4d30-4ecd-abe9-3bd5029d6ca1
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 01e9eed5-707a-41a1-8ab7-e65825e656cc
			defaultHierarchy: LocalDateTable_e512c564-4d08-4751-93b7-0d3d5b7a6bc9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9620226b-21a8-4e07-8261-4eca1063cfe6
		summarizeBy: none
		sourceColumn: day_month_year

		variation Variation
			isDefault
			relationship: 4974009a-0709-49d6-b665-5ccf44a5d7cd
			defaultHierarchy: LocalDateTable_36e90fe3-ef4e-4115-8e5e-4db13fca2f29.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: f6579ef8-c3e5-4420-9986-1a01c5efa06a
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 991dd13d-15f7-4af2-8b6e-af2ee36c450c
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 24ac201e-e877-42a1-a347-ed283c2842f1
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: bb5bab4f-c884-43a9-bf8b-95ca39c36950
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: f45e1b9f-9e5a-4694-a445-760f76ab07fe
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 0a679354-3baa-4c37-90c6-c65da21afaf1
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 052194b2-f112-4183-8776-b513a936c64f
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 9249080a-5133-46a9-a704-933fc15d11e3
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: a8423ea7-9f46-4da1-888b-21f1cfbb75f1
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 59bf2457-c3a1-4bb6-b95c-ac54d45117d8
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: f5a6f9c3-2a82-4e1a-bec8-c715baeb0901
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 8f00a310-8c8e-4930-ae53-1e07bf9fe636
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 406937d7-d7b7-40d8-9856-f40615c48fad
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 6dfbb889-70f3-4abb-8b55-65526b8e4040
		summarizeBy: none
		sourceColumn: month_year_name
		sortByColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 4241f635-f8a0-4f75-b946-4d82d4a28ea1
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	partition Death_Date-a843c7a3-2b2f-4142-92cc-ae6c02a71a66 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="SELECT [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      ,[MonthYearName] [month_year_name]#(lf)      ,[ytd_flag] = CASE WHEN [FinancialMonth] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Date] = EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END#(lf)#(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] BETWEEN '20160401' AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"financial_year", "Financial Year"}, {"month_name", "Month Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

