table EOL_Query
	lineageTag: eb0dc010-3c68-45de-8ae1-f4dbe40fcd62

	measure 'Small Number Suppression Line Chart' = IF(COUNT(EOL_Query[pseudo_nhs_number])<6,0,COUNT(EOL_Query[pseudo_nhs_number]))
		lineageTag: e3c57ac2-eacf-4e5e-a3c9-b3413b640fd0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pseudo_nhs_number
		dataType: string
		lineageTag: 5055346b-c727-4e0a-be36-b4c2425867dd
		summarizeBy: none
		sourceColumn: pseudo_nhs_number

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 619c1306-3f9d-4537-b6e6-61140803fc88
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 793c54f2-faf5-40b3-98f4-b5f61bcd6661
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column district
		dataType: string
		lineageTag: 7ec63859-addf-401b-8c32-5207342182a6
		summarizeBy: none
		sourceColumn: district

		annotation SummarizationSetBy = Automatic

	column practice
		dataType: string
		lineageTag: 8b0d4eab-1445-41dc-8a58-dac91b1e39de
		summarizeBy: none
		sourceColumn: practice

		annotation SummarizationSetBy = Automatic

	column death_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 738ba6c8-7e2a-4010-b6b8-0647670e1f06
		summarizeBy: none
		sourceColumn: death_date

		annotation SummarizationSetBy = Automatic

	column death_flag
		dataType: string
		lineageTag: 2f105c0e-3a3b-447c-8ebb-84501939f69b
		summarizeBy: none
		sourceColumn: death_flag

		annotation SummarizationSetBy = Automatic

	column palliative_care_register_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b4fda30-13dc-44b9-88ff-cdcc2f098054
		summarizeBy: none
		sourceColumn: palliative_care_register_date

		annotation SummarizationSetBy = Automatic

	column palliative_care_flag
		dataType: string
		lineageTag: d764f04c-8256-4146-b10e-23ef09f3bbde
		summarizeBy: none
		sourceColumn: palliative_care_flag

		annotation SummarizationSetBy = Automatic

	column expected_death_flag
		dataType: string
		lineageTag: 551bdefe-4e08-490f-a4f2-3b6e1dc13760
		summarizeBy: none
		sourceColumn: expected_death_flag

		annotation SummarizationSetBy = Automatic

	column place_of_death
		dataType: string
		lineageTag: 45e8b3bf-e4f1-4635-9643-7874fc3c47fa
		summarizeBy: none
		sourceColumn: place_of_death

		annotation SummarizationSetBy = Automatic

	column preferred_place_of_death
		dataType: string
		lineageTag: 5f1a80cb-b0b4-4516-a440-eecda4e1b5bf
		summarizeBy: none
		sourceColumn: preferred_place_of_death

		annotation SummarizationSetBy = Automatic

	column died_in_preferred_place_of_death_flag
		dataType: string
		lineageTag: 13b14559-45b3-452f-a6b0-7efc31e0f3b7
		summarizeBy: none
		sourceColumn: died_in_preferred_place_of_death_flag

		annotation SummarizationSetBy = Automatic

	column >3_emergency_admissions_flag
		dataType: string
		lineageTag: ccc35d39-acfa-47d9-90ff-6278da3fa629
		summarizeBy: none
		sourceColumn: >3_emergency_admissions_flag

		annotation SummarizationSetBy = Automatic

	column days_in_hospital_grouping
		dataType: string
		lineageTag: 31570312-4c57-463d-a90e-17ff838025de
		summarizeBy: none
		sourceColumn: days_in_hospital_grouping

		annotation SummarizationSetBy = Automatic

	column respect_form_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7a3c7d9c-9996-422f-8afe-fdf2ba4cfc78
		summarizeBy: none
		sourceColumn: respect_form_date

		annotation SummarizationSetBy = Automatic

	column age_banding_5_year
		dataType: string
		lineageTag: 934255b6-d8fb-4201-ab7f-ee627ea81618
		summarizeBy: none
		sourceColumn: age_banding_5_year

		annotation SummarizationSetBy = Automatic

	column age_banding_10_year
		dataType: string
		lineageTag: 5a263104-c6ea-4027-a0df-7599ed5b7c1d
		summarizeBy: none
		sourceColumn: age_banding_10_year

		annotation SummarizationSetBy = Automatic

	column preferred_POD_Recorded_or_not
		dataType: string
		lineageTag: e5aedca1-85dd-4c49-8125-3a7ba5f95d90
		summarizeBy: none
		sourceColumn: preferred_POD_Recorded_or_not

		annotation SummarizationSetBy = Automatic

	column 'POD - Not Recorded'
		dataType: string
		lineageTag: 67b0a5d3-cbac-4e2c-a407-7b1fc8897e49
		summarizeBy: none
		sourceColumn: POD - Not Recorded

		annotation SummarizationSetBy = Automatic

	column 'POD - Recorded'
		dataType: string
		lineageTag: 8d90f90f-dd80-40a3-97e7-c168c92a06bd
		summarizeBy: none
		sourceColumn: POD - Recorded

		annotation SummarizationSetBy = Automatic

	column pcn
		dataType: string
		lineageTag: 86c26e65-e683-48d3-b642-9f7d6e402707
		summarizeBy: none
		sourceColumn: pcn

		annotation SummarizationSetBy = Automatic

	column ethnicity
		dataType: string
		lineageTag: 5c162b5c-8b14-49ac-aa69-e4aa1b9012ad
		summarizeBy: none
		sourceColumn: ethnicity

		annotation SummarizationSetBy = Automatic

	column deprivation
		dataType: string
		lineageTag: dd91e693-76d0-497c-bfee-208d05bede78
		summarizeBy: none
		sourceColumn: deprivation

		annotation SummarizationSetBy = Automatic

	column provider
		dataType: string
		lineageTag: 73ce2db9-d90e-43d7-b558-7790430810d4
		summarizeBy: none
		sourceColumn: provider

		annotation SummarizationSetBy = Automatic

	column dementia_flag
		dataType: string
		lineageTag: 303d4cdd-5fbc-47fc-9b1b-719c625450b2
		summarizeBy: none
		sourceColumn: dementia_flag

		annotation SummarizationSetBy = Automatic

	column frailty_score
		dataType: string
		lineageTag: 57c7dcb6-296e-447f-bc36-0f0deffa44ea
		summarizeBy: none
		sourceColumn: frailty_score

		annotation SummarizationSetBy = Automatic

	column number_of_ltc
		dataType: string
		lineageTag: d7c56a00-c62d-42bf-bff7-cf65eb89da8a
		summarizeBy: none
		sourceColumn: number_of_ltc

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: double
		lineageTag: a80580c3-923f-4988-9507-620b3b44c474
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column respect_form_flag
		dataType: string
		lineageTag: b9387c16-db12-49b3-8e2d-132b8b304675
		summarizeBy: none
		sourceColumn: respect_form_flag

		annotation SummarizationSetBy = Automatic

	column pcsp_flag
		dataType: string
		lineageTag: 750616d2-8bd4-49bb-882a-34f8f6aa8a92
		summarizeBy: none
		sourceColumn: pcsp_flag

		annotation SummarizationSetBy = Automatic

	column pcsp_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4defb27a-47f8-4342-9b70-905c55004935
		summarizeBy: none
		sourceColumn: pcsp_date

		annotation SummarizationSetBy = Automatic

	column preferred_place_of_death_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c81840b-25b5-47ab-89cf-d38c790f3e1c
		summarizeBy: none
		sourceColumn: preferred_place_of_death_date

		variation Variation
			isDefault
			relationship: 9975e64b-46bb-4d5f-b0e6-2f213e6da61d
			defaultHierarchy: LocalDateTable_9a23ae5e-eb75-4993-89f7-42bc5aee38bd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition EOL_Query-2ad0523c-5ed2-4688-8771-316479b3a6ac = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Reporting", [Query="SELECT *#(lf)FROM [PowerBI_Reporting].[dbo].[EOL_Report_Table]"]),
				    #"Duplicated Column" = Table.DuplicateColumn(Source, "preferred_place_of_death", "preferred_place_of_death - Copy"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column",null,"Not Recorded",Replacer.ReplaceValue,{"preferred_place_of_death - Copy"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Care Home","Recorded",Replacer.ReplaceText,{"preferred_place_of_death - Copy"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Home","Recorded",Replacer.ReplaceText,{"preferred_place_of_death - Copy"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Undecided","Recorded",Replacer.ReplaceText,{"preferred_place_of_death - Copy"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value3", each true),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"preferred_place_of_death - Copy", "preferred_POD_Recorded_or_not"}}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Renamed Columns","Declined Discussion","Recorded",Replacer.ReplaceText,{"preferred_POD_Recorded_or_not"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Discussion not appropriate","Recorded",Replacer.ReplaceText,{"preferred_POD_Recorded_or_not"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Hospice","Recorded",Replacer.ReplaceText,{"preferred_POD_Recorded_or_not"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Hospital","Recorded",Replacer.ReplaceText,{"preferred_POD_Recorded_or_not"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Usual Place","Recorded",Replacer.ReplaceText,{"preferred_POD_Recorded_or_not"}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Replaced Value8", "preferred_POD_Recorded_or_not", "preferred_POD_Recorded_or_not - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column1",{{"preferred_POD_Recorded_or_not - Copy", "POD - Not Recorded"}}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Renamed Columns1","Recorded","",Replacer.ReplaceValue,{"POD - Not Recorded"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value9", each true),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Filtered Rows1", "preferred_POD_Recorded_or_not", "preferred_POD_Recorded_or_not - Copy"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column2",{{"preferred_POD_Recorded_or_not - Copy", "POD - Recorded"}}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Renamed Columns2","Not Recorded","",Replacer.ReplaceValue,{"POD - Recorded"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","",null,Replacer.ReplaceValue,{"POD - Recorded"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","",null,Replacer.ReplaceValue,{"POD - Not Recorded"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12",">3 Admissions","≥3 Admissions",Replacer.ReplaceText,{">3_emergency_admissions_flag"})
				in
				    #"Replaced Value13"

	annotation PBI_ResultType = Table

