table Palliative_Date
	lineageTag: e16c608b-4303-4844-8f9d-cebaa470f76e

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5fff01bb-7bef-40f8-82b5-af6bf213fe43
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 4e1126e8-b31a-4e6d-bb1c-df277db9a51d
			defaultHierarchy: LocalDateTable_35aa957f-a6c3-40b9-aafb-d51cc60797a8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5ccd4d0c-8937-4547-94c7-1261345d212d
		summarizeBy: none
		sourceColumn: day_month_year

		variation Variation
			isDefault
			relationship: ad6b6f62-600c-4bd1-a9e2-985fae25fdde
			defaultHierarchy: LocalDateTable_0006efd7-2ce9-4161-bc95-42e0a020b30a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: 3afc0e8b-44ba-4d87-b2a3-78610822fab5
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 19708fe1-d96c-4f72-b9e4-f3692539f5d3
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: e5901e93-c709-43dd-ac49-db9cbc6913b6
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: e6495943-0104-4f19-a176-1ab225e740cf
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 6534f585-852a-476a-8b2d-58b431e3b0ec
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 9cf9f45b-f703-44a2-b155-0c95071c3093
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 1fc60e14-e45d-402e-927f-72563c980708
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 06be2e8d-cef2-4df2-aaeb-fd8f2d610aff
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 325877e6-603f-454a-9ca7-69b7ce52f090
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 058efec1-668e-4324-8396-0bf340619a16
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 9bb1af79-6847-4758-8930-72ccaa215e0a
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 3b5e1873-0bbd-4bc3-bb4e-f7543b04f1de
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 5e5b82e8-1185-42e2-94ac-28ad220c32a3
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 7a35b771-f24e-424d-a0be-c4c172b5bb7b
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: d69a44a2-ee8a-4689-b159-85016a1af8e3
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	partition Palliative_Date-4bf99b2c-a313-441b-a62c-4ac1380fc496 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="SELECT [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      ,[MonthYearName] [month_year_name]#(lf)      ,[ytd_flag] = CASE WHEN [FinancialMonth] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Date] = EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END#(lf)#(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] BETWEEN '20160401' AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

