table PCSP_Date
	lineageTag: 791e7160-26d4-4e49-a012-fa74f62d7944

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 84a214c0-10bb-4ed7-837c-42bff4947556
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 4b56b2cb-45aa-4d6b-9ba2-a93b381b2cf8
			defaultHierarchy: LocalDateTable_22f15389-c975-4888-9446-c81e932682b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0e9e7865-422b-41ba-97ae-8b0d47bf4b2c
		summarizeBy: none
		sourceColumn: day_month_year

		variation Variation
			isDefault
			relationship: 1f574058-3edc-4252-9f3f-0cfecec5e532
			defaultHierarchy: LocalDateTable_ee16da0d-5eb8-4b6a-9c60-a4f8aa00d3a5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: f5a66c60-0497-4647-9507-b1e0cc07fbe5
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: ab573ae3-d3a7-4ea3-a769-38b7aa9e6ef1
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 68dc95ea-d3b2-490e-8755-dce831a28334
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 53bd8e7e-f1e9-40da-ac39-8fee7792d43b
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: d1cc20d1-f654-4989-8e3f-8fe4aa255308
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 1f50e3b9-0d32-4f84-81a6-f82e4506f277
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 5c0c0e5e-ddee-42d2-ae18-b914d247a960
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: ee48681a-94ec-44df-8ecc-e27afd1afcc1
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 2166dbbf-9d5b-4400-a32a-d86affbc2192
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 9ddf97ab-3e5b-48b5-80e0-6e5a241fe752
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: ed51ca79-72c4-4c7a-a2ab-d98e52b8462b
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 7412e4c7-adda-4319-9e34-850b992edbc5
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 2d3f66fb-816a-4f87-ad80-f1c430c31960
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 7a2e7d0c-00ab-4f6d-a0e7-f12a8099acb2
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 3464d4a9-16a2-46f8-9666-fecd29de454d
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	partition PCSP_Date-a03124a4-06d4-492c-b5a4-6fcd95a97a9b = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="SELECT [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      ,[MonthYearName] [month_year_name]#(lf)      ,[ytd_flag] = CASE WHEN [FinancialMonth] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Date] = EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END#(lf)#(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] BETWEEN '20160401' AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

