table Respect_Form_Date
	lineageTag: 4c4e54ec-24da-49ef-8149-5f13d49dd2ac

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: bb02206b-b3cf-4e78-bc10-579a9b3233ac
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 0d8a8156-ebcd-4fa4-926b-f8b87eca107d
			defaultHierarchy: LocalDateTable_65be197c-587b-4325-860f-9862e727dc78.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34826b16-ce77-4e89-a8d1-164014cc9a96
		summarizeBy: none
		sourceColumn: day_month_year

		variation Variation
			isDefault
			relationship: 8d232980-952d-48db-8bdd-4af5118abc92
			defaultHierarchy: LocalDateTable_6f709ac0-9992-4e7f-8559-b63aaee90dc4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: 154c9171-ae10-4bd7-bd99-95c7c65b180b
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 7cf2d750-7578-4b26-8693-9d6c48800cd0
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 08641f65-1220-474f-b86f-097e2a1dfe25
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 14154293-9fd5-45c4-a07c-523d52857dca
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 0648c28e-680f-4685-8070-fbd3245106fc
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: f3202b74-9cb6-44e1-9656-1be810d4bc14
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 8acb4804-4c0b-4dcc-bfdd-71432d00a991
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 618e153e-e30c-4545-8065-6d627e0c3572
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 09375746-6df7-47b1-8b9a-156d3f7e5f55
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 0820b515-cffd-46e9-9fab-4caf32d5aee0
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: df585291-4388-4519-8b74-ebaec5913585
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 45b42f82-c6b3-47fb-a7d8-b5f374ab07d5
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: f2e04c21-cabd-4730-9ab4-6762674e4881
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 1f4a0c15-b29a-46b9-8f8b-80dbff39c8fe
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: cbeda214-3fd9-46ea-ab13-0ad34448be98
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	partition Respect_Form_Date-dc2b0a21-acb4-443d-bae3-11c4de374f2b = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="SELECT [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      ,[MonthYearName] [month_year_name]#(lf)      ,[ytd_flag] = CASE WHEN [FinancialMonth] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Date] = EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END#(lf)#(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] BETWEEN '20160401' AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

