table non_specific_symptoms
	lineageTag: 37a7c079-27a6-4d46-9acf-2072184bdac6

	column 'Month flag' = ```
			
			
			VAR max_month = CONCATENATE(YEAR(MAX('non_specific_symptoms'[appointment_date])),MONTH(MAX('non_specific_symptoms'[appointment_date])))
			VAR current_month = CONCATENATE(YEAR('non_specific_symptoms'[appointment_date]),MONTH('non_specific_symptoms'[appointment_date]))
			
			VAR prior_date = EOMONTH(max('non_specific_symptoms'[appointment_date]), -1)
			
			VAR prior_month = CONCATENATE(YEAR(prior_date),MONTH(prior_date))
			
			RETURN IF(max_month = current_month,"Current Month",if(prior_month = current_month, "Prior Month", "Other Month"))
			
			```
		lineageTag: 4799cbc6-ee8f-437c-abc2-1d7d684f66cf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column UBRN
		dataType: string
		lineageTag: bdd35ba4-765a-42a3-a4d1-0058f64965e2
		summarizeBy: none
		sourceColumn: UBRN

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 1da8040f-9d11-4e61-9b3e-913be34604aa
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: ff8c9724-44a4-4d8d-85db-37211498de0c
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 913d82a0-894c-46a0-bdd6-7afb94091f0f
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: b66ebb5b-c0be-454c-b9b4-1bc4aee5a1ce
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: a87799bc-ba59-4d17-9c98-1e6240cff5db
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 89a14144-7131-481c-b7ff-94cb6c7eb20a
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 64102f2c-f811-4278-9dfb-4ef7d8242bd6
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column Consultant_Led_Flag
		dataType: string
		lineageTag: 9e18b9dd-2228-4457-a6cd-0558387ec4ca
		summarizeBy: none
		sourceColumn: Consultant_Led_Flag

		annotation SummarizationSetBy = Automatic

	column Referral_Priority
		dataType: string
		lineageTag: e5459d2d-826f-431c-b81d-9c525d5446ac
		summarizeBy: none
		sourceColumn: Referral_Priority

		annotation SummarizationSetBy = Automatic

	column InitialReferral
		dataType: int64
		formatString: 0
		lineageTag: b75ad6d8-61c0-4c84-9b7f-67647da54a2a
		summarizeBy: sum
		sourceColumn: InitialReferral

		annotation SummarizationSetBy = Automatic

	column Initial_Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: af3f7c95-5663-4032-92b6-e2bf1050f7a5
		summarizeBy: sum
		sourceColumn: Initial_Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column InitialReferralDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a104844-1524-48e6-997e-f94fe0661c15
		summarizeBy: none
		sourceColumn: InitialReferralDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InitialReferralMonth
		dataType: string
		lineageTag: 502098dd-ad3e-4c01-b470-44fda5c959cb
		summarizeBy: none
		sourceColumn: InitialReferralMonth

		annotation SummarizationSetBy = Automatic

	column InitialReferralFinancialYear
		dataType: string
		lineageTag: 3cbd2843-9b03-46a0-bd59-2a50ea8faa2b
		summarizeBy: none
		sourceColumn: InitialReferralFinancialYear

		annotation SummarizationSetBy = Automatic

	column InitialReferralYearmonth
		dataType: string
		lineageTag: 2e007b53-2506-4537-a1f6-3be206eae6f6
		summarizeBy: none
		sourceColumn: InitialReferralYearmonth

		annotation SummarizationSetBy = Automatic

	column InitialReferralFinancialMonth
		dataType: string
		lineageTag: 786c077f-efa8-4589-ba18-52d8937e6be1
		summarizeBy: none
		sourceColumn: InitialReferralFinancialMonth

		annotation SummarizationSetBy = Automatic

	column Derived_MainSpecialtyCode
		dataType: string
		lineageTag: b117e447-e7ed-4cd9-aa90-b4b1cc7b2a4f
		summarizeBy: none
		sourceColumn: Derived_MainSpecialtyCode

		annotation SummarizationSetBy = Automatic

	column Derived_MainSpecialtyDescription
		dataType: string
		lineageTag: 431a41d1-9cc3-4d4f-b811-d79c9a091ad0
		summarizeBy: none
		sourceColumn: Derived_MainSpecialtyDescription

		annotation SummarizationSetBy = Automatic

	column Derived_TreatmentFunctionCode
		dataType: string
		lineageTag: 56535749-6810-4be4-8cbc-4611e5d16541
		summarizeBy: none
		sourceColumn: Derived_TreatmentFunctionCode

		annotation SummarizationSetBy = Automatic

	column Derived_TreatmentFunctionDescription
		dataType: string
		lineageTag: bf0715a9-f119-4482-8787-ebfda8d33e27
		summarizeBy: none
		sourceColumn: Derived_TreatmentFunctionDescription

		annotation SummarizationSetBy = Automatic

	column ServiceID
		dataType: string
		lineageTag: 94d6b94c-5b4f-42e0-9511-c3bf21546f46
		summarizeBy: none
		sourceColumn: ServiceID

		annotation SummarizationSetBy = Automatic

	column ServiceName
		dataType: string
		lineageTag: 00ae406c-203f-4519-bdb7-93557ecf8e5f
		summarizeBy: none
		sourceColumn: ServiceName

		annotation SummarizationSetBy = Automatic

	column ClinicTypeCode
		dataType: string
		lineageTag: 39d2c125-bce0-44d5-889f-485ceaf54254
		summarizeBy: none
		sourceColumn: ClinicTypeCode

		annotation SummarizationSetBy = Automatic

	column ClinicType
		dataType: string
		lineageTag: 251a5d8a-ce4e-4d80-abf2-eb2f53f3afcb
		summarizeBy: none
		sourceColumn: ClinicType

		annotation SummarizationSetBy = Automatic

	column Provider_Code
		dataType: string
		lineageTag: 9c6cea90-b66f-4212-a2bf-d1d88e5be056
		summarizeBy: none
		sourceColumn: Provider_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Name
		dataType: string
		lineageTag: 0e936011-abc9-42a3-80c5-6b003ceb3d86
		summarizeBy: none
		sourceColumn: Provider_Name

		annotation SummarizationSetBy = Automatic

	column Provider_Group
		dataType: string
		lineageTag: 26533bc9-749d-4973-885c-8b9e56f7fd11
		summarizeBy: none
		sourceColumn: Provider_Group

		annotation SummarizationSetBy = Automatic

	column Referral_Type
		dataType: string
		lineageTag: 3383e89a-7f6d-407e-bfeb-3c4f86882ff8
		summarizeBy: none
		sourceColumn: Referral_Type

		annotation SummarizationSetBy = Automatic

	column DirectlyBookable
		dataType: int64
		formatString: 0
		lineageTag: 53f5c2f6-3e57-4538-a325-8e61f48671fa
		summarizeBy: sum
		sourceColumn: DirectlyBookable

		annotation SummarizationSetBy = Automatic

	column ReferralAccepted
		dataType: int64
		formatString: 0
		lineageTag: 335bf7aa-2307-4958-85cd-c10f1bfdbf63
		summarizeBy: sum
		sourceColumn: ReferralAccepted

		annotation SummarizationSetBy = Automatic

	column ReferralRejected
		dataType: int64
		formatString: 0
		lineageTag: 4b4193eb-1791-4f84-9c54-9c3390661a20
		summarizeBy: sum
		sourceColumn: ReferralRejected

		annotation SummarizationSetBy = Automatic

	column RAS
		dataType: int64
		formatString: 0
		lineageTag: 356df5d7-0fda-45a3-8e52-033c00dd0dd9
		summarizeBy: sum
		sourceColumn: RAS

		annotation SummarizationSetBy = Automatic

	column Rejection
		dataType: int64
		formatString: 0
		lineageTag: 0daef4ab-49ca-472b-aeb6-ec319236fbcd
		summarizeBy: sum
		sourceColumn: Rejection

		annotation SummarizationSetBy = Automatic

	column Booking
		dataType: int64
		formatString: 0
		lineageTag: a8c77723-1f3b-4314-9c5a-6c5deda760c1
		summarizeBy: sum
		sourceColumn: Booking

		annotation SummarizationSetBy = Automatic

	column BookingDate
		dataType: dateTime
		formatString: General Date
		lineageTag: b88d04cc-0337-495d-a112-be8c921e44d7
		summarizeBy: none
		sourceColumn: BookingDate

		variation Variation
			isDefault
			relationship: 0e327f77-3568-4030-b888-3cd4a426f3df
			defaultHierarchy: LocalDateTable_9b99e177-2e97-4a0b-b0c5-9e318d00a825.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Booking_Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9c36f311-3b03-4753-b58f-2e1b47db9dd7
		summarizeBy: sum
		sourceColumn: Booking_Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column BookingMonth
		dataType: string
		lineageTag: e3b3fbb0-b386-423e-84cd-d81da5d8f308
		summarizeBy: none
		sourceColumn: BookingMonth

		annotation SummarizationSetBy = Automatic

	column BookingFinancialYear
		dataType: string
		lineageTag: 7ea2856d-c1fe-488a-ac3e-9373e6ab9d71
		summarizeBy: none
		sourceColumn: BookingFinancialYear

		annotation SummarizationSetBy = Automatic

	column IndicativeWaitTime
		dataType: int64
		formatString: 0
		lineageTag: 2d7ef996-f664-471a-bba7-73f7b9196bd0
		summarizeBy: sum
		sourceColumn: IndicativeWaitTime

		annotation SummarizationSetBy = Automatic

	column InitialReferralPopulation
		dataType: double
		lineageTag: def1b8ae-e9e7-4306-97a6-1a1bd159dec8
		summarizeBy: sum
		sourceColumn: InitialReferralPopulation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BookingReferralPopulation
		dataType: double
		lineageTag: 70aa5d15-d0d1-4201-8027-52c4f3172004
		summarizeBy: sum
		sourceColumn: BookingReferralPopulation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InitialReferralRate
		dataType: double
		lineageTag: 7ea30a0c-367a-4ab3-a6f0-f8ff4a94004b
		summarizeBy: sum
		sourceColumn: InitialReferralRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BookingReferralRate
		dataType: double
		lineageTag: 6d481764-8c81-4835-8663-64e21985f91d
		summarizeBy: sum
		sourceColumn: BookingReferralRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShortlistCount
		dataType: string
		lineageTag: e88316f8-0fe4-492e-a75a-6d11b3663793
		summarizeBy: none
		sourceColumn: ShortlistCount

		annotation SummarizationSetBy = Automatic

	column Location_Code
		dataType: string
		lineageTag: f452e9bb-f888-4c7e-98f5-2c0176009186
		summarizeBy: none
		sourceColumn: Location_Code

		annotation SummarizationSetBy = Automatic

	column PseudoNHSNo
		dataType: string
		lineageTag: d6591db6-7466-46f7-915c-b3c8257c3691
		summarizeBy: none
		sourceColumn: PseudoNHSNo

		annotation SummarizationSetBy = Automatic

	column ReferralCount
		dataType: int64
		formatString: 0
		lineageTag: d9f04466-a48e-441b-b8dc-0701a4ec2584
		summarizeBy: sum
		sourceColumn: ReferralCount

		annotation SummarizationSetBy = Automatic

	partition non_specific_symptoms-a91b9d5d-2fab-4843-97e6-9677dd00d268 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select * from [PowerBI_Reporting].[PlannedCare].[tbl03_E_Referrals]#(lf)where ServiceID = '7983901'#(lf)or ServiceID = '7997198'#(lf)or ServiceID = '7997322'"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"InitialReferralDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

