table two_week_wait
	lineageTag: be82239b-e498-49b4-84e4-696f3d7ce249

	measure two_week_wait_performance = (SUM('two_week_wait'[total_referrals])-SUM('two_week_wait'[breaches]))/SUM('two_week_wait'[total_referrals])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b0c1e4e6-ef15-481d-bf4e-979d5e0a705f

	measure 2ww_target = MIN('two_week_wait'[target])
		formatString: 0%;-0%;0%
		lineageTag: f3a66939-f23e-4164-af60-b345928663a8

	measure 2ww_target_checker = IF('two_week_wait'[two_week_wait_performance] >= 'two_week_wait'[2ww_target], "#63BE7B","#F8696B")
		lineageTag: 4c03aef3-0e76-4911-8f57-338196002624

	measure Testing = SUM('two_week_wait'[total_referrals])
		formatString: 0
		lineageTag: 9ce8449f-5238-4970-b9a1-d76019654b37

	measure 'Testing Breaches' = SUM('two_week_wait'[breaches])
		formatString: 0
		lineageTag: 8212cb04-3835-43c1-9d84-3beb7e2697bf

	measure '2ww Within Target' = CALCULATE(sum('two_week_wait'[total_referrals])-sum('two_week_wait'[breaches]))
		formatString: 0
		lineageTag: 33ec6fc4-6406-4d10-8861-3a38c0195b54

	measure 'Data up to date' = MAX('two_week_wait'[report_date])
		formatString: mmmm yyyy
		lineageTag: 1a89420f-3366-413a-8428-bf2922a7fef3

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Data refresh date' = MAX('two_week_wait'[refresh_date])
		formatString: mmmm yyyy
		lineageTag: 91b160e7-e33d-4694-b9a9-04f39f56f6d6

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column type
		dataType: string
		lineageTag: 82b25783-3110-49a0-b2f0-921006530fa5
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column report_date
		dataType: dateTime
		formatString: dd mmmm yyyy
		lineageTag: 7860c9a3-24b6-4f6e-9025-4a26df8d859c
		summarizeBy: none
		sourceColumn: report_date

		variation Variation
			isDefault
			relationship: cbcc0ec0-8c7b-447f-b03f-17e3ddeeb6fc
			defaultHierarchy: LocalDateTable_2a6daa77-edc1-42ad-98b8-99f1e7eab037.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column provider_code
		dataType: string
		lineageTag: 71338bb7-35de-479c-ad6c-e8c4141a8359
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column provider_name
		dataType: string
		lineageTag: 2e3fb6b4-02c2-4c41-950d-c6efb8820a92
		summarizeBy: none
		sourceColumn: provider_name

		annotation SummarizationSetBy = Automatic

	column provider_group
		dataType: string
		lineageTag: a09c32f5-60b8-408f-ba0b-d4b536fcb606
		summarizeBy: none
		sourceColumn: provider_group

		annotation SummarizationSetBy = Automatic

	column tumour_type
		dataType: string
		lineageTag: efda79ae-5dcb-405f-9741-49dd5b171ca9
		summarizeBy: none
		sourceColumn: tumour_type

		annotation SummarizationSetBy = Automatic

	column tumour_group
		dataType: string
		lineageTag: 0e9ccc85-3f77-4212-8d27-c6a47af083ae
		summarizeBy: none
		sourceColumn: tumour_group

		annotation SummarizationSetBy = Automatic

	column total_referrals
		dataType: int64
		formatString: 0
		lineageTag: c3b0ccd5-ea2d-4a52-8773-85e66808077e
		summarizeBy: sum
		sourceColumn: total_referrals

		annotation SummarizationSetBy = Automatic

	column breaches
		dataType: int64
		formatString: 0
		lineageTag: 159b9317-78fe-459e-a003-b7a950239a11
		summarizeBy: sum
		sourceColumn: breaches

		annotation SummarizationSetBy = Automatic

	column target
		dataType: double
		lineageTag: cc5da702-134c-4ca1-921a-38571725c935
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column performance
		dataType: int64
		formatString: 0
		lineageTag: 59dea804-5632-4f91-96fc-a380cd2c09a9
		summarizeBy: sum
		sourceColumn: performance

		annotation SummarizationSetBy = Automatic

	column report_number
		dataType: string
		lineageTag: 9d140f36-c4cf-45fd-bb05-1f70a90c855c
		summarizeBy: none
		sourceColumn: report_number

		annotation SummarizationSetBy = Automatic

	column Report_name
		dataType: string
		lineageTag: 1ac9c34a-51cf-408f-916c-afedd2e46b05
		summarizeBy: none
		sourceColumn: Report_name

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 615f9661-59f7-40f7-b718-ae42e2328ca0
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		lineageTag: 759bd0a8-8381-49c0-ba17-8601008021dc
		summarizeBy: none
		sourceColumn: month
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 83dd9032-6862-4850-a721-7b9f0e9849e7
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column refresh_date
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: a7d320ef-deaf-4478-8a73-61f10bf61d3d
		summarizeBy: none
		sourceColumn: refresh_date

		variation Variation
			isDefault
			relationship: 59066edf-6e7f-4cee-bc3d-dbdfa2d17ca2
			defaultHierarchy: LocalDateTable_15336e04-5d77-4ec7-878f-1d27eef0c3a8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Month flag' = ```
			
			
			VAR max_month = MAX('two_week_wait'[firstdateofmonth])
			VAR current_month = 'two_week_wait'[firstdateofmonth]
			
			VAR prior_month = EDATE(max_month, -1)
			
			RETURN IF(max_month = current_month,"Current Month",if(prior_month = current_month, "Prior Month", "Other Month"))
			
			```
		lineageTag: 61d06377-4e37-46ea-8b04-01789b20c10d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Current month name' = ```
			
			
			VAR max_month = MONTH(MAX('two_week_wait'[report_date]))
			
			VAR month_name =
			SWITCH(TRUE(),
			max_month = 1, "January",
			max_month = 2, "February",
			max_month = 3, "March",
			max_month = 4, "April",
			max_month = 5, "May",
			max_month = 6, "June",
			max_month = 7, "July",
			max_month = 8, "August",
			max_month = 9, "September",
			max_month = 10, "October",
			max_month = 11, "November",
			max_month = 12, "December",
			"Error"
			)
			
			RETURN month_name
			
			```
		lineageTag: 5cd7b207-dd2e-4a86-92af-b647092bb649
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Prior month name' =
			
			
			VAR max_month = MONTH(EDATE(MAX('two_week_wait'[firstdateofmonth]), - 1))
			
			VAR month_name =
			SWITCH(TRUE(),
			max_month = 1, "January",
			max_month = 2, "February",
			max_month = 3, "March",
			max_month = 4, "April",
			max_month = 5, "May",
			max_month = 6, "June",
			max_month = 7, "July",
			max_month = 8, "August",
			max_month = 9, "September",
			max_month = 10, "October",
			max_month = 11, "November",
			max_month = 12, "December",
			"Error"
			)
			
			RETURN month_name
		lineageTag: 954e0cab-f477-4376-a0c1-b0d4de41f942
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column firstdateofmonth
		dataType: dateTime
		formatString: General Date
		lineageTag: d0aef91b-cad5-4237-b536-ed377a663af1
		summarizeBy: none
		sourceColumn: firstdateofmonth

		variation Variation
			isDefault
			relationship: 0cf18afe-16c7-496e-b271-c5d0fa0e1bc7
			defaultHierarchy: LocalDateTable_07ca0653-3c21-4bb7-bd0c-4915fa6a9ba3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition two_week_wait-fd7a2bcd-56fd-4454-8922-7a5cec6f62c5 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="SELECT * FROM [PowerBI_Reporting].[Performance].[tbl15_CancerWaitTimes2WW]  "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"report_date", type date}, {"target", Percentage.Type}, {"performance", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

