table DateReference
	lineageTag: 577a713c-cb07-4894-8a6c-24e75f4befc5

	measure 'Practice Variation' = [Max Cost Practice]-[Min Cost Practice]
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: cb252dcf-2f54-4f72-9edb-492bcd6b80ad

		annotation PBI_ChangedProperties = ["FormatString"]

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column Month
		dataType: int64
		formatString: 0
		lineageTag: a588255b-331a-49c4-8fe0-958beeffa829
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 13c8edda-e9f7-4bbb-9ea2-b858adae0579
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: d82706f4-05a7-47a7-874c-b8005091a558
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterName
		dataType: string
		lineageTag: b9e7b069-40ba-4a7b-9e27-f831775442a0
		summarizeBy: none
		sourceColumn: QuarterName

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 8dc4b9a2-9a33-464a-927b-86143afdf8f4
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		lineageTag: 50788323-3928-429a-be33-ba7ab04bc158
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

	column MonthYearName
		dataType: string
		lineageTag: 9d6569a1-9371-47c7-90b1-29367d01dc41
		summarizeBy: none
		sourceColumn: MonthYearName

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: string
		lineageTag: 560b76ff-9bbd-487e-ae62-59aa12784f77
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: f0d45b77-c98f-49be-8e44-731fd24ef82b
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FinancialQuarter
		dataType: int64
		formatString: 0
		lineageTag: 8c2f0282-d60d-4953-b5d8-10bddd8d3511
		summarizeBy: sum
		sourceColumn: FinancialQuarter

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 2406067e-485d-4362-80db-31e826e31ebf
		summarizeBy: sum
		sourceColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column FirstDateofYear
		dataType: dateTime
		formatString: General Date
		lineageTag: f578fe2c-9f77-44a6-90a0-9c44a7902c9b
		summarizeBy: none
		sourceColumn: FirstDateofYear

		variation Variation
			isDefault
			relationship: 250ecf81-e2d7-4c19-90b9-a0ebc0d72903
			defaultHierarchy: LocalDateTable_45ebe484-74d7-4671-afb5-2419d3e53b9f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofYear
		dataType: dateTime
		formatString: General Date
		lineageTag: 9c013a5e-0ee4-4f04-a3bd-05da2e6d6608
		summarizeBy: none
		sourceColumn: LastDateofYear

		variation Variation
			isDefault
			relationship: 1cbe2511-f772-419e-bcac-3d2d1aad9bd3
			defaultHierarchy: LocalDateTable_f1ce4323-edfc-49e5-8f1c-68b4c2a5ce68.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FirstDateofQuater
		dataType: dateTime
		formatString: General Date
		lineageTag: 317341ed-a2da-4081-9c81-8c089eccbc1f
		summarizeBy: none
		sourceColumn: FirstDateofQuater

		variation Variation
			isDefault
			relationship: ee38c658-0432-4f80-a004-b22530495cc2
			defaultHierarchy: LocalDateTable_d03b54f2-4950-46f9-a90e-643395d1f5d8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofQuater
		dataType: dateTime
		formatString: General Date
		lineageTag: 508fee13-eb73-4ae8-9b31-cc3182ad16df
		summarizeBy: none
		sourceColumn: LastDateofQuater

		variation Variation
			isDefault
			relationship: 7b637789-3704-452b-b3cd-93ab8284d3ac
			defaultHierarchy: LocalDateTable_2583d2c0-f703-400f-b472-9df96ef45eca.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FirstDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: e43297f1-c25f-44fb-ba16-81cabe23197b
		summarizeBy: none
		sourceColumn: FirstDateofMonth

		variation Variation
			isDefault
			relationship: 69ace310-e0dc-4d6d-85af-40ae52e5c4a3
			defaultHierarchy: LocalDateTable_8b3806f3-7e4f-4f53-a74e-56733f652b95.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 38fa30f8-813f-45d8-8bf6-321d5b1e48f7
		summarizeBy: none
		sourceColumn: LastDateofMonth

		variation Variation
			isDefault
			relationship: 84127a25-f9b0-48b4-ae21-16ec3ae3a3e2
			defaultHierarchy: LocalDateTable_ebe31304-33cf-48c0-b133-0e554245d811.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MonthNameShort
		dataType: string
		lineageTag: 27e07cc1-4d08-44c5-9bb4-0916b278c1a7
		summarizeBy: none
		sourceColumn: MonthNameShort
		sortByColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	partition DateReference-0b76cbbd-473e-468a-9c99-327141bcf8ce = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "CCG_REFERENCE", [Query="SELECT DISTINCT#(lf)#(tab)   [Month]#(lf)      ,[MonthName]#(lf)      ,[Quarter]#(lf)      ,[QuarterName]#(lf)      ,[Year]#(lf)      ,[MonthYear]#(lf)      ,[MonthYearName]#(lf)      ,[YearMonth]#(lf)      ,[FinancialYear]#(lf)      ,[FinancialQuarter]#(lf)      ,[FinancialMonth]#(lf)      ,[FirstDateofYear]#(lf)      ,[LastDateofYear]#(lf)      ,[FirstDateofQuater]#(lf)      ,[LastDateofQuater]#(lf)      ,[FirstDateofMonth]#(lf)      ,[LastDateofMonth]#(lf)FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)WHERE [DATE] BETWEEN '01-APR-2019' AND GETDATE()"]),
				    #"Inserted First Characters" = Table.AddColumn(Source, "First Characters", each Text.Start([MonthName], 3), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted First Characters",{{"First Characters", "MonthNameShort"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

