table Ref_Sankey_Group_Mapping_End
	lineageTag: d2bb93ff-9328-47bc-995f-71d8bf834cea

	column Sankey_Health_Group
		dataType: string
		lineageTag: ce5c53d1-5915-40ac-9607-84b03f7b1596
		summarizeBy: none
		sourceColumn: Sankey_Health_Group
		sortByColumn: Sankey_Health_Ordering

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sankey_PNG
		dataType: string
		lineageTag: 884746e1-4642-46da-906e-9746877efb39
		summarizeBy: none
		sourceColumn: Sankey_PNG
		sortByColumn: Sankey_PNG_Ordering

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sankey_PNG_Ordering
		dataType: int64
		formatString: 0
		lineageTag: e5235398-6da0-4b42-8ecc-c26cff376bcd
		summarizeBy: none
		sourceColumn: Sankey_PNG_Ordering

		annotation SummarizationSetBy = Automatic

	column Sankey_Health_Ordering
		dataType: string
		lineageTag: ac292df6-0eb0-4fbe-b656-43da02d70b83
		summarizeBy: none
		sourceColumn: Sankey_Health_Ordering

		annotation SummarizationSetBy = Automatic

	partition Ref_Sankey_Group_Mapping_End = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZLLTsMwEEV/xcq6FXn1JVbQCrFoomxYVVmYeGgGOXblOJT8PbZb0uaBxGIWM7732HOTw8F7Bcp12Xozz4/IXp5JCsDIE2u4NrOlqdjLZz1dQFIp5m81KHc6oQhvpG2JnJnZotMlkoGiGtx5beUxScx1OE+kekeGunX2raxOHL5NazQrh5i2L0b2BBg2VZ+w7gg7WaGgQpu3KSmwsIwN6aYJ/ZTq98wwhEGiFEYVhO4lfzHWN0ZWt0WJVCssHp6hpF8oFeV9WNDBUjiTjGoEYTPvd5Erly8ey7uVHodbW6Y/imLgsqLIpfFfZEBeFEV+aeLOmik42lXt4kty7YqJL7dxv9HQsrqzTDzR70x7+DBxylPD6TW48SRw5a645EZ2CPanG7Shqzz/AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sankey_Health_Group = _t, Sankey_PNG = _t, Sankey_PNG_Ordering = _t, Sankey_Health_Ordering = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sankey_Health_Group", type text}, {"Sankey_PNG", type text}, {"Sankey_PNG_Ordering", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

