table Ref_Sankey_Group_Mapping
	lineageTag: 729fcb3c-84f7-41bb-b555-b06d0b58b626

	column Sankey_Health_Group
		dataType: string
		lineageTag: afb660e5-52e6-43cd-9860-1fa07a775731
		summarizeBy: none
		sourceColumn: Sankey_Health_Group
		sortByColumn: Sankey_Health_Ordering

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sankey_PNG
		dataType: string
		lineageTag: 66b8979f-23a8-4cd5-a235-c20ed0357fa2
		summarizeBy: none
		sourceColumn: Sankey_PNG
		sortByColumn: Sankey_PNG_Ordering

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sankey_PNG_Ordering
		dataType: int64
		formatString: 0
		lineageTag: 334a9b5c-684f-4516-a0e1-53a6be2dd69d
		summarizeBy: none
		sourceColumn: Sankey_PNG_Ordering

		annotation SummarizationSetBy = Automatic

	column Sankey_Health_Ordering
		dataType: string
		lineageTag: 7a565ad3-8953-4e37-817d-e7c9267172b3
		summarizeBy: none
		sourceColumn: Sankey_Health_Ordering

		annotation SummarizationSetBy = Automatic

	partition Ref_Sankey_Group_Mapping = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZLLTsMwEEV/xcq6FXn1JVbQCrFoomxYVVmYeGgGOXblOJT8PbZb0uaBxGIWM7732HOTw8F7Bcp12Xozz4/IXp5JCsDIE2u4NrOlqdjLZz1dQFIp5m81KHc6oQhvpG2JnJnZotMlkoGiGtx5beUxScx1OE+kekeGunX2raxOHL5NazQrh5i2L0b2BBg2VZ+w7gg7WaGgQpu3KSmwsIwN6aYJ/ZTq98wwhEGiFEYVhO4lfzHWN0ZWt0WJVCssHp6hpF8oFeV9WNDBUjiTjGoEYTPvd5Erly8ey7uVHodbW6Y/imLgsqLIpfFfZEBeFEV+aeLOmik42lXt4kty7YqJL7dxv9HQsrqzTDzR70x7+DBxylPD6TW48SRw5a645EZ2CPanG7Shqzz/AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sankey_Health_Group = _t, Sankey_PNG = _t, Sankey_PNG_Ordering = _t, Sankey_Health_Ordering = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sankey_Health_Group", type text}, {"Sankey_PNG", type text}, {"Sankey_PNG_Ordering", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

