table 'Date Reference'
	lineageTag: b99a1142-f26e-4c71-8174-e71750f83bcc

	column Date_112
		dataType: int64
		formatString: 0
		lineageTag: aee1d7fe-c6e2-42d0-a5ba-fd49b61beac6
		summarizeBy: sum
		sourceColumn: Date_112

		annotation SummarizationSetBy = Automatic

	column Full_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6efc9212-91fb-47c3-9416-7f2bc2a78f46
		summarizeBy: none
		sourceColumn: Full_Date

		variation Variation
			isDefault
			relationship: 4306eef6-72ff-4372-ba82-fcebb608bc92
			defaultHierarchy: LocalDateTable_61ac4514-7803-489c-a43b-a50681118af9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Excel_Date_Value
		dataType: int64
		formatString: 0
		lineageTag: b9bafa84-b6d4-4a8e-a3c5-bb6f5586143e
		summarizeBy: sum
		sourceColumn: Excel_Date_Value

		annotation SummarizationSetBy = Automatic

	column Year_Month
		dataType: int64
		formatString: 0
		lineageTag: a1b30baa-454d-4b57-ad04-b16f1eff9e66
		summarizeBy: sum
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

	column Working_Day_Type
		dataType: string
		lineageTag: be693f0b-953b-463f-a6d8-39611e032d2f
		summarizeBy: none
		sourceColumn: Working_Day_Type

		annotation SummarizationSetBy = Automatic

	column Working_Day_Calc
		dataType: int64
		formatString: 0
		lineageTag: ad635c4f-02d8-479b-a7e7-5cfc9ee78bc7
		summarizeBy: sum
		sourceColumn: Working_Day_Calc

		annotation SummarizationSetBy = Automatic

	column Weekday_No
		dataType: int64
		formatString: 0
		lineageTag: 651f326e-9cef-49f5-9cf8-6d1be24cee68
		summarizeBy: sum
		sourceColumn: Weekday_No

		annotation SummarizationSetBy = Automatic

	column Weekday_Name
		dataType: string
		lineageTag: c5bd497c-b16d-4097-9643-10b26967e628
		summarizeBy: none
		sourceColumn: Weekday_Name

		annotation SummarizationSetBy = Automatic

	column Weekday_Short_Name
		dataType: string
		lineageTag: faef58a6-60ad-46f5-b50a-8e9a364e8c9e
		summarizeBy: none
		sourceColumn: Weekday_Short_Name

		annotation SummarizationSetBy = Automatic

	column Bank_Holiday_Desc
		dataType: string
		lineageTag: 5e6669c5-129a-41a5-9bf0-b6156357ac32
		summarizeBy: none
		sourceColumn: Bank_Holiday_Desc

		annotation SummarizationSetBy = Automatic

	column Month_No
		dataType: int64
		formatString: 0
		lineageTag: 45c26c54-395c-43bf-9f78-256cf06f8067
		summarizeBy: sum
		sourceColumn: Month_No

		annotation SummarizationSetBy = Automatic

	column Month_No_2_Char
		dataType: string
		lineageTag: 2ad1ff45-b317-4ba8-903b-2f630aab1c66
		summarizeBy: none
		sourceColumn: Month_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Month_Name
		dataType: string
		lineageTag: 07d07b14-88aa-46ef-95a7-8ae7db791bbc
		summarizeBy: none
		sourceColumn: Month_Name
		sortByColumn: Fin_Month_No

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Month_Short_Name
		dataType: string
		lineageTag: e319f514-feca-4319-8d5b-a1c5fc97dd4c
		summarizeBy: none
		sourceColumn: Month_Short_Name

		annotation SummarizationSetBy = Automatic

	column YearMonth_YYYYMM
		dataType: int64
		formatString: 0
		lineageTag: 3001b2e2-a310-4676-91e8-bbd91c078215
		summarizeBy: sum
		sourceColumn: YearMonth_YYYYMM

		annotation SummarizationSetBy = Automatic

	column MonthYear_MMMM_YYYYY
		dataType: string
		lineageTag: f09df8aa-ca58-414b-8261-0790e9584e1a
		summarizeBy: none
		sourceColumn: MonthYear_MMMM_YYYYY
		sortByColumn: Year_Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Fin_Year_First_Part
		dataType: int64
		formatString: 0
		lineageTag: b9041a3c-c5cf-404a-bb3b-60c6c3bca250
		summarizeBy: sum
		sourceColumn: Fin_Year_First_Part

		annotation SummarizationSetBy = Automatic

	column Fin_Year_Second_Part
		dataType: int64
		formatString: 0
		lineageTag: 01478960-1bf6-4f0c-a5a6-1a01a59178d9
		summarizeBy: sum
		sourceColumn: Fin_Year_Second_Part

		annotation SummarizationSetBy = Automatic

	column Fin_Year
		dataType: int64
		formatString: 0
		lineageTag: a9d5a162-1b9f-4884-9b92-eba44befc0c0
		summarizeBy: sum
		sourceColumn: Fin_Year

		annotation SummarizationSetBy = Automatic

	column Fin_Year_yy_yy
		dataType: string
		lineageTag: 274aa24a-968b-43a7-b3e6-122281058cb8
		summarizeBy: none
		sourceColumn: Fin_Year_yy_yy

		annotation SummarizationSetBy = Automatic

	column Fin_Year_YYYY_dash_YY
		dataType: string
		lineageTag: 59efbd6f-75de-4b5e-bd4e-3eb74e227e43
		summarizeBy: none
		sourceColumn: Fin_Year_YYYY_dash_YY

		annotation SummarizationSetBy = Automatic

	column Fin_Week_No
		dataType: int64
		formatString: 0
		lineageTag: dd25656a-fa63-4b56-bb8f-f30bbabde812
		summarizeBy: sum
		sourceColumn: Fin_Week_No

		annotation SummarizationSetBy = Automatic

	column Fin_Week_No_2_Char
		dataType: string
		lineageTag: 4c810559-8a28-4e89-90d6-b4f1a657cfff
		summarizeBy: none
		sourceColumn: Fin_Week_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Fin_Month_No
		dataType: int64
		formatString: 0
		lineageTag: 7e754141-4e6a-451b-a588-842d2842eb23
		summarizeBy: sum
		sourceColumn: Fin_Month_No

		annotation SummarizationSetBy = Automatic

	column Fin_Month_No_2_Char
		dataType: string
		lineageTag: 41126231-abf0-43f2-9121-7d2e44e76760
		summarizeBy: none
		sourceColumn: Fin_Month_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_No
		dataType: int64
		formatString: 0
		lineageTag: ec6cd084-a819-4e46-a304-fabc133b4489
		summarizeBy: sum
		sourceColumn: Fin_Quarter_No

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_Name
		dataType: string
		lineageTag: c4608398-5583-48ea-b989-f34f52c220ec
		summarizeBy: none
		sourceColumn: Fin_Quarter_Name

		annotation SummarizationSetBy = Automatic

	column Fin_Year_Quarter_YYYYYYQ
		dataType: int64
		formatString: 0
		lineageTag: d55ebd04-7984-4234-8c10-8e21c85fd5cf
		summarizeBy: sum
		sourceColumn: Fin_Year_Quarter_YYYYYYQ

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_Qq_Fin_Year_YYYY_dash_YY
		dataType: string
		lineageTag: 01aea1f8-46f3-47d7-a1ca-597012b5cfba
		summarizeBy: none
		sourceColumn: Fin_Quarter_Qq_Fin_Year_YYYY_dash_YY

		annotation SummarizationSetBy = Automatic

	column Cal_Week_No
		dataType: int64
		formatString: 0
		lineageTag: 9916cabd-d31d-4963-86ec-f3795b634ce2
		summarizeBy: sum
		sourceColumn: Cal_Week_No

		annotation SummarizationSetBy = Automatic

	column Cal_Week_No_2_Char
		dataType: string
		lineageTag: 718b01f2-1da4-49c8-9180-16fda890ad39
		summarizeBy: none
		sourceColumn: Cal_Week_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Cal_Quarter_No
		dataType: int64
		formatString: 0
		lineageTag: a0c1de01-f103-4896-8cce-e6babb764771
		summarizeBy: sum
		sourceColumn: Cal_Quarter_No

		annotation SummarizationSetBy = Automatic

	column Cal_Quarter_YYYYQ
		dataType: int64
		formatString: 0
		lineageTag: 202faa74-c87b-4f60-9270-fda5c0ac2fca
		summarizeBy: sum
		sourceColumn: Cal_Quarter_YYYYQ

		annotation SummarizationSetBy = Automatic

	column Cal_Quarter_Name
		dataType: string
		lineageTag: 89424609-e226-42ef-8235-61632d5d490a
		summarizeBy: none
		sourceColumn: Cal_Quarter_Name

		annotation SummarizationSetBy = Automatic

	column Cal_Year
		dataType: int64
		formatString: 0
		lineageTag: fe74fe64-be73-47a1-944c-716afc338326
		summarizeBy: sum
		sourceColumn: Cal_Year

		annotation SummarizationSetBy = Automatic

	column Quarter_Name
		dataType: string
		lineageTag: 90b3b33d-5a14-40d0-aa64-bdc801208e64
		summarizeBy: none
		sourceColumn: Quarter_Name

		annotation SummarizationSetBy = Automatic

	column Month_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 075bce73-8d67-4866-91de-31e0470e1bad
		summarizeBy: none
		sourceColumn: Month_Start

		variation Variation
			isDefault
			relationship: 8a8b4728-77ea-4740-8a44-3bed6e1f4ad4
			defaultHierarchy: LocalDateTable_f088c87f-93bc-4b93-ac68-19b50d1d6ce9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 4081f4d9-7c78-486a-8f70-05b29a899c1f
		summarizeBy: sum
		sourceColumn: Month_Start_112

		annotation SummarizationSetBy = Automatic

	column Month_End
		dataType: dateTime
		formatString: General Date
		lineageTag: c9c7f0c8-9621-46e6-bde8-6e9e82c771ec
		summarizeBy: none
		sourceColumn: Month_End

		variation Variation
			isDefault
			relationship: 1ba34fbb-f201-4f84-8dc6-f77af61db963
			defaultHierarchy: LocalDateTable_aedf2cde-4a06-4775-aa58-daf0dc9735d6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month_End_112
		dataType: int64
		formatString: 0
		lineageTag: 2520a9d0-ae48-4057-a969-1a412c5fe3df
		summarizeBy: sum
		sourceColumn: Month_End_112

		annotation SummarizationSetBy = Automatic

	column Previous_Month_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 37fc3012-7fa8-4f87-94ab-501f3b0fef58
		summarizeBy: none
		sourceColumn: Previous_Month_Start

		variation Variation
			isDefault
			relationship: f8b21486-d296-41f7-862d-fd9850b2c91e
			defaultHierarchy: LocalDateTable_7a3507fe-38f7-4c9b-a6e2-1d6a1bdba2e2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Month_Start_112
		dataType: int64
		formatString: 0
		lineageTag: bdb60211-408d-4987-b29f-df8204d3db05
		summarizeBy: sum
		sourceColumn: Previous_Month_Start_112

		annotation SummarizationSetBy = Automatic

	column Previous_Month_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 0fb3b036-0d75-451b-a661-e0686dd63f71
		summarizeBy: none
		sourceColumn: Previous_Month_End

		variation Variation
			isDefault
			relationship: 10afcffd-3c88-4a05-9f34-58dc13eb1765
			defaultHierarchy: LocalDateTable_def75b68-5a1f-49f4-ab66-94459897ddc9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Month_End_112
		dataType: int64
		formatString: 0
		lineageTag: a5d3c3d4-8663-494f-abdb-5456970d993b
		summarizeBy: sum
		sourceColumn: Previous_Month_End_112

		annotation SummarizationSetBy = Automatic

	column Next_Month_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 6122e1eb-6245-4c43-b1e9-dd1feab583ac
		summarizeBy: none
		sourceColumn: Next_Month_Start

		variation Variation
			isDefault
			relationship: ac1ed003-9fb0-4d11-8e08-22294389830a
			defaultHierarchy: LocalDateTable_66d20e83-7c49-4407-9d24-d12cc5a5334a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Month_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 3810e39e-3d20-4c58-9fd3-8ec4641e094a
		summarizeBy: sum
		sourceColumn: Next_Month_Start_112

		annotation SummarizationSetBy = Automatic

	column Next_Month_End
		dataType: dateTime
		formatString: General Date
		lineageTag: e2bd0501-13fb-4798-8874-6c51f9f7585a
		summarizeBy: none
		sourceColumn: Next_Month_End

		variation Variation
			isDefault
			relationship: 5f8121d6-b562-4bf6-b0af-7ed593ab4197
			defaultHierarchy: LocalDateTable_26225855-de3d-42f1-8413-f39d2c52869f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Month_End_112
		dataType: int64
		formatString: 0
		lineageTag: 6789ac40-6a92-41d1-a6e8-7ae8fe090cfd
		summarizeBy: sum
		sourceColumn: Next_Month_End_112

		annotation SummarizationSetBy = Automatic

	column Fin_Year_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: c6222991-d187-418f-8aa2-3d7481ffae35
		summarizeBy: none
		sourceColumn: Fin_Year_Start

		variation Variation
			isDefault
			relationship: b947777b-b3d7-4105-a601-ebca5105885d
			defaultHierarchy: LocalDateTable_a0ac6c4a-810d-4bd8-b414-2045ac3ecef3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Fin_Year_Start_112
		dataType: int64
		formatString: 0
		lineageTag: f6599d09-be79-4b4a-9e4d-8fe2cac9eba8
		summarizeBy: sum
		sourceColumn: Fin_Year_Start_112

		annotation SummarizationSetBy = Automatic

	column Fin_Year_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 75e78cf4-d1b2-4f5b-a2e4-f0400d9de590
		summarizeBy: none
		sourceColumn: Fin_Year_End

		variation Variation
			isDefault
			relationship: ca04a105-1470-4e5b-8c41-c3b92a60edde
			defaultHierarchy: LocalDateTable_2cc2b937-a3e9-4bb2-a5ce-b4059ee0d01d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Fin_Year_End_112
		dataType: int64
		formatString: 0
		lineageTag: 937537a3-315e-4b1e-966a-4812511625ec
		summarizeBy: sum
		sourceColumn: Fin_Year_End_112

		annotation SummarizationSetBy = Automatic

	column Previous_Fin_Year_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 4938c197-ca20-4197-95c9-830dcecbf1ce
		summarizeBy: none
		sourceColumn: Previous_Fin_Year_Start

		variation Variation
			isDefault
			relationship: f8bc1877-ced1-489e-a378-16d64753668e
			defaultHierarchy: LocalDateTable_c1c92147-e82a-4667-a15a-5cfebd4660ab.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Fin_Year_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 74c87747-9d98-4dd0-b6d0-90ce1c7c066f
		summarizeBy: sum
		sourceColumn: Previous_Fin_Year_Start_112

		annotation SummarizationSetBy = Automatic

	column Previous_Fin_Year_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 10107540-9cca-46d4-9e31-1b4da3a52682
		summarizeBy: none
		sourceColumn: Previous_Fin_Year_End

		variation Variation
			isDefault
			relationship: 12edce62-6763-474b-93db-99fa6841cb5a
			defaultHierarchy: LocalDateTable_7158268a-f187-432c-9c30-a5acc68f805a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Fin_Year_End_112
		dataType: int64
		formatString: 0
		lineageTag: 8939881d-00ec-4e74-a8f9-138153df6483
		summarizeBy: sum
		sourceColumn: Previous_Fin_Year_End_112

		annotation SummarizationSetBy = Automatic

	column Next_Fin_Year_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: a36932bc-0910-407c-920e-0f88e6401127
		summarizeBy: none
		sourceColumn: Next_Fin_Year_Start

		variation Variation
			isDefault
			relationship: c269e8bf-eaac-4d3f-96ee-4b58fa6d1b50
			defaultHierarchy: LocalDateTable_d2c164ac-b0e0-488b-b21a-674f96d616f8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Fin_Year_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 22b71016-a515-4754-b436-ec4833a37eda
		summarizeBy: sum
		sourceColumn: Next_Fin_Year_Start_112

		annotation SummarizationSetBy = Automatic

	column Next_Fin_Year_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 8187cb98-d16d-491a-b329-a58259466bbb
		summarizeBy: none
		sourceColumn: Next_Fin_Year_End

		variation Variation
			isDefault
			relationship: b1d339e1-9ba3-4d63-bf57-d28480719e4e
			defaultHierarchy: LocalDateTable_9ee48cf6-6c1b-4ad2-9b2a-1a7640700017.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Fin_Year_End_112
		dataType: int64
		formatString: 0
		lineageTag: a734bcb6-88e1-4432-9bc3-583b5ca5a1cd
		summarizeBy: sum
		sourceColumn: Next_Fin_Year_End_112

		annotation SummarizationSetBy = Automatic

	column Cal_Year_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: e11fdec4-28a0-4319-8d7a-b3497c739c86
		summarizeBy: none
		sourceColumn: Cal_Year_Start

		variation Variation
			isDefault
			relationship: 4576be28-6219-4808-bce7-f03ae85b3541
			defaultHierarchy: LocalDateTable_ff62706e-5add-4b03-b9db-e760dc025605.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Cal_Year_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 49c1d48d-57da-49a0-9d47-ad0dc93f88bb
		summarizeBy: sum
		sourceColumn: Cal_Year_Start_112

		annotation SummarizationSetBy = Automatic

	column Cal_Year_End
		dataType: dateTime
		formatString: General Date
		lineageTag: b08f5428-d396-46e9-a1ae-0fb9db28d75c
		summarizeBy: none
		sourceColumn: Cal_Year_End

		variation Variation
			isDefault
			relationship: c6b562ec-840b-4e81-9157-224abc56eb55
			defaultHierarchy: LocalDateTable_c5e18363-873d-4cb5-8f37-5b0ba9ed78ba.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Cal_Year_End_112
		dataType: int64
		formatString: 0
		lineageTag: 8edd2dbe-5f69-4e4e-9b7c-16dc67ecc336
		summarizeBy: sum
		sourceColumn: Cal_Year_End_112

		annotation SummarizationSetBy = Automatic

	column Previous_Cal_Year_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 0d9b80d9-d6bc-42d0-b1b0-fa95bcdc5327
		summarizeBy: none
		sourceColumn: Previous_Cal_Year_Start

		variation Variation
			isDefault
			relationship: 871e94c4-9f47-479a-91f0-7f21f85eb234
			defaultHierarchy: LocalDateTable_d58a6885-ed7c-40bf-9d5e-36c54e9b374b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Cal_Year_Start_112
		dataType: int64
		formatString: 0
		lineageTag: a1a1a1cb-21c8-4a7e-bdc3-2214e2d64ef2
		summarizeBy: sum
		sourceColumn: Previous_Cal_Year_Start_112

		annotation SummarizationSetBy = Automatic

	column Previous_Cal_Year_End
		dataType: dateTime
		formatString: General Date
		lineageTag: a125f6b7-06e1-4e0d-ab4f-557f211d694b
		summarizeBy: none
		sourceColumn: Previous_Cal_Year_End

		variation Variation
			isDefault
			relationship: 3a5a00c1-aa0a-4289-9b39-1b5a325f9630
			defaultHierarchy: LocalDateTable_33ddb196-5a79-4705-ac52-f23d2ddfd67b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Cal_Year_End_112
		dataType: int64
		formatString: 0
		lineageTag: 66bd9ad7-6d16-4960-98e2-ec1e7c303bbf
		summarizeBy: sum
		sourceColumn: Previous_Cal_Year_End_112

		annotation SummarizationSetBy = Automatic

	column Next_Cal_Year_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ad3ec57-a3a5-4fb5-b28b-3b556919fe01
		summarizeBy: none
		sourceColumn: Next_Cal_Year_Start

		variation Variation
			isDefault
			relationship: 1f884540-9c6f-4911-b17d-4629a79a81ad
			defaultHierarchy: LocalDateTable_62358591-5c1d-406c-85fe-53220abccad7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Cal_Year_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 56180d65-c501-4842-bbb8-747fd9802d3a
		summarizeBy: sum
		sourceColumn: Next_Cal_Year_Start_112

		annotation SummarizationSetBy = Automatic

	column Next_Cal_Year_End
		dataType: dateTime
		formatString: General Date
		lineageTag: cf40c2b3-0782-4523-b534-9c0e52e18d6c
		summarizeBy: none
		sourceColumn: Next_Cal_Year_End

		variation Variation
			isDefault
			relationship: c0965561-11da-45ea-bd84-db80d51df9ef
			defaultHierarchy: LocalDateTable_1a0a732b-f453-4ac4-ad93-c7077f7e5236.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Cal_Year_End_112
		dataType: int64
		formatString: 0
		lineageTag: 772f046b-481c-486b-bf2b-45b168d45f47
		summarizeBy: sum
		sourceColumn: Next_Cal_Year_End_112

		annotation SummarizationSetBy = Automatic

	column Quarter_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 1326f9ae-3874-4f56-a244-535cd98dbb34
		summarizeBy: none
		sourceColumn: Quarter_Start

		variation Variation
			isDefault
			relationship: 061c0c86-822b-466b-a35c-d34d9e643e9a
			defaultHierarchy: LocalDateTable_6741e070-a8f8-4d7e-ac66-dfa6d66cdda1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Quarter_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 2aa2e433-6bdd-44fc-8134-491985538b16
		summarizeBy: sum
		sourceColumn: Quarter_Start_112

		annotation SummarizationSetBy = Automatic

	column Quarter_End
		dataType: dateTime
		formatString: General Date
		lineageTag: db736353-25d6-4c08-bbcc-2a4d3db7b444
		summarizeBy: none
		sourceColumn: Quarter_End

		variation Variation
			isDefault
			relationship: c7f3e988-b83d-4b21-95ae-b25728925182
			defaultHierarchy: LocalDateTable_b66dd3fa-a2a7-4773-a0f2-3419acabcb85.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Quarter_End_112
		dataType: int64
		formatString: 0
		lineageTag: 565ff59c-7123-4e0e-9acf-00706225c684
		summarizeBy: sum
		sourceColumn: Quarter_End_112

		annotation SummarizationSetBy = Automatic

	column Previous_Quarter_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f833873-d5a6-4f68-9c14-60c94556ccd5
		summarizeBy: none
		sourceColumn: Previous_Quarter_Start

		variation Variation
			isDefault
			relationship: 7c905496-52cb-48aa-9f0d-608a4135bcff
			defaultHierarchy: LocalDateTable_043a36da-e059-462d-9bb8-f834373ed6f6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Quarter_Start_112
		dataType: int64
		formatString: 0
		lineageTag: a3722c66-2658-4bd3-a9a5-430c58892ea6
		summarizeBy: sum
		sourceColumn: Previous_Quarter_Start_112

		annotation SummarizationSetBy = Automatic

	column Previous_Quarter_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 80abd45c-8429-47a1-a362-44e395f10960
		summarizeBy: none
		sourceColumn: Previous_Quarter_End

		variation Variation
			isDefault
			relationship: 482cdd39-1300-4f36-baf2-0dd6a4992ca5
			defaultHierarchy: LocalDateTable_3b54fd1d-2db6-4573-a24f-17362dcb8ff1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Quarter_End_112
		dataType: int64
		formatString: 0
		lineageTag: fcb2d3eb-9c8d-4cfa-b9c1-26fda2f1873e
		summarizeBy: sum
		sourceColumn: Previous_Quarter_End_112

		annotation SummarizationSetBy = Automatic

	column Next_Quarter_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 7fb0d7de-626d-41ff-83a3-d722f6e6a71f
		summarizeBy: none
		sourceColumn: Next_Quarter_Start

		variation Variation
			isDefault
			relationship: c301cab2-48df-4a1f-8786-c9bdcff24032
			defaultHierarchy: LocalDateTable_ccb9e675-7ff2-4568-9cc7-0fb15592883a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Quarter_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 57d2658f-4bd3-40b6-bf9e-2943fd4042df
		summarizeBy: sum
		sourceColumn: Next_Quarter_Start_112

		annotation SummarizationSetBy = Automatic

	column Next_Quarter_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 63d6c2d7-3e45-4e00-815e-5f3647ed4b36
		summarizeBy: none
		sourceColumn: Next_Quarter_End

		variation Variation
			isDefault
			relationship: 8eb28f4b-dc6a-458f-b5a2-0536f9713e32
			defaultHierarchy: LocalDateTable_cc530a88-509c-474e-a1c5-2edbcd736592.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Quarter_End_112
		dataType: int64
		formatString: 0
		lineageTag: 2a442eb6-749d-4ec2-a975-abaa0ec37f26
		summarizeBy: sum
		sourceColumn: Next_Quarter_End_112

		annotation SummarizationSetBy = Automatic

	column Day_Of_Quarter
		dataType: int64
		formatString: 0
		lineageTag: 94048aee-1abd-440a-a66c-15c26c54043b
		summarizeBy: sum
		sourceColumn: Day_Of_Quarter

		annotation SummarizationSetBy = Automatic

	column Day_Of_Quarter_2_Char
		dataType: string
		lineageTag: 4becd8f5-06dd-4eed-9b38-d66acbe6d244
		summarizeBy: none
		sourceColumn: Day_Of_Quarter_2_Char

		annotation SummarizationSetBy = Automatic

	column Week_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: fe19d458-8027-49be-8c11-c4972df58ea1
		summarizeBy: none
		sourceColumn: Week_Start

		variation Variation
			isDefault
			relationship: dac1f9b9-9d58-4ad1-b49e-3d00e95dd121
			defaultHierarchy: LocalDateTable_52e9886f-9af2-470e-95ed-773a0c2954d0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Week_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 592bc1f2-320f-49d3-b791-17f2063f02f7
		summarizeBy: sum
		sourceColumn: Week_Start_112

		annotation SummarizationSetBy = Automatic

	column Week_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 177149e0-29f9-4650-8a53-38ca224af8cf
		summarizeBy: none
		sourceColumn: Week_End

		variation Variation
			isDefault
			relationship: e5240a12-ca9b-405a-9a85-1a66023fa885
			defaultHierarchy: LocalDateTable_8608230f-7c2c-40cf-bcc7-a6391f09c71e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Week_End_112
		dataType: int64
		formatString: 0
		lineageTag: 09d98017-d9d9-424a-9020-3b20d4b224ff
		summarizeBy: sum
		sourceColumn: Week_End_112

		annotation SummarizationSetBy = Automatic

	column Previous_Week_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b789a8d-03ac-4389-8665-6f449bef21a9
		summarizeBy: none
		sourceColumn: Previous_Week_Start

		variation Variation
			isDefault
			relationship: 65571027-3ffe-44d7-a016-f211c026e738
			defaultHierarchy: LocalDateTable_f6934248-6728-446e-b491-9b0523d2b79a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Week_Start_112
		dataType: int64
		formatString: 0
		lineageTag: e6462e96-e701-458c-99d5-59364c71030c
		summarizeBy: sum
		sourceColumn: Previous_Week_Start_112

		annotation SummarizationSetBy = Automatic

	column Previous_Week_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 92b2c539-2923-4188-9b92-3c121d4b5fa1
		summarizeBy: none
		sourceColumn: Previous_Week_End

		variation Variation
			isDefault
			relationship: 44550aa0-0afc-4aea-a192-487af2d3a363
			defaultHierarchy: LocalDateTable_2bd84716-e2cf-49ac-985d-89ae23686d1d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Week_End_112
		dataType: int64
		formatString: 0
		lineageTag: e98f6e25-0b7e-447d-8606-dd508132bff7
		summarizeBy: sum
		sourceColumn: Previous_Week_End_112

		annotation SummarizationSetBy = Automatic

	column Next_Week_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 381a0733-5fdc-4617-b02d-9f188e08887a
		summarizeBy: none
		sourceColumn: Next_Week_Start

		variation Variation
			isDefault
			relationship: b396a7c9-2ca0-47de-b8da-467ae6c39c65
			defaultHierarchy: LocalDateTable_de28be2a-dce6-4aa8-af6e-7c23c983bd22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Week_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 2f4ed0f3-715f-419e-9e11-954560c6b5ad
		summarizeBy: sum
		sourceColumn: Next_Week_Start_112

		annotation SummarizationSetBy = Automatic

	column Next_Week_End
		dataType: dateTime
		formatString: General Date
		lineageTag: 705af188-9146-422f-b25a-e2b9f401de63
		summarizeBy: none
		sourceColumn: Next_Week_End

		variation Variation
			isDefault
			relationship: c1af6a06-ca1f-44fb-b3d2-9a20ebed474c
			defaultHierarchy: LocalDateTable_e93f6cec-af47-45a5-a12f-b2f1e5b36154.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Week_End_112
		dataType: int64
		formatString: 0
		lineageTag: 8f8af9b8-fbae-4c05-911e-dbcf840f9142
		summarizeBy: sum
		sourceColumn: Next_Week_End_112

		annotation SummarizationSetBy = Automatic

	column Month_Day_No
		dataType: int64
		formatString: 0
		lineageTag: 46fba1c5-1884-42ab-90ca-0184b64eaa93
		summarizeBy: sum
		sourceColumn: Month_Day_No

		annotation SummarizationSetBy = Automatic

	column Month_Day_No_2_Char
		dataType: string
		lineageTag: d43f8227-ec19-400c-b4df-5f8ec879c85e
		summarizeBy: none
		sourceColumn: Month_Day_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Previous_Day
		dataType: dateTime
		formatString: General Date
		lineageTag: 042c09f3-33ab-419c-897f-26bb9ff898f9
		summarizeBy: none
		sourceColumn: Previous_Day

		variation Variation
			isDefault
			relationship: caa30602-e4b2-4286-8217-72654027009e
			defaultHierarchy: LocalDateTable_952ce69d-2647-429d-97ff-001db7223f05.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Previous_Day112
		dataType: int64
		formatString: 0
		lineageTag: 1a42e25e-e123-448c-8057-ec056d676e8f
		summarizeBy: sum
		sourceColumn: Previous_Day112

		annotation SummarizationSetBy = Automatic

	column Next_Day
		dataType: dateTime
		formatString: General Date
		lineageTag: afbed5a5-ff3f-43d6-a51c-77626ead6a8a
		summarizeBy: none
		sourceColumn: Next_Day

		variation Variation
			isDefault
			relationship: f2326502-7ca7-4568-bfd9-bb617d4cee8b
			defaultHierarchy: LocalDateTable_6af56cde-645b-4557-b6a7-44423f96ebcf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Next_Day_112
		dataType: int64
		formatString: 0
		lineageTag: f0e8c1cf-3f16-481d-b0b4-02505ed1bdd3
		summarizeBy: sum
		sourceColumn: Next_Day_112

		annotation SummarizationSetBy = Automatic

	column Day_Of_Year
		dataType: int64
		formatString: 0
		lineageTag: d305d696-36e7-44d0-964a-b9419b5043d0
		summarizeBy: sum
		sourceColumn: Day_Of_Year

		annotation SummarizationSetBy = Automatic

	column Day_Of_Year_3_Char
		dataType: string
		lineageTag: d0339c85-249d-4320-9c1c-fabeff0722c6
		summarizeBy: none
		sourceColumn: Day_Of_Year_3_Char

		annotation SummarizationSetBy = Automatic

	column Day_Of_Fin_Year
		dataType: int64
		formatString: 0
		lineageTag: c50ef11c-ed27-4b5f-8d86-89e38ce86bda
		summarizeBy: sum
		sourceColumn: Day_Of_Fin_Year

		annotation SummarizationSetBy = Automatic

	column Day_Of_Fin_Year_3_Char
		dataType: string
		lineageTag: 09fd0b0d-7bef-4c4e-9787-56d1671f281a
		summarizeBy: none
		sourceColumn: Day_Of_Fin_Year_3_Char

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 095a3125-c064-4b11-8ae2-adb4addd04b3
		summarizeBy: none
		sourceColumn: created_date

		variation Variation
			isDefault
			relationship: 01b3b34f-de37-4ffe-b2b9-327f8fb936c0
			defaultHierarchy: LocalDateTable_2c84578c-511d-4ead-9ffe-fd0f0f568bc0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column import_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e7c37223-4771-449d-9901-93d30c29f297
		summarizeBy: none
		sourceColumn: import_date

		variation Variation
			isDefault
			relationship: cd0255ef-f0f3-40a3-acef-57a084eea54c
			defaultHierarchy: LocalDateTable_7cb1ac8e-5615-4295-847f-816075fc5556.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column YearMonthIndex =
			
			
			
			RANKX(
			    ALL('Date Reference'[year_month]),
			    'Date Reference'[year_month],
			    ,
			    ASC,
			    DENSE
			) - 1
		formatString: 0
		lineageTag: 33ffba3a-2947-4de6-8a54-8da7ec4673f0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SPC_flag = IF('Date Reference'[Fin_Year_yy_yy] = "23/24" || 'Date Reference'[Fin_Year_yy_yy] = "24/25", 1, 0)
		formatString: 0
		lineageTag: ba213a03-effc-4010-b406-b1d16b402c6c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Test_SPC_flag = 1
		formatString: 0
		lineageTag: 93fc2156-c3f5-41f0-b6a4-8ff1e768efcb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column New_YearMonthIndex = YEAR([Full_Date]) * 100 + MONTH([Full_Date])
		formatString: 0
		lineageTag: b622b66b-31f2-47c1-836e-fe8ea2b86d29
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'Fin_Year_yy_yy Hierarchy'
		lineageTag: 4f9d6cd9-7c82-45b8-9c21-9bd67fb4e557

		level Fin_Year_yy_yy
			lineageTag: 9a534207-b490-4ea3-93e8-5f6d7297eb26
			column: Fin_Year_yy_yy

		level Month_Name
			lineageTag: cf69f042-fc96-4b42-ad0b-391b44d77060
			column: Month_Name

	partition 'Date Reference' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "DSCRO_NATIONAL_LOOKUPS", [Query="select *#(lf)from DSCRO_NATIONAL_LOOKUPS.dbo.ref_Dates#(lf)#(lf)where cast(Full_Date as date) between '2023-04-01' and EOMONTH(getdate())#(lf)#(lf)order by Full_Date"]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

