table 'Date table (month start)'
	lineageTag: 4342a7b4-86eb-4763-a4ae-b8db83cbcc1f

	column 'Sort Financial Year' = ```
			
			 var _month = month('Date table (month start)'[Date])
			 var _result = IF(_month > 3, _month-3, _month+9)
			 return
			 _result
			```
		formatString: 0
		lineageTag: 859c4eee-486d-4d45-b160-71b429a0cd84
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6ef5454f-238c-4ebb-96ad-4c6b3a810fe3
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: bc910298-8537-48fd-9976-c008d854a216
			defaultHierarchy: LocalDateTable_9e21ca9f-c9ab-49eb-b9f5-17540860e39c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 470d2cdb-a77d-4155-80a8-af0afb762213
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: f231bb66-c2cd-4dde-80f0-31d8ec817c12
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 92eca4a4-bbb1-4990-abc8-1940a98b28cf
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 163e681b-3a58-46bf-922e-18d3ecbe6bc4
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: dad46f4c-c263-4bf8-988d-78d039ae059c
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column Day_Of_Month
		dataType: int64
		formatString: 0
		lineageTag: 489a3d93-ac3d-4a3c-b1b2-2da9ce686cc0
		summarizeBy: sum
		sourceColumn: Day_Of_Month

		annotation SummarizationSetBy = Automatic

	column Fin_Week_No
		dataType: int64
		formatString: 0
		lineageTag: 0841b6f4-4a42-489c-8db2-fa1592b900dc
		summarizeBy: sum
		sourceColumn: Fin_Week_No

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b50d8e4-c559-4c60-be60-4153197de11c
		summarizeBy: none
		sourceColumn: quarter_start_date

		variation Variation
			isDefault
			relationship: 63102e03-21ba-4487-a5ac-bf872d1ff65a
			defaultHierarchy: LocalDateTable_7a2b6701-c1d7-4e14-8fad-27cc9d374778.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e7bdd6e-1f6c-40e6-919e-3617f41d8a67
		summarizeBy: none
		sourceColumn: quarter_end_date

		variation Variation
			isDefault
			relationship: 73a898bb-6ee2-4637-b5a1-91decf63b563
			defaultHierarchy: LocalDateTable_7d212293-f541-4947-b390-42891df67835.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: 0999184d-639a-4639-ba2b-974cacbb0894
		summarizeBy: sum
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 17f5ccaa-a731-4acb-8993-5e94a5644f34
		summarizeBy: sum
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 0ecae054-5c6c-4d14-b98f-7f25d4efca2c
		summarizeBy: sum
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 1beb85a3-574b-467d-9533-2941050d8a62
		summarizeBy: sum
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 70be07be-975b-409e-98d2-b2b415eadc3d
		summarizeBy: sum
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: 494b6d27-03dc-4a8b-8f3c-29316e0b2f4c
		summarizeBy: sum
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	column last_week
		dataType: int64
		formatString: 0
		lineageTag: 684282e7-8b0f-4c70-a434-c0619a6af29b
		summarizeBy: sum
		sourceColumn: last_week

		annotation SummarizationSetBy = Automatic

	column last_week_minus_7
		dataType: int64
		formatString: 0
		lineageTag: 86b804f4-d2b1-43cc-be71-634de57b773a
		summarizeBy: sum
		sourceColumn: last_week_minus_7

		annotation SummarizationSetBy = Automatic

	column last_2_weeks
		dataType: int64
		formatString: 0
		lineageTag: 893d2fe6-8560-4dad-8857-4493f46f07b1
		summarizeBy: sum
		sourceColumn: last_2_weeks

		annotation SummarizationSetBy = Automatic

	column week_checker
		dataType: int64
		formatString: 0
		lineageTag: 57067b71-04be-424e-bf86-0d3329935b1e
		summarizeBy: sum
		sourceColumn: week_checker

		annotation SummarizationSetBy = Automatic

	column daymonthyear
		dataType: string
		lineageTag: e62c14d6-1d3b-4b26-9164-983b567bd446
		summarizeBy: none
		sourceColumn: daymonthyear

		annotation SummarizationSetBy = Automatic

	column yearmonth
		dataType: int64
		formatString: 0
		lineageTag: 44894bfe-035d-4139-a23a-32ad2b38e938
		summarizeBy: sum
		sourceColumn: yearmonth

		annotation SummarizationSetBy = Automatic

	column isweekend
		dataType: int64
		formatString: 0
		lineageTag: 259d3f5a-1e81-4d32-8775-605d15bf707c
		summarizeBy: sum
		sourceColumn: isweekend

		annotation SummarizationSetBy = Automatic

	column isholiday
		dataType: int64
		formatString: 0
		lineageTag: 997ed8c7-a90d-4689-8dc6-81ddcfa2a4a6
		summarizeBy: sum
		sourceColumn: isholiday

		annotation SummarizationSetBy = Automatic

	column holidaydescription
		dataType: string
		lineageTag: f3308828-372f-47cf-b3e6-85d564ca97cf
		summarizeBy: none
		sourceColumn: holidaydescription

		annotation SummarizationSetBy = Automatic

	column isworkingday
		dataType: int64
		formatString: 0
		lineageTag: 3e8845f1-2bc0-454a-b45e-1f9a148762bc
		summarizeBy: sum
		sourceColumn: isworkingday

		annotation SummarizationSetBy = Automatic

	column financialweekofyear
		dataType: int64
		formatString: 0
		lineageTag: 926bcd08-583e-4ccd-9ab4-92a29c478b46
		summarizeBy: sum
		sourceColumn: financialweekofyear

		annotation SummarizationSetBy = Automatic

	column financialquarter
		dataType: int64
		formatString: 0
		lineageTag: 86a560cf-d7b8-40e0-8fc2-f502b7f075ee
		summarizeBy: sum
		sourceColumn: financialquarter

		annotation SummarizationSetBy = Automatic

	column dayofquarter
		dataType: int64
		formatString: 0
		lineageTag: 537ab3a6-b79c-41c3-b43c-ee6b554f2a9f
		summarizeBy: sum
		sourceColumn: dayofquarter

		annotation SummarizationSetBy = Automatic

	column WeekStart
		dataType: dateTime
		formatString: General Date
		lineageTag: b516dbde-219b-4777-932b-1ac3eb71a286
		summarizeBy: none
		sourceColumn: WeekStart

		variation Variation
			isDefault
			relationship: 273d96f8-8342-48ac-896f-598fa6af3a31
			defaultHierarchy: LocalDateTable_4b917a54-a27f-4e29-873b-d75120057c77.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column WeekEnd
		dataType: dateTime
		formatString: General Date
		lineageTag: 7fb34a61-157e-4363-b230-192dc913911b
		summarizeBy: none
		sourceColumn: WeekEnd

		variation Variation
			isDefault
			relationship: 168911a3-6052-41bf-be99-b5ca011e636d
			defaultHierarchy: LocalDateTable_9e7e04c2-fcf8-45c7-88b2-b1bad6317319.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column financialmonth
		dataType: int64
		formatString: 0
		lineageTag: aedae1f3-b79a-434a-86d5-b855babde75d
		summarizeBy: sum
		sourceColumn: financialmonth

		annotation SummarizationSetBy = Automatic

	column monthyearname
		dataType: string
		lineageTag: 577752a0-f3ed-4413-b307-a3683a5ea1b4
		summarizeBy: none
		sourceColumn: monthyearname

		annotation SummarizationSetBy = Automatic

	column monthyear
		dataType: string
		lineageTag: 41368dca-ad13-4fb4-9a35-0d3023a6ff73
		summarizeBy: none
		sourceColumn: monthyear

		annotation SummarizationSetBy = Automatic

	column ytdflag
		dataType: int64
		formatString: 0
		lineageTag: f94886ff-5b92-46f6-9a87-a26dda3478b7
		summarizeBy: sum
		sourceColumn: ytdflag

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 96ead9f8-9c6f-47cc-ba79-03f8909716cd
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: financialmonth

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: f54f0d27-5086-4f03-b1ee-c4e03819183d
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	partition 'Date table (month start)' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="/*===============================================================================================================#(lf)New Date Reference Script#(lf)Created by: Ben Adams#(lf)Created Date: 27/12/2023#(lf)===============================================================================================================*/#(lf)#(lf)with date_cte as#(lf)(#(lf)SELECT DISTINCT [date] = CAST([Full_Date] AS DATE)#(lf)               ,[daymonthyear] = CONVERT(VARCHAR, [Full_Date], 103) --> 103 converts to DD/MM/YYYY format#(lf)#(tab)#(tab)#(tab)   ,[day] = [Day_Of_Fin_Year]#(lf)#(tab)#(tab)#(tab)   ,[weekday] = [Weekday_No]#(lf)#(tab)#(tab)#(tab)   ,[weekday_name] = [Weekday_Name]#(lf)#(tab)#(tab)#(tab)   ,[month] = [Month_No]#(lf)#(tab)#(tab)#(tab)   ,[MonthName] = [Month_Short_Name]#(lf)#(tab)#(tab)#(tab)   ,[quarter] = [Cal_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[yearmonth] = [Year_Month]#(lf)#(tab)#(tab)#(tab)   ,[isweekend] = CASE WHEN [Weekday_No] IN (6,7) THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[isholiday] = CASE WHEN [Bank_Holiday_Desc] IS NOT NULL THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[holidaydescription] = [Bank_Holiday_Desc] --> Description of holiday type i.e., 'Bank Holiday'#(lf)#(tab)#(tab)#(tab)   ,[isworkingday] = [Working_Day_Calc]#(lf)#(tab)#(tab)#(tab)   ,[financialweekofyear] = [Fin_Week_No]#(lf)#(tab)#(tab)#(tab)   ,[FinancialYear] = REPLACE([Fin_Year_YYYY_dash_YY], ' - ', '/')#(lf)#(tab)#(tab)#(tab)   ,[financialquarter] = [Fin_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[dayofquarter] = [Day_Of_Quarter]#(lf)#(tab)#(tab)#(tab)   ,day([Full_Date]) as [Day_Of_Month]#(lf)#(tab)#(tab)#(tab)   ,Fin_Week_No#(lf)#(tab)#(tab)#(tab) #(lf)#(tab)#(tab)#(tab)   ,[WeekStart] =    ---adjusted for Thursday #(lf)  DATEADD(DAY, #(lf)        CASE #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 1 THEN -4  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 2 THEN -5  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 3 THEN -6  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 4 THEN 0  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 5 THEN -1  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 6 THEN -2  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 7 THEN -3  #(lf)        END, #(lf)        CAST([Full_Date] AS DATE))#(lf)#(lf),[WeekEnd] = #(lf)#(tab)#(tab)   DATEADD(DAY, #(lf)        CASE #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 1 THEN -4 + 6  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 2 THEN -5 + 6  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 3 THEN -6 + 6  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 4 THEN 0 + 6  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 5 THEN -1 + 6  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 6 THEN -2 + 6  #(lf)            WHEN DATEPART(WEEKDAY, CAST([Full_Date] AS DATE)) = 7 THEN -3 + 6  #(lf)        END, #(lf)        CAST([Full_Date] AS DATE))#(lf)#(lf)#(lf)#(lf)#(tab)#(tab)#(tab)   ,[quarter_start_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[quarter_end_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[month_day_no] = [Month_Day_No]#(lf)#(tab)#(tab)#(tab)   ,[financialmonth] = [Fin_Month_No]#(lf)#(tab)#(tab)#(tab)   ,[monthyearname] = CONCAT([Month_Short_Name], '-', LEFT([Date_112], 4))#(lf)#(tab)#(tab)#(tab)   ,[monthyear] = [MonthYear_MMMM_YYYYY]#(lf)#(tab)#(tab)#(tab)   ,[ytdflag] = CASE WHEN [Fin_Month_No] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([Fin_Month_No] AS INT)#(lf)                                           FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Full_Date] = EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END --> Establishes whether the month is included in year to date calculations and reflects across all years#(lf)#(tab)#(tab)#(tab)   ,[latest_month_flag] = CASE WHEN [Year_Month] IN #(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_month_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -2, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The month before the latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[latest_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                             (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                              FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -12, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      THEN 1 ELSE 0 END --> The latest 12 months within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                               (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                                FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -24, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)    AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        THEN 1 ELSE 0 END --> The 12 months before the latest 12 months within your date range - allows comparing current to previous#(lf)#(tab)#(tab)#(tab)   ,[same_month_last_year_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                                 (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END --> Same month last year as the latest month within the date range i.e., Nov-22 and Nov-23#(lf)#(tab)#(tab)#(tab),[last_week] = case when Week_Start_112 =#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)(SELECT DISTINCT MAX(Previous_Week_Start_112)#(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates] [a]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE cast([Full_Date] as date) =cast(GETDATE()  as date))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END #(lf)#(tab)#(tab)#(tab),[last_week_minus_7] = case when Week_Start_112 =#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)(SELECT DISTINCT MAX(Previous_Week_Start_112)#(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates] [a]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE cast([Full_Date] as date) =dateadd(day,-7,cast(GETDATE()  as date)))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END #(lf)#(tab)#(tab)#(tab),[last_2_weeks] = case when Week_Start_112 =#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)(SELECT DISTINCT MAX(Previous_Week_Start_112)#(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates] [a]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE cast([Full_Date] as date) =cast(GETDATE()  as date))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) when Week_Start_112 =#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)(SELECT DISTINCT MAX(Previous_Week_Start_112)#(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates] [a]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE cast([Full_Date] as date) =dateadd(day,-7,cast(GETDATE()  as date)))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END #(lf) #(lf) --INTO #date_ref#(lf)#(lf)FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)),#(lf)date1_cte as#(lf)(#(lf)SELECT *#(lf),[week_checker] = CASE WHEN CAST(GETDATE() AS DATE) < dateadd(day,+7,[WeekEnd]) THEN 1 ELSE 0 END#(lf)FROM date_cte#(lf))#(lf)SELECT *#(lf)FROM date1_cte#(lf)WHERE [week_checker] = 0 and [date] >= '20190401'#(lf)order by [date] desc"]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Day_Of_Month] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

