table 'Ref - Age'
	lineageTag: babe0917-f923-49af-9020-1d68bc558f38

	column Derived_Age
		dataType: int64
		formatString: 0
		lineageTag: 6cc7c1c0-2546-4384-b6a8-1b0f5ce89077
		summarizeBy: none
		sourceColumn: Derived_Age

		annotation SummarizationSetBy = Automatic

	column AgeBand5yr
		dataType: string
		lineageTag: d47b5d45-f4b7-4457-a6ae-12b4c27d395e
		summarizeBy: none
		sourceColumn: AgeBand5yr

		annotation SummarizationSetBy = Automatic

	column AgeBand10yr
		dataType: string
		lineageTag: cc9ef483-3891-42a5-8fc1-b85096d5c9ee
		summarizeBy: none
		sourceColumn: AgeBand10yr

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: 8edad08a-02a8-490c-96a2-d13d4353221b
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	partition 'Ref - Age' = m
		mode: import
		source =
				let
				    Source = #"Ref - Source Table",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Derived_Age", "AgeBand5yr", "AgeBand10yr", "AgeBand"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Derived_Age"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

