table 'Tirzepatide Cohorts'
	lineageTag: 4fade908-f43c-4203-98fc-119e0a040cd8

	measure PrescribingStartFlag
		lineageTag: 2fd64806-38ab-4848-b47d-70c6f5af6243

	measure %_Patients_Prescribed_Tirzep =
			
			VAR Numerator = calculate(count('Tirzepatide Cohorts'[Derived_NHS_Number]),'Tirzepatide Cohorts'[Already on WL Drug] = "Tirzepatide")+calculate(count('Tirzepatide Cohorts'[Derived_NHS_Number]),'Tirzepatide Cohorts'[Already on WL Drug] = "Tirzepatide  -National Programme")
			VAR Denominator = calculate(count('Tirzepatide Cohorts'[Derived_NHS_Number]))
			
			RETURN Numerator/Denominator
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5ab88ba7-cad7-492b-b08b-3928b7fa8e78

	measure Title_Elidgible_TZ_Chart =
			
			VAR CohortSelected =
			    SELECTEDVALUE(
			        'Tirzepatide Cohorts'[Cohort],
			        "All Cohorts"
			    )
			RETURN
			"Total " & CohortSelected&" Patients: By Prescription Type"
		lineageTag: df1decd0-3392-4f89-aee9-169f24552bdc

	measure Patients = if(calculate(count('Tirzepatide Cohorts'[Derived_NHS_Number]))=0,0,calculate(count('Tirzepatide Cohorts'[Derived_NHS_Number])))
		formatString: 0
		lineageTag: fbe58403-ea11-4002-b62f-fd234dfa287a

	column Derived_NHS_Number
		dataType: string
		lineageTag: eedde88e-93bc-47a9-98f0-0062d54367e3
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column 'BMI Value'
		dataType: double
		lineageTag: 68773257-01c6-4848-8861-304354ab3543
		summarizeBy: sum
		sourceColumn: BMI Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BMI Value - Adjusted'
		dataType: double
		lineageTag: 25316d43-d988-4dee-a99f-d853c0e2bdfc
		summarizeBy: sum
		sourceColumn: BMI Value - Adjusted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Obesity Group'
		dataType: string
		lineageTag: ff0fd12f-1c8d-473a-a370-40aa50fd2686
		summarizeBy: none
		sourceColumn: Obesity Group

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: a7079ffb-5943-4e10-9ebf-734e638acb66
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 87f9e1d7-1faf-4015-b595-1386b2563d62
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: daf17507-b8b6-4a63-88ba-a44de3eac9f0
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column PrimaryCareProvider
		dataType: string
		lineageTag: 4df7d946-3e19-4cef-87f9-fc512e57b223
		summarizeBy: none
		sourceColumn: PrimaryCareProvider

		annotation SummarizationSetBy = Automatic

	column Hypertension
		dataType: int64
		formatString: 0
		lineageTag: 33cd1f9c-cc86-415c-89da-f73462b3ce96
		summarizeBy: sum
		sourceColumn: Hypertension

		annotation SummarizationSetBy = Automatic

	column 'Dyslipidemia - LLT or Out of Threshold'
		dataType: int64
		formatString: 0
		lineageTag: 4748319f-2c10-4cbc-b04d-87abfc94b87f
		summarizeBy: sum
		sourceColumn: Dyslipidemia - LLT or Out of Threshold

		annotation SummarizationSetBy = Automatic

	column 'Obstructive sleep apnoea'
		dataType: int64
		formatString: 0
		lineageTag: 739e3f4d-7682-4a15-8cff-f6fdc0a0516d
		summarizeBy: sum
		sourceColumn: Obstructive sleep apnoea

		annotation SummarizationSetBy = Automatic

	column 'Athelerosclerotic Cardiovascular disease'
		dataType: int64
		formatString: 0
		lineageTag: a70a18b4-0974-4ed4-b63e-f45d51597af7
		summarizeBy: sum
		sourceColumn: Athelerosclerotic Cardiovascular disease

		annotation SummarizationSetBy = Automatic

	column 'Type 2 Diabetes Mellitus'
		dataType: int64
		formatString: 0
		lineageTag: d9efec9d-9ac1-453d-af14-6023919f7cb1
		summarizeBy: sum
		sourceColumn: Type 2 Diabetes Mellitus

		annotation SummarizationSetBy = Automatic

	column 'Hypertension - Not TTT'
		dataType: int64
		formatString: 0
		lineageTag: 5a05d548-99e1-4e2d-9557-10f105c9bb55
		summarizeBy: sum
		sourceColumn: Hypertension - Not TTT

		annotation SummarizationSetBy = Automatic

	column Cohort
		dataType: string
		lineageTag: 6c6fac57-978b-4272-a428-ad4dfed8a59d
		summarizeBy: none
		sourceColumn: Cohort

		annotation SummarizationSetBy = Automatic

	column 'Already on WL Drug'
		dataType: string
		lineageTag: 686998ab-d60b-4f3c-b5a7-ff25e7b35fa4
		summarizeBy: none
		sourceColumn: Already on WL Drug

		annotation SummarizationSetBy = Automatic

	column 'Already on WL Drug Flag'
		dataType: int64
		formatString: 0
		lineageTag: 0c2c5828-d99d-4aaf-b5fb-5cac5c6ac97e
		summarizeBy: sum
		sourceColumn: Already on WL Drug Flag

		annotation SummarizationSetBy = Automatic

	column MonthStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd28ac3f-ff02-49f1-af5c-417006d05ad2
		summarizeBy: none
		sourceColumn: MonthStart

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthEnd
		dataType: dateTime
		formatString: Long Date
		lineageTag: f5ae5f52-3490-411a-a956-ecabfb79441a
		summarizeBy: none
		sourceColumn: MonthEnd

		variation Variation
			isDefault
			relationship: 2089a812-58cb-4ce0-a73e-750ecaf602d6
			defaultHierarchy: LocalDateTable_2fa4063f-f52b-4748-9a82-140d398d076e.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: a3a5fbb5-4d24-4e08-a5fd-10e2c4ebf250
		summarizeBy: none
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column PrimaryCareProvider_description
		dataType: string
		lineageTag: a7dc0ad5-7d5f-409d-b61f-fe1fd85d3f29
		summarizeBy: none
		sourceColumn: PrimaryCareProvider_description

		annotation SummarizationSetBy = Automatic

	partition 'Tirzepatide Cohorts' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select *#(lf)from [PowerBI_Reporting].[WeightManagement].[tbl05_Tirzepatide_Cohorts]#(lf)where [Cohort] is not null"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,null,"Not Prescribed",Replacer.ReplaceValue,{"Already on WL Drug"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

