table 28days_Referrals
	lineageTag: 699eceb2-5de1-4d5a-92ca-c25b4c04ca13

	column clientid
		dataType: int64
		formatString: 0
		lineageTag: 0cee082d-6e19-454d-9ec6-f81ec16f9d1a
		summarizeBy: none
		sourceColumn: clientid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column funder
		dataType: string
		lineageTag: 2374b400-45b2-4b6c-ab85-b45eecbcac08
		summarizeBy: none
		sourceColumn: funder

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column nurseassessor
		dataType: string
		lineageTag: fe9f323a-8472-403e-93b8-45136ee4c8d3
		summarizeBy: none
		sourceColumn: nurseassessor

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column ccg
		dataType: string
		lineageTag: 67c5823c-e6db-4398-bd32-c6d6b86a95a9
		summarizeBy: none
		sourceColumn: ccg

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column sourceofreferral
		dataType: string
		lineageTag: ea8e3021-242d-4089-9941-9054174b4dae
		summarizeBy: none
		sourceColumn: sourceofreferral

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column sourceofreferralname
		dataType: string
		lineageTag: f141727f-89a1-40c3-9e2a-531c8250cb49
		summarizeBy: none
		sourceColumn: sourceofreferralname

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column carecat
		dataType: string
		lineageTag: 7e346ffd-4144-41f4-89e8-5bb2c7e2a088
		summarizeBy: none
		sourceColumn: carecat

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column dstsetting
		dataType: string
		lineageTag: 9b96f6e6-f951-44e0-8029-2360cbcab45c
		summarizeBy: none
		sourceColumn: dstsetting

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fasttrack
		dataType: string
		lineageTag: b2018b19-1eb4-46d9-b51e-688b8351cb9a
		summarizeBy: none
		sourceColumn: fasttrack

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fasttrackdate
		dataType: string
		lineageTag: 96f839cf-3423-4a40-a24b-5828922c4f9d
		summarizeBy: none
		sourceColumn: fasttrackdate

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column checklist
		dataType: dateTime
		formatString: Long Date
		lineageTag: f9a3a573-bdf1-4a4a-8a05-a5904b906b66
		summarizeBy: none
		sourceColumn: checklist

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column dst
		dataType: dateTime
		formatString: Long Date
		lineageTag: 94fb35b7-1702-4386-94b9-babb84ad64e6
		summarizeBy: none
		sourceColumn: dst

		variation Variation
			isDefault
			relationship: 066e996d-eb84-461a-93ef-3344062895f9
			defaultHierarchy: LocalDateTable_12f82161-783b-4d3e-ae3a-a782445ebfdd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column mdtrecommendation
		dataType: dateTime
		formatString: Long Date
		lineageTag: aeff2c51-13ec-41e1-a5d8-8e983f602df6
		summarizeBy: none
		sourceColumn: mdtrecommendation

		variation Variation
			isDefault
			relationship: 9741b30f-f3d5-479a-b6ae-c4937cbb60cb
			defaultHierarchy: LocalDateTable_07eb61e0-fb6b-44a3-be8a-ea6fc2ec06aa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column decision
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2fd64a02-b669-49bc-b87f-9d4d2ca861d8
		summarizeBy: none
		sourceColumn: decision

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column outcome
		dataType: string
		lineageTag: ef581f4a-0314-43eb-b9ba-2d59a45b8fe6
		summarizeBy: none
		sourceColumn: outcome

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column extractdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c8ec49ad-376e-4270-8b33-24616a96db89
		summarizeBy: none
		sourceColumn: extractdate

		variation Variation
			isDefault
			relationship: 93fa192f-a050-4938-a8e8-818702f78d7f
			defaultHierarchy: LocalDateTable_9fccf018-1bd4-4937-b3b8-16ca60aefb6e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column filename
		dataType: string
		lineageTag: 3b34d98d-6e96-426d-a2e2-b6acdcf7b403
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column agreementid
		dataType: string
		lineageTag: 0385a24c-2d26-4584-9ec4-d36043127d74
		summarizeBy: none
		sourceColumn: agreementid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column last_updated
		dataType: dateTime
		formatString: General Date
		lineageTag: cdb42ab7-6dd1-486a-bb34-5db8cd49e31d
		summarizeBy: none
		sourceColumn: last_updated

		variation Variation
			isDefault
			relationship: 3aec7a24-e02e-4314-869a-9d1a709b2303
			defaultHierarchy: LocalDateTable_51acfabb-5564-4b56-88af-9236c81548e5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 56a8c6db-c89c-47bf-82d1-4de0c22cc21f
		summarizeBy: none
		sourceColumn: deleted

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Completed days' =
			
			DATEDIFF (
			    '28days_Referrals'[checklist],
			    '28days_Referrals'[decision],
			    DAY
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: 98c3bab5-495c-4f71-ba08-f24ea4ffffba
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'current Outstanding over 12w' =
			
			IF (
			    DATEDIFF (
			        '28days_Referrals'[checklist],
			        TODAY (),
			        DAY
			    ) > ( 12 * 7 )
			        && ISBLANK ( '28days_Referrals'[decision] ),
			    1,
			    0
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: 3c89f26c-0c42-4820-8a5a-87e7f9a8be96
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'MDT assessment Days' =
			
			DATEDIFF (
			    '28days_Referrals'[checklist],
			    '28days_Referrals'[mdtrecommendation],
			    DAY
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: 4a61c0bb-9d21-49ae-b2de-2bce9447fadb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Verification Days' =
			
			DATEDIFF (
			    '28days_Referrals'[checklist],
			    '28days_Referrals'[decision],
			    DAY
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: ff28e45c-b7ae-47e7-81bf-2f292e726d39
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Open Cases exceeding 28days breakdown' =
			
			VAR daysdiff =
			    DATEDIFF (
			        '28days_Referrals'[checklist],
			        TODAY (),
			        DAY
			    ) - 28
			RETURN
			    SWITCH (
			        TRUE,
			        NOT (
			            ISBLANK ( '28days_Referrals'[decision] )
			        ), BLANK (),
			        daysdiff <= 0, BLANK (),
			        daysdiff <= 14, "0-2 weeks (1-14 Days)",
			        daysdiff <= 28, "2-4 weeks (15-28 Days)",
			        daysdiff <= 84, "4-12 weeks (29-84 Days)",
			        daysdiff <= 182, "12-26 weeks (85-182 Days)",
			        "26+ weeks (183+ Days)"
			    )
		displayFolder: _DAX_Columns
		lineageTag: 0457b461-342c-4eff-907d-9fe07168421b
		summarizeBy: none
		sortByColumn: 'Open Cases exceeding 28days Sort'

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	column 'Open Cases exceeding 28days Sort' =
			
			VAR daysdiff =
			    DATEDIFF (
			        '28days_Referrals'[checklist],
			        TODAY (),
			        DAY
			    ) - 28
			RETURN
			    SWITCH (
			        TRUE,
			        NOT (
			            ISBLANK ( '28days_Referrals'[decision] )
			        ), BLANK (),
			        daysdiff <= 0, BLANK (),
			        daysdiff <= 14, 1,
			        daysdiff <= 28, 2,
			        daysdiff <= 84, 3,
			        daysdiff <= 182, 4,
			        5
			    )
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: 87ac4c0d-e029-4253-9ab6-ca0ac7a95809
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Open Cases exceeding 28days breakdown dashview' =
			
			VAR daysdiff =
			    DATEDIFF (
			        '28days_Referrals'[checklist],
			        TODAY (),
			        DAY
			    ) - 28
			RETURN
			    SWITCH (
			        TRUE,
			        NOT (
			            ISBLANK ( '28days_Referrals'[decision] )
			        ), BLANK (),
			        daysdiff <= 0, BLANK (),
			        daysdiff <= 14, "0-2 weeks",
			        daysdiff <= 28, "2-4 weeks",
			        daysdiff <= 84, "4-12 weeks",
			        daysdiff <= 182, "12-26 weeks",
			        "26+ weeks"
			    )
		lineageTag: 658e82be-acd1-4fe1-8cc0-400dad2bbcb4
		summarizeBy: none
		sortByColumn: 'Open Cases exceeding 28days breakdown dashview sort'

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	column 'Open Cases exceeding 28days breakdown dashview sort' =
			
			VAR daysdiff =
			    DATEDIFF (
			        '28days_Referrals'[checklist],
			        TODAY (),
			        DAY
			    ) - 28
			RETURN
			    SWITCH (
			        TRUE,
			        NOT (
			            ISBLANK ( '28days_Referrals'[decision] )
			        ), BLANK (),
			        daysdiff <= 0, BLANK (),
			        daysdiff <= 14, "1",
			        daysdiff <= 28, "2",
			        daysdiff <= 84, "3",
			        daysdiff <= 182, "4",
			        "5"
			    )
		lineageTag: 8b1e879b-1fb7-4728-8457-f6c3d8a358f8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 28days_Referrals-323950bd-dc44-44eb-ac2b-da04226b7254 = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    vw_28days_201_load1 = data_mart_pid_011_chs_continuinghealthcare{[Name="vw_28days_201_load"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vw_28days_201_load1,{{"checklist", type date}, {"dst", type date}, {"mdtrecommendation", type date}, {"decision", type date}, {"extractdate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

