table 'Benchmarking order'
	lineageTag: 16d85903-538a-4095-a271-6afcd03f101e

	column Metric
		dataType: string
		lineageTag: 13e6df80-effb-4161-81a5-20bb3fac54f0
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 2ed0a79c-6505-4071-bf13-60a24542e3ff
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Benchmarking order-0b9346ac-66cc-45d6-9bbc-9e9d5f97be08' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fc7LCsIwEAXQXxmy7sb66lZSxZWIFkRKFrEdazBNZSb4/YZSF6mP9Zx775SlOOAVibRlkF37sOixhqPXrtZUg9xKkYiJUMl3uNHsoSBd3Qea9nTFjMwtOh+seyKx6dy4dfqHfvTOfr5wMv5mHKRZDnukKhTpBkNi3ifW1jTmYjEah3ORB7GIRbw5mOXI7N6HTCj1Ag==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

