table 'Open Cases Age Bands'
	lineageTag: 218135fe-5e37-4305-986f-6867e1626bb9

	column 'Days Over'
		dataType: string
		lineageTag: 0bfd8875-a4f9-4172-9f4d-64763760f2f1
		summarizeBy: none
		sourceColumn: Days Over
		sortByColumn: sort

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["SortByColumn"]

	column sort
		dataType: string
		lineageTag: e3e3b316-49bb-47a1-a736-285f2f9274a0
		summarizeBy: none
		sourceColumn: sort

		annotation SummarizationSetBy = Automatic

	partition 'Open Cases Age Bands-68f6b571-c573-471e-b0e9-fe83a97cacbc' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Rc0xDoAgEETRq5CtNDCJu4BZe29BKCyoLCmMtzfBuNbvT6YUWiDuau3sbmJwcvtx95kCMdVQSJBMM0SNZXAC21o26D+Pw1kg6xdoBqtYkd6D1duBRm+aqdYH", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Open Cases Exceeding" = _t, sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Open Cases Exceeding", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Open Cases Exceeding", "Days Over"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ChangedProperties = ["Name"]

