table PHB
	lineageTag: b17177c5-32c6-4662-9e1d-280a26e1b168

	column clientid
		dataType: int64
		formatString: 0
		lineageTag: 97d6ded9-6fa3-4e4b-91fa-4fbc85bcb0c1
		summarizeBy: none
		sourceColumn: clientid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column funder
		dataType: string
		lineageTag: 3c4b3530-b04b-47e3-85ba-2a92cc85cef3
		summarizeBy: none
		sourceColumn: funder

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column riskassessment
		dataType: string
		lineageTag: f088742c-4456-414e-9d2b-baf1c2405c8f
		summarizeBy: none
		sourceColumn: riskassessment

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column riskassessmentdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7907ff8-b70b-413b-9b04-fe0bcb69c2c5
		summarizeBy: none
		sourceColumn: riskassessmentdate

		variation Variation
			isDefault
			relationship: 454ff288-6bee-4bea-a124-d26b0675e524
			defaultHierarchy: LocalDateTable_4d7ec2de-f519-4a37-95f0-a903200fef54.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column riskassessmentwho
		dataType: string
		lineageTag: e2a2f76d-b804-45cd-8c8d-29088f5495da
		summarizeBy: none
		sourceColumn: riskassessmentwho

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column riskassessmentoutcome
		dataType: string
		lineageTag: 8f8c9ca3-63df-46c6-a28e-addc9695b81a
		summarizeBy: none
		sourceColumn: riskassessmentoutcome

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column phboffered
		dataType: string
		lineageTag: b9972eed-9d46-4475-ab60-bfb3a90faa10
		summarizeBy: none
		sourceColumn: phboffered

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column offerdate
		dataType: dateTime
		formatString: Short Date
		lineageTag: bba5889b-55ea-491c-a920-8fbd32fe6d3c
		summarizeBy: none
		sourceColumn: offerdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["FormatString","IsHidden"]

	column clientdecision
		dataType: string
		lineageTag: 7855bcc6-65cf-4b05-9429-386c8ccbef34
		summarizeBy: none
		sourceColumn: clientdecision

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column contractsent
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3635067-b0df-42f0-ac72-6e43acf6b27b
		summarizeBy: none
		sourceColumn: contractsent

		variation Variation
			isDefault
			relationship: ef22bba0-5355-48ef-879e-3868aad6044b
			defaultHierarchy: LocalDateTable_a6ebbdef-2750-45de-8982-903fe90a53e6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column contractreturned
		dataType: dateTime
		formatString: Long Date
		lineageTag: 14da28b9-ed07-46b7-b29c-2f741edfc85a
		summarizeBy: none
		sourceColumn: contractreturned

		variation Variation
			isDefault
			relationship: 48f65b7f-808d-4f38-bc78-66a7255739c6
			defaultHierarchy: LocalDateTable_7a6e4fde-9e87-41f8-8aa6-36b1b4112b53.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column budgettool
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ff900f75-2843-4288-9f65-a14b6f0ae32d
		summarizeBy: none
		sourceColumn: budgettool

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column budgettoolwhen
		dataType: string
		lineageTag: dbaf707a-bd11-48fa-93aa-fc0e848b98c2
		summarizeBy: none
		sourceColumn: budgettoolwhen

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column budgettoolwho
		dataType: string
		lineageTag: 9621661d-b91a-4737-80a7-433a798a00d2
		summarizeBy: none
		sourceColumn: budgettoolwho

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column indicativebudget
		dataType: int64
		formatString: 0
		lineageTag: 4a7a9e29-f1ba-43b9-baeb-1678e394454c
		summarizeBy: sum
		sourceColumn: indicativebudget

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column indicativebudgetper
		dataType: string
		lineageTag: 1a4e0215-2fe9-45e1-95bd-2e4fbdc226b8
		summarizeBy: none
		sourceColumn: indicativebudgetper

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column budgetvalue
		dataType: double
		lineageTag: 2adaf666-fe77-49e8-bf01-55122ccc8d10
		summarizeBy: sum
		sourceColumn: budgetvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation PBI_ChangedProperties = ["IsHidden"]

	column per
		dataType: string
		lineageTag: fe7d58d4-997f-4b66-bd11-777110494aee
		summarizeBy: none
		sourceColumn: per

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column budgetstart
		dataType: dateTime
		formatString: Long Date
		lineageTag: deb7cf23-c510-413b-bf79-e147f4828c63
		summarizeBy: none
		sourceColumn: budgetstart

		variation Variation
			isDefault
			relationship: d9eb921d-eb9a-4d31-8186-ed4484300852
			defaultHierarchy: LocalDateTable_bcd2a46f-9077-48c9-aad7-366ae49a4e58.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column budgetend
		dataType: dateTime
		formatString: Long Date
		lineageTag: adc4f0ad-4d23-4dad-a678-b05ea46ec19f
		summarizeBy: none
		sourceColumn: budgetend

		variation Variation
			isDefault
			relationship: f7bfb8db-a307-4c8a-9889-afc533db63c8
			defaultHierarchy: LocalDateTable_335d898b-ced3-47ad-8ff3-1a21b2c91647.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column outcomesagreed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c5e3e67f-b0e1-4c4b-9e62-ea2c2c92316c
		summarizeBy: none
		sourceColumn: outcomesagreed

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column extractdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f2b85222-e9f1-4682-8566-6ab5c88dd4fd
		summarizeBy: none
		sourceColumn: extractdate

		variation Variation
			isDefault
			relationship: 82743c3b-bfdd-4d65-9c93-3ea6617c2e49
			defaultHierarchy: LocalDateTable_de8279f7-1933-4089-a6ff-84672d580e17.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column filename
		dataType: string
		lineageTag: 724cd32f-dd25-42c9-8cc9-e77a720b633f
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column agreementid
		dataType: string
		lineageTag: 79d33ac1-425f-470f-b99a-94c1e8b0a48a
		summarizeBy: none
		sourceColumn: agreementid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column last_updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 178b05d1-b9f7-41e5-820d-c872dbdeafd0
		summarizeBy: none
		sourceColumn: last_updated

		variation Variation
			isDefault
			relationship: f73baad7-03d8-4d3d-9937-b4d3235a5e7b
			defaultHierarchy: LocalDateTable_28357b46-8b04-407a-8a41-2967d807bbf9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 35cafeb7-840d-4c6d-8ce8-fbcb7e0022ee
		summarizeBy: none
		sourceColumn: deleted

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	partition PHB-55fe0b20-8c63-49e6-8c94-4b09c60ddd2e = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    vw_phb_201_load1 = data_mart_pid_011_chs_continuinghealthcare{[Name="vw_phb_201_load"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vw_phb_201_load1,{{"riskassessmentdate", type date}, {"offerdate", type date}, {"contractsent", type date}, {"contractreturned", type date}, {"budgetstart", type date}, {"budgetend", type date}, {"extractdate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

