table Theograph
	lineageTag: 1ab00743-f74c-41d7-aa5e-0339c048a0ce

	column NHS_Number
		dataType: string
		lineageTag: 2bf6a900-a8ce-4c45-ab19-8b17f7c24034
		summarizeBy: none
		sourceColumn: NHS_Number

		annotation SummarizationSetBy = Automatic

	column Setting
		dataType: string
		lineageTag: d4873ae7-77c3-435f-a93f-c760baffc110
		summarizeBy: none
		sourceColumn: Setting

		annotation SummarizationSetBy = Automatic

	column Event
		dataType: string
		lineageTag: 2aaeca10-7bd1-4cea-b302-9f8aa0064670
		summarizeBy: none
		sourceColumn: Event

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 714c7ae9-f419-4d0e-bf8a-4fcb46c30d03
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 41e21dab-bc05-4cf5-9da9-5716cda0fda6
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: b68a28ad-0087-4e9f-b286-85271e44eeca
			defaultHierarchy: LocalDateTable_259ba8b8-6487-4076-a89e-cb3cb7f1f5c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column StartMonth
		dataType: string
		lineageTag: 6321f618-6352-4d11-b65f-f514cf949f77
		summarizeBy: none
		sourceColumn: StartMonth

		annotation SummarizationSetBy = Automatic

	column StartYear
		dataType: int64
		formatString: 0
		lineageTag: 53bdcfc3-517f-4421-b8b7-87924bc5d210
		summarizeBy: sum
		sourceColumn: StartYear

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: eadb0d20-45d9-49b5-9fc1-f37ca707cbcd
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: 2df9e0a9-d690-47bb-bbe8-60659f9a2629
			defaultHierarchy: LocalDateTable_538d2e71-9e4b-42c0-af0a-957ce8e906db.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ServiceDischargeDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: ce884df0-0169-4e25-b525-11d8395ef4e4
		summarizeBy: none
		sourceColumn: ServiceDischargeDate

		variation Variation
			isDefault
			relationship: 57687f83-3333-4bd2-bc01-99de1dd5d53f
			defaultHierarchy: LocalDateTable_d945f263-64f9-4dc6-8b0a-61d5a6c1c989.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Duration
		dataType: int64
		formatString: 0
		lineageTag: 18087327-e3a2-4df8-8c45-420ba842cff4
		summarizeBy: sum
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

	column Intervention
		dataType: dateTime
		formatString: Short Date
		lineageTag: 831142c2-293f-4600-ada1-424b29fbd053
		summarizeBy: none
		sourceColumn: Intervention

		variation Variation
			isDefault
			relationship: 2cd75213-c2fa-4381-93ba-607b2e6af17f
			defaultHierarchy: LocalDateTable_39262653-ca6e-4465-9b37-d712d8f90af3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InterventionMonth
		dataType: string
		lineageTag: 057d29f3-93b5-48cf-9f50-22152eeb6a04
		summarizeBy: none
		sourceColumn: InterventionMonth

		annotation SummarizationSetBy = Automatic

	column Diagnosis
		dataType: string
		lineageTag: c9d042e7-8880-4c32-af03-75b46b55f757
		summarizeBy: none
		sourceColumn: Diagnosis

		annotation SummarizationSetBy = Automatic

	column StartDateForPlot
		dataType: dateTime
		formatString: General Date
		lineageTag: 61e0f0cd-4ceb-4ef7-afe9-febafb4ff92a
		summarizeBy: none
		sourceColumn: StartDateForPlot

		variation Variation
			isDefault
			relationship: ca45dcd8-0c12-4e59-adac-b4e3aa94d739
			defaultHierarchy: LocalDateTable_3c9fb988-d56c-431b-9b06-c77c6319d4be.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDateForPlot
		dataType: dateTime
		formatString: General Date
		lineageTag: c448546f-9f7d-4776-a9bf-d5739dddf088
		summarizeBy: none
		sourceColumn: EndDateForPlot

		variation Variation
			isDefault
			relationship: 696fc55e-fb83-40c9-be72-5d691c013006
			defaultHierarchy: LocalDateTable_65b65fc4-bdf0-4d1e-9775-f725a4dc4a5c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column InterventionForPlot
		dataType: dateTime
		formatString: General Date
		lineageTag: b5f0bc83-36d6-4aa8-915e-0d97c3693765
		summarizeBy: none
		sourceColumn: InterventionForPlot

		variation Variation
			isDefault
			relationship: 1ad63e13-85a7-43cb-9ea2-45591208d9a6
			defaultHierarchy: LocalDateTable_000f8d11-4138-4aff-a91b-bf8ad39d5686.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition Theograph = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Sandbox", [Query="SELECT  [NHS_Number]#(lf)      ,[Setting]#(lf)      ,[Event]#(lf)      ,[Type]#(lf)      ,[StartDate] = cast ([StartDate] as date)#(lf)      ,[StartMonth]#(lf)      ,[StartYear]#(lf)      ,[EndDate]= cast([EndDate] as date)#(lf)      ,[ServiceDischargeDate]  = cast([ServiceDischargeDate] as date)#(lf)      ,[Duration]#(lf)      ,[Intervention] = cast([Intervention] as date)#(lf)      ,[InterventionMonth]#(lf)      ,[Diagnosis]#(lf)#(tab) , DATEADD(HOUR, 12, CAST(StartDate AS datetime)) AS StartDateForPlot,#(lf)  DATEADD(HOUR, 12, CAST(EndDate   AS datetime)) AS EndDateForPlot,#(lf)  DATEADD(HOUR, 12, CAST([Intervention] AS datetime)) AS InterventionForPlot#(lf)#(lf)#(lf)  FROM [Sandbox].[dbo].[TheographData]#(lf)"]),
				    #"Extracted Date" = Table.TransformColumns(Source,{{"StartDate", DateTime.Date, type date}, {"EndDate", DateTime.Date, type date}, {"ServiceDischargeDate", DateTime.Date, type date}, {"Intervention", DateTime.Date, type date}})
				in
				    #"Extracted Date"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

