table '8CP & 3TT (National)'
	lineageTag: e47b395c-871c-407a-9f34-5a6064f85fd7

	measure %_8CP_Nat = calculate(sum('8CP & 3TT (National)'[ALL EIGHT CARE PROCESSES_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[ALL EIGHT CARE PROCESSES_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cea07664-2119-40db-876a-4efb33f45bfa

	measure %_3TT_Nat = calculate(sum('8CP & 3TT (National)'[ALL THREE TREATMENT TARGETS (2024)_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[ALL THREE TREATMENT TARGETS (2024)_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6f16f094-cd35-4b8b-9352-e0de174e82fd

	measure %_BP_Nat = calculate(sum('8CP & 3TT (National)'[BLOOD PRESSURE_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[BLOOD PRESSURE_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 98748d40-6cff-479d-b8b0-d43e1fda0ccb

	measure %_BMI_Nat = calculate(sum('8CP & 3TT (National)'[BMI_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[BMI_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 48c0ae6d-2565-4f47-9e85-af356065ce17

	measure %_CHOL_Nat = calculate(sum('8CP & 3TT (National)'[CHOLESTEROL_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[CHOLESTEROL_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 55b981a4-55be-4d12-98d0-18e507dc9c9f

	measure %_CREA_Nat = calculate(sum('8CP & 3TT (National)'[SERUM CREATININE_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[SERUM CREATININE_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2db044e5-8342-41d9-9aaa-54a15555626b

	measure %_FOOT_Nat = calculate(sum('8CP & 3TT (National)'[FOOT SURVEILLANCE_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[FOOT SURVEILLANCE_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ed6a7108-d820-4ee9-83f3-4b29ea263455

	measure %_HBA1C_Nat = calculate(sum('8CP & 3TT (National)'[HBA1C_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[HBA1C_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 26d28a45-cbf1-4de8-8338-9cfbe18119ff

	measure %_SMOK_Nat = calculate(sum('8CP & 3TT (National)'[SMOKING_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[SMOKING_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5ef54028-6715-443e-a21b-08203f9ffe00

	measure %_URIN_Nat = calculate(sum('8CP & 3TT (National)'[URINE ALBUMIN_NUMERATOR]))/calculate(sum('8CP & 3TT (National)'[URINE ALBUMIN_DENOMINATOR]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8d1a8f6d-df39-4396-b604-7a1ffcd3f16e

	column SHEET
		dataType: string
		lineageTag: 4b396324-465e-471f-bcef-1e5a5097b896
		summarizeBy: none
		sourceColumn: SHEET

		annotation SummarizationSetBy = Automatic

	column AUDIT_PERIOD
		dataType: string
		lineageTag: 1dace5a9-5660-423b-ad2a-7bdf617f82da
		summarizeBy: none
		sourceColumn: AUDIT_PERIOD

		annotation SummarizationSetBy = Automatic

	column AUDIT_PERIOD_START
		dataType: string
		lineageTag: 29a65f5f-0a17-47d7-8bb6-83cdc2f5fbcc
		summarizeBy: none
		sourceColumn: AUDIT_PERIOD_START

		annotation SummarizationSetBy = Automatic

	column AUDIT_PERIOD_END
		dataType: dateTime
		formatString: Long Date
		lineageTag: 229391ca-7c83-4488-b117-cd192db955f2
		summarizeBy: none
		sourceColumn: AUDIT_PERIOD_END

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HBA1C_NUMERATOR
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: f6dcc5b2-a767-4ed0-b681-f7e6f153c025
		summarizeBy: sum
		sourceColumn: HBA1C_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column HBA1C_DENOMINATOR
		dataType: int64
		formatString: 0
		displayFolder: Figures
		lineageTag: fd0d3c5e-1f0b-4aa4-8b6d-c8f818f50c67
		summarizeBy: sum
		sourceColumn: HBA1C_DENOMINATOR

		annotation SummarizationSetBy = Automatic

	column CHOLESTEROL_NUMERATOR
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: e3765986-da1a-4489-bc4d-e42773b0ca86
		summarizeBy: sum
		sourceColumn: CHOLESTEROL_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column CHOLESTEROL_DENOMINATOR
		dataType: int64
		displayFolder: Figures
		lineageTag: da0e5e54-2405-40b9-8b1f-935df96b946d
		summarizeBy: sum
		sourceColumn: CHOLESTEROL_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BMI_NUMERATOR
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: dd02fc0f-c734-46b1-a627-e6da706b7b02
		summarizeBy: sum
		sourceColumn: BMI_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column BMI_DENOMINATOR
		dataType: int64
		displayFolder: Figures
		lineageTag: 6daf31bb-c38c-44e0-b13e-1dfe3b0d4278
		summarizeBy: sum
		sourceColumn: BMI_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SMOKING_NUMERATOR
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: 3a7c129e-0fd9-4578-a4a7-a8e7dc6e31a6
		summarizeBy: sum
		sourceColumn: SMOKING_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column SMOKING_DENOMINATOR
		dataType: int64
		displayFolder: Figures
		lineageTag: 31cc738b-61c1-4fbe-a0ca-fb274cf8dc91
		summarizeBy: sum
		sourceColumn: SMOKING_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Practice Name'
		dataType: string
		lineageTag: ecaaecdd-302f-418c-9fce-1d36550f8625
		summarizeBy: none
		sourceColumn: Practice Name

		annotation SummarizationSetBy = Automatic

	column PCN
		dataType: string
		lineageTag: 16ef6fb7-01db-49a0-9463-045d00d4ccee
		summarizeBy: none
		sourceColumn: PCN

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 5156eb6b-9b9c-4b29-9368-23266cc12a9f
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column Distinct
		dataType: int64
		formatString: 0
		lineageTag: 81e4f772-6933-4c70-a97c-0e31c4c795bc
		summarizeBy: sum
		sourceColumn: Distinct

		annotation SummarizationSetBy = Automatic

	column 'AUDIT YEAR'
		dataType: string
		lineageTag: ef962738-ab47-40f7-a487-c8572938cb74
		summarizeBy: none
		sourceColumn: AUDIT YEAR

		annotation SummarizationSetBy = Automatic

	column 'ICB CODE'
		dataType: string
		lineageTag: b3307455-bc14-4a9f-bb82-57d035064485
		summarizeBy: none
		sourceColumn: ICB CODE

		annotation SummarizationSetBy = Automatic

	column 'PCN CODE'
		dataType: string
		lineageTag: 647d86b2-6624-4df2-a6f8-659239d4be01
		summarizeBy: none
		sourceColumn: PCN CODE

		annotation SummarizationSetBy = Automatic

	column 'ORGANISATION CODE'
		dataType: string
		lineageTag: 8ea6bfe4-f8b1-4c29-8984-c8977cc44913
		summarizeBy: none
		sourceColumn: ORGANISATION CODE

		annotation SummarizationSetBy = Automatic

	column 'BLOOD PRESSURE_NUMERATOR'
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: 06c7c578-1342-4091-bdb8-4f4e05d6753e
		summarizeBy: sum
		sourceColumn: BLOOD PRESSURE_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'BLOOD PRESSURE_DENOMINATOR'
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: 9eef38ce-21ee-4790-bec2-6738440f9310
		summarizeBy: sum
		sourceColumn: BLOOD PRESSURE_DENOMINATOR

		annotation SummarizationSetBy = Automatic

	column 'SERUM CREATININE_NUMERATOR'
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: 857c9987-ad18-42c5-8c81-db2fcfdb9dd4
		summarizeBy: sum
		sourceColumn: SERUM CREATININE_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'SERUM CREATININE_DENOMINATOR'
		dataType: int64
		displayFolder: Figures
		lineageTag: 9ef0649d-48b9-4d7c-953e-65476f36c6e3
		summarizeBy: sum
		sourceColumn: SERUM CREATININE_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'URINE ALBUMIN_NUMERATOR'
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: f70f56bd-c061-491d-984f-abc689ba4c78
		summarizeBy: sum
		sourceColumn: URINE ALBUMIN_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'URINE ALBUMIN_DENOMINATOR'
		dataType: int64
		displayFolder: Figures
		lineageTag: 4f8d46e2-6c9a-41cb-840b-7eaac0082bcd
		summarizeBy: sum
		sourceColumn: URINE ALBUMIN_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FOOT SURVEILLANCE_NUMERATOR'
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: 4948b9fa-6889-4b48-bfcd-1ed4b4acfbe6
		summarizeBy: sum
		sourceColumn: FOOT SURVEILLANCE_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'FOOT SURVEILLANCE_DENOMINATOR'
		dataType: int64
		displayFolder: Figures
		lineageTag: ba39aa5c-d502-4940-b12d-1a79989b969f
		summarizeBy: sum
		sourceColumn: FOOT SURVEILLANCE_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ALL EIGHT CARE PROCESSES_NUMERATOR'
		dataType: int64
		formatString: #,0
		lineageTag: 3c9ab4de-0083-45f8-a7a8-178233e92203
		summarizeBy: sum
		sourceColumn: ALL EIGHT CARE PROCESSES_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'ALL EIGHT CARE PROCESSES_DENOMINATOR'
		dataType: int64
		lineageTag: f42293c3-5635-4766-a87f-0a41e3f87b1b
		summarizeBy: sum
		sourceColumn: ALL EIGHT CARE PROCESSES_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _NUMERATOR'
		dataType: int64
		formatString: #,0
		lineageTag: 903ff5d5-9110-4465-aec3-71574a189a2f
		summarizeBy: sum
		sourceColumn: PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _DENOMINATOR'
		dataType: int64
		lineageTag: dc5774ba-9336-4c5a-afbe-549a774d2ff6
		summarizeBy: sum
		sourceColumn: PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_NUMERATOR'
		dataType: int64
		lineageTag: 1a30a826-4687-44f8-be71-7b59acf05883
		summarizeBy: sum
		sourceColumn: SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_NUMERATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_DENOMINATOR'
		dataType: int64
		lineageTag: 1535e593-8cc6-4578-94a8-44c437f61436
		summarizeBy: sum
		sourceColumn: SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'COMBINED PREVENTION - ON STATINS_NUMERATOR'
		dataType: int64
		lineageTag: 932b4508-2172-4d6a-bce2-cca708d900d4
		summarizeBy: sum
		sourceColumn: COMBINED PREVENTION - ON STATINS_NUMERATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'COMBINED PREVENTION - ON STATINS_DENOMINATOR'
		dataType: int64
		lineageTag: 033d08fc-d8d2-4c45-911c-813244c62de3
		summarizeBy: sum
		sourceColumn: COMBINED PREVENTION - ON STATINS_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ALL THREE TREATMENT TARGETS (2024)_NUMERATOR'
		dataType: int64
		formatString: #,0
		lineageTag: 0d7f153b-3e7d-45ab-b1c4-50f773e162ed
		summarizeBy: sum
		sourceColumn: ALL THREE TREATMENT TARGETS (2024)_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'ALL THREE TREATMENT TARGETS (2024)_DENOMINATOR'
		dataType: int64
		lineageTag: aac84c57-b372-492d-89b6-134329571d25
		summarizeBy: sum
		sourceColumn: ALL THREE TREATMENT TARGETS (2024)_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RETINAL SCREENING_NUMERATOR'
		dataType: int64
		formatString: #,0
		displayFolder: Figures
		lineageTag: 98e580aa-022d-4ded-b1e6-4b633cb3473d
		summarizeBy: sum
		sourceColumn: RETINAL SCREENING_NUMERATOR

		annotation SummarizationSetBy = Automatic

	column 'RETINAL SCREENING_DENOMINATOR'
		dataType: int64
		displayFolder: Figures
		lineageTag: fab07f2d-34a4-42d0-b52f-824c6a53d5c1
		summarizeBy: sum
		sourceColumn: RETINAL SCREENING_DENOMINATOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '8CP & 3TT (National)' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="select *#(lf)from (#(lf)#(tab)SELECT #(lf)#(tab)[SHEET]#(lf)#(tab)#(tab)  ,[AUDIT_PERIOD]#(lf)#(tab)#(tab)  ,[AUDIT_PERIOD_START]#(lf)#(tab)#(tab)  ,[AUDIT_PERIOD_END]#(lf)#(tab)#(tab)  ,[AUDIT YEAR] = [audit_year]#(lf)#(tab)#(tab)  ,[ICB CODE] = [icb_code]#(lf)#(tab)#(tab)  ,[PCN CODE] = [pcn_code]#(lf)#(tab)#(tab)  ,[ORGANISATION CODE] = [organisation_code]#(lf)#(tab)#(tab)  ,[HBA1C_NUMERATOR]#(lf)#(tab)#(tab)  ,[HBA1C_DENOMINATOR]#(lf)#(tab)#(tab)  ,[BLOOD PRESSURE_NUMERATOR] = [blood_pressure_numerator]#(lf)#(tab)#(tab)  ,[BLOOD PRESSURE_DENOMINATOR] = [blood_pressure_denominator]#(lf)#(tab)#(tab)  ,[CHOLESTEROL_NUMERATOR]#(lf)#(tab)#(tab)  ,[CHOLESTEROL_DENOMINATOR]#(lf)#(tab)#(tab)  ,[SERUM CREATININE_NUMERATOR] = [serum_creatinine_numerator]#(lf)#(tab)#(tab)  ,[SERUM CREATININE_DENOMINATOR] = [serum_creatinine_denominator]#(lf)#(tab)#(tab)  ,[URINE ALBUMIN_NUMERATOR] = [urine_albumin_numerator]#(lf)#(tab)#(tab)  ,[URINE ALBUMIN_DENOMINATOR] = [urine_albumin_denominator]#(lf)#(tab)#(tab)  ,[FOOT SURVEILLANCE_NUMERATOR] = [foot_surveillance_numerator]#(lf)#(tab)#(tab)  ,[FOOT SURVEILLANCE_DENOMINATOR] = [foot_surveillance_denominator]#(lf)#(tab)#(tab)  ,[BMI_NUMERATOR]#(lf)#(tab)#(tab)  ,[BMI_DENOMINATOR]#(lf)#(tab)#(tab)  ,[SMOKING_NUMERATOR]#(lf)#(tab)#(tab)  ,[SMOKING_DENOMINATOR]#(lf)#(tab)#(tab)  ,[ALL EIGHT CARE PROCESSES_NUMERATOR] = [all_eight_care_processes_numerator]#(lf)#(tab)#(tab)  ,[ALL EIGHT CARE PROCESSES_DENOMINATOR] = [all_eight_care_processes_denominator]#(lf)#(tab)#(tab)  ,[PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _NUMERATOR] = [primary prevention_-_on_statins_without_cvd_history_numerator]#(lf)#(tab)#(tab)  ,[PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _DENOMINATOR] = [primary prevention_-_on_statins_without_cvd_history_denominator]#(lf)#(tab)#(tab)  ,[SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_NUMERATOR] = [secondary_prevention_-_on_statins_with_cvd_history_numerator]#(lf)#(tab)#(tab)  ,[SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_DENOMINATOR] = [secondary_prevention_-_on_statins_with_cvd_history_denominator]#(lf)#(tab)#(tab)  ,[COMBINED PREVENTION - ON STATINS_NUMERATOR] = [combined_prevention_-_on_statins_numerator]#(lf)#(tab)#(tab)  ,[COMBINED PREVENTION - ON STATINS_DENOMINATOR] = [combined_prevention_-_on_statins_denominator]#(lf)#(tab)#(tab)  ,[ALL THREE TREATMENT TARGETS (2024)_NUMERATOR] = [all_three_treatment_targets_(2024)_numerator]#(lf)#(tab)#(tab)  ,[ALL THREE TREATMENT TARGETS (2024)_DENOMINATOR] = [all_three_treatment_targets_(2024)_denominator]#(lf)#(tab)#(tab)  ,[RETINAL SCREENING_NUMERATOR] = [retinal_screening_numerator]#(lf)#(tab)#(tab)  ,[RETINAL SCREENING_DENOMINATOR] = [retinal_screening_denominator]#(lf)#(tab)#(tab)  ,isnull([b].ReportingOrganisationName,[c].ReportingOrganisationName) as [Practice Name]#(lf)#(tab)#(tab),isnull([b].PrimaryCareNetwork,[c].PrimaryCareNetwork) as [PCN]#(lf)#(tab)#(tab),isnull([b].Locality,[c].Locality) as [Locality]#(lf)#(tab)#(tab),row_number() over(partition by [organisation_code], AUDIT_PERIOD, SHEET order by [pcn_code] desc) as [Distinct]#(lf)#(tab)  FROM  [CCG_Reference].[Diabetes].[vw_NDA_CP_TT] [a]#(lf)#(tab)LEFT JOIN CCG_Reference.reference.vw_GPPractice [b] on [a].[organisation_code] = [b].ReportingOrganisationCode#(lf)#(tab)LEFT JOIN CCG_Reference.reference.vw_GPPractice [c] on [a].[organisation_code] = [c].OrganisationCode#(lf)#(tab)where [icb_code] LIKE 'QR1%'#(lf)#(tab)and [pcn_code] != [organisation_code]#(lf)#(tab))[a] #(lf)where [a].[Distinct] = 1"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"HBA1C_NUMERATOR", Int64.Type}, {"HBA1C_DENOMINATOR", Int64.Type}, {"BLOOD PRESSURE_NUMERATOR", Int64.Type}, {"BLOOD PRESSURE_DENOMINATOR", Int64.Type}, {"CHOLESTEROL_NUMERATOR", Int64.Type}, {"CHOLESTEROL_DENOMINATOR", Int64.Type}, {"SERUM CREATININE_NUMERATOR", Int64.Type}, {"SERUM CREATININE_DENOMINATOR", Int64.Type}, {"URINE ALBUMIN_NUMERATOR", Int64.Type}, {"URINE ALBUMIN_DENOMINATOR", Int64.Type}, {"FOOT SURVEILLANCE_NUMERATOR", Int64.Type}, {"FOOT SURVEILLANCE_DENOMINATOR", Int64.Type}, {"BMI_NUMERATOR", Int64.Type}, {"BMI_DENOMINATOR", Int64.Type}, {"SMOKING_NUMERATOR", Int64.Type}, {"SMOKING_DENOMINATOR", Int64.Type}, {"ALL EIGHT CARE PROCESSES_NUMERATOR", Int64.Type}, {"ALL EIGHT CARE PROCESSES_DENOMINATOR", Int64.Type}, {"PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _NUMERATOR", Int64.Type}, {"PRIMARY PREVENTION - ON STATINS WITHOUT CVD HISTORY _DENOMINATOR", Int64.Type}, {"SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_NUMERATOR", Int64.Type}, {"SECONDARY PREVENTION - ON STATINS WITH CVD HISTORY_DENOMINATOR", Int64.Type}, {"COMBINED PREVENTION - ON STATINS_NUMERATOR", Int64.Type}, {"COMBINED PREVENTION - ON STATINS_DENOMINATOR", Int64.Type}, {"ALL THREE TREATMENT TARGETS (2024)_NUMERATOR", Int64.Type}, {"ALL THREE TREATMENT TARGETS (2024)_DENOMINATOR", Int64.Type}, {"RETINAL SCREENING_NUMERATOR", Int64.Type}, {"RETINAL SCREENING_DENOMINATOR", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

