table 'Ref. Age Reference'
	lineageTag: e8a728c2-c9bd-4001-b0a4-a5a4fa544116

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 0f900687-c563-4c72-a1da-cea484f927da
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Adult/Child
		dataType: string
		lineageTag: bc7a556f-f1cc-4ab2-b345-9faae7ce5f14
		summarizeBy: none
		sourceColumn: Adult/Child

		annotation SummarizationSetBy = Automatic

	column 10YR_Age_Band
		dataType: string
		lineageTag: 213e8eb7-dd09-4c8e-b48c-ac044cc73fdf
		summarizeBy: none
		sourceColumn: 10YR_Age_Band

		annotation SummarizationSetBy = Automatic

	column 'Early Onset Bands'
		dataType: string
		lineageTag: 4857c1b0-9b26-48ec-8675-f004cc4e9a30
		summarizeBy: none
		sourceColumn: Early Onset Bands

		annotation SummarizationSetBy = Automatic

	partition 'Ref. Age Reference' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select age as ""Age"", case when age between '0' and '17' then '0-17' when age>='18' then '18+' end as ""Adult/Paeds"", ""10yr_age_band"" as ""10YR_Age_Band"", case when age<=17 then 'Children (0-17)' when age<=39 then 'Early Onset (18-39)' else 'Other (40+)' end as ""Early Onset Bands"" from ccg_reference.vw_ageband where age between '0' and '130'", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Adult/Paeds", "Adult/Child"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

