table Cover_Ind_Table_Full_Data_data
	lineageTag: e99b6805-4c70-49fe-939f-85f3ebfb15d5

	column Category
		dataType: string
		lineageTag: ac014115-09db-4a90-805f-d2ff9dfa5ec8
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: bdb32d5c-c20a-4f20-85f5-dc6fbd80f8e3
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: a62f58f5-5732-44bb-b917-7adf9252ee81
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column 'Last Updated'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c7eaa9b-1e31-47a7-b612-9a2985047262
		summarizeBy: none
		sourceColumn: Last Updated

		variation Variation
			isDefault
			relationship: ae752228-1784-425a-88ef-ca5f0038fa99
			defaultHierarchy: LocalDateTable_76438349-987f-4c0d-81cc-4a06ab9f0256.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Latest Period'
		dataType: string
		lineageTag: 22985ee7-b9b6-49c9-a0cf-613b90b1bfad
		summarizeBy: none
		sourceColumn: Latest Period

		annotation SummarizationSetBy = Automatic

	column 'Indicator in dataset'
		dataType: string
		lineageTag: 40770a80-6c93-487e-9068-2db75e0edeed
		summarizeBy: none
		sourceColumn: Indicator in dataset

		annotation SummarizationSetBy = Automatic

	column IndName
		dataType: string
		lineageTag: f1748792-9b3b-4daa-9fad-2397f58eeb99
		summarizeBy: none
		sourceColumn: IndName

		annotation SummarizationSetBy = Automatic

	column IndRef
		dataType: string
		lineageTag: 96e408f8-1905-4e4b-8e56-9bb9d2e6565a
		summarizeBy: none
		sourceColumn: IndRef

		annotation SummarizationSetBy = Automatic

	column LatestPeriod
		dataType: string
		lineageTag: 17a8bd84-9464-49eb-a1c1-ad46abf34b0f
		summarizeBy: none
		sourceColumn: LatestPeriod

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 2bacb37b-d608-4fb3-ac88-952011009556
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 10926617-a18f-41d1-9eb3-34e72441f581
			defaultHierarchy: LocalDateTable_c153b500-49b8-4188-bd36-f16abdefaa36.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column StartDate_Max
		dataType: dateTime
		formatString: General Date
		lineageTag: 580c29f2-cffc-4217-96a4-5c539d54845b
		summarizeBy: none
		sourceColumn: StartDate_Max

		variation Variation
			isDefault
			relationship: d0abc181-f8c8-454c-914d-6b3fadede330
			defaultHierarchy: LocalDateTable_3fbe8050-94db-4ee5-b992-61caf6e5f131.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CountIndRef
		dataType: int64
		formatString: 0
		lineageTag: 20fd3fc0-9fd1-4b51-89a7-936af70a62d6
		summarizeBy: sum
		sourceColumn: CountIndRef

		annotation SummarizationSetBy = Automatic

	partition Cover_Ind_Table_Full_Data_data-ad6b15b9-c61c-4d30-bd0b-00fd651eb584 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\Dataset_Explorer_LastUpdated.xlsx"), null, true),
				    Cover_Ind_Table_Full_Data_data_Sheet = Source{[Item="Cover_Ind_Table_Full_Data_data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Cover_Ind_Table_Full_Data_data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Category", type text}, {"Sub-Category", type text}, {"Indicator", type text}, {"Last Updated", type date}, {"Latest Period", type any}, {"Indicator in dataset", type text}, {"IndName", type text}, {"IndRef", type text}, {"LatestPeriod", type any}, {"StartDate", type datetime}, {"StartDate_Max", type datetime}, {"CountIndRef", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

