table 'Dashboard v2'
	lineageTag: 4292da5f-a825-4f6c-96ef-fa514538e5d8

	column Column1
		dataType: string
		lineageTag: eba359ce-a85c-4c27-95ac-8d16710e5ff1
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column 'Oversight theme'
		dataType: string
		lineageTag: 656311b7-4f6e-4459-8cb1-04609b5b8859
		summarizeBy: none
		sourceColumn: Oversight theme

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: 102d311f-dd22-41d9-9e4d-c63891f6b20b
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column 'Measure name (Metric)'
		dataType: string
		lineageTag: 1e4aca8b-f1bf-40b4-a394-03425f31e703
		summarizeBy: none
		sourceColumn: Measure name (Metric)

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 311576e5-1de6-4e0c-b923-865744cb9fe2
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column 'Indicator as a Mean Value'
		dataType: string
		lineageTag: bc896c5c-2773-40d4-86df-dd1890dcd554
		summarizeBy: none
		sourceColumn: Indicator as a Mean Value

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 91151ee8-5c7d-44bc-af13-2306d71017e9
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: dcf0b244-ebb9-4def-92b5-ab90fa841318
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: e45dcaa2-1e1b-4d9c-97a8-55fcb205257a
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Quartile
		dataType: string
		lineageTag: 48ba31ff-df6a-4a29-96e3-3870e42b6087
		summarizeBy: none
		sourceColumn: Quartile

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 431bd4df-e4e7-45ae-827d-6455efa851df
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 74ad9f95-6d9d-4aed-a16c-d492435463d4
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Direction
		dataType: string
		lineageTag: 67878bcb-0222-4810-b81a-8c98e9d5a7f0
		summarizeBy: none
		sourceColumn: Direction

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: be5fe93c-70af-4ef6-bd5c-bd35c17d2c81
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Comparison
		dataType: string
		lineageTag: 13db574a-660a-454a-aa28-57dc76433e95
		summarizeBy: none
		sourceColumn: Comparison

		annotation SummarizationSetBy = Automatic

	column 'Latest reporting period'
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 34874d90-ee7a-4cfd-a99b-8801b1df174f
		summarizeBy: none
		sourceColumn: Latest reporting period

		variation Variation
			isDefault
			relationship: 498d59fa-6ac9-4ac1-920f-6027ca3b45fa
			defaultHierarchy: LocalDateTable_30bdd044-302c-41ae-8bde-ca44b1ee8f58.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Column17
		dataType: string
		lineageTag: 4595dad9-fcc7-48ed-8ff6-b79b0e8de550
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 8c273ff6-fc9b-4a9e-b5ca-8bfe17de1e7a
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: a52747da-ef65-42c6-aada-c2853e0040f9
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: a91645f7-bb3a-456f-8e2e-e848ce5494ef
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: a38bfc50-0f3b-4fe4-8127-427fa4c814ac
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: 2f94da5a-a67b-4736-8a0c-71feb720beb5
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	partition 'Dashboard v2-9191f27f-8dbe-48bb-97ed-62953464120f' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\Dashboard v2.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type any}, {"Column2", type text}, {"System Oversight Framework Perfomance Metrics 2021/22", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type text}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type text}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"▲ ▼", type any}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",4),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Latest reporting period", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

