table MYE2persons
	lineageTag: ca85ba22-bb9f-4809-8ca3-68e81e430dd7

	column Code
		dataType: string
		lineageTag: 3df8227a-ae18-44f3-b2a1-4ab6e6bd8083
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 5e1285cf-4744-434f-8b3c-2f6bde91a297
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Geography
		dataType: string
		lineageTag: 1d0bf8f2-c405-40d5-8bb4-82ded3c02d8f
		summarizeBy: none
		sourceColumn: Geography

		annotation SummarizationSetBy = Automatic

	column 'All ages'
		dataType: int64
		formatString: 0
		lineageTag: a69a4284-b17f-4249-bb2b-e90bba6995e2
		summarizeBy: none
		sourceColumn: All ages

		annotation SummarizationSetBy = Automatic

	column 0
		dataType: int64
		formatString: 0
		lineageTag: 85c67dee-cff1-4622-ad05-cd7c5f835a8c
		summarizeBy: none
		sourceColumn: 0

		annotation SummarizationSetBy = Automatic

	column 1
		dataType: int64
		formatString: 0
		lineageTag: cf001353-b7c5-43d7-954d-57e1f80a032b
		summarizeBy: none
		sourceColumn: 1

		annotation SummarizationSetBy = Automatic

	column 2
		dataType: int64
		formatString: 0
		lineageTag: 543bb0ca-a67d-4899-90a2-88c2b424247f
		summarizeBy: none
		sourceColumn: 2

		annotation SummarizationSetBy = Automatic

	column 3
		dataType: int64
		formatString: 0
		lineageTag: 53f3650a-ac80-470e-a31b-d45a3405736a
		summarizeBy: none
		sourceColumn: 3

		annotation SummarizationSetBy = Automatic

	column 4
		dataType: int64
		formatString: 0
		lineageTag: 1efcc274-d2bb-4741-9c93-6bc2627ca931
		summarizeBy: none
		sourceColumn: 4

		annotation SummarizationSetBy = Automatic

	column 5
		dataType: int64
		formatString: 0
		lineageTag: 76cb0cc3-8e21-4b42-8f12-2154ac31afb0
		summarizeBy: none
		sourceColumn: 5

		annotation SummarizationSetBy = Automatic

	column 6
		dataType: int64
		formatString: 0
		lineageTag: dfecc9e0-4598-4c32-9b68-723d26df057d
		summarizeBy: none
		sourceColumn: 6

		annotation SummarizationSetBy = Automatic

	column 7
		dataType: int64
		formatString: 0
		lineageTag: bb4d108d-c754-4246-85b7-a2ccc6079675
		summarizeBy: none
		sourceColumn: 7

		annotation SummarizationSetBy = Automatic

	column 8
		dataType: int64
		formatString: 0
		lineageTag: 08610be0-d801-4c8f-8b34-e9b7887175f4
		summarizeBy: none
		sourceColumn: 8

		annotation SummarizationSetBy = Automatic

	column 9
		dataType: int64
		formatString: 0
		lineageTag: fae35134-ef2e-4b8e-a6a6-facc9ec8269b
		summarizeBy: none
		sourceColumn: 9

		annotation SummarizationSetBy = Automatic

	column 10
		dataType: int64
		formatString: 0
		lineageTag: bd76e454-5b37-4d22-bf25-ed151b1a22e6
		summarizeBy: none
		sourceColumn: 10

		annotation SummarizationSetBy = Automatic

	column 11
		dataType: int64
		formatString: 0
		lineageTag: 67d7c006-ca4a-44e1-a1fb-8247d17d38ba
		summarizeBy: none
		sourceColumn: 11

		annotation SummarizationSetBy = Automatic

	column 12
		dataType: int64
		formatString: 0
		lineageTag: 49f1fc9d-4dd9-496b-bfd8-a4579d39e9b2
		summarizeBy: none
		sourceColumn: 12

		annotation SummarizationSetBy = Automatic

	column 13
		dataType: int64
		formatString: 0
		lineageTag: e2b0ccce-8b8d-4804-a65d-d08620ef4a52
		summarizeBy: none
		sourceColumn: 13

		annotation SummarizationSetBy = Automatic

	column 14
		dataType: int64
		formatString: 0
		lineageTag: 4f090a8e-0273-4f24-b84d-6258358fd6e6
		summarizeBy: none
		sourceColumn: 14

		annotation SummarizationSetBy = Automatic

	column 15
		dataType: int64
		formatString: 0
		lineageTag: a7036083-db20-4084-a906-e5327bdc1c5b
		summarizeBy: none
		sourceColumn: 15

		annotation SummarizationSetBy = Automatic

	column 16
		dataType: int64
		formatString: 0
		lineageTag: b8cd83c0-4979-4cdd-9e42-a5d44e31ed05
		summarizeBy: none
		sourceColumn: 16

		annotation SummarizationSetBy = Automatic

	column 17
		dataType: int64
		formatString: 0
		lineageTag: 5fe7262d-978f-49c2-8932-81edf07428b6
		summarizeBy: none
		sourceColumn: 17

		annotation SummarizationSetBy = Automatic

	column 18
		dataType: int64
		formatString: 0
		lineageTag: 152c0022-ad42-45ff-a9de-d2cce7a7ef83
		summarizeBy: none
		sourceColumn: 18

		annotation SummarizationSetBy = Automatic

	column 19
		dataType: int64
		formatString: 0
		lineageTag: e9504e25-b57d-4181-893e-44c68414dd42
		summarizeBy: none
		sourceColumn: 19

		annotation SummarizationSetBy = Automatic

	column 20
		dataType: int64
		formatString: 0
		lineageTag: 9686cee9-59ee-4281-ad20-f608dedfbae4
		summarizeBy: none
		sourceColumn: 20

		annotation SummarizationSetBy = Automatic

	column 21
		dataType: int64
		formatString: 0
		lineageTag: ec8ca7b2-7c75-4ea1-8ecd-5ee18abf41cb
		summarizeBy: none
		sourceColumn: 21

		annotation SummarizationSetBy = Automatic

	column 22
		dataType: int64
		formatString: 0
		lineageTag: e352042c-63ab-48a8-b31f-941b8a091ef2
		summarizeBy: none
		sourceColumn: 22

		annotation SummarizationSetBy = Automatic

	column 23
		dataType: int64
		formatString: 0
		lineageTag: a707d15e-91dd-42c9-ba88-153c29570cae
		summarizeBy: none
		sourceColumn: 23

		annotation SummarizationSetBy = Automatic

	column 24
		dataType: int64
		formatString: 0
		lineageTag: aa2e2d82-7a45-448a-be8b-5b9ccf34cae2
		summarizeBy: none
		sourceColumn: 24

		annotation SummarizationSetBy = Automatic

	column 25
		dataType: int64
		formatString: 0
		lineageTag: 82dae9e7-cdaa-4437-a8f0-1e43521507e9
		summarizeBy: none
		sourceColumn: 25

		annotation SummarizationSetBy = Automatic

	column 26
		dataType: int64
		formatString: 0
		lineageTag: 332512d6-9c91-4734-8b7e-a74e0b77adec
		summarizeBy: none
		sourceColumn: 26

		annotation SummarizationSetBy = Automatic

	column 27
		dataType: int64
		formatString: 0
		lineageTag: 6e6ea6c8-e6ed-4d74-9691-fbbe69c5257b
		summarizeBy: none
		sourceColumn: 27

		annotation SummarizationSetBy = Automatic

	column 28
		dataType: int64
		formatString: 0
		lineageTag: f9606386-f655-4eea-ac47-625631b7f9de
		summarizeBy: none
		sourceColumn: 28

		annotation SummarizationSetBy = Automatic

	column 29
		dataType: int64
		formatString: 0
		lineageTag: 6a8d3d11-ce63-455a-bde2-57b2de57163b
		summarizeBy: none
		sourceColumn: 29

		annotation SummarizationSetBy = Automatic

	column 30
		dataType: int64
		formatString: 0
		lineageTag: 6d0c358d-3ffd-480f-a85c-f66e7b79074b
		summarizeBy: none
		sourceColumn: 30

		annotation SummarizationSetBy = Automatic

	column 31
		dataType: int64
		formatString: 0
		lineageTag: 7e0ff33a-02d0-4b1f-93a3-14ec21e81ea1
		summarizeBy: none
		sourceColumn: 31

		annotation SummarizationSetBy = Automatic

	column 32
		dataType: int64
		formatString: 0
		lineageTag: ee48f961-07b9-4553-8306-7354c8b2e99a
		summarizeBy: none
		sourceColumn: 32

		annotation SummarizationSetBy = Automatic

	column 33
		dataType: int64
		formatString: 0
		lineageTag: d695ad74-7628-48b2-bdcf-1c6732046a17
		summarizeBy: none
		sourceColumn: 33

		annotation SummarizationSetBy = Automatic

	column 34
		dataType: int64
		formatString: 0
		lineageTag: 774033f5-67a0-4534-a772-591437e4e028
		summarizeBy: none
		sourceColumn: 34

		annotation SummarizationSetBy = Automatic

	column 35
		dataType: int64
		formatString: 0
		lineageTag: 291e1cab-3856-492e-9bb7-26cb9135b62f
		summarizeBy: none
		sourceColumn: 35

		annotation SummarizationSetBy = Automatic

	column 36
		dataType: int64
		formatString: 0
		lineageTag: c78f9410-1738-442f-a806-fd20450b4823
		summarizeBy: none
		sourceColumn: 36

		annotation SummarizationSetBy = Automatic

	column 37
		dataType: int64
		formatString: 0
		lineageTag: 7773ae39-139d-474d-a776-cc6a972b9b8b
		summarizeBy: none
		sourceColumn: 37

		annotation SummarizationSetBy = Automatic

	column 38
		dataType: int64
		formatString: 0
		lineageTag: 6bb7202b-6fa8-4e58-8fc2-3cd968301e44
		summarizeBy: none
		sourceColumn: 38

		annotation SummarizationSetBy = Automatic

	column 39
		dataType: int64
		formatString: 0
		lineageTag: 85136116-ab3f-42b4-9632-10e96cde8904
		summarizeBy: none
		sourceColumn: 39

		annotation SummarizationSetBy = Automatic

	column 40
		dataType: int64
		formatString: 0
		lineageTag: 19cd1e9a-5db0-4e13-a4d3-332ff5043abf
		summarizeBy: none
		sourceColumn: 40

		annotation SummarizationSetBy = Automatic

	column 41
		dataType: int64
		formatString: 0
		lineageTag: 4f21211a-45de-47da-b4a5-76a90a60de72
		summarizeBy: none
		sourceColumn: 41

		annotation SummarizationSetBy = Automatic

	column 42
		dataType: int64
		formatString: 0
		lineageTag: 424c4dc6-43a1-4de7-9f21-09c961f4ad5f
		summarizeBy: none
		sourceColumn: 42

		annotation SummarizationSetBy = Automatic

	column 43
		dataType: int64
		formatString: 0
		lineageTag: 54160330-5699-407b-b78e-fb194a782672
		summarizeBy: none
		sourceColumn: 43

		annotation SummarizationSetBy = Automatic

	column 44
		dataType: int64
		formatString: 0
		lineageTag: 6d414f1c-9e7d-40d1-ac09-4d27c555996d
		summarizeBy: none
		sourceColumn: 44

		annotation SummarizationSetBy = Automatic

	column 45
		dataType: int64
		formatString: 0
		lineageTag: 20c5f6e4-5ab0-4fd9-985b-d00ece3d9014
		summarizeBy: none
		sourceColumn: 45

		annotation SummarizationSetBy = Automatic

	column 46
		dataType: int64
		formatString: 0
		lineageTag: db7bd28d-9c4e-49af-98e4-c4a7db8d0909
		summarizeBy: none
		sourceColumn: 46

		annotation SummarizationSetBy = Automatic

	column 47
		dataType: int64
		formatString: 0
		lineageTag: 19dcabae-efb2-4342-9f33-011083bb5ac6
		summarizeBy: none
		sourceColumn: 47

		annotation SummarizationSetBy = Automatic

	column 48
		dataType: int64
		formatString: 0
		lineageTag: cdcb853b-b4fe-49c7-b346-54df027a0de1
		summarizeBy: none
		sourceColumn: 48

		annotation SummarizationSetBy = Automatic

	column 49
		dataType: int64
		formatString: 0
		lineageTag: a3ccc50d-282e-4159-b44f-22b86b94de57
		summarizeBy: none
		sourceColumn: 49

		annotation SummarizationSetBy = Automatic

	column 50
		dataType: int64
		formatString: 0
		lineageTag: 14deb093-06d0-4370-be7e-068356dca1b7
		summarizeBy: none
		sourceColumn: 50

		annotation SummarizationSetBy = Automatic

	column 51
		dataType: int64
		formatString: 0
		lineageTag: 292982f5-9db4-4043-bbdf-e52a3d14a9a6
		summarizeBy: none
		sourceColumn: 51

		annotation SummarizationSetBy = Automatic

	column 52
		dataType: int64
		formatString: 0
		lineageTag: 359afcf4-b629-41e7-bf1a-716dc40bff89
		summarizeBy: none
		sourceColumn: 52

		annotation SummarizationSetBy = Automatic

	column 53
		dataType: int64
		formatString: 0
		lineageTag: 141e9eaa-c46e-4545-9c5e-1835dc47b4b0
		summarizeBy: none
		sourceColumn: 53

		annotation SummarizationSetBy = Automatic

	column 54
		dataType: int64
		formatString: 0
		lineageTag: 8e54d86a-7bf4-4ac8-bcf3-e46e21a3e29c
		summarizeBy: none
		sourceColumn: 54

		annotation SummarizationSetBy = Automatic

	column 55
		dataType: int64
		formatString: 0
		lineageTag: 406f0124-9b07-4b83-8fd8-e23fe56513d3
		summarizeBy: none
		sourceColumn: 55

		annotation SummarizationSetBy = Automatic

	column 56
		dataType: int64
		formatString: 0
		lineageTag: 44d388b2-2ba3-4f2c-801a-b58cacd80f98
		summarizeBy: none
		sourceColumn: 56

		annotation SummarizationSetBy = Automatic

	column 57
		dataType: int64
		formatString: 0
		lineageTag: 240ccb6a-49d4-4daa-9056-c29be9619359
		summarizeBy: none
		sourceColumn: 57

		annotation SummarizationSetBy = Automatic

	column 58
		dataType: int64
		formatString: 0
		lineageTag: 4821d8b0-8689-4029-ba7c-3d24369a5dfa
		summarizeBy: none
		sourceColumn: 58

		annotation SummarizationSetBy = Automatic

	column 59
		dataType: int64
		formatString: 0
		lineageTag: 7c9b367d-a0bf-4c64-9dea-255312c6ae9d
		summarizeBy: none
		sourceColumn: 59

		annotation SummarizationSetBy = Automatic

	column 60
		dataType: int64
		formatString: 0
		lineageTag: 7978551a-1eb8-496d-bee5-574ef06d2c68
		summarizeBy: none
		sourceColumn: 60

		annotation SummarizationSetBy = Automatic

	column 61
		dataType: int64
		formatString: 0
		lineageTag: c70f2dd4-98c8-4e1a-bac3-27e4feafe61f
		summarizeBy: none
		sourceColumn: 61

		annotation SummarizationSetBy = Automatic

	column 62
		dataType: int64
		formatString: 0
		lineageTag: 9c6e3b1a-703d-454f-8da9-9b4f93afeaa2
		summarizeBy: none
		sourceColumn: 62

		annotation SummarizationSetBy = Automatic

	column 63
		dataType: int64
		formatString: 0
		lineageTag: 0506e455-4292-4c76-9db3-6b12f1df6445
		summarizeBy: none
		sourceColumn: 63

		annotation SummarizationSetBy = Automatic

	column 64
		dataType: int64
		formatString: 0
		lineageTag: cd6dd836-c9cc-48fb-aab4-23a5502a6ac4
		summarizeBy: none
		sourceColumn: 64

		annotation SummarizationSetBy = Automatic

	column 65
		dataType: int64
		formatString: 0
		lineageTag: 3aff83e9-01dc-46cf-9cbf-1b5e08594585
		summarizeBy: none
		sourceColumn: 65

		annotation SummarizationSetBy = Automatic

	column 66
		dataType: int64
		formatString: 0
		lineageTag: ac93efa2-a0db-404e-ac82-834c42896864
		summarizeBy: none
		sourceColumn: 66

		annotation SummarizationSetBy = Automatic

	column 67
		dataType: int64
		formatString: 0
		lineageTag: cb1057fb-9d42-4346-a42b-356b0ab7a81d
		summarizeBy: none
		sourceColumn: 67

		annotation SummarizationSetBy = Automatic

	column 68
		dataType: int64
		formatString: 0
		lineageTag: 79d6037a-c314-4b1d-85b0-da1a8cd1b59c
		summarizeBy: none
		sourceColumn: 68

		annotation SummarizationSetBy = Automatic

	column 69
		dataType: int64
		formatString: 0
		lineageTag: a8e0d517-be30-495d-b95f-f03debbe8176
		summarizeBy: none
		sourceColumn: 69

		annotation SummarizationSetBy = Automatic

	column 70
		dataType: int64
		formatString: 0
		lineageTag: b16a30b4-e574-43ae-a064-bf0bc22df9ca
		summarizeBy: none
		sourceColumn: 70

		annotation SummarizationSetBy = Automatic

	column 71
		dataType: int64
		formatString: 0
		lineageTag: 9ecd47f1-6150-4992-9279-84bf37903ca6
		summarizeBy: none
		sourceColumn: 71

		annotation SummarizationSetBy = Automatic

	column 72
		dataType: int64
		formatString: 0
		lineageTag: 0f5c7a6a-85b6-404a-b06b-b0879f90622b
		summarizeBy: none
		sourceColumn: 72

		annotation SummarizationSetBy = Automatic

	column 73
		dataType: int64
		formatString: 0
		lineageTag: 94626774-d5f4-417f-a1da-bb6435fe357e
		summarizeBy: none
		sourceColumn: 73

		annotation SummarizationSetBy = Automatic

	column 74
		dataType: int64
		formatString: 0
		lineageTag: 3a80145e-69ae-4d89-be1e-0a87840da95e
		summarizeBy: none
		sourceColumn: 74

		annotation SummarizationSetBy = Automatic

	column 75
		dataType: int64
		formatString: 0
		lineageTag: da23f347-6f36-473a-8c36-c93f4e2475df
		summarizeBy: none
		sourceColumn: 75

		annotation SummarizationSetBy = Automatic

	column 76
		dataType: int64
		formatString: 0
		lineageTag: 808e6f63-ba3f-4cd2-9a85-b0d652ca89d0
		summarizeBy: none
		sourceColumn: 76

		annotation SummarizationSetBy = Automatic

	column 77
		dataType: int64
		formatString: 0
		lineageTag: af2a4a70-4539-4f6a-9c75-258564087308
		summarizeBy: none
		sourceColumn: 77

		annotation SummarizationSetBy = Automatic

	column 78
		dataType: int64
		formatString: 0
		lineageTag: 27a3e58d-caac-4f83-907d-38ff23b48c36
		summarizeBy: none
		sourceColumn: 78

		annotation SummarizationSetBy = Automatic

	column 79
		dataType: int64
		formatString: 0
		lineageTag: 3c01e1e6-1ff3-4f63-8762-109d6a18f2f0
		summarizeBy: none
		sourceColumn: 79

		annotation SummarizationSetBy = Automatic

	column 80
		dataType: int64
		formatString: 0
		lineageTag: 1704216e-84d7-4c13-a405-089b5ae30187
		summarizeBy: none
		sourceColumn: 80

		annotation SummarizationSetBy = Automatic

	column 81
		dataType: int64
		formatString: 0
		lineageTag: a662bdee-cf3a-4987-923c-6d1e19d4db5c
		summarizeBy: none
		sourceColumn: 81

		annotation SummarizationSetBy = Automatic

	column 82
		dataType: int64
		formatString: 0
		lineageTag: ec3b8e4b-36bd-48cd-af6f-ca0732542e6a
		summarizeBy: none
		sourceColumn: 82

		annotation SummarizationSetBy = Automatic

	column 83
		dataType: int64
		formatString: 0
		lineageTag: e5f1d935-91ea-4e04-9038-64a7713d13e0
		summarizeBy: none
		sourceColumn: 83

		annotation SummarizationSetBy = Automatic

	column 84
		dataType: int64
		formatString: 0
		lineageTag: 836a5a34-9f14-4501-b8fa-03d65227c7f5
		summarizeBy: none
		sourceColumn: 84

		annotation SummarizationSetBy = Automatic

	column 85
		dataType: int64
		formatString: 0
		lineageTag: 5495962e-1812-4ca0-9b85-103342884325
		summarizeBy: none
		sourceColumn: 85

		annotation SummarizationSetBy = Automatic

	column 86
		dataType: int64
		formatString: 0
		lineageTag: a8fcb19f-f17e-4738-b533-e81d13f58850
		summarizeBy: none
		sourceColumn: 86

		annotation SummarizationSetBy = Automatic

	column 87
		dataType: int64
		formatString: 0
		lineageTag: fa17997c-7c6a-4f2f-98a2-01f3cd4ed243
		summarizeBy: none
		sourceColumn: 87

		annotation SummarizationSetBy = Automatic

	column 88
		dataType: int64
		formatString: 0
		lineageTag: 9cb3427d-446b-4efb-9616-b6ec60fc30ab
		summarizeBy: none
		sourceColumn: 88

		annotation SummarizationSetBy = Automatic

	column 89
		dataType: int64
		formatString: 0
		lineageTag: 3e1d4949-fa2d-4de8-b55d-51d5f17f0d01
		summarizeBy: none
		sourceColumn: 89

		annotation SummarizationSetBy = Automatic

	column 90+
		dataType: int64
		formatString: 0
		lineageTag: 69192bc3-06d2-467a-8263-d2a1782aa147
		summarizeBy: none
		sourceColumn: 90+

		annotation SummarizationSetBy = Automatic

	partition MYE2persons-ba9805ec-4f34-42ae-8534-3edb8c61c892 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\ukpopestimatesmid2020on2021geography.xlsx"), null, true),
				    MYE2persons_Table = Source{[Item="MYE2persons",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(MYE2persons_Table,{{"Code", type text}, {"Name", type text}, {"Geography", type text}, {"All ages", Int64.Type}, {"0", Int64.Type}, {"1", Int64.Type}, {"2", Int64.Type}, {"3", Int64.Type}, {"4", Int64.Type}, {"5", Int64.Type}, {"6", Int64.Type}, {"7", Int64.Type}, {"8", Int64.Type}, {"9", Int64.Type}, {"10", Int64.Type}, {"11", Int64.Type}, {"12", Int64.Type}, {"13", Int64.Type}, {"14", Int64.Type}, {"15", Int64.Type}, {"16", Int64.Type}, {"17", Int64.Type}, {"18", Int64.Type}, {"19", Int64.Type}, {"20", Int64.Type}, {"21", Int64.Type}, {"22", Int64.Type}, {"23", Int64.Type}, {"24", Int64.Type}, {"25", Int64.Type}, {"26", Int64.Type}, {"27", Int64.Type}, {"28", Int64.Type}, {"29", Int64.Type}, {"30", Int64.Type}, {"31", Int64.Type}, {"32", Int64.Type}, {"33", Int64.Type}, {"34", Int64.Type}, {"35", Int64.Type}, {"36", Int64.Type}, {"37", Int64.Type}, {"38", Int64.Type}, {"39", Int64.Type}, {"40", Int64.Type}, {"41", Int64.Type}, {"42", Int64.Type}, {"43", Int64.Type}, {"44", Int64.Type}, {"45", Int64.Type}, {"46", Int64.Type}, {"47", Int64.Type}, {"48", Int64.Type}, {"49", Int64.Type}, {"50", Int64.Type}, {"51", Int64.Type}, {"52", Int64.Type}, {"53", Int64.Type}, {"54", Int64.Type}, {"55", Int64.Type}, {"56", Int64.Type}, {"57", Int64.Type}, {"58", Int64.Type}, {"59", Int64.Type}, {"60", Int64.Type}, {"61", Int64.Type}, {"62", Int64.Type}, {"63", Int64.Type}, {"64", Int64.Type}, {"65", Int64.Type}, {"66", Int64.Type}, {"67", Int64.Type}, {"68", Int64.Type}, {"69", Int64.Type}, {"70", Int64.Type}, {"71", Int64.Type}, {"72", Int64.Type}, {"73", Int64.Type}, {"74", Int64.Type}, {"75", Int64.Type}, {"76", Int64.Type}, {"77", Int64.Type}, {"78", Int64.Type}, {"79", Int64.Type}, {"80", Int64.Type}, {"81", Int64.Type}, {"82", Int64.Type}, {"83", Int64.Type}, {"84", Int64.Type}, {"85", Int64.Type}, {"86", Int64.Type}, {"87", Int64.Type}, {"88", Int64.Type}, {"89", Int64.Type}, {"90+", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

