table 'NDPP Referrals'
	lineageTag: 304fa42b-e474-403d-930c-aca3598871bb

	column 'Practice Code'
		dataType: string
		lineageTag: 9007ebd4-2962-4c4f-8add-b9db0ac73570
		summarizeBy: none
		sourceColumn: Practice Code

		annotation SummarizationSetBy = Automatic

	column 'Practice Name'
		dataType: string
		lineageTag: de7cf8b2-dbbb-421c-8ab8-ecbb7cd87cc5
		summarizeBy: none
		sourceColumn: Practice Name

		annotation SummarizationSetBy = Automatic

	column PCN
		dataType: string
		lineageTag: 1ebcaab3-43d2-47d8-a21a-d64e8c81854b
		summarizeBy: none
		sourceColumn: PCN

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 2097c18a-a1b1-4136-8581-b5a70538d3eb
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 8de21624-0352-4077-bde4-93d76a1d63c9
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: 0
		lineageTag: 8e0ff762-4fb1-4d1d-8b6e-7536f1053a1a
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	column 2019/20
		dataType: int64
		formatString: 0
		lineageTag: fcf5b843-5f33-47f5-9170-1f0b12880ad4
		summarizeBy: sum
		sourceColumn: 2019/20

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 17f230c2-df63-46b5-8695-566273bb6ff2
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column 2020/21
		dataType: int64
		formatString: 0
		lineageTag: 00e6df37-0e60-4dc3-84bc-4dac2c345ad4
		summarizeBy: sum
		sourceColumn: 2020/21

		annotation SummarizationSetBy = Automatic

	column 2021/22
		dataType: int64
		formatString: 0
		lineageTag: 9c7e1d90-ea7c-4deb-8e1d-75c7cb328db7
		summarizeBy: sum
		sourceColumn: 2021/22

		annotation SummarizationSetBy = Automatic

	column 2022/23
		dataType: int64
		formatString: 0
		lineageTag: 29068369-8387-47f2-9321-7bf33bfab1e4
		summarizeBy: sum
		sourceColumn: 2022/23

		annotation SummarizationSetBy = Automatic

	column 01/07/2019
		dataType: int64
		formatString: 0
		lineageTag: e3829f86-00ed-4a6b-8f49-67305210dc56
		summarizeBy: sum
		sourceColumn: 01/07/2019

		annotation SummarizationSetBy = Automatic

	column 01/08/2019
		dataType: int64
		formatString: 0
		lineageTag: 620e3e67-8518-4921-b701-48695c7e3afa
		summarizeBy: sum
		sourceColumn: 01/08/2019

		annotation SummarizationSetBy = Automatic

	column 01/09/2019
		dataType: int64
		formatString: 0
		lineageTag: d7f5d608-325d-4336-827c-405107bf0661
		summarizeBy: sum
		sourceColumn: 01/09/2019

		annotation SummarizationSetBy = Automatic

	column 01/10/2019
		dataType: int64
		formatString: 0
		lineageTag: 193fb597-c42d-45a7-a61d-46846ae3327e
		summarizeBy: sum
		sourceColumn: 01/10/2019

		annotation SummarizationSetBy = Automatic

	column 01/11/2019
		dataType: int64
		formatString: 0
		lineageTag: f05be648-7c42-4796-80d0-bfbc8eff82e1
		summarizeBy: sum
		sourceColumn: 01/11/2019

		annotation SummarizationSetBy = Automatic

	column 01/12/2019
		dataType: int64
		formatString: 0
		lineageTag: 81678082-ab3e-45c2-a987-795ee05c4818
		summarizeBy: sum
		sourceColumn: 01/12/2019

		annotation SummarizationSetBy = Automatic

	column 01/01/2020
		dataType: int64
		formatString: 0
		lineageTag: a8611d38-a2a7-4ded-a14c-1afbf2b46f37
		summarizeBy: sum
		sourceColumn: 01/01/2020

		annotation SummarizationSetBy = Automatic

	column 01/02/2020
		dataType: int64
		formatString: 0
		lineageTag: 2199d9f6-3984-48ed-a9cf-33ce2388e3ad
		summarizeBy: sum
		sourceColumn: 01/02/2020

		annotation SummarizationSetBy = Automatic

	column 01/03/2020
		dataType: int64
		formatString: 0
		lineageTag: 4f92a19c-086d-434f-be7a-4a7fc2565768
		summarizeBy: sum
		sourceColumn: 01/03/2020

		annotation SummarizationSetBy = Automatic

	column 01/04/2020
		dataType: int64
		formatString: 0
		lineageTag: 36272e87-233e-4bea-84a6-09ccde34958a
		summarizeBy: sum
		sourceColumn: 01/04/2020

		annotation SummarizationSetBy = Automatic

	column 01/05/2020
		dataType: int64
		formatString: 0
		lineageTag: d37e00f0-79a5-42b3-9055-43a23aefd60e
		summarizeBy: sum
		sourceColumn: 01/05/2020

		annotation SummarizationSetBy = Automatic

	column 01/06/2020
		dataType: int64
		formatString: 0
		lineageTag: 972c83ba-cb8c-478c-9b41-129dc23a7a59
		summarizeBy: sum
		sourceColumn: 01/06/2020

		annotation SummarizationSetBy = Automatic

	column 01/07/2020
		dataType: int64
		formatString: 0
		lineageTag: fe9fce9b-98eb-4f70-946e-1d33af61de2c
		summarizeBy: sum
		sourceColumn: 01/07/2020

		annotation SummarizationSetBy = Automatic

	column 01/08/2020
		dataType: int64
		formatString: 0
		lineageTag: 1b34c3f3-e2d0-481d-a113-0b0cdf92935b
		summarizeBy: sum
		sourceColumn: 01/08/2020

		annotation SummarizationSetBy = Automatic

	column 01/09/2020
		dataType: int64
		formatString: 0
		lineageTag: 69f370d9-a425-4866-86ed-329a85be183f
		summarizeBy: sum
		sourceColumn: 01/09/2020

		annotation SummarizationSetBy = Automatic

	column 01/10/2020
		dataType: int64
		formatString: 0
		lineageTag: eb8b64d4-25af-410e-a79b-a543c9e8a660
		summarizeBy: sum
		sourceColumn: 01/10/2020

		annotation SummarizationSetBy = Automatic

	column 01/11/2020
		dataType: int64
		formatString: 0
		lineageTag: 6f96a85b-08a1-4f95-a5d4-5770b6ba508e
		summarizeBy: sum
		sourceColumn: 01/11/2020

		annotation SummarizationSetBy = Automatic

	column 01/12/2020
		dataType: int64
		formatString: 0
		lineageTag: dc21585f-e9b2-42d6-96c3-0e3729b14881
		summarizeBy: sum
		sourceColumn: 01/12/2020

		annotation SummarizationSetBy = Automatic

	column 01/01/2021
		dataType: int64
		formatString: 0
		lineageTag: ac826b7b-cce4-4f13-826b-dff7d0935f0f
		summarizeBy: sum
		sourceColumn: 01/01/2021

		annotation SummarizationSetBy = Automatic

	column 01/02/2021
		dataType: int64
		formatString: 0
		lineageTag: 3b1c142b-bba1-4ec4-88bf-61d3f8bcb7b5
		summarizeBy: sum
		sourceColumn: 01/02/2021

		annotation SummarizationSetBy = Automatic

	column 01/03/2021
		dataType: int64
		formatString: 0
		lineageTag: bd66b2cb-0911-45a9-854e-5bfe3aee83f1
		summarizeBy: sum
		sourceColumn: 01/03/2021

		annotation SummarizationSetBy = Automatic

	column 01/04/2021
		dataType: int64
		formatString: 0
		lineageTag: 1ee6236d-6cd8-43cb-864b-29c31c399efe
		summarizeBy: sum
		sourceColumn: 01/04/2021

		annotation SummarizationSetBy = Automatic

	column 01/05/2021
		dataType: int64
		formatString: 0
		lineageTag: 5453dba3-7bb5-4c45-a7f0-a84e11e307d1
		summarizeBy: sum
		sourceColumn: 01/05/2021

		annotation SummarizationSetBy = Automatic

	column 01/06/2021
		dataType: int64
		formatString: 0
		lineageTag: 74f55292-bb6c-4e7e-b7fb-0e5ba0dacd72
		summarizeBy: sum
		sourceColumn: 01/06/2021

		annotation SummarizationSetBy = Automatic

	column 01/07/2021
		dataType: int64
		formatString: 0
		lineageTag: f04e2bfb-6776-45ba-8db2-b23e1093ea2c
		summarizeBy: sum
		sourceColumn: 01/07/2021

		annotation SummarizationSetBy = Automatic

	column 01/08/2021
		dataType: int64
		formatString: 0
		lineageTag: a57497a6-04bd-4aba-9464-c122ab589125
		summarizeBy: sum
		sourceColumn: 01/08/2021

		annotation SummarizationSetBy = Automatic

	column 01/09/2021
		dataType: int64
		formatString: 0
		lineageTag: 4b98e4e4-8ac5-416a-8ba2-4d9f9e576a36
		summarizeBy: sum
		sourceColumn: 01/09/2021

		annotation SummarizationSetBy = Automatic

	column 01/10/2021
		dataType: int64
		formatString: 0
		lineageTag: 408b2564-7753-4874-ad35-befd38dad7c9
		summarizeBy: sum
		sourceColumn: 01/10/2021

		annotation SummarizationSetBy = Automatic

	column 01/11/2021
		dataType: int64
		formatString: 0
		lineageTag: 9184983e-2224-457d-a77a-e9dc3c9cf736
		summarizeBy: sum
		sourceColumn: 01/11/2021

		annotation SummarizationSetBy = Automatic

	column 01/12/2021
		dataType: int64
		formatString: 0
		lineageTag: 4a4f8de4-8611-468f-9078-4c4debb1026f
		summarizeBy: sum
		sourceColumn: 01/12/2021

		annotation SummarizationSetBy = Automatic

	column 01/01/2022
		dataType: int64
		formatString: 0
		lineageTag: bacea55a-2a05-49ec-bcb3-c4a3b936adf1
		summarizeBy: sum
		sourceColumn: 01/01/2022

		annotation SummarizationSetBy = Automatic

	column 01/02/2022
		dataType: int64
		formatString: 0
		lineageTag: 430adaff-b2dc-40d8-b06a-1e0adb243c10
		summarizeBy: sum
		sourceColumn: 01/02/2022

		annotation SummarizationSetBy = Automatic

	column 01/03/2022
		dataType: int64
		formatString: 0
		lineageTag: 8f418075-f07d-420f-a4ea-9f1119b4b2ae
		summarizeBy: sum
		sourceColumn: 01/03/2022

		annotation SummarizationSetBy = Automatic

	column 01/04/2022
		dataType: int64
		formatString: 0
		lineageTag: 9afef41c-6378-46c2-8c1b-885a1c0cd8f7
		summarizeBy: sum
		sourceColumn: 01/04/2022

		annotation SummarizationSetBy = Automatic

	column 01/05/2022
		dataType: int64
		formatString: 0
		lineageTag: b3d57e73-0f64-40b5-a316-be5c26617186
		summarizeBy: sum
		sourceColumn: 01/05/2022

		annotation SummarizationSetBy = Automatic

	column 01/06/2022
		dataType: int64
		formatString: 0
		lineageTag: d5f8d08d-5fd7-44ad-8daf-75a5d500d8dd
		summarizeBy: sum
		sourceColumn: 01/06/2022

		annotation SummarizationSetBy = Automatic

	partition 'NDPP Referrals-110e4622-27c8-44db-9242-1c01f52dbafe' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Transformation\Diabetes\2. Project Management\National Diabetes Prevention Programme NDPP\Reports\Xyla H&W Reports\Monthly Reports\2022\Glocs NDPP Steering Group Report 07.06.22.xlsx"), null, true),
				    Referrals_Sheet = Source{[Item="Referrals",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Referrals_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type any}, {"Column5", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}, {"Column41", type any}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}, {"Column46", type any}, {"Column47", type any}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Practice Code", type text}, {"Practice Name", type text}, {"PCN", type text}, {"Column4", type any}, {"Locality", type text}, {"Total", Int64.Type}, {"2019/20", Int64.Type}, {"Column8", type any}, {"2020/21", Int64.Type}, {"2021/22", Int64.Type}, {"2022/23", Int64.Type}, {"01/07/2019", Int64.Type}, {"01/08/2019", Int64.Type}, {"01/09/2019", Int64.Type}, {"01/10/2019", Int64.Type}, {"01/11/2019", Int64.Type}, {"01/12/2019", Int64.Type}, {"01/01/2020", Int64.Type}, {"01/02/2020", Int64.Type}, {"01/03/2020", Int64.Type}, {"01/04/2020", Int64.Type}, {"01/05/2020", Int64.Type}, {"01/06/2020", Int64.Type}, {"01/07/2020", Int64.Type}, {"01/08/2020", Int64.Type}, {"01/09/2020", Int64.Type}, {"01/10/2020", Int64.Type}, {"01/11/2020", Int64.Type}, {"01/12/2020", Int64.Type}, {"01/01/2021", Int64.Type}, {"01/02/2021", Int64.Type}, {"01/03/2021", Int64.Type}, {"01/04/2021", Int64.Type}, {"01/05/2021", Int64.Type}, {"01/06/2021", Int64.Type}, {"01/07/2021", Int64.Type}, {"01/08/2021", Int64.Type}, {"01/09/2021", Int64.Type}, {"01/10/2021", Int64.Type}, {"01/11/2021", Int64.Type}, {"01/12/2021", Int64.Type}, {"01/01/2022", Int64.Type}, {"01/02/2022", Int64.Type}, {"01/03/2022", Int64.Type}, {"01/04/2022", Int64.Type}, {"01/05/2022", Int64.Type}, {"01/06/2022", Int64.Type}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type1",20)
				in
				    #"Removed Bottom Rows"

	annotation PBI_ResultType = Table

