table Sheet1
	lineageTag: bb28bcd2-4b89-442f-af1f-0b2cf2ee9a53

	measure 'Rate per 100000 of Population' =
			
			DIVIDE(SUM('Sheet1'[Value]), SUM('Piv (2)'[Total])) * 100000
		lineageTag: b8127291-bec9-4af1-a2f1-a370fc9ed1f3

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Other South West ICS' =
			
			DIVIDE(SUM('Sheet1'[Value]), SUM('Piv (2)'[Total])) * 100000
		lineageTag: 5e8560ac-86fa-417e-971a-0fe88df640bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Org Type'
		dataType: string
		lineageTag: 52fbc5e8-a1c8-438e-ae02-a1bcb93a5b8e
		summarizeBy: none
		sourceColumn: Org Type

		annotation SummarizationSetBy = Automatic

	column 'Org Name Full'
		dataType: string
		lineageTag: aafdefe2-51e1-43d9-8c97-638d9605ccb5
		summarizeBy: none
		sourceColumn: Org Name Full

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: 1d821934-2f6c-40f0-a11c-d6eb904356e8
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: d304f0c5-7844-4187-af68-28ed5aae3d9c
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column 'Aggregation Source'
		dataType: string
		lineageTag: d6ea5344-fce6-436a-8e0b-2e5b9e068500
		summarizeBy: none
		sourceColumn: Aggregation Source

		annotation SummarizationSetBy = Automatic

	column 'Period beginning'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7645417e-e1ed-4475-8b85-66e0601b6bd2
		summarizeBy: none
		sourceColumn: Period beginning

		variation Variation
			isDefault
			relationship: 4aa2d4ac-ccec-4938-b918-94d663c34eef
			defaultHierarchy: LocalDateTable_743a9447-9388-4728-abaa-68773e6cf53b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Category
		dataType: string
		lineageTag: 5925e0b4-fb3e-4ff9-ace0-9a27099f353a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'ICS Name Full'
		dataType: string
		lineageTag: 5e08fa3c-e0fe-42c6-8487-d238312b0d69
		summarizeBy: none
		sourceColumn: ICS Name Full

		annotation SummarizationSetBy = Automatic

	column 'NHS OF Metric Name'
		dataType: string
		lineageTag: 3187e27c-c6ef-4e9b-bb8d-bce63a95ad4c
		summarizeBy: none
		sourceColumn: NHS OF Metric Name

		annotation SummarizationSetBy = Automatic

	column 'Period Rank'
		dataType: int64
		formatString: 0
		lineageTag: 3c8ad7b1-5787-49a8-b815-8c8544d936f8
		summarizeBy: sum
		sourceColumn: Period Rank

		annotation SummarizationSetBy = Automatic

	column 'Region Name Full'
		dataType: string
		lineageTag: 502c1d95-2091-4005-b068-7dbef8d80b64
		summarizeBy: none
		sourceColumn: Region Name Full

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 60df4228-095d-460f-bb65-d65f0ebaab9e
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'NHS OF Metric Name Full'
		dataType: string
		lineageTag: 4bbc24fb-2b45-41e4-9f58-ce0935a7ea59
		summarizeBy: none
		sourceColumn: NHS OF Metric Name Full

		annotation SummarizationSetBy = Automatic

	column Origin_OrgType
		dataType: int64
		formatString: 0
		lineageTag: 10475020-1230-41ac-a576-51bbf8b9e22a
		summarizeBy: sum
		sourceColumn: Origin_OrgType

		annotation SummarizationSetBy = Automatic

	column 'Period Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: f5881c26-71fc-4ff4-b6f2-eb1e9586b4b4
		summarizeBy: none
		sourceColumn: Period Date

		variation Variation
			isDefault
			relationship: c6c04603-ee6b-44b0-b1b5-bdae518f144c
			defaultHierarchy: LocalDateTable_921d52f9-7086-4412-986b-1bcb6a0a5807.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Denominator
		dataType: string
		lineageTag: d3b22ebb-f328-4586-ad2e-300195b5d2e7
		summarizeBy: none
		sourceColumn: Denominator

		annotation SummarizationSetBy = Automatic

	column Numerator
		dataType: string
		lineageTag: 6789bfa7-feaf-452b-98ad-30bff4621852
		summarizeBy: none
		sourceColumn: Numerator

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 08d37c85-15da-4bcc-a0b0-d21426b5aba7
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ORG CODE'
		dataType: string
		lineageTag: f61717f3-9665-427c-a8ff-1f59b2189875
		summarizeBy: none
		sourceColumn: ORG CODE

		annotation SummarizationSetBy = Automatic

	column 'Other South West ICS Flag'
		dataType: string
		lineageTag: cf40eebb-846c-40f7-86f5-1649f14da105
		summarizeBy: none
		sourceColumn: Other South West ICS Flag

		annotation SummarizationSetBy = Automatic

	column 'Other South West ICS Value'
		dataType: string
		lineageTag: a09c744b-d5e5-4ce1-b11e-53a0bc1ffe48
		summarizeBy: none
		sourceColumn: Other South West ICS Value

		annotation SummarizationSetBy = Automatic

	column Code2
		dataType: string
		lineageTag: 0e784b5d-5d4f-4f5a-a93f-d8d1f8eda966
		summarizeBy: none
		sourceColumn: Code2

		annotation SummarizationSetBy = Automatic

	partition Sheet1-03462bc2-69b8-4c7a-957f-41ab0057716a = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\Data_extracted01022022.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Org Type", type text}, {"Org Name Full", type text}, {"Indicator", type text}, {"Code", type text}, {"Aggregation Source", type text}, {"Period beginning", type date}, {"Category", type text}, {"ICS Name Full", type text}, {"NHS OF Metric Name", type text}, {"Period Rank", Int64.Type}, {"Region Name Full", type text}, {"Sub-Category", type text}, {"NHS OF Metric Name Full", type text}, {"Origin_OrgType", Int64.Type}, {"Period Date", type datetime}, {"Denominator", type any}, {"Numerator", type any}, {"Value", type number}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([Org Name Full], ":"), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Text Before Delimiter",{"Org Type", "Org Name Full", "Text Before Delimiter", "Indicator", "Code", "Aggregation Source", "Period beginning", "Category", "ICS Name Full", "NHS OF Metric Name", "Period Rank", "Region Name Full", "Sub-Category", "NHS OF Metric Name Full", "Origin_OrgType", "Period Date", "Denominator", "Numerator", "Value"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Text Before Delimiter", "ORG CODE"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Other South West ICS", each if [Region Name Full] = "Y58: SOUTH WEST" then 1 else 0),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Conditional Column",{{"Other South West ICS", "Other South West ICS Flag"}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Renamed Columns1", "Other South West ICS Value", each if [Other South West ICS Flag] = 1 then [Value] else 0)
				in
				    #"Added Conditional Column1"

	annotation PBI_ResultType = Table

