table SQL_SOF_data_all
	lineageTag: dbee028e-cdb8-4145-8f54-565a9adecc1d

	column Period_Rank
		dataType: int64
		formatString: 0
		lineageTag: 93c2d4c9-a69d-4f8a-b090-8d75c4af2f15
		summarizeBy: sum
		sourceColumn: Period_Rank

		annotation SummarizationSetBy = Automatic

	column Region_Name_Full
		dataType: string
		lineageTag: 764c0963-bf18-44a5-87d8-1e8fefcdaef6
		summarizeBy: none
		sourceColumn: Region_Name_Full

		annotation SummarizationSetBy = Automatic

	column Sub_Category
		dataType: string
		lineageTag: 99387451-d5eb-4fc0-9905-3f5dacb46c29
		summarizeBy: none
		sourceColumn: Sub_Category

		annotation SummarizationSetBy = Automatic

	column Display_Value_P1
		dataType: double
		lineageTag: 1c6d8931-ec74-48b8-9535-6b9745cab204
		summarizeBy: sum
		sourceColumn: Display_Value_P1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NHS_OF_Metric_Name_Full
		dataType: string
		lineageTag: ba22423d-051a-49ac-8a19-bdad4e1b551f
		summarizeBy: none
		sourceColumn: NHS_OF_Metric_Name_Full

		annotation SummarizationSetBy = Automatic

	column Origin_OrgType
		dataType: int64
		formatString: 0
		lineageTag: a53e69bd-df64-4ffb-9e63-95abe849bf5a
		summarizeBy: sum
		sourceColumn: Origin_OrgType

		annotation SummarizationSetBy = Automatic

	column Period_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8fc87b59-7149-40a8-873c-0f2eadd48a29
		summarizeBy: none
		sourceColumn: Period_Date

		variation Variation
			isDefault
			relationship: bac555b8-a387-495f-bf02-0d3d1a2ff33a
			defaultHierarchy: LocalDateTable_a4a3594c-06fc-482f-b7a5-8f94ec765697.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Value_Benchmarking
		dataType: double
		lineageTag: c82fa153-add8-4512-a493-00feb0e07c08
		summarizeBy: sum
		sourceColumn: Value_Benchmarking

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Denominator
		dataType: double
		lineageTag: bd88e17e-34a9-4fb9-8841-36bee06ed108
		summarizeBy: sum
		sourceColumn: Denominator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Numerator
		dataType: double
		lineageTag: f01ea55d-793e-41fb-a55f-ffe1e2e3ccbd
		summarizeBy: sum
		sourceColumn: Numerator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		dataType: double
		lineageTag: aabebb40-a3cb-4336-bc60-5c576c317863
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Org_Name
		dataType: string
		lineageTag: 88af5e6b-90d4-44d7-ba62-80aecc042c18
		summarizeBy: none
		sourceColumn: Org_Name

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: 6d4d9a5e-ff45-4471-97f3-452daef4be96
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column Aggregation_Source
		dataType: string
		lineageTag: f639581f-eddd-4db4-9a9a-e9e8c776f48f
		summarizeBy: none
		sourceColumn: Aggregation_Source

		annotation SummarizationSetBy = Automatic

	column Period_beginning
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b1523b9-74ca-4c33-91d0-5f8fe00540c2
		summarizeBy: none
		sourceColumn: Period_beginning

		variation Variation
			isDefault
			relationship: 881daed6-6588-4fe7-be44-bb334a3d052a
			defaultHierarchy: LocalDateTable_66ce71ed-1fed-4870-b20b-ae709d02ba81.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d87f7b3a-f597-4b02-abbd-25ecddbfa7dd
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column ICS_Name_Full
		dataType: string
		lineageTag: a4623af4-eb9b-4822-990b-a6e5750c363f
		summarizeBy: none
		sourceColumn: ICS_Name_Full

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: ad865032-7dd8-400d-95a4-8a572e28c679
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column 'ORG CODE'
		dataType: string
		lineageTag: 9949a334-2ebe-4376-abb7-69d8f46fb2d4
		summarizeBy: none
		sourceColumn: ORG CODE

		annotation SummarizationSetBy = Automatic

	partition SQL_SOF_data_all-46cd0ecf-4770-485c-acef-e8e892b1b41b = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("GRH-CCG-SQL", "BIReports", [Query="SELECT [Period_Rank]#(lf)      ,[Region_Name_Full]#(lf)      ,[Sub_Category]#(lf)      ,[Display_Value_P1]#(lf)      ,[NHS_OF_Metric_Name_Full]#(lf)      ,[Origin_OrgType]#(lf)      ,[Period_Date]#(lf)      ,[Value_Benchmarking]#(lf)      ,[Denominator]#(lf)      ,[Numerator]#(lf)      ,[Value]#(lf)      ,[Org_Name]#(lf)      ,[Indicator]#(lf)      ,[Aggregation_Source]#(lf)      ,[Period_beginning]#(lf)      ,[Category]#(lf)      ,[ICS_Name_Full] FROM [BIReports].[dbo].[tbl_SOF_Metrics_Data]"]),
				    #"Inserted Text Between Delimiters" = Table.AddColumn(Source, "Text Between Delimiters", each Text.BetweenDelimiters([Org_Name], "(", ")"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Between Delimiters",{{"Text Between Delimiters", "ORG CODE"}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Renamed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Indicator], ":"), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "Code"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","","99",Replacer.ReplaceValue,{"ORG CODE"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value", "-", each if [ORG CODE] = "99" then [Org_Name] else [ORG CODE]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"-", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"ORG CODE"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"-", "ORG CODE"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns2","S001a: Appointments in general practice","S001a: The number of appointments that took place in general practice per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","S001a: Appointments in general practice","S001a: The number of appointments that took place in general practice per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","S005a: Daily discharges - as % of patients who no longer meet the criteria to reside in hospital","S005a: Patients discharged from hospital as a percentage of those who no longer meet the criteria to reside",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","S005a: Daily discharges - as % of patients who no longer meet the criteria to reside in hospital","S005a: Patients discharged from hospital as a percentage of those who no longer meet the criteria to reside",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","S008a: Overall size of the waiting list","S008a: The number of incomplete referral to treatment pathways per 100,000 of the population: size of the RTT waiting list",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","S008a: Overall size of the waiting list","S008a: The number of incomplete referral to treatment pathways per 100,000 of the population: size of the RTT waiting list",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","S009a: Patients waiting more than 52 weeks to start consultant-led treatment","S009a: Planned Care: The number of patients waiting more than 52 weeks to start treatment per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","S009a: Patients waiting more than 52 weeks to start consultant-led treatment","S009a: Planned Care: The number of patients waiting more than 52 weeks to start treatment per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","S010a: Cancer - first treatments","S010a: Cancer: The percentage of patients that are seen within 31 days from diagnosis to first treatment: decision to treat",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","S010a: Cancer - first treatments","S010a: Cancer: The percentage of patients that are seen within 31 days from diagnosis to first treatment: decision to treat",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","S011a: Cancer - people waiting longer than 62 days","S011a: Cancer: The number of patients waiting more than 62 days for cancer treatment from referral per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","S011a: Cancer - people waiting longer than 62 days","S011a: Cancer: The number of patients waiting more than 62 days for cancer treatment from referral per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","S012a: Cancer - % meeting faster diagnosis standard","S012a: Cancer: The percentage of patients who are diagnosed within 28 days of referral for suspected cancer",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","S012a: Cancer - % meeting faster diagnosis standard","S012a: Cancer: The percentage of patients who are diagnosed within 28 days of referral for suspected cancer",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","S013a: Diagnostic activity levels - Imaging","S013a: Diagnostics: The number of imaging diagnostics for selected modalities (MRI, CT and non-obstetric ultrasound) per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","S013a: Diagnostic activity levels - Imaging","S013a: Diagnostics: The number of imaging diagnostics for selected modalities (MRI, CT and non-obstetric ultrasound) per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","S013b: Diagnostic activity levels - Physiological measurement","S013b: Diagnostics: The number of physical measurement diagnostics for selected modalities (cardiology and echocardiography) per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","S013b: Diagnostic activity levels - Physiological measurement","S013b: Diagnostics: The number of physical measurement diagnostics for selected modalities (cardiology and echocardiography) per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","S013c: Diagnostic activity levels - Endoscopy","S013c: Diagnostics: The number of endoscopy diagnostics for selected modalities (colonoscopy, flexi sigmoidoscopy and gastroscopy) per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","S013c: Diagnostic activity levels - Endoscopy","S013c: Diagnostics: The number of endoscopy diagnostics for selected modalities (colonoscopy, flexi sigmoidoscopy and gastroscopy) per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","S014a: Cancer - proportion of people that survive cancer for at least 1 year after diagnosis","S014a: Cancer: The percentage of people who are still alive after at least 1 year of cancer diagnosis",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","S014a: Cancer - proportion of people that survive cancer for at least 1 year after diagnosis","S014a: Cancer: The percentage of people who are still alive after at least 1 year of cancer diagnosis",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","S015a: Cancer - proportion of cancers diagnosed at stages 1 or 2","S015a: Cancer: The percentage of cancers that are diagnosed at stages 1 or 2",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","S015a: Cancer - proportion of cancers diagnosed at stages 1 or 2","S015a: Cancer: The percentage of cancers that are diagnosed at stages 1 or 2",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","S017a: Outpatient - % of all activity delivered remotely via telephone or video consultation","S017a: Outpatients: The percentage of outpatient activity which is delivered remotely via telephone or video consultation",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","S017a: Outpatient - % of all activity delivered remotely via telephone or video consultation","S017a: Outpatients: The percentage of outpatient activity which is delivered remotely via telephone or video consultation",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","S019a: Ambulance handover delays greater than 30 minutes (as reported by NHS Acute Trusts)","S019a: Urgent Care: The total number of ambulance handover delays at the Emergency Department greater than 30 minutes",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","S019a: Ambulance handover delays greater than 30 minutes (as reported by NHS Acute Trusts)","S019a: Urgent Care: The total number of ambulance handover delays at the Emergency Department greater than 30 minutes",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","S020a: Ambulance response times (Category 1 incidents)","S020a: Category 1 incidents",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","S020a: Ambulance response times (Category 1 incidents)","S020a: Category 1 incidents",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","S020b: Ambulance response times (Category 2 incidents)","S020b: Category 2 incidents",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value32" = Table.ReplaceValue(#"Replaced Value31","S020b: Ambulance response times (Category 2 incidents)","S020b: Category 2 incidents",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value33" = Table.ReplaceValue(#"Replaced Value32","S020c: Ambulance response times (Category 3 incidents)","S020c: Category 3 incidents",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","S020c: Ambulance response times (Category 3 incidents)","S020c: Category 3 incidents",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value35" = Table.ReplaceValue(#"Replaced Value34","S020d: Ambulance response times (Category 4 incidents)","S020d: Category 4 incidents",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value36" = Table.ReplaceValue(#"Replaced Value35","S020d: Ambulance response times (Category 4 incidents)","S020d: Category 4 incidents",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value37" = Table.ReplaceValue(#"Replaced Value36","S021a: Maternity - % women on continuity of care pathway","S021a: Maternity: The percentage of women on the continuity of care pathway providing named midwives for individuals",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value38" = Table.ReplaceValue(#"Replaced Value37","S021a: Maternity - % women on continuity of care pathway","S021a: Maternity: The percentage of women on the continuity of care pathway providing named midwives for individuals",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value39" = Table.ReplaceValue(#"Replaced Value38","S022a: Maternity - number of stillbirths per 1,000 total births","S022a: Maternity: The number of stillbirths per 1,000 of total births",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value40" = Table.ReplaceValue(#"Replaced Value39","S022a: Maternity - number of stillbirths per 1,000 total births","S022a: Maternity: The number of stillbirths per 1,000 of total births",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value41" = Table.ReplaceValue(#"Replaced Value40","S023a: Maternity - number of neonatal deaths per 1,000 live births","S023a: Maternity: The number of neonatal deaths per 10,000 live births",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value42" = Table.ReplaceValue(#"Replaced Value41","S023a: Maternity - number of neonatal deaths per 1,000 live births","S023a: Maternity: The number of neonatal deaths per 10,000 live births",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value43" = Table.ReplaceValue(#"Replaced Value42","S024a: Proportion of NHS 111 callers given a booked time slot with an Emergency Department","S024a: Urgent Care: The percentage of NHS 111 callers given a booked time slot within an Emergency Department",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value44" = Table.ReplaceValue(#"Replaced Value43","S024a: Proportion of NHS 111 callers given a booked time slot with an Emergency Department","S024a: Urgent Care: The percentage of NHS 111 callers given a booked time slot within an Emergency Department",Replacer.ReplaceText,{"Indicator"}),	
					#"Replaced Value45" = Table.ReplaceValue(#"Replaced Value44","S026a: Proportion of ED patients who turn up unheralded","S026a: Urgent Care: The percentage of people turning up to the Emergency Department without a booked attendance",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value46" = Table.ReplaceValue(#"Replaced Value45","S026a: Proportion of ED patients who turn up unheralded","S026a: Urgent Care: The percentage of people turning up to the Emergency Department without a booked attendance",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value47" = Table.ReplaceValue(#"Replaced Value46","S029a: Reliance on specialist inpatient care for adults with a learning disability and/or autism","S029a: Learning Disabilities and Autism: The number of adult inpatients 18+ per 1 million of the adult population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value48" = Table.ReplaceValue(#"Replaced Value47","S029a: Reliance on specialist inpatient care for adults with a learning disability and/or autism","S029a: Learning Disabilities and Autism: The number of adult inpatients 18+ per 1 million of the adult population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value49" = Table.ReplaceValue(#"Replaced Value48","S030a: Percentage of people aged 14+  on the GP learning disability register receiving an annual health check","S030a: Learning Disabilities and Autism: The number of people aged 14+ on the GP LD reigster receiving an annual health check",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value50" = Table.ReplaceValue(#"Replaced Value49","S030a: Percentage of people aged 14+  on the GP learning disability register receiving an annual health check","S030a: Learning Disabilities and Autism: The number of people aged 14+ on the GP LD reigster receiving an annual health check",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value51" = Table.ReplaceValue(#"Replaced Value50","S031a: Number of personalised care interventions","S031a: Personalised Care: The number of people with personalised care interventions per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value52" = Table.ReplaceValue(#"Replaced Value51","S031a: Number of personalised care interventions","S031a: Personalised Care: The number of people with personalised care interventions per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value53" = Table.ReplaceValue(#"Replaced Value52","S032a: Personal Health Budgets","S032a: Personalised Care: The number of people with personal health budgets per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value54" = Table.ReplaceValue(#"Replaced Value53","S032a: Personal Health Budgets","S032a: Personalised Care: The number of people with personal health budgets per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value55" = Table.ReplaceValue(#"Replaced Value54","S033a: Social Prescribing unique patient referrals","S033a: Social Prescribing: The number of unique patient referrals per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value56" = Table.ReplaceValue(#"Replaced Value55","S033a: Social Prescribing unique patient referrals","S033a: Social Prescribing: The number of unique patient referrals per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value57" = Table.ReplaceValue(#"Replaced Value56","S034a: Summary Hospital-Level Mortality Indicator","S034a: Qualiity: Summary Hospital Level Mortality Indictor comparing number who die following hospitalisation and the number expected to die",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value58" = Table.ReplaceValue(#"Replaced Value57","S034a: Summary Hospital-Level Mortality Indicator","S034a: Qualiity: Summary Hospital Level Mortality Indictor comparing number who die following hospitalisation and the number expected to die",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value59" = Table.ReplaceValue(#"Replaced Value58","S035a: Overall CQC rating (provision of high-quality care)","S035a: provision of high-quality care",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value60" = Table.ReplaceValue(#"Replaced Value59","S035a: Overall CQC rating (provision of high-quality care)","S035a: provision of high-quality care",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value61" = Table.ReplaceValue(#"Replaced Value60","S036a: NHS Staff Survey Safety culture theme score","S036a: Quality: Summary Indicator providing an overall theme score regarding NHS perspection of a culture of safety",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value62" = Table.ReplaceValue(#"Replaced Value61","S036a: NHS Staff Survey Safety culture theme score","S036a: Quality: Summary Indicator providing an overall theme score regarding NHS perspection of a culture of safety",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value63" = Table.ReplaceValue(#"Replaced Value62","S037a: Patient experience of GP services","S037a: Primary Care: The percentage of people who assess their overall experience of GP Practices as 'very good' or 'fairly good'",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value64" = Table.ReplaceValue(#"Replaced Value63","S037a: Patient experience of GP services","S037a: Primary Care: The percentage of people who assess their overall experience of GP Practices as 'very good' or 'fairly good'",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value65" = Table.ReplaceValue(#"Replaced Value64","S038a: Potential under-reporting of patient safety incidents","S038a: Quality: The percentage of months (within a six month reporting period",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value66" = Table.ReplaceValue(#"Replaced Value65","S038a: Potential under-reporting of patient safety incidents","S038a: Quality: The percentage of months (within a six month reporting period",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value67" = Table.ReplaceValue(#"Replaced Value66","S039a: National Patient Safety Alerts not completed by deadline","S039a: Quality: The number of national patient safety alerts that are not completed by the deadline",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value68" = Table.ReplaceValue(#"Replaced Value67","S039a: National Patient Safety Alerts not completed by deadline","S039a: Quality: The number of national patient safety alerts that are not completed by the deadline",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value69" = Table.ReplaceValue(#"Replaced Value68","S040a: Methicillin-resistant Staphylococcus aureus (MRSA) bacteraemia infections","S040a: Quality: The number of counts in a month of the number of Methicillin-resistant Staphylococcus aureus (MRSA) bacteraemia infections",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value70" = Table.ReplaceValue(#"Replaced Value69","S040a: Methicillin-resistant Staphylococcus aureus (MRSA) bacteraemia infections","S040a: Quality: The number of counts in a month of the number of Methicillin-resistant Staphylococcus aureus (MRSA) bacteraemia infections",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value71" = Table.ReplaceValue(#"Replaced Value70","S041a: Clostridium difficile infections","S041a: Quality: The number of counts in a month of Clostridium difficile infections",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value72" = Table.ReplaceValue(#"Replaced Value71","S041a: Clostridium difficile infections","S041a: Quality: The number of counts in a month of Clostridium difficile infections",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value73" = Table.ReplaceValue(#"Replaced Value72","S042a: E. coli blood stream infections","S042a: Quality: The number of counts in a month of E. coli blood stream infections",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value74" = Table.ReplaceValue(#"Replaced Value73","S042a: E. coli blood stream infections","S042a: Quality: The number of counts in a month of E. coli blood stream infections",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value75" = Table.ReplaceValue(#"Replaced Value74","S044a: Antimicrobial resistance: appropriate prescribing of antibiotics in primary care","S044a: Quality: The percentage of Antimicrobial antibiotics prescribed in primary care compared to all oral antibacterials",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value76" = Table.ReplaceValue(#"Replaced Value75","S044a: Antimicrobial resistance: appropriate prescribing of antibiotics in primary care","S044a: Quality: The percentage of Antimicrobial antibiotics prescribed in primary care compared to all oral antibacterials",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value77" = Table.ReplaceValue(#"Replaced Value76","S044b: Antimicrobial resistance: appropriate prescribing of broad spectrum antibiotics in primary care","S044b: Quality: The percentage of broad-spectrum antibiotic items prescribed in primary care compared to all anti-bacterial items prescribed",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value78" = Table.ReplaceValue(#"Replaced Value77","S044b: Antimicrobial resistance: appropriate prescribing of broad spectrum antibiotics in primary care","S044b: Quality: The percentage of broad-spectrum antibiotic items prescribed in primary care compared to all anti-bacterial items prescribed",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value79" = Table.ReplaceValue(#"Replaced Value78","S045a: COVID-19 - % adults vaccinated","S045a: Vaccinations: The percentage of adults receiving a first COVID vaccination",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value80" = Table.ReplaceValue(#"Replaced Value79","S045a: COVID-19 - % adults vaccinated","S045a: Vaccinations: The percentage of adults receiving a first COVID vaccination",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value81" = Table.ReplaceValue(#"Replaced Value80","S046a: Population vaccination coverage - MMR for two doses","S046a: Vaccinations: The percentage of children 5 years old who have received two MMR doses",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value82" = Table.ReplaceValue(#"Replaced Value81","S046a: Population vaccination coverage - MMR for two doses","S046a: Vaccinations: The percentage of children 5 years old who have received two MMR doses",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value83" = Table.ReplaceValue(#"Replaced Value82","S047a: Percentage of people aged 65 and over who received a flu vaccination","S047a: Vaccinations: The percentage of people 65+ who received a flu vaccination",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value84" = Table.ReplaceValue(#"Replaced Value83","S047a: Percentage of people aged 65 and over who received a flu vaccination","S047a: Vaccinations: The percentage of people 65+ who received a flu vaccination",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value85" = Table.ReplaceValue(#"Replaced Value84","S048a: Cancer - bowel screening coverage, aged 60-74, screened in last 30 months","S048a: Screening: The percentage of adults 65-74 years who had a screening in the last 30 months for bowel cancer",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value86" = Table.ReplaceValue(#"Replaced Value85","S048a: Cancer - bowel screening coverage, aged 60-74, screened in last 30 months","S048a: Screening: The percentage of adults 65-74 years who had a screening in the last 30 months for bowel cancer",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value87" = Table.ReplaceValue(#"Replaced Value86","S049a: Cancer - breast screening coverage, females aged 50-70, screened in last 36 months","S049a: Screening: The percentage of women 50-70 years who had a screenining in the last 36 months for breast cancer",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value88" = Table.ReplaceValue(#"Replaced Value87","S049a: Cancer - breast screening coverage, females aged 50-70, screened in last 36 months","S049a: Screening: The percentage of women 50-70 years who had a screenining in the last 36 months for breast cancer",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value89" = Table.ReplaceValue(#"Replaced Value88","S050a: Cancer - cervical screening coverage, females aged 25-64, attending screening within target period","S050a: Screening: The number of women 25-64 who have had a screenining in the target period for cervical cancer",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value90" = Table.ReplaceValue(#"Replaced Value89","S050a: Cancer - cervical screening coverage, females aged 25-64, attending screening within target period","S050a: Screening: The number of women 25-64 who have had a screenining in the target period for cervical cancer",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value91" = Table.ReplaceValue(#"Replaced Value90","S051a: Number of people supported through the NHS Diabetes Prevention programme","S051a: Diabetes: The percentage of people supported through the Diabetes Prevention Programme of the number of people targeted to complete",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value92" = Table.ReplaceValue(#"Replaced Value91","S051a: Number of people supported through the NHS Diabetes Prevention programme","S051a: Diabetes: The percentage of people supported through the Diabetes Prevention Programme of the number of people targeted to complete",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value93" = Table.ReplaceValue(#"Replaced Value92","S052a: Diabetes patients that have achieved all the NICE recommended treatment targets","S052a: Diabetes: The percentage of adults and children that have met the NICE recommended treatment targets",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value94" = Table.ReplaceValue(#"Replaced Value93","S052a: Diabetes patients that have achieved all the NICE recommended treatment targets","S052a: Diabetes: The percentage of adults and children that have met the NICE recommended treatment targets",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value95" = Table.ReplaceValue(#"Replaced Value94","S054a: Number of people receiving mechanical thrombectomy","S054a: CVD: The percentage of all stroke patients that have received a medical thrombectomy",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value96" = Table.ReplaceValue(#"Replaced Value95","S054a: Number of people receiving mechanical thrombectomy","S054a: CVD: The percentage of all stroke patients that have received a medical thrombectomy",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value97" = Table.ReplaceValue(#"Replaced Value96","S055a: General Practice Referrals to NHS Digital Weight Management Programme - Crude Rate/100,000 population","S055a: Obesity: Total number of referrals to the NHS Digital Weight Management Programme per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value98" = Table.ReplaceValue(#"Replaced Value97","S055a: General Practice Referrals to NHS Digital Weight Management Programme - Crude Rate/100,000 population","S055a: Obesity: Total number of referrals to the NHS Digital Weight Management Programme per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value99" = Table.ReplaceValue(#"Replaced Value98","S059a: CQC well-led rating","S059a: Workforce: CQC Well-Led rating for Providers",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value100" = Table.ReplaceValue(#"Replaced Value99","S059a: CQC well-led rating","S059a: Workforce: CQC Well-Led rating for Providers",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value101" = Table.ReplaceValue(#"Replaced Value100","S064a: Proportion of staff who report that in the last three months they have come to work despite not feeling well enough to perform their duties","S064a: Workforce: The proportion of staff who reported in the last 3 months they have come into work despite not feeling well enough to perform their duties",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value102" = Table.ReplaceValue(#"Replaced Value101","S064a: Proportion of staff who report that in the last three months they have come to work despite not feeling well enough to perform their duties","S064a: Workforce: The proportion of staff who reported in the last 3 months they have come into work despite not feeling well enough to perform their duties",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value103" = Table.ReplaceValue(#"Replaced Value102","S065a: Percentage of staff who say they are satisfied or very satisfied with the opportunities for flexible working patterns","S065a: Workforce: The proportion of staff who say they are satisfied or very satisfied with the opportunities for flexibile working patterns",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value104" = Table.ReplaceValue(#"Replaced Value103","S065a: Percentage of staff who say they are satisfied or very satisfied with the opportunities for flexible working patterns","S065a: Workforce: The proportion of staff who say they are satisfied or very satisfied with the opportunities for flexibile working patterns",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value105" = Table.ReplaceValue(#"Replaced Value104","S067a: Leaver rate","S067a: Workforce: The percentage of staff who have left the NHS during the last 12 months",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value106" = Table.ReplaceValue(#"Replaced Value105","S067a: Leaver rate","S067a: Workforce: The percentage of staff who have left the NHS during the last 12 months",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value107" = Table.ReplaceValue(#"Replaced Value106","S068a: Sickness absence","S068a: Workforce: The number of FTE working days lost to sickness",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value108" = Table.ReplaceValue(#"Replaced Value107","S068a: Sickness absence","S068a: Workforce: The number of FTE working days lost to sickness",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value109" = Table.ReplaceValue(#"Replaced Value108","S069a: NHS Staff Survey Staff engagement theme score","S069a: Workforce: Summary Indicator providing an overall theme score for NHS Staff Engagement",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value110" = Table.ReplaceValue(#"Replaced Value109","S069a: NHS Staff Survey Staff engagement theme score","S069a: Workforce: Summary Indicator providing an overall theme score for NHS Staff Engagement",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value111" = Table.ReplaceValue(#"Replaced Value110","S070a: Number of people working in the NHS who have had a flu vaccination","S070a: Vaccinations: The percentage of eligible NHS staff who have received a flu vaccination",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value112" = Table.ReplaceValue(#"Replaced Value111","S070a: Number of people working in the NHS who have had a flu vaccination","S070a: Vaccinations: The percentage of eligible NHS staff who have received a flu vaccination",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value113" = Table.ReplaceValue(#"Replaced Value112","S072a: Proportion of staff who agree that their organisation acts fairly with regard to career progression / promotion, regardless of ethnic background, gender, religion, sexual orientation, disability or age","S072a: Workforce: The proportion of staff who agree that their organisation acts fairly with regard to career progression / promotion, regardless of ethnic background, gender, religion, sexual orientation, disability or age",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value114" = Table.ReplaceValue(#"Replaced Value113","S072a: Proportion of staff who agree that their organisation acts fairly with regard to career progression / promotion, regardless of ethnic background, gender, religion, sexual orientation, disability or age","S072a: Workforce: The proportion of staff who agree that their organisation acts fairly with regard to career progression / promotion, regardless of ethnic background, gender, religion, sexual orientation, disability or age",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value115" = Table.ReplaceValue(#"Replaced Value114","S081a: IAPT access (total numbers accessing services)","S081a: Mental Health: The number of people who first receive IAPT support per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value116" = Table.ReplaceValue(#"Replaced Value115","S081a: IAPT access (total numbers accessing services)","S081a: Mental Health: The number of people who first receive IAPT support per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value117" = Table.ReplaceValue(#"Replaced Value116","S082a: IAPT recovery rate (%)","S082a: Mental Health: The percentage of people moving to recovery as a result of IAPT support",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value118" = Table.ReplaceValue(#"Replaced Value117","S082a: IAPT recovery rate (%)","S082a: Mental Health: The percentage of people moving to recovery as a result of IAPT support",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value119" = Table.ReplaceValue(#"Replaced Value118","S083a: Estimated diagnosis rate for people with dementia","S083a: Dementia: The percentage of people diagnosed with dementia compared to the estimated prevalance of dementia",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value120" = Table.ReplaceValue(#"Replaced Value119","S083a: Estimated diagnosis rate for people with dementia","S083a: Dementia: The percentage of people diagnosed with dementia compared to the estimated prevalance of dementia",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value121" = Table.ReplaceValue(#"Replaced Value120","S084a: Children and young people (ages 0-17) mental health services access (number with 1+ contact)","S084a: Mental Health: The number of children and young people who have received 1+ contact from mental health services",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value122" = Table.ReplaceValue(#"Replaced Value121","S084a: Children and young people (ages 0-17) mental health services access (number with 1+ contact)","S084a: Mental Health: The number of children and young people who have received 1+ contact from mental health services",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value123" = Table.ReplaceValue(#"Replaced Value122","S085a: People with severe mental illness receiving a full annual physical health check and follow up interventions","S085a: Mental Health: The number of people with severe mental illness receiving a full annual physical health check and follow up interventions",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value124" = Table.ReplaceValue(#"Replaced Value123","S085a: People with severe mental illness receiving a full annual physical health check and follow up interventions","S085a: Mental Health: The number of people with severe mental illness receiving a full annual physical health check and follow up interventions",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value125" = Table.ReplaceValue(#"Replaced Value124","S086a: Inappropriate adult acute mental health Out of Area Placement (OAP) bed days (internal or external)","S086a: Mental Health: The number of inappropriate out of area placement bed days internal or external to the sending provider",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value126" = Table.ReplaceValue(#"Replaced Value125","S086a: Inappropriate adult acute mental health Out of Area Placement (OAP) bed days (internal or external)","S086a: Mental Health: The number of inappropriate out of area placement bed days internal or external to the sending provider",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value127" = Table.ReplaceValue(#"Replaced Value126","S086b: Inappropriate adult acute mental health Out of Area Placement (OAP) bed days (external only)","S086b: Mental Health: The number of inappropriate out of area placement bed days external to the sending provider",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value128" = Table.ReplaceValue(#"Replaced Value127","S086b: Inappropriate adult acute mental health Out of Area Placement (OAP) bed days (external only)","S086b: Mental Health: The number of inappropriate out of area placement bed days external to the sending provider",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value129" = Table.ReplaceValue(#"Replaced Value128","S087a: Rate per 100,000 population of people in adult acute mental health beds with a length of stay over 60 days","S087a: Mental Health: The number of people in adult acute older mental health beds over 60 days per 100,000 of the population",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value130" = Table.ReplaceValue(#"Replaced Value129","S087a: Rate per 100,000 population of people in adult acute mental health beds with a length of stay over 60 days","S087a: Mental Health: The number of people in adult acute older mental health beds over 60 days per 100,000 of the population",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value131" = Table.ReplaceValue(#"Replaced Value130","S087b: Rate per 100,000 population of people in older adult acute mental health care with a length of stay over 90 days","S087b: Mental Health: The number of adults in older adult acute mental health care with a length of stay over 90 days",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value132" = Table.ReplaceValue(#"Replaced Value131","S087b: Rate per 100,000 population of people in older adult acute mental health care with a length of stay over 90 days","S087b: Mental Health: The number of adults in older adult acute mental health care with a length of stay over 90 days",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value133" = Table.ReplaceValue(#"Replaced Value132","S088a: Number of women accessing specialist community perinatal mental health services","S088a: Maternity: The number of women accessing specialist community perinatal mental health services",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value134" = Table.ReplaceValue(#"Replaced Value133","S088a: Number of women accessing specialist community perinatal mental health services","S088a: Maternity: The number of women accessing specialist community perinatal mental health services",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value135" = Table.ReplaceValue(#"Replaced Value134","S089a: Waiting times for Urgent Referrals to Children and Young People's Eating Disorder services","S089a: Mental Health: The proportion of children and young people with urgent eating disorder cases waiting one week or less from referral to treatment",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value136" = Table.ReplaceValue(#"Replaced Value135","S089a: Waiting times for Urgent Referrals to Children and Young People's Eating Disorder services","S089a: Mental Health: The proportion of children and young people with urgent eating disorder cases waiting one week or less from referral to treatment",Replacer.ReplaceText,{"Indicator"}),
					#"Replaced Value137" = Table.ReplaceValue(#"Replaced Value136","S089b: Waiting times for Routine Referrals to Children and Young People Eating Disorder Services","S089b: Mental Health: The proportion of children and young people with routine eating disorder cases waiting four weeks or less from referral to treatment",Replacer.ReplaceText,{"NHS_OF_Metric_Name_Full"}),
					#"Replaced Value138" = Table.ReplaceValue(#"Replaced Value137","S089b: Waiting times for Routine Referrals to Children and Young People Eating Disorder Services","S089b: Mental Health: The proportion of children and young people with routine eating disorder cases waiting four weeks or less from referral to treatment",Replacer.ReplaceText,{"Indicator"})
				in
				    #"Replaced Value138"
				```

	annotation PBI_ResultType = Exception

