table 'SW ICS'
	lineageTag: 1c002ae3-c08b-46bf-8662-7e608aacf950

	column 'ICS Name Full'
		dataType: string
		lineageTag: 68acea91-27fa-4cb2-bd0e-41c491d07224
		summarizeBy: none
		sourceColumn: ICS Name Full

		annotation SummarizationSetBy = Automatic

	column 'Region Name Full'
		dataType: string
		lineageTag: 808f8129-389f-48a0-aafc-d5f4e0ef92d3
		summarizeBy: none
		sourceColumn: Region Name Full

		annotation SummarizationSetBy = Automatic

	column 'ORG CODE'
		dataType: string
		lineageTag: 9781fbee-6f31-44cf-9514-adae90725fa6
		summarizeBy: none
		sourceColumn: ORG CODE

		annotation SummarizationSetBy = Automatic

	column 'NHS AREA CODE'
		dataType: string
		lineageTag: ea1c4e20-d7ad-4310-b079-b3047f9f5a63
		summarizeBy: none
		sourceColumn: NHS AREA CODE

		annotation SummarizationSetBy = Automatic

	partition 'SW ICS-befd91b3-5b39-471a-8425-e2552e6e1504' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\List Of South West ICS.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"ICS Name Full", type text}, {"Region Name Full", type text}, {"ORG CODE", type text}, {"NHS AREA CODE", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

