table 'SW ORGs'
	lineageTag: efcb9049-d366-4ade-9804-58cee69c468a

	column 'ORG CODE'
		dataType: string
		lineageTag: 2c649c01-01ae-4bd9-a5c8-25700d743816
		summarizeBy: none
		sourceColumn: ORG CODE

		annotation SummarizationSetBy = Automatic

	column 'ORG Name'
		dataType: string
		lineageTag: 936424e4-24f9-4d8f-b1f6-e73baa339ae0
		summarizeBy: none
		sourceColumn: ORG Name

		annotation SummarizationSetBy = Automatic

	partition 'SW ORGs-625fe97a-3d92-4d45-990c-7019b5c40451' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjT0VdJR8vMIVnDPyS9NTi0uSS0qzsgsSlVwdnZXitUBqfCDqvBOLcrLL0eSiIBKBOfnAnWlliCkTJ2hUk5FmcUl+Tk6Cn75RSUZCJWJeSlATilQCKe9pjB7XVLL8vPg4pZG7jCzE4HaQQZBzHZNLC6BW6CjEFyemZcC1AdSEJ6ZU4LuKy+Y6fkIp8cCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"ORG CODE" = _t, #"ORG Name" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ORG CODE", type text}, {"ORG Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

