table Table2
	lineageTag: f8cdb766-4efc-4af0-a53e-e5f68efb8817

	column Indicator
		dataType: string
		lineageTag: 782cb436-229f-4533-8e31-725536bbe313
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: 85a92d07-0c8f-46f4-9ea4-a4ed87bebcbe
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	partition Table2-9c93f963-206a-4925-a69d-adf5bbe6cf19 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\Metrics Update Frequency.xlsx"), null, true),
				    Table2_Table = Source{[Item="Table2",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table2_Table,{{"Indicator", type text}, {"Frequency", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

