table 'Transformation Area summary - manual'
	lineageTag: 8eee95b5-e6f6-4e48-b907-177a5dea2556

	column 'ICS Transformation area '
		dataType: string
		lineageTag: aa90e809-eebe-47c7-a981-fe35d4a9b5cf
		summarizeBy: none
		sourceColumn: "ICS Transformation area "

		annotation SummarizationSetBy = Automatic

	column Q1
		dataType: int64
		formatString: 0
		lineageTag: b73c045f-8519-4374-8fa4-32576c27edd2
		summarizeBy: sum
		sourceColumn: Q1

		annotation SummarizationSetBy = Automatic

	column Q2
		dataType: int64
		formatString: 0
		lineageTag: cf8aa0b5-3b48-45c1-a2af-85ca816cbc78
		summarizeBy: sum
		sourceColumn: Q2

		annotation SummarizationSetBy = Automatic

	column Q3
		dataType: int64
		formatString: 0
		lineageTag: 954601e7-407a-4ca8-b9e4-bce3f21bba63
		summarizeBy: sum
		sourceColumn: Q3

		annotation SummarizationSetBy = Automatic

	column Q4
		dataType: int64
		formatString: 0
		lineageTag: be229656-cc2c-465e-9c8a-8d8b2c94cf7f
		summarizeBy: sum
		sourceColumn: Q4

		annotation SummarizationSetBy = Automatic

	partition 'Transformation Area summary - manual-ba5b32c0-ab60-482a-8eb7-4343bc2e12af' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\Quartiles Summary.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ICS Transformation area ", type text}, {"Q1", Int64.Type}, {"Q2", Int64.Type}, {"Q3", Int64.Type}, {"Q4", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

