table 'Manual Metrics'
	lineageTag: 661ff0a3-6c09-4545-ae11-1775af36ffa5

	measure Mean3 = CALCULATE(AVERAGEX('Manual Metrics',[Value]), ALLSELECTED('Manual Metrics'))
		lineageTag: ee0fd2e6-8c12-401b-92de-c31b7e247600

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure StdDevMM = CALCULATE(STDEVX.P('Manual Metrics',[Value]),ALLSELECTED('Manual Metrics'))
		lineageTag: ffb9ab98-ed23-4056-ab5d-201a3aa1e84f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UCLMM = [Mean3]+(3*[StdDevMM])
		lineageTag: 94ceac1e-b50d-497a-878a-99e760a92fef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LCLMM = [Mean3]-(3*[StdDevMM])
		lineageTag: ebb4686b-5689-4146-b290-9f050546f22d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MeanManual = CALCULATE(AVERAGEX('Manual Metrics',[Value]), ALLSELECTED('Manual Metrics'))
		lineageTag: 9c5fa5a1-ae0e-4a52-86d1-5d75723b82da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure StdDevManual = CALCULATE(STDEVX.P('Manual Metrics',[Value]),ALLSELECTED('Manual Metrics'), 'Manual Metrics'[SPC Flag] = 1)
		lineageTag: 468a31dc-1615-4fb4-86f7-aa00e746b7c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mean %' = CALCULATE(AVERAGEX('Manual Metrics',[Value - %]), ALLSELECTED('Manual Metrics'))
		lineageTag: b24b2c22-6dd8-40ab-b654-bc3547db9d2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'StdDevMM %' = CALCULATE(STDEVX.P('Manual Metrics',[Value - %]),ALLSELECTED('Manual Metrics'))
		lineageTag: e55ad981-a57e-47e8-97e3-d47ee7a9fe38

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LCLMM %' = IF([Mean %]-(3*[StdDevMM %]) < 0, 0, [Mean %]-(3*[StdDevMM %]))
		lineageTag: 2adeef37-2695-40fb-91c6-1cc86fdbed3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'UCLMM %' = IF([Mean %]+(3*[StdDevMM %]) > 1, 1, [Mean %]+(3*[StdDevMM %]))
		lineageTag: 5196ebc1-faf9-4810-b1b6-63be224e55d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period_Rank
		dataType: int64
		formatString: 0
		lineageTag: ffbd90bf-0b7d-4483-a81e-b9787b34d1e4
		summarizeBy: sum
		sourceColumn: Period_Rank

		annotation SummarizationSetBy = Automatic

	column NHS_OF_Metric_Name_Full
		dataType: string
		lineageTag: c968dca3-eb1b-4569-9c92-6b5aa645ef46
		summarizeBy: none
		sourceColumn: NHS_OF_Metric_Name_Full

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: f5082147-86db-496e-b75e-ad063b0301e6
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column Period_Date
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: a4cf7ade-c0f6-4e51-8a76-ce3aaa848c76
		summarizeBy: none
		sourceColumn: Period_Date

		variation Variation
			isDefault
			relationship: 7ff6edcf-ffd7-4657-96d3-7fcec74239da
			defaultHierarchy: LocalDateTable_c08058ae-6fcd-4e5e-a60f-c901f916477f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Value
		dataType: double
		lineageTag: 2fe1d611-2572-401d-8da5-a5a689e9c115
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Org_Name
		dataType: string
		lineageTag: b18ba2e5-e9a3-406c-93db-ad8a539724bd
		summarizeBy: none
		sourceColumn: Org_Name

		annotation SummarizationSetBy = Automatic

	column Period_beginning
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 9df94ff2-a835-42d4-99e5-d5a6a33aa6c0
		summarizeBy: none
		sourceColumn: Period_beginning

		variation Variation
			isDefault
			relationship: 3497e819-c44b-4386-b27e-f75c53ef034d
			defaultHierarchy: LocalDateTable_13759db8-ed3a-4ffe-8f75-f741592536b3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'National Target'
		dataType: double
		lineageTag: dc1b3021-c422-422d-9340-fb7556b4c41f
		summarizeBy: sum
		sourceColumn: National Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local Target'
		dataType: string
		lineageTag: 55ed573d-caa9-4440-a003-160f0254a841
		summarizeBy: none
		sourceColumn: Local Target

		annotation SummarizationSetBy = Automatic

	column 'Good Is'
		dataType: string
		lineageTag: 4bbe7bb1-d233-41b5-a6ab-a33c2c8e28ff
		summarizeBy: none
		sourceColumn: Good Is

		annotation SummarizationSetBy = Automatic

	column Rate/Value
		dataType: string
		lineageTag: 3b4f5f67-c137-4af2-b559-2420c9ea65d1
		summarizeBy: none
		sourceColumn: Rate/Value

		annotation SummarizationSetBy = Automatic

	column 'National Target Flagging'
		dataType: int64
		formatString: 0
		lineageTag: 497fa424-5735-4ce4-8dba-d99dfcbf148c
		summarizeBy: sum
		sourceColumn: National Target Flagging

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Rank
		dataType: string
		lineageTag: 743fbd83-0f1b-4e6a-bfa1-6fd0a73fd3f6
		summarizeBy: none
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		formatString: 0.0
		lineageTag: b9890486-ab55-4189-8ab5-39d94f363c8f
		summarizeBy: sum
		sourceColumn: Target

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Met target?'
		dataType: int64
		formatString: 0
		lineageTag: 75ff0a2c-c350-4922-b1cd-571e650f2b30
		summarizeBy: sum
		sourceColumn: Met target?

		annotation SummarizationSetBy = Automatic

	column 'SPC Flag'
		dataType: string
		lineageTag: f1b7b46c-e9d8-4f29-a3fe-f86002c16fb6
		summarizeBy: none
		sourceColumn: SPC Flag

		annotation SummarizationSetBy = Automatic

	column 'Value - %'
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ee66e322-fda1-474f-9d17-eefd0bd5cffb
		summarizeBy: sum
		sourceColumn: Value - %

		annotation SummarizationSetBy = Automatic

	column 'Target - %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 93373f15-a68e-4810-900c-9266c2bedc20
		summarizeBy: sum
		sourceColumn: Target - %

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 4cadf1dd-986e-4915-a98e-81d052f687d1
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 06594e0d-fad6-4517-91a4-2f15a5bcc845
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 16ac5660-9d34-40eb-a069-dcf2382c959b
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: c038848a-c828-4468-8fc1-ba14d4e886de
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	partition 'Manual Metrics-49bef1c9-36d7-4fff-924b-77aff01babb6' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\SOF Metrics\TAdams Working Folder\Data\Manual Metrics.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Period_Rank", Int64.Type}, {"NHS_OF_Metric_Name_Full", type text}, {"Indicator", type text}, {"Period_Date", type date}, {"Value", type number}, {"Org_Name", type text}, {"Period_beginning", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Indicator"}, #"Metric Polarity -manual update", {"ID"}, "Metric Polarity -manual update", JoinKind.LeftOuter),
				    #"Expanded Metric Polarity -manual update" = Table.ExpandTableColumn(#"Merged Queries", "Metric Polarity -manual update", {"Target Value", "Local target", "Good Is", "Rate/Value"}, {"Metric Polarity -manual update.Target Value", "Metric Polarity -manual update.Local target", "Metric Polarity -manual update.Good Is", "Metric Polarity -manual update.Rate/Value"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Metric Polarity -manual update",{{"Metric Polarity -manual update.Good Is", "Good Is"}, {"Metric Polarity -manual update.Local target", "Local Target"}, {"Metric Polarity -manual update.Rate/Value", "Rate/Value"}, {"Metric Polarity -manual update.Target Value", "National Target"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns",  "National Target Flagging", each if [Good Is]="Low" and [Value]<[National Target]
				then 1
				else if [Good Is]="Low" and [Value]>[National Target]
				then 0
				else if[Good Is]="High" and [Value]>[National Target] then 1
				else if[Good Is]="High" and [Value]<[National Target]
				then 0
				else null),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Met target?", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type1", "Value", "Value - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Value - Copy", "Value - %"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Value - %", Percentage.Type}}),
				    #"Divided Column" = Table.TransformColumns(#"Changed Type2", {{"Value - %", each _ / 100, Percentage.Type}}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Divided Column", "Target", "Target - Copy"),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Duplicated Column1",{{"Target - Copy", Percentage.Type}}),
				    #"Divided Column1" = Table.TransformColumns(#"Changed Type3", {{"Target - Copy", each _ / 100, Percentage.Type}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Divided Column1",{{"Target - Copy", "Target - %"}})
				in
				    #"Renamed Columns2"

	annotation PBI_ResultType = Table

