table Births
	lineageTag: 355420b1-7336-4083-a335-ba20a6fe92e9

	column UniqPregID
		dataType: string
		lineageTag: ed61d72e-e173-43de-859b-9ad8dca4d9c5
		summarizeBy: none
		sourceColumn: UniqPregID

		annotation SummarizationSetBy = Automatic

	column NHS_No_Mother
		dataType: string
		lineageTag: 6b547717-0149-4c8b-9e5e-8f285a6d4d92
		summarizeBy: none
		sourceColumn: NHS_No_Mother

		annotation SummarizationSetBy = Automatic

	column EthnicCategoryMother
		dataType: string
		lineageTag: 2b27faca-a926-4991-8a50-cee78f167246
		summarizeBy: none
		sourceColumn: EthnicCategoryMother

		annotation SummarizationSetBy = Automatic

	column EthnicCategoryMotherDescription
		dataType: string
		lineageTag: 907d40c6-022d-49f7-ad4c-ed6fa657e1b7
		summarizeBy: none
		sourceColumn: EthnicCategoryMotherDescription

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: int64
		formatString: 0
		lineageTag: f8d892dc-c8ce-4305-a478-76e88a87df5a
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column MSD401_ID
		dataType: int64
		formatString: 0
		lineageTag: 9ebb658b-4bb2-4ee3-941b-6aafd87d70a5
		summarizeBy: count
		sourceColumn: MSD401_ID

		annotation SummarizationSetBy = Automatic

	column NHS_Number_Baby
		dataType: string
		lineageTag: d6966c8a-9e85-412f-a5ad-92ad9160c53a
		summarizeBy: none
		sourceColumn: NHS_Number_Baby

		annotation SummarizationSetBy = Automatic

	column Org_Provider_Code
		dataType: string
		lineageTag: 51228420-9a8f-4188-9e0e-1baa91935f74
		summarizeBy: none
		sourceColumn: Org_Provider_Code

		annotation SummarizationSetBy = Automatic

	column Org_Provider_Desc
		dataType: string
		lineageTag: 11b1052a-00c6-4377-82dc-2f905297e34b
		summarizeBy: none
		sourceColumn: Org_Provider_Desc

		annotation SummarizationSetBy = Automatic

	column MSDS_ID_Baby
		dataType: string
		lineageTag: 90b8e61b-76a8-4bb2-a3e4-b995b6fad969
		summarizeBy: none
		sourceColumn: MSDS_ID_Baby

		annotation SummarizationSetBy = Automatic

	column MSDS_ID_Mother
		dataType: string
		lineageTag: 5dd77e09-ca87-4177-b496-91a478deae94
		summarizeBy: none
		sourceColumn: MSDS_ID_Mother

		annotation SummarizationSetBy = Automatic

	column Org_Local_Patient_Baby_Code
		dataType: string
		lineageTag: 23ae0cb3-eccf-4f25-a9d6-ec3510815ec3
		summarizeBy: none
		sourceColumn: Org_Local_Patient_Baby_Code

		annotation SummarizationSetBy = Automatic

	column Birth_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 500ca8b2-855d-461c-aaf5-0aad1a8ce67c
		summarizeBy: none
		sourceColumn: Birth_Date

		variation Variation
			isDefault
			relationship: 107db641-9dab-40a2-ba9f-1ecf1a2e2ce3
			defaultHierarchy: LocalDateTable_056baa8d-b1d1-4c3a-9601-c411c9641250.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Birth_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 96a19746-f0fa-481f-a303-6376e4430b06
		summarizeBy: none
		sourceColumn: Birth_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column FinYr_Birth_Date
		dataType: string
		lineageTag: c20c4eb7-fca4-4a6b-8ce2-5c27b64d1894
		summarizeBy: none
		sourceColumn: FinYr_Birth_Date

		annotation SummarizationSetBy = Automatic

	column YearMonth_Birth_Date
		dataType: string
		lineageTag: b27256bb-d9e8-4226-a258-005b77ae8a79
		summarizeBy: none
		sourceColumn: YearMonth_Birth_Date

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Outcome_Code
		dataType: string
		lineageTag: 322b0656-7937-4c53-b152-a7f29641efd8
		summarizeBy: none
		sourceColumn: Pregnancy_Outcome_Code

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Outcome_Desc
		dataType: string
		lineageTag: a2ae9296-d3a3-4a06-b744-883681ed418a
		summarizeBy: none
		sourceColumn: Pregnancy_Outcome_Desc

		annotation SummarizationSetBy = Automatic

	column Sex_Baby_Code
		dataType: string
		lineageTag: c99be9da-94d2-4a9f-b95c-e252176a32c2
		summarizeBy: none
		sourceColumn: Sex_Baby_Code

		annotation SummarizationSetBy = Automatic

	column Sex_Baby_Desc
		dataType: string
		lineageTag: 3c68bdfe-230c-47de-951f-5b9547d668b3
		summarizeBy: none
		sourceColumn: Sex_Baby_Desc

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category_Baby_Code
		dataType: string
		lineageTag: 717e3bc6-6d9f-416b-b37d-2262fd2e43a0
		summarizeBy: none
		sourceColumn: Ethnic_Category_Baby_Code

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category_Baby_Desc
		dataType: string
		lineageTag: 1200b76c-5927-46bd-b396-e0c2377e90b0
		summarizeBy: none
		sourceColumn: Ethnic_Category_Baby_Desc

		annotation SummarizationSetBy = Automatic

	column Birth_order
		dataType: string
		lineageTag: 5a0b01f6-21d5-47d9-9273-d71e50a3bc00
		summarizeBy: none
		sourceColumn: Birth_order

		annotation SummarizationSetBy = Automatic

	column Death_Date_Baby
		dataType: dateTime
		formatString: General Date
		lineageTag: 2fe480eb-12af-49ee-99f8-9dcefa4317b5
		summarizeBy: none
		sourceColumn: Death_Date_Baby

		variation Variation
			isDefault
			relationship: 56a88773-69a9-459d-b2d4-06fd1b6fb133
			defaultHierarchy: LocalDateTable_df3c10cb-ce68-4245-9e52-01d2d1a3b88a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Death_Time_Baby
		dataType: dateTime
		formatString: Long Time
		lineageTag: a3a28f27-5c72-4e9f-80be-fe9f957a7aca
		summarizeBy: none
		sourceColumn: Death_Time_Baby

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Presentation_Code
		dataType: string
		lineageTag: 32e07fcd-ffae-413b-b7f1-ed171516aa1b
		summarizeBy: none
		sourceColumn: Presentation_Code

		annotation SummarizationSetBy = Automatic

	column Presentation_Desc
		dataType: string
		lineageTag: 6106d47b-a485-47e6-9710-21a3ba4ab7d8
		summarizeBy: none
		sourceColumn: Presentation_Desc

		annotation SummarizationSetBy = Automatic

	column Gestation_Length
		dataType: int64
		formatString: 0
		lineageTag: 2c18002f-0dfe-4a64-ad36-2de35573d159
		summarizeBy: sum
		sourceColumn: Gestation_Length

		annotation SummarizationSetBy = Automatic

	column Delivery_Method_Code
		dataType: string
		lineageTag: 97453bb8-e01a-433a-ae9e-25ba770595b5
		summarizeBy: none
		sourceColumn: Delivery_Method_Code

		annotation SummarizationSetBy = Automatic

	column Delivery_Method_Description
		dataType: string
		lineageTag: c61b6be3-5292-4e9c-9c88-da6ad50b7177
		summarizeBy: none
		sourceColumn: Delivery_Method_Description

		annotation SummarizationSetBy = Automatic

	column WaterDeliveryInd
		dataType: string
		lineageTag: 7002e2ac-dd9e-4f2d-9747-a3d37f46f1f2
		summarizeBy: none
		sourceColumn: WaterDeliveryInd

		annotation SummarizationSetBy = Automatic

	column Water_Delivery_Indicator
		dataType: string
		lineageTag: b9b70ff9-d32b-4234-a36b-4bff5b3a40c9
		summarizeBy: none
		sourceColumn: Water_Delivery_Indicator

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Code
		dataType: string
		lineageTag: 17a5c45b-7e92-49c5-9274-b667948e7404
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Code

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Desc
		dataType: string
		lineageTag: 8034a2a3-7737-49a7-b86a-bbca29e4fab8
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Desc

		annotation SummarizationSetBy = Automatic

	column Setting_Place_Birth_Code
		dataType: string
		lineageTag: f28e57d3-d939-430a-be37-51b5e4e4d516
		summarizeBy: none
		sourceColumn: Setting_Place_Birth_Code

		annotation SummarizationSetBy = Automatic

	column Setting_Place_Birth_Desc
		dataType: string
		lineageTag: d5e1c3f2-3198-4b9e-a40d-7d29effabc86
		summarizeBy: none
		sourceColumn: Setting_Place_Birth_Desc

		annotation SummarizationSetBy = Automatic

	column Baby_First_Feed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9022f949-420f-4e0c-8add-2c0446f8c8df
		summarizeBy: none
		sourceColumn: Baby_First_Feed_Date

		variation Variation
			isDefault
			relationship: 13b652d0-9d88-4d36-bf5c-38dbe25bfd2b
			defaultHierarchy: LocalDateTable_76a5f4bd-37ef-4c32-ab4e-e4a117d82b4b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Baby_First_Feed_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: b5685bbe-3e31-498c-a107-77578023ecf1
		summarizeBy: none
		sourceColumn: Baby_First_Feed_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Baby_First_Feed_Type_Code
		dataType: string
		lineageTag: 910c673f-7458-4850-ac09-3c295b95e3dc
		summarizeBy: none
		sourceColumn: Baby_First_Feed_Type_Code

		annotation SummarizationSetBy = Automatic

	column Baby_First_Feed_Type_Desc
		dataType: string
		lineageTag: 74e8857c-c95e-415e-ad8b-e388f7a3a4ed
		summarizeBy: none
		sourceColumn: Baby_First_Feed_Type_Desc

		annotation SummarizationSetBy = Automatic

	column Skin_to_Skin_Contact_1hr_Indicator
		dataType: string
		lineageTag: 53dc2140-e5ec-45ca-bfb1-4b2dfd6edf5f
		summarizeBy: none
		sourceColumn: Skin_to_Skin_Contact_1hr_Indicator

		annotation SummarizationSetBy = Automatic

	column Discharge_Date_Baby
		dataType: dateTime
		formatString: General Date
		lineageTag: 5f937c5f-867e-4723-9234-6da5ce171489
		summarizeBy: none
		sourceColumn: Discharge_Date_Baby

		variation Variation
			isDefault
			relationship: 5d8c9999-327e-49ec-a659-55e5d46fa927
			defaultHierarchy: LocalDateTable_53fe4899-43da-4f18-8261-c97c1e7bb8cc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Discharge_Time_Baby
		dataType: dateTime
		formatString: Long Time
		lineageTag: e01ae0b5-1184-4efd-b515-87a133127768
		summarizeBy: none
		sourceColumn: Discharge_Time_Baby

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Labour_Delivery_ID
		dataType: string
		lineageTag: de65df5c-50c1-4f06-b6a5-239670e98a00
		summarizeBy: none
		sourceColumn: Labour_Delivery_ID

		annotation SummarizationSetBy = Automatic

	column Care_Prof_ID_Delivery
		dataType: string
		lineageTag: a5752e9e-efcc-4f2f-bd41-928a59f92e45
		summarizeBy: none
		sourceColumn: Care_Prof_ID_Delivery

		annotation SummarizationSetBy = Automatic

	column Birth_Day_of_Week_Baby
		dataType: string
		lineageTag: f6ca7106-47bf-48f1-90ad-3ee591827c7d
		summarizeBy: none
		sourceColumn: Birth_Day_of_Week_Baby

		annotation SummarizationSetBy = Automatic

	column Meridian_of_Birth_Baby
		dataType: int64
		formatString: 0
		lineageTag: ded4c899-150f-452a-98bc-27be1c81262b
		summarizeBy: sum
		sourceColumn: Meridian_of_Birth_Baby

		annotation SummarizationSetBy = Automatic

	column Age_At_Birth_Mother
		dataType: int64
		formatString: 0
		lineageTag: 11617cf5-41bc-4091-896f-fd24af3c3ef5
		summarizeBy: sum
		sourceColumn: Age_At_Birth_Mother

		annotation SummarizationSetBy = Automatic

	column Age_at_Death_Baby
		dataType: int64
		formatString: 0
		lineageTag: f65fa848-5b52-4ee9-b301-50d75ccbcb13
		summarizeBy: sum
		sourceColumn: Age_at_Death_Baby

		annotation SummarizationSetBy = Automatic

	column Year_of_Death_Baby
		dataType: int64
		formatString: 0
		lineageTag: 37e1ceff-14ea-4b31-bf7a-d97203e47e77
		summarizeBy: sum
		sourceColumn: Year_of_Death_Baby

		annotation SummarizationSetBy = Automatic

	column Month_of_Death_Baby
		dataType: int64
		formatString: 0
		lineageTag: 0fa881af-c60f-49aa-801a-0b302bc4e9c6
		summarizeBy: sum
		sourceColumn: Month_of_Death_Baby

		annotation SummarizationSetBy = Automatic

	column Day_of_Death_Baby
		dataType: int64
		formatString: 0
		lineageTag: 75f2ea5b-84dc-4031-acd9-1a1b47147e62
		summarizeBy: sum
		sourceColumn: Day_of_Death_Baby

		annotation SummarizationSetBy = Automatic

	column MeridianOfDeathBaby
		dataType: int64
		formatString: 0
		lineageTag: c8065edb-53c5-43a3-943d-8fd94d0dbf38
		summarizeBy: sum
		sourceColumn: MeridianOfDeathBaby

		annotation SummarizationSetBy = Automatic

	column Year_of_Birth_Baby
		dataType: int64
		formatString: 0
		lineageTag: fe16aaf0-5b6d-480a-87a2-b9e9b9d73c44
		summarizeBy: sum
		sourceColumn: Year_of_Birth_Baby

		annotation SummarizationSetBy = Automatic

	column Month_of_Birth_Baby
		dataType: int64
		formatString: 0
		lineageTag: 2862f815-db41-4769-935a-faa1894dcbda
		summarizeBy: sum
		sourceColumn: Month_of_Birth_Baby

		annotation SummarizationSetBy = Automatic

	column Report_Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: eab26d5a-fb07-45e5-b3cc-1b38be40442a
		summarizeBy: none
		sourceColumn: Report_Start_Date

		variation Variation
			isDefault
			relationship: 9a977846-d79f-43c5-bca4-4f77cd4e8090
			defaultHierarchy: LocalDateTable_e39be0dd-ddfb-499e-a409-de7db5d7e18c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Report_End_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 10752e21-9583-402c-9032-10b6be10fa13
		summarizeBy: none
		sourceColumn: Report_End_Date

		variation Variation
			isDefault
			relationship: a73d66c3-f6d9-4035-9d79-9e41ce3b8c6d
			defaultHierarchy: LocalDateTable_7b765af5-de75-4a0f-abea-3e99d9193923.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Processed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b523be7-7ff0-4243-942b-bf1eb9d2b24e
		summarizeBy: none
		sourceColumn: Processed_Date

		variation Variation
			isDefault
			relationship: 44f7112f-32cd-409a-979d-77a6684109ae
			defaultHierarchy: LocalDateTable_a9d397a7-3f38-4f6c-9886-d16088f19485.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d2ca35e-9762-4894-a59e-1e3fb12f318b
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: 741af84f-dda5-4598-95af-aec04cea8e52
			defaultHierarchy: LocalDateTable_08acdf8f-a878-440d-b013-64788f2d8dee.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: #,0
		lineageTag: aac4a1df-76e4-4eae-9edc-97dc1ea27814
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Month_Year_BirthMonth = Births[YearMonth_Birth_Date]
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 566286f3-3efa-4980-9a0f-02637bdf8343
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e602c6ce-0abe-4de8-81ec-d1e987744da2
			defaultHierarchy: LocalDateTable_9de51cfa-dd7f-4241-ad86-0900cb26fe6b.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Gestation_Length_Weeks
		dataType: int64
		formatString: 0
		lineageTag: 9be52de5-4ee0-4346-a4f2-669eb7c32ea7
		summarizeBy: sum
		sourceColumn: Gestation_Length_Weeks

		annotation SummarizationSetBy = Automatic

	column Gestation_Length_Days
		dataType: int64
		formatString: 0
		lineageTag: 66dbb37b-d463-4bfa-bd38-968f56b6cb97
		summarizeBy: sum
		sourceColumn: Gestation_Length_Days

		annotation SummarizationSetBy = Automatic

	column Locality_current
		dataType: string
		lineageTag: c5e61245-0645-4205-a9a4-1f6a5da24dc5
		summarizeBy: none
		sourceColumn: Locality_current

		annotation SummarizationSetBy = Automatic

	column PCN_current
		dataType: string
		lineageTag: 79d5005c-59dc-40a8-99ca-2467c1fa993a
		summarizeBy: none
		sourceColumn: PCN_current

		annotation SummarizationSetBy = Automatic

	column CountyMother
		dataType: string
		lineageTag: 5023c18b-ae34-400c-b9cc-5daa7d1d7121
		summarizeBy: none
		sourceColumn: CountyMother

		annotation SummarizationSetBy = Automatic

	column County_Name
		dataType: string
		lineageTag: 0fcf102c-0c2b-4b9d-be83-372fae9fc410
		summarizeBy: none
		sourceColumn: County_Name

		annotation SummarizationSetBy = Automatic

	column County_Mother_group
		dataType: string
		lineageTag: 7a2b85bd-81fc-4215-8d9a-46e676480ef0
		summarizeBy: none
		sourceColumn: County_Mother_group

		annotation SummarizationSetBy = Automatic

	column LSOAMother2011
		dataType: string
		lineageTag: e8321341-4f47-4d28-b9f5-4eb0e55975ce
		summarizeBy: none
		sourceColumn: LSOAMother2011

		annotation SummarizationSetBy = Automatic

	column LAD_UAMother
		dataType: string
		lineageTag: 71771c8a-ab14-40c4-8992-1b21eec8ee2a
		summarizeBy: none
		sourceColumn: LAD_UAMother

		annotation SummarizationSetBy = Automatic

	column ElectoralWardMother
		dataType: string
		lineageTag: 1a46bf2d-6b2b-4779-b0ff-3d1cdd8d6a31
		summarizeBy: none
		sourceColumn: ElectoralWardMother

		annotation SummarizationSetBy = Automatic

	column CCGFromFile
		dataType: string
		lineageTag: 186b81a7-c596-4582-a4e0-b040ebeac836
		summarizeBy: none
		sourceColumn: CCGFromFile

		annotation SummarizationSetBy = Automatic

	column Year_Month
		dataType: int64
		formatString: 0
		lineageTag: ac70f485-aff2-487a-8f6c-c631084ab692
		summarizeBy: sum
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

	column Birth_Day_No_of_Week_Baby
		dataType: int64
		formatString: 0
		lineageTag: e8a9eea1-149f-4181-900a-7d4b3af3ad9f
		summarizeBy: sum
		sourceColumn: Birth_Day_No_of_Week_Baby

		annotation SummarizationSetBy = Automatic

	column Sex_Baby_Long_Desc
		dataType: string
		lineageTag: 95ef76cd-264b-4443-999a-4e86a93e20b2
		summarizeBy: none
		sourceColumn: Sex_Baby_Long_Desc

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Desc_plus
		dataType: string
		lineageTag: 23adbcbb-4e0e-4e19-88ae-0a6461db1e4a
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Desc_plus

		annotation SummarizationSetBy = Automatic

	column Birth_Day_of_Week_Baby2
		dataType: int64
		formatString: 0
		lineageTag: 55822e66-7a45-4fd4-94c4-b106874ba70e
		summarizeBy: sum
		sourceColumn: Birth_Day_of_Week_Baby2

		annotation SummarizationSetBy = Automatic

	column Org_Local_Patient_Baby_Desc
		dataType: string
		lineageTag: c05fdb3d-5c49-43b9-89a2-05e39d846828
		summarizeBy: none
		sourceColumn: Org_Local_Patient_Baby_Desc

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_Code
		dataType: string
		lineageTag: fb593ce9-3f6c-48e0-8ee2-dbbe7be491f2
		summarizeBy: none
		sourceColumn: LSOA_Name_Code

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_only
		dataType: string
		lineageTag: bd977db1-0f05-48c8-a2ed-6f076de55eac
		summarizeBy: none
		sourceColumn: LSOA_Name_only

		annotation SummarizationSetBy = Automatic

	column LSOA_Plus
		dataType: string
		lineageTag: ce030511-91e8-4df4-8ad8-fc54d04493d6
		summarizeBy: none
		sourceColumn: LSOA_Plus

		annotation SummarizationSetBy = Automatic

	column LADNM
		dataType: string
		lineageTag: b038ce01-12ea-4bea-9a1b-88a78e4b8dad
		summarizeBy: none
		sourceColumn: LADNM

		annotation SummarizationSetBy = Automatic

	partition Births = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Current", [Query="SELECT distinct [UniqPregID]#(lf),[MotherNHSNo] as [NHS_No_Mother]#(lf)      ,[EthnicCategoryMother]#(lf)      ,[EthnicCategoryMotherDescription]#(lf)  #(lf) -- demographics#(lf), M.[LocalityName] as [Locality_current]#(lf), M.[NetworkName] as  [PCN_current]#(lf)#(lf),[CountyMother]#(lf),C.[County_Name]#(lf)#(lf), case when [CountyMother] = 'E10000013' then 'Gloucestershire'#(lf)when [CountyMother] IS NULL then 'Unknown'#(lf)else 'Out of County'#(lf)END as [County_Mother_group]#(lf)#(lf),[LSOAMother2011]#(lf)--,OOC.[Lower_Super_Output_Area_Code]#(lf),LSOA.[LSOA_Name] as [LSOA_Name_Code]#(lf)#(lf),LEFT(LSOA.[LSOA_Name],LEN(LSOA.[LSOA_Name])-5) as [LSOA_Name_only]  -- takes [LSOA_Name_Code] and removes code & space from end #(lf), case when [LSOA_Name] IS NULL then [LADNM]                          -- if no LSOA listed, use LAD#(lf)else LEFT(LSOA.[LSOA_Name],LEN(LSOA.[LSOA_Name])-5)#(lf)end as [LSOA_Plus]#(lf)#(lf)----------------------------------------------#(lf),[LAD_UAMother]                --LOCAL AUTHORITY DISTRICT/UNITARY AUTHORITY#(lf),LAD.[LADNM]#(lf)#(lf),[ElectoralWardMother] #(lf)#(lf),[CCGFromFile] #(lf) #(lf) ,[Period]                                                                     -- definition  -- doesn't always match the [PersonBirthDateBaby]#(lf)      ,[MSD401_ID]#(lf)      ,[BabyNHSNo] as [NHS_Number_Baby]#(lf)#(lf)      ,[OrgCodeProvider] as [Org_Provider_Code]#(lf)      ,[OrgCodeProviderDescription] as [Org_Provider_Desc]#(lf)      ,[MSDS_ID_Baby]#(lf)      ,[MSDS_ID_Mother]#(lf)   #(lf)      ,[OrgIDLocalPatientIdBaby] as [Org_Local_Patient_Baby_Code]#(lf)      ,[OrgIDLocalPatientIdBabyDescription] as [Org_Local_Patient_Baby_Desc]#(lf)#(lf)#(tab)      ,[PersonBirthDateBaby] as [Birth_Date]        -- includes Still Births             LINKS TO THIS FIELD#(lf)      ,[PersonBirthTimeBaby] as [Birth_Time]#(lf)      ,[FinYr_Birth_Date] = REPLACE(D.[Fin_Year_YYYY_dash_YY], ' - ', '/')#(lf)#(tab) ,D.[Year_Month]#(lf)#(tab) ,[YearMonth_Birth_Date] = STUFF(D.[Year_Month], 5,0,'/')#(lf)#(tab)  ,D.[MonthYear_MMMM_YYYYY]  as [MonthYear_Birth_Date_LongDate]#(lf)#(tab)#(lf)#(tab),[DayOfBirthBaby] as [Birth_Day_No_of_Week_Baby]#(lf), case when [DayOfBirthBaby] = '1' then 'Monday'#(lf)  when [DayOfBirthBaby] = '2' then 'Tuesday'#(lf)  when [DayOfBirthBaby] = '3' then 'Wednesday'#(lf)  when [DayOfBirthBaby] = '4' then 'Thursday'#(lf)  when [DayOfBirthBaby] = '5' then 'Friday'#(lf)  when [DayOfBirthBaby] = '6' then 'Saturday'#(lf)  when [DayOfBirthBaby] = '7' then 'Sunday'#(lf)  END as [Birth_Day_of_Week_Baby]#(lf)#(lf)       ,[YearOfBirthBaby] as [Year_of_Birth_Baby]#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)      ,[MonthOfBirthBaby] as [Month_of_Birth_Baby]#(tab)-- number of month only#(lf)#(tab)  ,[DayOfBirthBaby] as [Birth_Day_of_Week_Baby]#(lf)#(lf)#(tab),[PregOutcome] as [Pregnancy_Outcome_Code]#(lf)    ,[PregOutcomeDescription] as [Pregnancy_Outcome_Desc]#(lf)   #(lf)   ,[PersonPhenSex] as [Sex_Baby_Code]#(lf)      ,[PersonPhenSexDescription] as [Sex_Baby_Long_Desc]#(lf) , case when [PersonPhenSex] = '9' then 'Indeterminate'#(lf) when [PersonPhenSex] = 'X' then 'Unknown (not recorded)'#(lf)  else [PersonPhenSexDescription] #(lf) END as [Sex_Baby_Desc]#(lf)#(lf)       ,[EthnicCategoryBaby] as [Ethnic_Category_Baby_Code]#(lf)      ,[EthnicCategoryBabyDescription] as [Ethnic_Category_Baby_Desc]#(lf)      ,[BirthOrderMaternitySUS] as [Birth_order]#(lf)      ,[PersonDeathDateBaby] as [Death_Date_Baby]#(lf)      ,[PersonDeathTimeBaby] as [Death_Time_Baby]#(lf)      ,[FetusPresentation] as [Presentation_Code]#(lf)      ,[FetusPresentationDescription] as [Presentation_Desc]#(lf) #(lf) ----------------------------------------------------------------------------------------------#(lf) --Gestation Length #(lf)  ,[GestationLengthBirth] as [Gestation_Length]                   --  Contains days and weeks combined in 1 column.  Split into 2 columns#(lf)#(lf)  , case when [GestationLengthBirth] < '45' then [GestationLengthBirth]   --  split column into Weeks#(lf)  else  [GestationLengthBirth] / 7#(lf)  end as [Gestation_Length_Weeks]#(lf) #(lf)#(lf)  , case when [GestationLengthBirth] > '44' then [GestationLengthBirth]     --  split column into Days#(lf)  else [GestationLengthBirth] * 7#(lf)  end as [Gestation_Length_Days]#(lf)#(lf)  ----------------------------------------------------------------------------------------------#(lf)    ,[DeliveryMethodCode] as [Delivery_Method_Code]#(lf)      ,[DeliveryMethodCodeDescription] as [Delivery_Method_Description]#(lf)   #(lf)   ,[WaterDeliveryInd]#(lf)   , case when [WaterDeliveryInd] = 'N' then 'No'#(lf)   when [WaterDeliveryInd] = 'Y' then 'Yes'#(lf)   else NULL end as [Water_Delivery_Indicator]#(lf)#(lf)      ,[OrgSiteIDActualDelivery] as [Org_Site_Actual_Delivery_Code]#(lf)#(tab)  ,[OrgSiteIDActualDeliveryDescription] as [Org_Site_Actual_Delivery_Desc]#(lf), case when ([OrgSiteIDActualDeliveryDescription] is NULL and [OrgCodeProviderDescription] = 'GLOUCESTERSHIRE HOSPITALS NHS FOUNDATION TRUST')  then [OrgCodeProviderDescription]#(lf)else [OrgSiteIDActualDeliveryDescription]#(lf)END AS [Org_Site_Actual_Delivery_Desc_plus]                                        -- WHERE ACTUAL SITE IS NULL CAN THEN SEE WHICH ARE AT LEAST GHNHSFT#(lf)#(lf)#(lf)      ,[SettingPlaceBirth] as [Setting_Place_Birth_Code]#(lf)      ,[SettingPlaceBirthDescription]  as [Setting_Place_Birth_Desc]#(lf)   #(lf)   ,[BabyFirstFeedDate] as [Baby_First_Feed_Date]#(lf)      ,[BabyFirstFeedTime]  as [Baby_First_Feed_Time]#(lf)      ,[BabyFirstFeedIndCode] as [Baby_First_Feed_Type_Code]#(lf)      ,[BabyFirstFeedIndCodeDescription] as [Baby_First_Feed_Type_Desc]     -- Breast milk or not#(lf)   #(lf)     , case when [SkinToSkinContact1HourInd] = 'Y' then 'Yes'                  -- Yes / No#(lf)   when [SkinToSkinContact1HourInd] = 'N' then 'No'#(lf)   else [SkinToSkinContact1HourInd] end as [Skin_to_Skin_Contact_1hr_Indicator]#(lf)   #(lf)   #(tab)  ,[DischargeDateBabyHosp] as [Discharge_Date_Baby]#(lf)      ,[DischargeTimeBabyHosp] as [Discharge_Time_Baby]#(lf)      ,[LabourDeliveryID] as [Labour_Delivery_ID]#(lf)      ,[CareProfLIDDel] as [Care_Prof_ID_Delivery]#(lf)   #(lf)         #(lf)   ,[MerOfBirthBaby] as [Meridian_of_Birth_Baby]#(lf)      ,[AgeAtBirthMother] as [Age_At_Birth_Mother]#(lf) #(lf) ,[AgeAtDeathBaby] as [Age_at_Death_Baby]#(lf)      ,[YearOfDeathBaby] as [Year_of_Death_Baby]#(lf)      ,[MonthOfDeathBaby] as [Month_of_Death_Baby]#(lf)      ,[DayOfDeathBaby] as [Day_of_Death_Baby]#(lf)      ,[MeridianOfDeathBaby]#(lf)     #(lf)#(tab) ,[RPStartDate] as [Report_Start_Date]#(lf)      ,[RPEndDate] as [Report_End_Date]#(lf)      ,[ProcessedDate] as [Processed_Date]#(lf)#(tab)  ,[Data_Updated] = GETDATE() #(lf)#(tab)  ,[Counter] = 1#(lf)  FROM [CCG_Current].[MSDS].[vw_103_Birth] AS B#(lf) LEFT JOIN [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates] as D#(lf)  on B.[PersonBirthDateBaby] = D.[Full_Date]#(lf)#(lf) LEFT JOIN [BIReports].[MPI].[MPI_current] AS M                                    #(lf)  ON b.[MotherNHSNo] = M.[Derived_Pseudo_NHS]#(lf)#(lf)LEFT JOIN  [DSCRO_NATIONAL_LOOKUPS].[ODS].[Counties_England_SCD] AS C#(lf)ON B.[CountyMother] COLLATE SQL_Latin1_General_CP1_CS_AS = C.[County_Code2]#(lf)#(lf)left join [DSCRO_NATIONAL_LOOKUPS].[ODS].[LSOA_2001_Names_And_Codes_England_Wales_NI_SCD] as LSOA#(lf)on B.[LSOAMother2011] COLLATE SQL_Latin1_General_CP1_CS_AS = LSOA.[LSOA_Code]#(lf)#(lf)left join [DSCRO_NATIONAL_LOOKUPS].[Ordnance_Survey].[Local_Authority_Districts] as LAD#(lf)on B.[LAD_UAMother]  COLLATE SQL_Latin1_General_CP1_CS_AS = LAD.[LADCD]#(lf)#(lf)  where  [PersonBirthDateBaby] >= '01/04/2019' #(lf) order by [PersonPhenSex]"]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"MonthYear_Birth_Date_LongDate"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

