table Pregnancies
	lineageTag: 4dcb749d-95a9-4511-89c2-d1b8a2fc4293

	column CCGFromFile
		dataType: string
		lineageTag: 260a9c71-075b-4496-a6a1-703d438c12a8
		summarizeBy: none
		sourceColumn: CCGFromFile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: int64
		formatString: 0
		lineageTag: f8192514-3b3f-40fb-a807-fbb76bb06e39
		summarizeBy: sum
		sourceColumn: Period

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MSD101_ID
		dataType: int64
		formatString: 0
		lineageTag: a673c1e4-db51-4945-b09a-9d48ee0c8667
		summarizeBy: count
		sourceColumn: MSD101_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecordNumber
		dataType: int64
		formatString: 0
		lineageTag: ac16fa39-b78d-478d-894b-2fc9412d038a
		summarizeBy: sum
		sourceColumn: RecordNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UniqSubmissionID
		dataType: int64
		formatString: 0
		lineageTag: 3c35ef4e-33f6-4246-bfb6-815a06bd8372
		summarizeBy: count
		sourceColumn: UniqSubmissionID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Code_Provider
		dataType: string
		lineageTag: 370ba460-7b44-4821-baa9-11503819062a
		summarizeBy: none
		sourceColumn: Org_Code_Provider

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Code_Provider_Desc
		dataType: string
		lineageTag: 3839e4d9-4564-4766-8e94-c49e4b30209a
		summarizeBy: none
		sourceColumn: Org_Code_Provider_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MSDS_ID_Mother
		dataType: string
		lineageTag: f232f0a9-02ec-4d97-8877-9315932abc10
		summarizeBy: none
		sourceColumn: MSDS_ID_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unique_Pregnancy_ID
		dataType: string
		lineageTag: 64787497-aaca-4c59-ada4-45fa75282985
		summarizeBy: none
		sourceColumn: Unique_Pregnancy_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Antenatal_App_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8f7f4f50-88de-405e-b8ba-75087494bbbf
		summarizeBy: none
		sourceColumn: Antenatal_App_Date

		variation Variation
			isDefault
			relationship: 9908e28a-1930-4bda-b4ca-2431e264817b
			defaultHierarchy: LocalDateTable_35abc1f0-49eb-40e3-bebd-3e7c6776adf7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearMonth_Antenatal_AppDate
		dataType: string
		lineageTag: 2032f8ac-f117-4bfd-b055-8f4344708ce0
		summarizeBy: none
		sourceColumn: YearMonth_Antenatal_AppDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinYr_Antental_App_Date
		dataType: string
		lineageTag: 9e101632-8ec3-4df1-b733-de5d1b8cc327
		summarizeBy: none
		sourceColumn: FinYr_Antental_App_Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Confirmed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: da833528-1f6e-4308-a1ae-eb64ec04ab8f
		summarizeBy: none
		sourceColumn: Pregnancy_Confirmed_Date

		variation Variation
			isDefault
			relationship: 004e6319-68db-4ee7-b976-000848d061f9
			defaultHierarchy: LocalDateTable_469a56a5-d27a-4a9f-a7c5-2404f2d6a67e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estimated_Delivery_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 70ae4695-e433-47fc-9d40-b5898714174c
		summarizeBy: none
		sourceColumn: Estimated_Delivery_Date

		variation Variation
			isDefault
			relationship: 8a374dbc-6173-409b-a9aa-8133f8154272
			defaultHierarchy: LocalDateTable_93e906f8-f18f-402f-983b-c7bcce04f230.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Site_Booked
		dataType: string
		lineageTag: 17fe442a-f4f9-41ef-845d-6c09dc8a5597
		summarizeBy: none
		sourceColumn: Org_Site_Booked

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Site_Booked_Desc
		dataType: string
		lineageTag: 453e5407-fb6a-4464-9471-fb7393abb318
		summarizeBy: none
		sourceColumn: Org_Site_Booked_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EDD_Method
		dataType: string
		lineageTag: 52b4fddf-6d6a-418a-918c-503279f7b334
		summarizeBy: none
		sourceColumn: EDD_Method

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EDD_Method_Desc
		dataType: string
		lineageTag: 11618cac-a8da-4184-a86b-1f06b16ab21a
		summarizeBy: none
		sourceColumn: EDD_Method_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source_of_Referral_Code
		dataType: string
		lineageTag: 76608c67-0321-4688-8be1-36aa5a59a991
		summarizeBy: none
		sourceColumn: Source_of_Referral_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source_of_Referral_Desc
		dataType: string
		lineageTag: 4a2d83a2-a808-4cdf-a819-86aefe3c0857
		summarizeBy: none
		sourceColumn: Source_of_Referral_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reason_Late_Booking_Code
		dataType: string
		lineageTag: bacff1f5-ab30-4ab2-a35c-a5dcc2a22633
		summarizeBy: none
		sourceColumn: Reason_Late_Booking_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reason_Late_Booking_Desc
		dataType: string
		lineageTag: a706a7a9-a8a9-4b84-ab50-bda9fe0a9d5e
		summarizeBy: none
		sourceColumn: Reason_Late_Booking_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Preg_First_Contact_Professional_Code
		dataType: string
		lineageTag: 76ee18c1-facd-4599-95a2-eeaa7dc32a0b
		summarizeBy: none
		sourceColumn: Preg_First_Contact_Professional_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Last_Menstrual_Period_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ba286a1-0d6e-4bd2-b568-aa81ed0a2daa
		summarizeBy: none
		sourceColumn: Last_Menstrual_Period_Date

		variation Variation
			isDefault
			relationship: 58f3d3e3-7850-4f44-8a80-c4c16db1e28a
			defaultHierarchy: LocalDateTable_87ccae57-2395-43fe-981d-d8adc0e3c902.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Disability_Indicator_Mother
		dataType: string
		lineageTag: 22c6c3db-ea18-425b-8e20-1270a82bbe12
		summarizeBy: none
		sourceColumn: Disability_Indicator_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Language_Code
		dataType: string
		lineageTag: d8b9c909-9682-4a66-8925-38c1d7fd1ebb
		summarizeBy: none
		sourceColumn: Language_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Language_Desc
		dataType: string
		lineageTag: 697a2c2e-029a-42df-bb95-f912582788e6
		summarizeBy: none
		sourceColumn: Language_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MH_Prediction_Detection_Mother
		dataType: string
		lineageTag: aa297034-b554-4033-a448-e6f0ec0ad576
		summarizeBy: none
		sourceColumn: MH_Prediction_Detection_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Complex_Social_Factors_Ind
		dataType: string
		lineageTag: cd2726de-1784-4490-ba6c-c0490d4f29be
		summarizeBy: none
		sourceColumn: Complex_Social_Factors_Ind

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Status_Code
		dataType: string
		lineageTag: 2f871f55-473e-4ffa-bcdf-d45fead6a65f
		summarizeBy: none
		sourceColumn: Employment_Status_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Status_Desc
		dataType: string
		lineageTag: 02dbbf2b-61e9-4644-8532-ca4229a3aa3f
		summarizeBy: none
		sourceColumn: Employment_Status_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Support Status_Indicator'
		dataType: string
		lineageTag: 0eda984b-f079-4c83-ba04-286756234709
		summarizeBy: none
		sourceColumn: Support Status_Indicator

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Partner
		dataType: string
		lineageTag: 9058833d-31c4-4f8d-8f19-3d97f6e5efef
		summarizeBy: none
		sourceColumn: Employment_Partner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Partner_Desc
		dataType: string
		lineageTag: d8b8582e-9144-4ee8-b615-d771b8f17f00
		summarizeBy: none
		sourceColumn: Employment_Partner_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Previous_Casesareans_Number
		dataType: int64
		formatString: 0
		lineageTag: e56305e6-27fe-49d9-958d-a8b5579366bd
		summarizeBy: sum
		sourceColumn: Previous_Casesareans_Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Previous_Live_Births_Number
		dataType: int64
		formatString: 0
		lineageTag: 40d24a88-0b95-4998-acbf-77077409a9b1
		summarizeBy: sum
		sourceColumn: Previous_Live_Births_Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Previous_Still_Births
		dataType: int64
		formatString: 0
		lineageTag: 23134d1a-5d34-4a6c-8f2f-81ca9b7d1560
		summarizeBy: sum
		sourceColumn: Previous_Still_Births

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Previous_Losses < 24 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 5f233264-9b2a-4826-89b6-8d791ae3fe13
		summarizeBy: sum
		sourceColumn: Previous_Losses < 24 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Folic_Acid_Supplement_Code
		dataType: string
		lineageTag: 50f1dfa9-fa93-4626-96c8-e8374893fd47
		summarizeBy: none
		sourceColumn: Folic_Acid_Supplement_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Folic_Acid_Supplement_Desc
		dataType: string
		lineageTag: 81a879e7-96c8-4531-abc4-84fd6e5d4912
		summarizeBy: none
		sourceColumn: Folic_Acid_Supplement_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Date_Mat_Service
		dataType: dateTime
		formatString: General Date
		lineageTag: 5100cc61-9b4a-4fca-aa0d-2e793d67d98f
		summarizeBy: none
		sourceColumn: Discharge_Date_Mat_Service

		variation Variation
			isDefault
			relationship: 5694b993-066a-474c-a070-ffc54f64ae6c
			defaultHierarchy: LocalDateTable_f34a1e5a-23b5-48fa-a631-13ecd75652c4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Reason_Code
		dataType: string
		lineageTag: 7591d2ec-46aa-4707-948e-d4feedce94fa
		summarizeBy: none
		sourceColumn: Discharge_Reason_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Reason_Desc
		dataType: string
		lineageTag: 33014c4a-4075-4b30-8f8f-93465f52b68f
		summarizeBy: none
		sourceColumn: Discharge_Reason_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LPIDMother
		dataType: string
		lineageTag: 85776258-ec5c-4304-87f7-22cdf0b9cad4
		summarizeBy: none
		sourceColumn: LPIDMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PregnancyID
		dataType: string
		lineageTag: e3a33232-1432-4910-8fee-5131b8abfd41
		summarizeBy: none
		sourceColumn: PregnancyID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AntePathLevel
		dataType: int64
		formatString: 0
		lineageTag: 3ebfa0b5-a2d5-4cb4-b47c-89c7b810911e
		summarizeBy: sum
		sourceColumn: AntePathLevel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AntePathLevelDescription
		dataType: string
		lineageTag: e56a8327-d7d5-4897-bc1b-bcacf4487802
		summarizeBy: none
		sourceColumn: AntePathLevelDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gestation_Age_at_Appt_Date_in_Days
		dataType: int64
		formatString: 0
		lineageTag: cbe78812-0b1d-49f2-bac1-e1e08365c660
		summarizeBy: sum
		sourceColumn: Gestation_Age_at_Appt_Date_in_Days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Smoking_Status_at_Booking
		dataType: string
		lineageTag: ce374b14-2294-462d-bc4e-72d217e7b119
		summarizeBy: none
		sourceColumn: Smoking_Status_at_Booking

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Smoking_Status_at_Delivery
		dataType: string
		lineageTag: 5f183e14-0981-4a1a-abb7-015ee6fac9de
		summarizeBy: none
		sourceColumn: Smoking_Status_at_Delivery

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Smoking_Status_at_Discharge
		dataType: string
		lineageTag: 109b55fd-4d1b-4db2-a586-4e7561ae63a9
		summarizeBy: none
		sourceColumn: Smoking_Status_at_Discharge

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cigarettes_Per_Day_Band
		dataType: string
		lineageTag: ff5967e6-2ad0-4d9d-baf1-38feee75b9f8
		summarizeBy: none
		sourceColumn: Cigarettes_Per_Day_Band

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BMI_at_Booking
		dataType: string
		lineageTag: c851e444-f8c6-4fa2-8d2b-3465bb1080e6
		summarizeBy: none
		sourceColumn: BMI_at_Booking

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BMI_Band
		dataType: string
		lineageTag: 14c29d99-03f5-45f3-a3b4-06ff3d85295b
		summarizeBy: none
		sourceColumn: BMI_Band

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Age_At_Booking_Mother
		dataType: int64
		formatString: 0
		lineageTag: 28096e71-7ff7-4de0-818a-abeaf44ade24
		summarizeBy: sum
		sourceColumn: Age_At_Booking_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Age_At_Booking_Mother_AgeBand5yr
		dataType: string
		lineageTag: cc2f2db9-6f0f-4431-8bfc-06d42dfba097
		summarizeBy: none
		sourceColumn: Age_At_Booking_Mother_AgeBand5yr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Org_Code APLC'
		dataType: string
		lineageTag: 6f3f446f-49c4-4ea8-b03f-8865d0b1e6eb
		summarizeBy: none
		sourceColumn: Org_Code APLC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Lead_Ante_Provider_Code
		dataType: string
		lineageTag: e03ef643-c25d-447a-9bbe-f55ed1eaf02c
		summarizeBy: none
		sourceColumn: Lead_Ante_Provider_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Lead_Ante_Provider_Desc
		dataType: string
		lineageTag: 8cc62292-2fbe-4895-85d7-bb5905a92b45
		summarizeBy: none
		sourceColumn: Lead_Ante_Provider_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Report_Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b718543-7974-4f89-a369-a9b639dca4e9
		summarizeBy: none
		sourceColumn: Report_Start_Date

		variation Variation
			isDefault
			relationship: 7a823185-0db1-4ce0-b816-86aeea95e887
			defaultHierarchy: LocalDateTable_8508e14c-1d31-4f82-992b-b43244ad9534.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Report_End_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8c95b97f-27b8-4915-9f12-64dca45ae8fa
		summarizeBy: none
		sourceColumn: Report_End_Date

		variation Variation
			isDefault
			relationship: 4e4f5e2c-5d5c-4602-b9df-7a4d58d3eacf
			defaultHierarchy: LocalDateTable_6a6755ab-31a0-42ed-8c7a-adaa294c7638.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: #,0
		lineageTag: 1072b0a0-382c-4091-afc3-cafab2fcb7b9
		summarizeBy: sum
		sourceColumn: counter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Processed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2cf1b183-5f4d-4f76-8f2c-c2870141318f
		summarizeBy: none
		sourceColumn: Processed_Date

		variation Variation
			isDefault
			relationship: 364e5944-eb9c-4e84-9eea-e8e3e76ae1d8
			defaultHierarchy: LocalDateTable_79888c70-0c5e-44e2-950b-21fab526e924.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Commissioner_Code
		dataType: string
		lineageTag: 10671a5a-1709-45bc-a34a-01bc7768ed3e
		summarizeBy: none
		sourceColumn: Org_Commissioner_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Commissioner_Desc
		dataType: string
		lineageTag: 3e5577c5-2872-4653-a3af-4122054bb763
		summarizeBy: none
		sourceColumn: Org_Commissioner_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 35a06827-191a-4d54-843b-f01d433e0de1
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: 7acd4dfb-42d3-4a2b-a68b-af87135c4355
			defaultHierarchy: LocalDateTable_58e96f6c-866a-46f5-b2f9-71e8aca8d5ff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MonthYear_MMMM_YYYYY
		dataType: string
		lineageTag: 7b016cbf-2e3c-414b-9fec-950d681122cf
		summarizeBy: none
		sourceColumn: MonthYear_MMMM_YYYYY

		annotation SummarizationSetBy = Automatic

	column MotherNHSNo
		dataType: string
		lineageTag: a0341559-5a8b-46ee-8df4-2e01a1fddf18
		summarizeBy: none
		sourceColumn: MotherNHSNo

		annotation SummarizationSetBy = Automatic

	column CountyMother
		dataType: string
		lineageTag: 98a42674-1af2-42b0-acf3-e2eec7b666b1
		summarizeBy: none
		sourceColumn: CountyMother

		annotation SummarizationSetBy = Automatic

	column County_Name
		dataType: string
		lineageTag: c6c362a7-9df0-4b3b-ae0f-eb5f33b5b1e3
		summarizeBy: none
		sourceColumn: County_Name

		annotation SummarizationSetBy = Automatic

	column County_Mother_group
		dataType: string
		lineageTag: d777bc42-89cd-4ca3-869a-72314b509e08
		summarizeBy: none
		sourceColumn: County_Mother_group

		annotation SummarizationSetBy = Automatic

	column LSOAMother2011
		dataType: string
		lineageTag: b89f2ad0-f61e-40a2-ae7e-4a2fc09b7971
		summarizeBy: none
		sourceColumn: LSOAMother2011

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_Code
		dataType: string
		lineageTag: 7c12795b-0e95-4f5e-a634-66cb7f52f6d0
		summarizeBy: none
		sourceColumn: LSOA_Name_Code

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_only
		dataType: string
		lineageTag: af84b9a6-1a82-4a83-a04f-05229449f4d1
		summarizeBy: none
		sourceColumn: LSOA_Name_only

		annotation SummarizationSetBy = Automatic

	column LSOA_Plus
		dataType: string
		lineageTag: ebb86c5f-cb8e-4469-b5c2-4df226084038
		summarizeBy: none
		sourceColumn: LSOA_Plus

		annotation SummarizationSetBy = Automatic

	column LAD_UAMother
		dataType: string
		lineageTag: 993f259e-38cc-4356-be3c-9a18f91f3eac
		summarizeBy: none
		sourceColumn: LAD_UAMother

		annotation SummarizationSetBy = Automatic

	column LADNM
		dataType: string
		lineageTag: 42e8b2af-5395-4723-97b7-4a5b2babbe84
		summarizeBy: none
		sourceColumn: LADNM

		annotation SummarizationSetBy = Automatic

	column ElectoralWardMother
		dataType: string
		lineageTag: f4e7ffe7-94a7-4a49-9ffb-4e1c5fefdb3e
		summarizeBy: none
		sourceColumn: ElectoralWardMother

		annotation SummarizationSetBy = Automatic

	column Locality_current
		dataType: string
		lineageTag: 2a54d220-8c4f-46c2-8a0d-fc5b02397f10
		summarizeBy: none
		sourceColumn: Locality_current

		annotation SummarizationSetBy = Automatic

	column PCN_current
		dataType: string
		lineageTag: 6297bc9a-ca71-4d82-bb04-6d8ea456dddc
		summarizeBy: none
		sourceColumn: PCN_current

		annotation SummarizationSetBy = Automatic

	column Gestation_Length_Months
		dataType: int64
		formatString: 0
		lineageTag: c2f370a5-b555-4ac3-9911-bd1f368968d4
		summarizeBy: sum
		sourceColumn: Gestation_Length_Months

		annotation SummarizationSetBy = Automatic

	column Alcohol_Units_at_Booking
		dataType: string
		lineageTag: 6ce193dc-5188-48ef-92b4-54140b7f9f73
		summarizeBy: none
		sourceColumn: Alcohol_Units_at_Booking

		annotation SummarizationSetBy = Automatic

	column AlcoholUnitsPerWeekBand
		dataType: string
		lineageTag: 2fd35bcd-4fad-4d35-a3a5-010746439ec5
		summarizeBy: none
		sourceColumn: AlcoholUnitsPerWeekBand

		annotation SummarizationSetBy = Automatic

	column Gestation_Age_at_Appt_Date_in_Weeks
		dataType: int64
		formatString: 0
		lineageTag: e84d4e41-b89b-43f9-81c2-887758b72b43
		summarizeBy: sum
		sourceColumn: Gestation_Age_at_Appt_Date_in_Weeks

		annotation SummarizationSetBy = Automatic

	column Gestation_Age_at_Appt_Group
		dataType: string
		lineageTag: f8b6a40d-486f-4308-9433-7f7a04061c8d
		summarizeBy: none
		sourceColumn: Gestation_Age_at_Appt_Group

		annotation SummarizationSetBy = Automatic

	column Preg_First_Contact_Professional_Desc
		dataType: string
		lineageTag: 5e59caeb-5964-4408-afae-48ff4b43ada0
		summarizeBy: none
		sourceColumn: Preg_First_Contact_Professional_Desc

		annotation SummarizationSetBy = Automatic

	column 'Gestation_Length_Target_Zones Week+Days'
		dataType: string
		lineageTag: 041428d8-4bec-4424-be62-a957056e8d6d
		summarizeBy: none
		sourceColumn: Gestation_Length_Target_Zones Week+Days

		annotation SummarizationSetBy = Automatic

	partition Pregnancies = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Current", [Query="SELECT  distinct  [UniqPregID]#(lf)[MotherNHSNo]#(lf)      ,[Period]#(lf)      ,[MSD101_ID]#(lf)      ,[RecordNumber]#(lf)      ,[UniqSubmissionID]#(lf)      ,[MSDS_ID_Mother]#(lf)      ,[UniqPregID] as [Unique_Pregnancy_ID]#(lf)#(lf)--demographics#(lf)   ,[CCGFromFile]   #(lf)   ,[OrgIDComm] as [Org_Commissioner_Code]#(lf)   ,[OrgIDCommDescription] as [Org_Commissioner_Desc]#(lf)     ,[CountyMother]#(lf)     ,C.[County_Name]#(lf)#(tab)#(lf), case when [CountyMother] = 'E10000013' then 'Gloucestershire'#(lf)when [CountyMother] IS NULL then 'Unknown'#(lf)else 'Out of County'#(lf)END as [County_Mother_group]#(lf)#(lf),[LSOAMother2011]#(lf),LSOA.[LSOA_Name] as [LSOA_Name_Code]#(lf),LEFT(LSOA.[LSOA_Name],LEN(LSOA.[LSOA_Name])-5) as [LSOA_Name_only]  -- takes [LSOA_Name_Code] and removes code & space from end #(lf), case when [LSOA_Name] IS NULL then [LADNM]                          -- if no LSOA listed, use LAD#(lf)else LEFT(LSOA.[LSOA_Name],LEN(LSOA.[LSOA_Name])-5)#(lf)end as [LSOA_Plus]#(lf)#(lf),[LAD_UAMother]                --LOCAL AUTHORITY DISTRICT/UNITARY AUTHORITY#(lf),LAD.[LADNM]#(lf),[ElectoralWardMother]#(lf)#(lf), M.[LocalityName] as [Locality_current]#(lf), M.[NetworkName] as  [PCN_current]#(lf)#(lf)-------------------------------------------------------#(lf)  --DATES#(lf)    ,[AntenatalAppDate] as [Antenatal_App_Date]#(lf)#(tab)#(lf)#(tab),[YearMonth_Antenatal_AppDate]   = STUFF(D.[Year_Month], 5,0,'/')   -- new reference table formatted for forward slash#(lf)#(lf)#(tab),[FinYr_Antental_App_Date] = REPLACE(D.[Fin_Year_YYYY_dash_YY], ' - ', '/') -- new reference table formatted as 2022/23 not with hyphen in#(lf)#(tab),D.[MonthYear_MMMM_YYYYY]           -- new reference table formatted as Month Year for front page#(lf)#(tab)#(lf)#(tab),[PregFirstConDate] as [Pregnancy_Confirmed_Date]   -- not fully populated#(lf)     #(lf)   ,[EDDAgreed] as [Estimated_Delivery_Date]#(lf)  #(lf)  ---------------------------------------------------------------------------#(lf)-- Gestation#(lf)#(lf)      ,[GestAgeAppDate] as [Gestation_Age_at_Appt_Date_in_Days]                -- difference between [AntenatalAppDate]  and [EDDAgreed] #(lf)#(tab)  ,[GestAgeAppDate] / 7  AS [Gestation_Age_at_Appt_Date_in_Weeks]#(lf)#(lf)#(lf)--#(tab),  (CAST([GestAgeAppDate] AS NUMERIC) / 7) as [Gestation_Age_Weeks_decimals]#(tab)#(tab)#(tab)-- not currently using in dashboard#(lf)  , [GestAgeAppDate] / 30 AS [Gestation_Length_Months]                                      -- not currently using in dashboard#(lf)#(tab) #(lf)#(tab) ,case when (CAST([GestAgeAppDate] AS NUMERIC) / 7) < '9.99999999999' then '<10 weeks'   -- grouping gestation at booking into 3 categories#(lf)#(tab)    when ((CAST([GestAgeAppDate] AS NUMERIC) / 7) >= '10.0' and (CAST([GestAgeAppDate] AS NUMERIC) / 7) <'13.0') then  '10.0-12.6 weeks'#(lf)#(tab)    when (CAST([GestAgeAppDate] AS NUMERIC) / 7) >= '13' then '13.0 + weeks'#(lf)        END AS [Gestation_Age_at_Appt_Group]#(lf)#(lf)#(lf)   ,case when [GestAgeAppDate] < '70' then 'Early'                   -- categorising early/on time/ late bookings for target gestation weeks + days (ie 10-1 = 10 weeks & 1 day etc)#(lf)   when [GestAgeAppDate]  = '70' then 'In: 10-0'#(lf)   when [GestAgeAppDate]  = '71' then 'In: 10-1'#(lf)   when [GestAgeAppDate]  = '72' then 'In: 10-2'#(lf)   when [GestAgeAppDate]  = '73' then 'In: 10-3'#(lf)   when [GestAgeAppDate]  = '74' then 'In: 10-4'#(lf)   when [GestAgeAppDate]  = '75' then 'In: 10-5'#(lf)   when [GestAgeAppDate]  = '76' then 'In: 10-6'#(lf)   when [GestAgeAppDate]  = '77' then 'In: 11-0'#(lf)   when [GestAgeAppDate]  = '78' then 'In: 11-1'#(lf)   when [GestAgeAppDate]  = '79' then 'In: 11-2'#(lf)   when [GestAgeAppDate]  = '80' then 'In: 11-3'#(lf)   when [GestAgeAppDate]  = '81' then 'In: 11-4'#(lf)   when [GestAgeAppDate]  = '82' then 'In: 11-5'#(lf)   when [GestAgeAppDate]  = '83' then 'In: 11-6'#(lf)   when [GestAgeAppDate]  = '84' then 'In: 12-0'#(lf)   when [GestAgeAppDate]  = '85' then 'In: 12-1'#(lf)   when [GestAgeAppDate]  = '86' then 'In: 12-2'#(lf)   when [GestAgeAppDate]  = '87' then 'In: 12-3'#(lf)   when [GestAgeAppDate]  = '88' then 'In: 12-4'#(lf)   when [GestAgeAppDate]  = '89' then 'In: 12-5'#(lf)   when [GestAgeAppDate]  = '90' then 'In: 12-6'#(lf)   when [GestAgeAppDate] >= '91' then 'Late'#(lf)   #(tab)END AS [Gestation_Length_Target_Zones Week+Days]#(lf)#(lf)#(tab)   #(tab)   #(lf)  ---------------------------------------------------------------------------#(lf) #(lf)   ,[ReasonLateBooking] as [Reason_Late_Booking_Code]#(lf)      ,[ReasonLateBookingDescription] as [Reason_Late_Booking_Desc]#(lf)#(lf) ,[OrgCodeProvider] as [Org_Code_Provider]#(lf)      ,[OrgCodeProviderDescription] as [Org_Code_Provider_Desc]#(lf)  #(lf) ,[OrgSiteIDBooking] as [Org_Site_Booked]#(lf)      ,[OrgSiteIDBookingDescription] as [Org_Site_Booked_Desc]#(lf)      ,[EDDMethodAgreed] as [EDD_Method]#(lf)      ,[EDDMethodAgreedDescription] as  [EDD_Method_Desc]#(lf)      ,[SourceRefMat] as [Source_of_Referral_Code]#(lf)      ,[SourceRefMatDescription] as [Source_of_Referral_Desc]#(lf)         #(lf)      ,[PregFirstContactCareProfType] as [Preg_First_Contact_Professional_Code]#(lf)      ,[PregFirstContactCareProfTypeDescription] as [Preg_First_Contact_Professional_Desc]#(lf)#(lf)      ,[LastMenstrualPeriodDate] as [Last_Menstrual_Period_Date]#(lf)      ,[DisabilityIndMother] as [Disability_Indicator_Mother]#(lf)      #(lf)#(tab)  ,[LangCode] as [Language_Code]#(lf)      ,[LangCodeDescription] as [Language_Desc]#(lf)      ,[MHPredictionDetectionIndMother] as [MH_Prediction_Detection_Mother]#(lf)      ,[ComplexSocialFactorsInd] as [Complex_Social_Factors_Ind]#(lf)      ,[EmploymentStatusMother] as [Employment_Status_Code]#(lf)      ,[EmploymentStatusMotherDescription] as [Employment_Status_Desc]#(lf)      ,[SupportStatusIndMother] as [Support Status_Indicator]#(lf)      ,[EmploymentStatusPartner] as [Employment_Partner]#(lf)      ,[EmploymentStatusPartnerDescription] as [Employment_Partner_Desc]#(lf)      ,[PreviousCaesareanSections] as [Previous_Casesareans_Number]#(lf)      ,[PreviousLiveBirths] as [Previous_Live_Births_Number]#(lf)      ,[PreviousStillBirths] as [Previous_Still_Births]#(lf)      ,[PreviousLossesLessThan24Weeks] as [Previous_Losses < 24 Weeks]#(lf)      ,[FolicAcidSupplement] as [Folic_Acid_Supplement_Code]#(lf)      ,[FolicAcidSupplementDescription] as [Folic_Acid_Supplement_Desc]#(lf)     #(lf)#(tab) ,[DischargeDateMatService] as [Discharge_Date_Mat_Service]#(lf)      ,[DischReason] as [Discharge_Reason_Code]#(lf)      ,[DischReasonDescription] as [Discharge_Reason_Desc]#(lf)      ,[LPIDMother]#(lf)      ,[PregnancyID]                                                   --not this unique#(lf)      ,[AntePathLevel]#(lf)      ,[AntePathLevelDescription]#(lf)#(lf)----------------------------------------------------------------------------#(lf)      ,[SmokingStatusBooking] as [Smoking_Status_at_Booking]#(lf)      ,[SmokingStatusDelivery] as [Smoking_Status_at_Delivery]#(lf)      ,[SmokingStatusDischarge] as [Smoking_Status_at_Discharge]#(lf)       ,[CigarettesPerDayBand] as [Cigarettes_Per_Day_Band]#(lf)#(tab)   ,[AlcoholUnitsBooking] as [Alcohol_Units_at_Booking]#(lf)       ,[AlcoholUnitsPerWeekBand] #(lf)#(tab) ,[PersonBMIBooking] as [BMI_at_Booking]#(lf)      ,[PersonBMIBand] as [BMI_Band]#(lf)     #(lf)     ,[AgeAtBookingMother] as [Age_At_Booking_Mother]#(lf)#(tab)  ,case when [AgeAtBookingMother] < '16' then '<16'#(lf)#(tab)  when [AgeAtBookingMother] between '16' and '19' then '16-19'#(lf)#(tab)  when [AgeAtBookingMother] between '20' and '24' then '20-24'#(lf)#(tab)  when [AgeAtBookingMother] between '25' and '29' then '25-29'#(lf)#(tab)  when [AgeAtBookingMother] between '30' and '34' then '30-34'#(lf)#(tab)  when [AgeAtBookingMother] between '35' and '39' then '35-39'#(lf)#(tab)  when [AgeAtBookingMother] between '40' and '44' then '40-44'#(lf)#(tab)  when [AgeAtBookingMother] between '45' and '49' then '45-49'#(lf)#(tab)  when [AgeAtBookingMother] between '50' and '54' then '50-54'#(lf)#(tab)  when [AgeAtBookingMother] > '54' then '55+'#(lf)#(tab)  END as [Age_At_Booking_Mother_AgeBand5yr]#(lf)#(lf)      ,[OrgCodeAPLC] as [Org_Code APLC]#(lf)      ,[LeadAnteProvider] as [Lead_Ante_Provider_Code]#(lf)      ,[LeadAnteProviderDescription] as [Lead_Ante_Provider_Desc]#(lf)      ,[RPStartDate] as [Report_Start_Date]#(lf)      ,[RPEndDate] as [Report_End_Date]#(lf)#(tab)  , [counter] = 1#(lf)      ,[ProcessedDate] as [Processed_Date]#(lf)#(tab)  ,[Data_Updated] = GETDATE() #(lf)  FROM [CCG_Current].[MSDS].[vw_101_Pregnancy] as P#(lf)  left join [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates] as D#(lf)  on P.[AntenatalAppDate] = D.[Full_Date]#(lf)#(lf)   LEFT JOIN [BIReports].[MPI].[MPI_current] AS M                                    #(lf)  ON P.[MotherNHSNo] = M.[Derived_Pseudo_NHS]#(lf)#(lf)LEFT JOIN  [DSCRO_NATIONAL_LOOKUPS].[ODS].[Counties_England_SCD] AS C#(lf)ON P.[CountyMother] COLLATE SQL_Latin1_General_CP1_CS_AS = C.[County_Code2]#(lf)#(lf)left join [DSCRO_NATIONAL_LOOKUPS].[ODS].[LSOA_2001_Names_And_Codes_England_Wales_NI_SCD] as LSOA#(lf)on P.[LSOAMother2011] COLLATE SQL_Latin1_General_CP1_CS_AS = LSOA.[LSOA_Code]#(lf)#(lf)left join [DSCRO_NATIONAL_LOOKUPS].[Ordnance_Survey].[Local_Authority_Districts] as LAD#(lf)on P.[LAD_UAMother]  COLLATE SQL_Latin1_General_CP1_CS_AS = LAD.[LADCD]#(lf)#(lf)  where [AntenatalAppDate] >= '2019/04/01'"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"N","No",Replacer.ReplaceText,{"Disability_Indicator_Mother"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Y","Yes",Replacer.ReplaceText,{"Disability_Indicator_Mother"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Y","Yes",Replacer.ReplaceText,{"MH_Prediction_Detection_Mother"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","N","No",Replacer.ReplaceText,{"MH_Prediction_Detection_Mother"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Y","Yes",Replacer.ReplaceText,{"Complex_Social_Factors_Ind"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","N","No",Replacer.ReplaceText,{"Complex_Social_Factors_Ind"})
				in
				    #"Replaced Value5"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

