table REF_Date_Ref
	lineageTag: a411c1ac-5bb7-4e1b-8d7d-1ac32e5fa4e9

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a0cb97a-3e1a-4af5-b433-89691c45212b
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 9c58e56d-abb2-4dad-bd97-4e45570d04f3
			defaultHierarchy: LocalDateTable_273c5c26-a4e3-4790-b0c7-eab166ce39f5.'Date Hierarchy'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: adf48597-5e58-41f2-b80c-1b72722d8e4c
		summarizeBy: none
		sourceColumn: day_month_year

		variation Variation
			isDefault
			relationship: c0cb55c8-7b61-4548-8df4-4068cd892ff6
			defaultHierarchy: LocalDateTable_681bb82b-6295-4e99-ab74-e8fab7a89257.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: cd43c0be-6ca1-46bf-ae13-9e6c14ad930e
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 95e1289f-b9fb-41cd-8bd3-27f7a8e49dbe
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: dec4b1f1-f8b2-483f-9029-06f64441cedf
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 4ba71a0b-c53b-4981-841a-b67722e5fe9f
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 1c50f4e8-64eb-4ccf-8ce0-28efcd051320
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 35f60cb8-5000-4333-a774-3923fcde2c42
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: f4c92099-072a-4650-ac95-a64fba5985b4
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 99565d2f-4bd8-4f92-b4e1-066518216c81
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: d9b69520-8911-473e-9bb2-382a1dc791ef
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 60a6393c-11dd-4a57-82a9-762d1c4f4a52
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 185cb86c-5aae-42b9-992d-3eec288488a9
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: d2100c17-4e2b-42aa-bd69-8780ae79f8c9
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 2299f83a-27fe-44d6-9145-545db2a7c753
		summarizeBy: sum
		sourceColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: DD/MM/YYYY hh:nn
		lineageTag: a283f6f0-71aa-4841-9917-10158a415ff6
		summarizeBy: none
		sourceColumn: Last_Updated

		variation Variation
			isDefault
			relationship: 7c2ea25a-ea18-49f1-bde0-37a5836a2b90
			defaultHierarchy: LocalDateTable_12c15d8f-9602-487d-94f6-9562bfa93bc5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Data_up_to
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d200216a-051c-4b16-9e01-08ad203ff621
		summarizeBy: none
		sourceColumn: Data_up_to

		variation Variation
			isDefault
			relationship: 74047e1d-0da0-4a53-98c0-b4b5cc10beb7
			defaultHierarchy: LocalDateTable_9dd94ee0-9ec2-401c-8ec1-2d358afef02b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2d3116e1-d297-4c0d-94cd-fb5915e04e90
		summarizeBy: sum
		sourceColumn: Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column MonthYearName
		dataType: string
		lineageTag: 39e7a050-d24b-4451-b4c3-929bd916a0a4
		summarizeBy: none
		sourceColumn: MonthYearName
		sortByColumn: year_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YearMonthIndex =
			
			
			
			RANKX(
			    ALL(REF_Date_Ref[year_month]),
			    REF_Date_Ref[year_month],
			    ,
			    ASC,
			    DENSE
			) - 1
		formatString: 0
		lineageTag: 19fc6e66-56f8-45b2-8080-7308b058257e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SPC_Flag
		dataType: int64
		formatString: 0
		lineageTag: 007e109a-e25c-4d27-9db9-489fc0d618de
		summarizeBy: sum
		sourceColumn: SPC_Flag

		annotation SummarizationSetBy = Automatic

	partition REF_Date_Ref = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="set nocount on#(lf)#(lf)/*------------------------------------------------------------#(lf)Declare Variables #(lf)/-------------------------------------------------------------*/#(lf)#(lf)----------------------------------------------#(lf)--Obtain the latest date in ePACT Dataset#(lf)----------------------------------------------#(lf)#(lf)declare @data_up_to as date#(lf)declare @reporting_month as int#(lf)#(lf)set @data_up_to = #(lf)#(lf)(select p.ePACT_Data_Up_To#(lf)from #(lf)#(lf)(select [ePACT_Data_Up_To] = eomonth(MAX([ePACT_Data_Up_To]))#(lf)#(lf)from PowerBI_Reporting.Prescribing.tbl03_Pain_Meds_Prescribing#(lf)) as p #(lf)#(lf)where p.ePACT_Data_Up_To <=  dateadd(month,-1,(eomonth(cast(getdate() as date))))#(lf))#(lf)#(lf)#(lf)#(lf)----------------------------------------------#(lf)--Get the latest reporting month#(lf)----------------------------------------------#(lf)#(lf)#(lf)set @reporting_month = #(lf)#(lf)(select distinct  financial_month#(lf)#(lf)from ccg_reference.reference.vw_date as d#(lf)where  d.Date = @data_up_to)#(lf)#(lf)#(lf)  ----------------------------------------------#(tab)#(lf)--Create final output reference table#(lf)----------------------------------------------#(lf)#(lf)select [date] = [date]#(lf)      ,[day_month_year] =  [day_month_year]#(lf)      ,[day] =  [day]#(lf)      ,[weekday]  = [weekday]#(lf)      ,[weekday_name] =  [weekday_name]#(lf)      ,[month] =  [month]#(lf)      ,[month_name] = left([month_name],3)#(lf)      ,[quarter] =  [quarter]#(lf)      ,[year_month] =  [year_month]#(lf)      ,[is_weekend]  =  [is_weekend]#(lf)      ,[is_holiday] = [is_holiday]#(lf)      ,[financial_week_of_year]  = [financial_week_of_year]#(lf)      ,[financial_year] =  [financial_year]#(lf)      ,[financial_quarter] =  [financial_quarter]#(lf)      ,[financial_month] = [financial_month]#(lf)#(tab)  ,[Last_Updated] = getdate()#(lf)#(tab)  ,[MonthYearName] = month_year_name#(lf)#(tab),[Data_up_to] = @data_up_to#(lf)#(tab),[SPC_Flag] = case when  CAST(date AS DATE) BETWEEN '20210401' AND '20240331' THEN 1 ELSE 0 END#(lf)#(tab)  ,[Reporting_Month_Flag] = case when financial_month <= @reporting_month then 1 else 0 end #(lf)      #(lf)from ccg_reference.reference.vw_date#(lf)where [Date] between '20190401' and  @data_up_to#(lf)#(lf)#(lf)order by date#(lf)#(lf)#(lf)#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

