table REF_PLS_Current
	lineageTag: 9d1f43a0-45c0-4728-a9f8-d677c91162b9

	measure '% of over 60_MPI' =
			
			
			
			
			calculate(SUM(REF_PLS_Current[COUNTER]),REF_PLS_Current[60_Flag] = 1)/sum(REF_PLS_Current[COUNTER])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c0ec334c-f44e-423a-91e9-2fa91aeb886c

		changedProperty = IsHidden

	measure '% of over 80_MPI' =
			
			
			
			calculate(sum(REF_PLS_Current[COUNTER]),REF_PLS_Current[80_Flag] = 1)/sum(REF_PLS_Current[COUNTER])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 412c0319-ef55-4876-bcc4-f64913916cc5

		changedProperty = IsHidden

	measure '% of BME_MPI' =
			
			
			
			
			calculate(SUM(REF_PLS_Current[COUNTER]),REF_PLS_Current[BME_flag])/sum(REF_PLS_Current[COUNTER])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 62e69da9-7123-401c-898b-1ce19b165b19

		changedProperty = IsHidden

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: 1751bba3-cfda-4d1a-acc2-aae7d01e37cf
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: 3e387998-496b-4b93-a125-61339644748a
		summarizeBy: none
		sourceColumn: PracticeCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 5d87259a-ab2d-48d5-945b-292fb57f137c
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MentalIllnessDerived
		dataType: int64
		formatString: 0%;-0%;0%
		lineageTag: 53b092d8-105e-45c7-a44d-cd6bc7ac88d1
		summarizeBy: sum
		sourceColumn: MentalIllnessDerived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LTCCountDerived
		dataType: int64
		formatString: 0
		lineageTag: 7135237c-c9a6-4eed-bd83-f26bfdf59483
		summarizeBy: sum
		sourceColumn: LTCCountDerived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SmokerDerived
		dataType: int64
		formatString: 0
		lineageTag: f60b2e2a-f87d-425b-9696-26262c220db4
		summarizeBy: sum
		sourceColumn: SmokerDerived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EthnicOriginDescription
		dataType: string
		lineageTag: 35661dd5-9fbb-42dc-87fb-24eb527b55c3
		summarizeBy: none
		sourceColumn: EthnicOriginDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Ethnicity_Flag
		dataType: string
		lineageTag: 6055f3f3-6f30-4d6d-b842-68a233e4a004
		summarizeBy: none
		sourceColumn: Ethnicity_Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IMDemployment_countydecile
		dataType: int64
		lineageTag: 5e0fcefa-8d3d-4296-9cce-6081420e4122
		summarizeBy: sum
		sourceColumn: IMDemployment_countydecile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Derived_Age
		dataType: int64
		formatString: 0
		lineageTag: be21601c-f768-4de1-8b41-41e5040a718f
		summarizeBy: sum
		sourceColumn: Derived_Age

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 60_Flag
		dataType: int64
		formatString: 0
		lineageTag: de68034c-013c-4f71-b032-66bd92367143
		summarizeBy: sum
		sourceColumn: 60_Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 80_Flag
		dataType: int64
		formatString: 0
		lineageTag: a8930038-f227-40f0-b5f9-a3f9775ead6b
		summarizeBy: sum
		sourceColumn: 80_Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 2d081dcc-3143-4160-a502-57d55dceb63c
		summarizeBy: none
		sourceColumn: Gender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CCG_Of_Registration
		dataType: string
		lineageTag: 0012c7df-2d5f-49a7-9b20-7228d756132e
		summarizeBy: none
		sourceColumn: CCG_Of_Registration

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COUNTER
		dataType: int64
		formatString: 0
		lineageTag: a49b1a78-5382-413e-83e0-eda5dc1ac1ea
		summarizeBy: sum
		sourceColumn: COUNTER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BME_Flag
		dataType: int64
		formatString: 0
		lineageTag: 62fb9073-1ce2-4821-9471-05a626ffbb29
		summarizeBy: sum
		sourceColumn: BME_Flag

		annotation SummarizationSetBy = Automatic

	column LSOACode
		dataType: string
		lineageTag: 31a68813-374a-4c45-ad2d-111245e4d618
		summarizeBy: none
		sourceColumn: LSOACode

		annotation SummarizationSetBy = Automatic

	partition REF_PLS_Current = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="SELECT DISTINCT  [Derived_Pseudo_NHS] = PLS.PseudoNHSNumber#(lf)      ,pls.[PracticeCode]#(lf)     #(lf)#(tab)  ,[IMDcountyDecile] = PLS.IMDCountyDecile#(lf)#(tab),[MentalIllnessDerived] = PLS.MentalIllness#(lf)#(tab)  ,PLS.[LTCCountDerived]#(lf)#(tab),[SmokerDerived] = PLS.Smoker#(lf)#(tab)  ,[EthnicOriginDescription] = e.DerivedEthnicityDescription#(lf)#(lf)#(tab)  ,CASE#(lf)  /* Normalise group first to be safe on case/whitespace */#(lf)  WHEN UPPER(e.DerivedEthnicityGroup) LIKE '%NOT KNOWN%' THEN 0#(lf)#(lf)  /* White categories (NHS standard) */#(lf)  WHEN e.DerivedEthnicityCode IN ('A','B','C') THEN 0#(lf)#(lf)  /* Gypsy/Roma/Irish Traveller are White in ONS/NHS classification */#(lf)  WHEN e.DerivedEthnicityCode = 'T'#(lf)       OR UPPER(e.DerivedEthnicityDescription) LIKE '%TRAVELLER%'#(lf)       OR UPPER(e.DerivedEthnicityDescription) LIKE '%GYPSY%'#(lf)       OR UPPER(e.DerivedEthnicityDescription) LIKE '%ROMA%'#(lf)  THEN 0#(lf)#(lf)  /* Not stated / Not known single-letter/2-digit NHS codes */#(lf)  WHEN e.DerivedEthnicityCode IN ('Z','99') THEN 0#(lf)#(lf)  /* Everything else is BME */#(lf)  ELSE 1#(lf)END AS BME_Flag#(lf)#(lf), [Ethnicity_Flag] = e.DerivedEthnicityGroup#(lf)#(lf)#(lf),[LSOACode] =  PLS.LSOACode#(lf)#(lf)#(tab) ,[IMDemployment_countydecile] = cast(l.Derived_EmploymentDeprivationDomainGloucestershireDecile as int)#(lf)#(tab)  ,[Derived_Age] = PLS.DerivedAge#(lf)#(tab)#(tab)#(lf)#(tab)  ,CASE WHEN cast([DerivedAge] AS int) >= 60 THEN 1#(lf)#(tab)#(tab)    WHEN cast([DerivedAge] AS int) < 60 THEN NULL#(lf)#(tab)#(tab)    ELSE 'ERROR'#(lf)#(tab)#(tab)    END AS '60_Flag'#(lf)#(lf)#(tab)  ,CASE WHEN cast([DerivedAge] as int) >= 80 THEN 1#(lf)#(tab)#(tab)    WHEN cast([DerivedAge] as int) <80 THEN NULL#(lf)#(tab)#(tab)    ELSE 'ERROR'#(lf)#(tab)#(tab)    END AS '80_Flag'#(lf)#(lf)      ,[Gender]#(lf)#(tab)  ,[CCG_Of_Registration] = PLS.ICBofRegistration#(lf)#(tab)   ,1 as COUNTER#(lf)#(lf)#(lf)#(lf)#(lf)#(tab)    FROM [PowerBI_Reporting].PLS.tbl02_Summary as PLS#(lf)#(lf)#(tab)#(tab)LEFT JOIN [PowerBI_Reporting].PLS.tbl01_Ethnicity as e on e.PseudoNHSNumber = PLS.PseudoNHSNumber#(lf)#(lf)#(tab)#(tab)left join  CCG_Reference.Reference.vw_LSOA_IMD as l on PLS.LSOACode = l.LSOACode#(lf)#(lf)#(tab)#(tab)WHERE pls.[ICBofRegistration] LIKE '%11M%'#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"IMDcountyDecile", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

