table 'Age Band Order'
	lineageTag: 12f35ae5-49e1-45c3-97f3-9645527eaef7

	column 'Age Band'
		dataType: string
		lineageTag: 2e4c157f-95b5-4c3f-a0c2-2a2d27dc1a6b
		summarizeBy: none
		sourceColumn: Age Band
		sortByColumn: Column1

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 85fa4bcd-cdb0-4af9-8278-9a9a973bb61c
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 'Age Band Order' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("HcfBEYAgDATAXvKVmzkkQFIL8rIG+5dkf7uWPB/ZXqUUMdlliRLqZzPXiR4buUGMWM9NYsY0Z4TFWs4Jj925Sl4nVfb+AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Age Band" = _t, Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Age Band", type text}, {"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

