table 'date_table (2)'
	lineageTag: 382f5947-e277-41d0-b1cf-5d79114ecf7f

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 089e1a0c-bac1-4e7e-b1bf-658233545359
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 3de7e05b-4597-4288-b801-c62ec0ecbbef
			defaultHierarchy: LocalDateTable_c69d1a78-7b0a-4b8f-a8a9-9446bce73db6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: bcf4186b-08b6-4655-af2e-7d5e62f433bd
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 7e7c3398-0c30-4c19-a19c-fb272525d4d1
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 24fc2758-0a5c-4b43-9408-ac6a7433b424
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: ff02ee74-80ea-448d-8848-87c4fec3308e
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: ad3746f9-a6f8-4052-a558-eb32c8b506c5
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 0f9e3430-9c8c-4412-9911-d5d7ea8be71f
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 69b13adf-1647-41bf-9398-3773dff7c38b
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: de1e77fb-f1d5-4d84-9957-f3e0eaa83532
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 43b1c97c-a673-49f6-ba97-2bba5fc518f6
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 874708e0-4e86-4890-a3a7-4f3144154412
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 25536c48-b574-4b22-9fa1-213f9e0c9cc1
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 9c96bfd8-c83d-4c9d-a81c-2c6e7cf592cd
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 1770f9e1-c35f-4612-9329-61702f4cb0ba
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: e47103b7-6ceb-4f97-b161-28e4822b097b
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	hierarchy 'financial_year Hierarchy'
		lineageTag: e6bda323-eca3-46db-8180-eaabd65bd96c

		level financial_year
			lineageTag: 061dcd65-c1ac-4100-a266-e3a3df920c01
			column: financial_year

		level month_name
			lineageTag: 4f5b6754-3d27-4757-8359-6256aa6a18f2
			column: month_name

	partition 'date_table (2)-f03082e7-eb76-4133-a2df-2d64a33f38ca' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="select [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      #(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] >= '20190401'#(lf)and [Date] <= EOMONTH(DATEADD(MONTH, -1, GETDATE()))"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}, {"is_holiday", Int64.Type}, {"is_weekend", Int64.Type}, {"month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

