table hospice_at_home
	lineageTag: f23f5dc6-8741-4a47-8609-b79037436129

	measure Referrals_accepted =
			
			CALCULATE(
				COUNTA('hospice_at_home'[Counter]),
				'hospice_at_home'[Referral_Accepted] IN { "Yes" }
			)
		formatString: #,0
		lineageTag: a55284de-9a65-48f7-811c-05d5876f9479

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "FilteredMeasure"
				}

	measure Referrals = sum([Counter])
		formatString: #,0
		lineageTag: bca61a9d-72e7-4e6f-97bf-49fe0956e8ac

	measure counter_small_number_suppression = if(and(count(hospice_at_home[Counter])<5,count(hospice_at_home[Counter])>0),"<5",count(hospice_at_home[Counter]))
		formatString: 0
		lineageTag: 21b35212-b5c5-4bcb-903e-af6c117f8149

	measure practice_%_of_total =
			DIVIDE(
			                            CALCULATE(
			                                COUNT(hospice_at_home[Practice])
			                            ),
			                            CALCULATE(
			                                COUNT(hospice_at_home[Practice]),
			                                ALL(hospice_at_home)
			                                )
			                            )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d52fc973-332f-49e7-bf7c-37ab3ded349f

		changedProperty = FormatString

	measure %_of_total = ```
			
			        divide(
			            sum(hospice_at_home[Counter]),
			                calculate(
			                    sum(hospice_at_home[Counter]),
			                    allselected(hospice_at_home)
			                    ))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 839e0d9d-34be-4f40-807f-e9d7a8de4216

		changedProperty = FormatString

	measure %_accepted =
			
			DIVIDE(
			    CALCULATE(
				COUNTA('hospice_at_home'[Counter]),	'hospice_at_home'[Referral_Accepted] IN { "Yes" }),
			    CALCULATE(COUNTA('hospice_at_home'[Counter]),ALL('hospice_at_home'[Referral_Accepted]))
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 984333ad-662e-4fdd-8c2d-f5ebf1a0779c

	measure nhs_no_completion = ```
			
			        divide(
			            sum(hospice_at_home[nhs_no_flag]),
			                calculate(
			                    sum(hospice_at_home[Counter]),
			                    allselected(hospice_at_home)
			                    ))
			```
		formatString: 0%;-0%;0%
		lineageTag: 94521b07-e71d-41ae-8a96-256dfbccecd6

	measure %_cancer =
			
			DIVIDE(
			    CALCULATE(
				COUNTA('hospice_at_home'[Counter]),	'hospice_at_home'[Primary_Diagnosis] IN { "Cancer" }),
			    CALCULATE(COUNTA('hospice_at_home'[Counter]),ALL('hospice_at_home'[Primary_Diagnosis]))
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c3df058d-7a7f-4732-aa64-b1292c3469f6

	measure 'Average H@H Ref 2' =
			
			CALCULATE((AVERAGEX(
				KEEPFILTERS(VALUES('date_table'[day_month_year])),
				CALCULATE(sum(hospice_at_home[Counter])) +0
			)  ))
		lineageTag: 835b44a2-78dd-4efc-a451-73be0c30ed78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Measure = CALCULATE(SUM('hospice_at_home'[Counter]))
		formatString: 0
		lineageTag: ed7613ba-b315-46e0-9e78-d954c1862108

	measure 'H@H Referrals Rate per 1000 - By Month' =
			
			
			VAR HAHRef = CALCULATE ( SUM ('hospice_at_home'[Counter]) )
			VAR POP = CALCULATE ( SUM ( 'Population'[population] ) )
			
			RETURN (HAHREF/POP*1000)
		lineageTag: ca7bc70f-e442-4c6f-be1c-0715b6e91628

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'H@H Referrals - By Year' =
			
			
			VAR HAHREF = CALCULATE ( SUM ('hospice_at_home'[Counter] ) , ALLEXCEPT( 'date_table', 'date_table'[financial_year] )  )
			VAR POP = CALCULATE ( SUM ( Population[population] ) , ALLEXCEPT ('date_table', 'date_table'[financial_year] ), 'date_table'[month_name] IN {"Apr"} )
			
			RETURN (HAHREF/POP*1000)
		lineageTag: fa23b422-ff43-48fb-b37d-950406d53e00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Provider
		dataType: string
		lineageTag: e0613d71-9bdf-4fb9-882e-0caa32896fde
		summarizeBy: none
		sourceColumn: Provider

		annotation SummarizationSetBy = Automatic

	column Local_Patient_Identifier
		dataType: string
		lineageTag: 771f2da3-aff5-4fc3-8595-8ddb0b1b5c2c
		summarizeBy: none
		sourceColumn: Local_Patient_Identifier

		annotation SummarizationSetBy = Automatic

	column NHS_Number
		dataType: string
		lineageTag: c10f9adc-f226-4f28-8d02-679301fe9fc1
		summarizeBy: none
		sourceColumn: NHS_Number

		annotation SummarizationSetBy = Automatic

	column Referral_Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b306c121-8594-4937-9699-956826ea3e2e
		summarizeBy: none
		sourceColumn: Referral_Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Referral_Date_YearMonth
		dataType: string
		lineageTag: a38975b3-9865-4bee-b945-dd8655048071
		summarizeBy: none
		sourceColumn: Referral_Date_YearMonth

		annotation SummarizationSetBy = Automatic

	column Referral_Date_FinancialYear
		dataType: string
		lineageTag: 92a11aa8-7ca2-4c00-88dc-36ceff61cdfb
		summarizeBy: none
		sourceColumn: Referral_Date_FinancialYear

		annotation SummarizationSetBy = Automatic

	column Registration_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6e419107-73e7-4788-af26-fa9478f930f7
		summarizeBy: none
		sourceColumn: Registration_Date

		variation Variation
			isDefault
			relationship: 5667b112-d578-4acc-bc1e-84f0b6ba742b
			defaultHierarchy: LocalDateTable_eb26c3c1-b254-402b-abbe-9af7f1c7365c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Discharge_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: a2305d13-3244-439c-9a70-bae73cc4d240
		summarizeBy: none
		sourceColumn: Discharge_Date

		variation Variation
			isDefault
			relationship: 365a0893-6bbe-45c7-8015-4199f4c3684a
			defaultHierarchy: LocalDateTable_e477fb39-9a9d-4a9d-9367-ff96cc9c50d4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Source_of_Referral
		dataType: string
		lineageTag: a19c92b8-01ca-4028-b669-49273ccb6cbe
		summarizeBy: none
		sourceColumn: Source_of_Referral

		annotation SummarizationSetBy = Automatic

	column Referral_Accepted
		dataType: string
		lineageTag: 0687280d-254c-4e49-b564-e05d0bc08c3a
		summarizeBy: none
		sourceColumn: Referral_Accepted

		annotation SummarizationSetBy = Automatic

	column Reason_for_not_accepting
		dataType: string
		lineageTag: cf1ec644-299f-4219-bb03-8d7384ccd1bb
		summarizeBy: none
		sourceColumn: Reason_for_not_accepting

		annotation SummarizationSetBy = Automatic

	column Referral_accepted_–_funding_in_place
		dataType: string
		lineageTag: 83a6c807-3ada-416e-b80c-ffcbe9bf2158
		summarizeBy: none
		sourceColumn: Referral_accepted_–_funding_in_place

		annotation SummarizationSetBy = Automatic

	column Responded_to_referral_within_4_hours
		dataType: string
		lineageTag: 9fc88925-0f4d-46ff-8318-8c6b7ed19323
		summarizeBy: none
		sourceColumn: Responded_to_referral_within_4_hours

		annotation SummarizationSetBy = Automatic

	column GP_Practice
		dataType: string
		lineageTag: cf5347b8-9d4d-4503-ba60-26d1e1b61895
		summarizeBy: none
		sourceColumn: GP_Practice

		annotation SummarizationSetBy = Automatic

	column Practice
		dataType: string
		lineageTag: 119e5e5f-ba3d-4481-b37d-3af8069bb37d
		summarizeBy: none
		sourceColumn: Practice

		annotation SummarizationSetBy = Automatic

	column 'Practice Code'
		dataType: string
		lineageTag: 5e55a0bf-b9f1-430e-aea6-5f26f4f43a28
		summarizeBy: none
		sourceColumn: Practice Code

		annotation SummarizationSetBy = Automatic

	column Age_at_referral
		dataType: string
		lineageTag: 8307dff5-248f-41f2-927c-1b4330558a5a
		summarizeBy: none
		sourceColumn: Age_at_referral

		annotation SummarizationSetBy = Automatic

	column 'Age band'
		dataType: string
		lineageTag: 2e05c8a0-4b02-4956-ba8e-3425e8dfc842
		summarizeBy: none
		sourceColumn: Age band
		sortByColumn: age_band_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: ba2c2247-fa58-46f7-8d2d-d4eb17683e5a
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column 'Ethnicity Indicator'
		dataType: int64
		formatString: 0
		lineageTag: 0a3a69db-bd1d-4567-958a-0ec1a8ddd610
		summarizeBy: sum
		sourceColumn: Ethnicity Indicator

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: dbf96448-10e3-477a-9e4d-63fa926a7d5b
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Religious/personal_belief
		dataType: string
		lineageTag: 7981799a-1121-402c-b4f6-1132e8c4985a
		summarizeBy: none
		sourceColumn: Religious/personal_belief

		annotation SummarizationSetBy = Automatic

	column Primary_Diagnosis
		dataType: string
		lineageTag: 6031cd1f-30a0-4710-85a7-6e489ab96293
		summarizeBy: none
		sourceColumn: Primary_Diagnosis

		annotation SummarizationSetBy = Automatic

	column Patient_died
		dataType: string
		lineageTag: 2ff95d4c-3da9-46da-99ac-f45b0f256a91
		summarizeBy: none
		sourceColumn: Patient_died

		annotation SummarizationSetBy = Automatic

	column Death_in_preferred_place_of_care
		dataType: string
		lineageTag: e9fa9ab7-07c5-4aa3-b076-fa4e8a4e9da8
		summarizeBy: none
		sourceColumn: Death_in_preferred_place_of_care

		annotation SummarizationSetBy = Automatic

	column Location_of_discharge
		dataType: string
		lineageTag: e9a9735c-7b4a-437d-9be1-6640528af040
		summarizeBy: none
		sourceColumn: Location_of_discharge

		annotation SummarizationSetBy = Automatic

	column FileName
		dataType: string
		lineageTag: 56e4f05f-e59d-485d-b4e6-64b347be154d
		summarizeBy: none
		sourceColumn: FileName

		annotation SummarizationSetBy = Automatic

	column ProcessedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 1e66ea6c-3e7d-4878-a917-0debf193e2a0
		summarizeBy: none
		sourceColumn: ProcessedDate

		variation Variation
			isDefault
			relationship: 59ca3b6a-df70-4270-af89-7173980aaee4
			defaultHierarchy: LocalDateTable_b19e6413-6cf6-4dba-8dc1-30f3902a6cb9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: e44595f5-1c8a-4f3e-8602-7d02109d65f4
		summarizeBy: sum
		sourceColumn: Counter

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column age_band_order
		dataType: string
		lineageTag: 4e8f2b32-3b8c-4c8a-bac5-67775aef05e4
		summarizeBy: none
		sourceColumn: age_band_order

		annotation SummarizationSetBy = Automatic

	column patient_id
		dataType: string
		lineageTag: c10b7403-3147-44e2-af97-fc11368f5de8
		summarizeBy: none
		sourceColumn: patient_id

		annotation SummarizationSetBy = Automatic

	column LTCCountDerived
		dataType: int64
		formatString: 0
		lineageTag: 318f1de2-770b-4bef-866e-1876a72adb27
		summarizeBy: sum
		sourceColumn: LTCCountDerived

		annotation SummarizationSetBy = Automatic

	column ObesityDerived
		dataType: int64
		formatString: 0
		lineageTag: f122ce0b-7449-4a0e-88f2-8de8d465d7fe
		summarizeBy: sum
		sourceColumn: ObesityDerived

		annotation SummarizationSetBy = Automatic

	column SmokerDerived
		dataType: int64
		formatString: 0
		lineageTag: 40eff77e-20a6-45df-a175-2157c4530028
		summarizeBy: sum
		sourceColumn: SmokerDerived

		annotation SummarizationSetBy = Automatic

	column AsthmaDerived
		dataType: int64
		formatString: 0
		lineageTag: 8b2454b2-6c10-4ddd-b4c7-e0948a24ce96
		summarizeBy: sum
		sourceColumn: AsthmaDerived

		annotation SummarizationSetBy = Automatic

	column COPDDerived
		dataType: int64
		formatString: 0
		lineageTag: 83d05338-7e07-400c-af63-040fb48b40f7
		summarizeBy: sum
		sourceColumn: COPDDerived

		annotation SummarizationSetBy = Automatic

	column DementiaDerived
		dataType: int64
		formatString: 0
		lineageTag: 2f3cdc66-d57b-41ac-a9ad-39d655af9229
		summarizeBy: sum
		sourceColumn: DementiaDerived

		annotation SummarizationSetBy = Automatic

	column DepressionDerived
		dataType: int64
		formatString: 0
		lineageTag: 0279adfb-866e-45fb-881b-88e4b5644087
		summarizeBy: sum
		sourceColumn: DepressionDerived

		annotation SummarizationSetBy = Automatic

	column DiabetesDerived
		dataType: int64
		formatString: 0
		lineageTag: 2b925899-4335-45e0-a7da-c4c162182fc5
		summarizeBy: sum
		sourceColumn: DiabetesDerived

		annotation SummarizationSetBy = Automatic

	column PalliativeCareDerived
		dataType: int64
		formatString: 0
		lineageTag: 98408351-5666-4c56-89c5-f55b4df25343
		summarizeBy: sum
		sourceColumn: PalliativeCareDerived

		annotation SummarizationSetBy = Automatic

	column ChronicKidneyDiseaseDerived
		dataType: int64
		formatString: 0
		lineageTag: caa1d67c-f805-471a-b266-2cc002e84a7b
		summarizeBy: sum
		sourceColumn: ChronicKidneyDiseaseDerived

		annotation SummarizationSetBy = Automatic

	column EpilepsyDerived
		dataType: int64
		formatString: 0
		lineageTag: b2427a93-d90e-46b7-b0b8-65696519c5ac
		summarizeBy: sum
		sourceColumn: EpilepsyDerived

		annotation SummarizationSetBy = Automatic

	column HeartFailureDerived
		dataType: int64
		formatString: 0
		lineageTag: a5936477-8bfd-4415-95aa-857630bb2e8a
		summarizeBy: sum
		sourceColumn: HeartFailureDerived

		annotation SummarizationSetBy = Automatic

	column StrokeDerived
		dataType: int64
		formatString: 0
		lineageTag: f668fb50-20e1-4cb9-9774-70e5fc9680e6
		summarizeBy: sum
		sourceColumn: StrokeDerived

		annotation SummarizationSetBy = Automatic

	column AtrialFibrillationDerived
		dataType: int64
		formatString: 0
		lineageTag: 0e77e231-23fc-42b9-9c0d-db622b27859b
		summarizeBy: sum
		sourceColumn: AtrialFibrillationDerived

		annotation SummarizationSetBy = Automatic

	column CancerDerived
		dataType: int64
		formatString: 0
		lineageTag: f154fbf9-72ee-4078-97aa-48cb666de898
		summarizeBy: sum
		sourceColumn: CancerDerived

		annotation SummarizationSetBy = Automatic

	column CoronaryHeartDiseaseDerived
		dataType: int64
		formatString: 0
		lineageTag: f42de5b1-0ec2-4bf8-847d-6e14045d56e0
		summarizeBy: sum
		sourceColumn: CoronaryHeartDiseaseDerived

		annotation SummarizationSetBy = Automatic

	column HypertensionDerived
		dataType: int64
		formatString: 0
		lineageTag: 951e4ab7-b578-4cbe-847a-840e1954eaca
		summarizeBy: sum
		sourceColumn: HypertensionDerived

		annotation SummarizationSetBy = Automatic

	column HypothyroidismDerived
		dataType: int64
		formatString: 0
		lineageTag: 602b701a-a7f3-4d8b-943e-d8cd832c60a5
		summarizeBy: sum
		sourceColumn: HypothyroidismDerived

		annotation SummarizationSetBy = Automatic

	column LearningDisabilityDerived
		dataType: int64
		formatString: 0
		lineageTag: a92ba8f2-dcf0-46b0-b759-8ff8347fde5d
		summarizeBy: sum
		sourceColumn: LearningDisabilityDerived

		annotation SummarizationSetBy = Automatic

	column MentalIllnessDerived
		dataType: int64
		formatString: 0
		lineageTag: bfd3b285-f30b-4477-b95a-6863782ead08
		summarizeBy: sum
		sourceColumn: MentalIllnessDerived

		annotation SummarizationSetBy = Automatic

	column eFI_Catgory_derived
		dataType: string
		lineageTag: f8e4d0a2-9215-4225-ab9b-4a6d8f64b42f
		summarizeBy: none
		sourceColumn: eFI_Catgory_derived

		annotation SummarizationSetBy = Automatic

	column nhs_no_flag
		dataType: int64
		formatString: 0
		lineageTag: 88778c2c-8cc9-4027-9b5a-57c643354fff
		summarizeBy: sum
		sourceColumn: nhs_no_flag

		annotation SummarizationSetBy = Automatic

	column data_up_to
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 2400db9c-9877-432d-99b9-a1709420e28f
		summarizeBy: none
		sourceColumn: data_up_to

		variation Variation
			isDefault
			relationship: c3de506d-487a-4a2a-b733-5f2aa3ad8427
			defaultHierarchy: LocalDateTable_a6225891-636e-4317-88d7-2da28c333cea.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column date_refreshed
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: c856ae6e-499a-4e90-b3b7-6750bc2e025f
		summarizeBy: none
		sourceColumn: date_refreshed

		variation Variation
			isDefault
			relationship: 7ed818e5-df01-4870-a20b-500a6df65837
			defaultHierarchy: LocalDateTable_4fa54ca4-775d-47b0-83ad-05ea08035f78.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column DateOfDeath
		dataType: dateTime
		formatString: General Date
		lineageTag: 5a670f33-9c44-4be0-b68b-f46ff070c40a
		summarizeBy: none
		sourceColumn: DateOfDeath

		variation Variation
			isDefault
			relationship: 37aabfb5-8c28-462a-8a3c-a43ad9cc722c
			defaultHierarchy: LocalDateTable_a169ff9d-0201-49a1-b2df-5e80c7085d65.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column days_of_care
		dataType: int64
		formatString: 0
		lineageTag: db83d769-c03c-4940-8a5e-956e8d445c7d
		summarizeBy: sum
		sourceColumn: days_of_care

		annotation SummarizationSetBy = Automatic

	column days_of_care_flag
		dataType: string
		lineageTag: 0ab6b094-02a0-4133-99a8-236cb448414f
		summarizeBy: none
		sourceColumn: days_of_care_flag

		annotation SummarizationSetBy = Automatic

	column up_to_financial_quarter
		dataType: dateTime
		formatString: General Date
		lineageTag: 4f5652ab-a669-4c63-9b4f-358bfb9ea9ac
		summarizeBy: none
		sourceColumn: up_to_financial_quarter

		variation Variation
			isDefault
			relationship: 9cab3d00-3d0b-44aa-9191-ec3ed69604a7
			defaultHierarchy: LocalDateTable_7599fb8c-7dd7-4e57-b8d1-d7e5f1b3cf14.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Financial_quarter_flag
		dataType: string
		lineageTag: 198bff91-022e-4867-9afa-25b45fc1b7de
		summarizeBy: none
		sourceColumn: Financial_quarter_flag

		annotation SummarizationSetBy = Automatic

	partition hospice_at_home-e187f935-e874-4ade-bbe4-ec8c324ac58f = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_current", [Query="/****** Script for SelectTopNRows command from SSMS  ******/#(lf)#(lf)SET NOCOUNT ON#(lf)IF OBJECT_ID ('TEMPDB..#max_date') IS NOT NULL DROP TABLE #max_date#(lf)#(lf)#(lf)select #(lf)#(lf)[max_date] = max(referral_date)#(lf),[data_up_to] = EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)into #max_date#(lf)#(lf)from [CCG_Current].[Hospices].[vw_HospiceAtHome_Monthly]#(lf)#(lf)SET NOCOUNT ON#(lf)IF OBJECT_ID ('TEMPDB..#table_1') IS NOT NULL DROP TABLE #table_1#(lf)#(lf)#(lf)#(lf)SELECT DISTINCT [Provider]#(lf)      ,[Local_Patient_Identifier]#(lf)      ,[NHS_Number]#(lf)      ,[Referral_Date] = CAST([Referral_Date] AS date)#(lf)#(tab)  ,[Referral_Date_YearMonth] = [D].[YearMonth]#(lf)#(tab)  ,[Referral_Date_FinancialYear] = [D].[FinancialYear]#(lf)      ,[Registration_Date] = CASE WHEN [Registration_Date] < '2019-01-01' THEN NULL ELSE CAST([Registration_Date] AS date) END#(lf)      ,[Discharge_Date] = CASE WHEN [Discharge_Date] < '2019-01-01' THEN NULL ELSE CAST([Discharge_Date] AS date) END#(lf)#(tab)  ,[PDS].[DateOfDeath]#(lf)#(tab)  ,[days_of_care] = case when ([Referral_Accepted] = 'yes' and [Referral_Date] is not null and [Discharge_Date] is not null and [Discharge_Date]>=[Referral_Date]) then DATEDIFF(dd,[Referral_date],[discharge_date])#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) when ([Referral_Accepted] = 'yes' and [Referral_Date] is not null and [Discharge_Date] < '2018-01-01' and [DateOfDeath] is not null and [DateOfDeath]>=[Referral_Date]) then DATEDIFF(dd,[Referral_date],[DateOfDeath])#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) else null end#(lf)      ,[Source_of_Referral] = CASE WHEN [Source_of_Referral] = 'General Medical Practitioner' THEN 'GP'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN [Source_of_Referral] = 'General Medical Practicioner' THEN 'GP'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE [Source_of_Referral] END#(lf)      ,[Referral_Accepted]#(lf)      ,[Reason_for_not_accepting] = CASE WHEN [Reason_for_not_accepting] = ' ' THEN NULL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)     WHEN [Reason_for_not_accepting] = 'N/A' THEN NULL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) ELSE [Reason_for_not_accepting] END#(lf)      ,[Referral_accepted_–_funding_in_place]#(lf)      ,[Responded_to_referral_within_4_hours]#(lf)      ,[GP_Practice]#(lf)#(tab)  --,[Practice] = SUBSTRING([GP_Practice],0,charindex('-',[GP_Practice],0))#(lf)#(tab)  ,[Practice] = LEFT([GP_Practice],CHARINDEX('-',[GP_Practice])-1)#(lf)#(tab)  ,[Practice Code] = RIGHT([GP_Practice],CHARINDEX('-',(REVERSE([GP_Practice])))-2)#(lf)      ,[Age_at_referral]#(lf)#(tab)  ,[Age band] = CASE WHEN CAST([Age_at_referral] AS int) between '1' and '39' THEN '<40'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN CAST([Age_at_referral] AS int) between '40' and '49' THEN '40-49'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN CAST([Age_at_referral] AS int) between '50' and '59' THEN '50-59'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN CAST([Age_at_referral] AS int) between '60' and '69' THEN '60-69'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN CAST([Age_at_referral] AS int) between '70' and '79' THEN '70-79'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN CAST([Age_at_referral] AS int) between '80' and '89' THEN '80-89'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN CAST([Age_at_referral] AS int) between '90' and '99' THEN '90-99'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN CAST([Age_at_referral] AS int) between '100' and '150' THEN '100+' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) ELSE 'Unknown' END#(lf)      ,[Ethnicity]#(lf)#(tab)  ,[Ethnicity Indicator] = CASE WHEN [Ethnicity] = 'Unknown' THEN 0 ELSE 1 END#(lf)      ,[H].[Gender]#(lf)      ,[Religious/personal_belief]#(lf)      ,[Primary_Diagnosis]#(lf)      ,[Patient_died]#(lf)      ,[Death_in_preferred_place_of_care]#(lf)      ,[Location_of_discharge]#(lf)      ,[FileName]#(lf)      ,[ProcessedDate]#(lf)#(tab)  ,[M].[LTCCountDerived]#(lf)#(tab)  ,[ObesityDerived]#(lf)      ,[SmokerDerived]#(lf)      ,[AsthmaDerived]#(lf)      ,[COPDDerived]#(lf)      ,[DementiaDerived]#(lf)      ,[DepressionDerived]#(lf)      ,[DiabetesDerived]#(lf)      ,[PalliativeCareDerived]#(lf)      ,[ChronicKidneyDiseaseDerived]#(lf)      ,[EpilepsyDerived]#(lf)      ,[HeartFailureDerived]#(lf)      ,[StrokeDerived]#(lf)      ,[AtrialFibrillationDerived]#(lf)      ,[CancerDerived]#(lf)      ,[CoronaryHeartDiseaseDerived]#(lf)      ,[HypertensionDerived]#(lf)      ,[HypothyroidismDerived]#(lf)      ,[LearningDisabilityDerived]#(lf)      ,[MentalIllnessDerived]#(lf)#(tab)  ,[eFI_Catgory_derived]#(lf)#(tab)  ,[data_up_to] = EOMONTH(DATEADD(quarter, -1, getdate()))#(lf)#(tab)  ,[date_refreshed] = getdate()#(lf)#(lf)#(lf)#(tab)  ,[up_to_financial_quarter] = case when datepart(month,max_date) like 1 then EOMONTH(DATEADD(month, -1, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 2 then EOMONTH(DATEADD(month, -2, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 3 then EOMONTH(DATEADD(month, -0, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 4 then EOMONTH(DATEADD(month, -1, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 5 then EOMONTH(DATEADD(month, -2, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 6 then EOMONTH(DATEADD(month, -0, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 7 then EOMONTH(DATEADD(month, -1, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 8 then EOMONTH(DATEADD(month, -2, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 9 then EOMONTH(DATEADD(month, -0, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 10 then EOMONTH(DATEADD(month, -1, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 11 then EOMONTH(DATEADD(month, -2, [max].max_date))#(lf)#(tab)#(tab)#(tab)when datepart(month,max_date) like 12 then EOMONTH(DATEADD(month, -0, [max].max_date))#(lf)#(tab)#(tab)#(tab)END #(lf)#(tab)  #(lf)#(tab)INTO #table_1#(lf)#(lf)  FROM [CCG_Current].[Hospices].[vw_HospiceAtHome_Monthly][H]#(lf)#(lf)  LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup][D]#(lf)  ON [H].[Referral_Date] = [D].[Date]#(lf)  #(lf)  left join [BIReports].[MPI].[MPI_current][M]#(lf)  on [H].[NHS_Number] = [M].[Derived_Pseudo_NHS]#(lf)#(lf)  left join [CCG_Reference].[Population].[vw_PDS_Deaths][PDS]#(lf)  on [H].[NHS_Number] = [PDS].[Derived_NHS_Number]#(lf)#(lf)  LEFT JOIN #max_date [max] on [max].[data_up_to] = EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(lf)  where [Referral_Date] >= '2021-04-01'#(lf)and [Referral_Date] <= EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(lf)order by Referral_Date desc#(lf)#(lf)#(lf)#(lf)SELECT *#(lf),[Financial_quarter_flag] = case when Referral_Date > up_to_financial_quarter then '0' else '1' END#(lf)#(lf)FROM #table_1#(lf)#(lf)order by Referral_Date desc#(lf)"]),
				    #"Added Counter column" = Table.AddColumn(Source, "Counter", each 1),
				    #"Added age_band_order column" = Table.AddColumn(#"Added Counter column", "age_band_order", each if [Age band] = "<40" then 1 else if [Age band] = "40-49" then 2 else if [Age band] = "50-59" then 3 else if [Age band] = "60-69" then 4 else if [Age band] = "70-79" then 5 else if [Age band] = "80-89" then 6 else if [Age band] = "90-99" then 7 else if [Age band] = "100+" then 8 else null),
				    #"Added patient_id column" = Table.AddColumn(#"Added age_band_order column", "patient_id", each if [NHS_Number] = "" then [Local_Patient_Identifier] else [NHS_Number]),
				    #"Added nhs_no_flag" = Table.AddColumn(#"Added patient_id column", "nhs_no_flag", each if [NHS_Number] <> "" then 1 else 0),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added nhs_no_flag",{{"nhs_no_flag", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "days_of_care_flag", each if [days_of_care] >= 0 then 1 else 0),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Added Conditional Column", {{"days_of_care_flag", 0}})
				in
				    #"Replaced Errors"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

