table Benchmarking
	lineageTag: 1c80dabe-8245-4262-97ab-04dc195cfc78

	measure 'South West Benchmarking 0-18 Weeks' = ```
			CALCULATE(SUM(Benchmarking[0-18 Weeks]), Benchmarking[Benchmarking_SouthWest] <> "") 
			```
		formatString: #,0
		lineageTag: 2802416f-4dcd-46ec-a11c-a8a96ea0d616

		changedProperty = IsHidden

	measure '0-18 Weeks %' = DIVIDE(SUM(Benchmarking[0-18 Weeks]),SUM(Benchmarking[Total_All]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1621625a-b4b8-45b4-b8e8-52518ea083b8

		changedProperty = IsHidden

	measure Gloucestershire = CALCULATE(SUM(Benchmarking[0-18 Weeks])/SUM(Benchmarking[Total_All]), filter(Benchmarking, Benchmarking[Benchmarking_Organisation_Name] = "Gloucestershire ICB"))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4876df9c-c910-4add-a11f-2bf54a0b855e

		changedProperty = IsHidden

	measure 'South West' = CALCULATE(SUM(Benchmarking[0-18 Weeks])/SUM(Benchmarking[Total_All]), filter(Benchmarking, Benchmarking[Benchmarking_SouthWest] <> ""))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 650b24f3-885b-442c-84ea-2b3f3ea9b647

		changedProperty = IsHidden

	measure 'South west Provider title' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "South West Provider Overview - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: d0d7fece-c49e-477d-80e2-b60fdbf4af8a

		changedProperty = IsHidden

	measure 'Peer Benchmarking Provider title' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "Gloucestershire ICB Peers' Provider Overview - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: 51f7ab31-1c77-47e1-b4c4-9a198fcc9265

		changedProperty = IsHidden

	measure 'Gloucestershire 0-18 Weeks' = CALCULATE(sum(Benchmarking[0-18 Weeks]), filter(Benchmarking, Benchmarking[Benchmarking_Organisation_Name] = "Gloucestershire ICB"))
		formatString: #,0
		lineageTag: 6d80af5f-fc10-4df2-b42b-d3efb2d5767f

		changedProperty = IsHidden

	measure '<18 Weeks total performance title' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "0-18 Weeks (%) Performance Benchmarking  - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: fd339353-3aa1-49e8-8042-fce5ff88a9c0

		changedProperty = IsHidden

	measure '<18 Weeks total performance south west title' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "0-18 Weeks (%) Performance Benchmarking by South West ICB Region  - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: e87a3790-cee4-40df-bfe2-a9b07dfa1f1a

		changedProperty = IsHidden

	measure '<18 Weeks total title south west' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "0-18 Weeks Benchmarking by South West ICB Region - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: 36425d95-7814-4ff0-af9d-ef38e0bc3a96

		changedProperty = IsHidden

	measure '<18 Weeks total title England' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "0-18 Weeks - England - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: ec81dbac-3f75-4560-a2db-da24e4eca444

		changedProperty = IsHidden

	measure '0-18 Weeks total title south west' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "0-18 Weeks - South West - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: 47df5ab7-0ece-4407-a318-5419f9eb6b01

		changedProperty = IsHidden

	measure '0-18 Weeks total title gloucestershire' =
			
			Var TreatmentFunctionName = SELECTEDVALUE('Benchmarking'[Treatment Function Name])
			Var finalResult= "0-18 Weeks - Gloucestershire ICB - " & (TreatmentFunctionName) & ""
			Return finalResult
		lineageTag: 9d7593f2-4209-4df9-a524-b08842b402c8

		changedProperty = IsHidden

	measure '0-18 Weeks title' = ```
			SELECTEDVALUE(Benchmarking[RTT_Part_Description]) & ": 0-18 Weeks & > 18 Weeks" 
			```
		lineageTag: 009d3d33-acd7-4ac8-9e49-160930ec2452

		changedProperty = IsHidden

	measure '>35 Weeks title' = ```
			SELECTEDVALUE(Benchmarking[RTT_Part_Description]) & ": > 35 Weeks" 
			```
		lineageTag: a9208b40-f42a-490b-abc8-bdce82fbab98

		changedProperty = IsHidden

	measure '>52 Weeks title' = ```
			SELECTEDVALUE(Benchmarking[RTT_Part_Description]) & ": > 52 Weeks" 
			```
		lineageTag: c276a802-5021-441e-be55-c14c41480601

		changedProperty = IsHidden

	measure '>78 Weeks title' = ```
			SELECTEDVALUE(Benchmarking[RTT_Part_Description]) & ": > 78 Weeks" 
			```
		lineageTag: dcc8ae8c-1185-40db-98bf-1a5d7eebee98

		changedProperty = IsHidden

	measure '>104 Weeks title' = ```
			SELECTEDVALUE(Benchmarking[RTT_Part_Description]) & ": > 104 Weeks" 
			```
		lineageTag: 264b5d60-b329-40ac-83a8-f1224d5867f0

		changedProperty = IsHidden

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 0a59088c-9e92-4aee-a7aa-270aab2c5eda
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Financial_Year
		dataType: string
		lineageTag: 7a9846ad-d2b0-4080-921a-98e2c79804c6
		summarizeBy: none
		sourceColumn: Financial_Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 303e9aba-6e12-4bd7-95c8-c3b7bc0da9f5
		summarizeBy: none
		sourceColumn: FinancialYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: fd10613f-f1a3-483d-bd08-62ef64699384
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Sort Financial Year'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 78a80559-3b09-49b3-9ee4-60475c178ad2
		summarizeBy: none
		sourceColumn: MonthName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Provider_Parent_Organisation_Code
		dataType: string
		lineageTag: 1d90f13f-b692-4c0e-a8ad-795fbd091a69
		summarizeBy: none
		sourceColumn: Provider_Parent_Organisation_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Provider_Parent_Organisation_Name
		dataType: string
		lineageTag: 010ddd93-e70c-414c-8c01-edff300b0641
		summarizeBy: none
		sourceColumn: Provider_Parent_Organisation_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Benchmarking_England
		dataType: string
		lineageTag: f3606f12-2c45-4bc4-bdb6-fc9afa074165
		summarizeBy: none
		sourceColumn: Benchmarking_England

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Benchmarking_SouthWest
		dataType: string
		lineageTag: e9576c59-409e-487e-af20-99e32b36b2f4
		summarizeBy: none
		sourceColumn: Benchmarking_SouthWest

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Benchmarking_Organisation_Name
		dataType: string
		lineageTag: e5e249d1-3b17-4b4f-8c27-ebd45d9050f0
		summarizeBy: none
		sourceColumn: Benchmarking_Organisation_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Provider_Organisation_Code
		dataType: string
		lineageTag: 41c20c02-5f25-457b-b330-d7b0a34f288c
		summarizeBy: none
		sourceColumn: Provider_Organisation_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Provider
		dataType: string
		lineageTag: 75e3c309-669c-4303-9338-994ec75d1c87
		summarizeBy: none
		sourceColumn: Provider

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Organisation_Code
		dataType: string
		lineageTag: 61637f4b-d96a-4432-ba5a-fdb71c39f350
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Organisation_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Organisation_Name
		dataType: string
		lineageTag: 358702b9-6df1-4286-be6b-e776d682811d
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Organisation_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Organisation_Code
		dataType: string
		lineageTag: 0e814e16-d543-422b-82b3-e156e6e951fd
		summarizeBy: none
		sourceColumn: Commissioner_Organisation_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Organisation_Name
		dataType: string
		lineageTag: 6ae364fa-0d84-4588-90fd-31c139307a75
		summarizeBy: none
		sourceColumn: Commissioner_Organisation_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Name
		dataType: string
		lineageTag: 69bd696d-b017-4f16-85f5-9f4453554673
		summarizeBy: none
		sourceColumn: RTT_Part_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Description
		dataType: string
		lineageTag: b1aa3915-923c-49d1-a4a8-9e50f8108a72
		summarizeBy: none
		sourceColumn: RTT_Part_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Treatment_Function_Code
		dataType: string
		lineageTag: 71c1810e-2e30-45df-b189-929239ffc826
		summarizeBy: none
		sourceColumn: Treatment_Function_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Name'
		dataType: string
		lineageTag: cdcd9658-1a40-4090-9ac8-3767cab5bfa8
		summarizeBy: none
		sourceColumn: Treatment Function Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Total_All
		dataType: int64
		formatString: 0
		lineageTag: 8be02caf-96f0-4f7a-be59-1c4784c7185e
		summarizeBy: sum
		sourceColumn: Total_All

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '0-18 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: b916b08d-a563-4169-b7ec-6532f9869237
		summarizeBy: sum
		sourceColumn: 0-18 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column '> 18 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 4f4a1fc0-7b87-4815-807c-3f977bf118d9
		summarizeBy: sum
		sourceColumn: > 18 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 35 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 3a4617c1-450b-486c-bddb-799cdee6b604
		summarizeBy: sum
		sourceColumn: > 35 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '< 52 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: d1dc6303-d21f-43b7-9c01-2f7464503e02
		summarizeBy: sum
		sourceColumn: < 52 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 52 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 03163fd5-6a9e-48e4-9aca-cc5477dd4ab4
		summarizeBy: sum
		sourceColumn: > 52 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 78 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: fa00194c-d31f-49af-ad07-f37e6558ed95
		summarizeBy: sum
		sourceColumn: > 78 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 104 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: a8f901d2-1431-4b92-a6e8-24444b5977de
		summarizeBy: sum
		sourceColumn: > 104 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: bf56121b-d768-4a4c-ad9b-6a176782d200
		summarizeBy: none
		sourceColumn: Period

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Sort Financial Year' = ```
			
			 var _month = month('benchmarking'[period])
			 var _result = IF(_month > 3, _month-3, _month+9)
			 return
			 _result
			
			```
		formatString: 0
		lineageTag: 9c80f670-c2e4-4605-8868-65bbe18bd48b
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'GHT Flag' = IF(Benchmarking[Provider_Organisation_Code]="RTE", 1,0)
		formatString: 0
		lineageTag: fdc0864d-93ab-4c48-a304-d66c7f19b088
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy 'Period Hierarchy'
		lineageTag: 39d61af9-902a-4884-997d-68435983d471

		level Period
			lineageTag: 8688fbab-fc81-4aed-8502-f6870bc02e75
			column: Period

		level FinancialYear
			lineageTag: 602c7322-3b8a-44f6-b73f-2f2a406e1f62
			column: FinancialYear

		level Month
			lineageTag: 79b832da-bd35-43ec-b7da-3495b9ca93df
			column: Month

		changedProperty = IsHidden

	partition Benchmarking = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select id as ""ID"", financial_year as ""Financial_Year"", financialyear as ""FinancialYear"", date as ""Date"", month as ""Month"", monthname as ""MonthName"", provider_parent_organisation_code as ""Provider_Parent_Organisation_Code"", provider_parent_organisation_name as ""Provider_Parent_Organisation_Name"", benchmarking_england as ""Benchmarking_England"", benchmarking_southwest as ""Benchmarking_SouthWest"", benchmarking_organisation_name as ""Benchmarking_Organisation_Name"", provider_organisation_code as ""Provider_Organisation_Code"", provider_organisation_name as ""Provider_Organisation_Name"", commissioner_parent_organisation_code as ""Commissioner_Parent_Organisation_Code"", commissioner_parent_organisation_name as ""Commissioner_Parent_Organisation_Name"", commissioner_organisation_code as ""Commissioner_Organisation_Code"", commissioner_organisation_name as ""Commissioner_Organisation_Name"", rtt_part_name as ""RTT_Part_Name"", rtt_part_description as ""RTT_Part_Description"", treatment_function_code as ""Treatment_Function_Code"", treatment_function_name as ""Treatment_Function_Name"", total_all as ""Total_All"", band_0_18_weeks_total as ""0-18_Weeks_Total"", band_gt_18_weeks_total as "">_18_Weeks_Total"", band_gt_35_weeks_total as "">_35_Weeks_Total"", band_lt_52_weeks_total, band_gt_52_weeks_total as "">_52_Weeks_Total"", band_gt_78_weeks_total as "">_78_Weeks_Total"", band_gt_104_weeks_total as "">_104_Weeks_Total"" from data_mart_powerbi_performance.tbl04_rttbenchmarking", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Date", "Period"}, {"Provider_Organisation_Name", "Provider"}, {"0-18_Weeks_Total", "0-18 Weeks"}, {">_78_Weeks_Total", "> 78 Weeks"}, {">_18_Weeks_Total", "> 18 Weeks"}, {">_35_Weeks_Total", "> 35 Weeks"}, {"<_52_Weeks_Total", "< 52 Weeks"}, {">_52_Weeks_Total", "> 52 Weeks"}, {">_104_Weeks_Total", "> 104 Weeks"}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns",{{"Month", Text.Proper, type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Capitalized Each Word",{{"Treatment_Function_Name", "Treatment Function Name"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

