table 'Date Reference'
	lineageTag: 2168406e-611d-434b-a269-4f386ff8b8ce

	column 'Sort Financial Year' = ```
			
			 var _month = month('Date Reference'[Date])
			 var _result = IF(_month > 3, _month-3, _month+9)
			 return
			 _result
			
			```
		formatString: 0
		lineageTag: 93ccf73b-81af-4914-a6a0-4084fa5c1188
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: f563c491-5efc-4337-b9dd-487b4e4f8393
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 7686bb9b-f75f-465b-a1cb-7529122ed7a3
			defaultHierarchy: LocalDateTable_3b527572-8da0-4012-9abe-fd46bafa4e71.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column day_month_year
		dataType: string
		lineageTag: 3c70c509-df73-4339-b5c5-2b080bb2f633
		summarizeBy: none
		sourceColumn: day_month_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: efe9c749-0d08-4ec5-b3ea-cfdc84eff2d4
		summarizeBy: sum
		sourceColumn: day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 87122b11-0411-4e1e-b290-e9fef3ee0245
		summarizeBy: sum
		sourceColumn: weekday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 3a4a5e2d-9ad0-427f-aaaf-beef78de7466
		summarizeBy: none
		sourceColumn: weekday_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 0bd5b26a-757c-4864-ac37-1a6d96390430
		summarizeBy: sum
		sourceColumn: month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 06d27a88-5696-46b0-9018-9aa40292e8c6
		summarizeBy: none
		sourceColumn: month_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 6a769609-2fb8-4564-a836-e5f952d50d35
		summarizeBy: sum
		sourceColumn: quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 62ca8b51-3a62-4cd0-bb6d-eb723404e3ce
		summarizeBy: sum
		sourceColumn: year_month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 047588d8-1e90-4a2c-b15f-3c6dc2bb17b1
		summarizeBy: sum
		sourceColumn: is_weekend

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: ea881fcb-bbda-48ce-b535-6571ba46fc05
		summarizeBy: sum
		sourceColumn: is_holiday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: 64e228f9-3b18-4a7d-9179-201a58fb03a3
		summarizeBy: none
		sourceColumn: holiday_description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: e0185a31-9f2b-48ce-9cfd-0f842f6dc4d9
		summarizeBy: sum
		sourceColumn: is_working_day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: b8a2d61f-bfa7-4d67-9b1f-9c3d1e9a2aae
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 0079ef47-b60e-497e-91dc-69dcfd0b0a0c
		summarizeBy: none
		sourceColumn: financial_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 94fcfb79-6ad3-4063-b697-0574f2328538
		summarizeBy: sum
		sourceColumn: financial_quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: 112a1b79-fcee-44d9-b444-425ab177f26a
		summarizeBy: sum
		sourceColumn: day_of_quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: afa02437-b1cd-4dfc-8e24-6089ef221a15
		summarizeBy: none
		sourceColumn: quarter_start_date

		variation Variation
			isDefault
			relationship: d2c6bf80-527f-4fdb-baba-a8b410aec790
			defaultHierarchy: LocalDateTable_e70dbe9d-b306-4e86-803b-51450bad4f08.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1397c856-15a3-4842-82ab-5eb647b521f8
		summarizeBy: none
		sourceColumn: quarter_end_date

		variation Variation
			isDefault
			relationship: d3622c4f-4654-4116-a9a5-267669a4b419
			defaultHierarchy: LocalDateTable_fccf959a-fc24-4a74-8820-7a63d590f919.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: fa3e88db-5f86-4e97-9995-44c76e91826a
		summarizeBy: sum
		sourceColumn: month_day_no

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 9392db0d-865f-44da-89e9-988d01dab6ed
		summarizeBy: sum
		sourceColumn: financial_month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 1a916e74-bc48-43d3-ab0f-b252d45152c0
		summarizeBy: none
		sourceColumn: month_year_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: string
		lineageTag: b21404d3-033d-4fe0-a351-2dae11eededa
		summarizeBy: none
		sourceColumn: month_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 518ca471-b51b-49f2-8fd0-d033a7e98fc3
		summarizeBy: sum
		sourceColumn: ytd_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: e9137fbc-1dd0-47bc-9063-c6033d48082a
		summarizeBy: sum
		sourceColumn: latest_month_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: dce22e98-3a87-44a1-ad79-0ff312ebc9c4
		summarizeBy: sum
		sourceColumn: previous_month_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 281b339c-60e6-496b-bc23-580f52c6756f
		summarizeBy: sum
		sourceColumn: latest_12_months_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latest_6_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 5226a1a0-f8d8-4713-89ee-be79a034732d
		summarizeBy: sum
		sourceColumn: latest_6_months_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 69e89e01-b290-4b0f-93dc-8c9e3188a96a
		summarizeBy: sum
		sourceColumn: previous_12_months_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: d8402ff9-546b-4e49-8629-75d6b0d47d94
		summarizeBy: sum
		sourceColumn: same_month_last_year_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Last_Update
		dataType: dateTime
		formatString: General Date
		lineageTag: 5221908a-0366-4d30-bd74-801494c69d07
		summarizeBy: none
		sourceColumn: Last_Update

		variation Variation
			isDefault
			relationship: df83b2da-b25b-4739-8e4e-d473fd7a0ce1
			defaultHierarchy: LocalDateTable_3be42d38-2183-4309-bcb0-c10ca5299668.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Date Reference' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="select * from [ccg_reference].[reference].[vw_Date]#(lf)where cast([date] as date) between '01/04/2023' and '01/04/2030'"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"date", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([month_day_no] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

