table 'Treatment Function Code Reference'
	lineageTag: 225c1e7b-490e-405d-9217-9b91428c79c6

	column Treatment_Function_Code
		dataType: string
		lineageTag: 49550239-5c2a-44ce-9ced-908a6739a8c8
		summarizeBy: none
		sourceColumn: Treatment_Function_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Name'
		dataType: string
		lineageTag: d22c2ae4-5787-4d28-adbc-b021cccb3203
		summarizeBy: none
		sourceColumn: Treatment Function Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Treatment Function Code Reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fdJRa8IwEADgvxL67KDa6uizE7eHWVEHA5FxtIcpxESu6cB/v1ycq63pnhqaL3eXy+330fxrHMfRKFqiRgIltg0dkS5ii/RdFRgdRlczduaDjDLHh70xn98RNCcQoEuRk5XmDFhWRZ9OmC6AxMrU6PFOkgHbdwm7/CytBHUKJk29+KfiKYMVNmRqB6qCZVfMWKwV1JYLDUd5ZjMHKivjLkVQDNKk08Y3bZG0W7xzGyqND5obunS5ySDb0CWTSZs9tO279IJ0Ahvc9z3aYH2uyAlX8UAxafzXq0CY1L/vRmIzkCf1dSxUiaQGc0zjCV/4ogGLUJAsy3iKjAXl/3x6n1uJJJ6uQdsXrH9J0iHanRWvCMrKPkzv4JonEyy103lT0zu17Q3NzczuzPXbgsMP", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Treatment_Function_Code = _t, Treatment_Function_Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Treatment_Function_Code", type text}, {"Treatment_Function_Name", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Treatment_Function_Name", "Treatment Function Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

