table 'Unpivoted RTT'
	lineageTag: 8b904465-7551-4836-b3f5-afc9ca4eeea1

	measure 'Previous Month' = CALCULATE(sum('Unpivoted RTT'[Selected Month]), PARALLELPERIOD('Date Reference'[Date], -1, MONTH))
		lineageTag: 6853deac-9f01-491a-9a76-3d9053410e40

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Year' = CALCULATE(sum('Unpivoted RTT'[Selected Month]), PARALLELPERIOD('Date Reference'[Date], -12, MONTH))
		lineageTag: da866035-dadf-43fc-a3bc-3a00afbcc6d9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Version
		dataType: string
		lineageTag: 2f19dd52-b7a9-4b57-acae-e7d74fb7d314
		summarizeBy: none
		sourceColumn: Version

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8f78c435-96b4-4d43-839a-6022f395530d
		summarizeBy: none
		sourceColumn: Period

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Provider_Parent_Org_Code
		dataType: string
		lineageTag: 9ce16507-d28c-4ab5-87b7-b9f3486c4cf0
		summarizeBy: none
		sourceColumn: Provider_Parent_Org_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Provider_Parent_Name
		dataType: string
		lineageTag: ce6483bf-4be0-4dc7-8b71-40217e3b5c39
		summarizeBy: none
		sourceColumn: Provider_Parent_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Provider_Org_Code
		dataType: string
		lineageTag: 2136f5d2-67fc-4e0e-8c16-8d697147196c
		summarizeBy: none
		sourceColumn: Provider_Org_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Provider Name'
		dataType: string
		lineageTag: a869ad3e-c9d1-411a-b57b-b04fa64710a9
		summarizeBy: none
		sourceColumn: Provider Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Org_Code
		dataType: string
		lineageTag: 3eb8eede-ed6a-428d-91e3-ceac2d196534
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Org_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Name
		dataType: string
		lineageTag: 659bf150-9c1e-4377-ba9b-d189dce7e07b
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Org_Code
		dataType: string
		lineageTag: 79f7e88b-0048-45fe-9b7c-c2bc18be4a5d
		summarizeBy: none
		sourceColumn: Commissioner_Org_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Commissioner_Org_Name
		dataType: string
		lineageTag: eab3e21b-6905-4f7f-b3ff-6dbc043253d3
		summarizeBy: none
		sourceColumn: Commissioner_Org_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Type
		dataType: string
		lineageTag: d3918933-53f8-451f-b064-cb39128fd1b1
		summarizeBy: none
		sourceColumn: RTT_Part_Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Description
		dataType: string
		lineageTag: f282199f-1b56-4fc6-aac9-48fe6328263e
		summarizeBy: none
		sourceColumn: RTT_Part_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Code'
		dataType: string
		lineageTag: b70a7582-387b-414b-ba19-58cd713b8f52
		summarizeBy: none
		sourceColumn: Treatment Function Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Name'
		dataType: string
		lineageTag: a6d71145-a960-4659-8a87-3daf34ecfad7
		summarizeBy: none
		sourceColumn: Treatment Function Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 52 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 00fa6918-c1a8-4691-835c-a817a424e97a
		summarizeBy: sum
		sourceColumn: > 52 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '0-18 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 77f3ca63-01c9-4434-ba40-a4570078977d
		summarizeBy: sum
		sourceColumn: 0-18 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 18 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 6d883b8c-d9a2-4747-97f5-480f07cd5f9e
		summarizeBy: sum
		sourceColumn: > 18 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '0-35 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: bdbb164b-5555-47dc-9cdd-130cafca2829
		summarizeBy: sum
		sourceColumn: 0-35 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 35 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 9639cb5d-fb99-4ce8-8255-2ced9ff59991
		summarizeBy: sum
		sourceColumn: > 35 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 65 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 7d31fd92-ef74-471c-b9a9-bb951c5ff39f
		summarizeBy: sum
		sourceColumn: > 65 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '> 78 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: cf083c6e-fe36-4c27-a272-539e42f55e84
		summarizeBy: sum
		sourceColumn: > 78 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column %_of_<18
		dataType: double
		lineageTag: 7d323f35-2395-49cb-9a0d-63daf4b19490
		summarizeBy: sum
		sourceColumn: %_of_<18

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %_>18
		dataType: double
		lineageTag: 1d1527e3-a926-4ad3-9563-4fb69d7f1d47
		summarizeBy: sum
		sourceColumn: %_>18

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %<35
		dataType: double
		lineageTag: 1d4ac0a3-38b3-40fc-b72c-ed588a45dbe3
		summarizeBy: sum
		sourceColumn: %<35

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>35
		dataType: double
		lineageTag: 581e68f9-a9f8-4dc5-96d3-25f8537485a7
		summarizeBy: sum
		sourceColumn: %>35

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>65
		dataType: double
		lineageTag: 392469ff-a56f-4f43-ac02-876815e39197
		summarizeBy: sum
		sourceColumn: %>65

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>78
		dataType: double
		lineageTag: 526ecbb1-2c72-4748-bb11-1eb635e78187
		summarizeBy: sum
		sourceColumn: %>78

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>104
		dataType: double
		lineageTag: 12434450-3ceb-4571-a1fe-3c85f3d51ee3
		summarizeBy: sum
		sourceColumn: %>104

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Patients_with_unknown_clock_start_date
		dataType: double
		lineageTag: 45f93a72-ccbd-45cb-a044-db7033614d30
		summarizeBy: sum
		sourceColumn: Patients_with_unknown_clock_start_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total
		dataType: double
		lineageTag: a67e09c4-6c16-4f29-9161-09c2e1bb798b
		summarizeBy: sum
		sourceColumn: Total

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Filename
		dataType: string
		lineageTag: 0778be3e-46b0-4d29-ba0c-93a6a6028048
		summarizeBy: none
		sourceColumn: Filename

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '% < 18 Weeks'
		dataType: double
		lineageTag: 479cdfca-6351-4a0e-86e9-17527e0f0165
		summarizeBy: sum
		sourceColumn: % < 18 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of Weeks Waiting'
		dataType: int64
		formatString: 0
		lineageTag: 33750480-b0b6-45b7-b574-2c54ddb4bb5c
		summarizeBy: sum
		sourceColumn: Number of Weeks Waiting

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Selected Month'
		dataType: int64
		lineageTag: 3ee77506-381c-4d21-8982-74144a63249d
		summarizeBy: sum
		sourceColumn: Selected Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '> 104 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 38931126-5024-4378-8bf8-11e45f76c1d4
		summarizeBy: sum
		sourceColumn: > 104 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Unpivoted RTT' = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("grh-ccg-sql", "powerbi_reporting", [Query="  SELECT * FROM [PowerBI_Reporting].[Performance].[tbl03_RTT]"]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Total"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Gt_104_Weeks_SUM_1", "> 104 Weeks"}, 
				{"Gt_52_Weeks_Plus", "> 52 Weeks"}, 
				{"0-18_Weeks_SUM_1", "0-18 Weeks"}, 
				{">65_Weeks_SUM_1", "> 65 Weeks"}, 
				{">_18_Weeks_SUM_1", "> 18 Weeks"}, 
				{"0-35_Weeks_SUM_1", "0-35 Weeks"}, 
				{">_35_Weeks_SUM_1", "> 35 Weeks"}, 
				{">_78_Weeks_SUM_1", "> 78 Weeks"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"> 104 Weeks", Int64.Type}, {"> 52 Weeks", Int64.Type}, {"0-18 Weeks", Int64.Type}, {"> 65 Weeks", Int64.Type}, {"> 18 Weeks", Int64.Type}, {"0-35 Weeks", Int64.Type}, {"> 35 Weeks", Int64.Type}, {"> 78 Weeks", Int64.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"Treatment_Function_Code", "Treatment Function Code"},
				{"Treatment_Function_Name", "Treatment Function Name"}, {"Total_All", "Total"}, {"0-18 Weeks",
				"< 18 Weeks"}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Renamed Columns1",{{"< 18 Weeks", "0-18 Weeks"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns2", "% < 18 Weeks", each [#"%_of_<18"]/100),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"% < 18 Weeks", type number}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type2",{{"Gt_48_To_49_Weeks_SUM_1", "48-49 Weeks"}, {"Gt_49_To_50_Weeks_SUM_1", "49-50 Weeks"}, {"Gt_50_To_51_Weeks_SUM_1", "50-51 Weeks"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns3",{{"48-49 Weeks", Int64.Type}, {"49-50 Weeks", Int64.Type}, {"50-51 Weeks", Int64.Type}, {"Gt_51_To_52_Weeks_SUM_1", Int64.Type}, {"Period_Name", type date}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type3",{{"Gt_51_To_52_Weeks_SUM_1", "51"}, {"Provider_Org_Name", "Provider Name"}, {"Gt_00_To_01_Weeks_SUM_1", "0"}, {"Gt_01_To_02_Weeks_SUM_1", "1"}, {"Gt_02_To_03_Weeks_SUM_1", "2"}, {"Gt_03_To_04_Weeks_SUM_1", "3"}, {"Gt_04_To_05_Weeks_SUM_1", "4"}, {"Gt_05_To_06_Weeks_SUM_1", "5"}, {"Gt_06_To_07_Weeks_SUM_1", "6"}, {"Gt_07_To_08_Weeks_SUM_1", "7"}, {"Gt_08_To_09_Weeks_SUM_1", "8"}, {"Gt_09_To_10_Weeks_SUM_1", "9"}, {"Gt_10_To_11_Weeks_SUM_1", "10"}, {"Gt_11_To_12_Weeks_SUM_1", "11"}, {"Gt_12_To_13_Weeks_SUM_1", "12"}, {"Gt_13_To_14_Weeks_SUM_1", "13"}, {"Gt_14_To_15_Weeks_SUM_1", "14"}, {"Gt_15_To_16_Weeks_SUM_1", "15"}, {"Gt_16_To_17_Weeks_SUM_1", "16"}, {"Gt_17_To_18_Weeks_SUM_1", "17"}, {"Gt_18_To_19_Weeks_SUM_1", "18"}, {"Gt_19_To_20_Weeks_SUM_1", "19"}, {"Gt_20_To_21_Weeks_SUM_1", "20"}, {"Gt_21_To_22_Weeks_SUM_1", "21"}, {"Gt_22_To_23_Weeks_SUM_1", "22"}, {"Gt_23_To_24_Weeks_SUM_1", "23"}, {"Gt_24_To_25_Weeks_SUM_1", "24"}, {"Gt_25_To_26_Weeks_SUM_1", "25"}, {"Gt_26_To_27_Weeks_SUM_1", "26"}, {"Gt_27_To_28_Weeks_SUM_1", "27"}, {"Gt_28_To_29_Weeks_SUM_1", "28"}, {"Gt_29_To_30_Weeks_SUM_1", "29"}, {"Gt_30_To_31_Weeks_SUM_1", "30"}, {"Gt_31_To_32_Weeks_SUM_1", "31"}, {"Gt_32_To_33_Weeks_SUM_1", "32"}, {"Gt_33_To_34_Weeks_SUM_1", "33"}, {"Gt_34_To_35_Weeks_SUM_1", "34"}, {"Gt_35_To_36_Weeks_SUM_1", "35"}, {"Gt_36_To_37_Weeks_SUM_1", "36"}, {"Gt_37_To_38_Weeks_SUM_1", "37"}, {"Gt_38_To_39_Weeks_SUM_1", "38"}, {"Gt_39_To_40_Weeks_SUM_1", "39"}, {"Gt_40_To_41_Weeks_SUM_1", "40"}, {"Gt_41_To_42_Weeks_SUM_1", "41"}, {"Gt_42_To_43_Weeks_SUM_1", "42"}, {"Gt_43_To_44_Weeks_SUM_1", "43"}, {"Gt_44_To_45_Weeks_SUM_1", "44"}, {"Gt_45_To_46_Weeks_SUM_1", "45"}, {"Gt_46_To_47_Weeks_SUM_1", "46"}, {"Gt_47_To_48_Weeks_SUM_1", "47"}, {"48-49 Weeks", "48"}, {"49-50 Weeks", "49"}, {"50-51 Weeks", "50"}, {"Gt_52_To_53_Weeks_SUM_1", "52"}, {"Gt_53_To_54_Weeks_SUM_1", "53"}, {"Gt_54_To_55_Weeks_SUM_1", "54"}, {"Gt_55_To_56_Weeks_SUM_1", "55"}, {"Gt_56_To_57_Weeks_SUM_1", "56"}, {"Gt_57_To_58_Weeks_SUM_1", "57"}, {"Gt_58_To_59_Weeks_SUM_1", "58"}, {"Gt_59_To_60_Weeks_SUM_1", "59"}, {"Gt_60_To_61_Weeks_SUM_1", "60"}, {"Gt_61_To_62_Weeks_SUM_1", "61"}, {"Gt_62_To_63_Weeks_SUM_1", "62"}, {"Gt_63_To_64_Weeks_SUM_1", "63"}, {"Gt_64_To_65_Weeks_SUM_1", "64"}, {"Gt_65_To_66_Weeks_SUM_1", "65"}, {"Gt_66_To_67_Weeks_SUM_1", "66"}, {"Gt_67_To_68_Weeks_SUM_1", "67"}, {"Gt_68_To_69_Weeks_SUM_1", "68"}, {"Gt_69_To_70_Weeks_SUM_1", "69"}, {"Gt_70_To_71_Weeks_SUM_1", "70"}, {"Gt_71_To_72_Weeks_SUM_1", "71"}, {"Gt_72_To_73_Weeks_SUM_1", "72"}, {"Gt_73_To_74_Weeks_SUM_1", "73"}, {"Gt_74_To_75_Weeks_SUM_1", "74"}, {"Gt_75_To_76_Weeks_SUM_1", "75"}, {"Gt_76_To_77_Weeks_SUM_1", "76"}, {"Gt_77_To_78_Weeks_SUM_1", "77"}, {"Gt_78_To_79_Weeks_SUM_1", "78"}, {"Gt_79_To_80_Weeks_SUM_1", "79"}, {"Gt_80_To_81_Weeks_SUM_1", "80"}, {"Gt_81_To_82_Weeks_SUM_1", "81"}, {"Gt_82_To_83_Weeks_SUM_1", "82"}, {"Gt_83_To_84_Weeks_SUM_1", "83"}, {"Gt_84_To_85_Weeks_SUM_1", "84"}, {"Gt_85_To_86_Weeks_SUM_1", "85"}, {"Gt_86_To_87_Weeks_SUM_1", "86"}, {"Gt_87_To_88_Weeks_SUM_1", "87"}, {"Gt_88_To_89_Weeks_SUM_1", "88"}, {"Gt_89_To_90_Weeks_SUM_1", "89"}, {"Gt_90_To_91_Weeks_SUM_1", "90"}, {"Gt_91_To_92_Weeks_SUM_1", "91"}, {"Gt_92_To_93_Weeks_SUM_1", "92"}, {"Gt_93_To_94_Weeks_SUM_1", "93"}, {"Gt_94_To_95_Weeks_SUM_1", "94"}, {"Gt_95_To_96_Weeks_SUM_1", "95"}, {"Gt_96_To_97_Weeks_SUM_1", "96"}, {"Gt_97_To_98_Weeks_SUM_1", "97"}, {"Gt_98_To_99_Weeks_SUM_1", "98"}, {"Gt_99_To_100_Weeks_SUM_1", "99"}, {"Gt_100_To_101_Weeks_SUM_1", "100"}, {"Gt_101_To_102_Weeks_SUM_1", "101"}, {"Gt_102_To_103_Weeks_SUM_1", "102"}, {"Gt_103_To_104_Weeks_SUM_1", "103"}, {"Period_Name", "Period"}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Renamed Columns4", {"Version", "Period", "Provider_Parent_Org_Code", "Provider_Parent_Name", "Provider_Org_Code", "Provider Name", "Commissioner_Parent_Org_Code", "Commissioner_Parent_Name", "Commissioner_Org_Code", "Commissioner_Org_Name", "RTT_Part_Type", "RTT_Part_Description", "Treatment Function Code", "Treatment Function Name", "> 52 Weeks", "0-18 Weeks", "> 18 Weeks", "0-35 Weeks", "> 35 Weeks", "> 65 Weeks", "> 78 Weeks", "%_of_<18", "%_>18", "%<35", "%>35", "%>65", "%>78", "%>104", "Patients_with_unknown_clock_start_date", "Total", "Filename", "% < 18 Weeks", "> 104 Weeks"}, "Attribute", "Value"),
				    #"Renamed Columns5" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "Number of Weeks Waiting"}, {"Value", "Selected Month"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns5",{{"Number of Weeks Waiting", Int64.Type}, {"Selected Month", Int64.Type}}),
				    #"Extracted Last Characters" = Table.TransformColumns(#"Changed Type1", {{"Period", each Text.End(Text.From(_, "en-GB"), 9), type text}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Extracted Last Characters",{{"Period", type date}})
				in
				    #"Changed Type4"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

