table age_populations
	lineageTag: 46ae5deb-94d6-4049-9e63-756776abd991

	column age
		dataType: int64
		formatString: 0
		lineageTag: 1e2374ba-54da-48c0-8bfa-b639c667290f
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = age

		annotation PBI_WasHiddenAtRefresh = False

	column 5yr_age_band
		dataType: string
		lineageTag: 8b3bd581-d6a2-4233-aa55-936ee42008f0
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = 5yr_age_band

		annotation PBI_WasHiddenAtRefresh = False

	column 10yr_age_band
		dataType: string
		lineageTag: b3ab8ed4-1793-422b-bd45-f6be2e254b2c
		summarizeBy: none
		sourceColumn: 10yr_age_band

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = 10yr_age_band

		annotation PBI_WasHiddenAtRefresh = False

	column total_population
		dataType: int64
		formatString: 0
		lineageTag: d911972a-08f5-4592-8ef4-1dafa9ca8a51
		summarizeBy: sum
		sourceColumn: total_population

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = total_population

		annotation PBI_WasHiddenAtRefresh = False

	column mildly_frail_population
		dataType: int64
		formatString: 0
		lineageTag: 9aa2970f-bca0-4ee7-909f-f3465a2cb194
		summarizeBy: sum
		sourceColumn: mildly_frail_population

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = mildly_frail_population

		annotation PBI_WasHiddenAtRefresh = False

	column moderately_frail_population
		dataType: int64
		formatString: 0
		lineageTag: 562531b6-6c11-48b5-9a1d-72e0958c86b8
		summarizeBy: sum
		sourceColumn: moderately_frail_population

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = moderately_frail_population

		annotation PBI_WasHiddenAtRefresh = False

	column severely_frail_population
		dataType: int64
		formatString: 0
		lineageTag: 87f5e46e-21a4-4a09-bd19-025df4e4d11e
		summarizeBy: sum
		sourceColumn: severely_frail_population

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = severely_frail_population

		annotation PBI_WasHiddenAtRefresh = False

	partition age_populations-ce1f2953-280b-439b-ba16-04a6ab9aa0a2 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select * from [PowerBI_Reporting].[dbo].[Age_Frail_Populations]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"total_population", "total_population"}})
				in
				    #"Renamed Columns"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

