table ed_attendances
	lineageTag: dab4862a-368a-4c1d-a93e-1dd14181dee6

	measure mildly_frail_ed_att = CALCULATE(COUNT('ed_attendances'[counter]),FILTER('ed_attendances','ed_attendances'[efi_category] IN {"Mild Frailty"}))
		formatString: 0
		lineageTag: 126a31d0-c08b-430d-9d79-c32624ae918b

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure moderately_frail_ed_att = CALCULATE(COUNT('ed_attendances'[counter]),FILTER('ed_attendances','ed_attendances'[efi_category] IN {"Moderate Frailty"}))
		formatString: 0
		lineageTag: 887bdb8c-9a2f-4630-9c41-92151b615316

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure severely_frail_ed_att = CALCULATE(COUNT('ed_attendances'[counter]),FILTER('ed_attendances','ed_attendances'[efi_category] IN {"Severe Frailty"}))
		formatString: 0
		lineageTag: 7a0f8a60-fa36-4988-9ee8-37f09acd710e

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure dementia_ed_att_% = SUM('ed_attendances'[dementia_flag]) / [total_frail_ed_att]
		formatString: 0%;-0%;0%
		lineageTag: d6d09e57-1a97-4289-9d71-c143d7ac6ca2

		annotation Format = <Format Format="Percentage" Accuracy="0" />

	measure locality_mildly_frail_ed_att_per_1000 = ([mildly_frail_ed_att]/SUM(locality_populations[mildly_frail_population])*1000)
		formatString: 0.0
		lineageTag: b0f73a66-851f-4669-8d83-d8a5bf1c540b

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure locality_moderately_frail_ed_att_per_1000 = ([moderately_frail_ed_att]/SUM(locality_populations[moderately_frail_population])*1000)
		formatString: 0.0
		lineageTag: 9390b750-e00d-4c62-a8b8-48712a3d23c9

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure locality_severely_frail_ed_att_per_1000 = ([severely_frail_ed_att]/SUM(locality_populations[severely_frail_population])*1000)
		formatString: 0.0
		lineageTag: af377f2b-184a-42f4-a354-722879e69a2d

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure pcn_mildly_frail_ed_att_per_1000 = ([mildly_frail_ed_att]/SUM(pcn_populations[mildly_frail_population])*1000)
		formatString: 0.0
		lineageTag: 25eb8bb9-22d8-4061-b847-8429a62c773d

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure pcn_moderately_frail_ed_att_per_1000 = ([moderately_frail_ed_att]/SUM(pcn_populations[moderately_frail_population])*1000)
		formatString: 0.0
		lineageTag: 0ffb59d7-f03b-4435-8cbb-35ec5e775b1b

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure pcn_severely_frail_ed_att_per_1000 = ([severely_frail_ed_att]/SUM(pcn_populations[severely_frail_population])*1000)
		formatString: 0.0
		lineageTag: 6774b152-1d19-4565-94b1-49d5b83f778d

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure ambulance_atts_% = CALCULATE(COUNT('ed_attendances'[counter]),FILTER('ed_attendances','ed_attendances'[arrival_mode] IN {"Ambulance"}))/ SUM('ed_attendances'[counter])
		formatString: 0%;-0%;0%
		lineageTag: cdb370fa-f546-48aa-b412-4fa6629848fe

		annotation Format = <Format Format="Percentage" Accuracy="0" />

	measure mildly_frail_ed_att_per_1000_ot = ([mildly_frail_ed_att]/sum(frail_population_over_time[Mild_Frailty])*1000)
		formatString: 0.0
		lineageTag: 2062302d-3a19-4dfd-b173-2e8606d770cd

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_ed_att_per_1000_ot = ([moderately_frail_ed_att]/sum(frail_population_over_time[Moderate_Frailty])*1000)
		formatString: 0.0
		lineageTag: 7a1bc46f-37bf-4411-bdbb-d2c6d39933d2

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_ed_att_per_1000_ot = ([severely_frail_ed_att]/sum(frail_population_over_time[Severe_Frailty])*1000)
		formatString: 0.0
		lineageTag: 03a4e704-5de8-4c56-bf92-d97064cf0659

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure total_frail_ed_att = CALCULATE(COUNT('ed_attendances'[counter]))
		formatString: 0
		lineageTag: a9ae510a-65e3-4cef-8ac9-3de3a1b57c11

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure total_frail_ed_att_per_1000 = ([total_frail_ed_att]/[total_frail_population_ot])*1000
		formatString: 0.0
		lineageTag: 58d074b0-d9fb-432c-ad01-4a59a471874b

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_ed_att_per_1000_current = ([mildly_frail_ed_att]/[mildly_frail_population_current])*1000
		formatString: 0.0
		lineageTag: c1025f9d-f34f-4017-8030-f7fa09d6c7ff

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_ed_att_per_1000_current = ([moderately_frail_ed_att]/[moderately_frail_population_current])*1000
		lineageTag: 6cbcf1ea-5ca2-402f-a181-7ce94dc03615

	measure severely_frail_ed_att_per_1000_current = ([severely_frail_ed_att]/[severely_frail_population_current])*1000
		formatString: 0.0
		lineageTag: d9fa2c99-f50a-4886-86d8-00224c354f38

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure age_mildly_frail_ed_att_per_1000 = ([mildly_frail_ed_att]/SUM(age_populations[mildly_frail_population])*1000)
		formatString: 0.0
		lineageTag: 84ae8b08-f505-4d55-bfd3-e897da0b872e

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure age_moderately_frail_ed_att_per_1000 = ([moderately_frail_ed_att]/SUM(age_populations[moderately_frail_population])*1000)
		formatString: 0.0
		lineageTag: b33f6ecd-8b42-4167-b306-7e1af0bd708b

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure age_severely_frail_ed_att_per_1000 = ([severely_frail_ed_att]/SUM(age_populations[severely_frail_population])*1000)
		formatString: 0.0
		lineageTag: a68a2cd3-48b4-4f71-9a12-df98b6319405

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure deprivation_mildly_frail_ed_att_per_1000 = ([mildly_frail_ed_att]/SUM(deprivation_populations[mildly_frail_population])*1000)
		formatString: 0.0
		lineageTag: fa158818-c345-4f23-8717-d66799eea34c

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure deprivation_moderately_frail_ed_att_per_1000 = ([moderately_frail_ed_att]/SUM(deprivation_populations[moderately_frail_population])*1000)
		formatString: 0.0
		lineageTag: b7b41645-cb53-4998-8439-c15e705d1b91

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure deprivation_severely_frail_ed_att_per_1000 = ([severely_frail_ed_att]/SUM(deprivation_populations[severely_frail_population])*1000)
		formatString: 0.0
		lineageTag: 285239cd-22f7-4ece-92fa-4861a1a8b52e

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_ed_att_per_1000_2019/20 = ([mildly_frail_ed_att]/[mildly_frail_2019/20])*1000
		formatString: 0.0
		lineageTag: c212bf2c-078a-4854-b998-636854447ee0

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_ed_att_per_1000_2019/20 = ([moderately_frail_ed_att]/[moderately_frail_2019/20])*1000
		formatString: 0.0
		lineageTag: bf4a716c-1636-49ef-8938-7906f20b3e22

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_ed_att_per_1000_2019/20 = ([severely_frail_ed_att]/[severely_frail_2019/20])*1000
		formatString: 0.0
		lineageTag: b0dfe4d8-6756-4e16-a952-446640f6bab5

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_ed_att_per_1000_2022/23 = ([mildly_frail_ed_att]/[mildly_frail_2022/23])*1000
		formatString: 0.0
		lineageTag: c9175483-135e-4ab8-879c-d6ca0440535b

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_ed_att_per_1000_2022/23 = ([severely_frail_ed_att]/[severely_frail_2022/23])*1000
		formatString: 0.0
		lineageTag: c977066a-6fe3-403d-a373-4170552954e1

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_ed_att_per_1000_2022/23 = ([moderately_frail_ed_att]/[moderately_frail_2022/23])*1000
		formatString: 0.0
		lineageTag: 6aa1a0cd-74d7-479a-83fa-baa2be6a4caa

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_ed_att_per_1000_2020/21 = ([mildly_frail_ed_att]/[mildly_frail_2020/21])*1000
		formatString: 0.0
		lineageTag: 567e8364-3419-4173-a4d7-a777027a96cc

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_ed_att_per_1000_2020/21 = ([moderately_frail_ed_att]/[moderately_frail_2020/21])*1000
		formatString: 0.0
		lineageTag: 401dca13-e2ca-4ef5-b25c-b80cfdf19591

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_ed_att_per_1000_2020/21 = ([severely_frail_ed_att]/[severely_frail_2020/21])*1000
		formatString: 0.0
		lineageTag: c277b7bc-73a3-4174-8b96-217cf29626f4

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_ed_att_per_1000_2021/22 = ([mildly_frail_ed_att]/[mildly_frail_2021/22])*1000
		formatString: 0.0
		lineageTag: 63bf03e9-3fe5-44e4-924a-06842106915b

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_ed_att_per_1000_2021/22 = ([moderately_frail_ed_att]/[moderately_frail_2021/22])*1000
		formatString: 0.0
		lineageTag: b83436cb-411c-439d-8f41-5d062d41f3ef

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_ed_att_per_1000_2021/22 = ([severely_frail_ed_att]/[severely_frail_2021/22])*1000
		formatString: 0.0
		lineageTag: aa8807f8-abb3-471e-ab4c-0fe0abb2153a

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure total_frail_ed_att_2022/23 = CALCULATE(DISTINCTCOUNT('ed_attendances'[nhs_number]),FILTER('ed_attendances','ed_attendances'[efi_category] IN {"Mild Frailty","Moderate Frailty","Severe Frailty"}), FILTER(date_table,'date_table'[financial_year] = "2022/23"))
		formatString: 0
		lineageTag: 16b554ff-d839-4ec4-8599-fa0b4b9be1db

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure %_ed_att_2022/23 = [total_frail_ed_att_2022/23]/[total_frail_population_current]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 03623b06-61b8-48dc-8cda-3903f735cb7f

		annotation Format = <Format Format="Percentage" Accuracy="2" />

	column nhs_number
		dataType: string
		lineageTag: ec309e28-45a4-468d-828a-0d3ad617af70
		summarizeBy: none
		sourceColumn: nhs_number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = nhs_number

		annotation PBI_WasHiddenAtRefresh = False

	column arrival_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5f8ca62c-a0fe-4ea6-907b-8a63660321f2
		summarizeBy: none
		sourceColumn: arrival_date

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = arrival_date

		annotation PBI_WasHiddenAtRefresh = False

	column arrival_time
		dataType: dateTime
		formatString: hh:nn:ss
		lineageTag: c1326939-98a8-4563-a3c2-b9bce5160570
		summarizeBy: none
		sourceColumn: arrival_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="LongTime" FormatString="HH:mm:ss" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####Time

		annotation PBI_NameAtRefresh = arrival_time

		annotation PBI_WasHiddenAtRefresh = False

	column provider_code
		dataType: string
		lineageTag: ca36a589-4baa-44bd-a1eb-ed385f2decd6
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_code

		annotation PBI_WasHiddenAtRefresh = False

	column site_code
		dataType: string
		lineageTag: 2d3f77ef-e777-4dd6-b61c-6285d1e5ad39
		summarizeBy: none
		sourceColumn: site_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = site_code

		annotation PBI_WasHiddenAtRefresh = False

	column practice_code
		dataType: string
		lineageTag: c6392265-9417-48ce-8c64-e6ae7ac11a08
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = practice_code

		annotation PBI_WasHiddenAtRefresh = False

	column age_at_activity_date
		dataType: int64
		formatString: 0
		lineageTag: df053777-b8af-48bf-8f9b-2c7b36a673ff
		summarizeBy: none
		sourceColumn: age_at_activity_date

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = age_at_activity_date

		annotation PBI_WasHiddenAtRefresh = False

	column deprivation_decile
		dataType: int64
		formatString: 0
		lineageTag: c7ab50ab-9db0-4622-b9a6-5e432b765a3a
		summarizeBy: none
		sourceColumn: deprivation_decile

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = deprivation_decile

		annotation PBI_WasHiddenAtRefresh = False

	column locality
		dataType: string
		lineageTag: b0ba5880-a381-44f3-9898-35e78b375c41
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = locality

		annotation PBI_WasHiddenAtRefresh = False

	column primary_care_network
		dataType: string
		lineageTag: e3b856c7-99a7-4898-a6c9-4572bada105a
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = primary_care_network

		annotation PBI_WasHiddenAtRefresh = False

	column practice_name
		dataType: string
		lineageTag: 1e270f0c-cae9-4521-8a0e-2c66a8f0fc67
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = practice_name

		annotation PBI_WasHiddenAtRefresh = False

	column site_name
		dataType: string
		lineageTag: 6da3967b-348a-467e-afbb-3ea3ea4ed535
		summarizeBy: none
		sourceColumn: site_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = site_name

		annotation PBI_WasHiddenAtRefresh = False

	column chief_complaint_code
		dataType: string
		lineageTag: 17828ec4-3a6c-4181-a91d-42d1ebccf566
		summarizeBy: none
		sourceColumn: chief_complaint_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = chief_complaint_code

		annotation PBI_WasHiddenAtRefresh = False

	column id
		dataType: string
		lineageTag: 04d50321-36b5-4226-ae1a-3843f24436d1
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = id

		annotation PBI_WasHiddenAtRefresh = False

	column arrival_mode_code
		dataType: string
		lineageTag: 94b6ef18-b2c7-422a-b8e2-7b5cba00810d
		summarizeBy: none
		sourceColumn: arrival_mode_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = arrival_mode_code

		annotation PBI_WasHiddenAtRefresh = False

	column attendance_category_code
		dataType: string
		lineageTag: f0c37a0c-7173-43d0-a2a2-7219823c6c04
		summarizeBy: none
		sourceColumn: attendance_category_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = attendance_category_code

		annotation PBI_WasHiddenAtRefresh = False

	column department_type_code
		dataType: int64
		formatString: 0
		lineageTag: 303cce56-b3fc-412e-9986-32447284167f
		summarizeBy: sum
		sourceColumn: department_type_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = department_type_code

		annotation PBI_WasHiddenAtRefresh = False

	column diagnosis_code
		dataType: string
		lineageTag: 4562d801-cf9c-49e7-8f6f-f123471634ae
		summarizeBy: none
		sourceColumn: diagnosis_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = diagnosis_code

		annotation PBI_WasHiddenAtRefresh = False

	column code_of_commissioner
		dataType: string
		lineageTag: bf807b33-6d68-4bd6-b867-67ce96d7d94d
		summarizeBy: none
		sourceColumn: code_of_commissioner

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = code_of_commissioner

		annotation PBI_WasHiddenAtRefresh = False

	column departure_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d861760c-b16a-4b92-a21e-084ccb0bdf6b
		summarizeBy: none
		sourceColumn: departure_date

		variation Variation
			isDefault
			relationship: 5d1476e5-c094-416b-8f53-37953fea8336
			defaultHierarchy: LocalDateTable_2c1d2b57-ee48-4d15-b330-e3ea84d52762.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = departure_date

		annotation PBI_WasHiddenAtRefresh = False

	column departure_time
		dataType: dateTime
		formatString: hh:nn:ss
		lineageTag: 75f8e3fd-072c-42ad-b9ee-061ba645e2fb
		summarizeBy: none
		sourceColumn: departure_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="LongTime" FormatString="HH:mm:ss" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####Time

		annotation PBI_NameAtRefresh = departure_time

		annotation PBI_WasHiddenAtRefresh = False

	column minutes_in_ed
		dataType: int64
		formatString: 0
		lineageTag: 3a3a74ad-2e4c-4f83-aad5-f7fd76da98d2
		summarizeBy: sum
		sourceColumn: minutes_in_ed

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = minutes_in_ed

		annotation PBI_WasHiddenAtRefresh = False

	column decision_to_admit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 43179a6a-cfca-4617-bc1a-f9e2948d2e38
		summarizeBy: none
		sourceColumn: decision_to_admit_date

		variation Variation
			isDefault
			relationship: 7ea4921f-bc46-4f32-984b-4b45ae5d0325
			defaultHierarchy: LocalDateTable_50b4db23-7e53-41d7-8687-0793a2e26514.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = decision_to_admit_date

		annotation PBI_WasHiddenAtRefresh = False

	column counter
		dataType: int64
		formatString: 0
		lineageTag: e0ce4854-2666-4398-a099-758be9395aa5
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = counter

		annotation PBI_WasHiddenAtRefresh = False

	column financial_year
		dataType: string
		lineageTag: 8518ab8f-ba12-4280-89f6-02c443ae6c40
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = financial_year

		annotation PBI_WasHiddenAtRefresh = False

	column month_name
		dataType: string
		lineageTag: 243a3e43-6bfb-4e76-ac1e-10b38eb5ad66
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = month_name

		annotation PBI_WasHiddenAtRefresh = False

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 7652f7ef-f300-43f6-bbc2-b62429924fc5
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = financial_month

		annotation PBI_WasHiddenAtRefresh = False

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 0897502c-228f-4030-accc-68c1fe72aa9f
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = year_month

		annotation PBI_WasHiddenAtRefresh = False

	column lsoa
		dataType: string
		lineageTag: 65098fc7-9823-4f22-97c1-05b9018f89f8
		summarizeBy: none
		sourceColumn: lsoa

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = lsoa

		annotation PBI_WasHiddenAtRefresh = False

	column 5yr_age_band
		dataType: string
		lineageTag: 3992800b-650e-420f-a84e-ebf7c381f3b8
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = 5yr_age_band

		annotation PBI_WasHiddenAtRefresh = False

	column 10yr_age_band
		dataType: string
		lineageTag: 810bfdf4-d45c-419c-9a0b-0903d64cf3ea
		summarizeBy: none
		sourceColumn: 10yr_age_band

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = 10yr_age_band

		annotation PBI_WasHiddenAtRefresh = False

	column ethnic_origin
		dataType: string
		lineageTag: d1db968d-afef-4bbd-84de-b6c7bf44760b
		summarizeBy: none
		sourceColumn: ethnic_origin

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = ethnic_origin

		annotation PBI_WasHiddenAtRefresh = False

	column ethnic_origin_group
		dataType: string
		lineageTag: 424837e7-d2bc-4a70-8cb4-c664ff2fe0b9
		summarizeBy: none
		sourceColumn: ethnic_origin_group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = ethnic_origin_group

		annotation PBI_WasHiddenAtRefresh = False

	column living_in_a_care_home
		dataType: int64
		formatString: 0
		lineageTag: c98b914c-17c1-4865-ae6b-e7fe603803e4
		summarizeBy: sum
		sourceColumn: living_in_a_care_home

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = living_in_a_care_home

		annotation PBI_WasHiddenAtRefresh = False

	column living_alone
		dataType: int64
		formatString: 0
		lineageTag: a36f5064-ac50-4974-9669-39af523b722d
		summarizeBy: sum
		sourceColumn: living_alone

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = living_alone

		annotation PBI_WasHiddenAtRefresh = False

	column efi_category
		dataType: string
		lineageTag: b6b7dca5-bccc-4098-b2ef-64c1a17f1ea9
		summarizeBy: none
		sourceColumn: efi_category

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = efi_category

		annotation PBI_WasHiddenAtRefresh = False

	column provider_name
		dataType: string
		lineageTag: 60ce21fb-74c9-4532-bcf0-58194c3c578d
		summarizeBy: none
		sourceColumn: provider_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_name

		annotation PBI_WasHiddenAtRefresh = False

	column provider_group
		dataType: string
		lineageTag: 47033258-36a3-45b7-ab3b-7dcedec0c4af
		summarizeBy: none
		sourceColumn: provider_group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_group

		annotation PBI_WasHiddenAtRefresh = False

	column chief_complaint
		dataType: string
		lineageTag: 61d75b91-c1d7-4433-aaba-c736c4cca409
		summarizeBy: none
		sourceColumn: chief_complaint

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = chief_complaint

		annotation PBI_WasHiddenAtRefresh = False

	column diagnosis_description
		dataType: string
		lineageTag: a443fb16-f6d2-4448-b545-ebe689e3eb79
		summarizeBy: none
		sourceColumn: diagnosis_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = diagnosis_description

		annotation PBI_WasHiddenAtRefresh = False

	column department_type
		dataType: string
		lineageTag: 9e375c73-9d38-4ef8-a2c8-eb8010b9c35e
		summarizeBy: none
		sourceColumn: department_type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = department_type

		annotation PBI_WasHiddenAtRefresh = False

	column arrival_mode
		dataType: string
		lineageTag: ce708323-330c-489d-ac6a-cc3fc64d4db7
		summarizeBy: none
		sourceColumn: arrival_mode

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = arrival_mode

		annotation PBI_WasHiddenAtRefresh = False

	column attendance_category
		dataType: string
		lineageTag: 86e9f764-8301-48ae-bfa5-70cca3ca71f6
		summarizeBy: none
		sourceColumn: attendance_category

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = attendance_category

		annotation PBI_WasHiddenAtRefresh = False

	column dementia_flag
		dataType: int64
		formatString: 0
		lineageTag: 93c59472-113a-40b9-9f5f-6fa142b30188
		summarizeBy: sum
		sourceColumn: dementia_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = dementia_flag

		annotation PBI_WasHiddenAtRefresh = False

	column census_date
		dataType: string
		lineageTag: 6134cc35-230d-4e80-ab84-e9fc8d69a53d
		summarizeBy: none
		sourceColumn: census_date

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = census_date

		annotation PBI_WasHiddenAtRefresh = False

	column mild_frailty
		dataType: string
		lineageTag: a5af13c8-c9d6-4e16-a965-7741f61cf3d5
		summarizeBy: none
		sourceColumn: mild_frailty

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = mild_frailty

		annotation PBI_WasHiddenAtRefresh = False

	column moderate_frailty
		dataType: string
		lineageTag: 026477c6-85cb-4f1c-9c93-b7caee237acf
		summarizeBy: none
		sourceColumn: moderate_frailty

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = moderate_frailty

		annotation PBI_WasHiddenAtRefresh = False

	column severe_frailty
		dataType: string
		lineageTag: 8c1daeeb-8fc7-4a4b-82a0-087900a1dfa1
		summarizeBy: none
		sourceColumn: severe_frailty

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = severe_frailty

		annotation PBI_WasHiddenAtRefresh = False

	column arrival_hour
		dataType: int64
		formatString: 0
		lineageTag: 0901ed84-7927-4cf9-ba62-838c59c35d73
		summarizeBy: sum
		sourceColumn: arrival_hour

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = arrival_hour

		annotation PBI_WasHiddenAtRefresh = False

	column postcode_key
		dataType: string
		lineageTag: c7e85b3e-d3ea-4ff2-b77d-252bfe291bc5
		summarizeBy: none
		sourceColumn: postcode_key

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = postcode_key

		annotation PBI_WasHiddenAtRefresh = False

	column core_20
		dataType: int64
		formatString: 0
		lineageTag: 9d606753-d1a5-4580-806d-15e7cf43e2a2
		summarizeBy: sum
		sourceColumn: core_20

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = core_20

		annotation PBI_WasHiddenAtRefresh = False

	column discharge_status
		dataType: string
		lineageTag: 1cb4dd42-0d32-4972-90dd-6af0c73006a2
		summarizeBy: none
		sourceColumn: discharge_status

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = discharge_status

		annotation PBI_WasHiddenAtRefresh = False

	column discharge_destination
		dataType: string
		lineageTag: 98604b63-3ce7-4f52-b0a5-f6e77aa83712
		summarizeBy: none
		sourceColumn: discharge_destination

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = discharge_destination

		annotation PBI_WasHiddenAtRefresh = False

	column discharge_follow_up
		dataType: string
		lineageTag: 068c150c-2b3f-4565-ac60-e50a758c156d
		summarizeBy: none
		sourceColumn: discharge_follow_up

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = discharge_follow_up

		annotation PBI_WasHiddenAtRefresh = False

	column acuity_code
		dataType: string
		lineageTag: cbb8920b-cbdd-4891-9200-9cebe57a6890
		summarizeBy: none
		sourceColumn: acuity_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = acuity_code

		annotation PBI_WasHiddenAtRefresh = False

	column acuity
		dataType: string
		lineageTag: 0a467753-54f8-4838-a7f0-38019c7535b3
		summarizeBy: none
		sourceColumn: acuity

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = acuity

		annotation PBI_WasHiddenAtRefresh = False

	column major_minor_flag
		dataType: string
		lineageTag: 725f5793-6c8d-4cf0-9ac5-871ed2affca6
		summarizeBy: none
		sourceColumn: major_minor_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = major_minor_flag

		annotation PBI_WasHiddenAtRefresh = False

	column injury_illness_flag
		dataType: string
		lineageTag: 7973b55f-d5e2-480b-8b66-4bbdf5133dbe
		summarizeBy: none
		sourceColumn: injury_illness_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_illness_flag

		annotation PBI_WasHiddenAtRefresh = False

	column mental_health_classification_code
		dataType: string
		lineageTag: bd4b72ec-a626-4215-863c-5949f815ec81
		summarizeBy: none
		sourceColumn: mental_health_classification_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = mental_health_classification_code

		annotation PBI_WasHiddenAtRefresh = False

	column mental_health_classification
		dataType: string
		lineageTag: cffde491-d6b9-47b7-8f0b-e22ec8d6e333
		summarizeBy: none
		sourceColumn: mental_health_classification

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = mental_health_classification

		annotation PBI_WasHiddenAtRefresh = False

	column discharge_status_code
		dataType: string
		lineageTag: 5bb03ed6-144c-4a07-8ebf-6096ddc49b19
		summarizeBy: none
		sourceColumn: discharge_status_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = discharge_status_code

		annotation PBI_WasHiddenAtRefresh = False

	column discharge_destination_code
		dataType: string
		lineageTag: ab1af799-f5d4-4220-a2f7-5895654781e1
		summarizeBy: none
		sourceColumn: discharge_destination_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = discharge_destination_code

		annotation PBI_WasHiddenAtRefresh = False

	column discharge_follow_up_code
		dataType: string
		lineageTag: a13360c5-16ca-4f81-ba3f-bf7c2047c204
		summarizeBy: none
		sourceColumn: discharge_follow_up_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = discharge_follow_up_code

		annotation PBI_WasHiddenAtRefresh = False

	column admitted_flag
		dataType: int64
		formatString: 0
		lineageTag: 1d979f85-6446-4ea4-9c5a-80ab29e77955
		summarizeBy: sum
		sourceColumn: admitted_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = admitted_flag

		annotation PBI_WasHiddenAtRefresh = False

	column gender
		dataType: string
		lineageTag: f532d60f-6ac2-47c2-b75f-37ee59f2637f
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = gender

		annotation PBI_WasHiddenAtRefresh = False

	column injury_mechanism_code
		dataType: string
		lineageTag: 3a2c6ab2-da6b-4cf4-8917-6ce244053023
		summarizeBy: none
		sourceColumn: injury_mechanism_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_mechanism_code

		annotation PBI_WasHiddenAtRefresh = False

	column injury_mechanism
		dataType: string
		lineageTag: 2d1da981-9988-44b3-a662-175cd3221725
		summarizeBy: none
		sourceColumn: injury_mechanism

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_mechanism

		annotation PBI_WasHiddenAtRefresh = False

	column injury_intent_code
		dataType: string
		lineageTag: 7d2c3699-6a9d-432b-b28c-2b475caf2c99
		summarizeBy: none
		sourceColumn: injury_intent_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_intent_code

		annotation PBI_WasHiddenAtRefresh = False

	column injury_intent
		dataType: string
		lineageTag: 32739fa4-97a2-4e9b-8d23-405fa37616c8
		summarizeBy: none
		sourceColumn: injury_intent

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_intent

		annotation PBI_WasHiddenAtRefresh = False

	column injury_place
		dataType: string
		lineageTag: 2789f92e-4f6e-469e-9714-87a61d2b2b93
		summarizeBy: none
		sourceColumn: injury_place

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_place

		annotation PBI_WasHiddenAtRefresh = False

	column injury_place_code
		dataType: string
		lineageTag: 65092f3b-2055-4d94-ab88-fbbba42ec55b
		summarizeBy: none
		sourceColumn: injury_place_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_place_code

		annotation PBI_WasHiddenAtRefresh = False

	column injury_activity_type_code
		dataType: string
		lineageTag: d2315535-1659-46d8-88f7-5a24df509b73
		summarizeBy: none
		sourceColumn: injury_activity_type_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_activity_type_code

		annotation PBI_WasHiddenAtRefresh = False

	column injury_activity_type
		dataType: string
		lineageTag: b4d5d990-f3d0-4c96-91aa-6493a40be17a
		summarizeBy: none
		sourceColumn: injury_activity_type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = injury_activity_type

		annotation PBI_WasHiddenAtRefresh = False

	column referred_service_code
		dataType: string
		lineageTag: 42775655-6924-40d5-90bc-c5dce1299874
		summarizeBy: none
		sourceColumn: referred_service_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = referred_service_code

		annotation PBI_WasHiddenAtRefresh = False

	column referred_service
		dataType: string
		lineageTag: f0200ff3-2cb4-48c7-b985-e47a449cfe69
		summarizeBy: none
		sourceColumn: referred_service

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = referred_service

		annotation PBI_WasHiddenAtRefresh = False

	partition ed_attendances-7b0d53cd-4e71-485c-b9bf-5655f185b9a3 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_current", [Query="select * from [PowerBI_Reporting].[dbo].[ECDS_ED_Attendances]#(lf)where [age_at_activity_date] >= '65'#(lf)and [efi_category] in ('Mild Frailty','Moderate Frailty','Severe Frailty')"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"dementia_flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

