table frail_population_over_time
	lineageTag: 7a034835-3a8e-4819-ae76-e66afe16be88

	measure mildly_frail_per_1000_ot = CALCULATE((SUM('frail_population_over_time'[Mild_Frailty]))/(SUM(locality_populations[total_65+_population]))*1000)
		formatString: 0.0
		lineageTag: b01d91a7-0810-4889-a1e6-10b7ea7708f3

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_per_1000_ot = CALCULATE((SUM('frail_population_over_time'[Moderate_Frailty]))/(SUM(locality_populations[total_65+_population]))*1000)
		formatString: 0.0
		lineageTag: bbe7627b-3235-40b7-ba67-8768403db7ce

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_per_1000_ot = CALCULATE((SUM('frail_population_over_time'[Severe_Frailty]))/(SUM(locality_populations[total_65+_population]))*1000)
		formatString: 0.0
		lineageTag: 5a8d0b89-b138-4237-9864-00f0e29fb865

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_2019/20 = CALCULATE(SUM('frail_population_over_time'[Mild_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2020,03,01)))
		formatString: 0
		lineageTag: 9161552f-0080-4319-9574-eec85f596259

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" />

	measure total_frail_population_ot = SUM(frail_population_over_time[Mild_Frailty])+SUM(frail_population_over_time[Moderate_Frailty])+SUM(frail_population_over_time[Severe_Frailty])
		formatString: 0
		lineageTag: dedb88f8-473e-4068-8b3c-e5f60102e4d9

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure moderately_frail_2019/20 = CALCULATE(SUM('frail_population_over_time'[Moderate_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2020,03,01)))
		formatString: 0
		lineageTag: 42036734-c61a-4b50-a081-2ef4e4e19cad

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure severely_frail_2019/20 = CALCULATE(SUM('frail_population_over_time'[Severe_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2020,03,01)))
		formatString: 0
		lineageTag: 05d22181-3e9c-4eb3-8836-8ce191b1c819

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure mildly_frail_2022/23 = CALCULATE(SUM('frail_population_over_time'[Mild_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2023,01,01)))
		formatString: 0
		lineageTag: edcffa2c-3752-4703-b455-9f4a5899c402

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" />

	measure moderately_frail_2022/23 = CALCULATE(SUM('frail_population_over_time'[Moderate_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2023,01,01)))
		formatString: 0
		lineageTag: ee391bed-e936-44d5-9431-d2cd20931702

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure severely_frail_2022/23 = CALCULATE(SUM('frail_population_over_time'[Severe_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2023,01,01)))
		formatString: 0
		lineageTag: 36a5aea2-4807-496f-b854-bf065f5e7632

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure mildly_frail_2020/21 = CALCULATE(SUM('frail_population_over_time'[Mild_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2021,03,01)))
		formatString: 0
		lineageTag: 2b9ef300-c527-4f91-bc25-f9465ee3f52a

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" />

	measure moderately_frail_2020/21 = CALCULATE(SUM('frail_population_over_time'[Moderate_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2021,03,01)))
		formatString: 0
		lineageTag: 0ad5ab05-bb9c-4444-9634-351ac6b8fc4c

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure severely_frail_2020/21 = CALCULATE(SUM('frail_population_over_time'[Severe_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2021,03,01)))
		formatString: 0
		lineageTag: 7febba0f-0d57-44dd-aef1-416721927dc1

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure mildly_frail_2021/22 = CALCULATE(SUM('frail_population_over_time'[Mild_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2022,03,01)))
		formatString: 0
		lineageTag: a79b86f3-15cb-4c08-8dc3-e54b614800fd

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" />

	measure moderately_frail_2021/22 = CALCULATE(SUM('frail_population_over_time'[Moderate_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2022,03,01)))
		formatString: 0
		lineageTag: dc70862a-dbe9-4e74-9270-f33d45aaec4f

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure severely_frail_2021/22 = CALCULATE(SUM('frail_population_over_time'[Severe_Frailty]),FILTER('frail_population_over_time','frail_population_over_time'[Census_Date] = DATE(2022,03,01)))
		formatString: 0
		lineageTag: c8f76196-ae92-44b9-bf6d-f227deac801d

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure mild_frailty_py = ```
			CALCULATE(SUM(frail_population_over_time[Mild_Frailty]), SAMEPERIODLASTYEAR(date_table[date]))  
			```
		formatString: 0
		lineageTag: 4132e508-b051-4614-a350-75d24acc8c5b

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure mild_frailty_%_growth = DIVIDE(SUM(frail_population_over_time[Mild_Frailty]) - [mild_frailty_py], [mild_frailty_py])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9de1b8c4-e4e8-44b7-a32b-32e5308a9cba

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure moderate_frailty_py = ```
			CALCULATE(SUM(frail_population_over_time[Moderate_Frailty]), SAMEPERIODLASTYEAR(date_table[date]))  
			```
		formatString: 0
		lineageTag: 48805427-1dee-426a-89ff-6d13b7664769

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure severe_frailty_py = ```
			CALCULATE(SUM(frail_population_over_time[Severe_Frailty]), SAMEPERIODLASTYEAR(date_table[date]))  
			```
		formatString: 0
		lineageTag: 59e9b1ae-ef0b-43f8-bb5f-16dbdea7a304

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure moderate_frailty_%_growth = DIVIDE(SUM(frail_population_over_time[Moderate_Frailty]) - [moderate_frailty_py], [moderate_frailty_py])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b0c82307-1886-40a3-933a-c03e074a45a7

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure severe_frailty_%_growth = DIVIDE(SUM(frail_population_over_time[Severe_Frailty]) - [severe_frailty_py], [severe_frailty_py])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 11fb1ffb-36a5-444a-8d2f-efe67515b6d8

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure mildly_frail_per_1000_19/20 = CALCULATE([mildly_frail_2019/20])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: 8bf9b0ca-beaa-4603-b5ad-b4b6eda898f4

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_per_1000_20/21 = CALCULATE([mildly_frail_2020/21])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: cc9ff0de-85db-4032-b650-70e8a74305c4

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_per_1000_21/22 = CALCULATE([mildly_frail_2021/22])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: 4192471a-dc6b-4ee2-bc66-407f2d2670e5

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mildly_frail_per_1000_22/23 = CALCULATE([mildly_frail_2022/23])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: b025d641-c05e-48a2-8aba-bb6212ca1b1c

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_per_1000_19/20 = CALCULATE([moderately_frail_2019/20])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: 67399348-6382-4e83-a43e-712f4de039c9

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_per_1000_20/21 = CALCULATE([moderately_frail_2020/21])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: 412775ba-ac09-4cb8-a5be-0945ce31b71d

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_per_1000_21/22 = CALCULATE([moderately_frail_2021/22])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: 32e3a035-15b3-4937-8461-a8b71607bbb7

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure moderately_frail_per_1000_22/23 = CALCULATE([moderately_frail_2022/23])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: b3f92168-a04c-4080-820b-e1a7245427d7

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_per_1000_19/20 = CALCULATE([severely_frail_2019/20])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: 6c9374bb-da9d-42d8-b4bf-c9b1feef6812

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_per_1000_20/21 = CALCULATE([severely_frail_2020/21])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: b0de58dc-b121-41f9-922e-721d9ba92e41

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_per_1000_21/22 = CALCULATE([severely_frail_2021/22])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: dc48a6b8-bd4b-4ee2-a4e5-5fb923331f34

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure severely_frail_per_1000_22/23 = CALCULATE([severely_frail_2022/23])/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: 526b19eb-242a-450f-b71c-266498df501c

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	measure mild_frailty_variance = SUM(frail_population_over_time[Mild_Frailty]) - [mild_frailty_py]
		formatString: 0
		lineageTag: 1f03f91f-c7e5-4a09-bbff-155fafac031e

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure mild_frailty_pm = SUM(frail_population_over_time[Mild_Frailty])-CALCULATE(SUM(frail_population_over_time[Mild_Frailty]),PREVIOUSMONTH(date_table[date]))
		formatString: 0
		lineageTag: ecd63c47-5f8c-4d51-9c70-89fd75be8bf5

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure moderate_frailty_pm = SUM(frail_population_over_time[Moderate_Frailty])-CALCULATE(SUM(frail_population_over_time[Moderate_Frailty]),PREVIOUSMONTH(date_table[date]))
		formatString: 0
		lineageTag: 4b8af8db-50b0-41d9-9795-afc38195e92a

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure severe_frailty_pm = SUM(frail_population_over_time[Severe_Frailty])-CALCULATE(SUM(frail_population_over_time[Severe_Frailty]),PREVIOUSMONTH(date_table[date]))
		formatString: 0
		lineageTag: b6a7c713-fc2a-4c7e-89ac-138840c45ec9

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure total_frail_per_1000_ot = [total_frail_population_ot]/(SUM(locality_populations[total_65+_population]))*1000
		formatString: 0.0
		lineageTag: a56cc2ed-29e5-4992-9ba1-30a9a3201d01

		annotation Format = <Format Format="NumberDecimal" Accuracy="1" />

	column Census_Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a4513e80-147a-4488-8418-d0c1c84cac6e
		summarizeBy: none
		sourceColumn: Census_Date

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = DateTime#####Date

		annotation PBI_NameAtRefresh = Census_Date

		annotation PBI_WasHiddenAtRefresh = False

		annotation UnderlyingDateTimeDataType = Date

		annotation Format = <Format Format="DateTimeCustom"><DateTimes><DateTime LCID="2057" Group="ShortDate" FormatString="dd/MM/yyyy" /></DateTimes></Format>

	column Mild_Frailty
		dataType: int64
		formatString: 0
		lineageTag: f626e31f-2c18-479e-8286-8ac5a41677ec
		summarizeBy: sum
		sourceColumn: Mild_Frailty

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Mild_Frailty

		annotation PBI_WasHiddenAtRefresh = False

	column Moderate_Frailty
		dataType: int64
		formatString: 0
		lineageTag: bb9d8955-498b-4615-a920-a7fbf2115440
		summarizeBy: sum
		sourceColumn: Moderate_Frailty

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Moderate_Frailty

		annotation PBI_WasHiddenAtRefresh = False

	column Severe_Frailty
		dataType: int64
		formatString: 0
		lineageTag: 1163ff80-2b05-4c55-a395-e802cdd82e28
		summarizeBy: sum
		sourceColumn: Severe_Frailty

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Severe_Frailty

		annotation PBI_WasHiddenAtRefresh = False

	partition frail_population_over_time-4720155e-9d2e-499b-a4e5-e20df041bbe0 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select * from [PowerBI_Reporting].[dbo].[Frail_Population_Over_Time]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Census_Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

