table Extract
	lineageTag: 65e6a800-13ad-4bde-93c9-44dadac2a5c0

	measure TotalAntibiotics = Sum('Extract'[AntibioticAndTreatment])+Sum('Extract'[AntibioticNoTreatment])
		lineageTag: 572d8184-194f-4bec-8615-10fa2029e7d7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Antibiotics %' = [TotalAntibiotics]/sum('Extract'[AppointmentsBooked])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 963db6e7-b5fa-4fca-8af2-216af60e96e4

	measure 'Antibiotics % Last Year' = CALCULATE([Antibiotics %], SAMEPERIODLASTYEAR('Extract'[ReportingMonth]))
		lineageTag: c6e6ecc6-6980-41b0-9681-2267701a173d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Antibiotics % Latest Month' =
			
			VAR latestmonth = MONTH(MAX('Extract'[ReportingMonth]) )
			RETURN
			CALCULATE([Antibiotics %], FILTER('Extract', MONTH('Extract'[ReportingMonth]) = latestmonth ))
		lineageTag: 2d862274-d9cc-4f27-bc54-d0223fd7d2a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Antibiotics % Prev Month' = CALCULATE([Antibiotics %], DATEADD('Extract'[ReportingMonth], -1, MONTH) )
		lineageTag: 8978b9f8-951f-454a-a393-7d58320d449f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Extractions %'
		lineageTag: de859f59-fc7b-4ad7-8f01-c32da2597f64

	column ReportingMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 25ff5074-846d-4ea8-8c56-035d34927af3
		summarizeBy: none
		sourceColumn: ReportingMonth

		variation Variation
			isDefault
			relationship: 7ade4458-6bca-4b96-80cd-1aec71411bca
			defaultHierarchy: LocalDateTable_3cfade66-8cac-40d5-8252-204d56a97d8f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ProviderName
		dataType: string
		lineageTag: 85808ebd-e6f8-4910-b309-b9b8806e18c0
		summarizeBy: none
		sourceColumn: ProviderName

		annotation SummarizationSetBy = Automatic

	column AppointmentsAvailable
		dataType: int64
		lineageTag: d8fb5047-5c3f-4e30-a55f-480a36aa87bc
		summarizeBy: sum
		sourceColumn: AppointmentsAvailable

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AppointmentsBooked
		dataType: int64
		lineageTag: 235d9088-3022-4241-a2d8-d6d0c570c525
		summarizeBy: sum
		sourceColumn: AppointmentsBooked

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AppointmentsUnbooked
		dataType: int64
		lineageTag: d0173b03-c035-433b-b8eb-4f8fff944ed2
		summarizeBy: sum
		sourceColumn: AppointmentsUnbooked

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AppointmentsDNA
		dataType: int64
		lineageTag: abe91a75-cc68-4f57-971c-e0ed2137d99d
		summarizeBy: sum
		sourceColumn: AppointmentsDNA

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PatientsSeen
		dataType: double
		lineageTag: 8796d7e9-f775-4b5e-b176-d4f3b2321e66
		summarizeBy: sum
		sourceColumn: PatientsSeen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 0-17
		dataType: int64
		lineageTag: bee68036-fe98-4bec-a03c-c347af67ca7a
		summarizeBy: sum
		sourceColumn: 0-17

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 18-24
		dataType: int64
		lineageTag: 8491acb8-ecbd-4912-a516-e4702d70e6b5
		summarizeBy: sum
		sourceColumn: 18-24

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '25- 34'
		dataType: int64
		lineageTag: 8d11d8b3-1b48-4a6e-8970-45bfd64b2a99
		summarizeBy: sum
		sourceColumn: 25- 34

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 35-44
		dataType: int64
		lineageTag: 91350352-a21f-4e69-8009-2bab5e3abcbb
		summarizeBy: sum
		sourceColumn: 35-44

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 45-54
		dataType: int64
		lineageTag: 1f0956fd-3234-4745-87f8-91a58c75111e
		summarizeBy: sum
		sourceColumn: 45-54

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 55-64
		dataType: int64
		lineageTag: 7cd940d2-90c7-4087-b3d9-a97841b8c72a
		summarizeBy: sum
		sourceColumn: 55-64

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 65+
		dataType: int64
		lineageTag: 1c5f3380-4857-4077-9e73-96f03e74a92b
		summarizeBy: sum
		sourceColumn: 65+

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unknown
		dataType: double
		lineageTag: f2e35b02-ba40-4bd0-81dd-1e27e53e716c
		summarizeBy: sum
		sourceColumn: Unknown

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CompletedTreatments
		dataType: double
		lineageTag: 62046014-7a95-4963-9362-3ac9b5d85b17
		summarizeBy: sum
		sourceColumn: CompletedTreatments

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Extractions
		dataType: int64
		lineageTag: d1b95091-4f46-4d8e-bb07-352038b92d2a
		summarizeBy: sum
		sourceColumn: Extractions

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Openanddress/extripation
		dataType: int64
		lineageTag: fd0482e4-fcbf-461d-afd1-8169d737cab9
		summarizeBy: sum
		sourceColumn: Openanddress/extripation

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fillings
		dataType: int64
		lineageTag: dc2bd893-877d-4a3c-a522-c132847d9d4c
		summarizeBy: sum
		sourceColumn: Fillings

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Irrigation
		dataType: int64
		lineageTag: b2990e51-408c-4384-97cc-67657ea491f1
		summarizeBy: sum
		sourceColumn: Irrigation

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AssesmentandAdviceOnly
		dataType: double
		lineageTag: 3c5ac7a0-91bc-4090-a517-f250b0dde406
		summarizeBy: sum
		sourceColumn: AssesmentandAdviceOnly

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OtherTreatmentGiven
		dataType: double
		lineageTag: 1a05c804-63f1-4a90-95b3-74c2bdc5a16b
		summarizeBy: sum
		sourceColumn: OtherTreatmentGiven

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AntibioticAndTreatment
		dataType: double
		lineageTag: 37970c75-79a0-4b17-99c2-cd893b8afa8b
		summarizeBy: sum
		sourceColumn: AntibioticAndTreatment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AntibioticNoTreatment
		dataType: double
		lineageTag: b5fa7228-3add-48f6-818f-69ecd83c38a4
		summarizeBy: sum
		sourceColumn: AntibioticNoTreatment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NoFollowUpRequired
		dataType: double
		lineageTag: 30c50d87-872c-4221-b388-046e027cf0ed
		summarizeBy: sum
		sourceColumn: NoFollowUpRequired

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OnwardSecondaryCareReferral
		dataType: double
		lineageTag: ebe14fb4-816d-464f-a24d-a2b52abc9d94
		summarizeBy: sum
		sourceColumn: OnwardSecondaryCareReferral

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OnwardStabilisationReferral
		dataType: double
		lineageTag: 97928583-9d8e-40bd-99e0-5a677fb9c998
		summarizeBy: sum
		sourceColumn: OnwardStabilisationReferral

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OtherFollowUp
		dataType: double
		lineageTag: 63012af3-c525-47f9-850a-a7a648ffe1b6
		summarizeBy: sum
		sourceColumn: OtherFollowUp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OtherFollowUpDesc
		dataType: string
		lineageTag: 1db97bb6-9080-45ca-8657-7cf4b670a67d
		summarizeBy: none
		sourceColumn: OtherFollowUpDesc

		annotation SummarizationSetBy = Automatic

	column SubmittedBy
		dataType: string
		lineageTag: 016f4db6-2040-45a9-b099-66c9e7d25391
		summarizeBy: none
		sourceColumn: SubmittedBy

		annotation SummarizationSetBy = Automatic

	column SubmissionDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7bd6e597-2fe4-460e-a906-b5235733a505
		summarizeBy: none
		sourceColumn: SubmissionDate

		variation Variation
			isDefault
			relationship: ac216a18-67ea-4844-9774-c6b2df90cbc9
			defaultHierarchy: LocalDateTable_8c92a796-0372-49f9-b362-58477d75006a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 2f60c4b4-0fdc-4b55-ab72-8f598b34334f
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: FinancialMonth

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: d8507fe9-c1f4-47ef-af27-6cb1948289ee
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 3a906b05-98da-44f4-a94f-2ba00ee43bc2
		summarizeBy: sum
		sourceColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

	column 'Contract Number'
		dataType: double
		lineageTag: 8e9e3407-7031-42bc-9fe2-0a5847c751f4
		summarizeBy: sum
		sourceColumn: Contract Number

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Provider Number'
		dataType: string
		lineageTag: e6092612-547e-4e1f-b515-b63dce2b94d8
		summarizeBy: none
		sourceColumn: Provider Number

		annotation SummarizationSetBy = Automatic

	partition Extract = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "bireports", [Query="SELECT [UDC].*,#(lf)[Month] = LEFT([D].[MonthName],3),#(lf)[FinancialYear] = [D].[FinancialYear],#(lf)[FinancialMonth] = [D].[FinancialMonth]#(lf)FROM [BIReports].[dbo].[UrgentDentalCare] [UDC]#(lf)#(lf)#(tab)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] AS [D]#(lf)#(tab)ON [D].[Date] = CAST([UDC].[ReportingMonth] AS DATE)#(lf)"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"AntibioticPrescriptionIssuesFurtherTreatmentGiven", "AntibioticAndTreatment"}, {"AntibioticPrescriptionIssuesNoOtherTreatmentGiven", "AntibioticNoTreatment"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"FinancialMonth", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Provider Number", each if Text.Contains([ProviderName], "Bupa") then "Provider 1" else if Text.Contains([ProviderName], "Genix") then "Provider 3" else if Text.Contains([ProviderName], "Central") then "Provider 2" else if Text.Contains([ProviderName], "Tuffley") then "Provider 4" else "Not Recorded")
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

