table 'Date Reference'
	lineageTag: 2168406e-611d-434b-a269-4f386ff8b8ce

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 88cad601-e750-4664-9501-9b7bbfc01a6f
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6e513163-5e5b-44f6-a514-8deeaa55d134
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: de026a36-a638-43a6-9f37-52a0b695d3a1
			defaultHierarchy: LocalDateTable_1aa271a0-e9ba-4da7-a1a8-6892c674eb2c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column DayMonthYear
		dataType: string
		lineageTag: f97dd007-6bab-434f-8870-5ff881690391
		summarizeBy: none
		sourceColumn: DayMonthYear

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 0a54e64c-91a5-4c54-8087-08b874a1a7c6
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DaySuffix
		dataType: string
		lineageTag: d3d7cd01-2e06-4b14-8c45-712800df036f
		summarizeBy: none
		sourceColumn: DaySuffix

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: int64
		formatString: 0
		lineageTag: 707b816f-9900-4f42-ad1e-89c2ccda43f2
		summarizeBy: sum
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column WeekDayName
		dataType: string
		lineageTag: 0c1f3aec-5e33-4302-9d35-abf5954999d6
		summarizeBy: none
		sourceColumn: WeekDayName

		annotation SummarizationSetBy = Automatic

	column DayofWeekInMonth
		dataType: int64
		formatString: 0
		lineageTag: 69f108ff-3345-4567-99eb-1c765cc0e303
		summarizeBy: sum
		sourceColumn: DayofWeekInMonth

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: d88d6eed-da4d-43c4-a857-073c227cfdca
		summarizeBy: sum
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: f2b9240c-e894-430a-b715-6e653f541cf3
		summarizeBy: sum
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: 5786a6f3-44c5-4d09-bc99-6d7b5c03554b
		summarizeBy: sum
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 6f539b6f-5206-4374-9885-be7b218a3fb3
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 03031116-25d1-402c-ae8c-750d469d564a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: 'Sort Financial Year'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 1c01062a-e0a9-4af7-9df3-4942514d4b79
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterName
		dataType: string
		lineageTag: e0b34d3f-78a4-481a-adcf-012acdda0a95
		summarizeBy: none
		sourceColumn: QuarterName

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 438a7a47-f57c-4168-ba16-0db815a1fe8c
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		lineageTag: 56a39f71-d549-424c-965d-51f6287e6124
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

	column MonthYearName
		dataType: string
		lineageTag: 75842428-3d2c-460c-be01-2bac8f86dfb3
		summarizeBy: none
		sourceColumn: MonthYearName

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: string
		lineageTag: eb1d00e5-6bc6-4608-bebc-5489b3634a0b
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5805fb25-9ba2-4779-96ef-ee7a072b106a
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 680b19f1-4dad-473c-9d7f-f2c86b29dcb6
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FinancialWeekofYear
		dataType: int64
		formatString: 0
		lineageTag: 81c26f3f-594c-48cb-bd79-6cc84f1b2863
		summarizeBy: sum
		sourceColumn: FinancialWeekofYear

		annotation SummarizationSetBy = Automatic

	column HolidayName
		dataType: string
		lineageTag: 7d507977-5c84-493f-b454-cbbdf29a58b9
		summarizeBy: none
		sourceColumn: HolidayName

		annotation SummarizationSetBy = Automatic

	column SpecialDays
		dataType: string
		lineageTag: 67887d09-ec1c-4d47-912c-b673d4499543
		summarizeBy: none
		sourceColumn: SpecialDays

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: 9387792b-df8f-4520-af13-ad85c4a0bf34
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column FinancialQuarter
		dataType: int64
		formatString: 0
		lineageTag: f81852f9-1e61-460b-9d24-5e97197e6ef2
		summarizeBy: sum
		sourceColumn: FinancialQuarter

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: string
		lineageTag: 9f632526-b87e-45cf-90de-4ef63cadbe63
		summarizeBy: none
		sourceColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

	column FirstDateofYear
		dataType: dateTime
		formatString: General Date
		lineageTag: 1da1a4c6-3191-47ca-a88c-5ff09ac4720c
		summarizeBy: none
		sourceColumn: FirstDateofYear

		variation Variation
			isDefault
			relationship: ca0db5c1-7744-4e05-9009-cdb4e9463369
			defaultHierarchy: LocalDateTable_440be35e-4a04-461f-9f3f-ea24988c7279.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofYear
		dataType: dateTime
		formatString: General Date
		lineageTag: cb522b7c-de40-4cb4-be53-a36261f845d8
		summarizeBy: none
		sourceColumn: LastDateofYear

		variation Variation
			isDefault
			relationship: c8038ae0-3a0d-4b87-93f0-2d353970dca3
			defaultHierarchy: LocalDateTable_74436204-187f-4b16-bd9c-44ed2ed44336.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FirstDateofQuater
		dataType: dateTime
		formatString: General Date
		lineageTag: 02488c54-dd1f-44b1-b633-9e337b2fbe6b
		summarizeBy: none
		sourceColumn: FirstDateofQuater

		variation Variation
			isDefault
			relationship: 444bdb79-b5b5-4169-a0f3-02911a22687b
			defaultHierarchy: LocalDateTable_a1e522a9-a2fb-47c0-8aab-18b63332287c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofQuater
		dataType: dateTime
		formatString: General Date
		lineageTag: 10556130-01e6-46bc-81ff-a3d23ae6c72a
		summarizeBy: none
		sourceColumn: LastDateofQuater

		variation Variation
			isDefault
			relationship: 3b17a1a9-a283-4f5b-ab09-b6c377016874
			defaultHierarchy: LocalDateTable_06d435b6-2f76-423a-b538-a55aa348d5c6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FirstDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: eddf2cf4-4639-447e-852a-2adf0207faec
		summarizeBy: none
		sourceColumn: FirstDateofMonth

		variation Variation
			isDefault
			relationship: f9e95158-a58d-46d3-b09d-7d6e109a72d5
			defaultHierarchy: LocalDateTable_fc0af65f-33c5-43c7-a1d9-2579b85d79dd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 89ba1463-b816-4af2-943a-28a702b56633
		summarizeBy: none
		sourceColumn: LastDateofMonth

		variation Variation
			isDefault
			relationship: c69698c4-511d-4087-a5fa-b1ea99018c4b
			defaultHierarchy: LocalDateTable_d8d40849-801f-41af-a1d8-938df9fbfd22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FirstDateofWeek
		dataType: dateTime
		formatString: General Date
		lineageTag: 222e0d88-4a9e-494e-be47-93d3d0e0ae64
		summarizeBy: none
		sourceColumn: FirstDateofWeek

		variation Variation
			isDefault
			relationship: 93a78e2e-2d92-41d7-8197-dcdbde8ed6d3
			defaultHierarchy: LocalDateTable_28f45c38-c9c5-4f3d-a0be-38a55d0eb30c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastDateofWeek
		dataType: dateTime
		formatString: General Date
		lineageTag: c87a942a-c352-4142-b9ce-39617ce4a44d
		summarizeBy: none
		sourceColumn: LastDateofWeek

		variation Variation
			isDefault
			relationship: d65dc66a-f233-46f6-9c68-bbad59d250d4
			defaultHierarchy: LocalDateTable_27d27195-2132-411f-a1c2-532b0654feb7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column WeekBand
		dataType: string
		lineageTag: 2030a758-9b01-48bc-b3af-55f08a184e70
		summarizeBy: none
		sourceColumn: WeekBand

		annotation SummarizationSetBy = Automatic

	column CurrentYear
		dataType: int64
		formatString: 0
		lineageTag: 92ab2e77-9df7-464c-8051-4ea26f0b1426
		summarizeBy: sum
		sourceColumn: CurrentYear

		annotation SummarizationSetBy = Automatic

	column CurrentQuater
		dataType: int64
		formatString: 0
		lineageTag: a4cc856c-bb4a-4071-9df7-6d4e07e81998
		summarizeBy: sum
		sourceColumn: CurrentQuater

		annotation SummarizationSetBy = Automatic

	column CurrentMonth
		dataType: int64
		formatString: 0
		lineageTag: 612125cc-e1b8-461b-8e17-e70d1c32db29
		summarizeBy: sum
		sourceColumn: CurrentMonth

		annotation SummarizationSetBy = Automatic

	column CurrentWeek
		dataType: int64
		formatString: 0
		lineageTag: 5ff19953-0751-469b-bf68-1c01fb22e793
		summarizeBy: sum
		sourceColumn: CurrentWeek

		annotation SummarizationSetBy = Automatic

	column CurrentDay
		dataType: int64
		formatString: 0
		lineageTag: aac139d2-8ac7-4c49-95e0-8478948a01f1
		summarizeBy: sum
		sourceColumn: CurrentDay

		annotation SummarizationSetBy = Automatic

	column 'Sort Financial Year' = ```
			
			 var _month = month('Date Reference'[Date])
			 var _result = IF(_month > 3, _month-3, _month+9)
			 return
			 _result
			
			```
		formatString: 0
		lineageTag: 93ccf73b-81af-4914-a6a0-4084fa5c1188
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'FinancialYear Hierarchy'
		lineageTag: e54d4ced-cdb8-4359-af3d-9ab2c612cd82

		level 'Financial Year'
			lineageTag: 45e1cf55-a89e-450a-b2c5-ba21454f6192
			column: 'Financial Year'

		level MonthName
			lineageTag: ccc63c0f-d3c0-494e-8414-066c7e90b179
			column: MonthName

	partition 'Date Reference' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="select * from [CCG_Reference].[Reference].[vw_DateLookup]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"FinancialYear", "Financial Year"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

