table RTT
	lineageTag: 59985f39-8fef-4b1d-b66c-6a4046e1e566

	measure '< 18 Weeks %' =
			
			DIVIDE(SUM('RTT'[0-18 Weeks]), SUM('RTT'[Total]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 538acb42-e897-4e48-8a6a-6f55286a7c0e

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure '> 18 Weeks %' =
			
			DIVIDE(SUM('RTT'[> 18 Weeks]), SUM('RTT'[Total]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f489ee7b-5306-4b18-a952-5eedd182b625

	measure '> 35 Weeks %' =
			
			DIVIDE(SUM('RTT'[> 35 Weeks]), SUM('RTT'[Total]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 04e8e34a-954f-4a73-a068-e6564f40ca1a

	measure '> 52 Weeks %' =
			
			DIVIDE(SUM('RTT'[> 52 Weeks]), SUM('RTT'[Total]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 958230f4-7b31-49b6-9ddf-ae58bb7ccdc6

	measure '> 65 Weeks %' =
			
			DIVIDE(SUM('RTT'[> 65 Weeks]), SUM('RTT'[Total]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 3b7a9a39-a378-4bb2-901b-117e59d961fb

	measure '> 78 Weeks %' =
			
			DIVIDE(SUM('RTT'[> 78 Weeks]), SUM('RTT'[Total]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 84181492-0707-4324-bf62-08d52828f331

	measure '> 104 Weeks %' =
			
			DIVIDE(SUM('RTT'[> 104 Weeks]), SUM('RTT'[Total]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 17f49927-c906-48c1-9563-28d3ff2aaeeb

	measure 'Previous Month Total RTT Waiting List' = CALCULATE('RTT'[Total RTT Waiting List], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: #,0
		lineageTag: e6fbdf64-ff11-4fec-883e-9bcc71118b5e

	measure 'Total RTT Waiting List' = CALCULATE(sum('RTT'[Total]))
		formatString: #,0
		lineageTag: 7c124b64-5431-4ec1-80ce-c87cd3c95af1

	measure 'Total RTT Waiting List Variance' = CALCULATE([Total RTT Waiting List]-[Previous Month Total RTT Waiting List])
		lineageTag: 5b4430ed-ed34-4d59-8f32-8ac31d35c779

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No. 18+ Weeks' = CALCULATE(sum(RTT[> 18 Weeks]))
		formatString: #,0
		lineageTag: 39c1747f-0947-456a-b729-e672c5754e48

	measure 'No. 35+ Weeks' = CALCULATE(sum(RTT[> 35 Weeks]))
		formatString: #,0
		lineageTag: 72f1f452-6c5c-4bbf-8df8-9e66502333a4

	measure 'No. 52+ Weeks' = CALCULATE(sum(RTT[> 52 Weeks]))
		formatString: #,0
		lineageTag: 82c3a9d1-74b7-4fe2-beac-e538b30d3798

	measure 'No. 78+ Weeks' = CALCULATE(sum(RTT[> 78 Weeks]))
		formatString: #,0
		lineageTag: fa7542c2-80f8-49be-9741-e2fc04abbb3e

	measure 'Previous Month No. 18+ Weeks' = CALCULATE('RTT'[No. 18+ Weeks], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: #,0
		lineageTag: 89b99000-0d94-456f-af63-8a277ed19ca0

	measure 'No. 18+ Weeks Variance' = CALCULATE(RTT[No. 18+ Weeks]-RTT[Previous Month No. 18+ Weeks])
		formatString: #,0
		lineageTag: 21f320e8-40bf-45ac-9476-96b8f98ac515

	measure 'Previous Month No. 35+ Weeks' = CALCULATE('RTT'[No. 35+ Weeks], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: #,0
		lineageTag: 4ef02f75-50fd-4c31-934d-baca4e62857a

	measure 'No. 35+ Weeks Variance' = CALCULATE([No. 35+ Weeks]-[Previous Month No. 35+ Weeks])
		formatString: #,0
		lineageTag: b96360db-329d-455f-a072-3bccaf5079f3

	measure 'No 104+ Weeks' = CALCULATE(sum(RTT[> 104 Weeks]))
		formatString: #,0
		lineageTag: e1934168-76e8-4327-b063-430c47b0b94d

	measure 'Previous Month No. 52+ Weeks' = CALCULATE('RTT'[No. 52+ Weeks], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: #,0
		lineageTag: aa0fbb75-522a-4822-b8c4-84b73c9cb73d

	measure 'No. 52+ Weeks Variance' = CALCULATE([No. 52+ Weeks]-[Previous Month No. 52+ Weeks])
		formatString: #,0
		lineageTag: 54a5c573-d81b-4912-9c3c-fd4ddcc9fbdb

	measure 'Previous Month No. 78+ Weeks' = CALCULATE('RTT'[No. 78+ Weeks], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: #,0
		lineageTag: 2ef0d222-f4e5-4d65-81a3-9ae67977f485

	measure 'No. 78+ Weeks Variance' = CALCULATE(RTT[No. 78+ Weeks]-RTT[Previous Month No. 78+ Weeks])
		formatString: #,0
		lineageTag: ff33511b-8acf-42f0-81ae-b2ddec96ee55

	measure 'Previous Month No. 104+ Weeks' = CALCULATE('RTT'[No 104+ Weeks], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: #,0
		lineageTag: e2e57567-0157-4a88-bb83-b040957e9c14

	measure 'No. 104+ Weeks Variance' = CALCULATE([No 104+ Weeks]-[Previous Month No. 104+ Weeks])
		formatString: #,0
		lineageTag: eb26f44b-d328-4890-9236-de06b1fd5c73

	measure 'Previous Month > 18 Weeks %' = CALCULATE('RTT'[> 18 Weeks %], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7a86cf9e-1a05-44d9-b473-0398e923bdd6

	measure '% > 18 Weeks Variance' = CALCULATE('RTT'[> 18 Weeks %]-'RTT'[Previous Month > 18 Weeks %])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 31c885aa-08c9-4002-8367-70c6005e61e9

	measure 'Previous Month > 35 Weeks %' = CALCULATE('RTT'[> 35 Weeks %], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: af84a91a-3403-44e0-bc56-dc91a828a760

	measure '% > 35 Weeks Variance' = CALCULATE([> 35 Weeks %]-[Previous Month > 35 Weeks %])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 205a8663-2fa1-4aa1-98e5-43129d0064b2

	measure 'Previous Month > 52 Weeks %' = CALCULATE('RTT'[> 52 Weeks %], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5efcc374-ea6c-4226-ba40-ef010b2492c1

	measure '% > 52 Weeks Variance' = CALCULATE([> 52 Weeks %]-[Previous Month > 52 Weeks %])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a1e9c048-9c3d-4afe-be7d-547bb0cb51a1

	measure 'Previous Month > 78 Weeks' = CALCULATE('RTT'[> 78 Weeks %], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 511c7d44-9585-423b-b9b5-3ba59761d129

	measure '% > 78 Weeks Variance' = CALCULATE([> 78 Weeks %]-[Previous Month > 78 Weeks])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5a090ed5-d639-4008-92a3-2eca1ac51f92

	measure 'Previous Month > 104 Weeks %' = ```
			CALCULATE('RTT'[> 104 Weeks %], PARALLELPERIOD('RTT'[Period],-1,MONTH)) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9dfe97c7-0c03-46ed-b471-4788a2d1708d

	measure '% > 104 Weeks Variance' = calculate([> 104 Weeks %]-[Previous Month > 104 Weeks %])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1f198ebb-1496-4320-9e18-753d674e0e9d

	measure Average =
			CALCULATE(SUM('RTT'[0-18 Weeks])/[Total RTT Waiting List],
			ALLSELECTED('Date Reference'))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d4e01aba-92d6-4b4b-817e-018b25fef9b4

	measure SD = ```
			CALCULATE(STDEVX.P(VALUES('Date Reference'[MonthName]), [< 18 Weeks Total]), ALLEXCEPT('Date Reference','Date Reference'[MonthName]))
			
			```
		formatString: 0
		lineageTag: 0a5be5b0-aad8-4f85-89e3-6aba0dd33997

	measure 'Upper Limit' = [Average]+(3*[SD])
		lineageTag: 5065fdb6-08ba-4b09-aebc-acb577953370

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lower Limit' = CALCULATE([Average]-3*[sd])
		lineageTag: dcc1f105-5e21-4e21-8997-e66845b7f9e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Breaches > 48 Weeks' = sum('RTT'[48-49 Weeks])+SUM('RTT'[49-50 Weeks])+sum('RTT'[50-51 Weeks])+sum('RTT'[51-52 Weeks])+sum('RTT'[> 52 Weeks])
		formatString: 0
		lineageTag: b9e52bfa-8068-44f3-8bd2-64ce568836db

	measure '18-52 Weeks' = sum('RTT'[> 18 Weeks])-sum('RTT'[> 52 Weeks])
		formatString: #,0
		lineageTag: 8992f7db-938b-4f85-81ba-91350272c42a

	measure DynamicTitleName = ```
			
			Var TreatmentFunctionName = SELECTEDVALUE('rtt'[Treatment Function Name])
			Var finalResult= "ICB " & (TreatmentFunctionName) & " RTT Waiters" 
			Return finalResult
			```
		lineageTag: 603387a4-b061-4454-b764-2622f6b4cc75

	measure 'DynamicTitleName 1' = ```
			
			Var TreatmentFunctionName = SELECTEDVALUE('rtt'[Treatment Function Name])
			Var finalResult= "ICB " & (TreatmentFunctionName) & " RTT Performance" 
			Return finalResult
			```
		lineageTag: fa3ccc9f-b347-4514-9f06-734ae2763cd2

	measure zTest = CALCULATE(STDEV.P([% < 18 Weeks]), DATESBETWEEN('RTT'[Period], "01 April 2018" , "01 December 2020"))
		lineageTag: d8fbafb5-4583-49d1-bf03-17a5b43e944b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ztestsumforavg = CALCULATE(average((RTT[% < 18 Weeks])), DATESBETWEEN('RTT'[Period],  DATE(2021, 04, 01) , DATE(2023, 03, 01)))
		lineageTag: f3bb4bd4-4f52-4b21-85bb-732e12249698

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Z Upper limit' = [ztestsumforavg]+(3*[zTest])
		formatString: 0.00
		lineageTag: c0b2fdd6-8620-4889-a720-61bf2506b5f9

	measure 'z standard dev' = CALCULATE(STDEV.P('RTT'[% < 18 Weeks]), DATESBETWEEN('RTT'[Period], "01 April 2021", "31 March 2023"))
		lineageTag: 73c3be0f-2259-40f2-beeb-4b18c7303991

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '< 18 Weeks Total' = SUM('RTT'[0-18 Weeks])
		formatString: 0
		lineageTag: f3562425-7ae9-4095-913f-d0b757d616cd

	measure 'No. 65+ Weeks' = CALCULATE(sum(RTT[> 65 Weeks]))
		formatString: 0
		lineageTag: 1c73d691-c8fb-497f-b36e-0ba4f345bae6

	measure 'Previous Month No. 65+ Weeks' = CALCULATE('RTT'[No. 65+ Weeks], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: 0
		lineageTag: 44b101d3-735c-4201-b992-ef78965eb7dd

	measure 'No. 65+ Weeks Variance' = CALCULATE(RTT[No. 65+ Weeks]-RTT[Previous Month No. 65+ Weeks])
		formatString: 0
		lineageTag: d4ffe976-ecd7-4b81-9e03-30f85a39ee80

	measure 'Previous Month > 65 Weeks %' = CALCULATE('RTT'[> 65 Weeks %], PARALLELPERIOD('RTT'[Period],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 732bf7f0-5657-4d93-8648-7fea74c741d4

	measure '% > 65 Weeks Variance' = CALCULATE('RTT'[> 65 Weeks %]-'RTT'[Previous Month > 65 Weeks %])
		lineageTag: 2a2b3e21-73f4-4584-bdcf-eff1e5a10656

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Version
		dataType: string
		lineageTag: 04e664a5-3477-420e-934f-d9516cd60707
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6c066dd7-321d-494e-b1c5-c84d0c88a7e7
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Provider_Parent_Org_Code
		dataType: string
		lineageTag: fe6f360a-56dd-44b8-b3f8-9e049915f96b
		summarizeBy: none
		sourceColumn: Provider_Parent_Org_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Parent_Name
		dataType: string
		lineageTag: b7fa1f6e-0de0-49bb-894d-bf4ac06f28cd
		summarizeBy: none
		sourceColumn: Provider_Parent_Name

		annotation SummarizationSetBy = Automatic

	column Provider_Org_Code
		dataType: string
		lineageTag: 4e39f4d7-bd8b-4c7b-a205-aaab1739138a
		summarizeBy: none
		sourceColumn: Provider_Org_Code

		annotation SummarizationSetBy = Automatic

	column 'Provider Name'
		dataType: string
		lineageTag: 576580d0-371b-487b-aeac-1e75502891e4
		summarizeBy: none
		sourceColumn: Provider Name

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Org_Code
		dataType: string
		lineageTag: d383a568-fdf5-4025-a5b4-4c34be0c1b12
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Org_Code

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Name
		dataType: string
		lineageTag: 957894d0-c11a-4898-9a12-7ab21c0215dc
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Name

		annotation SummarizationSetBy = Automatic

	column Commissioner_Org_Code
		dataType: string
		lineageTag: 1017f9ef-34ed-45f8-b157-ca3ddcf6da79
		summarizeBy: none
		sourceColumn: Commissioner_Org_Code

		annotation SummarizationSetBy = Automatic

	column Commissioner_Org_Name
		dataType: string
		lineageTag: 2d61e346-fdb4-4c9d-812d-ba7e47848165
		summarizeBy: none
		sourceColumn: Commissioner_Org_Name

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Type
		dataType: string
		lineageTag: c4121bef-57a2-4002-8409-e631df33bc2d
		summarizeBy: none
		sourceColumn: RTT_Part_Type

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Description
		dataType: string
		lineageTag: 17cedd8b-5070-4dfe-bd31-1cdeebc18ef2
		summarizeBy: none
		sourceColumn: RTT_Part_Description

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Code'
		dataType: string
		lineageTag: b817332a-1710-4f71-9518-11f62670623c
		summarizeBy: none
		sourceColumn: Treatment Function Code

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Name'
		dataType: string
		lineageTag: 13ce7911-e32d-4bf5-853f-c06c126a0fbf
		summarizeBy: none
		sourceColumn: Treatment Function Name

		annotation SummarizationSetBy = Automatic

	column Gt_00_To_01_Weeks_SUM_1
		dataType: double
		formatString: #,0
		lineageTag: f2f7f538-3756-4601-91c1-86d39df02bd0
		summarizeBy: sum
		sourceColumn: Gt_00_To_01_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

	column Gt_01_To_02_Weeks_SUM_1
		dataType: double
		formatString: #,0
		lineageTag: 60099e0a-c5ad-48fb-83d0-2d06d0a247ee
		summarizeBy: sum
		sourceColumn: Gt_01_To_02_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

	column Gt_02_To_03_Weeks_SUM_1
		dataType: double
		formatString: #,0
		lineageTag: e280d64b-923e-4dc8-9870-30b87eb51541
		summarizeBy: sum
		sourceColumn: Gt_02_To_03_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

	column Gt_03_To_04_Weeks_SUM_1
		dataType: double
		formatString: #,0
		lineageTag: 0f7f0f6c-7597-4476-b0b6-5d7b7d081d3c
		summarizeBy: sum
		sourceColumn: Gt_03_To_04_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

	column Gt_04_To_05_Weeks_SUM_1
		dataType: double
		formatString: #,0
		lineageTag: a3c57c6f-8c30-4ff5-9c2e-4586a239ff7b
		summarizeBy: sum
		sourceColumn: Gt_04_To_05_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

	column Gt_05_To_06_Weeks_SUM_1
		dataType: double
		lineageTag: beeb67dc-caac-4fc9-86ca-953686fe950f
		summarizeBy: sum
		sourceColumn: Gt_05_To_06_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_06_To_07_Weeks_SUM_1
		dataType: double
		lineageTag: 68ad1010-a3ce-485d-b6ab-35da7cd78c70
		summarizeBy: sum
		sourceColumn: Gt_06_To_07_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_07_To_08_Weeks_SUM_1
		dataType: double
		lineageTag: e627335e-d5ad-4553-aaa6-d029cba67709
		summarizeBy: sum
		sourceColumn: Gt_07_To_08_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_08_To_09_Weeks_SUM_1
		dataType: double
		lineageTag: aa209711-8d6d-48ae-811a-adb15de40d81
		summarizeBy: sum
		sourceColumn: Gt_08_To_09_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_09_To_10_Weeks_SUM_1
		dataType: double
		lineageTag: a7dff29d-77a6-452d-a10d-4734e7d3a681
		summarizeBy: sum
		sourceColumn: Gt_09_To_10_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_10_To_11_Weeks_SUM_1
		dataType: double
		lineageTag: 5cbd0dc9-cbdd-4fe0-a360-b096a68f70e9
		summarizeBy: sum
		sourceColumn: Gt_10_To_11_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_11_To_12_Weeks_SUM_1
		dataType: double
		lineageTag: e04dad7a-cb0c-427c-b6fc-0f47d8d3e7ca
		summarizeBy: sum
		sourceColumn: Gt_11_To_12_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_12_To_13_Weeks_SUM_1
		dataType: double
		lineageTag: 52434277-3c5e-41ca-81bc-a20e0f65db3e
		summarizeBy: sum
		sourceColumn: Gt_12_To_13_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_13_To_14_Weeks_SUM_1
		dataType: double
		lineageTag: 8b6a9202-e647-492c-8460-5811f654a1cb
		summarizeBy: sum
		sourceColumn: Gt_13_To_14_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_14_To_15_Weeks_SUM_1
		dataType: double
		lineageTag: 97f86e0e-f40f-4c80-9a10-bb93296cf505
		summarizeBy: sum
		sourceColumn: Gt_14_To_15_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_15_To_16_Weeks_SUM_1
		dataType: double
		lineageTag: d3504a39-3575-47e2-862f-5af575ff3212
		summarizeBy: sum
		sourceColumn: Gt_15_To_16_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_16_To_17_Weeks_SUM_1
		dataType: double
		lineageTag: fe978d83-118d-4f06-a6b6-a37b7718862b
		summarizeBy: sum
		sourceColumn: Gt_16_To_17_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_17_To_18_Weeks_SUM_1
		dataType: double
		lineageTag: 417e9fa3-7741-4dea-9614-8321fa846ffd
		summarizeBy: sum
		sourceColumn: Gt_17_To_18_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_18_To_19_Weeks_SUM_1
		dataType: double
		lineageTag: 5010128e-38fd-45a5-8eae-7f69ceab2487
		summarizeBy: sum
		sourceColumn: Gt_18_To_19_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_19_To_20_Weeks_SUM_1
		dataType: double
		lineageTag: cdec4b38-4fd5-45ac-a1ba-70e7fa81a487
		summarizeBy: sum
		sourceColumn: Gt_19_To_20_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_20_To_21_Weeks_SUM_1
		dataType: double
		lineageTag: a5f7f3d2-5346-4c59-bc11-77d1e2ea621f
		summarizeBy: sum
		sourceColumn: Gt_20_To_21_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_21_To_22_Weeks_SUM_1
		dataType: double
		lineageTag: c45d26ca-c9b1-45f5-a6df-1b75221be454
		summarizeBy: sum
		sourceColumn: Gt_21_To_22_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_22_To_23_Weeks_SUM_1
		dataType: double
		lineageTag: 00155525-0441-4680-bf41-267342d5821f
		summarizeBy: sum
		sourceColumn: Gt_22_To_23_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_23_To_24_Weeks_SUM_1
		dataType: double
		lineageTag: 9ab72fca-b895-4416-9be0-042601e8923d
		summarizeBy: sum
		sourceColumn: Gt_23_To_24_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_24_To_25_Weeks_SUM_1
		dataType: double
		lineageTag: d5834a68-7441-4ef1-9eed-0bcf8bf56361
		summarizeBy: sum
		sourceColumn: Gt_24_To_25_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_25_To_26_Weeks_SUM_1
		dataType: double
		lineageTag: 5ce6d6ea-9a09-4574-bd09-80ef9c833591
		summarizeBy: sum
		sourceColumn: Gt_25_To_26_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_26_To_27_Weeks_SUM_1
		dataType: double
		lineageTag: f40441ec-2c9a-4f79-b890-3ac471839d43
		summarizeBy: sum
		sourceColumn: Gt_26_To_27_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_27_To_28_Weeks_SUM_1
		dataType: double
		lineageTag: 87b2e224-a337-4efa-97c2-3a53356211ad
		summarizeBy: sum
		sourceColumn: Gt_27_To_28_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_28_To_29_Weeks_SUM_1
		dataType: double
		lineageTag: 59e2a916-b7ac-415f-8cd8-ce535013b7b3
		summarizeBy: sum
		sourceColumn: Gt_28_To_29_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_29_To_30_Weeks_SUM_1
		dataType: double
		lineageTag: d09689ed-7d6e-4262-9f78-a763d8660573
		summarizeBy: sum
		sourceColumn: Gt_29_To_30_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_30_To_31_Weeks_SUM_1
		dataType: double
		lineageTag: 8d8819cd-5c0a-41a9-93c5-8ae2da6dc06a
		summarizeBy: sum
		sourceColumn: Gt_30_To_31_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_31_To_32_Weeks_SUM_1
		dataType: double
		lineageTag: aa02419a-2690-47b7-98af-59ea60177e78
		summarizeBy: sum
		sourceColumn: Gt_31_To_32_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_32_To_33_Weeks_SUM_1
		dataType: double
		lineageTag: b64abe8a-20f7-4bc1-8ac1-a0cd1ab8d60e
		summarizeBy: sum
		sourceColumn: Gt_32_To_33_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_33_To_34_Weeks_SUM_1
		dataType: double
		lineageTag: 86bbbce3-3395-4021-b025-c5e5910a0cba
		summarizeBy: sum
		sourceColumn: Gt_33_To_34_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_34_To_35_Weeks_SUM_1
		dataType: double
		lineageTag: ae0a77e2-603e-4a71-b7e1-266b64d12bf6
		summarizeBy: sum
		sourceColumn: Gt_34_To_35_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_35_To_36_Weeks_SUM_1
		dataType: double
		lineageTag: 70893f0d-fea7-4472-91a1-34032a13f036
		summarizeBy: sum
		sourceColumn: Gt_35_To_36_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_36_To_37_Weeks_SUM_1
		dataType: double
		lineageTag: 0d9ff739-0aca-4fc3-b85f-c738a6369e72
		summarizeBy: sum
		sourceColumn: Gt_36_To_37_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_37_To_38_Weeks_SUM_1
		dataType: double
		lineageTag: 4af543d9-a696-4e97-b7b6-1df9a455a7b4
		summarizeBy: sum
		sourceColumn: Gt_37_To_38_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_38_To_39_Weeks_SUM_1
		dataType: double
		lineageTag: 43e3d540-668a-4079-b36c-978af1025959
		summarizeBy: sum
		sourceColumn: Gt_38_To_39_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_39_To_40_Weeks_SUM_1
		dataType: double
		lineageTag: 490a9152-89e8-4360-82bf-483f4a6c5647
		summarizeBy: sum
		sourceColumn: Gt_39_To_40_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_40_To_41_Weeks_SUM_1
		dataType: double
		lineageTag: 3b7cb07f-a86e-4a91-96ae-2a0db67beaa5
		summarizeBy: sum
		sourceColumn: Gt_40_To_41_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_41_To_42_Weeks_SUM_1
		dataType: double
		lineageTag: af4030be-77b5-49cb-b1b2-2a468fe9454b
		summarizeBy: sum
		sourceColumn: Gt_41_To_42_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_42_To_43_Weeks_SUM_1
		dataType: double
		lineageTag: 5e030813-d612-4ec3-84c2-9099de52d391
		summarizeBy: sum
		sourceColumn: Gt_42_To_43_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_43_To_44_Weeks_SUM_1
		dataType: double
		lineageTag: 4adfc0bf-d3f0-46d0-ac85-0de79e447e8c
		summarizeBy: sum
		sourceColumn: Gt_43_To_44_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_44_To_45_Weeks_SUM_1
		dataType: double
		lineageTag: 975ee716-c8e4-4154-81e7-d529b3639467
		summarizeBy: sum
		sourceColumn: Gt_44_To_45_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_45_To_46_Weeks_SUM_1
		dataType: double
		lineageTag: fb4c43bd-a01c-42ca-a57c-f3a73a613917
		summarizeBy: sum
		sourceColumn: Gt_45_To_46_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_46_To_47_Weeks_SUM_1
		dataType: double
		lineageTag: 1f60ce4e-6d39-4d50-a10f-84f6ccaa8716
		summarizeBy: sum
		sourceColumn: Gt_46_To_47_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_47_To_48_Weeks_SUM_1
		dataType: double
		lineageTag: a58d4af3-6fcd-4c95-aeee-093a4119348d
		summarizeBy: sum
		sourceColumn: Gt_47_To_48_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '48-49 Weeks'
		dataType: int64
		lineageTag: 0226cdb4-0d87-417c-ba4a-ed2ade5eeffb
		summarizeBy: sum
		sourceColumn: 48-49 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '49-50 Weeks'
		dataType: int64
		lineageTag: cc3023b5-e2d9-4b5f-9369-0167b071b39d
		summarizeBy: sum
		sourceColumn: 49-50 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '50-51 Weeks'
		dataType: int64
		lineageTag: 3bcf5eed-b169-4c57-8f5d-a287c1609d09
		summarizeBy: sum
		sourceColumn: 50-51 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '51-52 Weeks'
		dataType: int64
		lineageTag: 3daa39b6-6bda-4a16-89de-8c48d729e2db
		summarizeBy: sum
		sourceColumn: 51-52 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_52_To_53_Weeks_SUM_1
		dataType: double
		lineageTag: 2827c794-7959-4a06-92bd-57d18b883da2
		summarizeBy: sum
		sourceColumn: Gt_52_To_53_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_53_To_54_Weeks_SUM_1
		dataType: double
		lineageTag: 89c14b14-6bd9-4fda-8115-97ff3d714c2e
		summarizeBy: sum
		sourceColumn: Gt_53_To_54_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_54_To_55_Weeks_SUM_1
		dataType: double
		lineageTag: 47e36a74-82b2-4be3-9ead-3d9ef570a207
		summarizeBy: sum
		sourceColumn: Gt_54_To_55_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_55_To_56_Weeks_SUM_1
		dataType: double
		lineageTag: 41951d0a-e6a7-43e4-825a-8594143585f3
		summarizeBy: sum
		sourceColumn: Gt_55_To_56_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_56_To_57_Weeks_SUM_1
		dataType: double
		lineageTag: 1850b68c-909f-4486-9096-2dc31de582c4
		summarizeBy: sum
		sourceColumn: Gt_56_To_57_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_57_To_58_Weeks_SUM_1
		dataType: double
		lineageTag: 4754f9e7-8bd8-40f3-9e5c-5976e50272e3
		summarizeBy: sum
		sourceColumn: Gt_57_To_58_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_58_To_59_Weeks_SUM_1
		dataType: double
		lineageTag: 1290944d-d9fd-40f0-a44e-e77496a7b54a
		summarizeBy: sum
		sourceColumn: Gt_58_To_59_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_59_To_60_Weeks_SUM_1
		dataType: double
		lineageTag: 7293ac4e-46fe-40a8-bf75-0d5f7f22b699
		summarizeBy: sum
		sourceColumn: Gt_59_To_60_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_60_To_61_Weeks_SUM_1
		dataType: double
		lineageTag: 9b9464e8-39ff-4690-827c-5b4c1e67a7f9
		summarizeBy: sum
		sourceColumn: Gt_60_To_61_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_61_To_62_Weeks_SUM_1
		dataType: double
		lineageTag: d73a44d6-94de-46b9-b761-8cc33ce9363b
		summarizeBy: sum
		sourceColumn: Gt_61_To_62_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_62_To_63_Weeks_SUM_1
		dataType: double
		lineageTag: 1d0fb7e8-bce7-46cd-9909-b4359e642100
		summarizeBy: sum
		sourceColumn: Gt_62_To_63_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_63_To_64_Weeks_SUM_1
		dataType: double
		lineageTag: ad95f320-4519-416f-9438-cb72996d8555
		summarizeBy: sum
		sourceColumn: Gt_63_To_64_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_64_To_65_Weeks_SUM_1
		dataType: double
		lineageTag: f4b6f17e-be35-41f0-b117-e440f5c087a9
		summarizeBy: sum
		sourceColumn: Gt_64_To_65_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_65_To_66_Weeks_SUM_1
		dataType: double
		lineageTag: fec70daf-8cfc-4fec-ab73-99337cb7329a
		summarizeBy: sum
		sourceColumn: Gt_65_To_66_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_66_To_67_Weeks_SUM_1
		dataType: double
		lineageTag: d62cdf8e-8248-4845-bf01-85577748d090
		summarizeBy: sum
		sourceColumn: Gt_66_To_67_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_67_To_68_Weeks_SUM_1
		dataType: double
		lineageTag: 91a9c530-ab0c-405b-97ed-f3ecbac26f23
		summarizeBy: sum
		sourceColumn: Gt_67_To_68_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_68_To_69_Weeks_SUM_1
		dataType: double
		lineageTag: cd2902b0-1f7b-45ca-9563-63e466da62d1
		summarizeBy: sum
		sourceColumn: Gt_68_To_69_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_69_To_70_Weeks_SUM_1
		dataType: double
		lineageTag: 2eaf7673-cf62-4d85-b077-507bd5b216b0
		summarizeBy: sum
		sourceColumn: Gt_69_To_70_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_70_To_71_Weeks_SUM_1
		dataType: double
		lineageTag: 27af51a6-a51d-489c-b2f3-802ce5c61102
		summarizeBy: sum
		sourceColumn: Gt_70_To_71_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_71_To_72_Weeks_SUM_1
		dataType: double
		lineageTag: 1beb575b-658e-4b9b-9248-bc144af41257
		summarizeBy: sum
		sourceColumn: Gt_71_To_72_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_72_To_73_Weeks_SUM_1
		dataType: double
		lineageTag: cf390dbf-1a3b-4963-b4ca-b03166fd9e0d
		summarizeBy: sum
		sourceColumn: Gt_72_To_73_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_73_To_74_Weeks_SUM_1
		dataType: double
		lineageTag: c24ff429-ae68-4d17-9ee0-236030ff4d62
		summarizeBy: sum
		sourceColumn: Gt_73_To_74_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_74_To_75_Weeks_SUM_1
		dataType: double
		lineageTag: 8a72de00-357a-4143-a8bc-49732938cbd9
		summarizeBy: sum
		sourceColumn: Gt_74_To_75_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_75_To_76_Weeks_SUM_1
		dataType: double
		lineageTag: 21f0ea6b-172e-4e6a-b6c7-c050fd632045
		summarizeBy: sum
		sourceColumn: Gt_75_To_76_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_76_To_77_Weeks_SUM_1
		dataType: double
		lineageTag: f69df127-71e1-4543-b417-2803ea909a4a
		summarizeBy: sum
		sourceColumn: Gt_76_To_77_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_77_To_78_Weeks_SUM_1
		dataType: double
		lineageTag: 4cb83a2a-cb81-4f9a-b0a8-8b9faa8db106
		summarizeBy: sum
		sourceColumn: Gt_77_To_78_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_78_To_79_Weeks_SUM_1
		dataType: double
		lineageTag: cfab4095-9996-4c9c-87d1-e6fd448dacdc
		summarizeBy: sum
		sourceColumn: Gt_78_To_79_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_79_To_80_Weeks_SUM_1
		dataType: double
		lineageTag: e9ecc3ca-d1b9-4408-a32c-6b78cd719bb7
		summarizeBy: sum
		sourceColumn: Gt_79_To_80_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_80_To_81_Weeks_SUM_1
		dataType: double
		lineageTag: e20f79f8-a7bf-4a4e-86cf-8e5b3b05322d
		summarizeBy: sum
		sourceColumn: Gt_80_To_81_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_81_To_82_Weeks_SUM_1
		dataType: double
		lineageTag: 2e2f072a-b048-46db-abdb-f5132ee87ee3
		summarizeBy: sum
		sourceColumn: Gt_81_To_82_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_82_To_83_Weeks_SUM_1
		dataType: double
		lineageTag: 754d7446-a8f1-4fd9-a4ec-1e411fb373b2
		summarizeBy: sum
		sourceColumn: Gt_82_To_83_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_83_To_84_Weeks_SUM_1
		dataType: double
		lineageTag: e16c4e06-720d-4851-bba4-a7a04499c7c8
		summarizeBy: sum
		sourceColumn: Gt_83_To_84_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_84_To_85_Weeks_SUM_1
		dataType: double
		lineageTag: fccee16c-7ca5-43f3-8c75-16b2e3d6bf1e
		summarizeBy: sum
		sourceColumn: Gt_84_To_85_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_85_To_86_Weeks_SUM_1
		dataType: double
		lineageTag: 392fc4b8-bb9e-4c3e-b334-c4c08c2c7070
		summarizeBy: sum
		sourceColumn: Gt_85_To_86_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_86_To_87_Weeks_SUM_1
		dataType: double
		lineageTag: a02e9fe1-8f36-4acf-bc9d-5287c87e3b97
		summarizeBy: sum
		sourceColumn: Gt_86_To_87_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_87_To_88_Weeks_SUM_1
		dataType: double
		lineageTag: 97667f48-e8b0-4cda-8ffb-17c578b3fb2c
		summarizeBy: sum
		sourceColumn: Gt_87_To_88_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_88_To_89_Weeks_SUM_1
		dataType: double
		lineageTag: ba53948f-29df-4644-b1c6-2870d78f8505
		summarizeBy: sum
		sourceColumn: Gt_88_To_89_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_89_To_90_Weeks_SUM_1
		dataType: double
		lineageTag: f2c9e578-44b2-4c92-81ac-df521b120efb
		summarizeBy: sum
		sourceColumn: Gt_89_To_90_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_90_To_91_Weeks_SUM_1
		dataType: double
		lineageTag: 26605025-1548-44bf-b082-dd52e301caa6
		summarizeBy: sum
		sourceColumn: Gt_90_To_91_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_91_To_92_Weeks_SUM_1
		dataType: double
		lineageTag: 7bdc5cde-7e3f-40f6-89d4-9825dde6cb43
		summarizeBy: sum
		sourceColumn: Gt_91_To_92_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_92_To_93_Weeks_SUM_1
		dataType: double
		lineageTag: 6e7b5f81-f767-492e-a722-038eb1bb0a55
		summarizeBy: sum
		sourceColumn: Gt_92_To_93_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_93_To_94_Weeks_SUM_1
		dataType: double
		lineageTag: d3596b83-5c25-47fa-b3ab-d8b455fba174
		summarizeBy: sum
		sourceColumn: Gt_93_To_94_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_94_To_95_Weeks_SUM_1
		dataType: double
		lineageTag: 73f07054-ee43-45a0-af44-7fc35a541d23
		summarizeBy: sum
		sourceColumn: Gt_94_To_95_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_95_To_96_Weeks_SUM_1
		dataType: double
		lineageTag: 2957d22a-3f90-460a-b624-479bb8032764
		summarizeBy: sum
		sourceColumn: Gt_95_To_96_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_96_To_97_Weeks_SUM_1
		dataType: double
		lineageTag: d8e5e846-9a78-49f5-be28-988d4d91ca0c
		summarizeBy: sum
		sourceColumn: Gt_96_To_97_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_97_To_98_Weeks_SUM_1
		dataType: double
		lineageTag: d516130f-03ed-4f67-a0dd-55d13ae4b97b
		summarizeBy: sum
		sourceColumn: Gt_97_To_98_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_98_To_99_Weeks_SUM_1
		dataType: double
		lineageTag: 05501dd6-0f21-4fbe-9ae9-877c5ac2ac13
		summarizeBy: sum
		sourceColumn: Gt_98_To_99_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_99_To_100_Weeks_SUM_1
		dataType: double
		lineageTag: 5e728911-19f7-43a3-b174-7001e78dbb7c
		summarizeBy: sum
		sourceColumn: Gt_99_To_100_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_100_To_101_Weeks_SUM_1
		dataType: double
		lineageTag: 11a02441-c34e-4179-98fc-adeadd60f916
		summarizeBy: sum
		sourceColumn: Gt_100_To_101_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_101_To_102_Weeks_SUM_1
		dataType: double
		lineageTag: 9705e783-0a97-491c-8f3c-7d162e9e2325
		summarizeBy: sum
		sourceColumn: Gt_101_To_102_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_102_To_103_Weeks_SUM_1
		dataType: double
		lineageTag: 6ec4c9d3-b534-4780-ade8-5f5636528cf9
		summarizeBy: sum
		sourceColumn: Gt_102_To_103_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gt_103_To_104_Weeks_SUM_1
		dataType: double
		lineageTag: af1e5e96-1bbe-467b-89c1-07cc45fc8c37
		summarizeBy: sum
		sourceColumn: Gt_103_To_104_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '> 104 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 8f7ad910-fc7d-4252-a9d4-2b113a9f545c
		summarizeBy: sum
		sourceColumn: > 104 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column '> 52 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: afacdf3d-1cd4-4944-8134-ea079d7490b5
		summarizeBy: sum
		sourceColumn: > 52 Weeks

		annotation SummarizationSetBy = Automatic

	column '0-18 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 0bfd9975-7cf6-4ade-86f2-0631e67e3b89
		summarizeBy: sum
		sourceColumn: 0-18 Weeks

		annotation SummarizationSetBy = Automatic

	column '> 65 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 648f98c3-3b8f-43f4-9eae-6d1d84246728
		summarizeBy: sum
		sourceColumn: > 65 Weeks

		annotation SummarizationSetBy = Automatic

	column 52-78_Weeks_SUM_1
		dataType: double
		lineageTag: 39670e53-563a-42c4-ae41-386d9992716c
		summarizeBy: sum
		sourceColumn: 52-78_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 78-104_Weeks_SUM_1
		dataType: double
		lineageTag: fb37211d-b03b-4cd0-9203-9635d873f542
		summarizeBy: sum
		sourceColumn: 78-104_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '> 18 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 33320808-3328-4d90-8331-c948e6b075fd
		summarizeBy: sum
		sourceColumn: > 18 Weeks

		annotation SummarizationSetBy = Automatic

	column '0-35 Weeks'
		dataType: int64
		lineageTag: bab0ab90-c1e1-49ff-b758-2e3ef3e488b1
		summarizeBy: sum
		sourceColumn: 0-35 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '> 35 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: bf5cdbd4-abe8-426c-80d9-c85346018462
		summarizeBy: sum
		sourceColumn: > 35 Weeks

		annotation SummarizationSetBy = Automatic

	column '> 78 Weeks'
		dataType: int64
		formatString: #,0
		lineageTag: 0c1f3eed-3150-4e2c-a7ef-2dbfcec885fb
		summarizeBy: sum
		sourceColumn: > 78 Weeks

		annotation SummarizationSetBy = Automatic

	column %_of_<18
		dataType: double
		lineageTag: 9dd75844-1369-44b1-909c-7b136f260aa2
		summarizeBy: sum
		sourceColumn: %_of_<18

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %_>18
		dataType: double
		lineageTag: 4517dedf-9e2a-4a96-bdd9-e0c7ca09a91b
		summarizeBy: sum
		sourceColumn: %_>18

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %<35
		dataType: double
		lineageTag: e4c8fabf-aeca-4296-a5cd-0f8a426f6576
		summarizeBy: sum
		sourceColumn: %<35

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>35
		dataType: double
		lineageTag: 25a2a53c-69ef-481d-be46-d29114d32987
		summarizeBy: sum
		sourceColumn: %>35

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>78
		dataType: double
		lineageTag: 6a9a4c2a-e8e1-4dba-9b0f-8fe074647636
		summarizeBy: sum
		sourceColumn: %>78

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>104
		dataType: double
		lineageTag: 67e83249-fed6-4ff3-8cf7-57c86b6c0f2a
		summarizeBy: sum
		sourceColumn: %>104

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Known
		dataType: double
		lineageTag: 227344d1-299e-4077-9d1b-0c6912f8064b
		summarizeBy: sum
		sourceColumn: Total_Known

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Patients_Unknown_Start
		dataType: double
		lineageTag: 7ea04535-0c10-4ad0-9cc9-e37cf434a42f
		summarizeBy: sum
		sourceColumn: Patients_Unknown_Start

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total
		dataType: double
		formatString: #,0
		lineageTag: d6d02548-6381-445d-b9b7-090c82688fc3
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: int64
		formatString: 0
		lineageTag: 989e4d11-bf99-48c0-90c7-047917d4d0c2
		summarizeBy: sum
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: f4150c08-07ec-4033-adfe-c10eb3023c72
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: 1e8e6504-4b17-4457-9301-22d761ac0977
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column Period2
		dataType: string
		lineageTag: 2eb94bd1-f8de-4fe2-831c-fd12b1c80c8a
		summarizeBy: none
		sourceColumn: Period2

		annotation SummarizationSetBy = Automatic

	column 'Sum of weeks' = (RTT[0-18 Weeks]+RTT[> 18 Weeks]+RTT[> 35 Weeks]+RTT[> 52 Weeks]+RTT[> 65 Weeks]+RTT[> 78 Weeks]+RTT[> 104 Weeks])
		formatString: 0
		lineageTag: c518acd3-bf38-42d3-997e-de156528ff81
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '% < 18 Weeks'
		dataType: double
		lineageTag: d307848b-6fc9-445d-b592-4824ef76d56e
		summarizeBy: sum
		sourceColumn: % < 18 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition RTT = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "gccg_analytics", [Query="SELECT *#(lf),[Financial_Year] = CASE WHEN RIGHT([Period],2) IN ('01','02','03') THEN CAST(LEFT([Period],4)-1 AS VARCHAR)+'/'+ CAST(RIGHT(LEFT([Period],4),2) AS VARCHAR) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CAST(LEFT([Period],4) AS VARCHAR)+'/'+CAST(RIGHT(LEFT([Period],4),2)+1 AS VARCHAR) END,#(lf)[Period2] = right([period],2)#(lf)#(lf) #(lf)#(lf)FROM [GCCG_Analytics].[dbo].[Performance_RTT_18wks_Incompletes_VW]#(lf)WHERE [Version] = 'FINAL'#(lf)AND CAST('01'+'/'+RIGHT(PERIOD,2)+'/'+LEFT(PERIOD,4)AS DATE) >= '01-MAR-1990'"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Gt_104_Weeks_SUM_1", "> 104 Weeks"}, {">_52_Weeks_SUM_1", "> 52 Weeks"}, {"0-18_Weeks_SUM_1", "0-18 Weeks"}, {">65_Weeks_SUM_1", "> 65 Weeks"}, {">_18_Weeks_SUM_1", "> 18 Weeks"}, {"0-35_Weeks_SUM_1", "0-35 Weeks"}, {">_35_Weeks_SUM_1", "> 35 Weeks"}, {">_78_Weeks_SUM_1", "> 78 Weeks"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"> 104 Weeks", Int64.Type}, {"> 52 Weeks", Int64.Type}, {"0-18 Weeks", Int64.Type}, {"> 65 Weeks", Int64.Type}, {"> 18 Weeks", Int64.Type}, {"0-35 Weeks", Int64.Type}, {"> 35 Weeks", Int64.Type}, {"> 78 Weeks", Int64.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"Treatment_Function_Code", "Treatment Function Code"}, {"Treatment_Function_Name", "Treatment Function Name"}, {"Total_All", "Total"}, {"0-18 Weeks", "< 18 Weeks"}, {"Financial_Year", "Financial Year"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Period", type date}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"< 18 Weeks", "0-18 Weeks"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns2", "% < 18 Weeks", each [#"%_of_<18"]/100),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"% < 18 Weeks", type number}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type2",{{"Gt_48_To_49_Weeks_SUM_1", "48-49 Weeks"}, {"Gt_49_To_50_Weeks_SUM_1", "49-50 Weeks"}, {"Gt_50_To_51_Weeks_SUM_1", "50-51 Weeks"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns3",{{"48-49 Weeks", Int64.Type}, {"49-50 Weeks", Int64.Type}, {"50-51 Weeks", Int64.Type}, {"Gt_51_To_52_Weeks_SUM_1", Int64.Type}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type3",{{"Gt_51_To_52_Weeks_SUM_1", "51-52 Weeks"}, {"Provider_Org_Name", "Provider Name"}})
				in
				    #"Renamed Columns4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

