table 'Unpivoted RTT'
	lineageTag: 54c3f168-2443-4455-9f60-8534a40d8f9f

	measure 'Previous Month' = CALCULATE(sum('Unpivoted RTT'[Selected Month]), PARALLELPERIOD(RTT[Period], -1, MONTH))
		formatString: 0
		lineageTag: aa1d2216-0fd4-4cc4-a779-ac1439e2cb9b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Previous Year' = CALCULATE(SUM('Unpivoted RTT'[Selected Month]), PARALLELPERIOD('RTT'[Period],-12,MONTH))
		formatString: 0
		lineageTag: 19345b14-f148-46b0-ad42-f0a9260a7afd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Dynamic Title Name 2' =
			
			Var CurrentPeriod = SELECTEDVALUE('RTT'[Period])
			Var finalResult= "Gloucestershire ICB - Waiter Distribution Split by Week - " & (CurrentPeriod) & " Vs Previous Year and Month"
			Return finalResult
		lineageTag: f7cb3647-ba8b-44c2-8d5a-ab1e3ef5734d

	column Version
		dataType: string
		lineageTag: 7d3c15c4-ce98-4379-b7e5-c4de4c9546e5
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: dateTime
		formatString: Long Date
		lineageTag: b454a7a7-8957-4a0d-bdcb-1f12b507a054
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Provider_Parent_Org_Code
		dataType: string
		lineageTag: 18e2c6a2-d14e-4b50-9582-47a8a94ef1dc
		summarizeBy: none
		sourceColumn: Provider_Parent_Org_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Parent_Name
		dataType: string
		lineageTag: 2cddd176-ef18-4bb9-b3d5-a39401064373
		summarizeBy: none
		sourceColumn: Provider_Parent_Name

		annotation SummarizationSetBy = Automatic

	column Provider_Org_Code
		dataType: string
		lineageTag: 8603ffa3-6ce3-443f-bd1e-afb3a1e3b379
		summarizeBy: none
		sourceColumn: Provider_Org_Code

		annotation SummarizationSetBy = Automatic

	column 'Provider Name'
		dataType: string
		lineageTag: a85e58a0-c7b3-4257-a33f-6886ac2ed71c
		summarizeBy: none
		sourceColumn: Provider Name

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Org_Code
		dataType: string
		lineageTag: 5cec0997-b672-4156-8617-9e449da75af6
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Org_Code

		annotation SummarizationSetBy = Automatic

	column Commissioner_Parent_Name
		dataType: string
		lineageTag: c4465410-7812-4f60-a752-1c01ab382c55
		summarizeBy: none
		sourceColumn: Commissioner_Parent_Name

		annotation SummarizationSetBy = Automatic

	column Commissioner_Org_Code
		dataType: string
		lineageTag: 820c0871-fbf6-4ab9-a05e-28b6f38ed87c
		summarizeBy: none
		sourceColumn: Commissioner_Org_Code

		annotation SummarizationSetBy = Automatic

	column Commissioner_Org_Name
		dataType: string
		lineageTag: 91aa93f3-f761-4a8e-93e4-a778f8191a4c
		summarizeBy: none
		sourceColumn: Commissioner_Org_Name

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Type
		dataType: string
		lineageTag: ccb93bdf-4a52-4dc5-af98-6c7a77607ec6
		summarizeBy: none
		sourceColumn: RTT_Part_Type

		annotation SummarizationSetBy = Automatic

	column RTT_Part_Description
		dataType: string
		lineageTag: d56320a3-b80e-4708-800f-48db7f3025db
		summarizeBy: none
		sourceColumn: RTT_Part_Description

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Code'
		dataType: string
		lineageTag: 7309e7f2-f462-401b-bf07-92cbf5ee14ab
		summarizeBy: none
		sourceColumn: Treatment Function Code

		annotation SummarizationSetBy = Automatic

	column 'Treatment Function Name'
		dataType: string
		lineageTag: f1eb4630-5ca5-47c4-853a-685e54079081
		summarizeBy: none
		sourceColumn: Treatment Function Name

		annotation SummarizationSetBy = Automatic

	column '> 104 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: f6599674-1f44-4627-a13b-e208bfeadc7b
		summarizeBy: sum
		sourceColumn: > 104 Weeks

		annotation SummarizationSetBy = Automatic

	column '> 52 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: d5eba34c-22d1-4c58-9332-bc27e3e74bfd
		summarizeBy: sum
		sourceColumn: > 52 Weeks

		annotation SummarizationSetBy = Automatic

	column '0-18 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 19c8e4fb-28f2-4f79-a17b-62992260358c
		summarizeBy: sum
		sourceColumn: 0-18 Weeks

		annotation SummarizationSetBy = Automatic

	column '> 65 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: aad69585-bf26-4c9c-942f-1296e2b2e802
		summarizeBy: sum
		sourceColumn: > 65 Weeks

		annotation SummarizationSetBy = Automatic

	column 52-78_Weeks_SUM_1
		dataType: double
		lineageTag: 4ed11d67-93e6-4e92-8b73-1d600071955e
		summarizeBy: sum
		sourceColumn: 52-78_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 78-104_Weeks_SUM_1
		dataType: double
		lineageTag: 5543a11b-8dc7-4a47-a44b-c404bfdc215a
		summarizeBy: sum
		sourceColumn: 78-104_Weeks_SUM_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '> 18 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: d29f5ddc-bc62-4e84-a35e-488601ca40b5
		summarizeBy: sum
		sourceColumn: > 18 Weeks

		annotation SummarizationSetBy = Automatic

	column '0-35 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 9a38210f-ef8a-4b20-8aed-f4324d5b44b4
		summarizeBy: sum
		sourceColumn: 0-35 Weeks

		annotation SummarizationSetBy = Automatic

	column '> 35 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: da25b090-6212-4b70-9567-eb9f14a08915
		summarizeBy: sum
		sourceColumn: > 35 Weeks

		annotation SummarizationSetBy = Automatic

	column '> 78 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: cc7ec15d-c5c8-43a6-a261-837ed4d1256b
		summarizeBy: sum
		sourceColumn: > 78 Weeks

		annotation SummarizationSetBy = Automatic

	column %_of_<18
		dataType: double
		lineageTag: d54e1773-a197-4a7a-813d-c342d2f9f302
		summarizeBy: sum
		sourceColumn: %_of_<18

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %_>18
		dataType: double
		lineageTag: 612749f3-818d-4637-8af0-de4c7af2f3a0
		summarizeBy: sum
		sourceColumn: %_>18

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %<35
		dataType: double
		lineageTag: 3e198e3a-6b69-4137-8c4a-c2ec94332cbf
		summarizeBy: sum
		sourceColumn: %<35

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>35
		dataType: double
		lineageTag: 1572f267-05b9-4586-b076-44ffbb8a8c3d
		summarizeBy: sum
		sourceColumn: %>35

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>78
		dataType: double
		lineageTag: 4552ffe5-3044-48a5-950f-a2d8c6cc2697
		summarizeBy: sum
		sourceColumn: %>78

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %>104
		dataType: double
		lineageTag: fc73cdac-c64e-47cf-b5ab-ef18a4be2664
		summarizeBy: sum
		sourceColumn: %>104

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Known
		dataType: double
		lineageTag: fe898882-f6f9-40bc-bffd-d482b923e881
		summarizeBy: sum
		sourceColumn: Total_Known

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Patients_Unknown_Start
		dataType: double
		lineageTag: 8ca45455-2952-4443-9874-c040e0692c23
		summarizeBy: sum
		sourceColumn: Patients_Unknown_Start

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total
		dataType: double
		lineageTag: 4edd854d-f7cb-4dab-9748-67004017c079
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status
		dataType: int64
		formatString: 0
		lineageTag: aa87de57-4c5d-4685-b66c-33808e0d7a16
		summarizeBy: sum
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: b6fe02bc-9430-4801-8ff7-588d5dce7a4a
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: 1426fede-20f9-46db-a4c8-5d45059d1908
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column Period2
		dataType: string
		lineageTag: a23d35aa-4b98-44f0-ad6d-14b1ff0ac9db
		summarizeBy: none
		sourceColumn: Period2

		annotation SummarizationSetBy = Automatic

	column '% < 18 Weeks'
		dataType: double
		lineageTag: 5f80d8d4-3794-4cc1-9ebf-6e149744841c
		summarizeBy: sum
		sourceColumn: % < 18 Weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of Weeks Waiting'
		dataType: int64
		formatString: 0
		lineageTag: 18a0b237-da9e-4657-98d9-77eef188df9e
		summarizeBy: sum
		sourceColumn: Number of Weeks Waiting

		annotation SummarizationSetBy = Automatic

	column 'Selected Month'
		dataType: double
		formatString: 0
		lineageTag: fde038d5-bc80-42ec-8469-bf5c29f9454e
		summarizeBy: sum
		sourceColumn: Selected Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition 'Unpivoted RTT' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "gccg_analytics", [Query="SELECT *#(lf),[Financial_Year] = CASE WHEN RIGHT([Period],2) IN ('01','02','03') THEN CAST(LEFT([Period],4)-1 AS VARCHAR)+'/'+ CAST(RIGHT(LEFT([Period],4),2) AS VARCHAR) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CAST(LEFT([Period],4) AS VARCHAR)+'/'+CAST(RIGHT(LEFT([Period],4),2)+1 AS VARCHAR) END,#(lf)[Period2] = right([period],2)#(lf)#(lf) #(lf)#(lf)FROM [GCCG_Analytics].[dbo].[Performance_RTT_18wks_Incompletes_VW]#(lf)WHERE [Version] = 'FINAL'#(lf)AND CAST('01'+'/'+RIGHT(PERIOD,2)+'/'+LEFT(PERIOD,4)AS DATE) >= '01-MAR-1990'"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Gt_104_Weeks_SUM_1", "> 104 Weeks"}, {">_52_Weeks_SUM_1", "> 52 Weeks"}, {"0-18_Weeks_SUM_1", "0-18 Weeks"}, {">65_Weeks_SUM_1", "> 65 Weeks"}, {">_18_Weeks_SUM_1", "> 18 Weeks"}, {"0-35_Weeks_SUM_1", "0-35 Weeks"}, {">_35_Weeks_SUM_1", "> 35 Weeks"}, {">_78_Weeks_SUM_1", "> 78 Weeks"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"> 104 Weeks", Int64.Type}, {"> 52 Weeks", Int64.Type}, {"0-18 Weeks", Int64.Type}, {"> 65 Weeks", Int64.Type}, {"> 18 Weeks", Int64.Type}, {"0-35 Weeks", Int64.Type}, {"> 35 Weeks", Int64.Type}, {"> 78 Weeks", Int64.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"Treatment_Function_Code", "Treatment Function Code"}, {"Treatment_Function_Name", "Treatment Function Name"}, {"Total_All", "Total"}, {"0-18 Weeks", "< 18 Weeks"}, {"Financial_Year", "Financial Year"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Period", type date}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"< 18 Weeks", "0-18 Weeks"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns2", "% < 18 Weeks", each [#"%_of_<18"]/100),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"% < 18 Weeks", type number}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type2",{{"Gt_48_To_49_Weeks_SUM_1", "48-49 Weeks"}, {"Gt_49_To_50_Weeks_SUM_1", "49-50 Weeks"}, {"Gt_50_To_51_Weeks_SUM_1", "50-51 Weeks"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns3",{{"48-49 Weeks", Int64.Type}, {"49-50 Weeks", Int64.Type}, {"50-51 Weeks", Int64.Type}, {"Gt_51_To_52_Weeks_SUM_1", Int64.Type}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type3",{{"Gt_51_To_52_Weeks_SUM_1", "51"}, {"Provider_Org_Name", "Provider Name"}, {"Gt_00_To_01_Weeks_SUM_1", "0"}, {"Gt_01_To_02_Weeks_SUM_1", "1"}, {"Gt_02_To_03_Weeks_SUM_1", "2"}, {"Gt_03_To_04_Weeks_SUM_1", "3"}, {"Gt_04_To_05_Weeks_SUM_1", "4"}, {"Gt_05_To_06_Weeks_SUM_1", "5"}, {"Gt_06_To_07_Weeks_SUM_1", "6"}, {"Gt_07_To_08_Weeks_SUM_1", "7"}, {"Gt_08_To_09_Weeks_SUM_1", "8"}, {"Gt_09_To_10_Weeks_SUM_1", "9"}, {"Gt_10_To_11_Weeks_SUM_1", "10"}, {"Gt_11_To_12_Weeks_SUM_1", "11"}, {"Gt_12_To_13_Weeks_SUM_1", "12"}, {"Gt_13_To_14_Weeks_SUM_1", "13"}, {"Gt_14_To_15_Weeks_SUM_1", "14"}, {"Gt_15_To_16_Weeks_SUM_1", "15"}, {"Gt_16_To_17_Weeks_SUM_1", "16"}, {"Gt_17_To_18_Weeks_SUM_1", "17"}, {"Gt_18_To_19_Weeks_SUM_1", "18"}, {"Gt_19_To_20_Weeks_SUM_1", "19"}, {"Gt_20_To_21_Weeks_SUM_1", "20"}, {"Gt_21_To_22_Weeks_SUM_1", "21"}, {"Gt_22_To_23_Weeks_SUM_1", "22"}, {"Gt_23_To_24_Weeks_SUM_1", "23"}, {"Gt_24_To_25_Weeks_SUM_1", "24"}, {"Gt_25_To_26_Weeks_SUM_1", "25"}, {"Gt_26_To_27_Weeks_SUM_1", "26"}, {"Gt_27_To_28_Weeks_SUM_1", "27"}, {"Gt_28_To_29_Weeks_SUM_1", "28"}, {"Gt_29_To_30_Weeks_SUM_1", "29"}, {"Gt_30_To_31_Weeks_SUM_1", "30"}, {"Gt_31_To_32_Weeks_SUM_1", "31"}, {"Gt_32_To_33_Weeks_SUM_1", "32"}, {"Gt_33_To_34_Weeks_SUM_1", "33"}, {"Gt_34_To_35_Weeks_SUM_1", "34"}, {"Gt_35_To_36_Weeks_SUM_1", "35"}, {"Gt_36_To_37_Weeks_SUM_1", "36"}, {"Gt_37_To_38_Weeks_SUM_1", "37"}, {"Gt_38_To_39_Weeks_SUM_1", "38"}, {"Gt_39_To_40_Weeks_SUM_1", "39"}, {"Gt_40_To_41_Weeks_SUM_1", "40"}, {"Gt_41_To_42_Weeks_SUM_1", "41"}, {"Gt_42_To_43_Weeks_SUM_1", "42"}, {"Gt_43_To_44_Weeks_SUM_1", "43"}, {"Gt_44_To_45_Weeks_SUM_1", "44"}, {"Gt_45_To_46_Weeks_SUM_1", "45"}, {"Gt_46_To_47_Weeks_SUM_1", "46"}, {"Gt_47_To_48_Weeks_SUM_1", "47"}, {"48-49 Weeks", "48"}, {"49-50 Weeks", "49"}, {"50-51 Weeks", "50"}, {"Gt_52_To_53_Weeks_SUM_1", "52"}, {"Gt_53_To_54_Weeks_SUM_1", "53"}, {"Gt_54_To_55_Weeks_SUM_1", "54"}, {"Gt_55_To_56_Weeks_SUM_1", "55"}, {"Gt_56_To_57_Weeks_SUM_1", "56"}, {"Gt_57_To_58_Weeks_SUM_1", "57"}, {"Gt_58_To_59_Weeks_SUM_1", "58"}, {"Gt_59_To_60_Weeks_SUM_1", "59"}, {"Gt_60_To_61_Weeks_SUM_1", "60"}, {"Gt_61_To_62_Weeks_SUM_1", "61"}, {"Gt_62_To_63_Weeks_SUM_1", "62"}, {"Gt_63_To_64_Weeks_SUM_1", "63"}, {"Gt_64_To_65_Weeks_SUM_1", "64"}, {"Gt_65_To_66_Weeks_SUM_1", "65"}, {"Gt_66_To_67_Weeks_SUM_1", "66"}, {"Gt_67_To_68_Weeks_SUM_1", "67"}, {"Gt_68_To_69_Weeks_SUM_1", "68"}, {"Gt_69_To_70_Weeks_SUM_1", "69"}, {"Gt_70_To_71_Weeks_SUM_1", "70"}, {"Gt_71_To_72_Weeks_SUM_1", "71"}, {"Gt_72_To_73_Weeks_SUM_1", "72"}, {"Gt_73_To_74_Weeks_SUM_1", "73"}, {"Gt_74_To_75_Weeks_SUM_1", "74"}, {"Gt_75_To_76_Weeks_SUM_1", "75"}, {"Gt_76_To_77_Weeks_SUM_1", "76"}, {"Gt_77_To_78_Weeks_SUM_1", "77"}, {"Gt_78_To_79_Weeks_SUM_1", "78"}, {"Gt_79_To_80_Weeks_SUM_1", "79"}, {"Gt_80_To_81_Weeks_SUM_1", "80"}, {"Gt_81_To_82_Weeks_SUM_1", "81"}, {"Gt_82_To_83_Weeks_SUM_1", "82"}, {"Gt_83_To_84_Weeks_SUM_1", "83"}, {"Gt_84_To_85_Weeks_SUM_1", "84"}, {"Gt_85_To_86_Weeks_SUM_1", "85"}, {"Gt_86_To_87_Weeks_SUM_1", "86"}, {"Gt_87_To_88_Weeks_SUM_1", "87"}, {"Gt_88_To_89_Weeks_SUM_1", "88"}, {"Gt_89_To_90_Weeks_SUM_1", "89"}, {"Gt_90_To_91_Weeks_SUM_1", "90"}, {"Gt_91_To_92_Weeks_SUM_1", "91"}, {"Gt_92_To_93_Weeks_SUM_1", "92"}, {"Gt_93_To_94_Weeks_SUM_1", "93"}, {"Gt_94_To_95_Weeks_SUM_1", "94"}, {"Gt_95_To_96_Weeks_SUM_1", "95"}, {"Gt_96_To_97_Weeks_SUM_1", "96"}, {"Gt_97_To_98_Weeks_SUM_1", "97"}, {"Gt_98_To_99_Weeks_SUM_1", "98"}, {"Gt_99_To_100_Weeks_SUM_1", "99"}, {"Gt_100_To_101_Weeks_SUM_1", "100"}, {"Gt_101_To_102_Weeks_SUM_1", "101"}, {"Gt_102_To_103_Weeks_SUM_1", "102"}, {"Gt_103_To_104_Weeks_SUM_1", "103"}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Renamed Columns4", {"Version", "Period", "Provider_Parent_Org_Code", "Provider_Parent_Name", "Provider_Org_Code", "Provider Name", "Commissioner_Parent_Org_Code", "Commissioner_Parent_Name", "Commissioner_Org_Code", "Commissioner_Org_Name", "RTT_Part_Type", "RTT_Part_Description", "Treatment Function Code", "Treatment Function Name", "> 104 Weeks", "> 52 Weeks", "0-18 Weeks", "> 65 Weeks", "52-78_Weeks_SUM_1", "78-104_Weeks_SUM_1", "> 18 Weeks", "0-35 Weeks", "> 35 Weeks", "> 78 Weeks", "%_of_<18", "%_>18", "%<35", "%>35", "%>78", "%>104", "Total_Known", "Patients_Unknown_Start", "Total", "Status", "Counter", "Financial Year", "Period2", "% < 18 Weeks"}, "Attribute", "Value"),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Unpivoted Columns",{{"Attribute", Int64.Type}}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Changed Type4",{{"Attribute", "Number of Weeks Waiting"}, {"Value", "Selected Month"}})
				in
				    #"Renamed Columns5"

	annotation PBI_ResultType = Table

