table 'REF_Baselines Meta Data Table'
	isHidden
	lineageTag: c42c5906-a923-4b5c-971f-1eefb1bbbd77

	column 'Baseline Metric '
		dataType: string
		isHidden
		lineageTag: 5ae95838-a1ca-4b14-861b-22bb26ddd63d
		summarizeBy: none
		sourceColumn: "Baseline Metric "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Read Codes Used '
		dataType: string
		isHidden
		lineageTag: 21a39bf5-1dc9-46ad-8e43-8e2b4300b678
		summarizeBy: none
		sourceColumn: "Read Codes Used "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SNOMED Codes Used'
		dataType: string
		isHidden
		lineageTag: 9767466c-a377-4164-81f2-cce82de12dad
		summarizeBy: none
		sourceColumn: SNOMED Codes Used

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '  .'
		dataType: string
		isHidden
		lineageTag: 4160c650-1c51-49ca-bfe9-09666f84271f
		summarizeBy: none
		sourceColumn: "  ."

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Addtional Information '
		dataType: string
		isHidden
		lineageTag: a15350f8-12e1-4c1a-8487-8ce69cbe5823
		summarizeBy: none
		sourceColumn: "Addtional Information "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'REF_Baselines Meta Data Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVnZUuNGFP2VrnkyVUBp8UbeDNiMh2HiMQ7YTvLQktpWB22oJTyeykM+I/m9fElua9dtFk+mhjIUPu67ry3/+uu7WRxGYZzwMCDwSlxGdi5PmBXS2CmRiHoepwl/YsSmMSMx23KRsPjd8bvfUk0zBku67Pbzf49LZN4bKcg5QizdVZCNgjAF2baQlUappSC2gtAWsr7rDS4Q57VvIeTz8LbNh+pam/PZ+Lx3ijV8NBCymu8V5LKFDM9HBuazZjpC2PgSIdPIw1TWQEFwLNYW5rO2xkq8NAUxMTKZYA1XQkESBYmxnx8+KMgnBcEasuUTQuh0jpCZ/4j5bLFXl79cIcR2cK7ak4d2JpiOYysIRVQ3LseywnslE7Cs+QTr8+FJyajoTpF+hs6MP2CPrS2szzSaYh9etqM8fD/4eIqQ/gjn6jKcIWTr40wYbXGXGLEvWB/vAZ+5x5kwWvQwlcBdYppgWVOBe8s0aVeKvtZ0bNdohuP18Rp7bO3u8n9/C6AnnsCvfP1+/EZ73fHEJZTMmZiNLxZkE8Y+0K1Ma1OmESliq2/sImdPTuC8Hfo+CxzmkNvU92m8JzOPBpIBGfss3rLA3pML2app4JBFzGgC55NMu8JSXRsMz3Qt+9G1fluebg6NvlZ9Wjjpm8xymJTIKel8/nmSs+2TT2FwIt/aocMESQVzKoUmoBFyPfzZIUdr3vsWMjrrIqqxgdvoONWMrxjR2y1grOmYStO6SJ+xTq8wH81QEEW6pkg3dAVR+DxjxV5BTAXBLft6v2ohk31qaoo39tjSdV8507YComPigjd6H/CZOS7m6TVudtNrNIZ72vtUyQRfkd7OBBmvrwqCo6x1TQVpe35i6HuE6PoXPFD1q7YVo66OGwf8+aLojDwPCuJ2o4kxpkKL1BgSQVc4rxTpe+WMSmUqSBdlgjZvN3G92y/ZlGcG2k1bw18sfdFXOI8UBA0ww9zg9Wuk3yp2qXmIRuNYX6L8oSZTqTwFWeK4qzE1ewqiWorHw9Zt2wVZpyvdRleyV+lRmq5kr24o0j8qyJWCKHVq3mNkjheO8aCLpZuKFbizaUofUyIoEU3R5xpJt+4i5cxCqWVcXzC8MIKnDGSLUDgXS2Q+zr9tnl/QwGZxNvYyJv2r28kRAfqPNGEiKT9vj0Hy1B0eegZeC5cLwgPbS+WHEVzNYNYKUIcmxKVwTaM5bc7G4XQbhAJIpNYxsRgsCixT3maBSAVxQGy2KoSBty8Zw4FQsHJJAStI5yr0YOVI4CSYK8gkpj7bhfHDUaYm3AvtMJZbycGrTwALgaJlR8qaFUYdgbnyfe6HE9K43hDYhTKNRKXRptSIRHEo2SXcBnscbtMELIeDW0ZGpGN5KTsCbntGYxJ54ILiPBflDtS4Nf1fQeeks40ZC6QkPwwStymmcQcD/v+H/QXp7JnnhTvJf8fYA2Y//j71L0knZo5k7tB9g3dWFc2YDLu9Qb0tFl3ixwRHijIqUcPvEvVqeKSgXiXI/HGBkoIGeNX+ISE7oHEE//71T0K2YQK1WdRlq7KPX28hVlr1n0P6BfDKGZ8+1zGaz6E2GxaDYcB3dnE7I8Ulq9hITKOZE8Ud+MWerTahjCVcqSKPJbJ5lYxXxhA9ewLEoBX/Qrw+HJzplfhyPyCNTw1cG4cOlLqhO8z2eFB5oHAAaXhAV5IVkujPGYtFGFCPywFS3Qhv00gKzW6NAQ+2NfuO4ElKpTpHfza0XIQJ9cjN5YL4jCVAAckDuSFFNvWNwij1MurGo8HPm6hK6pvUS7jDhc0jkCcvrjF74mzXGrRZkvosiSHBEylYZH4JUt8CmeEm0yOnE0UCCcKo7ZYJDS4T8Ou8nqwOf+JyWFn77CPBPGbL+D9rD0m4DxUjDT4ll2xDwZCCRH4q3BB0oZ4HJUcBspksM3LlhSn8m0AQXB6zt9K8yMcoZkW6Rx61mbTYgRu8W1Vhw7nTaFl3jNkLhPVTJHP79umfiBv6jHSOGmTuYWQiAstJJ6NokvM6I18mlw810oAn+5yRTLgGiz9qDd5SAVE+1MJfIw3SWMhSyIyvyD9/fTxIcJSQNKCWB2kWEvYFQihEEUgGbbTJMD6IoSySVAiZJIFsxxH08ijmMnEbvJJD4lJWRRpAmWcpX3GYdx8P4eDBJM77BBfU4p4MkgxVk5E4hJF8JgTRcRn1IJ8xi/RbPMOKetlQn8PSWrG52+0aAX8l3WQzbAd7+XNyWLALh1ZdsxGsitlK1Cn7MqtUpOCPCoW0gQC1EmazuDykeoKwmW5vXVzUppPLuJcD54YmsmPJTL4p5l/2bPLZGWkaTh9NRBjGZ0ZXKx+NfbMSNzCkQIs9OYfW+aL8lb5htA7Xv3/9XVwZsgknoyt3F7nCBLDTQ0lCq85aucgO7LhwmYB1p86/c6PNrhideaZE8gFrpUCbTqvonicr86RNZb4lLdt6MqosnLBbdBurxKAl9HtM7xmmVq+6WqMEDvaCZKHjLedly1SHSAYDvMO9ogPyTZlg9dPvkePzrCJFllwwjM+0fCmuxmm1wWRv4d45m92Dca7cjO7g7UWYBsl+BwV5dFQsXM9sKHBz4LCA5ztKLPszCGCVHvRFPaCbw3ICRZbP6HJqyNqWih3Xmh1nLqex7MCJC1cWso3DNBI/ZTLv6zLKlZdL+skOo1no5YaClpKT8ttcKbi8EBQegSuFQ/pa/mjgicWnZPGcwPpGIe8jsFWlcmfbuaEcWzA6WPVNcoPUSQt7WGETZKxgdpp9zVxcx2DuOPJQGkk/wVEe56qd5u0E4lX34kzjA+NU75Iwgx7T+ivt2gklx2wHx3Y0vMuDl/Vvh7hY/+SXIKrmP0hxhzvl/iBv09+r/u//AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Baseline Metric " = _t, #"Read Codes Used " = _t, #"SNOMED Codes Used" = _t, #"  ." = _t, #"Addtional Information " = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Baseline Metric ", type text}, {"Read Codes Used ", type text}, {"SNOMED Codes Used", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

