table REF_Date
	lineageTag: 9279430d-cc53-431d-b9c8-6825e4265501
	dataCategory: Time

	measure Latest_financial_year_in_dataset = ```
			
			
			 calculate(max(REF_Date[financial_year])
			 ,all(REF_Date))
			```
		lineageTag: 4260cf7d-664a-415f-a09c-5ec7855d841d

	measure Only_show_current_financial_year_flag = if(max(REF_Date[financial_year]) = [Latest_financial_year_in_dataset],1,0)
		formatString: 0
		lineageTag: c5bddeac-2149-4329-84aa-6fbedc73dd42

	measure Latest_reporting_month_year = ```
			
			
			 calculate(max(REF_Date[date])
			 ,all(REF_Date))
			```
		formatString: dd/mm/yyyyy
		lineageTag: b59484be-8173-4c40-abab-16b0f42fc437

		annotation PBI_FormatHint = {"isCustom":true}

	column date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 0b4f50ec-a1c8-48a8-9f6d-1c42b8c6c7bf
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: 80ba9e19-44f6-4c9f-986c-02b17c4de864
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: b163b590-3ee4-4f7d-b99f-0d53d270eec4
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 9c01977f-afde-4cee-a1e3-b4014c4ebe0c
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: e445cd6d-48be-4fb3-99c8-ede552ddbdc4
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 3c780e79-4edb-41fa-9113-b17753aa66cc
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: eb538693-753c-4299-b053-41821e04a94d
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: b30ef7eb-d3b1-4c74-a813-39129e7909f7
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 8d52bcb6-aa27-42b8-9755-a39b922a896e
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 0c1d31c7-a3ef-4c41-9d9c-8223961a261d
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 2c60dda0-05ce-4627-92dd-8ce6e34bc37c
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: b5de628d-b23e-4bfb-8d2a-5a2e2c33c810
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 5550225a-98bf-49bd-95cc-031eaeb4738d
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 0229824b-f9c4-407c-8f3e-2dcf455333b9
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 8a5a1bc7-82a7-4f01-9212-3c32f82c32d3
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_number =
			
			RANKX( ALL( 'REF_Date' ), 'REF_Date'[year_month], , ASC, Dense)
		formatString: 0
		lineageTag: 1ed908a3-ad67-4ae0-8bd4-3fad157646b7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Rolling_3_months
		dataType: int64
		formatString: 0
		lineageTag: 78c7170c-879d-444f-b7f6-0152f2876927
		summarizeBy: sum
		sourceColumn: Rolling_3_months

		annotation SummarizationSetBy = Automatic

	column Rolling_3_months_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 50b07d45-5349-4b24-9c30-b26edcf22892
		summarizeBy: none
		sourceColumn: Rolling_3_months_start_date

		annotation SummarizationSetBy = Automatic

	column Rolling_3_months_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 582d7f69-0265-4088-9381-68680a0e5444
		summarizeBy: none
		sourceColumn: Rolling_3_months_end_date

		annotation SummarizationSetBy = Automatic

	column First_Day_of_Month
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7a134c44-7462-463c-ae3f-48b5325173f7
		summarizeBy: none
		sourceColumn: First_Day_of_Month

		annotation SummarizationSetBy = Automatic

	column Latest_Reporting_Month_up_to_flag
		dataType: int64
		formatString: 0
		lineageTag: 77717ccd-ac16-46c2-af4f-cfc95181633d
		summarizeBy: sum
		sourceColumn: Latest_Reporting_Month_up_to_flag

		annotation SummarizationSetBy = Automatic

	column Last_Update
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 5402b5c9-3aba-4a64-a57f-57fe27264518
		summarizeBy: none
		sourceColumn: Last_Update

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5c38431a-21bd-4ab5-84f7-c49c559553c7
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column SPC_Flag
		dataType: int64
		formatString: 0
		lineageTag: 7dcd0dec-64c9-4048-a0de-3e24b4987779
		summarizeBy: sum
		sourceColumn: SPC_Flag

		annotation SummarizationSetBy = Automatic

	column YearMonthIndex =
			
			
			
			RANKX(
			    ALL(REF_Date[year_month]),
			    REF_Date[year_month],
			    ,
			    ASC,
			    DENSE
			) - 1
		formatString: 0
		lineageTag: 0bfdfcf4-aa91-4cf5-ad1e-63caf82a4597
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition REF_Date-eeea32ab-ab3a-4823-99b3-a1040d4050ac = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "DSCRO_NATIONAL_LOOKUPS", [Query="#(lf)---First part to obtain the date the report should go up to. Subject to data availability#(lf)#(lf)if object_id('tempdb..#date_end_ref') is not null#(lf)drop table #date_end_ref#(lf)#(lf)#(lf)set nocount on#(lf)#(lf)select *#(lf)into #date_end_ref#(lf)from CCG_Reference.Reference.vw_Date as d#(lf)where Date =  EOMONTH(DATEADD(MONTH, -2, cast(getdate() as date))) #(lf)#(lf)declare @end_date as date#(lf)set @end_date = (select date from #date_end_ref)#(lf)#(lf)#(lf)declare @end_date_reporting_month as int#(lf)set @end_date_reporting_month = (select financial_month from #date_end_ref)#(lf)#(lf)#(lf)select [date] = cast(d.Full_Date as date)#(lf)       ,[day] = [Day_Of_Fin_Year]#(lf)      ,[weekday] = [Weekday_No]#(lf)       ,[weekday_name] = [Weekday_Name]#(lf)#(tab)  ,[First_Day_of_Month] =  cast(DATEADD(MONTH, DATEDIFF(MONTH, 0, cast(d.Full_Date as date)), 0)  as date)#(lf)      ,[month] = [Month_No]#(lf)#(tab)  ,[month_name] =  [Month_Short_Name]#(lf)      ,[day_month_year] = CONVERT(VARCHAR, [Full_Date], 103) --> 103 converts to DD/MM/YYYY format#(lf)      ,[quarter] = [Cal_Quarter_No]#(lf)       ,[year_month] = [Year_Month]#(lf)      ,[is_weekend] = CASE WHEN [Weekday_No] IN (6,7) THEN 1 ELSE 0 END#(lf)      ,[is_holiday] = CASE WHEN [Bank_Holiday_Desc] IS NOT NULL THEN 1 ELSE 0 END#(lf)      ,[financial_week_of_year] = [Fin_Week_No]#(lf)      ,  [financial_year] = REPLACE([Fin_Year_YYYY_dash_YY], ' - ', '/')#(lf)      ,[financial_quarter] = [Fin_Quarter_No]#(lf)      , [financial_month] = [Fin_Month_No]#(lf)#(tab)  ,[Rolling_3_months] = case when cast([Full_Date] as date) between dateadd(day,1,eomonth(dateadd(month, -5, getdate()))) and eomonth(dateadd(month, -2, getdate())) then 1 else 0 END  ---This is used for cinapsis #(lf)      ,[Rolling_3_months_start_date] = dateadd(day,1,eomonth(dateadd(month, -5, getdate())))#(lf)#(tab)  ,[Rolling_3_months_end_date] = eomonth(dateadd(month, -2, getdate()))#(lf)#(tab)  ,[Latest_Reporting_Month_up_to_flag] = case when cast(Fin_Month_No as int) between 1 and @end_date_reporting_month then 1 else 0 end #(lf)#(tab)  ,[Last_Update] = GETDATE() #(lf)#(tab)  ,[Year] = Cal_Year#(lf)#(tab)  ,[SPC_Flag] = case when  CAST([Full_Date] AS DATE) BETWEEN '20210401' AND '20240331' THEN 1 ELSE 0 END#(lf) from [DSCRO_NATIONAL_LOOKUPS].dbo.ref_Dates as d#(lf)where cast([Full_Date] as date) between '20190401'  and @end_date#(lf)#(lf)--and eomonth(dateadd(month, -2, getdate()))#(lf)#(lf)#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

