table LoS
	lineageTag: aa97b465-5a6a-4df1-a68d-0e3c954ffb48

	measure TotalEDHPS = CALCULATE(count(LoS[HospitalProviderSpellNumber]), LoS[AdmissionType] = "Emergency")
		formatString: 0
		lineageTag: 3d0af35b-11a5-4a65-a339-28ee7a08bc69

	measure TotalHPS = count(LoS[HospitalProviderSpellNumber])
		formatString: 0
		lineageTag: 7da9cb81-73f2-4e7a-b958-6158e1b0d1ad

	measure TotalEDHPSLatestMonth = CALCULATE(count(LoS[HospitalProviderSpellNumber]), LoS[AdmissionType] = "Emergency", LoS[DischDate_HPS_MonthYear_No] = max(LoS[DischDate_HPS_MonthYear_No]))
		formatString: 0
		lineageTag: 3c4ca351-547d-4dc2-b764-7fe7fc959a84

	measure TotalEDReadmLatestMonth = CALCULATE(sum(Readmissions_30Days[Counter]),LoS[AdmissionType] = "Emergency", LoS[DischDate_HPS_MonthYear_No] = max(LoS[DischDate_HPS_MonthYear_No]))
		formatString: 0
		lineageTag: 13ff70e1-3b57-43c1-b097-71d58b15a90a

	measure LatestMonth = calculate(max(LoS[DischDate_HPS_MonthYear_No]), LoS[DischDate_HPS_FinYear] =  max(LoS[DischDate_HPS_FinYear]))
		lineageTag: d857153a-63f3-4b02-a126-b584d89b85e5

	measure LatestMonthyear = calculate(max(LoS[DischDate_HPS_MonthYear_No]))
		lineageTag: 8128e2cc-8272-4af1-bca0-541548d4f858

	measure Total0LoSEDHPSLatestMonth = CALCULATE(count(LoS[HospitalProviderSpellNumber]),LoS[AdmissionType] = "Emergency", LoS[DischDate_HPS_MonthYear_No] = max(LoS[DischDate_HPS_MonthYear_No]), LoS[ZeroLoSFlag] = 1)
		formatString: 0
		lineageTag: 4585266d-a03b-4a04-99a8-24c31eb8cddb

	measure TotalZeroLoSEDHPSLatestMonth = CALCULATE(count(LoS[HospitalProviderSpellNumber]), LoS[AdmissionType] = "Emergency", LoS[DischDate_HPS_MonthYear_No] = max(LoS[DischDate_HPS_MonthYear_No]), LoS[ZeroLoSFlag] = 1)
		formatString: 0
		lineageTag: 8646b039-9c49-41a0-8c1c-c0f6bef409ae

	measure ED%with0LoS = [Total0LoSEDHPSLatestMonth]/[TotalEDHPSLatestMonth]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1d350ffc-d389-4101-9a7d-33184e5b1673

	measure ReadmRate% = [TotalEDReadmLatestMonth]/[TotalEDHPSLatestMonth]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 610f6ad7-65e7-454b-9859-0d851d7adee1

	column UniqueCDSidentifier
		dataType: string
		lineageTag: 91fc3754-6e14-4d9a-838f-d64e13a44697
		summarizeBy: none
		sourceColumn: UniqueCDSidentifier

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: 5b7c8da9-1f39-4fd6-a381-0c90119a47c9
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column HospitalProviderSpellNumber
		dataType: string
		lineageTag: 336b921a-6d6c-484c-aa3d-e9853e9ffaba
		summarizeBy: none
		sourceColumn: HospitalProviderSpellNumber

		annotation SummarizationSetBy = Automatic

	column StartDate_HPS
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d9766aa-0ac3-40df-874e-dd04c46247c0
		summarizeBy: none
		sourceColumn: StartDate_HPS

		variation Variation
			isDefault
			relationship: 89be0baa-3d37-4039-abc4-f9ddcf91a19b
			defaultHierarchy: LocalDateTable_b45aea80-1d51-4ed6-bd63-4b0456e9dd5b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DischDate_HPS
		dataType: dateTime
		formatString: Long Date
		lineageTag: 09247d1d-fffc-42b5-b411-9ba082964801
		summarizeBy: none
		sourceColumn: DischDate_HPS

		variation Variation
			isDefault
			relationship: 9e63d83a-a40a-4175-8ead-70a743554d0b
			defaultHierarchy: LocalDateTable_4f99b9ce-c161-4992-8dff-ca0b2d5ba12d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StartDate_HPS_MonthYear
		dataType: string
		lineageTag: 7b87c264-79a1-4507-a346-24fa952bd397
		summarizeBy: none
		sourceColumn: StartDate_HPS_MonthYear

		annotation SummarizationSetBy = Automatic

	column StartDate_HPS_FinYear
		dataType: string
		lineageTag: 48a52800-1527-48a1-9d66-a31e63735689
		summarizeBy: none
		sourceColumn: StartDate_HPS_FinYear

		annotation SummarizationSetBy = Automatic

	column DischDate_HPS_MonthYear
		dataType: string
		lineageTag: 0525a924-6b69-44cf-8a9b-cfd0ab2ba2fd
		summarizeBy: none
		sourceColumn: DischDate_HPS_MonthYear

		annotation SummarizationSetBy = Automatic

	column DischDate_HPS_MonthYear_No
		dataType: string
		lineageTag: cd188bbb-8383-40ac-aea7-d31231a2babb
		summarizeBy: none
		sourceColumn: DischDate_HPS_MonthYear_No

		annotation SummarizationSetBy = Automatic

	column DischDate_HPS_FinYear
		dataType: string
		lineageTag: a6930dbd-b615-499f-b9c8-4bddd3c74fbd
		summarizeBy: none
		sourceColumn: DischDate_HPS_FinYear

		annotation SummarizationSetBy = Automatic

	column admitting_ward_code
		dataType: string
		lineageTag: 88612a33-c9f6-428e-af76-b37c9381d488
		summarizeBy: none
		sourceColumn: admitting_ward_code

		annotation SummarizationSetBy = Automatic

	column discharging_ward_code
		dataType: string
		lineageTag: 1514c3c9-0f28-4809-9d28-7588750034bc
		summarizeBy: none
		sourceColumn: discharging_ward_code

		annotation SummarizationSetBy = Automatic

	column all_ward_codes
		dataType: string
		lineageTag: 5126e6b5-fa0f-41d1-81ff-0e1625a4a317
		summarizeBy: none
		sourceColumn: all_ward_codes

		annotation SummarizationSetBy = Automatic

	column admitting_ward
		dataType: string
		lineageTag: 2ddcc915-8236-4c2b-a476-0b906bd379c1
		summarizeBy: none
		sourceColumn: admitting_ward

		annotation SummarizationSetBy = Automatic

	column discharging_ward
		dataType: string
		lineageTag: 1c75ea82-ac80-40bd-9799-25e02a5257b8
		summarizeBy: none
		sourceColumn: discharging_ward

		annotation SummarizationSetBy = Automatic

	column all_wards
		dataType: string
		lineageTag: c9b0d20b-853e-4d92-8d64-62d52bbd7ed9
		summarizeBy: none
		sourceColumn: all_wards

		annotation SummarizationSetBy = Automatic

	column DischMethod_HPS
		dataType: string
		lineageTag: 07ce9be1-899d-4753-8fd3-5a04a36e3a23
		summarizeBy: none
		sourceColumn: DischMethod_HPS

		annotation SummarizationSetBy = Automatic

	column DischMethod_HPS_Desc
		dataType: string
		lineageTag: 12eb8911-3a87-481b-8911-c8bc42ff022b
		summarizeBy: none
		sourceColumn: DischMethod_HPS_Desc

		annotation SummarizationSetBy = Automatic

	column SDECSplit
		dataType: string
		lineageTag: 1daf30eb-1a43-4d9a-8662-8e6cd895d7fb
		summarizeBy: none
		sourceColumn: SDECSplit

		annotation SummarizationSetBy = Automatic

	column SDEC_Flag
		dataType: int64
		formatString: 0
		lineageTag: 47013a3d-185d-4909-a63d-d78ec3dd4215
		summarizeBy: sum
		sourceColumn: SDEC_Flag

		annotation SummarizationSetBy = Automatic

	column WardSplit
		dataType: string
		lineageTag: 89c724d5-cb0d-47ef-90a2-58ddd035ff0b
		summarizeBy: none
		sourceColumn: WardSplit

		annotation SummarizationSetBy = Automatic

	column TrialWard_or_Other
		dataType: string
		lineageTag: cfb4dd2f-46cf-4cd1-a3d5-7f935558919e
		summarizeBy: none
		sourceColumn: TrialWard_or_Other

		annotation SummarizationSetBy = Automatic

	column WGWW1GRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 10c8d1f3-6acd-4537-bce9-9f13b6593dfb
		summarizeBy: sum
		sourceColumn: WGWW1GRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WGWW2GRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 1c81d0ab-7164-437e-a7cf-38ef399f2fa5
		summarizeBy: sum
		sourceColumn: WGWW2GRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WRYWCGHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 74a9060f-eb88-4fe7-a288-caa1d8d17a94
		summarizeBy: sum
		sourceColumn: WRYWCGHA_Flag

		annotation SummarizationSetBy = Automatic

	column WGTNCGHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: e8c8f52b-b0ec-442e-874a-2eca0ed4ded9
		summarizeBy: sum
		sourceColumn: WGTNCGHA_Flag

		annotation SummarizationSetBy = Automatic

	column WT3AGRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: aedbe413-06ad-4cbf-96b2-810b811ff24a
		summarizeBy: sum
		sourceColumn: WT3AGRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WT7AGRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: ece94bcb-699d-4acc-afe6-cc3a8692d6ac
		summarizeBy: sum
		sourceColumn: WT7AGRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WT7BGRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9e9dc805-e2b4-4527-8e2b-45deea70d5de
		summarizeBy: sum
		sourceColumn: WT7BGRHA_Flag

		annotation SummarizationSetBy = Automatic

	column IP_LOS
		dataType: int64
		formatString: 0
		lineageTag: 93f6833e-96b7-40ba-9080-e8761d3fa859
		summarizeBy: none
		sourceColumn: IP_LOS

		annotation SummarizationSetBy = User

	column ZeroLoSFlag
		dataType: int64
		formatString: 0
		lineageTag: e0818978-6f19-468e-8bfd-ccc2e4214b47
		summarizeBy: none
		sourceColumn: ZeroLoSFlag

		annotation SummarizationSetBy = User

	column IntendedManagement
		dataType: string
		lineageTag: bdb0c8bc-c86b-44a7-93ca-4e8d20be7664
		summarizeBy: none
		sourceColumn: IntendedManagement

		annotation SummarizationSetBy = Automatic

	column AgeasonAdmission
		dataType: int64
		formatString: 0
		lineageTag: 3f208110-f35c-4edc-9f26-2dde9682362c
		summarizeBy: none
		sourceColumn: AgeasonAdmission

		annotation SummarizationSetBy = User

	column AgeBand
		dataType: string
		lineageTag: 3efa8d3b-3109-47b9-809b-9a565b7e4863
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column AdmissionType
		dataType: string
		lineageTag: 78389998-3441-4f51-9b48-61c5ed39aa6e
		summarizeBy: none
		sourceColumn: AdmissionType

		annotation SummarizationSetBy = Automatic

	column AdmissionType2
		dataType: string
		lineageTag: 496357b6-7f74-42a8-aa3e-ba9d8ae34f7a
		summarizeBy: none
		sourceColumn: AdmissionType2

		annotation SummarizationSetBy = Automatic

	column SpellCount
		dataType: int64
		formatString: 0
		lineageTag: 9d3c94b2-5cdf-4d5f-bc6e-6acd9d3928c2
		summarizeBy: sum
		sourceColumn: SpellCount

		annotation SummarizationSetBy = Automatic

	column LatestRefreshDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b5eace18-79a3-4401-9af6-cb7f8d0b52ad
		summarizeBy: none
		sourceColumn: LatestRefreshDate

		variation Variation
			isDefault
			relationship: 44afa7b7-6b95-42ad-9ef4-363cf8cc801a
			defaultHierarchy: LocalDateTable_a4615f49-be9b-4d01-8a83-9c64b96c4663.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition LoS = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "powerbi_reporting"),
				    dbo_LoS = Source{[Schema="dbo",Item="LoS"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_LoS,{{"StartDate_HPS", type date}, {"DischDate_HPS", type date}, {"LatestRefreshDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

