table Readmissions_30Days
	lineageTag: 820d873a-b3ef-4136-9d28-e0c995dadac3

	column Pathway
		dataType: string
		lineageTag: 94a28aef-9d17-483d-bab2-93830ed7f181
		summarizeBy: none
		sourceColumn: Pathway

		annotation SummarizationSetBy = Automatic

	column Diagnosis_pathway
		dataType: string
		lineageTag: 07215c8f-afde-471d-9302-e09f03a03830
		summarizeBy: none
		sourceColumn: Diagnosis_pathway

		annotation SummarizationSetBy = Automatic

	column DischargeDate_FromHospitalProviderSpell_FinancialYear
		dataType: string
		lineageTag: c23544d0-cb89-48f5-bbf8-cb8291188738
		summarizeBy: none
		sourceColumn: DischargeDate_FromHospitalProviderSpell_FinancialYear

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: 35436cad-bbc0-43a8-9df3-352d8115b929
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Admission_method_group
		dataType: string
		lineageTag: 0c7df50a-c620-4cb7-bb21-cc01a78ce07a
		summarizeBy: none
		sourceColumn: Admission_method_group

		annotation SummarizationSetBy = Automatic

	column Readmission_diagnosis_group
		dataType: string
		lineageTag: 5e43879e-8385-4676-bebc-9c38a3b5c844
		summarizeBy: none
		sourceColumn: Readmission_diagnosis_group

		annotation SummarizationSetBy = Automatic

	column Previous_diagnosis_group
		dataType: string
		lineageTag: eb522406-41b4-4d14-b4f8-53845470da67
		summarizeBy: none
		sourceColumn: Previous_diagnosis_group

		annotation SummarizationSetBy = Automatic

	column Previous_admission_type
		dataType: string
		lineageTag: c6845361-6e85-46d6-aa9c-57abb06264be
		summarizeBy: none
		sourceColumn: Previous_admission_type

		annotation SummarizationSetBy = Automatic

	column Readmission_admission_type
		dataType: string
		lineageTag: 871da929-f493-4537-bcbd-ea1932fd9dce
		summarizeBy: none
		sourceColumn: Readmission_admission_type

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: 99e995ab-7d2d-44ca-8d44-1acee2ef1c64
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column days_between_admissions
		dataType: int64
		formatString: 0
		lineageTag: cda6a48b-c0be-4dca-a52c-b7423770e513
		summarizeBy: sum
		sourceColumn: days_between_admissions

		annotation SummarizationSetBy = Automatic

	column Re-admitted_within_7_Days_Flag
		dataType: int64
		formatString: 0
		lineageTag: 0d936637-7ee5-49d2-802a-1bb852bf64a3
		summarizeBy: sum
		sourceColumn: Re-admitted_within_7_Days_Flag

		annotation SummarizationSetBy = Automatic

	column row_counter
		dataType: int64
		formatString: 0
		lineageTag: 3ca5bb10-eb11-4a21-83c5-0124ae46252b
		summarizeBy: sum
		sourceColumn: row_counter

		annotation SummarizationSetBy = Automatic

	column Adult_Age_Band
		dataType: string
		lineageTag: e5d0b38e-584f-44c3-bfaf-d2117544fb25
		summarizeBy: none
		sourceColumn: Adult_Age_Band

		annotation SummarizationSetBy = Automatic

	column Place
		dataType: string
		lineageTag: ad24d43a-1d6e-413e-8d5c-d0b8029e5593
		summarizeBy: none
		sourceColumn: Place

		annotation SummarizationSetBy = Automatic

	column EFI_category
		dataType: string
		lineageTag: 7e1ee09c-744b-43f3-9e0f-65481988d4ab
		summarizeBy: none
		sourceColumn: EFI_category

		annotation SummarizationSetBy = Automatic

	column Previous_Hopsital_Provider_Spell_Number
		dataType: string
		lineageTag: 33f7b963-af37-4b1f-b5b0-7c6929c7db4f
		summarizeBy: none
		sourceColumn: Previous_Hopsital_Provider_Spell_Number

		annotation SummarizationSetBy = Automatic

	column Previous_Start_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d214d097-3364-4546-9534-2fadd102a504
		summarizeBy: none
		sourceColumn: Previous_Start_Date

		variation Variation
			isDefault
			relationship: 9ef86878-b7e7-41d2-bfc2-a958ceaa8802
			defaultHierarchy: LocalDateTable_526d912e-6349-4637-beb4-10103b31ac1e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Previous_End_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d61c19a9-86a6-4030-96c1-0caebe52f923
		summarizeBy: none
		sourceColumn: Previous_End_Date

		variation Variation
			isDefault
			relationship: f0fd8ed6-88a6-4c4d-8561-5598fded21fe
			defaultHierarchy: LocalDateTable_fa831dec-a870-43bc-96d3-c5b9c3a3d767.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Readmission_Hopsital_Provider_Spell_Number
		dataType: string
		lineageTag: 573775b9-d8de-4995-9475-d38845321c27
		summarizeBy: none
		sourceColumn: Readmission_Hopsital_Provider_Spell_Number

		annotation SummarizationSetBy = Automatic

	column Readmission_Start_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2049d9f1-b913-4f38-875f-5b46d05e671d
		summarizeBy: none
		sourceColumn: Readmission_Start_Date

		variation Variation
			isDefault
			relationship: 4c2230d4-f848-40cc-a3e0-256520ccdb5e
			defaultHierarchy: LocalDateTable_649a893c-eb44-4673-97db-9fe71098a8e9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Readmission_End_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a28ab7bb-c061-4f67-be75-4312707401bc
		summarizeBy: none
		sourceColumn: Readmission_End_Date

		variation Variation
			isDefault
			relationship: 754846bc-0fcc-4df2-be71-48d62725642c
			defaultHierarchy: LocalDateTable_3065c605-0fb3-4250-a990-63629ae7302b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Previous_Admitting_ward
		dataType: string
		lineageTag: 66e42af2-6f19-4a49-9eaa-e966c0e0e1af
		summarizeBy: none
		sourceColumn: Previous_Admitting_ward

		annotation SummarizationSetBy = Automatic

	column Readmission_Admitting_ward
		dataType: string
		lineageTag: b06c6681-71fe-4060-855a-4fc10db56e94
		summarizeBy: none
		sourceColumn: Readmission_Admitting_ward

		annotation SummarizationSetBy = Automatic

	column WardSplit
		dataType: string
		lineageTag: 85cedb95-8139-48b2-a78e-d4ae6aeb2a3e
		summarizeBy: none
		sourceColumn: WardSplit

		annotation SummarizationSetBy = Automatic

	column Readmission_Year_Month_Desc
		dataType: string
		lineageTag: 0ed0e0f4-3baa-4bef-a921-73c51d3d6c45
		summarizeBy: none
		sourceColumn: Readmission_Year_Month_Desc

		annotation SummarizationSetBy = Automatic

	column Readmission_Year_Month
		dataType: string
		lineageTag: f3981ba9-7a94-4523-8696-2961a751f50f
		summarizeBy: none
		sourceColumn: Readmission_Year_Month

		annotation SummarizationSetBy = Automatic

	column Frailty_Proxy
		dataType: string
		lineageTag: e0c67591-c871-46ae-961b-2c356db7fafb
		summarizeBy: none
		sourceColumn: Frailty_Proxy

		annotation SummarizationSetBy = Automatic

	column Provider_Code
		dataType: string
		lineageTag: 1be6042f-c5cb-41b2-92bc-29c8b862c81a
		summarizeBy: none
		sourceColumn: Provider_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Name
		dataType: string
		lineageTag: 2fb851e0-4e75-4885-9cfd-bde813af9223
		summarizeBy: none
		sourceColumn: Provider_Name

		annotation SummarizationSetBy = Automatic

	column Readmission_Provider_Code
		dataType: string
		lineageTag: e8472af4-611a-4fb7-8009-fd81a4779c88
		summarizeBy: none
		sourceColumn: Readmission_Provider_Code

		annotation SummarizationSetBy = Automatic

	column Readmission_Provider_Name
		dataType: string
		lineageTag: d0ad5d42-1740-4368-ad2b-f0eb2260ba70
		summarizeBy: none
		sourceColumn: Readmission_Provider_Name

		annotation SummarizationSetBy = Automatic

	column Readmission_Method
		dataType: string
		lineageTag: 7225a854-e3d0-4224-afb4-b4a5577d6609
		summarizeBy: none
		sourceColumn: Readmission_Method

		annotation SummarizationSetBy = Automatic

	partition Readmissions_30Days = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "powerbi_reporting"),
				    dbo_Readmissions_30Days = Source{[Schema="dbo",Item="Readmissions_30Days"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_Readmissions_30Days,{{"Previous_Start_Date", type date}, {"Previous_End_Date", type date}, {"Readmission_Start_Date", type date}, {"Readmission_End_Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

