table 'REF_Baselines Meta Data Table'
	isHidden
	lineageTag: c42c5906-a923-4b5c-971f-1eefb1bbbd77

	column 'Baseline Metric '
		dataType: string
		isHidden
		lineageTag: 5ae95838-a1ca-4b14-861b-22bb26ddd63d
		summarizeBy: none
		sourceColumn: "Baseline Metric "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Read Codes Used '
		dataType: string
		isHidden
		lineageTag: 21a39bf5-1dc9-46ad-8e43-8e2b4300b678
		summarizeBy: none
		sourceColumn: "Read Codes Used "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SNOMED Codes Used'
		dataType: string
		isHidden
		lineageTag: 9767466c-a377-4164-81f2-cce82de12dad
		summarizeBy: none
		sourceColumn: SNOMED Codes Used

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '  .'
		dataType: string
		isHidden
		lineageTag: 4160c650-1c51-49ca-bfe9-09666f84271f
		summarizeBy: none
		sourceColumn: "  ."

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Addtional Information '
		dataType: string
		isHidden
		lineageTag: a15350f8-12e1-4c1a-8487-8ce69cbe5823
		summarizeBy: none
		sourceColumn: "Addtional Information "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'REF_Baselines Meta Data Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVnZUhtHFP2VLj+JKqBm0UbeBEhYxiSyUECQ5KE109J0mI3pGWS58pDPSH4vX5LbPfttFjmOKUGhq777uUuPfvnl3SyJ4ihJeRQSeKUeI1uPp2wV0cQtKTH1fU5T/sSIQxNGErbhImXJu8N3v2aGYQ2WdNnt5/8elpR5b6RRThFlZXoaZa1RmEbZtCh3BqUrjeJoFNqi3N/0BmdI8n2wQpRPw+u2HGoabckn49PeMbbw0UKUu/lOo5y3KMPTkYXl3DMTUdj4HFGmsY+5VgONgnNxv8Jy7ldjLV+GRrExZTLBFt4JjZJqlATH+eGDRvlRo2AL2fIJUeh0jiiz4BHL2eCoLn++QBTHxVh1Jg9tJNiu62gUiriuPI51RbcaErCu+QTb8+FJQ1R8o2k/QWfGH3DE7lfYnmk8xTE8b2d5+H7w8RhR+iOM1WU0Q5RNgJEw2uAuMWKfsT3+Az5zi5EwWvQwl8BdYppiXVOBe8s0bVeKeW+Y2K/RDOfr4yWO2L23zf/9NYSeeAS/8vXb4RvtdctTj1AyZ2I2PluQdZQEwHdnr9YljEiRW3PtFJg9OoLzThQELHSZS66zIKDJjsx8GkoBZBywZMNCZ0fOZKumoUsWCaMpnE+VdYWnpjEYnpiG+jGNflufaQ+tvlF9WgTpq9xymdTIKel8+mmSi+2TH6PwSL51IpcJkgnmVgZNwCIUevizRYE2/Pctyuiki7jGFm6j48ywvmCK2W4BY8PEXIbRRfaMTXqB5RiWRtG0G5p2y9QompxnvNhpFFuj4JZ9ubtrUSa7zDa0aOywp/d97UzbC8iOjQve6n3AZ+a4mKeXuNlNL9EY7hnvMw0Jgaa9jQSZry8aBWfZ6NoapR35iWXuEMU0P+OBal60vRh1Tdw44M9nzWYUeTAQtxtDjDEXWqTGAARTk3ynad9pZ3QuW6N0ERKMebuJm91+KaY8MzCu2hb+vDIXfU3ySKOgAWbZa7x+jcxrzS8dh2g0js0lwg+1mc7la5QlzrueU7unUXRP8XjYeG2/AHWm1m1MDb1ajzJMDb2mpWn/qFEuNIpWp/YtpszxwjEedLF2W/MCdzZD62NaBiXF0Oy5RNpXN7F2ZqHVMq4vGF6YgqcMoEVokoslMh/nXzfPz2josESNPSWkf3E9OSDA/5GmTKTl5+0xSJ66w33PwGvhcUF46PiZ/DCGqxnMWgHm0JR4FK5pNOfNxbicbsJIAIu0OiErBosCU8Y7LBSZIC6oVatCFPq7UjAciAQrlxTwgnQuIh9WjhROgruCTBIasG2UPBwoM+Fe6ESJ3Er2Xn1CWAg0KztS16xw6gDcle/zOByRxvWGwC6kLBKVRevSIhInkRSXcgf8cblDU/AcDm4YGZHOys/YAUjbMZqQ2IcQFOe5KHegxq3pvyo6JZ1NwlgoNQVRmHpNNY07GMj/L+LPSGfHfD/aSvlbxh6w+PG3mX9OOglzpXCX7hqyVVU0czLs9gb1tlh0ie+THKnKqlQNv0nVq+mRinqVIvv7JUoqGuBV+7ukbI/GEf7z598p2UQp1GZRl63KPny9hayyqv/s0y9AVi74+LmO0XwOtV6zBBwDubOz6xkpLlnFRmJbTUwUd+AXe7behJRIuFLFPktl8yoF31lD9OwJKBat5BfqzeHgxKzUl/sBaXxq4drYd6DUDd1ljs/DKgJFAEgjAqYGVgDRHzOWiCikPpcDpLoRXmexVKpujSEPN7X4juBpRqU5B380rFxEKfXJ1fmCBIylwAHgAWxIlU174yjOfMXdeDT4aR1XoL7K/JS7XDg8Bn3y4pqwJ862rUGrQBqwNAGAp1KxUHEJs2AFOqO1siPnEwWABGHU8UpAQ8gE/Lqvg9XlT1wOq9VOfSSYzxyZ/2f9ISkPoGKkw8fknK0pOFKwyE+FF4Et1Peh5CiQHCbLjFz4UQb/ppAEjyfsLZgXeIwTVsA99qnDpMcu3OC9qgobwZ3Gy7pjzF5grJ8i2Zu3T/9AvChgpHPQYPP2YxMxeE46iqPJzmtEvswuH2pkIU93uSAJuIaI32sL3jIBcT7Uyl9jDbNEyFJQzlfsn7487qU4TkkW0pUPMIsI+wwpFKJIJIM22hSY7CVQFkkmhARJKNtxDL08TrgEbkNWuk9eyqrIQihzBflKwrz7uI8EHyZx3ie4oCvuyyTJVDUFiX0EyWdCkB2PUR/wjEVkXxMZVtTLmgYcltZKzM1220j4K3CTzbCd7OVP6X7JLgJadc1Gsiphd6KG7MuiMpFBPCoqwAYS1ALMenG+T/WEURNub11c9KaT67iVA+eKprJjSSRfFfNPPZt8dkbalttHExGG8YnVNcpHY19txBUMKbBiR06hdb6o/85cM1qn658//yquDGrCyezK3UWuMCHs9FCS0KpVKxfqwJYLjwlYd2r8nVptccXozJESyweslQFtPqPie56txEmby35Lm9p6FJdKJ+wW3cYqMWgp/RbXe5Zt1Kuu0SiBvaMgRZh4y3nZMz0gUsAA73Cv2IBiUwKsfvo9cgOuKlIocMEwPjHypbgap9UGo97CvXM2uwXnPLkZ3cDbsygL090WCvLgoFi4ntlQ4ObAYQHPd5RE9mdQwCo76It2QDeH5QSKLJ/R5dSQtS0NO6wtO1Qhp4nswKkHVxaySaIsFj8onbd1GeXGyyX9aIupKvVyQ0FLyVH5ba5UXF4IiojAlcIlfSN/NPDEkmOyeE5hfaOQ9xHYqjK5s229SI4tGB2s+ia5wepmhT+s8AkQK5iTqa+Zi+sYzB1XHspiGSc4ypPctOO8nUC+6l6sLN4zT/UuCTPoMau/0q6DUEpUOzj2oxFdHr5sfzvFxfonvwTRLf9OhrvcLfcHeZv+H8xXPTxv4Wsi/SjU7bu8KjC5nBWqZUoxz/OxgFDAnIUTuzwUcWOY5JYUaGz6L28B/4tRxw0NVX20Hpe1b9NbljQeiFFRhl5KAR12Hm/I4OsB/+1f", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Baseline Metric " = _t, #"Read Codes Used " = _t, #"SNOMED Codes Used" = _t, #"  ." = _t, #"Addtional Information " = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Baseline Metric ", type text}, {"Read Codes Used ", type text}, {"SNOMED Codes Used", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

