table 'REF_Meta Data (Codes to bring people onto the dashboard)'
	isHidden
	lineageTag: 9038dfeb-36f0-4087-80a6-3e9d8c3ef85b

	column 'Criteria '
		dataType: string
		isHidden
		lineageTag: 3998500a-ef4e-463b-ad32-18b8892d261c
		summarizeBy: none
		sourceColumn: "Criteria "
		sortByColumn: 'Criteria No.'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		isHidden
		lineageTag: 1cad32bb-370c-4807-b37d-643eef3d35bd
		summarizeBy: none
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Read Code '
		dataType: string
		isHidden
		lineageTag: d5ef6873-a6ec-4ed3-92c7-4f57eb844fce
		summarizeBy: none
		sourceColumn: "Read Code "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SNOMED Code'
		dataType: string
		isHidden
		lineageTag: beb79f5e-ba99-4f7d-8f7c-28e5c3d95270
		summarizeBy: none
		sourceColumn: SNOMED Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Additional Information'
		dataType: string
		isHidden
		lineageTag: b60216ca-01d9-4638-a296-02a93f6ae67a
		summarizeBy: none
		sourceColumn: Additional Information

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '.'
		dataType: string
		isHidden
		lineageTag: 2e6d4e9a-b347-4485-ac91-6911c070349c
		summarizeBy: none
		sourceColumn: .

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Criteria No.'
		dataType: string
		isHidden
		lineageTag: 42c57fff-1f7c-49e8-8180-20df0cf2fade
		summarizeBy: none
		sourceColumn: Criteria No.

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'REF_Meta Data (Codes to bring people onto the dashboard)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pVtrU9u61v4rmn6CGaB2EhLY77wfAoRCS1tK2m4omw+yrSQ6sS1vyU5wf/1ZkmxLvkHo6XQgl7UerbuWlsXj4zv33cG76ZLAz38yxxmS/x878Fr//xqHOaKxH2YBESjBKSVxKlC6winaEk4QXpIAjR2E4wCxDeGIxfAtQT6JRSZQgFMJ/O7p4PHdAF4gtOe4q310q5HQCguEkc8CgtgCfZhfooSzZcxESn1YN6A+ThlHWhgp3mByj395E/2y+uxkdDxxXEf9c51R9W259FCqcifX9uprg8T5e0E2UhV/xVkMyzJPpDzzU7ohKMnCiMWY5yiggmBBClHu8ez6QS+DDg/nbwA4uMdfRrhi/QkCoLcI8E9cOUepNqpUIw2zCm1XGqMFDkOhXCRdA4sBCXgGI058xgPwIBXII+mWkBhpXw7G4F+yFmjBWVRnIxWS5WSEKrG0bgN34pwM4JV+e3B4OPV9GgAGDpVA6KAgPD0ZjkaOMy4IwShoFgaEQ+TZdO6pa8EB1SV8WX43dk9OT5zS8+W3olpjcnp6arj35Rp3xM84lzop81gmPa5M6jcj9Y7Mb2fn39GC8chYz9b7YegtcClG8ZG78N1GxLquMzk5rUJ2XOdwhyeDsQnoSSugx5WIQVPECJzOwSNlWC84pmGa62CoRN7SdMWyVNFz9blEKBMxWeUCUi8EF2AVh+8jGgYl1FE9Hb3A0y/BqJ+LxUvSA0MUVDGP5jXJSqV/eA6bVEi3TRFKMollUg99tgQzwTc4GY0mjnNs6HrxTgfHE+MIx6hSBy4tP6ksv+wsY1TXv9tzF+3dwnIUqzw+x6DweZiJlPB9lUDkuaiq4AioK9IhDW9oUWKGQhYvobQmFVyhllyw4Yz70bhKOFlORZYkjKcb5EsBRLokaIgOUYiFzOVc/AVfpOgMPopg/aL4UvFPXALeHU//APAcPtpC9egEPPsDwAv4SL7rQvTcVYXYNPktZ15IIh1yFNJg7ksLH0LSQ0jn7+Wi3IZavB2KgcM5EnmUpCyqyUXeDpZgGtsQyyaERtAABb/NLnJ/xUK2lLH+XiQUwDMclogPDsZe3fwpTqGG48gzdpBUfhfVksMOYVPhLipOgpLm18/jyXlF8/jzybKDNL3R9Fdk5JpGXhbi2IdwIHxD4XfMUrqgULdkcSqSDjqNGbvRYcPJksrUMnjfTuYGL4Z2giaylcitLKpJ8IBdx+h8zqIkJCmFNWDF+Z2LIiKbkRBWktFacp3Ozo6PKq6LOXKPHQddUIE9Gkq3hnRD4yWCNdlWaeRrZGMicPK/ZpOcxUrHkC5gmw02mkVqmIBBDMvDXb4bCwqIH9LYXu7h7mJHXk42lGxbECdn08FRJ0TDpcTtpZJeXG1xbqjJrFssIw5bLAi3NblOworlksbgHV0imtBVw1jEaWePCcELpWeK9rwwg1bqEOVQcaFgd1WcX950V8AztKeyRiJCJ5euegAvdgU8R3s5keEkEXWP1gk42xXwAu2BVfdfKLB3x05XyS5TqMBxAUHHkIz4ql01IMMdQAYAAucNDrwKRYeehXJ5WaFcwa5LdssX8iB62RT5muRoSWJoXkKwgOwQZPLbBYU8pK9DxBm3dSYP/HWeLePrWuVaf3yZqYjvHWT+tv6yO1RD9m/r2e68TR3I/eYV5pp78PVdRX4dp2Qpe8igoOSUwSZGoVOCrttGMvy30b+GX4hMN7H1Qg9Nl7UL6HKuCrzHni2tl6Zm3ZQtSHvB+x8f+slk7PuZEHap8oOzOkNRC1rI/uW6TqhTvEH3MAwCs1vd0IhKe6nFyXNC/BQSIZdMOIF8fqYR2BM6X4gOlBPMbRi8C4xqS+HUH7cg7vHnFbUgoB1JGAvrISIdJ7viIIektqzI/n4TZ7X1d21qxr5f5T4hpX6xOBS7m11ajE+/xu2QbfcYHzcDm2PJ4MQAZSwOMA9EK/7gLBERmSiW1MlPG+At1pOuO7WZm8u1xZ19NBnd34d5tI8IjjlxoIY86vjb0clcJ9ddzCmU8zQCx1kZf2F2g1tOhM9pUrZbOyZu1Y5cTW5MO3JHFlpABLpHqimwFTy5Gk+bxCmr04JmscjC1A7U2zqPLLnABiaIslj2eU2ZU4KjjjBdRqITqBVsReNrOKfLcSdnc2F9dKd2dZ2S551YW2teh+sGI1SHmtoCigTFIQRapwUsGf42O9Fcjpm8ts2Ua8Fe0AK01f9+/Cp/h+rXwhzB5i/I2g7Q63T8Jk7dPtVz6Vos3opB46LG2ZJM3orCsrQB4/5yXBP338twp2EYEyHUeTstejDL6LemPv+IA0gVtVJHinaY/ubT9Y7MLWf/Wm31y/1XWY09VPtihkTkuRgKyOFP1wxFz02uF6q0lhtLOUJrj8Q02AvDGIBRox9ohsCqyJMIEVTLoByhUgERnnLql6Okk2qUhOUoiaYxaY6SLmaf0d45C4rm54JIB1Mg9/UoyR7+XLquY1w8DX+vCI1I0YCKVkMOP7bm5FoAGx844VX17WcohvSQxgvMfbn51mmnpyNr3b15nqzk2fcv9JhiDwQPGBfSRU+PIgGVhB8S/rSPQJ29kEEpYSnCKX4GrUrE2cA+YD7ewrnlEGqy7Kmg7j89JvKDlOMsQh7HtPxkRXAARvvPExJ5HIDRK2VnmTP4bQDvnypLgpRZrKJIjheepFSPMezTAdpgDvGcCrSnGMfoy9f5/pOF6Lo2ogUY2ebSkAlUTiZTLk5DOYqFc4+PQ4PmuAPbdT5bsRCOaoEBVUMmDQaCWJzOyOLkEBOUKROz1AJAe/ohjmyitHyo7s6nyvj3Mxd/aAVGZQWpiiAxDYkWpni9bxnGmvlbhpHh3BWUB+D9PFGzFcCL6LPcY/LE9p0VXjsA2lEumX+/lfkAWSFhh1CnwyXSOSdZ+ntBwiA9/IjXzOuQY9BrlasMXsXLlMX9Wgx6TaCnjwWHgMKAIUvUrIyEgmzhyxpO/jJOpXcLsRtu2Ad3i/maxuJFnZxeZuqv++oW/pQ/2Hw3ZJvDGS7IW4XpMs+GtSW+KhV3iBk3b7NtMBzqQsxby0DC/Brb9D9iy4oNYgleC8ifTdjO6INqPTQt6NT/N6OyF6OyD4ODAVnA5kvkWa2sfCbzdZtuHXEHx2a+0C411op36xfoZDm0epRPZxZtt331Iw44OqqDqCB2i/PpfEd21abUuY+dq8xwRwQ2FQhSj7NVnrAVDXQlbG4Jcv+LLLacpZzBzuWrJWSHrKuogG1brdxhoKHZIqd8mSt+aSO1KbXCCir1b4u+r1JbdpUs7g4shXwh5TSLbObh7syyrAvrVCXZB7uyJ5jjmFmZN3Bzw3wGdWCLZdfUk3HQuTybHvdceU8Oc4mebqlzYZARefR4tdLeY/fD2StYegtL1USB0wg2+jDvdvJ05Fpt8+uLww9z1tplr+lPCggv5w+g2gkygyA66kSCnipQM0OBZudW6ydmbXJogaGPVU/vQwbNrb1Fg6zWU8ILaMhzmTZQkEiywiGTg4zciDPITVBf8GwJrVKQ+R3FUtrA1PpZAo1GknbXKmtfu5RP9kCGfkPJ0VC3xd23oXRUIwAxWXfJ/BcQbJ6R4ZFWZimJEqYDt7nbOHdmhvChHP/CYUianOnjDCQcNlNzdzQ2el29//pXG3TifDYO/JhtVFNnhssavaT+4bnfzYZ3A5mdydE9aCXvFqjJW5cnzQLWlt22hJmIfVa9YNksq4fmIvOq970b8sNguPAaKC2B8NQ1Dwi/kG3Z70vpd8pzU8u/sPhw8T8E3eDtSB2BN3PvzTaoWxbcv7vjIfndoNad/Puqv+90onng1tfgyUFIo/eQj2o/ZNY4CIDuLaDUX3V0b65del/qCAHt+CVCXRjlFzLoKBE253hHTp+Ud6hi1odlDT+rEyruLFh4uTIRett5OGy3jo49wrntdZOk+/0CXaPDsI6xHbR9rYU73IGro6dwB6/yNZsJadkbi0vv4FAh2z2WJP1gkbKlkmBDEIaNSOx2ZpQgpkO+zWIfdOFZvO7qIYdmQjYnkZpUd7bSA4usO7nwbDLqIyrruimctRMyiHHUy9rnQes028PS4b7Bq+skpcUZLz0ZoAXBacZNssxq9fNPkBpBbB0lO9G6YuqTYUlYvKTqoUZ3z3KPvZ+JTc5xAI7eZZ8Yfjd8u2xesu82yvyIVQmVTzxgE8N9XbidYH3M/XUduKwJS52rbyuA3cZ0Ia0zrK1/8WS3g0o9n/Szcier32s9rYajC1y/aDdAKyYSKjtRHERUhag+o1F5exUOCdXl1SJtGpeRy//f8ZrEejobq4OBHIiX83e0N/8x31fXZI/Q31JEqM0rDOGobs6y2Dz/spjg4G5dteVkoZ+bEqRuZKFFiJeiNnCmCz0zVshLloJ2Bk0+R15hviSVei9odoQuMOweamSj0Dz5mKS4ZRgcoevyFrfH5IkD6t9STQzUXcSQ6OvGxqBHpSNcx3jCa3pCTuykipYj9D1hNcDe0SfNq8PDwejk2ClvvUI/oe8QmHvibf9bgeO65m5ssF/e22X+essYxLO6JwcYY6U49tiG1K9jVpfcO25k6rG8AG9u5XND+Tx8jPboETk6MADyqqy8uyyvjlZo+5V2ZcOhf01q705q705LAxz2Xeq1Vi1a/RrAoPZuWHs3qr2zLsqqO9py+CTQgqZ6JtuhkHXn9BtdW65C5ziG6gimmadZoG4PXBEcSluCmadLeeqWj0VVGSwvJwt4QyrIyXg4GI+c8jJuKfHoeOSOnI7b0K7804KZtIQKwf8zVpH3x+t/taBSAwKQctVEi8Kpe1mingPXI3Nf81BhLk5j8fqjoPqV3NqTqOYj9RhSvriHLnu/wi7qjy4CXYKtsvj0Xw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Criteria No." = _t, #"Criteria " = _t, Value = _t, #"Read Code " = _t, #"SNOMED Code" = _t, #"Additional Information" = _t, #"." = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Criteria ", type text}, {"Value", type text}, {"Read Code ", type text}, {"SNOMED Code", type text}, {"Additional Information", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

