table Date
	lineageTag: 41fde9ce-965d-445b-a0e6-375f4320dee9

	measure 'Current Date' = TODAY()
		formatString: mmmm yyyy
		lineageTag: 7daa4a16-67dd-40f9-8e20-251033c1cd0a

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b1cc181-c436-4db5-8eaa-9d1278ca32e9
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 6e27782b-42ee-4ebd-8afb-69f756c7e514
			defaultHierarchy: LocalDateTable_13f86f93-98dd-40ea-9ed6-fb7ee9af93f2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: fd553e38-cad3-4b01-86f2-e6b58ee86234
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: de16c2c4-d428-461d-aa53-310585c32b54
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: a4f2608f-e640-4ba0-9493-f43b4b9f719b
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: f282a101-babd-4659-9226-330532217b7f
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 969f705a-11c6-470c-b214-1f110c75e19c
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: e3e70410-5210-432f-b6d1-0d7df66e8122
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 0fa9998f-3ef4-4b27-b417-50d6c0801c2f
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 3a0b7ef1-6c92-4461-bdd0-74a793b9b8ca
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 0a2ed427-7e96-4e20-b087-f8ac1ccbb0c1
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: df5588c8-7545-4310-b2ef-2b56759f4f0a
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e89fb0a8-d48e-443d-ad2e-f3746991a6ab
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 5d2e9a5d-a56d-413c-92c7-943261067d9f
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 69ed8fbb-9e05-4dc3-8039-cd66301b0cb2
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 292775df-a37d-49ee-82ee-39f7a7c4fdc9
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 1dae739b-605c-4a58-96a5-c44c8e24b23a
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: a3586a5b-6293-4e9b-bd86-559a49ca38a4
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 16a64222-83c9-4415-95f8-b5960f7b15ba
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column ytd_description
		dataType: string
		lineageTag: 9419d029-4a29-4e70-829c-d02249ed791b
		summarizeBy: none
		sourceColumn: ytd_description

		annotation SummarizationSetBy = Automatic

	column Current_FY
		dataType: string
		lineageTag: 510cbec2-d60c-486a-97ba-d30800718ef5
		summarizeBy: none
		sourceColumn: Current_FY

		annotation SummarizationSetBy = Automatic

	column Last_FY
		dataType: string
		lineageTag: 89bdac5c-ea83-48c3-a892-03cf33bef492
		summarizeBy: none
		sourceColumn: Last_FY

		annotation SummarizationSetBy = Automatic

	column Current_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: b53b4fce-0744-418e-ae98-d674e1c0238b
		summarizeBy: sum
		sourceColumn: Current_FY_Flag

		annotation SummarizationSetBy = Automatic

	column Last_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: c26265fa-f085-4cd1-9771-cd6d48ee6523
		summarizeBy: sum
		sourceColumn: Last_FY_Flag

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="#(lf)#(lf)SET ANSI_WARNINGS OFF#(lf)SET NOCOUNT ON#(lf)if object_id ('tempdb..#FY_flag') is not null drop table #FY_flag#(lf)#(lf)SELECT distinct#(lf)#(lf)[Financial_year_abridged] = SUBSTRING([FinancialYear], 1, 4)#(lf)#(lf),[Current_FY] = case when cast(getdate() as date) = date then FinancialYear END#(lf),financialyear#(lf)#(lf)INTO #FY_flag #(lf)#(lf)FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)#(lf)ORDER BY FinancialYear#(lf)#(lf)if object_id ('tempdb..#FY_flag_2') is not null drop table #FY_flag_2#(lf)#(lf)SELECT #(lf)#(lf)[Financial_year_abridged] #(lf),[Current_FY] #(lf),financialyear#(lf),[Last_FY]#(lf)#(lf)INTO #FY_flag_2#(lf)#(lf)FROM #FY_flag#(lf)#(lf)LEFT JOIN#(lf)(SELECT DISTINCT#(lf)[FY_abridged] = SUBSTRING([FinancialYear], 1, 4)#(lf),[Last_FY] = financialyear#(lf)FROM [CCG_Reference].[Reference].[vw_DateLookup]) AS [B] ON [FY_abridged] = [Financial_year_abridged] - 1#(lf)#(lf)WHERE [Current_FY] IS NOT NULL#(lf)#(lf)ORDER BY financialyear#(lf)#(lf)#(lf)SELECT [Date] [date]#(lf)#(tab)  ,[month_number] = DENSE_RANK() over(order by [YearMonth])#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[A].[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      ,[MonthYearName] [month_year_name]#(lf)#(lf)      ,[ytd_flag] = CASE WHEN [FinancialMonth] <= (#(lf)                                           SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)                                           WHERE [Date] = EOMONTH(DATEADD(MONTH, -2, GETDATE()))#(lf)                                           )#(lf)                                           THEN 1 ELSE 0 END#(lf)#(tab)      ,[ytd_description] = CASE WHEN [FinancialMonth] <= (#(lf)                                           SELECT#(lf)                                           CAST([FinancialMonth] AS INT)#(lf)                                           FROM [CCG_Reference].[Reference].[vw_DateLookup]#(lf)                                           WHERE [Date] = EOMONTH(DATEADD(MONTH, -2, GETDATE()))#(lf)                                           )#(lf)                                           THEN 'Year to Date' ELSE '' END#(lf)#(tab),[B].[Current_FY]#(lf)#(tab),[C].[Last_FY]#(lf)#(tab),[Current_FY_Flag] = case when [B].[Current_FY] = [A].[FinancialYear] then 1 else 0 END#(lf)#(tab),[Last_FY_Flag] = case when [C].[Last_FY] = [A].[FinancialYear] then 1 else 0 END#(lf)#(lf)from [CCG_Reference].[Reference].[vw_DateLookup] [A]#(lf)#(lf)LEFT JOIN #FY_flag_2 [B] ON [A].[FinancialYear] = [B].[FinancialYear]#(lf)#(lf)LEFT JOIN #FY_flag_2 [C] ON [A].[FinancialYear] = [C].[Last_FY]#(lf)#(lf)where [Date] >'20160401' "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

