table '5. Weekly - NSHE Sitrep'
	lineageTag: 6e1f6692-ddf8-484c-9654-bdff5967bed1

	measure Adult_Occ_% = (SUM('5. Weekly - NSHE Sitrep'[Total adult G&A beds occupied]))/(SUM('5. Weekly - NSHE Sitrep'[Total adult G&A beds open]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Page 1
		lineageTag: a30d7231-9ca4-4242-b990-2e366200ca6f

	measure Adult_Occ_Plan_% = (SUM('5. Weekly - NSHE Sitrep'[PLAN: Occupied G&A beds (Adult)]))/(SUM('5. Weekly - NSHE Sitrep'[PLAN: Open General & Acute (G&A) beds (Adult)]))
		formatString: 0%;-0%;0%
		displayFolder: Page 1
		lineageTag: 5521a275-e938-4564-98f2-2621f36db375

	measure Paeds_Occ_% = (SUM('5. Weekly - NSHE Sitrep'[Total paediatric G&A beds occupied]))/(SUM('5. Weekly - NSHE Sitrep'[Total paediatric G&A beds open]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Page 1
		lineageTag: aacdd147-e2ad-494c-9749-e06855f831de

	measure Paeds_Occ_Plan_% = (SUM('5. Weekly - NSHE Sitrep'[PLAN: Occupied G&A beds (Paediatric)]))/(SUM('5. Weekly - NSHE Sitrep'[PLAN: Open General & Acute(G&A)  beds (Paediatric)]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Page 1
		lineageTag: 5f128f5f-b123-421b-9dcd-4bbf4fbfe234

	measure Community_Occ_% = (SUM('5. Weekly - NSHE Sitrep'[Community Beds Occupied]))/(SUM('5. Weekly - NSHE Sitrep'[Community Beds Available]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Page 1
		lineageTag: fb3e11cc-9977-4c9d-b3a5-57e2d29ca87d

	measure Community_Occ_Plan_% = (SUM('5. Weekly - NSHE Sitrep'[PLAN: Occupied Community Beds]))/(SUM('5. Weekly - NSHE Sitrep'[PLAN: Available Community Beds]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Page 1
		lineageTag: 94aadee6-9dd3-48d0-a7e2-c4edefe64ac2

	measure Avg_Response = (SUM('5. Weekly - NSHE Sitrep'[SWASFT: Cat 2 Total Response]))/(SUM('5. Weekly - NSHE Sitrep'[SWASFT: Cat 2 Responses]))
		displayFolder: Page 1
		lineageTag: 29cb1bd5-7c0a-463b-81f4-85d0b2b42284

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_Handover = ((SUM('5. Weekly - NSHE Sitrep'[SWASFT: Handover resource hours lost (>15 minutes)]))*60)/7
		formatString: 0
		displayFolder: Page 1
		lineageTag: fd90c256-88e5-4ef3-850e-8a90a500f0c9

	measure Type1_Colour = if(sum('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 1])<sum('5. Weekly - NSHE Sitrep'[Type 1 A&E Attendances (Plan) (GHFT)]),"#00cc00","#cc0000")
		displayFolder: Page 3
		lineageTag: 5a531ff8-679b-46c8-b709-35fc34a1f9b3

	measure Type3_Colour = if(sum('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 3])<sum('5. Weekly - NSHE Sitrep'[Type 3 A&E Attendances (Plan) (GHC)]),"#00cc00","#cc0000")
		displayFolder: Page 3
		lineageTag: 9a7aacde-b611-4844-8f92-07292d770f19

	measure Arrow_Type1 =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 1]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 1]),'Date Table'[last_week_minus_7] = 1)
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_High<Previous_Value_High,UNICHAR(UNICODE("↓"))))
		lineageTag: 405e7ea0-f6ee-4a4a-90d8-b673d1e84193

	measure ArrowColour_Type1 =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 1]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 1]),'Date Table'[last_week_minus_7] = 1)
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,"#AE2424",
			IF(Latest_Value_High<Previous_Value_High,"#78BE20"))
		lineageTag: ec00f4d9-3a48-432c-9d55-a870ee9f3a58

	measure Arrow_Type3 =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 3]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 3]),'Date Table'[last_week_minus_7] = 1)
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_High<Previous_Value_High,UNICHAR(UNICODE("↓"))))
		lineageTag: e85445ca-2f23-494f-85d0-6a2896d620ae

	measure ArrowColour_Type3 =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 3]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Number of A&E Attendances - Type 3]),'Date Table'[last_week_minus_7] = 1)
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,"#AE2424",
			IF(Latest_Value_High<Previous_Value_High,"#78BE20"))
		displayFolder: Page 3
		lineageTag: 61202c39-d4f2-4eac-8632-4df4b7d9fc15

	measure MH_Occ_% = (SUM('5. Weekly - NSHE Sitrep'[Mental Health Beds Occupied]))/(SUM('5. Weekly - NSHE Sitrep'[Mental Health Beds Available]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Page 3
		lineageTag: 5adaef28-3254-4d2f-8082-50d0930c0865

	measure UCR_2hr_Comp_% = (SUM('5. Weekly - NSHE Sitrep'[UCR 2hr (Compliant)]))/(SUM('5. Weekly - NSHE Sitrep'[UCR 2hr (Total Records)]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 197e0124-e71a-44c1-81eb-2faa392f09e8

	measure Arrow_UCR =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[UCR 2hr (Total Records)]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[UCR 2hr (Total Records)]),'Date Table'[last_week_minus_7] = 1)
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_High<Previous_Value_High,UNICHAR(UNICODE("↓"))))
		lineageTag: 54877b5f-f0c1-4e8e-953e-461337b983eb

	measure ArrowColour_UCR =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[UCR 2hr (Total Records)]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[UCR 2hr (Total Records)]),'Date Table'[last_week_minus_7] = 1)
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,"#78BE20",
			IF(Latest_Value_High<Previous_Value_High,"#AE2424"))
		lineageTag: de67926c-cbd2-4e6c-8576-0821c62b9bb7

	measure Arrow_Stream =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Streamed to FAS/SDEC]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Streamed to FAS/SDEC]),'Date Table'[last_week_minus_7] = 1)
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_High<Previous_Value_High,UNICHAR(UNICODE("↓"))))
		lineageTag: e2d123b9-17ce-4998-a1fc-c50ba524a075

	measure ArrowColour_Streamed =
			
			VAR Latest_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Streamed to FAS/SDEC]),'Date Table'[last_week] = 1)
			VAR Previous_Value_High = CALCULATE(SUM('5. Weekly - NSHE Sitrep'[Streamed to FAS/SDEC]),'Date Table'[last_week_minus_7] = 1)
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,"#78BE20",
			IF(Latest_Value_High<Previous_Value_High,"#AE2424"))
		lineageTag: 6dd3b601-4b84-421b-b1bf-df1e560c9708

	measure Avg_Handover = (SUM('5. Weekly - NSHE Sitrep'[SWASFT: Handover resource hours lost (>15 minutes)]))/(sum('5. Weekly - NSHE Sitrep'[SWASFT: Handover Delays (> 15 minutes)]))
		lineageTag: 6060c74a-bde5-47ba-8cf8-c16816b09db8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Avg_HandoverTime_Target = calculate(sum('5. Weekly - NSHE Sitrep'[SWASFT: Handover Delays Target])/7)/60
		lineageTag: ceca5110-0ac0-44ea-a86d-ea53e469b642

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 966b2f67-388d-49e4-9b7a-5025dc9714bb
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total adult G&A beds open'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: 450783f9-cfd7-47a5-a47b-226c00bfd56c
		summarizeBy: sum
		sourceColumn: Total adult G&A beds open

		annotation SummarizationSetBy = Automatic

	column 'Total paediatric G&A beds open'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: 56d0d2ae-e497-4283-84c7-f9aa78d822d5
		summarizeBy: sum
		sourceColumn: Total paediatric G&A beds open

		annotation SummarizationSetBy = Automatic

	column 'Total adult G&A beds occupied'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: 588da331-3d46-410c-9a28-6bea92478ab0
		summarizeBy: sum
		sourceColumn: Total adult G&A beds occupied

		annotation SummarizationSetBy = Automatic

	column 'Total paediatric G&A beds occupied'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: d9de2889-3840-4111-9bf7-392bf555779f
		summarizeBy: sum
		sourceColumn: Total paediatric G&A beds occupied

		annotation SummarizationSetBy = Automatic

	column 'PLAN: Open General & Acute (G&A) beds (Adult)'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: bacc504f-8cfd-4eb4-86a9-fa9a9760fba3
		summarizeBy: sum
		sourceColumn: PLAN: Open General & Acute (G&A) beds (Adult)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'PLAN: Occupied G&A beds (Adult)'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: d72fde6b-f2dd-4d48-92b4-48d9010a8b30
		summarizeBy: sum
		sourceColumn: PLAN: Occupied G&A beds (Adult)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'PLAN: Open General & Acute(G&A)  beds (Paediatric)'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: 597dea0c-80b4-458f-b0a5-92cf31cb019b
		summarizeBy: sum
		sourceColumn: PLAN: Open General & Acute(G&A)  beds (Paediatric)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'PLAN: Occupied G&A beds (Paediatric)'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: e3c81f52-f946-4142-86ad-a6bc13ddeeb8
		summarizeBy: sum
		sourceColumn: PLAN: Occupied G&A beds (Paediatric)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'PLAN: Available Community Beds'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: f78a4856-cf13-4ac9-ba42-d9ee094a190f
		summarizeBy: sum
		sourceColumn: PLAN: Available Community Beds

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'PLAN: Occupied Community Beds'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: 5adba2ed-972d-49c5-a066-e42fef6a1804
		summarizeBy: sum
		sourceColumn: PLAN: Occupied Community Beds

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'SWASFT: Cat 2 Responses'
		dataType: int64
		formatString: 0
		displayFolder: Page 1
		lineageTag: 65a32739-9a64-4c2d-a2e3-b707236e17ca
		summarizeBy: sum
		sourceColumn: SWASFT: Cat 2 Responses

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'SWASFT: Cat 2 Mean Response'
		dataType: double
		displayFolder: Page 1
		lineageTag: 0ff4ade2-71ed-453d-8a79-d2b94fb5a308
		summarizeBy: sum
		sourceColumn: SWASFT: Cat 2 Mean Response

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SWASFT: Cat 2 Total Response'
		dataType: double
		displayFolder: Page 1
		lineageTag: 965a4578-8b1f-44d9-99fa-1fc355f11141
		summarizeBy: sum
		sourceColumn: SWASFT: Cat 2 Total Response

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SWASFT: Cat 2 Target'
		dataType: double
		displayFolder: Page 1
		lineageTag: 1874adec-765b-47ef-acb5-69be9aeb1558
		summarizeBy: sum
		sourceColumn: SWASFT: Cat 2 Target

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Community Beds Available'
		dataType: double
		formatString: 0
		displayFolder: Page 1
		lineageTag: 847f9a11-ed0e-475a-8caf-c7e038c27382
		summarizeBy: sum
		sourceColumn: Community Beds Available

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Community Beds Occupied'
		dataType: double
		formatString: 0
		displayFolder: Page 1
		lineageTag: a5fec788-4d93-48eb-9776-57fcb4dd7568
		summarizeBy: sum
		sourceColumn: Community Beds Occupied

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'SWASFT: Handover duration (minutes)'
		dataType: double
		formatString: 0
		displayFolder: Page 1
		lineageTag: 6ea5c0f5-3a61-4cf5-9b37-80f880d27d26
		summarizeBy: sum
		sourceColumn: SWASFT: Handover duration (minutes)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'SWASFT: Handover Delays Target'
		dataType: double
		displayFolder: Page 1
		lineageTag: cf3fb085-e424-47c2-9bdc-51438ceda1f8
		summarizeBy: sum
		sourceColumn: SWASFT: Handover Delays Target

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SWASFT: Handover Delays (> 15 minutes)'
		dataType: double
		displayFolder: Page 1
		lineageTag: 056d1f75-6ce5-4c7a-9e4e-e5020682af7d
		summarizeBy: sum
		sourceColumn: SWASFT: Handover Delays (> 15 minutes)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SWASFT: Handover resource hours lost (>15 minutes)'
		dataType: double
		displayFolder: Page 1
		lineageTag: d837bd05-83ae-45c6-9b77-f4243eaaa415
		summarizeBy: sum
		sourceColumn: SWASFT: Handover resource hours lost (>15 minutes)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type 1 A&E Attendances (GHFT)'
		dataType: double
		displayFolder: Page 3
		lineageTag: 2ca99cb1-e30e-4d51-afee-708edb193a70
		summarizeBy: sum
		sourceColumn: Type 1 A&E Attendances (GHFT)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type 1 A&E Attendances (Plan) (GHFT)'
		dataType: double
		displayFolder: Page 3
		lineageTag: cb760b45-37d5-42dd-9f06-b56eb36c94eb
		summarizeBy: sum
		sourceColumn: Type 1 A&E Attendances (Plan) (GHFT)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type 3 A&E Attendances (GHC)'
		dataType: double
		displayFolder: Page 3
		lineageTag: 2db3c0e1-6f0c-4108-ae27-c020b41a8a79
		summarizeBy: sum
		sourceColumn: Type 3 A&E Attendances (GHC)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type 3 A&E Attendances (Plan) (GHC)'
		dataType: double
		displayFolder: Page 3
		lineageTag: 0785a4b9-83fc-4dfc-94d6-6b58f11da766
		summarizeBy: sum
		sourceColumn: Type 3 A&E Attendances (Plan) (GHC)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of A&E Attendances - Type 1'
		dataType: int64
		formatString: #,0
		displayFolder: Page 3
		lineageTag: d7984b12-96f9-4a9b-9b87-4afe7c16263b
		summarizeBy: sum
		sourceColumn: Number of A&E Attendances - Type 1

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Number of A&E Attendances - Type 3'
		dataType: int64
		formatString: #,0
		displayFolder: Page 3
		lineageTag: 2e03a131-75d5-4163-8ea7-c4bbfc265e01
		summarizeBy: sum
		sourceColumn: Number of A&E Attendances - Type 3

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'CATU Admissions'
		dataType: double
		formatString: 0
		lineageTag: 7b40afc7-b7f1-4002-95a1-b92c01485b9b
		summarizeBy: sum
		sourceColumn: CATU Admissions

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'CATU Plan'
		dataType: string
		lineageTag: bbacf7a3-5062-4310-a0fc-fe7ace2f0ef3
		summarizeBy: none
		sourceColumn: CATU Plan

		annotation SummarizationSetBy = Automatic

	column 'UCR 2hr (Compliant)'
		dataType: double
		displayFolder: Page 3
		lineageTag: e74d300b-f6c7-485a-961d-7974d08007cc
		summarizeBy: sum
		sourceColumn: UCR 2hr (Compliant)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'UCR 2hr (Non-Compliant)'
		dataType: double
		displayFolder: Page 3
		lineageTag: 138d4425-3eff-42d3-8ce2-a18af36ef6a7
		summarizeBy: sum
		sourceColumn: UCR 2hr (Non-Compliant)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'UCR 2hr (Total Records)'
		dataType: double
		formatString: 0
		displayFolder: Page 3
		lineageTag: 6ccbe393-6985-4adc-ad1e-bbec26e20e6f
		summarizeBy: sum
		sourceColumn: UCR 2hr (Total Records)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'UCR Plan (Number)'
		dataType: double
		displayFolder: Page 3
		lineageTag: 7307a7dd-6d98-41ef-821b-abc682d28de4
		summarizeBy: sum
		sourceColumn: UCR Plan (Number)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'UCR Plan (%)'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Page 3
		lineageTag: edeaddd5-c9af-44f2-9abc-f254882b1e66
		summarizeBy: sum
		sourceColumn: UCR Plan (%)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Mental Health Beds Available'
		dataType: double
		lineageTag: a115f4f1-de3a-4b1f-b334-09e05e0868a2
		summarizeBy: sum
		sourceColumn: Mental Health Beds Available

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mental Health Beds Occupied'
		dataType: double
		lineageTag: f6784735-250b-4fee-ac1d-f32e34404274
		summarizeBy: sum
		sourceColumn: Mental Health Beds Occupied

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Streamed to FAS/SDEC'
		dataType: int64
		formatString: 0
		lineageTag: bdabed64-79f8-4e6f-a8f7-782524ca08d5
		summarizeBy: sum
		sourceColumn: Streamed to FAS/SDEC

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Column39
		dataType: string
		lineageTag: 39e32d5e-01f6-448e-ad48-1f1872c0fe68
		summarizeBy: none
		sourceColumn: Column39

		annotation SummarizationSetBy = Automatic

	column Column40
		dataType: string
		lineageTag: 47842341-b688-4280-a8a4-5eb104834920
		summarizeBy: none
		sourceColumn: Column40

		annotation SummarizationSetBy = Automatic

	partition '5. Weekly - NSHE Sitrep' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\Daily\NHSI Daily Sitrep  backing 2223 2324.xlsx"), null, true),
				    #"Bed Occupancy Raw Data_Sheet" = Source{[Item="Bed Occupancy Raw Data",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Bed Occupancy Raw Data_Sheet",{{"Column1", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}, {"Column41", type any}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}, {"Column46", type any}, {"Column47", type any}, {"Column48", type any}, {"Column49", type any}, {"Column50", type any}, {"Column51", type any}, {"Column52", type any}, {"Column53", type any}, {"Column54", type any}, {"Column55", type any}, {"Column56", type any}, {"Column57", type any}, {"Column58", type any}, {"Column59", type any}, {"Column60", type any}, {"Column61", type any}, {"Column62", type any}, {"Column63", type any}, {"Column64", type any}, {"Column65", type any}, {"Column66", type any}, {"Column67", type any}, {"Column68", type any}, {"Column69", type any}, {"Column70", type any}, {"Column71", type any}, {"Column72", type any}, {"Column73", type any}, {"Column74", type any}, {"Column75", type any}, {"Column76", type any}, {"Column77", type any}, {"Column78", type any}, {"Column79", type any}, {"Column80", type any}, {"Column81", type any}, {"Column82", type any}, {"Column83", type any}, {"Column84", type any}, {"Column85", type any}, {"Column86", type any}, {"Column87", type any}, {"Column88", type any}, {"Column89", type any}, {"Column90", type any}, {"Column91", type any}, {"Column92", type any}, {"Column93", type any}, {"Column94", type any}, {"Column95", type any}, {"Column96", type any}, {"Column97", type any}, {"Column98", type any}, {"Column99", type any}, {"Column100", type any}, {"Column101", type any}, {"Column102", type any}, {"Column103", type any}, {"Column104", type any}, {"Column105", type any}, {"Column106", type any}, {"Column107", type any}, {"Column108", type any}, {"Column109", type any}, {"Column110", type any}, {"Column111", type any}, {"Column112", type any}, {"Column113", type any}, {"Column114", type any}, {"Column115", type any}, {"Column116", type any}, {"Column117", type any}, {"Column118", type any}, {"Column119", type any}, {"Column120", type any}, {"Column121", type any}, {"Column122", type any}, {"Column123", type any}, {"Column124", type any}, {"Column125", type any}, {"Column126", type any}, {"Column127", type any}, {"Column128", type any}, {"Column129", type any}, {"Column130", type any}, {"Column131", type any}, {"Column132", type any}, {"Column133", type any}, {"Column134", type any}, {"Column135", type any}, {"Column136", type any}, {"Column137", type any}, {"Column138", type any}, {"Column139", type any}, {"Column140", type any}, {"Column141", type any}, {"Column142", type any}, {"Column143", type any}, {"Column144", type any}, {"Column145", type any}, {"Column146", type any}, {"Column147", type any}, {"Column148", type any}, {"Column149", type any}, {"Column150", type any}, {"Column151", type any}, {"Column152", type any}, {"Column153", type any}, {"Column154", type any}, {"Column155", type any}, {"Column156", type any}, {"Column157", type any}, {"Column158", type any}, {"Column159", type any}, {"Column160", type any}, {"Column161", type any}, {"Column162", type any}, {"Column163", type any}, {"Column164", type any}, {"Column165", type any}, {"Column166", type any}, {"Column167", type any}, {"Column168", type any}, {"Column169", type any}, {"Column170", type any}, {"Column171", type any}, {"Column172", type any}, {"Column173", type any}, {"Column174", type any}, {"Column175", type any}, {"Column176", type any}, {"Column177", type any}, {"Column178", type any}, {"Column179", type any}, {"Column180", type any}, {"Column181", type any}, {"Column182", type any}, {"Column183", type any}, {"Column184", type any}, {"Column185", type any}, {"Column186", type any}, {"Column187", type any}, {"Column188", type any}, {"Column189", type any}, {"Column190", type any}, {"Column191", type any}, {"Column192", type any}, {"Column193", type any}, {"Column194", type any}, {"Column195", type any}, {"Column196", type any}, {"Column197", type any}, {"Column198", type any}, {"Column199", type any}, {"Column200", type any}, {"Column201", type any}, {"Column202", type any}, {"Column203", type any}, {"Column204", type any}, {"Column205", type any}, {"Column206", type any}, {"Column207", type any}, {"Column208", type any}, {"Column209", type any}, {"Column210", type any}, {"Column211", type any}, {"Column212", type any}, {"Column213", type any}, {"Column214", type any}, {"Column215", type any}, {"Column216", type any}, {"Column217", type any}, {"Column218", type any}, {"Column219", type any}, {"Column220", type any}, {"Column221", type any}, {"Column222", type any}, {"Column223", type any}, {"Column224", type any}, {"Column225", type any}, {"Column226", type any}, {"Column227", type any}, {"Column228", type any}, {"Column229", type any}, {"Column230", type any}, {"Column231", type any}, {"Column232", type any}, {"Column233", type any}, {"Column234", type any}, {"Column235", type any}, {"Column236", type any}, {"Column237", type any}, {"Column238", type any}, {"Column239", type any}, {"Column240", type any}, {"Column241", type any}, {"Column242", type any}, {"Column243", type any}, {"Column244", type any}, {"Column245", type any}, {"Column246", type any}, {"Column247", type any}, {"Column248", type any}, {"Column249", type any}, {"Column250", type any}, {"Column251", type any}, {"Column252", type any}, {"Column253", type any}, {"Column254", type any}, {"Column255", type any}, {"Column256", type any}, {"Column257", type any}, {"Column258", type any}, {"Column259", type any}, {"Column260", type any}, {"Column261", type any}, {"Column262", type any}, {"Column263", type any}, {"Column264", type any}, {"Column265", type any}, {"Column266", type any}, {"Column267", type any}, {"Column268", type any}, {"Column269", type any}, {"Column270", type any}, {"Column271", type any}, {"Column272", type any}, {"Column273", type any}, {"Column274", type any}, {"Column275", type any}, {"Column276", type any}, {"Column277", type any}, {"Column278", type any}, {"Column279", type any}, {"Column280", type any}, {"Column281", type any}, {"Column282", type any}, {"Column283", type any}, {"Column284", type any}, {"Column285", type any}, {"Column286", type any}, {"Column287", type any}, {"Column288", type any}, {"Column289", type any}, {"Column290", type any}, {"Column291", type any}, {"Column292", type any}, {"Column293", type any}, {"Column294", type any}, {"Column295", type any}, {"Column296", type any}, {"Column297", type any}, {"Column298", type any}, {"Column299", type any}, {"Column300", type any}, {"Column301", type any}, {"Column302", type any}, {"Column303", type any}, {"Column304", type any}, {"Column305", type any}, {"Column306", type any}, {"Column307", type any}, {"Column308", type any}, {"Column309", type any}, {"Column310", type any}, {"Column311", type any}, {"Column312", type any}, {"Column313", type any}, {"Column314", type any}, {"Column315", type any}, {"Column316", type any}, {"Column317", type any}, {"Column318", type any}, {"Column319", type any}, {"Column320", type any}, {"Column321", type any}, {"Column322", type any}, {"Column323", type any}, {"Column324", type any}, {"Column325", type any}, {"Column326", type any}, {"Column327", type any}, {"Column328", type any}, {"Column329", type any}, {"Column330", type any}, {"Column331", type any}, {"Column332", type any}, {"Column333", type any}, {"Column334", type any}, {"Column335", type any}, {"Column336", type any}, {"Column337", type any}, {"Column338", type any}, {"Column339", type any}, {"Column340", type any}, {"Column341", type any}, {"Column342", type any}, {"Column343", type any}, {"Column344", type any}, {"Column345", type any}, {"Column346", type any}, {"Column347", type any}, {"Column348", type any}, {"Column349", type any}, {"Column350", type any}, {"Column351", type any}, {"Column352", type any}, {"Column353", type any}, {"Column354", type any}, {"Column355", type any}, {"Column356", type any}, {"Column357", type any}, {"Column358", type any}, {"Column359", type any}, {"Column360", type any}, {"Column361", type any}, {"Column362", type any}, {"Column363", type any}, {"Column364", type any}, {"Column365", type any}, {"Column366", type any}, {"Column367", type any}, {"Column368", type any}, {"Column369", type any}, {"Column370", type any}, {"Column371", type any}, {"Column372", type any}, {"Column373", type any}, {"Column374", type any}, {"Column375", type any}, {"Column376", type any}, {"Column377", type any}, {"Column378", type any}, {"Column379", type any}, {"Column380", type any}, {"Column381", type any}, {"Column382", type any}, {"Column383", type any}, {"Column384", type any}, {"Column385", type any}, {"Column386", type any}, {"Column387", type any}, {"Column388", type any}, {"Column389", type any}, {"Column390", type any}, {"Column391", type any}, {"Column392", type any}, {"Column393", type any}, {"Column394", type any}, {"Column395", type any}, {"Column396", type any}, {"Column397", type any}, {"Column398", type any}, {"Column399", type any}, {"Column400", type any}, {"Column401", type any}, {"Column402", type any}, {"Column403", type any}, {"Column404", type any}, {"Column405", type any}, {"Column406", type any}, {"Column407", type any}, {"Column408", type any}, {"Column409", type any}, {"Column410", type any}, {"Column411", type any}, {"Column412", type any}, {"Column413", type any}, {"Column414", type any}, {"Column415", type any}, {"Column416", type any}, {"Column417", type any}, {"Column418", type any}, {"Column419", type any}, {"Column420", type any}, {"Column421", type any}, {"Column422", type any}, {"Column423", type any}, {"Column424", type any}, {"Column425", type any}, {"Column426", type any}, {"Column427", type any}, {"Column428", type any}, {"Column429", type any}, {"Column430", type any}, {"Column431", type any}, {"Column432", type any}, {"Column433", type any}, {"Column434", type any}, {"Column435", type any}, {"Column436", type any}, {"Column437", type any}, {"Column438", type any}, {"Column439", type any}, {"Column440", type any}, {"Column441", type any}, {"Column442", type any}, {"Column443", type any}, {"Column444", type any}, {"Column445", type any}, {"Column446", type any}, {"Column447", type any}, {"Column448", type any}, {"Column449", type any}, {"Column450", type any}, {"Column451", type any}, {"Column452", type any}, {"Column453", type any}, {"Column454", type any}, {"Column455", type any}, {"Column456", type any}, {"Column457", type any}, {"Column458", type any}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Column1] = null or [Column1] = "CATU Admissions" or [Column1] = "CATU Plan" or [Column1] = "Community Beds Available" or [Column1] = "Community Beds Occupied" or [Column1] = "Mental Health Beds Available" or [Column1] = "Mental Health Beds Occupied" or [Column1] = "Number of A&E Attendances - Type 1" or [Column1] = "Number of A&E Attendances - Type 3" or [Column1] = "PLAN: Available Community Beds" or [Column1] = "PLAN: Occupied Community Beds" or [Column1] = "PLAN: Occupied G&A beds (Adult)" or [Column1] = "PLAN: Occupied G&A beds (Paediatric)" or [Column1] = "PLAN: Open General & Acute (G&A) beds (Adult)" or [Column1] = "PLAN: Open General & Acute(G&A)  beds (Paediatric)" or [Column1] = "Streamed to FAS/SDEC" or [Column1] = "SWASFT: Cat 2 Mean Response" or [Column1] = "SWASFT: Cat 2 Responses" or [Column1] = "SWASFT: Cat 2 Target" or [Column1] = "SWASFT: Cat 2 Total Response" or [Column1] = "SWASFT: Handover Delays (> 15 minutes)" or [Column1] = "SWASFT: Handover Delays Target" or [Column1] = "SWASFT: Handover duration (minutes)" or [Column1] = "SWASFT: Handover resource hours lost (>15 minutes)" or [Column1] = "Total adult G&A beds occupied" or [Column1] = "Total adult G&A beds open" or [Column1] = "Total paediatric G&A beds occupied" or [Column1] = "Total paediatric G&A beds open" or [Column1] = "Type 1 A&E Attendances (GHFT)" or [Column1] = "Type 1 A&E Attendances (Plan) (GHFT)" or [Column1] = "Type 3 A&E Attendances (GHC)" or [Column1] = "Type 3 A&E Attendances (Plan) (GHC)" or [Column1] = "UCR 2hr (Compliant)" or [Column1] = "UCR 2hr (Non-Compliant)" or [Column1] = "UCR 2hr (Total Records)" or [Column1] = "UCR Plan (%)" or [Column1] = "UCR Plan (Number)")),
				    #"Transposed Table" = Table.Transpose(#"Filtered Rows"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type date}, {"Column2", type text}, {"Total adult G&A beds open", Int64.Type}, {"Total paediatric G&A beds open", Int64.Type}, {"Total adult G&A beds occupied", Int64.Type}, {"Total paediatric G&A beds occupied", Int64.Type}, {"PLAN: Open General & Acute (G&A) beds (Adult)", type any}, {"PLAN: Occupied G&A beds (Adult)", type any}, {"PLAN: Open General & Acute(G&A)  beds (Paediatric)", type any}, {"PLAN: Occupied G&A beds (Paediatric)", type any}, {"PLAN: Available Community Beds", type any}, {"PLAN: Occupied Community Beds", type any}, {"SWASFT: Cat 2 Responses", type any}, {"SWASFT: Cat 2 Mean Response", type any}, {"SWASFT: Cat 2 Total Response", type any}, {"SWASFT: Cat 2 Target", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Column2"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Column1", "Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

