table '111 Data'
	lineageTag: 2e936dd5-8320-4483-81da-a00c47563376

	measure 'Redirect % By Final Disposition on Columns' =
			
			DIVIDE (
			sum('111 Data'[Redirect]),
			CALCULATE ( sum('111 Data'[Redirect]),ALLSELECTED('111 Data'[FinalDispositonDescription]))
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 656eed32-4e2b-41c6-b613-cc7ceab83ba2

	column PseudoNHSNumber
		dataType: string
		lineageTag: e253a77e-d956-4a58-ae85-19ce2c6ac4f5
		summarizeBy: none
		sourceColumn: PseudoNHSNumber

		annotation SummarizationSetBy = Automatic

	column AdastraNumber
		dataType: string
		lineageTag: 85c883e9-5d37-45e3-961f-4f0cd9419c21
		summarizeBy: none
		sourceColumn: AdastraNumber

		annotation SummarizationSetBy = Automatic

	column PracNameCurrent
		dataType: string
		lineageTag: 8a890f7e-dfda-47da-b8ef-463fb5d953f9
		summarizeBy: none
		sourceColumn: PracNameCurrent

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: 24c2b07c-4262-4526-bcb8-4694db808b14
		summarizeBy: none
		sourceColumn: PracticeCode

		annotation SummarizationSetBy = Automatic

	column LocalityName
		dataType: string
		lineageTag: f2a4b7b8-7004-48d5-9163-f3865432df12
		summarizeBy: none
		sourceColumn: LocalityName

		annotation SummarizationSetBy = Automatic

	column NetworkName
		dataType: string
		lineageTag: 3becaa12-eef8-48d9-bc34-cfd1228beb58
		summarizeBy: none
		sourceColumn: NetworkName

		annotation SummarizationSetBy = Automatic

	column LTCCountDerived
		dataType: int64
		formatString: 0
		lineageTag: 0fde331a-2072-49b2-a9b6-22ac0c5a2cd0
		summarizeBy: sum
		sourceColumn: LTCCountDerived

		annotation SummarizationSetBy = Automatic

	column AgeBand10yr
		dataType: string
		lineageTag: 09f892b3-1cfc-4f8b-9edd-fe6887ae0655
		summarizeBy: none
		sourceColumn: AgeBand10yr

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 05b87280-0994-4863-bd67-7b0d9f6c4887
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 2cfcb675-8811-47cb-9c34-a11b3e58242d
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column DateOfCase
		dataType: dateTime
		formatString: Long Date
		lineageTag: f7d689d4-68a8-427d-86af-b26929aec26f
		summarizeBy: none
		sourceColumn: DateOfCase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthOfCase
		dataType: string
		lineageTag: 053bd427-552a-4864-a933-e4717c91148f
		summarizeBy: none
		sourceColumn: MonthOfCase

		annotation SummarizationSetBy = Automatic

	column YearOfCase
		dataType: int64
		formatString: 0
		lineageTag: 28177d90-9b03-4a07-9927-6f53d4689db5
		summarizeBy: sum
		sourceColumn: YearOfCase

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: string
		lineageTag: d2486718-9ec5-4ff8-b559-cf7a2bb206ca
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column BankHoliday
		dataType: string
		lineageTag: 71bcffcf-fc85-41f4-abdc-c7e113a52445
		summarizeBy: none
		sourceColumn: BankHoliday

		annotation SummarizationSetBy = Automatic

	column StandardisedTimeofCase
		dataType: dateTime
		formatString: Long Time
		lineageTag: 55d42dd8-54f4-4382-86a1-f51c2bcc25c8
		summarizeBy: none
		sourceColumn: StandardisedTimeofCase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column InitialDisposition
		dataType: string
		lineageTag: 8b474f07-2828-4b6c-9aab-94d013ef75a1
		summarizeBy: none
		sourceColumn: InitialDisposition

		annotation SummarizationSetBy = Automatic

	column InitialDispositionDescription
		dataType: string
		lineageTag: c5486484-6916-403d-ad15-a14cfc4d2084
		summarizeBy: none
		sourceColumn: InitialDispositionDescription

		annotation SummarizationSetBy = Automatic

	column FinalDispositon
		dataType: string
		lineageTag: a5e94cf8-c8f8-44c4-9b34-33a9c4b62fed
		summarizeBy: none
		sourceColumn: FinalDispositon

		annotation SummarizationSetBy = Automatic

	column FinalDispositonDescription
		dataType: string
		lineageTag: 1a60771a-9b2b-4096-b17a-4c48b4efb4ae
		summarizeBy: none
		sourceColumn: FinalDispositonDescription

		annotation SummarizationSetBy = Automatic

	column DispositionGroup
		dataType: string
		lineageTag: d95a81eb-b537-4972-bc05-3d0df02702b5
		summarizeBy: none
		sourceColumn: DispositionGroup

		annotation SummarizationSetBy = Automatic

	column DispositionGroup(PPG)
		dataType: string
		lineageTag: 889e32a7-4318-43ab-b723-879bbf20e437
		summarizeBy: none
		sourceColumn: DispositionGroup(PPG)

		annotation SummarizationSetBy = Automatic

	column ValidationRequired
		dataType: string
		lineageTag: 83f86469-1f2d-4dc2-ad55-1501830f6a97
		summarizeBy: none
		sourceColumn: ValidationRequired

		annotation SummarizationSetBy = Automatic

	column Validation
		dataType: string
		lineageTag: 9fb52fdc-4439-4634-a9f1-7031d70971ba
		summarizeBy: none
		sourceColumn: Validation

		annotation SummarizationSetBy = Automatic

	column ValidationType
		dataType: string
		lineageTag: 6854c03f-9c76-41c8-8d18-485a6a79d3f9
		summarizeBy: none
		sourceColumn: ValidationType

		annotation SummarizationSetBy = Automatic

	column Redirect
		dataType: int64
		formatString: 0
		lineageTag: ef1ab717-f7cb-48c2-8090-8027e747afdb
		summarizeBy: sum
		sourceColumn: Redirect

		annotation SummarizationSetBy = Automatic

	column CAS
		dataType: int64
		formatString: 0
		lineageTag: 392843c1-6b23-4cb1-b0c3-53934e25de25
		summarizeBy: sum
		sourceColumn: CAS

		annotation SummarizationSetBy = Automatic

	column ServiceName
		dataType: string
		lineageTag: ce6c9d3c-24df-43bf-ba36-5e7940b23d29
		summarizeBy: none
		sourceColumn: ServiceName

		annotation SummarizationSetBy = Automatic

	column SymptomGroup
		dataType: string
		lineageTag: 05595168-77f2-43ba-9002-5fa23663bed6
		summarizeBy: none
		sourceColumn: SymptomGroup

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 4ad0ff05-ba25-4ce9-af2f-27e88bc89a0f
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column ED
		dataType: int64
		formatString: 0
		lineageTag: 4825c928-5613-4926-a79b-1e0ca3080498
		summarizeBy: sum
		sourceColumn: ED

		annotation SummarizationSetBy = Automatic

	column GP
		dataType: int64
		formatString: 0
		lineageTag: 55cfb498-89cf-458e-95a5-dc40239f6375
		summarizeBy: sum
		sourceColumn: GP

		annotation SummarizationSetBy = Automatic

	column Call_Handler
		dataType: string
		lineageTag: 3c4831aa-e7ac-4733-803b-4c43605b66d2
		summarizeBy: none
		sourceColumn: Call_Handler

		annotation SummarizationSetBy = Automatic

	column Data_Source
		dataType: string
		lineageTag: 0ebf3504-24d6-4c35-a709-1eee5e011a98
		summarizeBy: none
		sourceColumn: Data_Source

		annotation SummarizationSetBy = Automatic

	column Local_OOC_Flag = SWITCH('111 Data'[Call_Handler],  "Local", "Local Call Handler", "Other Provider")
		lineageTag: 5c2e7507-3b7a-4e46-84b3-9f1de24784b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OOC_Flag = SWITCH([Call_Handler],  "Local", 0, 1)
		formatString: 0
		lineageTag: 84f4c039-9c57-43e1-8b78-519dccb771ad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Call_Closed_Flag
		dataType: int64
		formatString: 0
		lineageTag: eb5ae41f-3c36-4417-acb1-1352affb9c8f
		summarizeBy: sum
		sourceColumn: Call_Closed_Flag

		annotation SummarizationSetBy = Automatic

	column Category_1/2_Ambulance_Flag
		dataType: int64
		formatString: 0
		lineageTag: b29562dd-218e-499f-a9db-3f964fa752a0
		summarizeBy: sum
		sourceColumn: Category_1/2_Ambulance_Flag

		annotation SummarizationSetBy = Automatic

	column Category_3/4_Ambulance_Flag
		dataType: int64
		formatString: 0
		lineageTag: 1c6bdab1-5a87-480d-84c8-14c352c295ca
		summarizeBy: sum
		sourceColumn: Category_3/4_Ambulance_Flag

		annotation SummarizationSetBy = Automatic

	column COVID-19_Flag
		dataType: int64
		formatString: 0
		lineageTag: c2140f50-c3dd-4189-b6ce-5de2b047c8ec
		summarizeBy: sum
		sourceColumn: COVID-19_Flag

		annotation SummarizationSetBy = Automatic

	column Dental_Flag
		dataType: int64
		formatString: 0
		lineageTag: c5d5a5e5-e936-40dc-b972-015cd09198be
		summarizeBy: sum
		sourceColumn: Dental_Flag

		annotation SummarizationSetBy = Automatic

	column ED_Flag
		dataType: int64
		formatString: 0
		lineageTag: 5fa0ef1b-d1b7-4304-9acf-3211ea2c60c9
		summarizeBy: sum
		sourceColumn: ED_Flag

		annotation SummarizationSetBy = Automatic

	column Home_Management_Flag
		dataType: int64
		formatString: 0
		lineageTag: d05daf1b-18ad-40f0-ac4e-c0b930c70524
		summarizeBy: sum
		sourceColumn: Home_Management_Flag

		annotation SummarizationSetBy = Automatic

	column Other_Service_Referral_Flag
		dataType: int64
		formatString: 0
		lineageTag: ba11a905-1867-4cc1-86d6-1446cdc465d4
		summarizeBy: sum
		sourceColumn: Other_Service_Referral_Flag

		annotation SummarizationSetBy = Automatic

	column Pharmacy/Prescription_Flag
		dataType: int64
		formatString: 0
		lineageTag: 5202c132-1a17-4bbe-ac70-7aa51f4b6dcb
		summarizeBy: sum
		sourceColumn: Pharmacy/Prescription_Flag

		annotation SummarizationSetBy = Automatic

	column Primary_Care_Contact_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9315c0de-f4d1-4dcc-b027-67f28a4880e3
		summarizeBy: sum
		sourceColumn: Primary_Care_Contact_Flag

		annotation SummarizationSetBy = Automatic

	column Primary_Care_Speak_To_Flag
		dataType: int64
		formatString: 0
		lineageTag: 380b5f20-dbdb-48f0-b1ca-a281f0389eec
		summarizeBy: sum
		sourceColumn: Primary_Care_Speak_To_Flag

		annotation SummarizationSetBy = Automatic

	column Speak_to_CA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 8471de4b-2dba-40ed-b74f-f77e82b5a7f4
		summarizeBy: sum
		sourceColumn: Speak_to_CA_Flag

		annotation SummarizationSetBy = Automatic

	column 'Ambulance validations done' =
			
			IF(
			    FORMAT('111 Data'[ValidationRequired],"General") = "1" && FORMAT('111 Data'[Validation],"General") = "Pathways" && FORMAT('111 Data'[ValidationType],"General") = "Ambulance",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 30e006ab-05ad-42c5-b97e-da5589a6c41a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Ambulance validations required' =
			
			IF(
			    FORMAT('111 Data'[ValidationRequired],"General") = "1"  && FORMAT('111 Data'[ValidationType],"General") = "Ambulance",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 68b8feb7-5400-4354-97df-1c784a2fff8d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED validations required' =
			
			IF(
			    FORMAT('111 Data'[ValidationRequired],"General") = "1"  && FORMAT('111 Data'[ValidationType],"General") = "ED",
			    1,
			    0
			)
		formatString: 0
		lineageTag: afd24349-fb75-4cbb-95d9-ef3de2dc4b50
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED validations done' =
			
			IF(
			    FORMAT('111 Data'[ValidationRequired],"General") = "1" && FORMAT('111 Data'[Validation],"General") = "Pathways" && FORMAT('111 Data'[ValidationType],"General") = "ED",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 48b5eab1-9e77-41fe-beaa-2111404bd773
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Ambulance Redirections' =
			
			IF(
			    FORMAT('111 Data'[ValidationType],"General") = "Ambulance" && '111 Data'[Redirect]=1 ,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 3a2929ed-c9f9-45da-b47b-ea73d94a566a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED Redirections' = ```
			
			IF(
			
			    FORMAT('111 Data'[ValidationType],"General") = "ED" && '111 Data'[Redirect]=1 ,
			    1,
			    0
			) 
			
			```
		formatString: 0
		lineageTag: e1d324e0-88fb-4aeb-b877-8f0b8ce8fd62
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 6ee9c1d3-856a-4976-b341-bff5e5da3733
		summarizeBy: none
		sourceColumn: Last_Updated

		variation Variation
			isDefault
			relationship: 616a0999-3952-428c-98e7-afa42c4c2a2c
			defaultHierarchy: LocalDateTable_ac6a7ee5-a371-4089-ba60-6a3422a1fac7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Derived_PPG_Final_Disposition_Group =
			
			IF (
			    '111 Data'[DispositionGroup(PPG)]= "Call Closed",
			    "Call Closed",
			    IF (
			        '111 Data'[DispositionGroup(PPG)]= "Primary Care Contact",
			        "Contact Primary Care",
			           IF (
			            '111 Data'[DispositionGroup(PPG)] = "Primary Care Speak To",
			            "Contact Primary Care",
			        IF (
			        '111 Data'[DispositionGroup(PPG)]= "Category 1/2 Ambulance",
			        "Ambulance",
			                IF (
			        '111 Data'[DispositionGroup(PPG)]= "Category 3/4 Ambulance",
			        "Ambulance",
			            "All Other dispositions"
			        )
			    )
			)))
		lineageTag: 527c9899-abc3-4e57-b9b7-2ea1247cac71
		summarizeBy: none

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Ethnicity_Origin_Wider_Groups
		dataType: string
		lineageTag: d24bece7-813d-487e-a4e5-bfc5458518e9
		summarizeBy: none
		sourceColumn: Ethnicity_Origin_Wider_Groups

		annotation SummarizationSetBy = Automatic

	column Call_Closed_Flag2
		dataType: int64
		formatString: 0
		lineageTag: e7deb8e3-304b-4f9a-b5e3-f75dad0a2392
		summarizeBy: sum
		sourceColumn: Call_Closed_Flag2

		annotation SummarizationSetBy = Automatic

	column Category_1/2_Ambulance_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 4abe69dc-3661-4dfc-b2ad-4633957b89d2
		summarizeBy: sum
		sourceColumn: Category_1/2_Ambulance_Flag2

		annotation SummarizationSetBy = Automatic

	column Category_3/4_Ambulance_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 2458e16a-c039-4969-bd2a-61b8ed68a0cb
		summarizeBy: sum
		sourceColumn: Category_3/4_Ambulance_Flag2

		annotation SummarizationSetBy = Automatic

	column COVID-19_Flag2
		dataType: int64
		formatString: 0
		lineageTag: f137d797-caa1-4fa7-8be1-d3b98a5a8b65
		summarizeBy: sum
		sourceColumn: COVID-19_Flag2

		annotation SummarizationSetBy = Automatic

	column Dental_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 6081d11a-610d-4e9a-949a-8be6d0eb25c5
		summarizeBy: sum
		sourceColumn: Dental_Flag2

		annotation SummarizationSetBy = Automatic

	column ED_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 95926cb6-d2ae-4baf-862a-21a79bb85ed1
		summarizeBy: sum
		sourceColumn: ED_Flag2

		annotation SummarizationSetBy = Automatic

	column Home_Management_Flag2
		dataType: int64
		formatString: 0
		lineageTag: b032bab4-031a-4d94-8c5b-7f0e1af1c931
		summarizeBy: sum
		sourceColumn: Home_Management_Flag2

		annotation SummarizationSetBy = Automatic

	column Other_Service_Referral_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 8d524a07-f4dd-437e-9afe-555d0932fc05
		summarizeBy: sum
		sourceColumn: Other_Service_Referral_Flag2

		annotation SummarizationSetBy = Automatic

	column Pharmacy/Prescription_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 5b95660d-09ad-4048-8195-c117be82d5f0
		summarizeBy: sum
		sourceColumn: Pharmacy/Prescription_Flag2

		annotation SummarizationSetBy = Automatic

	column Primary_Care_Contact_Flag2
		dataType: int64
		formatString: 0
		lineageTag: e45b504b-1f27-4545-b322-7b4195eb8be7
		summarizeBy: sum
		sourceColumn: Primary_Care_Contact_Flag2

		annotation SummarizationSetBy = Automatic

	column Primary_Care_Speak_To_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 446ad8dd-41d1-4a51-836b-44118fd29142
		summarizeBy: sum
		sourceColumn: Primary_Care_Speak_To_Flag2

		annotation SummarizationSetBy = Automatic

	column Speak_to_CA_Flag2
		dataType: int64
		formatString: 0
		lineageTag: 3c9e1eda-d3cb-42e7-b8d2-2c6cea10d985
		summarizeBy: sum
		sourceColumn: Speak_to_CA_Flag2

		annotation SummarizationSetBy = Automatic

	partition '111 Data-47235561-0715-4ae8-a713-589783b761c8' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Reporting", [Query="select *#(lf),[Call_Closed_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Call Closed'  then 1 else 0 end#(lf),[Category_1/2_Ambulance_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Category 1/2 Ambulance' then 1 else 0 end#(lf),[Category_3/4_Ambulance_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Category 3/4 Ambulance' then 1 else 0 end#(lf),[COVID-19_Flag] =  CASE WHEN [DispositionGroup(PPG)] = 'COVID-19' then 1 else 0 end#(lf),[Dental_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Dental' then 1 else 0 end#(lf),[ED_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'ED' then 1 else 0 end#(lf),[Home_Management_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Home Management' then 1 else 0 end#(lf),[Other_Service_Referral_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Other Service Referral' then 1 else 0 end#(lf),[Pharmacy/Prescription_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Pharmacy/Prescription' then 1 else 0 end#(lf),[Primary_Care_Contact_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Primary Care Contact' then 1 else 0 end#(lf),[Primary_Care_Speak_To_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Primary Care Speak To' then 1 else 0 end#(lf),[Speak_to_CA_Flag] = CASE WHEN [DispositionGroup(PPG)] = 'Speak to CA' then 1 else 0 end#(lf),[Last_Updated] = cast(getdate() as date)#(lf)from [PowerBI_Reporting].[dbo].[111_all_calls]#(lf)#(lf)#(lf)where cast(DateOfCase as date) between '20201201' and eomonth(dateadd(month, -1, getdate()))"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"DateOfCase", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

