table 'Date Ref'
	lineageTag: f3720a45-800d-46de-9891-f81b231955e0

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 085dfea1-4d30-4ecd-abe9-3bd5029d6ca1
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 01e9eed5-707a-41a1-8ab7-e65825e656cc
			defaultHierarchy: LocalDateTable_e512c564-4d08-4751-93b7-0d3d5b7a6bc9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day_month_year
		dataType: string
		lineageTag: 9620226b-21a8-4e07-8261-4eca1063cfe6
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: f6579ef8-c3e5-4420-9986-1a01c5efa06a
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 991dd13d-15f7-4af2-8b6e-af2ee36c450c
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 24ac201e-e877-42a1-a347-ed283c2842f1
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: bb5bab4f-c884-43a9-bf8b-95ca39c36950
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: f45e1b9f-9e5a-4694-a445-760f76ab07fe
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 0a679354-3baa-4c37-90c6-c65da21afaf1
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 052194b2-f112-4183-8776-b513a936c64f
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9249080a-5133-46a9-a704-933fc15d11e3
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a8423ea7-9f46-4da1-888b-21f1cfbb75f1
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 59bf2457-c3a1-4bb6-b95c-ac54d45117d8
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: f5a6f9c3-2a82-4e1a-bec8-c715baeb0901
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 8f00a310-8c8e-4930-ae53-1e07bf9fe636
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 406937d7-d7b7-40d8-9856-f40615c48fad
		summarizeBy: sum
		sourceColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Reporting_Months_Flag
		dataType: int64
		formatString: 0
		lineageTag: b9e60215-2ce0-4746-8cc2-8578163b0a03
		summarizeBy: sum
		sourceColumn: Reporting_Months_Flag

		annotation SummarizationSetBy = Automatic

	column Current_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: 60d20fd0-764f-450c-af1a-6c22b086eacb
		summarizeBy: sum
		sourceColumn: Current_FY_Flag

		annotation SummarizationSetBy = Automatic

	column Last_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: e2ddaf1d-cf99-412e-9da6-c79eb9d8ea54
		summarizeBy: sum
		sourceColumn: Last_FY_Flag

		annotation SummarizationSetBy = Automatic

	column Baseline_year_comparison
		dataType: int64
		formatString: 0
		lineageTag: 5a36d9c7-1b32-4967-9296-8cba3619db98
		summarizeBy: sum
		sourceColumn: Baseline_year_comparison

		annotation SummarizationSetBy = Automatic

	column Current_year_to_compare
		dataType: int64
		formatString: 0
		lineageTag: 0b984c57-92fe-4e28-8b2e-0755758ebe82
		summarizeBy: sum
		sourceColumn: Current_year_to_compare

		annotation SummarizationSetBy = Automatic

	column FY_to_Compare
		dataType: int64
		formatString: 0
		lineageTag: ae8d2da5-3dd7-4837-af29-ad268dbbea03
		summarizeBy: sum
		sourceColumn: FY_to_Compare

		annotation SummarizationSetBy = Automatic

	partition 'Date Ref-a843c7a3-2b2f-4142-92cc-ae6c02a71a66' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="/*------------------------------------------------------------#(lf)Delete Temp Tables if exists#(lf)/-------------------------------------------------------------*/#(lf)IF OBJECT_ID('tempdb..#latest_reporting_month') is not null#(lf)drop table #latest_reporting_month#(lf)#(lf)#(lf)/*------------------------------------------------------------#(lf)Declare variables #(lf)/-------------------------------------------------------------*/#(lf)#(lf)--Gets current Financial year #(lf)declare @FY_Start_current as date#(lf)set @FY_Start_current = #(lf) cast(dateadd(month, 3, dateadd(year, datepart(year, dateadd(month, -3, getdate())) - 1900, 0)) as date)#(lf)#(lf) --Gets current Financial year end#(lf)declare @FY_END_current as date#(lf)set @FY_END_current = dateadd(day,-1,dateadd(YEAR,1,@FY_Start_current))#(lf)#(lf)--Gets last Financial year start#(lf)declare @Last_FY_Start as date#(lf)set @Last_FY_Start = dateadd(year,-1,@FY_Start_current)#(lf)#(lf)--Gets last Financial year end#(lf)declare @Last_FY_End as date#(lf)set @Last_FY_End = dateadd(year,-1,@FY_END_current)#(lf)#(lf)#(lf)/*------------------------------------------------------------#(lf)Create temp tables#(lf)/-------------------------------------------------------------*/#(lf)--- Creates the #(lf)select  #(lf)[First_Financial_Month]  =  min(cast(FinancialMonth as int))#(lf),[Latest_Financial_Month]  = max(cast(FinancialMonth as int))#(lf)into #latest_reporting_month#(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where date between #(lf)case when month(getdate()) = 4 then cast(dateadd(month, 3, dateadd(year, datepart(year, dateadd(month, -3, dateadd(month,-1,getdate()))) - 1900, 0)) as date) #(lf)else cast(dateadd(month, 3, dateadd(year, datepart(year, dateadd(month, -3, getdate())) - 1900, 0)) as date) end #(lf)AND  eomonth(dateadd(month, -1, getdate())) #(lf)#(lf)/*------------------------------------------------------------#(lf)Starts main query#(lf)/-------------------------------------------------------------*/#(lf)#(lf)#(lf)select [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)#(tab)  ,[Reporting_Months_Flag] = case when cast(d.FinancialMonth as int)  <= Latest_Financial_Month THEN 1 ELSE 0 END#(lf)#(tab)  ,[Current_FY_Flag] = case when d.Date between @FY_Start_current and @FY_END_current then 1 else 0 END #(lf)#(tab)  ,[Last_FY_Flag] = case when d.Date between @Last_FY_Start and @Last_FY_End then 1 else 0 END #(lf)#(lf)#(tab)  --FLAGS TO COMPARE FINANCIAL YEARS #(lf)#(tab)  ,[Baseline_year_comparison] = case when month(getdate()) = 4 and date between  dateadd(year,-1,@Last_FY_Start) and dateadd(year,-1,@Last_FY_End) then 1 #(lf)#(tab)  when month(getdate()) != 4 and date between  @Last_FY_Start and @Last_FY_End then 1 #(lf)#(tab)  ELSE 0 END#(lf)#(lf)#(tab)  ,[Current_year_to_compare] = case when month(getdate()) = 4 and date between @Last_FY_Start and @FY_END_current then 1#(lf)#(tab)  when month(getdate()) != 4 and date between  @FY_Start_current and @FY_END_current  then 1 ELSE 0  end #(lf)#(lf)#(tab)  ,[FY_to_Compare] = case when month(getdate()) = 4 and date between  dateadd(year,-1,@Last_FY_Start) and @Last_FY_End then 1#(lf)#(tab)  when month(getdate()) != 4 and date between  @Last_FY_Start and @FY_END_current then 1 ELSE 0  END#(lf)#(lf)      #(lf)from [CCG_Reference].[Reference].[vw_DateLookup] as d#(lf)#(lf)left join #latest_reporting_month as l on  d.FinancialMonth between l.First_Financial_Month and l.Latest_Financial_Month#(lf)#(lf)where [Date] between '20201201' and eomonth(dateadd(month, -1, getdate()))#(lf)#(lf)#(lf)#(lf)order by date#(lf)#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"date", type date}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

