table Cohort
	lineageTag: 37c000bf-fecf-4caa-9f83-b75b88c89ecd

	measure Diabetic_population = DISTINCTCOUNT(Cohort[Derived_Pseudo_NHS])
		formatString: 0
		lineageTag: da81c2b0-2505-4f6e-bc1d-74d1c5d874f6

	measure Population = distinctcount(Cohort[Derived_Pseudo_NHS])
		formatString: 0
		lineageTag: 22770032-9863-41e7-8294-898c9771ec55

	measure cohort_count = calculate(DISTINCTCOUNT(Cohort[Derived_Pseudo_NHS]),Cohort[Cohortflag] = 1)
		formatString: 0
		lineageTag: 412ea64a-8873-45e0-9a7b-e23a4cff5040

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: 200d7863-a116-4e19-85d2-9663804c0b15
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: ea789e93-b78c-49a5-9e85-e622392622a4
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 21c9a3e9-5f8c-487c-860c-0c45f72b5204
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Derived_Age
		dataType: int64
		formatString: 0
		lineageTag: ce0f5330-4301-48ee-a76d-37e57881f9f9
		summarizeBy: sum
		sourceColumn: Derived_Age

		annotation SummarizationSetBy = Automatic

	column AgeBand5yr
		dataType: string
		lineageTag: c9b16421-3a70-4fdd-b7c8-6c1a89f712a4
		summarizeBy: none
		sourceColumn: AgeBand5yr

		annotation SummarizationSetBy = Automatic

	column AgeBand10yr
		dataType: string
		lineageTag: f29aa576-b456-4937-857d-7b53bf361043
		summarizeBy: none
		sourceColumn: AgeBand10yr
		sortByColumn: Age_band_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: ce2cf9e1-3bc2-4f57-b1d1-93e469989e0a
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column EthnicOrigin
		dataType: string
		lineageTag: 4f5c8bb3-ae19-4f13-a30f-136b776980c6
		summarizeBy: none
		sourceColumn: EthnicOrigin

		annotation SummarizationSetBy = Automatic

	column EthnicOriginDescription
		dataType: string
		lineageTag: 7225667e-292e-4db2-a648-9d6473525cf9
		summarizeBy: none
		sourceColumn: EthnicOriginDescription

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: 9b2f29ea-73cd-408e-81e0-18aee23ffa93
		summarizeBy: none
		sourceColumn: PracticeCode

		annotation SummarizationSetBy = Automatic

	column PracNameCurrent
		dataType: string
		lineageTag: e0053c5a-e16b-46f9-a5df-9c1bcbf46aab
		summarizeBy: none
		sourceColumn: PracNameCurrent

		annotation SummarizationSetBy = Automatic

	column CCG_Of_Residence
		dataType: string
		lineageTag: 7c818647-0ced-4567-af5d-f9f5772b0017
		summarizeBy: none
		sourceColumn: CCG_Of_Residence

		annotation SummarizationSetBy = Automatic

	column CCG_Of_Registration
		dataType: string
		lineageTag: 15020b01-5008-47a7-adfa-62295b6cca96
		summarizeBy: none
		sourceColumn: CCG_Of_Registration

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_Postcode
		dataType: int64
		formatString: 0
		lineageTag: fb2a32db-8dbb-46cc-ae10-94a113f271a1
		summarizeBy: sum
		sourceColumn: Derived_Pseudo_Postcode

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingAlone
		dataType: int64
		formatString: 0
		lineageTag: b545e7c7-8da5-47d6-ac87-026b0c364c4a
		summarizeBy: sum
		sourceColumn: Derived_IsLivingAlone

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingInCareHome
		dataType: int64
		formatString: 0
		lineageTag: 3b1b2d7b-c67e-4221-802f-3dffa17a100b
		summarizeBy: sum
		sourceColumn: Derived_IsLivingInCareHome

		annotation SummarizationSetBy = Automatic

	column 'LSOA code'
		dataType: string
		lineageTag: 119dd22d-81c3-4189-9915-ef801a600415
		summarizeBy: none
		sourceColumn: LSOA code

		annotation SummarizationSetBy = Automatic

	column 'Current District Ward code'
		dataType: string
		lineageTag: 7b901704-dcff-4e61-9bb7-dfc6535d4215
		summarizeBy: none
		sourceColumn: Current District Ward code

		annotation SummarizationSetBy = Automatic

	column 'Current District Ward name'
		dataType: string
		lineageTag: 2086ad5a-c729-4e28-8c5b-b2718b41f7b9
		summarizeBy: none
		sourceColumn: Current District Ward name

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: 0e2ad0e4-b08b-42b8-8e69-605c83028a7b
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: double
		formatString: 0
		lineageTag: 0fbcbb2b-7eaf-4acf-926e-f23a84c45df8
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column IMDcountyQuintile
		dataType: double
		lineageTag: b0ff2382-a442-49fb-a714-2615e53f071c
		summarizeBy: sum
		sourceColumn: IMDcountyQuintile

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Easting
		dataType: string
		lineageTag: 9b25a1a4-b258-4b8a-8122-219a0a34ed4c
		summarizeBy: none
		sourceColumn: Easting

		annotation SummarizationSetBy = Automatic

	column Northing
		dataType: string
		lineageTag: e68b1222-e3b1-40f8-bfa5-2cf00b51fab6
		summarizeBy: none
		sourceColumn: Northing

		annotation SummarizationSetBy = Automatic

	column OutputArea2011
		dataType: string
		lineageTag: 99d1bd98-e770-4e20-a28a-abbaf60b5fd2
		summarizeBy: none
		sourceColumn: OutputArea2011

		annotation SummarizationSetBy = Automatic

	column RuralUrbanClass
		dataType: string
		lineageTag: b27fb169-e24e-4f1e-a5ca-fa246276ba7e
		summarizeBy: none
		sourceColumn: RuralUrbanClass

		annotation SummarizationSetBy = Automatic

	column LocalityName
		dataType: string
		lineageTag: 06373775-ee0c-40d5-bf15-4519cc130c79
		summarizeBy: none
		sourceColumn: LocalityName

		annotation SummarizationSetBy = Automatic

	column NetworkName
		dataType: string
		lineageTag: 0c448a93-4dc9-4a8c-9b57-e0bf674a3175
		summarizeBy: none
		sourceColumn: NetworkName

		annotation SummarizationSetBy = Automatic

	column InPCData
		dataType: string
		lineageTag: 2e2f41a9-bca5-4dbd-b8f5-a1a2393bccf3
		summarizeBy: none
		sourceColumn: InPCData

		annotation SummarizationSetBy = Automatic

	column EDTotal
		dataType: int64
		formatString: 0
		lineageTag: 4468c1bc-0482-41a8-9f8d-46eeb837479e
		summarizeBy: sum
		sourceColumn: EDTotal

		annotation SummarizationSetBy = Automatic

	column EDCost
		dataType: double
		lineageTag: c229eed7-ca8e-4909-89f7-62d9ae5dde04
		summarizeBy: sum
		sourceColumn: EDCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDonlyAETotal
		dataType: int64
		formatString: 0
		lineageTag: 974bf3d7-b585-49c2-836c-4c2119bc5ba0
		summarizeBy: sum
		sourceColumn: EDonlyAETotal

		annotation SummarizationSetBy = Automatic

	column EDonlyAECost
		dataType: double
		lineageTag: 4197d9a2-a192-4777-9e5c-e9a0e8f30eee
		summarizeBy: sum
		sourceColumn: EDonlyAECost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDonlyMIUTotal
		dataType: int64
		formatString: 0
		lineageTag: 681ce538-1e66-415c-937e-75bc327fe703
		summarizeBy: sum
		sourceColumn: EDonlyMIUTotal

		annotation SummarizationSetBy = Automatic

	column EDonlyMIUCost
		dataType: double
		lineageTag: b142ff22-e18c-472a-9145-2df0459910d9
		summarizeBy: sum
		sourceColumn: EDonlyMIUCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ElectiveAdmTotal
		dataType: int64
		formatString: 0
		lineageTag: 36722833-a0f5-49d9-8226-405a370ff072
		summarizeBy: sum
		sourceColumn: ElectiveAdmTotal

		annotation SummarizationSetBy = Automatic

	column ElectiveBedDaysTotal
		dataType: int64
		formatString: 0
		lineageTag: 81bb630d-41c6-4146-b98d-b8390cfccfbb
		summarizeBy: sum
		sourceColumn: ElectiveBedDaysTotal

		annotation SummarizationSetBy = Automatic

	column ElectiveAdmTotalCost
		dataType: double
		lineageTag: 12d6d1ec-d964-45d8-9c55-2462f9fa3458
		summarizeBy: sum
		sourceColumn: ElectiveAdmTotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AdmTotalBedDays
		dataType: int64
		formatString: 0
		lineageTag: 44a03627-1996-4646-bf5c-51fa396f3346
		summarizeBy: sum
		sourceColumn: AdmTotalBedDays

		annotation SummarizationSetBy = Automatic

	column AdmAvgLOS
		dataType: double
		lineageTag: 40fde247-8ea4-49dc-9dd1-e033cd88e95e
		summarizeBy: sum
		sourceColumn: AdmAvgLOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EmergencyAdmTotal
		dataType: int64
		formatString: 0
		lineageTag: 5542d7ca-9c45-4df7-a6e9-adf5bc9ac341
		summarizeBy: sum
		sourceColumn: EmergencyAdmTotal

		annotation SummarizationSetBy = Automatic

	column EmergencyBedDaysTotal
		dataType: int64
		formatString: 0
		lineageTag: 66ac3af5-6091-4258-944e-7659e5cf5cad
		summarizeBy: sum
		sourceColumn: EmergencyBedDaysTotal

		annotation SummarizationSetBy = Automatic

	column EmergencyAdmTotalCost
		dataType: double
		lineageTag: 74ba6d1b-ad78-43f9-b174-5ffa201feb73
		summarizeBy: sum
		sourceColumn: EmergencyAdmTotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AdmTotal
		dataType: int64
		formatString: 0
		lineageTag: c553ee94-4511-464f-8352-5ac38d8365e3
		summarizeBy: sum
		sourceColumn: AdmTotal

		annotation SummarizationSetBy = Automatic

	column AdmTotalCost
		dataType: double
		lineageTag: b3b8e0e6-8e6d-4413-96a9-36dd4ebda674
		summarizeBy: sum
		sourceColumn: AdmTotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OPAttFirstTotal
		dataType: int64
		formatString: 0
		lineageTag: 9909489f-17b1-4b30-9ba4-711a017e5875
		summarizeBy: sum
		sourceColumn: OPAttFirstTotal

		annotation SummarizationSetBy = Automatic

	column OPAttFUTotal
		dataType: int64
		formatString: 0
		lineageTag: d98e3f40-fcc5-4031-9976-0f120ac35a3c
		summarizeBy: sum
		sourceColumn: OPAttFUTotal

		annotation SummarizationSetBy = Automatic

	column OPProcTotal
		dataType: int64
		formatString: 0
		lineageTag: 3078b663-9472-4f21-8aea-f917d3fbe79d
		summarizeBy: sum
		sourceColumn: OPProcTotal

		annotation SummarizationSetBy = Automatic

	column OPTotal
		dataType: int64
		formatString: 0
		lineageTag: 87ec8671-b9c7-4e01-8472-c7ca102d06c9
		summarizeBy: sum
		sourceColumn: OPTotal

		annotation SummarizationSetBy = Automatic

	column OPTotalCost
		dataType: double
		lineageTag: 108cf054-863c-48c8-bf2c-fdb04661d421
		summarizeBy: sum
		sourceColumn: OPTotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GPapptTotal
		dataType: int64
		formatString: 0
		lineageTag: 62343e9f-1429-4c58-8616-f1d9af4ff581
		summarizeBy: sum
		sourceColumn: GPapptTotal

		annotation SummarizationSetBy = Automatic

	column GPapptTotalEstCost
		dataType: int64
		formatString: 0
		lineageTag: dd97dce8-cfd8-4421-a127-b0b44d9e4643
		summarizeBy: sum
		sourceColumn: GPapptTotalEstCost

		annotation SummarizationSetBy = Automatic

	column CCTotal
		dataType: int64
		formatString: 0
		lineageTag: 2f42f062-2aef-46ae-aa51-868170ea93f4
		summarizeBy: sum
		sourceColumn: CCTotal

		annotation SummarizationSetBy = Automatic

	column CommAdsTotal
		dataType: int64
		formatString: 0
		lineageTag: c438392c-8dd9-43c0-a4fa-cf9c7e171c67
		summarizeBy: sum
		sourceColumn: CommAdsTotal

		annotation SummarizationSetBy = Automatic

	column MHAdmissionTotal
		dataType: int64
		formatString: 0
		lineageTag: e242b402-145c-4a26-a275-b8c870e9e374
		summarizeBy: sum
		sourceColumn: MHAdmissionTotal

		annotation SummarizationSetBy = Automatic

	column MHContactTotal
		dataType: int64
		formatString: 0
		lineageTag: 7357b3c6-a230-4228-8cbd-ebe4228c2f26
		summarizeBy: sum
		sourceColumn: MHContactTotal

		annotation SummarizationSetBy = Automatic

	column 111Total
		dataType: int64
		formatString: 0
		lineageTag: 86757651-003f-467c-b621-afed55b311ed
		summarizeBy: sum
		sourceColumn: 111Total

		annotation SummarizationSetBy = Automatic

	column HIUFlag
		dataType: int64
		formatString: 0
		lineageTag: b8b62633-639b-4a93-87ad-cf67eb01bd35
		summarizeBy: sum
		sourceColumn: HIUFlag

		annotation SummarizationSetBy = Automatic

	column ccahFlag
		dataType: int64
		formatString: 0
		lineageTag: 121b0086-202e-4888-af76-6544beea5a17
		summarizeBy: sum
		sourceColumn: ccahFlag

		annotation SummarizationSetBy = Automatic

	column rrFlag
		dataType: int64
		formatString: 0
		lineageTag: 4d65d507-cebc-487d-863e-8ca385f00850
		summarizeBy: sum
		sourceColumn: rrFlag

		annotation SummarizationSetBy = Automatic

	column CavernFlag
		dataType: int64
		formatString: 0
		lineageTag: 1a7614a4-b571-45cf-823f-ef50b11db3b7
		summarizeBy: sum
		sourceColumn: CavernFlag

		annotation SummarizationSetBy = Automatic

	column CWSFlag
		dataType: int64
		formatString: 0
		lineageTag: 650d5225-db44-488f-a66e-467a79b5c5a1
		summarizeBy: sum
		sourceColumn: CWSFlag

		annotation SummarizationSetBy = Automatic

	column ICTFlag
		dataType: int64
		formatString: 0
		lineageTag: 28c598c1-e2a3-455a-834e-12029cab4ade
		summarizeBy: sum
		sourceColumn: ICTFlag

		annotation SummarizationSetBy = Automatic

	column 2gCaseloadFlag
		dataType: int64
		formatString: 0
		lineageTag: 7749374c-e8d3-4e16-834a-bf7908fffcab
		summarizeBy: sum
		sourceColumn: 2gCaseloadFlag

		annotation SummarizationSetBy = Automatic

	column BMI
		dataType: double
		lineageTag: 5865b26a-b753-4d66-94a3-984eeb0f6c67
		summarizeBy: sum
		sourceColumn: BMI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ParkHomeFlag
		dataType: int64
		formatString: 0
		lineageTag: 834c553d-2adf-4748-a58e-a202ab5a1c30
		summarizeBy: sum
		sourceColumn: ParkHomeFlag

		annotation SummarizationSetBy = Automatic

	column CarePlanFlag
		dataType: int64
		formatString: 0
		lineageTag: 7176be20-2aff-4d4f-bddc-0ef4b4fa00e6
		summarizeBy: sum
		sourceColumn: CarePlanFlag

		annotation SummarizationSetBy = Automatic

	column HouseboundFlag
		dataType: int64
		formatString: 0
		lineageTag: 4ada868b-81a5-46eb-b021-c507ea6b4208
		summarizeBy: sum
		sourceColumn: HouseboundFlag

		annotation SummarizationSetBy = Automatic

	column IAPTFlag
		dataType: int64
		formatString: 0
		lineageTag: a319dce0-6ba8-44fb-8c1d-7a565a6a0b77
		summarizeBy: sum
		sourceColumn: IAPTFlag

		annotation SummarizationSetBy = Automatic

	column eFI_Score_derived
		dataType: double
		lineageTag: 3c292fe9-c0ad-40f0-8ef3-1a61324becd8
		summarizeBy: sum
		sourceColumn: eFI_Score_derived

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column eFI_Catgory_derived
		dataType: string
		lineageTag: e5af9b2f-306d-459f-a875-d4b71de37446
		summarizeBy: none
		sourceColumn: eFI_Catgory_derived

		annotation SummarizationSetBy = Automatic

	column LTCCountDerived
		dataType: int64
		formatString: 0
		lineageTag: 4335fadd-69b6-4c08-ae1f-17ca82afea51
		summarizeBy: sum
		sourceColumn: LTCCountDerived

		annotation SummarizationSetBy = Automatic

	column ObesityDerived
		dataType: int64
		formatString: 0
		lineageTag: cc177ce7-1897-41cd-903d-c233fd0c4592
		summarizeBy: sum
		sourceColumn: ObesityDerived

		annotation SummarizationSetBy = Automatic

	column SmokerDerived
		dataType: int64
		formatString: 0
		lineageTag: 64859e19-5bd1-4484-8a33-fb3c82d582de
		summarizeBy: sum
		sourceColumn: SmokerDerived

		annotation SummarizationSetBy = Automatic

	column AsthmaDerived
		dataType: int64
		formatString: 0
		lineageTag: 49aa6118-8f02-4035-9799-7b053059ccff
		summarizeBy: sum
		sourceColumn: AsthmaDerived

		annotation SummarizationSetBy = Automatic

	column COPDDerived
		dataType: int64
		formatString: 0
		lineageTag: 70568dc2-6058-493c-b9e2-69decadfe75c
		summarizeBy: sum
		sourceColumn: COPDDerived

		annotation SummarizationSetBy = Automatic

	column DementiaDerived
		dataType: int64
		formatString: 0
		lineageTag: a7557581-d7b0-4fa1-b6e6-9f8b193b2ff1
		summarizeBy: sum
		sourceColumn: DementiaDerived

		annotation SummarizationSetBy = Automatic

	column DepressionDerived
		dataType: int64
		formatString: 0
		lineageTag: 856435d5-7471-412d-a096-b94eb3105d19
		summarizeBy: sum
		sourceColumn: DepressionDerived

		annotation SummarizationSetBy = Automatic

	column DiabetesDerived
		dataType: int64
		formatString: 0
		lineageTag: f05ac711-249b-4423-b887-3e52e40caaa4
		summarizeBy: sum
		sourceColumn: DiabetesDerived

		annotation SummarizationSetBy = Automatic

	column PalliativeCareDerived
		dataType: int64
		formatString: 0
		lineageTag: f4eec7ea-ea54-4da3-b747-78efe6c555d2
		summarizeBy: sum
		sourceColumn: PalliativeCareDerived

		annotation SummarizationSetBy = Automatic

	column ChronicKidneyDiseaseDerived
		dataType: int64
		formatString: 0
		lineageTag: cef8be52-29d6-486d-8fc3-f77ed42c96d4
		summarizeBy: sum
		sourceColumn: ChronicKidneyDiseaseDerived

		annotation SummarizationSetBy = Automatic

	column EpilepsyDerived
		dataType: int64
		formatString: 0
		lineageTag: a5feab6f-ca4d-4716-b875-4e6da8b9cd24
		summarizeBy: sum
		sourceColumn: EpilepsyDerived

		annotation SummarizationSetBy = Automatic

	column HeartFailureDerived
		dataType: int64
		formatString: 0
		lineageTag: 0c52bddb-d394-4758-976c-3e642d7067c6
		summarizeBy: sum
		sourceColumn: HeartFailureDerived

		annotation SummarizationSetBy = Automatic

	column StrokeDerived
		dataType: int64
		formatString: 0
		lineageTag: 5e0ff050-9d28-4296-923d-d015166e1bd6
		summarizeBy: sum
		sourceColumn: StrokeDerived

		annotation SummarizationSetBy = Automatic

	column AtrialFibrillationDerived
		dataType: int64
		formatString: 0
		lineageTag: cf36769e-605e-4f29-9bf4-97bfcf916163
		summarizeBy: sum
		sourceColumn: AtrialFibrillationDerived

		annotation SummarizationSetBy = Automatic

	column CancerDerived
		dataType: int64
		formatString: 0
		lineageTag: dd966d18-4c9b-4dfd-bd2a-0dcdfb08fb3f
		summarizeBy: sum
		sourceColumn: CancerDerived

		annotation SummarizationSetBy = Automatic

	column CoronaryHeartDiseaseDerived
		dataType: int64
		formatString: 0
		lineageTag: 9ff57e53-de96-4f31-9517-931512dc10db
		summarizeBy: sum
		sourceColumn: CoronaryHeartDiseaseDerived

		annotation SummarizationSetBy = Automatic

	column HypertensionDerived
		dataType: int64
		formatString: 0
		lineageTag: 6a0e6bb1-7248-4ce1-8689-b7d7af86efa2
		summarizeBy: sum
		sourceColumn: HypertensionDerived

		annotation SummarizationSetBy = Automatic

	column HypothyroidismDerived
		dataType: int64
		formatString: 0
		lineageTag: e1039bfd-c266-4fc7-a552-245712cd0336
		summarizeBy: sum
		sourceColumn: HypothyroidismDerived

		annotation SummarizationSetBy = Automatic

	column LearningDisabilityDerived
		dataType: int64
		formatString: 0
		lineageTag: 2c7cc9ef-2cea-435e-a267-6663019dcfef
		summarizeBy: sum
		sourceColumn: LearningDisabilityDerived

		annotation SummarizationSetBy = Automatic

	column MentalIllnessDerived
		dataType: int64
		formatString: 0
		lineageTag: 0f6074de-48a0-4302-92e0-de6bc3318bd1
		summarizeBy: sum
		sourceColumn: MentalIllnessDerived

		annotation SummarizationSetBy = Automatic

	column SegmentHealthLeeds
		dataType: string
		lineageTag: 6086c46c-f1aa-4924-8393-0d20d75eff29
		summarizeBy: none
		sourceColumn: SegmentHealthLeeds

		annotation SummarizationSetBy = Automatic

	column TimePeriodActivity
		dataType: string
		lineageTag: 14a95642-d874-4dde-b508-37e836cc3992
		summarizeBy: none
		sourceColumn: TimePeriodActivity

		annotation SummarizationSetBy = Automatic

	column Cohortflag
		dataType: int64
		formatString: 0
		lineageTag: e88e05b9-84d1-4097-89ec-7e7e80096775
		summarizeBy: sum
		sourceColumn: Cohortflag

		annotation SummarizationSetBy = Automatic

	column Derived_Clean_Diabetes_Type
		dataType: string
		lineageTag: 52d3f7cb-4e19-4cfa-9de8-376b59861a3c
		summarizeBy: none
		sourceColumn: Derived_Clean_Diabetes_Type

		annotation SummarizationSetBy = Automatic

	column Age_band_order
		dataType: int64
		formatString: 0
		lineageTag: 52a17921-5df1-4f99-91ec-295fd2621cc3
		summarizeBy: sum
		sourceColumn: Age_band_order

		annotation SummarizationSetBy = Automatic

	column diabetes_type
		dataType: string
		lineageTag: 4401726f-cf26-4b0b-b4da-e78e2573b6b1
		summarizeBy: none
		sourceColumn: diabetes_type

		annotation SummarizationSetBy = Automatic

	partition Cohort-f6e68e63-f536-4670-9d7d-1eee6890bea2 = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("grh-ccg-sql", "BIReports", [Query="/****** Script for SelectTopNRows command from SSMS  ******/#(lf)SET ANSI_NULLS ON#(lf)SET QUOTED_IDENTIFIER ON#(lf)set nocount on#(lf)set ansi_warnings off #(lf)#(lf)#(lf)IF OBJECT_ID('tempdb..#cohort') is not null#(lf)drop table #cohort#(lf)#(lf)SELECT DISTINCT #(lf)Derived_Pseudo_NHS=[NHS_Number]#(lf)INTO #COHORT#(lf)FROM [Data_Mart_Primary_Care_Meds].[Import].[Patient_Medication] AS [GP]#(lf)WHERE [Paid_BNF_Code] LIKE '2148%'#(lf)#(lf)#(lf)#(lf)SELECT distinct 1 as Counter#(lf),[Derived_Pseudo_NHS]#(lf)      ,[Gender]#(lf)      ,[Derived_Age]#(lf)      ,[AgeBand5yr]#(lf)      ,[AgeBand10yr]#(lf)      ,[AgeBand]#(lf)      ,[EthnicOrigin]#(lf)      ,[EthnicOriginDescription]#(lf)      ,[PracticeCode]#(lf)      ,[PracNameCurrent]#(lf)      ,[CCG_Of_Residence]#(lf)      ,[CCG_Of_Registration]#(lf)      ,[Derived_Pseudo_Postcode]#(lf)      ,[Derived_IsLivingAlone]#(lf)      ,[Derived_IsLivingInCareHome]#(lf)      ,[LSOA code]#(lf)      ,[Current District Ward code]#(lf)      ,[Current District Ward name]#(lf)      ,[District]#(lf)      ,[IMDcountyDecile]#(lf)      ,[IMDcountyQuintile]#(lf)      ,[Easting]#(lf)      ,[Northing]#(lf)      ,[OutputArea2011]#(lf)      ,[RuralUrbanClass]#(lf)      ,[LocalityName]#(lf)      ,[NetworkName]#(lf)      ,[InPCData]#(lf)      ,[EDTotal]#(lf)      ,[EDCost]#(lf)      ,[EDonlyAETotal]#(lf)      ,[EDonlyAECost]#(lf)      ,[EDonlyMIUTotal]#(lf)      ,[EDonlyMIUCost]#(lf)      ,[ElectiveAdmTotal]#(lf)      ,[ElectiveBedDaysTotal]#(lf)      ,[ElectiveAdmTotalCost]#(lf)      ,[AdmTotalBedDays]#(lf)      ,[AdmAvgLOS]#(lf)      ,[EmergencyAdmTotal]#(lf)      ,[EmergencyBedDaysTotal]#(lf)      ,[EmergencyAdmTotalCost]#(lf)      ,[AdmTotal]#(lf)      ,[AdmTotalCost]#(lf)      ,[OPAttFirstTotal]#(lf)      ,[OPAttFUTotal]#(lf)      ,[OPProcTotal]#(lf)      ,[OPTotal]#(lf)      ,[OPTotalCost]#(lf)      ,[GPapptTotal]#(lf)      ,[GPapptTotalEstCost]#(lf)      ,[CCTotal]#(lf)      ,[CommAdsTotal]#(lf)      ,[MHAdmissionTotal]#(lf)      ,[MHContactTotal]#(lf)      ,[111Total]#(lf)   #(lf)      ,[HIUFlag]#(lf)      ,[ccahFlag]#(lf)      ,[rrFlag]#(lf)      ,[CavernFlag]#(lf)      ,[CWSFlag]#(lf)      ,[ICTFlag]#(lf)      ,[2gCaseloadFlag]#(lf)      ,[mpi].[BMI]#(lf)      ,[ParkHomeFlag]#(lf)      ,[CarePlanFlag]#(lf)      ,[HouseboundFlag]#(lf)      ,[IAPTFlag]#(lf)      ,[eFI_Score_derived]#(lf)      ,[eFI_Catgory_derived]#(lf)      ,[LTCCountDerived]#(lf)      ,[ObesityDerived]#(lf)      ,[SmokerDerived]#(lf)      ,[AsthmaDerived]#(lf)      ,[COPDDerived]#(lf)      ,[DementiaDerived]#(lf)      ,[DepressionDerived]#(lf)      ,[DiabetesDerived]#(lf)      ,[PalliativeCareDerived]#(lf)      ,[ChronicKidneyDiseaseDerived]#(lf)      ,[EpilepsyDerived]#(lf)      ,[HeartFailureDerived]#(lf)      ,[StrokeDerived]#(lf)      ,[AtrialFibrillationDerived]#(lf)      ,[CancerDerived]#(lf)      ,[CoronaryHeartDiseaseDerived]#(lf)      ,[HypertensionDerived]#(lf)      ,[HypothyroidismDerived]#(lf)      ,[LearningDisabilityDerived]#(lf)      ,[MentalIllnessDerived]#(lf)      ,[SegmentHealthLeeds]#(lf)      ,[TimePeriodActivity]#(lf)#(tab)  ,[d].[Derived_Clean_Diabetes_Type]#(lf),case when#(lf)#(tab)  Derived_Pseudo_NHS in (select *#(lf)#(tab)  from #cohort)#(lf) then 1 else 0 end as Cohortflag#(lf) FROM [BIReports].[MPI].[MPI_current] [MPI]#(lf)#(lf) left join [Data_Mart_National_Diabetes_Audit].[NDA].[core_NDA] [d]#(lf) on [mpi].[derived_pseudo_nhs] = [d].[Derived_Pseudo_NHS_Number]"]),
				    #"Added Conditional Column" = Table.AddColumn(Source, "Age_band_order", each if [AgeBand10yr] = "0-9" then 1 else if [AgeBand10yr] = "10-19" then 2 else if [AgeBand10yr] = "20-29" then 3 else if [AgeBand10yr] = "30-39" then 4 else if [AgeBand10yr] = "40-49" then 5 else if [AgeBand10yr] = "50-59" then 6 else if [AgeBand10yr] = "60-69" then 7 else if [AgeBand10yr] = "70-79" then 8 else if [AgeBand10yr] = "80-89" then 9 else if [AgeBand10yr] = "90+" then 10 else 0),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Age_band_order", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "diabetes_type", each if [Derived_Clean_Diabetes_Type] = "01" then "Type 1"
				else if [Derived_Clean_Diabetes_Type] = "02" then "Type 2"
				else if [Derived_Clean_Diabetes_Type]  = "99" then "Other/Unknown"
				else if [Derived_Clean_Diabetes_Type]  = "06" then "Other/Unknown"
				else if [Derived_Clean_Diabetes_Type]  = "08" then "Other/Unknown"
				else if ([Derived_Clean_Diabetes_Type] is null and [DiabetesDerived] = 1) then "Other/Unknown (QOF)" 
				else "N/A")
				in
				    #"Added Custom"
				```

	annotation PBI_ResultType = Table

