table date_table
	lineageTag: e7d617bd-015d-4672-aac2-ea2f6d63e706
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 3032d405-5278-4d3f-9c25-73bcc23055b0
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: 1073026e-19c4-46b7-859b-30d38b923d1e
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: a17c74c1-1ae2-4d4c-9e8b-d6a0ae26a2a5
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: f46bca79-c3ac-4e74-8b05-6d7f97f51fbc
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 07bd0f79-449f-4d0d-a881-20fdee55f049
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 8304aea5-c08b-412f-95fa-aa0b2fc770a5
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: a92f7ffa-b3d6-4142-a472-864139faee68
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: dd6add1f-419c-4c0e-abe3-bf25ca2a824f
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: bf7de1bf-9c7a-47a4-80f4-e90e5fe3130e
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 91ebbebf-c40b-457c-8844-a926ff416396
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: f4289367-1ef2-4237-9277-648ac6696fd2
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 41cbcf41-5c37-4e73-b180-4b1a3b79c728
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: faa9a3a3-2828-4ac9-8eaf-2a4bf0a83add
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 9b6adb97-e538-4d9f-bb88-022582e26660
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: bca60b07-8e3c-4b1e-986e-4d9ee73bf928
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 9e9d2430-2a37-4b6f-9f73-16abb38fe2ce
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Year'
		dataType: string
		lineageTag: fb5c319a-b613-4236-a534-d57ee2d23876
		summarizeBy: none
		sourceColumn: Month Year

		annotation SummarizationSetBy = Automatic

	hierarchy 'financial_year Hierarchy'
		lineageTag: 59bfa55d-e762-4fa8-b365-351797a1d6f0

		level 'Financial Year'
			lineageTag: cd721b7b-a385-4a9c-a6be-62ef2d204a02
			column: financial_year

		level Month
			lineageTag: 80f74483-8b31-420c-829b-8c87ec5ff6a7
			column: month_name

	partition date_table-b4c61e4d-8ba8-4a96-a19b-469f407d87a7 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="select [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)      #(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] >= '20190401'"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}, {"is_holiday", Int64.Type}, {"is_weekend", Int64.Type}, {"month", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each Date.Year([date])),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Custom", "Year"}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Renamed Columns", "Month Year", each Text.Combine({[month_name], Text.From([Year], "en-GB")}, " "), type text)
				in
				    #"Inserted Merged Column"

	annotation PBI_ResultType = Table

