table REF_PNG
	lineageTag: 70f51013-e7bb-4c69-ac19-12f39e13c133

	column ACGPatientNeedsGroup
		dataType: string
		lineageTag: ff098d39-c8dd-4580-9e46-9373ae3d388c
		summarizeBy: none
		sourceColumn: ACGPatientNeedsGroup

		annotation SummarizationSetBy = Automatic

	column 'ACG Group Number'
		dataType: string
		lineageTag: 014ad1bf-71ee-4598-baee-40e23ae415d2
		summarizeBy: none
		sourceColumn: ACG Group Number

		annotation SummarizationSetBy = Automatic

	partition REF_PNG = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select distinct patient_need_group as ""ACGPatientNeedsGroup"" from data_mart_acg.vw_acgresults_full where islatest=1 and patient_need_group is not null", null, [EnableFolding=true]),
				    #"Added Custom" = Table.AddColumn(Source, "ACG Group Number", each Text.Start([ACGPatientNeedsGroup], 2))
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

