table LoS
	lineageTag: adb5b823-296d-43e8-83a2-bfb089bb04e0

	column UniqueCDSidentifier
		dataType: string
		lineageTag: 66db713a-1fec-417c-b0f2-8ee4d25dce24
		summarizeBy: none
		sourceColumn: UniqueCDSidentifier

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: 23af0fc4-090e-433c-b1ce-4dd88805f847
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column HospitalProviderSpellNumber
		dataType: string
		lineageTag: 5b0e1a3c-ae84-4960-bba3-93ebaf5aff8e
		summarizeBy: none
		sourceColumn: HospitalProviderSpellNumber

		annotation SummarizationSetBy = Automatic

	column StartDate_HPS
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8ec69e5e-0fbe-475a-884b-cde479ca92c7
		summarizeBy: none
		sourceColumn: StartDate_HPS

		variation Variation
			isDefault
			relationship: 33d877dc-05af-41ca-a680-2ffaaf9e1a33
			defaultHierarchy: LocalDateTable_df527161-f4a5-4ce4-93ef-2f81f65826c4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DischDate_HPS
		dataType: dateTime
		formatString: Short Date
		lineageTag: 663e8610-a20c-45fa-97d3-565d3fe282dd
		summarizeBy: none
		sourceColumn: DischDate_HPS

		variation Variation
			isDefault
			relationship: 19cc0672-04b8-4820-8cad-628cfea3df47
			defaultHierarchy: LocalDateTable_065acc98-ecfe-474f-9227-28e735b2af72.'Date Hierarchy'

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column StartDate_HPS_MonthYear
		dataType: string
		lineageTag: d48c7248-2248-4571-9246-ce89b97f2583
		summarizeBy: none
		sourceColumn: StartDate_HPS_MonthYear

		annotation SummarizationSetBy = Automatic

	column StartDate_HPS_FinYear
		dataType: string
		lineageTag: b80d29bf-02cc-4242-8535-e2202f96f75f
		summarizeBy: none
		sourceColumn: StartDate_HPS_FinYear

		annotation SummarizationSetBy = Automatic

	column DischDate_HPS_MonthYear
		dataType: string
		lineageTag: e14c4314-b5cb-4497-b510-b4f20f62f9d4
		summarizeBy: none
		sourceColumn: DischDate_HPS_MonthYear
		sortByColumn: DischDate_HPS_MonthYear_No

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DischDate_HPS_MonthYear_No
		dataType: string
		lineageTag: 5897ede0-dfae-46ab-b237-710e739a637f
		summarizeBy: none
		sourceColumn: DischDate_HPS_MonthYear_No

		annotation SummarizationSetBy = Automatic

	column DischDate_HPS_FinYear
		dataType: string
		lineageTag: 923b5350-333d-4d55-80da-fc9c600250b6
		summarizeBy: none
		sourceColumn: DischDate_HPS_FinYear

		annotation SummarizationSetBy = Automatic

	column admitting_ward_code
		dataType: string
		lineageTag: e17895ca-2652-48d3-b3d6-4dec8bbf3585
		summarizeBy: none
		sourceColumn: admitting_ward_code

		annotation SummarizationSetBy = Automatic

	column discharging_ward_code
		dataType: string
		lineageTag: ef6a26c8-81b1-4a28-b630-69b9358ca0d5
		summarizeBy: none
		sourceColumn: discharging_ward_code

		annotation SummarizationSetBy = Automatic

	column all_ward_codes
		dataType: string
		lineageTag: 95b84846-9112-44a9-a857-09311dbfd1b8
		summarizeBy: none
		sourceColumn: all_ward_codes

		annotation SummarizationSetBy = Automatic

	column admitting_ward
		dataType: string
		lineageTag: b415e0b2-cbdd-4465-b45e-f94bda417753
		summarizeBy: none
		sourceColumn: admitting_ward

		annotation SummarizationSetBy = Automatic

	column discharging_ward
		dataType: string
		lineageTag: c65e0434-487b-4f48-b7ea-fa77fdc7488d
		summarizeBy: none
		sourceColumn: discharging_ward

		annotation SummarizationSetBy = Automatic

	column all_wards
		dataType: string
		lineageTag: 2f705060-dab2-401b-8184-42092490d6c3
		summarizeBy: none
		sourceColumn: all_wards

		annotation SummarizationSetBy = Automatic

	column DischMethod_HPS
		dataType: string
		lineageTag: f72166ad-7d0b-451a-a8e1-87d4be8f20c7
		summarizeBy: none
		sourceColumn: DischMethod_HPS

		annotation SummarizationSetBy = Automatic

	column DischMethod_HPS_Desc
		dataType: string
		lineageTag: 2a1e82d6-7067-4b49-8623-b456a1b370ff
		summarizeBy: none
		sourceColumn: DischMethod_HPS_Desc

		annotation SummarizationSetBy = Automatic

	column WardSplit
		dataType: string
		lineageTag: d8cde27a-b307-468d-9912-9fe2c6bc5c00
		summarizeBy: none
		sourceColumn: WardSplit

		annotation SummarizationSetBy = Automatic

	column WGWW1GRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: fbb7138f-8d41-480f-9e36-21d770aa9a5f
		summarizeBy: sum
		sourceColumn: WGWW1GRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WGWW2GRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 340c7f8d-09f5-4032-b18a-339bc623db18
		summarizeBy: sum
		sourceColumn: WGWW2GRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WRYWCGHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9469c128-a6ad-4e5c-86d0-cacd72e106a2
		summarizeBy: sum
		sourceColumn: WRYWCGHA_Flag

		annotation SummarizationSetBy = Automatic

	column WGTNCGHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 87109c37-18dd-4f2d-be57-ae82e74a60a3
		summarizeBy: sum
		sourceColumn: WGTNCGHA_Flag

		annotation SummarizationSetBy = Automatic

	column WT3AGRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2feafbc7-d622-4780-a775-2e85862d15d3
		summarizeBy: sum
		sourceColumn: WT3AGRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WT7AGRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 4bfcab55-8343-4762-9d38-69bac5d05d96
		summarizeBy: sum
		sourceColumn: WT7AGRHA_Flag

		annotation SummarizationSetBy = Automatic

	column WT7BGRHA_Flag
		dataType: int64
		formatString: 0
		lineageTag: 85ae077e-0e4e-4e33-9b0a-32fe731bff54
		summarizeBy: sum
		sourceColumn: WT7BGRHA_Flag

		annotation SummarizationSetBy = Automatic

	column IP_LOS
		dataType: int64
		formatString: 0
		lineageTag: eaccc2a2-0c5a-41a6-89f2-68b497e70eab
		summarizeBy: sum
		sourceColumn: IP_LOS

		annotation SummarizationSetBy = Automatic

	column ZeroLoSFlag
		dataType: string
		lineageTag: 89c85821-9091-46dc-a204-8e03400188d8
		summarizeBy: none
		sourceColumn: ZeroLoSFlag

		annotation SummarizationSetBy = Automatic

	column IntendedManagement
		dataType: string
		lineageTag: 2bda6b9c-7aa0-4f33-be0d-9d35ab0cd924
		summarizeBy: none
		sourceColumn: IntendedManagement

		annotation SummarizationSetBy = Automatic

	column AgeasonAdmission
		dataType: int64
		formatString: 0
		lineageTag: 23730a4a-7abc-4574-8726-0fee27660d5a
		summarizeBy: sum
		sourceColumn: AgeasonAdmission

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: 409e61f4-5109-4a37-8989-391a8d2d23e8
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column AdmissionType
		dataType: string
		lineageTag: b1d91fab-db3b-4cf4-8713-43e4f310f40a
		summarizeBy: none
		sourceColumn: AdmissionType

		annotation SummarizationSetBy = Automatic

	column AdmissionType2
		dataType: string
		lineageTag: 93c8e0ed-b2a9-41c8-b8af-0d51f9b21cd6
		summarizeBy: none
		sourceColumn: AdmissionType2

		annotation SummarizationSetBy = Automatic

	column SpellCount
		dataType: int64
		formatString: 0
		lineageTag: 5980f0be-c623-440f-9155-b1ff35b18b75
		summarizeBy: sum
		sourceColumn: SpellCount

		annotation SummarizationSetBy = Automatic

	column latestRefresh = format(max(LoS[LatestRefreshDate]),"dd mmmm yyyy")
		lineageTag: 6155a261-300e-43c4-8626-c6784f7595c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column LatestRefreshDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 94fceda2-d02b-4e3b-865b-05c524b4d192
		summarizeBy: none
		sourceColumn: LatestRefreshDate

		variation Variation
			isDefault
			relationship: 1a09ccf5-3ad5-487a-a7c0-91642858aab7
			defaultHierarchy: LocalDateTable_d4da4f48-8d93-4644-ab2d-ae749c864f29.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column TrialWard_or_Other
		dataType: string
		lineageTag: 64d46958-ed92-4c84-b613-3b6beb2b7313
		summarizeBy: none
		sourceColumn: TrialWard_or_Other

		annotation SummarizationSetBy = Automatic

	column SDECSplit
		dataType: string
		lineageTag: cb797f3d-897b-44f9-934c-981efb379a55
		summarizeBy: none
		sourceColumn: SDECSplit

		annotation SummarizationSetBy = Automatic

	column SDEC_Flag
		dataType: string
		lineageTag: d1ab277d-c797-490b-9eea-a1ecabdb1a86
		summarizeBy: none
		sourceColumn: SDEC_Flag

		annotation SummarizationSetBy = Automatic

	partition LoS-853033d9-c32b-4593-92b5-2323f12b4956 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "powerbi_reporting"),
				    dbo_LoS = Source{[Schema="dbo",Item="LoS"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_LoS,{{"StartDate_HPS", type date}, {"DischDate_HPS", type date}, {"ZeroLoSFlag", type text}}),
				    #"ZeroLoSFlag value replaced 0" = Table.ReplaceValue(#"Changed Type","0","No",Replacer.ReplaceText,{"ZeroLoSFlag"}),
				    #"ZeroLoSFlag value replaced 1" = Table.ReplaceValue(#"ZeroLoSFlag value replaced 0","1","Yes",Replacer.ReplaceText,{"ZeroLoSFlag"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"ZeroLoSFlag value replaced 1",{{"SDEC_Flag", type text}}),
				    #"SDECFlag value replaced 0" = Table.ReplaceValue(#"Changed Type1","0","No",Replacer.ReplaceText,{"SDEC_Flag"}),
				    #"SDECFlag value replaced 1" = Table.ReplaceValue(#"SDECFlag value replaced 0","1","Yes",Replacer.ReplaceText,{"SDEC_Flag"})
				in
				    #"SDECFlag value replaced 1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

