table Readmissions
	lineageTag: a9ebc3d8-3b88-4d18-83a8-a1d6a1ca779e

	column Pathway
		dataType: string
		lineageTag: c6a75eba-44f9-4a04-abe1-64e2fb7aaf62
		summarizeBy: none
		sourceColumn: Pathway

		annotation SummarizationSetBy = Automatic

	column Diagnosis_pathway
		dataType: string
		lineageTag: 42cf1f67-2323-4f66-a5a2-b2af8d3dc31d
		summarizeBy: none
		sourceColumn: Diagnosis_pathway

		annotation SummarizationSetBy = Automatic

	column DischargeDate_FromHospitalProviderSpell_FinancialYear
		dataType: string
		lineageTag: 4474aa28-f289-46f4-beff-eeb164b2f82c
		summarizeBy: none
		sourceColumn: DischargeDate_FromHospitalProviderSpell_FinancialYear

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: fdfa1558-4c2d-4784-a7b5-78bd567cc8d8
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Admission_method_group
		dataType: string
		lineageTag: aa59ee55-2cc0-483b-9725-9b2847f6a597
		summarizeBy: none
		sourceColumn: Admission_method_group

		annotation SummarizationSetBy = Automatic

	column Readmission_diagnosis_group
		dataType: string
		lineageTag: fafde080-3176-4c11-a507-539e50ff8ffd
		summarizeBy: none
		sourceColumn: Readmission_diagnosis_group

		annotation SummarizationSetBy = Automatic

	column Previous_diagnosis_group
		dataType: string
		lineageTag: 225c96b0-8096-4faf-88cb-45301278d12a
		summarizeBy: none
		sourceColumn: Previous_diagnosis_group

		annotation SummarizationSetBy = Automatic

	column Previous_admission_type
		dataType: string
		lineageTag: 51c7d08c-8aa1-406a-91bc-c3d036d945b8
		summarizeBy: none
		sourceColumn: Previous_admission_type

		annotation SummarizationSetBy = Automatic

	column Readmission_admission_type
		dataType: string
		lineageTag: e634e2ea-3761-494b-8015-df441bce9532
		summarizeBy: none
		sourceColumn: Readmission_admission_type

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: 5a982ef5-475e-40a5-a038-9cee690ea803
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column days_between_admissions
		dataType: int64
		formatString: 0
		lineageTag: e7a591cc-856c-4b4c-92f5-74e0b29d6b61
		summarizeBy: sum
		sourceColumn: days_between_admissions

		annotation SummarizationSetBy = Automatic

	column Re-admitted_within_7_Days_Flag
		dataType: string
		lineageTag: cdad1936-7a42-4168-af9b-7ed96a3b2bd9
		summarizeBy: none
		sourceColumn: Re-admitted_within_7_Days_Flag

		annotation SummarizationSetBy = Automatic

	column row_counter
		dataType: int64
		formatString: 0
		lineageTag: 68e21590-5f4f-4d03-b8d0-c03ae850185a
		summarizeBy: sum
		sourceColumn: row_counter

		annotation SummarizationSetBy = Automatic

	column Adult_Age_Band
		dataType: string
		lineageTag: c2366216-08e7-498f-b67a-e52537d2078d
		summarizeBy: none
		sourceColumn: Adult_Age_Band

		annotation SummarizationSetBy = Automatic

	column Place
		dataType: string
		lineageTag: cfe673d9-20dd-4a69-bcc2-2d7977286ea1
		summarizeBy: none
		sourceColumn: Place

		annotation SummarizationSetBy = Automatic

	column EFI_category
		dataType: string
		lineageTag: 0d17b57e-df5a-41a2-a286-ca6c22995755
		summarizeBy: none
		sourceColumn: EFI_category

		annotation SummarizationSetBy = Automatic

	column Previous_Hopsital_Provider_Spell_Number
		dataType: string
		lineageTag: 68ed1a54-e850-4a63-a5a2-1c1f8e2b5822
		summarizeBy: none
		sourceColumn: Previous_Hopsital_Provider_Spell_Number

		annotation SummarizationSetBy = Automatic

	column Previous_Start_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f8d7a6c7-8eb4-4761-9c63-8993d238f8ed
		summarizeBy: none
		sourceColumn: Previous_Start_Date

		variation Variation
			isDefault
			relationship: 11164f52-08b6-44a9-8e53-4be2471c5a47
			defaultHierarchy: LocalDateTable_6e5b6c00-eaba-48a2-93f2-27e4e4318826.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Previous_End_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6b0b1320-a3c5-4895-b16f-b80a9629ffa5
		summarizeBy: none
		sourceColumn: Previous_End_Date

		variation Variation
			isDefault
			relationship: b2278c77-73fc-4460-aa66-fdeb923f934e
			defaultHierarchy: LocalDateTable_9f7a0b0f-102f-4821-9ed7-861fe36387da.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Readmission_Hopsital_Provider_Spell_Number
		dataType: string
		lineageTag: e567ac6c-4a6c-4075-998e-79ce1f903117
		summarizeBy: none
		sourceColumn: Readmission_Hopsital_Provider_Spell_Number

		annotation SummarizationSetBy = Automatic

	column Readmission_Start_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 75b0b5b2-e13b-496e-9c5c-611cc86766c3
		summarizeBy: none
		sourceColumn: Readmission_Start_Date

		variation Variation
			isDefault
			relationship: dec48a81-a051-4a18-abb7-62f332c9f5e5
			defaultHierarchy: LocalDateTable_3e488404-ffea-42fc-8ab0-71e8444d41cd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Readmission_End_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8153cc83-28ed-4de1-95e1-7e3972d17aa5
		summarizeBy: none
		sourceColumn: Readmission_End_Date

		variation Variation
			isDefault
			relationship: b50f5dfd-4c2a-42ae-960f-045a02fa81ff
			defaultHierarchy: LocalDateTable_18de9502-ef69-4b5b-bdc9-8ece9bf92c36.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Previous_Admitting_ward
		dataType: string
		lineageTag: 79804aaa-a4c6-474b-8582-f1c46999de60
		summarizeBy: none
		sourceColumn: Previous_Admitting_ward

		annotation SummarizationSetBy = Automatic

	column Readmission_Admitting_ward
		dataType: string
		lineageTag: 873655b3-4823-4211-8c0a-d319028577cb
		summarizeBy: none
		sourceColumn: Readmission_Admitting_ward

		annotation SummarizationSetBy = Automatic

	column WardSplit
		dataType: string
		lineageTag: 629936f7-ac0d-40f4-93a9-5277e5d57673
		summarizeBy: none
		sourceColumn: WardSplit

		annotation SummarizationSetBy = Automatic

	column Readmission_Year_Month_Desc
		dataType: string
		lineageTag: 82f9e731-9e60-43f6-8610-f89fd4550288
		summarizeBy: none
		sourceColumn: Readmission_Year_Month_Desc
		sortByColumn: Readmission_Year_Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Readmission_Year_Month
		dataType: string
		lineageTag: 489ebabf-2912-4e77-b783-5809a58acb2c
		summarizeBy: none
		sourceColumn: Readmission_Year_Month

		annotation SummarizationSetBy = Automatic

	column Frailty_Proxy
		dataType: string
		lineageTag: 44937cb5-19d1-4f08-bd61-96e6c4a9e98d
		summarizeBy: none
		sourceColumn: Frailty_Proxy

		annotation SummarizationSetBy = Automatic

	column Provider_Code
		dataType: string
		lineageTag: b759e617-5668-4492-9dbc-0ccba58aa05a
		summarizeBy: none
		sourceColumn: Provider_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Name
		dataType: string
		lineageTag: d9a4c4ac-050a-4840-b46a-037b85df8519
		summarizeBy: none
		sourceColumn: Provider_Name

		annotation SummarizationSetBy = Automatic

	column Readmission_Provider_Code
		dataType: string
		lineageTag: a6f5061f-feb7-448f-aa46-9a6de058d1ed
		summarizeBy: none
		sourceColumn: Readmission_Provider_Code

		annotation SummarizationSetBy = Automatic

	column Readmission_Provider_Name
		dataType: string
		lineageTag: 756a3306-1214-42dd-9af6-cccf33ab328b
		summarizeBy: none
		sourceColumn: Readmission_Provider_Name

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Readmission_Method
		dataType: string
		lineageTag: 44a56080-3a0b-4b7e-8a58-93f993ad4621
		summarizeBy: none
		sourceColumn: Readmission_Method

		annotation SummarizationSetBy = Automatic

	partition Readmissions-6e48a446-bea4-46e7-8ed6-451c76a9f2a5 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "powerbi_reporting"),
				    dbo_Readmissions = Source{[Schema="dbo",Item="Readmissions"]}[Data],
				    #"Datetime fields to Date" = Table.TransformColumnTypes(dbo_Readmissions,{{"Previous_Start_Date", type date}, {"Previous_End_Date", type date}, {"Readmission_Start_Date", type date}, {"Readmission_End_Date", type date}, {"Re-admitted_within_7_Days_Flag", type text}}),
				    #"7DayFlag 0 to No" = Table.ReplaceValue(#"Datetime fields to Date","0","No",Replacer.ReplaceText,{"Re-admitted_within_7_Days_Flag"}),
				    #"7DayFlag 1 to Yes" = Table.ReplaceValue(#"7DayFlag 0 to No","1","Yes",Replacer.ReplaceText,{"Re-admitted_within_7_Days_Flag"})
				in
				    #"7DayFlag 1 to Yes"

	annotation PBI_ResultType = Table

