table 'Activity Type Ref'
	lineageTag: e1c5a80b-569a-4d22-b6b6-e7e4b9e91a07

	measure 'Selected Cohort Activity Referrals (Yearly or Monthly Population)' = ```
			
			
			VAR Referral_Monthly_AS_Rate = [Local Monthly Age Standardised Rate per 1000 (Referrals)]
			VAR Referral_Yearly_AS_Rate = [Local Yearly Age Standardised Rate per 1000 (Referrals)]
			VAR Referral_Monthly_Crude_Rate = [Crude Monthly Local Rate per 1000 (Referrals)]
			VAR Referral_Yearly_Crude_Rate = [Crude Yearly Local Rate per 1000 (Referrals)]
			VAR Referral_Actual_Activity = [Number of Referrals]
			
			VAR Treatment_Monthly_AS_Rate = [Local Monthly Age Standardised Rate per 1000 (Treatments)]
			VAR Treatment_Yearly_AS_Rate = [Local Yearly Age Standardised Rate per 1000 (Treatments)]
			VAR Treatment_Monthly_Crude_Rate = [Crude Monthly Local Rate per 1000 (Treatments)]
			VAR Treatment_Yearly_Crude_Rate = [Crude Yearly Local Rate per 1000 (Treatments)]
			VAR Treatment_Actual_Activity = [Number of Treatments]
			
			VAR Deaths_Monthly_AS_Rate = [Local Monthly Age Standardised Rate per 1000 (Deaths)]
			VAR Deaths_Yearly_AS_Rate = [Local Yearly Age Standardised Rate per 1000 (Deaths)]
			VAR Deaths_Monthly_Crude_Rate = [Crude Monthly Local Rate per 1000 (Deaths)]
			VAR Deaths_Yearly_Crude_Rate = [Crude Yearly Local Rate per 1000 (Deaths)]
			VAR Deaths_Actual_Activity = [Local Events (Cancer Deaths)]
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Locality Slicer Activity Type])
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			
			VAR final = IFERROR(if(activity_type = "Actual Activity" && referral_or_treatment = "Referral"
			        ,Referral_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Referral"
			        ,Referral_Monthly_AS_Rate, 
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Referral"
			        ,Referral_Yearly_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Referral"
			        ,Referral_Monthly_Crude_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Referral"
			        ,Referral_Yearly_Crude_Rate,
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Treatment"
			        ,Treatment_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Treatment"
			        ,Treatment_Monthly_AS_Rate, 
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Treatment"
			        ,Treatment_Yearly_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Treatment"
			        ,Treatment_Monthly_Crude_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Treatment"
			        ,Treatment_Yearly_Crude_Rate,
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Deaths"
			        ,Deaths_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Deaths"
			        ,Deaths_Monthly_AS_Rate, 
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Deaths"
			        ,Deaths_Yearly_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Deaths"
			        ,Deaths_Monthly_Crude_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Deaths"
			        ,Deaths_Yearly_Crude_Rate
			       
			        ,0))))))))))))))),0)
			
			RETURN IF(final<0.000000001,0,final)
			```
		lineageTag: d25d785a-2a1d-4b2c-94f0-7dd16ab560ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ICB Activity Referrals (Yearly or Monthly Population)' = ```
			
			
			VAR Referral_Monthly_AS_Rate = [Reference monthly rate per 1000 (Referrals)]
			VAR Referral_Yearly_AS_Rate = [Reference yearly rate per 1000 (Referrals)]
			VAR Referral_Monthly_Crude_Rate = [Reference monthly rate per 1000 (Referrals)]
			VAR Referral_Yearly_Crude_Rate = [Reference yearly rate per 1000 (Referrals)]
			VAR Referral_Actual_Activity = [Reference Events (Referrals)]
			
			VAR Treatment_Monthly_AS_Rate = [Reference monthly rate per 1000 (Treatments)]
			VAR Treatment_Yearly_AS_Rate = [Reference yearly rate per 1000 (Treatments)]
			VAR Treatment_Monthly_Crude_Rate = [Reference monthly rate per 1000 (Treatments)]
			VAR Treatment_Yearly_Crude_Rate = [Reference yearly rate per 1000 (Treatments)]
			VAR Treatment_Actual_Activity = [Reference Events (Treatments)]
			
			VAR Deaths_Monthly_AS_Rate = [Reference monthly rate per 1000 (Deaths)]
			VAR Deaths_Yearly_AS_Rate = [Reference yearly rate per 1000 (Deaths)]
			VAR Deaths_Monthly_Crude_Rate = [Reference monthly rate per 1000 (Deaths)]
			VAR Deaths_Yearly_Crude_Rate = [Reference yearly rate per 1000 (Deaths)]
			VAR Deaths_Actual_Activity = [Reference Events (Cancer Deaths)]
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Locality Slicer Activity Type])
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			
			RETURN IFERROR(if(activity_type = "Actual Activity" && referral_or_treatment = "Referral"
			        ,Referral_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Referral"
			        ,Referral_Monthly_AS_Rate, 
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Referral"
			        ,Referral_Yearly_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Referral"
			        ,Referral_Monthly_Crude_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Referral"
			        ,Referral_Yearly_Crude_Rate,
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Treatment"
			        ,Treatment_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Treatment"
			        ,Treatment_Monthly_AS_Rate, 
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Treatment"
			        ,Treatment_Yearly_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Treatment"
			        ,Treatment_Monthly_Crude_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Treatment"
			        ,Treatment_Yearly_Crude_Rate,
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Deaths"
			        ,Deaths_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Deaths"
			        ,Deaths_Monthly_AS_Rate, 
			
			        if(activity_type = "Age Standardised Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Deaths"
			        ,Deaths_Yearly_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Monthly" && referral_or_treatment = "Deaths"
			        ,Deaths_Monthly_Crude_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && time_frame = "Yearly" && referral_or_treatment = "Deaths"
			        ,Deaths_Yearly_Crude_Rate
			       
			        ,BLANK()))))))))))))))),BLANK())
			```
		lineageTag: 3a9986d9-b9a7-4ae1-9f88-989e4d506228

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Cohort Activity (Current Population)' = ```
			
			
			VAR Referral_AS_Rate = [Local Age Standardised Rate per 1000 (Referrals)]
			VAR Referral_Crude_Rate = [Crude Local Rate per 1000 (Referrals)]
			VAR Referral_Actual_Activity = [Number of Referrals]
			
			VAR Treatment_AS_Rate = CALCULATE([Local Age Standardised Rate per 1000 (Treatments)], USERELATIONSHIP('Referrals & Treatments'[Diagnosed Cancer Type (Unknowns Removed)],'Cancer Type Ref'[Cancer Type (Fixed)]))
			VAR Treatment_Crude_Rate = CALCULATE([Crude Local Rate per 1000 (Treatments)], USERELATIONSHIP('Referrals & Treatments'[Diagnosed Cancer Type (Unknowns Removed)],'Cancer Type Ref'[Cancer Type (Fixed)]))
			VAR Treatment_Actual_Activity = CALCULATE([Number of Treatments], USERELATIONSHIP('Referrals & Treatments'[Diagnosed Cancer Type (Unknowns Removed)],'Cancer Type Ref'[Cancer Type (Fixed)]))
			
			VAR Deaths_AS_Rate = [Local Age Standardised Rate per 1000 (Cancer Deaths)]
			VAR Deaths_Crude_Rate = [Crude Local Rate per 1000 (Cancer Deaths)]
			VAR Deaths_Actual_Activity = SUM('Cancer Deaths'[counter])
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			
			
			RETURN IFERROR(if(activity_type = "Actual Activity" && referral_or_treatment = "Referral"
			        ,Referral_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Referral"
			        ,Referral_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Referral"
			        ,Referral_Crude_Rate, 
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Treatment"
			        ,Treatment_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Treatment"
			        ,Treatment_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Treatment"
			        ,Treatment_Crude_Rate, 
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Deaths"
			        ,Deaths_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Deaths"
			        ,Deaths_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Deaths"
			        ,Deaths_Crude_Rate
			
			
			        ,BLANK()))))))))),BLANK())
			```
		lineageTag: 52d788da-bd13-4ecf-a610-ced60c90342a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Time Series Graph Title with Legend' = ```
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			VAR legend_selected = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Demographics Legend Parameter', 'Demographics Legend Parameter'[Legend Parameter], 'Demographics Legend Parameter'[Legend Parameter Fields]),
			        'Demographics Legend Parameter'[Legend Parameter])
			
			VAR metric = IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Referral", "Cancer Referrals - ", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Treatment", "Cancer Treatments - ",BLANK()))
			
			RETURN CONCATENATE(metric, CONCATENATE(activity_type, CONCATENATE(" by ", CONCATENATE(legend_selected, CONCATENATE(" - ", time_frame)))))
			```
		lineageTag: 69c4025a-10c0-4b0b-a96e-fda6fa0127de

	measure 'Bar Chart Graph Title' = ```
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			VAR legend_selected = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Demographics Legend Parameter', 'Demographics Legend Parameter'[Legend Parameter], 'Demographics Legend Parameter'[Legend Parameter Fields]),
			        'Demographics Legend Parameter'[Legend Parameter])
			
			VAR metric = IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Referral", "Cancer Referrals - ", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Treatment", "Cancer Treatments - ",IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Deaths", "Cancer Deaths - ", BLANK())))
			
			RETURN CONCATENATE(metric, CONCATENATE(activity_type, CONCATENATE(" by ", legend_selected)))
			```
		lineageTag: fa6dfefd-5d83-4a9e-8bea-f72951eda954

	measure 'Bar Chart by Cancer Graph Title' = ```
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			VAR legend_selected = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Demographics Legend Parameter', 'Demographics Legend Parameter'[Legend Parameter], 'Demographics Legend Parameter'[Legend Parameter Fields]),
			        'Demographics Legend Parameter'[Legend Parameter])
			
			VAR metric = IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Referral", "Cancer Referrals - ", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Treatment", "Cancer Treatments - ",IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Deaths", "Cancer Deaths - ", BLANK())))
			
			RETURN CONCATENATE(metric, CONCATENATE(activity_type, CONCATENATE(" by ", CONCATENATE(legend_selected, " & Cancer Type"))))
			```
		lineageTag: b57b4c31-639d-479a-8426-94a67aa1e5a1

	measure 'Expected Events by Cancer Graph Title' = ```
			
			
			VAR legend_selected = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Demographics Legend Parameter', 'Demographics Legend Parameter'[Legend Parameter], 'Demographics Legend Parameter'[Legend Parameter Fields]),
			        'Demographics Legend Parameter'[Legend Parameter])
			
			VAR metric = IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Referral", " Cancer Referrals", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Treatment", " Cancer Treatments",BLANK()))
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			RETURN IF(referral_or_treatment = "Deaths",CONCATENATE("Number of Deaths compared to Expected Deaths ", CONCATENATE(" by ", CONCATENATE(legend_selected, " & Cancer Type"))),
			        IF(referral_or_treatment = BLANK(), BLANK(), CONCATENATE("Missing Expected ", CONCATENATE(metric, CONCATENATE(" by ", CONCATENATE(legend_selected, " & Cancer Type"))))))
			```
		lineageTag: 74fd0134-67cd-4a3f-9b73-569e91f2a485

	measure 'ICB Activity Referrals (Current Population)' = ```
			
			
			VAR Referral_AS_Rate = [Reference rate per 1000 (Referrals)]
			VAR Referral_Crude_Rate = [Reference rate per 1000 (Referrals)]
			VAR Referral_Actual_Activity = [Reference Events (Referrals)]
			
			VAR Treatment_AS_Rate = [Reference rate per 1000 (Treatments)]
			VAR Treatment_Crude_Rate = [Reference rate per 1000 (Treatments)]
			VAR Treatment_Actual_Activity = [Reference Events (Treatments)]
			
			VAR Deaths_AS_Rate = [Reference rate per 1000 (Cancer Deaths)]
			VAR Deaths_Crude_Rate = [Reference rate per 1000 (Cancer Deaths)]
			VAR Deaths_Actual_Activity = [Reference Events (Cancer Deaths)]
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			
			RETURN IFERROR(if(activity_type = "Actual Activity" && referral_or_treatment = "Referral"
			        ,Referral_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Referral"
			        ,Referral_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Referral"
			        ,Referral_Crude_Rate, 
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Treatment"
			        ,Treatment_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Treatment"
			        ,Treatment_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Treatment"
			        ,Treatment_Crude_Rate, 
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Deaths"
			        ,Deaths_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Deaths"
			        ,Deaths_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Deaths"
			        ,Deaths_Crude_Rate 
			
			
			        ,BLANK()))))))))),BLANK())
			```
		lineageTag: 1ff0f5ca-c5d9-441e-a187-845d971914cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scatterplot Referrals' = ```
			
			
			--Using current population for rate per 1000
			
			VAR Referral_AS_Rate = [Local Age Standardised Rate per 1000 (Referrals)]
			VAR Referral_Crude_Rate = [Crude Local Rate per 1000 (Referrals)]
			VAR Referral_Actual_Activity = [Number of Referrals]
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			RETURN IFERROR(if(activity_type = "Actual Activity" 
			        ,Referral_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000"
			        ,Referral_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" 
			        ,Referral_Crude_Rate 
			
			        ,BLANK()))),BLANK())
			```
		lineageTag: e5517cd1-5819-4fd8-9a7f-1b01ef1b6708

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scatterplot Treatments' = ```
			
			
			VAR Treatments_AS_Rate = [Local Age Standardised Rate per 1000 (Treatments)]
			VAR Treatments_Crude_Rate = [Crude Local Rate per 1000 (Treatments)]
			VAR Treatments_Actual_Activity = [Number of Treatments]
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			RETURN IFERROR(if(activity_type = "Actual Activity" 
			        ,Treatments_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000"
			        ,Treatments_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" 
			        ,Treatments_Crude_Rate 
			
			        ,BLANK()))),BLANK())
			```
		lineageTag: ee34dfe8-ff40-4639-a187-6411a0aa0270

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scatterplot ICB Referrals' = ```
			
			
			VAR Referral_AS_Rate = [Reference rate per 1000 (Referrals)]
			VAR Referral_Crude_Rate = [Reference rate per 1000 (Referrals)]
			--VAR Referral_Actual_Activity = [Reference Events (Referrals)]
			VAR Referral_Actual_Activity = CALCULATE(AVERAGEX(SUMMARIZE('GP Reference', 'GP Reference'[ReportingOrganisationName], "toAverage", [local Events (Referrals)]), [local Events (Referrals)]),ALL('GP Reference'))
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			RETURN IFERROR(if(activity_type = "Actual Activity" 
			        ,Referral_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" 
			        ,Referral_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" 
			        ,Referral_Crude_Rate
			
			        ,BLANK()))),BLANK())
			```
		lineageTag: 2bfe15a6-3c2c-4a3a-b1a6-92c832532d4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scatterplot ICB Treatments' = ```
			
			
			VAR Treatment_AS_Rate = [Reference rate per 1000 (Treatments)]
			VAR Treatment_Crude_Rate = [Reference rate per 1000 (Treatments)]
			VAR Treatment_Actual_Activity = CALCULATE(AVERAGEX(SUMMARIZE('GP Reference', 'GP Reference'[ReportingOrganisationName], "toAverage", [Local Events (Treatments)]), [Local Events (Treatments)]),ALL('GP Reference'))
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			
			RETURN IFERROR(if(activity_type = "Actual Activity"
			        ,Treatment_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000"
			        ,Treatment_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" 
			        ,Treatment_Crude_Rate
			
			        ,BLANK()))),BLANK())
			```
		lineageTag: 8a4a95ea-988e-4881-8d2f-354cf7af6984

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scatterplot Graph Title' =
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			
			RETURN CONCATENATE(activity_type, " for Cancer Referrals & Treatments")
		lineageTag: 10b69126-df41-4f5a-aeba-cea240930cd3

	measure 'test average' = AVERAGEX(SUMMARIZE('GP Reference', 'GP Reference'[ReportingOrganisationName], "toAverage", [local Events (Referrals)]), [local Events (Referrals)])
		lineageTag: 4c5ff18f-a511-42ee-a521-e3bf7ddfd20a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expected Events Graph' =
			
			
			VAR Referrals = [Inverted Difference in Expected Events (Referrals)]
			VAR Treatments = [Inverted Difference in Expected Events (Treatments)]
			VAR Deaths = [Difference in Expected Events (Cancer Deaths)]
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			
			RETURN IFERROR(if(referral_or_treatment = "Referral"
			        ,Referrals,
			
			        if(referral_or_treatment = "Treatment"
			        ,Treatments,
			
			        if(referral_or_treatment = "Deaths"
			        ,Deaths
			
			        ,BLANK()))),BLANK())
		lineageTag: da37986e-d856-4b7b-b891-adc259a9eb37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Time Series Graph Title' = ```
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			VAR legend_selected = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Demographics Legend Parameter', 'Demographics Legend Parameter'[Legend Parameter], 'Demographics Legend Parameter'[Legend Parameter Fields]),
			        'Demographics Legend Parameter'[Legend Parameter])
			
			VAR metric = IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Referral", "Cancer Referrals - ", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Treatment", "Cancer Treatments - ", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Deaths", "Cancer Deaths - ",BLANK())))
			
			RETURN CONCATENATE(metric, CONCATENATE(activity_type, CONCATENATE(" - ", time_frame)))
			```
		lineageTag: 13bd3990-9bad-4604-93a7-cf4e1b3578d3

	measure 'Expected Events Graph Title' = ```
			
			
			VAR legend_selected = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Demographics Legend Parameter', 'Demographics Legend Parameter'[Legend Parameter], 'Demographics Legend Parameter'[Legend Parameter Fields]),
			        'Demographics Legend Parameter'[Legend Parameter])
			
			VAR metric = IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Referral", " Cancer Referrals", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Treatment", " Cancer Treatments",BLANK()))
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			RETURN IF(referral_or_treatment = "Deaths",CONCATENATE("Number of Deaths compared to Expected Deaths ", CONCATENATE(" by ",legend_selected)),
			        IF(referral_or_treatment = BLANK(), BLANK(), CONCATENATE("Missing Expected ", CONCATENATE(metric, CONCATENATE(" by ",legend_selected)))))
			```
		lineageTag: b93776e8-6af7-4f9a-a8d0-fac9346cdcf7

	measure 'Time Series Graph Title by Cancer Type' = ```
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			
			VAR metric = IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Referral", "Cancer Referrals - ", IF(SELECTEDVALUE('Referral or Treatment'[Referral or Treatment]) = "Treatment", "Cancer Treatments - ",BLANK()))
			
			RETURN CONCATENATE(metric, CONCATENATE(activity_type, CONCATENATE(" by Cancer Type", CONCATENATE(" - ", time_frame))))
			```
		lineageTag: bd41dbe5-d7c7-4551-8b77-879e34dc5809

	measure 'Demographics Scatterplot Graph Title' =
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR y_axis = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			VAR x_axis = SELECTEDVALUE('Scatterplot X-Axis'[Scatterplot_X-Axis])
			
			RETURN CONCATENATE(activity_type, CONCATENATE(" for ", CONCATENATE(y_axis, CONCATENATE("s by ",(x_axis)))))
		lineageTag: 702cc347-2151-4ce1-99eb-f9fc2a7499a7

	measure 'Deaths without Treatment - Selected Cohort Activity Referrals (Current Population)' = ```
			
			
			VAR DwT_AS_Rate = [Local Age Standardised Rate per 1000 (DwT)]
			VAR DwT_Crude_Rate = [Crude Local Rate per 1000 (DwT)]
			VAR DwT_Actual_Activity = [Cancer deaths with no treatments]
			
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			
			RETURN IFERROR(if(activity_type = "Actual Activity" 
			        ,DwT_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000"
			        ,DwT_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" 
			        ,DwT_Crude_Rate 
			
			        ,BLANK()))),BLANK())
			```
		lineageTag: d7002a21-c50a-4440-9957-ce13049c1cc3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cancer Deaths - Selected Cohort Activity Referrals (Current Population)' = ```
			
			
			VAR DwT_AS_Rate = [Local Age Standardised Rate per 1000 (Cancer Deaths)]
			VAR DwT_Crude_Rate = [Crude Local Rate per 1000 (Cancer Deaths)]
			VAR DwT_Actual_Activity = SUM('Cancer Deaths'[counter])
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			RETURN IFERROR(if(activity_type = "Actual Activity" 
			        ,DwT_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000"
			        ,DwT_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" 
			        ,DwT_Crude_Rate 
			
			        ,BLANK()))),BLANK())
			```
		lineageTag: fc32154b-f383-42a0-8982-e64c8ee56a35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Berkeley Vale Activity (Current Population)' = ```
			
			
			VAR Referral_AS_Rate = CALCULATE([Reference rate per 1000 (Referrals)], 'GP Reference'[PrimaryCareNetwork_2] = "Berkeley Vale")
			VAR Referral_Crude_Rate = [Reference rate per 1000 (Referrals)]
			VAR Referral_Actual_Activity = [Reference Events (Referrals)]
			
			VAR Treatment_AS_Rate = [Reference rate per 1000 (Treatments)]
			VAR Treatment_Crude_Rate = [Reference rate per 1000 (Treatments)]
			VAR Treatment_Actual_Activity = [Reference Events (Treatments)]
			
			VAR Deaths_AS_Rate = [Reference rate per 1000 (Cancer Deaths)]
			VAR Deaths_Crude_Rate = [Reference rate per 1000 (Cancer Deaths)]
			VAR Deaths_Actual_Activity = [Reference Events (Cancer Deaths)]
			
			VAR activity_type = SELECTEDVALUE('Activity Type Ref'[Demographics Slicer Activity Type])
			
			VAR referral_or_treatment = SELECTEDVALUE('Referral or Treatment'[Referral or Treatment])
			
			VAR time_frame = 
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Locality Time X-Axis', 'Locality Time X-Axis'[Locality Time X-Axis], 'Locality Time X-Axis'[Time X-Axis Fields] ),
			        'Locality Time X-Axis'[Locality Time X-Axis])
			
			
			RETURN IFERROR(if(activity_type = "Actual Activity" && referral_or_treatment = "Referral"
			        ,Referral_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Referral"
			        ,Referral_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Referral"
			        ,Referral_Crude_Rate, 
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Treatment"
			        ,Treatment_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Treatment"
			        ,Treatment_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Treatment"
			        ,Treatment_Crude_Rate, 
			
			        if(activity_type = "Actual Activity" && referral_or_treatment = "Deaths"
			        ,Deaths_Actual_Activity,
			
			        if(activity_type = "Age Standardised Rate per 1000" && referral_or_treatment = "Deaths"
			        ,Deaths_AS_Rate, 
			
			        if(activity_type = "Crude Rate per 1000" && referral_or_treatment = "Deaths"
			        ,Deaths_Crude_Rate 
			
			
			        ,BLANK()))))))))),BLANK())
			```
		lineageTag: f292cc6f-fead-4048-9b52-d7a90312846d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Locality Slicer Activity Type'
		dataType: string
		lineageTag: c79da200-9d4c-4727-a15c-047914a9b4a5
		summarizeBy: none
		sourceColumn: Locality Slicer Activity Type

		annotation SummarizationSetBy = Automatic

	column 'Demographics Slicer Activity Type'
		dataType: string
		lineageTag: 829a0eaf-4b1d-426c-859e-3da0a86d5709
		summarizeBy: none
		sourceColumn: Demographics Slicer Activity Type

		annotation SummarizationSetBy = Automatic

	partition 'Activity Type Ref' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WckwuKU3MUQBSmWWZJZVKsTpAsfRUheCSxLyUxKKUzOLUFIWgxJJUhYLUIgVDAwMDsBLnotKUVHTxWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Activity Type" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Activity Type", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Activity Type", "Locality Slicer Activity Type"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "Locality Slicer Activity Type", "Locality Slicer Activity Type - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Locality Slicer Activity Type - Copy", "Demographics Slicer Activity Type"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

