table MPI
	lineageTag: cd402e79-bf5a-4ae7-a800-fc4e076a5f92

	column locality
		dataType: string
		lineageTag: e5a88576-2e9c-4bdf-afd5-1daa78379815
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column MH_flag
		dataType: int64
		formatString: 0
		lineageTag: 110e6aaf-f312-47fc-b964-07f21e727661
		summarizeBy: none
		sourceColumn: MH_flag

		annotation SummarizationSetBy = Automatic

	column LD_flag
		dataType: int64
		formatString: 0
		lineageTag: d6a7d255-d0f5-4a85-b1c8-44ec0615fcc8
		summarizeBy: none
		sourceColumn: LD_flag

		annotation SummarizationSetBy = Automatic

	column Core20Flag
		dataType: int64
		formatString: 0
		lineageTag: 377aad5f-0f9e-4e40-97c6-bc61598ad4b6
		summarizeBy: none
		sourceColumn: Core20Flag

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: 63e829ef-b583-44db-9dfd-277a013245ab
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column 5YR_Age_Band
		dataType: string
		lineageTag: 20004439-9b1f-43f5-a014-553359118497
		summarizeBy: none
		sourceColumn: 5YR_Age_Band

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: e90d0fec-ddaf-4ccc-8b76-77a9ed0a0d7a
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: 72f91bc2-15fc-420f-82ee-8a6cf1efc3c6
		summarizeBy: none
		sourceColumn: PracticeCode

		annotation SummarizationSetBy = Automatic

	column PseudoNHSNumber
		dataType: string
		lineageTag: 9f69ae1b-5719-48d6-b493-d580ed10e366
		summarizeBy: none
		sourceColumn: PseudoNHSNumber

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 46b32d5f-0a89-4002-a95d-2a7860a8b48f
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	partition MPI = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select case when locality ilike '%cotswold%' then 'Cotswolds' else locality end as ""locality"", case when mentalillness is null then 0 else mentalillness end as ""MH_flag"", case when learningdisability is null then 0 else learningdisability end as ""LD_flag"", case when core20flag is null then 0 else core20flag end as ""Core20Flag"", case when derivedethnicitygroup is null then 'Unknown' when derivedethnicitygroup ilike 'Not known' then 'Unknown' else derivedethnicitygroup end as ""Ethnic Origin Grouped"", case when ageband5yr = '0-4' then '00-04' when ageband5yr = '5-9' then '05-09' else ageband5yr end as ""5YR_Age_Band"", pseudonhsnumber as ""PseudoNHSNumber"", 1 as ""counter"", practicecode as ""PracticeCode"", primarycarenetwork as ""PrimaryCareNetwork"" from data_mart_powerbi_pls.tbl02_summary", null, [EnableFolding=true]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"85-89","85+",Replacer.ReplaceText,{"5YR_Age_Band"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","90+","85+",Replacer.ReplaceText,{"5YR_Age_Band"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

