table e_referrals
	lineageTag: 2dc1c5d0-ddf6-4e62-9a9c-d03316fd0f8c

	measure total_referrals = CALCULATE(COUNT('e_referrals'[UBRN]))
		formatString: 0
		lineageTag: 437767d2-a38c-49ff-b922-8b197f6e7bd0

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure total_rejections = CALCULATE(COUNT('e_referrals'[UBRN]),FILTER('e_referrals','e_referrals'[Rejection_Flag]=1))
		formatString: 0
		lineageTag: 8a962411-fa86-43e1-b938-df705c930899

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure rejection_rate = [total_rejections]/[total_referrals]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 21c9b064-38af-467a-8e02-8e301a3d49c0

		annotation Format = <Format Format="Percentage" Accuracy="2" />

	column type
		dataType: string
		lineageTag: 6791db2e-d99a-4b53-a178-f7fae212131b
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = type

		annotation PBI_WasHiddenAtRefresh = False

	column ubrn
		dataType: string
		lineageTag: 754bb86e-3096-462b-87f1-66a066cc0828
		summarizeBy: none
		sourceColumn: ubrn

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = ubrn

		annotation PBI_WasHiddenAtRefresh = False

	column practice_code
		dataType: string
		lineageTag: 5307f8e2-2f6d-4176-9195-432ba9939f64
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = practice_code

		annotation PBI_WasHiddenAtRefresh = False

	column practice_name
		dataType: string
		lineageTag: 0375246b-55eb-4b1a-8045-ed9d2c880385
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = practice_name

		annotation PBI_WasHiddenAtRefresh = False

	column primary_care_network
		dataType: string
		lineageTag: a370bd8b-8b80-4ee4-a028-4e3cc29b7730
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = primary_care_network

		annotation PBI_WasHiddenAtRefresh = False

	column locality
		dataType: string
		lineageTag: 973cd9a7-26ef-4df3-9da9-7c774759836a
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = locality

		annotation PBI_WasHiddenAtRefresh = False

	column patient_partial_postcode
		dataType: string
		lineageTag: 58856bfd-ba24-4a0c-ae23-bbe2875960c9
		summarizeBy: none
		sourceColumn: patient_partial_postcode

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = patient_partial_postcode

		annotation PBI_WasHiddenAtRefresh = False

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 12ec2528-17b2-4ae5-8487-a879bc2e6551
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = date

		annotation PBI_WasHiddenAtRefresh = False

	column month_name
		dataType: string
		lineageTag: c9517a60-1be0-43d3-a867-4091b7068c36
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = month_name

		annotation PBI_WasHiddenAtRefresh = False

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 57938b57-a341-4b9a-b02b-d8413a8bc3c1
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = financial_month

		annotation PBI_WasHiddenAtRefresh = False

	column financial_year
		dataType: string
		lineageTag: 1ddc4c03-a03a-403c-85c9-6f95af324c71
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = financial_year

		annotation PBI_WasHiddenAtRefresh = False

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 56d2c725-10ce-4519-8024-316d52eb3dab
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = year_month

		annotation PBI_WasHiddenAtRefresh = False

	column service_id
		dataType: string
		lineageTag: a1dbe3f7-5e86-4e54-a0c3-bb20ffbc7e51
		summarizeBy: none
		sourceColumn: service_id

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = service_id

		annotation PBI_WasHiddenAtRefresh = False

	column service_name
		dataType: string
		lineageTag: c8078800-773d-427a-a34b-867ebd69cb32
		summarizeBy: none
		sourceColumn: service_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = service_name

		annotation PBI_WasHiddenAtRefresh = False

	column triage_service_group
		dataType: string
		lineageTag: 81128706-05fd-440a-bef2-dab551296a30
		summarizeBy: none
		sourceColumn: triage_service_group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = triage_service_group

		annotation PBI_WasHiddenAtRefresh = False

	column main_specialty_code
		dataType: int64
		formatString: 0
		lineageTag: c8c38081-e7c8-40ec-8a9a-ee2f0916d908
		summarizeBy: sum
		sourceColumn: main_specialty_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = main_specialty_code

		annotation PBI_WasHiddenAtRefresh = False

	column main_specialty_description
		dataType: string
		lineageTag: f69e02c2-c2e8-4478-8e73-33a44f18e124
		summarizeBy: none
		sourceColumn: main_specialty_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = main_specialty_description

		annotation PBI_WasHiddenAtRefresh = False

	column treatment_function_code
		dataType: string
		lineageTag: 7d7c6030-36ec-4aef-bb5e-e24af25cc36b
		summarizeBy: none
		sourceColumn: treatment_function_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = treatment_function_code

		annotation PBI_WasHiddenAtRefresh = False

	column treatment_function_description
		dataType: string
		lineageTag: 6e5cbc95-c92d-4804-a1ca-46ee673ce40f
		summarizeBy: none
		sourceColumn: treatment_function_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = treatment_function_description

		annotation PBI_WasHiddenAtRefresh = False

	column clinic_type
		dataType: string
		lineageTag: 3a4b88a4-f053-4e58-8e4f-dd2e3a546d6c
		summarizeBy: none
		sourceColumn: clinic_type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = clinic_type

		annotation PBI_WasHiddenAtRefresh = False

	column priority_code
		dataType: string
		lineageTag: 7f29146e-5fa6-40b4-91de-50465187aa2e
		summarizeBy: none
		sourceColumn: priority_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = priority_code

		annotation PBI_WasHiddenAtRefresh = False

	column priority_description
		dataType: string
		lineageTag: 6aef0969-a3b8-4623-8b55-e7bb4cb00e5c
		summarizeBy: none
		sourceColumn: priority_description

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = priority_description

		annotation PBI_WasHiddenAtRefresh = False

	column provider_code
		dataType: string
		lineageTag: 2e682cb4-8954-4364-b06e-c3c6e8e647f5
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_code

		annotation PBI_WasHiddenAtRefresh = False

	column location_code
		dataType: string
		lineageTag: a733c3ae-f784-4453-8135-6d7c8b4f4ffb
		summarizeBy: none
		sourceColumn: location_code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = location_code

		annotation PBI_WasHiddenAtRefresh = False

	column location_name
		dataType: string
		lineageTag: a16dc353-6152-492d-b971-c530190a0d82
		summarizeBy: none
		sourceColumn: location_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = location_name

		annotation PBI_WasHiddenAtRefresh = False

	column provider_name
		dataType: string
		lineageTag: ab9c5def-411c-4d1d-88d7-b20d53f5f79a
		summarizeBy: none
		sourceColumn: provider_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_name

		annotation PBI_WasHiddenAtRefresh = False

	column provider_group
		dataType: string
		lineageTag: d69c9058-2f10-424d-a75c-b2bebf3a7d09
		summarizeBy: none
		sourceColumn: provider_group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = provider_group

		annotation PBI_WasHiddenAtRefresh = False

	column referral_flag
		dataType: int64
		formatString: 0
		lineageTag: d508360e-5735-451a-ae65-5d9fc9583800
		summarizeBy: sum
		sourceColumn: referral_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = referral_flag

		annotation PBI_WasHiddenAtRefresh = False

	column rejection_flag
		dataType: int64
		formatString: 0
		lineageTag: 4914239a-207d-4501-9b70-6037900d2075
		summarizeBy: sum
		sourceColumn: rejection_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = rejection_flag

		annotation PBI_WasHiddenAtRefresh = False

	column paediatric_flag
		dataType: int64
		formatString: 0
		lineageTag: dff2b885-a840-4988-a867-00a42745d45f
		summarizeBy: sum
		sourceColumn: paediatric_flag

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = paediatric_flag

		annotation PBI_WasHiddenAtRefresh = False

	column consultant_led_indicator
		dataType: string
		lineageTag: 0c6ba098-9f10-4970-88d1-15f45ddc3eb2
		summarizeBy: none
		sourceColumn: consultant_led_indicator

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = consultant_led_indicator

		annotation PBI_WasHiddenAtRefresh = False

	partition e_referrals-0b655155-e8f3-4e12-9a33-9d1c871e3c10 = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "CCG_Sandbox", [Query="SELECT * FROM [CCG_Sandbox].[dbo].[EReferrals]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"rejection_flag", Int64.Type}, {"paediatric_flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

