table waiting_list
	lineageTag: 5dd9ec31-0fba-4923-a4dc-edde0400f4d7

	column Count
		dataType: int64
		formatString: 0
		lineageTag: f7ce2de6-92d2-403b-b8fd-03c3c1ddf43b
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Count

		annotation PBI_WasHiddenAtRefresh = False

	column Date_And_Time_Data_Set_Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d579ff3-374f-40ab-ad30-a7d97ff96e6c
		summarizeBy: none
		sourceColumn: Date_And_Time_Data_Set_Created

		variation Variation
			isDefault
			relationship: b080a23b-9ca1-4234-96bb-75515514367a
			defaultHierarchy: LocalDateTable_db052d43-12cc-4e8e-8475-e9dc033fa175.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = Date_And_Time_Data_Set_Created

		annotation PBI_WasHiddenAtRefresh = False

	column Week_Ending_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: abe82173-5792-4b0d-a86e-38a1665c05c7
		summarizeBy: none
		sourceColumn: Week_Ending_Date

		variation Variation
			isDefault
			relationship: d9330d11-3247-4199-b284-903cf69fc21d
			defaultHierarchy: LocalDateTable_476aa518-724d-4f58-aa6c-0175e648b418.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = Week_Ending_Date

		annotation PBI_WasHiddenAtRefresh = False

	column Days
		dataType: int64
		formatString: 0
		lineageTag: 8b9abd79-af38-4ca4-8b4a-b9df111ec050
		summarizeBy: sum
		sourceColumn: Days

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Days

		annotation PBI_WasHiddenAtRefresh = False

	column Weeks
		dataType: double
		lineageTag: 99caeae3-ded9-4e30-8fe6-ad1c0adfd98d
		summarizeBy: sum
		sourceColumn: Weeks

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Weeks

		annotation PBI_WasHiddenAtRefresh = False

	column Weeks_Waiting_Banding
		dataType: string
		lineageTag: 0fcaed0a-128b-4da0-8ad4-88977e6cbfbb
		summarizeBy: none
		sourceColumn: Weeks_Waiting_Banding

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Weeks_Waiting_Banding

		annotation PBI_WasHiddenAtRefresh = False

	column Pseudo_NHS_Number
		dataType: string
		lineageTag: a6bf0ae8-9569-4733-8334-dd142b31bfba
		summarizeBy: none
		sourceColumn: Pseudo_NHS_Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Pseudo_NHS_Number

		annotation PBI_WasHiddenAtRefresh = False

	column Referral_Request_Received_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: e3a7c248-0099-4e73-ae65-0e4b6026d316
		summarizeBy: none
		sourceColumn: Referral_Request_Received_Date

		variation Variation
			isDefault
			relationship: 9121d67d-cb2d-4a9f-b16a-6abb2ba518a4
			defaultHierarchy: LocalDateTable_8e3864c2-2f8f-410c-a4d5-07f438cdd748.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = Referral_Request_Received_Date

		annotation PBI_WasHiddenAtRefresh = False

	column Organisation_Identifier_Code_Of_Provider
		dataType: string
		lineageTag: 1116296c-1778-46c9-ab19-312f2feaec61
		summarizeBy: none
		sourceColumn: Organisation_Identifier_Code_Of_Provider

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Organisation_Identifier_Code_Of_Provider

		annotation PBI_WasHiddenAtRefresh = False

	column Provider
		dataType: string
		lineageTag: d073b5c6-1a19-4813-872b-d465a689b47f
		summarizeBy: none
		sourceColumn: Provider

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Provider

		annotation PBI_WasHiddenAtRefresh = False

	column Organisation_Site_Identifier_Of_Treatment
		dataType: string
		lineageTag: 78c1ac79-c2d8-4126-a918-e23983f7df0c
		summarizeBy: none
		sourceColumn: Organisation_Site_Identifier_Of_Treatment

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Organisation_Site_Identifier_Of_Treatment

		annotation PBI_WasHiddenAtRefresh = False

	column Activity_Treatment_Function_Code
		dataType: string
		lineageTag: dac9eab1-a191-444f-be7c-ff2b74818786
		summarizeBy: none
		sourceColumn: Activity_Treatment_Function_Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Activity_Treatment_Function_Code

		annotation PBI_WasHiddenAtRefresh = False

	column 'Treatment Function'
		dataType: string
		lineageTag: c509c7bb-a276-4572-b8e4-1ec40462cd25
		summarizeBy: none
		sourceColumn: Treatment Function

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Treatment Function

		annotation PBI_WasHiddenAtRefresh = False

	column Referral_To_Treatment_Period_Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 76f8e8c7-eab7-460f-94a0-7eabb3469273
		summarizeBy: none
		sourceColumn: Referral_To_Treatment_Period_Start_Date

		variation Variation
			isDefault
			relationship: 485c5fd1-abfe-4847-b2a5-b887c2e00b60
			defaultHierarchy: LocalDateTable_86b1e661-9031-4865-bb74-f12da9ee710a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = Referral_To_Treatment_Period_Start_Date

		annotation PBI_WasHiddenAtRefresh = False

	column Organisation_Identifier_Code_Of_Commissioner
		dataType: string
		lineageTag: 7a8ba625-fe03-403b-bba6-bb51e3fe6a5e
		summarizeBy: none
		sourceColumn: Organisation_Identifier_Code_Of_Commissioner

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Organisation_Identifier_Code_Of_Commissioner

		annotation PBI_WasHiddenAtRefresh = False

	column Priority_Type_Code
		dataType: string
		lineageTag: 673177fd-748d-4851-90d6-42febea02612
		summarizeBy: none
		sourceColumn: Priority_Type_Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Priority_Type_Code

		annotation PBI_WasHiddenAtRefresh = False

	column Referral_To_Treatment_Period_End_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4fb9809a-f8f3-4235-b114-ad181d8112d7
		summarizeBy: none
		sourceColumn: Referral_To_Treatment_Period_End_Date

		variation Variation
			isDefault
			relationship: 118d8ae4-4206-474c-89e0-b1634e193dba
			defaultHierarchy: LocalDateTable_84512719-850d-4a84-9f1f-54ef4548bc3c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = Referral_To_Treatment_Period_End_Date

		annotation PBI_WasHiddenAtRefresh = False

	column Procedure_Priority_Code
		dataType: string
		lineageTag: 716d8b77-d635-420f-81f8-44ff9f906613
		summarizeBy: none
		sourceColumn: Procedure_Priority_Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Procedure_Priority_Code

		annotation PBI_WasHiddenAtRefresh = False

	column Waiting_List_Type
		dataType: string
		lineageTag: 04229f03-df25-4f24-b972-1f766691f8f8
		summarizeBy: none
		sourceColumn: Waiting_List_Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Waiting_List_Type

		annotation PBI_WasHiddenAtRefresh = False

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 32219e91-e6c0-4d75-a2f8-56c50057ef96
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = rank

		annotation PBI_WasHiddenAtRefresh = False

	column Priority
		dataType: string
		lineageTag: 0d2a8f0e-18bc-41f3-af2a-abccc078cd94
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Priority

		annotation PBI_WasHiddenAtRefresh = False

	partition waiting_list-6a4072ac-4de2-4346-8ca6-c76a015b56e3 = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Data_Mart_COVID19", [Query="SET ANSI_NULLS ON#(lf)SET QUOTED_IDENTIFIER ON#(lf)set nocount on#(lf)set ansi_warnings off #(lf)#(lf)DECLARE @WEEKENDING DATETIME#(lf)SET @WEEKENDING = (SELECT DISTINCT MAX(#(lf)CASE WHEN DATENAME(DW,[week_ending_date]) = 'MONDAY' THEN DATEADD(DD,-1,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'TUESDAY' THEN DATEADD(DD,-2,[week_ending_date])  #(lf)WHEN DATENAME(DW,[week_ending_date]) = 'WEDNESDAY' THEN DATEADD(DD,-3,[week_ending_date]) #(lf)WHEN  DATENAME(DW,[week_ending_date]) = 'THURSDAY' THEN DATEADD(DD,-4,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'FRIDAY' THEN DATEADD(DD,-5,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'SATURDAY' THEN DATEADD(DD,-6,[week_ending_date])ELSE [week_ending_date] END)#(lf)#(lf)FROM [Data_Mart_COVID19].[dbo].[National_Wait_List_Open_Pathways] where week_ending_date <= GETDATE())#(lf)#(lf)---------------------------------------------------------------------------------------------------------------------#(lf)----------------------------------------- ADMITTED PTL SCRIPT --------------------------------------------------#(lf)--------------------------------------------------------------------------------------------------------------------#(lf)#(lf)IF OBJECT_ID('tempdb..#ranktemp1') IS NOT NULL DROP TABLE #ranktemp1; #(lf)IF OBJECT_ID('tempdb..#temp_admitted_PTL') IS NOT NULL DROP TABLE #temp_admitted_PTL; #(lf)IF OBJECT_ID('tempdb..#ranktemp') IS NOT NULL DROP TABLE #ranktemp; #(lf)IF OBJECT_ID('tempdb..#temp_non_admitted_PTL') IS NOT NULL DROP TABLE #temp_non_admitted_PTL; #(lf)#(lf)#(lf)SELECT #(lf)'1' AS count#(lf)#(tab),[Date_And_Time_Data_Set_Created]#(lf)#(tab),[Week_Ending_Date]#(lf)#(tab),datediff(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) AS 'Days'#(lf)#(tab),datediff(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) / 7.0 'Weeks'#(lf)#(tab),[Weeks_Waiting_Banding] = CASE #(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 0 AND 126#(lf)#(tab)#(tab)#(tab)THEN '0 < 18 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 127 AND 182#(lf)#(tab)#(tab)#(tab)THEN '18 < 26 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 183 AND 280#(lf)#(tab)#(tab)#(tab)THEN '26 < 40 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 281 AND 364#(lf)#(tab)#(tab)#(tab)THEN '40 <  52 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date],@WEEKENDING) BETWEEN 365 AND 546#(lf)#(tab)#(tab)#(tab)THEN '52 < 78 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 547 AND 728#(lf)#(tab)#(tab)#(tab)THEN '78 < 104 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) > 729#(lf)#(tab)#(tab)#(tab)THEN '104+ Weeks'#(lf)#(tab)#(tab)ELSE 'NULL'#(lf)#(tab)#(tab)END#(lf)#(tab),[Pseudo_NHS_Number]#(lf)#(tab),[Referral_Request_Received_Date]#(lf)#(tab),WL.[Organisation_Identifier_Code_Of_Provider]#(lf)#(tab),CASE #(lf)#(tab)#(tab)WHEN TR.[Name] IS NOT NULL#(lf)#(tab)#(tab)#(tab)THEN TR.[Name]#(lf)#(tab)#(tab)When WL.Organisation_Identifier_Code_Of_Provider = 'R0D' #(lf)#(tab)#(tab)    then 'UNIVERSITY HOSPITALS DORSET NHS FOUNDATION TRUST'#(lf)#(tab)#(tab)ELSE IP.[Organisationname]#(lf)#(tab)#(tab)END AS 'Provider'#(lf)#(tab),[Organisation_Site_Identifier_Of_Treatment]#(lf)#(tab),[Activity_Treatment_Function_Code]#(lf)#(tab),TF.[TreatmentFunctionDescription] as 'Treatment Function'#(lf)#(tab),[Referral_To_Treatment_Period_Start_Date]#(lf)#(tab),[Organisation_Identifier_Code_Of_Commissioner]#(lf)#(tab),[Priority_Type_Code]#(lf)#(tab),[Referral_To_Treatment_Period_End_Date]#(lf)#(tab),[Procedure_Priority_Code]#(lf)#(tab),[Waiting_List_Type] = case when [Waiting_List_Type] = 'IRTT' then 'Admitted PTL'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when  [Waiting_List_Type] = 'ORTT' then 'Non-Admitted PTL'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)else 'Other' End#(lf)#(lf)#(tab),[Priority] = case when [procedure_priority_code] = 'P2' then [procedure_priority_code]#(lf)#(tab)when [procedure_priority_code] = 'P3' then [procedure_priority_code]#(lf)#(tab)when [procedure_priority_code] = 'P4' then [procedure_priority_code]#(lf)#(tab)when [procedure_priority_code] = 'P1' then [procedure_priority_code]#(lf)#(tab)ELSE 'Other/Unknown' END#(lf)#(lf)#(tab)#(lf)into #ranktemp1#(lf)FROM [Data_Mart_COVID19].[dbo].[National_Wait_List_Open_Pathways] WL#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_TreatmentFunction] TF #(lf)ON WL.[Activity_Treatment_Function_Code] = TF.[TreatmentFunctionCode]#(lf)#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_OrganisationTrust] TR #(lf)ON TR.[OrganisationCode] = [Organisation_Identifier_Code_Of_Provider]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_IndependentProvider] IP #(lf)ON IP.[OrganisationCode] = Left([Organisation_Identifier_Code_Of_Provider], 3) #(lf)#(lf)#(lf)WHERE [Referral_To_Treatment_Period_End_Date] IS NULL#(lf)#(tab)AND [Referral_To_Treatment_Period_Start_Date] IS NOT NULL#(lf)#(tab) and #(lf)CASE WHEN DATENAME(DW,[week_ending_date]) = 'MONDAY' THEN DATEADD(DD,-1,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'TUESDAY' THEN DATEADD(DD,-2,[week_ending_date])  #(lf)WHEN DATENAME(DW,[week_ending_date]) = 'WEDNESDAY' THEN DATEADD(DD,-3,[week_ending_date]) #(lf)WHEN  DATENAME(DW,[week_ending_date]) = 'THURSDAY' THEN DATEADD(DD,-4,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'FRIDAY' THEN DATEADD(DD,-5,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'SATURDAY' THEN DATEADD(DD,-6,[week_ending_date])ELSE [week_ending_date] END = @WEEKENDING#(lf)and [Waiting_List_Type] = 'IRTT'#(lf)#(lf)and Referral_To_Treatment_Period_Start_Date <=@WEEKENDING#(lf)and [Derived_Registered_CCG] = '11M'#(lf)--and WL.Organisation_Identifier_Code_Of_Provider like 'NT4%' #(lf)#(lf)/*============================================================================#(lf)ranking query#(lf)============================================================================*/#(lf)#(lf)select#(lf)#(tab)[Count]#(lf)#(tab),[Date_And_Time_Data_Set_Created]#(lf)#(tab),[Week_Ending_Date]#(lf)#(tab),[Days]#(lf)#(tab),[Weeks]#(lf)#(tab),[Weeks_Waiting_Banding]#(lf)#(tab),[Pseudo_NHS_Number]#(lf)#(tab),[Referral_Request_Received_Date]#(lf)#(tab),[Organisation_Identifier_Code_Of_Provider]#(lf)#(tab),[Q1].[Provider]#(lf)#(tab),[Organisation_Site_Identifier_Of_Treatment]#(lf)#(tab),[Activity_Treatment_Function_Code]#(lf)#(tab),[Treatment Function]#(lf)#(tab),[Referral_To_Treatment_Period_Start_Date]#(lf)#(tab),[Organisation_Identifier_Code_Of_Commissioner]#(lf)#(tab),[Priority_Type_Code]#(lf)#(tab),[Referral_To_Treatment_Period_End_Date]#(lf)#(tab),[Procedure_Priority_Code]#(lf)#(tab),[Waiting_List_Type]#(lf)#(tab),[rank] = [RANK].[RANK]#(lf)#(tab),[Priority]#(lf)#(lf)#(tab)INTO #temp_admitted_PTL#(lf)#(lf)from #ranktemp1 [Q1]#(lf)#(lf)LEFT JOIN (#(lf)SELECT *,#(lf)RANK= RANK() OVER(ORDER BY [RANKCOUNT]DESC) FROM (#(lf)#(lf)SELECT DISTINCT [PROVIDER],#(lf)[RANKCOUNT]=COUNT(*)#(lf)FROM #RANKTEMP1#(lf)GROUP BY [PROVIDER] #(lf)) AS SUB ) AS [RANK]#(lf)ON [RANK].[Provider] = [Q1].[Provider]#(lf)#(lf)#(lf)---------------------------------------------------------------------------------------------------------------------#(lf)----------------------------------------- NON-ADMITTED PTL SCRIPT --------------------------------------------------#(lf)--------------------------------------------------------------------------------------------------------------------#(lf)#(lf)#(lf)#(lf)--IF OBJECT_ID('tempdb..#ranktemp') IS NOT NULL DROP TABLE #ranktemp; #(lf)--IF OBJECT_ID('tempdb..#temp_admitted_PTL') IS NOT NULL DROP TABLE temp_admitted_PTL; #(lf)#(lf)SELECT #(lf)'1' AS count#(lf)#(tab),[Date_And_Time_Data_Set_Created]#(lf)#(tab),[Week_Ending_Date]#(lf)#(tab),datediff(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) AS 'Days'#(lf)#(tab),datediff(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) / 7.0 'Weeks'#(lf)#(tab),[Weeks_Waiting_Banding] = CASE #(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 0 AND 126#(lf)#(tab)#(tab)#(tab)THEN '0 < 18 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 127 AND 182#(lf)#(tab)#(tab)#(tab)THEN '18 < 26 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 183 AND 280#(lf)#(tab)#(tab)#(tab)THEN '26 < 40 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 281 AND 364#(lf)#(tab)#(tab)#(tab)THEN '40 <  52 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date],@WEEKENDING) BETWEEN 365 AND 546#(lf)#(tab)#(tab)#(tab)THEN '52 < 78 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) BETWEEN 547 AND 728#(lf)#(tab)#(tab)#(tab)THEN '78 < 104 Weeks'#(lf)#(tab)#(tab)WHEN DATEDIFF(dd, [Referral_To_Treatment_Period_Start_Date], @WEEKENDING) > 729#(lf)#(tab)#(tab)#(tab)THEN '104+ Weeks'#(lf)#(tab)#(tab)ELSE 'NULL'#(lf)#(tab)#(tab)END#(lf)#(tab),[Pseudo_NHS_Number]#(lf)#(tab),[Referral_Request_Received_Date]#(lf)#(tab),WL.[Organisation_Identifier_Code_Of_Provider]#(lf)#(tab),CASE #(lf)#(tab)#(tab)WHEN TR.[Name] IS NOT NULL#(lf)#(tab)#(tab)#(tab)THEN TR.[Name]#(lf)#(tab)#(tab)When WL.Organisation_Identifier_Code_Of_Provider = 'R0D' #(lf)#(tab)#(tab)    then 'UNIVERSITY HOSPITALS DORSET NHS FOUNDATION TRUST'#(lf)#(tab)#(tab)ELSE IP.[Organisationname]#(lf)#(tab)#(tab)END AS 'Provider'#(lf)#(tab),[Organisation_Site_Identifier_Of_Treatment]#(lf)#(tab),[Activity_Treatment_Function_Code]#(lf)#(tab),TF.[TreatmentFunctionDescription] as 'Treatment Function'#(lf)#(tab),[Referral_To_Treatment_Period_Start_Date]#(lf)#(tab),[Organisation_Identifier_Code_Of_Commissioner]#(lf)#(tab),[Priority_Type_Code]#(lf)#(tab),[Referral_To_Treatment_Period_End_Date]#(lf)#(tab),[Procedure_Priority_Code]#(lf)#(tab),[Waiting_List_Type] = case when [Waiting_List_Type] = 'IRTT' then 'Admitted PTL'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when  [Waiting_List_Type] = 'ORTT' then 'Non-Admitted PTL'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)else 'Other' End#(lf)#(lf)#(tab),[Priority] = case when [procedure_priority_code] = 'P2' then [procedure_priority_code]#(lf)#(tab)when [procedure_priority_code] = 'P3' then [procedure_priority_code]#(lf)#(tab)when [procedure_priority_code] = 'P4' then [procedure_priority_code]#(lf)#(tab)when [procedure_priority_code] = 'P1' then [procedure_priority_code]#(lf)#(tab)ELSE 'Other/Unknown'END#(lf)#(lf)into #ranktemp#(lf)FROM [Data_Mart_COVID19].[dbo].[National_Wait_List_Open_Pathways] WL#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_TreatmentFunction] TF #(lf)ON WL.[Activity_Treatment_Function_Code] = TF.[TreatmentFunctionCode]#(lf)#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_OrganisationTrust] TR #(lf)ON TR.[OrganisationCode] = [Organisation_Identifier_Code_Of_Provider]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_IndependentProvider] IP #(lf)ON IP.[OrganisationCode] = Left([Organisation_Identifier_Code_Of_Provider], 3) #(lf)#(lf)#(lf)WHERE [Referral_To_Treatment_Period_End_Date] IS NULL#(lf)#(tab)AND [Referral_To_Treatment_Period_Start_Date] IS NOT NULL#(lf)#(tab) and #(lf)CASE WHEN DATENAME(DW,[week_ending_date]) = 'MONDAY' THEN DATEADD(DD,-1,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'TUESDAY' THEN DATEADD(DD,-2,[week_ending_date])  #(lf)WHEN DATENAME(DW,[week_ending_date]) = 'WEDNESDAY' THEN DATEADD(DD,-3,[week_ending_date]) #(lf)WHEN  DATENAME(DW,[week_ending_date]) = 'THURSDAY' THEN DATEADD(DD,-4,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'FRIDAY' THEN DATEADD(DD,-5,[week_ending_date])#(lf)WHEN DATENAME(DW,[week_ending_date]) = 'SATURDAY' THEN DATEADD(DD,-6,[week_ending_date])ELSE [week_ending_date] END = @WEEKENDING#(lf)and [Waiting_List_Type] = 'ORTT'#(lf)and [Derived_Registered_CCG] = '11M'#(lf)#(lf)and Referral_To_Treatment_Period_Start_Date <= @WEEKENDING#(lf)--and WL.Organisation_Identifier_Code_Of_Provider like 'NT4%' #(lf)#(lf)/*============================================================================#(lf)ranking query#(lf)============================================================================*/#(lf)#(lf)select#(lf)#(tab)[Count]#(lf)#(tab),[Date_And_Time_Data_Set_Created]#(lf)#(tab),[Week_Ending_Date]#(lf)#(tab),[Days]#(lf)#(tab),[Weeks]#(lf)#(tab),[Weeks_Waiting_Banding]#(lf)#(tab),[Pseudo_NHS_Number]#(lf)#(tab),[Referral_Request_Received_Date]#(lf)#(tab),[Organisation_Identifier_Code_Of_Provider]#(lf)#(tab),[Q].[Provider]#(lf)#(tab),[Organisation_Site_Identifier_Of_Treatment]#(lf)#(tab),[Activity_Treatment_Function_Code]#(lf)#(tab),[Treatment Function]#(lf)#(tab),[Referral_To_Treatment_Period_Start_Date]#(lf)#(tab),[Organisation_Identifier_Code_Of_Commissioner]#(lf)#(tab),[Priority_Type_Code]#(lf)#(tab),[Referral_To_Treatment_Period_End_Date]#(lf)#(tab),[Procedure_Priority_Code]#(lf)#(tab),[Waiting_List_Type]#(lf)#(tab),[rank] = [RANK].[RANK]#(lf)#(tab),[Priority]#(lf)#(tab)#(lf)#(tab)INTO #temp_non_admitted_PTL#(lf)#(lf)from #ranktemp [Q]#(lf)LEFT JOIN (#(lf)SELECT *,#(lf)RANK= RANK() OVER(ORDER BY [RANKCOUNT]DESC) FROM (#(lf)#(lf)SELECT DISTINCT [PROVIDER],#(lf)[RANKCOUNT]=COUNT(*)#(lf)FROM #RANKTEMP#(lf)GROUP BY [PROVIDER] #(lf)) AS SUB ) AS [RANK]#(lf)ON [RANK].[Provider] = [Q].[Provider]#(lf)#(lf)#(lf)SELECT * FROM #temp_admitted_PTL#(lf)#(lf)UNION ALL #(lf)#(lf)SELECT * FROM #temp_non_admitted_PTL#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

