table B_Reviews
	lineageTag: 6320fa86-0328-41fd-9838-8d9b0a9b8b3d

	column clientid
		dataType: int64
		formatString: 0
		lineageTag: 4f27a9e0-96dc-471f-a964-ece7c217bf5b
		summarizeBy: none
		sourceColumn: clientid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dom_res
		dataType: string
		lineageTag: 99b179bc-366a-436d-be0a-ee7df59e0c5f
		summarizeBy: none
		sourceColumn: dom_res

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fundername
		dataType: string
		lineageTag: aae6ad8c-90e6-4894-87ac-033f1ec59c90
		summarizeBy: none
		sourceColumn: fundername

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column provider
		dataType: string
		lineageTag: fdf64387-8e36-49ac-93c5-8fd63f8a6f92
		summarizeBy: none
		sourceColumn: provider

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column carestayid
		dataType: int64
		formatString: 0
		lineageTag: 18075b15-7cce-4257-9ddc-b23f900584fe
		summarizeBy: sum
		sourceColumn: carestayid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column costtype
		dataType: string
		lineageTag: 9e33c68c-91b2-4478-a9d9-912164aba8fb
		summarizeBy: none
		sourceColumn: costtype

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column practicecode
		dataType: string
		lineageTag: aa4eb729-761e-42b8-ac3e-2e1efc2b0fa4
		summarizeBy: none
		sourceColumn: practicecode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ccgname
		dataType: string
		lineageTag: c1e84d30-4bd3-4f04-8c68-695ea6e66a2a
		summarizeBy: none
		sourceColumn: ccgname

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column startdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f340328-11be-4b63-add2-64ad9652f219
		summarizeBy: none
		sourceColumn: startdate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column enddate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4876184c-f864-478e-ad44-58fcc1ba1056
		summarizeBy: none
		sourceColumn: enddate

		variation Variation
			isDefault
			relationship: 1b179e4e-be68-40e8-a3c2-eeedb4ec1b5c
			defaultHierarchy: LocalDateTable_cceaf79d-5d6e-458a-bbab-e5848484fd81.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column carecategory
		dataType: string
		lineageTag: f4ff857a-c670-4b7f-8850-a2b953f41cf7
		summarizeBy: none
		sourceColumn: carecategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column days
		dataType: int64
		formatString: 0
		lineageTag: 8188a767-cad0-4708-bb93-320c8d1ea642
		summarizeBy: sum
		sourceColumn: days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weeklycost
		dataType: double
		lineageTag: 190e674f-8028-49c9-ae9d-712eb094b406
		summarizeBy: sum
		sourceColumn: weeklycost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total
		dataType: double
		lineageTag: 011ec3b9-714f-4d60-958f-ac713d528031
		summarizeBy: sum
		sourceColumn: total

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fundersince
		dataType: dateTime
		formatString: Long Date
		lineageTag: c753d438-a281-4a96-b4bf-1e72fd3597a0
		summarizeBy: none
		sourceColumn: fundersince

		variation Variation
			isDefault
			relationship: 835a603c-9683-4b01-a106-35356b387234
			defaultHierarchy: LocalDateTable_8d72f370-3528-4bae-9b5a-d01e121edead.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column percentagesplit
		dataType: double
		lineageTag: b21b0705-1850-44c5-b249-15b7e80417ba
		summarizeBy: sum
		sourceColumn: percentagesplit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status
		dataType: string
		lineageTag: 4ab3129f-d554-4862-8af1-09805d5ed1a8
		summarizeBy: none
		sourceColumn: status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column statussince
		dataType: dateTime
		formatString: Long Date
		lineageTag: 56478ed1-456c-4392-895a-e11e39647526
		summarizeBy: none
		sourceColumn: statussince

		variation Variation
			isDefault
			relationship: 8d90bf99-20c3-432b-889e-6d9ee09ccde6
			defaultHierarchy: LocalDateTable_bb41d78a-1295-4ea1-aa0d-26ce4c075203.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fasttrack
		dataType: string
		lineageTag: 4b671225-e8c2-4a1f-8aa9-e59bb181a69a
		summarizeBy: none
		sourceColumn: fasttrack

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fasttrackactivationdate
		dataType: string
		lineageTag: 9b479d7f-cba3-498d-b3c8-76bd80ffb4fe
		summarizeBy: none
		sourceColumn: fasttrackactivationdate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column reviewtype
		dataType: string
		lineageTag: 04e49a53-e7d8-446e-8b15-b29143d3aead
		summarizeBy: none
		sourceColumn: reviewtype

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column schedulereviewdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0a6fde89-a37f-4541-bb39-2b9f603de36f
		summarizeBy: none
		sourceColumn: schedulereviewdate

		variation Variation
			isDefault
			relationship: 1e933660-e8b1-474b-9dc0-e7b890cdff23
			defaultHierarchy: LocalDateTable_f2133325-caec-48a3-a240-ebff9fcf46bc.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nurseassessor
		dataType: string
		lineageTag: 8aeb6ad8-ff82-4ddb-9fe3-876aad57367b
		summarizeBy: none
		sourceColumn: nurseassessor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column checklistdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: df5b8dfa-1ce7-4679-86fe-ebbddbc79bdb
		summarizeBy: none
		sourceColumn: checklistdate

		variation Variation
			isDefault
			relationship: 5b43d59c-0be0-4c1f-b2da-ab5cf1d7ce31
			defaultHierarchy: LocalDateTable_7946bdbf-59bb-4400-942c-68d7b6f61ce3.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dst
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1283a40-a9ec-4526-a57f-37edfa658236
		summarizeBy: none
		sourceColumn: dst

		variation Variation
			isDefault
			relationship: 066319a8-b248-4eaa-a51e-144534ed8ea8
			defaultHierarchy: LocalDateTable_56c07e19-f3f2-4ba5-b6cb-eb87e02ea9a7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dstsetting
		dataType: string
		lineageTag: 041201dc-06de-4d13-ade3-4b58d22df7ac
		summarizeBy: none
		sourceColumn: dstsetting

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column mdtrecommendation
		dataType: dateTime
		formatString: Long Date
		lineageTag: c25ff6e9-4f92-41bf-8f0d-c7ea71707cc1
		summarizeBy: none
		sourceColumn: mdtrecommendation

		variation Variation
			isDefault
			relationship: 70e55251-cabb-4877-8895-de5cc8c262e8
			defaultHierarchy: LocalDateTable_07607b0c-8136-4c27-a44a-6e1d9cde0b7c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column decision
		dataType: dateTime
		formatString: Long Date
		lineageTag: 74a039fe-1e17-4033-905d-cbef75e286e6
		summarizeBy: none
		sourceColumn: decision

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column outcome
		dataType: string
		lineageTag: 86681459-c637-4ba1-b5cd-6af5213b2892
		summarizeBy: none
		sourceColumn: outcome

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sourceofreferral
		dataType: string
		lineageTag: ae3d5ceb-ae67-4d75-9400-0c474485707f
		summarizeBy: none
		sourceColumn: sourceofreferral

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sourceofreferralname
		dataType: string
		lineageTag: 3ca9419d-b588-453a-acf2-da446c7bbaf6
		summarizeBy: none
		sourceColumn: sourceofreferralname

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column negativechecklistdate
		dataType: string
		lineageTag: 40d05cde-672d-4b05-b277-ddcbb8c50aaf
		summarizeBy: none
		sourceColumn: negativechecklistdate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column negativesourceofreferral
		dataType: string
		lineageTag: 8ed387cf-92ba-41c2-9eea-a8460a43da91
		summarizeBy: none
		sourceColumn: negativesourceofreferral

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column negativesourceofreferralname
		dataType: string
		lineageTag: 989e7934-991d-4251-aea5-43cf0df9f794
		summarizeBy: none
		sourceColumn: negativesourceofreferralname

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sourceinfo
		dataType: string
		lineageTag: 6ceb2af8-80bb-47dc-b54c-ee92ef7daa68
		summarizeBy: none
		sourceColumn: sourceinfo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column extractdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e5304b32-ab01-4fb1-be49-27aa468cee36
		summarizeBy: none
		sourceColumn: extractdate

		variation Variation
			isDefault
			relationship: 63dfc0db-7700-4f1c-9fa6-b692e6e6072b
			defaultHierarchy: LocalDateTable_78feaffe-fbc4-4e80-b1c6-9d42577ad971.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column filename
		dataType: string
		lineageTag: 2df20df7-cc98-4959-853a-e1517edcf8af
		summarizeBy: none
		sourceColumn: filename

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column agreementid
		dataType: string
		lineageTag: 7563c0e7-d46d-4cf0-a9ca-e25348d5f0ee
		summarizeBy: none
		sourceColumn: agreementid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column last_updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 15a6a17d-1cdb-4782-ae4f-a07a8ea956ac
		summarizeBy: none
		sourceColumn: last_updated

		variation Variation
			isDefault
			relationship: b7ae3d6e-6b57-4ad1-8a24-affb541238b7
			defaultHierarchy: LocalDateTable_6d0bfc6b-0373-43b7-9171-edf081554c78.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f02efe8e-61e8-451b-a617-2f42b317827f
		summarizeBy: none
		sourceColumn: deleted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'review Outstanding' =
			
			IF (
			    B_Reviews[schedulereviewdate]
			        < TODAY (),
			    1,
			    0
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: 35789e6f-39bc-4bce-b121-7eb0301c92eb
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition B_Reviews-cdafb79c-2431-4b82-b16e-ad33418d8cf7 = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    vw_b_201_load1 = data_mart_pid_011_chs_continuinghealthcare{[Name="vw_b_201_load"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vw_b_201_load1,{{"startdate", type date}, {"enddate", type date}, {"fundersince", type date}, {"statussince", type date}, {"schedulereviewdate", type date}, {"checklistdate", type date}, {"dst", type date}, {"decision", type date}, {"extractdate", type date}, {"mdtrecommendation", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

