table Benchmarking
	lineageTag: a5d8d183-a989-4e7c-aef4-938a6ec18864

	column organisationcode
		dataType: string
		lineageTag: d10c4a56-08aa-4c1b-90c2-fbd5c17f1d91
		summarizeBy: none
		sourceColumn: organisationcode

		annotation SummarizationSetBy = Automatic

	column 'SW Peer Cluster 1' =
			Switch (true(),
			Benchmarking[Organisation Name] = "NHS Gloucestershire CCG" ,true(),
			Benchmarking[Organisation Name] = "NHS Kernow CCG" , true(),
			Benchmarking[Organisation Name] = "NHS Cornwall CCG" , true(),
			Benchmarking[Organisation Name] = "NHS Scilly CCG" , true(),
			Benchmarking[Organisation Name] = "NHS Devon CCG", true(),
			Benchmarking[Organisation Name] = "NHS Somerset CCG", true(),
			Benchmarking[Organisation Name] = "NHS Dorset CCG" , true(),
			False())
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4aba1d7e-6f83-44ad-85a9-bcaad3f9db81
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Time Period'
		dataType: string
		lineageTag: 2c0a589e-298c-478e-b1f7-adf83ff90a4d
		summarizeBy: none
		sourceColumn: Time Period

		annotation SummarizationSetBy = Automatic

	column 'Organisation Type'
		dataType: string
		lineageTag: 4d273cb9-fc0b-4e40-a2d6-2bc4ffbbfcce
		summarizeBy: none
		sourceColumn: Organisation Type

		annotation SummarizationSetBy = Automatic

	column 'Organisation Name'
		dataType: string
		lineageTag: ecead8f2-647d-432a-8b56-c9e74fa12c40
		summarizeBy: none
		sourceColumn: Organisation Name

		annotation SummarizationSetBy = Automatic

	column 'Referrals Exceed 28D Upto 2W'
		dataType: double
		lineageTag: 0a6a0ede-0142-403b-bfe7-2b41d60373f9
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D Upto 2W

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D Upto 2W Per 50000'
		dataType: double
		lineageTag: 8b631713-09d5-4148-8f63-a96a08991f3a
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D Upto 2W Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D 2W 4W'
		dataType: double
		lineageTag: 189ab579-6144-4848-bb63-c43d3f912fef
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D 2W 4W

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D 2W 4W Per 50000'
		dataType: double
		lineageTag: 4bc36957-b5ff-47e6-85ae-acf284ee8057
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D 2W 4W Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D 4W 12W'
		dataType: double
		lineageTag: 42c37c78-1d04-4070-9e70-23d8991aa0b6
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D 4W 12W

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D 4W 12W Per 50000'
		dataType: double
		lineageTag: d502d0d3-8cfd-4540-ae4a-c94df4c5bb65
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D 4W 12W Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D 12W 26W'
		dataType: double
		lineageTag: bbaa56e5-8ae4-4e79-8f82-9bbf493e8359
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D 12W 26W

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D 12W 26W Per 50000'
		dataType: double
		lineageTag: 007f2a53-d42a-4b3a-aad6-7f9848439a59
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D 12W 26W Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D >26W'
		dataType: double
		lineageTag: b9a8c61d-04e2-4ff5-bdf5-c1ea5cae84eb
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D >26W

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D >26W Per 50000'
		dataType: double
		lineageTag: 476c80e7-59e0-4921-b681-a187caea7e02
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D >26W Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D Total'
		dataType: double
		lineageTag: c3b4ca1b-c383-4a1b-9904-58b7d4a83806
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Exceed 28D Total1'
		dataType: double
		lineageTag: aa087380-240f-4f83-bb79-1ff3356b366e
		summarizeBy: sum
		sourceColumn: Referrals Exceed 28D Total1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Totalphbs
		dataType: double
		lineageTag: 04d84e76-9a87-49a4-b417-a6ce46a5dc01
		summarizeBy: sum
		sourceColumn: Totalphbs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Totalphbs Per 50000'
		dataType: double
		lineageTag: 99ce2364-6731-4c7b-8ded-89f844f81745
		summarizeBy: sum
		sourceColumn: Totalphbs Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Phbs Dirpmts'
		dataType: double
		lineageTag: 005c7a78-4a6b-454c-990b-7c1ced7f5c07
		summarizeBy: sum
		sourceColumn: Phbs Dirpmts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Phbs Dirpmts 50K'
		dataType: double
		lineageTag: f63a734b-efde-49f2-a3a6-c32991f45407
		summarizeBy: sum
		sourceColumn: Phbs Dirpmts 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Within 28D'
		dataType: double
		lineageTag: 098788e0-ab35-46cd-a647-3a1f8f9200fc
		summarizeBy: sum
		sourceColumn: Referrals Completed Within 28D

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Within 28D Per 50000'
		dataType: double
		lineageTag: 9f68da60-1d5c-4a18-a53d-81033f4e6cc4
		summarizeBy: sum
		sourceColumn: Referrals Completed Within 28D Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Within 28D Percentage'
		dataType: double
		lineageTag: 58f4de9d-cc81-49f3-b0cc-df83bf7c8104
		summarizeBy: sum
		sourceColumn: Referrals Completed Within 28D Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Totaldsts
		dataType: double
		lineageTag: ebccdc8d-a90c-46b3-bde1-3c238625eea2
		summarizeBy: sum
		sourceColumn: Totaldsts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Totaldsts 50K'
		dataType: double
		lineageTag: 9d28fa2a-4eb9-4537-a075-93d65fb25d95
		summarizeBy: sum
		sourceColumn: Totaldsts 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dstsacute
		dataType: double
		lineageTag: e26f8be4-5e18-45e1-9897-77f79537f241
		summarizeBy: sum
		sourceColumn: Dstsacute

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dstsacute 50K'
		dataType: double
		lineageTag: 57abf6c0-3251-40f4-ad88-7a45763a7845
		summarizeBy: sum
		sourceColumn: Dstsacute 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Xdstsacute
		dataType: double
		lineageTag: 11e86e6f-0614-47f3-9804-391bff191324
		summarizeBy: sum
		sourceColumn: Xdstsacute

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Population18
		dataType: double
		lineageTag: f1956068-c2c9-43c5-9bd4-594859b98689
		summarizeBy: sum
		sourceColumn: Population18

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Localrestotal
		dataType: double
		lineageTag: 877fcaf3-0706-4a14-bf87-2e2f11f39561
		summarizeBy: sum
		sourceColumn: Localrestotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Localrestotal 50K'
		dataType: double
		lineageTag: e2d168d6-8b67-43f4-a7f6-803dd8e09a7c
		summarizeBy: sum
		sourceColumn: Localrestotal 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Localreseligible
		dataType: double
		lineageTag: 262ff580-8248-458b-b135-eb56c904290c
		summarizeBy: sum
		sourceColumn: Localreseligible

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Localreseligible 50K'
		dataType: double
		lineageTag: 5756abab-8002-4721-8493-2687d1e528d8
		summarizeBy: sum
		sourceColumn: Localreseligible 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Xlocalreseligible
		dataType: double
		lineageTag: ef323433-0ac0-4cff-940e-41ac39c607ce
		summarizeBy: sum
		sourceColumn: Xlocalreseligible

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Incomplocalres
		dataType: double
		lineageTag: cfdc7668-b638-44ff-a5d7-842c28584dcb
		summarizeBy: sum
		sourceColumn: Incomplocalres

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Incomplocalres 50K'
		dataType: double
		lineageTag: e95ce920-2b9f-4f85-9114-d5f7fed977ff
		summarizeBy: sum
		sourceColumn: Incomplocalres 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Numberrefsdiscstd
		dataType: double
		lineageTag: bdba8b2e-d050-4fb0-93d3-4144554c6c26
		summarizeBy: sum
		sourceColumn: Numberrefsdiscstd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Numberrefsdiscstd 50K'
		dataType: double
		lineageTag: 171f7e76-19f7-4457-96e1-6dc2db3efec6
		summarizeBy: sum
		sourceColumn: Numberrefsdiscstd 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Numberrefsdiscft
		dataType: double
		lineageTag: 05db7b1b-721f-40af-943f-0cc3843eab4d
		summarizeBy: sum
		sourceColumn: Numberrefsdiscft

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Numberrefsdiscft 50K'
		dataType: double
		lineageTag: 2747c862-fa91-4738-960f-1ebf2d7a80d4
		summarizeBy: sum
		sourceColumn: Numberrefsdiscft 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Numbertotalrefsdisc
		dataType: double
		lineageTag: 11d1be5a-424c-40f5-89d4-bdfb7d7ca11d
		summarizeBy: sum
		sourceColumn: Numbertotalrefsdisc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Numbertotalrefsdisc 50K'
		dataType: double
		lineageTag: 8b8ea1ec-0d9a-49a8-abf3-c4985f6b5e30
		summarizeBy: sum
		sourceColumn: Numbertotalrefsdisc 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period = if (Benchmarking[Time Period] = max('Benchmarking'[Time Period]), "Most Recent Data" , 'Benchmarking'[Time Period] )
		lineageTag: 33a69cac-3f0c-4637-afeb-a93f08461bfe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Eligible Standard CHC Snpsht'
		dataType: double
		lineageTag: 727e6a7b-cdf0-496e-ba1b-09117d445406
		summarizeBy: sum
		sourceColumn: Eligible Standard CHC Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Standard CHC Per 50000 Snpsht'
		dataType: double
		lineageTag: 195ff6b4-46ad-4888-b77f-610537101fe9
		summarizeBy: sum
		sourceColumn: Eligible Standard CHC Per 50000 Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Fast Track CHC Snpsht'
		dataType: double
		lineageTag: d87cc388-7f99-4ee3-aab3-dbbd80d55643
		summarizeBy: sum
		sourceColumn: Eligible Fast Track CHC Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Fast Track CHC Per 50000 Snpsht'
		dataType: double
		lineageTag: 99873121-6b37-406c-b640-7ee170578082
		summarizeBy: sum
		sourceColumn: Eligible Fast Track CHC Per 50000 Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Total CHC Snpsht'
		dataType: double
		lineageTag: 41b52609-9c88-4319-ac29-9d7b0bb48998
		summarizeBy: sum
		sourceColumn: Eligible Total CHC Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Total CHC Per 50000 Snpsht'
		dataType: double
		lineageTag: 99c852ac-dd58-4e34-9874-21bdee3d41b3
		summarizeBy: sum
		sourceColumn: Eligible Total CHC Per 50000 Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible FNC Snpsht'
		dataType: double
		lineageTag: f73cf87e-314e-4763-a14f-a8f53571e099
		summarizeBy: sum
		sourceColumn: Eligible FNC Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible FNC Per 50000 Snpsht'
		dataType: double
		lineageTag: b621d8f0-c048-4016-8f91-9a78975cb6bc
		summarizeBy: sum
		sourceColumn: Eligible FNC Per 50000 Snpsht

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Standard CHC YTD'
		dataType: double
		lineageTag: 2d84e016-bb72-4215-8666-e5d9c8edfed0
		summarizeBy: sum
		sourceColumn: Eligible Standard CHC YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Standard CHC Per 50000 YTD'
		dataType: double
		lineageTag: 180d90eb-3102-4718-8226-ae27dbe114ba
		summarizeBy: sum
		sourceColumn: Eligible Standard CHC Per 50000 YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Fast Track CHC YTD'
		dataType: double
		lineageTag: ef0914b2-f0fb-4b56-8079-e5b82d2c0a5b
		summarizeBy: sum
		sourceColumn: Eligible Fast Track CHC YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Fast Track CHC Per 50000 YTD'
		dataType: double
		lineageTag: 88feb44d-74e4-4e72-ad44-613cdec464c8
		summarizeBy: sum
		sourceColumn: Eligible Fast Track CHC Per 50000 YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Total CHC YTD'
		dataType: double
		lineageTag: 406350f9-cc9f-47ec-99d5-6e9dfba0ac8c
		summarizeBy: sum
		sourceColumn: Eligible Total CHC YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Total CHC Per 50000 YTD'
		dataType: double
		lineageTag: 5204ecd2-244d-41a6-b2a4-45387e8c8389
		summarizeBy: sum
		sourceColumn: Eligible Total CHC Per 50000 YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible FNC YTD'
		dataType: double
		lineageTag: 5743cdf2-304e-4c36-8de7-d2ca68777b39
		summarizeBy: sum
		sourceColumn: Eligible FNC YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible FNC Per 50000 YTD'
		dataType: double
		lineageTag: 0f0d0924-5888-4603-bd76-20a28f35fd66
		summarizeBy: sum
		sourceColumn: Eligible FNC Per 50000 YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Referrals Standard CHC'
		dataType: double
		lineageTag: c73d88c1-3f3f-4469-b324-1b75bbc83d98
		summarizeBy: sum
		sourceColumn: New Referrals Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Referrals Standard CHC Per 50000'
		dataType: double
		lineageTag: 67bb2f1c-5e1f-4532-99d8-4299267ca382
		summarizeBy: sum
		sourceColumn: New Referrals Standard CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Referrals Fast Track CHC'
		dataType: double
		lineageTag: 202f0829-4206-4b7b-97ee-4437dab69231
		summarizeBy: sum
		sourceColumn: New Referrals Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Referrals Fast Track CHC Per 50000'
		dataType: double
		lineageTag: 3fcbb29f-1813-46d5-9bc3-5e90ffa411e8
		summarizeBy: sum
		sourceColumn: New Referrals Fast Track CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Referrals Total CHC'
		dataType: double
		lineageTag: b77c327b-b5bc-4551-bb61-a043ba6574e7
		summarizeBy: sum
		sourceColumn: New Referrals Total CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Referrals Total CHC Per 50000'
		dataType: double
		lineageTag: bfa6f101-ffa4-4303-b713-662ff6118eff
		summarizeBy: sum
		sourceColumn: New Referrals Total CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Standard CHC'
		dataType: double
		lineageTag: f8d758b2-c875-4b2f-abd2-dff878642c1a
		summarizeBy: sum
		sourceColumn: Referrals Completed Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Standard CHC Per 50000'
		dataType: double
		lineageTag: 06e01bb3-6b70-4542-8a25-f5c7a9c6e4d0
		summarizeBy: sum
		sourceColumn: Referrals Completed Standard CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Fast Track CHC'
		dataType: double
		lineageTag: 73f2777b-510a-48b2-84a0-ed78dd9d7023
		summarizeBy: sum
		sourceColumn: Referrals Completed Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Fast Track CHC Per 50000'
		dataType: double
		lineageTag: cb4ea574-f2f3-4b88-88f1-20e435c0d8e9
		summarizeBy: sum
		sourceColumn: Referrals Completed Fast Track CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Total CHC'
		dataType: double
		lineageTag: 052f3a7f-2a4e-4dcb-a6a1-b4032a311608
		summarizeBy: sum
		sourceColumn: Referrals Completed Total CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referrals Completed Total CHC Per 50000'
		dataType: double
		lineageTag: b5fa687e-e840-4282-8a5d-6401dfc9ad76
		summarizeBy: sum
		sourceColumn: Referrals Completed Total CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessments Completed Standard CHC'
		dataType: double
		lineageTag: 658755b2-af42-40c2-b071-8ca550a48e9b
		summarizeBy: sum
		sourceColumn: Assessments Completed Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessments Completed Standard CHC Per 50000'
		dataType: double
		lineageTag: cbe550b5-7c78-466a-84cb-d2807cf58743
		summarizeBy: sum
		sourceColumn: Assessments Completed Standard CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessments Completed Fast Track CHC'
		dataType: double
		lineageTag: 1230f079-559c-4c31-b99c-dce974526015
		summarizeBy: sum
		sourceColumn: Assessments Completed Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessments Completed Fast Track CHC Per 50000'
		dataType: double
		lineageTag: c75ac23e-3d53-4dd8-9ad5-d7a6a9099420
		summarizeBy: sum
		sourceColumn: Assessments Completed Fast Track CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessments Completed Total CHC'
		dataType: double
		lineageTag: e42b8880-f391-4315-9ccf-333e7255cc1e
		summarizeBy: sum
		sourceColumn: Assessments Completed Total CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessments Completed Total CHC Per 50000'
		dataType: double
		lineageTag: 78b0239e-e0fc-44ee-b01e-3843a8068dca
		summarizeBy: sum
		sourceColumn: Assessments Completed Total CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Assessments Standard CHC'
		dataType: double
		lineageTag: 15110506-2497-46a9-9688-1f255f1e055a
		summarizeBy: sum
		sourceColumn: Eligible Assessments Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Assessments Standard CHC Per 50000'
		dataType: double
		lineageTag: 0268fb93-83ce-45b6-a996-169b11e48861
		summarizeBy: sum
		sourceColumn: Eligible Assessments Standard CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Assessments Fast Track CHC'
		dataType: double
		lineageTag: d48ffa2d-08ca-4d2a-8846-a29d8a9bb7cb
		summarizeBy: sum
		sourceColumn: Eligible Assessments Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Assessments Fast Track CHC Per 50000'
		dataType: double
		lineageTag: b70927cc-5ca6-4c1a-829c-864ef36a61f9
		summarizeBy: sum
		sourceColumn: Eligible Assessments Fast Track CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Assessments Total CHC'
		dataType: double
		lineageTag: 926d95ed-7e97-4d2f-af09-4d5b228fe1d1
		summarizeBy: sum
		sourceColumn: Eligible Assessments Total CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligible Assessments Total CHC Per 50000'
		dataType: double
		lineageTag: 3c2183ec-5752-434c-b954-c9bbfc179d47
		summarizeBy: sum
		sourceColumn: Eligible Assessments Total CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Non Eligible Assessments Standard CHC'
		dataType: double
		lineageTag: b9a75759-aefb-4cbe-9a46-8c3f00fdb11f
		summarizeBy: sum
		sourceColumn: Non Eligible Assessments Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Non Eligible Assessments Standard CHC Per 50000'
		dataType: double
		lineageTag: f207421b-40d8-472d-a7f5-bd908c10c552
		summarizeBy: sum
		sourceColumn: Non Eligible Assessments Standard CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Non Eligible Assessments Fast Track CHC'
		dataType: double
		lineageTag: f9129bdc-6cc8-496f-ac38-8d562c6c27fd
		summarizeBy: sum
		sourceColumn: Non Eligible Assessments Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Non Eligible Assessments Fast Track CHC Per 50000'
		dataType: double
		lineageTag: be2f6ee6-a37f-4f14-a661-dc62b05a3929
		summarizeBy: sum
		sourceColumn: Non Eligible Assessments Fast Track CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Non Eligible Assessments Total CHC'
		dataType: double
		lineageTag: 5957ca48-33ad-4734-932a-15ab54ffc5b4
		summarizeBy: sum
		sourceColumn: Non Eligible Assessments Total CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Non Eligible Assessments Total CHC Per 50000'
		dataType: double
		lineageTag: b9f2f605-801b-4a13-b3d6-65beeb88db88
		summarizeBy: sum
		sourceColumn: Non Eligible Assessments Total CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No Longer Eligible Assessments Standard CHC'
		dataType: double
		lineageTag: 4cf3f219-0f38-4a98-9b10-248f0c6e824f
		summarizeBy: sum
		sourceColumn: No Longer Eligible Assessments Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No Longer Eligible Assessments Standard CHC Per 50000'
		dataType: double
		lineageTag: b18ca9d6-2bcb-4b2c-a162-369c74f6d411
		summarizeBy: sum
		sourceColumn: No Longer Eligible Assessments Standard CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No Longer Eligible Assessments Fast Track CHC'
		dataType: double
		lineageTag: 7a263514-51ec-4bc4-ba8a-81b6d0095e5d
		summarizeBy: sum
		sourceColumn: No Longer Eligible Assessments Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No Longer Eligible Assessments Fast Track CHC Per 50000'
		dataType: double
		lineageTag: 2ffd6c44-ed68-4e99-8ebf-f67afb364161
		summarizeBy: sum
		sourceColumn: No Longer Eligible Assessments Fast Track CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No Longer Eligible Assessments Total CHC'
		dataType: double
		lineageTag: 8149b23f-55ad-40c6-a447-1f730bc0064b
		summarizeBy: sum
		sourceColumn: No Longer Eligible Assessments Total CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No Longer Eligible Assessments Total CHC Per 50000'
		dataType: double
		lineageTag: b4cab7b5-84d4-40ea-93f4-b460dbd9ae5f
		summarizeBy: sum
		sourceColumn: No Longer Eligible Assessments Total CHC Per 50000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessment Conversion Standard CHC'
		dataType: double
		lineageTag: 25c9d88b-8ccc-4fd6-9fa4-b2399f4761a6
		summarizeBy: sum
		sourceColumn: Assessment Conversion Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assessment Conversion Fast Track CHC'
		dataType: double
		lineageTag: 26a44c9e-8553-4edb-905c-f1127a6e57ba
		summarizeBy: sum
		sourceColumn: Assessment Conversion Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referral Conversion Standard CHC'
		dataType: double
		lineageTag: 6b7b0065-8835-4c6f-b34e-d9b3c0d2c8b1
		summarizeBy: sum
		sourceColumn: Referral Conversion Standard CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Referral Conversion Fast Track CHC'
		dataType: double
		lineageTag: 94606f49-2b34-4b00-8e84-712a9332e332
		summarizeBy: sum
		sourceColumn: Referral Conversion Fast Track CHC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligpupoc YTD'
		dataType: double
		lineageTag: dba53f04-5840-41fb-988c-8d33cea4831a
		summarizeBy: sum
		sourceColumn: Eligpupoc YTD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eligpupoc YTD 50K'
		dataType: double
		lineageTag: 8af025dd-090c-4884-8543-b32cef1e2acc
		summarizeBy: sum
		sourceColumn: Eligpupoc YTD 50K

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Benchmarking-9d95f944-b372-4e40-a14b-764d9226b915 = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    tbl_benchmarking_201_load = data_mart_pid_011_chs_continuinghealthcare{[Name="tbl_benchmarking_201_load"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(tbl_benchmarking_201_load,{{"timeperiod", "Time Period"}, {"organisationtype", "Organisation Type"}, {"organisationname", "Organisation Name"}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Time Period", "Organisation Type", "organisationcode", "Organisation Name"}, "Attribute", "Value"),
				    #"Inserted Replaced Text" = Table.AddColumn(#"Unpivoted Columns", "Replaced Text", each Text.Replace(Text.Proper([Attribute]), "_", " "), type text),
				
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Replaced Text",{"Attribute"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Replaced Text", "Attribute"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","Elidgible","Eligible",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Fasttrack","Fast Track",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Ytd","YTD",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Fnc","FNC",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Chc","CHC",Replacer.ReplaceText,{"Attribute"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value4",{{"Value", type number}}),
				    #"Pivoted Column" = Table.Pivot(#"Changed Type", List.Distinct(#"Changed Type"[Attribute]), "Attribute", "Value")
				in
				    #"Pivoted Column"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

