table 'Benchmarking order'
	lineageTag: 16d85903-538a-4095-a271-6afcd03f101e

	column Metric
		dataType: string
		lineageTag: 13e6df80-effb-4161-81a5-20bb3fac54f0
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 2ed0a79c-6505-4071-bf13-60a24542e3ff
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Benchmarking order-0b9346ac-66cc-45d6-9bbc-9e9d5f97be08' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fY/BDoIwEER/ZdMzB0VRrqZoPBmjJMYQDhVWbCzFdBu/35V4Qax7fm9npijEAa/onDIEsmsfBj3WcPTK1srVILcS9uggmfCJSExFGf1WNoo85E5V95EU99KKCIlatJ4t+0RHurODJEZnf9BhAsPzYJmT9jdtIU6zd5GKH6kG2Uh6Y210oy8GAzPhnGfMLoZsaN+HXn7RuzGSirJ8AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

