table C_Onetimecost
	lineageTag: 07e46bba-bc08-45d7-9af9-d7c23877ad66

	column clientid
		dataType: int64
		formatString: 0
		lineageTag: 2382307b-6834-4cf4-aeb4-f4ad96f82abe
		summarizeBy: sum
		sourceColumn: clientid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dom_res
		dataType: string
		lineageTag: 7c16386c-a38a-4bf5-ad24-1ef95403c5ad
		summarizeBy: none
		sourceColumn: dom_res

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fundername
		dataType: string
		lineageTag: 4aebab55-251c-4fe5-8046-4e1629ef9890
		summarizeBy: none
		sourceColumn: fundername

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column provider
		dataType: string
		lineageTag: 8b75a8fa-534b-4158-bc1a-2f11c69519ff
		summarizeBy: none
		sourceColumn: provider

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column carestayid
		dataType: string
		lineageTag: 6167cc99-7d9b-481f-adcd-e3d6593a27a1
		summarizeBy: none
		sourceColumn: carestayid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column costtype
		dataType: string
		lineageTag: 3e0badbe-8a3e-409e-922f-e9def98e943b
		summarizeBy: none
		sourceColumn: costtype

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column practicecode
		dataType: string
		lineageTag: 8672c9ba-1769-45b5-b3ec-1b66803b97ce
		summarizeBy: none
		sourceColumn: practicecode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column onetimecostdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b957fd39-785e-4e1b-a351-ca560442c613
		summarizeBy: none
		sourceColumn: onetimecostdate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column carecategory
		dataType: string
		lineageTag: e2eda189-ae5d-4fac-b1d5-188cc752238e
		summarizeBy: none
		sourceColumn: carecategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: 69051109-42b5-4fa3-9870-cb5398b6222a
		summarizeBy: sum
		sourceColumn: cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column extractdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5dce6fbf-d085-4365-ac0b-4cec977b640c
		summarizeBy: none
		sourceColumn: extractdate

		variation Variation
			isDefault
			relationship: 9540736a-d2c5-455c-9d5d-46130123c36e
			defaultHierarchy: LocalDateTable_56cd9789-6909-43b5-85b4-0d466b795b40.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column filename
		dataType: string
		lineageTag: da6daed3-142e-48a4-9b4a-12ee00c8efa1
		summarizeBy: none
		sourceColumn: filename

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column agreementid
		dataType: string
		lineageTag: 19742a12-2b2b-4002-9260-0170f8e5434d
		summarizeBy: none
		sourceColumn: agreementid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column last_updated
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd3337f1-7d2e-450d-bf87-4dc711ff3e1c
		summarizeBy: none
		sourceColumn: last_updated

		variation Variation
			isDefault
			relationship: 75cf9f29-234a-41f5-a0c6-030b9a80f389
			defaultHierarchy: LocalDateTable_fba755b2-7114-49c7-943e-a1bcc82cea44.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 684a4e3b-0f0b-4c85-bbdf-a3eaa020051b
		summarizeBy: none
		sourceColumn: deleted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition C_Onetimecost-25d47981-3c2d-4bed-805f-63b17929b0bd = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    vw_c_201_load1 = data_mart_pid_011_chs_continuinghealthcare{[Name="vw_c_201_load"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vw_c_201_load1,{{"onetimecostdate", type date}, {"extractdate", type date}, {"last_updated", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

