table Finance
	lineageTag: e9530ea6-9d93-4f16-9356-dfb6af4fb4f2

	measure 'Annual Budget' = ```
			sum(Finance[Annual  Budget]) 
			```
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 411d6954-2ab4-48ef-a765-d055e50fee0a

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Forecast Outturn' = sum(Finance[Forecast  Outturn])
		lineageTag: d64e356a-16bb-4caf-97bc-0cc2ad0b3baa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Forecast Variance' = ```
			sum( Finance[Forecast  Variance]) 
			```
		lineageTag: 1ba2563d-3a0e-44f5-a947-1e555dff3920

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'In Month Budget' = sum (Finance[In Month  Budget])
		lineageTag: c305daca-9908-4fa1-b197-104a90d67eda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'In Month Costs' = ```
			sum( Finance[In  Month Costs] ) 
			```
		lineageTag: e76da9d1-2b13-4128-bd7a-f43fbd770d22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'In Month Variance' = ```
			sum(Finance[In  Month Variance]) 
			```
		lineageTag: 4f789551-0545-4606-9a62-4a2d9bb0e152

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Month Forecast Variance' = ```
			sum(Finance[Previous  Month Fore Cast Variance]) 
			```
		lineageTag: 6518bb90-685d-48be-9db6-c50cf4e4592b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Budget' = ```
			sum(Finance[YTD  Budget]) 
			```
		lineageTag: 944fcbf5-8b5f-49f4-b16c-198b4b0a8932

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Costs' = sum(Finance[YTD  Costs])
		lineageTag: a59ffa35-02ae-4eb1-af3b-d27f6d5e29fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Variance' = ```
			sum(Finance[YTD  Variance]) 
			```
		lineageTag: 42b1f586-a154-4b36-a503-1494d9914569

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Funder  Type'
		dataType: string
		lineageTag: ac4d106e-c3be-4be3-bed9-8fe43d1f0fa8
		summarizeBy: none
		sourceColumn: Funder  Type

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb06e86f-ea14-4e44-a91f-1feffe717560
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'In Month  Budget'
		dataType: double
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: d94cb24c-9b2e-4c9e-90f0-f278250e49df
		summarizeBy: sum
		sourceColumn: In Month  Budget

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'In  Month Costs'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: d087ffdb-47a5-4f9d-8ed6-45e5e85301f6
		summarizeBy: sum
		sourceColumn: In  Month Costs

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'In  Month Variance'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 2b5b4655-130d-4e55-bf4f-12ca4c15fe72
		summarizeBy: sum
		sourceColumn: In  Month Variance

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'YTD  Budget'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: d3b6b43a-9e40-4f51-8b1b-f315ebe15850
		summarizeBy: sum
		sourceColumn: YTD  Budget

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'YTD  Costs'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 207413ef-7fe8-440f-bfab-cfd7d16b897c
		summarizeBy: sum
		sourceColumn: YTD  Costs

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'YTD  Variance'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 2ac0c2f6-d7d0-4667-95a9-01d61d9cd36a
		summarizeBy: sum
		sourceColumn: YTD  Variance

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Annual  Budget'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 95e6be7d-8671-4bae-9ff6-15f75b1f8823
		summarizeBy: sum
		sourceColumn: Annual  Budget

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Forecast  Outturn'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: a3da12f0-4195-47d2-886a-08309efb3673
		summarizeBy: sum
		sourceColumn: Forecast  Outturn

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Forecast  Variance'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 45c3e865-a0e2-46bb-99e8-8d39e130d70c
		summarizeBy: sum
		sourceColumn: Forecast  Variance

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Previous  Month Fore Cast Variance'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: ca22b200-65ca-474f-b324-4511d728428a
		summarizeBy: sum
		sourceColumn: Previous  Month Fore Cast Variance

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Forecast Variance Comments'
		dataType: string
		lineageTag: ebf57906-cd67-4ed7-8908-fa88b27acf8c
		summarizeBy: none
		sourceColumn: Forecast Variance Comments

		annotation SummarizationSetBy = Automatic

	column Month = if (Finance[Date] = max(Finance[Date]), "Most Recent Data",   FORMAT( Finance[Date], ""  ))
		lineageTag: 330e59e3-77e2-4518-9a16-209a96fa7f78
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Area = ```
			switch(true(), 
			
			Finance[Funder  Type] = "CHC - Domiciliary" , "CHC - Domiciliary",
			Finance[Funder  Type] = "CHC - Residential" , "CHC - Residential",
			Finance[Funder  Type] in { "CHC Team - Non Pay" , "CHC Team - Pay", "Other"} , "CHC Team",
			Finance[Funder  Type] in { "S256 - Fully Funded CHC" , "S256 - Fully Funded Non CHC"}, "S256 - Fully Funded",
			Finance[Funder  Type] in { "S256 - Joint Funded CHC" , "S256 - Joint Funded Non CHC"}, "S256 - Joint",
			Finance[Funder  Type] = "PHBs Adult", "PHB",
			Finance[Funder  Type] = "FNC", "FNC",
			Finance[Funder  Type] = "HDP", "HDP",
			blank())
			```
		lineageTag: 08da2358-a221-42c2-a5f5-1cfad4b2c0e8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Finance-3497e7c1-081c-4ad1-b0dd-de8d12c344f0 = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    tbl_finance_201_load = data_mart_pid_011_chs_continuinghealthcare{[Name="tbl_finance_201_load"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(tbl_finance_201_load,{{"month", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"month", "Date"}, {"annualbudget", "Annual  Budget"}, {"forecastoutturn", "Forecast  Outturn"}, {"forecastvariance", "Forecast  Variance"}, {"forecastvariancecomments", "Forecast Variance Comments"}, {"fundertype", "Funder  Type"}, {"inmonthbudget", "In Month  Budget"}, {"inmonthcosts", "In  Month Costs"}, {"inmonthvariance", "In  Month Variance"}, {"previousmonthforecastvariance", "Previous  Month Fore Cast Variance"}, {"ytdbudget", "YTD  Budget"}, {"ytdvariance", "YTD  Variance"}, {"ytdcosts", "YTD  Costs"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates"," £- ","",Replacer.ReplaceText,{"In Month  Budget"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value"," £- ","",Replacer.ReplaceText,{"In  Month Costs"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1"," £- ","",Replacer.ReplaceText,{"In  Month Variance"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2"," £- ","",Replacer.ReplaceText,{"YTD  Budget"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3"," £- ","",Replacer.ReplaceText,{"YTD  Costs"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4"," £- ","",Replacer.ReplaceText,{"YTD  Variance"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5"," £- ","",Replacer.ReplaceText,{"Annual  Budget"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6"," £- ","",Replacer.ReplaceText,{"Forecast  Outturn"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7"," £- ","",Replacer.ReplaceText,{"Forecast  Variance"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8"," £- ","",Replacer.ReplaceText,{"Previous  Month Fore Cast Variance"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value9",{{"In Month  Budget", Currency.Type}, {"In  Month Costs", Currency.Type}, {"In  Month Variance", Currency.Type}, {"YTD  Budget", Currency.Type}, {"YTD  Costs", Currency.Type}, {"YTD  Variance", Currency.Type}, {"Annual  Budget", Currency.Type}, {"Forecast  Outturn", Currency.Type}, {"Forecast  Variance", Currency.Type}, {"Previous  Month Fore Cast Variance", Currency.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

