table Date_Table
	lineageTag: be67b0da-2e92-4500-80af-8c48b6fda8d1

	measure 'Last Updated' = TODAY()
		formatString: mmmm yyyy
		lineageTag: 3e2952f5-de50-41ab-8df7-bc76a084fd0f

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b9ec1e1-8049-4b89-b43a-5ad82c143ad8
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 8b1c78a0-0e1e-402c-9ed3-175f246d8c01
			defaultHierarchy: LocalDateTable_73e18a31-df1d-4855-a6b5-677257a4f0e8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: 0146341b-2470-4644-a453-d623ee54b1c7
		summarizeBy: sum
		sourceColumn: YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: af822dd6-561e-4ef0-ac83-d9a39f0f7498
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column Datekey
		dataType: int64
		formatString: 0
		lineageTag: 31ff030c-e000-47cb-8169-987a633ed0b0
		summarizeBy: sum
		sourceColumn: Datekey

		annotation SummarizationSetBy = Automatic

	column Full_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9413b04b-0992-4c3b-91a9-737af2710627
		summarizeBy: none
		sourceColumn: Full_Date

		variation Variation
			isDefault
			relationship: fc1f6546-586e-42ed-b35f-708d81dda511
			defaultHierarchy: LocalDateTable_bf2d0857-f71c-4a15-bc25-0fd4c7987b77.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Date_no_hyphen
		dataType: int64
		formatString: 0
		lineageTag: 02b225c4-f0e8-4a2a-ad6d-7112071e63e6
		summarizeBy: sum
		sourceColumn: Date_no_hyphen

		annotation SummarizationSetBy = Automatic

	column Excel_Date_Value
		dataType: int64
		formatString: 0
		lineageTag: 01da27a5-4d7e-4ebe-a424-fc2395e04762
		summarizeBy: sum
		sourceColumn: Excel_Date_Value

		annotation SummarizationSetBy = Automatic

	column Bank_Holiday_Desc
		dataType: string
		lineageTag: 25782135-95ba-4b9e-b7aa-fa0de68e639f
		summarizeBy: none
		sourceColumn: Bank_Holiday_Desc

		annotation SummarizationSetBy = Automatic

	column Bank_Holiday_Flag
		dataType: int64
		formatString: 0
		lineageTag: 667cdac5-4285-4160-b3c8-76de86a780f6
		summarizeBy: sum
		sourceColumn: Bank_Holiday_Flag

		annotation SummarizationSetBy = Automatic

	column Working_Day_Type
		dataType: string
		lineageTag: 297e6d8f-aa79-4907-9b99-9fe73a8a374a
		summarizeBy: none
		sourceColumn: Working_Day_Type

		annotation SummarizationSetBy = Automatic

	column Working_Day_Type_Full
		dataType: string
		lineageTag: 2728fe4e-eaca-47cf-afd2-3bed5327ad03
		summarizeBy: none
		sourceColumn: Working_Day_Type_Full

		annotation SummarizationSetBy = Automatic

	column Work_Day_Flag
		dataType: int64
		formatString: 0
		lineageTag: 425880e7-b8e4-41c8-97b8-32a3ab64237e
		summarizeBy: sum
		sourceColumn: Work_Day_Flag

		annotation SummarizationSetBy = Automatic

	column Weekend_Day_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2b370cf8-d6bd-4f37-acdc-ed9e197c6d14
		summarizeBy: sum
		sourceColumn: Weekend_Day_Flag

		annotation SummarizationSetBy = Automatic

	column Weekday_No
		dataType: int64
		formatString: 0
		lineageTag: 9cba5561-a923-41fa-b37f-049c9c710e82
		summarizeBy: sum
		sourceColumn: Weekday_No

		annotation SummarizationSetBy = Automatic

	column Weekday_Name
		dataType: string
		lineageTag: 6ad990ce-188b-4cf8-a0a9-627cd398c75b
		summarizeBy: none
		sourceColumn: Weekday_Name

		annotation SummarizationSetBy = Automatic

	column Weekday_Short_Name
		dataType: string
		lineageTag: 062dec93-0ec3-4421-9580-3b6fc73781cb
		summarizeBy: none
		sourceColumn: Weekday_Short_Name

		annotation SummarizationSetBy = Automatic

	column Week_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 0ceae120-ece5-4089-bae4-4d85238aea99
		summarizeBy: sum
		sourceColumn: Week_Start_112

		annotation SummarizationSetBy = Automatic

	column Week_End_112
		dataType: int64
		formatString: 0
		lineageTag: 4e4b35e8-5a75-40a0-821e-c0c54d0b75bf
		summarizeBy: sum
		sourceColumn: Week_End_112

		annotation SummarizationSetBy = Automatic

	column Fin_Week_No_2_Char
		dataType: string
		lineageTag: a12387ce-dd6a-4b94-b54d-9ea16dcbceff
		summarizeBy: none
		sourceColumn: Fin_Week_No_2_Char

		annotation SummarizationSetBy = Automatic

	column YearMonth_YYYYMM
		dataType: int64
		formatString: 0
		lineageTag: 83d524bd-6322-4ea9-9e9d-d4ad6dfddbdd
		summarizeBy: sum
		sourceColumn: YearMonth_YYYYMM

		annotation SummarizationSetBy = Automatic

	column Year-Month
		dataType: string
		lineageTag: 11b05bba-d26a-48b6-b2db-15b483bae3b5
		summarizeBy: none
		sourceColumn: Year-Month

		annotation SummarizationSetBy = Automatic

	column 'Year / Month'
		dataType: string
		lineageTag: fa5994fc-5036-4218-8193-4396179988bc
		summarizeBy: none
		sourceColumn: Year / Month

		annotation SummarizationSetBy = Automatic

	column Month_No_2_Char
		dataType: string
		lineageTag: 95188161-61f9-401c-b569-3cbb17872826
		summarizeBy: none
		sourceColumn: Month_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Month_Name
		dataType: string
		lineageTag: 38d9b2b4-2286-40e3-9e6d-8c36fba8922e
		summarizeBy: none
		sourceColumn: Month_Name

		annotation SummarizationSetBy = Automatic

	column Month_Short_Name
		dataType: string
		lineageTag: a1ece321-6808-4dd1-be33-47548704f00b
		summarizeBy: none
		sourceColumn: Month_Short_Name

		annotation SummarizationSetBy = Automatic

	column Month_Start_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 7512e76a-6cb6-410c-87bd-642529b1a03b
		summarizeBy: none
		sourceColumn: Month_Start_DateTime

		variation Variation
			isDefault
			relationship: de174e42-0393-4cf1-955d-5b4d92d62962
			defaultHierarchy: LocalDateTable_07011f47-acb4-48ce-b30f-aa44d9b0f36a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month_Start_112
		dataType: int64
		formatString: 0
		lineageTag: 911a49c2-069b-44f3-81b0-0d6f97c2e87e
		summarizeBy: sum
		sourceColumn: Month_Start_112

		annotation SummarizationSetBy = Automatic

	column Month_End_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: c9cf13c9-fe29-449d-afee-724006ceee7a
		summarizeBy: none
		sourceColumn: Month_End_DateTime

		variation Variation
			isDefault
			relationship: e666482b-243f-40db-a09e-0fa979550267
			defaultHierarchy: LocalDateTable_448da26c-a468-4f55-8558-fb7b217d89f2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month_End_112
		dataType: int64
		formatString: 0
		lineageTag: 3abf6391-9842-4767-a05a-31cdd19e0124
		summarizeBy: sum
		sourceColumn: Month_End_112

		annotation SummarizationSetBy = Automatic

	column MonthYear_MMMM_YYYYY
		dataType: string
		lineageTag: b85f1e71-ce93-4143-8526-d940dff53ffc
		summarizeBy: none
		sourceColumn: MonthYear_MMMM_YYYYY

		annotation SummarizationSetBy = Automatic

	column Fin_Month_No_2_Char
		dataType: string
		lineageTag: 69aacb1c-b221-40b9-93c4-2d95b92e806d
		summarizeBy: none
		sourceColumn: Fin_Month_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Quarter_Name
		dataType: string
		lineageTag: 8db69091-706b-46c2-9841-585b8cb69b15
		summarizeBy: none
		sourceColumn: Quarter_Name

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_No
		dataType: int64
		formatString: 0
		lineageTag: 80e19080-438c-4263-9208-6f66810dcc19
		summarizeBy: sum
		sourceColumn: Fin_Quarter_No

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_Name
		dataType: string
		lineageTag: 049f543b-bef0-4b2d-8900-6e3f9a341112
		summarizeBy: none
		sourceColumn: Fin_Quarter_Name

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_Qq_Fin_Year_YYYY_dash_YY
		dataType: string
		lineageTag: 600186ce-49a8-46e7-acfa-543559766e3f
		summarizeBy: none
		sourceColumn: Fin_Quarter_Qq_Fin_Year_YYYY_dash_YY

		annotation SummarizationSetBy = Automatic

	column Quarter_FinYr
		dataType: string
		lineageTag: 2112639a-2c25-47a1-9b9c-3ce76db5c742
		summarizeBy: none
		sourceColumn: Quarter_FinYr

		annotation SummarizationSetBy = Automatic

	column Fin_Year
		dataType: int64
		formatString: 0
		lineageTag: 7b64e36a-f680-47ea-858a-d6e9f1687e38
		summarizeBy: sum
		sourceColumn: Fin_Year

		annotation SummarizationSetBy = Automatic

	column Fin_Year_YYYY_dash_YY
		dataType: string
		lineageTag: 1eb80fa8-2760-43d1-99cf-d4526a68f7ba
		summarizeBy: none
		sourceColumn: Fin_Year_YYYY_dash_YY

		annotation SummarizationSetBy = Automatic

	column 'Fin_Year /'
		dataType: string
		lineageTag: 00aab97a-b02c-435b-8ee0-c37f57a79e88
		summarizeBy: none
		sourceColumn: Fin_Year /

		annotation SummarizationSetBy = Automatic

	column Day_Of_Fin_Year_3_Char
		dataType: string
		lineageTag: a2e1f67e-5cbd-477b-b7eb-c24eb1ddacaa
		summarizeBy: none
		sourceColumn: Day_Of_Fin_Year_3_Char

		annotation SummarizationSetBy = Automatic

	column Calendar_Year
		dataType: int64
		formatString: 0
		lineageTag: 30d69ff3-2932-4844-b6aa-cf2c53e8961f
		summarizeBy: sum
		sourceColumn: Calendar_Year

		annotation SummarizationSetBy = Automatic

	column Day_Of_Year_3_Char
		dataType: string
		lineageTag: 3949ced1-1a25-43ce-9fdc-495e19aea624
		summarizeBy: none
		sourceColumn: Day_Of_Year_3_Char

		annotation SummarizationSetBy = Automatic

	column Month_Day_No_2_Char
		dataType: string
		lineageTag: fbbe758d-2086-4219-94eb-2f92784a3b6c
		summarizeBy: none
		sourceColumn: Month_Day_No_2_Char

		annotation SummarizationSetBy = Automatic

	column Previous_Day112
		dataType: int64
		formatString: 0
		lineageTag: 1af4c7ad-2b98-4fab-921d-37d0b286d2da
		summarizeBy: sum
		sourceColumn: Previous_Day112

		annotation SummarizationSetBy = Automatic

	column Next_Day_112
		dataType: int64
		formatString: 0
		lineageTag: b5a47e2c-0469-40b7-9beb-6d5400e8edee
		summarizeBy: sum
		sourceColumn: Next_Day_112

		annotation SummarizationSetBy = Automatic

	partition Date_Table = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="SELECT *#(lf)FROM [PowerBI_Reporting].[Maternity].[tbl04_Date]"]),
				    #"Duplicated Column" = Table.AddColumn(Source, "Date_no_hyphen - Copy", each [Date_no_hyphen], type number),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Date_no_hyphen - Copy", "Datekey"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"Datekey", "Date", "Full_Date", "Date_no_hyphen", "Excel_Date_Value", "Bank_Holiday_Desc", "Bank_Holiday_Flag", "Working_Day_Type", "Working_Day_Type_Full", "Work_Day_Flag", "Weekend_Day_Flag", "Weekday_No", "Weekday_Name", "Weekday_Short_Name", "Week_Start_112", "Week_End_112", "Fin_Week_No_2_Char", "YearMonth", "YearMonth_YYYYMM", "Year-Month", "Year / Month", "Month_No_2_Char", "Month_Name", "Month_Short_Name", "Month_Start_DateTime", "Month_Start_112", "Month_End_DateTime", "Month_End_112", "MonthYear_MMMM_YYYYY", "Fin_Month_No_2_Char", "Quarter_Name", "Fin_Quarter_No", "Fin_Quarter_Name", "Fin_Quarter_Qq_Fin_Year_YYYY_dash_YY", "Quarter_FinYr", "Fin_Year", "Fin_Year_YYYY_dash_YY", "Fin_Year /", "FinancialYear", "Day_Of_Fin_Year_3_Char", "Calendar_Year", "Day_Of_Year_3_Char", "Month_Day_No_2_Char", "Previous_Day112", "Next_Day_112"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns1",{{"Datekey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

