table 104_day
	lineageTag: ea080d2a-1c9f-4d01-8aff-42d2cc342e93

	column id
		dataType: int64
		formatString: 0
		lineageTag: 4583b0e8-9f49-4577-928e-2d5c20dbafda
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column care
		dataType: string
		lineageTag: 19c0a34b-d1f6-4cb6-b5af-eb1517739db5
		summarizeBy: none
		sourceColumn: care

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column tumour_type
		dataType: string
		lineageTag: f88f91d9-20b8-447f-8a13-af894d95f9b8
		summarizeBy: none
		sourceColumn: tumour_type

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider_code
		dataType: string
		lineageTag: 3c470b38-cc4d-4c22-b774-5e6da84556bf
		summarizeBy: none
		sourceColumn: first_seen_provider_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider
		dataType: string
		lineageTag: b73b022b-c1db-4eb2-b7ff-b0381e214766
		summarizeBy: none
		sourceColumn: first_seen_provider

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider_group
		dataType: string
		lineageTag: 9db496b3-5d23-4fab-81f4-0c2167865fcb
		summarizeBy: none
		sourceColumn: first_seen_provider_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_treatment_provider_code
		dataType: string
		lineageTag: a35087a7-51b1-4ab3-ad13-21844152db38
		summarizeBy: none
		sourceColumn: first_treatment_provider_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_treatment_provider
		dataType: string
		lineageTag: ce62eb90-ff2d-412c-b308-0f38f4531613
		summarizeBy: none
		sourceColumn: first_treatment_provider

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_treatment_provider_group
		dataType: string
		lineageTag: 41d67f83-aebd-47e3-a759-c99fe30df7ed
		summarizeBy: none
		sourceColumn: first_treatment_provider_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column patient_cwt_ref
		dataType: string
		lineageTag: be3bfd0b-13a5-40df-bb27-4f1615a054c5
		summarizeBy: none
		sourceColumn: patient_cwt_ref

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column wait_days
		dataType: int64
		formatString: 0
		lineageTag: d02e783b-0c8f-4b2f-ac22-5f1ca728b907
		summarizeBy: sum
		sourceColumn: wait_days

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column delay_reason_code
		dataType: string
		lineageTag: d29c3fed-bc40-4bc9-8c68-0367cc030894
		summarizeBy: none
		sourceColumn: delay_reason_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column delay_reason
		dataType: string
		lineageTag: 8e51e71b-49de-444e-8751-ba7855b6625d
		summarizeBy: none
		sourceColumn: delay_reason

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column report_number
		dataType: string
		lineageTag: b12b6513-1561-480e-8a92-e86f9eac04d6
		summarizeBy: none
		sourceColumn: report_number

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column report_year
		dataType: string
		lineageTag: 6171bf58-375b-4f0b-82f8-9813cc82b34d
		summarizeBy: none
		sourceColumn: report_year

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column month_name
		dataType: string
		lineageTag: 675f7f5a-d179-4327-a38e-f61618f5dfc0
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column current_status
		dataType: string
		lineageTag: 8f9ae8b2-aa5c-4ae6-ba3d-5c3c41ae552e
		summarizeBy: none
		sourceColumn: current_status

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column report_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8a76ab5d-2fcf-4f7d-9f99-cdded683a3cc
		summarizeBy: none
		sourceColumn: report_date

		variation Variation
			isDefault
			relationship: 3e53cd7e-f403-4ccb-84ff-9136a944a8bd
			defaultHierarchy: LocalDateTable_bf940907-1deb-411b-8c15-3118974efec7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = DateTime#####not a type

	column counter
		dataType: int64
		formatString: 0
		lineageTag: cd3be866-e25e-4498-b512-2eb42e8b0b9e
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column financial_year
		dataType: string
		lineageTag: ab9f7e3d-6e01-4bbd-9ca9-0d280b99c357
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: cf9ec65b-58ed-461c-8744-d4ff7390cced
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	partition 104_day-c436e880-d445-443e-ab47-c6290484e6da = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "Data_Mart_Performance", [Query="select [id]#(lf)      ,[care]#(lf)      ,[tumour_type] [tumour_type]#(lf)      ,[first_seen_provider] [first_seen_provider_code]#(lf)#(tab)  ,[c].[Name] [first_seen_provider]#(lf)#(tab)  ,case when [first_seen_provider] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            else 'Other Provider' end as [first_seen_provider_group]#(lf)      ,[first_treatment_provider] [first_treatment_provider_code]#(lf)#(tab)  ,[d].[Name] [first_treatment_provider]#(lf)#(tab)  ,case when [first_treatment_provider] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            else 'Other Provider' end as [first_treatment_provider_group]#(lf)      ,[patient_cwt_ref]#(lf)      ,[wait_days]#(lf)      ,[delay_reason_code]#(lf)   --#(tab)  ,case when [delay_reason_code] = '01' then 'Clinic cancellation'#(lf)#(tab)  --      when [delay_reason_code] = '02' then 'Out-patient capacity inadequate (i.e. no cancelled clinic, but not enough slots for this Patient)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '03' then 'Administrative delay'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '04' then 'Elective cancellation (for non-medical reason) for treatment in an admitted care setting'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '05' then 'Elective capacity inadequate (Patient unable to be scheduled for treatment within standard time) for treatment in an admitted care setting'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '06' then 'Delay to diagnostic test or treatment planning (Retired 1 July 2012)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '07' then 'Complex diagnostic pathway (many, or complex, diagnostic tests required)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '08' then 'Delay due to referral between Trusts (Retired 1 July 2012)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '10' then 'Treatment delayed for medical reasons (Patient unfit for treatment episode, excluding planned recovery period following diagnostic test) in an admitted care setting'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '11' then 'Diagnosis delayed for medical reasons (Patient unfit for diagnostic episode, excluding planned recovery period following diagnostic test)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '13' then 'Delay due to recovery after an invasive test (Patient DIAGNOSIS or treatment delayed due to planned recovery period following an invasive diagnostic test)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '14' then 'Patient Did Not Attend treatment APPOINTMENT'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '16' then 'Patient Choice (Patient declined or cancelled an offered APPOINTMENT DATE for treatment)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '17' then 'Patient choice delay relating to first Out-Patient Appointment'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '18' then 'Health Care Provider initiated delay to diagnostic test or treatment planning'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '19' then 'Patient initiated (choice) delay to diagnostic test or treatment planning, advance notice given'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '20' then 'Patient Did Not Attend an APPOINTMENT for a diagnostic test or treatment planning event (no advance notice)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '21' then 'Patient failed to present for elective treatment (choice) in an admitted care setting'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '22' then 'Patient care not commissioned by the NHS in England (waiting time standard does not apply) for treatment in an admitted care setting'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '23' then 'Equipment breakdown'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '24' then 'Inconclusive diagnostic result'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '25' then 'Health Care Provider unable to make contact with Patient by telephone'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] = '26'#(tab)then 'Patient choice (Patient declined or cancelled an offered APPOINTMENT DATE for follow up APPOINTMENT)'#(lf)#(tab)#(tab)#(tab)--when [delay_reason_code] in ('97','98','99') then 'Other' else NULL #(lf)#(tab)#(tab)#(tab)--end as [delay_reason]#(lf) ,case when [delay_reason_code] = '01' then 'Clinic cancellation'#(lf)#(tab)        when [delay_reason_code] = '02' then 'Out-patient capacity inadequate'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '03' then 'Administrative delay'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '04' then 'Elective cancellation'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '05' then 'Elective capacity inadequate'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '06' then 'Delay to diagnostic test or treatment planning'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '07' then 'Complex diagnostic pathway'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '08' then 'Delay due to referral between Trusts'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '10' then 'Treatment delayed for medical reasons'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '11' then 'Diagnosis delayed for medical reasons'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '13' then 'Delay due to recovery after an invasive test'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '14' then 'Patient Did Not Attend'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '16' then 'Patient Choice'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '17' then 'Patient Choice'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '18' then 'Health Care Provider initiated delay to diagnostic test or treatment planning'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '19' then 'Patient choice delay to diagnostic test or treatment planning'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '20' then 'Patient Did Not Attend'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '21' then 'Patient failed to present for elective treatment by choice'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '22' then 'Patient care not commissioned by the NHS in England'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '23' then 'Equipment breakdown'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '24' then 'Inconclusive diagnostic result'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '25' then 'Provider unable to make contact with Patient'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] = '26'#(tab)then 'Patient Choice'#(lf)#(tab)#(tab)#(tab)when [delay_reason_code] in ('97','98','99') then 'Other' else NULL #(lf)#(tab)#(tab)#(tab)end as [delay_reason]#(lf)#(lf)#(tab)#(lf)      ,[report_number]#(lf)      ,[report_year]#(lf)      ,LEFT([Report_Month],3) [month_name]#(lf)      ,[current_status]#(lf)      ,[report_date]#(lf)      ,1 as [counter]#(lf)#(tab)  ,b.[FinancialYear] [financial_year]#(lf)#(tab)  ,b.[FinancialMonth] [financial_month]#(lf)  from [Data_Mart_Performance].[dbo].[Cancer_62_Day_Exceptions] [a]#(lf)  left join  [CCG_Reference].[Reference].[vw_DateLookup] [b] on [a].[Report_Date] = [b].[Date]#(lf)  left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [c] on [a].[First_Seen_Provider] = [c].[OrganisationCode]#(lf)  left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [d] on [a].[First_Treatment_Provider] = [d].[OrganisationCode]#(lf)  where [Wait_Days] >= '104'#(lf)  and [Extract_Type] = 'Monthly'#(lf)  and [Report_Date] >= '20190401'#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

