table 28_day
	lineageTag: 82aa9b94-981a-4290-858c-1df5362a81e5

	measure 28_day_performance = (SUM('28_day'[total_patients])-SUM('28_day'[breaches]))/(SUM('28_day'[total_patients]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d877ca7f-871f-4f4a-a028-55c475a7648e

	measure 28_day_target_% = MIN('28_day'[target])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2a39a535-b6e1-4925-8a58-e5215b136946

	measure 28_day_target_checker = IF('28_day'[28_day_performance] >= '28_day'[28_day_target_%], "#63BE7B","#F8696B")
		lineageTag: b9995869-98b7-4c04-888c-594bdda06dff

	column type
		dataType: string
		lineageTag: 594c532a-f422-4f4f-8849-1e0eb1d20693
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider_code
		dataType: string
		lineageTag: 1094e2ef-783c-4a13-92a0-19eca0598c2e
		summarizeBy: none
		sourceColumn: first_seen_provider_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider
		dataType: string
		lineageTag: 796e8d38-0bc4-42e2-a17d-e90fc684e259
		summarizeBy: none
		sourceColumn: first_seen_provider

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider_group
		dataType: string
		lineageTag: 2b25499d-90a9-4153-b5ac-8faf292b219f
		summarizeBy: none
		sourceColumn: first_seen_provider_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column tumour_type
		dataType: string
		lineageTag: fca5ac96-8683-4205-9a46-8ba747e481c7
		summarizeBy: none
		sourceColumn: tumour_type

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column tumour_group
		dataType: string
		lineageTag: bef4e5dd-111a-4623-9cc6-1c16bc4c5ce6
		summarizeBy: none
		sourceColumn: tumour_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column total_patients
		dataType: int64
		formatString: 0
		lineageTag: 4704a28a-1d19-49b9-8d1a-ff39e628e2b9
		summarizeBy: sum
		sourceColumn: total_patients

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column breaches
		dataType: int64
		formatString: 0
		lineageTag: bcae514c-abcb-4a78-a461-1299d4433914
		summarizeBy: sum
		sourceColumn: breaches

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column report_number
		dataType: string
		lineageTag: 78120b30-37d5-47aa-a2b9-7f04be5d982c
		summarizeBy: none
		sourceColumn: report_number

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column report_name
		dataType: string
		lineageTag: 722e6b69-c8f1-4214-8b61-160e3c5f0eac
		summarizeBy: none
		sourceColumn: report_name

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column financial_year
		dataType: string
		lineageTag: 0b5508d0-212b-49d3-b346-3118253334fe
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column month_name
		dataType: string
		lineageTag: 89615424-65cb-48cb-87b1-a406419ff8d6
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 4c8bd5e3-44e3-49f9-9ffe-b320dd88f923
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column target
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: b7a3cf21-1aae-4b6a-82c1-190c2de705bc
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Double#####not a type

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: b7f57bf0-ac6c-4ccd-b637-f504cdd32650
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	partition 28_day-92290be5-127e-4b9f-aaea-a197920d107b = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "Data_Mart_Performance", [Query="-----------------------#(lf)--- 28 DAY STANDARD ---#(lf)-----------------------#(lf)#(lf)select [type] = '28 Day'#(lf)      ,[first_seen_provider] [first_seen_provider_code]#(lf)#(tab)  ,[c].[name] [first_seen_provider]#(lf)#(tab)  ,case when [First_Seen_Provider] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            else 'Other Provider' end as [first_seen_provider_group]#(lf)      ,[Urgent_Suspected_Cancer_Type] [tumour_type]#(lf)#(tab)  ,case when [Urgent_Suspected_Cancer_Type] = 'acute leukaemia' then 'Suspected Acute Leukaemia'#(lf)#(tab)        when [Urgent_Suspected_Cancer_Type] like '%brain%' then 'Suspected Brain / Central Nervous System'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%cancer not initially suspected%' then 'Non-Cancer Breast Symptoms'#(lf)#(tab)#(tab)    when [Urgent_Suspected_Cancer_Type] like '%breast%' then 'Suspected Breast'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%children%' then 'Suspected Childrens Cancer'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%gynaecological%' then 'Suspected Gynaecological'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%Suspected haematological malignancies excluding acute leukaemia%' then 'Suspected Haematological Malignancies'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%Head and Neck%' then 'Suspected Head and Neck'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%lower gastrointestinal%' then 'Suspected Lower Gastrointestinal'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%lung%' then 'Suspected Lung'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%other%' then 'Suspected Other'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%sarcoma%' then 'Suspected Sarcoma'#(tab)   #(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%skin%' then 'Suspected Skin'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%suspected testicular%' then 'Suspected Testicular'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%upper gastrointestinal%' then 'Suspected Upper Gastrointestinal'#(lf)#(tab)#(tab)#(tab)when [Urgent_Suspected_Cancer_Type] like '%Suspected urological cancers (excluding testicular)%' then 'Suspected Urological'#(lf)#(tab)#(tab)#(tab)else 'Unknown' end as [tumour_group]#(lf)#(tab)  ,[No_Of_Patients] [total_patients]#(lf)#(tab)  ,[breaches] = ([Days_29_To_38]+[Days_39_To_62]+[Days_63_And_More])#(lf)      ,[report_number]#(lf)      ,case when [report_number] = '18.1' then '18.1 28 Day Two Week Wait'#(lf)#(tab)        when [report_number] = '18.2' then '18.2 28 Day Two Week Wait Non-Cancer Breast Symptoms'#(lf)#(tab)#(tab)#(tab)when [report_number] = '18.3' then '18.3 28 Day Screening'#(lf)#(tab)#(tab)#(tab)else 'error' end as [report_name]#(lf)#(tab)  ,[target] = 0.75#(lf)#(tab)  ,[d].[FinancialYear] [financial_year]#(lf)      ,LEFT([Report_Month],3) as [month_name]#(lf)#(tab)  ,[d].[FinancialMonth] [financial_month]#(lf)#(tab)  ,[d].[YearMonth] [year_month]#(lf)#(lf)#(lf)  from [Data_Mart_Performance].[dbo].[Cancer_28_Day_Aggregate_Data] [a]#(lf)  left join  [CCG_Reference].[Reference].[vw_DateLookup] [d] on [a].[Report_Date] = [d].[Date]#(lf)  left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [c] on [a].[First_Seen_Provider] = [c].[OrganisationCode]#(lf)  where [Report_Date] > '20190331'#(lf)  and [Extract_Type] = 'Monthly'"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}, {"year_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

