table 62_day
	lineageTag: 66b40863-174c-408b-9fbd-f3adaaa1216a

	measure 62_day_performance = (SUM('62_day'[total_treated])-SUM('62_day'[breaches]))/SUM('62_day'[total_treated])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 54704af9-0542-4876-b628-a2dc71342a7e

	measure 62_day_target_% = MIN('62_day'[target])
		lineageTag: 4ab9bdff-21ea-47bc-a01c-29396ba41b52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 62_day_target_checker = IF('62_day'[62_day_performance]>= '62_day'[62_day_target_%], "#63BE7B","#F8696B")
		lineageTag: 829d8292-280c-4414-bbec-fe5ac8099527

	column standard_group
		dataType: string
		lineageTag: c967cffa-a650-4257-b5e8-bdca13194beb
		summarizeBy: none
		sourceColumn: standard_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider_code
		dataType: string
		lineageTag: 2046821b-5264-4f93-808e-731011bdae86
		summarizeBy: none
		sourceColumn: first_seen_provider_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider
		dataType: string
		lineageTag: 79a58d41-6a50-4627-b3c7-cc37f9370721
		summarizeBy: none
		sourceColumn: first_seen_provider

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_seen_provider_group
		dataType: string
		lineageTag: 7c0f5766-8b11-4ff5-9d53-b18b98622585
		summarizeBy: none
		sourceColumn: first_seen_provider_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_treatment_provider_code
		dataType: string
		lineageTag: 6aa3c1da-0780-4bb4-88c5-f6804583e03e
		summarizeBy: none
		sourceColumn: first_treatment_provider_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_treatment_provider
		dataType: string
		lineageTag: c76e0fcb-d5df-44dd-97ab-47c958f2a7ad
		summarizeBy: none
		sourceColumn: first_treatment_provider

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column first_treatment_provider_group
		dataType: string
		lineageTag: 676aae85-94a8-4800-a457-b64cf46ceb8e
		summarizeBy: none
		sourceColumn: first_treatment_provider_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column consultant_upgrade_provider_code
		dataType: string
		lineageTag: bbe0ac68-269d-48bd-9264-5b51306f752d
		summarizeBy: none
		sourceColumn: consultant_upgrade_provider_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column consultant_upgrade_provider
		dataType: string
		lineageTag: b85e2f25-fcc9-4e3c-a939-04d4cf5f9e1d
		summarizeBy: none
		sourceColumn: consultant_upgrade_provider

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column consultant_upgrade_provider_group
		dataType: string
		lineageTag: 63f6d40a-8445-4ded-92b6-2f82e437d649
		summarizeBy: none
		sourceColumn: consultant_upgrade_provider_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column tumour_type
		dataType: string
		lineageTag: f12d779c-6ba5-4d42-af9d-e07c45158f68
		summarizeBy: none
		sourceColumn: tumour_type

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column total_treated
		dataType: int64
		formatString: 0
		lineageTag: e602a06d-f051-46ad-8bc9-9f65b1ecec03
		summarizeBy: sum
		sourceColumn: total_treated

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column breaches
		dataType: int64
		formatString: 0
		lineageTag: 1882846e-2d89-4fb5-88cc-b09f170bf2af
		summarizeBy: sum
		sourceColumn: breaches

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column target
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 238a2bb0-05be-4dd7-abe2-92d826a4e11f
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Double#####not a type

	column performance
		dataType: double
		lineageTag: e5ef3d30-5748-4356-a59a-2f93c814922d
		summarizeBy: sum
		sourceColumn: performance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation DataTypeAtRefresh = Double#####not a type

	column report_number
		dataType: string
		lineageTag: 4029a7e5-7135-4516-bd7b-cef538eca6ca
		summarizeBy: none
		sourceColumn: report_number

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column report_name
		dataType: string
		lineageTag: 46f6c41b-003e-43e8-b2c8-749e1d70f37b
		summarizeBy: none
		sourceColumn: report_name

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column financial_year
		dataType: string
		lineageTag: a2268285-d39d-457b-a702-1f1b82aac337
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column month_name
		dataType: string
		lineageTag: 2d777769-cb92-4c5d-bd7a-3325452347f5
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 4fb4fa3f-2d95-497e-b87e-50f4fc705cee
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	partition 62_day-f567a7fa-04f3-4d45-8cad-aab1b316e2bf = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "Data_Mart_Performance", [Query="-----------------------#(lf)--- 62 DAY STANDARD ---#(lf)-----------------------#(lf)#(lf)select [standard_group] = '62 Day'#(lf)      ,[first_seen_provider] [first_seen_provider_code]#(lf)#(tab)  ,[c].[Name] [first_seen_provider]#(lf)#(tab)  ,case when [First_Seen_Provider] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            else 'Other Provider' end as [first_seen_provider_group]#(lf)      ,[first_treatment_provider] [first_treatment_provider_code]#(lf)#(tab)  ,[e].[name] [first_treatment_provider]#(lf)#(tab)  ,case when [First_Treatment_Provider] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            else 'Other Provider' end as [first_treatment_provider_group]#(lf)      ,[consultant_upgrade_provider_code] = NULL#(tab) #(lf)      ,[consultant_upgrade_provider] = NULL#(tab)  #(lf)#(tab)  ,[consultant_upgrade_provider_group] = null#(lf)      ,[tumour_type] #(lf)      ,[Actual_Total_Treated] [total_treated]#(lf)#(tab)  ,[Total_Over_Target_Accountable_Provider_62_Day_Wait] [breaches] #(lf)#(tab)  ,case when [Report_Number] = '8.4' then '0.85'#(lf)#(tab)        when [Report_Number] = '9.4' then '0.90'#(lf)#(tab)        when [Report_Number] = '8.8' then 'Unknown'#(lf)#(tab)#(tab)#(tab)else 'error' end as [target]#(lf)      ,[%_Meeting_Standard] [performance]#(lf)      ,[Report_Number] [report_number]#(lf)#(tab)  ,case when [Report_Number] = '8.4' then '8.4 - 62 Day Wait'#(lf)#(tab)        when [Report_Number] = '9.4' then '9.4 - 62 Day Screening '#(lf)#(tab)        when [Report_Number] = '8.8' then '8.8 - 31 Day Rare Cancer '#(lf)#(tab)#(tab)#(tab)else 'error' end as [report_name]#(lf)#(tab)  ,[d].[FinancialYear] [financial_year]#(lf)      ,left([Report_Month],3) as [month_name]#(lf) #(tab)  ,[d].[FinancialMonth] [financial_month]#(lf)  #(lf)  from [Data_Mart_Performance].[dbo].[Cancer_62_Day_Aggregate_Data] [a]#(lf)  left join [CCG_Reference].[Reference].[vw_DateLookup] [d] on [a].[Report_Date] = [d].[Date]#(lf)  left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [c] on [a].[First_Seen_Provider] = [c].[OrganisationCode]#(lf)  left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [e] on [a].[First_Treatment_Provider] = [e].[OrganisationCode]#(lf)  where [Report_Date] > '20190331'#(lf)  and [Extract_Type] = 'Monthly'#(lf) #(lf) union all#(lf)#(lf)-------------------------------#(lf)--- 62 DAY UPGRADE STANDARD ---#(lf)-------------------------------#(lf)#(lf)select [standard_group] = '62 Day Upgrade'#(lf)      ,[first_seen_provider_code] = NULL#(lf)#(tab)  ,[first_seen_provider] = NULL#(lf)#(tab)  ,[first_seen_provider_group] = NULL#(lf)      ,[First_Treatment_Provider] [first_treatment_provider_code]#(lf)#(tab)  ,[c].[name] [first_treatment_provider]#(lf)#(tab)  ,case when [First_Treatment_Provider] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            else 'Other Provider' end as [first_treatment_provider_group]#(lf)      ,[consultant_upgrade_provider] [consultant_upgrade_provider_code]#(lf)#(tab)  ,[e].[name] [consultant_upgrade_provider]#(lf)#(tab)  ,case when [Consultant_Upgrade_Provider] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            else 'Other Provider' end as [consultant_upgrade_provider_group]#(lf)      ,[Tumour_Type] [Tumour Type]#(lf)      ,[Actual_Total_Treated] [Total Treated]#(lf)#(tab)  ,[Total_Over_Target_Accountable_Provider_62_Day_Wait] [breaches] #(lf)#(tab)  ,case when [Report_Number] = '10.4' then '0.85'#(lf)#(tab)#(tab)#(tab)else 'error' end as [target]#(lf)      ,[%_Meeting_Standard] [performance]#(lf)      ,[Report_Number] [report_number]#(lf)#(tab)  ,case when [Report_Number] = '10.4' then '10.4 - 62 Day Upgrade'#(lf)#(tab)#(tab)#(tab)else 'error' end as [report_name]#(lf)#(tab)  ,[d].[FinancialYear] [financial_year]#(lf)      ,left([Report_Month],3) as [month_name]#(lf) #(tab)  ,[d].[FinancialMonth] [financial_month]#(lf) #(lf)  from [Data_Mart_Performance].[dbo].[Cancer_62_Day_Upgrade_Aggregate_Data] [A]#(lf)  left join [CCG_Reference].[Reference].[vw_DateLookup] [d] on [a].[Report_Date] = [d].[Date]#(lf)  left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [c] on [a].[First_Treatment_Provider] = [c].[OrganisationCode]#(lf)  left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [e] on [a].[Consultant_Upgrade_Provider] = [e].[OrganisationCode]#(lf)  where [Report_Date] > '20190331'#(lf)  and [Extract_Type] = 'Monthly'"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}, {"target", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

