table two_week_wait
	lineageTag: be82239b-e498-49b4-84e4-696f3d7ce249

	measure two_week_wait_performance = (SUM('two_week_wait'[total_referrals])-SUM('two_week_wait'[breaches]))/SUM('two_week_wait'[total_referrals])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b0c1e4e6-ef15-481d-bf4e-979d5e0a705f

	measure 2ww_target = MIN('two_week_wait'[target])
		formatString: 0%;-0%;0%
		lineageTag: f3a66939-f23e-4164-af60-b345928663a8

	measure 2ww_target_checker = IF('two_week_wait'[two_week_wait_performance] >= 'two_week_wait'[2ww_target], "#63BE7B","#F8696B")
		lineageTag: 4c03aef3-0e76-4911-8f57-338196002624

	measure Testing = SUM('two_week_wait'[total_referrals])
		formatString: 0
		lineageTag: 9ce8449f-5238-4970-b9a1-d76019654b37

	measure 'Testing Breaches' = SUM('two_week_wait'[breaches])
		formatString: 0
		lineageTag: 8212cb04-3835-43c1-9d84-3beb7e2697bf

	column type
		dataType: string
		lineageTag: 82b25783-3110-49a0-b2f0-921006530fa5
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column report_date
		dataType: dateTime
		formatString: dd mmmm yyyy
		lineageTag: 7860c9a3-24b6-4f6e-9025-4a26df8d859c
		summarizeBy: none
		sourceColumn: report_date

		variation Variation
			isDefault
			relationship: cbcc0ec0-8c7b-447f-b03f-17e3ddeeb6fc
			defaultHierarchy: LocalDateTable_2a6daa77-edc1-42ad-98b8-99f1e7eab037.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation DataTypeAtRefresh = DateTime#####Date

	column provider_code
		dataType: string
		lineageTag: 71338bb7-35de-479c-ad6c-e8c4141a8359
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column provider_name
		dataType: string
		lineageTag: 2e3fb6b4-02c2-4c41-950d-c6efb8820a92
		summarizeBy: none
		sourceColumn: provider_name

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column provider_group
		dataType: string
		lineageTag: a09c32f5-60b8-408f-ba0b-d4b536fcb606
		summarizeBy: none
		sourceColumn: provider_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column tumour_type
		dataType: string
		lineageTag: efda79ae-5dcb-405f-9741-49dd5b171ca9
		summarizeBy: none
		sourceColumn: tumour_type

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column tumour_group
		dataType: string
		lineageTag: 0e9ccc85-3f77-4212-8d27-c6a47af083ae
		summarizeBy: none
		sourceColumn: tumour_group

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column total_referrals
		dataType: int64
		formatString: 0
		lineageTag: c3b0ccd5-ea2d-4a52-8773-85e66808077e
		summarizeBy: sum
		sourceColumn: total_referrals

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column breaches
		dataType: int64
		formatString: 0
		lineageTag: 159b9317-78fe-459e-a003-b7a950239a11
		summarizeBy: sum
		sourceColumn: breaches

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column target
		dataType: double
		lineageTag: cc5da702-134c-4ca1-921a-38571725c935
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation DataTypeAtRefresh = Double#####not a type

	column performance
		dataType: int64
		formatString: 0
		lineageTag: 59dea804-5632-4f91-96fc-a380cd2c09a9
		summarizeBy: sum
		sourceColumn: performance

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	column report_number
		dataType: string
		lineageTag: 9d140f36-c4cf-45fd-bb05-1f70a90c855c
		summarizeBy: none
		sourceColumn: report_number

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column Report_name
		dataType: string
		lineageTag: 1ac9c34a-51cf-408f-916c-afedd2e46b05
		summarizeBy: none
		sourceColumn: Report_name

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column financial_year
		dataType: string
		lineageTag: 615f9661-59f7-40f7-b718-ae42e2328ca0
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column month
		dataType: string
		lineageTag: 759bd0a8-8381-49c0-ba17-8601008021dc
		summarizeBy: none
		sourceColumn: month
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = String#####not a type

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 83dd9032-6862-4850-a721-7b9f0e9849e7
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Int64#####not a type

	partition two_week_wait-fd7a2bcd-56fd-4454-8922-7a5cec6f62c5 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "Data_Mart_Performance", [Query="------------------------------#(lf)--- two week wait standard ---#(lf)------------------------------#(lf)#(lf)select #(lf)[type] = '2WW',#(lf)[report_date] = [Report_Date], #(lf)[provider_code] = [Provider_Code],#(lf)[provider_name] = case when [Provider_Code] = 'RBA' then 'Somerset NHS Foundation Trust' #(lf)                       when [Provider_Code] = 'RQ6' then 'Liverpool University Hospitals NHS Foundation Trust' #(lf)                       else [p].[name] end,#(lf)[provider_group] = case when [Provider_Code] = 'RTE' then 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)                        else 'Other Provider' end,#(lf)[tumour_type] = [Tumour_Type],#(lf)[tumour_group] = case when [Tumour_Type] = 'acute leukaemia' then 'Suspected Acute Leukaemia'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%brain%' then 'Suspected Brain / Central Nervous System'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%cancer not initially suspected%' then 'Non-Cancer Breast Symptoms'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%breast%' then 'Suspected Breast'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%children%' then 'Suspected Childrens Cancer'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%gynaecological%' then 'Suspected Gynaecological'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%Suspected haematological malignancies excluding acute leukaemia%' then 'Suspected Haematological Malignancies'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%Head and Neck%' then 'Suspected Head and Neck'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%lower gastrointestinal%' then 'Suspected Lower Gastrointestinal'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%lung%' then 'Suspected Lung'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%other%' then 'Suspected Other'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%sarcoma%' then 'Suspected Sarcoma'#(tab)   #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%skin%' then 'Suspected Skin'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%suspected testicular%' then 'Suspected Testicular'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%upper gastrointestinal%' then 'Suspected Upper Gastrointestinal'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  when [Tumour_Type] LIKE '%Suspected urological cancers (excluding testicular)%' THEN 'Suspected Urological'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  else 'ERROR' end,#(lf)[total_referrals] = [Total_Referrals_Seen_During_The_Period],#(lf)[breaches] = ([Seen_15_To_16_Days]+[Seen_17_To_21_Days]+[Seen_22_To_28_Days]+[Seen_After_28_Days]),#(lf)[target] = '93%',#(lf)[performance] = [%_Meeting_Standard] ,#(lf)[report_number] = [Report_Number],#(lf)[Report_name] = case when [Report_Number] = '6.3' then '6.3 - Two Week Wait'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) when [Report_Number] = '6.4' then '6.4 - Breast Symptom Two Week Wait'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) else 'ERROR' end,#(lf)[financial_year] = [d].[FinancialYear], #(lf)[month] = left([Report_Month],3),#(lf)[financial_month] = [d].[FinancialMonth] #(lf)#(lf)from [Data_Mart_Performance].[dbo].[Cancer_2_Week_Aggregate_Data] [a]#(lf)left join [CCG_Reference].[Reference].[vw_DateLookup] [d] on [a].[Report_Date] = [d].[Date]#(lf)left join [CCG_Reference].[Reference].[vw_OrganisationTrust] [p] on [a].[Provider_Code] = [p].[organisationcode]#(lf)where [Report_Date] > '20190331'#(lf)and [Extract_Type] = 'Monthly'#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"report_date", type date}, {"target", Percentage.Type}, {"performance", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

