table Births
	lineageTag: 355420b1-7336-4083-a335-ba20a6fe92e9

	column UniqPregID
		dataType: string
		lineageTag: ed61d72e-e173-43de-859b-9ad8dca4d9c5
		summarizeBy: none
		sourceColumn: UniqPregID

		annotation SummarizationSetBy = Automatic

	column NHS_No_Mother
		dataType: string
		lineageTag: 6b547717-0149-4c8b-9e5e-8f285a6d4d92
		summarizeBy: none
		sourceColumn: NHS_No_Mother

		annotation SummarizationSetBy = Automatic

	column EthnicCategoryMother
		dataType: string
		lineageTag: 2b27faca-a926-4991-8a50-cee78f167246
		summarizeBy: none
		sourceColumn: EthnicCategoryMother

		annotation SummarizationSetBy = Automatic

	column EthnicCategoryMotherDescription
		dataType: string
		lineageTag: 907d40c6-022d-49f7-ad4c-ed6fa657e1b7
		summarizeBy: none
		sourceColumn: EthnicCategoryMotherDescription

		annotation SummarizationSetBy = Automatic

	column MSD401_ID
		dataType: string
		lineageTag: 9ebb658b-4bb2-4ee3-941b-6aafd87d70a5
		summarizeBy: none
		sourceColumn: MSD401_ID

		annotation SummarizationSetBy = Automatic

	column NHS_Number_Baby
		dataType: string
		lineageTag: d6966c8a-9e85-412f-a5ad-92ad9160c53a
		summarizeBy: none
		sourceColumn: NHS_Number_Baby

		annotation SummarizationSetBy = Automatic

	column Org_Provider_Code
		dataType: string
		lineageTag: 51228420-9a8f-4188-9e0e-1baa91935f74
		summarizeBy: none
		sourceColumn: Org_Provider_Code

		annotation SummarizationSetBy = Automatic

	column Org_Provider_Desc
		dataType: string
		lineageTag: 11b1052a-00c6-4377-82dc-2f905297e34b
		summarizeBy: none
		sourceColumn: Org_Provider_Desc

		annotation SummarizationSetBy = Automatic

	column MSDS_ID_Baby
		dataType: string
		lineageTag: 90b8e61b-76a8-4bb2-a3e4-b995b6fad969
		summarizeBy: none
		sourceColumn: MSDS_ID_Baby

		annotation SummarizationSetBy = Automatic

	column MSDS_ID_Mother
		dataType: string
		lineageTag: 5dd77e09-ca87-4177-b496-91a478deae94
		summarizeBy: none
		sourceColumn: MSDS_ID_Mother

		annotation SummarizationSetBy = Automatic

	column Org_Local_Patient_Baby_Code
		dataType: string
		lineageTag: 23ae0cb3-eccf-4f25-a9d6-ec3510815ec3
		summarizeBy: none
		sourceColumn: Org_Local_Patient_Baby_Code

		annotation SummarizationSetBy = Automatic

	column Birth_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 500ca8b2-855d-461c-aaf5-0aad1a8ce67c
		summarizeBy: none
		sourceColumn: Birth_Date

		annotation SummarizationSetBy = Automatic

	column Birth_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 96a19746-f0fa-481f-a303-6376e4430b06
		summarizeBy: none
		sourceColumn: Birth_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column FinYr_Birth_Date
		dataType: string
		lineageTag: c20c4eb7-fca4-4a6b-8ce2-5c27b64d1894
		summarizeBy: none
		sourceColumn: FinYr_Birth_Date

		annotation SummarizationSetBy = Automatic

	column YearMonth_Birth_Date
		dataType: string
		lineageTag: b27256bb-d9e8-4226-a258-005b77ae8a79
		summarizeBy: none
		sourceColumn: YearMonth_Birth_Date

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Outcome_Code
		dataType: string
		lineageTag: 322b0656-7937-4c53-b152-a7f29641efd8
		summarizeBy: none
		sourceColumn: Pregnancy_Outcome_Code

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Outcome_Desc
		dataType: string
		lineageTag: a2ae9296-d3a3-4a06-b744-883681ed418a
		summarizeBy: none
		sourceColumn: Pregnancy_Outcome_Desc

		annotation SummarizationSetBy = Automatic

	column Sex_Baby_Code
		dataType: string
		lineageTag: c99be9da-94d2-4a9f-b95c-e252176a32c2
		summarizeBy: none
		sourceColumn: Sex_Baby_Code

		annotation SummarizationSetBy = Automatic

	column Sex_Baby_Desc
		dataType: string
		lineageTag: 3c68bdfe-230c-47de-951f-5b9547d668b3
		summarizeBy: none
		sourceColumn: Sex_Baby_Desc

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category_Baby_Code
		dataType: string
		lineageTag: 717e3bc6-6d9f-416b-b37d-2262fd2e43a0
		summarizeBy: none
		sourceColumn: Ethnic_Category_Baby_Code

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category_Baby_Desc
		dataType: string
		lineageTag: 1200b76c-5927-46bd-b396-e0c2377e90b0
		summarizeBy: none
		sourceColumn: Ethnic_Category_Baby_Desc

		annotation SummarizationSetBy = Automatic

	column Birth_order
		dataType: int64
		formatString: 0
		lineageTag: 5a0b01f6-21d5-47d9-9273-d71e50a3bc00
		summarizeBy: sum
		sourceColumn: Birth_order

		annotation SummarizationSetBy = Automatic

	column Death_Date_Baby
		dataType: dateTime
		formatString: General Date
		lineageTag: 2fe480eb-12af-49ee-99f8-9dcefa4317b5
		summarizeBy: none
		sourceColumn: Death_Date_Baby

		variation Variation
			isDefault
			relationship: 56a88773-69a9-459d-b2d4-06fd1b6fb133
			defaultHierarchy: LocalDateTable_df3c10cb-ce68-4245-9e52-01d2d1a3b88a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Death_Time_Baby
		dataType: dateTime
		formatString: Long Time
		lineageTag: a3a28f27-5c72-4e9f-80be-fe9f957a7aca
		summarizeBy: none
		sourceColumn: Death_Time_Baby

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Presentation_Code
		dataType: string
		lineageTag: 32e07fcd-ffae-413b-b7f1-ed171516aa1b
		summarizeBy: none
		sourceColumn: Presentation_Code

		annotation SummarizationSetBy = Automatic

	column Presentation_Desc
		dataType: string
		lineageTag: 6106d47b-a485-47e6-9710-21a3ba4ab7d8
		summarizeBy: none
		sourceColumn: Presentation_Desc

		annotation SummarizationSetBy = Automatic

	column Gestation_Length
		dataType: int64
		formatString: 0
		lineageTag: 2c18002f-0dfe-4a64-ad36-2de35573d159
		summarizeBy: sum
		sourceColumn: Gestation_Length

		annotation SummarizationSetBy = Automatic

	column Delivery_Method_Code
		dataType: string
		lineageTag: 97453bb8-e01a-433a-ae9e-25ba770595b5
		summarizeBy: none
		sourceColumn: Delivery_Method_Code

		annotation SummarizationSetBy = Automatic

	column Delivery_Method_Description
		dataType: string
		lineageTag: c61b6be3-5292-4e9c-9c88-da6ad50b7177
		summarizeBy: none
		sourceColumn: Delivery_Method_Description

		annotation SummarizationSetBy = Automatic

	column WaterDeliveryInd
		dataType: string
		lineageTag: 7002e2ac-dd9e-4f2d-9747-a3d37f46f1f2
		summarizeBy: none
		sourceColumn: WaterDeliveryInd

		annotation SummarizationSetBy = Automatic

	column Water_Delivery_Indicator
		dataType: string
		lineageTag: b9b70ff9-d32b-4234-a36b-4bff5b3a40c9
		summarizeBy: none
		sourceColumn: Water_Delivery_Indicator

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Code
		dataType: string
		lineageTag: 17a5c45b-7e92-49c5-9274-b667948e7404
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Code

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Desc
		dataType: string
		lineageTag: 8034a2a3-7737-49a7-b86a-bbca29e4fab8
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Desc

		annotation SummarizationSetBy = Automatic

	column Setting_Place_Birth_Code
		dataType: string
		lineageTag: f28e57d3-d939-430a-be37-51b5e4e4d516
		summarizeBy: none
		sourceColumn: Setting_Place_Birth_Code

		annotation SummarizationSetBy = Automatic

	column Setting_Place_Birth_Desc
		dataType: string
		lineageTag: d5e1c3f2-3198-4b9e-a40d-7d29effabc86
		summarizeBy: none
		sourceColumn: Setting_Place_Birth_Desc

		annotation SummarizationSetBy = Automatic

	column Baby_First_Feed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9022f949-420f-4e0c-8add-2c0446f8c8df
		summarizeBy: none
		sourceColumn: Baby_First_Feed_Date

		variation Variation
			isDefault
			relationship: 13b652d0-9d88-4d36-bf5c-38dbe25bfd2b
			defaultHierarchy: LocalDateTable_76a5f4bd-37ef-4c32-ab4e-e4a117d82b4b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Baby_First_Feed_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: b5685bbe-3e31-498c-a107-77578023ecf1
		summarizeBy: none
		sourceColumn: Baby_First_Feed_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Baby_First_Feed_Type_Code
		dataType: int64
		formatString: 0
		lineageTag: 910c673f-7458-4850-ac09-3c295b95e3dc
		summarizeBy: count
		sourceColumn: Baby_First_Feed_Type_Code

		annotation SummarizationSetBy = Automatic

	column Baby_First_Feed_Type_Desc
		dataType: string
		lineageTag: 74e8857c-c95e-415e-ad8b-e388f7a3a4ed
		summarizeBy: none
		sourceColumn: Baby_First_Feed_Type_Desc

		annotation SummarizationSetBy = Automatic

	column Skin_to_Skin_Contact_1hr_Indicator
		dataType: string
		lineageTag: 53dc2140-e5ec-45ca-bfb1-4b2dfd6edf5f
		summarizeBy: none
		sourceColumn: Skin_to_Skin_Contact_1hr_Indicator

		annotation SummarizationSetBy = Automatic

	column Discharge_Date_Baby
		dataType: dateTime
		formatString: General Date
		lineageTag: 5f937c5f-867e-4723-9234-6da5ce171489
		summarizeBy: none
		sourceColumn: Discharge_Date_Baby

		variation Variation
			isDefault
			relationship: 5d8c9999-327e-49ec-a659-55e5d46fa927
			defaultHierarchy: LocalDateTable_53fe4899-43da-4f18-8261-c97c1e7bb8cc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Discharge_Time_Baby
		dataType: dateTime
		formatString: Long Time
		lineageTag: e01ae0b5-1184-4efd-b515-87a133127768
		summarizeBy: none
		sourceColumn: Discharge_Time_Baby

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Labour_Delivery_ID
		dataType: string
		lineageTag: de65df5c-50c1-4f06-b6a5-239670e98a00
		summarizeBy: none
		sourceColumn: Labour_Delivery_ID

		annotation SummarizationSetBy = Automatic

	column Care_Prof_ID_Delivery
		dataType: string
		lineageTag: a5752e9e-efcc-4f2f-bd41-928a59f92e45
		summarizeBy: none
		sourceColumn: Care_Prof_ID_Delivery

		annotation SummarizationSetBy = Automatic

	column Birth_Day_of_Week_Baby
		dataType: string
		lineageTag: f6ca7106-47bf-48f1-90ad-3ee591827c7d
		summarizeBy: none
		sourceColumn: Birth_Day_of_Week_Baby

		annotation SummarizationSetBy = Automatic

	column Meridian_of_Birth_Baby
		dataType: int64
		formatString: 0
		lineageTag: ded4c899-150f-452a-98bc-27be1c81262b
		summarizeBy: sum
		sourceColumn: Meridian_of_Birth_Baby

		annotation SummarizationSetBy = Automatic

	column Age_At_Birth_Mother
		dataType: int64
		formatString: 0
		lineageTag: 11617cf5-41bc-4091-896f-fd24af3c3ef5
		summarizeBy: sum
		sourceColumn: Age_At_Birth_Mother

		annotation SummarizationSetBy = Automatic

	column Age_at_Death_Baby
		dataType: int64
		formatString: 0
		lineageTag: f65fa848-5b52-4ee9-b301-50d75ccbcb13
		summarizeBy: sum
		sourceColumn: Age_at_Death_Baby

		annotation SummarizationSetBy = Automatic

	column Year_of_Death_Baby
		dataType: int64
		formatString: 0
		lineageTag: 37e1ceff-14ea-4b31-bf7a-d97203e47e77
		summarizeBy: sum
		sourceColumn: Year_of_Death_Baby

		annotation SummarizationSetBy = Automatic

	column Month_of_Death_Baby
		dataType: string
		lineageTag: 0fa881af-c60f-49aa-801a-0b302bc4e9c6
		summarizeBy: none
		sourceColumn: Month_of_Death_Baby

		annotation SummarizationSetBy = Automatic

	column Day_of_Death_Baby
		dataType: string
		lineageTag: 75f2ea5b-84dc-4031-acd9-1a1b47147e62
		summarizeBy: none
		sourceColumn: Day_of_Death_Baby

		annotation SummarizationSetBy = Automatic

	column MeridianOfDeathBaby
		dataType: int64
		formatString: 0
		lineageTag: c8065edb-53c5-43a3-943d-8fd94d0dbf38
		summarizeBy: sum
		sourceColumn: MeridianOfDeathBaby

		annotation SummarizationSetBy = Automatic

	column Year_of_Birth_Baby
		dataType: int64
		formatString: 0
		lineageTag: fe16aaf0-5b6d-480a-87a2-b9e9b9d73c44
		summarizeBy: sum
		sourceColumn: Year_of_Birth_Baby

		annotation SummarizationSetBy = Automatic

	column Month_of_Birth_Baby
		dataType: int64
		formatString: 0
		lineageTag: 2862f815-db41-4769-935a-faa1894dcbda
		summarizeBy: sum
		sourceColumn: Month_of_Birth_Baby

		annotation SummarizationSetBy = Automatic

	column Report_Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: eab26d5a-fb07-45e5-b3cc-1b38be40442a
		summarizeBy: none
		sourceColumn: Report_Start_Date

		variation Variation
			isDefault
			relationship: 9a977846-d79f-43c5-bca4-4f77cd4e8090
			defaultHierarchy: LocalDateTable_e39be0dd-ddfb-499e-a409-de7db5d7e18c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Report_End_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 10752e21-9583-402c-9032-10b6be10fa13
		summarizeBy: none
		sourceColumn: Report_End_Date

		variation Variation
			isDefault
			relationship: a73d66c3-f6d9-4035-9d79-9e41ce3b8c6d
			defaultHierarchy: LocalDateTable_7b765af5-de75-4a0f-abea-3e99d9193923.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Processed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b523be7-7ff0-4243-942b-bf1eb9d2b24e
		summarizeBy: none
		sourceColumn: Processed_Date

		variation Variation
			isDefault
			relationship: 44f7112f-32cd-409a-979d-77a6684109ae
			defaultHierarchy: LocalDateTable_a9d397a7-3f38-4f6c-9886-d16088f19485.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d2ca35e-9762-4894-a59e-1e3fb12f318b
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: 741af84f-dda5-4598-95af-aec04cea8e52
			defaultHierarchy: LocalDateTable_08acdf8f-a878-440d-b013-64788f2d8dee.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: #,0
		lineageTag: aac4a1df-76e4-4eae-9edc-97dc1ea27814
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Month_Year_BirthMonth = Births[YearMonth_Birth_Date]
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 566286f3-3efa-4980-9a0f-02637bdf8343
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e602c6ce-0abe-4de8-81ec-d1e987744da2
			defaultHierarchy: LocalDateTable_9de51cfa-dd7f-4241-ad86-0900cb26fe6b.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Gestation_Length_Weeks
		dataType: int64
		formatString: 0
		lineageTag: 9be52de5-4ee0-4346-a4f2-669eb7c32ea7
		summarizeBy: sum
		sourceColumn: Gestation_Length_Weeks

		annotation SummarizationSetBy = Automatic

	column Gestation_Length_Days
		dataType: int64
		formatString: 0
		lineageTag: 66dbb37b-d463-4bfa-bd38-968f56b6cb97
		summarizeBy: sum
		sourceColumn: Gestation_Length_Days

		annotation SummarizationSetBy = Automatic

	column Locality_current
		dataType: string
		lineageTag: c5e61245-0645-4205-a9a4-1f6a5da24dc5
		summarizeBy: none
		sourceColumn: Locality_current

		annotation SummarizationSetBy = Automatic

	column PCN_current
		dataType: string
		lineageTag: 79d5005c-59dc-40a8-99ca-2467c1fa993a
		summarizeBy: none
		sourceColumn: PCN_current

		annotation SummarizationSetBy = Automatic

	column CountyMother
		dataType: string
		lineageTag: 5023c18b-ae34-400c-b9cc-5daa7d1d7121
		summarizeBy: none
		sourceColumn: CountyMother

		annotation SummarizationSetBy = Automatic

	column County_Mother_group
		dataType: string
		lineageTag: 7a2b85bd-81fc-4215-8d9a-46e676480ef0
		summarizeBy: none
		sourceColumn: County_Mother_group

		annotation SummarizationSetBy = Automatic

	column LSOAMother2011
		dataType: string
		lineageTag: e8321341-4f47-4d28-b9f5-4eb0e55975ce
		summarizeBy: none
		sourceColumn: LSOAMother2011

		annotation SummarizationSetBy = Automatic

	column LAD_UAMother
		dataType: string
		lineageTag: 71771c8a-ab14-40c4-8992-1b21eec8ee2a
		summarizeBy: none
		sourceColumn: LAD_UAMother

		annotation SummarizationSetBy = Automatic

	column ElectoralWardMother
		dataType: string
		lineageTag: 1a46bf2d-6b2b-4779-b0ff-3d1cdd8d6a31
		summarizeBy: none
		sourceColumn: ElectoralWardMother

		annotation SummarizationSetBy = Automatic

	column CCGFromFile
		dataType: string
		lineageTag: 186b81a7-c596-4582-a4e0-b040ebeac836
		summarizeBy: none
		sourceColumn: CCGFromFile

		annotation SummarizationSetBy = Automatic

	column Year_Month
		dataType: int64
		formatString: 0
		lineageTag: ac70f485-aff2-487a-8f6c-c631084ab692
		summarizeBy: sum
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

	column Birth_Day_No_of_Week_Baby
		dataType: int64
		formatString: 0
		lineageTag: e8a9eea1-149f-4181-900a-7d4b3af3ad9f
		summarizeBy: sum
		sourceColumn: Birth_Day_No_of_Week_Baby

		annotation SummarizationSetBy = Automatic

	column Sex_Baby_Long_Desc
		dataType: string
		lineageTag: 95ef76cd-264b-4443-999a-4e86a93e20b2
		summarizeBy: none
		sourceColumn: Sex_Baby_Long_Desc

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Desc_plus
		dataType: string
		lineageTag: 23adbcbb-4e0e-4e19-88ae-0a6461db1e4a
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Desc_plus

		annotation SummarizationSetBy = Automatic

	column Org_Local_Patient_Baby_Desc
		dataType: string
		lineageTag: c05fdb3d-5c49-43b9-89a2-05e39d846828
		summarizeBy: none
		sourceColumn: Org_Local_Patient_Baby_Desc

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_Code
		dataType: string
		lineageTag: fb593ce9-3f6c-48e0-8ee2-dbbe7be491f2
		summarizeBy: none
		sourceColumn: LSOA_Name_Code

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_only
		dataType: string
		lineageTag: bd977db1-0f05-48c8-a2ed-6f076de55eac
		summarizeBy: none
		sourceColumn: LSOA_Name_only

		annotation SummarizationSetBy = Automatic

	column LSOA_Plus
		dataType: string
		lineageTag: ce030511-91e8-4df4-8ad8-fc54d04493d6
		summarizeBy: none
		sourceColumn: LSOA_Plus

		annotation SummarizationSetBy = Automatic

	column LoS_Baby_in_Hours
		dataType: int64
		formatString: 0
		lineageTag: aa69219c-2ca2-443e-a06a-b8469dcc7511
		summarizeBy: sum
		sourceColumn: LoS_Baby_in_Hours

		annotation SummarizationSetBy = Automatic

	column IMD_Glos_Decile
		dataType: string
		lineageTag: 5b3326dc-9d04-4037-ab74-d66186be4b87
		summarizeBy: none
		sourceColumn: IMD_Glos_Decile

		annotation SummarizationSetBy = Automatic

	column Birth_County_Group
		dataType: string
		lineageTag: cb379413-fbb3-48c8-9ceb-61512c83347a
		summarizeBy: none
		sourceColumn: Birth_County_Group

		annotation SummarizationSetBy = Automatic

	column Adm_to_NNU_Flag
		dataType: int64
		formatString: 0
		lineageTag: cc041d00-a547-447d-bcb2-f3710d3eccbe
		summarizeBy: sum
		sourceColumn: Adm_to_NNU_Flag

		annotation SummarizationSetBy = Automatic

	column Adm_to_NNU_Flag_Term
		dataType: int64
		formatString: 0
		lineageTag: ac7f3f50-5572-4aff-b806-ad3a120b5dc5
		summarizeBy: sum
		sourceColumn: Adm_to_NNU_Flag_Term

		annotation SummarizationSetBy = Automatic

	column Adm_to_NNU_Flag_PreTerm
		dataType: int64
		formatString: 0
		lineageTag: 7e3d3a7b-166c-4d25-ab6a-5c24b1c763e8
		summarizeBy: sum
		sourceColumn: Adm_to_NNU_Flag_PreTerm

		annotation SummarizationSetBy = Automatic

	column LoS_Baby_Birth_to_Discharge_Days_Hours
		dataType: double
		lineageTag: fae2a42c-7cc3-4604-83ad-44668631407c
		summarizeBy: sum
		sourceColumn: LoS_Baby_Birth_to_Discharge_Days_Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PreTermFlag
		dataType: int64
		formatString: 0
		lineageTag: 428a5ada-8ea6-446a-b772-766a7b98df76
		summarizeBy: sum
		sourceColumn: PreTermFlag

		annotation SummarizationSetBy = Automatic

	column CalcPreTermFlag
		dataType: int64
		formatString: 0
		lineageTag: c272456d-2d3e-48e5-bc45-c6fe827c2f25
		summarizeBy: sum
		sourceColumn: CalcPreTermFlag

		annotation SummarizationSetBy = Automatic

	column StillbirthFlag
		dataType: int64
		formatString: 0
		lineageTag: 545c450f-bde0-4a16-8368-3b4802b1d496
		summarizeBy: sum
		sourceColumn: StillbirthFlag

		annotation SummarizationSetBy = Automatic

	column CalcNeonatalDeaths0_28_Days
		dataType: int64
		formatString: 0
		lineageTag: 2a0ff41f-7169-4b1b-8ec9-ab92d37d945b
		summarizeBy: sum
		sourceColumn: CalcNeonatalDeaths0_28_Days

		annotation SummarizationSetBy = Automatic

	column CountyMotherDescription
		dataType: string
		lineageTag: 6b7118ca-beea-4533-be53-beb412d73c14
		summarizeBy: none
		sourceColumn: CountyMotherDescription

		annotation SummarizationSetBy = Automatic

	column LAD_UA_Name_Mother
		dataType: string
		lineageTag: ff4f39ba-36bf-4897-b2cb-262baa3121ba
		summarizeBy: none
		sourceColumn: LAD_UA_Name_Mother

		annotation SummarizationSetBy = Automatic

	column Org_Comm_Code
		dataType: string
		lineageTag: 224a1d00-461c-4a07-9c11-1e302f329821
		summarizeBy: none
		sourceColumn: Org_Comm_Code

		annotation SummarizationSetBy = Automatic

	column Org_Comm_Desc
		dataType: string
		lineageTag: 38324226-d6d4-43ff-ad71-9cda627fbc49
		summarizeBy: none
		sourceColumn: Org_Comm_Desc

		annotation SummarizationSetBy = Automatic

	partition Births = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select uniqpregid as ""UniqPregID"", nhs_no_mother as ""NHS_No_Mother"", ethniccategorymother as ""EthnicCategoryMother"", ethniccategorymotherdescription as ""EthnicCategoryMotherDescription"", locality_current as ""Locality_current"", pcn_current as ""PCN_current"", countymother as ""CountyMother"", countymotherdescription as ""CountyMotherDescription"", county_mother_group as ""County_Mother_group"", lsoamother2011 as ""LSOAMother2011"", lsoa_name_code as ""LSOA_Name_Code"", lsoa_name_only as ""LSOA_Name_only"", lsoa_plus as ""LSOA_Plus"", lad_uamother as ""LAD_UAMother"", lad_ua_name_mother as ""LAD_UA_Name_Mother"", electoralwardmother as ""ElectoralWardMother"", ccgfromfile as ""CCGFromFile"", org_comm_code as ""Org_Comm_Code"", org_comm_desc as ""Org_Comm_Desc"", imd_glos_decile as ""IMD_Glos_Decile"", msd401_id as ""MSD401_ID"", nhs_number_baby as ""NHS_Number_Baby"", org_provider_code as ""Org_Provider_Code"", org_provider_desc as ""Org_Provider_Desc"", msds_id_baby as ""MSDS_ID_Baby"", msds_id_mother as ""MSDS_ID_Mother"", org_local_patient_baby_code as ""Org_Local_Patient_Baby_Code"", org_local_patient_baby_desc as ""Org_Local_Patient_Baby_Desc"", birth_date as ""Birth_Date"", birth_time as ""Birth_Time"", finyr_birth_date as ""FinYr_Birth_Date"", year_month as ""Year_Month"", yearmonth_birth_date as ""YearMonth_Birth_Date"", monthyear_birth_date_longdate, birth_day_no_of_week_baby as ""Birth_Day_No_of_Week_Baby"", birth_day_of_week_baby as ""Birth_Day_of_Week_Baby"", year_of_birth_baby as ""Year_of_Birth_Baby"", month_of_birth_baby as ""Month_of_Birth_Baby"", meridian_of_birth_baby as ""Meridian_of_Birth_Baby"", pregnancy_outcome_code as ""Pregnancy_Outcome_Code"", pregnancy_outcome_desc as ""Pregnancy_Outcome_Desc"", sex_baby_code as ""Sex_Baby_Code"", sex_baby_long_desc as ""Sex_Baby_Long_Desc"", sex_baby_desc as ""Sex_Baby_Desc"", delivery_method_code as ""Delivery_Method_Code"", delivery_method_description as ""Delivery_Method_Description"", ethnic_category_baby_code as ""Ethnic_Category_Baby_Code"", ethnic_category_baby_desc as ""Ethnic_Category_Baby_Desc"", birth_order as ""Birth_order"", death_date_baby as ""Death_Date_Baby"", death_time_baby as ""Death_Time_Baby"", presentation_code as ""Presentation_Code"", presentation_desc as ""Presentation_Desc"", pretermflag as ""PreTermFlag"", calcpretermflag as ""CalcPreTermFlag"", stillbirthflag as ""StillbirthFlag"", gestation_length as ""Gestation_Length"", gestation_length_weeks as ""Gestation_Length_Weeks"", gestation_length_days as ""Gestation_Length_Days"", waterdeliveryind as ""WaterDeliveryInd"", water_delivery_indicator as ""Water_Delivery_Indicator"", org_site_actual_delivery_code as ""Org_Site_Actual_Delivery_Code"", org_site_actual_delivery_desc as ""Org_Site_Actual_Delivery_Desc"", org_site_actual_delivery_desc_plus as ""Org_Site_Actual_Delivery_Desc_plus"", birth_county_group as ""Birth_County_Group"", setting_place_birth_code as ""Setting_Place_Birth_Code"", setting_place_birth_desc as ""Setting_Place_Birth_Desc"", baby_first_feed_date as ""Baby_First_Feed_Date"", baby_first_feed_time as ""Baby_First_Feed_Time"", baby_first_feed_type_code as ""Baby_First_Feed_Type_Code"", baby_first_feed_type_desc as ""Baby_First_Feed_Type_Desc"", skin_to_skin_contact_1hr_indicator as ""Skin_to_Skin_Contact_1hr_Indicator"", adm_to_nnu_flag as ""Adm_to_NNU_Flag"", adm_to_nnu_flag_term as ""Adm_to_NNU_Flag_Term"", adm_to_nnu_flag_preterm as ""Adm_to_NNU_Flag_PreTerm"", calcneonataldeaths0_28_days as ""CalcNeonatalDeaths0_28_Days"", discharge_date_baby as ""Discharge_Date_Baby"", discharge_time_baby as ""Discharge_Time_Baby"", los_baby_birth_to_discharge_days_hours as ""LoS_Baby_Birth_to_Discharge_Days_Hours"", los_baby_in_hours as ""LoS_Baby_in_Hours"", age_at_birth_mother as ""Age_At_Birth_Mother"", labour_delivery_id as ""Labour_Delivery_ID"", care_prof_id_delivery as ""Care_Prof_ID_Delivery"", age_at_death_baby as ""Age_at_Death_Baby"", year_of_death_baby as ""Year_of_Death_Baby"", month_of_death_baby as ""Month_of_Death_Baby"", day_of_death_baby as ""Day_of_Death_Baby"", meridianofdeathbaby as ""MeridianOfDeathBaby"", report_start_date as ""Report_Start_Date"", report_end_date as ""Report_End_Date"", processed_date as ""Processed_Date"", data_updated as ""Data_Updated"", counter as ""Counter"" from data_mart_powerbi_maternity.tbl01_births", null, [EnableFolding=true]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"MonthYear_Birth_Date_LongDate"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

