table Deliveries
	lineageTag: e9275719-f107-4dd7-b521-65209cfb3e16

	column UniqPregID
		dataType: string
		lineageTag: ae7b7d1b-c4c3-44ef-bd63-8af18e72782b
		summarizeBy: none
		sourceColumn: UniqPregID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MotherNHSNo
		dataType: string
		lineageTag: 3bdb7d7c-c6b5-4679-acf9-e995510251e9
		summarizeBy: none
		sourceColumn: MotherNHSNo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CCGFromFile
		dataType: string
		lineageTag: 26022c23-bfcb-4d15-98ed-62a7130a871e
		summarizeBy: none
		sourceColumn: CCGFromFile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LAD_UAMother
		dataType: string
		lineageTag: b2664023-53c0-4770-a235-0f9069bee9a9
		summarizeBy: none
		sourceColumn: LAD_UAMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountyMother
		dataType: string
		lineageTag: dbc0e052-67b3-4df9-aea9-62de327f7dd6
		summarizeBy: none
		sourceColumn: CountyMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ElectoralWardMother
		dataType: string
		lineageTag: b063724d-f856-40e3-8dd4-89e01049fc99
		summarizeBy: none
		sourceColumn: ElectoralWardMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category_Code
		dataType: string
		lineageTag: 03c517d3-1604-4b36-af39-19fbc0f7f743
		summarizeBy: none
		sourceColumn: Ethnic_Category_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category_Desc
		dataType: string
		lineageTag: abdbaadb-1379-4de8-8183-31759f491039
		summarizeBy: none
		sourceColumn: Ethnic_Category_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PersonDeathDateMother
		dataType: dateTime
		formatString: General Date
		lineageTag: 42465369-f25f-4f66-9c5d-72952e4a510e
		summarizeBy: none
		sourceColumn: PersonDeathDateMother

		variation Variation
			isDefault
			relationship: e24392fc-a784-4043-a7e9-4777bcd13a76
			defaultHierarchy: LocalDateTable_4c224857-0837-465b-a828-413feaddb42f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PersonDeathTimeMother
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3deb0af7-e821-46d8-9654-280b27c8a37d
		summarizeBy: none
		sourceColumn: PersonDeathTimeMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Age_at_Death_Mother
		dataType: int64
		formatString: 0
		lineageTag: 00a6357e-48c8-48f9-b15c-f5eadc3d467f
		summarizeBy: sum
		sourceColumn: Age_at_Death_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearOfDeathMother
		dataType: int64
		formatString: 0
		lineageTag: d8f3c65c-a42a-4452-a3a5-e1d4fae9afab
		summarizeBy: sum
		sourceColumn: YearOfDeathMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthOfDeathMother
		dataType: int64
		formatString: 0
		lineageTag: ecf5de4d-2bf4-48ed-b12b-226785d4a512
		summarizeBy: sum
		sourceColumn: MonthOfDeathMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfWeekOfDeathMother
		dataType: int64
		formatString: 0
		lineageTag: 44ad4414-1c7f-4c8c-a23f-accc1da09c2b
		summarizeBy: sum
		sourceColumn: DayOfWeekOfDeathMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MeridianOfDeathMother
		dataType: int64
		formatString: 0
		lineageTag: b45ca47a-1f54-4bc8-84a6-123f75a9376f
		summarizeBy: sum
		sourceColumn: MeridianOfDeathMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SourceAdmCodeHospProvSpell
		dataType: string
		lineageTag: 54a8c490-b267-4138-9f42-ff1517a50225
		summarizeBy: none
		sourceColumn: SourceAdmCodeHospProvSpell

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SourceAdmCodeHospProvSpellDescription
		dataType: string
		lineageTag: e7bde8a1-6df2-4a22-bfb9-9f447fd5cef3
		summarizeBy: none
		sourceColumn: SourceAdmCodeHospProvSpellDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PatientClassCode
		dataType: string
		lineageTag: 09b25168-092f-43ca-aa95-443b8fd289ef
		summarizeBy: none
		sourceColumn: PatientClassCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Admission_Type
		dataType: string
		lineageTag: f6c0203a-9e10-47c8-afbf-8fa9455d7df7
		summarizeBy: none
		sourceColumn: Admission_Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AdmMethCodeHospProvSpell
		dataType: string
		lineageTag: cbddeb91-e8f3-405f-ac9f-98ad5afc0418
		summarizeBy: none
		sourceColumn: AdmMethCodeHospProvSpell

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AdmMethCodeHospProvSpellDescription
		dataType: string
		lineageTag: 7466e4b3-4ee0-46fd-9051-4686d88b0f90
		summarizeBy: none
		sourceColumn: AdmMethCodeHospProvSpellDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrgSiteIDOfTreat
		dataType: string
		lineageTag: 2504d788-ab63-4ed4-b69d-4caadd86df62
		summarizeBy: none
		sourceColumn: OrgSiteIDOfTreat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrgSiteIDOfTreatDescription
		dataType: string
		lineageTag: cbb06ac4-7c74-4ca4-af52-cfc44ad112d9
		summarizeBy: none
		sourceColumn: OrgSiteIDOfTreatDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MSD301_ID
		dataType: int64
		formatString: 0
		lineageTag: a8fe8fb5-3b3f-4aaf-b619-12183f8d0e3b
		summarizeBy: count
		sourceColumn: MSD301_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UniqSubmissionID
		dataType: string
		lineageTag: 8dd26cd8-2cd1-4c45-b1d1-96fb8f92e510
		summarizeBy: none
		sourceColumn: UniqSubmissionID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Provider_Code
		dataType: string
		lineageTag: d74c231a-7dd0-461f-b50e-e46aa272ff33
		summarizeBy: none
		sourceColumn: Org_Provider_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Provider_Desc
		dataType: string
		lineageTag: f4f8cd5f-5e7d-4dd1-83be-5ab9a8300191
		summarizeBy: none
		sourceColumn: Org_Provider_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MSDS_ID_Mother
		dataType: string
		lineageTag: 58ec53a5-67ff-4636-ab16-74b97e555a79
		summarizeBy: none
		sourceColumn: MSDS_ID_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PregnancyID
		dataType: string
		lineageTag: b1cc0349-a593-4bb2-9daa-249684050c4b
		summarizeBy: none
		sourceColumn: PregnancyID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Setting_Type_Intra_Code
		dataType: string
		lineageTag: e814f6b3-3b59-4355-857f-61086472b233
		summarizeBy: none
		sourceColumn: Setting_Type_Intra_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Setting_Type_Intra_Desc
		dataType: string
		lineageTag: c7efb4db-2606-4792-9a06-bc254b246878
		summarizeBy: none
		sourceColumn: Setting_Type_Intra_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reason_Change_Del_Setting_Code
		dataType: string
		lineageTag: 52341329-6418-4242-bd31-126fe5571cf8
		summarizeBy: none
		sourceColumn: Reason_Change_Del_Setting_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reason_Change_Del_Setting_Desc
		dataType: string
		lineageTag: 57384a58-1a83-4887-bc46-b9644a0188bb
		summarizeBy: none
		sourceColumn: Reason_Change_Del_Setting_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Labour_Onset_Method_Code
		dataType: string
		lineageTag: 13d51d19-f2b8-4290-9a1f-7c59ca716b42
		summarizeBy: none
		sourceColumn: Labour_Onset_Method_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Labour_Onset_Method_Desc
		dataType: string
		lineageTag: 768d0edc-8629-45d6-87a8-94eaf76b91bc
		summarizeBy: none
		sourceColumn: Labour_Onset_Method_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Labour_Onset_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 23896b87-9e7e-4c95-9191-8a028a92d6e5
		summarizeBy: none
		sourceColumn: Labour_Onset_Date

		variation Variation
			isDefault
			relationship: b89429e0-e953-46c5-b69e-6a885e2861e3
			defaultHierarchy: LocalDateTable_554ce985-70ca-4b52-b49c-e3eff4edf1ee.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Labour_Onset_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 77d30a7f-a80f-4c61-b8a2-f4c9f27bc13e
		summarizeBy: none
		sourceColumn: Labour_Onset_Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Labour_Onset_Date_YearMonth
		dataType: string
		lineageTag: 416a9a79-fb7e-4adb-b247-0dc869bfc35a
		summarizeBy: none
		sourceColumn: Labour_Onset_Date_YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Labour_Onset_FinYr
		dataType: string
		lineageTag: 86a4d9aa-8780-44a1-9e37-1d4888fa2413
		summarizeBy: none
		sourceColumn: Labour_Onset_FinYr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Casesarean_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d2b64de-5500-4742-93a8-251f67107671
		summarizeBy: none
		sourceColumn: Casesarean_Date

		variation Variation
			isDefault
			relationship: c389c94e-d85c-4be7-b56d-4a82c5f3b583
			defaultHierarchy: LocalDateTable_94c10925-5f71-4f03-8536-005d68949373.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Caesarean_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: f0882235-e355-4c9e-a942-52731959ae05
		summarizeBy: none
		sourceColumn: Caesarean_Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Caesarian_Date_YearMonth
		dataType: string
		lineageTag: 0f08fc2b-3cc0-45c5-b47f-4151359d7c7c
		summarizeBy: none
		sourceColumn: Caesarian_Date_YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Caesarian_Date_FinYr
		dataType: string
		lineageTag: d8c06698-63ce-4a28-87e2-e21907b0a36d
		summarizeBy: none
		sourceColumn: Caesarian_Date_FinYr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Start_Date_Delivery_Provider_Spell
		dataType: dateTime
		formatString: General Date
		lineageTag: 20ca117c-3b3c-46a7-9a16-cac153c39e80
		summarizeBy: none
		sourceColumn: Start_Date_Delivery_Provider_Spell

		variation Variation
			isDefault
			relationship: c0c74b08-b6d8-4565-8c21-3fafc27b7dfb
			defaultHierarchy: LocalDateTable_ebafb904-0822-4ed2-a5f8-ca9442bb8a83.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Start_Time_Delivery_Provider_Spell
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3ee36854-09e7-43f2-8371-c058d8e806fa
		summarizeBy: none
		sourceColumn: Start_Time_Delivery_Provider_Spell

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Decision_to_Deliver_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 175cf17c-be97-4109-ae18-659cc9e79f76
		summarizeBy: none
		sourceColumn: Decision_to_Deliver_Date

		variation Variation
			isDefault
			relationship: b5e1fc7d-7129-4860-879f-d917a5fca525
			defaultHierarchy: LocalDateTable_cc95e016-aa99-4eb8-9fc2-9e3c5ede653c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Decision_to_Deliver_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: d73b3937-e7d2-4985-ab69-bb4e77f5ec9d
		summarizeBy: none
		sourceColumn: Decision_to_Deliver_Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Admission_Method_Hospital_Provider_Spell_Code
		dataType: string
		lineageTag: 3dac627c-604c-4a57-b78e-0f890ef59c31
		summarizeBy: none
		sourceColumn: Admission_Method_Hospital_Provider_Spell_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Admission_Method_Hospital_Provider_Spell_Desc
		dataType: string
		lineageTag: a7c4c414-a465-4f4f-a476-d4f603f4dad1
		summarizeBy: none
		sourceColumn: Admission_Method_Hospital_Provider_Spell_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Date_Mother_Hospital
		dataType: dateTime
		formatString: General Date
		lineageTag: afb4ed1f-8798-4019-aa50-aa91a865066b
		summarizeBy: none
		sourceColumn: Discharge_Date_Mother_Hospital

		variation Variation
			isDefault
			relationship: 014b1afa-a5f6-44d5-ba0e-b05def097ce9
			defaultHierarchy: LocalDateTable_30bc9eb0-cc9f-4ca7-a236-6cc6cdd4b9d7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Time_Mother_Hospital
		dataType: dateTime
		formatString: Long Time
		lineageTag: 687fdc35-7997-4841-9482-331fc1710f53
		summarizeBy: none
		sourceColumn: Discharge_Time_Mother_Hospital

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Discharge_Method_Mother_Post_Delivery_Code
		dataType: string
		lineageTag: 400021f0-1d62-48a8-b883-5d3eb6964215
		summarizeBy: none
		sourceColumn: Discharge_Method_Mother_Post_Delivery_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Method_Mother_Post_Delivery_Desc
		dataType: string
		lineageTag: dbaecec0-6e60-4852-9cd9-9006ca0bbe9b
		summarizeBy: none
		sourceColumn: Discharge_Method_Mother_Post_Delivery_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Destination_Code
		dataType: string
		lineageTag: 4f01e30e-fda1-4378-a524-a25a4d57fcc8
		summarizeBy: none
		sourceColumn: Discharge_Destination_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Destination_Desc
		dataType: string
		lineageTag: 9e8ef84a-0589-434e-9138-a2642fc3decd
		summarizeBy: none
		sourceColumn: Discharge_Destination_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Postnatal_Lead_Provider_Code
		dataType: string
		lineageTag: 1c4e093c-ab3f-4e86-aeae-11d2419a9af3
		summarizeBy: none
		sourceColumn: Org_Postnatal_Lead_Provider_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Labour_Delivery_ID
		dataType: string
		lineageTag: 0da69775-d0c6-4924-b93f-3cb1473b891b
		summarizeBy: none
		sourceColumn: Labour_Delivery_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrgCodePPLC
		dataType: string
		lineageTag: 6e4ad0c8-55af-4758-848c-b979248f86eb
		summarizeBy: none
		sourceColumn: OrgCodePPLC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrgCodePPLCDescription
		dataType: string
		lineageTag: 0d3ea16b-cf18-4bdc-9f99-e91e9cb2563b
		summarizeBy: none
		sourceColumn: OrgCodePPLCDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Age_At_Labour_Mother
		dataType: int64
		formatString: 0
		lineageTag: e12dd7db-7ef1-4b10-81c3-03fc9e56137f
		summarizeBy: sum
		sourceColumn: Age_At_Labour_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LeadPostProvider
		dataType: string
		lineageTag: aabd021e-fce0-476b-8f54-1a85f2e739a7
		summarizeBy: none
		sourceColumn: LeadPostProvider

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LeadPostProviderDescription
		dataType: string
		lineageTag: c4ade60a-2474-4841-921a-a7bf15240171
		summarizeBy: none
		sourceColumn: LeadPostProviderDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PostPathLevel
		dataType: int64
		formatString: 0
		lineageTag: 24b93124-e9d3-4b9d-bd8b-c5f44c4c9750
		summarizeBy: sum
		sourceColumn: PostPathLevel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PostPathLevelDescription
		dataType: string
		lineageTag: 9a935260-7c73-4238-9ab0-9b9716200368
		summarizeBy: none
		sourceColumn: PostPathLevelDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: #,0
		lineageTag: 3315ee3b-8e28-424d-996a-dc26e1fa17a7
		summarizeBy: sum
		sourceColumn: counter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Processed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 47afc475-0f7d-4592-991d-77a096e60348
		summarizeBy: none
		sourceColumn: Processed_Date

		variation Variation
			isDefault
			relationship: 3ab0a8bc-5246-4342-bc8a-78dad7fdc226
			defaultHierarchy: LocalDateTable_f0e9da88-0dcf-4192-af48-2071d81739d2.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 82aa81c8-bbfa-4371-8033-5f8ef626718a
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: ec4c331b-674e-4358-8e73-467dbf65c4e4
			defaultHierarchy: LocalDateTable_fc0bec47-2a07-4a6a-aceb-3588fd9c5bb2.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column County_Mother_group
		dataType: string
		lineageTag: 99b58c8d-584c-42b9-aa61-43fda71fc425
		summarizeBy: none
		sourceColumn: County_Mother_group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LSOA_Name
		dataType: string
		lineageTag: a952253c-92b1-4807-957d-820501c77eb1
		summarizeBy: none
		sourceColumn: LSOA_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Locality_current
		dataType: string
		lineageTag: bc1142ce-bdc6-4410-a8e2-db570c77a339
		summarizeBy: none
		sourceColumn: Locality_current

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PCN_current
		dataType: string
		lineageTag: 7838714d-3384-4b09-83c8-579e697093db
		summarizeBy: none
		sourceColumn: PCN_current

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Start_Date_Delivery_Provider_Spell_YearMonth
		dataType: string
		lineageTag: b813dde3-ccb0-4ec6-9c80-7a2854057d9f
		summarizeBy: none
		sourceColumn: Start_Date_Delivery_Provider_Spell_YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Start_Date_Delivery_Provider_Spell_FinYr
		dataType: string
		lineageTag: e66d1869-8559-4046-bc5d-51c561cb8401
		summarizeBy: none
		sourceColumn: Start_Date_Delivery_Provider_Spell_FinYr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column No_Births_per_Delivery_fix
		dataType: int64
		formatString: 0
		lineageTag: 63572a65-c597-46f2-a26a-63690b8461e1
		summarizeBy: sum
		sourceColumn: No_Births_per_Delivery_fix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Postnatal_Lead_Provider_Desc
		dataType: string
		lineageTag: 29669a18-3013-402c-9400-7334daa788a0
		summarizeBy: none
		sourceColumn: Org_Postnatal_Lead_Provider_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LAD_UA_Name_Mother
		dataType: string
		lineageTag: 19298dcc-94c0-4ccf-889d-aeb08e98b976
		summarizeBy: none
		sourceColumn: LAD_UA_Name_Mother

		annotation SummarizationSetBy = Automatic

	column EthnicCategoryBaby
		dataType: string
		lineageTag: f7841e62-0bbe-4e05-affa-7302df3115b3
		summarizeBy: none
		sourceColumn: EthnicCategoryBaby

		annotation SummarizationSetBy = Automatic

	column EthnicCategoryBabyDescription
		dataType: string
		lineageTag: 855c1f97-8873-4aee-bbe4-08a7b6baf43c
		summarizeBy: none
		sourceColumn: EthnicCategoryBabyDescription

		annotation SummarizationSetBy = Automatic

	column IMD_Glos_Decile
		dataType: string
		lineageTag: 5c56c0fc-2104-4b12-9c13-4d32b4262d38
		summarizeBy: none
		sourceColumn: IMD_Glos_Decile

		annotation SummarizationSetBy = Automatic

	column IMD_England_Decile
		dataType: string
		lineageTag: 23a15426-db27-4c87-9570-95bd9b8aaee4
		summarizeBy: none
		sourceColumn: IMD_England_Decile

		annotation SummarizationSetBy = Automatic

	column Core20Flag
		dataType: int64
		formatString: 0
		lineageTag: 9d68e0c8-3665-4374-a30e-e178b00d874a
		summarizeBy: sum
		sourceColumn: Core20Flag

		annotation SummarizationSetBy = Automatic

	column Age_At_Delivery_Mother
		dataType: int64
		formatString: 0
		lineageTag: a58ae54a-6568-4356-8146-fe4f75a4c200
		summarizeBy: sum
		sourceColumn: Age_At_Delivery_Mother

		annotation SummarizationSetBy = Automatic

	column Lab_Caesar_Onset_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8f9aac27-a119-4a80-8ba8-64a0b26f7080
		summarizeBy: none
		sourceColumn: Lab_Caesar_Onset_Date

		annotation SummarizationSetBy = Automatic

	column Lab_Caesar_Onset_YM
		dataType: string
		lineageTag: ae43c6fc-4f24-4194-b84c-6367002eacdc
		summarizeBy: none
		sourceColumn: Lab_Caesar_Onset_YM

		annotation SummarizationSetBy = Automatic

	column Lab_Caesar_Onset_FinYr
		dataType: string
		lineageTag: 5b9ea6f9-2143-438b-8b13-419c88cc3a38
		summarizeBy: none
		sourceColumn: Lab_Caesar_Onset_FinYr

		annotation SummarizationSetBy = Automatic

	column DeliveryYearMonth
		dataType: string
		lineageTag: 0521bafc-066e-4a95-b09a-8079d8e0e392
		summarizeBy: none
		sourceColumn: DeliveryYearMonth

		annotation SummarizationSetBy = Automatic

	column DeliveryFinancialYear
		dataType: string
		lineageTag: 9be11738-7189-40b7-b481-d9a05d8ff88f
		summarizeBy: none
		sourceColumn: DeliveryFinancialYear

		annotation SummarizationSetBy = Automatic

	column SettingPlaceBirth
		dataType: string
		lineageTag: 99e9a3eb-ee16-490b-b510-bc8fbde35023
		summarizeBy: none
		sourceColumn: SettingPlaceBirth

		annotation SummarizationSetBy = Automatic

	column SettingPlaceBirthDescription
		dataType: string
		lineageTag: 1d87bd19-8abb-4a90-af24-44c1d3bff2f3
		summarizeBy: none
		sourceColumn: SettingPlaceBirthDescription

		annotation SummarizationSetBy = Automatic

	column BirthUniqPregID
		dataType: string
		lineageTag: 6a0fa1ba-feb5-4aba-a932-43b7c97e1b33
		summarizeBy: none
		sourceColumn: BirthUniqPregID

		annotation SummarizationSetBy = Automatic

	column Discharge_Mother_YearMonth
		dataType: string
		lineageTag: 6c58aa81-c0ae-42a9-9cf3-15a863748a08
		summarizeBy: none
		sourceColumn: Discharge_Mother_YearMonth

		annotation SummarizationSetBy = Automatic

	column Discharge_Mother_FinYear
		dataType: string
		lineageTag: bdaf9d0d-a027-4b4b-8ae5-03e6e4fa037d
		summarizeBy: none
		sourceColumn: Discharge_Mother_FinYear

		annotation SummarizationSetBy = Automatic

	column MonthNameOfDeathMother
		dataType: string
		lineageTag: aad1821c-121e-41b8-8001-4a713ac14c7e
		summarizeBy: none
		sourceColumn: MonthNameOfDeathMother

		annotation SummarizationSetBy = Automatic

	column DayNameOfWeekOfDeathMother
		dataType: string
		lineageTag: 57cdce43-324e-42fd-9848-aa69a5d93408
		summarizeBy: none
		sourceColumn: DayNameOfWeekOfDeathMother

		annotation SummarizationSetBy = Automatic

	column Continuity_of_Care_Plan_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2f9f4ebb-b07b-4742-94bc-9def762ee4b7
		summarizeBy: sum
		sourceColumn: Continuity_of_Care_Plan_Flag

		annotation SummarizationSetBy = Automatic

	column Continuity_of_Care_Plan_Team
		dataType: string
		lineageTag: 1c6ebd07-4f45-48fd-9681-c8bd2ebec742
		summarizeBy: none
		sourceColumn: Continuity_of_Care_Plan_Team

		annotation SummarizationSetBy = Automatic

	column Org_Site_Labour_Start_Intra_Code
		dataType: string
		lineageTag: ce108ddc-3268-4489-ae49-1afee71cc262
		summarizeBy: none
		sourceColumn: Org_Site_Labour_Start_Intra_Code

		annotation SummarizationSetBy = Automatic

	column Org_Site_Labour_Start_Intra_Desc
		dataType: string
		lineageTag: cb49ac93-2ed2-44c3-8e65-312933c8f37a
		summarizeBy: none
		sourceColumn: Org_Site_Labour_Start_Intra_Desc

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Code
		dataType: string
		lineageTag: c76cb06f-ef29-4ca5-a259-7c4971a1380a
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Code

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Desc
		dataType: string
		lineageTag: 77f5380f-c06f-48ce-a4c0-179bcf14fde8
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Desc

		annotation SummarizationSetBy = Automatic

	column 'Org_Site_changed_during labour_Flag'
		dataType: int64
		formatString: 0
		lineageTag: 67005409-6ab3-4c01-b3ea-35415917eef8
		summarizeBy: sum
		sourceColumn: Org_Site_changed_during labour_Flag

		annotation SummarizationSetBy = Automatic

	column LoS_Mother_Adm_to_Discharge_Days_Hours
		dataType: string
		lineageTag: 0040e441-c1ac-45cc-9498-c7ac7044c7b9
		summarizeBy: none
		sourceColumn: LoS_Mother_Adm_to_Discharge_Days_Hours

		annotation SummarizationSetBy = Automatic

	column LoS_Mother_in_Hours
		dataType: int64
		formatString: 0
		lineageTag: 579f0b48-2bd8-4f4d-8772-8f22b9e073d8
		summarizeBy: sum
		sourceColumn: LoS_Mother_in_Hours

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Desc_plus
		dataType: string
		lineageTag: 2822052e-5ff1-4fec-8632-46883dbb4de6
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Desc_plus

		annotation SummarizationSetBy = Automatic

	column Delivery_County_Group
		dataType: string
		lineageTag: b21d09cd-c117-467e-b043-68a6e0125225
		summarizeBy: none
		sourceColumn: Delivery_County_Group

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Outcome_Code
		dataType: int64
		formatString: 0
		lineageTag: 263d3d0c-d169-4269-8e50-bcdf9d760c78
		summarizeBy: count
		sourceColumn: Pregnancy_Outcome_Code

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Outcome_Desc
		dataType: string
		lineageTag: 0fc41f12-81e6-43b6-993b-154afa4e73b6
		summarizeBy: none
		sourceColumn: Pregnancy_Outcome_Desc

		annotation SummarizationSetBy = Automatic

	column LSOA_Code
		dataType: string
		lineageTag: 43c7ab95-6394-44af-b518-76cf0082f200
		summarizeBy: none
		sourceColumn: LSOA_Code

		annotation SummarizationSetBy = Automatic

	column SATOD_Code
		dataType: string
		lineageTag: eb4c7f31-d88e-4bf0-956c-931460c9373b
		summarizeBy: none
		sourceColumn: SATOD_Code

		annotation SummarizationSetBy = Automatic

	column SATOD_Desc
		dataType: string
		lineageTag: e18a3924-f7a3-4e67-9be9-2e3c31e21fea
		summarizeBy: none
		sourceColumn: SATOD_Desc

		annotation SummarizationSetBy = Automatic

	column Smoking_at_Discharge_Code
		dataType: string
		lineageTag: f4736944-af17-4646-9e04-0ea10c340332
		summarizeBy: none
		sourceColumn: Smoking_at_Discharge_Code

		annotation SummarizationSetBy = Automatic

	column Smoking_at_Discharge_Desc
		dataType: string
		lineageTag: 60712a55-5c56-445f-8eb0-56bdf37c2e13
		summarizeBy: none
		sourceColumn: Smoking_at_Discharge_Desc

		annotation SummarizationSetBy = Automatic

	column Org_Comm
		dataType: string
		lineageTag: 53114d1c-343c-420d-8067-8301209a294b
		summarizeBy: none
		sourceColumn: Org_Comm

		annotation SummarizationSetBy = Automatic

	column Org_Comm_Description
		dataType: string
		lineageTag: 0d4dcde8-bef1-4b46-92aa-301ed71cda34
		summarizeBy: none
		sourceColumn: Org_Comm_Description

		annotation SummarizationSetBy = Automatic

	column CountyMotherDescription
		dataType: string
		lineageTag: ad964a67-f1d8-40d3-8404-a48d82e02939
		summarizeBy: none
		sourceColumn: CountyMotherDescription

		annotation SummarizationSetBy = Automatic

	column Age_at_Delivery_AgeBand5yr
		dataType: string
		lineageTag: bf93d101-fe24-4022-8078-bd67a75ce2d7
		summarizeBy: none
		sourceColumn: Age_at_Delivery_AgeBand5yr

		annotation SummarizationSetBy = Automatic

	partition Deliveries = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select uniqpregid as ""UniqPregID"", mothernhsno as ""MotherNHSNo"", ccgfromfile as ""CCGFromFile"", org_comm as ""Org_Comm"", org_comm_description as ""Org_Comm_Description"", countymother as ""CountyMother"", countymotherdescription as ""CountyMotherDescription"", county_mother_group as ""County_Mother_group"", lsoa_code as ""LSOA_Code"", lsoa_name as ""LSOA_Name"", lad_uamother as ""LAD_UAMother"", lad_ua_name_mother as ""LAD_UA_Name_Mother"", electoralwardmother as ""ElectoralWardMother"", locality_current as ""Locality_current"", pcn_current as ""PCN_current"", ethnic_category_code as ""Ethnic_Category_Code"", ethnic_category_desc as ""Ethnic_Category_Desc"", ethniccategorybaby as ""EthnicCategoryBaby"", ethniccategorybabydescription as ""EthnicCategoryBabyDescription"", imd_glos_decile as ""IMD_Glos_Decile"", imd_england_decile as ""IMD_England_Decile"", core20flag as ""Core20Flag"", age_at_labour_mother as ""Age_At_Labour_Mother"", age_at_delivery_mother as ""Age_At_Delivery_Mother"", age_at_delivery_ageband5yr as ""Age_at_Delivery_AgeBand5yr"", satod_code as ""SATOD_Code"", satod_desc as ""SATOD_Desc"", smoking_at_discharge_code as ""Smoking_at_Discharge_Code"", smoking_at_discharge_desc as ""Smoking_at_Discharge_Desc"", sourceadmcodehospprovspell as ""SourceAdmCodeHospProvSpell"", sourceadmcodehospprovspelldescription as ""SourceAdmCodeHospProvSpellDescription"", patientclasscode as ""PatientClassCode"", admission_type as ""Admission_Type"", admmethcodehospprovspell as ""AdmMethCodeHospProvSpell"", admmethcodehospprovspelldescription as ""AdmMethCodeHospProvSpellDescription"", admission_method_hospital_provider_spell_code as ""Admission_Method_Hospital_Provider_Spell_Code"", admission_method_hospital_provider_spell_desc as ""Admission_Method_Hospital_Provider_Spell_Desc"", orgsiteidoftreat as ""OrgSiteIDOfTreat"", orgsiteidoftreatdescription as ""OrgSiteIDOfTreatDescription"", msd301_id as ""MSD301_ID"", uniqsubmissionid as ""UniqSubmissionID"", org_provider_code as ""Org_Provider_Code"", org_provider_desc as ""Org_Provider_Desc"", msds_id_mother as ""MSDS_ID_Mother"", pregnancyid as ""PregnancyID"", start_date_delivery_provider_spell as ""Start_Date_Delivery_Provider_Spell"", start_time_delivery_provider_spell as ""Start_Time_Delivery_Provider_Spell"", start_date_delivery_provider_spell_yearmonth as ""Start_Date_Delivery_Provider_Spell_YearMonth"", start_date_delivery_provider_spell_finyr as ""Start_Date_Delivery_Provider_Spell_FinYr"", labour_onset_method_code as ""Labour_Onset_Method_Code"", labour_onset_method_desc as ""Labour_Onset_Method_Desc"", labour_onset_date as ""Labour_Onset_Date"", labour_onset_time as ""Labour_Onset_Time"", labour_onset_date_yearmonth as ""Labour_Onset_Date_YearMonth"", labour_onset_finyr as ""Labour_Onset_FinYr"", casesarean_date as ""Casesarean_Date"", caesarean_time as ""Caesarean_Time"", caesarian_date_yearmonth as ""Caesarian_Date_YearMonth"", caesarian_date_finyr as ""Caesarian_Date_FinYr"", lab_caesar_onset_date as ""Lab_Caesar_Onset_Date"", lab_caesar_onset_ym as ""Lab_Caesar_Onset_YM"", lab_caesar_onset_finyr as ""Lab_Caesar_Onset_FinYr"", decision_to_deliver_date as ""Decision_to_Deliver_Date"", decision_to_deliver_time as ""Decision_to_Deliver_Time"", deliveryyearmonth as ""DeliveryYearMonth"", deliveryfinancialyear as ""DeliveryFinancialYear"", labour_delivery_id as ""Labour_Delivery_ID"", org_site_labour_start_intra_code as ""Org_Site_Labour_Start_Intra_Code"", org_site_labour_start_intra_desc as ""Org_Site_Labour_Start_Intra_Desc"", org_site_actual_delivery_code as ""Org_Site_Actual_Delivery_Code"", org_site_actual_delivery_desc as ""Org_Site_Actual_Delivery_Desc"", org_site_actual_delivery_desc_plus as ""Org_Site_Actual_Delivery_Desc_plus"", delivery_county_group as ""Delivery_County_Group"", setting_type_intra_code as ""Setting_Type_Intra_Code"", setting_type_intra_desc as ""Setting_Type_Intra_Desc"", reason_change_del_setting_code as ""Reason_Change_Del_Setting_Code"", reason_change_del_setting_desc as ""Reason_Change_Del_Setting_Desc"", ""org_site_changed_during labour_flag"" as ""Org_Site_changed_during labour_Flag"", settingplacebirth as ""SettingPlaceBirth"", settingplacebirthdescription as ""SettingPlaceBirthDescription"", orgcodepplc as ""OrgCodePPLC"", orgcodepplcdescription as ""OrgCodePPLCDescription"", no_births_per_delivery_fix as ""No_Births_per_Delivery_fix"", pregnancy_outcome_code as ""Pregnancy_Outcome_Code"", pregnancy_outcome_desc as ""Pregnancy_Outcome_Desc"", birthuniqpregid as ""BirthUniqPregID"", discharge_date_mother_hospital as ""Discharge_Date_Mother_Hospital"", discharge_time_mother_hospital as ""Discharge_Time_Mother_Hospital"", discharge_mother_yearmonth as ""Discharge_Mother_YearMonth"", discharge_mother_finyear as ""Discharge_Mother_FinYear"", discharge_method_mother_post_delivery_code as ""Discharge_Method_Mother_Post_Delivery_Code"", discharge_method_mother_post_delivery_desc as ""Discharge_Method_Mother_Post_Delivery_Desc"", discharge_destination_code as ""Discharge_Destination_Code"", discharge_destination_desc as ""Discharge_Destination_Desc"", los_mother_adm_to_discharge_days_hours as ""LoS_Mother_Adm_to_Discharge_Days_Hours"", los_mother_in_hours as ""LoS_Mother_in_Hours"", persondeathdatemother as ""PersonDeathDateMother"", persondeathtimemother as ""PersonDeathTimeMother"", age_at_death_mother as ""Age_at_Death_Mother"", yearofdeathmother as ""YearOfDeathMother"", monthofdeathmother as ""MonthOfDeathMother"", monthnameofdeathmother as ""MonthNameOfDeathMother"", dayofweekofdeathmother as ""DayOfWeekOfDeathMother"", daynameofweekofdeathmother as ""DayNameOfWeekOfDeathMother"", meridianofdeathmother as ""MeridianOfDeathMother"", org_postnatal_lead_provider_code as ""Org_Postnatal_Lead_Provider_Code"", org_postnatal_lead_provider_desc as ""Org_Postnatal_Lead_Provider_Desc"", leadpostprovider as ""LeadPostProvider"", leadpostproviderdescription as ""LeadPostProviderDescription"", postpathlevel as ""PostPathLevel"", postpathleveldescription as ""PostPathLevelDescription"", continuity_of_care_plan_flag as ""Continuity_of_Care_Plan_Flag"", continuity_of_care_plan_team as ""Continuity_of_Care_Plan_Team"", processed_date as ""Processed_Date"", counter, data_updated as ""Data_Updated"" from data_mart_powerbi_maternity.tbl02_deliveries", null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

