table Pregnancies
	lineageTag: 4dcb749d-95a9-4511-89c2-d1b8a2fc4293

	column CCGFromFile
		dataType: string
		lineageTag: 260a9c71-075b-4496-a6a1-703d438c12a8
		summarizeBy: none
		sourceColumn: CCGFromFile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: int64
		formatString: 0
		lineageTag: f8192514-3b3f-40fb-a807-fbb76bb06e39
		summarizeBy: sum
		sourceColumn: Period

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MSD101_ID
		dataType: string
		lineageTag: a673c1e4-db51-4945-b09a-9d48ee0c8667
		summarizeBy: none
		sourceColumn: MSD101_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecordNumber
		dataType: int64
		formatString: 0
		lineageTag: ac16fa39-b78d-478d-894b-2fc9412d038a
		summarizeBy: sum
		sourceColumn: RecordNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Code_Provider
		dataType: string
		lineageTag: 370ba460-7b44-4821-baa9-11503819062a
		summarizeBy: none
		sourceColumn: Org_Code_Provider

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Code_Provider_Desc
		dataType: string
		lineageTag: 3839e4d9-4564-4766-8e94-c49e4b30209a
		summarizeBy: none
		sourceColumn: Org_Code_Provider_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MSDS_ID_Mother
		dataType: string
		lineageTag: f232f0a9-02ec-4d97-8877-9315932abc10
		summarizeBy: none
		sourceColumn: MSDS_ID_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unique_Pregnancy_ID
		dataType: string
		lineageTag: 64787497-aaca-4c59-ada4-45fa75282985
		summarizeBy: none
		sourceColumn: Unique_Pregnancy_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Antenatal_App_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8f7f4f50-88de-405e-b8ba-75087494bbbf
		summarizeBy: none
		sourceColumn: Antenatal_App_Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearMonth_Antenatal_AppDate
		dataType: string
		lineageTag: 2032f8ac-f117-4bfd-b055-8f4344708ce0
		summarizeBy: none
		sourceColumn: YearMonth_Antenatal_AppDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinYr_Antental_App_Date
		dataType: string
		lineageTag: 9e101632-8ec3-4df1-b733-de5d1b8cc327
		summarizeBy: none
		sourceColumn: FinYr_Antental_App_Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Confirmed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: da833528-1f6e-4308-a1ae-eb64ec04ab8f
		summarizeBy: none
		sourceColumn: Pregnancy_Confirmed_Date

		variation Variation
			isDefault
			relationship: 004e6319-68db-4ee7-b976-000848d061f9
			defaultHierarchy: LocalDateTable_469a56a5-d27a-4a9f-a7c5-2404f2d6a67e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estimated_Delivery_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 70ae4695-e433-47fc-9d40-b5898714174c
		summarizeBy: none
		sourceColumn: Estimated_Delivery_Date

		variation Variation
			isDefault
			relationship: 8a374dbc-6173-409b-a9aa-8133f8154272
			defaultHierarchy: LocalDateTable_93e906f8-f18f-402f-983b-c7bcce04f230.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Site_Booked
		dataType: string
		lineageTag: 17fe442a-f4f9-41ef-845d-6c09dc8a5597
		summarizeBy: none
		sourceColumn: Org_Site_Booked

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Site_Booked_Desc
		dataType: string
		lineageTag: 453e5407-fb6a-4464-9471-fb7393abb318
		summarizeBy: none
		sourceColumn: Org_Site_Booked_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EDD_Method
		dataType: string
		lineageTag: 52b4fddf-6d6a-418a-918c-503279f7b334
		summarizeBy: none
		sourceColumn: EDD_Method

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EDD_Method_Desc
		dataType: string
		lineageTag: 11618cac-a8da-4184-a86b-1f06b16ab21a
		summarizeBy: none
		sourceColumn: EDD_Method_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source_of_Referral_Code
		dataType: string
		lineageTag: 76608c67-0321-4688-8be1-36aa5a59a991
		summarizeBy: none
		sourceColumn: Source_of_Referral_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source_of_Referral_Desc
		dataType: string
		lineageTag: 4a2d83a2-a808-4cdf-a819-86aefe3c0857
		summarizeBy: none
		sourceColumn: Source_of_Referral_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reason_Late_Booking_Code
		dataType: string
		lineageTag: bacff1f5-ab30-4ab2-a35c-a5dcc2a22633
		summarizeBy: none
		sourceColumn: Reason_Late_Booking_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reason_Late_Booking_Desc
		dataType: string
		lineageTag: a706a7a9-a8a9-4b84-ab50-bda9fe0a9d5e
		summarizeBy: none
		sourceColumn: Reason_Late_Booking_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Preg_First_Contact_Professional_Code
		dataType: string
		lineageTag: 76ee18c1-facd-4599-95a2-eeaa7dc32a0b
		summarizeBy: none
		sourceColumn: Preg_First_Contact_Professional_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Last_Menstrual_Period_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ba286a1-0d6e-4bd2-b568-aa81ed0a2daa
		summarizeBy: none
		sourceColumn: Last_Menstrual_Period_Date

		variation Variation
			isDefault
			relationship: 58f3d3e3-7850-4f44-8a80-c4c16db1e28a
			defaultHierarchy: LocalDateTable_87ccae57-2395-43fe-981d-d8adc0e3c902.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Disability_Indicator_Mother
		dataType: string
		lineageTag: 22c6c3db-ea18-425b-8e20-1270a82bbe12
		summarizeBy: none
		sourceColumn: Disability_Indicator_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Language_Code
		dataType: string
		lineageTag: d8b9c909-9682-4a66-8925-38c1d7fd1ebb
		summarizeBy: none
		sourceColumn: Language_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Language_Desc
		dataType: string
		lineageTag: 697a2c2e-029a-42df-bb95-f912582788e6
		summarizeBy: none
		sourceColumn: Language_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MH_Prediction_Detection_Mother
		dataType: string
		lineageTag: aa297034-b554-4033-a448-e6f0ec0ad576
		summarizeBy: none
		sourceColumn: MH_Prediction_Detection_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Complex_Social_Factors_Ind
		dataType: string
		lineageTag: cd2726de-1784-4490-ba6c-c0490d4f29be
		summarizeBy: none
		sourceColumn: Complex_Social_Factors_Ind

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Status_Code
		dataType: string
		lineageTag: 2f871f55-473e-4ffa-bcdf-d45fead6a65f
		summarizeBy: none
		sourceColumn: Employment_Status_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Status_Desc
		dataType: string
		lineageTag: 02dbbf2b-61e9-4644-8532-ca4229a3aa3f
		summarizeBy: none
		sourceColumn: Employment_Status_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Support Status_Indicator'
		dataType: string
		lineageTag: 0eda984b-f079-4c83-ba04-286756234709
		summarizeBy: none
		sourceColumn: Support Status_Indicator

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Partner
		dataType: string
		lineageTag: 9058833d-31c4-4f8d-8f19-3d97f6e5efef
		summarizeBy: none
		sourceColumn: Employment_Partner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employment_Partner_Desc
		dataType: string
		lineageTag: d8b8582e-9144-4ee8-b615-d771b8f17f00
		summarizeBy: none
		sourceColumn: Employment_Partner_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Previous_Casesareans_Number
		dataType: int64
		formatString: 0
		lineageTag: e56305e6-27fe-49d9-958d-a8b5579366bd
		summarizeBy: sum
		sourceColumn: Previous_Casesareans_Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Previous_Live_Births_Number
		dataType: int64
		formatString: 0
		lineageTag: 40d24a88-0b95-4998-acbf-77077409a9b1
		summarizeBy: sum
		sourceColumn: Previous_Live_Births_Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Previous_Still_Births
		dataType: int64
		formatString: 0
		lineageTag: 23134d1a-5d34-4a6c-8f2f-81ca9b7d1560
		summarizeBy: sum
		sourceColumn: Previous_Still_Births

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Previous_Losses < 24 Weeks'
		dataType: int64
		formatString: 0
		lineageTag: 5f233264-9b2a-4826-89b6-8d791ae3fe13
		summarizeBy: sum
		sourceColumn: Previous_Losses < 24 Weeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Folic_Acid_Supplement_Code
		dataType: string
		lineageTag: 50f1dfa9-fa93-4626-96c8-e8374893fd47
		summarizeBy: none
		sourceColumn: Folic_Acid_Supplement_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Folic_Acid_Supplement_Desc
		dataType: string
		lineageTag: 81a879e7-96c8-4531-abc4-84fd6e5d4912
		summarizeBy: none
		sourceColumn: Folic_Acid_Supplement_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Date_Mat_Service
		dataType: dateTime
		formatString: General Date
		lineageTag: 5100cc61-9b4a-4fca-aa0d-2e793d67d98f
		summarizeBy: none
		sourceColumn: Discharge_Date_Mat_Service

		variation Variation
			isDefault
			relationship: 5694b993-066a-474c-a070-ffc54f64ae6c
			defaultHierarchy: LocalDateTable_f34a1e5a-23b5-48fa-a631-13ecd75652c4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Reason_Code
		dataType: string
		lineageTag: 7591d2ec-46aa-4707-948e-d4feedce94fa
		summarizeBy: none
		sourceColumn: Discharge_Reason_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discharge_Reason_Desc
		dataType: string
		lineageTag: 33014c4a-4075-4b30-8f8f-93465f52b68f
		summarizeBy: none
		sourceColumn: Discharge_Reason_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LPIDMother
		dataType: string
		lineageTag: 85776258-ec5c-4304-87f7-22cdf0b9cad4
		summarizeBy: none
		sourceColumn: LPIDMother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PregnancyID
		dataType: string
		lineageTag: e3a33232-1432-4910-8fee-5131b8abfd41
		summarizeBy: none
		sourceColumn: PregnancyID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AntePathLevel
		dataType: int64
		formatString: 0
		lineageTag: 3ebfa0b5-a2d5-4cb4-b47c-89c7b810911e
		summarizeBy: sum
		sourceColumn: AntePathLevel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AntePathLevelDescription
		dataType: string
		lineageTag: e56a8327-d7d5-4897-bc1b-bcacf4487802
		summarizeBy: none
		sourceColumn: AntePathLevelDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gestation_Age_at_Appt_Date_in_Days
		dataType: int64
		formatString: 0
		lineageTag: cbe78812-0b1d-49f2-bac1-e1e08365c660
		summarizeBy: sum
		sourceColumn: Gestation_Age_at_Appt_Date_in_Days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cigarettes_Per_Day_Band
		dataType: string
		lineageTag: ff5967e6-2ad0-4d9d-baf1-38feee75b9f8
		summarizeBy: none
		sourceColumn: Cigarettes_Per_Day_Band

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BMI_at_Booking
		dataType: double
		lineageTag: c851e444-f8c6-4fa2-8d2b-3465bb1080e6
		summarizeBy: sum
		sourceColumn: BMI_at_Booking

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BMI_Band
		dataType: string
		lineageTag: 14c29d99-03f5-45f3-a3b4-06ff3d85295b
		summarizeBy: none
		sourceColumn: BMI_Band

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Age_At_Booking_Mother
		dataType: int64
		formatString: 0
		lineageTag: 28096e71-7ff7-4de0-818a-abeaf44ade24
		summarizeBy: sum
		sourceColumn: Age_At_Booking_Mother

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Age_At_Booking_Mother_AgeBand5yr
		dataType: string
		lineageTag: cc2f2db9-6f0f-4431-8bfc-06d42dfba097
		summarizeBy: none
		sourceColumn: Age_At_Booking_Mother_AgeBand5yr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Org_Code APLC'
		dataType: string
		lineageTag: 6f3f446f-49c4-4ea8-b03f-8865d0b1e6eb
		summarizeBy: none
		sourceColumn: Org_Code APLC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Lead_Ante_Provider_Code
		dataType: string
		lineageTag: e03ef643-c25d-447a-9bbe-f55ed1eaf02c
		summarizeBy: none
		sourceColumn: Lead_Ante_Provider_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Lead_Ante_Provider_Desc
		dataType: string
		lineageTag: 8cc62292-2fbe-4895-85d7-bb5905a92b45
		summarizeBy: none
		sourceColumn: Lead_Ante_Provider_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Report_Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b718543-7974-4f89-a369-a9b639dca4e9
		summarizeBy: none
		sourceColumn: Report_Start_Date

		variation Variation
			isDefault
			relationship: 7a823185-0db1-4ce0-b816-86aeea95e887
			defaultHierarchy: LocalDateTable_8508e14c-1d31-4f82-992b-b43244ad9534.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Report_End_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8c95b97f-27b8-4915-9f12-64dca45ae8fa
		summarizeBy: none
		sourceColumn: Report_End_Date

		variation Variation
			isDefault
			relationship: 4e4f5e2c-5d5c-4602-b9df-7a4d58d3eacf
			defaultHierarchy: LocalDateTable_6a6755ab-31a0-42ed-8c7a-adaa294c7638.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: #,0
		lineageTag: 1072b0a0-382c-4091-afc3-cafab2fcb7b9
		summarizeBy: sum
		sourceColumn: counter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Processed_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2cf1b183-5f4d-4f76-8f2c-c2870141318f
		summarizeBy: none
		sourceColumn: Processed_Date

		variation Variation
			isDefault
			relationship: 364e5944-eb9c-4e84-9eea-e8e3e76ae1d8
			defaultHierarchy: LocalDateTable_79888c70-0c5e-44e2-950b-21fab526e924.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Commissioner_Code
		dataType: string
		lineageTag: 10671a5a-1709-45bc-a34a-01bc7768ed3e
		summarizeBy: none
		sourceColumn: Org_Commissioner_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Org_Commissioner_Desc
		dataType: string
		lineageTag: 3e5577c5-2872-4653-a3af-4122054bb763
		summarizeBy: none
		sourceColumn: Org_Commissioner_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 35a06827-191a-4d54-843b-f01d433e0de1
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: 7acd4dfb-42d3-4a2b-a68b-af87135c4355
			defaultHierarchy: LocalDateTable_58e96f6c-866a-46f5-b2f9-71e8aca8d5ff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MonthYear_MMMM_YYYYY
		dataType: string
		lineageTag: 7b016cbf-2e3c-414b-9fec-950d681122cf
		summarizeBy: none
		sourceColumn: MonthYear_MMMM_YYYYY

		annotation SummarizationSetBy = Automatic

	column MotherNHSNo
		dataType: string
		lineageTag: a0341559-5a8b-46ee-8df4-2e01a1fddf18
		summarizeBy: none
		sourceColumn: MotherNHSNo

		annotation SummarizationSetBy = Automatic

	column CountyMother
		dataType: string
		lineageTag: 98a42674-1af2-42b0-acf3-e2eec7b666b1
		summarizeBy: none
		sourceColumn: CountyMother

		annotation SummarizationSetBy = Automatic

	column County_Mother_group
		dataType: string
		lineageTag: d777bc42-89cd-4ca3-869a-72314b509e08
		summarizeBy: none
		sourceColumn: County_Mother_group

		annotation SummarizationSetBy = Automatic

	column LSOAMother2011
		dataType: string
		lineageTag: b89f2ad0-f61e-40a2-ae7e-4a2fc09b7971
		summarizeBy: none
		sourceColumn: LSOAMother2011

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_only
		dataType: string
		lineageTag: af84b9a6-1a82-4a83-a04f-05229449f4d1
		summarizeBy: none
		sourceColumn: LSOA_Name_only

		annotation SummarizationSetBy = Automatic

	column LSOA_Plus
		dataType: string
		lineageTag: ebb86c5f-cb8e-4469-b5c2-4df226084038
		summarizeBy: none
		sourceColumn: LSOA_Plus

		annotation SummarizationSetBy = Automatic

	column LAD_UAMother
		dataType: string
		lineageTag: 993f259e-38cc-4356-be3c-9a18f91f3eac
		summarizeBy: none
		sourceColumn: LAD_UAMother

		annotation SummarizationSetBy = Automatic

	column ElectoralWardMother
		dataType: string
		lineageTag: f4e7ffe7-94a7-4a49-9ffb-4e1c5fefdb3e
		summarizeBy: none
		sourceColumn: ElectoralWardMother

		annotation SummarizationSetBy = Automatic

	column Locality_current
		dataType: string
		lineageTag: 2a54d220-8c4f-46c2-8a0d-fc5b02397f10
		summarizeBy: none
		sourceColumn: Locality_current

		annotation SummarizationSetBy = Automatic

	column PCN_current
		dataType: string
		lineageTag: 6297bc9a-ca71-4d82-bb04-6d8ea456dddc
		summarizeBy: none
		sourceColumn: PCN_current

		annotation SummarizationSetBy = Automatic

	column Gestation_Length_Months
		dataType: int64
		formatString: 0
		lineageTag: c2f370a5-b555-4ac3-9911-bd1f368968d4
		summarizeBy: sum
		sourceColumn: Gestation_Length_Months

		annotation SummarizationSetBy = Automatic

	column Gestation_Age_at_Appt_Date_in_Weeks
		dataType: int64
		formatString: 0
		lineageTag: e84d4e41-b89b-43f9-81c2-887758b72b43
		summarizeBy: sum
		sourceColumn: Gestation_Age_at_Appt_Date_in_Weeks

		annotation SummarizationSetBy = Automatic

	column Gestation_Age_at_Appt_Group
		dataType: string
		lineageTag: f8b6a40d-486f-4308-9433-7f7a04061c8d
		summarizeBy: none
		sourceColumn: Gestation_Age_at_Appt_Group

		annotation SummarizationSetBy = Automatic

	column Preg_First_Contact_Professional_Desc
		dataType: string
		lineageTag: 5e59caeb-5964-4408-afae-48ff4b43ada0
		summarizeBy: none
		sourceColumn: Preg_First_Contact_Professional_Desc

		annotation SummarizationSetBy = Automatic

	column 'Gestation_Length_Target_Zones Week+Days'
		dataType: string
		lineageTag: 041428d8-4bec-4424-be62-a957056e8d6d
		summarizeBy: none
		sourceColumn: Gestation_Length_Target_Zones Week+Days

		annotation SummarizationSetBy = Automatic

	column Alcohol_Units_per_wk_at_Booking
		dataType: double
		lineageTag: a434b0a2-35df-45ae-92c5-f832582ac4b0
		summarizeBy: sum
		sourceColumn: Alcohol_Units_per_wk_at_Booking

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Alcohol_Units_per wk_Band'
		dataType: string
		lineageTag: 3b969358-f71d-48e0-b2c7-bd6b2ec7d7a3
		summarizeBy: none
		sourceColumn: Alcohol_Units_per wk_Band

		annotation SummarizationSetBy = Automatic

	column 'Alcohol_Units_>1 /wk'
		dataType: string
		lineageTag: c211053e-610b-45e9-be3d-206694aeae61
		summarizeBy: none
		sourceColumn: Alcohol_Units_>1 /wk

		annotation SummarizationSetBy = Automatic

	column 'BMI >30'
		dataType: string
		lineageTag: e0eaae81-0699-48c2-a40b-3c18f4b2ef34
		summarizeBy: none
		sourceColumn: BMI >30

		annotation SummarizationSetBy = Automatic

	column PersonBMIBand
		dataType: string
		lineageTag: 1930a51e-06a4-42b2-9a06-39bee26204ba
		summarizeBy: none
		sourceColumn: PersonBMIBand

		annotation SummarizationSetBy = Automatic

	column Continuity_of_Care_Plan_Flag
		dataType: int64
		formatString: 0
		lineageTag: 3e20bdbc-d8fb-4b1e-82b1-a8e0647da7c9
		summarizeBy: sum
		sourceColumn: Continuity_of_Care_Plan_Flag

		annotation SummarizationSetBy = Automatic

	column Continuity_of_Care_Plan_Team
		dataType: string
		lineageTag: 46fcf6ce-7b62-4bf2-9f7e-f601f5c48e2f
		summarizeBy: none
		sourceColumn: Continuity_of_Care_Plan_Team

		annotation SummarizationSetBy = Automatic

	column Ethnicity_Mother_Code
		dataType: string
		lineageTag: d00b0767-cee3-4857-8783-4675fdfd68f4
		summarizeBy: none
		sourceColumn: Ethnicity_Mother_Code

		annotation SummarizationSetBy = Automatic

	column Ethnicity_Mother_Desc
		dataType: string
		lineageTag: d68b36bc-3dfb-4a56-8c32-649ccb89ffc1
		summarizeBy: none
		sourceColumn: Ethnicity_Mother_Desc

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Financial_Year
		dataType: string
		lineageTag: 57bb32d5-376b-49a0-b111-4f32d83c9058
		summarizeBy: none
		sourceColumn: Pregnancy_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Delivery_Financial_Year
		dataType: string
		lineageTag: dd33521f-598c-415a-bb89-b34b893188b5
		summarizeBy: none
		sourceColumn: Delivery_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Delivery_Year_Month
		dataType: string
		lineageTag: c0b726a3-22f1-4574-b48b-2cb5ae3134fc
		summarizeBy: none
		sourceColumn: Delivery_Year_Month

		annotation SummarizationSetBy = Automatic

	column 'Late_Booking_>_70 Day_Flag'
		dataType: int64
		formatString: 0
		lineageTag: 2ccd5158-00db-4d1b-8344-59b476fd3802
		summarizeBy: sum
		sourceColumn: Late_Booking_>_70 Day_Flag

		annotation SummarizationSetBy = Automatic

	column Smoking_Status_at_Booking_Code
		dataType: string
		lineageTag: c5dc1e07-b245-4866-94da-41a728aec447
		summarizeBy: none
		sourceColumn: Smoking_Status_at_Booking_Code

		annotation SummarizationSetBy = Automatic

	column Smoking_Status_at_Booking_Desc
		dataType: string
		lineageTag: e11294ee-42e0-4365-93ca-7e9653053861
		summarizeBy: none
		sourceColumn: Smoking_Status_at_Booking_Desc

		annotation SummarizationSetBy = Automatic

	column CountyMotherDescription
		dataType: string
		lineageTag: f6a470c7-fbed-4592-a7bd-1a44f1ae7ddd
		summarizeBy: none
		sourceColumn: CountyMotherDescription

		annotation SummarizationSetBy = Automatic

	column LSOA_Name_Mother2011
		dataType: string
		lineageTag: af520370-2f39-49d5-900a-f3184c0d6a7d
		summarizeBy: none
		sourceColumn: LSOA_Name_Mother2011

		annotation SummarizationSetBy = Automatic

	column LAD_UA_Name_Mother
		dataType: string
		lineageTag: 7a68c354-7c31-4dc9-b26f-b44c6e0b5045
		summarizeBy: none
		sourceColumn: LAD_UA_Name_Mother

		annotation SummarizationSetBy = Automatic

	column 'Late_Booking_>_84 Day_Flag'
		dataType: int64
		formatString: 0
		lineageTag: 9e8b5f68-df5d-4fc3-86c7-80edfc91ad8f
		summarizeBy: sum
		sourceColumn: Late_Booking_>_84 Day_Flag

		annotation SummarizationSetBy = Automatic

	partition Pregnancies = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select unique_pregnancy_id as ""Unique_Pregnancy_ID"", mothernhsno as ""MotherNHSNo"", period as ""Period"", msd101_id as ""MSD101_ID"", recordnumber as ""RecordNumber"", msds_id_mother as ""MSDS_ID_Mother"", ccgfromfile as ""CCGFromFile"", org_commissioner_code as ""Org_Commissioner_Code"", org_commissioner_desc as ""Org_Commissioner_Desc"", countymother as ""CountyMother"", countymotherdescription as ""CountyMotherDescription"", county_mother_group as ""County_Mother_group"", lsoamother2011 as ""LSOAMother2011"", lsoa_name_mother2011 as ""LSOA_Name_Mother2011"", lsoa_name_only as ""LSOA_Name_only"", lsoa_plus as ""LSOA_Plus"", lad_uamother as ""LAD_UAMother"", lad_ua_name_mother as ""LAD_UA_Name_Mother"", electoralwardmother as ""ElectoralWardMother"", locality_current as ""Locality_current"", pcn_current as ""PCN_current"", antenatal_app_date as ""Antenatal_App_Date"", yearmonth_antenatal_appdate as ""YearMonth_Antenatal_AppDate"", finyr_antental_app_date as ""FinYr_Antental_App_Date"", pregnancy_financial_year as ""Pregnancy_Financial_Year"", monthyear_mmmm_yyyyy as ""MonthYear_MMMM_YYYYY"", pregnancy_confirmed_date as ""Pregnancy_Confirmed_Date"", estimated_delivery_date as ""Estimated_Delivery_Date"", delivery_financial_year as ""Delivery_Financial_Year"", delivery_year_month as ""Delivery_Year_Month"", gestation_age_at_appt_date_in_days as ""Gestation_Age_at_Appt_Date_in_Days"", gestation_age_at_appt_date_in_weeks as ""Gestation_Age_at_Appt_Date_in_Weeks"", gestation_length_months as ""Gestation_Length_Months"", gestation_age_at_appt_group as ""Gestation_Age_at_Appt_Group"", ""gestation_length_target_zones week+days"" as ""Gestation_Length_Target_Zones Week+Days"", ""late_booking_>_84 day_flag"" as ""Late_Booking_>_84 Day_Flag"", ""late_booking_>_70 day_flag"" as ""Late_Booking_>_70 Day_Flag"", reason_late_booking_code as ""Reason_Late_Booking_Code"", reason_late_booking_desc as ""Reason_Late_Booking_Desc"", org_code_provider as ""Org_Code_Provider"", org_code_provider_desc as ""Org_Code_Provider_Desc"", org_site_booked as ""Org_Site_Booked"", org_site_booked_desc as ""Org_Site_Booked_Desc"", edd_method as ""EDD_Method"", edd_method_desc as ""EDD_Method_Desc"", source_of_referral_code as ""Source_of_Referral_Code"", source_of_referral_desc as ""Source_of_Referral_Desc"", preg_first_contact_professional_code as ""Preg_First_Contact_Professional_Code"", preg_first_contact_professional_desc as ""Preg_First_Contact_Professional_Desc"", continuity_of_care_plan_flag as ""Continuity_of_Care_Plan_Flag"", continuity_of_care_plan_team as ""Continuity_of_Care_Plan_Team"", last_menstrual_period_date as ""Last_Menstrual_Period_Date"", disability_indicator_mother as ""Disability_Indicator_Mother"", ethnicity_mother_code as ""Ethnicity_Mother_Code"", ethnicity_mother_desc as ""Ethnicity_Mother_Desc"", language_code as ""Language_Code"", language_desc as ""Language_Desc"", mh_prediction_detection_mother as ""MH_Prediction_Detection_Mother"", complex_social_factors_ind as ""Complex_Social_Factors_Ind"", employment_status_code as ""Employment_Status_Code"", employment_status_desc as ""Employment_Status_Desc"", ""support status_indicator"" as ""Support Status_Indicator"", employment_partner as ""Employment_Partner"", employment_partner_desc as ""Employment_Partner_Desc"", previous_casesareans_number as ""Previous_Casesareans_Number"", previous_live_births_number as ""Previous_Live_Births_Number"", previous_still_births as ""Previous_Still_Births"", ""previous_losses < 24 weeks"" as ""Previous_Losses < 24 Weeks"", folic_acid_supplement_code as ""Folic_Acid_Supplement_Code"", folic_acid_supplement_desc as ""Folic_Acid_Supplement_Desc"", discharge_date_mat_service as ""Discharge_Date_Mat_Service"", discharge_reason_code as ""Discharge_Reason_Code"", discharge_reason_desc as ""Discharge_Reason_Desc"", lpidmother as ""LPIDMother"", pregnancyid as ""PregnancyID"", antepathlevel as ""AntePathLevel"", antepathleveldescription as ""AntePathLevelDescription"", smoking_status_at_booking_code as ""Smoking_Status_at_Booking_Code"", smoking_status_at_booking_desc as ""Smoking_Status_at_Booking_Desc"", cigarettes_per_day_band as ""Cigarettes_Per_Day_Band"", alcohol_units_per_wk_at_booking as ""Alcohol_Units_per_wk_at_Booking"", ""alcohol_units_per wk_band"" as ""Alcohol_Units_per wk_Band"", ""alcohol_units_>1 /wk"" as ""Alcohol_Units_>1 /wk"", bmi_at_booking as ""BMI_at_Booking"", personbmiband as ""PersonBMIBand"", bmi_band as ""BMI_Band"", ""bmi >30"" as ""BMI >30"", age_at_booking_mother as ""Age_At_Booking_Mother"", age_at_booking_mother_ageband5yr as ""Age_At_Booking_Mother_AgeBand5yr"", ""org_code aplc"" as ""Org_Code APLC"", lead_ante_provider_code as ""Lead_Ante_Provider_Code"", lead_ante_provider_desc as ""Lead_Ante_Provider_Desc"", report_start_date as ""Report_Start_Date"", report_end_date as ""Report_End_Date"", counter, processed_date as ""Processed_Date"", data_updated as ""Data_Updated"" from data_mart_powerbi_maternity.tbl03_pregnancies", null, [EnableFolding=true]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"N","No",Replacer.ReplaceText,{"Disability_Indicator_Mother"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Y","Yes",Replacer.ReplaceText,{"Disability_Indicator_Mother"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Y","Yes",Replacer.ReplaceText,{"MH_Prediction_Detection_Mother"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","N","No",Replacer.ReplaceText,{"MH_Prediction_Detection_Mother"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Y","Yes",Replacer.ReplaceText,{"Complex_Social_Factors_Ind"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","N","No",Replacer.ReplaceText,{"Complex_Social_Factors_Ind"})
				in
				    #"Replaced Value5"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

