table '104 Day'
	lineageTag: 7a015176-db3e-4887-80b4-51c7127251be

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 71ee7430-6e2d-4955-a458-9fc4c0edc9c5
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = ID

		annotation PBI_WasHiddenAtRefresh = False

	column Care
		dataType: string
		lineageTag: b3fe9c93-6c80-4527-843d-e079c54abf0a
		summarizeBy: none
		sourceColumn: Care

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Care

		annotation PBI_WasHiddenAtRefresh = False

	column Tumour_Type
		dataType: string
		lineageTag: 1e840522-c37e-47cf-be2d-654ded0e5e9c
		summarizeBy: none
		sourceColumn: Tumour_Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Tumour_Type

		annotation PBI_WasHiddenAtRefresh = False

	column First_Seen_Provider
		dataType: string
		lineageTag: c4a59cdd-4887-4ae0-9f71-0e7fca4a1b44
		summarizeBy: none
		sourceColumn: First_Seen_Provider

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First_Seen_Provider

		annotation PBI_WasHiddenAtRefresh = False

	column First_Treatment_Provider
		dataType: string
		lineageTag: 0c0f54ba-1342-4669-b730-676cae8114b1
		summarizeBy: none
		sourceColumn: First_Treatment_Provider

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First_Treatment_Provider

		annotation PBI_WasHiddenAtRefresh = False

	column Patient_CWT_Ref
		dataType: string
		lineageTag: 817351a2-2060-4c64-8856-f2193945d728
		summarizeBy: none
		sourceColumn: Patient_CWT_Ref

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Patient_CWT_Ref

		annotation PBI_WasHiddenAtRefresh = False

	column Wait_Days
		dataType: int64
		formatString: 0
		lineageTag: 1c4a4139-a6e0-4e43-9af6-3016bceeb35d
		summarizeBy: sum
		sourceColumn: Wait_Days

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Wait_Days

		annotation PBI_WasHiddenAtRefresh = False

	column Delay_Reason_Code
		dataType: string
		lineageTag: 5b7afa17-6074-497f-b29a-cb9dfdec0a92
		summarizeBy: none
		sourceColumn: Delay_Reason_Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Delay_Reason_Code

		annotation PBI_WasHiddenAtRefresh = False

	column Report_Number
		dataType: string
		lineageTag: 6c6f7502-3ab8-4530-aae3-add272af2acb
		summarizeBy: none
		sourceColumn: Report_Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report_Number

		annotation PBI_WasHiddenAtRefresh = False

	column Report_Year
		dataType: string
		lineageTag: ad8e53a4-085d-4527-b08a-65707551ed35
		summarizeBy: none
		sourceColumn: Report_Year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report_Year

		annotation PBI_WasHiddenAtRefresh = False

	column Organisation_Type
		dataType: string
		lineageTag: 86f4ca3e-864f-4bf1-b9f4-8fa50a824312
		summarizeBy: none
		sourceColumn: Organisation_Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Organisation_Type

		annotation PBI_WasHiddenAtRefresh = False

	column Organisation_Code
		dataType: string
		lineageTag: 06eea9e0-389d-4020-b055-d7f344e98343
		summarizeBy: none
		sourceColumn: Organisation_Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Organisation_Code

		annotation PBI_WasHiddenAtRefresh = False

	column Current_Status
		dataType: string
		lineageTag: f8ad526b-1684-40ce-b50c-e878366bdae3
		summarizeBy: none
		sourceColumn: Current_Status

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Current_Status

		annotation PBI_WasHiddenAtRefresh = False

	column File_Name
		dataType: string
		lineageTag: cb9c4b37-cdc6-43f9-adef-792ca649fdce
		summarizeBy: none
		sourceColumn: File_Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = File_Name

		annotation PBI_WasHiddenAtRefresh = False

	column Data_Status
		dataType: string
		lineageTag: c548b02b-2b0c-45a6-911c-5f47f6139f71
		summarizeBy: none
		sourceColumn: Data_Status

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Data_Status

		annotation PBI_WasHiddenAtRefresh = False

	column Submission_Number
		dataType: int64
		formatString: 0
		lineageTag: c11ec308-f13d-41f0-bd34-1db8a5eaa93c
		summarizeBy: sum
		sourceColumn: Submission_Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Submission_Number

		annotation PBI_WasHiddenAtRefresh = False

	column File_Load_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: f422f308-445b-41fa-86b8-71bdf8ed0740
		summarizeBy: none
		sourceColumn: File_Load_Date

		variation Variation
			isDefault
			relationship: b75318f7-ef5e-4b0b-bc8d-706b5ecc0ec1
			defaultHierarchy: LocalDateTable_9c407f07-ff03-4ff8-9125-a0772167c2a1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = File_Load_Date

		annotation PBI_WasHiddenAtRefresh = False

	column Report_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: ddcd3013-ab8c-4163-9834-3b73522b7987
		summarizeBy: none
		sourceColumn: Report_Date

		variation Variation
			isDefault
			relationship: b72896e5-b93f-4ee0-b830-fcde9b2863cb
			defaultHierarchy: LocalDateTable_c823369d-29b9-4697-af4e-018e1e598def.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation PBI_NameAtRefresh = Report_Date

		annotation PBI_WasHiddenAtRefresh = False

	column Extract_Type
		dataType: string
		lineageTag: 70226c6b-1d0f-479e-8765-b9714e2df1e5
		summarizeBy: none
		sourceColumn: Extract_Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Extract_Type

		annotation PBI_WasHiddenAtRefresh = False

	column Total_Patients
		dataType: int64
		formatString: 0
		lineageTag: bbdca433-1cec-43fe-ba19-21a25385b696
		summarizeBy: sum
		sourceColumn: Total_Patients

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Total_Patients

		annotation PBI_WasHiddenAtRefresh = False

	column FinancialYear
		dataType: string
		lineageTag: 2ef9ecd2-0ab7-4f60-895e-c400b7aab6d4
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = FinancialYear

		annotation PBI_WasHiddenAtRefresh = False

	column Month
		dataType: string
		lineageTag: 75e5d023-250c-44cd-af59-abe0d13fa3db
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Month

		annotation PBI_WasHiddenAtRefresh = False

	column FinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 1f87c8e9-4831-48c3-ae70-f5946f50a823
		summarizeBy: sum
		sourceColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = FinancialMonth

		annotation PBI_WasHiddenAtRefresh = False

	partition '104 Day-d9ba8f23-7f70-429e-8fe0-cbd7b52e3eab' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Data_Mart_Performance", [Query="SELECT [ID]#(lf)      ,[Care]#(lf)      ,[Tumour_Type]#(lf)      ,[First_Seen_Provider]#(lf)      ,[First_Treatment_Provider]#(lf)      ,[Patient_CWT_Ref]#(lf)      ,[Wait_Days]#(lf)      ,[Delay_Reason_Code]#(lf)      ,[Report_Number]#(lf)      ,[Report_Year]#(lf)      ,LEFT([Report_Month],3) [Month]#(lf)      ,[Organisation_Type]#(lf)      ,[Organisation_Code]#(lf)      ,[Current_Status]#(lf)      ,[File_Name]#(lf)      ,[Data_Status]#(lf)      ,[Submission_Number]#(lf)      ,[File_Load_Date]#(lf)      ,[Report_Date]#(lf)      ,[Extract_Type]#(lf)#(tab)  ,1 AS [Total_Patients]#(lf)#(tab)  ,b.[FinancialYear]#(lf)#(tab)  ,b.[FinancialMonth]#(lf)  FROM [Data_Mart_Performance].[dbo].[Cancer_62_Day_Exceptions] a#(lf)  LEFT JOIN  [CCG_Reference].[Reference].[vw_DateLookup] b on a.[Report_Date] = b.[Date]#(lf)  WHERE [Wait_Days] >= '104'#(lf)  AND [Extract_Type] = 'Monthly'#(lf)  AND [Report_Date] >= '20190401'"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"FinancialMonth", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

