table '28 Day'
	lineageTag: d7cc0c22-4fb9-493f-8503-6b34c1bf7d87

	measure '28 Day Performance' = (SUM('28 Day'[Total Patients])-SUM('28 Day'[Breaches]))/(SUM('28 Day'[Total Patients]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 65dc6e21-2142-465b-b54b-e82616f7f5b1

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure '28 Day Target %' = MIN('28 Day'[Target])
		lineageTag: 58e629fe-cb8b-4a60-8665-c442ab19c691

		annotation Format = <Format Format="General" />

	measure '28 Day Target Checker' = IF('28 Day'[28 Day Performance] >= '28 Day'[28 Day Target %], "#63BE7B","#F8696B")
		lineageTag: b00b16ca-cac3-42fe-ae5d-19c7d26224ee

		annotation Format = <Format Format="Text" />

	column Type
		dataType: string
		lineageTag: 58209a93-101e-4811-9b9f-b6e472acac0b
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Type

		annotation PBI_WasHiddenAtRefresh = False

	column 'First Seen Provider Code'
		dataType: string
		lineageTag: baed7554-5282-406e-b615-bc96f6565578
		summarizeBy: none
		sourceColumn: First Seen Provider Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First Seen Provider Code

		annotation PBI_WasHiddenAtRefresh = False

	column 'First Seen Provider Group'
		dataType: string
		lineageTag: ccb0d2e9-a457-446e-9e80-d4937d4bc2d8
		summarizeBy: none
		sourceColumn: First Seen Provider Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First Seen Provider Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'Tumour Type'
		dataType: string
		lineageTag: 3ac5031b-f043-4f05-931a-02ca77aad3de
		summarizeBy: none
		sourceColumn: Tumour Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Tumour Type

		annotation PBI_WasHiddenAtRefresh = False

	column 'Tumour Group'
		dataType: string
		lineageTag: fa5ecad6-66b9-4cd5-83da-f7656d447729
		summarizeBy: none
		sourceColumn: Tumour Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Tumour Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'Total Patients'
		dataType: int64
		formatString: 0
		lineageTag: 18c32f51-99b1-47ce-b29f-de706c121542
		summarizeBy: sum
		sourceColumn: Total Patients

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Total Patients

		annotation PBI_WasHiddenAtRefresh = False

	column Breaches
		dataType: int64
		formatString: 0
		lineageTag: 8813d5b7-6c91-4dde-b2d8-0e2510840454
		summarizeBy: sum
		sourceColumn: Breaches

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Breaches

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Number'
		dataType: double
		lineageTag: 2154067e-09a9-4541-8e0c-da2c2f7e6a7a
		summarizeBy: sum
		sourceColumn: Report Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Report Number

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Name'
		dataType: string
		lineageTag: 00f4aeff-dcd6-4138-a3bc-f2a0206abcca
		summarizeBy: none
		sourceColumn: Report Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report Name

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Year'
		dataType: string
		lineageTag: 87b8378f-9d4b-4844-be94-ef5088fa39a8
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Financial Year

		annotation PBI_WasHiddenAtRefresh = False

	column Month
		dataType: string
		lineageTag: d69173ca-da73-4217-858b-27a03c2f445e
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Financial Month'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Month'
		dataType: int64
		formatString: 0
		lineageTag: 2f5f470f-9208-4f25-96f4-38bf73bf10f1
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Financial Month

		annotation PBI_WasHiddenAtRefresh = False

	column Target = 0.75
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9ce0bc2b-f436-4a75-b0a7-a15a92244182
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Percentage" Accuracy="1" />

		annotation DataTypeAtRefresh = Double#####not a type

	partition '28 Day-b49290f1-728c-4371-8cac-ee248cbab78a' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Data_Mart_Performance", [Query="-----------------------#(lf)--- 28 DAY STANDARD ---#(lf)-----------------------#(lf)#(lf)SELECT [Type] = '28 Day'#(lf)      ,[First_Seen_Provider] [First Seen Provider Code]#(lf)#(tab)  ,CASE WHEN [First_Seen_Provider] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [First Seen Provider Group]#(lf)      ,[Urgent_Suspected_Cancer_Type] [Tumour Type]#(lf)#(tab)  #(tab)  ,CASE WHEN [Urgent_Suspected_Cancer_Type] = 'acute leukaemia' THEN 'Suspected Acute Leukaemia'#(lf)#(tab)        WHEN [Urgent_Suspected_Cancer_Type] LIKE '%brain%' THEN 'Suspected Brain / Central Nervous System'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%cancer not initially suspected%' THEN 'Non-Cancer Breast Symptoms'#(lf)#(tab)#(tab)    WHEN [Urgent_Suspected_Cancer_Type] LIKE '%breast%' THEN 'Suspected Breast'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%children%' THEN 'Suspected Childrens Cancer'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%gynaecological%' THEN 'Suspected Gynaecological'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%Suspected haematological malignancies excluding acute leukaemia%' THEN 'Suspected Haematological Malignancies'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%Head and Neck%' THEN 'Suspected Head and Neck'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%lower gastrointestinal%' THEN 'Suspected Lower Gastrointestinal'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%lung%' THEN 'Suspected Lung'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%other%' THEN 'Suspected Other'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%sarcoma%' THEN 'Suspected Sarcoma'#(tab)   #(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%skin%' THEN 'Suspected Skin'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%suspected testicular%' THEN 'Suspected Testicular'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%upper gastrointestinal%' THEN 'Suspected Upper Gastrointestinal'#(lf)#(tab)#(tab)#(tab)WHEN [Urgent_Suspected_Cancer_Type] LIKE '%Suspected urological cancers (excluding testicular)%' THEN 'Suspected Urological'#(lf)#(tab)#(tab)#(tab)ELSE 'Unknown' END AS [Tumour Group]#(lf)#(tab)  ,[No_Of_Patients] [Total Patients]#(lf)#(tab)  ,[Breaches] = ([Days_29_To_38]+[Days_39_To_62]+[Days_63_And_More])#(lf)      ,[Report_Number] [Report Number]#(lf)     #(tab)  ,CASE WHEN [Report_Number] = '18.1' THEN '18.1 28 Day Two Week Wait'#(lf)#(tab)            WHEN [Report_Number] = '18.2' THEN '18.2 28 Day Two Week Wait Non-Cancer Breast Symptoms'#(lf)#(tab)#(tab)#(tab)    WHEN [Report_Number] = '18.3' THEN '18.3 28 Day Screening'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Report Name]#(lf)#(tab)  ,[B].[FinancialYear] [Financial Year]#(lf)      ,LEFT([Report_Month],3) as [Month]#(lf)#(tab)  ,[B].[FinancialMonth] [Financial Month]#(lf)#(lf)  FROM [Data_Mart_Performance].[dbo].[Cancer_28_Day_Aggregate_Data] a#(lf)  LEFT JOIN  [CCG_Reference].[Reference].[vw_DateLookup] b on a.[Report_Date] = b.[Date]#(lf)  WHERE [Report_Date] > '20190331'#(lf)  AND [Extract_Type] = 'Monthly'"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Financial Month", Int64.Type}, {"Report Number", type number}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

