table '31 Day'
	lineageTag: 00239f83-867f-4520-b47f-d8cde677efe6

	measure '31 Day Performance' = (SUM('31 Day'[Total Treated])-SUM('31 Day'[Breaches]))/SUM('31 Day'[Total Treated])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 41fe505b-fddc-48cf-8e51-476c08e43c48

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure '31 Day Target %' = MIN('31 Day'[Target])
		lineageTag: 54b94189-ccf3-43fa-bfa9-d67e8b2b11e6

		annotation Format = <Format Format="General" />

	measure '31 Day Target Checker' = IF('31 Day'[31 Day Performance] >= '31 Day'[31 Day Target %], "#63BE7B","#F8696B")
		lineageTag: fabdf4b2-d722-43e8-9710-d7b1590976a8

		annotation Format = <Format Format="Text" />

	column 'Standard Group'
		dataType: string
		lineageTag: 2e30c670-023c-47f7-8643-2b88b3b371af
		summarizeBy: none
		sourceColumn: Standard Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Standard Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'Provider Code'
		dataType: string
		lineageTag: 2e6f7a0b-43b9-4773-9223-e4149dbacf3f
		summarizeBy: none
		sourceColumn: Provider Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Provider Code

		annotation PBI_WasHiddenAtRefresh = False

	column 'Provider Group'
		dataType: string
		lineageTag: e9b882da-e839-444e-9890-41d7fc5a3a90
		summarizeBy: none
		sourceColumn: Provider Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Provider Group

		annotation PBI_WasHiddenAtRefresh = False

	column Type
		dataType: string
		lineageTag: 85055fa4-23b8-4302-a62d-1517d4296dab
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Type

		annotation PBI_WasHiddenAtRefresh = False

	column 'Total Treated'
		dataType: int64
		formatString: 0
		lineageTag: 14c14fba-d419-44b4-b412-ef9ae324f87f
		summarizeBy: sum
		sourceColumn: Total Treated

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Total Treated

		annotation PBI_WasHiddenAtRefresh = False

	column Breaches
		dataType: int64
		formatString: 0
		lineageTag: 5583d149-8b12-4af9-aac0-aada286c8dff
		summarizeBy: sum
		sourceColumn: Breaches

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Breaches

		annotation PBI_WasHiddenAtRefresh = False

	column Performance
		dataType: double
		lineageTag: 22f65605-9187-4afb-ab1b-d3bafda1614c
		summarizeBy: sum
		sourceColumn: Performance

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Performance

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Number'
		dataType: double
		lineageTag: 1b99b59e-f295-4003-8310-370a3a9261ce
		summarizeBy: sum
		sourceColumn: Report Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Report Number

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Name'
		dataType: string
		lineageTag: e67b95e5-0b5e-43bc-81cb-1a61685b8d7e
		summarizeBy: none
		sourceColumn: Report Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report Name

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Year'
		dataType: string
		lineageTag: 5cf5ff9a-d076-4272-b7c5-90623f69498e
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Financial Year

		annotation PBI_WasHiddenAtRefresh = False

	column Month
		dataType: string
		lineageTag: 12d99a7b-46ac-407a-9fab-89d868a55157
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Financial Month'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Month'
		dataType: int64
		formatString: 0
		lineageTag: 5bca9f59-3d30-472c-9f97-3edd0c4b51f2
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Financial Month

		annotation PBI_WasHiddenAtRefresh = False

	column Target
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: d6583397-f038-406f-833b-b808c094e0f3
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Target

		annotation PBI_WasHiddenAtRefresh = False

		annotation Format = <Format Format="Percentage" Accuracy="0" />

	partition '31 Day-7ae55095-11bb-4b7c-9f99-facf98f9280f' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Data_Mart_Performance", [Query="------------------------------------#(lf)--- 31 DAY TUMOUR GROUP STANDARD ---#(lf)------------------------------------#(lf)#(lf)SELECT [Standard Group] = '31 Day Tumour'#(lf)      ,[Provider_Code] [Provider Code]#(lf)#(tab)  ,CASE WHEN [Provider_Code] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [Provider Group]#(lf)      ,[Tumour_Type] [Type]#(lf)#(tab)  ,[Total_Treated] [Total Treated]#(lf)#(tab)  ,[Treated_After_31_Days] [Breaches]#(lf)      ,CASE WHEN [Report_Number] = '7.4' THEN '96%'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Target]#(lf)      ,[%_Meeting_Standard] [Performance]#(lf)      ,[Report_Number] [Report Number]#(lf)#(tab)  ,CASE WHEN [Report_Number] = '7.4' THEN '7.4 - 31 Day First Treatment'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Report Name]#(lf)#(tab)  ,[B].[FinancialYear] [Financial Year]#(lf)      ,LEFT([Report_Month],3) as [Month]#(lf) #(tab)  ,[B].[FinancialMonth] [Financial Month]#(lf) #(lf)  FROM [Data_Mart_Performance].[dbo].[Cancer_31_Day_Aggregate_Data] [A]#(lf)  LEFT JOIN  [CCG_Reference].[Reference].[vw_DateLookup] [B] ON [A].[Report_Date] = [B].[Date]#(lf)  WHERE [Report_Date] > '20190331'#(lf)  AND [Extract_Type] = 'Monthly'#(lf)#(lf)  UNION ALL#(lf)#(lf)---------------------------------------#(lf)--- 31 DAY TREATMENT GROUP STANDARD ---#(lf)---------------------------------------#(lf)#(lf)  SELECT [Standard Group] = '31 Day Treatment'#(lf)      ,[Provider_Code] [Provider Code]#(lf)#(tab)  ,CASE WHEN [Provider_Code] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [Provider Group]#(lf)      ,[Treatment_Group] [Type]#(lf)#(tab)  ,[Total_Treated] [Total Treated]#(lf)#(tab)  ,[Treated_After_31_Days] [Breaches]#(lf)#(tab)  ,CASE WHEN [Report_Number] = '7.11' AND [Treatment_Group] = 'Radiotherapy Treatments'THEN '94%'#(lf)#(tab)  #(tab)    WHEN [Report_Number] = '7.11' AND [Treatment_Group] = 'Surgery'THEN '94%'#(lf)#(tab)        WHEN [Report_Number] = '7.11' AND [Treatment_Group] = 'Drug Treatments'THEN '98%'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Target]#(lf)      ,[%_Meeting_Standard] [Performance]#(lf)      ,[Report_Number] [Report Number]#(lf)#(tab)  ,CASE WHEN [Report_Number] = '7.11' THEN '7.11 - 31 Day Subsequent Treatment'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Report Name]#(lf)#(tab)  ,[B].[FinancialYear] [Financial Year]#(lf)      ,LEFT([Report_Month],3) as [Month]#(lf)#(tab)  ,[B].[FinancialMonth] [Financial Month]#(lf)#(lf)  FROM [Data_Mart_Performance].[dbo].[Cancer_31_Day_Treatment_Aggregate_Data] [A]#(lf)  LEFT JOIN  [CCG_Reference].[Reference].[vw_DateLookup] [B] ON [A].[Report_Date] = [B].[Date]#(lf)  WHERE [Report_Date] > '20190331'#(lf)  AND [Extract_Type] = 'Monthly'"]),
				    #"Changed Type2" = Table.TransformColumnTypes(Source,{{"Target", Percentage.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type2",{{"Financial Month", Int64.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"Report Number", type number}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

