table '62 Day'
	lineageTag: 0108c60b-cfa6-4393-992a-3cbbaf1b2ec6

	measure '62 Day Performance' = (SUM('62 Day'[Total Treated])-SUM('62 Day'[Breaches]))/SUM('62 Day'[Total Treated])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 301b85ae-9423-4f3b-8dbe-ee890fc895e0

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure '62 Day Target %' = MIN('62 Day'[Target])
		lineageTag: c2efc5bb-5de7-4ede-b83c-7141663b247f

		annotation Format = <Format Format="General" />

	measure '62 Day Target Checker' = IF('62 Day'[62 Day Performance]>= '62 Day'[62 Day Target %], "#63BE7B","#F8696B")
		lineageTag: 7cdfc783-b365-40f3-97e9-23e956144865

		annotation Format = <Format Format="Text" />

	column 'Standard Group'
		dataType: string
		lineageTag: bd22d8a1-94be-4a61-bb57-5e46a1c4bd69
		summarizeBy: none
		sourceColumn: Standard Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Standard Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'First Seen Provider'
		dataType: string
		lineageTag: c4d57b68-2d64-4f40-bf7f-5e616df40633
		summarizeBy: none
		sourceColumn: First Seen Provider

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First Seen Provider

		annotation PBI_WasHiddenAtRefresh = False

	column 'First Seen Provider Group'
		dataType: string
		lineageTag: 76e238dd-2590-4d0c-bbde-62c3f50755e4
		summarizeBy: none
		sourceColumn: First Seen Provider Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First Seen Provider Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'First Treatment Provider'
		dataType: string
		lineageTag: d2d80eae-ba32-49d2-ac59-032568acee28
		summarizeBy: none
		sourceColumn: First Treatment Provider

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First Treatment Provider

		annotation PBI_WasHiddenAtRefresh = False

	column 'First Treatment Provider Group'
		dataType: string
		lineageTag: d0fc1bba-7589-4c8b-82f9-4c8237223b90
		summarizeBy: none
		sourceColumn: First Treatment Provider Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = First Treatment Provider Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'Consultant Upgrade Provider'
		dataType: string
		lineageTag: 0efc2e16-6ab8-4c57-9ea7-626de6414574
		summarizeBy: none
		sourceColumn: Consultant Upgrade Provider

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Consultant Upgrade Provider

		annotation PBI_WasHiddenAtRefresh = False

	column 'Consultant Upgrade Provider Group'
		dataType: string
		lineageTag: 3c0196ff-3559-460e-a244-be2b619bfee5
		summarizeBy: none
		sourceColumn: Consultant Upgrade Provider Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Consultant Upgrade Provider Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'Tumour Type'
		dataType: string
		lineageTag: 74d0a034-1f37-4711-868e-03e40ceee665
		summarizeBy: none
		sourceColumn: Tumour Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Tumour Type

		annotation PBI_WasHiddenAtRefresh = False

	column Breaches
		dataType: int64
		formatString: 0
		lineageTag: 027a3d8e-ce3a-4e68-a335-7d70600391e3
		summarizeBy: sum
		sourceColumn: Breaches

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Breaches

		annotation PBI_WasHiddenAtRefresh = False

	column Performance
		dataType: double
		lineageTag: 3ea16802-090e-4207-9631-d273e7092127
		summarizeBy: sum
		sourceColumn: Performance

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Performance

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Number'
		dataType: double
		lineageTag: dbfafa3f-c573-4773-bd60-2c5699fffd47
		summarizeBy: sum
		sourceColumn: Report Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report Number

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Name'
		dataType: string
		lineageTag: ec442260-030e-425d-bd70-af0578e60bfb
		summarizeBy: none
		sourceColumn: Report Name
		sortByColumn: 'Report Number'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report Name

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Year'
		dataType: string
		lineageTag: da18108b-e382-43d8-b3d7-d35788e9d476
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Financial Year

		annotation PBI_WasHiddenAtRefresh = False

	column Month
		dataType: string
		lineageTag: 2a0f00f6-b098-41d2-9030-60afcbd3b0a6
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Financial Month'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Month'
		dataType: int64
		formatString: 0
		lineageTag: 9912f23f-6c3a-4eeb-96e6-93a1a8672a83
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Financial Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Total Treated'
		dataType: int64
		formatString: 0
		lineageTag: 116a92be-dd1b-44ca-a144-da1c85cd48f5
		summarizeBy: sum
		sourceColumn: Total Treated

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Total Treated

		annotation PBI_WasHiddenAtRefresh = False

	column Target
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: 0370be53-895a-46c5-9604-21d382a5be3e
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Target

		annotation PBI_WasHiddenAtRefresh = False

		annotation Format = <Format Format="Percentage" Accuracy="0" />

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: f3db4291-9b7d-49a2-8668-2a98bca2d1c6
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Quarter

		annotation PBI_WasHiddenAtRefresh = False

	partition '62 Day-80ac8849-ab86-4476-8179-ad2a3cb4d4b9' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Data_Mart_Performance", [Query="-----------------------#(lf)--- 62 DAY STANDARD ---#(lf)-----------------------#(lf)#(lf)SELECT [Standard Group] = '62 Day'#(lf)      ,[First_Seen_Provider] [First Seen Provider]#(lf)#(tab)  ,CASE WHEN [First_Seen_Provider] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [First Seen Provider Group]#(lf)      ,[First_Treatment_Provider] [First Treatment Provider]#(lf)#(tab)  ,CASE WHEN [First_Treatment_Provider] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [First Treatment Provider Group]#(lf)      ,[Consultant Upgrade Provider] = NULL#(tab)  #(lf)#(tab)  ,[Consultant Upgrade Provider Group] = null#(lf)      ,[Tumour_Type] [Tumour Type]#(lf)      ,[Actual_Total_Treated] [Total Treated]#(lf)#(tab)  ,[Total_Over_Target_Accountable_Provider_62_Day_Wait] [Breaches] #(lf)#(tab)  ,CASE WHEN [Report_Number] = '8.4' THEN '85%'#(lf)#(tab)        WHEN [Report_Number] = '9.4' THEN '90%'#(lf)#(tab)        WHEN [Report_Number] = '8.8' THEN 'Unknown'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Target]#(lf)      ,[%_Meeting_Standard] [Performance]#(lf)      ,[Report_Number] [Report Number]#(lf)#(tab)  ,CASE WHEN [Report_Number] = '8.4' THEN '8.4 - 62 Day Wait'#(lf)#(tab)        WHEN [Report_Number] = '9.4' THEN '9.4 - 62 Day Screening '#(lf)#(tab)        WHEN [Report_Number] = '8.8' THEN '8.8 31 Day Rare Cancer '#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Report Name]#(lf)#(tab)  ,[B].[FinancialYear] [Financial Year]#(lf)      ,LEFT([Report_Month],3) as [Month]#(lf) #(tab)  ,[B].[FinancialMonth] [Financial Month]#(lf)#(tab)  ,[B].[Quarter] [Quarter]#(lf)  #(lf)  FROM [Data_Mart_Performance].[dbo].[Cancer_62_Day_Aggregate_Data] [A]#(lf)  LEFT JOIN  [CCG_Reference].[Reference].[vw_DateLookup] [B] ON [A].[Report_Date] = [B].[Date]#(lf)  WHERE [Report_Date] > '20190331'#(lf)  AND [Extract_Type] = 'Monthly'#(lf) #(lf) UNION ALL#(lf)#(lf)-------------------------------#(lf)--- 62 DAY UPGRADE STANDARD ---#(lf)-------------------------------#(lf)#(lf)SELECT [Standard Group] = '62 Day Upgrade'#(lf)      ,[First Seen Provider] = NULL#(lf)#(tab)  ,[First Seen Provider Group] = NULL#(lf)      ,[First_Treatment_Provider] [First Treatment Provider]#(lf)#(tab)  ,CASE WHEN [First_Treatment_Provider] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [First Treatment Provider Group]#(lf)      ,[Consultant_Upgrade_Provider]  [Consultant Upgrade Provider]#(lf)#(tab)  ,CASE WHEN [Consultant_Upgrade_Provider] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [Consultant Upgrade Provider Group]#(lf)      ,[Tumour_Type] [Tumour Type]#(lf)      ,[Actual_Total_Treated] [Total Treated]#(lf)#(tab)  ,[Total_Over_Target_Accountable_Provider_62_Day_Wait] [Breaches] #(lf)#(tab)  ,CASE WHEN [Report_Number] = '10.4' THEN '85%'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Target]#(lf)      ,[%_Meeting_Standard] [Performance]#(lf)      ,[Report_Number] [Report Number]#(lf)#(tab)  ,CASE WHEN [Report_Number] = '10.4' THEN '10.4 62 Day Upgrade'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Report Name]#(lf)#(tab)  ,[B].[FinancialYear] [Financial Year]#(lf)      ,LEFT([Report_Month],3) as [Month]#(lf)#(tab)  ,[B].[FinancialMonth] [Financial Month]#(lf)#(tab)  ,[B].[Quarter] [Quarter]#(lf)#(lf) #(lf)  FROM [Data_Mart_Performance].[dbo].[Cancer_62_Day_Upgrade_Aggregate_Data] [A]#(lf)  LEFT JOIN  [CCG_Reference].[Reference].[vw_DateLookup] [B] ON [A].[Report_Date] = [B].[Date]#(lf)  WHERE [Report_Date] > '20190331'#(lf)  AND [Extract_Type] = 'Monthly'"]),
				    #"Changed Type1" = Table.TransformColumnTypes(Source,{{"Quarter", Int64.Type}, {"Financial Month", Int64.Type}, {"Target", Percentage.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"Financial Month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

