table date_reference
	lineageTag: b3b4932a-619f-44a0-b3a4-d7fd5dcb1003

	column date
		dataType: dateTime
		formatString: dd mmmm yyyy
		lineageTag: dfea1b5b-fef5-4277-b559-e60741e4ba2e
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: da9e0a56-c41f-42e3-af06-e25410d428e5
			defaultHierarchy: LocalDateTable_f4f9446e-115a-4149-8e99-c005daf9292c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="2057" Group="LongDate" FormatString="dd MMMM yyyy" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####Date

		annotation PBI_NameAtRefresh = date

		annotation PBI_WasHiddenAtRefresh = False

	column week_day
		dataType: string
		lineageTag: d9604966-a38b-4321-8e14-d8fad208276a
		summarizeBy: none
		sourceColumn: week_day

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = week_day

		annotation PBI_WasHiddenAtRefresh = False

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: e977f889-a5e0-47b8-8080-7afdb5b7dba5
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = day_of_week

		annotation PBI_WasHiddenAtRefresh = False

	column day_of_year
		dataType: int64
		formatString: 0
		lineageTag: e5145e9e-1f77-4518-bbfd-e7e3d15cc43e
		summarizeBy: sum
		sourceColumn: day_of_year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = day_of_year

		annotation PBI_WasHiddenAtRefresh = False

	column week_of_month
		dataType: int64
		formatString: 0
		lineageTag: 90c29187-9433-4b55-a7ac-ef788efed0cd
		summarizeBy: sum
		sourceColumn: week_of_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = week_of_month

		annotation PBI_WasHiddenAtRefresh = False

	column month_name
		dataType: string
		lineageTag: 81b5a7d2-fc1c-406d-9a34-fbb8cca84553
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = month_name

		annotation PBI_WasHiddenAtRefresh = False

	column year
		dataType: int64
		formatString: 0
		lineageTag: 7f69a78b-a7b9-4c15-a8d4-3b27f1cd491e
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = year

		annotation PBI_WasHiddenAtRefresh = False

	column year_month
		dataType: string
		lineageTag: 9e23ea67-b7a3-4036-9eab-b8fe36f3bdec
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = year_month

		annotation PBI_WasHiddenAtRefresh = False

	column financial_week
		dataType: int64
		formatString: 0
		lineageTag: 0dcfdfd1-c76b-40b0-922c-47310e17def9
		summarizeBy: sum
		sourceColumn: financial_week

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = financial_week

		annotation PBI_WasHiddenAtRefresh = False

	column financial_year
		dataType: string
		lineageTag: 7ba74e38-3f67-4cab-b5b5-1e9145d6992f
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = financial_year

		annotation PBI_WasHiddenAtRefresh = False

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 7e47121e-f417-4b3f-8458-f276a0bec935
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = financial_quarter

		annotation PBI_WasHiddenAtRefresh = False

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: eff5f86e-dbea-47e3-91e2-189b8df57729
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = financial_month

		annotation PBI_WasHiddenAtRefresh = False

	partition date_reference-78428492-341b-4170-9e17-1f11eedebb44 = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "CCG_Reference", [Query="SELECT [Date] [date]#(lf)      ,[WeekDayName] [week_day]#(lf)      ,[DayofWeekInMonth] [day_of_week]#(lf)      ,[DayOfYear] [day_of_year]#(lf)      ,[WeekOfMonth] [week_of_month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Year] [year]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[FinancialWeekofYear] [financial_week]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf) #(lf)  FROM [CCG_Reference].[Reference].[vw_DateLookup]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_of_year", Int64.Type}, {"day_of_week", Int64.Type}, {"date", type date}, {"week_of_month", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

