table 'Two Week Wait'
	lineageTag: 47554672-258c-4206-823f-163625564fbc

	measure 'Two Week Wait Performance' = (SUM('Two Week Wait'[Total Referrals])-SUM('Two Week Wait'[Breaches]))/SUM('Two Week Wait'[Total Referrals])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1d00ec46-5578-4af4-b1c7-fc63f0a5f7ae

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure '2WW Target %' = MIN('Two Week Wait'[Target])
		lineageTag: 7bf585ca-600c-435c-aecf-dc5e39af869c

		annotation Format = <Format Format="General" />

	measure '2WW Target Checker' = IF('Two Week Wait'[Two Week Wait Performance] >= 'Two Week Wait'[2WW Target %], "#63BE7B","#F8696B")
		lineageTag: 56892b3b-db4d-4165-b1e6-52c99a11f7f8

		annotation Format = <Format Format="Text" />

	column Type
		dataType: string
		lineageTag: 3126b0b4-026f-45e5-b8cf-92baf7546f5c
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Type

		annotation PBI_WasHiddenAtRefresh = False

	column 'Provider Code'
		dataType: string
		lineageTag: 46acfc01-99d0-4c43-83ec-2b586febfb1e
		summarizeBy: none
		sourceColumn: Provider Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Provider Code

		annotation PBI_WasHiddenAtRefresh = False

	column 'Provider Group'
		dataType: string
		lineageTag: ec5806f2-4153-40f9-bd74-8b791da39a51
		summarizeBy: none
		sourceColumn: Provider Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Provider Group

		annotation PBI_WasHiddenAtRefresh = False

	column 'Tumour Type'
		dataType: string
		lineageTag: 1a2b822f-d224-4ad5-8948-a4ed8b478d08
		summarizeBy: none
		sourceColumn: Tumour Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Tumour Type

		annotation PBI_WasHiddenAtRefresh = False

	column 'Tumour Group'
		dataType: string
		lineageTag: 1edf68ef-2198-4a00-bb20-561a45a74774
		summarizeBy: none
		sourceColumn: Tumour Group

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Tumour Group

		annotation PBI_WasHiddenAtRefresh = False

	column Breaches
		dataType: int64
		formatString: 0
		lineageTag: e51a1a53-e015-4b59-ae7d-48750e0f3bc8
		summarizeBy: sum
		sourceColumn: Breaches

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Breaches

		annotation PBI_WasHiddenAtRefresh = False

	column Performance
		dataType: double
		lineageTag: 7a1bcb0e-4b97-4260-aefd-a3457105f2e9
		summarizeBy: sum
		sourceColumn: Performance

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Performance

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Number'
		dataType: double
		lineageTag: dd993686-2c8a-4d3f-8c9d-ccb78c2966fb
		summarizeBy: sum
		sourceColumn: Report Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Report Number

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Name'
		dataType: string
		lineageTag: d5ea5f7e-fc5e-422a-8f46-87761512c635
		summarizeBy: none
		sourceColumn: Report Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report Name

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Year'
		dataType: string
		lineageTag: b746fcab-0ffd-4c27-aa9d-d1768d4e6bd4
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Financial Year

		annotation PBI_WasHiddenAtRefresh = False

	column Month
		dataType: string
		lineageTag: 25173f03-898e-4f6f-9761-918ba8bcc22e
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Financial Month'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Financial Month'
		dataType: int64
		formatString: 0
		lineageTag: 901919ac-7600-4f32-8658-e1e2bbe3d036
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Financial Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Total Referrals'
		dataType: int64
		formatString: 0
		lineageTag: db52f840-1eca-4b00-a35b-faed42dc8fdc
		summarizeBy: sum
		sourceColumn: Total Referrals

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Total Referrals

		annotation PBI_WasHiddenAtRefresh = False

	column Target
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: bd148c28-cdaa-4823-9425-a0b197bb846f
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = Target

		annotation PBI_WasHiddenAtRefresh = False

		annotation Format = <Format Format="Percentage" Accuracy="0" />

	partition 'Two Week Wait-7db293eb-814f-4173-88fd-8638f97498b6' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "Data_Mart_Performance", [Query="------------------------------#(lf)--- TWO WEEK WAIT STANDARD ---#(lf)------------------------------#(lf)#(lf)SELECT [Type] = '2WW'#(lf)      ,[Provider_Code] [Provider Code]#(lf)#(tab)  ,CASE WHEN [Provider_Code] = 'RTE' THEN 'Gloucestershire Hospitals NHS Foundation Trust'#(lf)            ELSE 'Other Provider' END AS [Provider Group]#(lf)      ,[Tumour_Type] [Tumour Type]#(lf)#(tab)  ,CASE WHEN [Tumour_Type] = 'acute leukaemia' THEN 'Suspected Acute Leukaemia'#(lf)#(tab)        WHEN [Tumour_Type] LIKE '%brain%' THEN 'Suspected Brain / Central Nervous System'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%cancer not initially suspected%' THEN 'Non-Cancer Breast Symptoms'#(lf)#(tab)#(tab)    WHEN [Tumour_Type] LIKE '%breast%' THEN 'Suspected Breast'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%children%' THEN 'Suspected Childrens Cancer'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%gynaecological%' THEN 'Suspected Gynaecological'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%Suspected haematological malignancies excluding acute leukaemia%' THEN 'Suspected Haematological Malignancies'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%Head and Neck%' THEN 'Suspected Head and Neck'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%lower gastrointestinal%' THEN 'Suspected Lower Gastrointestinal'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%lung%' THEN 'Suspected Lung'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%other%' THEN 'Suspected Other'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%sarcoma%' THEN 'Suspected Sarcoma'#(tab)   #(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%skin%' THEN 'Suspected Skin'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%suspected testicular%' THEN 'Suspected Testicular'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%upper gastrointestinal%' THEN 'Suspected Upper Gastrointestinal'#(lf)#(tab)#(tab)#(tab)WHEN [Tumour_Type] LIKE '%Suspected urological cancers (excluding testicular)%' THEN 'Suspected Urological'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Tumour Group]#(lf)      ,[Total_Referrals_Seen_During_The_Period] [Total Referrals]#(lf)#(tab)  ,[Breaches] = ([Seen_15_To_16_Days]+[Seen_17_To_21_Days]+[Seen_22_To_28_Days]+[Seen_After_28_Days])#(lf)#(tab)  ,[Target] = '93%'#(lf)      ,[%_Meeting_Standard] [Performance]#(lf)      ,[Report_Number] [Report Number]#(lf)#(tab)  ,CASE WHEN [Report_Number] = '6.3' THEN '6.3 - Two Week Wait'#(lf)#(tab)        WHEN [Report_Number] = '6.4' THEN '6.4 - Breast Symptom Two Week Wait'#(lf)#(tab)#(tab)#(tab)ELSE 'ERROR' END AS [Report Name]#(lf)#(tab)  ,[B].[FinancialYear] [Financial Year]#(lf)      ,LEFT([Report_Month],3) as [Month]#(lf)#(tab)  ,[B].[FinancialMonth] [Financial Month]#(lf)#(lf)  FROM [Data_Mart_Performance].[dbo].[Cancer_2_Week_Aggregate_Data] [A]#(lf)  LEFT JOIN  [CCG_Reference].[Reference].[vw_DateLookup] [B] on [A].[Report_Date] = [B].[Date]#(lf)  WHERE [Report_Date] > '20190331'#(lf)  AND [Extract_Type] = 'Monthly'"]),
				    #"Changed Type1" = Table.TransformColumnTypes(Source,{{"Target", Percentage.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"Financial Month", Int64.Type}, {"Report Number", type number}})
				in
				    #"Changed Type"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

