table 'LTC Reference Table - ONLY LTC'
	lineageTag: 80556757-d5bf-498d-afee-abcb90ca911c

	column pseudo_nhs_number
		dataType: string
		lineageTag: 296ce212-cb10-4777-b5bf-1bb6a9aa5f7a
		summarizeBy: none
		sourceColumn: pseudo_nhs_number

		annotation SummarizationSetBy = Automatic

	column Population_Counter
		dataType: int64
		formatString: 0
		lineageTag: 7ceda56a-177f-4093-a23e-eca4d6b954de
		summarizeBy: sum
		sourceColumn: Population_Counter

		annotation SummarizationSetBy = Automatic

	column NumberOfLTC
		dataType: int64
		formatString: 0
		lineageTag: 377486ba-0f0b-45e1-a938-608d7c6c2c71
		summarizeBy: sum
		sourceColumn: NumberOfLTC

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: c6f71a94-23f4-4194-a54c-afe60f9613bb
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: e3287ddc-cb14-4756-9227-89b63f2bb863
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'LTC Reference Table - ONLY LTC' = m
		mode: import
		source =
				let
				    Source = #"LTC Reference Table - ALL",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Value] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

