table 'Date Table'
	lineageTag: 2444d6eb-fb42-4c1d-9219-c3ee95ae7c9d

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 58e9bd70-32ae-46a6-a3e9-0a69706be841
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 95906ccf-23f5-4c48-8c55-444da6560126
			defaultHierarchy: LocalDateTable_5e88b56f-3f11-4f56-a643-c36bcc4bd52c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: a55ed7c4-eea3-424a-8975-dc0962e05ff6
		summarizeBy: none
		sourceColumn: day_month_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 4294bd3a-5dbe-48fe-80bf-7a655275b713
		summarizeBy: sum
		sourceColumn: day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 27766702-4a6c-408d-ab78-7ff7c46714eb
		summarizeBy: sum
		sourceColumn: weekday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: b4c3c50c-967d-4573-83e1-b3443741614e
		summarizeBy: none
		sourceColumn: weekday_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 07f11b31-45a1-46d2-91a9-7af0fe07a73b
		summarizeBy: sum
		sourceColumn: month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 469a9caf-5733-4c83-8170-9c2925d632b5
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: c82cfe54-5021-4916-bcde-a8f90afc65ff
		summarizeBy: sum
		sourceColumn: quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 3fe7e638-aed1-4872-8a48-d2d989511eda
		summarizeBy: none
		sourceColumn: year_month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d96fc645-2839-40f7-a9d2-30dfde5e75ee
		summarizeBy: none
		sourceColumn: is_weekend

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 88adcba5-c2ae-4296-ac3f-82e0a0f005ae
		summarizeBy: none
		sourceColumn: is_holiday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 54a73283-693d-495f-97eb-62743fd62b27
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: f001d302-471e-47b0-bbb0-4231e3878777
		summarizeBy: none
		sourceColumn: financial_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 6c7f2575-716f-49ca-b5ce-41a383027fb1
		summarizeBy: sum
		sourceColumn: financial_quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 9870db1b-0623-4a28-b5ce-6f9c1e7a3bb6
		summarizeBy: sum
		sourceColumn: financial_month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: fdfb6705-910c-450c-8561-943ee6378c49
		summarizeBy: none
		sourceColumn: month_year_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstDateofMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 244d46d1-2bb1-4ef3-bf77-d9dea2f46ee5
		summarizeBy: none
		sourceColumn: FirstDateofMonth

		variation Variation
			isDefault
			relationship: 8f66f863-8f06-406c-924b-2f4cc3e78f26
			defaultHierarchy: LocalDateTable_aeac38cf-ef66-42f7-9268-56b936939ae1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Date Table' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select date as ""date"", daymonthyear as ""day_month_year"", day as ""day"", weekday as ""weekday"", weekdayname as ""weekday_name"", month as ""month"", left(monthname,3) as ""month_name"", quarter as ""quarter"", yearmonth as ""year_month"", isweekend as ""is_weekend"", isholiday as ""is_holiday"", financialweekofyear as ""financial_week_of_year"", financialyear as ""financial_year"", financialquarter as ""financial_quarter"", firstdateofmonth as ""FirstDateofMonth"", financialmonth as ""financial_month"", monthyearname as ""month_year_name"" from ccg_reference.vw_datelookup where ""date"" between '2018-04-01' and last_day(dateadd(month,-1,current_date))", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

