table MSK_APS_CORE_REF
	lineageTag: aed593ad-cd08-48c4-989e-40deaaf2500e

	column local_treatment_function_code
		dataType: string
		lineageTag: 4507e30a-22f3-4c1d-b4ff-5b4152f7a3d7
		summarizeBy: none
		sourceColumn: local_treatment_function_code

		annotation SummarizationSetBy = Automatic

	column appointment_type
		dataType: string
		lineageTag: e91895cc-5557-4a20-bbb6-179887917e29
		summarizeBy: none
		sourceColumn: appointment_type

		annotation SummarizationSetBy = Automatic

	column LTFC_appointment_type
		dataType: string
		lineageTag: d7d85679-7de2-4510-a545-b0d13509f43d
		summarizeBy: none
		sourceColumn: LTFC_appointment_type

		annotation SummarizationSetBy = Automatic

	column 'MSK APS_or_Core_MSK_Therapy'
		dataType: string
		lineageTag: 42311ae6-35b0-48b6-aa78-4969f0ca8001
		summarizeBy: none
		sourceColumn: MSK APS_or_Core_MSK_Therapy

		annotation SummarizationSetBy = Automatic

	partition MSK_APS_CORE_REF = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\CPG\MSK\Dashboard\Power BI\Outpatient\MSK APS_CORE_Import.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"local_treatment_function_code", type any}, {"appointment_type", type text}, {"LTFC_appointment_type", type text}, {"MSK APS_or_Core_MSK_Therapy", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

