table 'PPW Daily Data'
	lineageTag: 0684f710-b758-4961-8933-9ecd830c4ae4

	measure Total_on_PPW_List = DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: 71bbb211-d7b9-4215-b1e0-e4934ba4316d

	measure Total_with_dementia_recorded =
			
			
			Coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[First Dementia Date]))
			),0)
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: 17f35b70-98fd-4cc7-b59b-f1a10d535b01

	measure Total_with_cancer_recorded = ```
			
			
			COALESCE( CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Cancer Date]))
			),0)
			
			
			
			```
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: 0c7dea71-ca19-4ebd-9d4e-3104923fd5e1

	measure Total_with_a_last_GSF_recorded =
			
			
			COALESCE(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last GSF Status Date]))
			),0)
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: cb29ec51-b88f-48de-8231-59a42f6dc927

	measure Total_with_frailty_code =
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Frailty Code -grey the value is more recent Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 2b4b1eef-adc9-458b-9c51-ad421b170fef

	measure Total_with_a_rockwood_code =
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Rockwood Score -grey the code is more recent]))
			),0)
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: 704f2b5c-ba49-437d-8112-f3f3537f0ac8

	measure Total_with_a_overall_plan_of_care_code =
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last  Overall Plan of Care Date]))
			),0)
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: e256f59f-8574-4d0b-8899-944861496ef2

	measure Total_with_Last_Patients_Concerns_Expectation =
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Frailty Code -grey the value is more recent Date]))
			),0)
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: 592dd085-cb69-4dfc-a900-c8a7e34a9c7c

	measure Total_with_Last_care_plan =
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Personal Care Plan Date]))
			),0)
		formatString: #,0
		displayFolder: PPW Summary Page Measures
		lineageTag: 9d1c3ba8-0e51-449b-946d-de05d39e8a6d

	measure Fell_in_last_28_days = ```
			
			coalesce(CALCULATE(
			    DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)]),
			    DATEDIFF('PPW Daily Data'[Last fall date], 'PPW Daily Data'[Census_Date], DAY) <= 28,
			    DATEDIFF('PPW Daily Data'[Last fall date], 'PPW Daily Data'[Census_Date], DAY) >= 0,
			    NOT ISBLANK('PPW Daily Data'[Last fall date])
			),0)
			
			```
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 36897072-3c83-4c25-be4a-b720229098a5

	measure Hospital_Admission_in_the_last_28_days =
			
			coalesce(CALCULATE(
			    DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)]),
			    DATEDIFF('PPW Daily Data'[Last Hospital Admission Date], 'PPW Daily Data'[Census_Date], DAY) <= 28,
			    DATEDIFF('PPW Daily Data'[Last Hospital Admission Date], 'PPW Daily Data'[Census_Date], DAY) >= 0,
			    NOT ISBLANK('PPW Daily Data'[Last Hospital Admission Date])
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 0380af67-29b4-4ab1-ba83-bf19a73bd26b

	measure Emergency_department_attendance_in_the_last_28_days =
			
			COALESCE(CALCULATE(
			    DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)]),
			    DATEDIFF('PPW Daily Data'[Last Emergency Department Date], 'PPW Daily Data'[Census_Date], DAY) <= 28,
			    DATEDIFF('PPW Daily Data'[Last Emergency Department Date], 'PPW Daily Data'[Census_Date], DAY) >= 0,
			    NOT ISBLANK('PPW Daily Data'[Last Emergency Department Date])
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 4cabc4c3-574c-4eca-a7be-10bd8c79bc9b

	measure Total_with_Last_Respect_Form =
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Respect Form Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 9f352b99-f86a-42ea-a0ba-2cc605166320

	measure Total_with_end_of_life_care_plan =
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last End Of Life Care Plan Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 6aff5b69-6172-4d96-87aa-e57dd7dd0857

	measure Total_with_Last_Referral_To_Palliative_Care_Team =
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Referral To Palliative Care Team Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 39da01ed-eb9d-4cb6-b802-55b3b05adb28

	measure Total_with_Latest_Personalised_Care_and_Support_Plan =
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Latest Personalised Care and Support Plan Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 0bf8e40e-cd26-4f0c-9c29-9455f1ffda14

	measure Total_with_Last_Care_Coordinator_Assessment =
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Care Coordinator Assess Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 25ed17f3-9f71-44a0-bad2-b79bc0c4633f

	measure Total_with_a_Last_Frailty_Assessment = ```
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Frailty Assessment Date]))
			),0)
			
			
			```
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 3c443cba-487b-4560-92a0-109483a58435

	measure Total_with_Last_Seen_by_Community_Matron =
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Seen by Community Matron Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: b1c0cdb5-9efc-4f38-8b18-34e912a4fab7

	measure Total_with_Last_Care_Home_Assessment =
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Care Home Assessment Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 054f5407-6e15-497c-bd2d-5b04288f8fb2

	measure Total_with_multi-agency_case_management =
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Multi-agency Case Management Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: 60bcd967-ab1b-464a-a379-fa296d494bc6

	measure Total_with_Communication_Needs_assessment =
			
			
			coalesce(CALCULATE(
			DISTINCTCOUNT('PPW Daily Data'[NHS Number (Pseudo)])
			,NOT(ISBLANK('PPW Daily Data'[Last Communication Needs Date]))
			),0)
		formatString: 0
		displayFolder: PPW Summary Page Measures
		lineageTag: ebecb392-5834-4cf2-8ea0-6917b7bea713

	measure Hospital_admission_and_ED_attendances_colour = ```
			
			
			
			
			VAR FieldName = SELECTEDVALUE('Metric_Link_for_patient_level_ref'[Field Name])
			VAR LastAdmission =
			    SWITCH(
			        FieldName,
			        "Last Hospital Admission Date", MAX('PPW Daily Data'[Last Hospital Admission Date]),
			        "Last Emergency Department Date", MAX('PPW Daily Data'[Last Emergency Department Date]),
			        BLANK()
			    )
			VAR DataUpTo = MAX('PPW Daily Data'[PC_Data_up_to])
			VAR DaysBetween = DATEDIFF(LastAdmission, DataUpTo, DAY)
			
			RETURN
			IF(
			    FieldName IN { "Last Hospital Admission Date", "Last Emergency Department Date" },
			    SWITCH(
			        TRUE(),
			        ISBLANK(LastAdmission) || ISBLANK(DataUpTo), BLANK(),
			        DaysBetween <= 42, "#A3D9A5",  // Green
			        DaysBetween <= 182, "#FFD88A", // Amber
			        DaysBetween <= 365, "#F5A5A5" // Red
			       --"#D3D3D3" // Optional: default color if > 365
			    ),
			    BLANK() // No formatting for other field names
			)
			
			
			```
		lineageTag: 5f7fe585-4622-44ed-a170-792141f6b09f

	measure Frailty_colour = ```
			
			VAR FieldName = SELECTEDVALUE('Metric_Link_for_patient_level_ref'[Field Name])
			VAR Latest_Rockwood_code = MAX('PPW Daily Data'[Last Rockwood Score -grey the code is more recent])
			VAR Latest_frailty_code = MAX('PPW Daily Data'[Last Frailty Code -grey the value is more recent Date])
			VAR DataUpTo = MAX('PPW Daily Data'[PC_Data_up_to])
			VAR DaysBetween = DATEDIFF(Latest_Rockwood_code, DataUpTo, DAY)
			
			RETURN
			IF(
			    FieldName = "Last Rockwood Score -grey the code is more recent",
			    SWITCH(
			        TRUE(),
			        ISBLANK(Latest_frailty_code) || ISBLANK(DataUpTo) || ISBLANK(Latest_Rockwood_code), BLANK(),
			        Latest_Rockwood_code > Latest_frailty_code, "#D3D3D3", // Grey if Rockwood is more recent
			        DaysBetween <= 42, "#A3D9A5",  // Green
			        DaysBetween <= 182, "#FFD88A", // Amber
			        DaysBetween <= 365, "#F5A5A5" // Red
			      --  "#D3D3D3" // Optional: grey if > 365
			    ),
			    BLANK()
			)
			
			```
		lineageTag: c6d078e8-9670-4a66-9186-fb904adbfd72

	column Age
		dataType: int64
		formatString: 0
		lineageTag: e1302017-c215-4fb7-9a78-13a66d599beb
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: ed44dd4d-7b77-4fe3-a92a-7fd1a4f81672
		summarizeBy: none
		sourceColumn: Census_Date

		annotation SummarizationSetBy = Automatic

	column 'NHS Number (Pseudo)'
		dataType: string
		lineageTag: 04725ede-3007-473a-a08f-8a83239a3921
		summarizeBy: none
		sourceColumn: NHS Number (Pseudo)

		annotation SummarizationSetBy = Automatic

	column Date_of_Death
		dataType: dateTime
		formatString: General Date
		lineageTag: ff2624a7-6271-469a-a498-10eb7f6139a3
		summarizeBy: none
		sourceColumn: Date_of_Death

		variation Variation
			isDefault
			relationship: c304262a-5db5-4ac3-ac21-a5c2cb25e4ba
			defaultHierarchy: LocalDateTable_4a722758-865a-447a-823e-9861e6994472.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column deceased_flag
		dataType: int64
		formatString: 0
		lineageTag: 04235385-a11a-49a9-8f8f-670a3df76969
		summarizeBy: sum
		sourceColumn: deceased_flag

		annotation SummarizationSetBy = Automatic

	column Age_at_death
		dataType: int64
		formatString: 0
		lineageTag: aba2d548-c444-4b79-9032-34eedfc5ca5f
		summarizeBy: sum
		sourceColumn: Age_at_death

		annotation SummarizationSetBy = Automatic

	column 01_Flag
		dataType: int64
		formatString: 0
		lineageTag: 84ba2f82-4304-42ed-bec0-df097981bf4f
		summarizeBy: sum
		sourceColumn: 01_Flag

		annotation SummarizationSetBy = Automatic

	column 01h_Flag
		dataType: int64
		formatString: 0
		lineageTag: 1b004bd3-4b9a-461b-af50-ec1886649c6c
		summarizeBy: sum
		sourceColumn: 01h_Flag

		annotation SummarizationSetBy = Automatic

	column 01b_Flag
		dataType: int64
		formatString: 0
		lineageTag: 8eccf775-4057-4c68-8fc8-3858ced8a26d
		summarizeBy: sum
		sourceColumn: 01b_Flag

		annotation SummarizationSetBy = Automatic

	column 01e_Flag
		dataType: int64
		formatString: 0
		lineageTag: 4bc5176d-6d12-4761-87ff-601b4e89a127
		summarizeBy: sum
		sourceColumn: 01e_Flag

		annotation SummarizationSetBy = Automatic

	column 01c_Flag
		dataType: int64
		formatString: 0
		lineageTag: 047607d6-2c56-4ff4-a42c-dcf0703b7aac
		summarizeBy: sum
		sourceColumn: 01c_Flag

		annotation SummarizationSetBy = Automatic

	column 01d_Flag
		dataType: int64
		formatString: 0
		lineageTag: 75fd1212-96c9-4da5-8ae3-9b020358053c
		summarizeBy: sum
		sourceColumn: 01d_Flag

		annotation SummarizationSetBy = Automatic

	column 01g_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9dd0ef7b-cf67-47cd-a8d0-3dbe26ef4332
		summarizeBy: sum
		sourceColumn: 01g_Flag

		annotation SummarizationSetBy = Automatic

	column 01a_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9782aecf-19a1-40fd-aaa0-ccc15f2fdcb6
		summarizeBy: sum
		sourceColumn: 01a_Flag

		annotation SummarizationSetBy = Automatic

	column 01f_Flag
		dataType: int64
		formatString: 0
		lineageTag: 47d7b24b-8a48-4b1d-a6c3-88a25b78ebe5
		summarizeBy: sum
		sourceColumn: 01f_Flag

		annotation SummarizationSetBy = Automatic

	column 01dd_Flag
		dataType: int64
		formatString: 0
		lineageTag: 46d4360b-a337-4351-9825-d3df390e85c9
		summarizeBy: sum
		sourceColumn: 01dd_Flag

		annotation SummarizationSetBy = Automatic

	column In_Cohort_Flag
		dataType: int64
		formatString: 0
		lineageTag: 83589b7e-6694-48e8-94af-19fc530e5117
		summarizeBy: sum
		sourceColumn: In_Cohort_Flag

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: fdeae2d3-dd09-46dc-acf8-58f2be4ba4a5
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column practice_name
		dataType: string
		lineageTag: fa01004c-7bb9-4d3f-90ef-0efa76c84f57
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

	column primary_care_network
		dataType: string
		lineageTag: 0a268bcc-adba-4724-9fc4-c8d4758985de
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: 04d52526-b868-45fe-8e8d-6a59cabec121
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column Date_of_Birth
		dataType: dateTime
		formatString: General Date
		lineageTag: 6eb39c45-3ca2-4938-b3cf-7d774b901f89
		summarizeBy: none
		sourceColumn: Date_of_Birth

		variation Variation
			isDefault
			relationship: 782a8c04-4303-45bc-b918-6c638b1b43b3
			defaultHierarchy: LocalDateTable_39ccd60a-084a-4240-9a34-47cdee854e31.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band
		dataType: string
		lineageTag: d687ba73-fbd0-420d-9e6f-ac4ab0749848
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

	column 10yr_age_band
		dataType: string
		lineageTag: d3eeb04b-979f-4325-af5c-7da049693fe6
		summarizeBy: none
		sourceColumn: 10yr_age_band

		annotation SummarizationSetBy = Automatic

	column dementia_flag
		dataType: int64
		formatString: 0
		lineageTag: 2a900b28-6030-4a75-8911-9ae1d96b0c60
		summarizeBy: sum
		sourceColumn: dementia_flag

		annotation SummarizationSetBy = Automatic

	column Palliative_Care_Flag
		dataType: int64
		formatString: 0
		lineageTag: 377a748b-2ea0-4919-89f8-322fbcdfd689
		summarizeBy: sum
		sourceColumn: Palliative_Care_Flag

		annotation SummarizationSetBy = Automatic

	column Palliative_Care_ever_Flag
		dataType: int64
		formatString: 0
		lineageTag: 0ebe1052-9bc4-49e1-92c6-be49cee62f19
		summarizeBy: sum
		sourceColumn: Palliative_Care_ever_Flag

		annotation SummarizationSetBy = Automatic

	column Latest_code_not_palliative_Flag
		dataType: int64
		formatString: 0
		lineageTag: 0d267c8c-b660-459e-8a59-8f5d6e75f454
		summarizeBy: sum
		sourceColumn: Latest_code_not_palliative_Flag

		annotation SummarizationSetBy = Automatic

	column respect_form_flag
		dataType: int64
		formatString: 0
		lineageTag: d9e19b5b-c948-4b05-b544-2f2f1049b358
		summarizeBy: sum
		sourceColumn: respect_form_flag

		annotation SummarizationSetBy = Automatic

	column Preferred_place_of_death_recorded_flag
		dataType: int64
		formatString: 0
		lineageTag: 43dd3586-d741-44f7-9c21-83e6d1fa2e11
		summarizeBy: sum
		sourceColumn: Preferred_place_of_death_recorded_flag

		annotation SummarizationSetBy = Automatic

	column Preferred_place_of_death_recorded_ever_flag
		dataType: int64
		formatString: 0
		lineageTag: 09466950-59b6-452b-b8e0-c516f0c0320b
		summarizeBy: sum
		sourceColumn: Preferred_place_of_death_recorded_ever_flag

		annotation SummarizationSetBy = Automatic

	column died_in_preferred_place_of_death_flag
		dataType: int64
		formatString: 0
		lineageTag: da95c235-410d-42a4-9004-6902cef8d9f0
		summarizeBy: sum
		sourceColumn: died_in_preferred_place_of_death_flag

		annotation SummarizationSetBy = Automatic

	column GSF_Flag
		dataType: int64
		formatString: 0
		lineageTag: 35a3bf1a-4acd-4100-8dbd-d5db52bfab94
		summarizeBy: sum
		sourceColumn: GSF_Flag

		annotation SummarizationSetBy = Automatic

	column QOF_Cancer_and_GSF_Flag
		dataType: int64
		formatString: 0
		lineageTag: e7d61406-d450-4efd-9885-fdee8c7e0cb2
		summarizeBy: sum
		sourceColumn: QOF_Cancer_and_GSF_Flag

		annotation SummarizationSetBy = Automatic

	column non_cancer_diagnosis_Flag
		dataType: int64
		formatString: 0
		lineageTag: a40c50ba-9573-4809-8d1b-937301b62680
		summarizeBy: sum
		sourceColumn: non_cancer_diagnosis_Flag

		annotation SummarizationSetBy = Automatic

	column Cancer_QOF_Only_Flag
		dataType: int64
		formatString: 0
		lineageTag: f4047364-3101-4977-bbf5-3423f62bb95a
		summarizeBy: sum
		sourceColumn: Cancer_QOF_Only_Flag

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: dd9ab4a1-2cd6-43dc-b322-ec61489758de
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column Cohrot_Identified_Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4b54a37e-14ee-4c14-8d60-81a1d87bb1b9
		summarizeBy: none
		sourceColumn: Cohrot_Identified_Date

		variation Variation
			isDefault
			relationship: 70686044-e334-46cf-baa6-521865712fbc
			defaultHierarchy: LocalDateTable_dd4cb605-46c7-45a8-ad9e-6cfeab976c96.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column PC_Data_up_to
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7cfe666d-b2ff-4d14-9b23-d1dabf37faed
		summarizeBy: none
		sourceColumn: PC_Data_up_to

		variation Variation
			isDefault
			relationship: 847da2b5-fa2a-4278-8b97-06e42796144c
			defaultHierarchy: LocalDateTable_99803a7e-43e1-4e18-a90f-59bfb4ba99a6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Usual GP'
		dataType: string
		lineageTag: 3fdf7d0d-5968-419d-90c5-a6e67da89479
		summarizeBy: none
		sourceColumn: Usual GP

		annotation SummarizationSetBy = Automatic

	column 'NHS Number'
		dataType: string
		lineageTag: e34ff7ed-de62-4816-91dc-84140cd07d95
		summarizeBy: none
		sourceColumn: NHS Number

		annotation SummarizationSetBy = Automatic

	column Surname
		dataType: string
		lineageTag: 98f82aad-917b-43e7-9c72-0358abbb7316
		summarizeBy: none
		sourceColumn: Surname

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		lineageTag: 5c6f19b6-d1df-402a-bcc6-513a264e1949
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Full DOB'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 24b48fc7-7eec-4a8b-8f28-afa7719539fb
		summarizeBy: none
		sourceColumn: Full DOB

		variation Variation
			isDefault
			relationship: 9ddfad6f-e3d0-49ae-9e7c-190364a84825
			defaultHierarchy: LocalDateTable_6658ac03-1de7-4abe-82af-c6ce92716232.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Full address'
		dataType: string
		lineageTag: dac715f7-fd4f-4484-9606-7694be60c117
		summarizeBy: none
		sourceColumn: Full address

		annotation SummarizationSetBy = Automatic

	column 'Date of Death'
		dataType: dateTime
		formatString: General Date
		lineageTag: 02d45306-26cf-4abe-9c6b-9d771463711a
		summarizeBy: none
		sourceColumn: Date of Death

		variation Variation
			isDefault
			relationship: dc7ae961-23e0-49f9-9e86-f4db7e55ca85
			defaultHierarchy: LocalDateTable_9f15a0b7-02ea-46d5-bb93-71c10510d672.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Residence'
		dataType: string
		lineageTag: 44877d42-836a-442d-a40a-ab000a6175e4
		summarizeBy: none
		sourceColumn: Last Residence

		annotation SummarizationSetBy = Automatic

	column 'Last GSF Status Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8ebc44f1-18c4-49ac-8e6b-cc60e6513afe
		summarizeBy: none
		sourceColumn: Last GSF Status Date

		variation Variation
			isDefault
			relationship: e8cc1de1-7a73-4659-8142-08ef10617422
			defaultHierarchy: LocalDateTable_e3ed7b6a-fe3a-419d-9cdf-94a5f8fb05fb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last GSF Status Desc'
		dataType: string
		lineageTag: dc486257-4b35-4e65-b1a5-b07169af66b7
		summarizeBy: none
		sourceColumn: Last GSF Status Desc

		annotation SummarizationSetBy = Automatic

	column 'First Dementia Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 33344408-70d9-42c9-aaef-543ac9a98f5b
		summarizeBy: none
		sourceColumn: First Dementia Date

		variation Variation
			isDefault
			relationship: ed52f535-b1a1-418f-95b6-2c8b8bb72db7
			defaultHierarchy: LocalDateTable_bc460186-0e46-4791-a964-089b666a2293.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'First Dementia Desc'
		dataType: string
		lineageTag: c3123211-eb42-4050-b51d-f497ab82b04f
		summarizeBy: none
		sourceColumn: First Dementia Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Cancer Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2d36af04-596f-4b4a-9a84-b79f17ac4645
		summarizeBy: none
		sourceColumn: Last Cancer Date

		variation Variation
			isDefault
			relationship: 801b454f-b32a-474a-9e50-26d74061a642
			defaultHierarchy: LocalDateTable_e7a5618c-1ec7-4fd8-8a0b-8f7047c07f5f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Cancer Desc'
		dataType: string
		lineageTag: 57a08bf4-9d6c-4912-a5b4-b766d52d7a0a
		summarizeBy: none
		sourceColumn: Last Cancer Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Frailty Code -grey the value is more recent Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 21e65825-21e6-4a25-860d-83cc502b8696
		summarizeBy: none
		sourceColumn: Last Frailty Code -grey the value is more recent Date

		variation Variation
			isDefault
			relationship: bc18b967-52f3-4246-90ca-d962b62d048d
			defaultHierarchy: LocalDateTable_06078800-10a4-4ed0-b03b-8b8d03b4949f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Frailty Code -red severe -orange moderate Desc'
		dataType: string
		lineageTag: ae9dc1dd-2559-4387-b6cb-ae42a0c8ba89
		summarizeBy: none
		sourceColumn: Last Frailty Code -red severe -orange moderate Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Rockwood Score -grey the code is more recent'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0fc58b5b-be83-4f3c-83c3-20f6466b6031
		summarizeBy: none
		sourceColumn: Last Rockwood Score -grey the code is more recent

		variation Variation
			isDefault
			relationship: 0e9f1289-cb1b-40c6-bf77-22d2ee679be8
			defaultHierarchy: LocalDateTable_61eca234-3960-4914-b7ba-f03a18a3d2af.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Rockwood Score -red severe -orange moderate'
		dataType: string
		lineageTag: 7b19f905-99ee-48fe-a6c7-367382848a24
		summarizeBy: none
		sourceColumn: Last Rockwood Score -red severe -orange moderate

		annotation SummarizationSetBy = Automatic

	column 'Last  Overall Plan of Care Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6bfded0d-a69c-4265-ae8f-a1661e577b62
		summarizeBy: none
		sourceColumn: Last  Overall Plan of Care Date

		variation Variation
			isDefault
			relationship: 4f2ce2f5-ec15-4494-9dd3-7a9848e5bb9d
			defaultHierarchy: LocalDateTable_cc8bd598-605f-4e32-a0f7-45c0e2a22504.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last  Patients Concern Expectation Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: cba944b2-3700-4aaf-957a-bc6e15c34917
		summarizeBy: none
		sourceColumn: Last  Patients Concern Expectation Date

		variation Variation
			isDefault
			relationship: 48eb5fec-7f95-4c3c-9ebf-79ba3eebee06
			defaultHierarchy: LocalDateTable_1b4ca9a5-dfbe-448e-912c-5dc78d7b186f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Personal Care Plan Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ee4e15c4-6a53-4955-9849-8c047f41d9a0
		summarizeBy: none
		sourceColumn: Last Personal Care Plan Date

		variation Variation
			isDefault
			relationship: 44a30957-d9de-458a-ae5b-3d193a3e2a6f
			defaultHierarchy: LocalDateTable_0f41ff0a-e6ac-4026-9bda-e4e42e79264d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Personal Care Plan Desc'
		dataType: string
		lineageTag: c8167933-8842-4b49-b67d-6d8b3571bd1e
		summarizeBy: none
		sourceColumn: Last Personal Care Plan Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Respect Form Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 272d379d-58fc-4bc4-bf17-72ebc0fd3011
		summarizeBy: none
		sourceColumn: Last Respect Form Date

		variation Variation
			isDefault
			relationship: 7464ffc3-4e90-4af5-b7ed-cabd6f7f6343
			defaultHierarchy: LocalDateTable_23b01acb-cfef-45eb-9a29-4ceb87160e3b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Resuscitation Status Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 718a9fcb-aba5-4dfc-a320-468d3211d456
		summarizeBy: none
		sourceColumn: Last Resuscitation Status Date

		variation Variation
			isDefault
			relationship: 7cda41c7-0409-415f-aab0-97bab1f31fd6
			defaultHierarchy: LocalDateTable_8d3add9d-75dd-480a-8898-0e07cf9fce49.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Resuscitation Discussion With Patient Desc'
		dataType: string
		lineageTag: cd197a3c-3098-4928-9f18-13b14f322b1a
		summarizeBy: none
		sourceColumn: Last Resuscitation Discussion With Patient Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Treatment Escalation Plan Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 51c9ae3b-1f06-422c-9f3d-25442f304b60
		summarizeBy: none
		sourceColumn: Last Treatment Escalation Plan Date

		variation Variation
			isDefault
			relationship: 4229df10-946c-41a4-84c7-f99335c1e106
			defaultHierarchy: LocalDateTable_da748846-d4b4-4646-b183-b7188805dec4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Special Patient Note Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 811ff790-9d06-4c57-8793-54f98855a79f
		summarizeBy: none
		sourceColumn: Last Special Patient Note Date

		variation Variation
			isDefault
			relationship: 0f2daeed-75c8-4833-b890-c12a0bc34143
			defaultHierarchy: LocalDateTable_4123eda7-017c-450f-8b29-9b0b0b09a7fd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Fall Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 50658d0c-cbd1-4914-acbf-72489e8add56
		summarizeBy: none
		sourceColumn: Last Fall Date

		variation Variation
			isDefault
			relationship: 1047b07f-ef3d-48ed-b745-e396d75c9374
			defaultHierarchy: LocalDateTable_60ac615c-3fb9-45d3-bf9d-833b47fd3c98.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Fall Desc'
		dataType: string
		lineageTag: b3928a27-f1fd-4f49-8d7a-8d84ba1a94d8
		summarizeBy: none
		sourceColumn: Last Fall Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Assessment for no. Falls'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5ed638ac-1bb2-4289-bbe4-c8f79c97e152
		summarizeBy: none
		sourceColumn: Last Assessment for no. Falls

		variation Variation
			isDefault
			relationship: f7fa7789-132c-4c6b-9c3e-9ff020da83ad
			defaultHierarchy: LocalDateTable_5080c50a-20d4-4195-92c3-65de44c64101.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Number of falls in last year'
		dataType: int64
		formatString: 0
		lineageTag: 85b6d681-6a12-4f19-bf3e-c0efb849ebf5
		summarizeBy: sum
		sourceColumn: Number of falls in last year

		annotation SummarizationSetBy = Automatic

	column 'Last Emergency Department Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7c8f62d0-6dab-4c6c-a69c-baa3aec03b6a
		summarizeBy: none
		sourceColumn: Last Emergency Department Date

		variation Variation
			isDefault
			relationship: e98db40f-7be7-4596-8761-84164918a941
			defaultHierarchy: LocalDateTable_28dd8878-37f5-4268-a55d-44da4a01632d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Emergency Department Desc'
		dataType: string
		lineageTag: a0d47def-0e9a-4550-a0a5-9ac9272ada2f
		summarizeBy: none
		sourceColumn: Last Emergency Department Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Hospital Admission Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8b1bc7c6-913b-4514-aa19-0912873061ef
		summarizeBy: none
		sourceColumn: Last Hospital Admission Date

		variation Variation
			isDefault
			relationship: 2400d14d-4caf-47cc-9237-44079108deab
			defaultHierarchy: LocalDateTable_07cbd83b-bc93-4f2d-9b98-02ba37820eb6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Hospital Admission Desc'
		dataType: string
		lineageTag: 05796db0-f501-4c25-8062-e88fda5d1a5c
		summarizeBy: none
		sourceColumn: Last Hospital Admission Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Comprehensive Geriatric Ass Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4a41e295-aa2e-4930-b51b-0c30f71ad693
		summarizeBy: none
		sourceColumn: Last Comprehensive Geriatric Ass Date

		variation Variation
			isDefault
			relationship: bcdab55d-5d6a-4da1-9357-19dec45c1fad
			defaultHierarchy: LocalDateTable_bb1ed48c-fb8d-4032-84ef-ea68c4b5ce1a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Nutrition assessment Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 213c32be-53cc-44f3-a971-d2b2fd48df62
		summarizeBy: none
		sourceColumn: Last Nutrition assessment Date

		variation Variation
			isDefault
			relationship: 92667f44-0953-4c4e-adb2-b3915fb53b82
			defaultHierarchy: LocalDateTable_817743ae-3319-4886-aa7d-88cdbfd890a8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Nutrition assessment Desc'
		dataType: string
		lineageTag: 8fea8693-061c-496b-ba4c-5ce65e106437
		summarizeBy: none
		sourceColumn: Last Nutrition assessment Desc

		annotation SummarizationSetBy = Automatic

	column 'Last SMR Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a76405bb-5f82-41d2-b3a2-5943281cffc8
		summarizeBy: none
		sourceColumn: Last SMR Date

		variation Variation
			isDefault
			relationship: 7d4002c5-9f47-483e-af79-2c440bbf9917
			defaultHierarchy: LocalDateTable_6ffee5ab-ec1b-4f9c-9334-821b4a3c303d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last referral To Social prescriber Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9f9ffdc4-65cc-4d05-939f-9e4bf7d4998d
		summarizeBy: none
		sourceColumn: Last referral To Social prescriber Date

		variation Variation
			isDefault
			relationship: bf0a90be-c631-4ff7-a42e-7a329e1f9ca3
			defaultHierarchy: LocalDateTable_0404d4b6-1ab3-454c-b740-d265a2de521d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last referral to Social Prescriber Desc'
		dataType: string
		lineageTag: f7c9f8a6-5ce1-47f1-8786-81589ad58ab1
		summarizeBy: none
		sourceColumn: Last referral to Social Prescriber Desc

		annotation SummarizationSetBy = Automatic

	column 'Last Care Coordinator Assess Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f345ebd8-d9f1-43f2-b6f2-0963462d7a74
		summarizeBy: none
		sourceColumn: Last Care Coordinator Assess Date

		variation Variation
			isDefault
			relationship: a2e2c138-5cc6-4e27-a899-74d538aae1f0
			defaultHierarchy: LocalDateTable_420cfb55-8154-4da8-96b8-0def28b860b9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Multi-agency Case Management Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: e220d5b5-e939-4bd9-9bf9-fc4002362fd7
		summarizeBy: none
		sourceColumn: Last Multi-agency Case Management Date

		variation Variation
			isDefault
			relationship: 276ad8b2-a221-44ff-aecd-87b19b55625c
			defaultHierarchy: LocalDateTable_91840cc5-5736-444b-9bcb-3c81fffe3f22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Frailty Assessment Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: bcab1157-5921-47e4-a474-ce9c14e937aa
		summarizeBy: none
		sourceColumn: Last Frailty Assessment Date

		variation Variation
			isDefault
			relationship: ee3640bc-a604-4795-969a-7093398a54b1
			defaultHierarchy: LocalDateTable_135ad257-3fce-422c-95be-898b692d36b8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Seen by Community Matron Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: fc555793-ef40-41f1-b581-4ca64e37d88d
		summarizeBy: none
		sourceColumn: Last Seen by Community Matron Date

		variation Variation
			isDefault
			relationship: bfcca5bc-c9fb-45e4-b2ea-896612f9c912
			defaultHierarchy: LocalDateTable_04fbe2ce-deec-444e-bd1f-181fb1d1b2a5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last seen by Health Support Worker Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f49df0b6-b197-4efc-a57b-246253217b2d
		summarizeBy: none
		sourceColumn: Last seen by Health Support Worker Date

		variation Variation
			isDefault
			relationship: 11d95741-8f6a-4b94-9ae9-d491eff30400
			defaultHierarchy: LocalDateTable_525fe40a-d8a9-4e81-9b28-eeb8f76c67c9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Care Home Assessment Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0b4d2508-bba1-4371-9b8d-ea009789355a
		summarizeBy: none
		sourceColumn: Last Care Home Assessment Date

		variation Variation
			isDefault
			relationship: 7ee8d298-94a8-4fdd-87e6-d8d04275db8d
			defaultHierarchy: LocalDateTable_8276f8f6-ff3b-4aae-ae24-ec7289f53635.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Proactive Care Started Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1e015fbf-4289-4b91-9f8e-370d5ede4c26
		summarizeBy: none
		sourceColumn: Last Proactive Care Started Date

		variation Variation
			isDefault
			relationship: 73670a6e-54e1-460b-b945-25099f9978a5
			defaultHierarchy: LocalDateTable_108dfcdd-7424-4777-8ae0-c88a44a053cd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Proactive Care Ended Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: fc5986a0-4b71-4026-bd9e-5b20ac5aafea
		summarizeBy: none
		sourceColumn: Last Proactive Care Ended Date

		variation Variation
			isDefault
			relationship: 8c66b764-0e35-49b0-9d9f-8247d80516bc
			defaultHierarchy: LocalDateTable_d5c4144b-4ae7-473d-bce2-a4bdd23a8739.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Lasting Power Of Attorney for Property Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 14ea5637-7f5b-4825-b0b5-b0c05a96e364
		summarizeBy: none
		sourceColumn: Last Lasting Power Of Attorney for Property Date

		variation Variation
			isDefault
			relationship: 5979d853-23f4-45c1-b98c-272a5405dd6b
			defaultHierarchy: LocalDateTable_fdaf268c-c07b-47c6-832a-af2c8586ca30.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Lasting Power Of Attorney for Welfare Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: d12fb9b4-0022-4139-b9aa-b83f7d7b11c0
		summarizeBy: none
		sourceColumn: Last Lasting Power Of Attorney for Welfare Date

		variation Variation
			isDefault
			relationship: 8242775e-eba9-476c-99d9-356fd64c2081
			defaultHierarchy: LocalDateTable_acf49162-ebf7-438c-b54d-4ba8d905b1e4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Mental Capacity Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 46e3cef3-5798-4b5c-b16b-03b31eb27b9d
		summarizeBy: none
		sourceColumn: Last Mental Capacity Date

		variation Variation
			isDefault
			relationship: b9ab04cb-0c9a-47ea-bc8f-455e3d05b86a
			defaultHierarchy: LocalDateTable_eada5dd2-ca08-4d58-89a8-2d6df81a4c7b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Communication Needs Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4d2c822d-3d19-4bfe-a880-d53f9a125e0b
		summarizeBy: none
		sourceColumn: Last Communication Needs Date

		variation Variation
			isDefault
			relationship: c41d6c95-326e-4425-b73a-e085602f1ad9
			defaultHierarchy: LocalDateTable_c631635b-40e4-42b9-ab1c-fffd2d918630.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Patient Aware Of Diagnosis Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 339e6ab0-a704-4456-8241-181e0edbc476
		summarizeBy: none
		sourceColumn: Last Patient Aware Of Diagnosis Date

		variation Variation
			isDefault
			relationship: d9c05c9b-84f3-4343-b744-6ec47de784d2
			defaultHierarchy: LocalDateTable_2d2f6b5d-5dd9-4557-a70a-0c7a7327c568.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Has A Carer Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ada25e4e-2bfb-4799-8598-f127a9328c5b
		summarizeBy: none
		sourceColumn: Last Has A Carer Date

		variation Variation
			isDefault
			relationship: 6b8680f6-3fdf-4a9f-ab0f-031b802cb6d8
			defaultHierarchy: LocalDateTable_a3057aab-b746-4804-a155-5b17e7eb7267.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Carer Is Aware Of Prognosis Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ce2c1e27-85c2-4c5d-ab71-2e788fa635ad
		summarizeBy: none
		sourceColumn: Last Carer Is Aware Of Prognosis Date

		variation Variation
			isDefault
			relationship: c368a10e-6dc9-4362-933d-3f2ff2c1e9ce
			defaultHierarchy: LocalDateTable_aaced70d-57cb-436a-ade2-177332827b8a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Preferred Place Of Care Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2eab3e30-4a0d-422a-a604-5154160765bc
		summarizeBy: none
		sourceColumn: Last Preferred Place Of Care Date

		variation Variation
			isDefault
			relationship: 01a6581c-9ac7-4ade-a352-2edc79d15e5d
			defaultHierarchy: LocalDateTable_968d0afa-2705-4637-a01e-279351e656c6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Preferred Place Of Death Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: d90bdb0f-6ecb-413c-bfae-3fb5673b9813
		summarizeBy: none
		sourceColumn: Last Preferred Place Of Death Date

		variation Variation
			isDefault
			relationship: a8687e78-b4ab-4c6f-8a2d-e07b949f3891
			defaultHierarchy: LocalDateTable_b990f63d-11a1-4556-a7ef-033a0f90837a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last DS1500 Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b18b68e5-5f65-49a7-84ec-e0b4440e71f6
		summarizeBy: none
		sourceColumn: Last DS1500 Date

		variation Variation
			isDefault
			relationship: 250415d5-1cbe-4251-abbc-488648dd6b04
			defaultHierarchy: LocalDateTable_e17912fe-e839-4c4d-9f0c-84ef6e63b664.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Anticipatory Prescribing Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a06bf51d-de68-4061-a0c9-84148413c8c7
		summarizeBy: none
		sourceColumn: Last Anticipatory Prescribing Date

		variation Variation
			isDefault
			relationship: 852ff95b-4730-47fc-a202-8a1c8985bbc8
			defaultHierarchy: LocalDateTable_ac304fc7-4c17-49de-8011-0d7dd4a1744f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Referral To Palliative Care Team Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 10649d35-b6a2-4df6-95c9-0ae15a705cbf
		summarizeBy: none
		sourceColumn: Last Referral To Palliative Care Team Date

		variation Variation
			isDefault
			relationship: cff53b7f-18ff-4da4-9a57-44a03c78305a
			defaultHierarchy: LocalDateTable_cdb6f4ad-0848-439e-9ce3-57b5c8ec6e76.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last End Of Life Care Plan Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 32473b21-4d6b-4bf9-81a2-6ae5217dfe39
		summarizeBy: none
		sourceColumn: Last End Of Life Care Plan Date

		variation Variation
			isDefault
			relationship: b38a7a6d-c834-42ce-a1ab-a5bbb3f30520
			defaultHierarchy: LocalDateTable_368ce9aa-5f47-4220-af9e-f6ea006658ce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last End Of Life Care Plan Desc'
		dataType: string
		lineageTag: d7a40a13-e416-4c8e-9979-7c0b653391e1
		summarizeBy: none
		sourceColumn: Last End Of Life Care Plan Desc

		annotation SummarizationSetBy = Automatic

	column 'Latest Personalised Care and Support Plan Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7ee4ce55-6b06-4497-8d5d-1e19fe4acf63
		summarizeBy: none
		sourceColumn: Latest Personalised Care and Support Plan Date

		variation Variation
			isDefault
			relationship: c8d5aa59-00d8-45ea-9265-12df0fa7ff7d
			defaultHierarchy: LocalDateTable_ab0f87bd-b8dd-4c01-8962-820be01ce286.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Latest Personalised Care Plan Desc'
		dataType: string
		lineageTag: 09400def-1e88-41c8-9ad4-7e92999b6339
		summarizeBy: none
		sourceColumn: Latest Personalised Care Plan Desc

		annotation SummarizationSetBy = Automatic

	partition 'PPW Daily Data' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select *#(lf)from PowerBI_Reporting.AgeingWell.tbl18_Daily_Proactive_Whiteboard_Cohort#(lf)#(lf)where in_cohort_flag = 1"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"nhs_number", "NHS Number (Pseudo)"}}),
				    #"Last Treatment Escalation Plan - replace null values for unpivoted data souce" = Table.ReplaceValue(#"Renamed Columns",null,#datetime(1900, 1, 1, 0, 0, 0),Replacer.ReplaceValue,{"Last Treatment Escalation Plan Date"})
				in
				    #"Last Treatment Escalation Plan - replace null values for unpivoted data souce"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

