table '2. A&E  Patient level data QOF'
	lineageTag: 524d9853-8132-4ada-8415-d16f21295fcc

	measure PercentageQOF = calculate(sum('2. A&E  Patient level data QOF'[Value]))/calculate(sum('2. A&E  Patient level data QOF'[Counter]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5f159e04-761c-48eb-9bde-2503e1a8f88c

	column CDS_Unique_Identifier
		dataType: string
		lineageTag: 4a163095-4c2c-4169-af7f-2ab9bc0a3cf7
		summarizeBy: none
		sourceColumn: CDS_Unique_Identifier

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: fc495e79-f937-4883-b2f8-1f0080bd7b4a
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 819bbd01-ef8c-46ae-a4a3-0512cbd63e77
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Counter = 1
		formatString: 0
		lineageTag: 56b22bd5-9242-4162-8cea-c6061bee8817
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition '2. A&E  Patient level data QOF' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select id, data_source, counter, nhs_number, local_patient_identifier as ""Local_Patient_Identifier"", cds_unique_identifier as ""CDS_Unique_Identifier"", arrival_date, arrival_time, arrival_hour, arrival_mode_code, arrival_mode, arrival_mode_grouped, attendance_category_code, attendance_category, attendance_source_code, attendance_source, acuity_code, acuity, major_minor_flag, departure_date, departure_time, minutes_in_ed, hours_in_ed, decision_to_admit_date, breach_reason, admitted_flag, discharge_status_code, discharge_status, discharge_destination_code, discharge_destination, discharge_follow_up_code, discharge_follow_up, disposal_method_code, disposal_method, referred_service_code, referred_service, ed_12hr_mh_flag as ""12hour_flag_in_ED_MH_Reasons"", commissioner_group, code_of_commissioner, responsible_ccg_from_general_practice as ""Responsible_CCG_From_General_Practice"", derived_commissioner_based_on_postcode as ""Derived_commissioner_based_on_postcode"", provider_group_derived, provider_group, provider_code, provider_name, site_code, site_name, department_type_code, department_type, chief_complaint_code, chief_complaint, presenting_complaint, diagnosis_code, diagnosis_code_1, diagnosis_code_1_description, ecds_diagnosis_group1 as ""ECDS_Diagnosis_Group1"", ecds_diagnosis_group2 as ""ECDS_Diagnosis_Group2"", ecds_diagnosis_group3 as ""ECDS_Diagnosis_Group3"", ecds_diagnosis_description as ""ECDS_Diagnosis_Description"", ecds_diagnosis_icd10_equivalent as ""ECDS_Diagnosis_ICD10_Equivalent"", ecds_diagnosis_icd10_equivalent_description as ""ECDS_Diagnosis_ICD10_Equivalent_Description"", ecds_diagnosis_icd10_equivalent_chapter as ""ECDS_Diagnosis_ICD10_Equivalent_Chapter"", ecds_diagnosis_icd10_equivalent_subchapter as ""ECDS_Diagnosis_ICD10_Equivalent_SubChapter"", injury_mechanism_code, injury_mechanism, injury_intent_code, injury_intent, injury_place_code, injury_place, injury_activity_type_code, injury_activity_type, injury_illness_flag, mental_health_classification_code, mental_health_classification, mh_att_flag as ""MH_Att_Flag"", ecds_mh_ed_reattendance_within_30_days_flag as ""ECDS_MH_ED_Reattendance_within_30_days_flag"", ecds_mh_ed_reattendance_within_6_months_flag as ""ECDS_MH_ED_Reattendance_within_6_months_flag"", ecds_mh_ed_reattendance_within_12_months_flag as ""ECDS_MH_ED_Reattendance_within_12_months_flag"", current_hiu_flag as ""Current_HIU_flag"", current_hiu_flag_identified_date as ""Current_HIU_flag_identified_date"", hrg_code, hrg_description, hrg_sub_chapter_description, tariff, mff as ""MFF"", total_tariff_plus_mff as ""total_tariff_plus_MFF"", tariff_applied, financial_year, month_name, financial_month, year_month, census_date, weekday_name, gender, gender_code, age_at_activity_date, locality, primary_care_network, practice_code, practice_name, lsoa, postcode_key, postcode_ecds, deprivation_decile, core_20, age_band_5yr as ""5yr_age_band"", age_band_10yr as ""10yr_age_band"", working_age_band, ethnic_origin_code, ethnic_origin, ethnic_origin_group, living_in_a_care_home, living_alone, mild_frailty, moderate_frailty, severe_frailty, efi_category, atrialfib_flag, asthma_flag, cancer_flag, coronaryheart_flag, chronickidney_flag, copd_flag, dementia_flag, depression_flag, diabetes_flag, epilepsy_flag, heartfailure_flag, hypertension_flag, learningdisability_flag, mentalhealth_flag, obesity_flag, peripheralarterialdisease_flag, palliativecare_flag, stroke_flag, tia_flag, spc_flag as ""SPC Flag"", ytd_flag as ""YTD Flag"", weekday_sorter as ""Weekday Sorter"", latest_month_flag as ""Latest_Month_Flag"", latest_month_flag_1920 as ""1920_Latest_Month_Flag"", last_updated as ""Last_Updated"" from data_mart_powerbi_urgentcare.tbl01_ecds where arrival_date >= '2018-04-01'", null, [EnableFolding=true]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"id", "data_source", "counter", "arrival_date", "arrival_time", "arrival_hour", "arrival_mode_code", "arrival_mode", "arrival_mode_grouped", "attendance_category_code", "attendance_category", "attendance_source_code", "attendance_source", "acuity_code", "acuity", "major_minor_flag", "departure_date", "departure_time", "minutes_in_ed", "decision_to_admit_date", "breach_reason", "admitted_flag", "discharge_status_code", "discharge_status", "discharge_destination_code", "discharge_destination", "discharge_follow_up_code", "discharge_follow_up", "disposal_method_code", "disposal_method", "referred_service_code", "referred_service", "commissioner_group", "code_of_commissioner", "provider_group", "provider_code", "provider_name", "site_code", "site_name", "department_type_code", "department_type", "chief_complaint_code", "chief_complaint", "presenting_complaint", "diagnosis_code", "diagnosis_code_1", "diagnosis_code_1_description", "injury_mechanism_code", "injury_mechanism", "injury_intent_code", "injury_intent", "injury_place_code", "injury_place", "injury_activity_type_code", "injury_activity_type", "injury_illness_flag", "mental_health_classification_code", "mental_health_classification", "MH_Att_Flag", "hrg_code", "hrg_description", "hrg_sub_chapter_description", "tariff", "MFF", "total_tariff_plus_MFF", "tariff_applied", "financial_year", "month_name", "financial_month", "year_month", "census_date", "weekday_name", "gender", "age_at_activity_date", "locality", "primary_care_network", "practice_code", "practice_name", "lsoa", "postcode_key", "postcode_ecds", "deprivation_decile", "core_20", "5yr_age_band", "10yr_age_band", "working_age_band", "ethnic_origin_code", "ethnic_origin", "ethnic_origin_group", "living_in_a_care_home", "living_alone", "mild_frailty", "moderate_frailty", "severe_frailty", "efi_category", "nhs_number", "ECDS_Diagnosis_Group1", "ECDS_Diagnosis_Group2", "ECDS_Diagnosis_Group3", "ECDS_Diagnosis_Description", "ECDS_Diagnosis_ICD10_Equivalent", "ECDS_Diagnosis_ICD10_Equivalent_Description", "ECDS_Diagnosis_ICD10_Equivalent_Chapter", "ECDS_Diagnosis_ICD10_Equivalent_SubChapter", "gender_code", "hours_in_ed", "provider_group_derived", "SPC Flag", "YTD Flag", "Weekday Sorter", "Latest_Month_Flag", "1920_Latest_Month_Flag"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"CDS_Unique_Identifier"}, "Attribute", "Value")
				in
				    #"Unpivoted Other Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

