table '3. Admissions QOF'
	lineageTag: 8be4c763-d3c3-4326-be70-a64e68c9b794

	column UniqueCDSidentifier
		dataType: string
		lineageTag: 8b07282f-f20a-451d-ab6d-830f1a01e5d8
		summarizeBy: none
		sourceColumn: UniqueCDSidentifier

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 6b96e537-b0cf-4100-bc9e-b5fde43a7b83
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		formatString: 0
		lineageTag: 9638998b-f462-4e33-87b1-af3205ab7191
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition '3. Admissions QOF' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select nhs_number, start_date, discharge_ready_date, discharge_date, age, practice_code, provider_code, site_code, treatment_function_code, hrg_code, patient_classification_code, readmission_flag, counter, financial_year, month_name, financial_month, year_month, practice_name, primary_care_network, locality, post_code, lsoa, deprivation, ""5yr_age_band"", ""10yr_age_band"", ethnic_origin, ethnic_origin_group, efi_category, provider_name, provider_group, site_name, treatment_function_description, hrg_description, hrg_sub_chapter_description, total_bed_days, patient_classification, ""short_stay_0-1_day_flag"", short_stay_72hr_flag, ""long_stay_28day+_flag"", nctr_flag as ""NCTR_flag"", nctr_time as ""NCTR_Time"", community_hospital_flag as ""Community_Hospital_Flag"", admission_method_group_grouped, working_age_band, los_bands as ""LoS_Bands"", commissioner_code, assessment_flag, ytd_flag as ""YTD_Flag"", admission_hour, admission_day, commissioner_group, gender, glos_deprivation, icd10_description as ""ICD10_description"", icd10_chapter as ""ICD10_chapter"", icd10_subchapter as ""ICD10_subchapter"", discharge_destination_group_grouped, uniquecdsidentifier as ""UniqueCDSidentifier"", ght_admitting_ward_code as ""GHT_admitting_ward_code"", ght_admitting_ward as ""GHT_admitting_ward"", ght_discharging_ward_code as ""GHT_discharging_ward_code"", ght_discharging_ward as ""GHT_discharging_ward"", ght_all_ward_codes as ""GHT_all_ward_codes"", ght_all_wards as ""GHT_all_wards"", sdec_flag, ""spc flag"" as ""SPC Flag"", atrialfib_flag, asthma_flag, cancer_flag, coronaryheart_flag, chronickidney_flag, copd_flag, dementia_flag, depression_flag, diabetes_flag, epilepsy_flag, heartfailure_flag, hypertension_flag, learningdisability_flag, mentalhealth_flag, obesity_flag, peripheralarterialdisease_flag, palliativecare_flag, stroke_flag, tia_flag, los_bands_order as ""LoS_Bands_Order"", total_tariff_plus_mff, tariff_used, mh_related_admission as ""MH_Related_Admission"", los as ""LoS"" from data_mart_powerbi_secondarycare.tbl07_inpatients_uec", null, [EnableFolding=true]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"counter", "nhs_number", "start_date", "admission_hour", "admission_day", "discharge_ready_date", "NCTR_Time", "discharge_date", "LoS_Bands", "LoS_Bands_Order", "treatment_function_code", "treatment_function_description", "hrg_code", "ICD10_description", "ICD10_chapter", "ICD10_subchapter", "patient_classification_code", "hrg_description", "hrg_sub_chapter_description", "total_bed_days", "patient_classification", "admission_method_group_grouped", "discharge_destination_group_grouped", "assessment_flag", "readmission_flag", "sdec_flag", "short_stay_0-1_day_flag", "short_stay_72hr_flag", "long_stay_28day+_flag", "NCTR_flag", "Community_Hospital_Flag", "YTD_Flag", "provider_group", "provider_name", "provider_code", "site_code", "site_name", "commissioner_group", "commissioner_code", "age", "gender", "locality", "primary_care_network", "practice_code", "practice_name", "post_code", "lsoa", "deprivation", "glos_deprivation", "5yr_age_band", "10yr_age_band", "working_age_band", "ethnic_origin", "ethnic_origin_group", "efi_category", "financial_year", "month_name", "financial_month", "year_month", "SPC Flag", "GHT_admitting_ward_code", "GHT_admitting_ward", "GHT_discharging_ward_code", "GHT_discharging_ward", "GHT_all_ward_codes", "GHT_all_wards", "total_tariff_plus_mff", "tariff_used"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"UniqueCDSidentifier"}, "Attribute", "Value")
				in
				    #"Unpivoted Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

