table 'Chief Complaint Group'
	lineageTag: b10b79a3-d7a0-413a-8778-3d83a860a2a2

	column 'Chief Complaint'
		dataType: string
		lineageTag: b4c027e6-a055-402c-8818-85452596f566
		summarizeBy: none
		sourceColumn: Chief Complaint

		annotation SummarizationSetBy = Automatic

	column 'Chief Complaint Group'
		dataType: string
		lineageTag: b94d4292-50f2-4ddd-b17b-f1c7383009f1
		summarizeBy: none
		sourceColumn: Chief Complaint Group

		annotation SummarizationSetBy = Automatic

	partition 'Chief Complaint Group-7ab5ca74-fa8c-4f7c-9ce1-658bbba23c5d' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lVjJcts4EP0VlM92eWr+wLuTchSV5TiH1BxAsCViBKI5WCTRXz8NkJQoi6Doi0tGvwZ6X/jnz8VNpRE4k5q5ApiGbYZGX1xe3Eiz5TW7ZpkB7gqpVxf/XP65uJfLpRReubpHSKNrG69PIx7RgFxplmFeByEM2Eoa7tDUzBkuXJr1mUOJlauttGnQa+8+buj2kQsXzsgcTRpwx00uuThcdCcN2YI7iZrAoginERh+sYpLPQJ6kWXGpBUF6SH5CHAG3DBba4EVjMDmXFXSxXM7AlucveiXlnQKhiumYMUgh3JMvIddhdYbYA5ZphBzxnV+jabx6VJ5mRP3g95Ig7oE7bhq/FdXSDFnGuVP6d/0v568lvt4M71XSkEiQfvcBB5QIMinZ7lmqJec/mHWZyUYSxoO4uYoLeom4k+pb7iTgsFySY8yXLIVt5ds6Uuw7GZ2f/3zlW14hd7YQe77GAlmBWxpsGRQR1Hpb5MlSuH2ylcMq8IVXJWocBUV49aCteGiI3wvq8hdsCN36mCGo2tba5GsdE6pt2oVb8lzit+Qk8dM8wIdSYFZ47b29BXyT7h3aT29mEvrvMm4Fn3iTZZjKYNEbZI8cesMSu0oqsJ5RN3GaCIJyKRkRVuXlcMyhb6juHeyigGawtxLyt2iqUjDAKpYBV/JJOBzwcrlKpA3sC9Xk9gQLIaHvJ3KYSisfFL5UAwpZynYZPLGZykE+lWRBBzigeu0YN+517mM7hykv6C18Y6qAiddEjfj3qYd8UrqngmPxZbSAjTjIZggCXunSHNN0g7SbyxVId14HHQse9eMgpMq2DXjOf1qYU34UXyJM9A7U9N75LQlj2k5iq25xtZpI7BH2IA5g3lGGxqAikc2VLFLRhFBNUWL+pIiNYTQuTvqihhULbqmdAaMU7E/gGKmaR4G/vPkAMjPsFBDAyawrBTs2pweQ6OlukTkmIyRrX3wDOMChQyRZjBTUJ4B/0YKfiZ47CRjwH3t8kbqFiwdhv+4qbtaQ//yQdqj4nq9j/4T8lOIYlZS8R8kHxKZDELP+3IQ9lPJVVKCrvpbYdAlLpjTiT223AkivN9L5FMEqjopxCs46mwhaEiXtCXfpXCyDBgLu9B1+GpFI5rdO/8T/lYBhSOlaOy1lH/h2mfgcXShIVis245C1XKQ8kATWd517BSC08zSNS07CPpc42nQm4Qr0bthwT4jk7rRiQkWUGiHZesNBwmpDojkKzNuyRsCdWyS0RsDIPrRxccptYvDJRfDb8zJCTU9EOa3LSjVlPpT3ALDjFoY5K43Spzi3qSmePHDVrlT6HOadUglKyR6qyHabwbedDNZN891c0+w0AT8x4dMEYMcIZqGaN+0xbJpXye0H94KqqFb4OtwdRBE0dYxBJ35Mks9vwD50czOp6QKQBQsr+3Sa9G6+AT1ZmhVM0OUXzSzkXI1TcvSjQK21KTZlqt1498T4O+ekiFWWBmVH1Tolta6sKDtC9fP7KnWgwm0oWFQ8yPIE8Vy08lWYT0EQ1HFNfv7LzI0rG0Cq4JsaeB7fEfRBtWUpkHikMA3eifB1XQ2t7Uo0Dbt7JrdQsE3FHKGdidO+dFoLj/C9sqyjjiR7y70U8rEUDKCgQFCnrEcqlBnYyufcs19h6cShlOZnrlSXpAButV2CtO8qG2zIPVbwRTOBajllQy1LeTrly218Bm5PKQ9DWE+1sUpbDeZ4a2Qi3U3Q9D0zK7YNswcR+feHOEejK/cJ97PcUyrrfAkFwSdHI2HHvrwb04UrW/tWh7d9ELJZJoYvmLRLnWfPA95H9b/KOYgJPzoxe7hvELdiZQZL20T9we6S4h0y8W6rYdvhvuShxGM0t1TN1vT1t8t1c13mL1Ao9je8rPfJyYykH02MdaaFTocZSTh9Ava3jYRXVA9nI5WuKUKBTtHNVi6L5gh9rzJaE/b3hee+R62sH6/HkW/RB2CTSc6sxsaGuXbnjeJo9FjCkdDpG2Q8bLyrls1JvJM0+NXlOYLis/ClzIJy2YB4sHItPWhyWOJnqGGw/8xQ44+aXYfzlx84mLkI2LruBjqh6+Fe2uPfYB8NLSpZc2HgdPvYPu9ibY5VMnV30shc3rSFWFGd1O7Ql/uo9gYFPaf/wE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Chief Complaint" = _t, #"Chief Complaint Group" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Chief Complaint", type text}, {"Chief Complaint Group", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

