table 'ED Attendances'
	lineageTag: 644c967f-5866-49bb-b819-01280dad488b

	column 'Fiscal Year'
		dataType: string
		lineageTag: 3e077c7c-bd94-4ab3-873e-78ec3ef9ed72
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Organisation - STP of Registration'
		dataType: string
		lineageTag: ef751504-e803-4250-b80b-d03ab4488685
		summarizeBy: none
		sourceColumn: Organisation - STP of Registration

		annotation SummarizationSetBy = Automatic

	column 'Chief Complaint'
		dataType: string
		lineageTag: 59bf8002-e306-4e29-b77e-e577c7191f84
		summarizeBy: none
		sourceColumn: Chief Complaint

		annotation SummarizationSetBy = Automatic

	column 'All Attendances'
		dataType: int64
		formatString: 0
		lineageTag: e418cc02-276d-47db-a3f6-c67ae72f1ac9
		summarizeBy: sum
		sourceColumn: All Attendances

		annotation SummarizationSetBy = Automatic

	column 'Total Tariff'
		dataType: double
		lineageTag: 0706aa37-5345-4197-9e6b-2b035f69f845
		summarizeBy: sum
		sourceColumn: Total Tariff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Av. Tariff'
		dataType: double
		lineageTag: 40aa35e4-487d-4b69-97f6-6a7a31370117
		summarizeBy: sum
		sourceColumn: Av. Tariff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No. Admissions from A&E'
		dataType: double
		lineageTag: 883d6bfb-432f-4838-86fa-b9eba2aa6d40
		summarizeBy: sum
		sourceColumn: No. Admissions from A&E

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Admitted'
		dataType: double
		lineageTag: 48e5a935-cc2f-4cc3-9e57-4811bf76c882
		summarizeBy: sum
		sourceColumn: % Admitted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mean Total Time in A&E for Admitted'
		dataType: string
		lineageTag: 8f9df7c5-38c3-4233-8cc4-91011323867e
		summarizeBy: none
		sourceColumn: Mean Total Time in A&E for Admitted

		annotation SummarizationSetBy = Automatic

	column 'Mean Total Time in A&E for Admitted - Peer Sub ICBs'
		dataType: string
		lineageTag: 83a2ff39-a621-433d-b52e-717016b678a6
		summarizeBy: none
		sourceColumn: Mean Total Time in A&E for Admitted - Peer Sub ICBs

		annotation SummarizationSetBy = Automatic

	column 'Mean Total Time in A&E for Admitted - Trust Group'
		dataType: string
		lineageTag: a2c791f7-f17d-462f-ba4e-95f79e36fa8a
		summarizeBy: none
		sourceColumn: Mean Total Time in A&E for Admitted - Trust Group

		annotation SummarizationSetBy = Automatic

	column 'Mean Total Time in A&E for Admitted - National'
		dataType: string
		lineageTag: 724fcc0e-33c8-4b33-8175-e08778d6914f
		summarizeBy: none
		sourceColumn: Mean Total Time in A&E for Admitted - National

		annotation SummarizationSetBy = Automatic

	column '% Decision to Admit to Admission >12h'
		dataType: double
		lineageTag: 8738db3e-0762-446e-8124-db984a85eb06
		summarizeBy: sum
		sourceColumn: % Decision to Admit to Admission >12h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Decision to Admit to Admission >12h - Peer Sub ICBs'
		dataType: double
		lineageTag: 69b1731e-ea75-44ff-bdfe-78400a845989
		summarizeBy: sum
		sourceColumn: % Decision to Admit to Admission >12h - Peer Sub ICBs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Decision to Admit to Admission >12h - Trust Group'
		dataType: string
		lineageTag: 012722b7-dc3f-4181-93b6-7dee015a9b1b
		summarizeBy: none
		sourceColumn: % Decision to Admit to Admission >12h - Trust Group

		annotation SummarizationSetBy = Automatic

	column '% Decision to Admit to Admission >12h - National'
		dataType: string
		lineageTag: 1117abc7-3579-4bec-b172-f4aedd8bb51c
		summarizeBy: none
		sourceColumn: % Decision to Admit to Admission >12h - National

		annotation SummarizationSetBy = Automatic

	column '% Decision to Admit to Admission <=4h'
		dataType: double
		lineageTag: 6b171cba-eb4f-4412-8f22-23e97ed78c63
		summarizeBy: sum
		sourceColumn: % Decision to Admit to Admission <=4h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Decision to Admit to Admission <=4h - Peer Sub ICBs'
		dataType: double
		lineageTag: 3d057f97-5f68-4572-8260-514fd2d8ee6e
		summarizeBy: sum
		sourceColumn: % Decision to Admit to Admission <=4h - Peer Sub ICBs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Decision to Admit to Admission <=4h - Trust Group'
		dataType: string
		lineageTag: 8d4e988e-536f-4c83-8ff1-b50e2d17df0a
		summarizeBy: none
		sourceColumn: % Decision to Admit to Admission <=4h - Trust Group

		annotation SummarizationSetBy = Automatic

	column '% Decision to Admit to Admission <=4h - National'
		dataType: string
		lineageTag: a7ada15f-1ba6-4319-8133-58fb7e6d65dc
		summarizeBy: none
		sourceColumn: % Decision to Admit to Admission <=4h - National

		annotation SummarizationSetBy = Automatic

	column 'No. 7 Day Reattendances'
		dataType: int64
		formatString: 0
		lineageTag: bc265ce3-c61e-494b-bcd4-ba36b70c9aae
		summarizeBy: sum
		sourceColumn: No. 7 Day Reattendances

		annotation SummarizationSetBy = Automatic

	column 'Unplanned Attendances'
		dataType: int64
		formatString: 0
		lineageTag: 7c272984-d0f2-422d-89a6-0a8acd1078b6
		summarizeBy: sum
		sourceColumn: Unplanned Attendances

		annotation SummarizationSetBy = Automatic

	column '7 Day Reattendance Rate'
		dataType: double
		lineageTag: abe85078-7d4a-429b-a8cd-23af8ef78dff
		summarizeBy: sum
		sourceColumn: 7 Day Reattendance Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '7 Day Reattendance Rate - Peer Sub ICBs'
		dataType: double
		lineageTag: f294998f-f967-4dfb-8712-6a4da910f93e
		summarizeBy: sum
		sourceColumn: 7 Day Reattendance Rate - Peer Sub ICBs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '7 Day Reattendance Rate - Trust Group'
		dataType: string
		lineageTag: a3267bbd-8fbb-4093-a025-9a8832d6fc03
		summarizeBy: none
		sourceColumn: 7 Day Reattendance Rate - Trust Group

		annotation SummarizationSetBy = Automatic

	column '7 Day Reattendance Rate - National'
		dataType: string
		lineageTag: cf4d843a-797a-402f-8bea-1d6800744ecd
		summarizeBy: none
		sourceColumn: 7 Day Reattendance Rate - National

		annotation SummarizationSetBy = Automatic

	column Population = LOOKUPVALUE(Population[Registered Population],Population[Organisation],'ED Attendances'[Organisation - STP of Registration])
		formatString: 0
		lineageTag: c0d41973-5aeb-48e0-9c06-9ccf23fb734d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED Attendance Rate' = DIVIDE('ED Attendances'[All Attendances],('ED Attendances'[Population]/1000))
		lineageTag: b85c82dc-e0e7-4a8a-9ccc-b0268c67d750
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ED 7 day Reattendance Rate' = DIVIDE('ED Attendances'[No. 7 Day Reattendances],('ED Attendances'[Population]/1000))
		lineageTag: d50bbc75-b469-428b-8f9b-a13d196134dc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'ED Attendances-78f8b8e9-253b-4da4-a80d-f9672eefaa76' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("M:\Finance\Business Intelligence\SYSTEM BENCHMARKING\23-24 Plan - benchmarking\23-24 PROG BENCHMARKING\Working Files\Dashboard Files\ED\AE_Strategic_Analysis_Comm_live - Main.csv"),[Delimiter="	", Columns=26, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Fiscal Year", type text}, {"Organisation - STP of Registration", type text}, {"Chief Complaint", type text}, {"All Attendances", Int64.Type}, {"Total Tariff", Currency.Type}, {"Av. Tariff", Currency.Type}, {"No. Admissions from A&E", Int64.Type}, {"% Admitted", Percentage.Type}, {"Mean Total Time in A&E for Admitted", type time}, {"Mean Total Time in A&E for Admitted - Peer Sub ICBs", type time}, {"Mean Total Time in A&E for Admitted - Trust Group", type text}, {"Mean Total Time in A&E for Admitted - National", type text}, {"% Decision to Admit to Admission >12h", Percentage.Type}, {"% Decision to Admit to Admission >12h - Peer Sub ICBs", Percentage.Type}, {"% Decision to Admit to Admission >12h - Trust Group", type text}, {"% Decision to Admit to Admission >12h - National", type text}, {"% Decision to Admit to Admission <=4h", Percentage.Type}, {"% Decision to Admit to Admission <=4h - Peer Sub ICBs", Percentage.Type}, {"% Decision to Admit to Admission <=4h - Trust Group", type text}, {"% Decision to Admit to Admission <=4h - National", type text}, {"No. 7 Day Reattendances", Int64.Type}, {"Unplanned Attendances", Int64.Type}, {"7 Day Reattendance Rate", Percentage.Type}, {"7 Day Reattendance Rate - Peer Sub ICBs", Percentage.Type}, {"7 Day Reattendance Rate - Trust Group", type text}, {"7 Day Reattendance Rate - National", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,0,Replacer.ReplaceValue,{"Total Tariff", "Av. Tariff", "No. Admissions from A&E", "% Admitted", "Mean Total Time in A&E for Admitted", "Mean Total Time in A&E for Admitted - Peer Sub ICBs", "Mean Total Time in A&E for Admitted - Trust Group", "Mean Total Time in A&E for Admitted - National"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

