table Population
	lineageTag: eb4cb28a-620b-4d83-86be-3deabcd15ff8

	column Organisation
		dataType: string
		lineageTag: fe49946f-9d9f-46c3-b4ba-9f7c9e899c52
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column 'Registered Population'
		dataType: int64
		formatString: 0
		lineageTag: 3cce5a5f-aab4-43b5-af91-0d85f459e1c3
		summarizeBy: sum
		sourceColumn: Registered Population

		annotation SummarizationSetBy = Automatic

	partition Population-79096d19-588f-46d8-a3ce-49134baf26fe = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZJNbsQgDIWvgrL2AvIDYckEZ4KGgQpIp9Vo7n+NElIpaaUm3RmJ79nv2c9n5aZILipNRDlNnA+5QhUTif6OIWICEh/Gae/Kh4exKU4mIDEu4TWohJoMKr8vXgVdQUWkkCAlI9ULVnWN4fJZ6FKd4AwY7YE33V7gPbc/IGpBQfwg/DL630jPZAb6DbhaPw8YU7Z8PB4XLTRcbOSEAUcf9MqVjHz4l1TPOqhZs0lZ4wZv3RlGM1bLDbsbXfpGPy/LixE/jsKiXABr6cbHKfi30hRIQruYWX0EvJmD3LscImXtTuj7ZA4Q2ULd7W4jzuPo7e338Z2baDlIyrPQ6ws=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Organisation = _t, #"Registered Population" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Organisation", type text}, {"Registered Population", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

