table GHT_OntheDay
	lineageTag: 8109d384-f4e3-4a0c-8c47-cb89c240e809

	measure 'Completed: Counter (GHT) minus Aborts or Cancel Flag' =
			
			SUM('GHT_OntheDay'[Counter (GHT)]) - SUM('GHT_OntheDay'[Aborts or Cancel Flag])
		formatString: 0
		lineageTag: f39aba64-168f-42b1-a80d-a5582e155bba

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalSubtraction"
				}

		changedProperty = FormatString

	measure 'Proportion GHT: Completed (GHT) out of Booked (GHT)' =
			
			DIVIDE(
				[Completed: Counter (GHT) minus Aborts or Cancel Flag],
				SUM('GHT_OntheDay'[Counter (GHT)])
			)
		formatString: 0%;-0%;0%
		lineageTag: d4acb1c4-13ca-4933-a58b-6d2a227fbad0

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Proportion (GHT): Aborts out of Booked (GHT)' =
			
			DIVIDE(
				SUM('GHT_OntheDay'[Aborts only Flag]),
				SUM('GHT_OntheDay'[Counter (GHT)])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 02c869ea-fec1-46a3-ac9b-4119b9e27828

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Proportion (GHT) :Cancelled out of Booked (GHT)' =
			
			DIVIDE(
				SUM('GHT_OntheDay'[Cancelled only Flag]),
				SUM('GHT_OntheDay'[Counter (GHT)])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 335e5cfc-3e1f-44b2-86c5-e01905bc3ccb

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Complete + Aborts (GHT)' =
			
			SUM('GHT_OntheDay'[Counter (GHT)]) - SUM('GHT_OntheDay'[Cancelled only Flag])
		formatString: 0
		lineageTag: cd8a33d3-bd17-47ad-9142-7f1fef3b66f6

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalSubtraction"
				}

		changedProperty = FormatString

	column Activity_Month_GHT
		dataType: string
		lineageTag: e8bd0e08-2bda-48ad-9a24-48f7793c2ca1
		summarizeBy: none
		sourceColumn: Activity_Month_GHT

		annotation SummarizationSetBy = Automatic

	column passengerID
		dataType: int64
		formatString: 0
		lineageTag: ea5f5132-1518-4b40-b92c-80dc86997db8
		summarizeBy: count
		sourceColumn: passengerID

		annotation SummarizationSetBy = Automatic

	column Pseudo_NHS_Number
		dataType: string
		lineageTag: 79cc3c52-5b07-4282-83a6-067f23e19138
		summarizeBy: none
		sourceColumn: Pseudo_NHS_Number

		annotation SummarizationSetBy = Automatic

	column MPI_Pseudo_NHS_no
		dataType: string
		lineageTag: 9bf13a60-e45d-45a0-a004-0bf53cf64826
		summarizeBy: none
		sourceColumn: MPI_Pseudo_NHS_no

		annotation SummarizationSetBy = Automatic

	column Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8c92a4bf-c52c-41bc-9421-11dc0be4abe5
		summarizeBy: none
		sourceColumn: Start_Date

		variation Variation
			isDefault
			relationship: 6bd4a1d7-204d-45be-aab2-e6c334cdca1f
			defaultHierarchy: LocalDateTable_aae2a4db-f7d7-4900-b9ca-9083f819677e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Contract GHT OTD '
		dataType: string
		lineageTag: a11257f0-0e46-426d-8031-352040e8162d
		summarizeBy: none
		sourceColumn: "Contract GHT OTD "

		annotation SummarizationSetBy = Automatic

	column Contract_Hospital_Description
		dataType: string
		lineageTag: 7dc9976b-14a8-42ae-b190-0a735dc9e5e9
		summarizeBy: none
		sourceColumn: Contract_Hospital_Description

		annotation SummarizationSetBy = Automatic

	column Contract_Clinic_Description
		dataType: string
		lineageTag: fce13add-e1df-4827-93f3-2d2a1bf3719a
		summarizeBy: none
		sourceColumn: Contract_Clinic_Description

		annotation SummarizationSetBy = Automatic

	column Requested_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d72a1cf-7169-4fb9-bd4a-a6adc258e93e
		summarizeBy: none
		sourceColumn: Requested_DateTime

		variation Variation
			isDefault
			relationship: af0f2d08-86bb-4fcd-9adc-3f6c82b01f54
			defaultHierarchy: LocalDateTable_f257bb27-a6fe-431c-b100-88591e880ad0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Requested_Method_Description
		dataType: string
		lineageTag: f4a07b67-db02-40c6-a117-cfc8c39c2efe
		summarizeBy: none
		sourceColumn: Requested_Method_Description

		annotation SummarizationSetBy = Automatic

	column Transport_Reason_Description
		dataType: string
		lineageTag: 36b132e3-5529-497c-ae6f-5c42b6cdde05
		summarizeBy: none
		sourceColumn: Transport_Reason_Description

		annotation SummarizationSetBy = Automatic

	column Booking_Source
		dataType: string
		lineageTag: 41d6d715-dc17-43ef-8bae-13f2a37dc0e6
		summarizeBy: none
		sourceColumn: Booking_Source

		annotation SummarizationSetBy = Automatic

	column Direction_Description
		dataType: string
		lineageTag: f3095037-f54e-419d-b463-732a25248505
		summarizeBy: none
		sourceColumn: Direction_Description

		annotation SummarizationSetBy = Automatic

	column From_Hospital_Description
		dataType: string
		lineageTag: 7269eef6-9ed5-40d9-adbb-5bbcabca3195
		summarizeBy: none
		sourceColumn: From_Hospital_Description

		annotation SummarizationSetBy = Automatic

	column To_Hospital_Description
		dataType: string
		lineageTag: afb30d18-d209-4d7c-9fce-f5b0af457edb
		summarizeBy: none
		sourceColumn: To_Hospital_Description

		annotation SummarizationSetBy = Automatic

	column From_Clinic_Description
		dataType: string
		lineageTag: b7e4b7aa-31d2-4c12-9060-9f18d136cc4f
		summarizeBy: none
		sourceColumn: From_Clinic_Description

		annotation SummarizationSetBy = Automatic

	column To_Clinic_Description
		dataType: string
		lineageTag: 509575f1-ccb6-4154-92ba-4109bcb34169
		summarizeBy: none
		sourceColumn: To_Clinic_Description

		annotation SummarizationSetBy = Automatic

	column Category_Description
		dataType: string
		lineageTag: a0942919-e51e-444c-abe2-8f8037d81600
		summarizeBy: none
		sourceColumn: Category_Description

		annotation SummarizationSetBy = Automatic

	column Category_Mapped_Description
		dataType: string
		lineageTag: 437f5b78-fa3c-4c8d-bf31-c4ce9c87f658
		summarizeBy: none
		sourceColumn: Category_Mapped_Description

		annotation SummarizationSetBy = Automatic

	column Cat_Mapped_Desc_National
		dataType: string
		lineageTag: 6b8b890f-d843-4539-bc15-2aeae4ab17b6
		summarizeBy: none
		sourceColumn: Cat_Mapped_Desc_National

		annotation SummarizationSetBy = Automatic

	column Booking_Notice_Days
		dataType: int64
		formatString: 0
		lineageTag: 8a68786a-9ef5-4617-bdcb-298bb0b3b39c
		summarizeBy: sum
		sourceColumn: Booking_Notice_Days

		annotation SummarizationSetBy = Automatic

	column Booking_Notice_Days_Grouped
		dataType: string
		lineageTag: 349bea89-e2c5-42ef-8a6d-4313d681d3cb
		summarizeBy: none
		sourceColumn: Booking_Notice_Days_Grouped

		annotation SummarizationSetBy = Automatic

	column Requested_on_or_After_Day_of_Transport
		dataType: int64
		formatString: 0
		lineageTag: d5ce346a-9568-4773-8996-484233b089e7
		summarizeBy: sum
		sourceColumn: Requested_on_or_After_Day_of_Transport

		annotation SummarizationSetBy = Automatic

	column Planned_Journey_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0f43e0c5-2c84-41f2-b964-00a34d3b2e37
		summarizeBy: none
		sourceColumn: Planned_Journey_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Planned_Time
		dataType: int64
		formatString: 0
		lineageTag: d471cf01-559a-4c81-9299-e7fbc521ed76
		summarizeBy: sum
		sourceColumn: Planned_Time

		annotation SummarizationSetBy = Automatic

	column Journey_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: e75b625f-5457-4bb1-b454-454dcb7a38f0
		summarizeBy: none
		sourceColumn: Journey_DateTime

		variation Variation
			isDefault
			relationship: b2a671f4-5e04-4d63-8bbd-f9d3f43550e3
			defaultHierarchy: LocalDateTable_56c07a7f-4922-484f-a2d8-762483a58ffd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Journey_Hour
		dataType: int64
		formatString: 0
		lineageTag: 0a8f014f-6243-45ae-af7e-1e3290ec18d9
		summarizeBy: sum
		sourceColumn: Journey_Hour

		annotation SummarizationSetBy = Automatic

	column Journey_Day
		dataType: string
		lineageTag: d6362161-f357-4ea3-a8e4-a8a7b1672b9c
		summarizeBy: none
		sourceColumn: Journey_Day

		annotation SummarizationSetBy = Automatic

	column Ready_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 88d64af8-0360-412e-821d-d687736d41d8
		summarizeBy: none
		sourceColumn: Ready_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Pick_Up_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 1af546ba-ac4a-4140-97c0-eb6737aea1e2
		summarizeBy: none
		sourceColumn: Pick_Up_DateTime

		variation Variation
			isDefault
			relationship: b4d79ab2-7fdd-4700-8293-36e074258c8d
			defaultHierarchy: LocalDateTable_bdb7c153-4d9e-42ef-821f-c684553d6637.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Drop_Off_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: d70777a7-61f2-49f8-b304-4d3aa2a04224
		summarizeBy: none
		sourceColumn: Drop_Off_DateTime

		variation Variation
			isDefault
			relationship: c3cf827a-e944-4007-911a-68047993d400
			defaultHierarchy: LocalDateTable_74ed9eb3-16d0-4845-913e-854fdaa8962a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Time_on_Vehicle_Minutes
		dataType: int64
		formatString: 0
		lineageTag: 2c7fba47-d422-4bba-a538-094343cde125
		summarizeBy: sum
		sourceColumn: Time_on_Vehicle_Minutes

		annotation SummarizationSetBy = Automatic

	column Early_Late_Minutes
		dataType: int64
		formatString: 0
		lineageTag: 2274cc53-a1ff-463d-8464-8b82f8d10688
		summarizeBy: sum
		sourceColumn: Early_Late_Minutes

		annotation SummarizationSetBy = Automatic

	column Wait_and_Return_Flag
		dataType: int64
		formatString: 0
		lineageTag: d55d3ba7-66a4-4714-947b-bc3eb590a789
		summarizeBy: sum
		sourceColumn: Wait_and_Return_Flag

		annotation SummarizationSetBy = Automatic

	column Waiting_Time_Minutes
		dataType: int64
		formatString: 0
		lineageTag: 4532ae4d-13d0-492f-8e7c-3e57e1a7e050
		summarizeBy: sum
		sourceColumn: Waiting_Time_Minutes

		annotation SummarizationSetBy = Automatic

	column Escort_Seats
		dataType: int64
		formatString: 0
		lineageTag: 6b21932a-e4fb-4cc1-ba60-77d5dad2001f
		summarizeBy: sum
		sourceColumn: Escort_Seats

		annotation SummarizationSetBy = Automatic

	column Medical_Escort_Count
		dataType: int64
		formatString: 0
		lineageTag: 3a2ccb00-cb60-4241-b4d2-bc48e72cca73
		summarizeBy: sum
		sourceColumn: Medical_Escort_Count

		annotation SummarizationSetBy = Automatic

	column Relative_Escort_Count
		dataType: int64
		formatString: 0
		lineageTag: c3ad8928-c465-4639-84fc-84b7c8d79192
		summarizeBy: sum
		sourceColumn: Relative_Escort_Count

		annotation SummarizationSetBy = Automatic

	column Speciality_Description
		dataType: string
		lineageTag: be6fe0c0-0928-4399-8523-9f53d4c619e6
		summarizeBy: none
		sourceColumn: Speciality_Description

		annotation SummarizationSetBy = Automatic

	column total_passengers_carried
		dataType: int64
		formatString: 0
		lineageTag: 264436cf-cd30-497b-80bf-c970d0061e93
		summarizeBy: sum
		sourceColumn: total_passengers_carried

		annotation SummarizationSetBy = Automatic

	column Planned_Mileage
		dataType: double
		formatString: #,0
		lineageTag: 1306890a-aa59-44e9-b2e6-7f60731030a4
		summarizeBy: sum
		sourceColumn: Planned_Mileage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Actual_Mileage
		dataType: double
		formatString: #,0
		lineageTag: 20caed8c-673f-4d98-8a58-9e74d464ee5c
		summarizeBy: sum
		sourceColumn: Actual_Mileage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Mobility_Description
		dataType: string
		lineageTag: d8ce40d7-0736-4e2f-aa0f-ce12b773c3d3
		summarizeBy: none
		sourceColumn: Mobility_Description

		annotation SummarizationSetBy = Automatic

	column Mobility_MainGroup
		dataType: string
		lineageTag: fe26e28d-bc4e-4f56-9ece-78d724e9db29
		summarizeBy: none
		sourceColumn: Mobility_MainGroup

		annotation SummarizationSetBy = Automatic

	column National_Mobility_High_Level
		dataType: string
		lineageTag: 2de7597b-38d1-4f7e-8ba6-d9f2cfdabe0b
		summarizeBy: none
		sourceColumn: National_Mobility_High_Level

		annotation SummarizationSetBy = Automatic

	column National_Mobility_Sub_Level
		dataType: string
		lineageTag: 4c2bb073-488b-49ba-afac-7cbd35521711
		summarizeBy: none
		sourceColumn: National_Mobility_Sub_Level

		annotation SummarizationSetBy = Automatic

	column National_Mobility_Add_Req
		dataType: string
		lineageTag: 58ce03ec-dc0b-4140-ada2-881e72a0a298
		summarizeBy: none
		sourceColumn: National_Mobility_Add_Req

		annotation SummarizationSetBy = Automatic

	column 'Aborts (GHT)'
		dataType: string
		lineageTag: cf6828cf-32be-4927-825f-6c8a5ac636f4
		summarizeBy: none
		sourceColumn: Aborts (GHT)

		annotation SummarizationSetBy = Automatic

	column 'Cancelled (GHT)'
		dataType: string
		lineageTag: 6a06b0b2-727f-4632-bd10-b409cec597f0
		summarizeBy: none
		sourceColumn: Cancelled (GHT)

		annotation SummarizationSetBy = Automatic

	column Cancelled_on_Day_of_Transport
		dataType: int64
		formatString: 0
		lineageTag: 3cd4adef-a3ff-49ab-99db-9997d06acfcb
		summarizeBy: sum
		sourceColumn: Cancelled_on_Day_of_Transport

		annotation SummarizationSetBy = Automatic

	column Derived_EarlyLate_Minute_Timeband
		dataType: string
		lineageTag: 3b946f39-a516-48b2-a1e4-c8e63bf3d1d4
		summarizeBy: none
		sourceColumn: Derived_EarlyLate_Minute_Timeband

		annotation SummarizationSetBy = Automatic

	column Derived_Waiting_Time_Minute_Timeband
		dataType: string
		lineageTag: f933cec1-2314-42a6-a879-311c8b0c13ae
		summarizeBy: none
		sourceColumn: Derived_Waiting_Time_Minute_Timeband

		annotation SummarizationSetBy = Automatic

	column Patient_Age_When_Transported
		dataType: string
		lineageTag: 3d836220-1069-4757-9bca-c7cc00d94334
		summarizeBy: none
		sourceColumn: Patient_Age_When_Transported

		annotation SummarizationSetBy = Automatic

	column AgeBand_National
		dataType: string
		lineageTag: af549ed9-1b05-42f6-b93b-c9b5024d3111
		summarizeBy: none
		sourceColumn: AgeBand_National

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: fd268da9-fb84-4e21-b0bb-a5edfe6b589d
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin'
		dataType: string
		lineageTag: 9fc01962-ea83-4fc8-b792-57ebe5889983
		summarizeBy: none
		sourceColumn: Ethnic Origin

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: db772069-cdd4-42eb-b6f4-b0a4ee301b2d
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 03fd8470-7494-4968-b58b-0031253493ed
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column Core20Flag
		dataType: int64
		formatString: 0
		lineageTag: a7faaa15-6437-4e2c-aedf-6cc5a7c5ade8
		summarizeBy: sum
		sourceColumn: Core20Flag

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: b23e8021-2d22-4780-b12e-49e38309c93e
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column localityname
		dataType: string
		lineageTag: 57a462b3-5bb8-43eb-aa3a-7439e219b60d
		summarizeBy: none
		sourceColumn: localityname

		annotation SummarizationSetBy = Automatic

	column NetworkName
		dataType: string
		lineageTag: 714ffcea-8086-4f37-8481-51e66df1b91f
		summarizeBy: none
		sourceColumn: NetworkName

		annotation SummarizationSetBy = Automatic

	column Easting
		dataType: string
		lineageTag: 4747639c-d69d-461f-93ca-de6be4c9d27b
		summarizeBy: none
		sourceColumn: Easting

		annotation SummarizationSetBy = Automatic

	column Northing
		dataType: string
		lineageTag: 1d3783b7-68dd-4701-afe8-5c88e5998815
		summarizeBy: none
		sourceColumn: Northing

		annotation SummarizationSetBy = Automatic

	column RuralUrbanClass
		dataType: string
		lineageTag: 813522b7-77e0-4b38-8ab0-c4645482d071
		summarizeBy: none
		sourceColumn: RuralUrbanClass

		annotation SummarizationSetBy = Automatic

	column SegmentHealthLeeds
		dataType: string
		lineageTag: a1db4ab8-5dd5-4f61-b3b3-2cbdf9eaebe9
		summarizeBy: none
		sourceColumn: SegmentHealthLeeds

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: double
		lineageTag: bd9fe031-32f5-4756-9b30-b56586bcb3bf
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 1 Income'
		dataType: double
		lineageTag: 0833094b-1fca-4f3e-bf8c-0129c0aef78e
		summarizeBy: sum
		sourceColumn: IMD 1 Income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 2 Employment'
		dataType: double
		lineageTag: 97f4d7ba-a8a3-4d3a-a01d-00904c119ecf
		summarizeBy: sum
		sourceColumn: IMD 2 Employment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 3 Education'
		dataType: double
		lineageTag: 460ceb5f-5797-48ae-89cc-defea28a69a6
		summarizeBy: sum
		sourceColumn: IMD 3 Education

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 4 Health'
		dataType: double
		lineageTag: d027c0b1-a925-40c8-a3d7-01d23a0b9c9d
		summarizeBy: sum
		sourceColumn: IMD 4 Health

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 5 Crime'
		dataType: double
		lineageTag: e41bb25e-7b93-40fe-bed2-731d1e3bca4b
		summarizeBy: sum
		sourceColumn: IMD 5 Crime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 6 Barriers to Housing and Services'
		dataType: double
		lineageTag: 6c661632-1f82-40ed-bd3b-9e5633700bac
		summarizeBy: sum
		sourceColumn: IMD 6 Barriers to Housing and Services

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 7 Living Environment'
		dataType: double
		lineageTag: b575ea7b-50f7-4cd4-a1a2-aeb3541d6493
		summarizeBy: sum
		sourceColumn: IMD 7 Living Environment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b970006-fcf9-457c-b6db-d2f1b7bd5f4e
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: 277e4222-9a8f-4121-925a-05ee820a95f0
			defaultHierarchy: LocalDateTable_e87da443-6cfc-43ff-8071-db6d2dad0fb1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Counter (GHT)'
		dataType: int64
		formatString: #,0
		lineageTag: 80317475-d2ce-4bbc-bba2-4ee48578af59
		summarizeBy: sum
		sourceColumn: Counter (GHT)

		annotation SummarizationSetBy = Automatic

	column Date_of_Activity
		dataType: dateTime
		formatString: General Date
		lineageTag: 812b9d4d-c22b-4adb-9595-0e35e39eafb9
		summarizeBy: none
		sourceColumn: Date_of_Activity

		variation Variation
			isDefault
			relationship: 3721e95b-c22b-40fe-962a-156e613a6c64
			defaultHierarchy: LocalDateTable_de187ede-f6d2-42a7-bed8-cc21eef9ff81.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 636ed0a2-5645-461a-b73c-c26dc44be67d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column FinYear
		dataType: string
		lineageTag: d17a758f-3bc8-472f-ad65-df51695d8292
		summarizeBy: none
		sourceColumn: FinYear

		annotation SummarizationSetBy = Automatic

	column Quarter_FinYr
		dataType: string
		lineageTag: 1c0cf88b-f827-4795-985b-91cc35e179eb
		summarizeBy: none
		sourceColumn: Quarter_FinYr

		annotation SummarizationSetBy = Automatic

	column Covid_sus_or_conf_journeys
		dataType: int64
		formatString: 0
		lineageTag: 386694aa-0119-4664-8d27-6677a81553fe
		summarizeBy: sum
		sourceColumn: Covid_sus_or_conf_journeys

		annotation SummarizationSetBy = Automatic

	column Mileage_Bands
		dataType: string
		lineageTag: fcb5b711-7077-4638-8b08-7726aa2f2499
		summarizeBy: none
		sourceColumn: Mileage_Bands

		annotation SummarizationSetBy = Automatic

	column 'Aborts or Cancel Flag'
		dataType: int64
		formatString: 0
		lineageTag: 1c7cef59-3e48-4de5-9db7-b92ac2996eb3
		summarizeBy: sum
		sourceColumn: Aborts or Cancel Flag

		annotation SummarizationSetBy = Automatic

	column 'Aborts only Flag'
		dataType: int64
		formatString: 0
		lineageTag: 908e93bd-7d2e-4614-ba25-ccfd4367d09d
		summarizeBy: sum
		sourceColumn: Aborts only Flag

		annotation SummarizationSetBy = Automatic

	column 'Cancelled only Flag'
		dataType: int64
		formatString: 0
		lineageTag: ae84dc09-0361-4401-b15f-9984383abd96
		summarizeBy: sum
		sourceColumn: Cancelled only Flag

		annotation SummarizationSetBy = Automatic

	column Abort/Cancelled/Completed
		dataType: string
		lineageTag: 9639c6bc-3725-41b3-bd2c-f3606b3c46f1
		summarizeBy: none
		sourceColumn: Abort/Cancelled/Completed

		annotation SummarizationSetBy = Automatic

	column Patient_Practice_Code
		dataType: string
		lineageTag: e2656b10-5c48-47c4-a02d-9dfaad0b9c32
		summarizeBy: none
		sourceColumn: Patient_Practice_Code

		annotation SummarizationSetBy = Automatic

	column Patient_Practice_Description
		dataType: string
		lineageTag: 735744bb-6c47-43f6-ae7b-ba3c549ff587
		summarizeBy: none
		sourceColumn: Patient_Practice_Description

		annotation SummarizationSetBy = Automatic

	column Age_reference
		dataType: string
		lineageTag: 67dfdfb3-ae6c-4e00-b98c-e619a5fb7e80
		summarizeBy: none
		sourceColumn: Age_reference

		annotation SummarizationSetBy = Automatic

	column AgeBand_5yr_not_ordered
		dataType: string
		lineageTag: 42180b26-411a-4896-8301-4ad4ba6b2116
		summarizeBy: none
		sourceColumn: AgeBand_5yr_not_ordered

		annotation SummarizationSetBy = Automatic

	column AgeBand_5yr_ordered
		dataType: string
		lineageTag: a6d21232-8658-459b-9f4d-184290d18a0b
		summarizeBy: none
		sourceColumn: AgeBand_5yr_ordered

		annotation SummarizationSetBy = Automatic

	column AgeBand_10yr
		dataType: string
		lineageTag: 91df86b0-d802-4f18-840e-e4bb53920513
		summarizeBy: none
		sourceColumn: AgeBand_10yr

		annotation SummarizationSetBy = Automatic

	column Living_in_Care_Home
		dataType: string
		lineageTag: 12f3dd7e-eb30-4c95-b6af-17b12622a398
		summarizeBy: none
		sourceColumn: Living_in_Care_Home

		annotation SummarizationSetBy = Automatic

	partition GHT_OntheDay = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Processing", [Query="EXEC [dbo].[SP_PTS_GHT]#(lf);#(lf)#(lf)SELECT *#(lf)FROM [PowerBI_Reporting].[dbo].[PTS_GHT]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Counter", "Counter (GHT)"}, {"Cancel_Reason_Description", "Cancelled (GHT)"}, {"Abort_Reason_Description", "Aborts (GHT)"}, {"Contract_Description", "Contract GHT OTD "}, {"Activity_Month", "Activity_Month_GHT"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","Canceled","Cancelled",Replacer.ReplaceText,{"Cancelled (GHT)"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

