table Main_Journeys
	lineageTag: 41022937-0cae-4bcd-903b-dbdf39436343

	measure 'Main + GHT'
		lineageTag: 5492224e-8b49-4f35-8110-696c0d1b3871

	measure 'All Journeys_Main + GHT' =
			
			SUM('Main_Journeys'[Counter (Main)]) + SUM('GHT_OntheDay'[Counter (GHT)])
		formatString: 0
		lineageTag: 1830b3c5-a162-45da-b789-7bb4b2f2917d

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalAddition"
				}

		changedProperty = FormatString

	measure 'passengerID divided by Counter (Main)' =
			
			DIVIDE(
				COUNTA('Dialysis Distinct Patients'[passengerID]),
				SUM('Main_Journeys'[Counter (Main)])
			)
		formatString: #,0
		lineageTag: a2487087-9c9d-424b-ae11-b63fe3323dcf

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Completed: Counter (Main) minus Aborts or Cancel Flag' =
			
			SUM('Main_Journeys'[Counter (Main)]) - SUM('Main_Journeys'[Aborts or Cancel Flag])
		formatString: #,0
		lineageTag: 13344722-cae2-4492-8b14-783da00abe70

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalSubtraction"
				}

		changedProperty = FormatString

	measure 'Proportion Completed out of Booked (Main)' =
			
			DIVIDE(
				[Completed: Counter (Main) minus Aborts or Cancel Flag],
				SUM('Main_Journeys'[Counter (Main)])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 0eafe2c2-8cf2-4cc5-a4b9-d7a267ea58b0

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'KPI_2a_Achieved percentage' =
			
			DIVIDE(
				SUM('Main_Journeys'[KPI_2a_Achieved_Numerator]),
				SUM('Main_Journeys'[KPI_2a_Denominator])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 17b76c1b-74ec-4ab9-96c8-739181c0b59d

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'KPI_2b_Achieved Percentage' =
			
			DIVIDE(
				SUM('Main_Journeys'[KPI_2b_Achieved_Numerator]),
				SUM('Main_Journeys'[KPI_2b_Denominator])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e949a8ed-576f-47fe-a523-c299bb9c4369

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure KPI_3a_Achieved_Percentage =
			
			DIVIDE(
				SUM('Main_Journeys'[KPI_3a_Achieved_Numerator]),
				SUM('Main_Journeys'[KPI_3a_Denominator])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 46aea29f-f7e7-4dbe-86ef-43e46bebd339

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'KPI_5 Achieved Percentage' =
			
			DIVIDE(
				SUM('Main_Journeys'[KPI_5_Numerator]),
				SUM('Main_Journeys'[Counter (Main)])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ad997d90-756b-40ed-9de7-a81656db4f0b

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Proportion (Main): Aborts out of Booked' =
			
			DIVIDE(
				SUM('Main_Journeys'[Aborts only Flag]),
				SUM('Main_Journeys'[Counter (Main)])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: bb10c138-3af9-4739-828c-2e8ac2a329ee

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Proportion (Main): Cancelled out of Booked Main)' =
			
			DIVIDE(
				SUM('Main_Journeys'[Cancelled only Flag]),
				SUM('Main_Journeys'[Counter (Main)])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1b669016-081b-4172-8361-b822f7923de8

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Complete + Aborts (Main)' =
			
			SUM('Main_Journeys'[Counter (Main)]) - SUM('Main_Journeys'[Cancelled only Flag])
		formatString: #,0
		lineageTag: f8b237b2-6297-441b-a1b2-5c890165055b

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalSubtraction"
				}

		changedProperty = FormatString

	column Activity_Month
		dataType: string
		lineageTag: 856a9abe-718a-4bc3-8f80-fd1ef9e5fdb8
		summarizeBy: none
		sourceColumn: Activity_Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column passengerID
		dataType: int64
		formatString: 0
		lineageTag: 93132f57-46d2-4306-b5ef-63705f919cb1
		summarizeBy: count
		sourceColumn: passengerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Pseudo_NHS_Number
		dataType: string
		lineageTag: 4e16b7f3-e252-4d74-8ba4-260d33c1e195
		summarizeBy: none
		sourceColumn: Pseudo_NHS_Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MPI_Pseudo_NHS_no
		dataType: string
		lineageTag: 390c6307-6d36-4af8-89b2-0c07a0b3b8b0
		summarizeBy: none
		sourceColumn: MPI_Pseudo_NHS_no

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 08db4c13-db95-4c33-8116-501b862c83f3
		summarizeBy: none
		sourceColumn: Start_Date

		variation Variation
			isDefault
			relationship: f2d9e5d5-da7b-4d95-afc5-cf5b483ad699
			defaultHierarchy: LocalDateTable_14ce73bb-b0c1-4ea6-b73f-96db61b0f73e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Contract Main'
		dataType: string
		lineageTag: 3ebf775f-9896-4af5-89a3-1b21ca5b9ff9
		summarizeBy: none
		sourceColumn: Contract Main

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Contract_Hospital_Description
		dataType: string
		lineageTag: 511fbcae-29ef-4989-a332-c184ada6b0ea
		summarizeBy: none
		sourceColumn: Contract_Hospital_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Contract_Clinic_Description
		dataType: string
		lineageTag: 4d6bd57f-3fb4-4f17-9e23-84244a139857
		summarizeBy: none
		sourceColumn: Contract_Clinic_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Requested_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b10dd4b-9f9d-422c-a169-c1149d8156cf
		summarizeBy: none
		sourceColumn: Requested_DateTime

		variation Variation
			isDefault
			relationship: 801e93b4-0f70-446d-a51f-a2c022a80ea5
			defaultHierarchy: LocalDateTable_ef475f3e-e6bb-4a47-a1a3-e1da73064c69.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Requested_Method_Description
		dataType: string
		lineageTag: b63b8e57-a131-42e2-ab97-566c029a2345
		summarizeBy: none
		sourceColumn: Requested_Method_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Transport_Reason_Description
		dataType: string
		lineageTag: 5a5f3075-f84c-407e-96f6-12e5975a6b86
		summarizeBy: none
		sourceColumn: Transport_Reason_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Booking_Source
		dataType: string
		lineageTag: 2dacf096-fa71-4178-9e2f-c418fe00b6e5
		summarizeBy: none
		sourceColumn: Booking_Source

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Direction_Description
		dataType: string
		lineageTag: aae176bc-b04c-4b5f-ad0c-e0a1e3f6c8f6
		summarizeBy: none
		sourceColumn: Direction_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column From_Hospital_Description
		dataType: string
		lineageTag: e89282d4-8f08-4bdc-af8b-9516fe74141f
		summarizeBy: none
		sourceColumn: From_Hospital_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column To_Hospital_Description
		dataType: string
		lineageTag: 486aaffd-26e1-4fde-9e04-b96e3894cf96
		summarizeBy: none
		sourceColumn: To_Hospital_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column From_Clinic_Description
		dataType: string
		lineageTag: d909f6e8-65b7-4bdb-b694-3667c979659d
		summarizeBy: none
		sourceColumn: From_Clinic_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column To_Clinic_Description
		dataType: string
		lineageTag: e4cb87a9-7095-49da-906d-d2ce88114000
		summarizeBy: none
		sourceColumn: To_Clinic_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Category_Description
		dataType: string
		lineageTag: 8c20323f-26b6-4a96-bc7e-807e7ea302c8
		summarizeBy: none
		sourceColumn: Category_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Category_Mapped_Description
		dataType: string
		lineageTag: 85e19c75-19ff-46e6-8a12-224de281ec9c
		summarizeBy: none
		sourceColumn: Category_Mapped_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cat_Mapped_Desc_National
		dataType: string
		lineageTag: 4269f989-f1e4-4b11-9c29-d073aa9c7b47
		summarizeBy: none
		sourceColumn: Cat_Mapped_Desc_National

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Booking_Notice_Days
		dataType: int64
		formatString: 0
		lineageTag: f56d171d-b875-4802-b969-82954c113620
		summarizeBy: sum
		sourceColumn: Booking_Notice_Days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Booking_Notice_Days_Grouped
		dataType: string
		lineageTag: ca2a1a9c-0fa4-42ae-a58f-46c35850218d
		summarizeBy: none
		sourceColumn: Booking_Notice_Days_Grouped

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Requested_on_or_After_Day_of_Transport
		dataType: int64
		formatString: 0
		lineageTag: c4a57beb-8c93-4c22-ba95-0c3df3efad51
		summarizeBy: sum
		sourceColumn: Requested_on_or_After_Day_of_Transport

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Planned_Journey_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 09f4a275-83b4-486e-a8c1-1953bfe2e3cf
		summarizeBy: none
		sourceColumn: Planned_Journey_Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Planned_Time
		dataType: int64
		formatString: 0
		lineageTag: fbeddc2b-66c8-4d47-8c19-b31dc8759379
		summarizeBy: sum
		sourceColumn: Planned_Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Journey_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 5a25d17c-d457-4795-a8d5-9815aa520566
		summarizeBy: none
		sourceColumn: Journey_DateTime

		variation Variation
			isDefault
			relationship: 805f0842-7b88-405e-a5cf-ffd35a2231e6
			defaultHierarchy: LocalDateTable_4c998f50-12f3-45d2-a76e-1ac45a073f94.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Journey_Hour
		dataType: int64
		formatString: 0
		lineageTag: 7327f17a-09d4-46cf-8544-a2c241086f0d
		summarizeBy: sum
		sourceColumn: Journey_Hour

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Journey_Day
		dataType: string
		lineageTag: 4fb3807e-37a8-4b1b-af30-f74c63d4fe19
		summarizeBy: none
		sourceColumn: Journey_Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Ready_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 2b77a013-f7b4-4a3c-a516-26b10f5d1780
		summarizeBy: none
		sourceColumn: Ready_Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Pick_Up_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 6368853d-585f-4ce3-bb74-ee3ed93ce6b3
		summarizeBy: none
		sourceColumn: Pick_Up_DateTime

		variation Variation
			isDefault
			relationship: 109a6926-8271-4af5-9ea1-17ca7e0b0f4d
			defaultHierarchy: LocalDateTable_0f3d21ba-03af-4c98-830c-8b5317e04a77.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Drop_Off_DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 3f3162ff-7c06-47a9-a5ce-bda3dd3b100d
		summarizeBy: none
		sourceColumn: Drop_Off_DateTime

		variation Variation
			isDefault
			relationship: 946556fc-3876-4bf3-8766-f3cdc92ec0dc
			defaultHierarchy: LocalDateTable_c4474072-83d5-4b55-a6de-7a90d3120909.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Time_on_Vehicle_Minutes
		dataType: int64
		formatString: 0
		lineageTag: 492590ea-b90f-42be-ba9e-4c7c28e6e73d
		summarizeBy: sum
		sourceColumn: Time_on_Vehicle_Minutes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Early_Late_Minutes
		dataType: int64
		formatString: 0
		lineageTag: a4c2243d-1a85-4a88-8fce-8472e7b7b85d
		summarizeBy: sum
		sourceColumn: Early_Late_Minutes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column KPI_2a_timebands
		dataType: string
		lineageTag: 3e600699-e251-440b-b3b6-5ecf198faee3
		summarizeBy: none
		sourceColumn: KPI_2a_timebands

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column KPI_2b_timebands
		dataType: string
		lineageTag: e1b7808a-bafe-4153-bb66-d7ce353d92a0
		summarizeBy: none
		sourceColumn: KPI_2b_timebands

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column KPI_3a_timebands
		dataType: string
		lineageTag: ab358b2d-aeb5-45fe-ba9d-21d4e4724443
		summarizeBy: none
		sourceColumn: KPI_3a_timebands

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'KPI_5 Abort/Cancel Avoidance'
		dataType: string
		lineageTag: 2c4f4b97-0aca-46af-b0b5-426d1b84e9b4
		summarizeBy: none
		sourceColumn: KPI_5 Abort/Cancel Avoidance

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Wait_and_Return_Flag
		dataType: int64
		formatString: 0
		lineageTag: 346e09c7-5e47-40d3-92a7-cd2d026b08c3
		summarizeBy: sum
		sourceColumn: Wait_and_Return_Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Waiting_Time_Minutes
		dataType: int64
		formatString: 0
		lineageTag: 00fc7700-cde2-4a28-8b89-c90b55221d65
		summarizeBy: sum
		sourceColumn: Waiting_Time_Minutes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Escort_Seats
		dataType: int64
		formatString: 0
		lineageTag: 962352f0-1865-43af-bcac-54dbc71a92fc
		summarizeBy: sum
		sourceColumn: Escort_Seats

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Medical_Escort_Count
		dataType: int64
		formatString: 0
		lineageTag: adf4f129-79da-4d6f-816f-bbe1eb5aab72
		summarizeBy: sum
		sourceColumn: Medical_Escort_Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Relative_Escort_Count
		dataType: int64
		formatString: 0
		lineageTag: 66f9429a-7de9-4021-a744-f1d0942cd21c
		summarizeBy: sum
		sourceColumn: Relative_Escort_Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Speciality_Description
		dataType: string
		lineageTag: df00b1ce-0dfc-4ab5-8c54-f6db6c042b6f
		summarizeBy: none
		sourceColumn: Speciality_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column total_passengers_carried
		dataType: int64
		formatString: 0
		lineageTag: 42c9d5f6-cf4e-4087-92e8-aaa546b0048a
		summarizeBy: sum
		sourceColumn: total_passengers_carried

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Planned_Mileage
		dataType: double
		formatString: #,0
		lineageTag: 59ce73f4-146d-4ecd-be24-6045c988c8ac
		summarizeBy: sum
		sourceColumn: Planned_Mileage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Actual_Mileage
		dataType: double
		formatString: #,0
		lineageTag: c041d2d4-a1ff-40fd-b011-2f046e19277f
		summarizeBy: sum
		sourceColumn: Actual_Mileage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Mobility_Description
		dataType: string
		lineageTag: 01696f2e-29c5-4c14-8bba-86d62f0fa562
		summarizeBy: none
		sourceColumn: Mobility_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mobility_MainGroup
		dataType: string
		lineageTag: 9515d8b7-b0da-476f-b8cc-9a4dcccc29cd
		summarizeBy: none
		sourceColumn: Mobility_MainGroup

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column National_Mobility_High_Level
		dataType: string
		lineageTag: 62695227-4e08-4866-a772-30f23fb1fc46
		summarizeBy: none
		sourceColumn: National_Mobility_High_Level

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column National_Mobility_Sub_Level
		dataType: string
		lineageTag: 24064a02-910d-45df-a0c9-6254f8a7e757
		summarizeBy: none
		sourceColumn: National_Mobility_Sub_Level

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column National_Mobility_Add_Req
		dataType: string
		lineageTag: 96119464-7d19-48c5-8ecf-3b4db1ac2b45
		summarizeBy: none
		sourceColumn: National_Mobility_Add_Req

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Aborts (Main)'
		dataType: string
		lineageTag: b8702fd2-944c-4446-b812-9107b9045da8
		summarizeBy: none
		sourceColumn: Aborts (Main)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cancelled (Main)'
		dataType: string
		lineageTag: 3b81155e-8c3b-4433-9ce7-b8e6291feef9
		summarizeBy: none
		sourceColumn: Cancelled (Main)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cancelled_on_Day_of_Transport
		dataType: int64
		formatString: 0
		lineageTag: d5a083ae-6677-4f9e-86ab-03a902e6bc82
		summarizeBy: sum
		sourceColumn: Cancelled_on_Day_of_Transport

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Derived_EarlyLate_Minute_Timeband
		dataType: string
		lineageTag: 89ccc5d4-be20-4569-89be-27a80a73eaf4
		summarizeBy: none
		sourceColumn: Derived_EarlyLate_Minute_Timeband

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Derived_Waiting_Time_Minute_Timeband
		dataType: string
		lineageTag: dd35f191-9d48-4719-a6cb-3b60d0a955c7
		summarizeBy: none
		sourceColumn: Derived_Waiting_Time_Minute_Timeband

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Patient_Age_When_Transported
		dataType: string
		lineageTag: 0f4d31bb-1693-4a74-baf5-292ea2761d3f
		summarizeBy: none
		sourceColumn: Patient_Age_When_Transported

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgeBand_National
		dataType: string
		lineageTag: af3bc6a6-ba5e-49fd-a165-b0a1a9682f07
		summarizeBy: none
		sourceColumn: AgeBand_National

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 3a0b6bae-92f5-43da-a2f6-75ffba284f05
		summarizeBy: none
		sourceColumn: Gender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin'
		dataType: string
		lineageTag: e52e1cfe-2c0c-4116-bdcf-0d6b267f8556
		summarizeBy: none
		sourceColumn: Ethnic Origin

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: 5f4d22aa-3499-4fa4-9fcc-5149001cc676
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: c31eb47b-ada5-45e5-8e08-34ac5eec5ef6
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Core20Flag
		dataType: int64
		formatString: 0
		lineageTag: 8698a419-83fc-4b1a-9e1d-caa8332fc87f
		summarizeBy: sum
		sourceColumn: Core20Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: b8637e80-6114-4fb3-b1b2-89055fda3c74
		summarizeBy: none
		sourceColumn: District

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column localityname
		dataType: string
		lineageTag: b4877e6a-34ed-49c5-be27-adf2ce0654b2
		summarizeBy: none
		sourceColumn: localityname

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NetworkName
		dataType: string
		lineageTag: 4b808848-d9f3-4d61-bb4b-f6cf86fe50a5
		summarizeBy: none
		sourceColumn: NetworkName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Easting
		dataType: string
		lineageTag: 89005bfb-5dbf-4a05-9e59-3e777a0b6840
		summarizeBy: none
		sourceColumn: Easting

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Northing
		dataType: string
		lineageTag: c8cd1ed5-e37c-4ac6-828b-bb2e0d50facd
		summarizeBy: none
		sourceColumn: Northing

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RuralUrbanClass
		dataType: string
		lineageTag: e9e2e456-41b7-4f2b-8868-b25f57b02873
		summarizeBy: none
		sourceColumn: RuralUrbanClass

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SegmentHealthLeeds
		dataType: string
		lineageTag: 0221dadf-f87f-4c5d-9d45-378724f314f3
		summarizeBy: none
		sourceColumn: SegmentHealthLeeds

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: double
		lineageTag: d31c5e60-b914-417f-b3a2-85a8c8f273a1
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 1 Income'
		dataType: double
		lineageTag: 6dfbfc74-20c7-4de9-86bc-e60af588f2e8
		summarizeBy: sum
		sourceColumn: IMD 1 Income

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 2 Employment'
		dataType: double
		lineageTag: c00c356c-03de-4e96-932c-455415deace3
		summarizeBy: sum
		sourceColumn: IMD 2 Employment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 3 Education'
		dataType: double
		lineageTag: bcb25d03-55a2-4025-8e24-905b69db4ffe
		summarizeBy: sum
		sourceColumn: IMD 3 Education

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 4 Health'
		dataType: double
		lineageTag: 7f16b332-235b-4447-a14f-e5a5a6b085b1
		summarizeBy: sum
		sourceColumn: IMD 4 Health

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 5 Crime'
		dataType: double
		lineageTag: d7267cc0-fb88-46a4-a3fd-0d99caf454ad
		summarizeBy: sum
		sourceColumn: IMD 5 Crime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 6 Barriers to Housing and Services'
		dataType: double
		lineageTag: 600c46b0-27c9-42c9-aa08-792d5327d015
		summarizeBy: sum
		sourceColumn: IMD 6 Barriers to Housing and Services

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IMD 7 Living Environment'
		dataType: double
		lineageTag: f68c0877-39d7-4e3c-82e4-7f2f84889e7c
		summarizeBy: sum
		sourceColumn: IMD 7 Living Environment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: ceb18500-46ab-4f6c-be2d-2c99d46d302a
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: 6d0da13f-a055-4024-94cf-92dbd96eed1b
			defaultHierarchy: LocalDateTable_353e7633-443b-49ca-8bcd-55827869eedb.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Counter (Main)'
		dataType: int64
		formatString: #,0
		lineageTag: 8aac4d58-fc3d-4d69-9f45-407f43b33d7d
		summarizeBy: sum
		sourceColumn: Counter (Main)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Activity Month_mmmyyyy format' = Main_Journeys[Activity_Month]
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 7b0f62d2-26ee-4a34-9ea9-ca89caa4b26a
		summarizeBy: none

		variation Variation
			isDefault
			relationship: ca801019-525b-40a8-a17b-a0677a33b962
			defaultHierarchy: LocalDateTable_924f5550-452c-48b3-9897-7b83c1042383.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Date_of_Activity
		dataType: dateTime
		formatString: General Date
		lineageTag: ac318714-2d77-4e9a-9ba2-32f9585d5c7d
		summarizeBy: none
		sourceColumn: Date_of_Activity

		variation Variation
			isDefault
			relationship: 6b14d67b-9a43-4582-a5be-6fc12c0b9575
			defaultHierarchy: LocalDateTable_a5778073-b55b-4953-9855-03652cfc3ab9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4bb39d59-8516-42f8-adb1-a79cd5e1ba0c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column FinYear
		dataType: string
		lineageTag: 4ec41732-81f6-478a-a072-db0cf234cc6c
		summarizeBy: none
		sourceColumn: FinYear

		annotation SummarizationSetBy = Automatic

	column Quarter_FinYr
		dataType: string
		lineageTag: 23a55dff-9e1d-42c6-a63a-ce5d21aa5460
		summarizeBy: none
		sourceColumn: Quarter_FinYr

		annotation SummarizationSetBy = Automatic

	column KPI_2a_Achieved_Numerator
		dataType: int64
		formatString: #,0
		lineageTag: 66e816f2-d9ad-44e6-9265-ca5b025419c2
		summarizeBy: sum
		sourceColumn: KPI_2a_Achieved_Numerator

		annotation SummarizationSetBy = Automatic

	column KPI_2a_Denominator
		dataType: int64
		formatString: #,0
		lineageTag: f3ae6b8c-80c9-4b92-93a6-606ea3f7d872
		summarizeBy: sum
		sourceColumn: KPI_2a_Denominator

		annotation SummarizationSetBy = Automatic

	column KPI_2b_Achieved_Numerator
		dataType: int64
		formatString: #,0
		lineageTag: a8efd4ea-cab4-4540-806b-c0295f41928f
		summarizeBy: sum
		sourceColumn: KPI_2b_Achieved_Numerator

		annotation SummarizationSetBy = Automatic

	column KPI_2b_Denominator
		dataType: int64
		formatString: #,0
		lineageTag: 308bfe74-19fd-4256-a204-c147e9089882
		summarizeBy: sum
		sourceColumn: KPI_2b_Denominator

		annotation SummarizationSetBy = Automatic

	column KPI_3a_Achieved_Numerator
		dataType: int64
		formatString: #,0
		lineageTag: 884c41af-347d-4c2b-8166-d1ec3dbf22a6
		summarizeBy: sum
		sourceColumn: KPI_3a_Achieved_Numerator

		annotation SummarizationSetBy = Automatic

	column KPI_3a_Denominator
		dataType: int64
		formatString: #,0
		lineageTag: 0e0a57d1-af8e-4ac1-8ec2-e8c339a7c51e
		summarizeBy: sum
		sourceColumn: KPI_3a_Denominator

		annotation SummarizationSetBy = Automatic

	column KPI_5_Numerator
		dataType: int64
		formatString: #,0
		lineageTag: 66649af2-3f5a-4e45-966e-fccaee945fe9
		summarizeBy: sum
		sourceColumn: KPI_5_Numerator

		annotation SummarizationSetBy = Automatic

	column 'Nye Bevan Practice Code'
		dataType: string
		lineageTag: 0907f8bc-f9b4-45c3-9ac3-03ec657346b1
		summarizeBy: none
		sourceColumn: Nye Bevan Practice Code

		annotation SummarizationSetBy = Automatic

	column 'Nye Bevan Practice Desc'
		dataType: string
		lineageTag: 1beddd2a-8a69-45d7-bd70-af60cdd32b2f
		summarizeBy: none
		sourceColumn: Nye Bevan Practice Desc

		annotation SummarizationSetBy = Automatic

	column 'Nye Bevan Flag'
		dataType: int64
		formatString: 0
		lineageTag: 5ac7f101-caec-46f7-9ee0-5fe996fb05a2
		summarizeBy: sum
		sourceColumn: Nye Bevan Flag

		annotation SummarizationSetBy = Automatic

	column Speciality_Covid_sus_or_conf_journeys
		dataType: int64
		formatString: #,0
		lineageTag: 68d0238b-3405-4b5e-931c-9d0b15910575
		summarizeBy: sum
		sourceColumn: Speciality_Covid_sus_or_conf_journeys

		annotation SummarizationSetBy = Automatic

	column Mileage_Bands
		dataType: string
		lineageTag: 3cab24c6-88e6-4b50-b6b2-7203158df79c
		summarizeBy: none
		sourceColumn: Mileage_Bands

		annotation SummarizationSetBy = Automatic

	column 'Aborts or Cancel Flag'
		dataType: int64
		formatString: #,0
		lineageTag: 3509edeb-4f93-415b-864e-0686206d76c4
		summarizeBy: sum
		sourceColumn: Aborts or Cancel Flag

		annotation SummarizationSetBy = Automatic

	column 'Aborts only Flag'
		dataType: int64
		formatString: #,0
		lineageTag: ebd1c66d-5ce5-4f7e-a526-f229e1ea4df3
		summarizeBy: sum
		sourceColumn: Aborts only Flag

		annotation SummarizationSetBy = Automatic

	column 'Cancelled only Flag'
		dataType: int64
		formatString: #,0
		lineageTag: a662adaa-a98a-43a7-885e-86725bfb92e8
		summarizeBy: sum
		sourceColumn: Cancelled only Flag

		annotation SummarizationSetBy = Automatic

	column Abort/Cancelled/Completed
		dataType: string
		lineageTag: 1dbd6670-db2a-4fae-b56c-2c7b7326eb87
		summarizeBy: none
		sourceColumn: Abort/Cancelled/Completed

		annotation SummarizationSetBy = Automatic

	column 'Journey Cost'
		dataType: double
		lineageTag: fef63f43-7744-4a45-99e0-93e390618104
		summarizeBy: sum
		sourceColumn: Journey Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Patient_Practice_Code
		dataType: string
		lineageTag: 812a4db7-d8e1-40d9-a43f-7baf10b5fba6
		summarizeBy: none
		sourceColumn: Patient_Practice_Code

		annotation SummarizationSetBy = Automatic

	column Patient_Practice_Description
		dataType: string
		lineageTag: e9952fef-b3dd-4f8c-995f-6045bfcf0a14
		summarizeBy: none
		sourceColumn: Patient_Practice_Description

		annotation SummarizationSetBy = Automatic

	column Age_reference
		dataType: string
		lineageTag: d1b872c0-3dcf-49f4-9ea8-40be06434c12
		summarizeBy: none
		sourceColumn: Age_reference

		annotation SummarizationSetBy = Automatic

	column AgeBand_5yr_not_ordered
		dataType: string
		lineageTag: a4ddc6d9-bb5c-4417-bb88-6a4e2c69ad6b
		summarizeBy: none
		sourceColumn: AgeBand_5yr_not_ordered

		annotation SummarizationSetBy = Automatic

	column AgeBand_5yr_ordered
		dataType: string
		lineageTag: f63e50c4-11e2-4e36-b596-8f275615d500
		summarizeBy: none
		sourceColumn: AgeBand_5yr_ordered

		annotation SummarizationSetBy = Automatic

	column AgeBand_10yr
		dataType: string
		lineageTag: 1df4b2b0-5815-4f95-9431-a1523b64a317
		summarizeBy: none
		sourceColumn: AgeBand_10yr

		annotation SummarizationSetBy = Automatic

	column Living_in_Care_Home
		dataType: string
		lineageTag: ee5f9134-7c03-42d6-82f8-966c043da677
		summarizeBy: none
		sourceColumn: Living_in_Care_Home

		annotation SummarizationSetBy = Automatic

	column 'From NBT Hospitals' = IF(Main_Journeys[From_Hospital_Description] = "Southmead Hospital", [From_Hospital_Description], "Other")
		lineageTag: 7ba64078-859f-4be3-93ae-8d38004bea82
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Join Month'
		dataType: string
		lineageTag: 9e792efc-1163-4ce6-8c3c-f9c7d3ecbcd8
		summarizeBy: none
		sourceColumn: Join Month

		annotation SummarizationSetBy = Automatic

	partition Main_Journeys = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Processing", [Query="EXEC [dbo].[SP_PTS_main]#(lf);#(lf)#(lf)SELECT *#(lf)FROM [PowerBI_Reporting].[dbo].[PTS_Main]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Counter", "Counter (Main)"}, {"Cancel_Reason_Description", "Cancelled (Main)"}, {"Abort_Reason_Description", "Aborts (Main)"}, {"Contract_Description", "Contract Main"}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns","Hospital Outpatient","Outpatient",Replacer.ReplaceValue,{"Category_Mapped_Description"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value2",{{"KPI 3a timebands", "KPI_3a_timebands"}, {"KPI 5 Abort/Cancel Avoidance", "KPI_5 Abort/Cancel Avoidance"}, {"KPI_2b_Denominator", "KPI_2b_Denominator"}, {"KPI_3a_Denominator", "KPI_3a_Denominator"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",null,"Non-Covid-19",Replacer.ReplaceValue,{"Speciality_Description"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Replaced Value",{{"Covid_sus_or_conf_journeys", "Speciality_Covid_sus_or_conf_journeys"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns2","Canceled","Cancelled",Replacer.ReplaceText,{"Cancelled (Main)"}),
				    #"Added Custom Column" = Table.AddColumn(#"Replaced Value1", "Custom", each Text.Combine({Date.ToText(Date.From([Activity_Month]), "MMMM"), " ", Date.ToText(Date.From([Activity_Month]), "yyyy")}), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Added Custom Column",{{"Custom", "Join Month"}})
				in
				    #"Renamed Columns3"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

