table Target_upload
	lineageTag: a7ec1ee0-d3d8-4bd7-8e6d-f008e0a7e632

	measure 'Conditional Penalty KPI 2a' = IF(Main_Journeys[KPI_2a_Achieved percentage] > 0.8499, 0, SUM(Target_upload[2a Penalty Monthly £]))
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: eb0725cb-58fe-442a-9087-92c86f2dcc0a

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Conditional Penalty KPI 2b' = IF(Main_Journeys[KPI_2b_Achieved percentage] > 0.8499, 0, SUM(Target_upload[2b Penalty Monthly £]))
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 553c2983-02cd-4651-ab0a-08616a6c3e21

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Conditional Penalty KPI 3a' = IF(Main_Journeys[KPI_3a_Achieved_Percentage] > 0.8999, 0, SUM(Target_upload[3a  Penalty Monthly £]))
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 16efd494-c820-448c-acbd-99313df79a1b

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column Month
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 11d1a6e0-86b1-40d2-9113-b9f116aa46fe
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: eafe3c09-4771-4095-8295-af07e0eb22b0
			defaultHierarchy: LocalDateTable_f1345458-2085-4a02-97a3-cbada5f41f62.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Fin_Year
		dataType: string
		lineageTag: 05a5c15a-75e7-48de-8ffc-d1fc77d0364f
		summarizeBy: none
		sourceColumn: Fin_Year

		annotation SummarizationSetBy = Automatic

	column 'Total Annual Contract Value'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 7775bce2-0a0b-420d-bb4d-bd1b6d40b8aa
		summarizeBy: sum
		sourceColumn: Total Annual Contract Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Monthly Contract Value'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: cbb243f4-5ca9-4314-91db-ec20f60426d0
		summarizeBy: sum
		sourceColumn: Monthly Contract Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Target KPI 2a'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b3374b9e-f8e0-4703-bbe3-730628604487
		summarizeBy: sum
		sourceColumn: Target KPI 2a

		annotation SummarizationSetBy = Automatic

	column '2a Penalty - Monthly %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7387b1ee-e7dc-4f8a-9ee5-309c392f9bc9
		summarizeBy: sum
		sourceColumn: 2a Penalty - Monthly %

		annotation SummarizationSetBy = Automatic

	column '2a Penalty Monthly £'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 3f545065-ba1d-41fb-b3ae-568b2467c7bc
		summarizeBy: sum
		sourceColumn: 2a Penalty Monthly £

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Target KPI 2b'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 034e0eb1-a8b1-47dc-82f5-dcf9dac2355e
		summarizeBy: sum
		sourceColumn: Target KPI 2b

		annotation SummarizationSetBy = Automatic

	column '2b Penalty - Monthly %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4db2a284-f9ca-44e4-bd8f-0f1579a26e33
		summarizeBy: sum
		sourceColumn: 2b Penalty - Monthly %

		annotation SummarizationSetBy = Automatic

	column '2b Penalty Monthly £'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: cc2e24c7-caef-4d54-ab19-ebab2dd21642
		summarizeBy: sum
		sourceColumn: 2b Penalty Monthly £

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Target KPI  3a'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4216d188-21e6-4fbe-908f-c16023c98c4e
		summarizeBy: sum
		sourceColumn: Target KPI  3a

		annotation SummarizationSetBy = Automatic

	column '3a Penalty - Monthly %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f2e92941-f25e-49a9-9666-9f90e0db6eb8
		summarizeBy: sum
		sourceColumn: 3a Penalty - Monthly %

		annotation SummarizationSetBy = Automatic

	column '3a  Penalty Monthly £'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: e590e0f1-25fb-4150-a11d-743aef3cb97e
		summarizeBy: sum
		sourceColumn: 3a  Penalty Monthly £

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Target KPI 5'
		dataType: int64
		formatString: 0%;-0%;0%
		lineageTag: 0fd73c31-82b1-4061-b624-8c10e5b72329
		summarizeBy: sum
		sourceColumn: Target KPI 5

		annotation SummarizationSetBy = Automatic

	column '5 Penalty - Monthly %'
		dataType: int64
		formatString: 0%;-0%;0%
		lineageTag: 84d0708b-4d1c-4cdc-9bea-341dfba22fba
		summarizeBy: sum
		sourceColumn: 5 Penalty - Monthly %

		annotation SummarizationSetBy = Automatic

	column '5 Penalty Monthly £'
		dataType: int64
		formatString: "£"#,0;-"£"#,0;"£"#,0
		lineageTag: 906817d6-d9f9-4158-85bb-fbfe05834fd4
		summarizeBy: sum
		sourceColumn: 5 Penalty Monthly £

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Join Month'
		dataType: string
		lineageTag: 5bfe09d1-7c72-4c0d-bee3-534af7875b6f
		summarizeBy: none
		sourceColumn: Join Month

		annotation SummarizationSetBy = Automatic

	column 'Conditional Penalty KPI 2a column' =
			IF(([KPI_2a_Achieved percentage]
			) > 0.849999, 0, Target_upload[2a Penalty Monthly £])
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: c40f1feb-49e2-4dd7-a055-64f81433897a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Conditional Penalty KPI 2b column' =
			IF(([KPI_2b_Achieved Percentage]
			) > 0.849999, 0, Target_upload[2b Penalty Monthly £])
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: c14150b2-0355-4327-aaf6-de1b3e9b9b7c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Conditional Penalty KPI 3a column' =
			IF(([KPI_3a_Achieved_Percentage]
			) > 0.899999, 0, Target_upload[3a  Penalty Monthly £])
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 91b93056-3d81-49a9-8469-d0bade07ba61
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	partition Target_upload = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\PERF\PTS\Dashboard_development\Power BI dashboard_ FINAL\Scripts_AND_Upload to PBI files\08. KPI_targets_penalties_for upload.xlsx"), null, true),
				    Target_upload_Sheet = Source{[Item="Target_upload",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Target_upload_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month", type date}, {"Fin_Year", type text}, {"Total Contract Value 2023/24", type number}, {"Monthly Contract Value 2023/24", type number}, {"Target KPI 2a", type number}, {"2a Penalty - Monthly #(lf)%", type number}, {"2a Penalty Monthly #(lf)£", type number}, {"Target KPI 2b", type number}, {"2b Penalty - Monthly #(lf)%", type number}, {"2b Penalty Monthly #(lf)£", type number}, {"Target KPI  3a", type number}, {"3a Penalty - Monthly %", type number}, {"3a  Penalty Monthly #(lf)£", type number}, {"Target KPI 5", Int64.Type}, {"5 Penalty - Monthly #(lf)%", Int64.Type}, {"5 Penalty Monthly £", Int64.Type}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type",10),
				    #"Removed Bottom Rows1" = Table.RemoveLastN(#"Removed Bottom Rows",2),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Bottom Rows1",{{"Total Contract Value 2023/24", "Total Annual Contract Value"}, {"Monthly Contract Value 2023/24", "Monthly Contract Value"}}),
				    #"Added Custom Column" = Table.AddColumn(#"Renamed Columns", "Custom", each Text.Combine({Date.ToText([Month], "MMMM"), " ", Date.ToText([Month], "yyyy")}), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom Column",{{"Custom", "Join Month"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

