table 'Admissions Falls'
	lineageTag: acb7f50a-86d6-447e-9a94-67d48d4aea43

	measure '% Admitted' =
			CALCULATE(SUM('ED Falls'[admitted_flag])
			/
			SUM('ED Falls'[counter_ED_falls])*100)
		lineageTag: 89489461-fb58-4a5b-bfd1-5735591de09a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Locality Rate Per 1000 Falls Admissions' = (sum('Admissions Falls'[Number of Admissions])/sum('Place Population'[Population]))*1000
		lineageTag: de939e67-7438-4036-b01b-b68110a8babb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure count_of_pop_PCN = count('Place Population'[Primary Care Network])
		formatString: 0
		lineageTag: 950fa3db-f9da-412b-9fd2-416af17be761

	measure count_of_ED_PCN = count('ED Falls'[primary_care_network])
		formatString: 0
		lineageTag: a2da525d-e1ca-4211-9afd-ee8642c629aa

	measure ed_PCN_rate_per_1000 = ('Admissions Falls'[count_of_ED_PCN]/'Admissions Falls'[count_of_pop_PCN]) * 1000
		lineageTag: 7314adef-40cf-4471-8899-373c2c60617f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '2021/22 ED Admissions' = CALCULATE(sum('Admissions Falls'[Number of Admissions]),DATESBETWEEN('Date Table'[Date],date(2021,4,1),date(2022,3,31)))
		formatString: 0
		lineageTag: 36c76f91-593d-43d1-bed6-02e475cd6cc6

	measure 'Comparison YTD 2021/22 ED Admissions' = CALCULATE(sum('Admissions Falls'[Number of Admissions]),DATESBETWEEN('Date Table'[Date],date(2021,4,1),date(2021,9,30)))
		formatString: 0
		lineageTag: b4e18ade-075a-4535-a705-8233205255c1

	measure '2022/23 ED Admissions' = CALCULATE(sum('Admissions Falls'[Number of Admissions]),DATESBETWEEN('Date Table'[Date],date(2022,4,1),date(2023,3,31)))
		formatString: 0
		lineageTag: 5ea82a9e-648d-4e25-854b-95cb91b5ec02

	measure 'Dementia rate per 1000' = sum('Admissions Falls'[Number of Admissions])/sum('Dementia population'[COUNTER])*1000
		lineageTag: 9562dba0-9f62-41b5-b079-72e83a98fa9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frailty rate per 1000' = sum('Admissions Falls'[Number of Admissions])/sum('Frail population'[COUNTER])*1000
		lineageTag: 47d3649f-edc6-4ceb-9ac9-452a942e23b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Living alone rate per 1000' = sum('Admissions Falls'[Number of Admissions])/sum('Living Alone Population'[COUNTER])*1000
		lineageTag: 7141a348-aa1f-47f0-b5ac-ab6831e63358

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Care home rate per 1000' = sum('Admissions Falls'[Number of Admissions])/sum('Care home population'[COUNTER])*1000
		lineageTag: 2432e685-b1ce-49a5-be4b-35c6fbb80979

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Died in hospital %' = sum('Admissions Falls'[Died in hospital flag])/sum('Admissions Falls'[Number of Admissions])*100
		lineageTag: 0729ef87-4412-4db3-b1c9-def79c5bf4b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cheltenham Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Cheltenham")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cheltenham"))*1000
		lineageTag: d68a795a-aa69-406e-a8c4-308732e9ce8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotswolds Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Cotswolds")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cotswolds"))*1000
		lineageTag: fae03319-085d-42ee-94ee-e4fbe262ed21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gloucester Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Gloucester City")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Gloucester City"))*1000
		lineageTag: 847cc75c-a714-42c6-b094-1cd27803e1e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'S&BV Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Stroud and Berkeley Vale")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Stroud and Berkeley Vale"))*1000
		lineageTag: 7dd4bb8c-9d31-4bcf-a8e0-390950f347f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FOD Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="The Forest of Dean")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="The Forest of Dean"))*1000
		lineageTag: f5767bbc-2d6d-4207-bd34-54b0356b681f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TWNS Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Tewkesbury Newent and Staunton")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Tewkesbury Newent and Staunton"))*1000
		lineageTag: b316a802-a0f2-4c17-94fb-f7255187c6ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fit Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Fit")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Fit"))*1000
		lineageTag: 070e18a6-02d0-4235-b6be-b4ca883b5cb5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mild Frailty Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Mild Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Mild Frailty"))*1000
		lineageTag: 3930b93d-886d-418b-bcbe-bc09d49a9b31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Moderate Frailty Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Moderate Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Moderate Frailty"))*1000
		lineageTag: 2821cd3b-8e7d-47f3-980a-73680bea48d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unknown Frailty Rate Per 1000 Falls Admission' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Unknown")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Unknown"))*1000
		lineageTag: 4b13edd7-c15a-4855-8f06-05678ea12e8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Is Living Alone Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[living_alone_status]="Living Alone")
			/CALCULATE(sum('Living Alone Population'[COUNTER]),'Living Alone Population'[Living Alone Status]="Living Alone"))*1000
		lineageTag: 5d06bed8-2c27-407c-b464-d3ae52cf4f7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Not Living Alone Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[living_alone_status]="Not Living Alone")
			/CALCULATE(sum('Living Alone Population'[COUNTER]),'Living Alone Population'[Living Alone Status]="Not Living Alone"))*1000
		lineageTag: 638eb46d-bb37-47a0-861b-9b1c0238b0d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LD Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Learning Disability Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Learning Disability Home"))*1000
		lineageTag: 01865da5-c1fc-4a7d-80ba-e69513fe2ffa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Non-Care Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Not Living in a Care Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Not Living in a Care Home"))*1000
		lineageTag: 1e06c83f-dbfd-4dee-9ee0-148662c4b06e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nursing Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Nursing Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Nursing Home"))*1000
		lineageTag: 5bf350e8-3ffa-400e-b419-c215d9127d04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Residential Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Residential Care Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Residential Care Home"))*1000
		lineageTag: 3833c409-fa85-4251-87d3-d27730df77f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unknown Care Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Unknown Care Home Type")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Unknown Care Home Type"))*1000
		lineageTag: df37d53a-3ce3-4370-a10f-9922889ef923

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Severe Frailty Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Severe Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Severe Frailty"))*1000
		lineageTag: c81970c8-eb92-4e59-92a2-f9876a1a56ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Has Dementia Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[dementia_status]="Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="Dementia"))*1000
		lineageTag: 663a814c-8a44-4fec-a06f-a0b5f67f83c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Dementia Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[dementia_status]="No Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="No Dementia"))*1000
		lineageTag: 89e9472b-0205-44a0-a046-99e9c84ac95f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 10_year_age_band
		dataType: string
		lineageTag: 78bb55f7-eaf3-41cf-aec0-b270d5d6d05b
		summarizeBy: none
		sourceColumn: 10_year_age_band

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 15aec3b0-421a-4158-82ea-85d7f0b407ba
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column hospital_provider_spell_number
		dataType: string
		lineageTag: a69ea1e8-a43d-4a3e-b201-ccfd5a37561f
		summarizeBy: none
		sourceColumn: hospital_provider_spell_number

		annotation SummarizationSetBy = Automatic

	column nhs_number
		dataType: string
		lineageTag: f738268f-e825-4bfe-8136-63ab8e5df91f
		summarizeBy: none
		sourceColumn: nhs_number

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: 2efde196-d8ef-4cd8-9c27-be2a42325f3b
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column site
		dataType: string
		lineageTag: dc774dd6-c224-401b-bb1e-c2564a9f54fd
		summarizeBy: none
		sourceColumn: site

		annotation SummarizationSetBy = Automatic

	column discharge_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 72db6a49-7138-4ed5-a813-8ef515e282fc
		summarizeBy: none
		sourceColumn: discharge_date

		annotation SummarizationSetBy = Automatic

	column discharge_date_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b9aa7c6-43a9-4bc0-8dd1-1b9efba29151
		summarizeBy: none
		sourceColumn: discharge_date_time

		variation Variation
			isDefault
			relationship: a7dbcfd0-b840-493c-8e49-aabc4a2ce7b7
			defaultHierarchy: LocalDateTable_dda466a7-b861-4f3c-8428-d554ab3c0fd1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 34f83085-7524-4365-889b-da7bfb503ca6
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 934ce9f2-497a-4f85-b017-4efb52a2b342
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: f373f2d7-8489-4237-8545-002393f2df66
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band
		dataType: string
		lineageTag: 072bca16-164e-414c-b51b-3dfba48846ca
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: bc447328-98c4-4b71-9201-58d960de4662
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column practice_name
		dataType: string
		lineageTag: ec93b7cd-b7db-423c-9dca-d06bddd5a464
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

	column primary_care_network
		dataType: string
		lineageTag: 6b315a21-ecb1-4f8e-8dea-5cd65910afe4
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: 7f6317dd-c09e-40f9-8f8d-1f047cb86f2b
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column hrg_code
		dataType: string
		lineageTag: 4ddafa9e-c9a5-430b-8688-53eee1d744dd
		summarizeBy: none
		sourceColumn: hrg_code

		annotation SummarizationSetBy = Automatic

	column hrg_description
		dataType: string
		lineageTag: e64b4ef2-8e74-46b1-a532-34e1bb850e1e
		summarizeBy: none
		sourceColumn: hrg_description

		annotation SummarizationSetBy = Automatic

	column length_of_stay
		dataType: int64
		formatString: 0
		lineageTag: b666dabb-9d65-48dc-bd9b-b4755de7cf06
		summarizeBy: sum
		sourceColumn: length_of_stay

		annotation SummarizationSetBy = Automatic

	column 'Number of Admissions'
		dataType: int64
		formatString: 0
		lineageTag: 0676af4e-09bc-4bd8-a6dc-9c409dab17f2
		summarizeBy: sum
		sourceColumn: Number of Admissions

		annotation SummarizationSetBy = Automatic

	column current_total_plus_mff
		dataType: double
		lineageTag: 903074a4-997b-42ad-9161-cc168081010e
		summarizeBy: sum
		sourceColumn: current_total_plus_mff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column primary_diagnosis_code
		dataType: string
		lineageTag: 08ec44d8-f260-4fe7-9d2c-57dea40c696a
		summarizeBy: none
		sourceColumn: primary_diagnosis_code

		annotation SummarizationSetBy = Automatic

	column icd_10_description
		dataType: string
		lineageTag: 97a089b9-b1c4-4324-be4d-adcfb7909f76
		summarizeBy: none
		sourceColumn: icd_10_description

		annotation SummarizationSetBy = Automatic

	column primary_procedure_code
		dataType: string
		lineageTag: 35bc077d-70ef-40e1-b78c-15fb220dc60a
		summarizeBy: none
		sourceColumn: primary_procedure_code

		annotation SummarizationSetBy = Automatic

	column primary_procedure_description
		dataType: string
		lineageTag: 5054280e-4796-4e0f-812c-865320e1ca06
		summarizeBy: none
		sourceColumn: primary_procedure_description

		annotation SummarizationSetBy = Automatic

	column emergency_admission_fnof_flag
		dataType: int64
		formatString: 0
		lineageTag: 56623ed3-11bd-4372-811c-d1c374ef2098
		summarizeBy: sum
		sourceColumn: emergency_admission_fnof_flag

		annotation SummarizationSetBy = Automatic

	column dementia_status
		dataType: string
		lineageTag: 8fc1cf8b-61dc-4dfe-a2aa-e27231b39655
		summarizeBy: none
		sourceColumn: dementia_status

		annotation SummarizationSetBy = Automatic

	column living_alone_status
		dataType: string
		lineageTag: 59f93984-f115-4853-bd0e-b323ad3f4e32
		summarizeBy: none
		sourceColumn: living_alone_status

		annotation SummarizationSetBy = Automatic

	column frailty_score
		dataType: double
		lineageTag: 0ff0aaa7-3339-4d74-8d7c-63d2d5a1093d
		summarizeBy: sum
		sourceColumn: frailty_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column frailty_category
		dataType: string
		lineageTag: 7bbd52f6-5e1c-4ec0-9e39-b0876d34abf8
		summarizeBy: none
		sourceColumn: frailty_category

		annotation SummarizationSetBy = Automatic

	column 0-1_days_los
		dataType: int64
		formatString: 0
		lineageTag: e2d81486-caa4-4440-bab6-7c50aaaa39e3
		summarizeBy: sum
		sourceColumn: 0-1_days_los

		annotation SummarizationSetBy = Automatic

	column 2+_days_los
		dataType: int64
		formatString: 0
		lineageTag: 8ad67778-808a-44ad-9712-8b5c74a13893
		summarizeBy: sum
		sourceColumn: 2+_days_los

		annotation SummarizationSetBy = Automatic

	column DischargeDestination_HospitalProviderSpell
		dataType: string
		lineageTag: 99da2c25-739a-4a28-81bc-1e5222e508ce
		summarizeBy: none
		sourceColumn: DischargeDestination_HospitalProviderSpell

		annotation SummarizationSetBy = Automatic

	column DischargeDestination_HospitalProviderSpell_Description
		dataType: string
		lineageTag: 48f7b85e-8ae3-4b82-ba0c-266325033b39
		summarizeBy: none
		sourceColumn: DischargeDestination_HospitalProviderSpell_Description

		annotation SummarizationSetBy = Automatic

	column 'Patient Discharged or Died'
		dataType: string
		lineageTag: 80c670a2-82c5-4d89-b6aa-9ae358fb4a16
		summarizeBy: none
		sourceColumn: Patient Discharged or Died

		annotation SummarizationSetBy = Automatic

	column 'Died in hospital flag'
		dataType: int64
		formatString: 0
		lineageTag: 5139da46-6fa1-428c-be40-48f60994f52f
		summarizeBy: sum
		sourceColumn: Died in hospital flag

		annotation SummarizationSetBy = Automatic

	column correct_practice_code
		dataType: string
		lineageTag: cf6e6b2d-5305-410e-8911-5fc618dbfaca
		summarizeBy: none
		sourceColumn: correct_practice_code

		annotation SummarizationSetBy = Automatic

	column GPPractice_Derived_Name
		dataType: string
		lineageTag: a2c88429-263d-4f45-a435-c419a952254d
		summarizeBy: none
		sourceColumn: GPPractice_Derived_Name

		annotation SummarizationSetBy = Automatic

	column 'Care Home Type'
		dataType: string
		lineageTag: 3955516f-23a4-4255-89e2-862ff28c1454
		summarizeBy: none
		sourceColumn: Care Home Type

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingInCareHome
		dataType: int64
		formatString: 0
		lineageTag: 0539e4fc-2f0f-4eca-93a1-ad1cefc29bf5
		summarizeBy: sum
		sourceColumn: Derived_IsLivingInCareHome

		annotation SummarizationSetBy = Automatic

	column Care_home_status
		dataType: string
		lineageTag: 6f64e751-dd35-48b7-be1d-7147acba9ade
		summarizeBy: none
		sourceColumn: Care_home_status

		annotation SummarizationSetBy = Automatic

	column deceased_nhs_number
		dataType: string
		lineageTag: 9aee5d82-1948-4673-a0f7-90f120038c3c
		summarizeBy: none
		sourceColumn: deceased_nhs_number

		annotation SummarizationSetBy = Automatic

	column mortality_flag
		dataType: string
		lineageTag: 0b2fab6d-9a0d-43fd-a128-d7b257ce663c
		summarizeBy: none
		sourceColumn: mortality_flag

		annotation SummarizationSetBy = Automatic

	column date_of_death
		dataType: dateTime
		formatString: General Date
		lineageTag: 95ebf5ed-b064-46be-a534-3801e6a7943d
		summarizeBy: none
		sourceColumn: date_of_death

		variation Variation
			isDefault
			relationship: 43dd2085-f49b-4c61-ad1f-66e81c572fb6
			defaultHierarchy: LocalDateTable_4aef56c9-1456-4fa4-953c-5f1e5d3d6a2f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column death_in_weeks
		dataType: int64
		formatString: 0
		lineageTag: 7403a068-a636-4e57-b274-419181d50402
		summarizeBy: sum
		sourceColumn: death_in_weeks

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: fe2b1aeb-7bf6-4eaa-b293-f9b9f39a00a7
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Grouped_Discharge_Destination
		dataType: string
		lineageTag: f88b6e17-614e-4c34-bad2-625187cbffb2
		summarizeBy: none
		sourceColumn: Grouped_Discharge_Destination

		annotation SummarizationSetBy = Automatic

	column DischargeMethod_HospitalProviderSpell_Description
		dataType: string
		lineageTag: 871d4c56-3328-4db3-894a-35d9e5b22ef8
		summarizeBy: none
		sourceColumn: DischargeMethod_HospitalProviderSpell_Description

		annotation SummarizationSetBy = Automatic

	column DischargeDestination_HospitalProviderSpell2
		dataType: string
		lineageTag: 1f24b550-e56f-441d-8eff-e09b7858221f
		summarizeBy: none
		sourceColumn: DischargeDestination_HospitalProviderSpell2

		annotation SummarizationSetBy = Automatic

	hierarchy 'icd_10_description Hierarchy'
		lineageTag: 9e44340a-1f51-4678-bf6c-f07a1b4f6843

		level 'Admission Description (ICD10 Code)'
			lineageTag: 20dd6d55-caf2-4d3d-aaef-59c5916bd18f
			column: icd_10_description

		level hrg_description
			lineageTag: fa15acf7-f01f-436a-bca3-17d22fb6d06e
			column: hrg_description

	hierarchy 'locality Hierarchy'
		lineageTag: afbca03c-f875-4019-9793-739a86d398b0

		level Locality
			lineageTag: e96b80bc-c10d-4008-9458-532ef6fae63c
			column: locality

		level primary_care_network
			lineageTag: f11ef746-5811-41e3-8065-36eb380c0efc
			column: primary_care_network

	partition 'Admissions Falls-3f1d6f62-d376-41f4-b0c9-33296dc7f7ad' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_current", [Query="--==--==--==--==--==--==--==--==--==--==--==--==--==--==#(lf)-- GHFT ED Attendances for Falls -- #(lf)--==--==--==--==--==--==--==--==--==--==--==--==--==--==#(lf)--Created by: Kyran Witney#(lf)--Created on: #(lf)--Updated by: Alex Davey#(lf)--Updated on: 28/02/2023#(lf)#(lf)SET ANSI_WARNINGS OFF#(lf)SET NOCOUNT ON#(lf)if object_id ('tempdb..#Temp_Dementia') is not null drop table #Temp_Dementia#(lf)#(lf)--- DEMENTIA TEMP#(lf)#(lf)SELECT DISTINCT [PseudoNHSNo],#(lf)[Dementia]#(lf)INTO #Temp_Dementia#(lf)FROM [CCG_Current].[PrimaryCare].[vw_LongTermConditionsQOFPatients]#(lf)WHERE [Dementia] = '1'#(lf)#(lf)#(lf)--Care home temp table, pulling in care home name and type#(lf)#(lf)SET ANSI_WARNINGS OFF#(lf)SET NOCOUNT ON#(lf)if object_id ('tempdb..#Care_Home') is not null drop table #Care_Home#(lf)#(lf)SELECT DISTINCT#(lf) #(lf)#(tab)Derived_Pseudo_NHSNumber#(lf)      ,[Residential_or_Nursing_home_Location_Name]#(lf)#(tab)  ,[Nursing Care Homes ]#(lf)#(tab)  ,[Care Home Type]#(lf)#(tab)  ,[Date_of_incident] = cast([Time_Of_Incident] as date)#(lf)#(lf)#(tab)  INTO #Care_Home#(lf)#(lf)  FROM [CCG_Current].[SWASFT].[vw_AmbulanceServicePatient] [A]#(lf)#(lf)  LEFT JOIN [BIReports].[dbo].[CHLookup2022_Oct] [CH] ON [CH].[SWASFT Care Home Name] = [A].[Residential_or_Nursing_home_Location_Name]#(lf)   #(lf)  where #(lf)  #(lf)   [Residential_or_Nursing_home_Location] not like 'null'#(lf)#(lf)  and Derived_Pseudo_NHSNumber not like 'Null'#(lf)#(lf)  and [Care Home Type] not like 'NULL'#(lf)#(lf)#(lf)---- MAIN SCRIPT#(lf)#(lf)SELECT   distinct#(lf)          'Hospital Admission' [type]#(lf)#(tab)#(tab)  #(lf)#(tab)#(tab),[Grouped_Discharge_Destination] = case when DischargeDestination_HospitalProviderSpell like '19' then 'Usual Place of Residence'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '29' then 'Temporary Place of Residence'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '30' then 'Psychiatric Accomodation'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '37' then 'Court/Prison/Police Station'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '38' then 'Court/Prison/Police Station'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '48' then 'Psychiatric Accomodation'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '49' then 'Psychiatric Accomodation'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '50' then 'Psychiatric Accomodation'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '51' then 'Other Hospital Provider'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '52' then 'Other Hospital Provider'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '53' then 'Other Hospital Provider'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '54' then 'Care Home'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '65' then 'Local Authority Care'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '66' then 'Local Authority Care'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '79' then 'Patient Died'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '84' then 'Psychiatric Accomodation'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '85' then 'Care Home'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '87' then 'Non-NHS Hospital'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DischargeDestination_HospitalProviderSpell like '88' then 'Hospice'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)else 'Not Coded'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(lf)#(tab)#(tab),DischargeDestination_HospitalProviderSpell#(lf)#(tab)#(tab),DischargeMethod_HospitalProviderSpell_Description#(lf)#(lf)          ,[hospital_provider_spell_number] = [HospitalProviderSpellNumber]#(lf)          ,[HPS].[Derived_Pseudo_NHS] [nhs_number]#(lf)#(tab)#(tab)  #(lf)#(tab)#(tab)  ,Sex = case when [sex] like '1' then 'Male' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)when [Sex] like '2' then 'Female'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)end#(lf)          ,[OrganisationCode_CodeOfProvider] [provider_code]#(lf)#(tab)#(tab)  ,CASE WHEN [SiteCode_ofTreatmentAtEpisodeStartDate] = 'RTE01' THEN 'Cheltenham General Hospital'#(lf)                WHEN [SiteCode_ofTreatmentAtEpisodeStartDate] = 'RTE03' THEN 'Gloucester Royal Hospital'#(lf)#(tab)#(tab)#(tab)#(tab)else 'Out of County Hospital'#(lf)                END AS [site]#(lf)          ,CAST(DischargeDate_FromHospitalProviderSpell AS DATE) [discharge_date]#(lf)#(tab)#(tab)  --,[DP].[Date_Of_Death] [date_of_death]#(lf)#(tab)#(tab)  ,[DischargeDestination_HospitalProviderSpell]#(lf)#(tab)#(tab)  ,[DischargeDate_FromHospitalProviderSpell] [discharge_date_time]#(lf)#(tab)#(tab)  ,DischargeDestination_HospitalProviderSpell_Description#(lf)#(tab)#(tab)  ,case when DischargeDestination_HospitalProviderSpell like '79' then 'Died in Hospital'#(lf)#(tab)#(tab)  else 'Discharged'#(lf)#(tab)#(tab)  end as 'Patient Discharged or Died'#(lf)#(tab)#(tab)  ,case when DischargeDestination_HospitalProviderSpell like '79' then '1'#(lf)#(tab)#(tab)  else '0'#(lf)#(tab)#(tab)  end as 'Died in hospital flag'#(lf)          ,[D].[YearMonth] [year_month]#(lf)          ,LEFT([D].[MonthName],3) [month_name]#(lf)          ,[D].[FinancialYear] [financial_year]#(lf)          ,[A].[5yr_age_band] [5yr_age_band]#(lf)          ,[gppractice_derived] [practice_code]#(lf)#(lf)#(tab)#(tab)  ,[correct_practice_code] = case when [gppractice_derived]  like 'L84001' then 'L84050'#(lf)#(tab)#(tab)when [gppractice_derived]  like 'L84002' then 'L84606'#(lf)#(tab)#(tab)when [gppractice_derived]  like 'L84020' then 'L84012'#(lf)#(tab)#(tab)when [gppractice_derived]  like 'L84044' then 'L84027'#(lf)#(tab)#(tab)when [gppractice_derived]  like 'L84056' then 'L84033'#(lf)#(tab)#(tab)when [gppractice_derived]  like 'L84032' then 'L84077'#(lf)#(tab)#(tab)else [gppractice_derived]#(lf)#(tab)#(tab)end#(lf)#(lf)#(lf)#(lf)#(tab)#(tab)  ,GPPractice_Derived_Name#(lf)          ,[GP].OrganisationName [practice_name]#(lf)          ,[GP].primarycarenetwork [primary_care_network]#(lf)          ,CASE WHEN [GP].[Locality] LIKE '%Cotswold%' THEN 'Cotswolds' ELSE [GP].[Locality] END AS [locality]#(lf)          ,[SpellCOREHRG] [hrg_code]#(lf)          ,[SpellCOREHRG_Description] [hrg_description]#(lf)          ,[length_of_stay] = cast([Derived_SEM_SpellLOS] AS INT)#(lf)#(lf)          ,1 [counter]#(lf)          ,[Derived_Current_TotalPlusMFF] [current_total_plus_mff]#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)  ,[Derived_SEM_SpellPDiag] [primary_diagnosis_code]   #(lf)#(tab)#(tab)  ,[ICD].[ICD10Description] [icd_10_description]#(lf)#(tab)#(tab)  ,[PrimaryProcedure_OPCS] [primary_procedure_code]#(lf)#(tab)#(tab)  ,[PrimaryProcedure_OPCS_Description] [primary_procedure_description] #(lf)#(tab)      ,CASE WHEN [ICD10Code] = 'S720' THEN 1 ELSE 0 END AS [emergency_admission_fnof_flag]#(lf) ,case when [DM].[Dementia] like '1' then 'Dementia'#(lf)#(tab)#(tab)when [DM].[Dementia] like 'null' then 'No Dementia'#(lf)#(tab)#(tab)when [DM].[Dementia] like '0' then 'No dementia'#(lf)#(tab)#(tab)else 'No dementia'#(lf)#(tab)#(tab)end as 'dementia_status'#(lf)#(tab)#(tab)#(lf)#(tab)   #(tab),case  #(lf)#(tab)#(tab)when [mpi].Derived_IsLivingInCareHome like '1' then 'Not Living Alone'#(lf)#(tab)#(tab)when [Care Home Type] not like 'null' then 'Not Living Alone'#(lf)#(tab)#(tab)when [mpi].[Derived_IsLivingAlone] like '0' then 'Not Living Alone'#(lf)#(tab)#(tab)when [mpi].[Derived_IsLivingAlone] is null  then 'Not Living Alone'#(lf)#(lf)#(tab)#(tab)else 'Living Alone'#(lf)#(tab)#(tab)end as 'living_alone_status'#(lf)#(lf)#(tab)#(tab)#(lf)#(lf)#(lf)#(lf)       #(tab),[CH].[Care Home Type]#(lf)#(tab)#(tab),[MPI].Derived_IsLivingInCareHome#(lf)#(lf)#(tab)#(tab),[Care_home_status] = case when [mpi].Derived_IsLivingInCareHome like '1' and [CH].[Care Home Type] IS NULL then 'Unknown Care Home Type'#(lf)#(tab)#(tab)when ([CH].[Care Home Type] not like 'NULL') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type] not like 'null') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome like '0' and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(lf)#(tab)#(tab)end#(lf)#(tab)#(lf)#(tab)#(tab)  ,[DP].[Derived_NHS_Number] [deceased_nhs_number]#(lf)#(tab)#(tab)  ,CASE WHEN [HPS].[Derived_Pseudo_NHS] = [DP].[Derived_NHS_Number] THEN 'Deceased'#(lf)#(tab)#(tab)        ELSE 'Alive' END AS [mortality_flag]#(lf)#(tab)#(tab)  ,[DP].[DateOfDeath] [date_of_death]#(lf)#(tab)#(tab)  ,DATEDIFF(week,[StartDate_HospitalProviderSpell], [DateOfDeath]) AS [death_in_weeks]#(lf),[10_year_age_band] = case when([A].[Age] between '65' and '74') THEN '65 to 74' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when ([A].[Age]between '75' and '84') THEN '75 to 84'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when ([A].[Age] between '85' and '94') THEN '85 to 94'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when ([A].[Age] > '94') THEN '95+'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)else 'Under 65'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)end#(lf)#(tab),[MPI].[eFI_Score_derived] [frailty_score]#(lf)        , case when [MPI].[eFI_Catgory_derived]  like 'Fit' then 'Fit' #(lf)#(tab)#(tab)when [MPI].[eFI_Catgory_derived] like 'mild frailty' then 'Mild Frailty'#(lf)#(tab)#(tab)when [MPI].[eFI_Catgory_derived] like 'moderate frailty' then 'Moderate Frailty'#(lf)#(tab)#(tab)when [MPI].[eFI_Catgory_derived] like 'severe frailty' then 'Severe Frailty'#(lf)#(tab)#(tab)when [MPI].[eFI_Catgory_derived] like 'unknown' then 'Unknown'#(lf)#(tab)#(tab)else 'Unknown'#(lf)#(tab)#(tab)end as [frailty_category]#(lf)#(tab)#(tab),case when(cast([Derived_SEM_SpellLOS] AS INT) between '0' and '1') then cast([Derived_SEM_SpellLOS] AS INT)#(lf)#(tab)#(tab)else '0'#(lf)#(tab)#(tab)end as '0-1_days_los'#(lf)#(tab)#(tab),case when(cast([Derived_SEM_SpellLOS] AS INT) > '1') then cast([Derived_SEM_SpellLOS] AS INT)#(lf)#(tab)#(tab)else '0'#(lf)#(tab)#(tab)end as '2+_days_los'#(lf)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)FROM [CCG_Current].[SEM].[vw_HospitalProviderSpell] [HPS]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_AgeBand] [A] ON [HPS].[AgeatCDSActivityDate] = [A].[Age]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] [D] ON CAST([HPS].DischargeDate_FromHospitalProviderSpell AS DATE) = [D].[date]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_GPPractice] [GP] ON [gppractice_derived] = [GP].OrganisationCode#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_HRG] [HRG] ON [HPS].[SpellCOREHRG] = [HRGCode]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_ICD10] [ICD] ON LEFT([HPS].[Derived_SEM_SpellPDiag],4) = [ICD].ICD10Code#(lf)LEFT JOIN #Temp_Dementia [DM] ON [HPS].[Derived_Pseudo_NHS] = [DM].[PseudoNHSNo]#(lf)LEFT JOIN [BIReports].[MPI].[MPI_current] [MPI] ON [HPS].[Derived_Pseudo_NHS] = [MPI].[Derived_Pseudo_NHS]#(lf)--LEFT JOIN [CCG_Reference].[Population].[vw_NHAIS_Deaths] [DP] ON [HPS].[Derived_Pseudo_NHS] = [DP].[Derived_Pseudo_NHS]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Population].[vw_PDS_Deaths] [DP] ON [HPS].[Derived_Pseudo_NHS] = [DP].[Derived_NHS_Number]#(lf)#(lf)LEFT JOIN #Care_Home [CH] ON [CH].Derived_Pseudo_NHSNumber = [HPS].Derived_Pseudo_NHS#(lf)#(lf)WHERE CAST([HPS].DischargeDate_FromHospitalProviderSpell AS DATE) between '20190401'   AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(lf)#(lf)AND LEFT([HPS].[AdmissionMethod_HospitalProviderSpell],1) = '2'#(lf)AND [HPS].[OrganisationCode_CodeOfCommissioner] LIKE '11M%'#(lf)AND [HPS].[AgeatCDSActivityDate] >= 65#(lf)AND (CONCAT(ISNULL(Diagnosis1stSecondary_ICD ,0) , ISNULL(Diagnosis2ndSecondary_ICD ,0) , ISNULL(Diagnosis3rdSecondary_ICD ,0) , ISNULL(Diagnosis4thSecondary_ICD,0), #(lf)           ISNULL(Diagnosis5thSecondary_ICD ,0) , ISNULL(Diagnosis6thSecondary_ICD ,0) , ISNULL(Diagnosis7thSecondary_ICD ,0) , ISNULL(Diagnosis8thSecondary_ICD,0), #(lf)#(tab)       ISNULL(Diagnosis9thSecondary_ICD ,0) , ISNULL(Diagnosis10thSecondary_ICD ,0) , ISNULL(Diagnosis11thSecondary_ICD ,0) , ISNULL(Diagnosis12thSecondary_ICD,0), #(lf)#(tab)       ISNULL( [Derived_SEM_SpellPDiag],0) ) LIKE '%W[00-19]%' AND [ICD].[ICD10_Chapter_Description] = 'Injury, poisoning and certain other consequences of external causes')#(lf)#(lf)#(tab)and Locality not like 'null'#(lf)#(lf)#(tab)#(lf)#(tab)#(tab)  order by DischargeDate_FromHospitalProviderSpell asc"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Died in hospital flag", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"counter", "Number of Admissions"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

