table 'ED Falls'
	lineageTag: 7a8b887e-4283-45ab-99fa-c6fd59137f70

	measure 'Locality Rate Per 1000 Falls Attendances' = (sum('ED Falls'[counter_ED_falls])/sum('Place Population'[Population]))*1000
		lineageTag: 259d098b-90c2-4dfa-a4c6-4aed36aa0cc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '2021/22 ED Falls' = CALCULATE(sum('ED Falls'[counter_ED_falls]),DATESBETWEEN('Date Table'[Date],date(2021,4,1),date(2022,3,31)))
		formatString: 0
		lineageTag: 30e39d60-e9e8-47ab-a669-ad230cd28327

	measure '2022/23 ED Falls' = CALCULATE(sum('ED Falls'[counter_ED_falls]),DATESBETWEEN('Date Table'[Date],date(2022,4,1),date(2022,12,31)))
		formatString: 0
		lineageTag: 82e46d8a-ae1a-415e-85b1-3dbde02e3aa8

	measure 'Comparison 2021/22 ED Falls' = CALCULATE(sum('ED Falls'[counter_ED_falls]),DATESBETWEEN('Date Table'[Date],date(2021,4,1),date(2021,12,31)))
		formatString: 0
		lineageTag: 16fce6a6-9648-4852-bda9-d961b456942c

	measure 'Dementia Rate Per 1000 Falls Attendances' = (sum('ED Falls'[counter_ED_falls])/sum('Dementia population'[COUNTER]))*1000
		lineageTag: 19fbfa6f-731e-46a1-ad82-a049de28170a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Care Home Rate Per 1000 Attendances' = (sum('ED Falls'[counter_ED_falls])/sum('Care home population'[COUNTER]))*1000
		lineageTag: 3b97d434-cc66-49cd-b0c7-40cd3de606a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Living Alone Status Rate Per 1000 Falls Attendances' = (sum('ED Falls'[counter_ED_falls])/sum('Living Alone Population'[COUNTER]))*1000
		lineageTag: db521b4d-7294-4f90-8201-a553bae61d30

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frailty Rate Per 1000 Attendances' = (sum('ED Falls'[counter_ED_falls])/sum('Frail population'[COUNTER]))*1000
		lineageTag: 7dabc98f-e1f9-4110-a88b-4cbda481b0ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Has Dementia Rate Per 1000 Falls Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[dementia_status]="Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="Dementia"))*1000
		lineageTag: de888b81-1823-4c4e-b255-3b0cae060680

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Old Dementia Rate Per 1000 Falls Attendances' = (sum('ED Falls'[counter_ED_falls])/sum('Dementia population'[COUNTER]))*1000
		lineageTag: b34c97db-0898-46ca-a7e6-38415657359b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Dementia Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[dementia_status]="No Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="No Dementia"))*1000
		lineageTag: 07006319-ced0-467a-9512-b15057d62030

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cheltenham Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[locality]="Cheltenham")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cheltenham"))*1000
		lineageTag: ce9f92e7-df25-4825-b003-0099b9d74ef3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TWNS Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[locality]="Tewkesbury Newent and Staunton")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Tewkesbury Newent and Staunton"))*1000
		lineageTag: 8d3c214c-58d4-46a8-8c59-48f95322e4ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FOD Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[locality]="The Forest of Dean")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="The Forest of Dean"))*1000
		lineageTag: 2b625bbf-be42-42d8-a88b-e5c775600bee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gloucester Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[locality]="Gloucester City")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Gloucester City"))*1000
		lineageTag: 176cbfaa-1949-499c-8ade-cfbfbe1e70b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'S&BV Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[locality]="Stroud and Berkeley Vale")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Stroud and Berkeley Vale"))*1000
		lineageTag: 405a3338-fa11-4d74-90e4-53c24756377c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotswolds Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[locality]="Cotswolds")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cotswolds"))*1000
		lineageTag: 4b7ccbc2-b710-4c2c-83b4-f267a37f40b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Moderate Frailty Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[frailty_category]="Moderate Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Moderate Frailty"))*1000
		lineageTag: d363990a-9d03-4828-beec-0ed31fa7d7f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mild Frailty Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[frailty_category]="Mild Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Mild Frailty"))*1000
		lineageTag: 3c94a9c1-5641-4c3d-b8f0-69edaeafe2fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fit Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[frailty_category]="Fit")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Fit"))*1000
		lineageTag: 389c1896-00dd-42f4-9401-f780411958a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Severe Frailty Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[frailty_category]="Severe Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Severe Frailty"))*1000
		lineageTag: 4a52e8a1-7fcf-4516-ae1e-78ffe53edb40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Living Alone Rate Per 1000 Falls Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[living_alone_status]="Living Alone")
			/CALCULATE(sum('Living Alone Population'[COUNTER]),'Living Alone Population'[Living Alone Status]="Living Alone"))*1000
		lineageTag: ea37b789-8b4b-4d4d-a274-1f0f1b4fe5d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Not Living Alone Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[living_alone_status]="Not Living Alone")
			/CALCULATE(sum('Living Alone Population'[COUNTER]),'Living Alone Population'[Living Alone Status]="Not Living Alone"))*1000
		lineageTag: 0f94a949-6c29-4b3b-a079-f253d34f2f4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Attendance Rate per 1000' = (sum('ED Falls'[counter_ED_falls])/sum('Place Population'[Population]))*1000
		lineageTag: 7639067e-cdda-4d70-a1bf-33fdaf3244f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LD Home Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[Care_home_status]="Learning Disability Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Learning Disability Home"))*1000
		lineageTag: 05677097-5168-4f9a-9926-0d3cc6eed12b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Not Living in a Care Home Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[Care_home_status]="Not Living in a Care Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Not Living in a Care Home"))*1000
		lineageTag: e1ebe2ce-7c6e-4f69-8fee-e4ef11acef8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nursing Home Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls'[counter_ED_falls]),'ED Falls'[Care_home_status]="Nursing Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Nursing Home"))*1000
		lineageTag: e21216a7-f2f9-46c1-995f-d070bb63ab68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Residential Care Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Residential Care Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Residential Care Home"))*1000
		lineageTag: 77334245-5f85-4177-b185-d48174263188

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unknown Care Home Rate Per 1000 Attendances' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Unknown Care Home Type")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Unknown Care Home Type"))*1000
		lineageTag: 85ad79d7-11cc-44dd-a10d-e8749ef3a92a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column presenting_complaint
		dataType: string
		lineageTag: d8452d37-ce38-4335-a0d6-d18c4d99dd20
		summarizeBy: none
		sourceColumn: presenting_complaint

		annotation SummarizationSetBy = Automatic

	column 10_year_age_band
		dataType: string
		lineageTag: 3c8762d6-cb94-4ce1-9858-7a0f9b762889
		summarizeBy: none
		sourceColumn: 10_year_age_band

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 0d10acb7-9c6a-4e8e-9a05-bdbfaa69d8a6
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column ed_attendance_number
		dataType: string
		lineageTag: 02379fcb-6480-47fa-a439-5bbe011dd201
		summarizeBy: none
		sourceColumn: ed_attendance_number

		annotation SummarizationSetBy = Automatic

	column nhs_number
		dataType: string
		lineageTag: 717424ba-1f6c-4cad-900c-899e800ae8de
		summarizeBy: none
		sourceColumn: nhs_number

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: 13700436-38f3-42ce-8aee-58a52c8d9514
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column site
		dataType: string
		lineageTag: 488bb10f-b7f5-4b16-9a2c-89e42841c3b4
		summarizeBy: none
		sourceColumn: site

		annotation SummarizationSetBy = Automatic

	column arrival_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9b1213a4-92ac-43a4-8598-87273cfb1c65
		summarizeBy: none
		sourceColumn: arrival_date

		annotation SummarizationSetBy = Automatic

	column arrival_date_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 3d5dcb89-7858-49c4-adeb-404201f18dc8
		summarizeBy: none
		sourceColumn: arrival_date_time

		variation Variation
			isDefault
			relationship: 814987cd-d84c-46bf-a006-4bd13c8d05a7
			defaultHierarchy: LocalDateTable_b7932bce-7141-49ce-95a6-cc3fb7705ce0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column arrival_time_flag
		dataType: string
		lineageTag: 2e7909fa-5eb2-47a2-bf48-38a20dddc65c
		summarizeBy: none
		sourceColumn: arrival_time_flag

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 19c59bb9-a119-480d-9d80-edb5bad2ef2d
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 540119fa-8c9c-4f38-b983-e6e92c6e48a8
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: a84dff98-e024-4641-87c2-b4899218eba3
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band
		dataType: string
		lineageTag: c96b647d-7cee-44fc-8970-7f348dafeb2b
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: 195062e9-00d7-496e-8d47-ba58fb092e60
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column practice_name
		dataType: string
		lineageTag: bc05c47c-bdb1-4c7d-8ea1-234ec846a7ea
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

	column primary_care_network
		dataType: string
		lineageTag: c270a05b-ec7b-43af-9ecd-346497f3ae64
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = User

	column locality
		dataType: string
		lineageTag: a650407f-577b-4450-baf5-17d421946cab
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column hrg_code
		dataType: string
		lineageTag: 9ff83e4e-7853-4ebe-aa20-bf6e7e2483f8
		summarizeBy: none
		sourceColumn: hrg_code

		annotation SummarizationSetBy = Automatic

	column hrg_description
		dataType: string
		lineageTag: 65d387a5-a8f4-4065-b12e-137927444294
		summarizeBy: none
		sourceColumn: hrg_description

		annotation SummarizationSetBy = Automatic

	column counter_ED_falls
		dataType: int64
		formatString: 0
		lineageTag: 960f5990-e20a-4928-ba32-38a0e47935e6
		summarizeBy: sum
		sourceColumn: counter_ED_falls

		annotation SummarizationSetBy = Automatic

	column arrival_mode_code
		dataType: string
		lineageTag: 3d9ce97a-c9ea-4594-b9b5-f75f04e284a6
		summarizeBy: none
		sourceColumn: arrival_mode_code

		annotation SummarizationSetBy = Automatic

	column arrival_mode_description
		dataType: string
		lineageTag: 00d6a94a-1965-4219-aa68-2069d1bc3660
		summarizeBy: none
		sourceColumn: arrival_mode_description

		annotation SummarizationSetBy = Automatic

	column source_of_referral_code
		dataType: string
		lineageTag: 9da0ff79-bd29-476c-a9f2-59b062ab3dfb
		summarizeBy: none
		sourceColumn: source_of_referral_code

		annotation SummarizationSetBy = Automatic

	column source_of_referral_description
		dataType: string
		lineageTag: 47401796-43f3-42d3-8345-c596272754d6
		summarizeBy: none
		sourceColumn: source_of_referral_description

		annotation SummarizationSetBy = Automatic

	column attendance_category_code
		dataType: string
		lineageTag: 6fdcd5a2-3149-4e1b-bade-9da48fecaa4d
		summarizeBy: none
		sourceColumn: attendance_category_code

		annotation SummarizationSetBy = Automatic

	column disposal_code
		dataType: string
		lineageTag: 2581fcba-646b-4ac9-ae34-0fa009b9d616
		summarizeBy: none
		sourceColumn: disposal_code

		annotation SummarizationSetBy = Automatic

	column disposal_description
		dataType: string
		lineageTag: 70bc9728-ce4a-4523-bbdf-c9b153b15ebf
		summarizeBy: none
		sourceColumn: disposal_description

		annotation SummarizationSetBy = Automatic

	column admitted_flag
		dataType: int64
		formatString: 0
		lineageTag: ca7ce94b-f95c-4db1-bc53-59ec0e4d4da5
		summarizeBy: sum
		sourceColumn: admitted_flag

		annotation SummarizationSetBy = Automatic

	column ed_department_type
		dataType: string
		lineageTag: 6f8ab5dc-f615-4b67-b7ac-4235e6c73ddb
		summarizeBy: none
		sourceColumn: ed_department_type

		annotation SummarizationSetBy = Automatic

	column frailty_score
		dataType: double
		lineageTag: 7f48ae2d-08f5-45cd-a5d2-1aabc7e156b8
		summarizeBy: sum
		sourceColumn: frailty_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column frailty_category
		dataType: string
		lineageTag: 68d10b09-c95f-4b10-bdae-0a5b3f5f4bc4
		summarizeBy: none
		sourceColumn: frailty_category

		annotation SummarizationSetBy = Automatic

	column dementia_status
		dataType: string
		lineageTag: f9cfbdc8-f47e-45f2-bbb0-fa463de7ba8a
		summarizeBy: none
		sourceColumn: dementia_status

		annotation SummarizationSetBy = Automatic

	column living_alone_status
		dataType: string
		lineageTag: 07ebe93c-1a7c-4bc7-b9c4-14ab22f7df9d
		summarizeBy: none
		sourceColumn: living_alone_status

		annotation SummarizationSetBy = Automatic

	column admitted_flag_description
		dataType: string
		lineageTag: 80ff86c9-3572-426f-be4e-cca4d3d5adad
		summarizeBy: none
		sourceColumn: admitted_flag_description

		annotation SummarizationSetBy = Automatic

	column grouped_ed_arrival_method
		dataType: string
		lineageTag: 941d7b7c-ebe6-477b-9529-7b2de6e2b1b4
		summarizeBy: none
		sourceColumn: grouped_ed_arrival_method

		annotation SummarizationSetBy = Automatic

	column grouped_source_of_referral
		dataType: string
		lineageTag: 9fc99836-b77b-4f40-a792-f67f72ae2ecc
		summarizeBy: none
		sourceColumn: grouped_source_of_referral

		annotation SummarizationSetBy = Automatic

	column correct_practice_code
		dataType: string
		lineageTag: a1709b01-0d0f-4f2b-9531-2efad59c0179
		summarizeBy: none
		sourceColumn: correct_practice_code

		annotation SummarizationSetBy = Automatic

	column ReportingOrganisationName
		dataType: string
		lineageTag: 9f8bc3f8-d9db-4b69-b4aa-9f62a3fc9b3c
		summarizeBy: none
		sourceColumn: ReportingOrganisationName

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingInCareHome
		dataType: int64
		formatString: 0
		lineageTag: c237a147-79c8-42f1-9483-b20cae6b2b93
		summarizeBy: sum
		sourceColumn: Derived_IsLivingInCareHome

		annotation SummarizationSetBy = Automatic

	column 'Care Home Type'
		dataType: string
		lineageTag: d2037bc7-4fce-4ee4-a0d3-441c6b93c6a1
		summarizeBy: none
		sourceColumn: Care Home Type

		annotation SummarizationSetBy = Automatic

	column Care_home_status
		dataType: string
		lineageTag: 1186e558-7a91-4aab-b7b8-58b8b41470dd
		summarizeBy: none
		sourceColumn: Care_home_status

		annotation SummarizationSetBy = Automatic

	column Care_home_status2
		dataType: string
		lineageTag: 02664604-d7cc-4073-8bb6-1a14a95e08a3
		summarizeBy: none
		sourceColumn: Care_home_status2

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingAlone
		dataType: int64
		formatString: 0
		lineageTag: 69d73e48-6be3-4d7b-a0e3-4b541f58e7fa
		summarizeBy: sum
		sourceColumn: Derived_IsLivingAlone

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: eb6f815b-140b-4923-ad3c-2455593294ce
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	hierarchy 'locality Hierarchy'
		lineageTag: abbf225f-29f4-4837-b25a-4ed29cd4d1fc

		level locality
			lineageTag: 61b8e256-55a2-4515-86d8-8bdda19c3fef
			column: locality

		level primary_care_network
			lineageTag: da7647e5-3eb3-4cf0-90c4-45a425e4ac8d
			column: primary_care_network

	partition 'ED Falls-1dc2f4ba-4ece-46db-8fe3-1c6f8763b10f' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_current", [Query="--==--==--==--==--==--==--==--==--==--==--==--==--==--==#(lf)-- GHFT ED Attendances for Falls -- #(lf)--==--==--==--==--==--==--==--==--==--==--==--==--==--==#(lf)--Created by: Kyran Witney#(lf)--Created on: #(lf)--Updated by: Alex Davey#(lf)--Updated on: 31/01/2023#(lf)#(lf)#(lf)SET ANSI_WARNINGS OFF#(lf)SET NOCOUNT ON#(lf)if object_id ('tempdb..#Temp_Dementia') is not null drop table #Temp_Dementia#(lf)#(lf)--- DEMENTIA TEMP#(lf)#(lf)SELECT DISTINCT [PseudoNHSNo],#(lf)[Dementia]#(lf)INTO #Temp_Dementia#(lf)FROM [CCG_Current].[PrimaryCare].[vw_LongTermConditionsQOFPatients]#(lf)WHERE [Dementia] = '1'#(lf)#(lf)#(lf)--Care home temp table, pulling in care home name and type#(lf)#(lf)SET ANSI_WARNINGS OFF#(lf)SET NOCOUNT ON#(lf)if object_id ('tempdb..#Care_Home') is not null drop table #Care_Home#(lf)#(lf)SELECT DISTINCT#(lf) #(lf)#(tab)Derived_Pseudo_NHSNumber#(lf)      ,[Residential_or_Nursing_home_Location_Name]#(lf)#(tab)  ,[Nursing Care Homes ]#(lf)#(tab)  ,[Care Home Type]#(lf)#(tab)  ,[Date_of_incident] = cast([Time_Of_Incident] as date)#(lf)#(lf)#(tab)  INTO #Care_Home#(lf)#(lf)  FROM [CCG_Current].[SWASFT].[vw_AmbulanceServicePatient] [A]#(lf)#(lf)  LEFT JOIN [BIReports].[dbo].[CHLookup2022_Oct] [CH] ON [CH].[SWASFT Care Home Name] = [A].[Residential_or_Nursing_home_Location_Name]#(lf)   #(lf)  where #(lf)  #(lf)   [Residential_or_Nursing_home_Location] not like 'null'#(lf)#(lf)  and Derived_Pseudo_NHSNumber not like 'Null'#(lf)#(lf)  and [Care Home Type] not like 'NULL'#(lf)#(lf)#(lf)#(lf)-- MAIN SCRIPT #(lf)#(lf)#(lf)SELECT  distinct 'ED Attendance' [type]#(lf),Gender#(lf)        ,[ae_attendance_number] [ed_attendance_number]#(lf)        ,[ED].[Derived_Pseudo_NHS] [nhs_number]#(lf)#(tab)#(tab),[mpi].[Derived_IsLivingAlone]#(lf)#(lf)#(tab)#(tab),case  #(lf)#(tab)#(tab)when [mpi].Derived_IsLivingInCareHome like '1' then 'Not Living Alone'#(lf)#(tab)#(tab)when [Care Home Type] not like 'null' then 'Not Living Alone'#(lf)#(tab)#(tab)when [mpi].[Derived_IsLivingAlone] like '0' then 'Not Living Alone'#(lf)#(tab)#(tab)when [mpi].[Derived_IsLivingAlone] is null  then 'Not Living Alone'#(lf)#(lf)#(tab)#(tab)else 'Living Alone'#(lf)#(tab)#(tab)end as 'living_alone_status'#(lf)#(lf)#(tab)#(tab),[mpi].Derived_IsLivingInCareHome#(lf)#(tab)#(tab),[CH].[Care Home Type]#(lf)#(lf)#(tab)#(tab),[Care_home_status] = case when [mpi].Derived_IsLivingInCareHome like '1' and [CH].[Care Home Type] IS NULL then 'Unknown Care Home Type'#(lf)#(tab)#(tab)when ([CH].[Care Home Type] not like 'NULL') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type] not like 'null') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome like '0' and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(lf)#(tab)#(tab)end#(lf)#(tab)#(lf)#(lf)        ,[organisation_code_of_provider] [provider_code]#(lf)        ,CASE WHEN [organisation_code_of_provider] = 'RTE01' THEN 'Cheltenham General Hospital'#(lf)              WHEN [organisation_code_of_provider] = 'RTE03' THEN 'Gloucester Royal Hospital'#(lf)              END [site]#(lf)        ,CAST([arrival_date] AS DATE) [arrival_date]#(lf)#(tab)#(tab),[arrival_date] [arrival_date_time]#(lf)#(tab)#(tab),CASE WHEN CAST([arrival_date] AS TIME) BETWEEN '08:00:00' AND '20:00:00' THEN '8am - 8pm'#(lf)              WHEN CAST([arrival_date] AS TIME) IS NULL THEN 'NULL'#(lf)              ELSE 'Night Attendance' END AS 'arrival_time_flag'#(lf)        ,[D].[YearMonth] [year_month]#(lf)        ,LEFT([D].[MonthName],3) [month_name]#(lf)        ,[D].[FinancialYear] [financial_year]#(lf)        ,[A].[5yr_age_band] [5yr_age_band]#(lf)        ,[code_of_gp_practice_registered_gmp] [practice_code]#(lf)#(lf)#(tab)#(tab),[correct_practice_code] = case when [code_of_gp_practice_registered_gmp]  like 'L84001' then 'L84050'#(lf)#(tab)#(tab)when [code_of_gp_practice_registered_gmp]  like 'L84002' then 'L84606'#(lf)#(tab)#(tab)when [code_of_gp_practice_registered_gmp]  like 'L84020' then 'L84012'#(lf)#(tab)#(tab)when [code_of_gp_practice_registered_gmp]  like 'L84044' then 'L84027'#(lf)#(tab)#(tab)when [code_of_gp_practice_registered_gmp]  like 'L84056' then 'L84033'#(lf)#(tab)#(tab)when [code_of_gp_practice_registered_gmp]  like 'L84032' then 'L84077'#(lf)#(tab)#(tab)else [code_of_gp_practice_registered_gmp]#(lf)#(tab)#(tab)end#(lf)#(lf)#(tab)#(tab),ReportingOrganisationName#(lf)#(tab)#(tab)#(lf)        ,[GP].OrganisationName [practice_name]#(lf)        ,[GP].primarycarenetwork [primary_care_network]#(lf)        ,CASE WHEN [GP].Locality LIKE '%Cotswold%' THEN 'Cotswolds' ELSE [GP].Locality END AS [locality]#(lf)        ,[EM_HRG] [hrg_code] -- neeeds review and potentially join to HRG ref table if needed#(lf)        ,[HRGCodeDescription] [hrg_description] -- neeeds review and potentially join to HRG ref table if needed#(lf)#(tab)#(tab), 1 AS [counter]#(lf)#(tab)    ,[ae_arrival_mode_code] [arrival_mode_code]#(lf)#(tab)#(tab),[local_ae_arrival_mode] [arrival_mode_description]#(lf)        ,[ae_source_of_referral_for_ae_code] [source_of_referral_code]#(lf)#(tab)#(tab),[SOR].[AESourceOfReferralName] [source_of_referral_description]#(lf)#(tab)    ,[ae_attendance_category_code] [attendance_category_code]#(lf)        ,[ae_attendance_disposal_code] [disposal_code]#(lf)#(tab)#(tab),[DC].[DisposalDescription] [disposal_description] #(lf)#(tab)#(tab),CASE WHEN [ae_attendance_disposal_code] = '01' THEN 'Admitted'#(lf)#(tab)#(tab)      ELSE 'Not admitted' END AS [admitted_flag_description]#(lf)#(tab)#(tab),CASE WHEN [ae_attendance_disposal_code] = '01' THEN '1'#(lf)#(tab)#(tab)      ELSE '0' END AS [admitted_flag]#(lf)#(tab)#(tab),[ae_department_type_code] [ed_department_type] -- ED or MIU attendance#(lf)#(tab)#(tab)#(tab),[MPI].[eFI_Score_derived] [frailty_score]#(lf)        ,[MPI].[eFI_Catgory_derived] [frailty_category]#(lf)#(tab)#(tab)--,[DP].[Derived_Pseudo_NHS] [deceased_nhs_number]#(lf)--,CASE WHEN [ED].[Derived_Pseudo_NHS] = [DP].[Derived_Pseudo_NHS] THEN 'Deceased'#(lf)--ELSE 'Alive' END AS [mortality_flag]#(lf)--,[DP].[Date_Of_Death] [date_of_death]#(lf)--,DATEDIFF(week,[arrival_date], [Date_Of_Death]) AS [death_in_weeks]#(lf),presenting_complaint#(lf),[10_year_age_band] = case when([A].[Age] between '65' and '74') THEN '65 to 74' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when ([A].[Age]between '75' and '84') THEN '75 to 84'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when ([A].[Age] between '85' and '94') THEN '85 to 94'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when ([A].[Age] > '94') THEN '95+'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)else 'Under 65'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)end#(lf) ,case when [DM].[Dementia] like '1' then 'Dementia'#(lf)#(tab)#(tab)when [DM].[Dementia] like 'null' then 'No Dementia'#(lf)#(tab)#(tab)when [DM].[Dementia] like '0' then 'No dementia'#(lf)#(tab)#(tab)else 'No dementia'#(lf)#(tab)#(tab)end as 'dementia_status'#(lf)#(lf) #(lf)#(tab)#(tab)#(lf)#(tab)#(tab),[Care_home_status] = case when [mpi].Derived_IsLivingInCareHome like '1' and [CH].[Care Home Type] IS NULL then 'Unknown Care Home Type'#(lf)#(tab)#(tab)when ([CH].[Care Home Type] not like 'NULL') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type] not like 'null') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome like '0' and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(lf)#(tab)#(tab)end#(lf)#(tab)#(lf)#(lf)#(tab),case when [local_ae_arrival_mode]  like 'ambulance' then 'Ambulance'#(lf)#(tab)when [local_ae_arrival_mode]  like 'air ambulance' then 'Ambulance'#(lf)#(tab)else 'Non-Ambulance'#(lf)#(tab)end as 'grouped_ed_arrival_method'#(lf)#(lf)#(tab),case when [SOR].[AESourceOfReferralName] like 'Emergency services' then 'Emergency services' #(lf)#(tab)when [SOR].[AESourceOfReferralName] like 'Self referral' then 'Self referral'#(lf)#(tab)else  'Other'#(lf)#(tab)end as 'grouped_source_of_referral'#(lf)      #(tab)#(tab)#(lf)#(tab)#(lf)FROM [CCG_Current].[GHFT].[vw_ED_Attendance] [ED]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_AgeBand] [A] ON [ED].[age_at_CDS_activity_date] = [A].[Age]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] [D] ON CAST([ED].[arrival_date] AS DATE) = [D].[date]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_GPPractice] [GP] ON [ED].[code_of_gp_practice_registered_gmp] = [GP].OrganisationCode#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_HRG] [HRG] ON [ED].[EM_HRG] = [HRGCode]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_aesourceofreferral] [SOR] on [ED].ae_source_of_referral_for_ae_code = [SOR].[AESourceOfReferralCode]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_aearrivalmode] [AM] on [ED].[ae_arrival_mode_code] = [AM].[AEArrivalModeCode]#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_aeattendancedisposal] [DC] on [ED].ae_attendance_disposal_code = [DC].[DisposalCode]#(lf)LEFT JOIN #Temp_Dementia [DM] ON [ED].[Derived_Pseudo_NHS] = [DM].[PseudoNHSNo]#(lf)LEFT JOIN [BIReports].[MPI].[MPI_current] [MPI] ON [ED].[Derived_Pseudo_NHS] = [MPI].[Derived_Pseudo_NHS]#(lf)--LEFT JOIN [CCG_Reference].[Population].[vw_NHAIS_Deaths] [DP] ON [ED].[Derived_Pseudo_NHS] = [DP].[Derived_Pseudo_NHS]#(lf)--LEFT JOIN [CCG_Reference].[Reference].[vw_aediagnosis] g on left([ED].diagnosis_code_01,3) = g.[Diagnosis Code]#(lf)LEFT JOIN #Care_Home [CH] ON [CH].Derived_Pseudo_NHSNumber = [ED].Derived_Pseudo_NHS#(lf)#(lf)#(lf)WHERE [presenting_complaint] LIKE '%f[ae]ll%'#(lf)#(lf)and [locality] not like 'null'#(lf)#(lf)AND [ED].[age_at_CDS_activity_date] >= 65#(lf)AND CAST([ED].[arrival_date] AS DATE) >= '20190401'#(lf)and CAST([ED].[arrival_date] AS DATE) < '20230101'#(lf)AND CCG_Of_Registration like '%11M%'#(lf)#(lf)order by arrival_date#(lf)#(lf)#(lf)#(lf)"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"counter", "counter_ED_falls"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"admitted_flag", Int64.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"admitted_flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

