table 'SWAST Falls'
	lineageTag: e23893d4-c2a4-4a3b-882d-98d1d98d665a

	measure 'Rate Per 1000 Falls SWAST' = (sum('SWAST Falls'[Number of Calls])/sum('Place Population'[Population]))*1000
		lineageTag: a7d6d8ef-3f0d-43d4-b5c8-d3a4395a57e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Calls in 2022/23' = CALCULATE(sum('SWAST Falls'[Number of Calls]),DATESBETWEEN('Date Table'[Date],date(2022,4,1),date(2023,3,31)))
		formatString: 0
		lineageTag: ffe8e98e-ae43-45e9-9315-4692bb62e68c

	measure 'Number of Calls in 2021/22' = CALCULATE(sum('SWAST Falls'[Number of Calls]),DATESBETWEEN('Date Table'[Date],date(2021,4,1),date(2022,3,31)))
		formatString: 0
		lineageTag: 556e9960-2ab3-48b2-bce3-c6e773a119b6

	measure '2021/22 calls comparison' = CALCULATE(sum('SWAST Falls'[Number of Calls]),DATESBETWEEN('Date Table'[Date],date(2021,4,1),date(2021,10,31)))
		formatString: 0
		lineageTag: bcaf6314-ae0c-463b-9a6f-688188328db8

	measure '2022/23 calls comparison' = CALCULATE(sum('SWAST Falls'[Number of Calls]),DATESBETWEEN('Date Table'[Date],date(2022,4,1),date(2022,10,31)))
		formatString: 0
		lineageTag: 86c680c4-c5a8-4bd4-ba1d-ea86797a6bed

	column id
		dataType: int64
		formatString: 0
		lineageTag: 0ae02a35-9edb-4085-ad83-45bb483e564c
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column incident_number
		dataType: string
		lineageTag: 662f1357-5f7d-4520-8901-7c524261e114
		summarizeBy: none
		sourceColumn: incident_number

		annotation SummarizationSetBy = Automatic

	column derived_pseudo_nhsnumber
		dataType: string
		lineageTag: 9e98b219-4418-47ad-885b-76c926f818eb
		summarizeBy: none
		sourceColumn: derived_pseudo_nhsnumber

		annotation SummarizationSetBy = Automatic

	column symptom_group_chief_complaint
		dataType: string
		lineageTag: f4a02be2-8fdd-48a4-8f5e-053332b80fc4
		summarizeBy: none
		sourceColumn: symptom_group_chief_complaint

		annotation SummarizationSetBy = Automatic

	column pathways_ampds_disposition
		dataType: string
		lineageTag: 75916b06-944b-4454-9f8d-be527b1115ae
		summarizeBy: none
		sourceColumn: pathways_ampds_disposition

		annotation SummarizationSetBy = Automatic

	column outcome
		dataType: string
		lineageTag: 380cb600-6785-4436-854a-30094fdc0761
		summarizeBy: none
		sourceColumn: outcome

		annotation SummarizationSetBy = Automatic

	column month_of_call
		dataType: string
		lineageTag: d7d1a481-2025-4db9-adb0-f4998ff658f6
		summarizeBy: none
		sourceColumn: month_of_call

		annotation SummarizationSetBy = Automatic

	column age_bracket
		dataType: string
		lineageTag: ce91d775-f93d-4756-bf9d-05174e32d2ef
		summarizeBy: none
		sourceColumn: age_bracket

		annotation SummarizationSetBy = Automatic

	column response_time_band
		dataType: string
		lineageTag: 6aa8ed29-78c7-4450-b356-6a8c9c03fb7c
		summarizeBy: none
		sourceColumn: response_time_band

		annotation SummarizationSetBy = Automatic

	column response_target_1_clock_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 2a972782-fd63-44c2-9e5b-744045f92427
		summarizeBy: none
		sourceColumn: response_target_1_clock_start

		variation Variation
			isDefault
			relationship: 09cea17c-52e2-4bd4-a7d3-4b9d785bc3e3
			defaultHierarchy: LocalDateTable_b6ce3e67-fffb-4e5a-908a-551d25e20c13.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column response_target_1_clock_stop
		dataType: dateTime
		formatString: General Date
		lineageTag: eed34bff-981f-482f-9c10-89a7f0a834ab
		summarizeBy: none
		sourceColumn: response_target_1_clock_stop

		variation Variation
			isDefault
			relationship: db14bff3-c7ff-4ca6-ad18-489c4b08571a
			defaultHierarchy: LocalDateTable_4b4b1b74-81b3-4e9b-8d45-3b56fb104100.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column response_time_sec
		dataType: int64
		formatString: 0
		lineageTag: 127e8902-3235-4fde-ab3a-1c97c79abe9f
		summarizeBy: sum
		sourceColumn: response_time_sec

		annotation SummarizationSetBy = Automatic

	column residential_or_nursing_home_location
		dataType: string
		lineageTag: beee1b72-035d-415c-9bb4-5450b9b71823
		summarizeBy: none
		sourceColumn: residential_or_nursing_home_location

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 7a2e88c9-5aff-4a70-994a-8bf3b5f613dc
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column outcome_expanded
		dataType: string
		lineageTag: 4bda1406-313c-4409-ba0b-1c76ff2c4231
		summarizeBy: none
		sourceColumn: outcome_expanded

		annotation SummarizationSetBy = Automatic

	column 'Number of Calls'
		dataType: int64
		formatString: 0
		lineageTag: bbffc9c5-a679-42dd-baa9-010653e12831
		summarizeBy: sum
		sourceColumn: Number of Calls

		annotation SummarizationSetBy = Automatic

	column time_of_incident
		dataType: dateTime
		formatString: General Date
		lineageTag: 29fae622-2f06-492f-90f6-a8300a9900c9
		summarizeBy: none
		sourceColumn: time_of_incident

		variation Variation
			isDefault
			relationship: 29d0fa67-4c29-48dd-9c83-c577d927b77c
			defaultHierarchy: LocalDateTable_cedd15e2-4c3d-4de3-a1d0-1789a8c26bcc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column date_of_incident
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b0bf34b-4adb-4a84-af30-d36cd91e7b19
		summarizeBy: none
		sourceColumn: date_of_incident

		annotation SummarizationSetBy = Automatic

	column response_time_minutes
		dataType: int64
		formatString: 0
		lineageTag: 491560fa-2934-40f2-8920-bf73a95acf09
		summarizeBy: sum
		sourceColumn: response_time_minutes

		annotation SummarizationSetBy = Automatic

	column response_time_hours
		dataType: int64
		formatString: 0
		lineageTag: 53ebbfa2-7e8b-4750-b8c0-027c1b465d6d
		summarizeBy: sum
		sourceColumn: response_time_hours

		annotation SummarizationSetBy = Automatic

	column hour_of_incident
		dataType: string
		lineageTag: e7bcc45a-77c5-4b76-89bc-e8457b49cb25
		summarizeBy: none
		sourceColumn: hour_of_incident

		annotation SummarizationSetBy = Automatic

	column dementia_status
		dataType: string
		lineageTag: 8d001994-cd26-4052-9873-179d3f6194df
		summarizeBy: none
		sourceColumn: dementia_status

		annotation SummarizationSetBy = Automatic

	column living_alone_status
		dataType: string
		lineageTag: d88c5a3d-b23d-4024-b904-b612518922c9
		summarizeBy: none
		sourceColumn: living_alone_status

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingInCareHome
		dataType: int64
		formatString: 0
		lineageTag: aad2071d-c075-4fa5-ac17-a66fb5d6dbab
		summarizeBy: sum
		sourceColumn: Derived_IsLivingInCareHome

		annotation SummarizationSetBy = Automatic

	column 'Care Home Type'
		dataType: string
		lineageTag: 4f384f59-efd2-448c-a356-bfda8c3e9e53
		summarizeBy: none
		sourceColumn: Care Home Type

		annotation SummarizationSetBy = Automatic

	column Care_home_status
		dataType: string
		lineageTag: 5005b4b3-8e70-40c4-92bd-7bbf30bf0f89
		summarizeBy: none
		sourceColumn: Care_home_status

		annotation SummarizationSetBy = Automatic

	column Day_of_week
		dataType: string
		lineageTag: 5b2f31fb-c14f-4adf-a178-4abefad73f77
		summarizeBy: none
		sourceColumn: Day_of_week

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: e7dbcd06-1fbf-4814-8068-9566804aa730
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingAlone
		dataType: int64
		formatString: 0
		lineageTag: 7de7566a-cd12-42d8-89c7-8adc46e2ecb5
		summarizeBy: sum
		sourceColumn: Derived_IsLivingAlone

		annotation SummarizationSetBy = Automatic

	column First_Ward_Attended
		dataType: string
		lineageTag: a82ad812-57bb-464e-8197-3a3f8e10eee9
		summarizeBy: none
		sourceColumn: First_Ward_Attended

		annotation SummarizationSetBy = Automatic

	column First_Hospital_Attended
		dataType: string
		lineageTag: fe2f1888-f545-42d7-8044-c4fdf2ad51aa
		summarizeBy: none
		sourceColumn: First_Hospital_Attended

		annotation SummarizationSetBy = Automatic

	column Provider
		dataType: string
		lineageTag: c96b44c1-9eea-4ef1-82f3-56400bca827f
		summarizeBy: none
		sourceColumn: Provider

		annotation SummarizationSetBy = Automatic

	column Conveyed_To_Ward_Type
		dataType: string
		lineageTag: 27618de5-50fa-4418-abc4-b58d609a4a30
		summarizeBy: none
		sourceColumn: Conveyed_To_Ward_Type

		annotation SummarizationSetBy = Automatic

	partition 'SWAST Falls-b0cf5c5d-ce02-4153-a597-3c597a1d7181' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_current", [Query="/****** Script for SelectTopNRows command from SSMS  ******/#(lf)--Created by: Alex Davey#(lf)--Created on: 01/10/2022#(lf)--Updated by: Alex Davey#(lf)--Updated on: 28/02/2023#(lf)#(lf)SELECT distinct#(lf)#(lf)#(tab)#(tab)[id]#(lf)#(tab)#(tab),[incident_number]#(lf)#(tab)#(tab),'SWAST Call' [type]#(lf)#(tab)#(tab),[time_of_incident]#(lf)#(tab)#(tab),[date_of_incident] = cast([time_of_incident] as date)#(lf)      ,[derived_pseudo_nhsnumber]#(lf)#(tab)  ,[symptom_group_chief_complaint]#(lf)      ,[pathways_ampds_disposition]#(lf)      ,[outcome]#(lf)#(tab)  ,[month_of_call]#(lf)#(tab)  ,[age_bracket]  #(lf)#(tab) #(lf)#(tab)  ,datediff(MI,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) as 'response_time_minutes'#(lf)#(tab)  ,datediff(HOUR,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) as 'response_time_hours'#(lf)#(tab)  ,case when datediff(MINUTE,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) < '180' then 'Within 3 hours'#(lf)#(tab)#(tab)#(tab)when datediff(MINUTE,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) between '180' and '360' then 'Between 3 and 6 hours'#(lf)#(tab)#(tab)#(tab)when datediff(MINUTE,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) between '360' and '540' then 'Between 6 and 9 hours'#(lf)#(tab)#(tab)#(tab)when datediff(MINUTE,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) between '540' and '720' then 'Between 9 and 12 hours'#(lf)#(tab)#(tab)#(tab)when datediff(MINUTE,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) > '720' then 'Greater than 12 hours'#(lf)#(tab)#(tab)#(tab)else 'error'#(lf)#(tab)#(tab)#(tab)end as 'response_time_band'#(lf)#(lf)#(tab),[hour_of_incident] =  #(lf)#(tab)case when [Response_Target_1_Clock Start] not like 'null' then concat(datepart(hour, [time_of_incident]),':00')#(lf)#(tab)else 'null'#(lf)#(tab)end#(lf)#(lf)#(tab),[Day_of_week] =#(tab)case when DATEPART(weekday,[time_of_incident]) like '1' then 'Sunday'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DATEPART(weekday,[time_of_incident]) like '2' then 'Monday'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DATEPART(weekday,[time_of_incident]) like '3' then 'Tuesday'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DATEPART(weekday,[time_of_incident]) like '4' then 'Wednesday'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DATEPART(weekday,[time_of_incident]) like '5' then 'Thursday'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DATEPART(weekday,[time_of_incident]) like '6' then 'Friday'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)when DATEPART(weekday,[time_of_incident]) like '7' then 'Saturday'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(lf)#(tab) ,case when [LTC].[Dementia] like '1' then 'Dementia'#(lf)#(tab)#(tab)when [LTC].[Dementia] like 'null' then 'No Dementia'#(lf)#(tab)#(tab)when [LTC].[Dementia] like '0' then 'No dementia'#(lf)#(tab)#(tab)else 'No dementia'#(lf)#(tab)#(tab)end as 'dementia_status'#(lf)#(lf)#(tab)#(tab),[mpi].Derived_IsLivingAlone#(lf)#(lf)  ,case  #(lf)#(tab)#(tab)when [mpi].Derived_IsLivingInCareHome like '1' then 'Not Living Alone'#(lf)#(tab)#(tab)when [Care Home Type] not like 'null' then 'Not Living Alone'#(lf)#(tab)#(tab)when [mpi].[Derived_IsLivingAlone] like '0' then 'Not Living Alone'#(lf)#(tab)#(tab)when [mpi].[Derived_IsLivingAlone] is null  then 'Not Living Alone'#(lf)#(lf)#(tab)#(tab)else 'Living Alone'#(lf)#(tab)#(tab)end as 'living_alone_status'#(lf)#(lf)        ,[MPI].[Derived_IsLivingInCareHome]#(lf)#(tab)#(tab),[Care Home Type]#(lf)#(lf)#(tab)#(tab)#(tab),[Care_home_status] = case when [mpi].Derived_IsLivingInCareHome like '1' and [CH].[Care Home Type] IS NULL then 'Unknown Care Home Type'#(lf)#(tab)#(tab)when ([CH].[Care Home Type] not like 'NULL') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type] not like 'null') then [CH].[Care Home Type]#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome IS NULL and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(tab)#(tab)when  ([mpi].Derived_IsLivingInCareHome like '0' and [CH].[Care Home Type]  IS NULL) then 'Not Living in a Care Home'#(lf)#(lf)#(tab)#(tab)end#(lf)#(lf)#(tab)  ,[response_target_1_clock_start] = [response_target_1_clock start]#(lf)#(tab)  ,[response_target_1_clock_stop] = [response_target_1_clock stop]#(lf)#(tab)  ,datediff(SECOND,[Response_Target_1_Clock Start],[Response_Target_1_Clock Stop]) as 'response_time_sec'#(lf)#(lf)#(lf)#(tab)  ,residential_or_nursing_home_location#(lf)#(tab)  ,[financial_year] = financialyear#(lf)#(tab)  ,[counter] = '1'#(lf)#(tab) #(lf)#(lf),CASE WHEN outcome = 'See & Convey' and Conveyed_To_Ward_Type = 'A&E' then 'See & Convey - A&E'#(lf)else outcome end as 'outcome_expanded'#(lf)#(lf),First_Ward_Attended#(lf),First_Hospital_Attended#(lf),Provider = Name#(lf),Conveyed_To_Ward_Type#(lf)#(lf)#(lf)  FROM [CCG_Current].[SWASFT].[vw_AmbulanceServicePatient]#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] ON CAST([vw_AmbulanceServicePatient].[Time_Of_Incident] AS DATE) = [date]#(lf)#(lf)LEFT JOIN [CCG_Current].[PrimaryCare].[vw_LongTermConditionsQOFPatients] [LTC] on [LTC].PseudoNHSNo = [derived_pseudo_nhsnumber]#(lf)#(lf)LEFT JOIN [BIReports].MPI.MPI_current [MPI] ON [MPI].Derived_Pseudo_NHS = [derived_pseudo_nhsnumber]#(lf)#(lf) LEFT JOIN [BIReports].[dbo].[CHLookup2022_Oct] [CH] ON [CH].[SWASFT Care Home Name] = [Residential_or_Nursing_home_Location_Name]#(lf)   #(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_OrganisationTrust] ON [OrganisationCode] = SUBSTRING(First_Hospital_Attended,0,4)#(lf)#(lf)  WHERE [CCG] like '11M'#(lf)  #(lf)  and [Derived_Pseudo_NHSNumber] NOT LIKE 'NULL'#(lf)#(lf)  and ([Age_Bracket] like '65-69 Years Old'#(lf)  or [Age_Bracket] like '70-74 Years Old'#(lf)  or [Age_Bracket] like '75-79 Years Old'#(lf)  or [Age_Bracket] like '80-84 Years Old'#(lf)  or [Age_Bracket] like '85-89 Years Old'#(lf)  or [Age_Bracket] like '90-94 Years Old'#(lf)  or [Age_Bracket] like '95-99 Years Old'#(lf)  or [Age_Bracket] like '100 Years Old Or Over')#(lf)#(lf)  and [Symptom_Group_Chief_Complaint] like '%Fall%'#(lf)#(lf)and [Outcome] not like 'In Progress'#(lf)#(lf)#(lf)order by [hour_of_incident] asc"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"counter", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"counter", "number_of_calls"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"hour_of_incident", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"number_of_calls", "Number of Calls"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

