table 'Rapid Response'
	lineageTag: dd101c09-ac68-4888-9d85-d20c4af79d08

	measure 'RR Rate per 1000 Monthly' = ```
			
			
			VAR RR = CALCULATE ( SUM ('Rapid Response'[Care Home Rapid Response] ))
			VAR POP = [Care Home Population Per Month] 
			
			RETURN (RR/POP*1000)
			```
		lineageTag: ba2705d6-57ae-4247-9f80-9dbdb25c42f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RR Rate per 1000 Yearly' =
			
			
			VAR RR = CALCULATE ( SUM ('Rapid Response'[Care Home Rapid Response] ))
			VAR POP = CALCULATE ( [Care Home Population Per Month]  , ALLEXCEPT ('date table', 'date table'[financial_year] ), 'date table'[month_name] IN {"Apr"} )
			RETURN (RR/POP*1000)
		lineageTag: 35c31141-8d69-4363-b470-f6a886876c20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current FY top 3 RR codes' =
			
			CALCULATE (
			SUM ( 'Rapid Response'[Care Home Rapid Response] ),
			ALLEXCEPT ( 'Rapid Response', 'Rapid Response'[PrimaryReferralReasonDescription] ),
			'Rapid Response'[Rapid response year adjusted] = 'Rapid Response'[Rapid response current year]
			)
		formatString: 0
		lineageTag: 8f0e5041-d171-477c-9b58-3379b089d24d

	measure 'Last FY top 3 RR codes' = ```
			
			CALCULATE (
			SUM ( 'Rapid Response'[Care Home Rapid Response] ),
			ALLEXCEPT ( 'Rapid Response', 'Rapid Response'[PrimaryReferralReasonDescription] ),
			'Rapid Response'[Rapid response year adjusted] = 'Rapid Response'[Rapid response previous year], 'Rapid Response'[Rapid response YTD] = "Year to Date"
			)
			
			```
		formatString: 0
		lineageTag: c2e3d658-2980-4a35-bf60-6b6248527a6e

	measure 'CY Reasons RR Rate per 1000 Yearly' =
			
			
			VAR SWAST = [Current FY top 3 RR codes]
			VAR POP = CALCULATE ( [Care Home Population Per Month]  , ALLEXCEPT ('date table', 'date table'[financial_year] ), 'Rapid Response'[Rapid response year adjusted] = 'Rapid Response'[Rapid response current year], 'date table'[month_name] IN {"Apr"} )
			
			
			RETURN (SWAST/POP*1000)
		lineageTag: cdb3ff64-439e-4ac7-9a6f-f85fffe3df85

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Reasons RR Rate per 1000 Yearly' =
			
			
			VAR SWAST = [Last FY top 3 RR codes]
			VAR POP = CALCULATE ( [Care Home Population Per Month] , ALLEXCEPT ('date table', 'date table'[financial_year] ), 'Rapid Response'[Rapid response year adjusted] = 'Rapid Response'[Rapid response previous year], 'Rapid Response'[Rapid response YTD] = "Year to Date", 'date table'[month_name] IN {"Apr"} )
			
			
			RETURN (SWAST/POP*1000)
		lineageTag: dfb906d4-3839-46d3-926b-fea98788ee67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of rapid response from CH patients' = IFERROR(CALCULATE(sum('Rapid Response'[Care Home Rapid Response])/sum('Rapid Response'[Counter])), blank())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e9795a22-a26f-4b46-a720-1793d1e6f755

	measure 'Rapid Response activity y-axis' = ```
			
			
			VAR  rate_or_actual = 
			    if(SELECTEDVALUE('Actual or Rate'[Actual or Rate]) = "Actual Activity", "Actual"
			    ,if(SELECTEDVALUE('Actual or Rate'[Actual or Rate]) = "Rate per 1000", "Rate"))
			
			
			VAR x_axis =
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Month or Year Parameter', 'Month or Year Parameter'[Month or Year Parameter], 'Month or Year Parameter'[Month or Year Parameter Fields] ),
			        'Month or Year Parameter'[Month or Year Parameter])
			
			RETURN  if(rate_or_actual = "Rate" && x_axis = "Yearly", 'Rapid Response'[RR Rate per 1000 Yearly]
			
			        ,if(rate_or_actual = "Rate" && x_axis = "Monthly", 'Rapid Response'[RR Rate per 1000 Monthly]
			        
			        ,if(rate_or_actual = "Actual", CALCULATE(sum('Rapid Response'[Care Home Rapid Response])))))
			```
		lineageTag: e3c21465-b303-4e64-bffb-efd79ca161ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RR activity title' = ```
			
			
			VAR  rate_or_actual = 
			    if(SELECTEDVALUE('Actual or Rate'[Actual or Rate]) = "Actual Activity", "Actual"
			    ,if(SELECTEDVALUE('Actual or Rate'[Actual or Rate]) = "Rate per 1000", "Rate"))
			
			
			VAR x_axis =
			    SELECTCOLUMNS (
			        SUMMARIZE ( 'Month or Year Parameter', 'Month or Year Parameter'[Month or Year Parameter], 'Month or Year Parameter'[Month or Year Parameter Fields] ),
			        'Month or Year Parameter'[Month or Year Parameter])
			
			RETURN  if(rate_or_actual = "Rate", "Rapid Response Referrals for Care Home Residents - Rate per 1000"
			        ,if(rate_or_actual = "Actual", "Rapid Response Referrals for Care Home Residents - Actual Number of Calls"))
			```
		lineageTag: 3adcccf1-3cf9-4ad6-aebc-e35f060c0ca7

	column ServiceRequestID
		dataType: string
		lineageTag: 0eaed3ef-c98b-4a0f-84a3-92346b08b3fa
		summarizeBy: none
		sourceColumn: ServiceRequestID

		annotation SummarizationSetBy = Automatic

	column ReferralRequestReceivedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: c3614206-1804-4f11-a1f7-2861fa3857b4
		summarizeBy: none
		sourceColumn: ReferralRequestReceivedDate

		annotation SummarizationSetBy = Automatic

	column SourceOfReferralDescription
		dataType: string
		lineageTag: ba94cbf6-1416-46f9-81aa-df819a4886de
		summarizeBy: none
		sourceColumn: SourceOfReferralDescription

		annotation SummarizationSetBy = Automatic

	column OrgIDReferring
		dataType: string
		lineageTag: eadc165d-15b6-424c-820d-bb5603c813fa
		summarizeBy: none
		sourceColumn: OrgIDReferring

		annotation SummarizationSetBy = Automatic

	column ReferringStaffGroupDescription
		dataType: string
		lineageTag: 6b42fe71-850f-4745-85d5-4917c0874bdf
		summarizeBy: none
		sourceColumn: ReferringStaffGroupDescription

		annotation SummarizationSetBy = Automatic

	column PriorityTypeDescription
		dataType: string
		lineageTag: 82b22602-ac14-48e9-92c2-a7eada6e5769
		summarizeBy: none
		sourceColumn: PriorityTypeDescription

		annotation SummarizationSetBy = Automatic

	column PrimaryReferralReasonDescription
		dataType: string
		lineageTag: 947ba59c-8b42-438f-bb35-ea8842643be4
		summarizeBy: none
		sourceColumn: PrimaryReferralReasonDescription

		annotation SummarizationSetBy = Automatic

	column DischargeDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5039a528-0cf6-40fc-9c27-13b756049168
		summarizeBy: none
		sourceColumn: DischargeDate

		variation Variation
			isDefault
			relationship: 78ec59f7-a8c3-4e5d-86e2-6819c71a8cc6
			defaultHierarchy: LocalDateTable_9d3cd193-07b2-4270-bd7e-ef1509d7e59e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column OrgIDProviderDescription
		dataType: string
		lineageTag: c9e6496c-ab57-44c2-b65a-45ce14906956
		summarizeBy: none
		sourceColumn: OrgIDProviderDescription

		annotation SummarizationSetBy = Automatic

	column UniqueServiceRequestID
		dataType: string
		lineageTag: d906c8c4-b40a-4185-ac97-1bd29a005232
		summarizeBy: none
		sourceColumn: UniqueServiceRequestID

		annotation SummarizationSetBy = Automatic

	column AgeYrReferralReceivedDate
		dataType: string
		lineageTag: 5d07f708-72c7-40c3-b9a4-bddad923a107
		summarizeBy: none
		sourceColumn: AgeYrReferralReceivedDate

		annotation SummarizationSetBy = Automatic

	column DerivedPseudoNHS
		dataType: string
		lineageTag: f28f9bf7-ee7b-433b-9a37-871b2c68d31d
		summarizeBy: none
		sourceColumn: DerivedPseudoNHS

		annotation SummarizationSetBy = Automatic

	column TeamTypeDescription
		dataType: string
		lineageTag: 18b63576-1dee-4597-88e6-717c9ecb0600
		summarizeBy: none
		sourceColumn: TeamTypeDescription

		annotation SummarizationSetBy = Automatic

	column ReferralClosureReasonDescription
		dataType: string
		lineageTag: dea8e091-4563-461c-9a49-246378c164a2
		summarizeBy: none
		sourceColumn: ReferralClosureReasonDescription

		annotation SummarizationSetBy = Automatic

	column ReferralRejectionReasonDescription
		dataType: string
		lineageTag: 2ff95b05-a97d-4f15-b904-0257bafea235
		summarizeBy: none
		sourceColumn: ReferralRejectionReasonDescription

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: da4bce96-4952-4193-97e6-db36cde8c4ff
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: string
		lineageTag: 55f85078-a4ea-4aa8-865c-de6c6fae8815
		summarizeBy: none
		sourceColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c3e299a8-cf37-4b68-9b56-ecf64042e4b5
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: 684d506f-4128-4da1-a735-cdca483dc1f2
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Service
		dataType: string
		lineageTag: f1bbbf2e-04bf-4454-a1de-eb40a2e94fa0
		summarizeBy: none
		sourceColumn: Service

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: 77c13f27-dd66-4410-9b56-9b6e6028f13b
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column 'Care Home Rapid Response'
		dataType: int64
		formatString: 0
		lineageTag: 0c718baf-4bba-4b53-98e6-6bd1878b3b3d
		summarizeBy: sum
		sourceColumn: Care Home Rapid Response

		annotation SummarizationSetBy = Automatic

	column Pseudo_NHS_Number
		dataType: string
		lineageTag: 1f6fff55-8215-4eab-9d74-3a49ab37e559
		summarizeBy: none
		sourceColumn: Pseudo_NHS_Number

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 1bbc4d62-fb62-478a-a9ba-0805501d0d17
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column 'Rapid response max financial month' = ```
			
			VAR currmonth = MONTH(MAX('Rapid Response'[ReferralRequestReceivedDate]))
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: bd98a765-33bd-41cb-9f8b-33ab8082c462
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Rapid response financial month' = ```
			
			VAR currmonth = MONTH('Rapid Response'[ReferralRequestReceivedDate]
			)
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 767e400b-c56b-4270-8fc2-3789bf32ea19
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Rapid response YTD' = ```
			if('Rapid Response'[Rapid response financial month] <= 'Rapid Response'[Rapid response max financial month], "Year to Date", "Not Year to Date")
			
			```
		lineageTag: 807d4198-21e9-4b51-89e0-a0e96863f474
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Rapid response current year' = ```
			
			VAR max_year = YEAR(MAX('Rapid Response'[ReferralRequestReceivedDate]
			))
			VAR max_month = MONTH(MAX('Rapid Response'[ReferralRequestReceivedDate]
			))
			VAR financial_month = SWITCH(TRUE(),
			max_month = 4, 1,
			max_month = 5, 2,
			max_month = 6, 3,
			max_month = 7, 4,
			max_month = 8, 5,
			max_month = 9, 6,
			max_month = 10, 7,
			max_month = 11, 8,
			max_month = 12, 9,
			max_month = 1, 10,
			max_month = 2, 11,
			max_month = 3, 12
			)
			VAR adjust_year = SWITCH(TRUE(),
			max_month = 1, max_year - 1,
			max_month = 2, max_year - 1,
			max_month = 3, max_year - 1,
			max_month = 4, max_year,
			max_month = 5, max_year,
			max_month = 6, max_year,
			max_month = 7, max_year,
			max_month = 8, max_year,
			max_month = 9, max_year,
			max_month = 10, max_year,
			max_month = 11, max_year,
			max_month = 12, max_year
			)
			return adjust_year
			
			```
		formatString: 0
		lineageTag: 77229f85-8ce6-4fa4-b351-a935a9b7ecc4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Rapid response year adjusted' = ```
			if(
			    'Rapid Response'[Rapid response financial month] = 10, YEAR('Rapid Response'[ReferralRequestReceivedDate]) -1, 
			    if('Rapid Response'[Rapid response financial month] = 11, YEAR('Rapid Response'[ReferralRequestReceivedDate]) -1, 
			    if('Rapid Response'[Rapid response financial month]= 12, YEAR('Rapid Response'[ReferralRequestReceivedDate]) -1, year('Rapid Response'[ReferralRequestReceivedDate]))))
			
			```
		formatString: 0
		lineageTag: 3ada9122-1c82-43a6-8743-974948618bd5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Rapid response previous year' = ```
			'Rapid Response'[Rapid response current year] - 1
			
			```
		formatString: 0
		lineageTag: 7e0c1b39-9b41-41e6-a975-6ac52e60c980
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Care_home_status
		dataType: string
		lineageTag: 8d81a70a-974d-436f-aacb-76209f717cc2
		summarizeBy: none
		sourceColumn: Care_home_status

		annotation SummarizationSetBy = Automatic

	partition 'Rapid Response' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="#(lf)SET ANSI_WARNINGS OFF#(lf)SET NOCOUNT ON#(lf)if object_id ('tempdb..#Care_Home') is not null drop table #Care_Home#(lf)#(lf)SELECT DISTINCT#(lf) #(lf)#(tab)Derived_Pseudo_NHSNumber#(lf)    #(tab)  ,[Date_of_incident] = min([Time_Of_Incident]) #(lf)#(lf)#(tab)  INTO #Care_Home#(lf)#(lf)  FROM [CCG_Current].[SWASFT].[vw_AmbulanceServicePatient] [A]#(lf)#(lf)  LEFT JOIN bireports.dbo.Care_Home_Mapping_May23 [CH] ON [CH].[SWASFT Name] = [A].[Residential_or_Nursing_home_Location_Name]#(lf)   #(lf)  where #(lf)  #(lf)   [Residential_or_Nursing_home_Location] not like 'null'#(lf)#(lf)  and Derived_Pseudo_NHSNumber not like 'Null'#(lf)#(lf)  and [Broad Type (confirmed)] not like 'NULL'#(lf)#(lf)  GROUP BY#(lf)  Derived_Pseudo_NHSNumber#(lf)  #(lf)  order by [Date_of_incident]#(lf)#(lf)IF OBJECT_ID ('TEMPDB..#table1') IS NOT NULL DROP TABLE #table1#(lf)#(lf)SELECT distinct R.ServiceRequestID#(lf),ReferralRequestReceivedDate#(lf),SourceOfReferralDescription#(lf),OrgIDReferring#(lf),ReferringStaffGroupDescription#(lf),PriorityTypeDescription#(lf),PrimaryReferralReasonDescription#(lf),DischargeDate#(lf),OrgIDProviderDescription#(lf),UniqueServiceRequestID#(lf),AgeYrReferralReceivedDate#(lf),DerivedPseudoNHS#(lf),TeamTypeDescription#(lf),ReferralClosureReasonDescription#(lf),ReferralRejectionReasonDescription#(lf)#(tab),d.FinancialYear#(lf)#(tab),d.FinancialMonth#(lf)#(tab),d.MonthName#(lf)#(tab),h.Team#(lf)#(tab),h.Service#(lf)#(tab),[Counter] = 1#(lf)#(tab),[Care_home_patient_flag] = case when ReferralRequestReceivedDate between [P].[Care_home_date] and end_date then 1 else 0 END#(lf)#(tab),p.[Pseudo_NHS_Number]#(lf)#(tab),Care_home_status = case when [Date_of_incident] <= cast(ReferralRequestReceivedDate as date) then [CH_C].[Broad Type (confirmed)]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) when [Date_of_incident] > cast(ReferralRequestReceivedDate as date) then 'Unknown care home type'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) when cast(ReferralRequestReceivedDate as date) between [P].[Care_home_date] and [end_date] and [Date_of_incident] IS NULL THEN 'Unknown care home type'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) ELSE NULL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) END#(lf)#(lf)#(tab)#(lf)#(tab),[rank] = RANK() OVER   #(lf)    (PARTITION BY UniqueServiceRequestID ORDER BY case when ReferralRequestReceivedDate between [P].[Care_home_date] and [End_date] then 1 else 0 END DESC)#(lf)#(lf)#(lf)#(tab)  into #table1#(lf)#(tab)  FROM [CCG_Current].[CSDS].[vw_301_Referral] as r#(lf) #(lf)#(tab)  left join CCG_Reference.Reference.vw_DateLookup as d on d.Date = r.ReferralRequestReceivedDate#(lf)#(tab)  left join CCG_Reference.GHC.vw_Hierarchy as h on r.Current_CostCentre = H.Cost_Centre#(lf)#(tab)  LEFT JOIN [PowerBI_Reporting].[dbo].[Care_Home_Patients_PC_Data_v4] [P] ON P.[Pseudo_NHS_Number] = [r].DerivedPseudoNHS#(lf)#(lf)#(tab)  LEFT JOIN #Care_Home [CH_A] ON [CH_A].[Derived_Pseudo_NHSNumber] = [R].[DerivedPseudoNHS]#(lf)#(tab)  LEFT JOIN [CCG_Current].[SWASFT].[vw_AmbulanceServicePatient] [CH_B] on [CH_B].Time_Of_Incident =  [CH_A].Date_of_incident and [CH_B].Derived_Pseudo_NHSNumber = [CH_A].Derived_Pseudo_NHSNumber#(lf)#(tab)  LEFT JOIN bireports.dbo.Care_Home_Mapping_May23 [CH_C] ON [CH_C].[SWASFT Name] = [CH_B].[Residential_or_Nursing_home_Location_Name]#(lf)#(lf)#(lf)#(tab)  where OrgIDProvider in ('R1J','RTQ')#(lf)#(lf)#(lf)#(tab)  and r.ReferralRequestReceivedDate between '20220401' and EOMONTH(DATEADD(MONTH, -1, GETDATE()))#(lf)#(tab)#(lf)#(lf)#(tab)  and h.Cost_Centre in ('G15503', --Rapid Response#(lf)#(tab)  'G15503a', --Rapid Response - RR - ENDNS#(lf)#(tab) 'G15503b')--Rapid Response - RR - District Nursing#(lf)#(tab)#(tab)#(lf)#(tab) #(lf)#(tab)#(tab)select#(lf)#(tab)#(tab)*#(lf)#(tab)#(tab)from #table1#(lf)#(tab)#(tab)where [rank] = 1"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Care_home_patient_flag", "Care Home Rapid Response"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

