table 'FY Order 2'
	lineageTag: eecbcd5b-ffca-4ea0-966e-2e3ab4b508f2

	column 'Financial Year'
		dataType: string
		lineageTag: 993ff6e8-4364-47f9-88f2-22d2c8dc500d
		summarizeBy: none
		sourceColumn: Financial Year
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 8aac92a0-928e-4cf8-9e4c-eef6dcf8bbc6
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'FY Order 2-da6b7b85-d97a-495e-b2b5-e8d329ac69fb' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("NcexDcAwCATAXagtPbzBUWax2H+NfAquu3uNHi/otiys1386GDrnAVLfc4Jbz/kGU695gqWfeYFHf6z7Aw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Financial Year" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Financial Year", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

