table 'SWAST 5 Year Age Band'
	lineageTag: fa7dbcf9-8bcb-40fc-844e-0e4752f5cec5

	column Column1
		dataType: string
		lineageTag: 14d3960a-2115-4d5d-a910-4db699491025
		summarizeBy: none
		sourceColumn: Column1
		sortByColumn: Column2

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: int64
		formatString: 0
		lineageTag: cb3e7891-af87-4fa1-b995-cc84fd67700f
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition 'SWAST 5 Year Age Band-d069729f-55b3-4787-979b-cb62f5db7775' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VcoxCsAgDEDRq0hmA7E1ak7hXMShULdCwULP36JDyfr+LwUckdna3m+Tz8Nc3eSndbDgoNoCwijy98+X6YTila/DE2PSv59OmPTPwyNj1H+YThj1H4cHxqD/BLW+", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

