table '02 Admission Date Table'
	lineageTag: 706637ee-ba2a-4782-bd67-b3ea339d5b77

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: b436d5c3-831c-40ed-aea0-7d39efebad60
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7d7eb3a4-53a9-4355-b05a-6a04fbf36bc9
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: e55c3dfe-f360-4f79-99ba-3252d8f0d565
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 83332ca5-452a-41ca-aaf1-8cd0142757f7
		summarizeBy: none
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 7b06d3a4-6966-4d51-a726-a6ef46f6b9d3
		summarizeBy: none
		sourceColumn: weekday_name
		sortByColumn: weekday

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: b117bcd7-95fe-488d-9856-72462484ae82
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 88caef0b-d408-42f7-bd39-ee94e02e9e77
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 14f68d73-cea6-4125-b539-5e30d9578f9c
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 51916268-92f4-46b2-8fc1-fbb449affa97
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 70340688-3529-4c37-afd8-b39970769db4
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: af8b899d-b58b-4d3e-8d6e-241d0f6ac21a
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: c44e18e0-e377-4f38-b61f-1b5856a231b2
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: 08ef89b7-83d9-4e1c-94c9-58795a5302b5
		summarizeBy: none
		sourceColumn: is_working_day

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 030e251f-0b79-426c-a591-dbf4148e93ec
		summarizeBy: none
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 55e39093-a48f-437f-9380-f9a0e96f90b6
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: b4c9ad79-d169-472c-a990-aae191eb2d85
		summarizeBy: none
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: 79f434c5-fc90-42e1-8caf-79a222c6a182
		summarizeBy: none
		sourceColumn: day_of_quarter

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7dcd60ed-12ff-432a-a821-66d8158a1a9c
		summarizeBy: none
		sourceColumn: quarter_start_date

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d6c07e77-5bfc-4996-b752-c6facdbc5565
		summarizeBy: none
		sourceColumn: quarter_end_date

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: d287f95a-414f-40ef-9f3f-0573f3c10751
		summarizeBy: none
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 7bceedc2-2db4-4337-904c-be5f46e4a097
		summarizeBy: none
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 0eec55b5-0a44-4823-a4d9-b95a99b64b61
		summarizeBy: none
		sourceColumn: month_year_name

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column month_year
		dataType: string
		lineageTag: 54eabbcb-966b-41ff-9ab4-017152cdc2cf
		summarizeBy: none
		sourceColumn: month_year

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 7fab9315-ac00-404d-a61c-3bb8e918c750
		summarizeBy: none
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 3adf1ea1-95e2-4c88-923c-4974696635f8
		summarizeBy: none
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 9a790a0e-d38e-4155-b91d-2d3b80a23c3e
		summarizeBy: none
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 6a90dcb0-c7d1-4f72-a29f-a3369621a6c9
		summarizeBy: none
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 9f3d8569-41c4-44d7-b825-b2cbe8bea859
		summarizeBy: none
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: 7b969404-850b-4136-aca4-1111e927ec1f
		summarizeBy: none
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	column Adm_Week_Ending_Sunday = ```
			
			VAR _CURRENT = '02 Admission Date Table'[date]
			RETURN 
			    _CURRENT + (7 - weekday(_CURRENT, 2) ) 
			```
		formatString: Long Date
		lineageTag: a2a3b1fa-5094-419c-afc3-d284a10fc9e2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Last_Updated_Date
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 076dd6d8-3f74-4ea9-a14f-337cf6482d0a
		summarizeBy: none
		sourceColumn: Last_Updated_Date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	hierarchy 'day_month_year Hierarchy'
		lineageTag: a551ddd6-b674-42cf-b810-855b9886cfbc

		level Date
			lineageTag: de563a65-6450-486b-b3a8-afa8806b752d
			column: day_month_year

		level 'Week Ending'
			lineageTag: 14f8ad0b-d246-4935-ac65-bdcbe8e40716
			column: Adm_Week_Ending_Sunday

		level 'Month Year'
			lineageTag: 3e8a4651-e465-4c5f-a881-9576d3f12d74
			column: month_year_name

	partition '02 Admission Date Table' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select date, day_month_year, day, weekday, weekday_name, month, month_name, quarter, year_month, is_weekend, is_holiday, holiday_description, is_working_day, financial_week_of_year, financial_year, financial_quarter, day_of_quarter, quarter_start_date, quarter_end_date, month_day_no, financial_month, month_year_name, month_year, ytd_flag, latest_month_flag, previous_month_flag, latest_12_months_flag, latest_6_months_flag, previous_12_months_flag, same_month_last_year_flag, last_update as ""Last_Updated_Date"" from ccg_reference.vw_date", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

