table '05 Hospital @ Home'
	lineageTag: 749ce3c2-c895-47d8-8a7b-01a9165c8aee

	measure 'Full Week Flag' = ```
			
			VAR ThisWeek = SELECTEDVALUE('05 Hospital @ Home'[Week_Ending_Sunday])
			VAR NumDays = 
			    CALCULATE(
			        DISTINCTCOUNT('05 Hospital @ Home'[ContactDate]),  -- or AdmissionDate if that’s more accurate
			        '05 Hospital @ Home'[Week_Ending_Sunday]= ThisWeek
			    )
			RETURN IF(NumDays = 7, 1, 0)
			```
		formatString: 0
		lineageTag: 58512fa1-fbcb-4c22-b212-47255d9b196e

	measure 'H@H LATEST WEEK' = CALCULATE(SUM('05 Hospital @ Home'[Counter]), '05 Hospital @ Home'[Latest_Full_Week_flag] = 1) +0
		formatString: 0
		lineageTag: 441fb2aa-1c7f-4f11-bc12-a9a8ace07803

	measure 'H@H PREVIOUS WEEK' = CALCULATE(SUM('05 Hospital @ Home'[Counter]), '05 Hospital @ Home'[Previous_Full_Week_Flag] = 1) +0
		formatString: 0
		lineageTag: 6e1727da-2974-4758-aaaf-528adbb8154a

	measure 'H@H LATEST 4WEEK' = (CALCULATE(SUM('05 Hospital @ Home'[Counter]), '05 Hospital @ Home'[Latest_4Full_Week_flag] = 1) /4) +0
		formatString: 0
		lineageTag: 3e85607e-ea8b-4627-8a96-9d386abddeb2

	measure 'H@H PREVIOUS 4WEEK' = (CALCULATE(SUM('05 Hospital @ Home'[Counter]), '05 Hospital @ Home'[Previous_4Full_Week_flag] = 1) /4)+0
		formatString: 0
		lineageTag: 654c7dbf-ef28-4dbf-919c-292f5c24e12a

	measure Latest_Full_Week_Date_hah = ```
			
			VAR _week = CALCULATE(MAX('05 Hospital @ Home'[Week_Ending_Sunday]), 
			FILTER('05 Hospital @ Home', '05 Hospital @ Home'[Is_Complete_Latest_Week_Flag] = 1) ) 
			
			RETURN 
			FORMAT(_week, "dd mmmm yyyy")
			```
		lineageTag: a6e80fd2-b4b3-47a9-abd7-35c82e942362

	column UniqueServiceRequestID
		dataType: string
		lineageTag: c9f39ec4-860c-4d0f-86dd-7001c94710dc
		summarizeBy: none
		sourceColumn: UniqueServiceRequestID

		annotation SummarizationSetBy = Automatic

	column Visitcount
		dataType: int64
		formatString: 0
		lineageTag: 48044975-8a2b-47d3-a97e-51b0e4861c58
		summarizeBy: sum
		sourceColumn: Visitcount

		annotation SummarizationSetBy = Automatic

	column UniqueCareContactID
		dataType: string
		lineageTag: 634ad240-c294-4e8d-82b0-b816c4179e76
		summarizeBy: none
		sourceColumn: UniqueCareContactID

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: da20b36f-3b81-4fb6-82af-b4d98fa8ee72
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column OrgIDCommissioner
		dataType: string
		lineageTag: e0789ea1-13db-423b-ab8d-58ea3db0c706
		summarizeBy: none
		sourceColumn: OrgIDCommissioner

		annotation SummarizationSetBy = Automatic

	column OrgIDCommissionerDescription
		dataType: string
		lineageTag: 3685195c-c2cb-4da2-ae14-e5cbb9aee5ff
		summarizeBy: none
		sourceColumn: OrgIDCommissionerDescription

		annotation SummarizationSetBy = Automatic

	column OrgIDProvider
		dataType: string
		lineageTag: 83f1b840-9575-4313-a05c-4b818e729410
		summarizeBy: none
		sourceColumn: OrgIDProvider

		annotation SummarizationSetBy = Automatic

	column OrgIDProviderDescription
		dataType: string
		lineageTag: ee846f88-6a4f-413c-8423-a3a0f72e1e92
		summarizeBy: none
		sourceColumn: OrgIDProviderDescription

		annotation SummarizationSetBy = Automatic

	column ContactDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc9902be-fd22-4e6a-b558-2d68158303ef
		summarizeBy: none
		sourceColumn: ContactDate

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ContactTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0d82d471-f30b-4e95-86ef-fe7e7fbd33d0
		summarizeBy: none
		sourceColumn: ContactTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column AdminCategory
		dataType: string
		lineageTag: 5fa0689b-21eb-496a-87a5-3bc7ef4f0313
		summarizeBy: none
		sourceColumn: AdminCategory

		annotation SummarizationSetBy = Automatic

	column AdminCategoryDescription
		dataType: string
		lineageTag: 240bc529-74cf-44c7-bb39-4129d9a5eb98
		summarizeBy: none
		sourceColumn: AdminCategoryDescription

		annotation SummarizationSetBy = Automatic

	column CareContactDuration
		dataType: string
		lineageTag: 180f857f-3723-4051-9368-b18f0b92fe99
		summarizeBy: none
		sourceColumn: CareContactDuration

		annotation SummarizationSetBy = Automatic

	column ConsultationType
		dataType: string
		lineageTag: 9289a6c7-5879-4368-99b9-f1661be8d515
		summarizeBy: none
		sourceColumn: ConsultationType

		annotation SummarizationSetBy = Automatic

	column ConsultationTypeDescription
		dataType: string
		lineageTag: 5429f4ed-eded-4e07-a65a-9415b7b8f35e
		summarizeBy: none
		sourceColumn: ConsultationTypeDescription

		annotation SummarizationSetBy = Automatic

	column CareContactSubject
		dataType: string
		lineageTag: ca5ca2d1-6947-4a50-97fb-b80f502ae0bb
		summarizeBy: none
		sourceColumn: CareContactSubject

		annotation SummarizationSetBy = Automatic

	column CareContactSubjectDescription
		dataType: string
		lineageTag: bb55cc97-ccbc-4d01-b133-efe5ec33bc16
		summarizeBy: none
		sourceColumn: CareContactSubjectDescription

		annotation SummarizationSetBy = Automatic

	column ConsultationMediumUsed
		dataType: string
		lineageTag: eea5e3da-a2d3-4b75-ab50-0c354a307401
		summarizeBy: none
		sourceColumn: ConsultationMediumUsed

		annotation SummarizationSetBy = Automatic

	column ConsultationMediumUsedDescription
		dataType: string
		lineageTag: fb51a526-2523-4c38-9201-9c2be1ad7e04
		summarizeBy: none
		sourceColumn: ConsultationMediumUsedDescription

		annotation SummarizationSetBy = Automatic

	column ActivityLocationType
		dataType: string
		lineageTag: 58287a22-d635-4825-811b-72cb4f32cec3
		summarizeBy: none
		sourceColumn: ActivityLocationType

		annotation SummarizationSetBy = Automatic

	column ActivityLocationTypeDescription
		dataType: string
		lineageTag: 330576e0-ce97-46c9-951d-863d3b22999e
		summarizeBy: none
		sourceColumn: ActivityLocationTypeDescription

		annotation SummarizationSetBy = Automatic

	column TreatmentOrgSiteID
		dataType: string
		lineageTag: 8a649439-3d78-4a11-b60c-4220c41f390e
		summarizeBy: none
		sourceColumn: TreatmentOrgSiteID

		annotation SummarizationSetBy = Automatic

	column TreatmentOrgSiteIDDescription
		dataType: string
		lineageTag: 0bb211ec-2498-46be-86a4-009cc952c623
		summarizeBy: none
		sourceColumn: TreatmentOrgSiteIDDescription

		annotation SummarizationSetBy = Automatic

	column ReferralCostCentre
		dataType: string
		lineageTag: 8414cc26-dbfe-410f-91df-08737752d665
		summarizeBy: none
		sourceColumn: ReferralCostCentre

		annotation SummarizationSetBy = Automatic

	column AllCostCentresOnReferral
		dataType: string
		lineageTag: 97b1cc80-dce4-48d7-a879-c939b47355d8
		summarizeBy: none
		sourceColumn: AllCostCentresOnReferral

		annotation SummarizationSetBy = Automatic

	column ReferralRequestReceivedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: e2e78656-8106-4487-a369-d3c17603630b
		summarizeBy: none
		sourceColumn: ReferralRequestReceivedDate

		annotation SummarizationSetBy = Automatic

	column ClinicalContactFlag
		dataType: int64
		formatString: 0
		lineageTag: f2a04657-c6e0-4ce7-bd33-912d9ca9a11e
		summarizeBy: sum
		sourceColumn: ClinicalContactFlag

		annotation SummarizationSetBy = Automatic

	column AttendOrNot
		dataType: string
		lineageTag: 8cf50cf8-42d3-46be-b5be-9086ffafa9b6
		summarizeBy: none
		sourceColumn: AttendOrNot

		annotation SummarizationSetBy = Automatic

	column AttendOrNotDescription
		dataType: string
		lineageTag: ab889c08-2ffd-4455-9669-a3acb04ea10a
		summarizeBy: none
		sourceColumn: AttendOrNotDescription

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 18a9b184-52ed-4baf-aef9-a09e978044b7
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 1c270e76-bc1c-411e-8c29-7e590c44a14d
		summarizeBy: sum
		sourceColumn: FinancialMonth

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 97b811e5-5acc-4220-9ec7-497919930e29
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: FinancialMonth

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: 84cd6045-724a-4df4-80f3-24318d0501c0
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Service
		dataType: string
		lineageTag: 4d91cd24-a4bc-4949-bd3d-480976e98a83
		summarizeBy: none
		sourceColumn: Service

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: 288e2cf4-81c0-4577-8f37-3496005613be
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Latest_Full_Week_flag = ```
			
			VAR MaxFullWeek = 
			    CALCULATE(
			        MAX('05 Hospital @ Home'[Week_Ending_Sunday]),
			        FILTER(
			            '05 Hospital @ Home',
			            '05 Hospital @ Home'[Is_Complete_Latest_Week_Flag] = 1
			        )
			    )
			
			RETURN 
			IF('05 Hospital @ Home'[Week_Ending_Sunday] = MaxFullWeek, 1, 0)
			
			
			```
		formatString: 0
		lineageTag: b0e39c1d-28a1-4654-85d1-6ef2311c2f22
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column AgeBand5yr
		dataType: string
		lineageTag: 46111251-a990-42e6-ba30-a09538df0c80
		summarizeBy: none
		sourceColumn: AgeBand5yr

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: bac2c35a-4dd7-4573-bab3-9ab848726e82
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column LocalityName
		dataType: string
		lineageTag: d656106f-ac63-454f-b291-b5d5d5b4a377
		summarizeBy: none
		sourceColumn: LocalityName

		annotation SummarizationSetBy = Automatic

	column EthnicOriginDescription
		dataType: string
		lineageTag: df9bdb75-1bd1-445f-8790-9faec4c0e7fc
		summarizeBy: none
		sourceColumn: EthnicOriginDescription

		annotation SummarizationSetBy = Automatic

	column RuralUrbanClass
		dataType: string
		lineageTag: e1755c9f-7f10-4e69-ab74-7a16f3c16d4d
		summarizeBy: none
		sourceColumn: RuralUrbanClass

		annotation SummarizationSetBy = Automatic

	column eFI_Catgory_derived
		dataType: string
		lineageTag: 73041cd0-809a-40b2-a8f3-bb2233973364
		summarizeBy: none
		sourceColumn: eFI_Catgory_derived

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 7296e61e-89ab-4710-9b6c-de6f25eeef1d
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column ContactHour = ```
			HOUR('05 Hospital @ Home'[ContactTime]) 
			```
		formatString: 0
		lineageTag: 58bed96e-58fe-4a80-b9f1-ba9655d49034
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SeenorNotSeen
		dataType: string
		lineageTag: 9f797957-5eac-4c31-913e-eaa93c83fb65
		summarizeBy: none
		sourceColumn: SeenorNotSeen

		annotation SummarizationSetBy = Automatic

	column Previous_Full_Week_Flag = ```
			
			VAR LatestFullWeek =
			    CALCULATE(
			        MAX('05 Hospital @ Home'[Week_Ending_Sunday]),
			        FILTER(
			            '05 Hospital @ Home',
			            '05 Hospital @ Home'[Is_Complete_Latest_Week_Flag] = 1
			        )
			    )
			VAR PreviousWeek = LatestFullWeek - 7
			RETURN
			IF('05 Hospital @ Home'[Week_Ending_Sunday] = PreviousWeek, 1, 0)
			
			```
		formatString: 0
		lineageTag: cbda7aeb-77a0-4744-9892-dc90c247d1a8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Latest_4Full_Week_flag = ```
			
			VAR LatestWeek = 
			    CALCULATE(
			        MAX('05 Hospital @ Home'[Week_Ending_Sunday]),
			        '05 Hospital @ Home'[Is_Complete_Latest_Week_Flag] = 1,
			        ALL('05 Hospital @ Home') 
			    )
			VAR PreviousWeek = LatestWeek - 7
			VAR TwoWeeksAgo = LatestWeek - 14
			VAR ThreeWeeksAgo = LatestWeek - 21
			RETURN
			    IF (
			        '05 Hospital @ Home'[Week_Ending_Sunday] IN {LatestWeek, PreviousWeek, TwoWeeksAgo, ThreeWeeksAgo},
			        1,
			        0
			    )
			
			```
		formatString: 0
		lineageTag: eddb0d1f-bf30-46ac-a755-013638bdb0f7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Week_Ending_Sunday
		dataType: dateTime
		formatString: Long Date
		lineageTag: f17249e8-bf60-43c2-825b-2d2c9939f20c
		summarizeBy: none
		sourceColumn: Week_Ending_Sunday

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'LSOA Code'
		dataType: string
		lineageTag: 41b8da97-7f39-42ab-b2df-b8637ba841eb
		summarizeBy: none
		sourceColumn: LSOA Code

		annotation SummarizationSetBy = Automatic

	column Is_Complete_Latest_Week_Flag =
			
			VAR MaxWeek =
			    CALCULATE(
			        MAX('05 Hospital @ Home'[Week_Ending_Sunday]),
			        ALL('05 Hospital @ Home')
			    )
			VAR NumDaysInMaxWeek =
			    CALCULATE(
			        DISTINCTCOUNT('05 Hospital @ Home'[ContactDate]),
			        FILTER(
			            ALL('05 Hospital @ Home'),
			            '05 Hospital @ Home'[Week_Ending_Sunday] = MaxWeek
			        )
			    )
			RETURN
			    IF (
			        '05 Hospital @ Home'[Week_Ending_Sunday] = MaxWeek && NumDaysInMaxWeek < 7,
			        0,
			        1
			    )
		formatString: 0
		lineageTag: 90d1cbdc-9cd5-435b-adc9-9693d5aac35f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Previous_4Full_Week_flag = ```
			
			VAR LatestWeek = 
			    CALCULATE(
			        MAX('05 Hospital @ Home'[Week_Ending_Sunday]),
			        '05 Hospital @ Home'[Is_Complete_Latest_Week_Flag] = 1,
			        ALL('05 Hospital @ Home') 
			    )
			VAR Fourweeksago = LatestWeek - 28
			VAR FiveWeeksAgo = LatestWeek - 35
			VAR SixWeeksAgo = LatestWeek - 42
			VAR SevenWeeksAgo = LatestWeek - 49
			RETURN
			    IF (
			        '05 Hospital @ Home'[Week_Ending_Sunday] IN {Fourweeksago, FiveWeeksAgo, SixWeeksAgo, SevenWeeksAgo},
			        1,
			        0
			    )
			
			```
		formatString: 0
		lineageTag: 89516220-7810-4b35-9aa4-6058126ea6ad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.day_month_year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: de7b85be-b8c5-4eaa-8017-bf1538d83090
		summarizeBy: none
		sourceColumn: Discharge Date Table.day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Discharge Date Table.day'
		dataType: int64
		formatString: 0
		lineageTag: 21cc2206-f6f2-4f9a-b243-23c0a86da45f
		summarizeBy: sum
		sourceColumn: Discharge Date Table.day

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.weekday'
		dataType: int64
		formatString: 0
		lineageTag: 60261e43-bd1c-4587-bc2c-8d3f265cbd8f
		summarizeBy: sum
		sourceColumn: Discharge Date Table.weekday

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.weekday_name'
		dataType: string
		lineageTag: af73d916-ff07-455e-9909-bd38b1f89320
		summarizeBy: none
		sourceColumn: Discharge Date Table.weekday_name

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.month'
		dataType: int64
		formatString: 0
		lineageTag: ea0b52ae-6515-481a-b968-100be5434720
		summarizeBy: sum
		sourceColumn: Discharge Date Table.month

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.month_name'
		dataType: string
		lineageTag: d98c29ba-e17e-41e1-8699-222188ff0615
		summarizeBy: none
		sourceColumn: Discharge Date Table.month_name

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.year_month'
		dataType: int64
		formatString: 0
		lineageTag: 46c2cf41-b62a-4c45-bb5d-6d2c3d83143f
		summarizeBy: sum
		sourceColumn: Discharge Date Table.year_month

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.financial_year'
		dataType: string
		lineageTag: f765d9e1-8bc5-4ce5-9293-499fada4f4dc
		summarizeBy: none
		sourceColumn: Discharge Date Table.financial_year

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.financial_month'
		dataType: int64
		formatString: 0
		lineageTag: 017e3c1d-3654-4789-a395-664750e8f0f5
		summarizeBy: sum
		sourceColumn: Discharge Date Table.financial_month

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.month_year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4e2ecddd-08ec-473d-b277-071e64d342e1
		summarizeBy: none
		sourceColumn: Discharge Date Table.month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Rural_Urban
		dataType: string
		lineageTag: 2025464c-e615-44ec-8471-b122e6b2e0e3
		summarizeBy: none
		sourceColumn: Rural_Urban

		annotation SummarizationSetBy = Automatic

	column Age_at_referral
		dataType: int64
		formatString: 0
		lineageTag: e3ae043d-0a00-4d57-aa0a-e6969dc4b722
		summarizeBy: sum
		sourceColumn: Age_at_referral

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: f3ff4926-d42a-475a-a291-7ded34c14acc
		summarizeBy: none
		sourceColumn: Last_Updated

		annotation SummarizationSetBy = Automatic

	hierarchy 'ContactDate Hierarchy'
		lineageTag: 294d198f-d94b-43be-980a-94f40c229054

		level ContactDate
			lineageTag: 1637ca74-9aa8-424c-9e1f-52be6fd1506c
			column: ContactDate

		level Week_Ending_Sunday
			lineageTag: 64ff96dc-c669-45c5-b64a-6782723f15ce
			column: Week_Ending_Sunday

		level MonthName
			lineageTag: 26be4af2-14f8-4f7b-aaf0-0a3b1573c169
			column: MonthName

	partition '05 Hospital @ Home' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Reporting", [Query="#(lf)SELECT *#(lf)FROM [PowerBI_Reporting].[SecondaryCare].tbl02_Hospital_at_Home"]),
				    #"Merged Queries" = Table.NestedJoin(Source, {"ContactDate"}, #"06 H@H Date Table", {"date"}, "Discharge Date Table", JoinKind.LeftOuter),
				    #"Expanded Discharge Date Table" = Table.ExpandTableColumn(#"Merged Queries", "Discharge Date Table", {"day_month_year", "day", "weekday", "weekday_name", "month", "month_name", "year_month", "financial_year", "financial_month", "month_year"}, {"Discharge Date Table.day_month_year", "Discharge Date Table.day", "Discharge Date Table.weekday", "Discharge Date Table.weekday_name", "Discharge Date Table.month", "Discharge Date Table.month_name", "Discharge Date Table.year_month", "Discharge Date Table.financial_year", "Discharge Date Table.financial_month", "Discharge Date Table.month_year"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Discharge Date Table",null,"Unknown",Replacer.ReplaceValue,{"ConsultationTypeDescription"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"Unknown",Replacer.ReplaceValue,{"ActivityLocationTypeDescription"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value1", "SeenorNotSeen", each if [AttendOrNot] = "5" then "Seen" else if [AttendOrNot] = "6" then "Not Seen" else "Unknown"),
				    #"Replaced Value2" = Table.ReplaceValue(#"Added Conditional Column","Other locations not elsewhere classified","Unknown",Replacer.ReplaceText,{"ActivityLocationTypeDescription"})
				in
				    #"Replaced Value2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

