table '06 H@H Date Table'
	lineageTag: 4c549ef2-7e56-4dca-9449-0782c7e56ca6

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 357d259c-f15e-4790-98f6-641878b540f3
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: f5851792-7461-49b4-84ee-e4312d8f066a
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: b8fbc464-d662-4e7d-a228-d97752896cc2
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 7b88336e-3358-4e12-a926-1d9870800952
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 515338ca-f289-48c3-8e13-bb5327322f4a
		summarizeBy: none
		sourceColumn: weekday_name
		sortByColumn: weekday

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 052394e3-5a7c-4928-a5b7-8c9d85a788f0
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: f4125f41-bb77-4ea4-9d6c-399075074270
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 64e85d95-1993-4342-b424-f893d018da73
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 0e53ec5b-054b-4ca3-b059-b913391e87d5
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 43273ab2-83ff-4555-bb39-7c28cf4c969b
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 2655cbc2-4b69-4735-8979-4cf148cf223c
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: 155b6258-80ca-49da-9e5e-c69062923e1b
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: d39a657d-b3d0-4b9c-8e00-1203c8f5bf94
		summarizeBy: sum
		sourceColumn: is_working_day

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 0ca4a1b8-245b-4b48-9cc6-1cf57517be94
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 878d626c-9989-47aa-8f4b-8de5fa0af279
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 2b234b4b-bdc4-4f36-9c1e-c1fd70f9721b
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: e0a91b1c-8821-41e7-958e-210ab2248aeb
		summarizeBy: sum
		sourceColumn: day_of_quarter

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8a763f60-dc8a-4a7d-81da-5df897c4c2a6
		summarizeBy: none
		sourceColumn: quarter_start_date

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 81afdd98-fbe9-4efb-aa41-9d1ec31672c3
		summarizeBy: none
		sourceColumn: quarter_end_date

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: fd5a6630-d531-4d3f-8d3d-d3fe3f7da586
		summarizeBy: sum
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 1b7f361e-ee81-4817-850d-f60bfa0e05bf
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: aca2ea28-e9d1-4d05-8867-9391153f7e9e
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: e0acd3af-a624-4ec4-9a77-71a17aaa91c8
		summarizeBy: none
		sourceColumn: month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 4b9f980e-9e75-45be-9ade-d5b067e8e1dd
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 76e5c99b-a566-4ce4-9b1c-c74ee00a4df5
		summarizeBy: sum
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: dea04ab1-7a13-4b59-a774-7e0be2c2f0b5
		summarizeBy: sum
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: eb8eb553-c828-4463-b48a-cfa8466e119d
		summarizeBy: sum
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 00ea9d04-4b1a-4311-a047-939ebcae7913
		summarizeBy: sum
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: c78a97ff-3ad3-4223-a067-c5488a3fee3f
		summarizeBy: sum
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	column Discharge_Week_Ending_Sunday = ```
			
			VAR _CURRENT = '06 H@H Date Table'[date]
			RETURN 
			    _CURRENT + (7 - weekday(_CURRENT, 2) ) 
			```
		formatString: dd mmmm yyyy
		lineageTag: 4ad21699-cd1a-4bb8-bb98-c4a135bbcc8b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Week_Ending_Sunday_Disch = ```
			
			VAR _CURRENT = '06 H@H Date Table'[date]
			RETURN 
			    _CURRENT + (7 - weekday(_CURRENT, 2) ) 
			```
		formatString: Long Date
		lineageTag: ae84b699-5c12-43c9-ba8a-faa261023d39
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Latest_week_discharge_flag = ```
			
			IF('06 H@H Date Table'[Week_Ending_Sunday_Disch] = CALCULATE(MAX('06 H@H Date Table'[Week_Ending_Sunday_Disch]), ALL('06 H@H Date Table')), 1,0)
			
			```
		formatString: 0
		lineageTag: 5092188d-d079-4660-80dc-5c7c70ffd3d3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: daaf7b34-584b-4eb1-8dac-53a9f13c6fff
		summarizeBy: none
		sourceColumn: Last_Updated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Data_Up_To
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1646b5e7-7cd6-4bbd-91fe-f6669ce1d169
		summarizeBy: none
		sourceColumn: Data_Up_To

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	hierarchy 'month_year Hierarchy'
		lineageTag: 71ee3816-5f83-47e3-b7f0-65900f0dc306

		level month_year
			lineageTag: 56fa2e97-936b-4687-8507-ba9cde2dd3b4
			column: month_year

		level Discharge_Week_Ending_Sunday
			lineageTag: 40472bee-2b05-46a1-8043-81cc72c0eabd
			column: Discharge_Week_Ending_Sunday

		level day_month_year
			lineageTag: 3f82202f-8b2a-4768-9d25-f31785d5cd7e
			column: day_month_year

	hierarchy 'day_month_year Hierarchy'
		lineageTag: e461d299-4898-4764-9327-bc3d62455db1

		level Date
			lineageTag: 263b65b2-5513-4601-a350-327983d30c3d
			column: day_month_year

		level 'Month Year'
			lineageTag: c1ccb1af-3045-461f-9a51-e378759079ab
			column: month_year

		level 'Week End'
			lineageTag: f0e0ef11-aa30-48fd-8343-9f572745e849
			column: Week_Ending_Sunday_Disch

	partition '06 H@H Date Table' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "SELECT DISTINCT cast(d.full_date as date) as ""date"" ,to_char(d.full_date,'DD/MM/YYYY') as ""day_month_year"" ,d.day_of_fin_year as ""day"" ,d.weekday_no as ""weekday"" ,d.weekday_name as ""weekday_name"" ,d.month_no as ""month"" ,d.month_short_name as ""month_name"" ,d.cal_quarter_no as ""quarter"" ,d.year_month as ""year_month"" ,case when d.weekday_no in (6,7) then 1 else 0 end as ""is_weekend"" ,case when d.bank_holiday_desc is not null then 1 else 0 end as ""is_holiday"" ,d.bank_holiday_desc as ""holiday_description"" ,d.working_day_calc as ""is_working_day"" ,d.fin_week_no as ""financial_week_of_year"" ,replace(d.fin_year_yyyy_dash_yy,' - ','/') as ""financial_year"" ,d.fin_quarter_no as ""financial_quarter"" ,d.day_of_quarter as ""day_of_quarter"" ,cast(d.quarter_start as date) as ""quarter_start_date"" ,cast(d.quarter_start as date) as ""quarter_end_date"" ,d.month_day_no as ""month_day_no"" ,d.fin_month_no as ""financial_month"" ,concat(concat(d.month_short_name,'-'),left(d.date_112,4)) as ""month_year_name"" ,d.monthyear_mmmm_yyyyy as ""month_year"" ,case when d.fin_month_no <= (select cast(fin_month_no as int) from dscro_national_lookups.ref_dates where full_date = last_day(add_months(current_date,-1))) then 1 else 0 end as ""ytd_flag"" ,case when d.year_month in (select max(year_month) from dscro_national_lookups.ref_dates where full_date between '2019-04-01' and last_day(add_months(current_date,-1))) then 1 else 0 end as ""latest_month_flag"" ,case when d.year_month in (select max(year_month) from dscro_national_lookups.ref_dates where full_date between '2019-04-01' and last_day(add_months(current_date,-2))) then 1 else 0 end as ""previous_month_flag"" ,case when d.year_month in (select year_month from dscro_national_lookups.ref_dates where full_date between last_day(add_months(current_date,-12)) and last_day(add_months(current_date,-1))) then 1 else 0 end as ""latest_12_months_flag"" ,case when d.year_month in (select year_month from dscro_national_lookups.ref_dates where full_date between last_day(add_months(current_date,-24)) and last_day(add_months(current_date,-13))) then 1 else 0 end as ""previous_12_months_flag"" ,case when d.year_month in (select max(year_month) from dscro_national_lookups.ref_dates where full_date between '2019-04-01' and last_day(add_months(current_date,-13))) then 1 else 0 end as ""same_month_last_year_flag"" ,last_day(add_months(current_date,-2)) as ""Data_Up_To"" ,getdate() as ""Last_Updated"" FROM dscro_national_lookups.ref_dates d WHERE cast(d.full_date as date) between '2023-04-01' and last_day(add_months(current_date,-2))", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"month_year", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

