table '09 Readmissions Date Table'
	lineageTag: cc9f4e2c-d819-4470-84c5-71b73b8a8fa1

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: b75f5a48-4038-4989-8d21-94fbc6ba6cba
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d9ae24b-eb5f-42a6-94d4-0f93b500beb0
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: 83600c7d-4473-4573-97f3-1dd3ac92d958
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 62bcb5c9-3fa7-45e3-997c-aaf9b2d0bde9
		summarizeBy: none
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 2b5b1ed3-ed6c-4b53-8f4a-eed4a9790aab
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 52016233-eed2-40c7-b9c2-08181677d775
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 9736fe94-3a2b-4fba-9a05-226103b99b0c
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: faef3311-83ad-4416-b558-16c9a5da96ee
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 8bfc5b59-ba04-4859-90ac-997c4f16679e
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: e77cf818-b05f-405a-a50e-7ac39c99d29d
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: de49c1fc-1836-45ae-8a0e-22144e86875d
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: 774b6f33-f2fc-4b3e-bb08-5b5a1cb11b38
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: d5419f74-6f6e-4221-9369-f7dd69548995
		summarizeBy: none
		sourceColumn: is_working_day

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: f7986e16-8613-41b7-a7ae-01d4e7707eac
		summarizeBy: none
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 96bdd5d7-d6b8-4fb0-8814-f7793c14ee54
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: d36ee953-1680-4bae-86f2-5b36d75770db
		summarizeBy: none
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: f05465b1-1c8d-4d89-8025-088ff50c013c
		summarizeBy: none
		sourceColumn: day_of_quarter

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 665df3c4-d287-444d-ad7c-b44d82c23046
		summarizeBy: none
		sourceColumn: quarter_start_date

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 309139bc-c646-41fc-84ec-ce0f716e24b0
		summarizeBy: none
		sourceColumn: quarter_end_date

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: b78cd8dd-5a38-474f-a50a-f6652781cb98
		summarizeBy: none
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: c74d8d62-1864-4653-b1d1-ce9eb97c8d21
		summarizeBy: none
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: b1107d9f-df9e-420d-b8db-d21d8f37720d
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: string
		lineageTag: 7c4123ea-5a1e-47b5-8f75-c60bdb9d163b
		summarizeBy: none
		sourceColumn: month_year

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 6566ec32-6eaf-4fb8-8771-864580c4cab3
		summarizeBy: none
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: b6c1603c-a8f5-4e91-a0ee-6b1981f92a05
		summarizeBy: none
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 56f673dd-04d7-4fe4-b282-f3b92ae24a00
		summarizeBy: none
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 01b9a30e-9b89-48f5-8c36-a91127a1b00c
		summarizeBy: none
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 9b343b0e-405e-45df-848f-1245f682dc57
		summarizeBy: none
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: 01b30f87-1313-4364-b24d-5c2400d06a37
		summarizeBy: none
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	partition '09 Readmissions Date Table' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select date, day_month_year, day, weekday, weekday_name, month, month_name, quarter, year_month, is_weekend, is_holiday, holiday_description, is_working_day, financial_week_of_year, financial_year, financial_quarter, day_of_quarter, quarter_start_date, quarter_end_date, month_day_no, financial_month, month_year_name, month_year, ytd_flag, latest_month_flag, previous_month_flag, latest_12_months_flag, latest_6_months_flag, previous_12_months_flag, same_month_last_year_flag, last_update as ""Last_Updated_Date"" from ccg_reference.vw_date", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

