table Table
	lineageTag: b1f34b2f-04b6-406a-8ef7-3359ff0bf677

	column Column1
		dataType: string
		lineageTag: 2a0c8598-43d3-449f-9861-1191d0de9e4c
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: int64
		formatString: 0
		lineageTag: 7b854c26-6a1e-43c7-b58d-75721186d96e
		summarizeBy: sum
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Hcy5EYAwDATAXi5WAOZ1aLD5WtCo/zZ8XLbRuqPAMCLMcVBJOqlJqtQsNWqRLmqVbmqTHmqXXipL3z8PiOg=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

