table Diagnostic
	lineageTag: 0f468cc6-1ad3-434d-be06-7965be754a02

	measure 'performance >6weeks' =
			
			var sixweeks = sum('Diagnostic'[>6 weeks])
			var wl = sum('Diagnostic'[Total wl sum 1])
			
			return sixweeks/wl
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 697eff2f-7772-4467-85e1-a72e154d0cd7

	measure '>6 weeks Total' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[>6 weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: #,0
		lineageTag: 1eaec4fe-d234-4f5e-8c82-b63a8dbdfd04

	measure 'Waiting List Latest Month' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[Total wl sum 1]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: #,0
		lineageTag: ae29338f-98a3-42ff-ad42-c84a6afc86ae

	measure 'Activity Latest Month' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[Total activity sum 1]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: #,0
		lineageTag: f0dc4f4a-bcef-4c53-8216-bb3278340253

	measure '06 < 07 Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[6-7_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: b5efa79d-b2e6-4c1e-8150-cbe9ea6a09ae

	measure '07 < 08 Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[7-8_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: 738da0ea-7f2b-40ba-83f2-95c51af18e8d

	measure '08 < 09 Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[8-9_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: 28938667-f7f0-4b35-8729-f82eb2211977

	measure '09 < 10 Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[9-10_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: 859dfd28-955a-4f82-a4bf-d103618b39f3

	measure '10 < 11 Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[10-11_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: 0f4d8650-a02f-45d9-8318-f47254a06d0a

	measure '11 < 12 Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[11-12_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: 2d565193-6b3d-4316-8faf-1e39a2c8db38

	measure '12 < 13 Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[12-13_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: fdc40b1b-8383-431f-90ee-c728dffb556b

	measure '13+ Weeks' = ```
			
			
			
			VAR MaxDate = MAX ( 'Date'[date] )
			
			VAR SOMMaxDate = DATE ( YEAR ( MaxDate ) , MONTH ( MaxDate ) ,1 )
			
			VAR EOMMaxDate = EOMONTH( MaxDate , 0 )
			
			VAR Result =
			
			CALCULATE( SUM('Diagnostic'[13_Weeks]) ,  
			
			    FILTER (
			
			        ALL ( 'Date'[date] ),
			
			        'Date'[date]>= SOMMaxDate && 'Date'[Date] <= EOMMaxDate) )
			
			
			
			
			RETURN
			
			    Result 
			```
		formatString: 0
		lineageTag: bab77e5d-fdce-43c3-9619-619019459a3f

	measure 'Performance Latest month' = ```
			
			
			CALCULATETABLE(
			    {'Diagnostic'[performance >6weeks]} ,
			    'Date'[year_month] = MAX ('Date'[year_month]))
			
			```
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: 46e1385c-6c14-4af7-ae50-0919e0fd9887

	column version
		dataType: string
		lineageTag: 4436feea-373d-4e7e-83d5-439818524498
		summarizeBy: none
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column period
		dataType: dateTime
		formatString: General Date
		lineageTag: ff89e80b-a0bd-443e-a25d-8507f853fcbf
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

	column commissioner_org_code
		dataType: string
		lineageTag: 523d7056-9d30-4d4c-ba8b-4f4d716ad18b
		summarizeBy: none
		sourceColumn: commissioner_org_code

		annotation SummarizationSetBy = Automatic

	column commissioner_org_name
		dataType: string
		lineageTag: d14e527e-e27a-41a3-b3ff-d27dd9f2152e
		summarizeBy: none
		sourceColumn: commissioner_org_name

		annotation SummarizationSetBy = Automatic

	column provider_org_code
		dataType: string
		lineageTag: dda5ef1f-5886-4231-9338-75fed7cfb953
		summarizeBy: none
		sourceColumn: provider_org_code

		annotation SummarizationSetBy = Automatic

	column provider_org_name
		dataType: string
		lineageTag: 478cb9b7-c296-40cc-95d1-cfb883c26135
		summarizeBy: none
		sourceColumn: provider_org_name

		annotation SummarizationSetBy = Automatic

	column diagnostic_test_sort_order
		dataType: string
		lineageTag: f7d35435-6b45-489d-b39b-c0743024a861
		summarizeBy: none
		sourceColumn: diagnostic_test_sort_order

		annotation SummarizationSetBy = Automatic

	column diagnostic_test
		dataType: string
		lineageTag: b51a0015-4243-463b-81f6-422bd0cc35bb
		summarizeBy: none
		sourceColumn: diagnostic_test

		annotation SummarizationSetBy = Automatic

	column 'Total wl sum 1'
		dataType: int64
		formatString: 0
		lineageTag: 73dd606b-9005-49d0-a0b8-a1a70ac93395
		summarizeBy: sum
		sourceColumn: Total wl sum 1

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Total activity sum 1'
		dataType: int64
		formatString: 0
		lineageTag: 75d44b73-c1be-4ee7-b2f8-2e7476c2c537
		summarizeBy: sum
		sourceColumn: Total activity sum 1

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column '0-2 weeks'
		dataType: int64
		formatString: 0
		lineageTag: 374aee8d-24b3-437c-a1f4-10e9ddbde9ca
		summarizeBy: sum
		sourceColumn: 0-2 weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column '2-4 weeks'
		dataType: int64
		formatString: 0
		lineageTag: b1dacb4e-65da-48b4-b0f8-b212e58a4c1c
		summarizeBy: sum
		sourceColumn: 2-4 weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column '4-6 weeks'
		dataType: int64
		formatString: 0
		lineageTag: 4bd4d35c-805c-4a83-9aeb-665552c0fcdb
		summarizeBy: sum
		sourceColumn: 4-6 weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column '>6 weeks'
		dataType: int64
		formatString: 0
		lineageTag: 947d3d7c-8efe-4deb-8822-4d2ed4defa61
		summarizeBy: sum
		sourceColumn: >6 weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: d7a52b7f-f9b9-46d9-a589-aba30dd46e4d
		summarizeBy: sum
		sourceColumn: counter

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 57582dbe-4677-4750-aea1-8f7fab280040
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column month_name_short
		dataType: string
		lineageTag: 0ba25740-eb6f-410e-b1c6-0719a665d8b7
		summarizeBy: none
		sourceColumn: month_name_short

		annotation SummarizationSetBy = Automatic

	column 0-1_Weeks
		dataType: string
		lineageTag: df877f12-14fe-4886-b7b7-852c6bce98be
		summarizeBy: none
		sourceColumn: 0-1_Weeks

		annotation SummarizationSetBy = Automatic

	column 1-2_Weeks
		dataType: string
		lineageTag: fdf35e36-ce1e-4bbd-ac27-db5c1b4927fb
		summarizeBy: none
		sourceColumn: 1-2_Weeks

		annotation SummarizationSetBy = Automatic

	column '2 3_Weeks'
		dataType: string
		lineageTag: adad5010-a467-436c-837f-0dba630dd5df
		summarizeBy: none
		sourceColumn: 2 3_Weeks

		annotation SummarizationSetBy = Automatic

	column 3-4_Weeks
		dataType: string
		lineageTag: f5f51af4-e1c3-49ce-9c35-e0aa3d698bf5
		summarizeBy: none
		sourceColumn: 3-4_Weeks

		annotation SummarizationSetBy = Automatic

	column 4-5_Weeks
		dataType: string
		lineageTag: e7d546ad-fee2-4ed1-a6b8-b13232a9f5f8
		summarizeBy: none
		sourceColumn: 4-5_Weeks

		annotation SummarizationSetBy = Automatic

	column 5-6_Weeks
		dataType: string
		lineageTag: a13da97c-c5d5-4d52-8439-ab33fa181dae
		summarizeBy: none
		sourceColumn: 5-6_Weeks

		annotation SummarizationSetBy = Automatic

	column 6-7_Weeks
		dataType: int64
		formatString: 0
		lineageTag: 70633b39-17df-425f-b54d-6722b72b68a2
		summarizeBy: sum
		sourceColumn: 6-7_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 7-8_Weeks
		dataType: int64
		formatString: 0
		lineageTag: 9d1def81-95a2-4bc6-8bdb-e36a0efa979a
		summarizeBy: sum
		sourceColumn: 7-8_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 8-9_Weeks
		dataType: int64
		formatString: 0
		lineageTag: b93a203e-52dc-4607-bac6-f79c8d81bae7
		summarizeBy: sum
		sourceColumn: 8-9_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 9-10_Weeks
		dataType: int64
		formatString: 0
		lineageTag: 3ac3216d-3c62-4ae8-a43f-22d25287cdc3
		summarizeBy: sum
		sourceColumn: 9-10_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 10-11_Weeks
		dataType: int64
		formatString: 0
		lineageTag: ca947aaa-d0fb-4d98-ba83-05b273cec546
		summarizeBy: sum
		sourceColumn: 10-11_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 11-12_Weeks
		dataType: int64
		formatString: 0
		lineageTag: bf18012c-ec73-406b-ac01-3b801c248650
		summarizeBy: sum
		sourceColumn: 11-12_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 12-13_Weeks
		dataType: int64
		formatString: 0
		lineageTag: e0614246-d281-4083-bfd1-c979b5653993
		summarizeBy: sum
		sourceColumn: 12-13_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 13_Weeks
		dataType: int64
		formatString: 0
		lineageTag: d2187541-5e24-4073-ba4b-dd5c63862c65
		summarizeBy: sum
		sourceColumn: 13_Weeks

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 729e0f26-c946-41b5-b9da-29f1d1d194a6
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column GHT
		dataType: string
		lineageTag: cfb15c9d-13dd-42c1-9260-68b627b3ab8d
		summarizeBy: none
		sourceColumn: GHT

		annotation SummarizationSetBy = Automatic

	column ICB
		dataType: string
		lineageTag: 69bdf219-8241-4ee7-a090-aaad7c05561e
		summarizeBy: none
		sourceColumn: ICB

		annotation SummarizationSetBy = Automatic

	column CDC
		dataType: string
		lineageTag: dcf90cfc-0f03-4350-b809-fb6bc1ce94bb
		summarizeBy: none
		sourceColumn: CDC

		annotation SummarizationSetBy = Automatic

	partition Diagnostic-c1220903-6c21-422f-9a38-d981005f90e1 = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Reporting", [Query="--EXEC [Performance].[SP02_DiagnosticPerformance] #(lf)--;#(lf)#(lf) select *#(lf) from [PowerBI_Reporting].[Performance].[tbl02_DiagnosticPerformance]#(lf)"]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"0-2_weeks", "0-2 weeks"}, {"2-4_weeks", "2-4 weeks"}, {"4-6_weeks", "4-6 weeks"}, {">6_weeks", ">6 weeks"}, {"total_wl_sum_1", "Total wl sum 1"}, {"total_activity_sum_1", "Total activity sum 1"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

