table ACC09
	lineageTag: 42f22740-f5d5-4bc6-9caa-ea3da58cc0b7

	column Indicator
		dataType: string
		lineageTag: 0d279888-52d1-45d5-ac0c-527bb8178b14
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column 'National Target'
		dataType: string
		lineageTag: 311780ad-1897-4421-b8ac-b2cb0f987f3d
		summarizeBy: none
		sourceColumn: National Target

		annotation SummarizationSetBy = Automatic

	column 'Desired Direction'
		dataType: string
		lineageTag: b2dfd297-5bfa-462a-a331-7c42514bef03
		summarizeBy: none
		sourceColumn: Desired Direction

		annotation SummarizationSetBy = Automatic

	column 'Date run'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 71baf97d-eccd-4491-a21c-69e71b8d5fb6
		summarizeBy: none
		sourceColumn: Date run

		variation Variation
			isDefault
			relationship: a84ce823-7a1d-4386-9b00-0dece1a1b328
			defaultHierarchy: LocalDateTable_85f97f87-aa31-43b4-94ac-9fb1fe70b341.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Central
		dataType: double
		lineageTag: 70a84939-1f66-4345-8d30-30d79f1a5d13
		summarizeBy: sum
		sourceColumn: Central

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Underwood Surgery'
		dataType: double
		lineageTag: 72218bc0-53a4-4830-9edf-41db8c554aff
		summarizeBy: sum
		sourceColumn: Underwood Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Yorkleigh Surgery'
		dataType: double
		lineageTag: 67948edf-d0a6-4be6-92c9-feec5ac2f341
		summarizeBy: sum
		sourceColumn: Yorkleigh Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Berkeley Place Surgery at Wilson Health Centre'
		dataType: double
		lineageTag: 6a889353-69fc-4909-be21-0fbc4f51754f
		summarizeBy: sum
		sourceColumn: Berkeley Place Surgery at Wilson Health Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Overton Park Surgery'
		dataType: double
		lineageTag: 6ccf89b4-eb90-45a9-87b4-16203480114d
		summarizeBy: sum
		sourceColumn: Overton Park Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Royal Crescent Surgery at Wilson Health Centre'
		dataType: double
		lineageTag: 73cfb06d-5b43-4af3-b710-98fdb1b151f0
		summarizeBy: sum
		sourceColumn: Royal Crescent Surgery at Wilson Health Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Peripheral
		dataType: double
		lineageTag: d3f8e413-6c46-49f7-8601-e47044bf86d4
		summarizeBy: sum
		sourceColumn: Peripheral

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Winchcombe Medical Centre'
		dataType: double
		lineageTag: be2e2419-a403-4c44-a015-fffb591f77d1
		summarizeBy: sum
		sourceColumn: Winchcombe Medical Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sixways Clinic'
		dataType: double
		lineageTag: cc2ced10-20fc-4466-b229-aea916d4b8c5
		summarizeBy: sum
		sourceColumn: Sixways Clinic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cleevelands Medical Centre'
		dataType: double
		lineageTag: fb62e2a8-f019-41f5-ad97-50429492b37d
		summarizeBy: sum
		sourceColumn: Cleevelands Medical Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Leckhampton Surgery'
		dataType: double
		lineageTag: b4f1970f-acb7-46bc-a873-f1d103762767
		summarizeBy: sum
		sourceColumn: Leckhampton Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stoke Road Surgery'
		dataType: double
		lineageTag: 2054610b-53bf-4b24-8231-ff8dbd0d7971
		summarizeBy: sum
		sourceColumn: Stoke Road Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'St Paul''s'
		dataType: double
		lineageTag: 3d73443c-aa3f-41a2-a6b8-9ccf787dac62
		summarizeBy: sum
		sourceColumn: St Paul's

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'St.George''s Surgery'
		dataType: double
		lineageTag: 11ea011d-dfd6-4d38-964d-c9ad8e6d785c
		summarizeBy: sum
		sourceColumn: St.George's Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weston House Practice'
		dataType: double
		lineageTag: 33dcc164-0d0a-459b-b710-adacfa5dccb6
		summarizeBy: sum
		sourceColumn: Weston House Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'The Royal Well Surgery'
		dataType: double
		lineageTag: 84759f30-9541-4fe2-a843-5650986ad5f1
		summarizeBy: sum
		sourceColumn: The Royal Well Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'St.Catherine''s Surgery'
		dataType: double
		lineageTag: e2809469-2d5c-4b7a-ae90-8977ce3c8e7e
		summarizeBy: sum
		sourceColumn: St.Catherine's Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stroud Cotswolds'
		dataType: double
		lineageTag: 604c20ab-f652-4716-b036-5f004434d7de
		summarizeBy: sum
		sourceColumn: Stroud Cotswolds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Minchinhampton Surgery'
		dataType: double
		lineageTag: 5b673125-5a3e-4a0d-9a02-b5c9b0d01be9
		summarizeBy: sum
		sourceColumn: Minchinhampton Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rowcroft Medical Centre'
		dataType: double
		lineageTag: 3f956db4-809e-4a87-8ab4-a4c6824d93d0
		summarizeBy: sum
		sourceColumn: Rowcroft Medical Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Frithwood Surgery'
		dataType: double
		lineageTag: 8655878c-3da0-4333-932a-26f43d6b6aab
		summarizeBy: sum
		sourceColumn: Frithwood Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Painswick Surgery'
		dataType: double
		lineageTag: 9cae756f-8bfd-4c54-8aa9-013b5cf51d97
		summarizeBy: sum
		sourceColumn: Painswick Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Beeches Green Surgery'
		dataType: double
		lineageTag: 2b820759-2613-45e5-b074-8d02cf891b8a
		summarizeBy: sum
		sourceColumn: Beeches Green Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TWNS
		dataType: double
		lineageTag: d871dad2-18a2-44d0-b296-f0b89d94951b
		summarizeBy: sum
		sourceColumn: TWNS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Staunton & Corse Surgery'
		dataType: double
		lineageTag: 62841e51-0ed0-40fd-9b7f-ecddba7a1617
		summarizeBy: sum
		sourceColumn: Staunton & Corse Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Church Street Medical'
		dataType: double
		lineageTag: 709d6402-8c18-4eb1-b61d-62083ba5cd66
		summarizeBy: sum
		sourceColumn: Church Street Medical

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Newent Doctors Practice'
		dataType: double
		lineageTag: 2d614e56-2f0e-40fd-bb37-662a069fbc9a
		summarizeBy: sum
		sourceColumn: Newent Doctors Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mythe Medical Practice'
		dataType: double
		lineageTag: cc622b31-d1b2-421a-b4c1-60eb1542962f
		summarizeBy: sum
		sourceColumn: Mythe Medical Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'West Cheltenham Medical'
		dataType: double
		lineageTag: 54acd61e-3acb-4bfd-b01b-2cad2034a271
		summarizeBy: sum
		sourceColumn: West Cheltenham Medical

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HQ
		dataType: double
		lineageTag: 24cd7a09-be88-474f-9f53-2f68934546fa
		summarizeBy: sum
		sourceColumn: HQ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hadwen Health'
		dataType: double
		lineageTag: 03a5cc1f-b0c7-4e81-9a48-6bcfe4e9c160
		summarizeBy: sum
		sourceColumn: Hadwen Health

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quedgeley Medical Centre'
		dataType: double
		lineageTag: 3cbb1a3a-7ffe-429a-91ee-283df49334d5
		summarizeBy: sum
		sourceColumn: Quedgeley Medical Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'South Cotswolds'
		dataType: double
		lineageTag: dfec55dd-96bb-4cff-a6b5-17504f41ef10
		summarizeBy: sum
		sourceColumn: South Cotswolds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Upper Thames Medical Group'
		dataType: double
		lineageTag: 5cbdfed2-5d5e-4853-8fb0-7b4ac276143e
		summarizeBy: sum
		sourceColumn: Upper Thames Medical Group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Phoenix Health Group'
		dataType: double
		lineageTag: fa1fbb9f-b154-4064-98f7-9ff9602428f1
		summarizeBy: sum
		sourceColumn: Phoenix Health Group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cirencester Health Group'
		dataType: double
		lineageTag: 0e8483b4-59be-4c6a-8ffc-c0fc96b961df
		summarizeBy: sum
		sourceColumn: Cirencester Health Group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hilary Cottage Surgery'
		dataType: double
		lineageTag: 0e1bd009-f045-476c-bb91-c7bcd3e868d9
		summarizeBy: sum
		sourceColumn: Hilary Cottage Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RENDCOMB SURGERY'
		dataType: double
		lineageTag: 6a442959-e0fd-4d23-8788-df240a3a6e9d
		summarizeBy: sum
		sourceColumn: RENDCOMB SURGERY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'West Forest of Dean'
		dataType: double
		lineageTag: eaa1ae60-7795-4687-b632-745c1a7c9ee8
		summarizeBy: sum
		sourceColumn: West Forest of Dean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lydney Medical Practice'
		dataType: double
		lineageTag: 74a3aa73-5906-4bb8-851b-17419497c91d
		summarizeBy: sum
		sourceColumn: Lydney Medical Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Yorkley Health Centre'
		dataType: double
		lineageTag: baae7698-d82a-4697-baa3-9beeb559b9f8
		summarizeBy: sum
		sourceColumn: Yorkley Health Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Severnbank Surgery'
		dataType: double
		lineageTag: 670bba71-38a9-4718-abf2-8be5f9e809ba
		summarizeBy: sum
		sourceColumn: Severnbank Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forest Green'
		dataType: double
		lineageTag: 69e3b2bd-c8bf-47d6-8c49-d0bb583990c2
		summarizeBy: sum
		sourceColumn: Forest Green

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forest Health Care'
		dataType: double
		lineageTag: 92e34cb9-e589-4556-ac07-730f7f36772a
		summarizeBy: sum
		sourceColumn: Forest Health Care

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Drs Weiss, Stallard & Tingay'
		dataType: double
		lineageTag: 8794074d-2747-4231-8e50-b420ea76c319
		summarizeBy: sum
		sourceColumn: Drs Weiss, Stallard & Tingay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dockham Surgery'
		dataType: double
		lineageTag: 9925fb80-204b-448a-a204-4a6c3acb4e1a
		summarizeBy: sum
		sourceColumn: Dockham Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Drybrook Surgery'
		dataType: double
		lineageTag: 707df736-1dc3-4f02-9954-9ab0e8cc6899
		summarizeBy: sum
		sourceColumn: Drybrook Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NSG
		dataType: double
		lineageTag: ab763635-435e-42b8-b155-4fb30ec07abc
		summarizeBy: sum
		sourceColumn: NSG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hucclecote Surgery'
		dataType: double
		lineageTag: a2ad2f84-e9fb-413c-b515-acfadfd5c434
		summarizeBy: sum
		sourceColumn: Hucclecote Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Churchdown Surgery'
		dataType: double
		lineageTag: 758edcc9-88ba-4cb9-af4d-1226b8e97fac
		summarizeBy: sum
		sourceColumn: Churchdown Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Longlevens Surgery'
		dataType: double
		lineageTag: b5124589-7595-45ef-ad3d-3739d23282cc
		summarizeBy: sum
		sourceColumn: Longlevens Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Brockworth Surgery'
		dataType: double
		lineageTag: 746264c1-514e-4893-8004-be47914bd4db
		summarizeBy: sum
		sourceColumn: Brockworth Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'The Alney Practice'
		dataType: double
		lineageTag: 1d009dc3-3cd4-4712-8bcf-0244a8604497
		summarizeBy: sum
		sourceColumn: The Alney Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Aspen
		dataType: double
		lineageTag: fc760cc7-c412-44d7-8a6d-50c3af14eed5
		summarizeBy: sum
		sourceColumn: Aspen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Aspen Medical Practice'
		dataType: double
		lineageTag: 802744ec-2945-4062-9b0f-8dbba9939e0d
		summarizeBy: sum
		sourceColumn: Aspen Medical Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Berkeley Vale'
		dataType: double
		lineageTag: a6810d29-c0de-4e41-b555-a9be52406941
		summarizeBy: sum
		sourceColumn: Berkeley Vale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'The Culverhay Surgery'
		dataType: double
		lineageTag: caf9e301-6097-4201-93d3-e4ef7d6115cd
		summarizeBy: sum
		sourceColumn: The Culverhay Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'The Chipping Surgery'
		dataType: double
		lineageTag: a6f364c5-80a2-4350-86eb-1e68c392ee9f
		summarizeBy: sum
		sourceColumn: The Chipping Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cam & Uley Family Practice'
		dataType: double
		lineageTag: 17c8cce4-db5d-4ce8-824d-d553229eb862
		summarizeBy: sum
		sourceColumn: Cam & Uley Family Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'May Lane Surgery'
		dataType: double
		lineageTag: 2c1d5d78-bb60-4afc-8880-fa6c0e777426
		summarizeBy: sum
		sourceColumn: May Lane Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'North Cotswolds'
		dataType: double
		lineageTag: 7c4b091b-b645-43eb-b354-cbf2cdb69535
		summarizeBy: sum
		sourceColumn: North Cotswolds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stow Surgery'
		dataType: double
		lineageTag: 8b41e298-f7fb-4a60-97d9-f73edae0b9cd
		summarizeBy: sum
		sourceColumn: Stow Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cotswold Medical Practice'
		dataType: double
		lineageTag: d26b16b3-b977-42b5-8e1f-a25defc07fc5
		summarizeBy: sum
		sourceColumn: Cotswold Medical Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Campden Surgery'
		dataType: double
		lineageTag: 4685fdb9-a7c7-42e9-888e-e6fb6a5d5698
		summarizeBy: sum
		sourceColumn: Campden Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mann Cottage Surgery'
		dataType: double
		lineageTag: ed83b5d5-0ca9-47be-9f6c-dd496b791ad2
		summarizeBy: sum
		sourceColumn: Mann Cottage Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'White House Surgery'
		dataType: double
		lineageTag: 07dd0d25-1769-454a-827c-d1dcfbf2ba3f
		summarizeBy: sum
		sourceColumn: White House Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Severn Health'
		dataType: double
		lineageTag: 4d4a3382-bed3-4b22-8b8b-d07dc09a64bd
		summarizeBy: sum
		sourceColumn: Severn Health

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price''s Mill Surgery'
		dataType: double
		lineageTag: 0dda6680-d689-468b-9d06-53d1f72f1faf
		summarizeBy: sum
		sourceColumn: Price's Mill Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Five Valleys Medical Practice'
		dataType: double
		lineageTag: 5ecb8c5f-9997-43fe-88e6-cb09f3c8eb58
		summarizeBy: sum
		sourceColumn: Five Valleys Medical Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'The Willow Practice'
		dataType: double
		lineageTag: 267973f0-6e6b-4916-b9f0-713ff237a4dc
		summarizeBy: sum
		sourceColumn: The Willow Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stonehouse Health Clinic'
		dataType: double
		lineageTag: 85b9fd6c-1008-4c81-b47d-696c7bd149b4
		summarizeBy: sum
		sourceColumn: Stonehouse Health Clinic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Inner City'
		dataType: double
		lineageTag: 48353afd-b054-49da-8eff-3d2d9bb28651
		summarizeBy: sum
		sourceColumn: Inner City

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Partners In Health, Pavilion Family Drs'
		dataType: double
		lineageTag: ee45bfca-4a00-4e78-b22c-af35ad3a77b1
		summarizeBy: sum
		sourceColumn: Partners In Health, Pavilion Family Drs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Severnside Medical Practice'
		dataType: double
		lineageTag: 52e99f3a-bd88-480e-aa85-60b0729a30d2
		summarizeBy: sum
		sourceColumn: Severnside Medical Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Kingsholm Surgery'
		dataType: double
		lineageTag: f1b05e5e-ce15-4212-b94d-d7ab34a89df3
		summarizeBy: sum
		sourceColumn: Kingsholm Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gloucester Health Access Centre'
		dataType: double
		lineageTag: 9e331efb-5d11-4fcf-9cf0-c80e479a8c90
		summarizeBy: sum
		sourceColumn: Gloucester Health Access Centre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RB
		dataType: double
		lineageTag: 6a5f92dc-4cf0-4637-80f5-d3c6072f06f2
		summarizeBy: sum
		sourceColumn: RB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rosebank Health Surgery'
		dataType: double
		lineageTag: 4f513fbd-c11a-49ba-b243-2e63b651f79b
		summarizeBy: sum
		sourceColumn: Rosebank Health Surgery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ICB
		dataType: double
		lineageTag: 61c6c634-c8ac-4d93-a062-819c84926ba4
		summarizeBy: sum
		sourceColumn: ICB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %
		dataType: double
		lineageTag: 73da9973-be01-43a4-a686-16a340fad738
		summarizeBy: sum
		sourceColumn: %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'March 2025 Target' = 25.26
		lineageTag: 66c762cc-c0be-4d69-88e0-d0461398e845
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dean Medical Practice'
		dataType: double
		lineageTag: f0029569-8416-4159-b8c0-a8aa18d898cc
		summarizeBy: sum
		sourceColumn: Dean Medical Practice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ACC09 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("M:\Info\Projects\Pharmacy referrals\Processed_Data\ACC09 raw table.xlsx"), null, true),
				    #"Raw data_Sheet" = Source{[Item="Raw data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Raw data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Indicator", type text}, {"National Target", type text}, {"Desired Direction", type text}, {"Date run", type date}, {"Central", type number}, {"Underwood Surgery", type number}, {"Yorkleigh Surgery", type number}, {"Berkeley Place Surgery at Wilson Health Centre", type number}, {"Overton Park Surgery", type number}, {"Royal Crescent Surgery at Wilson Health Centre", type number}, {"Peripheral", type number}, {"Winchcombe Medical Centre", type number}, {"Sixways Clinic", type number}, {"Cleevelands Medical Centre", type number}, {"Leckhampton Surgery", type number}, {"Stoke Road Surgery", type number}, {"St Paul's", type number}, {"St.George's Surgery", type number}, {"Weston House Practice", type number}, {"The Royal Well Surgery", type number}, {"St.Catherine's Surgery", type number}, {"Stroud Cotswolds", type number}, {"Minchinhampton Surgery", type number}, {"Rowcroft Medical Centre", type number}, {"Frithwood Surgery", type number}, {"Painswick Surgery", type number}, {"Beeches Green Surgery", type number}, {"TWNS", type number}, {"Staunton & Corse Surgery", type number}, {"Church Street Medical", type number}, {"Newent Doctors Practice", type number}, {"Mythe Medical Practice", type number}, {"West Cheltenham Medical", type number}, {"HQ", type number}, {"Hadwen Health", type number}, {"Quedgeley Medical Centre", type number}, {"South Cotswolds", type number}, {"Upper Thames Medical Group", type number}, {"Phoenix Health Group", type number}, {"Cirencester Health Group", type number}, {"Hilary Cottage Surgery", type number}, {"RENDCOMB SURGERY", type number}, {"West Forest of Dean", type number}, {"Lydney Medical Practice", type number}, {"Yorkley Health Centre", type number}, {"Dean Medical Practice", type number}, {"Severnbank Surgery", type number}, {"Forest Green", type number}, {"Forest Health Care", type number}, {"Drs Weiss, Stallard & Tingay", type number}, {"Dockham Surgery", type number}, {"Drybrook Surgery", type number}, {"NSG", type number}, {"Hucclecote Surgery", type number}, {"Churchdown Surgery", type number}, {"Longlevens Surgery", type number}, {"Brockworth Surgery", type number}, {"The Alney Practice", type number}, {"Aspen", type number}, {"Aspen Medical Practice", type number}, {"Berkeley Vale", type number}, {"The Culverhay Surgery", type number}, {"The Chipping Surgery", type number}, {"Cam & Uley Family Practice", type number}, {"May Lane Surgery", type number}, {"North Cotswolds", type number}, {"Stow Surgery", type number}, {"Cotswold Medical Practice", type number}, {"Campden Surgery", type number}, {"Mann Cottage Surgery", type number}, {"White House Surgery", type number}, {"Severn Health", type number}, {"Price's Mill Surgery", type number}, {"Five Valleys Medical Practice", type number}, {"The Willow Practice", type number}, {"Stonehouse Health Clinic", type number}, {"Inner City", type number}, {"Partners In Health, Pavilion Family Drs", type number}, {"Severnside Medical Practice", type number}, {"Kingsholm Surgery", type number}, {"Gloucester Health Access Centre", type number}, {"RB", type number}, {"Rosebank Health Surgery", type number}, {"ICB", type number}, {"%", type number}}),
				    #"Filled Down" = Table.FillDown(#"Changed Type",{"Date run"})
				in
				    #"Filled Down"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

