table BundlingPaymentCriteria
	lineageTag: a17b5ac6-4247-4f4e-aad4-1261bc3c6c3c

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d59df2d-e2ce-4fe0-8d11-e0e69be216c1
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: 28f98135-de44-42a0-a18f-4e0ce0f4d7a1
			defaultHierarchy: LocalDateTable_e88575e5-fdfb-4492-96cb-deb5c849b784.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Threshold £1000'
		dataType: int64
		formatString: 0
		lineageTag: 49c0d585-1c6d-4ec4-8a94-a217990f54f5
		summarizeBy: sum
		sourceColumn: Threshold £1000

		annotation SummarizationSetBy = Automatic

	column 'Threshold £500'
		dataType: int64
		formatString: 0
		lineageTag: 3e00e49c-ae8c-4703-9217-bc175821f4af
		summarizeBy: sum
		sourceColumn: Threshold £500

		annotation SummarizationSetBy = Automatic

	column 'Bundling opt in needed'
		dataType: int64
		formatString: 0
		lineageTag: 75e92167-4006-4160-87bd-6668be1e2dfd
		summarizeBy: sum
		sourceColumn: Bundling opt in needed

		annotation SummarizationSetBy = Automatic

	column '1+ ABPM needed'
		dataType: int64
		formatString: 0
		lineageTag: 3b35daa4-9bab-45d1-9a65-2813cb88ba5b
		summarizeBy: sum
		sourceColumn: 1+ ABPM needed

		annotation SummarizationSetBy = Automatic

	column '#+ OC needed'
		dataType: int64
		formatString: 0
		lineageTag: a960f772-4053-4545-a287-4ae7e78f5d63
		summarizeBy: sum
		sourceColumn: #+ OC needed

		annotation SummarizationSetBy = Automatic

	column 'Artificial Threshold £1000' = 30
		formatString: 0
		lineageTag: 839cd597-f265-4c40-993e-4edfcca963cd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Artificial Threshold £500' = 20
		formatString: 0
		lineageTag: 6211e12d-e6f0-45fa-a824-800212177e17
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition BundlingPaymentCriteria = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jdFLCsAgDATQu7guNBk/tWcp3v8atRWFYsMIZvdIRua6nOgu2CEIbnNapz4ZU7YmfBfREoGKOK6IRRInByd5EDPL2QmsLSqcKCegRN4tT1KYccGJ78SbhwInkZP0Ie+39L8lhvIKOhdQ62pGOrfFEBZQaywRhBXkbaSulBs=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Month = _t, #"Threshold £1000" = _t, #"Threshold £500" = _t, #"Bundling opt in needed" = _t, #"1+ ABPM needed" = _t, #"#+ OC needed" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Month", type date}, {"Threshold £1000", Int64.Type}, {"Threshold £500", Int64.Type}, {"Bundling opt in needed", Int64.Type}, {"1+ ABPM needed", Int64.Type}, {"#+ OC needed", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

