table Consultations_ICB
	lineageTag: f51d9511-fdee-4882-9439-4280fe8916c7

	measure 'PF consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[PF_Total])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: e92fe164-ceca-4fa3-b921-c1198e9afb29

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BP consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[BP_Total])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: 4cd35417-a5f4-4417-b6ce-b0376f9c5c81

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OC consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[OC_Total])*100000,
				SUM('ICB_populations_childbearing_FYtoMonth'[Population])
			)
		lineageTag: ee23e5f7-97ef-418a-a79d-37dd8c712a1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PF CP consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[Clinical pathways consultation])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: 90756484-5647-425f-b84d-adbf576fa3fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PF MI consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[Minor illness referral])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: dcd41985-fc05-41ba-afc3-db6dce88e46b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PF UM consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[Urgent medicine supply])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: 06cb04e3-50a9-4081-9f1f-534362cb72b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BP Clinic consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[CLINIC])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: a6ad46df-f816-41ce-b8a1-97476013b385

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BP ABPM consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[ABPM])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: 253351c2-5190-472c-956f-0d5cd94b342d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OP_Plan consultations per 100k population' =
			
			DIVIDE(
				SUM('Consultations_ICB'[OP_plan_total])*100000,
				SUM('ICB_populations_FYtoMonth'[Population])
			)
		lineageTag: 526621b8-ef96-4b27-bf59-6903efbf9a35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Region Code'
		dataType: string
		lineageTag: 2be0e977-5347-4ffa-a545-ec50a08c9bcf
		summarizeBy: none
		sourceColumn: Region Code

		annotation SummarizationSetBy = Automatic

	column 'Region Name'
		dataType: string
		lineageTag: 7b5a3759-48be-438a-8d0d-95b005bce1a0
		summarizeBy: none
		sourceColumn: Region Name

		annotation SummarizationSetBy = Automatic

	column 'ICB Code'
		dataType: string
		lineageTag: 997d096e-1b00-45cf-8deb-fc26f8fc760f
		summarizeBy: none
		sourceColumn: ICB Code

		annotation SummarizationSetBy = Automatic

	column 'ICB Name'
		dataType: string
		lineageTag: 61756fc6-433e-4998-8dd1-844086353f2f
		summarizeBy: none
		sourceColumn: ICB Name

		annotation SummarizationSetBy = Automatic

	column Consultation_Month
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c2a5254-de76-452b-a14c-f0edb9861d66
		summarizeBy: none
		sourceColumn: Consultation_Month

		annotation SummarizationSetBy = Automatic

	column NumPharms
		dataType: int64
		lineageTag: 4f392607-3b01-4ace-9ac0-12555dab7204
		summarizeBy: sum
		sourceColumn: NumPharms

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PFOpt
		dataType: int64
		lineageTag: dbb63137-a5e7-42fd-89e3-2b93db22b6b9
		summarizeBy: sum
		sourceColumn: PFOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BPOpt
		dataType: int64
		lineageTag: bc8e59f9-fc12-4268-8878-7642efa1c604
		summarizeBy: sum
		sourceColumn: BPOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OCOpt
		dataType: int64
		lineageTag: 3057b8aa-bbea-41f6-ba1a-965a911010ba
		summarizeBy: sum
		sourceColumn: OCOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AllThreeOpt
		dataType: int64
		lineageTag: 4ac20823-5220-4b8d-b340-53bdf348b461
		summarizeBy: sum
		sourceColumn: AllThreeOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ABPM
		dataType: int64
		lineageTag: 993a1791-7827-4ed6-b24f-96169368e309
		summarizeBy: sum
		sourceColumn: ABPM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CLINIC
		dataType: int64
		lineageTag: fd3823c3-6cb2-4025-96db-1a8df9631a81
		summarizeBy: sum
		sourceColumn: CLINIC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BP_Total
		dataType: int64
		lineageTag: 1873e0f5-896a-4081-b1a2-dd05686b0c5e
		summarizeBy: sum
		sourceColumn: BP_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Initiation
		dataType: int64
		lineageTag: 2d221b48-1e2a-4eda-9e5b-7d0e48390cd8
		summarizeBy: sum
		sourceColumn: Initiation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ongoing provision'
		dataType: int64
		lineageTag: 43b3cbaa-5df2-4c27-ae68-74dc80bcd1c5
		summarizeBy: sum
		sourceColumn: Ongoing provision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OC_Total
		dataType: int64
		lineageTag: 5b803da7-ea2e-4ece-913b-1be503f47cd6
		summarizeBy: sum
		sourceColumn: OC_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Clinical pathways consultation'
		dataType: int64
		lineageTag: ffaecb04-aa13-4211-938b-457f1a5d58ec
		summarizeBy: sum
		sourceColumn: Clinical pathways consultation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Minor illness referral'
		dataType: int64
		lineageTag: 7d343d92-547d-48d8-844e-d6d87cf368ac
		summarizeBy: sum
		sourceColumn: Minor illness referral

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Urgent medicine supply'
		dataType: int64
		lineageTag: 216ea62c-da0b-42a3-a5ed-5712f6e0949c
		summarizeBy: sum
		sourceColumn: Urgent medicine supply

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PF_Total
		dataType: int64
		lineageTag: fa38cb60-6f7b-4b23-91af-256fdf965c3b
		summarizeBy: sum
		sourceColumn: PF_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Acute Otitis Media'
		dataType: int64
		lineageTag: c6cbda2a-f2d8-47d1-bc57-43a234bf072b
		summarizeBy: sum
		sourceColumn: Acute Otitis Media

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Acute Sore Throat'
		dataType: int64
		lineageTag: 2fcf9ba3-c355-4ebe-8541-875fb9e212e2
		summarizeBy: sum
		sourceColumn: Acute Sore Throat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Impetigo
		dataType: int64
		lineageTag: e56206d3-ef8a-4261-8d95-1b31fb1858e4
		summarizeBy: sum
		sourceColumn: Impetigo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Infected Insect Bites'
		dataType: int64
		lineageTag: 55ea30f9-14d7-4800-9724-7e8a1495d43e
		summarizeBy: sum
		sourceColumn: Infected Insect Bites

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Shingles
		dataType: int64
		lineageTag: 53b8cd4c-15c8-41bc-8c14-34f3047896a9
		summarizeBy: sum
		sourceColumn: Shingles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sinusitis
		dataType: int64
		lineageTag: d3605850-b9f0-407a-ac3b-2736d06fe90e
		summarizeBy: sum
		sourceColumn: Sinusitis

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Uncomplicated UTI'
		dataType: int64
		lineageTag: 80022d88-0169-4f4b-a281-2b9e613e2ce1
		summarizeBy: sum
		sourceColumn: Uncomplicated UTI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PFOpt_pct = 100*[PFOpt]/[NumPharms]
		lineageTag: 537dacca-2cf8-4868-af53-c14bedc3baf1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BPOpt_pct = ```
			100*[BPOpt]/[NumPharms]
			
			```
		lineageTag: 0e9a8d10-1e82-40d8-8684-809cce11085f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OCOpt_pct = 100*[OCOpt]/[NumPharms]
		lineageTag: 7450ec75-f915-4633-8e8c-a7b54ec675b7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AllThreeOpt_pct = [AllThreeOpt]/[NumPharms]
		lineageTag: d9c2ff7f-8d9f-4cef-a4dc-10c841ae95c5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OP_plan_total = 'Consultations_ICB'[Clinical pathways consultation] + 'Consultations_ICB'[BP_Total] + 'Consultations_ICB'[OC_Total]
		formatString: 0
		lineageTag: 3951d46c-0d24-45aa-be7e-6d0659d2b6f8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Consultations_ICB = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "BIReports", [Query="-- Pulls data from one table only. UNIONs use group bys to add England and SW average rows. #(lf)-- ICB level data#(lf)SELECT [Region Code]#(lf),[Region Name]#(lf),[ICB Code]#(lf),[ICB Name]#(lf),Consultation_Month#(lf),NumPharms#(lf),PFOpt#(lf),BPOpt#(lf),OCOpt#(lf),AllThreeOpt#(lf),ABPM#(lf),CLINIC#(lf),BP_Total#(lf),Initiation#(lf),[Ongoing provision]#(lf),OC_Total#(lf),[Clinical pathways consultation]#(lf),[Minor illness referral]#(lf),[Urgent medicine supply]#(lf),PF_Total#(lf),[Acute Otitis Media]#(lf),[Acute Sore Throat]#(lf),Impetigo#(lf),[Infected Insect Bites]#(lf),Shingles#(lf),Sinusitis#(lf),[Uncomplicated UTI]#(lf)FROM PowerBI_Reporting.primarycare.[tbl07_Pharm_Consultations_ICB]#(lf)#(lf)UNION -- England average#(lf)#(lf)SELECT 'ENG' AS [Region Code]#(lf),'ENGLAND' AS [Region Name]#(lf),'ENG' AS [ICB Code]#(lf),'ENGLAND' AS [ICB Name]#(lf), Consultation_Month#(lf),SUM(NumPharms) AS NumPharms#(lf),SUM(PFOpt) AS PFOpt#(lf),SUM(BPOpt) AS BPOpt#(lf),SUM(OCOpt) AS OCOpt#(lf),SUM(AllThreeOpt) AS AllThreeOpt#(lf),SUM(ABPM) AS ABPM#(lf),SUM(CLINIC) AS CLINIC#(lf),SUM(BP_Total) AS BP_Total#(lf),SUM(Initiation) AS Initiation#(lf),SUM([Ongoing provision]) AS [Ongoing provision]#(lf),SUM(OC_Total) AS OC_Total#(lf),SUM([Clinical pathways consultation]) AS [Clinical pathways consultation]#(lf),SUM([Minor illness referral]) AS [Minor illness referral]#(lf),SUM([Urgent medicine supply]) AS [Urgent medicine supply]#(lf),SUM(PF_Total) AS PF_Total#(lf),SUM([Acute Otitis Media]) AS [Acute Otitis Media]#(lf),SUM([Acute Sore Throat]) AS [Acute Sore Throat]#(lf),SUM(Impetigo) AS Impetigo#(lf),SUM([Infected Insect Bites]) AS [Infected Insect Bites]#(lf),SUM(Shingles) AS Shingles#(lf),SUM(Sinusitis) AS Sinusitis#(lf),SUM([Uncomplicated UTI]) AS [Uncomplicated UTI]#(lf)FROM PowerBI_Reporting.primarycare.[tbl07_Pharm_Consultations_ICB]#(lf)GROUP BY Consultation_Month#(lf)#(lf)UNION -- South West region average#(lf)#(lf)SELECT [Region Code]#(lf), [Region Name]#(lf),[Region Code] AS [ICB Code]#(lf),[Region Name] AS [ICB Name]#(lf), Consultation_Month#(lf),SUM(NumPharms) AS NumPharms#(lf),SUM(PFOpt) AS PFOpt#(lf),SUM(BPOpt) AS BPOpt#(lf),SUM(OCOpt) AS OCOpt#(lf),SUM(AllThreeOpt) AS AllThreeOpt#(lf),SUM(ABPM) AS ABPM#(lf),SUM(CLINIC) AS CLINIC#(lf),SUM(BP_Total) AS BP_Total#(lf),SUM(Initiation) AS Initiation#(lf),SUM([Ongoing provision]) AS [Ongoing provision]#(lf),SUM(OC_Total) AS OC_Total#(lf),SUM([Clinical pathways consultation]) AS [Clinical pathways consultation]#(lf),SUM([Minor illness referral]) AS [Minor illness referral]#(lf),SUM([Urgent medicine supply]) AS [Urgent medicine supply]#(lf),SUM(PF_Total) AS PF_Total#(lf),SUM([Acute Otitis Media]) AS [Acute Otitis Media]#(lf),SUM([Acute Sore Throat]) AS [Acute Sore Throat]#(lf),SUM(Impetigo) AS Impetigo#(lf),SUM([Infected Insect Bites]) AS [Infected Insect Bites]#(lf),SUM(Shingles) AS Shingles#(lf),SUM(Sinusitis) AS Sinusitis#(lf),SUM([Uncomplicated UTI]) AS [Uncomplicated UTI]#(lf)FROM PowerBI_Reporting.primarycare.[tbl07_Pharm_Consultations_ICB]#(lf)WHERE [Region Code] = 'Y58'#(lf)GROUP BY [Region Code], [Region Name], Consultation_Month#(lf);"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"NumPharms", Int64.Type}, {"PFOpt", Int64.Type}, {"BPOpt", Int64.Type}, {"OCOpt", Int64.Type}, {"AllThreeOpt", Int64.Type}, {"ABPM", Int64.Type}, {"CLINIC", Int64.Type}, {"BP_Total", Int64.Type}, {"Initiation", Int64.Type}, {"Ongoing provision", Int64.Type}, {"OC_Total", Int64.Type}, {"Clinical pathways consultation", Int64.Type}, {"Minor illness referral", Int64.Type}, {"Urgent medicine supply", Int64.Type}, {"PF_Total", Int64.Type}, {"Acute Otitis Media", Int64.Type}, {"Acute Sore Throat", Int64.Type}, {"Impetigo", Int64.Type}, {"Infected Insect Bites", Int64.Type}, {"Shingles", Int64.Type}, {"Sinusitis", Int64.Type}, {"Uncomplicated UTI", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

