table Consultations
	lineageTag: 4e6aa28a-7f0c-4d09-be3b-7b3134075607

	measure Bundle_1+ = COUNT(Consultations[PF_Total]) + COUNT(Consultations[BP_Total]) + COUNT(Consultations[OC_Total])
		formatString: 0
		lineageTag: de1c7cc0-1da3-49c8-8e90-3ffbdc9def21

	measure 3xOpt% =
			
			DIVIDE(
				SUM('Consultations'[AllThreeOpt]),
				DISTINCTCOUNT('REF_Reporting_Pharmacy_ODS_codes (semi-auto)'[Reporting_ODS])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: fbfaf761-1288-43fc-b0d3-9a4e8b7c686b

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 3xService_1+Consultation% =
			
			DIVIDE(
				SUM('Consultations'[3xService_1+Consultation]),
				COUNTA('REF_Reporting_Pharmacy_ODS_codes (semi-auto)'[Reporting_ODS])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4d050889-e2fd-4905-8bf4-0758efb63fc6

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure OP_plan_monthly_target = 92164/12
		lineageTag: ac1a75de-3114-4753-a389-17d813bcf73f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OP_plan_cum_target =
			
			[OP_plan_monthly_target] * COUNTA('REF_Date'[Year_Month])
		lineageTag: 9d148b09-2d55-41cb-af15-65289fa61e42

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalMultiplication"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AllThree_Total =
			
			SUM('Consultations'[PF_Total]) + SUM('Consultations'[BP_Total]) + SUM('Consultations'[OC_Total])
		lineageTag: 49e0befe-0919-4535-a9e4-0d8dc1d0d931

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalAddition"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Diff1
		lineageTag: 0be1eb38-4b2e-4ca0-82f3-589f2a6d0898

	column 'Pharmacy ODS Code'
		dataType: string
		lineageTag: 2a5d8b36-14ab-4692-876c-dbb764e539b3
		summarizeBy: none
		sourceColumn: Pharmacy ODS Code

		annotation SummarizationSetBy = Automatic

	column Consultation_Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0d490208-5581-4118-bbb4-46feb1084175
		summarizeBy: none
		sourceColumn: Consultation_Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Contract Type'
		dataType: string
		lineageTag: 154029b2-5618-4d25-9c29-e41431912fcc
		summarizeBy: none
		sourceColumn: Contract Type

		annotation SummarizationSetBy = Automatic

	column '100 Hour Pharmacy'
		dataType: string
		lineageTag: c37fa90e-57fe-4b92-8387-8246c71f89fc
		summarizeBy: none
		sourceColumn: 100 Hour Pharmacy

		annotation SummarizationSetBy = Automatic

	column PFOpt
		dataType: int64
		lineageTag: 75ccf416-8dc8-46f3-aaad-f10fc8d8eeaa
		summarizeBy: sum
		sourceColumn: PFOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BPOpt
		dataType: int64
		lineageTag: a0555771-6306-4e87-bc5c-cb40ca4030ce
		summarizeBy: sum
		sourceColumn: BPOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OCOpt
		dataType: int64
		lineageTag: 793d6fc6-1fd5-4b29-88e9-2c286a2267a8
		summarizeBy: sum
		sourceColumn: OCOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AllThreeOpt
		dataType: int64
		lineageTag: fc737755-bdbd-48b9-9220-a2e3e911221f
		summarizeBy: sum
		sourceColumn: AllThreeOpt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ABPM
		dataType: int64
		lineageTag: 70233e08-91c4-474c-818c-f09f6686f994
		summarizeBy: sum
		sourceColumn: ABPM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CLINIC
		dataType: int64
		lineageTag: 775d0eca-3b0a-4eca-b699-1d876ba121a5
		summarizeBy: sum
		sourceColumn: CLINIC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BP_Total
		dataType: int64
		lineageTag: 2e636e42-32cd-4325-bc79-480b78abad66
		summarizeBy: sum
		sourceColumn: BP_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Initiation
		dataType: int64
		lineageTag: 982eb05c-d71d-4023-9a1b-b58db3f05380
		summarizeBy: sum
		sourceColumn: Initiation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ongoing provision'
		dataType: int64
		lineageTag: 2e5509ea-988f-43aa-afa4-a237e587ba7b
		summarizeBy: sum
		sourceColumn: Ongoing provision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OC_Total
		dataType: int64
		lineageTag: d7a9daf5-be29-4060-a5ce-3b7dc1828f5b
		summarizeBy: sum
		sourceColumn: OC_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Clinical pathways consultation'
		dataType: int64
		lineageTag: 77d35759-8cc3-43e7-b86d-5f9d1d99c8bb
		summarizeBy: sum
		sourceColumn: Clinical pathways consultation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Minor illness referral'
		dataType: int64
		lineageTag: da781802-a9aa-4863-b244-9fdec3776e01
		summarizeBy: sum
		sourceColumn: Minor illness referral

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Urgent medicine supply'
		dataType: int64
		lineageTag: ed3772e5-7c76-4799-a713-6424744147fc
		summarizeBy: sum
		sourceColumn: Urgent medicine supply

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PF_Total
		dataType: int64
		lineageTag: 048251de-2eba-4920-a30a-f5d5aead1130
		summarizeBy: sum
		sourceColumn: PF_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Acute Otitis Media'
		dataType: int64
		lineageTag: 78071b10-0ea0-43e0-a046-6d784bf7309d
		summarizeBy: sum
		sourceColumn: Acute Otitis Media

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Acute Sore Throat'
		dataType: int64
		lineageTag: fa8fe947-d96a-4969-93ad-662811e23bcc
		summarizeBy: sum
		sourceColumn: Acute Sore Throat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Impetigo
		dataType: int64
		lineageTag: f89a7928-cb01-43bf-a586-770dbfe8f065
		summarizeBy: sum
		sourceColumn: Impetigo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Infected Insect Bites'
		dataType: int64
		lineageTag: dff5bee4-b8a7-4aa6-a13c-2f8c13978c70
		summarizeBy: sum
		sourceColumn: Infected Insect Bites

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Shingles
		dataType: int64
		lineageTag: 7bef0ef3-62a9-481a-bdc4-31badfa28769
		summarizeBy: sum
		sourceColumn: Shingles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sinusitis
		dataType: int64
		lineageTag: e8dc3b95-23a7-4462-8b9f-a8c5e99a5aea
		summarizeBy: sum
		sourceColumn: Sinusitis

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Uncomplicated UTI'
		dataType: int64
		lineageTag: 47bc3ac6-21a6-4244-ad67-9c4f22583dc3
		summarizeBy: sum
		sourceColumn: Uncomplicated UTI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 3xService_1+Consultation = IF ( ( IF(Consultations[PF_Total]>=1,1) + IF(Consultations[BP_Total]>=1,1) + IF(Consultations[OC_Total]>=1,1) ) = 3, 1)
		formatString: 0
		lineageTag: 8cb7b6e0-57e7-4065-966c-53ee62372f96
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 3xService_NoConsultation = IF ( ( IF(Consultations[PF_Total]>=1,1) + IF(Consultations[BP_Total]>=1,1) + IF(Consultations[OC_Total]>=1,1) ) = 0, 0)
		formatString: 0
		lineageTag: e2167ad4-40ff-41f8-a6f1-eaf8b817bacf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column OP_plan_total = 'Consultations'[Clinical pathways consultation] + 'Consultations'[BP_Total] + 'Consultations'[OC_Total]
		formatString: 0
		lineageTag: 0a1037fe-5f3d-4098-875c-0a17e71623dc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Consultations = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "BIReports", [Query="SELECT * FROM PowerBI_Reporting.primarycare.[tbl07_Pharm_Consultations];"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PFOpt", Int64.Type}, {"BPOpt", Int64.Type}, {"OCOpt", Int64.Type}, {"AllThreeOpt", Int64.Type}, {"ABPM", Int64.Type}, {"CLINIC", Int64.Type}, {"BP_Total", Int64.Type}, {"Initiation", Int64.Type}, {"Ongoing provision", Int64.Type}, {"OC_Total", Int64.Type}, {"Clinical pathways consultation", Int64.Type}, {"Minor illness referral", Int64.Type}, {"Urgent medicine supply", Int64.Type}, {"PF_Total", Int64.Type}, {"Acute Otitis Media", Int64.Type}, {"Acute Sore Throat", Int64.Type}, {"Impetigo", Int64.Type}, {"Infected Insect Bites", Int64.Type}, {"Shingles", Int64.Type}, {"Sinusitis", Int64.Type}, {"Uncomplicated UTI", Int64.Type}, {"Consultation_Month", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

