table 'REF_Reporting_Pharmacy_ODS_codes (semi-auto)'
	lineageTag: cb7e4c3e-d8cb-4047-94d6-50df4c6dbb21

	column 'Pharmacy Trading Name'
		dataType: string
		lineageTag: 18d2109c-5d9e-420f-88c9-3a4835e1298d
		summarizeBy: none
		sourceColumn: Pharmacy Trading Name

		annotation SummarizationSetBy = Automatic

	column first_entry
		dataType: dateTime
		formatString: General Date
		lineageTag: 794afdde-5f8b-45ff-b6a6-14bf1beea590
		summarizeBy: none
		sourceColumn: first_entry

		variation Variation
			isDefault
			relationship: 6997cdf8-2012-4ef2-96c9-8b0c57346404
			defaultHierarchy: LocalDateTable_59830ff0-726b-428b-a1df-025810fb3201.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column last_entry
		dataType: dateTime
		formatString: General Date
		lineageTag: ce1f7da2-9790-4819-a002-162a2c666a4f
		summarizeBy: none
		sourceColumn: last_entry

		variation Variation
			isDefault
			relationship: 8e028af7-5f9d-4dae-acb2-b906caa4a7d3
			defaultHierarchy: LocalDateTable_3def8eac-abed-4cf3-8f96-f287ec274368.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column active_ODS
		dataType: int64
		formatString: 0
		lineageTag: dce18bd5-4d9b-4d4c-825a-d03625614e4c
		summarizeBy: sum
		sourceColumn: active_ODS

		annotation SummarizationSetBy = Automatic

	column ODS_change_recorded
		dataType: int64
		formatString: 0
		lineageTag: 8276e7da-4915-48d5-9bc7-9b90cecd2193
		summarizeBy: sum
		sourceColumn: ODS_change_recorded

		annotation SummarizationSetBy = Automatic

	column Reporting_ODS
		dataType: string
		lineageTag: 09199e2a-309a-4e1f-b74a-0d80986072f0
		summarizeBy: none
		sourceColumn: Reporting_ODS

		annotation SummarizationSetBy = Automatic

	column 'Pharmacy ODS Code'
		dataType: string
		lineageTag: b905340c-6379-48ae-b4f0-15dc95a55c4a
		summarizeBy: none
		sourceColumn: Pharmacy ODS Code

		annotation SummarizationSetBy = Automatic

	partition 'REF_Reporting_Pharmacy_ODS_codes (semi-auto)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rdnbbuM2EAbgVzFyvSl0PvSOoWhJNiXZFG3F2OYx+v4l/7HsYut0E3OADTZQgE/yiJwZjn/+fNmKXVG+/HgRWkth1ObQCTMIeXGXkijJXqPkNYo3UfQn/tHV/DUqfrkaux//P3EfPxw86OgK96q5uZtWTyepZqvMs7cAjFtYWcUPbtFNetCqb7vNQRjRqGdvBB432u2K2t9obkRwhGBBFWmSuitvounEEB55r5F7THNG12tw5TaP+Vxo5A5lzeh6Da7apRmfCw3u1lQJnwsNblvnjOsBGtwuLyo+F9q6KxjXAzRyz3nJ6HoN7r6pGOMADa7e5YwuNHLPMWMcoMEd4zric6GRu9QFo+s1uIeyYNzH0OAek4wxDtDIPUeM+QEaXDPGjC40uOcsYly/0MiVnPsNGtyLihjrGzRyTcGYf6FRPT5nD553o/uht6p51odK+07XD+pnqA+V1nP2qO6H+lDhvxcJnl+ZvdLqEhx5eBT5LsWTT5Odn46zN659VVUGa96g7kTgL0EaDOodJPVQIRoM6hja8LjBoHquKH+HaDCoKnZZcNxg0N5J4jRUg0GVSufBnxQG7TtdFaEaDKoeR8pCIRoMOnrZIvgtwKBKoaPg9QaD9sIxRd0x07Tf9ko34b20F+lzd7m/IkU/ztJM8xxsQ6Q3ZHFe8efwgz7Nn2TaB9bnd4jx1ux6cmnHxK8o6WBtpzE8Lt6jjBHlCWSlrRpZzhleJLuoIrL92IDjuSFSNllKxLzrD4d+bDdSDIdGffkOv16Nbm/1dgq1dLr9zR0eWL95q/c7vC81PkM/NspsJxO+3iHSmjSYfMipU+O8ca9g6Gf7dPow6+jDmqQEqxXLA8Ojw/muTiHbeZm+vvU/fZGmWre+GEqfVhrhNqRa+vCdD5AmIEuWsdIAQTclyiUfDRD0EjE/NUAqfRKJqlFnZdTpPfwQJddEdTwk/mpjLqgP4bL3aOUNOJY0JzP7Lta93l6HN7NQqUgOhU+x297M1mURrcOPVF6kFm2p/LO7vehybPjIxWtUcHK8x3bTTUjcgQkEHPVtZe0fuP1jlUNPO96jHq6r/dVWq/OJYdrgteu0F13Jff49dz3HwD1d85O+oAR3YtmrfzUPSRSVodEBfT0D4ay2E4NiSIDH9aDWjBh17TrfAYanqHEdde0X7BkmFxqVxSUq+FxoVMpb/IXJhUYtlMBoQyvZadGErzp4FOEdGmLtm4/wxgwaFRdZ+g2uL83IMBKARplOJt4dhNkru5mtUYoh4XmUKrnBXwZh5y/2qe5q9WkXuSuvYcZvn7v1N3vHm7vkqOGDr+FiDF8Y8OiJU0yZXd7xh4JGifDVAZLCHGNfD65ecZwHwFEiyuuSYNO7SDPkIg9SqDOUrNHVq25x8Q6sheCuRTbyOXn66+8oSko5je4W63P3Lk1r+3TiB0032WOYe/AH36WX4Y0TQPqmmGZXZlrcEmzCQz7c5liLqVlleJRGDCYWswuHfTN904ZvHZBUZIsM+HSy3UYqw5EBYVKfukUqmQ/h32WDouVRFr4guubRZ9bwSMOjqXydJZCnUXXTaQ4PNETKUfushm2mU8PVsQO9DkXi6s6bSYQfdEFeCy/hp4MyjTm1DLV3pY+7rGClAdLSzvGdsVWznDYuldiJowfO16+OhUZ7yszrW5tKEzpevrmP5841f3CA0plpyPl5oNQTVzjg2E5t/jN9udcgZ6XfHF/eJjDdgnRuT9stx/dE4CgyUezf69KPspPT8PblsMSfdW5yWTMjfvsf+/uTv7vd6NR3K8tkfRfElL+A0m5qkdSXyyBcJ8QzL4H58fEP", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Pharmacy ODS Code" = _t, #"Pharmacy Trading Name" = _t, first_entry = _t, last_entry = _t, active_ODS = _t, ODS_change_recorded = _t, Reporting_ODS = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Pharmacy ODS Code", type text}, {"Pharmacy Trading Name", type text}, {"first_entry", type datetime}, {"last_entry", type datetime}, {"active_ODS", Int64.Type}, {"ODS_change_recorded", Int64.Type}, {"Reporting_ODS", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

