table 'REF_Pharmacy_Name (manual)'
	lineageTag: 8374bc41-d324-46af-a44d-fa3f89f6dd5c

	column Reporting_ODS
		dataType: string
		lineageTag: e9f161d8-4f07-4bb3-9b9f-93acc3658bac
		summarizeBy: none
		sourceColumn: Reporting_ODS

		annotation SummarizationSetBy = Automatic

	column 'Pharmacy Trading Name'
		dataType: string
		lineageTag: 86f768b6-9f35-4308-8149-93ed95b553c2
		summarizeBy: none
		sourceColumn: Pharmacy Trading Name

		annotation SummarizationSetBy = Automatic

	column 'Pharmacy Name'
		dataType: string
		lineageTag: 53e2b427-3e31-42c4-a626-c66f990a3b92
		summarizeBy: none
		sourceColumn: Pharmacy Name

		annotation SummarizationSetBy = Automatic

	column Organisation
		dataType: string
		lineageTag: 5204403f-5b78-473b-a2c7-8a2d9edc87c4
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column 'Organisation Type'
		dataType: string
		lineageTag: 68600b13-e370-4e6c-bbee-3a310fdc2f0f
		summarizeBy: none
		sourceColumn: Organisation Type

		annotation SummarizationSetBy = Automatic

	column 'Possible discrepency'
		dataType: int64
		formatString: 0
		lineageTag: 877018ee-df9e-4ba0-852f-d72178e03628
		summarizeBy: none
		sourceColumn: Possible discrepency

		annotation SummarizationSetBy = Automatic

	column Note
		dataType: string
		lineageTag: e77a585c-9756-4b13-bb05-e1ededbfa595
		summarizeBy: none
		sourceColumn: Note

		annotation SummarizationSetBy = Automatic

	column PCN
		dataType: string
		lineageTag: 04288201-4a88-453b-a727-6c46c34a0e21
		summarizeBy: none
		sourceColumn: PCN

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: c17f1dbe-742e-4efa-ae6e-da49a70b1c10
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	hierarchy 'Organisation Type Hierarchy'
		lineageTag: e2808de5-46a9-4caa-8e0f-1b38976b17c8

		level 'Organisation Type'
			lineageTag: 65350c1b-d767-4abe-b85a-5991f53f7492
			column: 'Organisation Type'

		level Organisation
			lineageTag: 3b8d446e-a872-4415-bd3a-f10846b35b91
			column: Organisation

		level 'Pharmacy Name'
			lineageTag: 7ffa02b5-87e8-48ca-94ea-f3edb965ccdf
			column: 'Pharmacy Name'

	hierarchy 'Locality Hierarchy'
		lineageTag: 95fe6858-c403-424a-8745-cafeb114e3c0

		level Locality
			lineageTag: 3ba5981e-551b-4e71-a211-8d767c0f2d44
			column: Locality

		level PCN
			lineageTag: eee6b63c-41e8-4e44-a676-81994cb4d825
			column: PCN

		level 'Pharmacy Name'
			lineageTag: 6d37c056-9e31-45b5-8597-c77792e17138
			column: 'Pharmacy Name'

	partition 'REF_Pharmacy_Name (manual)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zVttd6LIEv4rnHy6c85kjhpfP91DAEXDiwLK5OzdDx3pRE4IeAHHzb/f6sYoDQhIzOx+2J1YtNTT1dVVT1W3f/xxM+Zn/cHN9xteUQTekLi5zBsqLzwSkecJKMTcfIPCN7R+LxZNfQdvMfzPj+GTEUT4Cfmv3P92rVanz92jMA78FxRjeDjxgt0aRzEOOcGNyZdb8N/Nn98BhiUM2wmMqSQeUXCyrqiKNJ3I3Jw3eFFKMLjYOUL4zsmB9+Zh92XDzVGIHJwfk4MpI2eP/Q+Qix12XrCH3wsxtnPvc3HERXgLymLMBeFLxCHfIX9w8fsW/zeZkKq0BgUTmij6UpBMSzKKpmIGu3hDrMWZ8b9jGrNZf0S+aYo84xv0c8oxMp/N3RbD3+ErpvOIAHOFA4AiAvGeF2VeTau6R84GvaWMxHu/XD8xUOYZcUD84gY+8lhtU98/6SxDoazag3oo7sNg/boPwnhThUMjg6ht6fJyJ/0VYAyt3akHRtjswvWGMxzA5UabYBtxgofxL1yFTdhgL8Y+HYBDd7vBYUbOIOIXd71LEDnB3v8y8wjqYFQTDLWFBzoiTsWOu0YeJ8AWCq9tH2Hcq+nEMt57OI5hyS6AQDGX6deUUYFJOGWqTi1JLMRB4qYZf+csvH+NqrBYtmaSf2Asjp524UdgyXyJU2Lnxym2xAGXGXAILqtua1jTXEEYPWHIPGL4Zf60WLVqbjdAA1mNbreP0FYKqU784+86d/W0P7j+S7RH71VaG+fi+aDfrQdFCXyHGuIaFlh0uq3aal882NF+pcM2doaVMKzpmmoQQs7l+F/4t0Q9rT2qaSUNuV5UK0OZYMvQh5iEPDrYjMNg51B09xhyOJnfCnmYAfIg1rWQhveHSFWKwoYZc+MgJP8Ez5yIEbGitcF54QmF3OvXRDEn7yAx67KYWyfsa/aoXxeEC5GMENXXJrH2pHJsDGsGq8UOvUeuU5nqmtCl2apXky6Z7l8QsqK07muugDS7qxmyzJibYCC5QH7n3pVRPBr9mjHcjINXfH1HfJRaNfkZANjfBv5tvMG3duBVAknilRDEEFE8h8Td9N8pAj3r1dyP5t6tmTxSRoDVm6OdRzPaIDpviEW3iIiVEaHlFioWznCjCNIr5MnPGeQTpGgy6tV0InuDnIstWMkh+VW3wIfKTGdDngEYCaP+gkD7CWP+7HcoIZaMB0mRHhlzfmS2dEgqkLEldzYf1kqVipwwG123SEi/D8BT0qXkLorQC849IV6G4mOSTjQJQZS4WV3lC2XYL1EubNAWe7QEEJIcXYKh0ex5+a5dBsANsX+kPqUWoEypOgbJk1KFEoriU4+lTGGTlGgsku1zRvkYueFzEDpXmqrWad+VaJsgz0MvGxLYcAx08Eg8SlRfEismQlKCn1F/LC7vQ1zpW43on2X1y3bWEQCD/1qzl/hWLeXJLqla8SYcnF8MB3UQHIv7EgDlfHMmJTXhGU2HQlAOdhHmVNdfb5IUvT1k0i+Ia3OlV4YIPB2SEoTV6m3eKKqtlFZZkEk3Y8t0X9LCTe27xR1lWYauP4ynkiIyiS0MgtdnF3tM57hYyia3xkWpJffIB4GfaqZg6KaZxiMg14/WYRCdbMD9J2lFf6t+zCK8YJc0bHgbFq0kyGHIXFmaRQTI3KCdj16ZJS2SNYZObAlF8/FdPyin2r1hTgtiLsRbDybjvxAS7+MN3XNHtYl/aB2S8wXArli6xqwGDPRI9yoFtEjGgr+wDpFbvQ7VLymWpGV4bPpdp2pgG8KMSLuqeEQZospALfeHrQQOOXjJGYQ6dc4kRdLMitZM0oo9oC4lT+fzqTbhBF6di1IGhLvdkiUFDraF17NQzj8r2r/VgKykc/7vAfTTHlELTTVRMsa6wcQzAepETElTKkDAK+C9t8H2W60RLKwDoZiEGJdyDEqafI68yUNP2PsIEQY9ExN0WdJMDrxKnZoWndsG+xHhGm9uFBcJGjA8y+gMqDJFyhkm8HDBpBUveHeib3UGsGa5kIGdsc54NrqjgC3T1pUM4MMMGW8qEl7iRu2jrYwhTYuWLHE59ZxiiV8GIXUCZHeJJ4s8KJTsKZMIRQR1K967TO2HQyiUZdfzCgfcfJ4iiwNafNZHFAbIoawRUlAy+Spc5dSRVwfDSwDM31EYc0IdxY0MYrcuWyITO4c5VcGpG1cOhblAk7QorSRDWv5kYBCugHd/pfUUyVgfLV+GxbxDdopoPFLayKgL358IPWTUFciaRdFDWFBpa1JcGiZpxIBXTBWmHyPuwohwoDF6cz2mA3P+yRV6Myu1T6jKeGqYFiRCRUljGrshTEeAKjqttVjKYln6r35yDHT6K1VN2UNiDAjowEgYhYkBmXh9e4rXRY+/OJxPetRLJ5ysU+Z0SneTj3PQ01bhow0w+ec429XJDc2BLU+H7YJ3AJs/9EAGI2LMyY8PiCemXgBRpZdSuLn3WzHO5RF9rkirJUOGJx7+tWNobl7S/NJP+niZpsbT9SNTnrLXvU7fjjYue8er5NElXq880qpA5u0HKVVYdVqtQWrNZETCV1pHXnK2FKh7PjDptQiF05OBgq5puvGBaArgErIg79ZrD6+DmJlysfRTlTQNzO7zMwR4P+agmHEIvfbRG/7o89A29oxXJSZdzWAEY5icoHnR9HNCu1szmXQ4GKWbbP86fRUq8/TmOqfeokbvZdUAIwQhKCMpmTP/X4Wngec82DRf1EAiQ3H+/hTsQh9zNr2ucW0sht3q18OSDhOlKBpfGuH7XeLFpr60ZE6QDI09bVHQLsQeo7VAdGm8LdszMk8PYxVJkBVeZEKdgtcbDznM/i2SNSv3H2a0GaaQYpapqRVSpjL5JS+50nVaWxiQnKg8itl1eHf81PlWpkwuf/oV9GImdAhQlTceJIszLUOSGEJ0SNdA5TCO04Y6++AzJFUwaMxTectkm0QqiiOWGuQlrOImZ0fWbHD3D6q3e7QwUklhxGsSCwAqH+RjFkJedgVCbt3RC05AB0j7UJR41hJuvIZg6MDKMViKxZ/yhTYN9Cpw9EzHUIUvZYhigahZ/0DsjQaJVmMKTmBm9IYurHqU0ZwXstevG2QWu0s5NbAiS7bBH06sn05kD0uf6mrlRZcUprZBL60aug1eJzIzNoJ9cms3RTYgoYKlb3X/1iJ3V1BCHnIji4hHtfnV5ECzJhbIGa9gucMhVwWEC1voM4OeL5n8VLPujak4YfajCbE0fgpdSOrMuheL2dWocxdzPKaRyJwzt/7NLWK0sR+bU83JoE94DJTCJA8wVgeHJZGe9e4CWXPlj6NuhyrXNUnWlyZr54ITlnPSTx33HGLfQ3dEsRj6UizokRxekm+EnH1wBVByqz08gTJ0XiyAZJCmYR5QVvz5JLWYdamvLOeSIRrLCYOFhD0n3L1UXgHIjzy7WSsd6GGW2OdiRMd7AVVomt0N6NEf1FiSKejcVAP/Zut9C0frAOx+C96cqumzbZEzw3JJpi475hVayjaAFXjkFxNR8hOAurCa9AZWo2aGSxdZdfE1Zvia2muGEsygR3tETjvo/by6SOukDTE5PG8CKkQxPaoiP6o4bozaztdkg0we6AX2Obm0YE8FpiNOuOGcXEzYu2umBX72QSbQNrzUItuUC1nL8ThzXdHaPT97TG12uiNR9uy3/2JQsCl1sKeaIAu6es84gE2uBq2DtydmMYuln7qBoLXa3X8ehajcETZv6xYpIfL53A5iUjXk0/bZB1cosPgJZVv2o8pDfZE7DLLf3xBUE/fZw59z8k/1Yv/8Gw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [PharmacyCode = _t, #"Pharmacy Trading Name" = _t, #"Pharmacy Name" = _t, Organisation = _t, #"Organisation Type" = _t, PCN = _t, Locality = _t, #"Possible discrepency" = _t, Note = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PharmacyCode", type text}, {"Pharmacy Trading Name", type text}, {"Pharmacy Name", type text}, {"Organisation", type text}, {"Organisation Type", type text}, {"Possible discrepency", Int64.Type}, {"Note", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"PharmacyCode", "Reporting_ODS"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

