table 'Admissions Falls'
	lineageTag: acb7f50a-86d6-447e-9a94-67d48d4aea43

	measure '% Admitted' =
			CALCULATE(SUM('ED Falls (GHFT Only)'[admitted_flag])
			/
			SUM('ED Falls (GHFT Only)'[counter_ED_falls]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 89489461-fb58-4a5b-bfd1-5735591de09a

	measure 'Locality Rate Per 1000 Falls Admissions' =
			
			
			VAR ACTIVITY = CALCULATE ( sum('Admissions Falls'[Number of Admissions]))
			VAR POP = CALCULATE ( 'Practice Population'[April Population for Yearly Rate], ALLEXCEPT ('Date Table', 'Date Table'[Financial Year] ) )
			
			RETURN (ACTIVITY/POP*1000)
		lineageTag: de939e67-7438-4036-b01b-b68110a8babb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure count_of_pop_PCN = count('Place Population'[Primary Care Network])
		formatString: 0
		lineageTag: 950fa3db-f9da-412b-9fd2-416af17be761

	measure count_of_ED_PCN = count('ED Falls (GHFT Only)'[primary_care_network])
		formatString: 0
		lineageTag: a2da525d-e1ca-4211-9afd-ee8642c629aa

	measure ed_PCN_rate_per_1000 = ('Admissions Falls'[count_of_ED_PCN]/'Admissions Falls'[count_of_pop_PCN]) * 1000
		lineageTag: 7314adef-40cf-4471-8899-373c2c60617f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Year ED Admissions' = CALCULATE(sum('Admissions Falls'[Number of Admissions]), 'Admissions Falls'[Admission year adjusted] = 'Admissions Falls'[Admissions previous year])
		formatString: 0
		lineageTag: 36c76f91-593d-43d1-bed6-02e475cd6cc6

	measure 'Comparison Previous YTD ED Admissions' = CALCULATE(sum('Admissions Falls'[Number of Admissions]), 'Admissions Falls'[Admission year adjusted] = 'Admissions Falls'[Admissions previous year] && 'Admissions Falls'[Admissions YTD] = "Year to Date")
		formatString: 0
		lineageTag: b4e18ade-075a-4535-a705-8233205255c1

	measure 'Current Year ED Admissions' = CALCULATE(sum('Admissions Falls'[Number of Admissions]), 'Admissions Falls'[Admission year adjusted] = 'Admissions Falls'[Admissions current year])
		formatString: 0
		lineageTag: 5ea82a9e-648d-4e25-854b-95cb91b5ec02

	measure 'Dementia rate per 1000' = sum('Admissions Falls'[Number of Admissions])/sum('Dementia population'[COUNTER])*1000
		lineageTag: 9562dba0-9f62-41b5-b079-72e83a98fa9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frailty rate per 1000' = sum('Admissions Falls'[Number of Admissions])/sum('Frail population'[COUNTER])*1000
		lineageTag: 47d3649f-edc6-4ceb-9ac9-452a942e23b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Care home rate per 1000' = sum('Admissions Falls'[Number of Admissions])/sum('Care home population'[COUNTER])*1000
		lineageTag: 2432e685-b1ce-49a5-be4b-35c6fbb80979

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Died in hospital %' = sum('Admissions Falls'[Died in hospital flag])/sum('Admissions Falls'[Number of Admissions])*100
		lineageTag: 0729ef87-4412-4db3-b1c9-def79c5bf4b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cheltenham Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Cheltenham")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cheltenham"))*1000
		lineageTag: d68a795a-aa69-406e-a8c4-308732e9ce8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotswolds Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Cotswolds")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cotswolds"))*1000
		lineageTag: fae03319-085d-42ee-94ee-e4fbe262ed21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gloucester Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Gloucester City")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Gloucester City"))*1000
		lineageTag: 847cc75c-a714-42c6-b094-1cd27803e1e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'S&BV Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Stroud and Berkeley Vale")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Stroud and Berkeley Vale"))*1000
		lineageTag: 7dd4bb8c-9d31-4bcf-a8e0-390950f347f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FOD Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="The Forest of Dean")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="The Forest of Dean"))*1000
		lineageTag: f5767bbc-2d6d-4207-bd34-54b0356b681f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TWNS Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[locality]="Tewkesbury Newent and Staunton")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Tewkesbury Newent and Staunton"))*1000
		lineageTag: b316a802-a0f2-4c17-94fb-f7255187c6ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fit Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Fit")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Fit"))*1000
		lineageTag: 070e18a6-02d0-4235-b6be-b4ca883b5cb5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mild Frailty Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Mild Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Mild Frailty"))*1000
		lineageTag: 3930b93d-886d-418b-bcbe-bc09d49a9b31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Moderate Frailty Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Moderate Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Moderate Frailty"))*1000
		lineageTag: 2821cd3b-8e7d-47f3-980a-73680bea48d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unknown Frailty Rate Per 1000 Falls Admission' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Unknown")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Unknown"))*1000
		lineageTag: 4b13edd7-c15a-4855-8f06-05678ea12e8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LD Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="LD")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="LD"))*1000
		lineageTag: 01865da5-c1fc-4a7d-80ba-e69513fe2ffa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Non-Care Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Not Living in a Care Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Not Living in a Care Home"))*1000
		lineageTag: 1e06c83f-dbfd-4dee-9ee0-148662c4b06e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nursing Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Nursing")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Nursing"))*1000
		lineageTag: 5bf350e8-3ffa-400e-b419-c215d9127d04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Residential Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Residential")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Residential"))*1000
		lineageTag: 3833c409-fa85-4251-87d3-d27730df77f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unknown Care Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Unknown Care Home Type")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Unknown Care Home Type"))*1000
		lineageTag: df37d53a-3ce3-4370-a10f-9922889ef923

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Severe Frailty Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[frailty_category]="Severe Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Severe Frailty"))*1000
		lineageTag: c81970c8-eb92-4e59-92a2-f9876a1a56ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Has Dementia Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[dementia_status]="Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="Dementia"))*1000
		lineageTag: 663a814c-8a44-4fec-a06f-a0b5f67f83c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Dementia Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[dementia_status]="No Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="No Dementia"))*1000
		lineageTag: 89e9472b-0205-44a0-a046-99e9c84ac95f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deaths 30 Days After Admission' = calculate(count('Admissions Falls'[Number of Admissions]),FILTER('Admissions Falls',[death_in_days_from_admission]<31&&'Admissions Falls'[mortality_flag]="Deceased"))
		formatString: 0
		lineageTag: 92e7e68a-8561-4cd7-91d1-4231c767ac99

	measure 'Deaths 90 Days After Admission' = countrows(FILTER('Admissions Falls',[death_in_days_from_admission]<91&&'Admissions Falls'[mortality_flag]="Deceased"))
		formatString: 0
		lineageTag: 50a756d3-37c4-472a-8cd0-8c008bced26e

	measure 'Admissions with death after 90 Days After Discharge or No Death' = countrows(FILTER('Admissions Falls',[death_in_days_from_discharge]>90||'Admissions Falls'[mortality_flag]="Alive"))
		formatString: 0
		lineageTag: b87e87a8-5c1b-497e-b679-0383a22e81bb

	measure '% #FNOF' = ```
			
			divide(
			    CALCULATE(
				SUM('Admissions Falls'[Number of Admissions]),
				'Admissions Falls'[icd_10_description] IN { "S720 Fracture of Neck of Femur"  })
			    ,sum('Admissions Falls'[Number of Admissions]))
			
			
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 002c2e33-9931-4fe0-b197-3b9de930bbc1

	measure Max_Admissions_Date = ```
			CALCULATE(MAX('Date Table'[Date]),FILTER('Admissions Falls',[discharge_date]))
			
			 
			```
		formatString: General Date
		lineageTag: f805e40b-b810-4cbb-9b84-44c046135fbb

	measure Min_Admissions_Date = ```
			CALCULATE(MIN('Date Table'[Date]),FILTER('Admissions Falls',[discharge_date]))
			
			```
		formatString: General Date
		lineageTag: 4a3600c6-e0f1-44cc-8a39-cad808a1886f

	measure Number_of_days_admissions = DATEDIFF('Admissions Falls'[Min_Admissions_Date],'Admissions Falls'[Max_Admissions_Date],DAY)
		formatString: 0
		lineageTag: b7d6127d-f499-48a3-a3d4-9b96b7aa42ac

	measure Average_admission_falls_per_day =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Date Table'[DayMonthYear])),
				CALCULATE(SUM('Admissions Falls'[Number of Admissions]))
			)
		lineageTag: 0ff496c8-54a0-4904-9b94-d8c8650ac4e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MH Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Mental Health")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Mental Health"))*1000
		lineageTag: 12bbbedf-6734-4b9c-8247-b7c3bd2568dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median LOS' = MEDIAN('Admissions Falls'[length_of_stay])
		lineageTag: 39963f9e-6925-4a61-94df-a5710c6e4a29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Over/Under YTD Comparison Admissions' = ('Admissions Falls'[Current Year ED Admissions] - 'Admissions Falls'[Comparison Previous YTD ED Admissions]) / 'Admissions Falls'[Comparison Previous YTD ED Admissions]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f977b5a1-381b-4a20-84fe-fcbf8b10ebed

	measure 'New rate per 1000 monthly' =
			
			
			VAR activity = CALCULATE(SUM('Admissions Falls'[Number of Admissions]))
			
			VAR POP = CALCULATE ( sum('Practice Population'[population]) )
			
			RETURN activity/pop*1000
		lineageTag: c13e0878-3094-450a-8c6a-cd3ccb2f3b00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'New rate per 1000 yearly' =
			
			
			VAR activity = CALCULATE(SUM('Admissions Falls'[Number of Admissions]))
			
			VAR POP = CALCULATE ( sum('Practice Population'[population]),'Date Table'[Month Name] IN {"Apr"}  ,ALLEXCEPT('Date Table','Date Table'[Financial Year]))
			
			RETURN IFERROR(activity/pop*1000, BLANK())
		formatString: 0
		lineageTag: 7932de80-c26b-4a7a-b5f4-f26945c27cfd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Care Home Admissions' = CALCULATE(SUM('Admissions Falls'[Number of Admissions]), 'Admissions Falls'[Care_home_status] <> "Not Living in a Care Home")
		formatString: 0
		lineageTag: 235dd8cf-9513-41aa-ba8b-c5b28304bff2

	measure 'Non-Care Home Admissions' = CALCULATE(SUM('Admissions Falls'[Number of Admissions]), 'Admissions Falls'[Care_home_status] = "Not Living in a Care Home")
		formatString: 0
		lineageTag: 048eb739-e405-414e-a7e2-ed5b90bf64bf

	measure '% Care Home Admissions' = [Care Home Admissions] / SUM('Admissions Falls'[Number of Admissions])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f28039a9-5751-4773-b968-e36f28e21d4b

	measure 'Gloucestershire Rate Per 1000 Falls Admissions' =
			
			
			VAR ACTIVITY = CALCULATE ( sum('Admissions Falls'[Number of Admissions]),ALL('GP Reference'))
			VAR POP = CALCULATE ( 'Practice Population'[April Population for Yearly Rate], ALLEXCEPT ('Date Table', 'Date Table'[Financial Year] ) ,ALL('GP Reference'))
			
			RETURN ACTIVITY/POP*1000
		lineageTag: f67f6f66-31b6-4309-a7b2-67d52813a073

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gloucestershire Falls Admissions' =
			
			
			VAR ACTIVITY = CALCULATE ( sum('Admissions Falls'[Number of Admissions]),ALL('GP Reference'))
			
			RETURN ACTIVITY
		formatString: 0
		lineageTag: 9cc070b2-9b8a-4694-b0fa-d91bdfcd9dfa

	measure '% #FNOF Glocuestershire' = ```
			
			divide(
			    CALCULATE(
				SUM('Admissions Falls'[Number of Admissions]),
				'Admissions Falls'[icd_10_description] IN { "S720 Fracture of Neck of Femur"  },all('GP Reference'))
			    ,CALCULATE(sum('Admissions Falls'[Number of Admissions]),ALL('GP Reference')))
			
			
			
			```
		lineageTag: b748ae4f-978a-4e46-b3ff-304d7d7834e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 10_year_age_band
		dataType: string
		lineageTag: 78bb55f7-eaf3-41cf-aec0-b270d5d6d05b
		summarizeBy: none
		sourceColumn: 10_year_age_band

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 15aec3b0-421a-4158-82ea-85d7f0b407ba
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column hospital_provider_spell_number
		dataType: int64
		formatString: 0
		lineageTag: a69ea1e8-a43d-4a3e-b201-ccfd5a37561f
		summarizeBy: sum
		sourceColumn: hospital_provider_spell_number

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: 2efde196-d8ef-4cd8-9c27-be2a42325f3b
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column site
		dataType: string
		lineageTag: dc774dd6-c224-401b-bb1e-c2564a9f54fd
		summarizeBy: none
		sourceColumn: site

		annotation SummarizationSetBy = Automatic

	column discharge_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 72db6a49-7138-4ed5-a813-8ef515e282fc
		summarizeBy: none
		sourceColumn: discharge_date

		annotation SummarizationSetBy = Automatic

	column discharge_date_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b9aa7c6-43a9-4bc0-8dd1-1b9efba29151
		summarizeBy: none
		sourceColumn: discharge_date_time

		variation Variation
			isDefault
			relationship: a7dbcfd0-b840-493c-8e49-aabc4a2ce7b7
			defaultHierarchy: LocalDateTable_dda466a7-b861-4f3c-8428-d554ab3c0fd1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 34f83085-7524-4365-889b-da7bfb503ca6
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 934ce9f2-497a-4f85-b017-4efb52a2b342
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: f373f2d7-8489-4237-8545-002393f2df66
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band
		dataType: string
		lineageTag: 072bca16-164e-414c-b51b-3dfba48846ca
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: bc447328-98c4-4b71-9201-58d960de4662
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column practice_name
		dataType: string
		lineageTag: ec93b7cd-b7db-423c-9dca-d06bddd5a464
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

	column primary_care_network
		dataType: string
		lineageTag: 6b315a21-ecb1-4f8e-8dea-5cd65910afe4
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: 7f6317dd-c09e-40f9-8f8d-1f047cb86f2b
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column hrg_code
		dataType: string
		lineageTag: 4ddafa9e-c9a5-430b-8688-53eee1d744dd
		summarizeBy: none
		sourceColumn: hrg_code

		annotation SummarizationSetBy = Automatic

	column length_of_stay
		dataType: int64
		formatString: 0
		lineageTag: b666dabb-9d65-48dc-bd9b-b4755de7cf06
		summarizeBy: sum
		sourceColumn: length_of_stay

		annotation SummarizationSetBy = Automatic

	column 'Number of Admissions'
		dataType: int64
		formatString: 0
		lineageTag: 0676af4e-09bc-4bd8-a6dc-9c409dab17f2
		summarizeBy: sum
		sourceColumn: Number of Admissions

		annotation SummarizationSetBy = Automatic

	column primary_diagnosis_code
		dataType: string
		lineageTag: 08ec44d8-f260-4fe7-9d2c-57dea40c696a
		summarizeBy: none
		sourceColumn: primary_diagnosis_code

		annotation SummarizationSetBy = Automatic

	column icd_10_description
		dataType: string
		lineageTag: 97a089b9-b1c4-4324-be4d-adcfb7909f76
		summarizeBy: none
		sourceColumn: icd_10_description

		annotation SummarizationSetBy = Automatic

	column primary_procedure_code
		dataType: string
		lineageTag: 35bc077d-70ef-40e1-b78c-15fb220dc60a
		summarizeBy: none
		sourceColumn: primary_procedure_code

		annotation SummarizationSetBy = Automatic

	column emergency_admission_fnof_flag
		dataType: int64
		formatString: 0
		lineageTag: 56623ed3-11bd-4372-811c-d1c374ef2098
		summarizeBy: sum
		sourceColumn: emergency_admission_fnof_flag

		annotation SummarizationSetBy = Automatic

	column living_alone_status
		dataType: string
		lineageTag: 59f93984-f115-4853-bd0e-b323ad3f4e32
		summarizeBy: none
		sourceColumn: living_alone_status

		annotation SummarizationSetBy = Automatic

	column frailty_score
		dataType: double
		lineageTag: 0ff0aaa7-3339-4d74-8d7c-63d2d5a1093d
		summarizeBy: sum
		sourceColumn: frailty_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column frailty_category
		dataType: string
		lineageTag: 7bbd52f6-5e1c-4ec0-9e39-b0876d34abf8
		summarizeBy: none
		sourceColumn: frailty_category

		annotation SummarizationSetBy = Automatic

	column 0-1_days_los
		dataType: int64
		formatString: 0
		lineageTag: e2d81486-caa4-4440-bab6-7c50aaaa39e3
		summarizeBy: sum
		sourceColumn: 0-1_days_los

		annotation SummarizationSetBy = Automatic

	column 2+_days_los
		dataType: int64
		formatString: 0
		lineageTag: 8ad67778-808a-44ad-9712-8b5c74a13893
		summarizeBy: sum
		sourceColumn: 2+_days_los

		annotation SummarizationSetBy = Automatic

	column 'Patient Discharged or Died'
		dataType: string
		lineageTag: 80c670a2-82c5-4d89-b6aa-9ae358fb4a16
		summarizeBy: none
		sourceColumn: Patient Discharged or Died

		annotation SummarizationSetBy = Automatic

	column 'Died in hospital flag'
		dataType: int64
		formatString: 0
		lineageTag: 5139da46-6fa1-428c-be40-48f60994f52f
		summarizeBy: sum
		sourceColumn: Died in hospital flag

		annotation SummarizationSetBy = Automatic

	column correct_practice_code
		dataType: string
		lineageTag: cf6e6b2d-5305-410e-8911-5fc618dbfaca
		summarizeBy: none
		sourceColumn: correct_practice_code

		annotation SummarizationSetBy = Automatic

	column deceased_nhs_number
		dataType: string
		lineageTag: 9aee5d82-1948-4673-a0f7-90f120038c3c
		summarizeBy: none
		sourceColumn: deceased_nhs_number

		annotation SummarizationSetBy = Automatic

	column mortality_flag
		dataType: string
		lineageTag: 0b2fab6d-9a0d-43fd-a128-d7b257ce663c
		summarizeBy: none
		sourceColumn: mortality_flag

		annotation SummarizationSetBy = Automatic

	column date_of_death
		dataType: dateTime
		formatString: General Date
		lineageTag: 95ebf5ed-b064-46be-a534-3801e6a7943d
		summarizeBy: none
		sourceColumn: date_of_death

		variation Variation
			isDefault
			relationship: 43dd2085-f49b-4c61-ad1f-66e81c572fb6
			defaultHierarchy: LocalDateTable_4aef56c9-1456-4fa4-953c-5f1e5d3d6a2f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: fe2b1aeb-7bf6-4eaa-b293-f9b9f39a00a7
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Grouped_Discharge_Destination
		dataType: string
		lineageTag: f88b6e17-614e-4c34-bad2-625187cbffb2
		summarizeBy: none
		sourceColumn: Grouped_Discharge_Destination

		annotation SummarizationSetBy = Automatic

	column death_in_days_from_admission
		dataType: int64
		formatString: 0
		lineageTag: 684da779-a185-4edf-8bbd-fa71e962e086
		summarizeBy: sum
		sourceColumn: death_in_days_from_admission

		annotation SummarizationSetBy = Automatic

	column death_in_days_from_discharge
		dataType: int64
		formatString: 0
		lineageTag: 746b28e7-03d0-4cdc-a23a-50321a426294
		summarizeBy: sum
		sourceColumn: death_in_days_from_discharge

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band_expanded
		dataType: string
		lineageTag: b1f2093b-d7d4-479b-a542-c46240503e25
		summarizeBy: none
		sourceColumn: 5yr_age_band_expanded

		annotation SummarizationSetBy = Automatic

	column PDS_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ece7dd0d-a76a-45e1-b6e8-ce527291a27e
		summarizeBy: none
		sourceColumn: PDS_date

		variation Variation
			isDefault
			relationship: fe9886b8-d5cc-46c5-a1c8-d241656db083
			defaultHierarchy: LocalDateTable_5f163ca8-8db8-4590-a0c5-9158b5590080.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Date_of_incident
		dataType: dateTime
		formatString: General Date
		lineageTag: db982ded-7dac-43e0-83a2-8d800b045d6f
		summarizeBy: none
		sourceColumn: Date_of_incident

		variation Variation
			isDefault
			relationship: b44da915-c37f-4dba-9dfc-532c4f380722
			defaultHierarchy: LocalDateTable_d9836565-8d3f-448a-96bc-1a74a613e88a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Care_home_status
		dataType: string
		lineageTag: 8fe49b5e-9706-41c5-91ea-de24b3e909b1
		summarizeBy: none
		sourceColumn: Care_home_status

		annotation SummarizationSetBy = Automatic

	column 'Broad Type (confirmed)'
		dataType: string
		lineageTag: 3cea863d-eed1-4525-a6d9-32b33bf62ff3
		summarizeBy: none
		sourceColumn: Broad Type (confirmed)

		annotation SummarizationSetBy = Automatic

	column 'Broad Type (old)'
		dataType: string
		lineageTag: 3f07f8b9-9968-4659-810e-cc439f314b9e
		summarizeBy: none
		sourceColumn: Broad Type (old)

		annotation SummarizationSetBy = Automatic

	column 'Admissions max financial month' = ```
			
			VAR currmonth = MONTH(MAX('Admissions Falls'[discharge_date]))
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 1f15623e-d77f-4dc0-a8b7-e4b42e4fe63d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Admissions financial month' = ```
			
			VAR currmonth = MONTH('Admissions Falls'[discharge_date])
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 9c8f1024-261e-4ef8-989b-08db2a04d116
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Admissions YTD' = if('Admissions Falls'[Admissions financial month] <= 'Admissions Falls'[Admissions max financial month], "Year to Date", "Not Year to Date")
		lineageTag: d527e127-53d2-468e-922d-0b8177538f89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Admissions current year' = ```
			
			VAR max_year = YEAR(MAX('Admissions Falls'[discharge_date]))
			VAR max_month = MONTH(MAX('Admissions Falls'[discharge_date]))
			VAR financial_month = SWITCH(TRUE(),
			max_month = 4, 1,
			max_month = 5, 2,
			max_month = 6, 3,
			max_month = 7, 4,
			max_month = 8, 5,
			max_month = 9, 6,
			max_month = 10, 7,
			max_month = 11, 8,
			max_month = 12, 9,
			max_month = 1, 10,
			max_month = 2, 11,
			max_month = 3, 12
			)
			VAR adjust_year = SWITCH(TRUE(),
			max_month = 1, max_year - 1,
			max_month = 2, max_year - 1,
			max_month = 3, max_year - 1,
			max_month = 4, max_year,
			max_month = 5, max_year,
			max_month = 6, max_year,
			max_month = 7, max_year,
			max_month = 8, max_year,
			max_month = 9, max_year,
			max_month = 10, max_year,
			max_month = 11, max_year,
			max_month = 12, max_year
			)
			return adjust_year
			
			```
		formatString: 0
		lineageTag: ecd2f81f-bc88-4e55-82db-8da4d9721f04
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Admission year adjusted' = ```
			if(
			    [Admissions financial month] = 10, YEAR('Admissions Falls'[discharge_date]) -1, 
			    if([Admissions financial month] = 11, YEAR('Admissions Falls'[discharge_date]) -1, 
			    if([Admissions financial month] = 12, YEAR('Admissions Falls'[discharge_date]) -1, year('Admissions Falls'[discharge_date]))))
			```
		formatString: 0
		lineageTag: b4bafa28-6c13-490f-b407-1862c4dd5347
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Admissions previous year' = 'Admissions Falls'[Admissions current year] - 1
		formatString: 0
		lineageTag: 4adada55-fc90-469d-b1a9-a39c3ac6e684
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Shortened_ethnic_category
		dataType: string
		lineageTag: 5af44b11-7726-49e1-ad5d-2557f82d22e0
		summarizeBy: none
		sourceColumn: Shortened_ethnic_category

		annotation SummarizationSetBy = Automatic

	column care_home_status_ranking
		dataType: int64
		formatString: 0
		lineageTag: 61e60cf5-6ed7-4b72-9929-ac88bc6e7a79
		summarizeBy: sum
		sourceColumn: care_home_status_ranking

		annotation SummarizationSetBy = Automatic

	column spell_patient_identity_nhs_number_value
		dataType: string
		lineageTag: b7b947f9-369d-4b36-8b5c-64437c542741
		summarizeBy: none
		sourceColumn: spell_patient_identity_nhs_number_value

		annotation SummarizationSetBy = Automatic

	column duplicates
		dataType: string
		lineageTag: a006d78b-c977-48ad-9d6e-573007b608a3
		summarizeBy: none
		sourceColumn: duplicates

		annotation SummarizationSetBy = Automatic

	column spell_discharge_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b053e30-95cd-41a1-87a9-9007c475fa2b
		summarizeBy: none
		sourceColumn: spell_discharge_date

		variation Variation
			isDefault
			relationship: dbb3433a-99f9-4367-aa57-acd46a99f5ff
			defaultHierarchy: LocalDateTable_e1668155-1232-4a7d-a067-a03b9ba42f95.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column StartDate_HospitalProviderSpell
		dataType: dateTime
		formatString: General Date
		lineageTag: 91bc47eb-fc5f-440a-af38-f48f742eb967
		summarizeBy: none
		sourceColumn: StartDate_HospitalProviderSpell

		variation Variation
			isDefault
			relationship: 04f8c30e-cec2-4432-873b-0a962829e6f5
			defaultHierarchy: LocalDateTable_f92feef3-9b0a-4e2f-8ab2-441f7d33f2fe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Care_home_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 90c8537e-91e1-4e8d-8733-e6971064d993
		summarizeBy: none
		sourceColumn: Care_home_date

		variation Variation
			isDefault
			relationship: e371724f-bd2c-42cd-a723-1bb90b03cfe0
			defaultHierarchy: LocalDateTable_f23b1170-5939-4338-9e44-d8206a11db92.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column End_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e09a9e8-09b8-4069-a3dc-e3dd955c72c7
		summarizeBy: none
		sourceColumn: End_date

		variation Variation
			isDefault
			relationship: 9b71364e-92a1-45ef-a6bb-f4a5b719f6cb
			defaultHierarchy: LocalDateTable_3015e1eb-35ec-4e3f-a50c-1c8acfaa89d0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column spell_discharge_destination
		dataType: string
		lineageTag: f9dbd47a-f9ff-4a2b-85f9-9eef3b7f1b51
		summarizeBy: none
		sourceColumn: spell_discharge_destination

		annotation SummarizationSetBy = Automatic

	column spell_discharge_method
		dataType: string
		lineageTag: 6535d8a3-0717-4986-9f75-cb6c8097f44c
		summarizeBy: none
		sourceColumn: spell_discharge_method

		annotation SummarizationSetBy = Automatic

	column spell_patient_identity_age_at_cds_activity_date
		dataType: int64
		formatString: 0
		lineageTag: afb2769a-1981-4868-9390-e0d6ee57b2d6
		summarizeBy: sum
		sourceColumn: spell_patient_identity_age_at_cds_activity_date

		annotation SummarizationSetBy = Automatic

	column spell_patient_identity_ethnic_category
		dataType: string
		lineageTag: 921103ed-460b-42c2-93d2-d76e859c229a
		summarizeBy: none
		sourceColumn: spell_patient_identity_ethnic_category

		annotation SummarizationSetBy = Automatic

	column spell_clinical_coding_grouper_derived_primary_diagnosis
		dataType: string
		lineageTag: 62072bbd-d39a-4073-81fd-078c0a5259ca
		summarizeBy: none
		sourceColumn: spell_clinical_coding_grouper_derived_primary_diagnosis

		annotation SummarizationSetBy = Automatic

	column primary_diagnosis_description
		dataType: string
		lineageTag: 8469e90d-8382-4fd8-b302-e3b318ea92c0
		summarizeBy: none
		sourceColumn: primary_diagnosis_description

		annotation SummarizationSetBy = Automatic

	column spell_clinical_coding_grouper_derived_secondary_diagnosis
		dataType: string
		lineageTag: 1b5c4015-8b06-470f-b24e-200e0ed6fa8c
		summarizeBy: none
		sourceColumn: spell_clinical_coding_grouper_derived_secondary_diagnosis

		annotation SummarizationSetBy = Automatic

	column secondary_diagnosis_description
		dataType: string
		lineageTag: 5f09d567-5250-4622-9f0b-b3da94b43c33
		summarizeBy: none
		sourceColumn: secondary_diagnosis_description

		annotation SummarizationSetBy = Automatic

	column dementia_status
		dataType: string
		lineageTag: fd3e2a56-757c-41fc-9e36-5be55186e473
		summarizeBy: none
		sourceColumn: dementia_status

		annotation SummarizationSetBy = Automatic

	hierarchy 'icd_10_description Hierarchy'
		lineageTag: 9e44340a-1f51-4678-bf6c-f07a1b4f6843

		level 'Admission Description (ICD10 Code)'
			lineageTag: 20dd6d55-caf2-4d3d-aaef-59c5916bd18f
			column: icd_10_description

	hierarchy 'locality Hierarchy'
		lineageTag: afbca03c-f875-4019-9793-739a86d398b0

		level Locality
			lineageTag: e96b80bc-c10d-4008-9458-532ef6fae63c
			column: locality

		level primary_care_network
			lineageTag: f11ef746-5811-41e3-8065-36eb380c0efc
			column: primary_care_network

	partition 'Admissions Falls-3f1d6f62-d376-41f4-b0c9-33296dc7f7ad' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select * from [PowerBI_Reporting].[Falls].[tbl01_Falls_Admissions]#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Died in hospital flag", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"counter", "Number of Admissions"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

