table 'Day of Week'
	lineageTag: 80991fff-61ac-4f6c-8acc-8485d5357ee8

	column Order
		dataType: int64
		formatString: 0
		lineageTag: e2edd0c9-1141-446c-8239-1d63a0354557
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: 46a1be77-62a8-499c-8649-2454e8fbceeb
		summarizeBy: none
		sourceColumn: Day of Week
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Day of Week-7255d9c4-2e9d-4460-b8b8-1178b0bf1295' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfLNz0tJrFSK1YlWMgJyQ0pTi2F8YyA/PDUlDyFiAlKRUVoEFzAFCrgVZcK4ZkBucGJJaRFMwBwkUAqxIRYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Order = _t, #"Day of Week" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Order", Int64.Type}, {"Day of Week", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

