table 'ED Falls (GHFT & SWAST)'
	lineageTag: 4185b671-b5bc-4b79-99fa-187a0a57b666

	measure '% ED (GHFT & SWAST) Admitted' =
			CALCULATE(SUM('ED Falls (GHFT & SWAST)'[admitted_flag])
			/
			SUM('ED Falls (GHFT & SWAST)'[counter]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 197a1923-f029-4278-ac57-f92768d2d4a5

	measure 'ED&SWAST Frailty Rate Per 1000 Attendances' = (sum('ED Falls (GHFT & SWAST)'[counter])/sum('Frail population'[COUNTER]))*1000
		lineageTag: 09818afd-0a26-4c3f-808a-517279f6d579

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Attendance Rate per 1000 GHFT & SWAST' =
			
			VAR ACTIVITY = CALCULATE ( sum('ED Falls (GHFT & SWAST)'[counter]))
			VAR POP = CALCULATE ( 'Practice Population'[April Population for Yearly Rate], ALLEXCEPT ('Date Table', 'Date Table'[Financial Year] ) )
			
			RETURN (ACTIVITY/POP*1000)
		lineageTag: 9fff341b-b1a8-4d29-a60a-28fae31c9d8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cheltenham Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[locality]="Cheltenham")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cheltenham"))*1000
		lineageTag: dc73073a-6f76-4c1e-acfb-25d0b0210d0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotswolds Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[locality]="Cotswolds")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cotswolds"))*1000
		lineageTag: baa4b76d-89ff-45ca-a77f-cf77291935c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gloucester City Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[locality]="Gloucester City")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Gloucester City"))*1000
		lineageTag: fcc965d7-bbbe-41dc-9a8a-8524bd1be393

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stroud & Berkeley Vale Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[locality]="Stroud and Berkeley Vale")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Stroud and Berkeley Vale"))*1000
		lineageTag: b647541f-1ee2-4d7a-8265-2b8440df263a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tewkesbury Newent and Staunton Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[locality]="Tewkesbury Newent and Staunton")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Tewkesbury Newent and Staunton"))*1000
		lineageTag: 1925c0fd-3976-49fe-bff8-615e0b53db41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'The Forest of Dean Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[locality]="The Forest of Dean")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="The Forest of Dean"))*1000
		lineageTag: 9426e16c-aadd-456c-bce6-52d4272a7796

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Has Dementia Rate Per 1000 Falls Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT Only)'[dementia_status]="Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="Dementia"))*1000
		lineageTag: 2d645a7f-8386-42df-ab74-31c1c97bb4ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Dementia Rate Per 1000 Falls Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT Only)'[dementia_status]="No Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="No Dementia"))*1000
		lineageTag: ab9b8225-2da9-415e-ac61-b533a3358edb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fit Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[frailty_category]="Fit")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Fit"))*1000
		lineageTag: f3b9f467-916c-40b5-ad01-0b5f3730f1b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mild Frailty Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[frailty_category]="Mild Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Mild Frailty"))*1000
		lineageTag: 34fa7eb9-8dad-48b5-b964-10c9180cc5ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Moderate Frailty Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[frailty_category]="Moderate Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Moderate Frailty"))*1000
		lineageTag: 26f7b94a-ada9-4a20-b437-9b2ce2ca35b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Severete Frailty Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[frailty_category]="Severe Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Severe Frailty"))*1000
		lineageTag: facc3e81-b93e-40f0-b453-612ff8a49552

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LD Home Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[Care_home_status]="LD")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="LD"))*1000
		lineageTag: 9981919b-d3b6-42b3-aa7f-937d200f19a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mental Health Home Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[Care_home_status]="Mental Health")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Mental Health"))*1000
		lineageTag: 74e9c93a-41f5-4fe1-9173-bf519399e77b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nursing Home Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[Care_home_status]="Nursing")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Nursing"))*1000
		lineageTag: c3d41f01-6371-43ef-bb70-8ef66dc3338d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Not living in a care home Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[Care_home_status]="Not living in a care home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Not living in a care home"))*1000
		lineageTag: 8f2a1057-3202-4588-af0d-d652dd8fcce7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Residential Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[Care_home_status]="Residential")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Residential"))*1000
		lineageTag: 1db14ff2-059f-48e5-9b87-e77dccd6d234

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unknown Care Home Type Rate Per 1000 Attendances GHFT & SWAST' =
			(calculate(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[Care_home_status]="Unknown Care Home Type")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Unknown Care Home Type"))*1000
		lineageTag: 0280872e-831b-4b3b-93f8-ed06b849b3a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NULL Diagnosis Attendances (GHFT & SWAST)' = ```
			
			CALCULATE(
				SUM('ED Falls (GHFT & SWAST)'[counter]),
				ISBLANK('ED Falls (GHFT & SWAST)'[Diagnosis_1]) 
			)
			```
		formatString: 0
		lineageTag: 1f1fd5a2-8d71-4653-87cf-52988c88d410

	measure 'Non-NULL Diagnosis Attendances (GHFT & SWAST)' =
			
			SUM('ED Falls (GHFT & SWAST)'[counter]) - [NULL Diagnosis Attendances (GHFT & SWAST)]
		formatString: 0
		lineageTag: ef45c817-51a6-48b0-a01a-26b81340a264

	measure 'Non-Injury Attendances (GHFT & SWAST)' =
			
			CALCULATE(
				SUM('ED Falls (GHFT & SWAST)'[counter]),
				'ED Falls (GHFT & SWAST)'[Injury Flag] = "No")
		formatString: 0
		lineageTag: a047c23e-4c98-4fd7-8e1c-eb811db57338

	measure '% Non-Injury Attendances (GHFT & SWAST)' =
			
			calculate('ED Falls (GHFT & SWAST)'[Non-Injury Attendances (GHFT & SWAST)]
			/
			'ED Falls (GHFT & SWAST)'[Non-NULL Diagnosis Attendances (GHFT & SWAST)])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 25899529-efa7-4b6f-a925-a432066380f7

	measure 'Average_attendance_falls_per_day (GHFT & SWAST)' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Date Table'[DayMonthYear])),
				CALCULATE(SUM('ED Falls (GHFT & SWAST)'[counter]))
			)
		formatString: 0.0
		lineageTag: c5392dfa-8dee-45d0-b99f-135d5512af2d

	measure 'Previous Year ED Falls (GHFT & SWAST)' = CALCULATE(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST year adjusted] = 'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST previous year])
		formatString: 0
		lineageTag: 7fe84757-da89-4e91-ac01-0d52b33f72e3

	measure 'Current Year ED Falls (GHFT & SWAST)' = CALCULATE(sum('ED Falls (GHFT & SWAST)'[counter]), 'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST year adjusted] = 'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST current year])
		formatString: 0
		lineageTag: 5b296af2-9565-4237-b72a-e5d547b57a94

	measure 'Comparison previous YTD ED Falls (GHFT & SWAST)' = CALCULATE(sum('ED Falls (GHFT & SWAST)'[counter]),'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST year adjusted] = 'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST previous year] && 'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST YTD] = "Year to Date")
		formatString: 0
		lineageTag: 817b9752-244e-4918-b5d7-5523f9544242

	measure 'Average_attendance_non-admitted_falls_per_day (GHFT & SWAST)' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Date Table'[DayMonthYear])),
				CALCULATE(SUM('ED Falls (GHFT & SWAST)'[admitted_flag]))
			)
		lineageTag: a0238700-956b-4bb2-8688-15eb343e810b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average_non-injurious_falls_per_day (GHFT & SWAST)' = ```
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Date Table'[DayMonthYear])),
				'ED Falls (GHFT & SWAST)'[Non-Injury Attendances (GHFT & SWAST)])
			
			```
		lineageTag: 73ed579a-af4e-4925-8611-823c55c8714b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Over/Under YTD Comparison ED GHFT & SWAST' = ```
			('ED Falls (GHFT & SWAST)'[Current Year ED Falls (GHFT & SWAST)] - 'ED Falls (GHFT & SWAST)'[Comparison previous YTD ED Falls (GHFT & SWAST)]) / 'ED Falls (GHFT & SWAST)'[Comparison previous YTD ED Falls (GHFT & SWAST)] 
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 34de9708-bfa1-4cb4-b665-92c8fa1547e9

	measure '% of Chief Complaints' = ```
			SUM('ED Falls (GHFT & SWAST)'[counter]) / CALCULATE(SUM('ED Falls (GHFT & SWAST)'[counter]) , ALLSELECTED('ED Falls (GHFT & SWAST)'[Chief_Complaint_translated])) 
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8c34f14d-b04e-41b4-ba7a-0565e2dcca36

	measure 'Gloucestershire Rate Per 1000 Falls Attendances' =
			
			
			VAR ACTIVITY = CALCULATE ( sum('ED Falls (GHFT & SWAST)'[counter]),ALL('GP Reference'))
			VAR POP = CALCULATE ( 'Practice Population'[April Population for Yearly Rate], ALLEXCEPT ('Date Table', 'Date Table'[Financial Year] ) ,ALL('GP Reference'))
			
			RETURN ACTIVITY/POP*1000
		lineageTag: c9ca9f50-5a29-43f2-8973-b8c7856666ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gloucestershire Falls Attendances' =
			
			
			VAR ACTIVITY = CALCULATE ( sum('ED Falls (GHFT & SWAST)'[counter]),ALL('GP Reference'))
			
			RETURN ACTIVITY
		formatString: 0
		lineageTag: f56e6c32-4659-4d49-b734-324d3402948b

	column type
		dataType: string
		lineageTag: ae3bd0b8-833d-433f-84a2-356ab5e57acd
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column Refresh_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ba9b7b25-999c-46c6-91aa-1b47fdf57ffc
		summarizeBy: none
		sourceColumn: Refresh_date

		variation Variation
			isDefault
			relationship: 799dcb0c-7e23-4b0c-bc34-e92402ff8603
			defaultHierarchy: LocalDateTable_25d3ad4d-7210-46e1-b6a1-98b40881bbec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column cds_unique_identifier
		dataType: string
		lineageTag: 84929b6d-acd6-4f3d-8cb8-a3d27986e063
		summarizeBy: none
		sourceColumn: cds_unique_identifier

		annotation SummarizationSetBy = Automatic

	column nhs_number
		dataType: string
		lineageTag: 9db9a436-41aa-4a6d-83bc-08306d04273a
		summarizeBy: none
		sourceColumn: nhs_number

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingAlone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3df3879c-68fc-4aab-8d5d-b63bd66fe37b
		summarizeBy: none
		sourceColumn: Derived_IsLivingAlone

		annotation SummarizationSetBy = Automatic

	column living_alone_status
		dataType: string
		lineageTag: 2748a793-2d78-4aff-9a92-c90ab0890688
		summarizeBy: none
		sourceColumn: living_alone_status

		annotation SummarizationSetBy = Automatic

	column PDS_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 292a41d8-7d7c-443a-906b-74ebf91490dd
		summarizeBy: none
		sourceColumn: PDS_date

		variation Variation
			isDefault
			relationship: 8a5b6830-1a1a-4546-a117-def7ec427f54
			defaultHierarchy: LocalDateTable_f31bf8c5-8853-4a9f-8595-b33f6a176b8f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Date_of_incident
		dataType: dateTime
		formatString: General Date
		lineageTag: 42ac2907-4fc8-4203-afab-2c442efe1834
		summarizeBy: none
		sourceColumn: Date_of_incident

		variation Variation
			isDefault
			relationship: 53e27dbb-6c72-482c-ba9f-e2bd5986ca37
			defaultHierarchy: LocalDateTable_e44e452f-1eed-4fb0-a1bd-9596b6995ce5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Broad Type (confirmed)'
		dataType: string
		lineageTag: 216f90d2-00ae-406e-9b3c-16a4a3e428c8
		summarizeBy: none
		sourceColumn: Broad Type (confirmed)

		annotation SummarizationSetBy = Automatic

	column 'Broad Type (old)'
		dataType: string
		lineageTag: ad421f6e-ee7b-49ce-aa3f-13e8c27e76b0
		summarizeBy: none
		sourceColumn: Broad Type (old)

		annotation SummarizationSetBy = Automatic

	column Care_home_status
		dataType: string
		lineageTag: ed18facf-6f69-4b04-ac1b-0b629bf02502
		summarizeBy: none
		sourceColumn: Care_home_status

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: aedc67db-fec5-433b-be2b-db392af9c723
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column Site_code
		dataType: string
		lineageTag: 9c7f22df-10ef-4b3f-920a-afd85da03cdf
		summarizeBy: none
		sourceColumn: Site_code

		annotation SummarizationSetBy = Automatic

	column site
		dataType: string
		lineageTag: 5b036d30-ddc0-4d49-a84e-9635990a452d
		summarizeBy: none
		sourceColumn: site

		annotation SummarizationSetBy = Automatic

	column arrival_date_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 73c8557b-62b1-4a67-a57d-1b82d95abb48
		summarizeBy: none
		sourceColumn: arrival_date_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column arrival_time_flag
		dataType: string
		lineageTag: 39fb24bc-58ff-409f-bec1-258f12b8377b
		summarizeBy: none
		sourceColumn: arrival_time_flag

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: b71f89ae-e634-41d7-807a-937c7cbece4a
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: d3716b6a-9e0c-4fd4-9da3-706ffaef6824
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 984e345a-5887-4c51-83b3-1eeded769833
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band
		dataType: string
		lineageTag: 0a196abc-606d-4349-8da3-54e7e671a764
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: c7c267fb-1c5a-4924-8ce7-9a22059400f7
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column correct_practice_code
		dataType: string
		lineageTag: 2da127c6-fe69-4aa8-ac21-caa0a73cfdb1
		summarizeBy: none
		sourceColumn: correct_practice_code

		annotation SummarizationSetBy = Automatic

	column ReportingOrganisationName
		dataType: string
		lineageTag: 96431f89-d01a-4207-aec8-33751c229f67
		summarizeBy: none
		sourceColumn: ReportingOrganisationName

		annotation SummarizationSetBy = Automatic

	column practice_name
		dataType: string
		lineageTag: 38474954-99fe-48f5-bb52-1089c0cd119d
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

	column primary_care_network
		dataType: string
		lineageTag: 5b130b3e-59db-42df-a012-d6f311ce9a2f
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: 93159a27-412a-4f60-9f93-847283623cae
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column hrg_code
		dataType: string
		lineageTag: 4a6b9bca-a6d4-41ae-8493-bec218d23754
		summarizeBy: none
		sourceColumn: hrg_code

		annotation SummarizationSetBy = Automatic

	column hrg_description
		dataType: string
		lineageTag: 280a6f54-3b17-448c-83e4-4a91c76ce128
		summarizeBy: none
		sourceColumn: hrg_description

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: 888deb12-68f7-4019-9830-95a4a8250b7e
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column ed_department_type
		dataType: string
		lineageTag: 59fb94ee-8dd8-4376-90d5-6428d266783f
		summarizeBy: none
		sourceColumn: ed_department_type

		annotation SummarizationSetBy = Automatic

	column frailty_score
		dataType: double
		lineageTag: 6608cbd8-55b1-4aa1-b61c-6c7048e5ad9b
		summarizeBy: sum
		sourceColumn: frailty_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column frailty_category
		dataType: string
		lineageTag: 4f54f5b5-5cf0-4141-8f0e-b51c2828e54c
		summarizeBy: none
		sourceColumn: frailty_category

		annotation SummarizationSetBy = Automatic

	column deceased_nhs_number
		dataType: string
		lineageTag: cd897113-4c18-4327-ac89-db7c8e113b62
		summarizeBy: none
		sourceColumn: deceased_nhs_number

		annotation SummarizationSetBy = Automatic

	column mortality_flag
		dataType: string
		lineageTag: b0b970da-3dce-4c40-b158-8f72cfd86bd4
		summarizeBy: none
		sourceColumn: mortality_flag

		annotation SummarizationSetBy = Automatic

	column date_of_death
		dataType: dateTime
		formatString: General Date
		lineageTag: 526162df-ff3f-4fd4-ad7b-f2041d787431
		summarizeBy: none
		sourceColumn: date_of_death

		variation Variation
			isDefault
			relationship: a37450f9-c9ef-4f75-8738-d6f0139a1952
			defaultHierarchy: LocalDateTable_2a3ce601-e1b0-430f-bca1-21b7f90d608d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column death_in_weeks
		dataType: int64
		formatString: 0
		lineageTag: 788db328-9e71-44a3-a58c-98616c8fb11c
		summarizeBy: sum
		sourceColumn: death_in_weeks

		annotation SummarizationSetBy = Automatic

	column presenting_complaint
		dataType: string
		lineageTag: 11a6e910-5b03-4e20-9249-181db7a885d1
		summarizeBy: none
		sourceColumn: presenting_complaint

		annotation SummarizationSetBy = Automatic

	column 10_year_age_band
		dataType: string
		lineageTag: 9590f14c-a4b1-4e56-90ad-97e43b705397
		summarizeBy: none
		sourceColumn: 10_year_age_band

		annotation SummarizationSetBy = Automatic

	column dementia_status
		dataType: string
		lineageTag: c560085e-bd21-4708-b8dd-c07b1293d906
		summarizeBy: none
		sourceColumn: dementia_status

		annotation SummarizationSetBy = Automatic

	column Arrival_mode
		dataType: string
		lineageTag: 2f712f4a-e0e1-4cd7-a29c-cae9f05e40fa
		summarizeBy: none
		sourceColumn: Arrival_mode

		annotation SummarizationSetBy = Automatic

	column Attendance_source
		dataType: string
		lineageTag: 7ce10423-dfb5-4cd1-afef-0d07509ef080
		summarizeBy: none
		sourceColumn: Attendance_source

		annotation SummarizationSetBy = Automatic

	column Discharge_status
		dataType: string
		lineageTag: 73e96bc1-f3ef-457b-8865-41722e842d48
		summarizeBy: none
		sourceColumn: Discharge_status

		annotation SummarizationSetBy = Automatic

	column Discharge_destination
		dataType: string
		lineageTag: e539b57e-4446-4043-bf4e-f9d7ce07f0ed
		summarizeBy: none
		sourceColumn: Discharge_destination

		annotation SummarizationSetBy = Automatic

	column local_discharge_status
		dataType: string
		lineageTag: 74d202a6-dc11-449f-ba0f-aa43e4826821
		summarizeBy: none
		sourceColumn: local_discharge_status

		annotation SummarizationSetBy = Automatic

	column local_disposal_method_grouped
		dataType: string
		lineageTag: 5d9c9e40-22d2-4aec-af93-e2e5d2fe4881
		summarizeBy: none
		sourceColumn: local_disposal_method_grouped

		annotation SummarizationSetBy = Automatic

	column admitted_flag_description
		dataType: string
		lineageTag: 74dbdf6d-d931-4ff6-87c3-a50c5a8fbb95
		summarizeBy: none
		sourceColumn: admitted_flag_description

		annotation SummarizationSetBy = Automatic

	column admitted_flag
		dataType: int64
		formatString: 0
		lineageTag: 28856395-131f-4fdd-9ab9-a36d712908b1
		summarizeBy: sum
		sourceColumn: admitted_flag

		annotation SummarizationSetBy = Automatic

	column grouped_ed_arrival_method
		dataType: string
		lineageTag: caa39dd7-2b59-4d1f-911d-e5511fb31303
		summarizeBy: none
		sourceColumn: grouped_ed_arrival_method

		annotation SummarizationSetBy = Automatic

	column incident_location
		dataType: string
		lineageTag: 5bd4d9a2-b400-47f2-b083-d19be62d7bd6
		summarizeBy: none
		sourceColumn: incident_location

		annotation SummarizationSetBy = Automatic

	column incident_location_home_or_not
		dataType: string
		lineageTag: 552f3c39-4bad-4a0b-b49a-135170499af3
		summarizeBy: none
		sourceColumn: incident_location_home_or_not

		annotation SummarizationSetBy = Automatic

	column incident_location_grouped
		dataType: string
		lineageTag: 0820ddaa-575c-4605-8a1d-4df427f4dd2a
		summarizeBy: none
		sourceColumn: incident_location_grouped

		annotation SummarizationSetBy = Automatic

	column Source_of_referral
		dataType: string
		lineageTag: 17024b17-f630-4158-a5c9-11f81168676e
		summarizeBy: none
		sourceColumn: Source_of_referral

		annotation SummarizationSetBy = Automatic

	column GHFT_or_SWAST_recording
		dataType: string
		lineageTag: b88328dd-f381-425b-b816-2b9a9c6cf508
		summarizeBy: none
		sourceColumn: GHFT_or_SWAST_recording

		annotation SummarizationSetBy = Automatic

	column day_time_attendance
		dataType: string
		lineageTag: cf1fbddf-84b6-4502-aa2f-d41dab2f6039
		summarizeBy: none
		sourceColumn: day_time_attendance

		annotation SummarizationSetBy = Automatic

	column hour_of_attendance
		dataType: string
		lineageTag: 71155353-56c3-44c4-ac83-57158924425f
		summarizeBy: none
		sourceColumn: hour_of_attendance

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: eb7deea8-9166-4556-a0a5-cb808e38295e
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'ED & SWAST max financial month' = ```
			
			VAR currmonth = MONTH(MAX('ED Falls (GHFT & SWAST)'[arrival_date]))
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: fa5500b4-76f5-43ca-b8ab-358671eab586
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED & SWAST financial month' = ```
			
			VAR currmonth = MONTH('ED Falls (GHFT & SWAST)'[arrival_date])
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: cccc05bb-21af-4565-ac36-e02a9341f677
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED (GHFT & SWAST) max financial month' = ```
			
			VAR currmonth = MONTH(MAX('ED Falls (GHFT & SWAST)'[arrival_date]))
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 1d355cfd-79c9-4f56-891c-2b00387bcce3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT & SWAST financial month' = ```
			
			VAR currmonth = MONTH('ED Falls (GHFT & SWAST)'[arrival_date])
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 66dbec90-5250-4e34-8481-2555e5ee23b2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT & SWAST YTD' = ```
			if('ED Falls (GHFT & SWAST)'[ED & SWAST financial month] <= 'ED Falls (GHFT & SWAST)'[ED & SWAST max financial month], "Year to Date", "Not Year to Date")
			
			```
		lineageTag: 36d9f666-0f5d-482e-9b45-ca99de47ac23
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT & SWAST current year' = ```
			
			VAR max_year = YEAR(MAX('ED Falls (GHFT & SWAST)'[arrival_date]))
			VAR max_month = MONTH(MAX('ED Falls (GHFT & SWAST)'[arrival_date]))
			VAR financial_month = SWITCH(TRUE(),
			max_month = 4, 1,
			max_month = 5, 2,
			max_month = 6, 3,
			max_month = 7, 4,
			max_month = 8, 5,
			max_month = 9, 6,
			max_month = 10, 7,
			max_month = 11, 8,
			max_month = 12, 9,
			max_month = 1, 10,
			max_month = 2, 11,
			max_month = 3, 12
			)
			VAR adjust_year = SWITCH(TRUE(),
			max_month = 1, max_year - 1,
			max_month = 2, max_year - 1,
			max_month = 3, max_year - 1,
			max_month = 4, max_year,
			max_month = 5, max_year,
			max_month = 6, max_year,
			max_month = 7, max_year,
			max_month = 8, max_year,
			max_month = 9, max_year,
			max_month = 10, max_year,
			max_month = 11, max_year,
			max_month = 12, max_year
			)
			return adjust_year
			
			```
		formatString: 0
		lineageTag: 0253030e-1307-45fc-ae5d-7ab62a3102c0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT & SWAST year adjusted' = ```
			if(
			    'ED Falls (GHFT & SWAST)'[ED & SWAST financial month] = 10, YEAR('ED Falls (GHFT & SWAST)'[arrival_date]) -1, 
			    if('ED Falls (GHFT & SWAST)'[ED & SWAST financial month] = 11, YEAR('ED Falls (GHFT & SWAST)'[arrival_date]) -1, 
			    if('ED Falls (GHFT & SWAST)'[ED & SWAST financial month]= 12, YEAR('ED Falls (GHFT & SWAST)'[arrival_date]) -1, year('ED Falls (GHFT & SWAST)'[arrival_date]))))
			
			
			
			```
		formatString: 0
		lineageTag: bf7c7e0d-454e-4578-b4d2-9bc854651dd5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT & SWAST previous year' = ```
			'ED Falls (GHFT & SWAST)'[ED GHFT & SWAST current year] - 1
			
			```
		formatString: 0
		lineageTag: 94ad98de-8782-4296-9709-bd1ccf0875d0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column LSOA_11
		dataType: string
		lineageTag: 31017883-f669-4257-82c8-b7ab9b425173
		summarizeBy: none
		sourceColumn: LSOA_11

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category
		dataType: string
		lineageTag: 1b66b783-b7e3-4765-b50a-af360d0b3f00
		summarizeBy: none
		sourceColumn: Ethnic_Category

		annotation SummarizationSetBy = Automatic

	column Diagnosis_all
		dataType: string
		lineageTag: bb8146a6-e77a-4a48-8e04-44c510d8aad7
		summarizeBy: none
		sourceColumn: Diagnosis_all

		annotation SummarizationSetBy = Automatic

	column Diagnosis_1
		dataType: string
		lineageTag: 0ffbe5f8-55b7-476d-9f20-3362b3e74ec6
		summarizeBy: none
		sourceColumn: Diagnosis_1

		annotation SummarizationSetBy = Automatic

	column Diagnosis_2
		dataType: string
		lineageTag: d573fddd-6f0d-4860-a47d-eaeea32b72a8
		summarizeBy: none
		sourceColumn: Diagnosis_2

		annotation SummarizationSetBy = Automatic

	column Diagnosis_3
		dataType: string
		lineageTag: 83f82c4e-d329-4610-8ba7-c3b769684cdd
		summarizeBy: none
		sourceColumn: Diagnosis_3

		annotation SummarizationSetBy = Automatic

	column Diagnosis_4
		dataType: string
		lineageTag: e1341365-831b-47e4-9b68-5026719dff6b
		summarizeBy: none
		sourceColumn: Diagnosis_4

		annotation SummarizationSetBy = Automatic

	column Diagnosis_5
		dataType: string
		lineageTag: 21133ca2-bffe-4177-97fb-d47097445972
		summarizeBy: none
		sourceColumn: Diagnosis_5

		annotation SummarizationSetBy = Automatic

	column Diagnosis_6
		dataType: string
		lineageTag: e75e3fcb-9d5b-48b7-8588-2d2a9254a5fd
		summarizeBy: none
		sourceColumn: Diagnosis_6

		annotation SummarizationSetBy = Automatic

	column Diagnosis_7
		dataType: string
		lineageTag: d610ec69-52c1-4fbf-b409-b74386afc36a
		summarizeBy: none
		sourceColumn: Diagnosis_7

		annotation SummarizationSetBy = Automatic

	column Diagnosis_8
		dataType: string
		lineageTag: 53605571-121f-4470-bd09-aeed5ba30503
		summarizeBy: none
		sourceColumn: Diagnosis_8

		annotation SummarizationSetBy = Automatic

	column Treatment_all
		dataType: string
		lineageTag: 04a27f3c-113e-44d3-951f-d9eb29fb8e1d
		summarizeBy: none
		sourceColumn: Treatment_all

		annotation SummarizationSetBy = Automatic

	column Treatment_1
		dataType: string
		lineageTag: 7a04cbc2-c3ef-497c-9081-964184a29569
		summarizeBy: none
		sourceColumn: Treatment_1

		annotation SummarizationSetBy = Automatic

	column Treatment_2
		dataType: string
		lineageTag: e7f58782-aa5c-4208-b733-91ce591b9a0c
		summarizeBy: none
		sourceColumn: Treatment_2

		annotation SummarizationSetBy = Automatic

	column Treatment_3
		dataType: string
		lineageTag: 8c6d73b0-5a23-44f8-85b2-2ddc1ec9190f
		summarizeBy: none
		sourceColumn: Treatment_3

		annotation SummarizationSetBy = Automatic

	column Treatment_4
		dataType: string
		lineageTag: 58ae00d6-615e-4f0b-8e30-cb394153b5fb
		summarizeBy: none
		sourceColumn: Treatment_4

		annotation SummarizationSetBy = Automatic

	column Treatment_5
		dataType: string
		lineageTag: d2b16565-ea42-4113-9d85-9867eda58e0c
		summarizeBy: none
		sourceColumn: Treatment_5

		annotation SummarizationSetBy = Automatic

	column Treatment_6
		dataType: string
		lineageTag: 66699050-6e84-4bd1-bdaf-eb42ee068f53
		summarizeBy: none
		sourceColumn: Treatment_6

		annotation SummarizationSetBy = Automatic

	column Treatment_7
		dataType: string
		lineageTag: 1b0dcb07-1815-43a6-b8a0-79c236a96d67
		summarizeBy: none
		sourceColumn: Treatment_7

		annotation SummarizationSetBy = Automatic

	column Treatment_8
		dataType: string
		lineageTag: e6043334-1985-4287-be6d-f35679eb4173
		summarizeBy: none
		sourceColumn: Treatment_8

		annotation SummarizationSetBy = Automatic

	column Investigation_all
		dataType: string
		lineageTag: deeab1a5-7e31-49c7-8228-0d144badd8cb
		summarizeBy: none
		sourceColumn: Investigation_all

		annotation SummarizationSetBy = Automatic

	column Investigation_1
		dataType: string
		lineageTag: 9410f32f-1c2e-4bd6-9090-d524fd1669ff
		summarizeBy: none
		sourceColumn: Investigation_1

		annotation SummarizationSetBy = Automatic

	column Investigation_2
		dataType: string
		lineageTag: 1f1bdf53-d9b8-4b3b-88fe-3b1f458182bf
		summarizeBy: none
		sourceColumn: Investigation_2

		annotation SummarizationSetBy = Automatic

	column Investigation_3
		dataType: string
		lineageTag: a9469897-a503-43ab-bc67-ce1de299ce09
		summarizeBy: none
		sourceColumn: Investigation_3

		annotation SummarizationSetBy = Automatic

	column Investigation_4
		dataType: string
		lineageTag: 5e12889b-29cb-429c-aedb-73d4c3203d6c
		summarizeBy: none
		sourceColumn: Investigation_4

		annotation SummarizationSetBy = Automatic

	column Investigation_5
		dataType: string
		lineageTag: 76a0f571-91a5-4921-b69f-d54c4fb9e14d
		summarizeBy: none
		sourceColumn: Investigation_5

		annotation SummarizationSetBy = Automatic

	column Investigation_6
		dataType: string
		lineageTag: 98df8971-4ba8-4864-b779-786300a5d434
		summarizeBy: none
		sourceColumn: Investigation_6

		annotation SummarizationSetBy = Automatic

	column Investigation_7
		dataType: string
		lineageTag: 7d75811c-b468-4203-9b33-a6358c1e42af
		summarizeBy: none
		sourceColumn: Investigation_7

		annotation SummarizationSetBy = Automatic

	column Investigation_8
		dataType: string
		lineageTag: 474fec67-bdca-448a-a3ea-ed09d4740cef
		summarizeBy: none
		sourceColumn: Investigation_8

		annotation SummarizationSetBy = Automatic

	column Chief_Complaint_translated
		dataType: string
		lineageTag: 601db2ef-d6b6-429f-84a6-4d6e0ccd23c3
		summarizeBy: none
		sourceColumn: Chief_Complaint_translated

		annotation SummarizationSetBy = Automatic

	column 'Injurious Attendance' =
			
			SWITCH(TRUE(),
			'ED Falls (GHFT & SWAST)'[Diagnosis_1] = "No abnormality detected" && 'ED Falls (GHFT & SWAST)'[Diagnosis_2] = BLANK(), "No",
			'ED Falls (GHFT & SWAST)'[Diagnosis_1] = "No abnormality detected" && 'ED Falls (GHFT & SWAST)'[Diagnosis_2] = "No abnormality detected", "No",
			"Yes")
		lineageTag: 86babfca-45ab-4cbe-9aba-8b58a76d8a8a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Injury Flag'
		dataType: string
		lineageTag: f0ce7706-96e3-45b9-a181-f973dbe3bf8c
		summarizeBy: none
		sourceColumn: Injury Flag

		annotation SummarizationSetBy = Automatic

	column Arrival_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2015ad1b-67be-4ebc-97dd-5e914d8aca64
		summarizeBy: none
		sourceColumn: Arrival_Date

		annotation SummarizationSetBy = Automatic

	column care_home_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 43ac76a9-6add-459a-ba01-4f2461839768
		summarizeBy: none
		sourceColumn: care_home_date

		variation Variation
			isDefault
			relationship: 5ff4f3f6-8cc5-4360-a84a-e0982176eb10
			defaultHierarchy: LocalDateTable_1eb3d05e-51f8-471a-8e1b-fc7714d9c225.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column End_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0c0f1814-af81-4dc3-bc6e-1cc8f98a6166
		summarizeBy: none
		sourceColumn: End_date

		variation Variation
			isDefault
			relationship: fc55467f-d52f-4417-8e90-25511cdce157
			defaultHierarchy: LocalDateTable_d09ee76b-0b19-44a0-b7b5-6f1d308997ad.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_1
		dataType: string
		lineageTag: a7c54a66-d80c-4a0f-b006-89bb498561c3
		summarizeBy: none
		sourceColumn: Diagnoses_Code_1

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_2
		dataType: string
		lineageTag: 12170530-be5a-4a91-866f-d727149459c4
		summarizeBy: none
		sourceColumn: Diagnoses_Code_2

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_3
		dataType: string
		lineageTag: fb49013e-0bbc-42f3-8cf5-e2a5622fd4ab
		summarizeBy: none
		sourceColumn: Diagnoses_Code_3

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_4
		dataType: string
		lineageTag: 7657d613-3b97-4869-b8d7-ebf3c9c01844
		summarizeBy: none
		sourceColumn: Diagnoses_Code_4

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_5
		dataType: string
		lineageTag: 697483fc-0931-4ed6-8145-b6fa8a80d65b
		summarizeBy: none
		sourceColumn: Diagnoses_Code_5

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_6
		dataType: string
		lineageTag: 483bf41f-7e42-4425-9767-bf8044096931
		summarizeBy: none
		sourceColumn: Diagnoses_Code_6

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_7
		dataType: string
		lineageTag: d7840fe1-b670-4e19-a951-cdc222016255
		summarizeBy: none
		sourceColumn: Diagnoses_Code_7

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_8
		dataType: string
		lineageTag: d6ea7e80-7fd9-42c6-a540-22797df5f404
		summarizeBy: none
		sourceColumn: Diagnoses_Code_8

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_1
		dataType: string
		lineageTag: 3b936fc2-ff72-46c9-984b-f459a9546c91
		summarizeBy: none
		sourceColumn: Treatment_Code_1

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_2
		dataType: string
		lineageTag: a4673067-735d-421a-a02e-66c4aa5dad10
		summarizeBy: none
		sourceColumn: Treatment_Code_2

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_3
		dataType: string
		lineageTag: 2c8aed98-24c9-4df0-a043-0832a15289cc
		summarizeBy: none
		sourceColumn: Treatment_Code_3

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_4
		dataType: string
		lineageTag: a406afc3-9eb2-413b-bd07-cd8607591ecb
		summarizeBy: none
		sourceColumn: Treatment_Code_4

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_5
		dataType: string
		lineageTag: 7bb6c88f-4da4-4f94-b4dc-95a9783e980e
		summarizeBy: none
		sourceColumn: Treatment_Code_5

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_6
		dataType: string
		lineageTag: 968a7e5f-a240-4d4f-89be-a875d048d84c
		summarizeBy: none
		sourceColumn: Treatment_Code_6

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_7
		dataType: string
		lineageTag: e672af19-bd7f-4a1f-9c7a-b2b58e8ba591
		summarizeBy: none
		sourceColumn: Treatment_Code_7

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_8
		dataType: string
		lineageTag: 8431a1d8-2b01-4c65-9d2d-caef48c0d31c
		summarizeBy: none
		sourceColumn: Treatment_Code_8

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_1
		dataType: string
		lineageTag: 2eef81b9-2ba6-482d-b827-817bf76dd807
		summarizeBy: none
		sourceColumn: Investigation_Code_1

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_2
		dataType: string
		lineageTag: 770e128f-7356-4880-a7c1-fac4991f49c7
		summarizeBy: none
		sourceColumn: Investigation_Code_2

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_3
		dataType: string
		lineageTag: 2c882150-c203-40d0-9189-7e2de891cd6b
		summarizeBy: none
		sourceColumn: Investigation_Code_3

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_4
		dataType: string
		lineageTag: ebc27ea6-8634-4383-9a89-71aa1ff04ee8
		summarizeBy: none
		sourceColumn: Investigation_Code_4

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_5
		dataType: string
		lineageTag: 872cef31-d048-4a77-8a3e-daa71383e992
		summarizeBy: none
		sourceColumn: Investigation_Code_5

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_6
		dataType: string
		lineageTag: 0fdb1625-672d-4ec0-8b39-e46c9304f0e8
		summarizeBy: none
		sourceColumn: Investigation_Code_6

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_7
		dataType: string
		lineageTag: 99bcee94-54c6-4cd1-844e-a44dcfae446f
		summarizeBy: none
		sourceColumn: Investigation_Code_7

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_8
		dataType: string
		lineageTag: c2eccf89-b2e6-4e00-b83e-b2bcdfdff9f6
		summarizeBy: none
		sourceColumn: Investigation_Code_8

		annotation SummarizationSetBy = Automatic

	column Destination
		dataType: string
		lineageTag: 90fbe771-cad7-4903-9763-1417ff125926
		summarizeBy: none
		sourceColumn: Destination

		annotation SummarizationSetBy = Automatic

	column Chief_Complaint
		dataType: string
		lineageTag: 8ccd4fd5-1250-4bfb-91c4-30bf3048804c
		summarizeBy: none
		sourceColumn: Chief_Complaint

		annotation SummarizationSetBy = Automatic

	column Stated_Gender
		dataType: string
		lineageTag: a09c17fb-2cf6-4f81-b8e5-700782bc0a2c
		summarizeBy: none
		sourceColumn: Stated_Gender

		annotation SummarizationSetBy = Automatic

	column Age_At_CDS_Activity_Date
		dataType: string
		lineageTag: 59e75e22-9220-4fcf-a903-843a71caad2a
		summarizeBy: none
		sourceColumn: Age_At_CDS_Activity_Date

		annotation SummarizationSetBy = Automatic

	column ProcessedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 12b63928-5540-43a1-b96b-bea7c64543f2
		summarizeBy: none
		sourceColumn: ProcessedDate

		variation Variation
			isDefault
			relationship: f35f906a-1f5f-4432-b268-85487fb01791
			defaultHierarchy: LocalDateTable_0c4fcb0b-84d8-41aa-a6f3-6fab5d2fe61e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Core20_Flag
		dataType: string
		lineageTag: e92f9a10-0a74-4932-878a-a5f8e4ab6c2d
		summarizeBy: none
		sourceColumn: Core20_Flag

		annotation SummarizationSetBy = Automatic

	column IMD
		dataType: string
		lineageTag: 9775eea1-0c03-49fd-8a88-d588e7134895
		summarizeBy: none
		sourceColumn: IMD

		annotation SummarizationSetBy = Automatic

	column Ethnic_Origin_Grouped
		dataType: string
		lineageTag: 31c89f82-cc08-43c2-91b1-493560c57c7e
		summarizeBy: none
		sourceColumn: Ethnic_Origin_Grouped

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: string
		lineageTag: 95157b87-2b27-4a48-b3fc-053e1e9df247
		summarizeBy: none
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column MH_Flag
		dataType: string
		lineageTag: e1a2de73-9146-4af5-b41c-41c0da546b16
		summarizeBy: none
		sourceColumn: MH_Flag

		annotation SummarizationSetBy = Automatic

	partition 'ED Falls (GHFT & SWAST)' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select * from [PowerBI_Reporting].[Falls].[tbl05_Falls_ED_GHFT_And_SWAST]#(lf)", CommandTimeout=#duration(0, 1, 40, 0)]),
				    #"Added Conditional Column" = Table.AddColumn(Source, "Injury Flag", each if Text.Contains([Diagnosis_all], "No abnormality detected") then "No" else "Yes"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"admitted_flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

