table 'ED Falls (GHFT Only)'
	lineageTag: 7a8b887e-4283-45ab-99fa-c6fd59137f70

	measure 'Locality Rate Per 1000 Falls Attendances' = (sum('ED Falls (GHFT Only)'[counter_ED_falls])/sum('Place Population'[Population]))*1000
		lineageTag: 259d098b-90c2-4dfa-a4c6-4aed36aa0cc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Year ED Falls' = CALCULATE(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[ED GHFT year adjusted] = 'ED Falls (GHFT Only)'[ED GHFT previous year])
		formatString: 0
		lineageTag: 30e39d60-e9e8-47ab-a669-ad230cd28327

	measure 'Current Year ED Falls' = CALCULATE(sum('ED Falls (GHFT Only)'[counter_ED_falls]), 'ED Falls (GHFT Only)'[ED GHFT year adjusted] = 'ED Falls (GHFT Only)'[ED GHFT current year])
		formatString: 0
		lineageTag: 82e46d8a-ae1a-415e-85b1-3dbde02e3aa8

	measure 'Comparison to previous YTD ED Falls' = CALCULATE(sum('ED Falls (GHFT Only)'[counter_ED_falls]), 'ED Falls (GHFT Only)'[ED GHFT year adjusted] = 'ED Falls (GHFT Only)'[ED GHFT previous year] && 'ED Falls (GHFT Only)'[ED GHFT YTD] = "Year to Date")
		formatString: 0
		lineageTag: 16fce6a6-9648-4852-bda9-d961b456942c

	measure 'Dementia Rate Per 1000 Falls Attendances' = (sum('ED Falls (GHFT Only)'[counter_ED_falls])/sum('Dementia population'[COUNTER]))*1000
		lineageTag: 19fbfa6f-731e-46a1-ad82-a049de28170a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Care Home Rate Per 1000 Attendances' = (sum('ED Falls (GHFT Only)'[counter_ED_falls])/sum('Care home population'[COUNTER]))*1000
		lineageTag: 3b97d434-cc66-49cd-b0c7-40cd3de606a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frailty Rate Per 1000 Attendances' = (sum('ED Falls (GHFT Only)'[counter_ED_falls])/sum('Frail population'[COUNTER]))*1000
		lineageTag: 7dabc98f-e1f9-4110-a88b-4cbda481b0ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Has Dementia Rate Per 1000 Falls Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[dementia_status]="Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="Dementia"))*1000
		lineageTag: de888b81-1823-4c4e-b255-3b0cae060680

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Old Dementia Rate Per 1000 Falls Attendances' = (sum('ED Falls (GHFT Only)'[counter_ED_falls])/sum('Dementia population'[COUNTER]))*1000
		lineageTag: b34c97db-0898-46ca-a7e6-38415657359b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Dementia Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[dementia_status]="No Dementia")
			/CALCULATE(sum('Dementia population'[COUNTER]),'Dementia population'[Dementia Status]="No Dementia"))*1000
		lineageTag: 07006319-ced0-467a-9512-b15057d62030

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cheltenham Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[locality]="Cheltenham")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cheltenham"))*1000
		lineageTag: ce9f92e7-df25-4825-b003-0099b9d74ef3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TWNS Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[locality]="Tewkesbury Newent and Staunton")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Tewkesbury Newent and Staunton"))*1000
		lineageTag: 8d3c214c-58d4-46a8-8c59-48f95322e4ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FOD Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[locality]="The Forest of Dean")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="The Forest of Dean"))*1000
		lineageTag: 2b625bbf-be42-42d8-a88b-e5c775600bee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gloucester Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[locality]="Gloucester City")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Gloucester City"))*1000
		lineageTag: 176cbfaa-1949-499c-8ade-cfbfbe1e70b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'S&BV Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[locality]="Stroud and Berkeley Vale")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Stroud and Berkeley Vale"))*1000
		lineageTag: 405a3338-fa11-4d74-90e4-53c24756377c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotswolds Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[locality]="Cotswolds")
			/CALCULATE(sum('Place Population'[Population]),'Place Population'[Locality]="Cotswolds"))*1000
		lineageTag: 4b7ccbc2-b710-4c2c-83b4-f267a37f40b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Moderate Frailty Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[frailty_category]="Moderate Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Moderate Frailty"))*1000
		lineageTag: d363990a-9d03-4828-beec-0ed31fa7d7f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mild Frailty Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[frailty_category]="Mild Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Mild Frailty"))*1000
		lineageTag: 3c94a9c1-5641-4c3d-b8f0-69edaeafe2fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fit Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[frailty_category]="Fit")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Fit"))*1000
		lineageTag: 389c1896-00dd-42f4-9401-f780411958a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Severe Frailty Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[frailty_category]="Severe Frailty")
			/CALCULATE(sum('Frail population'[COUNTER]),'Frail population'[Frailty Category]="Severe Frailty"))*1000
		lineageTag: 4a52e8a1-7fcf-4516-ae1e-78ffe53edb40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Attendance Rate per 1000' =
			
			
			VAR ACTIVITY = CALCULATE ( sum('ED Falls (GHFT Only)'[counter_ED_falls]))
			VAR POP = CALCULATE ( 'Practice Population'[April Population for Yearly Rate], ALLEXCEPT ('Date Table', 'Date Table'[Financial Year] ) )
			
			RETURN (ACTIVITY/POP*1000)
		lineageTag: 7639067e-cdda-4d70-a1bf-33fdaf3244f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LD Home Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[Care_home_status]="LD")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="LD"))*1000
		lineageTag: 05677097-5168-4f9a-9926-0d3cc6eed12b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Not Living in a Care Home Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[Care_home_status]="Not Living in a Care Home")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Not Living in a Care Home"))*1000
		lineageTag: e1ebe2ce-7c6e-4f69-8fee-e4ef11acef8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nursing Home Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[Care_home_status]="Nursing")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Nursing"))*1000
		lineageTag: e21216a7-f2f9-46c1-995f-d070bb63ab68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Residential Care Home Rate Per 1000' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Residential")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Residential"))*1000
		lineageTag: 77334245-5f85-4177-b185-d48174263188

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unknown Care Home Rate Per 1000 Attendances' =
			(calculate(sum('Admissions Falls'[Number of Admissions]),'Admissions Falls'[Care_home_status]="Unknown Care Home Type")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Unknown Care Home Type"))*1000
		lineageTag: 85ad79d7-11cc-44dd-a10d-e8749ef3a92a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Non-Injury Attendances' =
			
			CALCULATE(
				SUM('ED Falls (GHFT Only)'[counter_ED_falls]),
				'ED Falls (GHFT Only)'[Treatment_all] IN { "Patient given written advice", "Review of medication", "Cardiac monitor surveillance", "Treatment not indicated"  }
			)
		lineageTag: 8cddc119-c487-4c1d-a9ac-c433d7ac1ace

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "FilteredMeasure"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Min_Attendance_Date = CALCULATE(MIN('Date Table'[Date]),FILTER('ED Falls (GHFT Only)',[arrival_date]))
		formatString: General Date
		lineageTag: 6c2ec041-2aab-4846-ad06-e1c5d8e4b24c

	measure Max_Attendance_Date = CALCULATE(MAX('Date Table'[Date]),FILTER('ED Falls (GHFT Only)',[arrival_date]))
		formatString: General Date
		lineageTag: e158bd6b-773f-4f98-a94b-cd57ebc4ff9f

	measure Number_of_days_attendance = DATEDIFF('ED Falls (GHFT Only)'[Min_Attendance_Date],'ED Falls (GHFT Only)'[Max_Attendance_Date],DAY)
		formatString: 0
		lineageTag: 9ca08798-1e0c-48d6-9deb-8c3ca9853acc

	measure Average_attendance_falls_per_day =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Date Table'[DayMonthYear])),
				CALCULATE(SUM('ED Falls (GHFT Only)'[counter_ED_falls]))
			)
		formatString: 0.0
		lineageTag: 83427db9-478c-4bd7-8437-a013e9931103

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "AveragePerCategory"
				}

		changedProperty = FormatString

	measure 'MH Home Rate Per 1000 Attendances' =
			(calculate(sum('ED Falls (GHFT Only)'[counter_ED_falls]),'ED Falls (GHFT Only)'[Care_home_status]="Mental Health")
			/CALCULATE(sum('Care home population'[COUNTER]),'Care home population'[Care_home_status]="Mental Health"))*1000
		lineageTag: 4d7e66b4-e4c6-400d-a252-6abd445ace4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure 2'
		lineageTag: 84970633-c64f-438f-9813-4efe36449ffb

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Average_attendance_not-admitted_falls_per_day =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Date Table'[DayMonthYear])),
				CALCULATE(SUM('ED Falls (GHFT Only)'[admitted_flag]))
			)
		lineageTag: 3af4c10e-9a9b-4992-a4b9-0c6d3613a07e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average_non-injurious_falls_per_day (GHFT Only)' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Date Table'[DayMonthYear])),
				'ED Falls (GHFT Only)'[Non-Injury Attendances])
		lineageTag: 7241a7fb-132c-421d-8ba7-d80067d5ee67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Over/Under YTD Comparison' = ```
			('ED Falls (GHFT Only)'[Current Year ED Falls] - 'ED Falls (GHFT Only)'[Comparison to previous YTD ED Falls]) / 'ED Falls (GHFT Only)'[Comparison to previous YTD ED Falls] 
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 44ce746d-7ad2-4508-b2de-8f0ff2640861

	measure 'Max ED Date (Year Format)' = MAX('ED Falls (GHFT Only)'[arrival_date])
		formatString: General Date
		lineageTag: e88317d8-a21f-4813-b2fb-5b7e67410294

	column presenting_complaint
		dataType: string
		lineageTag: d8452d37-ce38-4335-a0d6-d18c4d99dd20
		summarizeBy: none
		sourceColumn: presenting_complaint

		annotation SummarizationSetBy = Automatic

	column 10_year_age_band
		dataType: string
		lineageTag: 3c8762d6-cb94-4ce1-9858-7a0f9b762889
		summarizeBy: none
		sourceColumn: 10_year_age_band

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 0d10acb7-9c6a-4e8e-9a05-bdbfaa69d8a6
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column nhs_number
		dataType: string
		lineageTag: 717424ba-1f6c-4cad-900c-899e800ae8de
		summarizeBy: none
		sourceColumn: nhs_number

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: 13700436-38f3-42ce-8aee-58a52c8d9514
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column site
		dataType: string
		lineageTag: 488bb10f-b7f5-4b16-9a2c-89e42841c3b4
		summarizeBy: none
		sourceColumn: site

		annotation SummarizationSetBy = Automatic

	column arrival_date_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3d5dcb89-7858-49c4-adeb-404201f18dc8
		summarizeBy: none
		sourceColumn: arrival_date_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column arrival_time_flag
		dataType: string
		lineageTag: 2e7909fa-5eb2-47a2-bf48-38a20dddc65c
		summarizeBy: none
		sourceColumn: arrival_time_flag

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 19c59bb9-a119-480d-9d80-edb5bad2ef2d
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 540119fa-8c9c-4f38-b983-e6e92c6e48a8
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: a84dff98-e024-4641-87c2-b4899218eba3
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band
		dataType: string
		lineageTag: c96b647d-7cee-44fc-8970-7f348dafeb2b
		summarizeBy: none
		sourceColumn: 5yr_age_band

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: 195062e9-00d7-496e-8d47-ba58fb092e60
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column practice_name
		dataType: string
		lineageTag: bc05c47c-bdb1-4c7d-8ea1-234ec846a7ea
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

	column primary_care_network
		dataType: string
		lineageTag: c270a05b-ec7b-43af-9ecd-346497f3ae64
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = User

	column locality
		dataType: string
		lineageTag: a650407f-577b-4450-baf5-17d421946cab
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column hrg_code
		dataType: string
		lineageTag: 9ff83e4e-7853-4ebe-aa20-bf6e7e2483f8
		summarizeBy: none
		sourceColumn: hrg_code

		annotation SummarizationSetBy = Automatic

	column hrg_description
		dataType: string
		lineageTag: 65d387a5-a8f4-4065-b12e-137927444294
		summarizeBy: none
		sourceColumn: hrg_description

		annotation SummarizationSetBy = Automatic

	column counter_ED_falls
		dataType: int64
		formatString: 0
		lineageTag: 960f5990-e20a-4928-ba32-38a0e47935e6
		summarizeBy: sum
		sourceColumn: counter_ED_falls

		annotation SummarizationSetBy = Automatic

	column admitted_flag
		dataType: int64
		formatString: 0
		lineageTag: ca7ce94b-f95c-4db1-bc53-59ec0e4d4da5
		summarizeBy: sum
		sourceColumn: admitted_flag

		annotation SummarizationSetBy = Automatic

	column ed_department_type
		dataType: string
		lineageTag: 6f8ab5dc-f615-4b67-b7ac-4235e6c73ddb
		summarizeBy: none
		sourceColumn: ed_department_type

		annotation SummarizationSetBy = Automatic

	column frailty_score
		dataType: double
		lineageTag: 7f48ae2d-08f5-45cd-a5d2-1aabc7e156b8
		summarizeBy: sum
		sourceColumn: frailty_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column frailty_category
		dataType: string
		lineageTag: 68d10b09-c95f-4b10-bdae-0a5b3f5f4bc4
		summarizeBy: none
		sourceColumn: frailty_category

		annotation SummarizationSetBy = Automatic

	column dementia_status
		dataType: string
		lineageTag: f9cfbdc8-f47e-45f2-bbb0-fa463de7ba8a
		summarizeBy: none
		sourceColumn: dementia_status

		annotation SummarizationSetBy = Automatic

	column admitted_flag_description
		dataType: string
		lineageTag: 80ff86c9-3572-426f-be4e-cca4d3d5adad
		summarizeBy: none
		sourceColumn: admitted_flag_description

		annotation SummarizationSetBy = Automatic

	column grouped_ed_arrival_method
		dataType: string
		lineageTag: 941d7b7c-ebe6-477b-9529-7b2de6e2b1b4
		summarizeBy: none
		sourceColumn: grouped_ed_arrival_method

		annotation SummarizationSetBy = Automatic

	column correct_practice_code
		dataType: string
		lineageTag: a1709b01-0d0f-4f2b-9531-2efad59c0179
		summarizeBy: none
		sourceColumn: correct_practice_code

		annotation SummarizationSetBy = Automatic

	column ReportingOrganisationName
		dataType: string
		lineageTag: 9f8bc3f8-d9db-4b69-b4aa-9f62a3fc9b3c
		summarizeBy: none
		sourceColumn: ReportingOrganisationName

		annotation SummarizationSetBy = Automatic

	column Care_home_status
		dataType: string
		lineageTag: 1186e558-7a91-4aab-b7b8-58b8b41470dd
		summarizeBy: none
		sourceColumn: Care_home_status

		annotation SummarizationSetBy = Automatic

	column Derived_IsLivingAlone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 69d73e48-6be3-4d7b-a0e3-4b541f58e7fa
		summarizeBy: none
		sourceColumn: Derived_IsLivingAlone

		annotation SummarizationSetBy = Automatic

	column PDS_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 17c06294-3901-489d-976c-c2094e9fd767
		summarizeBy: none
		sourceColumn: PDS_date

		variation Variation
			isDefault
			relationship: c998e56c-d433-4c25-bd32-0b96ede468ec
			defaultHierarchy: LocalDateTable_15c5fb82-5084-4633-a73a-038af3121f80.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Date_of_incident
		dataType: dateTime
		formatString: General Date
		lineageTag: 7d45f2ba-8d2c-4615-9fe1-f077a016551a
		summarizeBy: none
		sourceColumn: Date_of_incident

		variation Variation
			isDefault
			relationship: 4502e6a2-f218-4be3-9cb2-bc1a31ecbd7d
			defaultHierarchy: LocalDateTable_e188f3f8-e6ac-4c9b-8419-3b3c4b5a8ca6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column deceased_nhs_number
		dataType: string
		lineageTag: 94106ba0-e50b-4729-91f6-07fb078bc0de
		summarizeBy: none
		sourceColumn: deceased_nhs_number

		annotation SummarizationSetBy = Automatic

	column mortality_flag
		dataType: string
		lineageTag: 7709e197-08b3-4788-8127-33e333868c49
		summarizeBy: none
		sourceColumn: mortality_flag

		annotation SummarizationSetBy = Automatic

	column date_of_death
		dataType: dateTime
		formatString: General Date
		lineageTag: 5f964e33-dc5e-481f-9a1e-1b0e891a219b
		summarizeBy: none
		sourceColumn: date_of_death

		variation Variation
			isDefault
			relationship: 27b207b3-a7d8-4db1-96d3-0de540afe912
			defaultHierarchy: LocalDateTable_655231b3-1ab3-46ce-9708-0c0b98fb773a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column death_in_weeks
		dataType: int64
		formatString: 0
		lineageTag: fcd2c357-cdad-43ea-9bb0-d99c01574eec
		summarizeBy: sum
		sourceColumn: death_in_weeks

		annotation SummarizationSetBy = Automatic

	column living_alone_status
		dataType: string
		lineageTag: 56a1850b-bb83-474d-81d1-ff42f99a4cdb
		summarizeBy: none
		sourceColumn: living_alone_status

		annotation SummarizationSetBy = Automatic

	column 'Broad Type (confirmed)'
		dataType: string
		lineageTag: 0d3d4418-ff3a-4b3f-afc1-831251e0b5d1
		summarizeBy: none
		sourceColumn: Broad Type (confirmed)

		annotation SummarizationSetBy = Automatic

	column 'Broad Type (old)'
		dataType: string
		lineageTag: d76d3bb2-2563-486b-a588-154a462bcb58
		summarizeBy: none
		sourceColumn: Broad Type (old)

		annotation SummarizationSetBy = Automatic

	column Refresh_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a72040a8-a50a-4de0-a5be-f6be406c9a2e
		summarizeBy: none
		sourceColumn: Refresh_date

		variation Variation
			isDefault
			relationship: 19d06b1e-1f50-4f4e-b70c-2e5f8bbb45cc
			defaultHierarchy: LocalDateTable_559aada2-d1ba-4a93-a0db-4c6b5e6cda79.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column cds_unique_identifier
		dataType: string
		lineageTag: 354a3c1e-984f-4516-b810-77692921750c
		summarizeBy: none
		sourceColumn: cds_unique_identifier

		annotation SummarizationSetBy = Automatic

	column Site_code
		dataType: string
		lineageTag: eee73be1-51d9-4120-a697-d9203b3b741e
		summarizeBy: none
		sourceColumn: Site_code

		annotation SummarizationSetBy = Automatic

	column Arrival_mode
		dataType: string
		lineageTag: 96402943-512b-415f-8532-5c634cdb44c0
		summarizeBy: none
		sourceColumn: Arrival_mode

		annotation SummarizationSetBy = Automatic

	column Attendance_source
		dataType: string
		lineageTag: 76c7fc48-10c0-4558-99a8-8dfe2e999c5d
		summarizeBy: none
		sourceColumn: Attendance_source

		annotation SummarizationSetBy = Automatic

	column Discharge_status
		dataType: string
		lineageTag: d12205d5-616c-41ab-99f1-4258e7b8e4f1
		summarizeBy: none
		sourceColumn: Discharge_status

		annotation SummarizationSetBy = Automatic

	column Discharge_destination
		dataType: string
		lineageTag: 216c7aef-5e29-4566-b8e4-a16267b4b55c
		summarizeBy: none
		sourceColumn: Discharge_destination

		annotation SummarizationSetBy = Automatic

	column local_discharge_status
		dataType: string
		lineageTag: 64f7dc6a-82e0-4b5d-bea7-6bf1bdb669fa
		summarizeBy: none
		sourceColumn: local_discharge_status

		annotation SummarizationSetBy = Automatic

	column local_disposal_method_grouped
		dataType: string
		lineageTag: e7ad4b67-4413-48d1-b22c-94e27fabf6a7
		summarizeBy: none
		sourceColumn: local_disposal_method_grouped

		annotation SummarizationSetBy = Automatic

	column incident_location
		dataType: string
		lineageTag: eeb38f4b-5d65-4274-b879-0d6810b81cac
		summarizeBy: none
		sourceColumn: incident_location

		annotation SummarizationSetBy = Automatic

	column incident_location_home_or_not
		dataType: string
		lineageTag: efae4427-7435-4313-b0a6-2e9a360a6528
		summarizeBy: none
		sourceColumn: incident_location_home_or_not

		annotation SummarizationSetBy = Automatic

	column incident_location_grouped
		dataType: string
		lineageTag: a56af24b-17d1-4aa5-842a-7d2ce36a2aa3
		summarizeBy: none
		sourceColumn: incident_location_grouped

		annotation SummarizationSetBy = Automatic

	column Source_of_referral
		dataType: string
		lineageTag: 529889e6-7e33-4f3b-8524-b64b6db33373
		summarizeBy: none
		sourceColumn: Source_of_referral

		annotation SummarizationSetBy = Automatic

	column day_time_attendance
		dataType: string
		lineageTag: 670d5a3d-0ee9-4b31-ad50-72169830954a
		summarizeBy: none
		sourceColumn: day_time_attendance

		annotation SummarizationSetBy = Automatic

	column hour_of_attendance
		dataType: string
		lineageTag: 2d4351d5-6626-47f1-9056-b9a25368d3e9
		summarizeBy: none
		sourceColumn: hour_of_attendance

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 3f8ad584-fdd5-42d3-8838-7204af007bd7
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'ED max financial month' = ```
			
			VAR currmonth = MONTH(MAX('ED Falls (GHFT Only)'[arrival_date]))
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 188d036c-a09d-4a77-a16c-20e499ef2e38
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED financial month' = ```
			
			VAR currmonth = MONTH('ED Falls (GHFT Only)'[arrival_date]
			)
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 9bdb9091-b7fb-4ac0-b2f2-126b0522359d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED YTD' = ```
			IF('ED Falls (GHFT Only)'[ED financial month] <= 'ED Falls (GHFT Only)'[ED max financial month], "Year to Date", "Not Year to Date")
			
			```
		lineageTag: ca4c5e32-1884-4f9f-a75f-4d69d9cf7fcd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT max financial month' = ```
			
			VAR currmonth = MONTH(MAX('ED Falls (GHFT Only)'[arrival_date]))
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: bc0f14b7-8d13-4d65-a077-9e204e3b9558
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT financial month' = ```
			
			VAR currmonth = MONTH('ED Falls (GHFT Only)'[arrival_date])
			VAR cal = SWITCH(TRUE(),
			currmonth = 4, 1,
			currmonth = 5, 2,
			currmonth = 6, 3,
			currmonth = 7, 4,
			currmonth = 8, 5,
			currmonth = 9, 6,
			currmonth = 10, 7,
			currmonth = 11, 8,
			currmonth = 12, 9,
			currmonth = 1, 10,
			currmonth = 2, 11,
			currmonth = 3, 12
			)
			return cal
			
			```
		formatString: 0
		lineageTag: 263b3a30-5a45-42d5-8403-617d9dda1698
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT YTD' = ```
			if('ED Falls (GHFT Only)'[ED financial month] <= 'ED Falls (GHFT Only)'[ED GHFT max financial month], "Year to Date", "Not Year to Date")
			
			```
		lineageTag: b879308b-9d9c-4aa4-a9a7-7e4b486cc48a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT current year' = ```
			
			VAR max_year = YEAR(MAX('ED Falls (GHFT Only)'[arrival_date]))
			VAR max_month = MONTH(MAX('ED Falls (GHFT Only)'[arrival_date]))
			VAR financial_month = SWITCH(TRUE(),
			max_month = 4, 1,
			max_month = 5, 2,
			max_month = 6, 3,
			max_month = 7, 4,
			max_month = 8, 5,
			max_month = 9, 6,
			max_month = 10, 7,
			max_month = 11, 8,
			max_month = 12, 9,
			max_month = 1, 10,
			max_month = 2, 11,
			max_month = 3, 12
			)
			VAR adjust_year = SWITCH(TRUE(),
			max_month = 1, max_year - 1,
			max_month = 2, max_year - 1,
			max_month = 3, max_year - 1,
			max_month = 4, max_year,
			max_month = 5, max_year,
			max_month = 6, max_year,
			max_month = 7, max_year,
			max_month = 8, max_year,
			max_month = 9, max_year,
			max_month = 10, max_year,
			max_month = 11, max_year,
			max_month = 12, max_year
			)
			return adjust_year
			
			```
		formatString: 0
		lineageTag: 6f38b479-6549-41b5-8018-28cc82f6d22c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT year adjusted' = ```
			if(
			    'ED Falls (GHFT Only)'[ED financial month] = 10, YEAR('ED Falls (GHFT Only)'[arrival_date]) -1, 
			    if('ED Falls (GHFT Only)'[ED financial month] = 11, YEAR('ED Falls (GHFT Only)'[arrival_date]) -1, 
			    if('ED Falls (GHFT Only)'[ED financial month] = 12, YEAR('ED Falls (GHFT Only)'[arrival_date]) -1, year('ED Falls (GHFT Only)'[arrival_date]))))
			
			```
		formatString: 0
		lineageTag: 3d701930-9272-4420-a5d7-e793301d9365
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ED GHFT previous year' = ```
			'ED Falls (GHFT Only)'[ED GHFT current year] - 1
			
			```
		formatString: 0
		lineageTag: f1d9f249-a395-41e2-b538-8a21560379fb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column LSOA_11
		dataType: string
		lineageTag: f643e4e3-9eed-4baf-9f80-7be1d544d23b
		summarizeBy: none
		sourceColumn: LSOA_11

		annotation SummarizationSetBy = Automatic

	column Ethnic_Category
		dataType: string
		lineageTag: 0e4cdc68-8b47-42c6-8bbe-0c2249ee2e36
		summarizeBy: none
		sourceColumn: Ethnic_Category

		annotation SummarizationSetBy = Automatic

	column Diagnosis_all
		dataType: string
		lineageTag: 435dd97e-b5aa-4617-9b64-3957cef03608
		summarizeBy: none
		sourceColumn: Diagnosis_all

		annotation SummarizationSetBy = Automatic

	column Diagnosis_1
		dataType: string
		lineageTag: 0910f560-0d9d-4360-b1a9-acbd127c3147
		summarizeBy: none
		sourceColumn: Diagnosis_1

		annotation SummarizationSetBy = Automatic

	column Diagnosis_2
		dataType: string
		lineageTag: e3be61a9-378b-4a16-8852-b0dd022389fd
		summarizeBy: none
		sourceColumn: Diagnosis_2

		annotation SummarizationSetBy = Automatic

	column Diagnosis_3
		dataType: string
		lineageTag: 5975db15-f778-4d40-9e2a-77d010e82fd9
		summarizeBy: none
		sourceColumn: Diagnosis_3

		annotation SummarizationSetBy = Automatic

	column Diagnosis_4
		dataType: string
		lineageTag: 52438d82-73e5-4002-988d-370dd43cda16
		summarizeBy: none
		sourceColumn: Diagnosis_4

		annotation SummarizationSetBy = Automatic

	column Diagnosis_5
		dataType: string
		lineageTag: 337a78cd-5f90-4291-897c-9b10fe4486c7
		summarizeBy: none
		sourceColumn: Diagnosis_5

		annotation SummarizationSetBy = Automatic

	column Diagnosis_6
		dataType: string
		lineageTag: a94b966b-4104-4ca9-87cf-4d3346f73f85
		summarizeBy: none
		sourceColumn: Diagnosis_6

		annotation SummarizationSetBy = Automatic

	column Diagnosis_7
		dataType: string
		lineageTag: 8acd9526-0664-498c-8878-2740c7f006bb
		summarizeBy: none
		sourceColumn: Diagnosis_7

		annotation SummarizationSetBy = Automatic

	column Diagnosis_8
		dataType: string
		lineageTag: 5455e3ae-c931-47f3-9c36-91e6254cf86a
		summarizeBy: none
		sourceColumn: Diagnosis_8

		annotation SummarizationSetBy = Automatic

	column Treatment_all
		dataType: string
		lineageTag: bcd6c9a9-41da-4810-889b-1b86a637b7ae
		summarizeBy: none
		sourceColumn: Treatment_all

		annotation SummarizationSetBy = Automatic

	column Treatment_1
		dataType: string
		lineageTag: 808be6e1-10d8-40cf-a2f8-e0f82edcb078
		summarizeBy: none
		sourceColumn: Treatment_1

		annotation SummarizationSetBy = Automatic

	column Treatment_2
		dataType: string
		lineageTag: bb9ba4fe-afe2-4503-a558-1301e06ebd2f
		summarizeBy: none
		sourceColumn: Treatment_2

		annotation SummarizationSetBy = Automatic

	column Treatment_3
		dataType: string
		lineageTag: aa40f85b-b206-4dfe-a245-179326796ecf
		summarizeBy: none
		sourceColumn: Treatment_3

		annotation SummarizationSetBy = Automatic

	column Treatment_4
		dataType: string
		lineageTag: af641382-9244-4a65-ba5e-3e3d03feb95a
		summarizeBy: none
		sourceColumn: Treatment_4

		annotation SummarizationSetBy = Automatic

	column Treatment_5
		dataType: string
		lineageTag: 7a5aae36-56f6-4706-b5c3-b1dc7efff1c1
		summarizeBy: none
		sourceColumn: Treatment_5

		annotation SummarizationSetBy = Automatic

	column Treatment_6
		dataType: string
		lineageTag: e40070d9-e310-4a0f-aa1a-7b0732fb2b60
		summarizeBy: none
		sourceColumn: Treatment_6

		annotation SummarizationSetBy = Automatic

	column Treatment_7
		dataType: string
		lineageTag: a5260539-5ecc-499f-adb1-511955b7e464
		summarizeBy: none
		sourceColumn: Treatment_7

		annotation SummarizationSetBy = Automatic

	column Treatment_8
		dataType: string
		lineageTag: c34a1131-e95a-4792-90ff-23206acd234b
		summarizeBy: none
		sourceColumn: Treatment_8

		annotation SummarizationSetBy = Automatic

	column Chief_Complaint_translated
		dataType: string
		lineageTag: dfebd661-df23-4f04-a21a-1fd279ad1698
		summarizeBy: none
		sourceColumn: Chief_Complaint_translated

		annotation SummarizationSetBy = Automatic

	column Investigation_all
		dataType: string
		lineageTag: dd5d3d09-6e0c-4656-aff2-d7423a301559
		summarizeBy: none
		sourceColumn: Investigation_all

		annotation SummarizationSetBy = Automatic

	column Investigation_1
		dataType: string
		lineageTag: 4baa8360-63ae-44de-bcd8-a24d58318de5
		summarizeBy: none
		sourceColumn: Investigation_1

		annotation SummarizationSetBy = Automatic

	column Investigation_2
		dataType: string
		lineageTag: 1c662164-4061-4b89-88b4-909656569c84
		summarizeBy: none
		sourceColumn: Investigation_2

		annotation SummarizationSetBy = Automatic

	column Investigation_3
		dataType: string
		lineageTag: e736a65f-b9a9-4c3b-8c76-98aa30051174
		summarizeBy: none
		sourceColumn: Investigation_3

		annotation SummarizationSetBy = Automatic

	column Investigation_4
		dataType: string
		lineageTag: 1b0eb14c-9a0d-4a64-851c-b0fb6bc1c5f7
		summarizeBy: none
		sourceColumn: Investigation_4

		annotation SummarizationSetBy = Automatic

	column Investigation_5
		dataType: string
		lineageTag: 5a93e770-1dcb-4251-8bb2-86affd0f00e7
		summarizeBy: none
		sourceColumn: Investigation_5

		annotation SummarizationSetBy = Automatic

	column Investigation_6
		dataType: string
		lineageTag: 37b8d28e-2769-4f43-a514-17e0552e8fc7
		summarizeBy: none
		sourceColumn: Investigation_6

		annotation SummarizationSetBy = Automatic

	column Investigation_7
		dataType: string
		lineageTag: 5700f2ff-a3a7-488b-bc6a-2ca0cf6cd8b4
		summarizeBy: none
		sourceColumn: Investigation_7

		annotation SummarizationSetBy = Automatic

	column Investigation_8
		dataType: string
		lineageTag: f9e8c023-b23e-4297-96f9-0b2d74be9c3c
		summarizeBy: none
		sourceColumn: Investigation_8

		annotation SummarizationSetBy = Automatic

	column 'Injury Flag'
		dataType: string
		lineageTag: 67201975-a091-4e82-b19b-c31c4b677219
		summarizeBy: none
		sourceColumn: Injury Flag

		annotation SummarizationSetBy = Automatic

	column Arrival_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: e771d36f-b124-4f1c-9e1a-f53302b0dbf3
		summarizeBy: none
		sourceColumn: Arrival_Date

		variation Variation
			isDefault
			relationship: b2978496-bbe2-44c0-a7bb-2c20ab3cadf4
			defaultHierarchy: LocalDateTable_24dd093a-d4fe-4e24-98d6-ef46629fe784.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column care_home_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4b63b893-20c2-45c7-80cb-8fa4fc2c8856
		summarizeBy: none
		sourceColumn: care_home_date

		variation Variation
			isDefault
			relationship: e57a9f97-e20b-4d9f-89d3-39bdc8312bb0
			defaultHierarchy: LocalDateTable_440a82be-4a38-4343-9779-e6c22003a1ee.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column End_date
		dataType: dateTime
		formatString: General Date
		lineageTag: bbb43440-e3de-4e4d-9179-2e2427cbc877
		summarizeBy: none
		sourceColumn: End_date

		variation Variation
			isDefault
			relationship: 19307628-bd06-4ef4-bea4-361f0ee1ecaf
			defaultHierarchy: LocalDateTable_794aaa06-35e1-46a0-9b34-8f297b3076f3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_1
		dataType: string
		lineageTag: 42deca61-aefb-4c20-8249-c6712d08eb96
		summarizeBy: none
		sourceColumn: Diagnoses_Code_1

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_2
		dataType: string
		lineageTag: 18334233-5964-4aed-b5a1-fb7eee5669de
		summarizeBy: none
		sourceColumn: Diagnoses_Code_2

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_3
		dataType: string
		lineageTag: f99002b3-c8ee-4b11-9ae7-3f2b08e4a3a5
		summarizeBy: none
		sourceColumn: Diagnoses_Code_3

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_4
		dataType: string
		lineageTag: e0ca0917-8ea6-4c48-b402-67d17e3cc208
		summarizeBy: none
		sourceColumn: Diagnoses_Code_4

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_5
		dataType: string
		lineageTag: 432d0c31-a15b-48d1-bab4-647f229c33b7
		summarizeBy: none
		sourceColumn: Diagnoses_Code_5

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_6
		dataType: string
		lineageTag: 8b039282-2f98-44f3-b9e5-83ee19e1bbfb
		summarizeBy: none
		sourceColumn: Diagnoses_Code_6

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_7
		dataType: string
		lineageTag: cba5c5c4-c4dc-4d4e-8a08-49cdce8660c3
		summarizeBy: none
		sourceColumn: Diagnoses_Code_7

		annotation SummarizationSetBy = Automatic

	column Diagnoses_Code_8
		dataType: string
		lineageTag: e1b8c765-1217-4915-869d-87d8a4eb8833
		summarizeBy: none
		sourceColumn: Diagnoses_Code_8

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_1
		dataType: string
		lineageTag: 344edaf0-a01b-4939-b859-2332d03e53b0
		summarizeBy: none
		sourceColumn: Treatment_Code_1

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_2
		dataType: string
		lineageTag: 91c21005-8647-4983-ac0c-956210ef43c4
		summarizeBy: none
		sourceColumn: Treatment_Code_2

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_3
		dataType: string
		lineageTag: 25671ce8-60ef-44e7-b883-8e884023181c
		summarizeBy: none
		sourceColumn: Treatment_Code_3

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_4
		dataType: string
		lineageTag: ff33f584-ed26-4914-88c2-065ca2994dea
		summarizeBy: none
		sourceColumn: Treatment_Code_4

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_5
		dataType: string
		lineageTag: d64c4d72-75e4-4d44-baaa-33a86f68e5bc
		summarizeBy: none
		sourceColumn: Treatment_Code_5

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_6
		dataType: string
		lineageTag: 7c5e18f5-a66e-4a82-a4d1-403c184f67e8
		summarizeBy: none
		sourceColumn: Treatment_Code_6

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_7
		dataType: string
		lineageTag: 82ab13ab-2c99-4532-8a31-50e9d4236236
		summarizeBy: none
		sourceColumn: Treatment_Code_7

		annotation SummarizationSetBy = Automatic

	column Treatment_Code_8
		dataType: string
		lineageTag: d7ec8312-1edf-43ff-8474-6607f636e6d2
		summarizeBy: none
		sourceColumn: Treatment_Code_8

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_1
		dataType: string
		lineageTag: bd7a0283-2463-4a30-8411-7e27e4fe7a92
		summarizeBy: none
		sourceColumn: Investigation_Code_1

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_2
		dataType: string
		lineageTag: 45e8b55d-f5f2-4d02-91ed-7a394039f17e
		summarizeBy: none
		sourceColumn: Investigation_Code_2

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_3
		dataType: string
		lineageTag: 1a333372-84ae-4e69-a54f-db665aadf7bc
		summarizeBy: none
		sourceColumn: Investigation_Code_3

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_4
		dataType: string
		lineageTag: 9d05f17b-a1c4-4f4a-a01e-fcddecc1ec95
		summarizeBy: none
		sourceColumn: Investigation_Code_4

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_5
		dataType: string
		lineageTag: 51719e17-ed8e-4503-8cee-f030bafbbc8c
		summarizeBy: none
		sourceColumn: Investigation_Code_5

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_6
		dataType: string
		lineageTag: e99d0e16-a65a-417c-a3ed-0b4e935315ae
		summarizeBy: none
		sourceColumn: Investigation_Code_6

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_7
		dataType: string
		lineageTag: 38116e0d-5d7f-43ea-b7fa-4dda28f6dc01
		summarizeBy: none
		sourceColumn: Investigation_Code_7

		annotation SummarizationSetBy = Automatic

	column Investigation_Code_8
		dataType: string
		lineageTag: 0bad9413-e207-4d45-af6b-f4313fe426f4
		summarizeBy: none
		sourceColumn: Investigation_Code_8

		annotation SummarizationSetBy = Automatic

	column Destination
		dataType: string
		lineageTag: b4f82c8f-8c19-4890-8a95-af3a84b9cce5
		summarizeBy: none
		sourceColumn: Destination

		annotation SummarizationSetBy = Automatic

	column Chief_Complaint
		dataType: string
		lineageTag: b41dc63e-84bb-47fa-ac7c-10431b058208
		summarizeBy: none
		sourceColumn: Chief_Complaint

		annotation SummarizationSetBy = Automatic

	column Stated_Gender
		dataType: string
		lineageTag: 0324725b-08b8-4c4a-97f2-ede03e30a2c5
		summarizeBy: none
		sourceColumn: Stated_Gender

		annotation SummarizationSetBy = Automatic

	column Age_At_CDS_Activity_Date
		dataType: string
		lineageTag: a219c439-4219-4ee4-a7fb-14f446f3d916
		summarizeBy: none
		sourceColumn: Age_At_CDS_Activity_Date

		annotation SummarizationSetBy = Automatic

	column ProcessedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5237ddb5-e276-49b1-a6ad-195c7d991dcb
		summarizeBy: none
		sourceColumn: ProcessedDate

		variation Variation
			isDefault
			relationship: 88fc0df0-dd7e-4b56-8dbe-35e48a55e046
			defaultHierarchy: LocalDateTable_8778e06d-98e5-43c8-a2a1-a84c9dae3656.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	hierarchy 'locality Hierarchy'
		lineageTag: abbf225f-29f4-4837-b25a-4ed29cd4d1fc

		level locality
			lineageTag: 61b8e256-55a2-4515-86d8-8bdda19c3fef
			column: locality

		level primary_care_network
			lineageTag: da7647e5-3eb3-4cf0-90c4-45a425e4ac8d
			column: primary_care_network

	partition 'ED Falls (GHFT Only)-1dc2f4ba-4ece-46db-8fe3-1c6f8763b10f' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select type, refresh_date as ""Refresh_date"", cds_unique_identifier, arrival_date as ""Arrival_Date"", nhs_number, derived_islivingalone as ""Derived_IsLivingAlone"", diagnosis_all as ""Diagnosis_all"", diagnosis_1 as ""Diagnosis_1"", diagnosis_2 as ""Diagnosis_2"", diagnosis_3 as ""Diagnosis_3"", diagnosis_4 as ""Diagnosis_4"", diagnosis_5 as ""Diagnosis_5"", diagnosis_6 as ""Diagnosis_6"", diagnosis_7 as ""Diagnosis_7"", diagnosis_8 as ""Diagnosis_8"", treatment_all as ""Treatment_all"", treatment_1 as ""Treatment_1"", treatment_2 as ""Treatment_2"", treatment_3 as ""Treatment_3"", treatment_4 as ""Treatment_4"", treatment_5 as ""Treatment_5"", treatment_6 as ""Treatment_6"", treatment_7 as ""Treatment_7"", treatment_8 as ""Treatment_8"", investigation_all as ""Investigation_all"", investigation_1 as ""Investigation_1"", investigation_2 as ""Investigation_2"", investigation_3 as ""Investigation_3"", investigation_4 as ""Investigation_4"", investigation_5 as ""Investigation_5"", investigation_6 as ""Investigation_6"", investigation_7 as ""Investigation_7"", investigation_8 as ""Investigation_8"", living_alone_status, pds_date as ""PDS_date"", date_of_incident as ""Date_of_incident"", broad_type_confirmed as ""Broad Type (confirmed)"", broad_type_old as ""Broad Type (old)"", care_home_date, end_date as ""End_date"", provider_code, site_code as ""Site_code"", site, arrival_date_time, arrival_time_flag, day_time_attendance, hour_of_attendance, year_month, month_name, financial_year, ""5yr_age_band"", gender as ""Gender"", practice_code, correct_practice_code, reportingorganisationname as ""ReportingOrganisationName"", practice_name, primary_care_network, locality, hrg_code, hrg_description, counter, ed_department_type, frailty_score, frailty_category, deceased_nhs_number, mortality_flag, date_of_death, death_in_weeks, presenting_complaint, ""10_year_age_band"", dementia_status, arrival_mode as ""Arrival_mode"", attendance_source as ""Attendance_source"", discharge_status as ""Discharge_status"", discharge_destination as ""Discharge_destination"", local_discharge_status, local_disposal_method_grouped, admitted_flag_description, admitted_flag, grouped_ed_arrival_method, incident_location, incident_location_home_or_not, incident_location_grouped, source_of_referral as ""Source_of_referral"", lsoa_11 as ""LSOA_11"", ethnic_category as ""Ethnic_Category"", chief_complaint_translated as ""Chief_Complaint_translated"", diagnoses_code_1 as ""Diagnoses_Code_1"", diagnoses_code_2 as ""Diagnoses_Code_2"", diagnoses_code_3 as ""Diagnoses_Code_3"", diagnoses_code_4 as ""Diagnoses_Code_4"", diagnoses_code_5 as ""Diagnoses_Code_5"", diagnoses_code_6 as ""Diagnoses_Code_6"", diagnoses_code_7 as ""Diagnoses_Code_7"", diagnoses_code_8 as ""Diagnoses_Code_8"", treatment_code_1 as ""Treatment_Code_1"", treatment_code_2 as ""Treatment_Code_2"", treatment_code_3 as ""Treatment_Code_3"", treatment_code_4 as ""Treatment_Code_4"", treatment_code_5 as ""Treatment_Code_5"", treatment_code_6 as ""Treatment_Code_6"", treatment_code_7 as ""Treatment_Code_7"", treatment_code_8 as ""Treatment_Code_8"", investigation_code_1 as ""Investigation_Code_1"", investigation_code_2 as ""Investigation_Code_2"", investigation_code_3 as ""Investigation_Code_3"", investigation_code_4 as ""Investigation_Code_4"", investigation_code_5 as ""Investigation_Code_5"", investigation_code_6 as ""Investigation_Code_6"", investigation_code_7 as ""Investigation_Code_7"", investigation_code_8 as ""Investigation_Code_8"", destination as ""Destination"", chief_complaint as ""Chief_Complaint"", stated_gender as ""Stated_Gender"", age_at_cds_activity_date as ""Age_At_CDS_Activity_Date"", care_home_status as ""Care_home_status"", processeddate as ""ProcessedDate"" from data_mart_powerbi_falls.tbl02_falls_ed_ghft_only", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"counter", "counter_ED_falls"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"admitted_flag", Int64.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"admitted_flag", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Injury Flag", each if Text.Contains([Diagnosis_all], "No abnormality detected") then "No" else "Yes")
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

