table 'Ethnicity reference'
	lineageTag: 776da49f-1047-4663-9dce-3a090b5e4eff

	column 'Ethnic Code'
		dataType: string
		lineageTag: 9e647f22-fe8a-4d64-84dc-ad238aeb2539
		summarizeBy: none
		sourceColumn: Ethnic Code

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Description'
		dataType: string
		lineageTag: 65ce6efb-61c5-4485-925b-f618efefa3c0
		summarizeBy: none
		sourceColumn: Ethnic Description

		annotation SummarizationSetBy = Automatic

	partition 'Ethnicity reference' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fZDNTsMwEIRfxfK5PECPSSnlr6WCAxJRD05s6lXKurKNgLdn401IiMA3a+ab9exWlSzkQj5biEZciNJDhGDlYVHJcqLf+EFdTdQCv4SL1njBSq2a9ujdO+qEXhK6hU+jCWVAoRbliSixUh7q2ihM5DpDFq8emp67+pMrAvT+ZuKP5d6SMit3TWgKCud5wrB8ty7qYeRtjturFkJUCAm9y6GlwuNJaRMsw/c5eOzOzqz7lrJ8HMryY8z+vuwuh05Pu8+CP33YmfV5pOxDstfRIjRiQ945dGUsoAkmUU//UuN4w043+5xCLxTauSjoytHwb8tlr7XoPqj84Rs=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Ethnic Code" = _t, #"Ethnic Description" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Ethnic Code", type text}, {"Ethnic Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

