table 'Frail population'
	lineageTag: 99dfb3be-3fa7-4ffc-825b-27986ea06973

	column COUNTER
		dataType: int64
		formatString: 0
		lineageTag: 16c61dc7-eccb-42e3-ba38-3862dd347b94
		summarizeBy: sum
		sourceColumn: COUNTER

		annotation SummarizationSetBy = Automatic

	column 'Frailty Category'
		dataType: string
		lineageTag: 36c5dc7f-5c51-4ba0-b03c-8bca2316548a
		summarizeBy: none
		sourceColumn: Frailty Category

		annotation SummarizationSetBy = Automatic

	partition 'Frail population-6813feea-a750-48b0-a19d-691be3a9ea02' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select case when mpi.eficategoryderived ilike 'Fit' then 'Fit' when mpi.eficategoryderived ilike 'mild frailty' then 'Mild Frailty' when mpi.eficategoryderived ilike 'moderate frailty' then 'Moderate Frailty' when mpi.eficategoryderived ilike 'severe frailty' then 'Severe Frailty' when mpi.eficategoryderived ilike 'unknown' then 'Unknown' else 'Unknown' end as frailty_category, count(mpi.pseudonhsnumber) as ""COUNTER"" from data_mart_pls.vw_summary mpi where mpi.derivedage >= 65 group by 1", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"frailty_category", "Frailty Category"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

