table 'GP Reference'
	lineageTag: a9d87f8e-30d3-473c-a67f-a1107d59dc96

	column Locality
		dataType: string
		lineageTag: f9ccbfee-4aff-4b9f-958b-2c0f098f36ca
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column Network
		dataType: string
		lineageTag: e1ea4b08-5631-48b9-9106-3334bf60e80e
		summarizeBy: none
		sourceColumn: Network

		annotation SummarizationSetBy = Automatic

	column Place
		dataType: string
		lineageTag: b5bbf0d2-107a-4269-a49e-fcba8b31edb3
		summarizeBy: none
		sourceColumn: Place

		annotation SummarizationSetBy = Automatic

	column 'Primary Care Network'
		dataType: string
		lineageTag: a10c2c63-8d0a-403c-a6d4-bd3a64998a67
		summarizeBy: none
		sourceColumn: Primary Care Network

		annotation SummarizationSetBy = Automatic

	column OrganisationCode
		dataType: string
		lineageTag: 1306f9a9-6bb5-4f61-ab6c-dde9a4afceda
		summarizeBy: none
		sourceColumn: OrganisationCode

		annotation SummarizationSetBy = Automatic

	column 'Practice Name'
		dataType: string
		lineageTag: 3298b0ae-9da1-40c0-a1ca-b58a5807a8db
		summarizeBy: none
		sourceColumn: Practice Name

		annotation SummarizationSetBy = Automatic

	column ReportingOrganisationName
		dataType: string
		lineageTag: df0cfa60-c018-4362-bb38-703080831b6e
		summarizeBy: none
		sourceColumn: ReportingOrganisationName

		annotation SummarizationSetBy = Automatic

	column ITSystem
		dataType: string
		lineageTag: 444c2b6a-c0a6-4f00-8dff-ba1c0cfbc75e
		summarizeBy: none
		sourceColumn: ITSystem

		annotation SummarizationSetBy = Automatic

	column NumberOfLocations
		dataType: int64
		formatString: 0
		lineageTag: 08c5bc4c-84fb-49e6-96da-7cf3da1bd9b7
		summarizeBy: sum
		sourceColumn: NumberOfLocations

		annotation SummarizationSetBy = Automatic

	column NumberOfEnhancedServices
		dataType: int64
		formatString: 0
		lineageTag: ba763e3e-7ada-4cde-baa9-7eb5d60e5372
		summarizeBy: sum
		sourceColumn: NumberOfEnhancedServices

		annotation SummarizationSetBy = Automatic

	column DispensingPractice
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bac853d3-e20d-4b66-8011-7ffdd55ce1b3
		summarizeBy: none
		sourceColumn: DispensingPractice

		annotation SummarizationSetBy = Automatic

	column DispensingPracticeDescription
		dataType: string
		lineageTag: 9caeeddf-9ecc-48d3-9997-70f74e35a081
		summarizeBy: none
		sourceColumn: DispensingPracticeDescription

		annotation SummarizationSetBy = Automatic

	column ContractType
		dataType: string
		lineageTag: 3de18fa9-8f8d-40d5-8119-a5d25480e00f
		summarizeBy: none
		sourceColumn: ContractType

		annotation SummarizationSetBy = Automatic

	column CoCommissioningModel
		dataType: string
		lineageTag: b844b7d8-46a1-4cc4-b92a-d2a2378f4431
		summarizeBy: none
		sourceColumn: CoCommissioningModel

		annotation SummarizationSetBy = Automatic

	column OnlineAppointmentsEnabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f5184830-77af-4bf9-b3d9-fb33326e26bd
		summarizeBy: none
		sourceColumn: OnlineAppointmentsEnabled

		annotation SummarizationSetBy = Automatic

	column OnlineAppointmentsEnabledDescription
		dataType: string
		lineageTag: b83bf3b9-8109-41b7-91ef-c935a1977f72
		summarizeBy: none
		sourceColumn: OnlineAppointmentsEnabledDescription

		annotation SummarizationSetBy = Automatic

	column OnlinePrescriptionsEnabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fc66d998-7323-4fc3-9d5c-572cb3feac08
		summarizeBy: none
		sourceColumn: OnlinePrescriptionsEnabled

		annotation SummarizationSetBy = Automatic

	column OnlinePrescriptionsEnabledDescription
		dataType: string
		lineageTag: 3efbb0cb-df68-4aab-a96e-c5a06943654b
		summarizeBy: none
		sourceColumn: OnlinePrescriptionsEnabledDescription

		annotation SummarizationSetBy = Automatic

	column NationalGrouping
		dataType: string
		lineageTag: b9b1a962-88bb-4df8-8949-de4671a8b948
		summarizeBy: none
		sourceColumn: NationalGrouping

		annotation SummarizationSetBy = Automatic

	column HighLevelHealthGeography
		dataType: string
		lineageTag: 0180ceb1-d7da-4447-9198-1c8b9318cf3a
		summarizeBy: none
		sourceColumn: HighLevelHealthGeography

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		lineageTag: b6708a48-d06d-4359-aa48-1c7d5ab8b672
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

	column AddressLine2
		dataType: string
		lineageTag: 0c3af911-081f-4e31-9488-dd9ceb173bbb
		summarizeBy: none
		sourceColumn: AddressLine2

		annotation SummarizationSetBy = Automatic

	column AddressLine3
		dataType: string
		lineageTag: 13cbc7ff-24e8-4737-a123-e4bd1b02be9a
		summarizeBy: none
		sourceColumn: AddressLine3

		annotation SummarizationSetBy = Automatic

	column AddressLine4
		dataType: string
		lineageTag: 2e7a7d7e-dfa0-45b5-b1ff-7174bf7a80b9
		summarizeBy: none
		sourceColumn: AddressLine4

		annotation SummarizationSetBy = Automatic

	column AddressLine5
		dataType: string
		lineageTag: 3b0490da-4107-4f2a-99eb-435c66fe8c93
		summarizeBy: none
		sourceColumn: AddressLine5

		annotation SummarizationSetBy = Automatic

	column Postcode
		dataType: string
		lineageTag: ea0cf3cc-4d6e-4750-b27c-08496b9ef20c
		summarizeBy: none
		sourceColumn: Postcode

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: string
		lineageTag: bb77ca4c-ef4e-4c49-9406-fdf738d6ba6b
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

	column CloseDate
		dataType: string
		lineageTag: 4aebda61-e3c1-4626-8878-bdb38c348043
		summarizeBy: none
		sourceColumn: CloseDate

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: string
		lineageTag: cc1e45d3-6c4e-41bb-ae0f-8122fda56c56
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = Automatic

	column StatusDescription
		dataType: string
		lineageTag: 45d4eb59-df3e-41f6-abd4-7a5b64054cac
		summarizeBy: none
		sourceColumn: StatusDescription

		annotation SummarizationSetBy = Automatic

	column OrganisationSubTypeCode
		dataType: string
		lineageTag: 67bc3fda-118f-49a8-aa92-6ef55c449f83
		summarizeBy: none
		sourceColumn: OrganisationSubTypeCode

		annotation SummarizationSetBy = Automatic

	column OrganisationSubTypeDescription
		dataType: string
		lineageTag: 92907f72-032b-40ae-bc16-868dc0eb5b17
		summarizeBy: none
		sourceColumn: OrganisationSubTypeDescription

		annotation SummarizationSetBy = Automatic

	column Commissioner
		dataType: string
		lineageTag: b7212d29-2d8f-4ba9-a9f1-0e5a36c2bc97
		summarizeBy: none
		sourceColumn: Commissioner

		annotation SummarizationSetBy = Automatic

	column JoinProviderPurchaserDate
		dataType: string
		lineageTag: d2de5642-f40a-411f-8cde-f7fb8e848c7e
		summarizeBy: none
		sourceColumn: JoinProviderPurchaserDate

		annotation SummarizationSetBy = Automatic

	column LeftProviderPurchaserDate
		dataType: string
		lineageTag: a6e9491d-1bbd-44f3-ac0b-038ede8bf40d
		summarizeBy: none
		sourceColumn: LeftProviderPurchaserDate

		annotation SummarizationSetBy = Automatic

	column ContactTelephoneNumber
		dataType: string
		lineageTag: 4e074bae-01d5-4886-8d90-661b233da59c
		summarizeBy: none
		sourceColumn: ContactTelephoneNumber

		annotation SummarizationSetBy = Automatic

	column AmendedRecordIndicator
		dataType: string
		lineageTag: 8c3b886c-476d-4326-82f4-5ae65c234d14
		summarizeBy: none
		sourceColumn: AmendedRecordIndicator

		annotation SummarizationSetBy = Automatic

	column ProviderPurchaser
		dataType: string
		lineageTag: 9491e35a-15b1-4f02-b2db-58274e388d38
		summarizeBy: none
		sourceColumn: ProviderPurchaser

		annotation SummarizationSetBy = Automatic

	column PrescribingSetting
		dataType: string
		lineageTag: 920ddd0b-bfdf-4bc6-87a0-c950f9b9635d
		summarizeBy: none
		sourceColumn: PrescribingSetting

		annotation SummarizationSetBy = Automatic

	column PrescribingSettingDescription
		dataType: string
		lineageTag: 5394df84-6465-4468-8f54-4c25b99c6959
		summarizeBy: none
		sourceColumn: PrescribingSettingDescription

		annotation SummarizationSetBy = Automatic

	column UpdateDate
		dataType: string
		lineageTag: b81fad85-5d72-440c-ba83-c27340c6bb37
		summarizeBy: none
		sourceColumn: UpdateDate

		annotation SummarizationSetBy = Automatic

	column ReportingOrganisationCode
		dataType: string
		lineageTag: 860ac565-338b-416d-be6a-a1bcbbb344b8
		summarizeBy: none
		sourceColumn: ReportingOrganisationCode

		annotation SummarizationSetBy = Automatic

	hierarchy 'Locality Hierarchy'
		lineageTag: e70fbf9f-2478-462e-a605-24cb6c185a5c

		level Locality
			lineageTag: 5a6f591c-3b3c-407a-bcd1-f2ebbdc31050
			column: Locality

		level 'Primary Care Network'
			lineageTag: 06c30b5e-c0d8-483e-96e1-21826a2d646e
			column: 'Primary Care Network'

		level ReportingOrganisationName
			lineageTag: 39aefcd5-54b1-42b7-9d8d-070af4443507
			column: ReportingOrganisationName

	partition 'GP Reference' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select case when locality ilike '%cotswold%' then 'Cotswolds' else locality end as ""Locality"", network as ""Network"", place as ""Place"", primarycarenetwork as ""PrimaryCareNetwork"", organisationcode as ""OrganisationCode"", organisationname as ""OrganisationName"", reportingorganisationname as ""ReportingOrganisationName"", itsystem as ""ITSystem"", numberoflocations as ""NumberOfLocations"", numberofenhancedservices as ""NumberOfEnhancedServices"", dispensingpractice as ""DispensingPractice"", dispensingpracticedescription as ""DispensingPracticeDescription"", contracttype as ""ContractType"", cocommissioningmodel as ""CoCommissioningModel"", onlineappointmentsenabled as ""OnlineAppointmentsEnabled"", onlineappointmentsenableddescription as ""OnlineAppointmentsEnabledDescription"", onlineprescriptionsenabled as ""OnlinePrescriptionsEnabled"", onlineprescriptionsenableddescription as ""OnlinePrescriptionsEnabledDescription"", nationalgrouping as ""NationalGrouping"", highlevelhealthgeography as ""HighLevelHealthGeography"", addressline1 as ""AddressLine1"", addressline2 as ""AddressLine2"", addressline3 as ""AddressLine3"", addressline4 as ""AddressLine4"", addressline5 as ""AddressLine5"", postcode as ""Postcode"", opendate as ""OpenDate"", closedate as ""CloseDate"", statuscode as ""StatusCode"", statusdescription as ""StatusDescription"", organisationsubtypecode as ""OrganisationSubTypeCode"", organisationsubtypedescription as ""OrganisationSubTypeDescription"", commissioner as ""Commissioner"", joinproviderpurchaserdate as ""JoinProviderPurchaserDate"", leftproviderpurchaserdate as ""LeftProviderPurchaserDate"", contacttelephonenumber as ""ContactTelephoneNumber"", amendedrecordindicator as ""AmendedRecordIndicator"", providerpurchaser as ""ProviderPurchaser"", prescribingsetting as ""PrescribingSetting"", prescribingsettingdescription as ""PrescribingSettingDescription"", updatedate as ""UpdateDate"", reportingorganisationcode as ""ReportingOrganisationCode"" from icb_data_reference.vw_gppractice", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"OrganisationName", "Practice Name"}, {"PrimaryCareNetwork", "Primary Care Network"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

