table 'Hour of day'
	lineageTag: efdc99cd-b6ff-4bd4-9c5f-26892b03ce2a

	column 'Hour of Call'
		dataType: string
		lineageTag: 656aecde-ebde-4a42-b11b-348aba9eb35f
		summarizeBy: none
		sourceColumn: Hour of Call
		sortByColumn: Order

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 1b301d96-147d-49b1-b1a8-0780c5c3fe6a
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Hour of day-b94e474e-1e04-4cf2-b41e-1d84fc361681' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Lc+5FcAwCETBXogVePFdi576b8N7OIGfDcxZqFFda0zOUbtrZx2ug3W6Ttbluli362Y9rof1ul4WNicXG2k5CARJCAVZCAZpCAd5CAiJCAmZCAqpCAu5Hbfldtz2f/+Dcjtuy+24PrPW+gA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Hour of Call" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Hour of Call", type text}, {"Order", Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Order", Order.Ascending}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Sorted Rows","0","12am",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","1","1am",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","1am2am","12am",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","2","2am",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","3","3am",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","4","4am",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","5","5am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","6","6am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","7","7am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","8","8am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","9","9am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","1am12amam","10am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","1am1am","11am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","1am2am","12pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","1am3am","1pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","1am4am","2pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","1am5","3pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","1am6","4pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","1am7","5pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","1am8","6pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","1am9","7pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","2am12amam","8pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","2am1am","9pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","2am2am","10pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","2am3am","11pm",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","12amam","12am",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","12am","0:00",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","1am","1:00",Replacer.ReplaceValue,{"Hour of Call"}),
				    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","2am","2:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","3am","3:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","4am","4:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","5am","5:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value32" = Table.ReplaceValue(#"Replaced Value31","6am","6:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value33" = Table.ReplaceValue(#"Replaced Value32","7am","7:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","8am","8:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value35" = Table.ReplaceValue(#"Replaced Value34","9am","9:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value36" = Table.ReplaceValue(#"Replaced Value35","10am","10:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value37" = Table.ReplaceValue(#"Replaced Value36","11am","11:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value38" = Table.ReplaceValue(#"Replaced Value37","12pm","12:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value39" = Table.ReplaceValue(#"Replaced Value38","1pm","13:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value40" = Table.ReplaceValue(#"Replaced Value39","2pm","14:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value41" = Table.ReplaceValue(#"Replaced Value40","3pm","15:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value42" = Table.ReplaceValue(#"Replaced Value41","4pm","16:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value43" = Table.ReplaceValue(#"Replaced Value42","5pm","17:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value44" = Table.ReplaceValue(#"Replaced Value43","6pm","18:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value45" = Table.ReplaceValue(#"Replaced Value44","7pm","19:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value46" = Table.ReplaceValue(#"Replaced Value45","8pm","20:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value47" = Table.ReplaceValue(#"Replaced Value46","9pm","21:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value48" = Table.ReplaceValue(#"Replaced Value47","10pm","22:00",Replacer.ReplaceText,{"Hour of Call"}),
				    #"Replaced Value49" = Table.ReplaceValue(#"Replaced Value48","113:00","23:00",Replacer.ReplaceText,{"Hour of Call"})
				in
				    #"Replaced Value49"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

