table 'IMD Reference'
	lineageTag: c563cbf1-d007-4048-b776-ea55a1c40576

	column LSOACode
		dataType: string
		lineageTag: 447858dc-3d7e-4d18-8594-b75feeafd5fd
		summarizeBy: none
		sourceColumn: LSOACode

		annotation SummarizationSetBy = Automatic

	column Deprivation
		dataType: string
		lineageTag: 1ee604de-be27-4bf2-9e47-5e23c2fa5e2d
		summarizeBy: none
		sourceColumn: Deprivation

		annotation SummarizationSetBy = Automatic

	partition 'IMD Reference' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select distinct l.lsoacode as ""LSOACode"", l.derived_imdgloucestershiredecile as ""Derived_IMDGloucestershireDecile"" from ccg_reference.vw_postcode p left join ccg_reference.vw_lsoa_imd l on l.lsoacode = p.lsoa_2021 where l.lsoacode is not null", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Derived_IMDGloucestershireDecile", "Deprivation"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

