table 'Place Population'
	lineageTag: e82408e1-d6a5-46f9-889c-2ff81f1f72f1

	column 'Practice Name'
		dataType: string
		lineageTag: 1873de2e-2324-4efe-8caa-00a64f82c1a7
		summarizeBy: none
		sourceColumn: Practice Name

		annotation SummarizationSetBy = Automatic

	column 'Primary Care Network'
		dataType: string
		lineageTag: c10d8b9e-4dd4-41de-aaff-964647a6b3b6
		summarizeBy: none
		sourceColumn: Primary Care Network

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 4df671cb-d16b-43f4-83f2-ea801d1fe425
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: int64
		formatString: 0
		lineageTag: 47ef9f7c-4cda-4b62-b9fc-b6ec14300bde
		summarizeBy: sum
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	column 'Practice Code'
		dataType: string
		lineageTag: 68f2a7e6-3421-4814-9639-8d5863e60b1b
		summarizeBy: none
		sourceColumn: Practice Code

		annotation SummarizationSetBy = Automatic

	partition 'Place Population-8d48a121-6143-4b08-8736-14d7ae438563' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select gp.organisationcode as ""Practice Code"", gp.organisationname as ""Practice Name"", gp.primarycarenetwork as ""Primary Care Network"", case when gp.locality ilike '%cotswold%' then 'Cotswolds' else gp.locality end as ""Locality"", count(mpi.pseudonhsnumber) as ""COUNTER"" from data_mart_pls.vw_summary mpi left join db01_reference.icb_data_reference.vw_gppractice gp on mpi.practicecode = gp.organisationcode where mpi.derivedage >= 65 and gp.organisationname not ilike 'The Homeless Healthcare Team' group by 1,2,3,4 order by 1", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"COUNTER", "Population"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

