table 'Acute Admissions'
	lineageTag: fb076462-bc17-4000-a78c-fd26c579a0cc

	column pseudo_nhs_number
		dataType: string
		lineageTag: b738f8fa-4bfc-4e20-a60c-675f801ff880
		summarizeBy: none
		sourceColumn: pseudo_nhs_number

		annotation SummarizationSetBy = Automatic

	column gppractice_derived_name
		dataType: string
		lineageTag: 0cceee31-9ba0-49cb-8fff-e9fa85838a2f
		summarizeBy: none
		sourceColumn: gppractice_derived_name

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: ef309cfa-2bd7-4b42-956e-e34286bf4e1e
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column hospitalproviderspellnumber
		dataType: string
		lineageTag: c4e99132-1f88-479b-b6b9-2034a3506f41
		summarizeBy: none
		sourceColumn: hospitalproviderspellnumber

		annotation SummarizationSetBy = Automatic

	column uniquecdsidentifier
		dataType: string
		lineageTag: 28facefe-8a2e-4ac2-a96f-8b60325c3611
		summarizeBy: none
		sourceColumn: uniquecdsidentifier

		annotation SummarizationSetBy = Automatic

	column spell_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b15dc3a-a2da-40d7-80a5-6ab76f4cc2ef
		summarizeBy: none
		sourceColumn: spell_start_date

		annotation SummarizationSetBy = Automatic

	column spell_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d6a07756-318e-4258-87c0-ff5062de8e49
		summarizeBy: none
		sourceColumn: spell_end_date

		variation Variation
			isDefault
			relationship: f84c63a9-2b08-4267-868c-f7f2b3166874
			defaultHierarchy: LocalDateTable_aa21637e-16cf-40da-ad19-83c42687990b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column los_in_days
		dataType: double
		formatString: 0
		lineageTag: a36aeb3a-42b4-4e0d-872c-f9d2944ad519
		summarizeBy: sum
		sourceColumn: los_in_days

		annotation SummarizationSetBy = Automatic

	column los_bands
		dataType: string
		lineageTag: 256f04a3-4fcb-4122-80f5-0716273e57d6
		summarizeBy: none
		sourceColumn: los_bands

		annotation SummarizationSetBy = Automatic

	column primary_diagnosis
		dataType: string
		lineageTag: 4d01612c-bb23-41ab-b7d3-a9084e1cb3f7
		summarizeBy: none
		sourceColumn: primary_diagnosis

		annotation SummarizationSetBy = Automatic

	column diagnosisprimary_icd
		dataType: string
		lineageTag: fcf53da8-10e6-45ce-a6ba-b3a2beb73125
		summarizeBy: none
		sourceColumn: diagnosisprimary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis1stsecondary_icd
		dataType: string
		isHidden
		lineageTag: 331140ed-a2f4-4069-a4dd-4968d11f4620
		summarizeBy: none
		sourceColumn: diagnosis1stsecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis2ndsecondary_icd
		dataType: string
		isHidden
		lineageTag: e3344173-9ef1-4d78-97c2-954ca5cfc22b
		summarizeBy: none
		sourceColumn: diagnosis2ndsecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis3rdSecondary_icd
		dataType: string
		isHidden
		lineageTag: eb9d3f84-ffab-4f04-b79d-d65110669ca6
		summarizeBy: none
		sourceColumn: diagnosis3rdSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis4thSecondary_icd
		dataType: string
		isHidden
		lineageTag: 958e480d-96ef-45c9-91c3-9b80336db457
		summarizeBy: none
		sourceColumn: diagnosis4thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis5thSecondary_icd
		dataType: string
		isHidden
		lineageTag: 9c2b0027-6bcd-4ce7-ad39-ce737fb889d4
		summarizeBy: none
		sourceColumn: diagnosis5thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis6thSecondary_icd
		dataType: string
		isHidden
		lineageTag: 58cea92d-21d9-4012-ab57-31f212d978eb
		summarizeBy: none
		sourceColumn: diagnosis6thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis7thSecondary_icd
		dataType: string
		isHidden
		lineageTag: 7e8fc1d0-f6f6-4f66-8277-694ab28abba7
		summarizeBy: none
		sourceColumn: diagnosis7thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis8thSecondary_icd
		dataType: string
		isHidden
		lineageTag: 09889b16-5ef1-4cef-941a-bfe4770e4a12
		summarizeBy: none
		sourceColumn: diagnosis8thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis9thSecondary_icd
		dataType: string
		isHidden
		lineageTag: f18eb452-a763-4327-b8f5-1da5fde9ad36
		summarizeBy: none
		sourceColumn: diagnosis9thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis10thSecondary_icd
		dataType: string
		isHidden
		lineageTag: 3c713c5a-b176-4b5a-bb04-3bc9d618c348
		summarizeBy: none
		sourceColumn: diagnosis10thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis11thSecondary_icd
		dataType: string
		isHidden
		lineageTag: 77bdbdf3-b873-4287-958c-8cf290242d1b
		summarizeBy: none
		sourceColumn: diagnosis11thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column diagnosis12thSecondary_icd
		dataType: string
		isHidden
		lineageTag: e9f273f3-5638-43ce-a768-844fa2225fd2
		summarizeBy: none
		sourceColumn: diagnosis12thSecondary_icd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column keyrespiratoryconditionflag
		dataType: string
		lineageTag: 0d29e742-aa2c-4786-82cf-a9afaec7466d
		summarizeBy: none
		sourceColumn: keyrespiratoryconditionflag

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: 62a97a0f-727c-4727-88d4-874ad2d6207c
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column derived_current_totalplusmff
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: fa594b09-c783-45ae-aa85-a7987284b57e
		summarizeBy: sum
		sourceColumn: derived_current_totalplusmff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column los_group
		dataType: string
		lineageTag: f34e5465-9ba9-46d2-b4c4-234ceabe06cd
		summarizeBy: none
		sourceColumn: los_group

		annotation SummarizationSetBy = Automatic

	column admissionmethod_category
		dataType: string
		lineageTag: a6395ec3-44e8-4d8c-b1c2-9d8bf69e86f3
		summarizeBy: none
		sourceColumn: admissionmethod_category

		annotation SummarizationSetBy = Automatic

	column admission_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: ca8b5de0-b832-4f49-8e4a-45060b861e2c
		summarizeBy: none
		sourceColumn: admission_datetime

		variation Variation
			isDefault
			relationship: 94f4aee7-8d95-49ab-a3d8-66eddee75522
			defaultHierarchy: LocalDateTable_a38e54c8-d949-4845-9cb2-6f7567c458a0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column discharge_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 8ac08d70-c2d6-4fd0-877d-e749dacda446
		summarizeBy: none
		sourceColumn: discharge_datetime

		variation Variation
			isDefault
			relationship: ca43e72a-2414-43ad-bd12-3b10fa434f20
			defaultHierarchy: LocalDateTable_f0cf7612-f15b-4a61-af47-7a82e8e9d6c7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column admitting_ward
		dataType: string
		lineageTag: ee738531-8781-4b11-9b54-7614b753b04b
		summarizeBy: none
		sourceColumn: admitting_ward

		annotation SummarizationSetBy = Automatic

	column admitting_ward_code
		dataType: string
		lineageTag: 7f114a78-1d40-4da3-8f5d-f227e9de5019
		summarizeBy: none
		sourceColumn: admitting_ward_code

		annotation SummarizationSetBy = Automatic

	column discharging_ward
		dataType: string
		lineageTag: 01b6a54d-4451-41bb-98fb-9a951add0ae7
		summarizeBy: none
		sourceColumn: discharging_ward

		annotation SummarizationSetBy = Automatic

	column discharging_ward_code
		dataType: string
		lineageTag: 778d52d5-e20c-4440-a157-4e4781706cd6
		summarizeBy: none
		sourceColumn: discharging_ward_code

		annotation SummarizationSetBy = Automatic

	column all_wards
		dataType: string
		lineageTag: 12991bec-0861-453f-a3d4-db793ffd88f5
		summarizeBy: none
		sourceColumn: all_wards

		annotation SummarizationSetBy = Automatic

	column all_ward_codes
		dataType: string
		lineageTag: 6923749d-e624-4fdf-a599-a5612addfa25
		summarizeBy: none
		sourceColumn: all_ward_codes

		annotation SummarizationSetBy = Automatic

	column admit_to_non_ward_area_or_ward
		dataType: string
		lineageTag: 0c4a2318-1ea7-4a32-8feb-40bb4225401c
		summarizeBy: none
		sourceColumn: admit_to_non_ward_area_or_ward

		annotation SummarizationSetBy = Automatic

	column discharge_from_non_ward_or_ward
		dataType: string
		lineageTag: f484aea2-9bfb-4646-b1b3-ecc318bb2482
		summarizeBy: none
		sourceColumn: discharge_from_non_ward_or_ward

		annotation SummarizationSetBy = Automatic

	partition 'Acute Admissions-21b6481c-3777-4d62-b61b-35c26c2c5ba4' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Processing", [Query="EXEC [dbo].[Resp_Emerg_Admissions]#(lf);#(lf)#(lf)SELECT *#(lf)FROM [PowerBI_Reporting].[dbo].[Resp_Emerg_Admissions]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"counter", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

