table 'New Readmissions'
	lineageTag: ef65359d-6d31-426f-a3d1-3d9371b27ce3

	column pseudo_nhs_number
		dataType: string
		lineageTag: 20f841f9-1938-42aa-a475-1161846f979b
		summarizeBy: none
		sourceColumn: pseudo_nhs_number

		annotation SummarizationSetBy = Automatic

	column hospitalproviderspellnumber
		dataType: string
		lineageTag: 47e427c1-c154-458d-8dce-6e836d7ce3a6
		summarizeBy: none
		sourceColumn: hospitalproviderspellnumber

		annotation SummarizationSetBy = Automatic

	column uniquecdsidentifier
		dataType: string
		lineageTag: 4d041867-8209-4d1a-887d-8d4ab62abf29
		summarizeBy: none
		sourceColumn: uniquecdsidentifier

		annotation SummarizationSetBy = Automatic

	column gp_practice_code
		dataType: string
		lineageTag: 7cfe2f5b-3895-4748-8d73-b35f78c68950
		summarizeBy: none
		sourceColumn: gp_practice_code

		annotation SummarizationSetBy = Automatic

	column admission_method_category
		dataType: string
		lineageTag: 2a65c7ce-6e99-4646-b33b-e2e591b3a1b7
		summarizeBy: none
		sourceColumn: admission_method_category

		annotation SummarizationSetBy = Automatic

	column Spell_Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: a1ad9d6d-17d1-435b-a063-6a316b83bc36
		summarizeBy: none
		sourceColumn: Spell_Start_Date

		annotation SummarizationSetBy = Automatic

	column spell_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9ddeddd9-462a-4a32-af63-4d891e4632c9
		summarizeBy: none
		sourceColumn: spell_end_date

		variation Variation
			isDefault
			relationship: 021028c0-0249-46fd-96f9-322d93ed53ec
			defaultHierarchy: LocalDateTable_189afaf5-bfed-490c-9354-fc9d4b7b1339.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column los_in_days
		dataType: int64
		formatString: 0
		lineageTag: d1906583-d266-437f-8869-6b5fbcd32d13
		summarizeBy: sum
		sourceColumn: los_in_days

		annotation SummarizationSetBy = Automatic

	column los_bands
		dataType: string
		lineageTag: 81f70c0b-8e06-4bb8-b776-3e57b8654a27
		summarizeBy: none
		sourceColumn: los_bands

		annotation SummarizationSetBy = Automatic

	column derived_current_totalplusmff
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 5de66d97-2fcb-4283-8097-574de3252a7f
		summarizeBy: sum
		sourceColumn: derived_current_totalplusmff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column primary_diagnosis
		dataType: string
		lineageTag: 52920d3c-1790-4f2a-b86c-41a4620f71ed
		summarizeBy: none
		sourceColumn: primary_diagnosis

		annotation SummarizationSetBy = Automatic

	column diagnosisprimary_icd
		dataType: string
		lineageTag: 9f442a3b-258c-4d65-9d1d-388b057f7012
		summarizeBy: none
		sourceColumn: diagnosisprimary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis1stsecondary_icd
		dataType: string
		lineageTag: d18484ea-8b21-4094-8fa1-c05a468ad784
		summarizeBy: none
		sourceColumn: diagnosis1stsecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis2ndsecondary_icd
		dataType: string
		lineageTag: 13062e6a-a310-420a-b334-078858cf3c29
		summarizeBy: none
		sourceColumn: diagnosis2ndsecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis3rdSecondary_icd
		dataType: string
		lineageTag: 066aa88f-c03c-4ab1-92de-f5340354145c
		summarizeBy: none
		sourceColumn: diagnosis3rdSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis4thSecondary_icd
		dataType: string
		lineageTag: b5017562-a9dd-4409-9ee9-a145c3646d41
		summarizeBy: none
		sourceColumn: diagnosis4thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis5thSecondary_icd
		dataType: string
		lineageTag: aa735388-d557-4793-808c-3b90f5ca9556
		summarizeBy: none
		sourceColumn: diagnosis5thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis6thSecondary_icd
		dataType: string
		lineageTag: 2bd9a41d-ce31-454f-8465-4b68d598a421
		summarizeBy: none
		sourceColumn: diagnosis6thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis7thSecondary_icd
		dataType: string
		lineageTag: d40ac78e-9ed2-47fb-8f08-9ed049a9110a
		summarizeBy: none
		sourceColumn: diagnosis7thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis8thSecondary_icd
		dataType: string
		lineageTag: 805d6951-3ead-48ff-994e-467efa19ac80
		summarizeBy: none
		sourceColumn: diagnosis8thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis9thSecondary_icd
		dataType: string
		lineageTag: 338d5db7-f2d2-4562-afcb-35d00f9ce807
		summarizeBy: none
		sourceColumn: diagnosis9thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis10thSecondary_icd
		dataType: string
		lineageTag: 0980f2fb-adaa-4595-abbe-2056fd8960c8
		summarizeBy: none
		sourceColumn: diagnosis10thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis11thSecondary_icd
		dataType: string
		lineageTag: c1cc3f6f-a8bd-46f9-aea1-f7c3182a7946
		summarizeBy: none
		sourceColumn: diagnosis11thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column diagnosis12thSecondary_icd
		dataType: string
		lineageTag: e4cca05e-c115-40fc-82c1-55ebc7dda8f1
		summarizeBy: none
		sourceColumn: diagnosis12thSecondary_icd

		annotation SummarizationSetBy = Automatic

	column keyrespiratoryconditionflag
		dataType: string
		lineageTag: 2e0410ae-17ed-4852-b228-2e66bb9e78f4
		summarizeBy: none
		sourceColumn: keyrespiratoryconditionflag

		annotation SummarizationSetBy = Automatic

	column readmission_365_day
		dataType: int64
		formatString: 0
		lineageTag: b128aa88-545f-4d93-9222-8174875c7f91
		summarizeBy: sum
		sourceColumn: readmission_365_day

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: 0
		lineageTag: 9eebd8f9-2c9f-4695-b85b-132192e44f0d
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	partition 'New Readmissions-6559f721-b027-43c4-abbb-32e08a08d84a' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Processing", [Query="EXEC [dbo].[Resp_Emerg_Readmissions] #(lf)SELECT *#(lf)FROM [PowerBI_Reporting].[dbo].[Resp_Emerg_Readmissions] "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"counter", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

