table New_Spirometry
	lineageTag: d5f29153-e6e1-437b-aeca-7113fd35f13b

	column pseudo_nhs_no
		dataType: string
		lineageTag: 8ad52cfa-5259-4cd7-91f5-c561d1c7bda9
		summarizeBy: none
		sourceColumn: pseudo_nhs_no

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: fa07e162-8d5d-4829-a2ef-ff83707bf8bb
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column practice_description
		dataType: string
		lineageTag: 3dbcfc88-7f0d-4fab-9bce-0d4686e8ed78
		summarizeBy: none
		sourceColumn: practice_description

		annotation SummarizationSetBy = Automatic

	column event_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 465b987f-51b5-43d2-9eee-e20014624b44
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

	column event_code_description
		dataType: string
		lineageTag: 72794dbb-ddfd-42a0-8b1a-b49eb4a53661
		summarizeBy: none
		sourceColumn: event_code_description

		annotation SummarizationSetBy = Automatic

	column first_test
		dataType: int64
		formatString: 0
		lineageTag: 6d60658d-6527-424d-8807-1e5c5dd66c6a
		summarizeBy: sum
		sourceColumn: first_test

		annotation SummarizationSetBy = Automatic

	partition New_Spirometry-d2a72e52-a668-4b4f-bd7b-d96b67dd3f2e = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Processing", [Query="EXEC [dbo].[Resp_Primary_Care_Spirometry]#(lf);#(lf)SELECT *#(lf)FROM [PowerBI_Reporting].[dbo].[Resp_Primary_Care_Spirometry] "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"first_test", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [first_test] = 1)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

