table 'Advice and Guidance'
	lineageTag: 4283cc07-181c-42de-9c6c-b55b81a2c503

	column UBRN
		dataType: string
		lineageTag: 471516d9-0140-419e-8eb7-02cf545ca8c5
		summarizeBy: none
		sourceColumn: UBRN

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: a45cdcee-d37b-4f62-a39a-0343ec90cb92
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: 6a9ea913-f7b5-43f9-88f6-ce9aa99d132d
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 4cc91ec7-cdec-4f6c-84da-4285cb716e69
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: c8fc16a1-d2e4-4d9b-82a1-fa7fbda9ea0d
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: 77f17853-1845-4585-9c3b-c3b1d0c904f2
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 9d75472b-42e8-4d95-bbda-6649598cdcd7
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column DateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 08beb1eb-9ebb-4d79-b87d-7962b3a5b979
		summarizeBy: none
		sourceColumn: DateTime

		variation Variation
			isDefault
			relationship: 2d01b913-fbbd-45b8-866e-ec386433626b
			defaultHierarchy: LocalDateTable_8a0b659c-3196-46a4-a5d8-a93796154944.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: d3e85ea1-731b-42ec-b026-c02d5db360ac
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: FinancialMonth

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 8c51f160-2062-4d39-8f6e-041acd9ef65c
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column Derived_MainSpecialtyCode
		dataType: string
		lineageTag: b87532d0-4b1d-4f69-bb67-92945b148972
		summarizeBy: none
		sourceColumn: Derived_MainSpecialtyCode

		annotation SummarizationSetBy = Automatic

	column Specialty
		dataType: string
		lineageTag: e7982d96-8df7-4bf7-9029-efc287536a48
		summarizeBy: none
		sourceColumn: Specialty

		annotation SummarizationSetBy = Automatic

	column ClinicType
		dataType: string
		lineageTag: bab2834a-189c-49e1-bcea-ea4ef1c5b81a
		summarizeBy: none
		sourceColumn: ClinicType

		annotation SummarizationSetBy = Automatic

	column Provider_Code
		dataType: string
		lineageTag: d18e1170-c70f-46d1-a834-3b0959cbb8af
		summarizeBy: none
		sourceColumn: Provider_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Name
		dataType: string
		lineageTag: d5b1fa6e-8124-426e-8ed1-4c8e26cfff60
		summarizeBy: none
		sourceColumn: Provider_Name

		annotation SummarizationSetBy = Automatic

	column Provider_Group
		dataType: string
		lineageTag: 77d4a9cc-8460-431a-822d-2888f54882aa
		summarizeBy: none
		sourceColumn: Provider_Group

		annotation SummarizationSetBy = Automatic

	column AdviceRequests
		dataType: int64
		formatString: 0
		lineageTag: 05f89f10-4f6a-415e-a66c-23e686340507
		summarizeBy: sum
		sourceColumn: AdviceRequests

		annotation SummarizationSetBy = Automatic

	column Responded
		dataType: int64
		formatString: 0
		lineageTag: 16e6f6a7-f612-4c43-a3bc-cf15f117de28
		summarizeBy: sum
		sourceColumn: Responded

		annotation SummarizationSetBy = Automatic

	column ResponseID
		dataType: string
		lineageTag: 22cd116e-7a40-4139-9ff1-fa4da216812e
		summarizeBy: none
		sourceColumn: ResponseID

		annotation SummarizationSetBy = Automatic

	column ResponseDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b84258c-d0fb-49ce-99ef-59b1d71b51b4
		summarizeBy: none
		sourceColumn: ResponseDate

		variation Variation
			isDefault
			relationship: 17c7c4ef-c846-40b2-b32d-f98ce37b6a15
			defaultHierarchy: LocalDateTable_17fe48fd-5297-4bdc-a9f0-af1716cd9e04.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ResponseTime
		dataType: int64
		formatString: 0
		lineageTag: e100b91a-9bae-42e5-bfc7-d893b1ac3467
		summarizeBy: sum
		sourceColumn: ResponseTime

		annotation SummarizationSetBy = Automatic

	column AdditionalRequest
		dataType: dateTime
		formatString: General Date
		lineageTag: 00c334f0-ce53-4f51-b629-1802ff9da5ff
		summarizeBy: none
		sourceColumn: AdditionalRequest

		variation Variation
			isDefault
			relationship: 553232ff-a03b-4142-a1ba-57f0e4f9fc47
			defaultHierarchy: LocalDateTable_ecfd598b-7fac-4d12-8521-767f9b7ed24d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column RANK
		dataType: int64
		formatString: 0
		lineageTag: 8c99fb92-e47a-4d98-a2a6-1b79ae082ee7
		summarizeBy: sum
		sourceColumn: RANK

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 04b23d95-65f7-4a41-a796-e92951ad4fb6
		summarizeBy: sum
		sourceColumn: FinancialMonth

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 84a2dffb-a03a-4740-8bc4-c69dc4d72ad1
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column ReportingMonth
		dataType: int64
		formatString: 0
		lineageTag: 89a6edaa-4b4f-43cc-9474-c8340b3dacc0
		summarizeBy: sum
		sourceColumn: ReportingMonth

		annotation SummarizationSetBy = Automatic

	partition 'Advice and Guidance' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="#(lf)SELECT * FROM [PowerBI_Reporting].[PlannedCare].[tbl04_AdviceAndGuidance]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Derived_MainSpecialtyDescription", "Specialty"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

