table date_table
	isHidden
	lineageTag: 6e675f31-74a6-4511-9ea9-d9cd96cf0239

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8479412a-eddd-49ac-af16-0314afff90ad
		summarizeBy: count
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: adbb3580-0d39-4755-a32a-ebf2a21c1c75
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 545bb6f9-e8f0-490c-b8e0-eec11a0d6e90
			defaultHierarchy: LocalDateTable_4fed267e-1dd8-420e-977b-92c23a819e7e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayMonthYear
		dataType: string
		isHidden
		lineageTag: cbd8301c-4189-4d48-81c4-50ef14897890
		summarizeBy: none
		sourceColumn: DayMonthYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0b8a3729-da4a-4c3b-93ab-60fc6dbf98e5
		summarizeBy: sum
		sourceColumn: Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DaySuffix
		dataType: string
		isHidden
		lineageTag: 30b407ec-ed32-4237-805b-c18c35efd201
		summarizeBy: none
		sourceColumn: DaySuffix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 18be9bb9-e267-4745-9cbf-f94f7bb828cd
		summarizeBy: sum
		sourceColumn: Weekday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekDayName
		dataType: string
		isHidden
		lineageTag: af07dc5f-7d65-4a7f-8233-b290d4c79a8d
		summarizeBy: none
		sourceColumn: WeekDayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayofWeekInMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 67e65e42-6cec-4c51-b3da-264693398ebd
		summarizeBy: sum
		sourceColumn: DayofWeekInMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0b2da2d3-f2ef-4bde-a0d8-930a7f276358
		summarizeBy: sum
		sourceColumn: DayOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f7381993-58b4-41d6-bf7b-197290147c3c
		summarizeBy: sum
		sourceColumn: WeekOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekOfYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c215f97-33ab-4579-961a-96d31fcdbbbd
		summarizeBy: sum
		sourceColumn: WeekOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 915fa50a-7f58-41bc-93d5-3acc3f84e6ec
		summarizeBy: sum
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		isHidden
		lineageTag: 3fc4cabe-873e-4e6a-8812-d0d501637fab
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: FinancialMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2ab1bebb-e3f3-4ccb-b55c-a06639e1b0b4
		summarizeBy: sum
		sourceColumn: Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QuarterName
		dataType: string
		isHidden
		lineageTag: 4487620a-f5f2-4262-9378-ce3ca3cc581b
		summarizeBy: none
		sourceColumn: QuarterName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 47b3be2c-556c-4fad-a26a-9c34625997a5
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		isHidden
		lineageTag: eb00576a-b26f-42ee-a0fb-92d6d21be6bf
		summarizeBy: none
		sourceColumn: MonthYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthYearName
		dataType: string
		isHidden
		lineageTag: 7aa36d8d-0b6b-4d4c-9ed9-7422ab6ab215
		summarizeBy: none
		sourceColumn: MonthYearName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fa9b89d6-060c-4566-a069-3a46aae5ef01
		summarizeBy: sum
		sourceColumn: year_month
		sortByColumn: 'Financial Year'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2034db15-66ae-476f-bc8f-add4a522124d
		summarizeBy: none
		sourceColumn: IsWeekend

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4dfa884b-347b-4b08-a128-d748c6026a6c
		summarizeBy: none
		sourceColumn: IsHoliday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinancialWeekofYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ef6568f4-e3e4-4279-ac47-a479aab5455b
		summarizeBy: sum
		sourceColumn: FinancialWeekofYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HolidayName
		dataType: string
		isHidden
		lineageTag: e3e1c0d5-04dd-4038-82dc-72cf2c730d94
		summarizeBy: none
		sourceColumn: HolidayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SpecialDays
		dataType: string
		isHidden
		lineageTag: 69309ecd-2d04-4cdf-b217-f29058fd11ff
		summarizeBy: none
		sourceColumn: SpecialDays

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		isHidden
		lineageTag: 50dda7b4-ec6f-4391-a40b-5ee3f1cea6ec
		summarizeBy: none
		sourceColumn: Financial Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinancialQuarter
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: decb507a-64be-46e9-9834-e2f3267fe667
		summarizeBy: sum
		sourceColumn: FinancialQuarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c450b3d7-5dbf-4075-92ed-ec5a80d62b4c
		summarizeBy: sum
		sourceColumn: FinancialMonth

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column FirstDateofYear
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 4c9c20ce-4093-4389-bbc4-34da330fa68a
		summarizeBy: none
		sourceColumn: FirstDateofYear

		variation Variation
			isDefault
			relationship: eb1d292c-4045-4943-924a-bad796a145c6
			defaultHierarchy: LocalDateTable_e542c064-a273-434f-a330-5eea91fa64f5.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastDateofYear
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 48c27105-a6c0-4508-808f-14d044abfb91
		summarizeBy: none
		sourceColumn: LastDateofYear

		variation Variation
			isDefault
			relationship: 15a694aa-ebc5-4bac-8277-f0fc832e9b8a
			defaultHierarchy: LocalDateTable_0ba57a69-e7db-4fdb-8486-9f3b9d5cc0e3.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstDateofQuater
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 61813b31-f276-43b5-a8f7-37e020889a11
		summarizeBy: none
		sourceColumn: FirstDateofQuater

		variation Variation
			isDefault
			relationship: 68629d1b-1370-4b44-9d76-662df563961d
			defaultHierarchy: LocalDateTable_d4e75042-7823-48a4-83df-42e52de9cc85.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastDateofQuater
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 547a3ea4-d9e0-4fee-8c92-14774fddfbaa
		summarizeBy: none
		sourceColumn: LastDateofQuater

		variation Variation
			isDefault
			relationship: de1def29-ecb4-4ebb-8ad2-a2118473bfcd
			defaultHierarchy: LocalDateTable_62896726-9601-4dc4-b155-4b6dad929c6d.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstDateofMonth
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 3e62a251-2eda-4fdb-a591-5ee2fc23b3ae
		summarizeBy: none
		sourceColumn: FirstDateofMonth

		variation Variation
			isDefault
			relationship: b5a5eb2c-89a7-4b29-84c4-99f41d875921
			defaultHierarchy: LocalDateTable_1ee02ed2-ffd2-42b4-a541-7887ff57c3fd.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastDateofMonth
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 3fda05e9-9e6c-4b18-9ba1-cf56b2a5e05e
		summarizeBy: none
		sourceColumn: LastDateofMonth

		variation Variation
			isDefault
			relationship: b382cf22-c46a-48a2-b674-33505826dbdc
			defaultHierarchy: LocalDateTable_7a668360-397f-4b38-ab15-2453807a5053.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstDateofWeek
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: c2b18327-c0d9-4a0f-aacf-b9a6a7fdc7d8
		summarizeBy: none
		sourceColumn: FirstDateofWeek

		variation Variation
			isDefault
			relationship: a8242f5a-8239-483a-876b-233bc24666ba
			defaultHierarchy: LocalDateTable_f9ba08c8-945b-43ba-a105-6d6fcc9ef9dd.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastDateofWeek
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 1dca8090-359d-4e6a-8fda-30619dbe2588
		summarizeBy: none
		sourceColumn: LastDateofWeek

		variation Variation
			isDefault
			relationship: 04f07cdc-d6fe-4867-8864-1dc871263001
			defaultHierarchy: LocalDateTable_490c8bd5-d3fa-4cc9-b954-bbf40fc0aaf6.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekBand
		dataType: string
		isHidden
		lineageTag: 32e49a67-8b9c-4d09-986b-cda741d24dc7
		summarizeBy: none
		sourceColumn: WeekBand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 67dc43c4-6090-41ad-99b5-9cd418186d06
		summarizeBy: sum
		sourceColumn: CurrentYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentQuater
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 05dc955c-80ad-4846-a561-ce0b81eab679
		summarizeBy: sum
		sourceColumn: CurrentQuater

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b392b61f-613c-4d58-84f4-dec7ec78cd01
		summarizeBy: sum
		sourceColumn: CurrentMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentWeek
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d08158c6-0d23-43f1-80b3-b21427896e5c
		summarizeBy: sum
		sourceColumn: CurrentWeek

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentDay
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f5946098-aed0-416e-9394-a96754386c12
		summarizeBy: sum
		sourceColumn: CurrentDay

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition date_table-4919b28c-06fb-4a2e-8247-f0dadd718d4e = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select datekey as ""DateKey"", date as ""Date"", daymonthyear as ""DayMonthYear"", day as ""Day"", daysuffix as ""DaySuffix"", weekday as ""Weekday"", weekdayname as ""WeekDayName"", dayofweekinmonth as ""DayofWeekInMonth"", dayofyear as ""DayOfYear"", weekofmonth as ""WeekOfMonth"", weekofyear as ""WeekOfYear"", month as ""Month"", left(monthname,3) as ""MonthName"", quarter as ""Quarter"", quartername as ""QuarterName"", year as ""Year"", monthyear as ""MonthYear"", monthyearname as ""MonthYearName"", yearmonth as ""YearMonth"", isweekend as ""IsWeekend"", isholiday as ""IsHoliday"", financialweekofyear as ""FinancialWeekofYear"", holidayname as ""HolidayName"", specialdays as ""SpecialDays"", financialyear as ""FinancialYear"", financialquarter as ""FinancialQuarter"", financialmonth as ""FinancialMonth"", firstdateofyear as ""FirstDateofYear"", lastdateofyear as ""LastDateofYear"", firstdateofquater as ""FirstDateofQuater"", lastdateofquater as ""LastDateofQuater"", firstdateofmonth as ""FirstDateofMonth"", lastdateofmonth as ""LastDateofMonth"", firstdateofweek as ""FirstDateofWeek"", lastdateofweek as ""LastDateofWeek"", weekband as ""WeekBand"", currentyear as ""CurrentYear"", currentquater as ""CurrentQuater"", currentmonth as ""CurrentMonth"", currentweek as ""CurrentWeek"", currentday as ""CurrentDay"" from ccg_reference.vw_datelookup where date >= '20190401'", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"YearMonth", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"FinancialYear", "Financial Year"}, {"MonthName", "Month Name"}, {"YearMonth", "year_month"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

