table date
	lineageTag: f3720a45-800d-46de-9891-f81b231955e0

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 085dfea1-4d30-4ecd-abe9-3bd5029d6ca1
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 01e9eed5-707a-41a1-8ab7-e65825e656cc
			defaultHierarchy: LocalDateTable_e512c564-4d08-4751-93b7-0d3d5b7a6bc9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9620226b-21a8-4e07-8261-4eca1063cfe6
		summarizeBy: none
		sourceColumn: day_month_year

		variation Variation
			isDefault
			relationship: 4974009a-0709-49d6-b665-5ccf44a5d7cd
			defaultHierarchy: LocalDateTable_36e90fe3-ef4e-4115-8e5e-4db13fca2f29.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: f6579ef8-c3e5-4420-9986-1a01c5efa06a
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 991dd13d-15f7-4af2-8b6e-af2ee36c450c
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 24ac201e-e877-42a1-a347-ed283c2842f1
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: bb5bab4f-c884-43a9-bf8b-95ca39c36950
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: f45e1b9f-9e5a-4694-a445-760f76ab07fe
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 0a679354-3baa-4c37-90c6-c65da21afaf1
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 052194b2-f112-4183-8776-b513a936c64f
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 9249080a-5133-46a9-a704-933fc15d11e3
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: a8423ea7-9f46-4da1-888b-21f1cfbb75f1
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 59bf2457-c3a1-4bb6-b95c-ac54d45117d8
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: f5a6f9c3-2a82-4e1a-bec8-c715baeb0901
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 8f00a310-8c8e-4930-ae53-1e07bf9fe636
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 406937d7-d7b7-40d8-9856-f40615c48fad
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: d1585f06-da46-46e8-aa35-66b331ad8930
		summarizeBy: none
		sourceColumn: Last_Updated

		variation Variation
			isDefault
			relationship: 21c3a1c8-6912-4e3e-84c4-ba63104148f1
			defaultHierarchy: LocalDateTable_c7a7871b-7690-42e1-97d0-344049e21a97.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Data_up_to
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: f82485fc-d28d-4cf3-96bb-a37806344f84
		summarizeBy: none
		sourceColumn: Data_up_to

		variation Variation
			isDefault
			relationship: dce907ce-1071-49b7-b446-565c7c2ded28
			defaultHierarchy: LocalDateTable_eb042f5f-3dac-412e-ac4a-70ee3bc55e8e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: 70aaef80-5f03-43ae-82c3-7bfaafa874fb
		summarizeBy: sum
		sourceColumn: Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 859d3878-bc1e-4863-acf0-b64c45e79db1
		summarizeBy: none
		sourceColumn: month_year

		variation Variation
			isDefault
			relationship: a56735c6-c869-4e9c-9c21-fcf4eee086d2
			defaultHierarchy: LocalDateTable_66c5538c-66a6-46e3-8851-e815e86c64af.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition date-a843c7a3-2b2f-4142-92cc-ae6c02a71a66 = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="set nocount on#(lf)#(lf)/*------------------------------------------------------------#(lf)Declare Variables #(lf)/-------------------------------------------------------------*/#(lf)#(lf)----------------------------------------------#(lf)--Obtain the latest date in SEM data#(lf)----------------------------------------------#(lf)#(lf)declare @data_up_to as date#(lf)declare @reporting_month as int#(lf)#(lf)set @data_up_to = (select  MAX(AppointmentDate)#(lf)  from #(lf)  [PowerBI_Reporting].[PlannedCare].[tbl02_Outpatients] [A]#(lf)  where AppointmentDate <=   eomonth(dateadd(month, -1, getdate())))#(lf)#(lf)#(lf)----------------------------------------------#(lf)--Get the latest reporting month#(lf)----------------------------------------------#(lf)#(lf)#(lf)set @reporting_month = #(lf)#(lf)(select d.FinancialMonth#(lf)#(lf)from #(lf)#(lf)(select  MAX(AppointmentDate) as 'latest_date'#(lf)  from #(lf)  [PowerBI_Reporting].[PlannedCare].[tbl02_Outpatients] [A]#(lf)  where AppointmentDate <= eomonth(dateadd(month, -1, getdate()))) as o #(lf)#(lf)left join #(lf)#(lf)  [CCG_Reference].[Reference].[vw_DateLookup] as d on d.Date = o.latest_date)#(lf)#(lf)#(lf) #(lf)  ----------------------------------------------#(lf)--Create final output reference table#(lf)----------------------------------------------#(lf)#(lf)select [Date] [date]#(lf)      ,[DayMonthYear] [day_month_year]#(lf)      ,[Day] [day]#(lf)      ,[Weekday] [weekday]#(lf)      ,[WeekDayName] [weekday_name]#(lf)      ,[Month] [month]#(lf)      ,left([MonthName],3) [month_name]#(lf)      ,[Quarter] [quarter]#(lf)      ,[YearMonth] [year_month]#(lf)      ,[IsWeekend] [is_weekend]#(lf)      ,[IsHoliday] [is_holiday]#(lf)      ,[FinancialWeekofYear] [financial_week_of_year]#(lf)      ,[FinancialYear] [financial_year]#(lf)      ,[FinancialQuarter] [financial_quarter]#(lf)      ,[FinancialMonth] [financial_month]#(lf)#(tab)  ,[Last_Updated] = getdate()#(lf)#(tab)  ,[Data_up_to] = @data_up_to#(lf)#(tab)  ,[Reporting_Month_Flag] = case when FinancialMonth <= @reporting_month then 1 else 0 end #(lf)      #(lf)from [CCG_Reference].[Reference].[vw_DateLookup]#(lf)where [Date] between '20190401' and  eomonth(dateadd(month, -1, getdate()))"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "day_month_year", "day_month_year - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"day_month_year - Copy", "month_year"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

