table E-Referrals
	lineageTag: f6693a4c-f369-4d19-980d-21fc6df64f3c

	measure 'Rejection %' = calculate(divide(sum('E-Referrals'[Rejection]),sum('E-Referrals'[DirectlyBookable])))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3cd3db26-0555-47f7-ad29-b80deedc130a

	measure GHFTCountOnly = ```
			CALCULATE( 
			    SUM('E-Referrals'[Counter]),
			    'E-Referrals'[Provider_Code] = "RTE", 
			    REMOVEFILTERS('E-Referrals'[Provider_Name], 'E-Referrals'[Provider_Group] ) ) +0
			```
		formatString: 0
		lineageTag: f7c7d40c-676a-4fcf-ad56-3cc26f8c8d94

	measure OtherCountOnly = CALCULATE( SUM('E-Referrals'[Counter]), 'E-Referrals'[Provider_Code] <> "RTE" ) +0
		formatString: 0
		lineageTag: fa55242e-5e9a-4dce-8681-af6f705543d2

	measure TotalCount = ```
			CALCULATE( 
			    SUM('E-Referrals'[Counter]),
			        REMOVEFILTERS('E-Referrals'[Provider_Name], 'E-Referrals'[Provider_Group] ) ) +0
			```
		formatString: 0
		lineageTag: 70d41d42-d3b4-4380-9b97-dffd76ec1fad

	measure OtherPercentage = ```
			
			DIVIDE(
			    CALCULATE(SUM('E-Referrals'[Counter]), 'E-Referrals'[GHFT or Other] = "Other"), 
			    CALCULATE(SUM('E-Referrals'[Counter]), 
			    REMOVEFILTERS('E-Referrals'[Provider_Name], 'E-Referrals'[Provider_Group] )), 
			    0 ) +0
			```
		lineageTag: 3fed3ade-2383-4a2f-ab89-848777b733fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UBRN
		dataType: string
		lineageTag: 64182a7c-8d54-4aef-b2a6-b33deaec951c
		summarizeBy: none
		sourceColumn: UBRN

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 8b4ddc77-4af7-4702-94b0-ba2d15f920e4
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column AgeBand
		dataType: string
		lineageTag: 85f46d91-4e7b-4331-93f4-a7a26c50149a
		summarizeBy: none
		sourceColumn: AgeBand

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: ab4f57a0-d387-41bd-b4cb-0bd62a1ed838
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: 383371eb-f9b1-4f3a-91bc-3eabb774f51e
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: 7e49a8ea-c35d-4c66-bcc9-127fe88fbf3d
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 3d0ef604-bf60-4ed3-8cb0-0c9da653e6b5
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column Consultant_Led_Flag
		dataType: string
		lineageTag: d6ad88df-089c-4791-8ffd-99dd37d7ca81
		summarizeBy: none
		sourceColumn: Consultant_Led_Flag

		annotation SummarizationSetBy = Automatic

	column Referral_Priority
		dataType: string
		lineageTag: 5da055fa-5dbb-4ea4-99da-1e45ca51dfb7
		summarizeBy: none
		sourceColumn: Referral_Priority

		annotation SummarizationSetBy = Automatic

	column InitialReferralDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 60253ac0-54ff-4ebf-a69a-57e15f3c2d9b
		summarizeBy: none
		sourceColumn: InitialReferralDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InitialReferralMonth
		dataType: string
		lineageTag: 64c32d48-5916-43cc-86c8-337f88c52b7d
		summarizeBy: none
		sourceColumn: InitialReferralMonth
		sortByColumn: InitialReferralFinancialMonth

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column InitialReferralFinancialYear
		dataType: string
		lineageTag: 572b2cc5-2cfb-49a1-8031-44ecad0e4f10
		summarizeBy: none
		sourceColumn: InitialReferralFinancialYear

		annotation SummarizationSetBy = Automatic

	column InitialReferralYearmonth
		dataType: string
		lineageTag: c4a9b80e-cddd-4cee-9208-83966a30885f
		summarizeBy: none
		sourceColumn: InitialReferralYearmonth

		annotation SummarizationSetBy = Automatic

	column Derived_MainSpecialtyCode
		dataType: string
		lineageTag: 4149c7e3-70de-4e45-8b7b-b92179ed6552
		summarizeBy: none
		sourceColumn: Derived_MainSpecialtyCode

		annotation SummarizationSetBy = Automatic

	column Derived_MainSpecialtyDescription
		dataType: string
		lineageTag: 6c1be072-1d02-479f-9fe7-fd2a961e2592
		summarizeBy: none
		sourceColumn: Derived_MainSpecialtyDescription

		annotation SummarizationSetBy = Automatic

	column ServiceID
		dataType: string
		lineageTag: bec08606-6efa-4a7f-ab22-4f3bf7d79404
		summarizeBy: none
		sourceColumn: ServiceID

		annotation SummarizationSetBy = Automatic

	column ServiceName
		dataType: string
		lineageTag: cdaf9b85-efbe-451c-930b-34b248a11f77
		summarizeBy: none
		sourceColumn: ServiceName

		annotation SummarizationSetBy = Automatic

	column ClinicTypeCode
		dataType: string
		lineageTag: d82889ab-a697-4902-bb54-4874975efb64
		summarizeBy: none
		sourceColumn: ClinicTypeCode

		annotation SummarizationSetBy = Automatic

	column ClinicType
		dataType: string
		lineageTag: 99435418-22f8-493c-bb5d-f5b551e47029
		summarizeBy: none
		sourceColumn: ClinicType

		annotation SummarizationSetBy = Automatic

	column Provider_Code
		dataType: string
		lineageTag: 313c77be-c34c-4217-86b3-a33256229ac4
		summarizeBy: none
		sourceColumn: Provider_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Name
		dataType: string
		lineageTag: 06d12587-5257-47e1-ab26-cbd10ec549bc
		summarizeBy: none
		sourceColumn: Provider_Name

		annotation SummarizationSetBy = Automatic

	column Provider_Group
		dataType: string
		lineageTag: 7374dfd4-b63e-4b62-ba74-707e5d67abf5
		summarizeBy: none
		sourceColumn: Provider_Group

		annotation SummarizationSetBy = Automatic

	column Referral_Type
		dataType: string
		lineageTag: 04b14af8-c3d5-4762-acec-65412cb53f3d
		summarizeBy: none
		sourceColumn: Referral_Type

		annotation SummarizationSetBy = Automatic

	column ReferralAccepted
		dataType: int64
		formatString: 0
		lineageTag: 125c758a-229f-42a5-96b6-0df1de8c0073
		summarizeBy: sum
		sourceColumn: ReferralAccepted

		annotation SummarizationSetBy = Automatic

	column ReferralRejected
		dataType: int64
		formatString: 0
		lineageTag: 0d1a3afa-792c-461b-93e9-dd213e236bc8
		summarizeBy: sum
		sourceColumn: ReferralRejected

		annotation SummarizationSetBy = Automatic

	column RAS
		dataType: int64
		formatString: 0
		lineageTag: af756405-615b-443c-99eb-092a5baa15d9
		summarizeBy: sum
		sourceColumn: RAS

		annotation SummarizationSetBy = Automatic

	column Booking
		dataType: int64
		formatString: 0
		lineageTag: 6a165b66-6671-4e46-844e-a319d3d9d7f1
		summarizeBy: sum
		sourceColumn: Booking

		annotation SummarizationSetBy = Automatic

	column BookingDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 86386cae-d7dd-46f1-8610-251515db83a0
		summarizeBy: none
		sourceColumn: BookingDate

		variation Variation
			isDefault
			relationship: 819be601-19bc-4594-b4d3-6981a1e110ef
			defaultHierarchy: LocalDateTable_24dd3174-7690-4f9e-8f73-f8a5e865eda4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column BookingMonth
		dataType: string
		lineageTag: ff8886dd-e22d-466e-8b61-30ec57b73744
		summarizeBy: none
		sourceColumn: BookingMonth

		annotation SummarizationSetBy = Automatic

	column BookingFinancialYear
		dataType: string
		lineageTag: 2ff12682-2957-4c09-bdb2-37885734391e
		summarizeBy: none
		sourceColumn: BookingFinancialYear

		annotation SummarizationSetBy = Automatic

	column IndicativeWaitTime
		dataType: int64
		formatString: 0
		lineageTag: ace522b7-df4b-4825-a865-455fd5e2e1b6
		summarizeBy: sum
		sourceColumn: IndicativeWaitTime

		annotation SummarizationSetBy = Automatic

	column Rejection
		dataType: int64
		formatString: 0
		lineageTag: 370372c7-d68f-4449-8c70-e0c64ff0879e
		summarizeBy: sum
		sourceColumn: Rejection

		annotation SummarizationSetBy = Automatic

	column InitialReferral
		dataType: int64
		formatString: 0
		lineageTag: bc79dd4e-a171-42cf-8903-7fc2c2e26cfd
		summarizeBy: sum
		sourceColumn: InitialReferral

		annotation SummarizationSetBy = Automatic

	column DirectlyBookable
		dataType: int64
		formatString: 0
		lineageTag: fced0ed5-5a56-49f7-a822-d69fd23968db
		summarizeBy: sum
		sourceColumn: DirectlyBookable

		annotation SummarizationSetBy = Automatic

	column Initial_Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: 05c3b2ba-453e-4b1e-a326-c24ac3c083a9
		summarizeBy: sum
		sourceColumn: Initial_Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column Booking_Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: bfdbaa27-fddb-47c1-bcaf-3eb3ba397d21
		summarizeBy: sum
		sourceColumn: Booking_Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column Derived_TreatmentFunctionCode
		dataType: string
		lineageTag: fe37c910-e585-4551-b959-773e74cead51
		summarizeBy: none
		sourceColumn: Derived_TreatmentFunctionCode

		annotation SummarizationSetBy = Automatic

	column Derived_TreatmentFunctionDescription
		dataType: string
		lineageTag: 726a0d98-bc39-4dd9-b34d-27193f75d4af
		summarizeBy: none
		sourceColumn: Derived_TreatmentFunctionDescription

		annotation SummarizationSetBy = Automatic

	column InitialReferralPopulation
		dataType: double
		lineageTag: cdee3f28-f072-42b4-bf77-8fa0aecfceae
		summarizeBy: sum
		sourceColumn: InitialReferralPopulation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BookingReferralPopulation
		dataType: double
		lineageTag: 15962457-a499-4a77-8c1e-ef82a609d724
		summarizeBy: sum
		sourceColumn: BookingReferralPopulation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InitialReferralRate
		dataType: double
		formatString: 0.0
		lineageTag: cfd26e08-0064-4bd1-a4bf-84018817dbf1
		summarizeBy: sum
		sourceColumn: InitialReferralRate

		annotation SummarizationSetBy = Automatic

	column BookingReferralRate
		dataType: double
		lineageTag: 6ce0c630-f6ea-4f25-919f-c02033c1126f
		summarizeBy: sum
		sourceColumn: BookingReferralRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InitialReferralFinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 3b1b25e6-8d63-4acf-a2fc-87a3f15c5da7
		summarizeBy: sum
		sourceColumn: InitialReferralFinancialMonth

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 1937f1b1-afed-4e15-8425-9b440ac9e959
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column ShortlistCount
		dataType: string
		lineageTag: 61c00a94-dfa0-4a39-8beb-e04a161ddae1
		summarizeBy: none
		sourceColumn: ShortlistCount

		annotation SummarizationSetBy = Automatic

	column Location_Code
		dataType: string
		lineageTag: f85fd8ef-addb-4b48-9c63-f5d7cd671daf
		summarizeBy: none
		sourceColumn: Location_Code

		annotation SummarizationSetBy = Automatic

	column PseudoNHSNo
		dataType: string
		lineageTag: 9aa7b5da-cbb6-436a-8afc-e14171fcc2ca
		summarizeBy: none
		sourceColumn: PseudoNHSNo

		annotation SummarizationSetBy = Automatic

	column ReferralCount
		dataType: int64
		formatString: 0
		lineageTag: 69100b9f-65d9-4e0e-8477-fb2249447096
		summarizeBy: sum
		sourceColumn: ReferralCount

		annotation SummarizationSetBy = Automatic

	column 'GHFT or Other'
		dataType: string
		lineageTag: 0ee1579f-e42b-4285-8a5a-89a8ca6f6e3e
		summarizeBy: none
		sourceColumn: GHFT or Other

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: 0c731d65-fd84-4440-b923-4a379fd87dc6
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column 'InitialReferral YTD Filter' = ```
			
			VAR current_month = MONTH('E-Referrals'[InitialReferralDate])
			VAR f_current_month = SWITCH(TRUE(),
			current_month = 4, 1,
			current_month = 5, 2,
			current_month = 6, 3,
			current_month = 7, 4,
			current_month = 8, 5,
			current_month = 9, 6,
			current_month = 10, 7,
			current_month = 11, 8,
			current_month = 12, 9,
			current_month = 1, 10,
			current_month = 2, 11,
			current_month = 3, 12
			)
			VAR max_month = MONTH(MAX('E-Referrals'[InitialReferralDate]))
			VAR f_max_month = SWITCH(TRUE(),
			max_month = 4, 1,
			max_month = 5, 2,
			max_month = 6, 3,
			max_month = 7, 4,
			max_month = 8, 5,
			max_month = 9, 6,
			max_month = 10, 7,
			max_month = 11, 8,
			max_month = 12, 9,
			max_month = 1, 10,
			max_month = 2, 11,
			max_month = 3, 12
			)
			return if(f_current_month <= f_max_month, "Year to Date", "Not Year to Date")
			
			```
		lineageTag: 0d18394c-40c3-4076-be6d-9225fcc4b9d6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'BookingDate YTD Filter' = ```
			
			VAR current_month = MONTH('E-Referrals'[BookingDate])
			VAR f_current_month = SWITCH(TRUE(),
			current_month = 4, 1,
			current_month = 5, 2,
			current_month = 6, 3,
			current_month = 7, 4,
			current_month = 8, 5,
			current_month = 9, 6,
			current_month = 10, 7,
			current_month = 11, 8,
			current_month = 12, 9,
			current_month = 1, 10,
			current_month = 2, 11,
			current_month = 3, 12
			)
			VAR max_month = MONTH(MAX('E-Referrals'[BookingDate]))
			VAR f_max_month = SWITCH(TRUE(),
			max_month = 4, 1,
			max_month = 5, 2,
			max_month = 6, 3,
			max_month = 7, 4,
			max_month = 8, 5,
			max_month = 9, 6,
			max_month = 10, 7,
			max_month = 11, 8,
			max_month = 12, 9,
			max_month = 1, 10,
			max_month = 2, 11,
			max_month = 3, 12
			)
			return if(f_current_month <= f_max_month, "Year to Date", "Not Year to Date")
			
			```
		lineageTag: b2b36d5b-4656-4a24-9b5f-8417305623b6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition E-Referrals = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select ubrn as ""UBRN"", pseudonhsno as ""PseudoNHSNo"", age as ""Age"", ageband as ""AgeBand"", gender as ""Gender"", practice_code as ""Practice_Code"", practice_name as ""Practice_Name"", primarycarenetwork as ""PrimaryCareNetwork"", locality as ""Locality"", consultant_led_flag as ""Consultant_Led_Flag"", referral_priority as ""Referral_Priority"", initialreferral as ""InitialReferral"", referralcount as ""ReferralCount"", initial_reporting_month_flag as ""Initial_Reporting_Month_Flag"", initialreferraldate as ""InitialReferralDate"", initialreferralmonth as ""InitialReferralMonth"", initialreferralfinancialyear as ""InitialReferralFinancialYear"", initialreferralyearmonth as ""InitialReferralYearmonth"", initialreferralfinancialmonth as ""InitialReferralFinancialMonth"", derived_mainspecialtycode as ""Derived_MainSpecialtyCode"", derived_mainspecialtydescription as ""Derived_MainSpecialtyDescription"", location_code as ""Location_Code"", derived_treatmentfunctioncode as ""Derived_TreatmentFunctionCode"", derived_treatmentfunctiondescription as ""Derived_TreatmentFunctionDescription"", serviceid as ""ServiceID"", servicename as ""ServiceName"", clinictypecode as ""ClinicTypeCode"", clinictype as ""ClinicType"", provider_code as ""Provider_Code"", provider_name as ""Provider_Name"", provider_group as ""Provider_Group"", referral_type as ""Referral_Type"", directlybookable as ""DirectlyBookable"", referralaccepted as ""ReferralAccepted"", referralrejected as ""ReferralRejected"", ras as ""RAS"", rejection as ""Rejection"", booking as ""Booking"", bookingdate as ""BookingDate"", booking_reporting_month_flag as ""Booking_Reporting_Month_Flag"", bookingmonth as ""BookingMonth"", bookingfinancialyear as ""BookingFinancialYear"", indicativewaittime as ""IndicativeWaitTime"", initialreferralpopulation as ""InitialReferralPopulation"", bookingreferralpopulation as ""BookingReferralPopulation"", initialreferralrate as ""InitialReferralRate"", bookingreferralrate as ""BookingReferralRate"", shortlistcount as ""ShortlistCount"" from data_mart_powerbi_plannedcare.tbl03_e_referrals", null, [EnableFolding=true]),
				    #"Added Conditional Column" = Table.AddColumn(Source, "GHFT or Other", each if [Provider_Code] = "RTE" then "GHFT" else "Other"),
				    #"Added Custom" = Table.AddColumn(#"Added Conditional Column", "Counter", each 1),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Counter", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,"Not Specified",Replacer.ReplaceValue,{"Provider_Name"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each true),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"InitialReferralDate", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

