table '1. Programme Level Metrics'
	lineageTag: 1bbc599d-03e6-4ef1-85d4-7313efd4f014

	measure ArrowsProg =
			
			VAR Latest_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="High")
			VAR Previous_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 2,'1. Programme Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="Low")
			VAR Previous_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 2,'1. Programme Level Metrics'[Good Is]="Low")
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_High<Previous_Value_High,UNICHAR(UNICODE("↓")),
			IF(Latest_Value_Low>Previous_Value_Low,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_Low<Previous_Value_Low,UNICHAR(UNICODE("↓")),""))))
		lineageTag: 1edce63a-c29a-480e-8965-e303f5749e39

	measure 'Arrow Colours Prog' =
			
			VAR Latest_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="High")
			VAR Previous_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 2,'1. Programme Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="Low")
			VAR Previous_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 2,'1. Programme Level Metrics'[Good Is]="Low")
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,"#78BE20",
			IF(Latest_Value_High<Previous_Value_High,"#AE2424",
			IF(Latest_Value_Low>Previous_Value_Low,"#AE2424",
			IF(Latest_Value_Low<Previous_Value_Low,"#78BE20"))))
		lineageTag: 4b8166fc-3605-49a6-bc4a-f470751250db

	measure 'Target Colours Prog' =
			
			VAR Latest_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="High")
			VAR Target_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Target]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="Low")
			VAR Target_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Target]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="Low")
			
			RETURN
			
			IF(Latest_Value_High>Target_Value_High,"#78BE20",
			IF(Latest_Value_High<Target_Value_High,"#AE2424",
			IF(Latest_Value_Low>Target_Value_Low,"#AE2424",
			IF(Latest_Value_Low<Target_Value_Low,"#78BE20"))))
		lineageTag: dc782a93-f3f7-4085-acce-7dc41671b6b0

	measure Target_SymbolProg =
			
			VAR Latest_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Value]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="Low")
			VAR Target_Value_High = CALCULATE(SUM('1. Programme Level Metrics'[Target]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="High")
			VAR Target_Value_Low = CALCULATE(SUM('1. Programme Level Metrics'[Target]),'1. Programme Level Metrics'[Order Time] = 1,'1. Programme Level Metrics'[Good Is]="Low")
			
			RETURN
			IF(Latest_Value_High>Target_Value_High,UNICHAR(UNICODE("✔")),
			IF(Latest_Value_High<Target_Value_High,UNICHAR(UNICODE("⨯")),
			IF(Latest_Value_Low>Target_Value_Low,UNICHAR(UNICODE("⨯")),
			IF(Latest_Value_Low<Target_Value_Low,UNICHAR(UNICODE("✔")),""))))
		lineageTag: d995d0fd-4f99-4536-a32c-d6ce89f43481

	column 'Indicator Code'
		dataType: string
		lineageTag: b0c9dc46-2ef4-4efa-a899-d854460da435
		summarizeBy: none
		sourceColumn: Indicator Code

		annotation SummarizationSetBy = Automatic

	column 'Indicator Name'
		dataType: string
		lineageTag: 6477fdf1-cfc0-4679-b1a6-a907f36be26f
		summarizeBy: none
		sourceColumn: Indicator Name

		annotation SummarizationSetBy = Automatic

	column 'Indicator Description'
		dataType: string
		lineageTag: 112dc130-2b72-4321-80de-ee8e8933b451
		summarizeBy: none
		sourceColumn: Indicator Description

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: afb2db66-1949-4ef6-bbe7-62bb9425129c
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column 'Financial Month'
		dataType: int64
		formatString: 0
		lineageTag: 8b3ee74e-0ea4-4e1a-abc1-7b9009148be8
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 9649e811-15ad-43e8-bf55-d0e2992106c2
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Financial Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Time Period'
		dataType: string
		lineageTag: 47845529-bf60-453f-b078-3fd26e416b4f
		summarizeBy: none
		sourceColumn: Time Period
		sortByColumn: 'Year Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Time Period Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: bd098183-c03a-44b3-ac2d-6c9b51b5837f
		summarizeBy: none
		sourceColumn: Time Period Date

		variation Variation
			isDefault
			relationship: 4f775e01-6d8a-4250-80bf-e6e94779ed26
			defaultHierarchy: LocalDateTable_7b5bb61a-a31a-4b52-936f-af36aae7d032.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Area Name'
		dataType: string
		lineageTag: ad6acbcf-2156-4d67-92f0-7d6e7ee818ac
		summarizeBy: none
		sourceColumn: Area Name

		annotation SummarizationSetBy = Automatic

	column Numerator
		dataType: double
		lineageTag: 33499df6-5727-405f-b089-308676e73687
		summarizeBy: sum
		sourceColumn: Numerator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Denominator
		dataType: double
		lineageTag: 5568a0cd-bd68-42a9-acf4-eda76302a3fb
		summarizeBy: sum
		sourceColumn: Denominator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		dataType: double
		lineageTag: 7b107cb3-85a3-4d2b-bf36-62484f230eef
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Programme Measure Group'
		dataType: string
		lineageTag: 2033a46d-87b0-42e7-9b6a-4135b0b0ff0b
		summarizeBy: none
		sourceColumn: Programme Measure Group

		annotation SummarizationSetBy = Automatic

	column 'Indicator Group'
		dataType: string
		lineageTag: f354fadb-0c61-45b9-89ef-1cb58e620ebc
		summarizeBy: none
		sourceColumn: Indicator Group

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		lineageTag: a22d9b74-1b28-4848-a811-bbe95c45bbdf
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Patients'
		dataType: double
		lineageTag: 8407b650-9024-4250-86e0-65aa43d95127
		summarizeBy: sum
		sourceColumn: Target Patients

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Time'
		dataType: int64
		formatString: 0
		lineageTag: a8f9f680-3c8e-4c26-a3da-36b6775a0845
		summarizeBy: sum
		sourceColumn: Order Time

		annotation SummarizationSetBy = Automatic

	column 'Order Indicator'
		dataType: int64
		formatString: 0
		lineageTag: 0193df65-5bee-4aec-85e7-cb6bb3a29ac1
		summarizeBy: sum
		sourceColumn: Order Indicator

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: e418ec04-de43-43d5-8d31-216b7a881f1e
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: e039f37b-433c-40c4-8168-f344b295bb76
		summarizeBy: sum
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column 'Target Patients Flag'
		dataType: int64
		formatString: 0
		lineageTag: 699bcd77-b557-4a24-b694-98b172f6de51
		summarizeBy: sum
		sourceColumn: Target Patients Flag

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Good Is'
		dataType: string
		lineageTag: 933e8fb6-692c-455c-88c6-44f9e28e356f
		summarizeBy: none
		sourceColumn: Good Is

		annotation SummarizationSetBy = Automatic

	column 'Meta Data'
		dataType: string
		lineageTag: 66683e14-7a52-4cb0-91d3-cf2c5993cd98
		summarizeBy: none
		sourceColumn: Meta Data

		annotation SummarizationSetBy = Automatic

	column 'Target Flagging'
		dataType: int64
		formatString: 0
		lineageTag: c1201241-c4b1-42eb-8909-a1900230271a
		summarizeBy: sum
		sourceColumn: Target Flagging

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Target %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e28bbda8-bc29-4d82-836f-92a14c0cbcf7
		summarizeBy: sum
		sourceColumn: Target %

		annotation SummarizationSetBy = Automatic

	column 'Value - %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b93723e8-a380-4c4d-852b-422970cdceeb
		summarizeBy: sum
		sourceColumn: Value - %

		annotation SummarizationSetBy = Automatic

	column 'Data Source'
		dataType: string
		lineageTag: d8618dd9-1369-473f-8692-01cec66dd0cc
		summarizeBy: none
		sourceColumn: Data Source

		annotation SummarizationSetBy = Automatic

	column 'Quarter Name'
		dataType: string
		lineageTag: ef9ea675-c34e-47d6-be6c-808c97ffd14a
		summarizeBy: none
		sourceColumn: Quarter Name
		sortByColumn: 'Quarter Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Quarter Number'
		dataType: int64
		formatString: 0
		lineageTag: 6845a85c-b291-4876-b410-ba2cca0e4a7d
		summarizeBy: sum
		sourceColumn: Quarter Number

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition '1. Programme Level Metrics-d6c02214-887b-4c03-a996-8265e480670c' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select programme_measure_group as ""Programme Measure Group"", indicator_group as ""Indicator Group"", indicator_code as ""Indicator Code"", indicator_name as ""Indicator Name"", indicator_description as ""Indicator Description"", area_name as ""Area Name"", data_source as ""Data Source"", target as ""Target"", target_patients as ""Target Patients"", good_is as ""Good Is"", financial_year as ""Financial Year"", year as ""Year"", financial_month as ""Financial Month"", month_name as ""Month Name"", time_period as ""Time Period"", time_period_date as ""Time Period Date"", year_month as ""Year Month"", quarter_name as ""Quarter Name"", quarter_number as ""Quarter Number"", numerator as ""Numerator"", denominator as ""Denominator"", value as ""Value"", meta_data as ""Meta Data"", order_indicator as ""Order Indicator"", order_time as ""Order Time"" from data_mart_powerbi_circulatory.tbl10_circulatory_snapshots_programme", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", type number}, {"Denominator", type number}, {"Numerator", type number}, {"Target", Percentage.Type}, {"Target Patients", type number}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Value", "Value - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Value - Copy", "Value (%)"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Value (%)", Percentage.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Value (%)"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Columns", "Target Patients Flag", each if [Numerator] >= [Target Patients] then 1 else 0),
				    #"Added Custom" = Table.AddColumn(#"Added Conditional Column", "Target Flagging", each if [Good Is]="Low" and [Numerator]<[Target Patients]
				then 1
				else if [Good Is]="Low" and [Numerator]>[Target Patients]
				then 0
				else if[Good Is]="High" and [Numerator]>[Target Patients]
				then 1
				else if[Good Is]="High" and [Numerator]<[Target Patients]
				then 0
				else null),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Target %", each [Target]/100),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Target %", Percentage.Type}}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Changed Type2", "Value", "Value - Copy"),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Duplicated Column1",{{"Value - Copy", Percentage.Type}}),
				    #"Divided Column" = Table.TransformColumns(#"Changed Type3", {{"Value - Copy", each _ / 100, Percentage.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Divided Column",{{"Value - Copy", "Value - %"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

