table '2. Project Level Metrics'
	lineageTag: 0c334916-6c2c-4d8c-9583-2796d671e9c6

	measure Arrows =
			
			VAR Latest_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="High")
			VAR Previous_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 2,'2. Project Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="Low")
			VAR Previous_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 2,'2. Project Level Metrics'[Good Is]="Low")
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_High<Previous_Value_High,UNICHAR(UNICODE("↓")),
			IF(Latest_Value_Low>Previous_Value_Low,UNICHAR(UNICODE("↑")),
			IF(Latest_Value_Low<Previous_Value_Low,UNICHAR(UNICODE("↓")),""))))
		lineageTag: 5d3b50eb-6461-4c89-a715-084819a1b7af

	measure 'Arrow Colours' =
			
			VAR Latest_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="High")
			VAR Previous_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 2,'2. Project Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="Low")
			VAR Previous_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 2,'2. Project Level Metrics'[Good Is]="Low")
			
			RETURN
			
			IF(Latest_Value_High>Previous_Value_High,"#78BE20",
			IF(Latest_Value_High<Previous_Value_High,"#AE2424",
			IF(Latest_Value_Low>Previous_Value_Low,"#AE2424",
			IF(Latest_Value_Low<Previous_Value_Low,"#78BE20"))))
		lineageTag: 5a0d4085-30dc-4203-ab10-f006072bb2bf

	measure Target_Symbol =
			
			VAR Latest_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="Low")
			VAR Target_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Target]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="High")
			VAR Target_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Target]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="Low")
			
			RETURN
			IF(Latest_Value_High>Target_Value_High,UNICHAR(UNICODE("✔")),
			IF(Latest_Value_High<Target_Value_High,UNICHAR(UNICODE("⨯")),
			IF(Latest_Value_Low>Target_Value_Low,UNICHAR(UNICODE("⨯")),
			IF(Latest_Value_Low<Target_Value_Low,UNICHAR(UNICODE("✔")),""))))
		lineageTag: 97d4c594-cfc6-4e4c-a279-2dd804e7f3ac

	measure 'Target Colours' =
			
			VAR Latest_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="High")
			VAR Target_Value_High = CALCULATE(SUM('2. Project Level Metrics'[Target]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="High")
			VAR Latest_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Value]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="Low")
			VAR Target_Value_Low = CALCULATE(SUM('2. Project Level Metrics'[Target]),'2. Project Level Metrics'[Order Time] = 1,'2. Project Level Metrics'[Good Is]="Low")
			
			RETURN
			
			IF(Latest_Value_High>Target_Value_High,"#78BE20",
			IF(Latest_Value_High<Target_Value_High,"#AE2424",
			IF(Latest_Value_Low>Target_Value_Low,"#AE2424",
			IF(Latest_Value_Low<Target_Value_Low,"#78BE20"))))
		lineageTag: 54a0a627-e7a9-4029-b243-f5176d5698c7

	column 'Indicator Group'
		dataType: string
		lineageTag: a8bb2abd-d66a-407c-b97f-9be1a794c918
		summarizeBy: none
		sourceColumn: Indicator Group

		annotation SummarizationSetBy = Automatic

	column 'Indicator Code'
		dataType: string
		lineageTag: 4591aa89-8a65-41aa-8e2f-a99320b8f95d
		summarizeBy: none
		sourceColumn: Indicator Code

		annotation SummarizationSetBy = Automatic

	column 'Indicator Name'
		dataType: string
		lineageTag: a299e146-6df0-4918-afe5-043c2c276aca
		summarizeBy: none
		sourceColumn: Indicator Name

		annotation SummarizationSetBy = Automatic

	column 'Indicator Description'
		dataType: string
		lineageTag: 0f380096-a94e-4fde-a77c-0774a6fd07ab
		summarizeBy: none
		sourceColumn: Indicator Description

		annotation SummarizationSetBy = Automatic

	column 'Area Name'
		dataType: string
		lineageTag: 64d3db79-6dfa-43ca-81df-7be5e1c72a0d
		summarizeBy: none
		sourceColumn: Area Name

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		lineageTag: c3b5eb9f-ea8b-4f81-a2f8-d2e219832e7f
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Patients'
		dataType: double
		lineageTag: 07bdbf49-4908-40a7-8b76-803cf6d58a45
		summarizeBy: sum
		sourceColumn: Target Patients

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Good Is'
		dataType: string
		lineageTag: 579e1165-9578-45fe-bc52-9f7a8f510480
		summarizeBy: none
		sourceColumn: Good Is

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: 583e7956-b681-4583-adf8-e6a0a33b7dc7
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2802a947-7040-4487-8d96-a48c78f67dc2
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Financial Month'
		dataType: int64
		formatString: 0
		lineageTag: e227ca6a-8252-4f19-918f-497412af8d02
		summarizeBy: sum
		sourceColumn: Financial Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 32bb70e0-2ab6-4859-a5d5-3fff28331576
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Financial Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Time Period'
		dataType: string
		lineageTag: b05c4d14-78a6-4810-8bfe-9e51f5e24cab
		summarizeBy: none
		sourceColumn: Time Period
		sortByColumn: 'Order Time'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Time Period Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 332a868f-2ddf-4ea3-9d79-ed0a38c195dd
		summarizeBy: none
		sourceColumn: Time Period Date

		variation Variation
			isDefault
			relationship: dcbb558b-215d-4319-b564-6812e07ab3fa
			defaultHierarchy: LocalDateTable_8750f00f-be87-477e-8d72-614496c93372.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: 32520172-d835-49e6-8854-6b8555ad24ce
		summarizeBy: sum
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column Numerator
		dataType: double
		lineageTag: bdd70f44-a653-4485-9436-5481f3e4f759
		summarizeBy: sum
		sourceColumn: Numerator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Denominator
		dataType: double
		lineageTag: 6917b22a-7702-45a0-ace8-03e6837fedd0
		summarizeBy: sum
		sourceColumn: Denominator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		dataType: double
		lineageTag: 887b694e-ea30-469b-9e18-8b36dd62764a
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meta Data'
		dataType: string
		lineageTag: 3150ba3d-cf8f-45b2-b37d-2adf6eeac57a
		summarizeBy: none
		sourceColumn: Meta Data

		annotation SummarizationSetBy = Automatic

	column 'Order Indicator'
		dataType: int64
		formatString: 0
		lineageTag: 46e47441-2ff3-4547-b89e-2c46e45672d8
		summarizeBy: sum
		sourceColumn: Order Indicator

		annotation SummarizationSetBy = Automatic

	column 'Order Time'
		dataType: int64
		formatString: 0
		lineageTag: 0053fac9-f96a-4626-8a32-3d4d35029176
		summarizeBy: sum
		sourceColumn: Order Time

		annotation SummarizationSetBy = Automatic

	column 'Target Flagging'
		dataType: int64
		formatString: 0
		lineageTag: db2824cb-7917-48c8-9f5e-406b55ff837e
		summarizeBy: sum
		sourceColumn: Target Flagging

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Programme Measure Group'
		dataType: string
		lineageTag: e9b9fb01-772f-47eb-bb85-3c18f98e845e
		summarizeBy: none
		sourceColumn: Programme Measure Group

		annotation SummarizationSetBy = Automatic

	column 'Target % OLD'
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 120e8c6d-d9c4-4a8f-b6dc-eb484d10de9e
		summarizeBy: sum
		sourceColumn: Target % OLD

		annotation SummarizationSetBy = Automatic

	column 'Target %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 11848c01-1d7d-4ac7-9dcb-176a1c6ff17f
		summarizeBy: sum
		sourceColumn: Target %

		annotation SummarizationSetBy = Automatic

	column 'Value %'
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5efce15d-65db-4827-ae15-b3e1b778ceb2
		summarizeBy: sum
		sourceColumn: Value %

		annotation SummarizationSetBy = Automatic

	column 'Quarter Name'
		dataType: string
		lineageTag: b237481a-ac07-4259-a19d-7cdec5060244
		summarizeBy: none
		sourceColumn: Quarter Name

		annotation SummarizationSetBy = Automatic

	column 'Quarter Number'
		dataType: string
		lineageTag: 51da142c-7629-499f-ac39-fcce7485bda9
		summarizeBy: none
		sourceColumn: Quarter Number

		annotation SummarizationSetBy = Automatic

	partition '2. Project Level Metrics' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select programme_measure_group as ""Programme Measure Group"", indicator_group as ""Indicator Group"", indicator_code as ""Indicator Code"", indicator_name as ""Indicator Name"", indicator_description as ""Indicator Description"", area_name as ""Area Name"", target as ""Target"", target_patients as ""Target Patients"", good_is as ""Good Is"", financial_year as ""Financial Year"", year as ""Year"", financial_month as ""Financial Month"", month_name as ""Month Name"", time_period as ""Time Period"", time_period_date as ""Time Period Date"", year_month as ""Year Month"", quarter_name as ""Quarter Name"", quarter_number as ""Quarter Number"", numerator as ""Numerator"", denominator as ""Denominator"", value as ""Value"", meta_data as ""Meta Data"", order_indicator as ""Order Indicator"", order_time as ""Order Time"", processeddate from data_mart_powerbi_circulatory.tbl07_circulatory_snapshots_project", null, [EnableFolding=true]),
				    #"Added Custom" = Table.AddColumn(Source, "Target Flagging", each if [Good Is]="Low" and [Numerator]<[Target Patients]
				then 1
				else if [Good Is]="Low" and [Numerator]>[Target Patients]
				then 0
				else if[Good Is]="High" and [Numerator]>[Target Patients]
				then 1
				else if[Good Is]="High" and [Numerator]<[Target Patients]
				then 0
				else null),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Added Custom", "Target", "Target - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Target - Copy", "Target % OLD"}}),
				    #"Inserted Division" = Table.AddColumn(#"Renamed Columns", "Division", each [#"Target % OLD"] / 100, Percentage.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Division",{{"Division", "Target %"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns1", "Value %", each [Value]/100),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"Value %", Percentage.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

