table 'Demographics - Static'
	lineageTag: aa3d7e98-1b5d-4c55-9713-67d443bad3cf

	column 'NHS Number'
		dataType: string
		lineageTag: 2b79eaf2-62b4-438e-8cfb-f321f56957fd
		summarizeBy: none
		sourceColumn: NHS Number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: 30c199e9-84ce-4f65-98a0-b81605d75bef
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 25a87633-30bf-468a-afc4-3db5522675ca
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	partition 'Demographics - Static' = m
		mode: import
		source =
				let
				    Source = #"5. Heart Failure",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"NHS Number", "Ethnicity", "Gender"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"NHS Number"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

