table 'REF Sex'
	lineageTag: e52e4ea4-c6e3-4f95-b12a-856e6c91872a

	column M/F
		dataType: string
		lineageTag: 73cd921f-04d7-452f-94e7-09f03775b47c
		summarizeBy: none
		sourceColumn: M/F

		annotation SummarizationSetBy = Automatic

	column 'Binary M/F'
		dataType: int64
		formatString: 0
		lineageTag: 317b88be-e47f-4e83-bf32-aabd3a2ec0fe
		summarizeBy: sum
		sourceColumn: Binary M/F

		annotation SummarizationSetBy = Automatic

	column Male/Female
		dataType: string
		lineageTag: dfbe90cc-da5a-44c4-9f9e-4cd8dc23b2fa
		summarizeBy: none
		sourceColumn: Male/Female

		annotation SummarizationSetBy = Automatic

	partition 'REF Sex' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8lXSUTIEYt/EnFSlWJ1oJTcgxwiI3VJzYUJ++SUK3nn55XlAYQMgRvBhssEFqcmZaZmpKUBZS6gKhFhsLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"M/F" = _t, #"Binary M/F" = _t, #"Male/Female" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"M/F", type text}, {"Binary M/F", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

