table 'REF Ethnicity'
	lineageTag: ccee6454-14da-4132-9524-8a51b55673bf

	column Category
		dataType: string
		lineageTag: ebfd69d2-f138-41a0-9cf0-629c8831ff4a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Main_description
		dataType: string
		lineageTag: 879547ef-e487-4fa0-a48f-0514a1c2889c
		summarizeBy: none
		sourceColumn: Main_description

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Background'
		dataType: string
		lineageTag: ff714dc5-07f6-4039-bd20-d9502ad294f7
		summarizeBy: none
		sourceColumn: Ethnic Background

		annotation SummarizationSetBy = Automatic

	partition 'REF Ethnicity' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fZS7coQwDEV/xUO9+Yhlqy3y6FIwFAactYaNyNjObPL3weYlBazOWEcH+ZqhqoriVLwMQfU4PJCt61NVnD1oVINTOi0aBwG8HbEz/qohWLNWdNvf3PCNXSwedqknJXSJbys13u66M96CpKeY6LtiN25IqpkQLW+6Bx80ijNtUHSV9/HEEWvSguT54aBNIx0jMbwZkT1rwnOF3ktene8S33bRDprGyHNvUHQ9w4/p2KCfcYcPmiA21w6irncLwSiNnUrXQAT/K8dd0+jbFey7OSFZaCQ5D0/kNR3QBIvQqni6L8/yoZWxcICzpBie918soPEmK1zqeUP8U4xfdkgxHEsIEj0pB3a2R0qG3f0UFj3RDqKucv0Yl8Zlh1JXx5npua7/AA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Main_description = _t, #"Ethnic Background" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Category", type text}, {"Main_description", type text}, {"Ethnic Background", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

