table AHC
	lineageTag: 533e1953-a73e-4f00-864d-249c66ea5b25

	measure '% AHCs completed' =
			
			DIVIDE(
				SUM('AHC'[Counter_Event]),
				SUM('Cohort_LDA&A_over time'[Counter])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 97f20982-c841-4bc1-be7f-a37e13512729

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure Monthly_LD_Cohort = ```
			
			CALCULATE(
			    COUNT('Cohort_LDA&A_over time'[Counter]),
			    FILTER(
			        ALL('Cohort_LDA&A_over time'[census_date]),
			        'Cohort_LDA&A_over time'[census_date] = MAX('AHC'[census_Date])
			    )
			)
			
			
			```
		formatString: 0
		lineageTag: d9962d9f-c25f-4cfa-a90e-4fc26f9d332c

	measure AHC_Percentage_Complete = ```
			
			DIVIDE(
			    [Cumulative_Distinct_Event_FY],
			    [Monthly_LD_Cohort],
			    0
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 00454dfc-4c5a-4aa8-bb73-e4ea29241c21

	measure Cumulative_Distinct_Event_FY = ```
			
			CALCULATE(
			    SUM(AHC[Distinct_Events]),
			    FILTER(
			        ALL(AHC),
			        AHC[census_Date] <= MAX(AHC[census_Date]) &&
			        AHC[FinancialYear] = MAX(AHC[FinancialYear])
			    )
			)
			
			```
		formatString: 0
		lineageTag: b3f98c50-da07-47e8-8d53-f83a7a4e9ba8

	column census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: eaf1ed92-323a-4fd4-85c6-aa728b4b5c2d
		summarizeBy: none
		sourceColumn: census_Date

		annotation SummarizationSetBy = Automatic

	column Census_Financial_Year
		dataType: string
		lineageTag: f1766445-6f44-4cf9-be5e-8b3005e3c38b
		summarizeBy: none
		sourceColumn: Census_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Census_Month_Name
		dataType: string
		lineageTag: 0703335d-1d9f-4bcf-af7c-64258f2b106a
		summarizeBy: none
		sourceColumn: Census_Month_Name

		annotation SummarizationSetBy = Automatic

	column Derived_NHS_Number
		dataType: string
		lineageTag: 767379ba-1df9-41fa-8cfd-0ea4d9d346bf
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 3cfa05ec-94a7-4756-a163-20f30f981de2
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: b20dace9-d26b-487e-a6fe-22f9f8f58942
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 8978e9ed-8cbd-4b8a-9b4c-abd2da02604a
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 4b686efc-4e4f-424f-b3ac-ab64dfc3f8ad
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 511dd9cf-bf6e-42f9-8bbe-e71402461a1c
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 85860b4d-cb44-4191-bc30-754a50f4d89c
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column efi_category
		dataType: string
		lineageTag: fa1e6c09-b2ce-477b-a12d-ab7eef828345
		summarizeBy: none
		sourceColumn: efi_category

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 57075ff0-e4aa-493b-a84a-4a4808e78944
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 57504519-cae8-43be-8d6a-37a2ea0bbabe
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column ADHD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 1af343fb-710f-41c9-a97c-df8d322c56cb
		summarizeBy: sum
		sourceColumn: ADHD_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 91452f9e-3f81-431d-9fbb-c5276c155aac
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Counter_Cohort
		dataType: int64
		formatString: 0
		lineageTag: 51095c74-ea43-440a-be10-6be45ec2771b
		summarizeBy: sum
		sourceColumn: Counter_Cohort

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 0e9664ad-8360-4fd9-91dd-48473cbd7ee4
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column PseudoNHSNumber
		dataType: string
		lineageTag: 2365dddc-c557-4835-8fe5-937d8028c4dd
		summarizeBy: none
		sourceColumn: PseudoNHSNumber

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: 870f0024-757e-4e26-aec2-2e4989fd4b57
		summarizeBy: none
		sourceColumn: PracticeCode

		annotation SummarizationSetBy = Automatic

	column PracticeDescription
		dataType: string
		lineageTag: eaa26b1a-c9e4-4159-bc75-32a03d5b75b0
		summarizeBy: none
		sourceColumn: PracticeDescription

		annotation SummarizationSetBy = Automatic

	column EventCode
		dataType: string
		lineageTag: 25ff629f-2448-4b5f-bce5-342af221db04
		summarizeBy: none
		sourceColumn: EventCode

		annotation SummarizationSetBy = Automatic

	column SnomedCode
		dataType: string
		lineageTag: 983c690a-a2a9-47a6-bdf0-8b565b4764eb
		summarizeBy: none
		sourceColumn: SnomedCode

		annotation SummarizationSetBy = Automatic

	column SnomedCodeDescription
		dataType: string
		lineageTag: 00ce19cb-49ab-4c84-8f45-c274e228d8cb
		summarizeBy: none
		sourceColumn: SnomedCodeDescription

		annotation SummarizationSetBy = Automatic

	column Age_at_Event
		dataType: int64
		formatString: 0
		lineageTag: df0bc040-9049-44e3-813d-62475ebfd4ee
		summarizeBy: sum
		sourceColumn: Age_at_Event

		annotation SummarizationSetBy = Automatic

	column Age_Event_2cats
		dataType: string
		lineageTag: 1adff7a5-f04d-4471-9405-9e934e917fd0
		summarizeBy: none
		sourceColumn: Age_Event_2cats

		annotation SummarizationSetBy = Automatic

	column Age_Event_3cats
		dataType: string
		lineageTag: 0c1d86bd-a02d-47cc-a95f-c9b011c2377a
		summarizeBy: none
		sourceColumn: Age_Event_3cats

		annotation SummarizationSetBy = Automatic

	column SourceSystem
		dataType: string
		lineageTag: a7a96ece-2ab0-4adb-84c5-7f79ff9049ce
		summarizeBy: none
		sourceColumn: SourceSystem

		annotation SummarizationSetBy = Automatic

	column Event_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: e2a0ef17-4579-4e32-9c94-44a97be7a7e8
		summarizeBy: none
		sourceColumn: Event_Date

		variation Variation
			isDefault
			relationship: 2c9fdc08-0c7f-428c-97dc-e416c855a0b4
			defaultHierarchy: LocalDateTable_97e36d75-7071-4d30-bd2a-3a2ed9907473.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 50921db8-66cf-4ce4-a154-5e45becc54be
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_Name
		dataType: string
		lineageTag: e80ccd15-313d-4c97-ae12-d3d85a6f9710
		summarizeBy: none
		sourceColumn: Fin_Quarter_Name

		annotation SummarizationSetBy = Automatic

	column Quarter_FinYr
		dataType: string
		lineageTag: 1b5fef26-5024-4d17-8de1-e5b771d1a74b
		summarizeBy: none
		sourceColumn: Quarter_FinYr

		annotation SummarizationSetBy = Automatic

	column Year_Month
		dataType: string
		lineageTag: 843ac718-71b7-4254-a163-2019f9d26b86
		summarizeBy: none
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

	column Month_Name
		dataType: string
		lineageTag: f36fbbb0-a5a1-40b8-83cb-2ec0206fb2dd
		summarizeBy: none
		sourceColumn: Month_Name

		annotation SummarizationSetBy = Automatic

	column Fin_Week
		dataType: string
		lineageTag: 4b1fc344-9b7b-4836-9499-7394cde36f43
		summarizeBy: none
		sourceColumn: Fin_Week

		annotation SummarizationSetBy = Automatic

	column 'First AHC in FinYr'
		dataType: int64
		formatString: 0
		lineageTag: 9e80810e-2d60-49e3-8ea6-c8170d756f31
		summarizeBy: sum
		sourceColumn: First AHC in FinYr

		annotation SummarizationSetBy = Automatic

	column Counter_Event
		dataType: int64
		formatString: 0
		lineageTag: 0044a3e0-9d58-4801-83cc-f0842360fb11
		summarizeBy: sum
		sourceColumn: Counter_Event

		annotation SummarizationSetBy = Automatic

	column Distinct_Events
		dataType: int64
		formatString: 0
		lineageTag: 5903b3da-05ba-4939-bfcd-04584d56a55c
		summarizeBy: sum
		sourceColumn: Distinct_Events

		annotation SummarizationSetBy = Automatic

	partition AHC = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select census_date as ""census_Date"", census_financial_year as ""Census_Financial_Year"", census_month_name as ""Census_Month_Name"", derived_nhs_number as ""Derived_NHS_Number"", gender as ""Gender"", ethnic_origin_grouped as ""Ethnic Origin Grouped"", ethnic_origin_wider_groups as ""Ethnic Origin Wider Groups"", locality as ""Locality"", primarycarenetwork as ""PrimaryCareNetwork"", imdcountydecile as ""IMDcountyDecile"", efi_category, autism_flag as ""Autism_Flag"", ld_flag as ""LD_Flag"", adhd_flag as ""ADHD_Flag"", ld_autism_flag as ""LD_Autism_Flag"", counter_cohort as ""Counter_Cohort"", id as ""ID"", pseudonhsnumber as ""PseudoNHSNumber"", practicecode as ""PracticeCode"", practicedescription as ""PracticeDescription"", eventcode as ""EventCode"", snomedcode as ""SnomedCode"", snomedcodedescription as ""SnomedCodeDescription"", age_at_event as ""Age_at_Event"", age_event_2cats as ""Age_Event_2cats"", age_event_3cats as ""Age_Event_3cats"", sourcesystem as ""SourceSystem"", event_date as ""Event_Date"", financialyear as ""FinancialYear"", fin_quarter_name as ""Fin_Quarter_Name"", quarter_finyr as ""Quarter_FinYr"", year_month as ""Year-Month"", month_name as ""Month_Name"", fin_week as ""Fin_Week"", first_ahc_in_finyr as ""First AHC in FinYr"", counter_event as ""Counter_Event"", distinct_events as ""Distinct_Events"" from data_mart_powerbi_ldanda.tbl02_ld_ahc", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Year-Month", "Year_Month"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

