table 'BMI_Smokers_LTC_current census'
	lineageTag: ff63f53d-f6f3-4ea9-acbd-f3e8e2bb9d4c

	measure '% Smokers in Cohort' =
			
			DIVIDE(
				SUM('BMI_Smokers_LTC_current census'[Smoker]),
				SUM('BMI_Smokers_LTC_current census'[Counter_Cohort])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d4f152bb-be35-4d36-9b2c-61ff75ad9028

	column Census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 83a2bc7b-6486-4630-9c35-f08bfb31f37c
		summarizeBy: none
		sourceColumn: Census_Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Census_Financial_Year
		dataType: string
		lineageTag: 367c2e09-7300-4aab-81a6-e7aea0a4194c
		summarizeBy: none
		sourceColumn: Census_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Census_Month_Name
		dataType: string
		lineageTag: 40e1498e-70a7-4aa2-a2d9-79d47e11328d
		summarizeBy: none
		sourceColumn: Census_Month_Name

		annotation SummarizationSetBy = Automatic

	column Derived_NHS_Number
		dataType: string
		lineageTag: e58ea9e6-15db-4f0a-939f-a98d1b958a3a
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: 36f2ec90-debd-419d-baea-1b4f3e2f62e7
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: 74d95c35-152f-466e-b613-ddcad6630377
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: cfcd8a67-9917-4119-b915-5093bb2480fa
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: ec08500a-ede3-4007-b61e-fd22d323b393
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 323bc3ac-a4fb-4ea6-b933-ff4088b7ec77
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: 6dc1c256-75be-4b94-a6e4-5c7a6f5f6787
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 8257990e-1230-437d-998a-3987d1191962
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 96128648-87d6-4c42-9a20-e226d5fcbe0c
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 05cbf808-5f84-47ce-ae61-7a40af7395d3
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 82349228-dc5b-48f2-bcfe-288a23028e7c
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Counter_Cohort
		dataType: int64
		formatString: 0
		lineageTag: 3d10ec1e-de33-497f-a73d-7bef8ffeda43
		summarizeBy: sum
		sourceColumn: Counter_Cohort

		annotation SummarizationSetBy = Automatic

	column BMI
		dataType: double
		lineageTag: 0ec67d76-78ee-4555-a8e7-4e079d7b86ca
		summarizeBy: sum
		sourceColumn: BMI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BMIEventDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 4843745f-eb67-4fd7-a73a-67c574204c97
		summarizeBy: none
		sourceColumn: BMIEventDate

		variation Variation
			isDefault
			relationship: e2ae7af7-03c8-4d29-a9df-501a4daf318d
			defaultHierarchy: LocalDateTable_cbef2994-cb3e-47f5-bb6d-ca576408391e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column BMIGroup
		dataType: string
		lineageTag: a8a15a44-97ad-4b77-8b00-4b3fc269979e
		summarizeBy: none
		sourceColumn: BMIGroup

		annotation SummarizationSetBy = Automatic

	column Obesity
		dataType: int64
		formatString: 0
		lineageTag: f2068b7e-65db-492a-a339-a679c5101fb6
		summarizeBy: sum
		sourceColumn: Obesity

		annotation SummarizationSetBy = Automatic

	column HistoryOfObesity
		dataType: int64
		formatString: 0
		lineageTag: df05a190-bedb-42dd-978e-39b7c831d8e3
		summarizeBy: sum
		sourceColumn: HistoryOfObesity

		annotation SummarizationSetBy = Automatic

	column Smoker
		dataType: int64
		formatString: 0
		lineageTag: 3d02c544-8668-40d7-9541-fcf709290df3
		summarizeBy: sum
		sourceColumn: Smoker

		annotation SummarizationSetBy = Automatic

	column HistoryOfSmoking
		dataType: int64
		formatString: 0
		lineageTag: eb807bde-efbd-4464-aa17-3e42103a7ea2
		summarizeBy: sum
		sourceColumn: HistoryOfSmoking

		annotation SummarizationSetBy = Automatic

	column LTCCountDerived
		dataType: int64
		formatString: 0
		lineageTag: e0b71f5e-9b4f-4b15-8fe9-ff823bd41396
		summarizeBy: sum
		sourceColumn: LTCCountDerived

		annotation SummarizationSetBy = Automatic

	column LTCount_Derived_Fix
		dataType: int64
		formatString: 0
		lineageTag: ead049ee-82cd-46f2-a578-c9a8ea02a070
		summarizeBy: sum
		sourceColumn: LTCount_Derived_Fix

		annotation SummarizationSetBy = Automatic

	column LearningDisability
		dataType: int64
		formatString: 0
		lineageTag: 0400a8b1-6382-4d60-a769-d18ced2b2dae
		summarizeBy: sum
		sourceColumn: LearningDisability

		annotation SummarizationSetBy = Automatic

	column Asthma
		dataType: int64
		formatString: 0
		lineageTag: 23296708-43df-40d8-862b-7ec5820834b9
		summarizeBy: sum
		sourceColumn: Asthma

		annotation SummarizationSetBy = Automatic

	column COPD
		dataType: int64
		formatString: 0
		lineageTag: a87ea92d-4539-4e23-952e-5b6461041af0
		summarizeBy: sum
		sourceColumn: COPD

		annotation SummarizationSetBy = Automatic

	column Dementia
		dataType: int64
		formatString: 0
		lineageTag: 39af7cde-80db-4338-83f2-abf3f80bce1b
		summarizeBy: sum
		sourceColumn: Dementia

		annotation SummarizationSetBy = Automatic

	column Depression
		dataType: int64
		formatString: 0
		lineageTag: 3d83b7c5-2ac8-4e5f-bbba-d7c2fa2f041d
		summarizeBy: sum
		sourceColumn: Depression

		annotation SummarizationSetBy = Automatic

	column Diabetes
		dataType: int64
		formatString: 0
		lineageTag: 116c989e-669d-4866-836e-567427e137cb
		summarizeBy: sum
		sourceColumn: Diabetes

		annotation SummarizationSetBy = Automatic

	column PalliativeCare
		dataType: int64
		formatString: 0
		lineageTag: ee381cc9-8f35-4f91-9ed4-b4d7b7856f1f
		summarizeBy: sum
		sourceColumn: PalliativeCare

		annotation SummarizationSetBy = Automatic

	column ChronicKidneyDisease
		dataType: int64
		formatString: 0
		lineageTag: 9e293575-7d86-4aab-88b3-5890de803f2c
		summarizeBy: sum
		sourceColumn: ChronicKidneyDisease

		annotation SummarizationSetBy = Automatic

	column Epilepsy
		dataType: int64
		formatString: 0
		lineageTag: 0c7524ef-29d6-4db8-b843-73110bb372f5
		summarizeBy: sum
		sourceColumn: Epilepsy

		annotation SummarizationSetBy = Automatic

	column HeartFailure
		dataType: int64
		formatString: 0
		lineageTag: 4f7f5892-5c37-4d13-83e5-da831e57b8e6
		summarizeBy: sum
		sourceColumn: HeartFailure

		annotation SummarizationSetBy = Automatic

	column Stroke
		dataType: int64
		formatString: 0
		lineageTag: 48c6cd08-10fd-4c8a-8ef2-358f2de70f1b
		summarizeBy: sum
		sourceColumn: Stroke

		annotation SummarizationSetBy = Automatic

	column AtrialFibrillation
		dataType: int64
		formatString: 0
		lineageTag: 650c9167-e9a2-4e59-8f18-29f5cacb9b9a
		summarizeBy: sum
		sourceColumn: AtrialFibrillation

		annotation SummarizationSetBy = Automatic

	column Cancer
		dataType: int64
		formatString: 0
		lineageTag: f8669de3-ffb7-473a-a8e1-e633f8ea190b
		summarizeBy: sum
		sourceColumn: Cancer

		annotation SummarizationSetBy = Automatic

	column CoronaryHeartDisease
		dataType: int64
		formatString: 0
		lineageTag: 6d14ad77-7bbf-46dd-a2c1-a40ebccbdb4d
		summarizeBy: sum
		sourceColumn: CoronaryHeartDisease

		annotation SummarizationSetBy = Automatic

	column Hypertension
		dataType: int64
		formatString: 0
		lineageTag: e88f35e4-4d08-468d-910e-49ea615cbffb
		summarizeBy: sum
		sourceColumn: Hypertension

		annotation SummarizationSetBy = Automatic

	column MentalIllness
		dataType: int64
		formatString: 0
		lineageTag: bd8daab2-1641-4b15-b825-59fd1b08fb06
		summarizeBy: sum
		sourceColumn: MentalIllness

		annotation SummarizationSetBy = Automatic

	column ACGPatientNeedsGroup
		dataType: string
		lineageTag: ff1356b1-5200-4712-abf2-f5c7d152e912
		summarizeBy: none
		sourceColumn: ACGPatientNeedsGroup

		annotation SummarizationSetBy = Automatic

	column Condition_Category
		dataType: string
		lineageTag: 743abaf7-e04e-46f3-83ff-d1842d02fcef
		summarizeBy: none
		sourceColumn: Condition_Category

		annotation SummarizationSetBy = Automatic

	column 5YR_Age_Band
		dataType: string
		lineageTag: 67cbd2d9-fea9-48da-9783-002acd31e701
		summarizeBy: none
		sourceColumn: 5YR_Age_Band

		annotation SummarizationSetBy = Automatic

	column Age_Band_3cats
		dataType: string
		lineageTag: dab9693e-370b-4150-a61d-d4178c60fa43
		summarizeBy: none
		sourceColumn: Age_Band_3cats

		annotation SummarizationSetBy = Automatic

	column Age_Band_2cats
		dataType: string
		lineageTag: 2c3361c8-fb7b-491e-9013-ff1b47aa1a47
		summarizeBy: none
		sourceColumn: Age_Band_2cats

		annotation SummarizationSetBy = Automatic

	partition 'BMI_Smokers_LTC_current census' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select census_date as ""Census_Date"", census_financial_year as ""Census_Financial_Year"", census_month_name as ""Census_Month_Name"", derived_nhs_number as ""Derived_NHS_Number"", practice_code as ""Practice_Code"", practice_name as ""Practice_Name"", primarycarenetwork as ""PrimaryCareNetwork"", locality as ""Locality"", ethnic_origin_wider_groups as ""Ethnic Origin Wider Groups"", ethnic_origin_grouped as ""Ethnic Origin Grouped"", imdcountydecile as ""IMDcountyDecile"", ld_flag as ""LD_Flag"", autism_flag as ""Autism_Flag"", ld_autism_flag as ""LD_Autism_Flag"", condition_category as ""Condition_Category"", counter_cohort as ""Counter_Cohort"", age_band_5yr as ""5YR_Age_Band"", age_band_3cats as ""Age_Band_3cats"", age_band_2cats as ""Age_Band_2cats"", bmi as ""BMI"", bmieventdate as ""BMIEventDate"", bmigroup as ""BMIGroup"", obesity as ""Obesity"", historyofobesity as ""HistoryOfObesity"", smoker as ""Smoker"", historyofsmoking as ""HistoryOfSmoking"", ltccountderived as ""LTCCountDerived"", ltcount_derived_fix as ""LTCount_Derived_Fix"", learningdisability as ""LearningDisability"", asthma as ""Asthma"", copd as ""COPD"", dementia as ""Dementia"", depression as ""Depression"", diabetes as ""Diabetes"", palliativecare as ""PalliativeCare"", chronickidneydisease as ""ChronicKidneyDisease"", epilepsy as ""Epilepsy"", heartfailure as ""HeartFailure"", stroke as ""Stroke"", atrialfibrillation as ""AtrialFibrillation"", cancer as ""Cancer"", coronaryheartdisease as ""CoronaryHeartDisease"", hypertension as ""Hypertension"", mentalillness as ""MentalIllness"", acgpatientneedsgroup as ""ACGPatientNeedsGroup"" from data_mart_powerbi_ldanda.tbl09_lda_bmi_smoke_ltcs_cc", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Census_Date", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows",null,"Unknown",Replacer.ReplaceValue,{"BMIGroup"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value", each true),
				    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows1","<14","0-13",Replacer.ReplaceText,{"Age_Band_2cats"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

