table 'Cohort_LDA&A_over time'
	lineageTag: 67671e09-bd7e-4e01-a7d6-a95600aff0d0

	column Census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: bf93e659-7c83-4016-aaa5-ba706478fb26
		summarizeBy: none
		sourceColumn: Census_Date

		annotation SummarizationSetBy = Automatic

	column Census_Financial_Year
		dataType: string
		lineageTag: 422b4bec-f741-429e-a9b9-1b237e951edb
		summarizeBy: none
		sourceColumn: Census_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Census_Month_Name
		dataType: string
		lineageTag: bd227d84-1cab-4fc0-9f87-71f8661d6ca5
		summarizeBy: none
		sourceColumn: Census_Month_Name

		annotation SummarizationSetBy = Automatic

	column Derived_NHS_Number
		dataType: string
		lineageTag: 3ba38bae-a1d7-420a-9793-4c7fea674b78
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: cc70dc7f-98ef-46ba-aa81-210b3447dbd2
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: 8807f9cc-5793-4368-8297-72560bf4a17e
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: c9cb23b4-9c32-4ad9-ba0c-60259401b69c
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: ddee2718-3d5d-4ee0-9d98-914a1fdc253a
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column Age_at_census
		dataType: int64
		formatString: 0
		lineageTag: b789f096-70d4-4d18-8c86-c651676fa0df
		summarizeBy: sum
		sourceColumn: Age_at_census

		annotation SummarizationSetBy = Automatic

	column 5YR_Age_Band
		dataType: string
		lineageTag: c84398b6-3984-4475-9280-8fa6dede0e78
		summarizeBy: none
		sourceColumn: 5YR_Age_Band

		annotation SummarizationSetBy = Automatic

	column 10YR_Age_Band
		dataType: string
		lineageTag: 1224ebd2-de2b-4e68-9520-3ef18cd6da33
		summarizeBy: none
		sourceColumn: 10YR_Age_Band

		annotation SummarizationSetBy = Automatic

	column Age_Band_3cats
		dataType: string
		lineageTag: c39afb97-29b5-47de-ae7f-787f8a0b8e1f
		summarizeBy: none
		sourceColumn: Age_Band_3cats

		annotation SummarizationSetBy = Automatic

	column Age_Band_2cats
		dataType: string
		lineageTag: 76974bab-2874-44a3-9235-13a69106302f
		summarizeBy: none
		sourceColumn: Age_Band_2cats

		annotation SummarizationSetBy = Automatic

	column efi_category
		dataType: string
		lineageTag: ae4cd20c-3e71-40a6-8a6e-b8f4bd635d83
		summarizeBy: none
		sourceColumn: efi_category

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 2709b79c-d5ff-44e2-b930-a7de3ed7fe79
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EthnicOriginDescription
		dataType: string
		lineageTag: 3bf0d7ab-2bb3-46fc-b89a-7a9ea59981fe
		summarizeBy: none
		sourceColumn: EthnicOriginDescription

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 7ef6804d-d1cd-4bb2-a5f9-2c9ff7d11cbc
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: 3d1b0c5c-14d2-4a6a-9768-2044c96139f8
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 5cf9df53-298d-481e-83d2-e226b2ebd87f
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 8175c611-c9d3-43b7-8d1c-2368104e5449
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 0f097110-9643-4bcf-a18f-be51fe3a3f90
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column ADHD_Flag
		dataType: int64
		formatString: 0
		lineageTag: dc0f636d-b40c-420f-8b8f-c5520d9d660b
		summarizeBy: sum
		sourceColumn: ADHD_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 19c74e8c-2f2b-44be-aca9-2f167f4ed5b8
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: a107f380-ee95-4ec0-9f74-1bd3a4aca875
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column Data_Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: cb7cacc2-d829-45e3-a32b-998f90456d76
		summarizeBy: none
		sourceColumn: Data_Updated

		variation Variation
			isDefault
			relationship: 1be9ff85-ad1b-4506-b0c7-295e0b02163d
			defaultHierarchy: LocalDateTable_b9833fbe-ada2-4b0b-bb76-9cd8165e0d3b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Cohort_LDA&A_over time' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select census_date as ""Census_Date"", census_financial_year as ""Census_Financial_Year"", census_month_name as ""Census_Month_Name"", derived_nhs_number as ""Derived_NHS_Number"", practice_code as ""Practice_Code"", practice_name as ""Practice_Name"", primarycarenetwork as ""PrimaryCareNetwork"", locality as ""Locality"", age_at_census as ""Age_at_census"", age_band_5yr as ""5YR_Age_Band"", age_band_10yr as ""10YR_Age_Band"", age_band_3cats as ""Age_Band_3cats"", age_band_2cats as ""Age_Band_2cats"", efi_category, gender as ""Gender"", ethnicorigindescription as ""EthnicOriginDescription"", ethnic_origin_wider_groups as ""Ethnic Origin Wider Groups"", ethnic_origin_grouped as ""Ethnic Origin Grouped"", imdcountydecile as ""IMDcountyDecile"", autism_flag as ""Autism_Flag"", ld_flag as ""LD_Flag"", adhd_flag as ""ADHD_Flag"", ld_autism_flag as ""LD_Autism_Flag"", counter as ""Counter"", data_updated as ""Data_Updated"" from data_mart_powerbi_ldanda.tbl01_ld_autism_adhd_cohort", null, [EnableFolding=true]),
				    #"5yr ageband 0-4 to 0-04" = Table.ReplaceValue(Source,"0-4","0-04",Replacer.ReplaceValue,{"5YR_Age_Band"}),
				    #"5yr ageband 5-9 to 05-09" = Table.ReplaceValue(#"5yr ageband 0-4 to 0-04","5-9","05-09",Replacer.ReplaceValue,{"5YR_Age_Band"}),
				    #"10yr ageband 0-9 to 0-09" = Table.ReplaceValue(#"5yr ageband 5-9 to 05-09","0-9","0-09",Replacer.ReplaceValue,{"10YR_Age_Band"}),
				    Capitalized_Practice_Name = Table.TransformColumns(#"10yr ageband 0-9 to 0-09",{{"Practice_Name", Text.Proper, type text}})
				in
				    Capitalized_Practice_Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

