table 'ED_over time'
	lineageTag: 393af038-a2be-46f0-866f-bc693e34f4a4

	column Derived_NHS_Number
		dataType: string
		lineageTag: b28630a2-f2b4-44b4-88c5-5cc92eaf40e7
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Census_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 61ca51dc-6c03-4cdc-bd0d-e9b6f6e21f13
		summarizeBy: none
		sourceColumn: Census_date

		variation Variation
			isDefault
			relationship: 1cd5eae6-3c19-43dc-b94b-ccaa89443395
			defaultHierarchy: LocalDateTable_86d37f70-b26a-4bd3-9eed-d03713d52cac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: d8f3733e-3a44-4544-a747-006fb41b920a
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 97c0e332-2242-4541-b261-3a286900e876
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: eca92f66-5109-43fc-a2a2-a91d4e4d02d8
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Condition_Category
		dataType: string
		lineageTag: 27a74527-30c3-4d42-8ab5-fbbc033a8cfe
		summarizeBy: none
		sourceColumn: Condition_Category

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: 82b7dee8-99ce-4f8f-b00c-99ebecb80cac
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 59ec33fb-4bde-4cf8-b7e7-cc18258dae00
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column LDA_Counter
		dataType: int64
		formatString: 0
		lineageTag: 085866c1-d592-43f0-b16b-1d08f37cf9fa
		summarizeBy: sum
		sourceColumn: LDA_Counter

		annotation SummarizationSetBy = Automatic

	column nhs_number
		dataType: string
		lineageTag: 406435be-ea02-44fa-b99f-7a8da6da34c9
		summarizeBy: none
		sourceColumn: nhs_number

		annotation SummarizationSetBy = Automatic

	column data_source
		dataType: string
		lineageTag: defe2120-fb38-4e69-8621-9e36863afc98
		summarizeBy: none
		sourceColumn: data_source

		annotation SummarizationSetBy = Automatic

	column CDS_Unique_Identifier
		dataType: string
		lineageTag: 5efb27d4-a099-4b97-aac0-90194bd0f825
		summarizeBy: none
		sourceColumn: CDS_Unique_Identifier

		annotation SummarizationSetBy = Automatic

	column arrival_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 77465b2a-de68-4a59-98fc-ff7b89a5537d
		summarizeBy: none
		sourceColumn: arrival_date

		annotation SummarizationSetBy = Automatic

	column arrival_hour
		dataType: int64
		formatString: 0
		lineageTag: f1f932be-4a96-41ca-b915-bbfe5bb77c6d
		summarizeBy: sum
		sourceColumn: arrival_hour

		annotation SummarizationSetBy = Automatic

	column arrival_mode_grouped
		dataType: string
		lineageTag: 4c9b10ab-101e-4598-b047-8a7358ced153
		summarizeBy: none
		sourceColumn: arrival_mode_grouped

		annotation SummarizationSetBy = Automatic

	column attendance_category
		dataType: string
		lineageTag: ede6ff19-72de-48a6-9606-d40652e7a0c0
		summarizeBy: none
		sourceColumn: attendance_category

		annotation SummarizationSetBy = Automatic

	column attendance_source
		dataType: string
		lineageTag: cec6cf75-7661-4bd5-886f-1d676ba7033e
		summarizeBy: none
		sourceColumn: attendance_source

		annotation SummarizationSetBy = Automatic

	column acuity
		dataType: string
		lineageTag: f0ebbffd-1835-4e48-980b-6ae36cfaa03e
		summarizeBy: none
		sourceColumn: acuity

		annotation SummarizationSetBy = Automatic

	column major_minor_flag
		dataType: string
		lineageTag: 6ea7b434-aa4f-43bc-adc9-b4b6f7a7ce31
		summarizeBy: none
		sourceColumn: major_minor_flag

		annotation SummarizationSetBy = Automatic

	column departure_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a08f84e3-fffa-4c3c-9d59-72fbadec29c1
		summarizeBy: none
		sourceColumn: departure_date

		variation Variation
			isDefault
			relationship: be374aa1-0668-4261-afb9-2cad293f0a9d
			defaultHierarchy: LocalDateTable_5d35accb-4467-4695-977d-47d28d9baf6b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column minutes_in_ed
		dataType: int64
		formatString: 0
		lineageTag: 50676f89-ac18-4939-97c4-db3ecace5154
		summarizeBy: sum
		sourceColumn: minutes_in_ed

		annotation SummarizationSetBy = Automatic

	column hours_in_ed
		dataType: double
		lineageTag: 902b4a59-1e50-47f6-8294-132e96a173ac
		summarizeBy: sum
		sourceColumn: hours_in_ed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column decision_to_admit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 22650d75-11e5-461f-8d23-dedd9f34e3ac
		summarizeBy: none
		sourceColumn: decision_to_admit_date

		variation Variation
			isDefault
			relationship: 957a12b6-f219-43d0-b482-8b9d6d84135b
			defaultHierarchy: LocalDateTable_4ad278cd-c9b0-464d-abf3-113008d7614f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column breach_reason
		dataType: string
		lineageTag: fb5a1284-ac87-4bbe-b839-642e7d69ad45
		summarizeBy: none
		sourceColumn: breach_reason

		annotation SummarizationSetBy = Automatic

	column admitted_flag
		dataType: string
		lineageTag: df6cef03-d4e9-4bed-a101-37c1e9d5face
		summarizeBy: none
		sourceColumn: admitted_flag

		annotation SummarizationSetBy = Automatic

	column discharge_status
		dataType: string
		lineageTag: 60b90ac2-d973-4463-80de-d93bf8482289
		summarizeBy: none
		sourceColumn: discharge_status

		annotation SummarizationSetBy = Automatic

	column discharge_destination
		dataType: string
		lineageTag: ea238902-d725-4073-bcc2-b2952c37c597
		summarizeBy: none
		sourceColumn: discharge_destination

		annotation SummarizationSetBy = Automatic

	column commissioner_group
		dataType: string
		lineageTag: b38e9e35-b84d-4250-b527-0c958c61a8a0
		summarizeBy: none
		sourceColumn: commissioner_group

		annotation SummarizationSetBy = Automatic

	column code_of_commissioner
		dataType: string
		lineageTag: 736f06d1-f41a-4330-8591-4b3618903134
		summarizeBy: none
		sourceColumn: code_of_commissioner

		annotation SummarizationSetBy = Automatic

	column provider_group_derived
		dataType: string
		lineageTag: 89423df7-7771-4991-8ef0-ecb811789465
		summarizeBy: none
		sourceColumn: provider_group_derived

		annotation SummarizationSetBy = Automatic

	column provider_group
		dataType: string
		lineageTag: b11d4b9f-9b25-4a4b-a3d8-f9e4a0f207d5
		summarizeBy: none
		sourceColumn: provider_group

		annotation SummarizationSetBy = Automatic

	column site_code
		dataType: string
		lineageTag: 83f42c36-92c4-415f-be2e-b2e746b2f8cd
		summarizeBy: none
		sourceColumn: site_code

		annotation SummarizationSetBy = Automatic

	column site_name
		dataType: string
		lineageTag: 663b94e0-d6c3-409e-ad79-147fe4ffe094
		summarizeBy: none
		sourceColumn: site_name

		annotation SummarizationSetBy = Automatic

	column department_type
		dataType: string
		lineageTag: d90d5eee-ccc4-4435-b495-69b272020939
		summarizeBy: none
		sourceColumn: department_type

		annotation SummarizationSetBy = Automatic

	column ECDS_Diagnosis_Description
		dataType: string
		lineageTag: 00f6c293-6ad0-4ca7-b2f3-5c130a14c3db
		summarizeBy: none
		sourceColumn: ECDS_Diagnosis_Description

		annotation SummarizationSetBy = Automatic

	column ECDS_Diagnosis_ICD10_Equivalent_Chapter
		dataType: string
		lineageTag: b01d7556-cdca-40a1-b065-47d7c6ac84a0
		summarizeBy: none
		sourceColumn: ECDS_Diagnosis_ICD10_Equivalent_Chapter

		annotation SummarizationSetBy = Automatic

	column injury_illness_flag
		dataType: string
		lineageTag: ab428a8c-3d72-4af8-8dda-7c91354f5c61
		summarizeBy: none
		sourceColumn: injury_illness_flag

		annotation SummarizationSetBy = Automatic

	column Financial_Year_Activity
		dataType: string
		lineageTag: d3438507-1135-4cbf-a15e-aae528f017a5
		summarizeBy: none
		sourceColumn: Financial_Year_Activity

		annotation SummarizationSetBy = Automatic

	column Month_Name_Activity
		dataType: string
		lineageTag: 09dc4e67-3b67-43ee-8d29-1f30627971f4
		summarizeBy: none
		sourceColumn: Month_Name_Activity

		annotation SummarizationSetBy = Automatic

	column Year_Month_Activity
		dataType: int64
		formatString: 0
		lineageTag: 2b034d06-1798-4020-b444-cc113f17a001
		summarizeBy: sum
		sourceColumn: Year_Month_Activity

		annotation SummarizationSetBy = Automatic

	column 'Year / Month Activity'
		dataType: string
		lineageTag: 1eadd30f-ea42-42e5-9929-2f46e5150714
		summarizeBy: none
		sourceColumn: Year / Month Activity

		annotation SummarizationSetBy = Automatic

	column Weekday_Name_Activity
		dataType: string
		lineageTag: b8c9d6c1-a3f2-4c4a-b563-1b5fe2342002
		summarizeBy: none
		sourceColumn: Weekday_Name_Activity

		annotation SummarizationSetBy = Automatic

	column age_at_activity_date
		dataType: int64
		formatString: 0
		lineageTag: 95c07bb9-c118-4911-95ef-2f2d8c7ad0a0
		summarizeBy: sum
		sourceColumn: age_at_activity_date

		annotation SummarizationSetBy = Automatic

	column Age_Event_2cats
		dataType: string
		lineageTag: 470d507f-59eb-4723-a4bc-f036ad9bd4f9
		summarizeBy: none
		sourceColumn: Age_Event_2cats

		annotation SummarizationSetBy = Automatic

	column Age_Event_3cats
		dataType: string
		lineageTag: 9f7e9a60-4f18-45ce-9fe8-ae54c6886583
		summarizeBy: none
		sourceColumn: Age_Event_3cats

		annotation SummarizationSetBy = Automatic

	column 5yr_Ageband_at_Activity
		dataType: string
		lineageTag: 86b46e3f-b51e-4500-b98c-8e1d0ca371e4
		summarizeBy: none
		sourceColumn: 5yr_Ageband_at_Activity

		annotation SummarizationSetBy = Automatic

	column 10yr_age_band_at_activity
		dataType: string
		lineageTag: 1120b043-c023-4066-b632-7cb34621e0ab
		summarizeBy: none
		sourceColumn: 10yr_age_band_at_activity

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: 6ab8b213-a402-490a-b966-f5fb77f72555
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column primary_care_network
		dataType: string
		lineageTag: 69ecfa2a-6bf4-4b50-a5c9-b3ec97eae567
		summarizeBy: none
		sourceColumn: primary_care_network

		annotation SummarizationSetBy = Automatic

	column practice_code
		dataType: string
		lineageTag: 80954467-6aa9-46a2-a4ac-36d2ed67bff9
		summarizeBy: none
		sourceColumn: practice_code

		annotation SummarizationSetBy = Automatic

	column practice_name
		dataType: string
		lineageTag: bdfda4c0-eb11-4e1a-82b8-25ec99c549a6
		summarizeBy: none
		sourceColumn: practice_name

		annotation SummarizationSetBy = Automatic

	column lsoa
		dataType: string
		lineageTag: 5e3d48c0-690b-45fd-81bb-856d5a286e54
		summarizeBy: none
		sourceColumn: lsoa

		annotation SummarizationSetBy = Automatic

	column deprivation_decile
		dataType: int64
		formatString: 0
		lineageTag: 43b14fdf-e81c-4735-9119-dfb952755b03
		summarizeBy: sum
		sourceColumn: deprivation_decile

		annotation SummarizationSetBy = Automatic

	column core_20
		dataType: int64
		formatString: 0
		lineageTag: 2c48a897-a709-40c5-be16-86293eadc5f4
		summarizeBy: sum
		sourceColumn: core_20

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 9daee5fa-b9cc-4b87-b073-5b4e76ff75f8
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column efi_category
		dataType: string
		lineageTag: 6e454d3c-33f1-4ab1-a35a-3396a2c7bafa
		summarizeBy: none
		sourceColumn: efi_category

		annotation SummarizationSetBy = Automatic

	column 'SPC Flag'
		dataType: int64
		formatString: 0
		lineageTag: 016840ff-cb4f-402e-9f8d-48bedab8e95d
		summarizeBy: sum
		sourceColumn: SPC Flag

		annotation SummarizationSetBy = Automatic

	column 'Weekday Sorter'
		dataType: int64
		formatString: 0
		lineageTag: 32ef08f2-2052-47b2-a433-b3ce7d95cac4
		summarizeBy: sum
		sourceColumn: Weekday Sorter

		annotation SummarizationSetBy = Automatic

	column Counter_Event
		dataType: int64
		formatString: 0
		lineageTag: 95c3b0da-bec4-4047-873d-68c17f532eeb
		summarizeBy: sum
		sourceColumn: Counter_Event

		annotation SummarizationSetBy = Automatic

	column Acuity_short_desc
		dataType: string
		lineageTag: eb4db5a7-f778-4efd-8386-e7536adf7768
		summarizeBy: none
		sourceColumn: Acuity_short_desc

		annotation SummarizationSetBy = Automatic

	partition 'ED_over time' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Reporting", [Query="SELECT *#(lf)FROM [PowerBI_Reporting].[LDandA].[tbl06_ED_ot]"]),
				    #"Ethnic_null to unknown" = Table.ReplaceValue(Source,null,"Unknown",Replacer.ReplaceValue,{"Ethnic Origin Grouped"}),
				    #"Wider Grps_ null to unknown" = Table.ReplaceValue(#"Ethnic_null to unknown",null,"Unknown",Replacer.ReplaceValue,{"Ethnic Origin Wider Groups"}),
				    #"att source_null to not recorded" = Table.ReplaceValue(#"Wider Grps_ null to unknown",null,"not recorded",Replacer.ReplaceValue,{"attendance_source"}),
				    #"acuity null to not rec" = Table.ReplaceValue(#"att source_null to not recorded",null,"not recorded",Replacer.ReplaceValue,{"acuity"}),
				    #"Maj min null to not rec" = Table.ReplaceValue(#"acuity null to not rec",null,"not recorded",Replacer.ReplaceValue,{"major_minor_flag"}),
				    #"Added Custom Column" = Table.AddColumn(#"Maj min null to not rec", "Custom", each Text.Combine({Text.Start(Text.From([Year_Month_Activity], "en-GB"), 4), "/", Text.Middle(Text.From([Year_Month_Activity], "en-GB"), 4)}), type text),
				    #"Y/M Activity_format" = Table.RenameColumns(#"Added Custom Column",{{"Custom", "Year / Month Activity"}}),
				    #"Moved Y/M Act next to Y_M_Act" = Table.ReorderColumns(#"Y/M Activity_format",{"Derived_NHS_Number", "Census_date", "LD_Flag", "Autism_Flag", "LD_Autism_Flag", "Condition_Category", "Ethnic Origin Grouped", "Ethnic Origin Wider Groups", "LDA_Counter", "nhs_number", "data_source", "CDS_Unique_Identifier", "arrival_date", "arrival_hour", "arrival_mode_grouped", "attendance_category", "attendance_source", "acuity", "major_minor_flag", "departure_date", "minutes_in_ed", "hours_in_ed", "decision_to_admit_date", "breach_reason", "admitted_flag", "discharge_status", "discharge_destination", "commissioner_group", "code_of_commissioner", "provider_group_derived", "provider_group", "site_code", "site_name", "department_type", "ECDS_Diagnosis_Description", "ECDS_Diagnosis_ICD10_Equivalent_Chapter", "injury_illness_flag", "Financial_Year_Activity", "Month_Name_Activity", "Year_Month_Activity", "Year / Month Activity", "Weekday_Name_Activity", "age_at_activity_date", "Age_Event_2cats", "Age_Event_3cats", "5yr_Ageband_at_Activity", "10yr_age_band_at_activity", "locality", "primary_care_network", "practice_code", "practice_name", "lsoa", "deprivation_decile", "core_20", "gender", "efi_category", "SPC Flag", "Weekday Sorter", "Counter_Event"}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Moved Y/M Act next to Y_M_Act", "Text Before Delimiter", each Text.BeforeDelimiter([acuity], " ", 1), type text),
				    #"Acuity short desc added" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "Acuity_short_desc"}}),
				    #"Move Acuity short desc next to Acuity" = Table.ReorderColumns(#"Acuity short desc added",{"Derived_NHS_Number", "Census_date", "LD_Flag", "Autism_Flag", "LD_Autism_Flag", "Condition_Category", "Ethnic Origin Grouped", "Ethnic Origin Wider Groups", "LDA_Counter", "nhs_number", "data_source", "CDS_Unique_Identifier", "arrival_date", "arrival_hour", "arrival_mode_grouped", "attendance_category", "attendance_source", "acuity", "Acuity_short_desc", "major_minor_flag", "departure_date", "minutes_in_ed", "hours_in_ed", "decision_to_admit_date", "breach_reason", "admitted_flag", "discharge_status", "discharge_destination", "commissioner_group", "code_of_commissioner", "provider_group_derived", "provider_group", "site_code", "site_name", "department_type", "ECDS_Diagnosis_Description", "ECDS_Diagnosis_ICD10_Equivalent_Chapter", "injury_illness_flag", "Financial_Year_Activity", "Month_Name_Activity", "Year_Month_Activity", "Year / Month Activity", "Weekday_Name_Activity", "age_at_activity_date", "Age_Event_2cats", "Age_Event_3cats", "5yr_Ageband_at_Activity", "10yr_age_band_at_activity", "locality", "primary_care_network", "practice_code", "practice_name", "lsoa", "deprivation_decile", "core_20", "gender", "efi_category", "SPC Flag", "Weekday Sorter", "Counter_Event"})
				in
				    #"Move Acuity short desc next to Acuity"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

