table HAP
	lineageTag: abcc9924-1950-4840-9281-95f1bc5a411e

	measure Cumulative_Distinct_Event_HAP_FY = ```
			
			CALCULATE(
			    SUM(HAP[Distinct_Events]),
			    FILTER(
			        ALL(HAP),
			        HAP[census_Date]<= MAX(HAP[census_Date]) &&
			        HAP[FinancialYear] = MAX(HAP[FinancialYear])
			    )
			)
			
			```
		formatString: 0
		lineageTag: 08362116-14aa-4ddc-a8e0-3816f23d468e

	measure HAP_Percentage_Complete = ```
			
			DIVIDE(
			    [Cumulative_Distinct_Event_HAP_FY],
			    [Monthly_LD_Cohort_HAP],
			    0
			)
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d80835a6-d917-45fe-affa-66e951c41ae2

	measure Monthly_LD_Cohort_HAP = ```
			
			CALCULATE(
			    COUNT('Cohort_LDA&A_over time'[Counter]),
			    FILTER(
			        ALL('Cohort_LDA&A_over time'[census_date]),
			        'Cohort_LDA&A_over time'[census_date] = MAX('HAP'[census_Date])
			    )
			)
			
			
			```
		formatString: 0
		lineageTag: 134e18a7-6009-4e2d-a613-e9e111ac10b2

	measure '% HAPs completed' =
			
			DIVIDE(
				SUM('HAP'[Counter_Event]),
				SUM('Cohort_LDA&A_over time'[Counter])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e9ffb542-a748-49e5-8148-1459b13025b6

	column census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d7b6d14-6a5e-46f4-9751-187b0bd274a3
		summarizeBy: none
		sourceColumn: census_Date

		annotation SummarizationSetBy = Automatic

	column Census_Financial_Year
		dataType: string
		lineageTag: 556e2fb4-3b07-47ae-9216-22cb691f10a0
		summarizeBy: none
		sourceColumn: Census_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Census_Month_Name
		dataType: string
		lineageTag: 82069991-81e5-4117-94a9-2cce8ce7d870
		summarizeBy: none
		sourceColumn: Census_Month_Name

		annotation SummarizationSetBy = Automatic

	column Derived_NHS_Number
		dataType: string
		lineageTag: 1a654e56-2935-43c7-b8de-dac75b4a9ee8
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: f9436201-a984-4119-873a-a0403e5b9dde
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: 1551236f-4b3d-4083-8f1d-855e7ea97f9a
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 455847a8-f721-4aa6-9c41-1cf8e6d9845e
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: f760a2a2-183c-4ca5-8aa6-04c93fd60edb
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: c00a7707-92a9-42c8-b83c-e480df6a3b40
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 2df773db-6526-4ca4-9218-4ad5938599ea
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column efi_category
		dataType: string
		lineageTag: 4c4e53f5-3051-4f60-b3d1-5b830c9eb65f
		summarizeBy: none
		sourceColumn: efi_category

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 0baa7284-d6d7-44ae-9ae8-1c206cb160fa
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: e1ffba49-172f-44f2-967a-855459d9c7d9
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column ADHD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9dafc057-71e5-4278-8ab4-1259d6535322
		summarizeBy: sum
		sourceColumn: ADHD_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 6e07d967-dcae-4731-94d1-d9846b1b92f6
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Counter_Cohort
		dataType: int64
		formatString: 0
		lineageTag: e8f3f10c-8440-471e-9f2e-d6346f131143
		summarizeBy: sum
		sourceColumn: Counter_Cohort

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 7d53ef84-1646-4796-a104-5988c2ebd6e2
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column PseudoNHSNumber
		dataType: string
		lineageTag: ef8c83fc-91d4-436c-bc84-cf8f5da994fd
		summarizeBy: none
		sourceColumn: PseudoNHSNumber

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: b55a4a4f-f083-40f7-b5f8-755af98c8a11
		summarizeBy: none
		sourceColumn: PracticeCode

		annotation SummarizationSetBy = Automatic

	column PracticeDescription
		dataType: string
		lineageTag: d63357a0-41ce-4255-9a71-47ad781d1a8b
		summarizeBy: none
		sourceColumn: PracticeDescription

		annotation SummarizationSetBy = Automatic

	column EventCode
		dataType: string
		lineageTag: 351423a8-1224-4615-83e2-09f41f781192
		summarizeBy: none
		sourceColumn: EventCode

		annotation SummarizationSetBy = Automatic

	column SnomedCode
		dataType: string
		lineageTag: 73a157fd-8986-4371-b2a1-c2005764f93a
		summarizeBy: none
		sourceColumn: SnomedCode

		annotation SummarizationSetBy = Automatic

	column SnomedCodeDescription
		dataType: string
		lineageTag: 79fbf750-c21b-4c92-9a83-5d86984a8f17
		summarizeBy: none
		sourceColumn: SnomedCodeDescription

		annotation SummarizationSetBy = Automatic

	column Age_at_Event
		dataType: int64
		formatString: 0
		lineageTag: 8066025f-3cbe-4ae8-aa19-ae9582f96950
		summarizeBy: sum
		sourceColumn: Age_at_Event

		annotation SummarizationSetBy = Automatic

	column Age_Event_2cats
		dataType: string
		lineageTag: 7b70c093-1f5d-4052-bb36-02ab9e9ee040
		summarizeBy: none
		sourceColumn: Age_Event_2cats

		annotation SummarizationSetBy = Automatic

	column Age_Event_3cats
		dataType: string
		lineageTag: 464fe3e8-4fc7-4428-98e3-f454fc60786f
		summarizeBy: none
		sourceColumn: Age_Event_3cats

		annotation SummarizationSetBy = Automatic

	column SourceSystem
		dataType: string
		lineageTag: 57946d04-75a9-4d3e-b08c-3f44f4db3d8c
		summarizeBy: none
		sourceColumn: SourceSystem

		annotation SummarizationSetBy = Automatic

	column Event_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1f59c2e5-9603-4857-bb5d-deed493091b3
		summarizeBy: none
		sourceColumn: Event_Date

		variation Variation
			isDefault
			relationship: e9975721-c9c2-4945-b86b-a6376bbf45fe
			defaultHierarchy: LocalDateTable_328df00c-9a33-4a8f-a6bf-6ebcb762193d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 03e30935-d9ee-45a9-9dc1-b5f7bc0a7436
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column Fin_Quarter_Name
		dataType: string
		lineageTag: c2400afd-5585-44bf-8571-1bb97818f7e0
		summarizeBy: none
		sourceColumn: Fin_Quarter_Name

		annotation SummarizationSetBy = Automatic

	column Quarter_FinYr
		dataType: string
		lineageTag: aa6674af-0cc8-4259-bf8c-a6b5395dd9a3
		summarizeBy: none
		sourceColumn: Quarter_FinYr

		annotation SummarizationSetBy = Automatic

	column Year_Month_Event
		dataType: string
		lineageTag: 65196535-9d2f-4021-ba17-1b45c7764d5e
		summarizeBy: none
		sourceColumn: Year_Month_Event

		annotation SummarizationSetBy = Automatic

	column Month_Name
		dataType: string
		lineageTag: 23859535-3f35-4f9e-9a38-d0d8e3eacdc4
		summarizeBy: none
		sourceColumn: Month_Name

		annotation SummarizationSetBy = Automatic

	column Fin_Week
		dataType: string
		lineageTag: a3acdb3b-7964-42b1-9d15-c390dad33734
		summarizeBy: none
		sourceColumn: Fin_Week

		annotation SummarizationSetBy = Automatic

	column 'First HAP in FinYr'
		dataType: int64
		formatString: 0
		lineageTag: bf86d1dc-0c50-4ed5-aba1-67d3195fff88
		summarizeBy: sum
		sourceColumn: First HAP in FinYr

		annotation SummarizationSetBy = Automatic

	column Counter_Event
		dataType: int64
		formatString: 0
		lineageTag: 6c91b75b-1198-4140-8738-a6f1274c2313
		summarizeBy: sum
		sourceColumn: Counter_Event

		annotation SummarizationSetBy = Automatic

	column Distinct_Events
		dataType: int64
		formatString: 0
		lineageTag: 9a69ae07-0746-432d-bfec-b6e1a150d75c
		summarizeBy: sum
		sourceColumn: Distinct_Events

		annotation SummarizationSetBy = Automatic

	partition HAP = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select census_date as ""census_Date"", census_financial_year as ""Census_Financial_Year"", census_month_name as ""Census_Month_Name"", derived_nhs_number as ""Derived_NHS_Number"", gender as ""Gender"", ethnic_origin_grouped as ""Ethnic Origin Grouped"", ethnic_origin_wider_groups as ""Ethnic Origin Wider Groups"", locality as ""Locality"", primarycarenetwork as ""PrimaryCareNetwork"", imdcountydecile as ""IMDcountyDecile"", efi_category, autism_flag as ""Autism_Flag"", ld_flag as ""LD_Flag"", adhd_flag as ""ADHD_Flag"", ld_autism_flag as ""LD_Autism_Flag"", counter_cohort as ""Counter_Cohort"", id as ""ID"", pseudonhsnumber as ""PseudoNHSNumber"", practicecode as ""PracticeCode"", practicedescription as ""PracticeDescription"", eventcode as ""EventCode"", snomedcode as ""SnomedCode"", snomedcodedescription as ""SnomedCodeDescription"", age_at_event as ""Age_at_Event"", age_event_2cats as ""Age_Event_2cats"", age_event_3cats as ""Age_Event_3cats"", sourcesystem as ""SourceSystem"", event_date as ""Event_Date"", financialyear as ""FinancialYear"", fin_quarter_name as ""Fin_Quarter_Name"", quarter_finyr as ""Quarter_FinYr"", year_month as ""Year-Month"", month_name as ""Month_Name"", fin_week as ""Fin_Week"", first_hap_in_finyr as ""First HAP in FinYr"", counter_event as ""Counter_Event"", distinct_events as ""Distinct_Events"" from data_mart_powerbi_ldanda.tbl03_ld_hap", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Year-Month", "Year_Month_Event"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

