table 'IP and Daycases - over time'
	lineageTag: b3544665-285c-4745-938f-93541ac6b376

	column Derived_NHS_Number
		dataType: string
		lineageTag: 31e18f93-002b-49cb-89f6-ffbe43237934
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Census_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9e3e7065-ecce-402b-98bb-f7f25811b4e8
		summarizeBy: none
		sourceColumn: Census_date

		variation Variation
			isDefault
			relationship: d501700b-a43b-471c-be42-a59bfb14656c
			defaultHierarchy: LocalDateTable_bcaab5c8-8e44-45f9-9aa4-5313dde49611.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 7686b4e4-25c8-44a5-bd0e-7030fac36eba
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: dfebc18b-b8ee-452b-8524-6e030a715f23
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 8d471147-bb61-47e4-b8f3-79ef4d560828
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Condition_Category
		dataType: string
		lineageTag: a088dea1-b368-40b7-bf49-a6a78d005245
		summarizeBy: none
		sourceColumn: Condition_Category

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: 5286894e-721e-49ac-b42c-f32669f602de
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 8a33e7d3-9c4f-4fa7-8970-be2d4521c020
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column Counter_Cohort
		dataType: int64
		formatString: 0
		lineageTag: c6fd023a-f5ca-4e6f-a756-93c4c326b9a0
		summarizeBy: sum
		sourceColumn: Counter_Cohort

		annotation SummarizationSetBy = Automatic

	column Age_at_Activity
		dataType: int64
		formatString: 0
		lineageTag: c84f1a49-9ee8-4d7b-b715-fa5c9130f15e
		summarizeBy: sum
		sourceColumn: Age_at_Activity

		annotation SummarizationSetBy = Automatic

	column Age_Event_2cats
		dataType: string
		lineageTag: f574adda-8648-4150-af98-1143c719e8b0
		summarizeBy: none
		sourceColumn: Age_Event_2cats

		annotation SummarizationSetBy = Automatic

	column Age_Event_3cats
		dataType: string
		lineageTag: 27c4e35c-baef-4a89-accd-b816d69ca1c7
		summarizeBy: none
		sourceColumn: Age_Event_3cats

		annotation SummarizationSetBy = Automatic

	column 5yr_Ageband_IP_Activity
		dataType: string
		lineageTag: a824bc2e-66d4-49e9-a308-ea64f93272d6
		summarizeBy: none
		sourceColumn: 5yr_Ageband_IP_Activity

		annotation SummarizationSetBy = Automatic

	column 10yr_age_band_at_Activity
		dataType: string
		lineageTag: a650b1ca-4a3c-4ea6-bebc-9466900b196e
		summarizeBy: none
		sourceColumn: 10yr_age_band_at_Activity

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 8e6f8767-9667-48b9-9d26-de23fa9933bb
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column efi_category
		dataType: string
		lineageTag: 9dd57b61-bc97-4915-b34a-d841bd8af207
		summarizeBy: none
		sourceColumn: efi_category

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: e080100f-21b0-476c-b166-6ec5d07c4c02
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: 6458df8f-e1a8-4b85-99d3-811821e061a6
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column Primary_Care_Network
		dataType: string
		lineageTag: 6df679b0-361e-419f-a9da-1a168ad9a24b
		summarizeBy: none
		sourceColumn: Primary_Care_Network

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: b1b93429-471a-4a53-bf86-38ef98e6f961
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column LSOA
		dataType: string
		lineageTag: da5f725e-cdfd-45ca-af1b-6caade493586
		summarizeBy: none
		sourceColumn: LSOA

		annotation SummarizationSetBy = Automatic

	column Commissioner_Code
		dataType: string
		lineageTag: d8a1efb9-ede7-4f17-adbc-b08ffac25db5
		summarizeBy: none
		sourceColumn: Commissioner_Code

		annotation SummarizationSetBy = Automatic

	column Commissioner_Group
		dataType: string
		lineageTag: ffc4a9f8-9731-4bfc-a4ba-221ea8370349
		summarizeBy: none
		sourceColumn: Commissioner_Group

		annotation SummarizationSetBy = Automatic

	column Financial_Year_Activity
		dataType: string
		lineageTag: 9c8bd983-0e29-446c-8c78-4bd04a8f333c
		summarizeBy: none
		sourceColumn: Financial_Year_Activity

		annotation SummarizationSetBy = Automatic

	column Month_Name_Activity
		dataType: string
		lineageTag: ef889da2-431f-44d8-8b2f-dc8b8befa155
		summarizeBy: none
		sourceColumn: Month_Name_Activity

		annotation SummarizationSetBy = Automatic

	column Year_Month_Activity
		dataType: int64
		formatString: 0
		lineageTag: 9927cc3f-d3cb-4444-9290-cbd1bd20b6e6
		summarizeBy: sum
		sourceColumn: Year_Month_Activity

		annotation SummarizationSetBy = Automatic

	column Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: d4fbcab3-bbd8-4d08-9286-9e4227127271
		summarizeBy: none
		sourceColumn: Start_Date

		annotation SummarizationSetBy = Automatic

	column Admission_Day
		dataType: string
		lineageTag: 828e1cda-22bd-4aa9-b0d7-08723aa28755
		summarizeBy: none
		sourceColumn: Admission_Day

		annotation SummarizationSetBy = Automatic

	column discharge_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 62c70498-e094-4ae4-9df5-c31e2af8ccf2
		summarizeBy: none
		sourceColumn: discharge_date

		variation Variation
			isDefault
			relationship: b7fd8500-c490-4280-b605-3900b9a1246d
			defaultHierarchy: LocalDateTable_6b62aa31-f0b5-4b57-b4d9-d37fca866760.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Short_Stay_0-1_day_flag
		dataType: int64
		formatString: 0
		lineageTag: ad4c9ba8-965e-4d1e-9d19-7cf8aedeb427
		summarizeBy: sum
		sourceColumn: Short_Stay_0-1_day_flag

		annotation SummarizationSetBy = Automatic

	column Short_Stay_72hr_flag
		dataType: int64
		formatString: 0
		lineageTag: 05bd4a96-380e-4a53-aeab-144a19b770d2
		summarizeBy: sum
		sourceColumn: Short_Stay_72hr_flag

		annotation SummarizationSetBy = Automatic

	column Long_Stay_28day+_flag
		dataType: int64
		formatString: 0
		lineageTag: 6d5d131d-e14e-4a3a-9880-b32f5842ee3f
		summarizeBy: sum
		sourceColumn: Long_Stay_28day+_flag

		annotation SummarizationSetBy = Automatic

	column LoS_Bands
		dataType: string
		lineageTag: 05626347-2fd0-4b49-9bbe-6e7e4bcb2e5d
		summarizeBy: none
		sourceColumn: LoS_Bands

		annotation SummarizationSetBy = Automatic

	column LoS_Bands_Order
		dataType: int64
		formatString: 0
		lineageTag: 8133fd29-56c0-498d-8dc1-b41eda9df4fc
		summarizeBy: sum
		sourceColumn: LoS_Bands_Order

		annotation SummarizationSetBy = Automatic

	column Total_Bed_Days
		dataType: int64
		formatString: 0
		lineageTag: 9670a091-d068-4c84-9f93-9006c34e3cea
		summarizeBy: sum
		sourceColumn: Total_Bed_Days

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: 0513615e-9af0-4c6a-a872-3d5a46ea6bf7
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column Provider_Name
		dataType: string
		lineageTag: 8abca912-a4cc-4a70-b314-f14b26ed9303
		summarizeBy: none
		sourceColumn: Provider_Name

		annotation SummarizationSetBy = Automatic

	column Site_Name
		dataType: string
		lineageTag: 0bc0eddd-a829-4ee5-911d-e26a70ec46b3
		summarizeBy: none
		sourceColumn: Site_Name

		annotation SummarizationSetBy = Automatic

	column Treatment_Function_Description
		dataType: string
		lineageTag: 4e6fe0fe-c1f6-485c-85cd-dfd55cdd9e1a
		summarizeBy: none
		sourceColumn: Treatment_Function_Description

		annotation SummarizationSetBy = Automatic

	column ICD10_description
		dataType: string
		lineageTag: 9ef0bf37-09fe-4246-9191-bc054f7eafb0
		summarizeBy: none
		sourceColumn: ICD10_description

		annotation SummarizationSetBy = Automatic

	column ICD10_subchapter
		dataType: string
		lineageTag: cfd95938-e1e9-4c63-80cd-d257cfde0f82
		summarizeBy: none
		sourceColumn: ICD10_subchapter

		annotation SummarizationSetBy = Automatic

	column Admission_Method
		dataType: string
		lineageTag: 69a5115e-7e1a-439a-a8a6-c76678e2a2e4
		summarizeBy: none
		sourceColumn: Admission_Method

		annotation SummarizationSetBy = Automatic

	column Admission_Method_Group
		dataType: string
		lineageTag: 47ac6e79-df43-40df-aa8d-50591202a555
		summarizeBy: none
		sourceColumn: Admission_Method_Group

		annotation SummarizationSetBy = Automatic

	column Admission_Method_Group_Grouped
		dataType: string
		lineageTag: 6b201e4a-c0ee-493b-851e-b213aac9d2e3
		summarizeBy: none
		sourceColumn: Admission_Method_Group_Grouped

		annotation SummarizationSetBy = Automatic

	column Patient_Classification
		dataType: string
		lineageTag: 011e1bf6-9f02-4455-a674-e9f65416ed59
		summarizeBy: none
		sourceColumn: Patient_Classification

		annotation SummarizationSetBy = Automatic

	column Elective_flag
		dataType: int64
		formatString: 0
		lineageTag: a3c7117f-583a-4efb-ae6d-4758ce752aad
		summarizeBy: sum
		sourceColumn: Elective_flag

		annotation SummarizationSetBy = Automatic

	column Non_Elective_flag
		dataType: int64
		formatString: 0
		lineageTag: 07a087c3-5792-45a4-8976-ac0f907aebf9
		summarizeBy: sum
		sourceColumn: Non_Elective_flag

		annotation SummarizationSetBy = Automatic

	column Emergency_Admission_flag
		dataType: int64
		formatString: 0
		lineageTag: bba21111-6fbe-492c-b27c-71922b564485
		summarizeBy: sum
		sourceColumn: Emergency_Admission_flag

		annotation SummarizationSetBy = Automatic

	column Assessment_flag
		dataType: int64
		formatString: 0
		lineageTag: 096f9d20-efa5-469b-9786-2ef392f5d1cc
		summarizeBy: sum
		sourceColumn: Assessment_flag

		annotation SummarizationSetBy = Automatic

	column SDEC_flag
		dataType: string
		lineageTag: 9b23c3f1-9f7b-4089-ae29-a1c28cb2dccd
		summarizeBy: none
		sourceColumn: SDEC_flag

		annotation SummarizationSetBy = Automatic

	column MH_Related_Admission
		dataType: int64
		formatString: 0
		lineageTag: 9bf8fc33-ceab-4714-bc0a-47c0a92a8516
		summarizeBy: sum
		sourceColumn: MH_Related_Admission

		annotation SummarizationSetBy = Automatic

	column MH_Substance_Misuse_Admission
		dataType: int64
		formatString: 0
		lineageTag: 9280f4dd-1c47-49e6-9c1a-7f3ff3bbf8c8
		summarizeBy: sum
		sourceColumn: MH_Substance_Misuse_Admission

		annotation SummarizationSetBy = Automatic

	column MH_Related_Eating_Disorders_Admission
		dataType: int64
		formatString: 0
		lineageTag: 8e4269d5-c848-4d04-9cec-410770ee61a8
		summarizeBy: sum
		sourceColumn: MH_Related_Eating_Disorders_Admission

		annotation SummarizationSetBy = Automatic

	column Counter_Event
		dataType: int64
		formatString: 0
		lineageTag: b6af9d0c-69ca-4e80-a50e-d8fe7ada9daa
		summarizeBy: sum
		sourceColumn: Counter_Event

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Activity'
		dataType: string
		lineageTag: cdb3a61b-88ec-4c57-bdd2-76c0fc43c30e
		summarizeBy: none
		sourceColumn: Year-Month of Activity

		annotation SummarizationSetBy = Automatic

	partition 'IP and Daycases - over time' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select derived_nhs_number as ""Derived_NHS_Number"", census_date as ""Census_date"", ld_flag as ""LD_Flag"", autism_flag as ""Autism_Flag"", ld_autism_flag as ""LD_Autism_Flag"", condition_category as ""Condition_Category"", ethnic_origin_grouped as ""Ethnic Origin Grouped"", ethnic_origin_wider_groups as ""Ethnic Origin Wider Groups"", counter_cohort as ""Counter_Cohort"", age_at_activity as ""Age_at_Activity"", age_event_2cats as ""Age_Event_2cats"", age_event_3cats as ""Age_Event_3cats"", ""5yr_ageband_ip_activity"" as ""5yr_Ageband_IP_Activity"", ""10yr_age_band_at_activity"" as ""10yr_age_band_at_Activity"", gender, efi_category, practice_code, practice_name, primary_care_network, locality, lsoa, commissioner_code, commissioner_group, financial_year_activity as ""Financial_Year_Activity"", month_name_activity as ""Month_Name_Activity"", year_month_activity as ""Year_Month_Activity"", start_date, admission_day, discharge_date, short_stay_0_1_day_flag as ""short_stay_0-1_day_flag"", short_stay_72hr_flag, long_stay_28day_flag as ""long_stay_28day+_flag"", los_bands as ""LoS_Bands"", los_bands_order as ""LoS_Bands_Order"", total_bed_days, provider_code, provider_name, site_name, treatment_function_description, icd10_description as ""ICD10_description"", icd10_subchapter as ""ICD10_subchapter"", admission_method, admission_method_group, admission_method_group_grouped, patient_classification, elective_flag, non_elective_flag, emergency_admission_flag as ""Emergency_Admission_flag"", assessment_flag, sdec_flag, mh_related_admission as ""MH_Related_Admission"", mh_substance_misuse_admission as ""MH_Substance_Misuse_Admission"", mh_related_eating_disorders_admission as ""MH_Related_Eating_Disorders_Admission"", counter_event as ""Counter_Event"" from data_mart_powerbi_ldanda.tbl04_lda_ip_ot", null, [EnableFolding=true]),
				    #"Year-Month in correct format" = Table.AddColumn(Source, "Custom", each Text.Combine({Text.Start(Text.From([Year_Month_Activity], "en-GB"), 4), "-", Text.Middle(Text.From([Year_Month_Activity], "en-GB"), 4)}), type text),
				    #"Year-Month of Activity" = Table.RenameColumns(#"Year-Month in correct format",{{"Custom", "Year-Month of Activity"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Year-Month of Activity","7-14 Days","07-14 Days",Replacer.ReplaceText,{"LoS_Bands"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","0-1 Days","0-01 Days",Replacer.ReplaceText,{"LoS_Bands"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","1-3 Days","01-03 Days",Replacer.ReplaceText,{"LoS_Bands"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","3-7 Days","03-07 Days",Replacer.ReplaceText,{"LoS_Bands"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value3", each true),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"gender", "Gender"}, {"practice_code", "Practice_Code"}, {"practice_name", "Practice_Name"}, {"primary_care_network", "Primary_Care_Network"}, {"locality", "Locality"}, {"lsoa", "LSOA"}, {"commissioner_code", "Commissioner_Code"}, {"commissioner_group", "Commissioner_Group"}, {"start_date", "Start_Date"}, {"admission_day", "Admission_Day"}, {"short_stay_0-1_day_flag", "Short_Stay_0-1_day_flag"}, {"short_stay_72hr_flag", "Short_Stay_72hr_flag"}, {"long_stay_28day+_flag", "Long_Stay_28day+_flag"}, {"total_bed_days", "Total_Bed_Days"}, {"provider_name", "Provider_Name"}, {"site_name", "Site_Name"}, {"treatment_function_description", "Treatment_Function_Description"}, {"admission_method", "Admission_Method"}, {"admission_method_group", "Admission_Method_Group"}, {"admission_method_group_grouped", "Admission_Method_Group_Grouped"}, {"patient_classification", "Patient_Classification"}, {"elective_flag", "Elective_flag"}, {"non_elective_flag", "Non_Elective_flag"}, {"assessment_flag", "Assessment_flag"}, {"sdec_flag", "SDEC_flag"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

