table 'Mat: Pregs_over time'
	lineageTag: 2a1f5740-35ee-447e-a33a-440057f50dfd

	measure '% Pregs / LD Cohort' =
			
			DIVIDE(
				SUM('Mat: Pregs_over time'[Counter_Pregs]),
				SUM('Mat: Pregs_over time'[Counter_Cohort])
			)
		formatString: 0
		lineageTag: 53a42d2b-6c35-4432-aae1-792005dc7e70

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Rate Pregs / LD Cohort' =
			
			DIVIDE(
				SUM('Mat: Pregs_over time'[Counter_Pregs]),
				SUM('Mat: Pregs_over time'[Counter_Cohort])
			)*1000
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f351e241-94fc-40e0-b86e-04df6bec1c52

	column Census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 05ce9ca4-d02f-41b0-932e-eabd99795cfe
		summarizeBy: none
		sourceColumn: Census_Date

		annotation SummarizationSetBy = Automatic

	column Census_Financial_Year
		dataType: string
		lineageTag: bf6096f6-a8f5-494c-a53f-78e714f1c24b
		summarizeBy: none
		sourceColumn: Census_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Census_Month_Name
		dataType: string
		lineageTag: e3f31bc1-93a8-4bc8-8402-5647315b7d96
		summarizeBy: none
		sourceColumn: Census_Month_Name

		annotation SummarizationSetBy = Automatic

	column Derived_NHS_Number
		dataType: string
		lineageTag: 1f0f6d2c-d6b0-4377-be0b-fa0531784b49
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: e8d80df4-f640-4bdd-9440-cff644a453cb
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: 30ab64ca-7e01-49f8-b250-602b5b032a22
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 878060b6-8c04-481e-b4b3-a709da643f77
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 722bbf65-1d21-418a-bb83-cdf3b8c042bd
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 96f69b8c-0335-4fdc-a74e-12ad6a0d87d4
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: a6113ee7-9a30-4530-b3d3-35a046b19f50
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 106328f6-bbe6-4d4c-a647-98f98b2a8ffb
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9e4a5c51-9b7d-4485-94ab-aca6086023b3
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: fbdb5c6f-0b1b-4262-9fa1-325ce3c876ef
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: d5f7c12a-97d5-49cc-82f7-aa3060419589
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Counter_Cohort
		dataType: int64
		formatString: 0
		lineageTag: 8f6097d2-2d58-43c4-af14-fbf84335635b
		summarizeBy: sum
		sourceColumn: Counter_Cohort

		annotation SummarizationSetBy = Automatic

	column MotherNHSNo
		dataType: string
		lineageTag: 7a2b0274-0871-4c7c-a275-a8ab3a0db628
		summarizeBy: none
		sourceColumn: MotherNHSNo

		annotation SummarizationSetBy = Automatic

	column Antenatal_App_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dcd873e1-94ed-463e-9897-d32ca0b3c769
		summarizeBy: none
		sourceColumn: Antenatal_App_Date

		variation Variation
			isDefault
			relationship: de1fca2f-c205-4e89-ae07-98af5f3db511
			defaultHierarchy: LocalDateTable_27d2fc7f-cd22-41cf-8920-e17da07ecf7a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FinYr_Antental_App_Date
		dataType: string
		lineageTag: 38806960-7243-4c11-ae4c-a39d7472d43f
		summarizeBy: none
		sourceColumn: FinYr_Antental_App_Date

		annotation SummarizationSetBy = Automatic

	column YearMonth_Antenatal_AppDate
		dataType: string
		lineageTag: c7036993-758f-4420-be05-5527cf8f2546
		summarizeBy: none
		sourceColumn: YearMonth_Antenatal_AppDate

		annotation SummarizationSetBy = Automatic

	column Counter_Pregs
		dataType: int64
		formatString: 0
		lineageTag: 2878207f-843a-4d19-8cfe-d78e4a427c3d
		summarizeBy: sum
		sourceColumn: Counter_Pregs

		annotation SummarizationSetBy = Automatic

	column Age_At_Booking_Mother
		dataType: int64
		formatString: 0
		lineageTag: 9688e120-cc24-418a-b585-ac2ff149f5bf
		summarizeBy: sum
		sourceColumn: Age_At_Booking_Mother

		annotation SummarizationSetBy = Automatic

	column Age_At_Booking_Mother_AgeBand5yr
		dataType: string
		lineageTag: bfa7e42f-8ce3-45a6-a8e5-3afd21d55206
		summarizeBy: none
		sourceColumn: Age_At_Booking_Mother_AgeBand5yr

		annotation SummarizationSetBy = Automatic

	column Age_Event_2cats
		dataType: string
		lineageTag: 65774c54-0c57-43e5-84e8-9d4f0b60b5d1
		summarizeBy: none
		sourceColumn: Age_Event_2cats

		annotation SummarizationSetBy = Automatic

	column Age_Event_3cats
		dataType: string
		lineageTag: 5f7d26f3-ec04-4484-8127-e8638fb48677
		summarizeBy: none
		sourceColumn: Age_Event_3cats

		annotation SummarizationSetBy = Automatic

	column Folic_Acid_Supplement_Desc
		dataType: string
		lineageTag: b7279803-4d41-4a83-9d3b-20f2358ec8d7
		summarizeBy: none
		sourceColumn: Folic_Acid_Supplement_Desc

		annotation SummarizationSetBy = Automatic

	column 'Late_Booking_>_84 Day_Flag'
		dataType: int64
		formatString: 0
		lineageTag: 78bb2e51-a665-45f0-946a-63227615710d
		summarizeBy: sum
		sourceColumn: Late_Booking_>_84 Day_Flag

		annotation SummarizationSetBy = Automatic

	column 'Late_Booking_>_70 Day_Flag'
		dataType: int64
		formatString: 0
		lineageTag: 7bb4ffc5-39d7-4da2-b79b-2de0c779e7ba
		summarizeBy: sum
		sourceColumn: Late_Booking_>_70 Day_Flag

		annotation SummarizationSetBy = Automatic

	column Previous_Casesareans_Number
		dataType: int64
		formatString: 0
		lineageTag: b74b9b97-e09c-4b3e-913a-252e0c2355bc
		summarizeBy: sum
		sourceColumn: Previous_Casesareans_Number

		annotation SummarizationSetBy = Automatic

	column Previous_Live_Births_Number
		dataType: int64
		formatString: 0
		lineageTag: 4f24837c-550d-4fb3-8141-8f50f3c88c4a
		summarizeBy: sum
		sourceColumn: Previous_Live_Births_Number

		annotation SummarizationSetBy = Automatic

	column Previous_Still_Births
		dataType: int64
		formatString: 0
		lineageTag: 619f83e2-4338-4135-9d3d-68fdd37ef81a
		summarizeBy: sum
		sourceColumn: Previous_Still_Births

		annotation SummarizationSetBy = Automatic

	column 'Gestation_Length_Target_Zones Week+Days'
		dataType: string
		lineageTag: 81ccaf30-54ac-4ce4-ba17-e174db374abb
		summarizeBy: none
		sourceColumn: Gestation_Length_Target_Zones Week+Days

		annotation SummarizationSetBy = Automatic

	column Gestation_Age_at_Appt_Group
		dataType: string
		lineageTag: 4a686e39-49f7-4d92-8122-0f9d06df0809
		summarizeBy: none
		sourceColumn: Gestation_Age_at_Appt_Group

		annotation SummarizationSetBy = Automatic

	column Condition_Category
		dataType: string
		lineageTag: 939aa2ea-4762-43a6-97ba-a8b93398c408
		summarizeBy: none
		sourceColumn: Condition_Category

		annotation SummarizationSetBy = Automatic

	partition 'Mat: Pregs_over time' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select census_date as ""Census_Date"", census_financial_year as ""Census_Financial_Year"", census_month_name as ""Census_Month_Name"", derived_nhs_number as ""Derived_NHS_Number"", practice_code as ""Practice_Code"", practice_name as ""Practice_Name"", primarycarenetwork as ""PrimaryCareNetwork"", locality as ""Locality"", ethnic_origin_wider_groups as ""Ethnic Origin Wider Groups"", ethnic_origin_grouped as ""Ethnic Origin Grouped"", imdcountydecile as ""IMDcountyDecile"", ld_flag as ""LD_Flag"", autism_flag as ""Autism_Flag"", ld_autism_flag as ""LD_Autism_Flag"", condition_category as ""Condition_Category"", counter_cohort as ""Counter_Cohort"", mothernhsno as ""MotherNHSNo"", antenatal_app_date as ""Antenatal_App_Date"", finyr_antental_app_date as ""FinYr_Antental_App_Date"", yearmonth_antenatal_appdate as ""YearMonth_Antenatal_AppDate"", counter_pregs as ""Counter_Pregs"", age_at_booking_mother as ""Age_At_Booking_Mother"", age_at_booking_mother_ageband5yr as ""Age_At_Booking_Mother_AgeBand5yr"", age_event_2cats as ""Age_Event_2cats"", age_event_3cats as ""Age_Event_3cats"", folic_acid_supplement_desc as ""Folic_Acid_Supplement_Desc"", late_booking_84_day_flag as ""Late_Booking_>_84 Day_Flag"", late_booking_70_day_flag as ""Late_Booking_>_70 Day_Flag"", previous_casesareans_number as ""Previous_Casesareans_Number"", previous_live_births_number as ""Previous_Live_Births_Number"", previous_still_births as ""Previous_Still_Births"", gestation_length_target_zones_week_days as ""Gestation_Length_Target_Zones Week+Days"", gestation_age_at_appt_group as ""Gestation_Age_at_Appt_Group"" from data_mart_powerbi_ldanda.tbl07_lda_pregnancy_ot", null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Antenatal_App_Date", type date}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"YearMonth_Antenatal_AppDate", Order.Descending}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Sorted Rows",{{"Practice_Name", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

