table 'Mat: Dels_Births_over time'
	lineageTag: 6437141e-c9bc-4747-b484-68382c3576b4

	column Census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0cf63c64-34d2-42e7-8034-2405d97340b3
		summarizeBy: none
		sourceColumn: Census_Date

		variation Variation
			isDefault
			relationship: 4f1e41d7-0853-4880-9499-2d44cefd16e8
			defaultHierarchy: LocalDateTable_209539b6-53ec-4174-97f2-9d399406d2e0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Census_Financial_Year
		dataType: string
		lineageTag: f6bc7626-a713-4bb2-9b9e-23c0bf5319d8
		summarizeBy: none
		sourceColumn: Census_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Census_Month_Name
		dataType: string
		lineageTag: f7fbc4b6-b2ec-44b7-8221-e7cd43590e39
		summarizeBy: none
		sourceColumn: Census_Month_Name

		annotation SummarizationSetBy = Automatic

	column Derived_NHS_Number
		dataType: string
		lineageTag: 9379b6c1-df99-449f-a2ec-3235f27e803b
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Practice_Code
		dataType: string
		lineageTag: 74b37315-321f-41a5-b1fd-1d862f7b2bcc
		summarizeBy: none
		sourceColumn: Practice_Code

		annotation SummarizationSetBy = Automatic

	column Practice_Name
		dataType: string
		lineageTag: 6d7338f7-fd1d-405d-831e-6188a48661ff
		summarizeBy: none
		sourceColumn: Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 76a686db-46ab-4fa9-900d-108c4f8b190b
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 7e6a361d-2a5f-4859-b4f7-9709e291f4a1
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Wider Groups'
		dataType: string
		lineageTag: 3fe35877-470e-4ae5-84de-110263f0996e
		summarizeBy: none
		sourceColumn: Ethnic Origin Wider Groups

		annotation SummarizationSetBy = Automatic

	column 'Ethnic Origin Grouped'
		dataType: string
		lineageTag: d5cc3773-f3df-45c3-bdf3-7d960d52c887
		summarizeBy: none
		sourceColumn: Ethnic Origin Grouped

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: bce35780-1653-4cd1-ac97-18430099c416
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 849583d0-d806-4ae9-b74f-fcd97343bd52
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: d5936b28-f95c-49fc-be32-e8b04e90b720
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2fefa106-8a0d-4c18-9c98-2bebc15ea231
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Counter_Cohort
		dataType: int64
		formatString: 0
		lineageTag: d49ac032-da5b-4b42-ad4e-271c4ac1bbba
		summarizeBy: sum
		sourceColumn: Counter_Cohort

		annotation SummarizationSetBy = Automatic

	column MotherNHSNo
		dataType: string
		lineageTag: 41ec2ddc-470e-41a8-ab6e-8666022618d8
		summarizeBy: none
		sourceColumn: MotherNHSNo

		annotation SummarizationSetBy = Automatic

	column Lab_Caesar_Onset_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1364f86b-a679-4af8-8dbf-9f466acceb86
		summarizeBy: none
		sourceColumn: Lab_Caesar_Onset_Date

		variation Variation
			isDefault
			relationship: f54776ca-5539-4d77-82b7-0287ea1c29da
			defaultHierarchy: LocalDateTable_a8d23a92-6746-4d6e-877e-fe83ffd89ccd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Lab_Caesar_Onset_FinYr
		dataType: string
		lineageTag: 1ccca0f5-3c33-4d2a-be53-2258bd13e2b9
		summarizeBy: none
		sourceColumn: Lab_Caesar_Onset_FinYr

		annotation SummarizationSetBy = Automatic

	column Lab_Caesar_Onset_YM
		dataType: string
		lineageTag: d96af029-11cf-48aa-811e-8cc45f4d1fec
		summarizeBy: none
		sourceColumn: Lab_Caesar_Onset_YM

		annotation SummarizationSetBy = Automatic

	column Counter_Delivery_Flag
		dataType: int64
		formatString: 0
		lineageTag: f05b4e1c-44b5-4762-8bda-f69034be4c7e
		summarizeBy: sum
		sourceColumn: Counter_Delivery_Flag

		annotation SummarizationSetBy = Automatic

	column Age_At_Delivery_Mother
		dataType: int64
		formatString: 0
		lineageTag: 0c7897a0-c8fd-4fa1-9644-2e33c3724b9e
		summarizeBy: sum
		sourceColumn: Age_At_Delivery_Mother

		annotation SummarizationSetBy = Automatic

	column Age_at_Delivery_AgeBand5yr
		dataType: string
		lineageTag: 17a23660-92ff-4e6d-a91a-5e2c3ffc46da
		summarizeBy: none
		sourceColumn: Age_at_Delivery_AgeBand5yr

		annotation SummarizationSetBy = Automatic

	column Age_Event_2cats
		dataType: string
		lineageTag: 45a46e4c-9214-4c06-8aa1-00c042c843ea
		summarizeBy: none
		sourceColumn: Age_Event_2cats

		annotation SummarizationSetBy = Automatic

	column Age_Event_3cats
		dataType: string
		lineageTag: 3377d9b3-6f8c-4cf0-a693-9290ddeb1d51
		summarizeBy: none
		sourceColumn: Age_Event_3cats

		annotation SummarizationSetBy = Automatic

	column Admission_Method_Hospital_Provider_Spell_Desc
		dataType: string
		lineageTag: b93050e2-e342-438f-a6f1-e639f32f5f55
		summarizeBy: none
		sourceColumn: Admission_Method_Hospital_Provider_Spell_Desc

		annotation SummarizationSetBy = Automatic

	column Labour_Onset_Method_Desc
		dataType: string
		lineageTag: 98ed62c4-f3a2-4aa1-a79d-3160bdcd9f4c
		summarizeBy: none
		sourceColumn: Labour_Onset_Method_Desc

		annotation SummarizationSetBy = Automatic

	column Org_Site_Actual_Delivery_Desc_plus
		dataType: string
		lineageTag: d7f79632-76f0-424d-96de-759156a3812a
		summarizeBy: none
		sourceColumn: Org_Site_Actual_Delivery_Desc_plus

		annotation SummarizationSetBy = Automatic

	column Delivery_County_Group
		dataType: string
		lineageTag: bdafe550-a11e-4741-8b1e-91a0c5132e14
		summarizeBy: none
		sourceColumn: Delivery_County_Group

		annotation SummarizationSetBy = Automatic

	column Counter_Babies_per_delivery
		dataType: int64
		formatString: 0
		lineageTag: 5067a1f9-2509-4b5b-ae60-98dd6302bb4e
		summarizeBy: sum
		sourceColumn: Counter_Babies_per_delivery

		annotation SummarizationSetBy = Automatic

	column Pregnancy_Outcome_Desc
		dataType: string
		lineageTag: f0e1170d-baa4-4384-8080-04ea5d59ab83
		summarizeBy: none
		sourceColumn: Pregnancy_Outcome_Desc

		annotation SummarizationSetBy = Automatic

	column Condition_Category
		dataType: string
		lineageTag: fad5813c-95cc-419e-8a76-b428b785a3b9
		summarizeBy: none
		sourceColumn: Condition_Category

		annotation SummarizationSetBy = Automatic

	partition 'Mat: Dels_Births_over time' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select census_date as ""Census_Date"", census_financial_year as ""Census_Financial_Year"", census_month_name as ""Census_Month_Name"", derived_nhs_number as ""Derived_NHS_Number"", practice_code as ""Practice_Code"", practice_name as ""Practice_Name"", primarycarenetwork as ""PrimaryCareNetwork"", locality as ""Locality"", ethnic_origin_wider_groups as ""Ethnic Origin Wider Groups"", ethnic_origin_grouped as ""Ethnic Origin Grouped"", imdcountydecile as ""IMDcountyDecile"", ld_flag as ""LD_Flag"", autism_flag as ""Autism_Flag"", ld_autism_flag as ""LD_Autism_Flag"", condition_category as ""Condition_Category"", counter_cohort as ""Counter_Cohort"", mothernhsno as ""MotherNHSNo"", lab_caesar_onset_date as ""Lab_Caesar_Onset_Date"", lab_caesar_onset_finyr as ""Lab_Caesar_Onset_FinYr"", lab_caesar_onset_ym as ""Lab_Caesar_Onset_YM"", counter_delivery_flag as ""Counter_Delivery_Flag"", age_at_delivery_mother as ""Age_At_Delivery_Mother"", age_at_delivery_ageband5yr as ""Age_at_Delivery_AgeBand5yr"", age_event_2cats as ""Age_Event_2cats"", age_event_3cats as ""Age_Event_3cats"", admission_method_hospital_provider_spell_desc as ""Admission_Method_Hospital_Provider_Spell_Desc"", labour_onset_method_desc as ""Labour_Onset_Method_Desc"", org_site_actual_delivery_desc_plus as ""Org_Site_Actual_Delivery_Desc_plus"", delivery_county_group as ""Delivery_County_Group"", counter_babies_per_delivery as ""Counter_Babies_per_delivery"", pregnancy_outcome_desc as ""Pregnancy_Outcome_Desc"" from data_mart_powerbi_ldanda.tbl08_lda_del_births_ot", null, [EnableFolding=true]),
				    #"Sorted Rows" = Table.Sort(Source,{{"MotherNHSNo", Order.Descending}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Sorted Rows",{{"Practice_Name", Text.Proper, type text}, {"Org_Site_Actual_Delivery_Desc_plus", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

