table 'Mental Health: Current Cohort'
	lineageTag: f604aec4-aa3d-4666-995d-78afc5754bd5

	column Derived_NHS_Number
		dataType: string
		lineageTag: 58ef85ca-51d6-4641-a774-79afcc7e6e80
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Census_date
		dataType: dateTime
		formatString: General Date
		lineageTag: cb4716b0-582b-4f74-adc9-1cd73db43d5d
		summarizeBy: none
		sourceColumn: Census_date

		variation Variation
			isDefault
			relationship: 5fc828a8-0181-40f0-998d-05d3bd036b5b
			defaultHierarchy: LocalDateTable_535dc8a8-a78b-442e-ab1d-24a972285cc1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: 39935d0a-e104-4a16-b4e0-2e43a01bbfcd
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 765a8a00-1322-43e7-924e-2ea1195b2782
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 6e6f712b-9ec4-4f2a-b05d-2735ef27a7b3
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Condition_Category
		dataType: string
		lineageTag: 01b70309-3cfb-4e1d-9054-8dc4fb0f1788
		summarizeBy: none
		sourceColumn: Condition_Category

		annotation SummarizationSetBy = Automatic

	column nhsnumber
		dataType: string
		lineageTag: 65a52e61-e5cc-4eb2-b8ae-649ab54a616f
		summarizeBy: none
		sourceColumn: nhsnumber

		annotation SummarizationSetBy = Automatic

	column UniqServReqID
		dataType: string
		lineageTag: f35bf4b8-4f20-4ab3-9c21-f37e9813ccbf
		summarizeBy: none
		sourceColumn: UniqServReqID

		annotation SummarizationSetBy = Automatic

	column Commissioner_Code
		dataType: string
		lineageTag: c5ffd46c-ef37-40ec-81ce-9c9843c0a50a
		summarizeBy: none
		sourceColumn: Commissioner_Code

		annotation SummarizationSetBy = Automatic

	column Commissioner_Desc
		dataType: string
		lineageTag: 40a86481-230d-49fd-b9f2-ab9d7853c10e
		summarizeBy: none
		sourceColumn: Commissioner_Desc

		annotation SummarizationSetBy = Automatic

	column Provider_Code
		dataType: string
		lineageTag: fa3719fd-a173-46f6-a537-47e039eb5cc1
		summarizeBy: none
		sourceColumn: Provider_Code

		annotation SummarizationSetBy = Automatic

	column Provider_Desc
		dataType: string
		lineageTag: 137edce1-d1ec-4c66-b0c9-b6126236eced
		summarizeBy: none
		sourceColumn: Provider_Desc

		annotation SummarizationSetBy = Automatic

	column Referring_Org_Code
		dataType: string
		lineageTag: 93fd10c2-6546-4193-8215-f2234c8b4292
		summarizeBy: none
		sourceColumn: Referring_Org_Code

		annotation SummarizationSetBy = Automatic

	column Referring_Org_Desc
		dataType: string
		lineageTag: e2ecb6dd-9bdf-41d7-b4ce-c8db6d2378db
		summarizeBy: none
		sourceColumn: Referring_Org_Desc

		annotation SummarizationSetBy = Automatic

	column Age_at_Service_Referral_Received
		dataType: string
		lineageTag: 64826d2a-8e90-49a0-a46e-32360b8f6960
		summarizeBy: none
		sourceColumn: Age_at_Service_Referral_Received

		annotation SummarizationSetBy = Automatic

	column Age_Event_2cats
		dataType: string
		lineageTag: f97b50f0-5839-4cd4-9e71-6036d7fb03ea
		summarizeBy: none
		sourceColumn: Age_Event_2cats

		annotation SummarizationSetBy = Automatic

	column Age_Event_3cats
		dataType: string
		lineageTag: 458d56d6-fcbf-4d21-9d7a-17491c1feb5e
		summarizeBy: none
		sourceColumn: Age_Event_3cats

		annotation SummarizationSetBy = Automatic

	column Gender_Description
		dataType: string
		lineageTag: 42c66af4-4e6e-4a28-9a82-9cee5ee56004
		summarizeBy: none
		sourceColumn: Gender_Description

		annotation SummarizationSetBy = Automatic

	column Referral_Received_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f3b5e32-e781-4307-88c3-d239074a6ebb
		summarizeBy: none
		sourceColumn: Referral_Received_Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Referral_Received_Time
		dataType: string
		lineageTag: 874ea828-8843-4e26-8def-beae7e49c8d3
		summarizeBy: none
		sourceColumn: Referral_Received_Time

		annotation SummarizationSetBy = Automatic

	column Source_of_Referral_Description
		dataType: string
		lineageTag: 4b187a47-1b72-47fd-8c62-bc1cc078e7a7
		summarizeBy: none
		sourceColumn: Source_of_Referral_Description

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 67c97030-6400-4b8f-bb19-5fd269c44502
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Primary_Referral_Reason_Description
		dataType: string
		lineageTag: 322b5a25-a2d6-40c2-af70-3eab5b7d5747
		summarizeBy: none
		sourceColumn: Primary_Referral_Reason_Description

		annotation SummarizationSetBy = Automatic

	column Service_Discharge_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5d0c21f1-75a7-4776-bad1-9b7dcca64f32
		summarizeBy: none
		sourceColumn: Service_Discharge_Date

		variation Variation
			isDefault
			relationship: 06b98f3e-53c9-49d9-a3ac-7d733da5e3a9
			defaultHierarchy: LocalDateTable_3b4ce727-405c-4b7f-a7fa-601c2df0cfa2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Service_Discharge_Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 01a97341-2701-4e2b-8ed9-083174142c37
		summarizeBy: none
		sourceColumn: Service_Discharge_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Referred_to_Service_Code
		dataType: string
		lineageTag: 4068c7d9-42de-4767-8686-4378676ac422
		summarizeBy: none
		sourceColumn: Referred_to_Service_Code

		annotation SummarizationSetBy = Automatic

	column Referred_to_Service_Desc
		dataType: string
		lineageTag: d3df5220-43e4-4099-9c5f-99c86296e349
		summarizeBy: none
		sourceColumn: Referred_to_Service_Desc

		annotation SummarizationSetBy = Automatic

	column Referred_to_Service_Grouped
		dataType: string
		lineageTag: 6e0dcce3-2c7a-404b-b127-207c8bb07b9d
		summarizeBy: none
		sourceColumn: Referred_to_Service_Grouped

		annotation SummarizationSetBy = Automatic

	column Length_of_referral_days
		dataType: string
		lineageTag: e13675b8-57a3-4605-86a3-bf20e148c0cd
		summarizeBy: none
		sourceColumn: Length_of_referral_days

		annotation SummarizationSetBy = Automatic

	column Length_of_referral_days_banding
		dataType: string
		lineageTag: 9a906c25-db03-4537-9064-268473579f91
		summarizeBy: none
		sourceColumn: Length_of_referral_days_banding

		annotation SummarizationSetBy = Automatic

	column Counter_Refs
		dataType: int64
		formatString: #,0
		lineageTag: ac16ffe6-04db-4bd0-bcbf-ca7778045778
		summarizeBy: sum
		sourceColumn: Counter_Refs

		annotation SummarizationSetBy = Automatic

	column Number_of_Attended_Contacts
		dataType: int64
		formatString: 0
		lineageTag: f0824820-e085-4ade-9164-20bcf990a4ee
		summarizeBy: sum
		sourceColumn: Number_of_Attended_Contacts

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Commissioners_Grouped
		dataType: string
		lineageTag: 1b19d332-483e-4f92-97d7-b91c87b7b8be
		summarizeBy: none
		sourceColumn: Commissioners_Grouped

		annotation SummarizationSetBy = Automatic

	column 5yr_age_band_at_referral
		dataType: string
		lineageTag: 58f872b3-472b-4b48-b12d-5843c46248ff
		summarizeBy: none
		sourceColumn: 5yr_age_band_at_referral

		annotation SummarizationSetBy = Automatic

	column 10yr_age_band_at_referral
		dataType: string
		lineageTag: 8666efee-1002-4f6d-9c82-742f87fdd4d4
		summarizeBy: none
		sourceColumn: 10yr_age_band_at_referral

		annotation SummarizationSetBy = Automatic

	partition 'Mental Health: Current Cohort' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "PowerBI_Reporting", [Query="SELECT *#(lf)FROM [PowerBI_Reporting].[LDandA].[tbl10_LDA_MH_refs_cc]"]),
				    #"Caps Comm_Desc" = Table.TransformColumns(Source,{{"Commissioner_Desc", Text.Proper, type text}}),
				    #"Cape ICB_Comm_Desc" = Table.ReplaceValue(#"Caps Comm_Desc","Icb","ICB",Replacer.ReplaceText,{"Commissioner_Desc"}),
				    #"Caps ICB_Comm_Desc" = Table.ReplaceValue(#"Cape ICB_Comm_Desc","Nhs","NHS",Replacer.ReplaceText,{"Commissioner_Desc"}),
				    Caps_Prov_Desc = Table.TransformColumns(#"Caps ICB_Comm_Desc",{{"Provider_Desc", Text.Proper, type text}}),
				    Cape_ICB_Prov_Desc = Table.ReplaceValue(Caps_Prov_Desc,"Icb","ICB",Replacer.ReplaceText,{"Provider_Desc"}),
				    Caps_NHS_Prov_Desc = Table.ReplaceValue(Cape_ICB_Prov_Desc,"Nhs","NHS",Replacer.ReplaceText,{"Provider_Desc"}),
				    Caps_Ref_Org = Table.TransformColumns(Caps_NHS_Prov_Desc,{{"Referring_Org_Desc", Text.Proper, type text}}),
				    Caps_ICB_Ref_Org = Table.ReplaceValue(Caps_Ref_Org,"Icb","ICB",Replacer.ReplaceText,{"Referring_Org_Desc"}),
				    Caps_NHS_Ref_Org = Table.ReplaceValue(Caps_ICB_Ref_Org,"Nhs","NHS",Replacer.ReplaceText,{"Referring_Org_Desc"}),
				    #"Ageband 5-9 now 05-09" = Table.ReplaceValue(Caps_NHS_Ref_Org,"5-9","05-09",Replacer.ReplaceValue,{"5yr_age_band_at_referral"}),
				    #"Ageband 0-4 now 0-04" = Table.ReplaceValue(#"Ageband 5-9 now 05-09","0-4","0-04",Replacer.ReplaceValue,{"5yr_age_band_at_referral"}),
				    #"Replace null with Not specified in Gender" = Table.ReplaceValue(#"Ageband 0-4 now 0-04",null,"Not specified",Replacer.ReplaceValue,{"Gender_Description"}),
				    #"Replace null with Not Recorder in Ref Reason" = Table.ReplaceValue(#"Replace null with Not specified in Gender",null,"Not Recorded",Replacer.ReplaceValue,{"Primary_Referral_Reason_Description"})
				in
				    #"Replace null with Not Recorder in Ref Reason"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

