table 'Pop Dems'
	lineageTag: c865b561-b3f6-4d3e-bb37-497ce7823406

	measure 'Rate per 1000 population' = (sum('Pop Dems'[QOF_LearningDisability])/sum('Pop Dems'[Population_Counter]))*1000
		lineageTag: 64c85984-7589-43f5-b1e4-e0d447ee388f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Derived_NHS_Number
		dataType: string
		lineageTag: b1413bf3-7f64-460e-82fb-cc1caac0691a
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column Population_Counter
		dataType: int64
		formatString: 0
		lineageTag: 3345ffbc-7d19-40e1-b514-89001f0179a1
		summarizeBy: sum
		sourceColumn: Population_Counter

		annotation SummarizationSetBy = Automatic

	column Actual_Age
		dataType: int64
		formatString: 0
		lineageTag: 9d733151-b256-4d72-8a3f-aac72dd2d6c2
		summarizeBy: sum
		sourceColumn: Actual_Age

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: string
		lineageTag: ba678baf-1308-4423-9a3f-88a8f00f32ad
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Age_Rank
		dataType: int64
		formatString: 0
		lineageTag: b5e60c10-7916-4a06-950e-1fe0436f6497
		summarizeBy: sum
		sourceColumn: Age_Rank

		annotation SummarizationSetBy = Automatic

	column Ageband
		dataType: string
		lineageTag: afb754fe-0b88-4d83-9fe3-e5d1abeb3361
		summarizeBy: none
		sourceColumn: Ageband

		annotation SummarizationSetBy = Automatic

	column Under_18
		dataType: int64
		formatString: 0
		lineageTag: 53940dce-b656-4196-a54e-dd79811381a2
		summarizeBy: sum
		sourceColumn: Under_18

		annotation SummarizationSetBy = Automatic

	column 65_and_Over
		dataType: int64
		formatString: 0
		lineageTag: 099a385e-a954-408f-a33d-c8644dd270b9
		summarizeBy: sum
		sourceColumn: 65_and_Over

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: c6aa3e47-9355-402d-851e-ecb2769a1730
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Care_Home
		dataType: int64
		formatString: 0
		lineageTag: 4debc936-72bb-4a27-a7d0-edcea8c8f85f
		summarizeBy: sum
		sourceColumn: Care_Home

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: 8be81104-3d14-4241-a187-96861b0f660f
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column EthnicMinority
		dataType: int64
		formatString: 0
		lineageTag: 10de5da5-83b8-4373-978c-496f2a269bfd
		summarizeBy: sum
		sourceColumn: EthnicMinority

		annotation SummarizationSetBy = Automatic

	column IMD_Decile_England
		dataType: int64
		formatString: 0
		lineageTag: 3a729f1f-32f6-4ffb-9f42-da2bf6bcd19f
		summarizeBy: sum
		sourceColumn: IMD_Decile_England

		annotation SummarizationSetBy = Automatic

	column IMD_Decile_Gloucester
		dataType: int64
		formatString: 0
		lineageTag: 9013c006-9e0b-4e80-b910-bd537743aace
		summarizeBy: sum
		sourceColumn: IMD_Decile_Gloucester

		annotation SummarizationSetBy = Automatic

	column Core20
		dataType: int64
		formatString: 0
		lineageTag: 3815bda5-db65-4470-8ec5-6f6a6024a473
		summarizeBy: sum
		sourceColumn: Core20

		annotation SummarizationSetBy = Automatic

	column GP_Practice_Code
		dataType: string
		lineageTag: ea4f1056-f58c-4d24-a7a2-424104d523ac
		summarizeBy: none
		sourceColumn: GP_Practice_Code

		annotation SummarizationSetBy = Automatic

	column GP_Practice_Name
		dataType: string
		lineageTag: 3c585ac2-680b-440f-9499-6338eee1aa5e
		summarizeBy: none
		sourceColumn: GP_Practice_Name

		annotation SummarizationSetBy = Automatic

	column PrimaryCareNetwork
		dataType: string
		lineageTag: 36e52511-6485-4334-8a4a-f637b6cee6a4
		summarizeBy: none
		sourceColumn: PrimaryCareNetwork

		annotation SummarizationSetBy = Automatic

	column GPLatitude
		dataType: string
		lineageTag: f76184ac-2fd1-4e5f-9634-9cff23cb9c98
		summarizeBy: none
		sourceColumn: GPLatitude

		annotation SummarizationSetBy = Automatic

	column GPLongitude
		dataType: string
		lineageTag: 7be95f9c-a83d-4cff-9c6e-e7048e3b59a2
		summarizeBy: none
		sourceColumn: GPLongitude

		annotation SummarizationSetBy = Automatic

	column Locality
		dataType: string
		lineageTag: 8eee279c-6c09-41ce-8788-f67313f89922
		summarizeBy: none
		sourceColumn: Locality

		annotation SummarizationSetBy = Automatic

	column Registered
		dataType: int64
		formatString: 0
		lineageTag: 2eb10528-6203-4565-9505-9cc92112d903
		summarizeBy: sum
		sourceColumn: Registered

		annotation SummarizationSetBy = Automatic

	column Resident
		dataType: int64
		formatString: 0
		lineageTag: eed5605c-0435-475f-a34d-ab45b0479993
		summarizeBy: sum
		sourceColumn: Resident

		annotation SummarizationSetBy = Automatic

	column Registered_Text
		dataType: string
		lineageTag: 09506780-b140-4ae6-b457-919320634a83
		summarizeBy: none
		sourceColumn: Registered_Text

		annotation SummarizationSetBy = Automatic

	column Resident_Text
		dataType: string
		lineageTag: 994791a5-f5f0-47c2-9b5c-d9a7c800ec19
		summarizeBy: none
		sourceColumn: Resident_Text

		annotation SummarizationSetBy = Automatic

	column Derived_Postcode_Key
		dataType: string
		lineageTag: 11933882-390c-4069-a48b-a8885ba7005f
		summarizeBy: none
		sourceColumn: Derived_Postcode_Key

		annotation SummarizationSetBy = Automatic

	column LSOA_Code
		dataType: string
		lineageTag: edbd07a2-be92-4efb-97aa-080eb11db566
		summarizeBy: none
		sourceColumn: LSOA_Code

		annotation SummarizationSetBy = Automatic

	column LSOA_Name
		dataType: string
		lineageTag: a79b59f3-9e1c-4f38-9180-d7d4bab8d9d0
		summarizeBy: none
		sourceColumn: LSOA_Name

		annotation SummarizationSetBy = Automatic

	column Ward_Code
		dataType: string
		lineageTag: bd832f0a-c08c-4fe6-af00-5cd0b93a562e
		summarizeBy: none
		sourceColumn: Ward_Code

		annotation SummarizationSetBy = Automatic

	column Ward_Name
		dataType: string
		lineageTag: 1891aa3a-ffef-43a3-aa17-c5ad1390d835
		summarizeBy: none
		sourceColumn: Ward_Name

		annotation SummarizationSetBy = Automatic

	column District_Code
		dataType: string
		lineageTag: 7939198b-bff6-46c6-bda6-c44a4dfcc0d7
		summarizeBy: none
		sourceColumn: District_Code

		annotation SummarizationSetBy = Automatic

	column District_Name
		dataType: string
		lineageTag: d03c22fc-d8a3-4fd4-a2fe-1455e220e835
		summarizeBy: none
		sourceColumn: District_Name

		annotation SummarizationSetBy = Automatic

	column EFi_Category
		dataType: string
		lineageTag: 7bd06e40-0bb7-4824-8fff-091ce897ebdb
		summarizeBy: none
		sourceColumn: EFi_Category

		annotation SummarizationSetBy = Automatic

	column QOF_Asthma
		dataType: int64
		formatString: 0
		lineageTag: 0564da8e-84d7-4991-96f8-df964d0e0a2c
		summarizeBy: sum
		sourceColumn: QOF_Asthma

		annotation SummarizationSetBy = Automatic

	column QOF_AtrialFibrilation
		dataType: int64
		formatString: 0
		lineageTag: 876096c1-b37d-4168-99d0-6f60cda79ed1
		summarizeBy: sum
		sourceColumn: QOF_AtrialFibrilation

		annotation SummarizationSetBy = Automatic

	column QOF_Cancer
		dataType: int64
		formatString: 0
		lineageTag: d47aaf68-567f-4c7d-a643-6f93f78dcd3e
		summarizeBy: sum
		sourceColumn: QOF_Cancer

		annotation SummarizationSetBy = Automatic

	column QOF_ChronicKidneyDisease
		dataType: int64
		formatString: 0
		lineageTag: d997f833-8264-44e7-8ba9-89b38091e7ce
		summarizeBy: sum
		sourceColumn: QOF_ChronicKidneyDisease

		annotation SummarizationSetBy = Automatic

	column QOF_COPD
		dataType: int64
		formatString: 0
		lineageTag: da6a19e0-edf3-4de8-ba25-6fb873f9213a
		summarizeBy: sum
		sourceColumn: QOF_COPD

		annotation SummarizationSetBy = Automatic

	column QOF_CoronaryHeartDisease
		dataType: int64
		formatString: 0
		lineageTag: 4ae4288a-67d2-4514-8cc3-4d41901d34c4
		summarizeBy: sum
		sourceColumn: QOF_CoronaryHeartDisease

		annotation SummarizationSetBy = Automatic

	column QOF_Dementia
		dataType: int64
		formatString: 0
		lineageTag: dda10a6d-fe2c-40d2-8b1e-8c78903ce760
		summarizeBy: sum
		sourceColumn: QOF_Dementia

		annotation SummarizationSetBy = Automatic

	column QOF_Depression
		dataType: int64
		formatString: 0
		lineageTag: a9da46ad-7bd9-4a4c-9880-b3943a40ec28
		summarizeBy: sum
		sourceColumn: QOF_Depression

		annotation SummarizationSetBy = Automatic

	column QOF_Diabetes
		dataType: int64
		formatString: 0
		lineageTag: 84bf66dd-6926-420c-85e1-8e08240b4fe5
		summarizeBy: sum
		sourceColumn: QOF_Diabetes

		annotation SummarizationSetBy = Automatic

	column QOF_Epilepsy
		dataType: int64
		formatString: 0
		lineageTag: 0c11e8a5-3579-4bb6-8af3-b744c2aa163c
		summarizeBy: sum
		sourceColumn: QOF_Epilepsy

		annotation SummarizationSetBy = Automatic

	column QOF_HeartFailure
		dataType: int64
		formatString: 0
		lineageTag: bd7284ff-85d4-4695-85be-01133a316ee8
		summarizeBy: sum
		sourceColumn: QOF_HeartFailure

		annotation SummarizationSetBy = Automatic

	column QOF_Hypertension
		dataType: int64
		formatString: 0
		lineageTag: 16592e3a-ba67-44da-b64d-c48b6cbf7b8e
		summarizeBy: sum
		sourceColumn: QOF_Hypertension

		annotation SummarizationSetBy = Automatic

	column QOF_LearningDisability
		dataType: int64
		formatString: 0
		lineageTag: b9c5bfd0-4cc4-49eb-bb37-1f7177e6a50a
		summarizeBy: sum
		sourceColumn: QOF_LearningDisability

		annotation SummarizationSetBy = Automatic

	column QOF_MentalHealth
		dataType: int64
		formatString: 0
		lineageTag: 8a5e09f7-af0a-4b0a-a26a-cc3dbc061769
		summarizeBy: sum
		sourceColumn: QOF_MentalHealth

		annotation SummarizationSetBy = Automatic

	column QOF_NonDiabeticHyperglycaemia
		dataType: int64
		formatString: 0
		lineageTag: c1d14f0c-7308-4a57-94f9-1072ce0c21be
		summarizeBy: sum
		sourceColumn: QOF_NonDiabeticHyperglycaemia

		annotation SummarizationSetBy = Automatic

	column QOF_Obesity
		dataType: int64
		formatString: 0
		lineageTag: 014b66cf-0dd4-4e63-a0d2-8bb013fddb5c
		summarizeBy: sum
		sourceColumn: QOF_Obesity

		annotation SummarizationSetBy = Automatic

	column QOF_Osteoporosis
		dataType: int64
		formatString: 0
		lineageTag: db8d1bd9-e2cf-40de-9757-6584508fe300
		summarizeBy: sum
		sourceColumn: QOF_Osteoporosis

		annotation SummarizationSetBy = Automatic

	column QOF_PalliativeCare
		dataType: int64
		formatString: 0
		lineageTag: f0c3d426-3bbb-4cb3-bf72-b1bce897bb92
		summarizeBy: sum
		sourceColumn: QOF_PalliativeCare

		annotation SummarizationSetBy = Automatic

	column QOF_PeripheralArterialDisease
		dataType: int64
		formatString: 0
		lineageTag: 622af8f5-6854-4948-8fe9-8abe536497f1
		summarizeBy: sum
		sourceColumn: QOF_PeripheralArterialDisease

		annotation SummarizationSetBy = Automatic

	column QOF_RheumatoidArthritis
		dataType: int64
		formatString: 0
		lineageTag: 50be105e-71f1-46fe-abd8-802c7b0ded75
		summarizeBy: sum
		sourceColumn: QOF_RheumatoidArthritis

		annotation SummarizationSetBy = Automatic

	column QOF_StrokeAndTIA
		dataType: int64
		formatString: 0
		lineageTag: 8ad42622-c325-4adc-a55f-d5d7731267fe
		summarizeBy: sum
		sourceColumn: QOF_StrokeAndTIA

		annotation SummarizationSetBy = Automatic

	column ActivityDate
		dataType: dateTime
		formatString: General Date
		lineageTag: ea257783-56be-4739-a4c1-b919b22efeb3
		summarizeBy: none
		sourceColumn: ActivityDate

		variation Variation
			isDefault
			relationship: 0dc7355e-1b7f-4de9-9968-232b9b994253
			defaultHierarchy: LocalDateTable_eb583c2e-c1cc-475f-8cf5-10e60e9ca4e8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column WorkingAge
		dataType: int64
		formatString: 0
		lineageTag: 06b71d9f-22dd-4450-afbc-e4c4a9996692
		summarizeBy: sum
		sourceColumn: WorkingAge

		annotation SummarizationSetBy = Automatic

	column LSOA_2021
		dataType: string
		lineageTag: e4b4838a-bb03-4165-bc09-b68c9cd79622
		summarizeBy: none
		sourceColumn: LSOA_2021

		annotation SummarizationSetBy = Automatic

	column RuralUrbanClass
		dataType: string
		lineageTag: 8f5479d1-b843-43cc-8555-4ce20825379d
		summarizeBy: none
		sourceColumn: RuralUrbanClass

		annotation SummarizationSetBy = Automatic

	column NON_QOF_Smoker
		dataType: int64
		formatString: 0
		lineageTag: 09b4db19-cff6-415f-b47b-ec4850564c61
		summarizeBy: sum
		sourceColumn: NON_QOF_Smoker

		annotation SummarizationSetBy = Automatic

	column PatientNeedsGroup
		dataType: string
		lineageTag: 89e3b1a4-d23d-40c1-8c98-50b4df9aaf5d
		summarizeBy: none
		sourceColumn: PatientNeedsGroup

		annotation SummarizationSetBy = Automatic

	partition 'Pop Dems' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Reporting", [Query="select *#(lf)FROM [PowerBI_Reporting].[PHM].[tbl02_DemographicsOverview]#(lf)"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"M","Male",Replacer.ReplaceText,{"Gender"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"Gender"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","U","Unknown",Replacer.ReplaceText,{"Gender"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value2", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

