table SWASFT_over_time
	lineageTag: 6c5c416e-9e0a-4ec8-b2d8-fdd95923fce5

	column Derived_NHS_Number
		dataType: string
		lineageTag: aa821283-2184-40af-aa89-f310c441d087
		summarizeBy: none
		sourceColumn: Derived_NHS_Number

		annotation SummarizationSetBy = Automatic

	column LD_Flag
		dataType: int64
		formatString: 0
		lineageTag: c159409c-cff7-4c7e-83fe-31dbbdfee156
		summarizeBy: sum
		sourceColumn: LD_Flag

		annotation SummarizationSetBy = Automatic

	column Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 7d493151-53d5-475a-839e-c4fccf4c6a6c
		summarizeBy: sum
		sourceColumn: Autism_Flag

		annotation SummarizationSetBy = Automatic

	column LD_Autism_Flag
		dataType: int64
		formatString: 0
		lineageTag: 5f515ba4-4105-403c-8761-d00d8f92d98d
		summarizeBy: sum
		sourceColumn: LD_Autism_Flag

		annotation SummarizationSetBy = Automatic

	column Condition_Category
		dataType: string
		lineageTag: bfe3b5d7-9427-4ad5-83c6-48d117dd03d8
		summarizeBy: none
		sourceColumn: Condition_Category

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHSNumber
		dataType: string
		lineageTag: 44ae4e27-bbaf-447f-bde2-1161263cfd92
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHSNumber

		annotation SummarizationSetBy = Automatic

	column Incident_Number
		dataType: string
		lineageTag: f1a22d59-6046-46ce-9f20-00627212fc14
		summarizeBy: none
		sourceColumn: Incident_Number

		annotation SummarizationSetBy = Automatic

	column Time_Of_Incident
		dataType: dateTime
		formatString: General Date
		lineageTag: bacf1be7-14fd-4761-b9d4-8a45d34ea82a
		summarizeBy: none
		sourceColumn: Time_Of_Incident

		variation Variation
			isDefault
			relationship: 263b0ce1-54c0-4351-9727-40448ed353d8
			defaultHierarchy: LocalDateTable_91a73fa6-ccd7-4d7c-915f-975835e76f1f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Date_of_Incident
		dataType: dateTime
		formatString: General Date
		lineageTag: d685478c-42d4-42ba-ad6b-023af39bad89
		summarizeBy: none
		sourceColumn: Date_of_Incident

		annotation SummarizationSetBy = Automatic

	column Month_of_Call
		dataType: string
		lineageTag: 5ecb9a78-2a2c-4c35-b563-269a9409db8e
		summarizeBy: none
		sourceColumn: Month_of_Call

		annotation SummarizationSetBy = Automatic

	column CCG
		dataType: string
		lineageTag: 50196a13-61be-4178-ae66-d53d8a421362
		summarizeBy: none
		sourceColumn: CCG

		annotation SummarizationSetBy = Automatic

	column Symptom_Group_Chief_Complaint
		dataType: string
		lineageTag: b3c151a2-4289-4900-8ca0-29473e3a7e0e
		summarizeBy: none
		sourceColumn: Symptom_Group_Chief_Complaint

		annotation SummarizationSetBy = Automatic

	column Pathways_AMPDS_Disposition
		dataType: string
		lineageTag: d2024421-9a83-4b30-a575-a6eace38cb3e
		summarizeBy: none
		sourceColumn: Pathways_AMPDS_Disposition

		annotation SummarizationSetBy = Automatic

	column Managed_Incident
		dataType: string
		lineageTag: 8a893dd6-040e-4bc1-be18-3f770b376a0e
		summarizeBy: none
		sourceColumn: Managed_Incident

		annotation SummarizationSetBy = Automatic

	column Incident_Colour
		dataType: string
		lineageTag: 41cc5634-b3f1-4ab6-a6ef-82eee9a503ca
		summarizeBy: none
		sourceColumn: Incident_Colour

		annotation SummarizationSetBy = Automatic

	column Outcome
		dataType: string
		lineageTag: 1283736f-cb23-4bbe-81b6-c776b0f65944
		summarizeBy: none
		sourceColumn: Outcome

		annotation SummarizationSetBy = Automatic

	column Age_Bracket
		dataType: string
		lineageTag: dc16f17b-550b-4e3c-a87b-3e2b73191877
		summarizeBy: none
		sourceColumn: Age_Bracket

		annotation SummarizationSetBy = Automatic

	column Ageband_at_event
		dataType: string
		lineageTag: c0669cd7-e3be-41e7-a3ec-dd2e1ee6efc7
		summarizeBy: none
		sourceColumn: Ageband_at_event
		sortByColumn: AgeBand_Sort_Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Local_Authority
		dataType: string
		lineageTag: 4fe285d6-8da9-4a30-a0e1-cb19f4cb640c
		summarizeBy: none
		sourceColumn: Local_Authority

		annotation SummarizationSetBy = Automatic

	column Ward
		dataType: string
		lineageTag: 49c88ee8-cfaa-44d1-93ac-13f1611cf282
		summarizeBy: none
		sourceColumn: Ward

		annotation SummarizationSetBy = Automatic

	column Mental_Health_Call_Indicator
		dataType: string
		lineageTag: ce9e7823-718a-4b92-aefb-930bdf1de8c1
		summarizeBy: none
		sourceColumn: Mental_Health_Call_Indicator

		annotation SummarizationSetBy = Automatic

	column Suicide_Call_Indicator
		dataType: string
		lineageTag: c95ffb60-5ed9-4721-9198-d1a129430076
		summarizeBy: none
		sourceColumn: Suicide_Call_Indicator

		annotation SummarizationSetBy = Automatic

	column High_Intensity_User_Call_Indicator
		dataType: string
		lineageTag: 839850ac-ae15-4ebb-96ef-639fe9175c4f
		summarizeBy: none
		sourceColumn: High_Intensity_User_Call_Indicator

		annotation SummarizationSetBy = Automatic

	column counter_event
		dataType: int64
		formatString: #,0
		lineageTag: a17c4511-b152-44f4-9671-f1e3d09c238e
		summarizeBy: sum
		sourceColumn: counter_event

		annotation SummarizationSetBy = Automatic

	column AgeBand_Sort_Order
		dataType: int64
		formatString: 0
		lineageTag: 9ddc7128-7009-403b-9577-16724bcc6583
		summarizeBy: sum
		sourceColumn: AgeBand_Sort_Order

		annotation SummarizationSetBy = Automatic

	column High_Intensity_User_Call_Indicator_Y/N
		dataType: string
		lineageTag: 5ffc289d-071d-40bd-891d-0bbe74b50c8f
		summarizeBy: none
		sourceColumn: High_Intensity_User_Call_Indicator_Y/N

		annotation SummarizationSetBy = Automatic

	column Categories_desc
		dataType: string
		lineageTag: 19d5a386-342a-4c20-8447-f5dbb4b6ac92
		summarizeBy: none
		sourceColumn: Categories_desc

		annotation SummarizationSetBy = Automatic

	column Census_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5e25bc48-569c-4f85-8e6a-37594bd31ec8
		summarizeBy: none
		sourceColumn: Census_Date

		variation Variation
			isDefault
			relationship: b957f6c3-71b5-43ce-90ef-e236ab60a799
			defaultHierarchy: LocalDateTable_d02495d6-ad90-4d19-854d-95eb17e7718b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Census_Financial_Year
		dataType: string
		lineageTag: 9d1c2a2c-71ed-4881-82a2-5a45a7f097e4
		summarizeBy: none
		sourceColumn: Census_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Census_Month_Name
		dataType: string
		lineageTag: 7535db61-e928-4c4e-8c4e-b8174d8a707f
		summarizeBy: none
		sourceColumn: Census_Month_Name

		annotation SummarizationSetBy = Automatic

	partition SWASFT_over_time = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select derived_nhs_number as ""Derived_NHS_Number"", census_date as ""Census_Date"", census_financial_year as ""Census_Financial_Year"", census_month_name as ""Census_Month_Name"", ld_flag as ""LD_Flag"", autism_flag as ""Autism_Flag"", ld_autism_flag as ""LD_Autism_Flag"", condition_category as ""Condition_Category"", derived_pseudo_nhsnumber as ""Derived_Pseudo_NHSNumber"", incident_number as ""Incident_Number"", time_of_incident as ""Time_Of_Incident"", date_of_incident as ""Date_of_Incident"", month_of_call as ""Month_of_Call"", ccg as ""CCG"", symptom_group_chief_complaint as ""Symptom_Group_Chief_Complaint"", pathways_ampds_disposition as ""Pathways_AMPDS_Disposition"", managed_incident as ""Managed_Incident"", incident_colour as ""Incident_Colour"", categories_desc as ""Categories_desc"", outcome as ""Outcome"", age_bracket as ""Age_Bracket"", ageband_at_event as ""Ageband_at_event"", ageband_sort_order as ""AgeBand_Sort_Order"", local_authority as ""Local_Authority"", ward as ""Ward"", mental_health_call_indicator as ""Mental_Health_Call_Indicator"", suicide_call_indicator as ""Suicide_Call_Indicator"", high_intensity_user_call_indicator as ""High_Intensity_User_Call_Indicator"", ""high_intensity_user_call_indicator_y/n"" as ""High_Intensity_User_Call_Indicator_Y/N"", counter_event from data_mart_powerbi_ldanda.tbl11_lda_swasft_ot", null, [EnableFolding=true]),
				    #"Counter to Whole No." = Table.TransformColumnTypes(Source,{{"counter_event", Int64.Type}})
				in
				    #"Counter to Whole No."

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

