table 'PES Date Table'
	lineageTag: a27eb5ba-3812-4797-9ed0-6e1ce37f3302

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: a4e192ec-14bb-472f-84ef-3f4e6f43092f
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: a7b2e7d0-29b5-4cfb-8ab7-5c0a13e4cabe
			defaultHierarchy: LocalDateTable_befb198e-0db0-42e9-8641-a773d145e318.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 834d324d-8b47-4df1-9817-61681b393383
		summarizeBy: none
		sourceColumn: day_month_year

		variation Variation
			isDefault
			relationship: d17afa49-da8d-4eb1-840c-fb0c1f9e6917
			defaultHierarchy: LocalDateTable_39b8e5c0-a7b6-4bd9-bdbd-5aef1c08cda1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: a69a9e0e-f9b1-4bbc-befd-b4f8d49f4830
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: cfe51e8e-ee4e-476c-b06f-d86407b8b2bf
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: b895694e-52dc-4d52-aaeb-a45691a02153
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 72b5ee26-3126-42ae-aab4-077a2bfc408d
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 194b20f0-bdf9-4374-9ae3-c302cc046e41
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 5d021c0d-8e3e-4f42-8ad5-036e91f090d8
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 1e782668-3ddf-4d03-ae3a-5ce0f653e62e
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: bc9c7ad4-ba3d-4184-97a0-cad08fafa75e
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 531af7f9-48ad-4d52-be7e-ea4d9b464e82
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: 4e608572-ae23-4b28-a44e-c84b7053965e
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: 5453a9ee-8886-43bd-86ee-c47f56c95668
		summarizeBy: sum
		sourceColumn: is_working_day

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: ddb1f8d3-fc47-4439-8d8f-3ef8eaaf210e
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 671d06ec-3ff4-45d1-8dd9-f1df0377fe81
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: a6cb6bb4-3567-4438-94f4-c2b93465aa05
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: e6b0ef53-b7f1-48cd-b602-7e906dac42af
		summarizeBy: sum
		sourceColumn: day_of_quarter

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 307bba81-2dfc-41a4-b14a-0eb5ac5c9c5f
		summarizeBy: none
		sourceColumn: quarter_start_date

		variation Variation
			isDefault
			relationship: 2dd8746e-0828-425b-a68f-a78d43cc3979
			defaultHierarchy: LocalDateTable_0029d3e6-ec80-4282-96b1-c128d392fc39.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d6ac7576-1e48-47c0-9ab5-a4e358c70a6f
		summarizeBy: none
		sourceColumn: quarter_end_date

		variation Variation
			isDefault
			relationship: 67823f50-bcf2-4b97-bf3b-3fc0ee19c882
			defaultHierarchy: LocalDateTable_b14ace3f-6751-41fc-bae7-325024660a60.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: 69726d62-85fa-4607-8102-7765469a6707
		summarizeBy: sum
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 3656bbde-f5fd-45b0-ad33-28fd471b5225
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 34fcbb94-8cd0-44f6-94e5-6ff5a963b7ca
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: be45a6bb-a919-4a25-9c41-b506c7540382
		summarizeBy: none
		sourceColumn: month_year

		variation Variation
			isDefault
			relationship: 63868032-6486-4fb8-85a6-037c2d40eac7
			defaultHierarchy: LocalDateTable_5d030c5e-d7ea-47a4-a17c-7f3908a5914c.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 0fb6970c-faa9-4087-a4e6-798e5d020208
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: ad2b7849-cf43-4266-973b-8869551be74f
		summarizeBy: sum
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 0fa23f84-ba43-4030-a784-62ed3252627d
		summarizeBy: sum
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: e1f9357b-1f52-4bd2-ae92-5593c766057d
		summarizeBy: sum
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 804c3905-a56d-46e6-b74d-2eab4c37b5a5
		summarizeBy: sum
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: b76d7dff-97ea-40ca-aade-511bcf3fba77
		summarizeBy: sum
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	column financial_quarters
		dataType: string
		lineageTag: b4f2460b-1ed5-4691-bc06-4ae5d5d07e8a
		summarizeBy: none
		sourceColumn: financial_quarters

		annotation SummarizationSetBy = Automatic

	hierarchy 'financial_year Hierarchy'
		lineageTag: be9d417c-2319-4d23-91f8-8466ab92dd94

		level financial_year
			lineageTag: b438993c-2667-4056-896d-07d9fd078e12
			column: financial_year

		level financial_quarters
			lineageTag: 7dd00701-9535-4a59-9084-6aa6c5c213d9
			column: financial_quarters

		level month_year
			lineageTag: 88623f7e-23bb-44de-a699-435a6cc6abb0
			column: month_year

	partition 'PES Date Table' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="/*===============================================================================================================#(lf)Pop Health Optom dates #(lf)#(lf)New Date Reference Script#(lf)Created by: Ben Adams#(lf)Created Date: 27/12/2023#(lf)===============================================================================================================*/#(lf)#(lf)DECLARE @MaxDate DATE = (SELECT MAX([ProcessedDate]) FROM [ICB_Products].[Patient].[vw_Summary]);#(lf)DECLARE @LatestFullMonthEnd DATE = EOMONTH(@MaxDate, -1); #(lf)#(lf)SELECT DISTINCT [date] = CAST([Full_Date] AS DATE)#(lf)               ,[day_month_year] = CONVERT(VARCHAR, [Full_Date], 103) --> 103 converts to DD/MM/YYYY format#(lf)#(tab)#(tab)#(tab)   ,[day] = [Day_Of_Fin_Year]#(lf)#(tab)#(tab)#(tab)   ,[weekday] = [Weekday_No]#(lf)#(tab)#(tab)#(tab)   ,[weekday_name] = [Weekday_Name]#(lf)#(tab)#(tab)#(tab)   ,[month] = [Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_name] = [Month_Short_Name]#(lf)#(tab)#(tab)#(tab)   ,[quarter] = [Cal_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[year_month] = [Year_Month]#(lf)#(tab)#(tab)#(tab)   ,[is_weekend] = CASE WHEN [Weekday_No] IN (6,7) THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[is_holiday] = CASE WHEN [Bank_Holiday_Desc] IS NOT NULL THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[holiday_description] = [Bank_Holiday_Desc] --> Description of holiday type i.e., 'Bank Holiday'#(lf)#(tab)#(tab)#(tab)   ,[is_working_day] = [Working_Day_Calc]#(lf)#(tab)#(tab)#(tab)   ,[financial_week_of_year] = [Fin_Week_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_year] = REPLACE([Fin_Year_YYYY_dash_YY], ' - ', '/')#(lf)#(tab)#(tab)#(tab)   ,[financial_quarter] = [Fin_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[day_of_quarter] = [Day_Of_Quarter]#(lf)#(tab)#(tab)#(tab)   ,[quarter_start_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[quarter_end_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[month_day_no] = [Month_Day_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_month] = [Fin_Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_year_name] = CONCAT([Month_Short_Name], '-', LEFT([Date_112], 4))#(lf)#(tab)#(tab)#(tab)   ,[month_year] = [MonthYear_MMMM_YYYYY]#(lf)#(tab)#(tab)#(tab)   ,[ytd_flag] = CASE WHEN [Fin_Month_No] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([Fin_Month_No] AS INT)#(lf)                                           FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Full_Date] = EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END --> Establishes whether the month is included in year to date calculations and reflects across all years#(lf)#(tab)#(tab)#(tab)   ,[latest_month_flag] = CASE WHEN [Year_Month] IN #(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_month_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -2, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The month before the latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[latest_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                             (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                              FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -12, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      THEN 1 ELSE 0 END --> The latest 12 months within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                               (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                                FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -24, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)    AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        THEN 1 ELSE 0 END --> The 12 months before the latest 12 months within your date range - allows comparing current to previous#(lf)#(tab)#(tab)#(tab)   ,[same_month_last_year_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                                 (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END --> Same month last year as the latest month within the date range i.e., Nov-22 and Nov-23#(lf) #(lf)FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf) #(lf)WHERE [Full_Date] BETWEEN '20180401' AND @LatestFullMonthEnd#(lf)#(lf)-- EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) ) --> This can be changed to meet your date range need. #(lf)                                                                                      --  The EOMONTH function finds the latest complete month.#(lf) #(lf)ORDER BY CAST([Full_Date] AS DATE) DESC"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "financial_quarters", each if [financial_quarter] = 1 then "Q1" else if [financial_quarter] = 2 then "Q2" else if [financial_quarter] = 3 then "Q3" else if [financial_quarter] = 4 then "Q4" else "NULL")
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

