table REF_Date_Ref
	lineageTag: a411c1ac-5bb7-4e1b-8d7d-1ac32e5fa4e9
	dataCategory: Time

	measure Latest_Reporting_Month_Year_Text =
			
			VAR Latest_date_in_report = MAX(REF_Date_Ref[date])
			RETURN FORMAT(Latest_date_in_report, "MMMM yyyy")
		lineageTag: 862b25e7-1aef-481e-8481-2d5411fd06f0

	column date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 4a0cb97a-3e1a-4af5-b433-89691c45212b
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: adf48597-5e58-41f2-b80c-1b72722d8e4c
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: cd43c0be-6ca1-46bf-ae13-9e6c14ad930e
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 95e1289f-b9fb-41cd-8bd3-27f7a8e49dbe
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: dec4b1f1-f8b2-483f-9029-06f64441cedf
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 4ba71a0b-c53b-4981-841a-b67722e5fe9f
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 1c50f4e8-64eb-4ccf-8ce0-28efcd051320
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 35f60cb8-5000-4333-a774-3923fcde2c42
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: f4c92099-072a-4650-ac95-a64fba5985b4
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 99565d2f-4bd8-4f92-b4e1-066518216c81
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: d9b69520-8911-473e-9bb2-382a1dc791ef
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 60a6393c-11dd-4a57-82a9-762d1c4f4a52
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 185cb86c-5aae-42b9-992d-3eec288488a9
		summarizeBy: none
		sourceColumn: financial_year
		sortByColumn: Date_Order_Financial_Year

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: d2100c17-4e2b-42aa-bd69-8780ae79f8c9
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 2299f83a-27fe-44d6-9145-545db2a7c753
		summarizeBy: sum
		sourceColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: a283f6f0-71aa-4841-9917-10158a415ff6
		summarizeBy: none
		sourceColumn: Last_Updated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Data_up_to
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d200216a-051c-4b16-9e01-08ad203ff621
		summarizeBy: none
		sourceColumn: Data_up_to

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2d3116e1-d297-4c0d-94cd-fb5915e04e90
		summarizeBy: sum
		sourceColumn: Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column Date_Order
		dataType: int64
		formatString: 0
		lineageTag: 16794060-639b-4d96-85bf-af89edf132f7
		summarizeBy: sum
		sourceColumn: Date_Order

		annotation SummarizationSetBy = Automatic

	column Date_Order_Financial_Year
		dataType: int64
		formatString: 0
		lineageTag: 06003db1-384b-46bb-976a-041a1562c334
		summarizeBy: sum
		sourceColumn: Date_Order_Financial_Year

		annotation SummarizationSetBy = Automatic

	column GHC_Inpatient_Data_Date_Range_Flag
		dataType: int64
		formatString: 0
		lineageTag: 44a2fcd4-0391-4075-9802-50bcd3c4a28b
		summarizeBy: sum
		sourceColumn: GHC_Inpatient_Data_Date_Range_Flag

		annotation SummarizationSetBy = Automatic

	column GHC_Inpatient_Data_Data_up_to
		dataType: dateTime
		formatString: Short Date
		lineageTag: d3d84221-c96a-4e7f-9ce5-84be7efb6a05
		summarizeBy: none
		sourceColumn: GHC_Inpatient_Data_Data_up_to

		annotation SummarizationSetBy = Automatic

	partition REF_Date_Ref = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "with v as ( select (case when md = last_day(md) then md else last_day(add_months(md,-1)) end) as end_date, (case when mi = last_day(mi) then mi else last_day(add_months(mi,-1)) end) as inpatient_end_date from (select (select max(cast(referral_recieved_date as date)) from db02_nopid.data_mart_powerbi_community.tbl02_csds_referrals where cast(referral_recieved_date as date) <= current_date) as md, (select max(cast(discharge_date as date)) from db02_nopid.data_mart_powerbi_secondarycare.tbl07_inpatients where cast(discharge_date as date) <= current_date and provider_code like 'RTQ%') as mi) x ), fy_order as ( select financial_year, row_number() over (order by first_date_in_fy asc) as financial_year_order from (select financial_year, min(""date"") as first_date_in_fy from ccg_reference.vw_date, v where ""date"" between '2022-04-01' and v.end_date group by financial_year) fy ) select row_number() over (order by d.""date"" asc) as ""Date_Order"", fyo.financial_year_order as ""Date_Order_Financial_Year"", d.""date"" as ""date"", d.day_month_year as ""day_month_year"", d.""day"" as ""day"", d.weekday as ""weekday"", d.weekday_name as ""weekday_name"", d.""month"" as ""month"", left(d.month_name,3) as ""month_name"", d.""quarter"" as ""quarter"", d.year_month as ""year_month"", d.is_weekend as ""is_weekend"", d.is_holiday as ""is_holiday"", d.financial_week_of_year as ""financial_week_of_year"", d.financial_year as ""financial_year"", d.financial_quarter as ""financial_quarter"", d.financial_month as ""financial_month"", getdate() as ""Last_Updated"", v.end_date as ""Data_up_to"", case when d.financial_month <= (select cast(financialmonth as int) from ccg_reference.vw_datelookup dl, v where dl.""date"" = v.end_date) then 1 else 0 end as ""Reporting_Month_Flag"", case when cast(d.""date"" as date) <= cast(v.inpatient_end_date as date) then 1 else 0 end as ""GHC_Inpatient_Data_Date_Range_Flag"", v.inpatient_end_date as ""GHC_Inpatient_Data_Data_up_to"" from ccg_reference.vw_date d cross join v left join fy_order fyo on d.financial_year = fyo.financial_year where d.""date"" between '2022-04-01' and v.end_date order by d.""date""", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}, {"day", Int64.Type}, {"weekday", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}, {"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

