table REF_Length_of_referral_banding_order_ref
	lineageTag: 2940780b-9530-4603-bca6-6e9cf7c222ae

	column Length_of_referral_banding
		dataType: string
		lineageTag: 936e0521-12ed-46b4-833f-e24a33e4e9df
		summarizeBy: none
		sourceColumn: Length_of_referral_banding
		sortByColumn: Length_of_referral_banding_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Length_of_referral_banding_order
		dataType: int64
		formatString: 0
		lineageTag: 1a86090e-44a8-44e9-8c67-d650368af29a
		summarizeBy: none
		sourceColumn: Length_of_referral_banding_order

		annotation SummarizationSetBy = Automatic

	partition REF_Length_of_referral_banding_order_ref = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fcwxDoMwDEbhq/zyTIeW9iJdUYZIOA0qtaXEBY5P0qEswPaGT6/r6MmBU/IjRpaXRVxK5AyLXqDCmJnf1NCVXLOHKzGFzfqTudDbAa2m0KDf9Lft+TYPCz4qFqu9H9gNwUsPnTgV/SDnVg==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Length_of_referral_banding = _t, Length_of_referral_banding_order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Length_of_referral_banding", type text}, {"Length_of_referral_banding_order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

