table REF_MetaData
	lineageTag: 3c47f7c8-7786-456b-bb07-d53f6d4a9182

	column Tab
		dataType: string
		lineageTag: 7a89b1a7-ce9a-4433-9d6e-97d821383325
		summarizeBy: none
		sourceColumn: Tab

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: a14dd136-3920-441b-b3e2-60e985a72b0c
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column ConstructionDescription
		dataType: string
		lineageTag: 578759c0-fc30-4e08-985a-608099d5ae90
		summarizeBy: none
		sourceColumn: ConstructionDescription

		annotation SummarizationSetBy = Automatic

	column 'Additional definitions'
		dataType: string
		lineageTag: 0ad9e220-086f-4d1e-9424-8f16d0c9d139
		summarizeBy: none
		sourceColumn: Additional definitions

		annotation SummarizationSetBy = Automatic

	column 'Measure Name'
		dataType: string
		lineageTag: c47dfb08-02a5-4552-8edc-ed1339188490
		summarizeBy: none
		sourceColumn: Measure Name

		annotation SummarizationSetBy = Automatic

	column '.'
		dataType: string
		lineageTag: 672caa88-836b-46b7-b526-39cd00adb76e
		summarizeBy: none
		sourceColumn: .

		annotation SummarizationSetBy = Automatic

	partition REF_MetaData = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZNNT9tAEIb/yquciBoh4ELbW2QMthocFDtFiHBY7DFesdl1d8eJ+PeddQKoVQ+Vknjj+XrmndnHx8lthh93eZjMJulpdvoNxbB9Jg/XInm4w/yFGgy2kTfnXxGGvnee5RV33g0vHYqsRBvtDbZkWRl0pAx3COR3uqYATzXpnbYvUAxDKjDgLKF24l4zTs4vsJVzB++MEb+poFSdDpCPErfBcqTpyfWGoCLQGdjh/BL7zqFTO5Kf5jP9H9lJcyfwjRYOMXloezhP5SRtEHpPO+2GgHeQcApBWFv9axCrYi2NhVmsHGt4asl7afSZeE9kBUbZRmhmH0UbxfRhjiU8RdmiBoGV5zGA5NuT166Z4Qh5rWqKnbXynDEZ6jvpZVYp8wp+6wmt8KsYFZyVqahnM/qHntRr7G2nG3IRIwyGBdxZwWamcT5HuiD6mLcRQbfQvBnOzi4uw4cuEB+ZF79F8gO+CsHVWvFnkkOLMqD/6TL6iqZYxrra1mZoZC9iRCsTd/sY0XsX4X3A9w1v7M1iuU7SskpXZZavUmTpfFFlmBdXSObyP67d9XJdXM2rfFmgWq3LKsZVefIFJ1WaFiXyAskqL/NyGi0P4n2Dv/JGw31elNWyOMhQ4j4vM5wkWbqo0iKb307/hZNIsjJdLHJJWaarn3kypnpfXLlP2GtjYEkki+tFe7gdiTjbcWAkA/J03L73xo/KyCKLSXZT7gJJGh4vWSq5J09PvwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Tab = _t, #"Measure Name" = _t, Description = _t, #"Construction#(lf)Description" = _t, #"Additional definitions" = _t, #"." = _t])
				in
				    Source

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

