table 'A_ Main data'
	lineageTag: d4acce48-a571-4fe0-b58e-54788d89dbc2

	column clientid
		dataType: int64
		formatString: 0
		lineageTag: ae774368-e83c-48f0-9490-a20323e0cfab
		summarizeBy: none
		sourceColumn: clientid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column dateofbirth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9f19ebb0-f5ab-4f5f-b9ad-25257804139e
		summarizeBy: none
		sourceColumn: dateofbirth

		variation Variation
			isDefault
			relationship: 40035302-0252-475a-97df-8710374fe613
			defaultHierarchy: LocalDateTable_6204680e-63e1-443c-ae5e-bb6deaf8aa40.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column referraldate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b327cd32-44d4-4a39-a864-da12d7ac7631
		summarizeBy: none
		sourceColumn: referraldate

		variation Variation
			isDefault
			relationship: dec2bcad-708e-4538-a2cb-4df67121d5f8
			defaultHierarchy: LocalDateTable_fd944bf0-0289-4b40-ba87-efd4edf536d2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column communicationneeds
		dataType: string
		lineageTag: 98256032-c23c-4aac-b805-ce1e31b1f50e
		summarizeBy: none
		sourceColumn: communicationneeds

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column disability
		dataType: string
		lineageTag: 803e1752-c29e-4ad4-bad3-afd34d9ecaff
		summarizeBy: none
		sourceColumn: disability

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column carecategory
		dataType: string
		lineageTag: 3a648e9d-d41c-4c32-82d1-c851fa3bdbfd
		summarizeBy: none
		sourceColumn: carecategory

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column budgetcode
		dataType: string
		lineageTag: 155d7b88-ab0e-4fcb-88ef-7e9ba0e49371
		summarizeBy: none
		sourceColumn: budgetcode

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column nurseassessor
		dataType: string
		lineageTag: a65a41ab-d46f-4573-a9a2-de041cc478ce
		summarizeBy: none
		sourceColumn: nurseassessor

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column casemanager
		dataType: string
		lineageTag: 93166c6e-1049-4424-9f43-d95701348046
		summarizeBy: none
		sourceColumn: casemanager

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column currentgp
		dataType: string
		lineageTag: 41403c27-91cd-4939-9279-6820ec595122
		summarizeBy: none
		sourceColumn: currentgp

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column currentgppracticecode
		dataType: string
		lineageTag: afc5bee7-6d56-4fb8-9dea-b705f35ecbbe
		summarizeBy: none
		sourceColumn: currentgppracticecode

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column originatinggp
		dataType: string
		lineageTag: a4a24044-e16f-47c7-87f5-3e52a27e43cf
		summarizeBy: none
		sourceColumn: originatinggp

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column originatinggppracticecode
		dataType: string
		lineageTag: 8f04462c-a3db-4900-bf77-1db9b19ac7ef
		summarizeBy: none
		sourceColumn: originatinggppracticecode

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column ccgname
		dataType: string
		lineageTag: 377f96b9-aec1-4927-aa90-4dd707ccdec6
		summarizeBy: none
		sourceColumn: ccgname

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column scheduledreviewdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f704c240-8253-4311-a7a6-1c7d7fd3d3f7
		summarizeBy: none
		sourceColumn: scheduledreviewdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column typeofreview
		dataType: string
		lineageTag: add6557c-22ec-4398-aa3e-b6cf4cee4cc8
		summarizeBy: none
		sourceColumn: typeofreview

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column actualreview
		dataType: dateTime
		formatString: Long Date
		lineageTag: 13606ec7-59dd-4968-bd16-0f13a6a6d600
		summarizeBy: none
		sourceColumn: actualreview

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column funderattimeofactualreview
		dataType: string
		lineageTag: 2240257f-2150-4ce7-b813-b5c346978d8e
		summarizeBy: none
		sourceColumn: funderattimeofactualreview

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column reviewoutcomeofactualreview
		dataType: string
		lineageTag: 1711dfab-4f85-4d97-8913-b301c3d26d1b
		summarizeBy: none
		sourceColumn: reviewoutcomeofactualreview

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column paneldate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 18e6473e-39ae-4d78-9dc6-eff441e4a82b
		summarizeBy: none
		sourceColumn: paneldate

		variation Variation
			isDefault
			relationship: 2175ce56-9a83-4d20-95c2-77663adee316
			defaultHierarchy: LocalDateTable_bfc8cfdd-2189-492c-868b-2f208861a581.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column paneloutcome
		dataType: string
		lineageTag: 29db1a5f-1b5e-4c19-8851-a7873f7a959e
		summarizeBy: none
		sourceColumn: paneloutcome

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column panelnotes
		dataType: string
		lineageTag: 4495e7a2-4c3e-4bd3-a663-1388761c08e1
		summarizeBy: none
		sourceColumn: panelnotes

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fundingalert
		dataType: string
		lineageTag: c68b45e8-c6b7-47f9-b440-e8f1be80b281
		summarizeBy: none
		sourceColumn: fundingalert

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fasttrack
		dataType: string
		lineageTag: 75ccc116-3249-4a50-8c06-7e3e7dd11efb
		summarizeBy: none
		sourceColumn: fasttrack

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fasttrackactivationdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 437cf6a6-92a4-4a34-bf4f-fbb5f811a978
		summarizeBy: none
		sourceColumn: fasttrackactivationdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column checklistdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0aaea67-1b2b-44f0-9836-98cdee314f12
		summarizeBy: none
		sourceColumn: checklistdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column dstdate
		dataType: string
		lineageTag: 7ebbfe48-abd9-43ce-842a-a9e89c1ffaf8
		summarizeBy: none
		sourceColumn: dstdate

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column dstsetting
		dataType: string
		lineageTag: 5d7f567f-8aa9-4915-9ae2-6093bf075ae9
		summarizeBy: none
		sourceColumn: dstsetting

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column mdtrecommendation
		dataType: string
		lineageTag: af0f30db-22f9-41a7-aad9-d19103034f55
		summarizeBy: none
		sourceColumn: mdtrecommendation

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column decisiondate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0a88d444-ac44-43cf-bbd6-0043744749b0
		summarizeBy: none
		sourceColumn: decisiondate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column outcome
		dataType: string
		lineageTag: 47761c11-eed2-4b2f-8d94-9fa44b94426f
		summarizeBy: none
		sourceColumn: outcome

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column sourceofreferral
		dataType: string
		lineageTag: 7d2be3ee-a6c4-4c52-b8cf-18bf388e0fe5
		summarizeBy: none
		sourceColumn: sourceofreferral

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column sourceofreferralname
		dataType: string
		lineageTag: d32f80f5-0d28-46e3-a239-6fb929ff58e6
		summarizeBy: none
		sourceColumn: sourceofreferralname

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column negativechecklistdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4e0f8e19-7b01-4a98-afd2-de236ee013a7
		summarizeBy: none
		sourceColumn: negativechecklistdate

		variation Variation
			isDefault
			relationship: 752f2064-010d-4e65-8163-ed203fcc2914
			defaultHierarchy: LocalDateTable_6165a102-dcae-4669-95d3-10cdf34cb7ff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column negativechecklistsourceofreferral
		dataType: string
		lineageTag: 540cb284-17fc-433c-83b1-79a16dede65f
		summarizeBy: none
		sourceColumn: negativechecklistsourceofreferral

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column negativechecklistsourceofreferralname
		dataType: string
		lineageTag: 6e059a9f-1e9a-412f-bfc4-0a21072f550d
		summarizeBy: none
		sourceColumn: negativechecklistsourceofreferralname

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column responsibleauthority
		dataType: string
		lineageTag: de8a20f6-79cd-425a-8123-04fd237714b7
		summarizeBy: none
		sourceColumn: responsibleauthority

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column status
		dataType: string
		lineageTag: 14bbbf52-4dde-4d98-a32b-c84f8f441b8d
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column statussince
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4ee72b2-f329-4449-90a5-30174fcba35f
		summarizeBy: none
		sourceColumn: statussince

		variation Variation
			isDefault
			relationship: e7eb4240-a413-438c-9296-da7213e2f725
			defaultHierarchy: LocalDateTable_18c4fc19-64d6-499e-af85-ca20f869955a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column dateofdeath
		dataType: dateTime
		formatString: Long Date
		lineageTag: 555c0aec-f879-42ad-bdea-cbdaff28de1d
		summarizeBy: none
		sourceColumn: dateofdeath

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column legalstatus
		dataType: string
		lineageTag: 52f75937-5c2d-41c5-b683-effe8a9a7061
		summarizeBy: none
		sourceColumn: legalstatus

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fundername
		dataType: string
		lineageTag: 7a1995fa-136a-4d15-8629-c47b4e692071
		summarizeBy: none
		sourceColumn: fundername

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fundersince
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5753fb87-8afb-41fb-96ee-f0a03ffd07d3
		summarizeBy: none
		sourceColumn: fundersince

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden","FormatString"]

		annotation UnderlyingDateTimeDataType = Date

	column funderend
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4dd1e44f-5cfc-4c09-9101-9d4f432dcaec
		summarizeBy: none
		sourceColumn: funderend

		variation Variation
			isDefault
			relationship: a1b1e7c6-cf1f-431a-8795-90f80497cd2a
			defaultHierarchy: LocalDateTable_f25716d7-894f-4382-9d0d-745c0bdfde92.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column fundersplit
		dataType: string
		lineageTag: 55431c49-0073-4ba2-8b4c-6cd214aa81c3
		summarizeBy: none
		sourceColumn: fundersplit

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column extractdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: fe49f414-c558-4a26-a934-564e34433c2e
		summarizeBy: none
		sourceColumn: extractdate

		variation Variation
			isDefault
			relationship: ed7a3bea-3482-4523-9013-1cd8463c3b40
			defaultHierarchy: LocalDateTable_de1172f4-36d0-4b00-ba4c-886634560d53.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column filename
		dataType: string
		lineageTag: ce3d559c-1e50-4e73-adca-2102a8dce83b
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column agreementid
		dataType: string
		lineageTag: b0300507-98c0-45dc-8737-dc4029ae47ed
		summarizeBy: none
		sourceColumn: agreementid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column last_updated
		dataType: dateTime
		formatString: General Date
		lineageTag: ef21f705-10e3-42c7-96d4-8568747ee909
		summarizeBy: none
		sourceColumn: last_updated

		variation Variation
			isDefault
			relationship: 7cabe029-fec3-4cf3-963b-455a6356214b
			defaultHierarchy: LocalDateTable_58388e71-b249-4a9d-8a2a-7a43dcf88ae1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7dbb2133-d4bb-482c-93d6-65c369072821
		summarizeBy: none
		sourceColumn: deleted

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Review Outstanding' =
			
			IF (
			    'A_ Main data'[scheduledreviewdate]
			        < TODAY (),
			    1,
			    0
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: 7aa12eb9-4550-4ed3-8a9b-2dcb455dedab
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'RIP Days' =
			
			IF (
			    DATEDIFF (
			        'A_ Main data'[fasttrackactivationdate],
			        'A_ Main data'[dateofdeath],
			        DAY
			    ) > ( 12 * 7 ),
			    1,
			    0
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: a9040b5c-cf62-46f1-8162-e306340f5781
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Reviews in time' =
			
			IF (
			    'A_ Main data'[scheduledreviewdate] > 'A_ Main data'[actualreview],
			    1,
			    0
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: df99a5fc-466f-4de7-a2ec-9e5784f5b5da
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Days Over' =
			
			IF (
			    'A_ Main data'[scheduledreviewdate] < 'A_ Main data'[actualreview],
			    DATEDIFF (
			        'A_ Main data'[scheduledreviewdate],
			        'A_ Main data'[actualreview],
			        DAY
			    ),
			    BLANK ()
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: 970f7592-aa21-4e0c-b11d-8b91a51e8a32
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Negative checklists closed to ccg numbers' =
			
			IF (
			    'A_ Main data'[status] = "Closed"
			        && 'A_ Main data'[statussince]
			            < EDATE (
			                'A_ Main data'[negativechecklistdate],
			                1
			            ),
			    1,
			    0
			)
		formatString: 0
		displayFolder: _DAX_Columns
		lineageTag: e1a9214e-fe14-4474-9968-a9e8c423cbc1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'RIP Groups' =
			
			SWITCH (
			    TRUE (),
			    ISBLANK ( 'A_ Main data'[dateofdeath] ), "Alive",
			    DATEDIFF (
			        'A_ Main data'[fasttrackactivationdate],
			        'A_ Main data'[dateofdeath],
			        DAY
			    ) < 28, "Within 28 Days",
			    DATEDIFF (
			        'A_ Main data'[fasttrackactivationdate],
			        'A_ Main data'[dateofdeath],
			        DAY
			    ) < 56, "Within 56 Days",
			    DATEDIFF (
			        'A_ Main data'[fasttrackactivationdate],
			        'A_ Main data'[dateofdeath],
			        DAY
			    ) < ( 12 * 7 ), "Within 12 Weeks",
			    "Over 12 Weeks"
			)
		displayFolder: _DAX_Columns
		lineageTag: 5fdea09a-5149-46d0-9398-248c163b8a62
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Fundersince2 = DATE(year('A_ Main data'[fundersince]), month('A_ Main data'[fundersince]), day('A_ Main data'[fundersince]))
		formatString: Long Date
		lineageTag: 4f328e42-b7b3-4961-a30f-14229cd0e60b
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 9060a897-2bb2-45c8-9c92-0cc4c0948d10
			defaultHierarchy: LocalDateTable_a2ad3b3a-ccd0-4231-8d01-a438862b62cf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["DataType"]

	column Column = RELATED(Ids_Aggregation[Age])
		lineageTag: f44053ef-a4c3-4fa8-93af-ccbe8301155f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'A_ Main data-a806cba9-a52b-4c48-9145-b4c790083891' = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    vw_a_201_load1 = data_mart_pid_011_chs_continuinghealthcare{[Name="vw_a_201_load"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vw_a_201_load1,{{"checklistdate", type date}, {"dateofbirth", type date}, {"referraldate", type date}, {"scheduledreviewdate", type date}, {"paneldate", type date}, {"statussince", type date}, {"dateofdeath", type date}, {"fundersince", type date}, {"funderend", type date}, {"extractdate", type date}, {"actualreview", type date}}),
				    Custom1 = Table.SelectRows(#"Changed Type", each Date.IsInCurrentYear([funderend])  or Date.IsInPreviousNYears([funderend], 3) or [funderend] = null),
				    #"Changed Type1" = Table.TransformColumnTypes(Custom1,{{"decisiondate", type date}, {"fasttrackactivationdate", type date}, {"negativechecklistdate", type date}, {"clientid", Int64.Type}, {"fundersince", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

