table Appeals
	lineageTag: f0b190bb-484d-444d-8ffb-7ebe1b6928ea

	column clientid
		dataType: int64
		formatString: 0
		lineageTag: c96a58f9-b57d-49ca-9dc6-0c605be18c02
		summarizeBy: sum
		sourceColumn: clientid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column episodeid
		dataType: int64
		formatString: 0
		lineageTag: 7bc20578-4fdb-4f8e-8c78-4d85a4faad07
		summarizeBy: sum
		sourceColumn: episodeid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column activationdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 378bf18c-4f9f-4a6f-bf8b-a11700600194
		summarizeBy: none
		sourceColumn: activationdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column description
		dataType: string
		lineageTag: 119d6976-9867-4857-8fb9-8283fb64d8f7
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column type
		dataType: string
		lineageTag: 6ba09320-4ed4-4eac-84a6-4f6c019e7bb2
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column progress
		dataType: string
		lineageTag: 8adb444f-9d7a-416e-b614-7f047c6a7400
		summarizeBy: none
		sourceColumn: progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column appealsmanager
		dataType: string
		lineageTag: 8d89f9dd-d331-4719-a4db-aad6eaecf53b
		summarizeBy: none
		sourceColumn: appealsmanager

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column outcome
		dataType: string
		lineageTag: 903d0f8d-e15f-4298-9b89-f78a8f9a2b49
		summarizeBy: none
		sourceColumn: outcome

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column appealperiodfrom
		dataType: dateTime
		formatString: Long Date
		lineageTag: e3d9e3e7-4c35-417e-bb42-2a3ffc0a859f
		summarizeBy: none
		sourceColumn: appealperiodfrom

		variation Variation
			isDefault
			relationship: 6b45e8fa-475b-4a8e-8824-3eb7506dac05
			defaultHierarchy: LocalDateTable_4c0f3cc9-dd8f-4e66-a3d9-2df5d58e640f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column appealperiodto
		dataType: dateTime
		formatString: Long Date
		lineageTag: 573e0f9c-d94c-479e-9e2b-548ec3275c6b
		summarizeBy: none
		sourceColumn: appealperiodto

		variation Variation
			isDefault
			relationship: cb9b4c06-34df-41b4-9e0f-04307dbe2e21
			defaultHierarchy: LocalDateTable_73b26740-4c7a-4a14-9b51-0655f0ba79e4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column valueperweek
		dataType: double
		lineageTag: 6ea5f542-8b14-434b-861c-56a25d96eee5
		summarizeBy: sum
		sourceColumn: valueperweek

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation PBI_ChangedProperties = ["IsHidden"]

	column totalvalue
		dataType: double
		lineageTag: 62bea7bf-8360-4c0f-82b4-89fc1994e44f
		summarizeBy: sum
		sourceColumn: totalvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation PBI_ChangedProperties = ["IsHidden"]

	column questionnaire
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4452266a-6125-469a-af99-25e6176fab2d
		summarizeBy: none
		sourceColumn: questionnaire

		variation Variation
			isDefault
			relationship: 06ecb59c-dcfd-4338-82a7-2ee5a6b0b249
			defaultHierarchy: LocalDateTable_6f383fe0-0d7b-445d-9314-04a7778688a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column checklist
		dataType: dateTime
		formatString: Long Date
		lineageTag: c16a9124-b96f-49ef-9d0f-201da40ad93a
		summarizeBy: none
		sourceColumn: checklist

		variation Variation
			isDefault
			relationship: ba27c43f-9fa9-4461-8b56-fd76b3eb21b1
			defaultHierarchy: LocalDateTable_0f8152b5-b2e8-4499-838c-57813cfb7ed8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column dst
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e1e53fd-6b11-407a-b1db-62c1ad67d897
		summarizeBy: none
		sourceColumn: dst

		variation Variation
			isDefault
			relationship: 67e1931a-acba-4eab-832d-6cb7aeb219cc
			defaultHierarchy: LocalDateTable_4ed14252-9b41-42ee-9004-901cb1e289bb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column decision
		dataType: dateTime
		formatString: Long Date
		lineageTag: a215008d-78f8-4a89-ac00-5481a30ef54b
		summarizeBy: none
		sourceColumn: decision

		variation Variation
			isDefault
			relationship: 88aaf649-e376-41db-bbd4-746ed488f86a
			defaultHierarchy: LocalDateTable_ee696491-ea5e-44ca-a90c-d9c132319a2d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column eligibledatefrom
		dataType: dateTime
		formatString: Long Date
		lineageTag: 58c61ed6-1f2c-4f86-8b06-a0e51c9d82d1
		summarizeBy: none
		sourceColumn: eligibledatefrom

		variation Variation
			isDefault
			relationship: 5f1604d0-20f9-49b4-8392-d0290bfcb5d1
			defaultHierarchy: LocalDateTable_22e12c3f-ba37-4f23-b793-5176307a736f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column eligibledateto
		dataType: dateTime
		formatString: Long Date
		lineageTag: ecea1f84-a6e2-4730-8b48-98e39d8bade3
		summarizeBy: none
		sourceColumn: eligibledateto

		variation Variation
			isDefault
			relationship: 6319f077-c1d3-4b97-821d-72dbf470feca
			defaultHierarchy: LocalDateTable_901973c9-1932-46fb-834b-e63d67b3fa6d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column eligiblevalueperweek
		dataType: double
		lineageTag: df709b9e-5593-4286-a89f-f049b9126a49
		summarizeBy: sum
		sourceColumn: eligiblevalueperweek

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation PBI_ChangedProperties = ["IsHidden"]

	column eligibletotalvalue
		dataType: double
		lineageTag: b66f530b-4a14-406d-a962-10307cd5837e
		summarizeBy: sum
		sourceColumn: eligibletotalvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation PBI_ChangedProperties = ["IsHidden"]

	column extractdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 730317bb-7acb-4e3d-ab61-3f40a8076f68
		summarizeBy: none
		sourceColumn: extractdate

		variation Variation
			isDefault
			relationship: 0751f543-e523-4738-82a8-b141c65dbab8
			defaultHierarchy: LocalDateTable_6240cceb-f7d9-49ec-933d-755ebae10b0f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["IsHidden"]

	column filename
		dataType: string
		lineageTag: 65b0931a-f70f-4a64-ab91-2739d5ec2c4d
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column agreementid
		dataType: string
		lineageTag: ae029a34-2247-4f42-8ab1-82e7fefebc4e
		summarizeBy: none
		sourceColumn: agreementid

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column last_updated
		dataType: dateTime
		formatString: General Date
		lineageTag: 96f0cd49-4c19-47e3-ae92-6aec3050c09b
		summarizeBy: none
		sourceColumn: last_updated

		variation Variation
			isDefault
			relationship: 1de1d934-a0f8-4f60-afdf-ed2c5976769f
			defaultHierarchy: LocalDateTable_98994bc7-a0f4-4616-a32a-682c5745858a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f9c76150-6515-40ca-9941-a9e04fbd2efa
		summarizeBy: none
		sourceColumn: deleted

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column Stage =
			
			SWITCH (
			    TRUE (),
			    Appeals[type] = "Appeal", "Stage 2",
			    Appeals[type] = "IRP", "Stage 3",
			    Appeals[type] = "PUPOC", "PUPOC"
			)
		displayFolder: _DAX_Columns
		lineageTag: 30aa8afd-05fd-4d84-8cc2-0603e3afa05d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	column Resolutions =
			
			IF (
			    Appeals[Stage] = "Stage 2"
			        || Appeals[Stage] = "Stage 3"
			        || Appeals[type] = "PUPOC",
			    IF (
			        Appeals[decision]
			            = BLANK (),
			        "Outstanding",
			        "Complete"
			    ),
			    ""
			)
		displayFolder: _DAX_Columns
		lineageTag: a32a5b55-e157-4fac-809c-726714f9911d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	partition Appeals-caa0893f-e175-4952-a69b-3a5441f78848 = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("redshift-cluster-2.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5439","dw01"),
				    data_mart_pid_011_chs_continuinghealthcare = Source{[Name="data_mart_pid_011_chs_continuinghealthcare"]}[Data],
				    vw_app_201_load1 = data_mart_pid_011_chs_continuinghealthcare{[Name="vw_app_201_load"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vw_app_201_load1,{{"activationdate", type date}, {"appealperiodfrom", type date}, {"appealperiodto", type date}, {"questionnaire", type date}, {"checklist", type date}, {"dst", type date}, {"decision", type date}, {"eligibledatefrom", type date}, {"eligibledateto", type date}, {"extractdate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

