table REF_Gender
	lineageTag: 5e5ecc82-8fc8-44b2-81f0-35861e42a3f9

	column Gender_Code
		dataType: string
		lineageTag: 42ac6be0-bd13-41c3-9fdb-b4304e071a56
		summarizeBy: none
		sourceColumn: Gender_Code

		annotation SummarizationSetBy = Automatic

	column Gender_Description
		dataType: string
		lineageTag: 164855f9-f13c-4cf5-ac27-8e5e62fad170
		summarizeBy: none
		sourceColumn: Gender_Description

		annotation SummarizationSetBy = Automatic

	column Gender_for_GP_Populations
		dataType: string
		lineageTag: 7ade132c-8cd8-473c-8380-6a91a69cf313
		summarizeBy: none
		sourceColumn: Gender_for_GP_Populations

		annotation SummarizationSetBy = Automatic

	partition REF_Gender = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select distinct gender_code as ""Gender_Code"", gender_description as ""Gender_Description"", cast(NULL as varchar(50)) as ""Gender_for_GP_Populations"" from data_mart_powerbi_mentalhealth.tbl02_mhsds_mh_inpatients where gender_code is not null union select distinct gender_code, gender_description, cast(NULL as varchar(50)) from data_mart_powerbi_mentalhealth.tbl01_mhsds_mh_referrals where gender_code is not null union select distinct gender_code, gender_description, cast(NULL as varchar(50)) from data_mart_powerbi_mentalhealth.tbl03_mhsds_mh_contacts where gender_code is not null", null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Gender_Description] <> "Female" and [Gender_Description] <> "Male"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

