table REF_Commissioner
	lineageTag: 20f505d3-3ea1-45cb-8f77-08956300aa89

	column Commissioner_Code
		dataType: string
		lineageTag: f60d73ef-854b-4d6d-b4de-ab6dff468da5
		summarizeBy: none
		sourceColumn: Commissioner_Code

		annotation SummarizationSetBy = Automatic

	column Commissioner_Description
		dataType: string
		lineageTag: 4955879a-a19b-4b22-a7ba-3685a08842f4
		summarizeBy: none
		sourceColumn: Commissioner_Description

		annotation SummarizationSetBy = Automatic

	column Provider_Type
		dataType: string
		lineageTag: 8e384c4f-b78e-4a75-82f0-efea6f0fb5c7
		summarizeBy: none
		sourceColumn: Provider_Type

		annotation SummarizationSetBy = Automatic

	column Provider_Group
		dataType: string
		lineageTag: 64e529fa-e5c3-4a33-bda3-01d4534ae13f
		summarizeBy: none
		sourceColumn: Provider_Group

		annotation SummarizationSetBy = Automatic

	column Commissioner_Group
		dataType: string
		lineageTag: a3caf31b-9793-44af-8410-e683d15e83db
		summarizeBy: none
		sourceColumn: Commissioner_Group

		annotation SummarizationSetBy = Automatic

	partition REF_Commissioner = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select p.code as ""Provider_Code"", p.name as ""Provider_Description"", p.ods_api_role_name as ""Provider_Type"", case when p.code like 'RTQ%' then p.name when p.ods_api_role_name = 'NHS TRUST' then 'OTHER NHS TRUSTS' when p.ods_api_role_name = 'INDEPENDENT SECTOR H/C PROVIDER SITE' then 'INDEPENDENT SECTOR HEALTHCARE PROVIDER' else p.ods_api_role_name end as ""Provider_Group"", case when p.code in ('11M','QR1') then 'NHS GLOUCESTERSHIRE ICB - 11M' when p.code is null then null else 'All Other Commissioners' end as ""Commissioner_Group"" from dscro_national_lookups.ods_all_codes as p", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Provider_Code", "Commissioner_Code"}, {"Provider_Description", "Commissioner_Description"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

