table REF_Date_Ref
	lineageTag: a411c1ac-5bb7-4e1b-8d7d-1ac32e5fa4e9
	dataCategory: Time

	measure Latest_Reporting_Month_Year_Text =
			
			FORMAT(CALCULATE(
			MAX(REF_Date_Ref[date])
			,ALL(REF_Date_Ref)),"MMMM YYYY")
		lineageTag: 862b25e7-1aef-481e-8481-2d5411fd06f0

	measure Latest_Updated_Date_Text = ```
			
			FORMAT(
			    CALCULATE(MAX(REF_Date_Ref[Last_Updated])),
			    "DD/MM/YYYY HH:mm"
			)
			
			```
		lineageTag: c12a602f-1831-4725-b523-a89c06f2fe93

	column date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 4a0cb97a-3e1a-4af5-b433-89691c45212b
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: adf48597-5e58-41f2-b80c-1b72722d8e4c
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: cd43c0be-6ca1-46bf-ae13-9e6c14ad930e
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 95e1289f-b9fb-41cd-8bd3-27f7a8e49dbe
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: dec4b1f1-f8b2-483f-9029-06f64441cedf
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 4ba71a0b-c53b-4981-841a-b67722e5fe9f
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 1c50f4e8-64eb-4ccf-8ce0-28efcd051320
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 35f60cb8-5000-4333-a774-3923fcde2c42
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: f4c92099-072a-4650-ac95-a64fba5985b4
		summarizeBy: sum
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 99565d2f-4bd8-4f92-b4e1-066518216c81
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: d9b69520-8911-473e-9bb2-382a1dc791ef
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 60a6393c-11dd-4a57-82a9-762d1c4f4a52
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 185cb86c-5aae-42b9-992d-3eec288488a9
		summarizeBy: none
		sourceColumn: financial_year
		sortByColumn: Date_Order_Financial_Year

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: d2100c17-4e2b-42aa-bd69-8780ae79f8c9
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 2299f83a-27fe-44d6-9145-545db2a7c753
		summarizeBy: sum
		sourceColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: MMMM YYYY
		lineageTag: a283f6f0-71aa-4841-9917-10158a415ff6
		summarizeBy: none
		sourceColumn: Last_Updated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Data_up_to
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d200216a-051c-4b16-9e01-08ad203ff621
		summarizeBy: none
		sourceColumn: Data_up_to

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Reporting_Month_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2d3116e1-d297-4c0d-94cd-fb5915e04e90
		summarizeBy: sum
		sourceColumn: Reporting_Month_Flag

		annotation SummarizationSetBy = Automatic

	column Date_Order
		dataType: int64
		formatString: 0
		lineageTag: 16794060-639b-4d96-85bf-af89edf132f7
		summarizeBy: sum
		sourceColumn: Date_Order

		annotation SummarizationSetBy = Automatic

	column Date_Order_Financial_Year
		dataType: int64
		formatString: 0
		lineageTag: 06003db1-384b-46bb-976a-041a1562c334
		summarizeBy: sum
		sourceColumn: Date_Order_Financial_Year

		annotation SummarizationSetBy = Automatic

	column Month_Number = RANKX( ALL( 'REF_Date_Ref' ), 'REF_Date_Ref'[year_month], , ASC, Dense)
		formatString: 0
		lineageTag: 17223df6-aa57-498d-b42d-0bc5c11d25ad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column FirstDayOfMonth
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 7514847a-860c-49ad-8461-0f0724899430
		summarizeBy: none
		sourceColumn: FirstDayOfMonth

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column FirstDayofFinancialYear
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: e1b023e6-0495-49ae-ab2d-d65ec1c2634a
		summarizeBy: none
		sourceColumn: FirstDayofFinancialYear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition REF_Date_Ref = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "CCG_Reference", [Query="#(lf)#(tab)set nocount on#(lf)#(lf)#(tab)/*------------------------------------------------------------#(lf)#(tab)Declare Variables #(lf)#(tab)/-------------------------------------------------------------*/#(lf)#(tab)#(tab)declare @end_date as date#(lf)#(tab)declare @reporting_month as int#(lf)    DECLARE @max_data_date date#(lf)#(tab)declare @max_population_over_time_census date;#(lf)#(lf)select   @max_data_date =  MAX( CAST(r.Referral_Recieved_Date AS date))#(lf)FROM PowerBI_Reporting.mentalhealth.tbl01_MHSDS_MH_Referrals as r#(lf)WHERE cast(r.Referral_Recieved_Date as date) <= CAST(getdate() as date);#(lf)#(lf)select @max_population_over_time_census = EOMONTH(MAX(cast(p.Census_Date as date)))#(lf)FROM PowerBI_Reporting.AgeingWell.tbl02_Proactive_Whiteboard_Registered_Population_Over_Time as p#(lf)WHERE cast(p.Census_Date as date) <= CAST(getdate() as date);#(lf)#(lf)IF @max_data_date IS NULL#(lf)    THROW 51000, 'No data found in MHSDS Referral view (max date is NULL).', 1;#(lf)#(lf)#(lf)IF @max_population_over_time_census  < @max_data_date#(lf)    THROW 51000, 'Population over time table not in line with MHSDS data - CHECK!', 1;#(lf)#(lf)-- Latest complete month end:#(lf)-- if max date is month-end => that month is complete#(lf)-- else => use previous month end#(lf)SET @end_date =#(lf)    CASE#(lf)        WHEN @max_data_date = EOMONTH(@max_data_date) THEN @max_data_date#(lf)        ELSE EOMONTH(@max_data_date, -1)#(lf)    END;#(lf)#(lf)#(lf)#(tab)----------------------------------------------#(lf)#(tab)--Get the latest reporting month#(lf)#(tab)----------------------------------------------#(lf)#(lf)#(tab)set @reporting_month = #(lf)#(lf)#(tab)(select d.FinancialMonth#(lf)#(lf)#(tab)from #(lf)#(lf)#(tab)(select   [latest_date] = @end_date) as o #(lf)  #(lf)#(tab)  left join    [CCG_Reference].[Reference].[vw_DateLookup] as d on d.Date = o.latest_date)#(lf)#(lf)#(lf)#(tab)  ----------------------------------------------#(lf)#(tab)--Get the latest reporting month#(lf)#(tab)----------------------------------------------#(lf)#(tab) if object_id ('tempdb..#FY_order') is not null drop table #FY_order#(lf)#(lf)#(tab)select FY.financial_year#(lf)#(tab),[Financial_Year_Order] = row_number () over (order by fy.[First_date_in_FY] asc)#(lf)#(lf)#(tab)into #FY_order#(lf)#(lf)#(tab)from #(lf)#(tab)(SELECT   financial_year,[First_date_in_FY] = min(date)#(lf)#(tab)FROM CCG_Reference.Reference.vw_Date as d#(lf)#(tab)where [Date] between '20220401' and  @end_date#(lf)#(tab)group by financial_year) as fy#(lf)#(lf)#(lf)#(tab)  ----------------------------------------------#(lf)#(tab)--Create final output reference table#(lf)#(tab)----------------------------------------------#(lf)#(lf)#(tab)select #(lf)#(lf)#(tab)[Date_Order] = row_number ()  over ( order by date asc)#(lf)#(tab),[Date_Order_Financial_Year] = fyo.[Financial_Year_Order]#(lf)#(tab),[date] = d.date#(lf)#(tab)   ,[day_month_year] = d.day_month_year#(lf)#(tab)#(tab)  , [day] = d.day#(lf)#(tab)#(tab)  ,[weekday] = d.weekday#(lf)#(tab)#(tab)  ,[weekday_name]#(lf)#(tab)#(tab)  ,[month]#(lf)#(tab)#(tab) ,[month_name] = left(d.month_name,3)#(lf)#(tab)#(tab)  ,[Quarter] [quarter]#(lf)#(tab)#(tab)  , [year_month] = d.year_month#(lf)#(tab)#(tab)  ,[is_weekend] = d.is_weekend#(lf)#(tab)#(tab)  ,[is_holiday] = d.is_holiday#(lf)#(tab)#(tab)  ,[financial_week_of_year] = d.financial_week_of_year#(lf)#(tab)#(tab)  ,[financial_year] = d.financial_year#(lf)#(tab)#(tab)  ,[financial_quarter] =d.financial_quarter#(lf)#(tab)#(tab)  ,[financial_month] = d.financial_month #(lf)#(tab)#(tab)  ,[Last_Updated] = getdate()#(lf)#(tab)#(tab)  ,[Data_up_to] =  @end_date#(lf)#(tab)#(tab)  ,[Reporting_Month_Flag] = case when d.financial_month <= @reporting_month then 1 else 0 end #(lf)#(tab)#(tab)  ,[FirstDayOfMonth] = cast(DATEFROMPARTS(YEAR([Date]), MONTH([Date]), 1) as date)#(lf)#(tab)#(tab)  ,[FirstDayofFinancialYear] =    CASE #(lf)        WHEN MONTH([Date]) >= 4 THEN DATEFROMPARTS(YEAR([Date]), 4, 1)#(lf)        ELSE DATEFROMPARTS(YEAR([Date]) - 1, 4, 1)#(lf)    END #(lf)#(lf)#(lf)#(tab)from CCG_Reference.Reference.vw_Date as d#(lf)#(tab)LEFT JOIN #FY_order as fyo on d.financial_year = fyo.financial_year COLLATE SQL_Latin1_General_CP1_CI_AS#(lf)#(lf)#(lf)#(tab)where d.date between '20220401' and   @end_date#(lf)#(lf)#(lf)#(tab)order by d.date#(lf)#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"day_month_year", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

