table REF_MetaData
	isHidden
	lineageTag: 3c47f7c8-7786-456b-bb07-d53f6d4a9182

	column Tab
		dataType: string
		isHidden
		lineageTag: 7a89b1a7-ce9a-4433-9d6e-97d821383325
		summarizeBy: none
		sourceColumn: Tab

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		isHidden
		lineageTag: a14dd136-3920-441b-b3e2-60e985a72b0c
		summarizeBy: none
		sourceColumn: Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ConstructionDescription
		dataType: string
		isHidden
		lineageTag: 578759c0-fc30-4e08-985a-608099d5ae90
		summarizeBy: none
		sourceColumn: ConstructionDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Additional definitions'
		dataType: string
		isHidden
		lineageTag: 0ad9e220-086f-4d1e-9424-8f16d0c9d139
		summarizeBy: none
		sourceColumn: Additional definitions

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Measure Name'
		dataType: string
		isHidden
		lineageTag: c47dfb08-02a5-4552-8edc-ed1339188490
		summarizeBy: none
		sourceColumn: Measure Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '.'
		dataType: string
		isHidden
		lineageTag: 672caa88-836b-46b7-b526-39cd00adb76e
		summarizeBy: none
		sourceColumn: .

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition REF_MetaData = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jVNNb9swDP0rRE4JlhpJL912M1y1NpY4ReS0KJoeVJuJBciSJ8nO8u9HOR/FtssAf1Ai9fj4SL29jZYp/HjK3Gg6YlEafYO8az7QgtlB8voE8R4r6HRFO/Ov4Lq2NdbTlq+t6fY15CmHXfBX0KD2QkGNQvkaHNpelujAYomyl3oPwoNC4TyA0QilofDSw3h+Cw3ZNVijFMVNiEpRSwf0CArrtA9sWjStQhCB0Ay8gfkdHGoDteiRPtUn/B/oKH1N5CtJPMhlQeqTPSGLykBoLfbSdA4uRFwERGGj5c+OvMJLKsxNQ+aQw+IOraVCP9AfEDWREboiNtNr0kp4vLpDCotBtqCB88L64QDS26KVpppCrFQ47DrlKZ3RpGVZCy1dA/7YkogY7SN4ECXeeHMT/tMCFbY1lTpYDVaylLQghh6HdpzJOJJDHYeMcgfSb7vZ7PbOXWUAiqH2+GMgemIrnDOlFP4T5FQR9eN/igqxLmK/StVVRJ01QqrByZf8yiqCVaAl9TkqAO6o/+YQAFtrekkz5+D7Vj8uVpuE8YKteZqtGaQsXhQpxPk9JDGtwwg+rDb5fVxkqxyK9YYXW11kyRcYF4zlHLIcknXGMz7Z6leKfIS/MLf6Jct5scpP6nB4yXgK4yRli4Llabyc/EsjISDOFouM4DhbP2cJwVxGl24UHCR1VSOpGAYMD2B6JL0aDMOL1GyL5/m7FHtWg0aZXDSddBuQYPxwzRhhj97ffwM=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Tab = _t, #"Measure Name" = _t, Description = _t, #"Construction#(lf)Description" = _t, #"Additional definitions" = _t, #"." = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Tab", type text}, {"Measure Name", type text}, {"Description", type text}, {"Construction#(lf)Description", type text}, {"Additional definitions", type text}, {".", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

