table 'REF LoS Date Table'
	lineageTag: 27c5a240-1d78-46d9-bd79-e7772992304c

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9d77ad95-a0e0-4361-8f87-210af9302405
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: f43f8ff8-ad23-43ad-bb51-a9f3b62e16b5
			defaultHierarchy: LocalDateTable_93269ec7-405c-4a6c-9dbd-91454bff804e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: string
		lineageTag: bfc71c00-ecd8-4e2e-a218-226c34827c78
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: bbb16f04-d2d0-46db-8846-139c4f05a35e
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 569c4787-5d44-422e-90a6-88460e2cdf8b
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 8edfde4c-027d-4aaf-90e5-9c68616a14d9
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: e9378bc1-bc5e-43f5-ad38-a2a093ed8998
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: a4c31569-9a07-425b-94fc-36e91a9030d6
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 95ced5aa-0285-4c62-81f2-0257c109c29f
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 8a15e559-60cb-473e-871d-83503e07bd55
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 26c6e63c-5a21-4c0e-9648-a16c8ee33d73
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c2b56bc4-9dc9-4c21-893e-a5e12536f3e7
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: cf41acb4-6e21-4108-a012-36c51d3fff4c
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 06ffc798-1ad1-44e5-830d-d44913117362
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 04e22929-aa2d-4083-af0b-95fd6df875f8
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 0b8ea570-cf26-474d-a007-50bb9cb700da
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column financial_quarter_name
		dataType: string
		lineageTag: e7332800-58a8-4822-83d0-52928d5244af
		summarizeBy: none
		sourceColumn: financial_quarter_name

		annotation SummarizationSetBy = Automatic

	column year_quarter
		dataType: string
		lineageTag: 05cb2c8c-ecb9-41c0-8721-2ccea15e8343
		summarizeBy: none
		sourceColumn: year_quarter

		annotation SummarizationSetBy = Automatic

	column financial_quarter_counter
		dataType: int64
		formatString: 0
		lineageTag: 521527a9-baa1-4f08-859e-c8dbc9d62d56
		summarizeBy: sum
		sourceColumn: financial_quarter_counter

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 81714b9a-e5af-4394-9182-31c1bf07527d
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column ytd_description
		dataType: string
		lineageTag: d54c66df-56fb-421a-a76b-ddbbd357a2a0
		summarizeBy: none
		sourceColumn: ytd_description

		annotation SummarizationSetBy = Automatic

	column Current_FY
		dataType: string
		lineageTag: 3ea4c1ad-130f-4644-bb94-31f774c9873b
		summarizeBy: none
		sourceColumn: Current_FY

		annotation SummarizationSetBy = Automatic

	column Last_FY
		dataType: string
		lineageTag: 91b48dde-53d8-4cbd-abe9-90f509046348
		summarizeBy: none
		sourceColumn: Last_FY

		annotation SummarizationSetBy = Automatic

	column Current_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: 50ecbeda-2f3b-42f2-9eb0-04f507221f20
		summarizeBy: sum
		sourceColumn: Current_FY_Flag

		annotation SummarizationSetBy = Automatic

	column Last_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: 9a9a3157-6dfe-47d2-8a62-13d39b2c1e92
		summarizeBy: sum
		sourceColumn: Last_FY_Flag

		annotation SummarizationSetBy = Automatic

	partition 'REF LoS Date Table' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select a.date as ""date"", a.daymonthyear as ""day_month_year"", a.day as ""day"", a.weekday as ""weekday"", a.weekdayname as ""weekday_name"", a.month as ""month"", left(a.monthname,3) as ""month_name"", a.quarter as ""quarter"", a.yearmonth as ""year_month"", a.isweekend as ""is_weekend"", a.isholiday as ""is_holiday"", a.financialweekofyear as ""financial_week_of_year"", a.financialyear as ""financial_year"", a.financialquarter as ""financial_quarter"", a.financialmonth as ""financial_month"", case when a.financialquarter=1 then 'Quarter 1' when a.financialquarter=2 then 'Quarter 2' when a.financialquarter=3 then 'Quarter 3' when a.financialquarter=4 then 'Quarter 4' end as ""financial_quarter_name"", concat(concat(substring(a.financialyear,3,2), substring(a.financialyear,6,2)), a.financialquarter) as ""year_quarter"", dense_rank() over (order by concat(concat(substring(a.financialyear,3,2), substring(a.financialyear,6,2)), a.financialquarter)) as ""financial_quarter_counter"", case when a.financialmonth <= (select cast(financialmonth as int) from ccg_reference.vw_datelookup where date = last_day(dateadd(month,-2,current_date))) then 1 else 0 end as ""ytd_flag"", case when a.financialmonth <= (select cast(financialmonth as int) from ccg_reference.vw_datelookup where date = last_day(dateadd(month,-2,current_date))) then 'Year to Date' else '' end as ""ytd_description"", (select financialyear from ccg_reference.vw_datelookup where date = current_date) as ""Current_FY"", (select max(financialyear) from ccg_reference.vw_datelookup where left(financialyear,4) = cast((select left(financialyear,4)::int from ccg_reference.vw_datelookup where date=current_date) - 1 as varchar)) as ""Last_FY"", case when (select financialyear from ccg_reference.vw_datelookup where date = current_date) = a.financialyear then 1 else 0 end as ""Current_FY_Flag"", case when (select max(financialyear) from ccg_reference.vw_datelookup where left(financialyear,4) = cast((select left(financialyear,4)::int from ccg_reference.vw_datelookup where date=current_date) - 1 as varchar)) = a.financialyear then 1 else 0 end as ""Last_FY_Flag"" from ccg_reference.vw_datelookup a where a.date >= '2019-04-01' and a.date <= last_day(dateadd(month,-1,current_date))", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

