table 'REF date_table'
	lineageTag: e7d617bd-015d-4672-aac2-ea2f6d63e706

	column date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3032d405-5278-4d3f-9c25-73bcc23055b0
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 9970f0e3-acd4-4524-af04-057aa66db489
			defaultHierarchy: LocalDateTable_227861b1-2555-4dad-819d-748b728ad2bc.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column day_month_year
		dataType: string
		lineageTag: 1073026e-19c4-46b7-859b-30d38b923d1e
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: a17c74c1-1ae2-4d4c-9e8b-d6a0ae26a2a5
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: f46bca79-c3ac-4e74-8b05-6d7f97f51fbc
		summarizeBy: sum
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: 07bd0f79-449f-4d0d-a881-20fdee55f049
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 8304aea5-c08b-412f-95fa-aa0b2fc770a5
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: a92f7ffa-b3d6-4142-a472-864139faee68
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: dd6add1f-419c-4c0e-abe3-bf25ca2a824f
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: bf7de1bf-9c7a-47a4-80f4-e90e5fe3130e
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 91ebbebf-c40b-457c-8844-a926ff416396
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: f4289367-1ef2-4237-9277-648ac6696fd2
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 41cbcf41-5c37-4e73-b180-4b1a3b79c728
		summarizeBy: sum
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: faa9a3a3-2828-4ac9-8eaf-2a4bf0a83add
		summarizeBy: none
		sourceColumn: financial_year

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 9b6adb97-e538-4d9f-bb88-022582e26660
		summarizeBy: sum
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: bca60b07-8e3c-4b1e-986e-4d9ee73bf928
		summarizeBy: sum
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column financial_quarter_name
		dataType: string
		lineageTag: 9bb4cfff-6d01-4883-b460-2198c2e21718
		summarizeBy: none
		sourceColumn: financial_quarter_name

		annotation SummarizationSetBy = Automatic

	column year_quarter
		dataType: string
		lineageTag: 714d5087-2c6a-4fe1-b358-f074c1f92953
		summarizeBy: none
		sourceColumn: year_quarter

		annotation SummarizationSetBy = Automatic

	column financial_quarter_counter
		dataType: int64
		formatString: 0
		lineageTag: 6d3d9194-c4ca-4310-9346-340088b638d5
		summarizeBy: sum
		sourceColumn: financial_quarter_counter

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 72948c67-6ad8-43cf-9f68-5d89663d50ed
		summarizeBy: sum
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column ytd_description
		dataType: string
		lineageTag: 3e7cbc43-b312-4a72-92e6-bf567bfcbec0
		summarizeBy: none
		sourceColumn: ytd_description

		annotation SummarizationSetBy = Automatic

	column Current_FY
		dataType: string
		lineageTag: fa971241-b8ce-4d79-93a3-34fe754fbfdf
		summarizeBy: none
		sourceColumn: Current_FY

		annotation SummarizationSetBy = Automatic

	column Last_FY
		dataType: string
		lineageTag: d4bef1ab-794d-45e3-917f-3d9a18efa881
		summarizeBy: none
		sourceColumn: Last_FY

		annotation SummarizationSetBy = Automatic

	column Current_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: 6de1e732-8e97-4101-ac80-4615f5a7245c
		summarizeBy: sum
		sourceColumn: Current_FY_Flag

		annotation SummarizationSetBy = Automatic

	column Last_FY_Flag
		dataType: int64
		formatString: 0
		lineageTag: 30be7da3-bf62-4ac8-8a53-5bc0f2400164
		summarizeBy: sum
		sourceColumn: Last_FY_Flag

		annotation SummarizationSetBy = Automatic

	column 'School Holiday Flag' =
			
			SWITCH(TRUE(),
			'REF date_table'[date] >= VALUE("30/10/2023") && 'REF date_table'[date] <= VALUE("05/11/2023"), 1,
			'REF date_table'[date] >= VALUE("25/12/2023") && 'REF date_table'[date] <= VALUE("07/01/2024"), 1,
			'REF date_table'[date] >= VALUE("12/02/2024") && 'REF date_table'[date] <= VALUE("18/02/2024"), 1,
			'REF date_table'[date] >= VALUE("25/03/2024") && 'REF date_table'[date] <= VALUE("07/04/2024"), 1,
			'REF date_table'[date] >= VALUE("27/05/2024") && 'REF date_table'[date] <= VALUE("02/06/2024"), 1,
			'REF date_table'[date] >= VALUE("23/07/2024") && 'REF date_table'[date] <= VALUE("01/09/2024"), 1,
			0)
		formatString: 0
		lineageTag: 14bb91a5-3029-4b26-92c8-0e59ec9d3489
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Counter = 1
		formatString: 0
		lineageTag: 4b0d4ab0-a032-4870-852a-6b118da5b4f8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Day Counter' = 1
		formatString: 0
		lineageTag: 15635089-7224-4ef3-b2d6-3976ed63fecc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'financial_year Hierarchy'
		lineageTag: 52d8a591-a940-4428-9bb4-bbd7feacb185

		level 'Financial Year'
			lineageTag: 12131c7b-8238-4437-a9da-f3a8c329f017
			column: financial_year

		level Month
			lineageTag: 28664f2e-d4a0-4681-90c6-223272e6d5ec
			column: month_name

		level date
			lineageTag: fdf98f65-01ad-4914-93a8-493620a19814
			column: date

	partition 'REF date_table-b4c61e4d-8ba8-4a96-a19b-469f407d87a7' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db01_reference"), "select a.date as ""date"", a.daymonthyear as ""day_month_year"", a.day as ""day"", a.weekday as ""weekday"", a.weekdayname as ""weekday_name"", a.month as ""month"", left(a.monthname,3) as ""month_name"", a.quarter as ""quarter"", a.yearmonth as ""year_month"", a.isweekend as ""is_weekend"", a.isholiday as ""is_holiday"", a.financialweekofyear as ""financial_week_of_year"", a.financialyear as ""financial_year"", a.financialquarter as ""financial_quarter"", a.financialmonth as ""financial_month"", case when a.financialquarter=1 then 'Quarter 1' when a.financialquarter=2 then 'Quarter 2' when a.financialquarter=3 then 'Quarter 3' when a.financialquarter=4 then 'Quarter 4' end as ""financial_quarter_name"", concat(concat(substring(a.financialyear,3,2), substring(a.financialyear,6,2)), a.financialquarter) as ""year_quarter"", dense_rank() over (order by concat(concat(substring(a.financialyear,3,2), substring(a.financialyear,6,2)), a.financialquarter)) as ""financial_quarter_counter"", case when a.financialmonth <= (select cast(financialmonth as int) from ccg_reference.vw_datelookup where date = last_day(dateadd(month,-4,current_date))) then 1 else 0 end as ""ytd_flag"", case when a.financialmonth <= (select cast(financialmonth as int) from ccg_reference.vw_datelookup where date = last_day(dateadd(month,-4,current_date))) then 'Year to Date' else '' end as ""ytd_description"", (select financialyear from ccg_reference.vw_datelookup where date = current_date) as ""Current_FY"", (select max(financialyear) from ccg_reference.vw_datelookup where left(financialyear,4) = cast((select left(financialyear,4)::int from ccg_reference.vw_datelookup where date=current_date) - 1 as varchar)) as ""Last_FY"", case when (select financialyear from ccg_reference.vw_datelookup where date = current_date) = a.financialyear then 1 else 0 end as ""Current_FY_Flag"", case when (select max(financialyear) from ccg_reference.vw_datelookup where left(financialyear,4) = cast((select left(financialyear,4)::int from ccg_reference.vw_datelookup where date=current_date) - 1 as varchar)) = a.financialyear then 1 else 0 end as ""Last_FY_Flag"" from ccg_reference.vw_datelookup a where a.date >= '2019-04-01' and a.date <= last_day(dateadd(month,-1,current_date))", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"financial_month", Int64.Type}, {"is_holiday", Int64.Type}, {"is_weekend", Int64.Type}, {"month", Int64.Type}, {"year_month", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

