table 'A&G Date Table'
	lineageTag: 58efe30c-6a88-4169-a9e2-12b745294c27
	dataCategory: Time

	measure AGCurrentFY =
			
			MAX('A&G Date Table'[Financial Year])  // Automatically detect the latest FY
		lineageTag: 22856a76-6cb3-4abf-b062-f70390fa2d0d

	measure AGPreviousFY =
			
			VAR TodayDate = TODAY()
			VAR CurrentYear = YEAR(TodayDate)
			VAR CurrentMonth = MONTH(TodayDate)
			RETURN
			    IF(
			        CurrentMonth >= 4,
			        FORMAT(CurrentYear - 1, "0000") & "/" & RIGHT(FORMAT(CurrentYear, "0000"), 2),
			        FORMAT(CurrentYear - 2, "0000") & "/" & RIGHT(FORMAT(CurrentYear - 1, "0000"), 2)
			    )
		lineageTag: fe88fdef-2bec-451a-bb1e-8a0f08483448

	measure AGPreviousPreviousFY =
			
			VAR TodayDate = TODAY()
			VAR CurrentYear = YEAR(TodayDate)
			VAR CurrentMonth = MONTH(TodayDate)
			RETURN
			    IF(
			        CurrentMonth >= 4,
			        FORMAT(CurrentYear - 2, "0000") & "/" & RIGHT(FORMAT(CurrentYear -1, "0000"), 2),
			        FORMAT(CurrentYear - 3, "0000") & "/" & RIGHT(FORMAT(CurrentYear - 2, "0000"), 2)
			    )
		lineageTag: f7efad9b-eda7-47ca-99c3-385b5e14226d

	column date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: cf8a79bd-1e5d-49c1-bd30-ca4f3d29b498
		summarizeBy: none
		sourceColumn: date
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06f615b8-d931-4601-8d8a-839987d7782c
		summarizeBy: none
		sourceColumn: day_month_year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: 997d8bbc-c728-4a59-81de-ac3dbd4405f8
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: 34b8975f-e817-4711-bdbe-08763607122e
		summarizeBy: none
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: b9f6e5d0-1ff0-4725-a8c3-e633237984b1
		summarizeBy: none
		sourceColumn: weekday_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 53a85185-5352-4715-a398-481d9baf1a6e
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: cfd7bc64-fc63-43f9-9ba7-202f1bc994b9
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: financial_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 486e86b6-2f92-4cc7-a347-b1e7b47dbc29
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 9c1e269c-78eb-4bae-971a-e82a1d6ce15f
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: c6343de7-bc46-4816-8066-1165439185e2
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 82992862-c4b7-44c1-a3f0-c36babfd6509
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: 27c0c062-b3e9-47bc-9876-8e20192ddf3e
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: eee56672-e9e7-45f3-abfb-937554ae1e00
		summarizeBy: none
		sourceColumn: is_working_day

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: e1d78f55-638c-4668-90e1-660dfeeb3241
		summarizeBy: none
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column 'Financial Year'
		dataType: string
		lineageTag: 64445e02-dcf8-40cc-a7ec-1f1ee54e706b
		summarizeBy: none
		sourceColumn: Financial Year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 540bcb12-2508-4c00-a958-129099d7438a
		summarizeBy: none
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: 6d810446-e5fd-42fe-9e8c-98a1daa96bee
		summarizeBy: none
		sourceColumn: day_of_quarter

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b7eeebc-1672-4143-b8c0-0e39275739d6
		summarizeBy: none
		sourceColumn: quarter_start_date

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 362bc4d7-233f-4b40-bdbb-2e585713fe19
		summarizeBy: none
		sourceColumn: quarter_end_date

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: 43adf7a6-7978-4c88-9c86-50bb940284b3
		summarizeBy: none
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 7bd4ea79-e5eb-4a57-ad7f-895a91b55793
		summarizeBy: none
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 3f5cba54-86c3-4103-b017-60f85993d74a
		summarizeBy: none
		sourceColumn: month_year_name

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column month_year
		dataType: string
		lineageTag: 37d89077-99b2-4fae-9e26-a148a1b625ec
		summarizeBy: none
		sourceColumn: month_year
		sortByColumn: year_month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: 18b02c66-db93-4114-ad6a-ec80e19b8aa1
		summarizeBy: none
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: a497df6e-3eea-46c0-ab62-027b76e2aa69
		summarizeBy: none
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 13679d3e-1b52-49a4-accc-6466ee88aedf
		summarizeBy: none
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 422a429e-330b-4d8f-adce-3fb5b5b531b0
		summarizeBy: none
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 1a5dc39a-4ebe-4d9a-9fcf-7b827293ecce
		summarizeBy: none
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: a8582379-4bbb-42f3-a1c0-938223dcd2a0
		summarizeBy: none
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	column SPC_flag =
			
			IF(
			    AND('A&G Date Table'[date] >= DATE(2023,11,01),  'A&G Date Table'[date] <= DATE(2024,10,31)),  1, 0)
		formatString: 0
		lineageTag: 8fc3c9d6-8238-458e-ba9e-527e936a69e8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column YearMonthIndex = ```
			---this field orders months in your date table so the moving average calculates correctly. 
			
			RANKX(
			    ALL('A&G Date Table'[year_month]),
			    'A&G Date Table'[year_month],
			    ,
			    ASC,
			    DENSE
			) - 1
			```
		formatString: 0
		lineageTag: 38e99c88-bc7a-4c8e-bec9-da256ce38007
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'day_month_year Hierarchy'
		lineageTag: 4df4dfa9-c6cd-43b4-8dc9-cd735db121ba

		level day_month_year
			lineageTag: 135c7db4-bb43-4a7a-9c47-b57307bfb7a3
			column: day_month_year

		level month_name
			lineageTag: 2840615e-641c-4fd3-ab7f-4a6505464e8f
			column: month_name

		level 'Financial Year'
			lineageTag: a02841b0-7e9b-4d5b-b373-9280eee2d773
			column: 'Financial Year'

	hierarchy 'financial_year Hierarchy'
		lineageTag: 066b876c-44e3-4209-9f49-3d564019751c

		level 'Financial Year'
			lineageTag: e1943ed1-bea2-402b-9166-15e14b5bf51b
			column: 'Financial Year'

		level month_name
			lineageTag: 0e73c57b-db94-4fd6-bfb3-08a946f06a73
			column: month_name

	partition 'A&G Date Table' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="/*===============================================================================================================#(lf)A&G Optom dates table #(lf)#(lf)New Date Reference Script#(lf)Created by: Ben Adams#(lf)Created Date: 27/12/2023#(lf)===============================================================================================================*/#(lf)#(lf)DECLARE @MaxDate DATE = (SELECT MAX([ActionDateTime]) FROM [CCG_Current].[EReferrals].[vw_Events] );#(lf)DECLARE @LatestFullMonthEnd DATE = EOMONTH(@MaxDate); #(lf)#(lf)SELECT DISTINCT [date] = CAST([Full_Date] AS DATE)#(lf)               ,[day_month_year] = CONVERT(VARCHAR, [Full_Date], 103) --> 103 converts to DD/MM/YYYY format#(lf)#(tab)#(tab)#(tab)   ,[day] = [Day_Of_Fin_Year]#(lf)#(tab)#(tab)#(tab)   ,[weekday] = [Weekday_No]#(lf)#(tab)#(tab)#(tab)   ,[weekday_name] = [Weekday_Name]#(lf)#(tab)#(tab)#(tab)   ,[month] = [Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_name] = [Month_Short_Name]#(lf)#(tab)#(tab)#(tab)   ,[quarter] = [Cal_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[year_month] = [Year_Month]#(lf)#(tab)#(tab)#(tab)   ,[is_weekend] = CASE WHEN [Weekday_No] IN (6,7) THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[is_holiday] = CASE WHEN [Bank_Holiday_Desc] IS NOT NULL THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[holiday_description] = [Bank_Holiday_Desc] --> Description of holiday type i.e., 'Bank Holiday'#(lf)#(tab)#(tab)#(tab)   ,[is_working_day] = [Working_Day_Calc]#(lf)#(tab)#(tab)#(tab)   ,[financial_week_of_year] = [Fin_Week_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_year] = REPLACE([Fin_Year_YYYY_dash_YY], ' - ', '/')#(lf)#(tab)#(tab)#(tab)   ,[financial_quarter] = [Fin_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[day_of_quarter] = [Day_Of_Quarter]#(lf)#(tab)#(tab)#(tab)   ,[quarter_start_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[quarter_end_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[month_day_no] = [Month_Day_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_month] = [Fin_Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_year_name] = CONCAT([Month_Short_Name], '-', LEFT([Date_112], 4))#(lf)#(tab)#(tab)#(tab)   ,[month_year] = [MonthYear_MMMM_YYYYY]#(lf)#(tab)#(tab)#(tab)   ,[ytd_flag] = CASE WHEN [Fin_Month_No] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([Fin_Month_No] AS INT)#(lf)                                           FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Full_Date] = EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END --> Establishes whether the month is included in year to date calculations and reflects across all years#(lf)#(tab)#(tab)#(tab)   ,[latest_month_flag] = CASE WHEN [Year_Month] IN #(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_month_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -2, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The month before the latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[latest_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                             (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                              FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -12, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      THEN 1 ELSE 0 END --> The latest 12 months within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                               (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                                FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -24, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)    AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        THEN 1 ELSE 0 END --> The 12 months before the latest 12 months within your date range - allows comparing current to previous#(lf)#(tab)#(tab)#(tab)   ,[same_month_last_year_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                                 (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END --> Same month last year as the latest month within the date range i.e., Nov-22 and Nov-23#(lf) #(lf)FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf) #(lf)WHERE [Full_Date] BETWEEN '20200401' AND @LatestFullMonthEnd#(lf)#(lf)-- EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) ) --> This can be changed to meet your date range need. #(lf)                                                                                      --  The EOMONTH function finds the latest complete month.#(lf) #(lf)ORDER BY CAST([Full_Date] AS DATE) DESC"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"financial_year", "Financial Year"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

