table Emergency_Admissions_Dynamic_Measures_Table
	lineageTag: 5a51c745-968b-4e40-b9ed-5836aa24c669

	measure Emergency_Admission_Measure_Value = ```
			SWITCH(
										MIN(Emergency_Admissions_Dynamic_Measures_Table[Measure ID]) ,
										--------------------------------------
										1,[mildly_frail_emg_adm_per_1000_ot],
			                            2,[moderately_frail_emg_adm_per_1000_ot],
									3,[severely_frail_emg_adm_per_1000_ot]
									
			
										)
			```
		formatString: 0.0
		lineageTag: 137ed520-42ad-4c5c-a5c8-e637f93602ee

	column 'Measure Name '
		dataType: string
		lineageTag: 5f61934e-dcc7-4d77-b6ee-0af643a8234d
		summarizeBy: none
		sourceColumn: "Measure Name "

		annotation SummarizationSetBy = Automatic

	column 'Measure ID'
		dataType: int64
		formatString: 0.0
		lineageTag: 95fd0600-8254-4f69-9800-dc04ed6004e5
		summarizeBy: none
		sourceColumn: Measure ID

		annotation SummarizationSetBy = Automatic

	partition Emergency_Admissions_Dynamic_Measures_Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8s3MSalUcCtKzMxRcM1NLUpPzUuuVHBMyc0sLs7Mz1MISixJVShILVIwNDAwUMgvA7JKMnNTFZR0lAyVYnWABuSnpBYlluSkkmmKEdiU4FSgWGoOmWYYK8XGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Measure Name " = _t, #"Measure ID" = _t]),
				    #"Reordered Columns" = Table.ReorderColumns(Source,{"Measure ID", "Measure Name "}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"Measure Name ", type text}, {"Measure ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

