table 'Age ref'
	lineageTag: cfb3ef2b-5cd9-4e06-8fba-056848701294

	column AgeBand5yr
		dataType: string
		lineageTag: ae3e4f7b-d16a-406a-8889-dcae79b20fb3
		summarizeBy: none
		sourceColumn: AgeBand5yr
		sortByColumn: Column1

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 5b4829b0-3acc-47ed-8866-27543e819781
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 'Age ref' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Jc7JDQQhEEPRXLhOWyoWAx0L6vzTGMq+8fSRyueUwChPqeV7TqmBmuoWUd+rIbVAy0aLaNmm1AM927KInm1L4x7I9lrEyFZDZIA67/skqNpMJPyegamf3jaJqZ8etwJL1esWsVQ9bwe2qvdt/hJ33vcH", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [AgeBand5yr = _t, Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"AgeBand5yr", type text}, {"Column1", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

