table 'Cancer incidence'
	lineageTag: d4b41b67-7dfb-430a-b438-ac6cb23d79a0

	column cancer_type
		dataType: string
		lineageTag: 5cf03d2c-29f6-4d04-b003-5d2e8c48edb9
		summarizeBy: none
		sourceColumn: cancer_type

		annotation SummarizationSetBy = Automatic

	column Gloucestershire
		dataType: double
		lineageTag: 498f6d9e-77d5-4d24-83ba-5740b87014a6
		summarizeBy: sum
		sourceColumn: Gloucestershire

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Core 20'
		dataType: double
		lineageTag: ac868121-ae4f-48ed-8e11-99bb5954fc53
		summarizeBy: sum
		sourceColumn: Core 20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ethnic Minority'
		dataType: double
		lineageTag: f6517cf6-61dc-443a-9b28-a47a72083885
		summarizeBy: sum
		sourceColumn: Ethnic Minority

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mental Health'
		dataType: double
		lineageTag: 3b8cd445-c505-4826-8f13-3ba0099d9d01
		summarizeBy: sum
		sourceColumn: Mental Health

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Learning Disability'
		dataType: double
		lineageTag: edc5d35a-1038-494e-ba85-4f3d0c1e1785
		summarizeBy: sum
		sourceColumn: Learning Disability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gloucester City'
		dataType: double
		lineageTag: f2ff20ec-0acf-4a6f-9b54-06cedcd779ec
		summarizeBy: sum
		sourceColumn: Gloucester City

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cheltenham
		dataType: double
		lineageTag: b6f36969-efec-4977-8cc3-81c57c007261
		summarizeBy: sum
		sourceColumn: Cheltenham

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cotswolds
		dataType: double
		lineageTag: f5157b7b-491a-4fdd-b8ba-f841ef133030
		summarizeBy: sum
		sourceColumn: Cotswolds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forest of Dean'
		dataType: double
		lineageTag: 21409ba3-e6b7-43fa-bf03-ccf9ff7a0de7
		summarizeBy: sum
		sourceColumn: Forest of Dean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stroud & Berkeley Vale'
		dataType: double
		lineageTag: 390f4cc8-3d32-4217-82c5-65ea240afbae
		summarizeBy: sum
		sourceColumn: Stroud & Berkeley Vale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TWNS
		dataType: double
		lineageTag: 237f8b47-c32d-40f3-95ff-095b0d6b86ff
		summarizeBy: sum
		sourceColumn: TWNS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Cancer incidence' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "data_mart_performance", [Query="#(tab)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#table1') IS NOT NULL DROP TABLE #table1#(lf)#(tab)#(lf)#(tab)SELECT DISTINCT [B].[FinancialYear]#(lf)#(tab),[Primary_Diagnosis_ICD]#(lf)#(tab),[ICD10CodeDescription]#(lf)#(lf)#(tab),[Cancer_type] = CASE#(lf)#(tab)WHEN [Primary_Diagnosis_ICD] LIKE '%C3[3-9]%' then 'Lung Cancer'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C4[3-4]%' then 'Skin Cancer'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C5[1-8]%' then 'Gynaecological Cancers'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C50%' then 'Breast Cancer'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C1[7-9]%' then 'Lower-Gastrointestinal Cancers'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C2[0-1]%' then 'Lower-Gastrointestinal Cancers'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C26%' then 'Lower-Gastrointestinal Cancers'#(lf)#(lf)#(tab)END#(lf)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[B].MonthName#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[B].YearMonth#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[Record_ID]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[A].[Pseudo_NHS_Number]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[Referral_Type] = CASE WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '01' THEN 'Suspected breast cancer'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '02' THEN 'Suspected childrens cancer' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '03' THEN 'Suspected lung cancer'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '04' THEN 'Suspected haematological malignancies excluding acute leukaemia'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '05' THEN 'Suspected acute leukaemia'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '06' THEN 'Suspected upper gastrointestinal cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '07' THEN 'Suspected lower gastrointestinal cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '08' THEN 'Suspected skin cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '09' THEN 'Suspected gynaecological cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '10' THEN 'Suspected brain or central nervous system tumours'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '11' THEN 'Suspected urological cancers (excluding testicular)'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '12' THEN 'Suspected testicular cancer'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '13' THEN 'Suspected head and neck cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '14' THEN 'Suspected sarcomas'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '16' THEN 'Exhibited (non-cancer) breast symptoms - cancer not initially suspected'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '17' THEN 'Suspected cancer- non-specific symptoms'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '18' THEN 'Other suspected cancer (not listed)'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) ELSE [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] END#(lf) #(lf)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[Counter] = 1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[A].Cancer_Treatment_Period_Start_Date#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[A].Cancer_Referral_To_Treatment_Period_Start_Date#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,Patient_ODS_Code_Of_GP_Practice#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[GP].OrganisationName#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[GP].[PrimaryCareNetwork]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[locality] = case when [GP].Locality like '%cotswold%' then 'Cotswolds' else [GP].[locality] end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[PD].[DateOfDeath]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment] = datediff(day, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath])#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment_within_one_year] = case when datediff(day, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath]) <= 365 then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment_within_sixth_month] = case when datediff(month, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath]) <= 6 then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment_within_four_weeks] = case when datediff(week, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath]) <= 4 then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[a].Patient_Gender#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[age_at_treatment] = DATEDIFF(year, [P].[Derived_Year_Month_Of_Birth], [A].Cancer_Treatment_Period_Start_Date)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[age].[5YR_Age_Band]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[sex] = case when [a].Patient_Gender like 1 then 'Male' when [a].Patient_Gender like 2 then 'Female' END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[A].[Local_Area_District_Of_Residence]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[A].Lowest_Geographical_Area_Of_Residence#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[IMD].[Derived_IMDGloucestershireDecile]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_flag] = CASE WHEN [PD].[Derived_NHS_Number] IS NULL THEN 0 ELSE 1 END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),Core20Flag = case when Lowest_Geographical_Area_Of_Residence in ('E01022120','E01022122','E01022131','E01022133','E01022147','E01022152','E01022160','E01022164','E01022238','E01022284','E01022285','E01022288','E01022289','E01022290','E01022291','E01022292','E01022311','E01022319','E01022320','E01022322','E01022323','E01022324','E01022328','E01022329','E01022332','E01022333','E01022346','E01022347','E01022458','E01032932','E01032937') then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Eth].[Ethnic Origin Grouped]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[MH_flag] = CASE WHEN [LTC_CODE] = 'QOF48_MH_COD' THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[LD_flag] = CASE WHEN [LTC_CODE] = 'QOF48_LD_COD' THEN 1 ELSE 0 END #(lf)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(lf)#(tab)  INTO #table1#(lf)#(lf)#(tab)  FROM [Data_Mart_Performance].[dbo].[Cancer_Waits_v2] AS [A]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] AS [B] ON [B].[date] = [A].[Cancer_Treatment_Period_Start_Date]#(lf) #(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_ICD10] AS [ICD10] ON [ICD10].[ICD10Code] = [A].[Primary_Diagnosis_ICD]#(lf) #(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_GPPractice] AS [GP] ON [GP].[OrganisationCode] = Patient_ODS_Code_Of_GP_Practice#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Population].[vw_PDS_Deaths] [PD] ON [PD].[Derived_NHS_Number] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Population].[vw_PDS_All] [P] ON [P].[Derived_NHS_Number] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_AgeBand] [Age] ON [Age].Age = DATEDIFF(year, [P].[Derived_Year_Month_Of_Birth], [A].Cancer_Treatment_Period_Start_Date)#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_GeographyMapping] [G] ON [G].[LSOACode] = [A].[Lowest_Geographical_Area_Of_Residence]#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_LSOA_IMD] [IMD] ON [IMD].[LSOACode] = [A].[Lowest_Geographical_Area_Of_Residence]#(lf)#(tab)  #(lf)#(tab)  LEFT JOIN [BIReports].[MPI].[Ethnicity_Table] [Eth] ON [Eth].[PseudoNHSNo] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Current].[PrimaryCare].[vw_LongTermConditionsEvents] [PC] ON [PC].[Pseudo_NHS_Number] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  WHERE #(lf)#(tab)  [A].[Primary_Diagnosis_ICD] IS NOT NULL#(lf)#(tab)  AND #(lf)#(tab)  (#(lf)#(tab) [Primary_Diagnosis_ICD] LIKE '%C3[3-9]%' #(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C4[3-4]%' #(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C5[1-8]%'#(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C50%' #(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C1[7-9]%'#(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C2[0-1]%'#(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C26%'#(lf)#(tab)  )#(lf)#(lf)#(tab)  AND #(lf)#(tab)  [yearmonth] >= '201804'#(lf)#(lf)#(tab)  #(tab)  ORDER BY [Patient_ODS_Code_Of_GP_Practice]#(lf)------------------------------------------------------------------#(lf)--Base table for reference population - from MPI table#(lf)------------------------------------------------------------------#(lf)#(lf)#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#ref_pop') IS NOT NULL DROP TABLE #ref_pop#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  locality = m.LocalityName#(lf)#(tab)  ,MH_flag = m.MentalIllnessDerived#(lf)#(tab)  ,LD_flag = m.LearningDisabilityDerived#(lf)#(tab)  ,Core20Flag#(lf)#(tab)  ,[Ethnic Origin Grouped] = EthnicOriginDescription#(lf)#(tab)  ,[5YR_Age_Band] = m.AgeBand5yr#(lf)#(tab)  ,Derived_Pseudo_NHS#(lf)#(tab)  ,[counter] = 1#(lf)#(tab)  into #ref_pop#(lf)#(tab)  from BIReports.MPI.MPI_current m#(lf)#(tab)  order by locality, [5YR_Age_Band]#(lf)#(lf)------------------------------------------------------------------#(lf)--Grouped table for reference population#(lf)------------------------------------------------------------------#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#ref_pop_age_band') IS NOT NULL DROP TABLE #ref_pop_age_band#(lf)#(tab)  SELECT#(lf)#(tab)  [reference_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #ref_pop_age_band#(lf)#(tab)  from #ref_pop#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)------------------------------------------------------------------#(lf)--Grouped tables for local populations#(lf)------------------------------------------------------------------#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_dep') IS NOT NULL DROP TABLE #local_pop_dep#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_deprived] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_dep#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where Core20Flag like 1#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_MH') IS NOT NULL DROP TABLE #local_pop_MH#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_MH] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_MH#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where MH_flag like 1#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_LD') IS NOT NULL DROP TABLE #local_pop_LD#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_LD] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_LD#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where LD_flag like 1#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_ethnicity') IS NOT NULL DROP TABLE #local_pop_ethnicity#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_ethnicity] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_ethnicity#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where [Ethnic Origin Grouped] in ('Black or Black British', 'Mixed', 'Asian or Asian British', 'Other Ethnic Groups')#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_glos') IS NOT NULL DROP TABLE #local_pop_glos#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_glos] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_glos#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where locality like 'Gloucester City'#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_chelt') IS NOT NULL DROP TABLE #local_pop_chelt#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_chelt] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_chelt#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where locality like 'Cheltenham'#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_TWNS') IS NOT NULL DROP TABLE #local_pop_TWNS#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_TWNS] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_TWNS#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where locality like 'Tewkesbury Newent and Staunton'#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_SBV') IS NOT NULL DROP TABLE #local_pop_SBV#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_SBV] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_SBV#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where locality like 'Stroud and Berkeley Vale'#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_FOD') IS NOT NULL DROP TABLE #local_pop_FOD#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_FOD] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_FOD#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where locality like 'The Forest of Dean'#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_pop_cots') IS NOT NULL DROP TABLE #local_pop_cots#(lf)#(tab)  SELECT#(lf)#(tab)  [local_population_cots] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  into #local_pop_cots#(lf)#(tab)  from #ref_pop#(lf)#(tab)  where locality like '%Cotswolds%'#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(lf)------------------------------------------------------------------#(lf)--Reference event table#(lf)------------------------------------------------------------------#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#ref_event_age_band') IS NOT NULL DROP TABLE #ref_event_age_band#(lf)#(tab)  SELECT#(lf)#(tab)  [reference_events] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #ref_event_age_band#(lf)#(tab)  from #table1#(lf)#(tab)  group by [5YR_Age_Band], Cancer_type#(lf)#(lf)------------------------------------------------------------------#(lf)--Local events tables#(lf)------------------------------------------------------------------#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_dep') IS NOT NULL DROP TABLE #local_event_dep#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_deprived] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_dep#(lf)#(tab)  from #table1#(lf)#(tab)  where Core20Flag like 1#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_MH') IS NOT NULL DROP TABLE #local_event_MH#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_MH] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_MH#(lf)#(tab)  from #table1#(lf)#(tab)  where MH_flag like 1#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_LD') IS NOT NULL DROP TABLE #local_event_LD#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_LD] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_LD#(lf)#(tab)  from #table1#(lf)#(tab)  where LD_flag like 1#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_ethnicity') IS NOT NULL DROP TABLE #local_event_ethnicity#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_ethnicity] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_ethnicity#(lf)#(tab)  from #table1#(lf)#(tab)  where [Ethnic Origin Grouped] in ('Black or Black British', 'Mixed', 'Asian or Asian British', 'Other Ethnic Groups')#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_glos') IS NOT NULL DROP TABLE #local_event_glos#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_glos] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_glos#(lf)#(tab)  from #table1#(lf)#(tab)  where locality like 'Gloucester City'#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_chelt') IS NOT NULL DROP TABLE #local_event_chelt#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_chelt] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_chelt#(lf)#(tab)  from #table1#(lf)#(tab)  where locality like 'Cheltenham'#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_TWNS') IS NOT NULL DROP TABLE #local_event_TWNS#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_TWNS] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_TWNS#(lf)#(tab)  from #table1#(lf)#(tab)  where locality like 'Tewkesbury Newent and Staunton'#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_SBV') IS NOT NULL DROP TABLE #local_event_SBV#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_SBV] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_SBV#(lf)#(tab)  from #table1#(lf)#(tab)  where locality like 'Stroud and Berkeley Vale'#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_FOD') IS NOT NULL DROP TABLE #local_event_FOD#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_FOD] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_FOD#(lf)#(tab)  from #table1#(lf)#(tab)  where locality like 'The Forest of Dean'#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#local_event_cots') IS NOT NULL DROP TABLE #local_event_cots#(lf)#(tab)  SELECT#(lf)#(tab)  [local_event_cots] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,Cancer_type#(lf)#(tab)  into #local_event_cots#(lf)#(tab)  from #table1#(lf)#(tab)  where locality like 'Cotswolds'#(lf)#(tab)  group by [5YR_Age_Band],Cancer_type#(lf)#(lf)------------------------------------------------------------------#(lf)--Overall reference table for age standardisation#(lf)------------------------------------------------------------------#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#reference') IS NOT NULL DROP TABLE #reference#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [reference_events] = sum([reference_events])#(lf)#(tab)  ,rp.[5YR_Age_Band]#(lf)#(tab)  ,[reference_population] = sum([reference_population])#(lf)#(tab)  ,[reference_rate] = (cast(sum([reference_events]) as float)) / (cast(sum([reference_population]) as float))#(lf)#(tab)  ,[cancer_type] #(lf)#(tab)  into #reference#(lf)#(tab)  from #ref_pop_age_band rp left join #ref_event_age_band re on re.[5YR_Age_Band] = rp.[5YR_Age_Band]#(lf)#(tab)  where rp.[5YR_Age_Band] is not null#(lf)#(tab)  group by rp.[5YR_Age_Band], [cancer_type]#(lf)#(tab)  order by [cancer_type], rp.[5YR_Age_Band]#(lf)#(lf)------------------------------------------------------------------#(lf)--Local event tables for age standardisation#(lf)------------------------------------------------------------------#(lf)#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#deprived') IS NOT NULL DROP TABLE #deprived#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_deprived = sum(local_event_deprived)#(lf)#(tab)  ,local_population_deprived = sum(local_population_deprived)#(lf)#(tab)  ,lpd.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #deprived#(lf)#(tab)  from #local_pop_dep lpd#(lf)#(tab)  left join #local_event_dep led on led.[5YR_Age_Band] =lpd.[5YR_Age_Band]#(lf)#(tab)  group by lpd.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#ethnicity') IS NOT NULL DROP TABLE #ethnicity#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_ethnicity = sum(local_event_ethnicity)#(lf)#(tab)  ,local_population_ethnicity = sum(local_population_ethnicity)#(lf)#(tab)  ,lpe.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #ethnicity#(lf)#(tab)  from #local_pop_ethnicity lpe#(lf)#(tab)  left join #local_event_ethnicity lee on lee.[5YR_Age_Band] =lpe.[5YR_Age_Band]#(lf)#(tab)  group by lpe.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#mental_health') IS NOT NULL DROP TABLE #mental_health#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_MH = sum(local_event_MH)#(lf)#(tab)  ,local_population_MH = sum(local_population_MH)#(lf)#(tab)  ,lpm.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #mental_health#(lf)#(tab)  from #local_pop_MH lpm#(lf)#(tab)  left join #local_event_MH lem on lem.[5YR_Age_Band] =lpm.[5YR_Age_Band]#(lf)#(tab)  group by lpm.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#LD') IS NOT NULL DROP TABLE #LD#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_LD = sum(local_event_LD)#(lf)#(tab)  ,local_population_LD = sum(local_population_LD)#(lf)#(tab)  ,lpl.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #LD#(lf)#(tab)  from #local_pop_LD lpl#(lf)#(tab)  left join #local_event_LD lel on lel.[5YR_Age_Band] =lpl.[5YR_Age_Band]#(lf)#(tab)  group by lpl.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#gloucester') IS NOT NULL DROP TABLE #gloucester#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_glos = sum(local_event_glos)#(lf)#(tab)  ,local_population_glos = sum(local_population_glos)#(lf)#(tab)  ,lpg.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #gloucester#(lf)#(tab)  from #local_pop_glos lpg#(lf)#(tab)  left join #local_event_glos leg on leg.[5YR_Age_Band] =lpg.[5YR_Age_Band]#(lf)#(tab)  group by lpg.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#cheltenham') IS NOT NULL DROP TABLE #cheltenham#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_chelt = sum(local_event_chelt)#(lf)#(tab)  ,local_population_chelt = sum(local_population_chelt)#(lf)#(tab)  ,lpc.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #cheltenham#(lf)#(tab)  from #local_pop_chelt lpc#(lf)#(tab)  left join #local_event_chelt lec on lec.[5YR_Age_Band] =lpc.[5YR_Age_Band]#(lf)#(tab)  group by lpc.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#TWNS') IS NOT NULL DROP TABLE #TWNS#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_TWNS = sum(local_event_TWNS)#(lf)#(tab)  ,local_population_TWNS = sum(local_population_TWNS)#(lf)#(tab)  ,lpt.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #TWNS#(lf)#(tab)  from #local_pop_TWNS lpt#(lf)#(tab)  left join #local_event_TWNS let on let.[5YR_Age_Band] =lpt.[5YR_Age_Band]#(lf)#(tab)  group by lpt.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#SBV') IS NOT NULL DROP TABLE #SBV#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_SBV = sum(local_event_SBV)#(lf)#(tab)  ,local_population_SBV = sum(local_population_SBV)#(lf)#(tab)  ,lps.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #sbv#(lf)#(tab)  from #local_pop_SBV lps#(lf)#(tab)  left join #local_event_SBV les on les.[5YR_Age_Band] =lps.[5YR_Age_Band]#(lf)#(tab)  group by lps.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#FOD') IS NOT NULL DROP TABLE #FOD#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_FOD = sum(local_event_FOD)#(lf)#(tab)  ,local_population_FOD = sum(local_population_FOD)#(lf)#(tab)  ,lpf.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #FOD#(lf)#(tab)  from #local_pop_FOD lpf#(lf)#(tab)  left join #local_event_FOD lef on lef.[5YR_Age_Band] =lpf.[5YR_Age_Band]#(lf)#(tab)  group by lpf.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#Cotswolds') IS NOT NULL DROP TABLE #Cotswolds#(lf)#(tab)  SELECT#(lf)#(tab)  local_event_cots = sum(local_event_cots)#(lf)#(tab)  ,local_population_cots = sum(local_population_cots)#(lf)#(tab)  ,lpc.[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  into #Cotswolds#(lf)#(tab)  from #local_pop_cots lpc#(lf)#(tab)  left join #local_event_cots lec on lec.[5YR_Age_Band] =lpc.[5YR_Age_Band]#(lf)#(tab)  group by lpc.[5YR_Age_Band] ,[cancer_type]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#combined') IS NOT NULL DROP TABLE #combined#(lf)#(lf)#(tab)  SELECT #(lf)#(tab)  r.[5YR_Age_Band]#(lf)#(tab)  ,r.[cancer_type]#(lf)#(tab)  ,reference_events = cast(r.reference_events as float)#(lf)#(tab)  ,reference_population = cast(r.reference_population as float)#(lf)#(tab)  ,reference_rate = cast(r.reference_rate as float)#(lf)#(lf)#(tab)  ,core_20_local_events = cast(d.local_event_deprived as float)#(lf)#(tab)  ,core_20_local_population = cast(d.local_population_deprived as float)#(lf)#(tab)  ,[core_20_local_expected_events] = cast(d.local_population_deprived * reference_rate as float)#(lf)#(lf)#(tab)  ,ethnic_minority_local_events = cast(e.local_event_ethnicity as float)#(lf)#(tab)  ,ethnic_minority_local_population = cast(e.local_population_ethnicity as float)#(lf)#(tab)  ,[ethnic_minority_local_expected_events] = cast(e.local_population_ethnicity * reference_rate as float)#(lf)#(lf)#(tab)  ,MH_local_events = cast(m.local_event_MH as float)#(lf)#(tab)  ,MH_local_population = cast(m.local_population_MH as float)#(lf)#(tab)  ,[MH_local_expected_events] = cast(m.local_population_MH * reference_rate as float)#(lf)#(lf)#(tab)  ,LD_local_events = ld.local_event_LD#(lf)#(tab)  ,LD_local_population = ld.local_population_LD#(lf)#(tab)  ,[LD_local_expected_events] = cast(ld.local_population_LD * reference_rate as float)#(lf)#(lf)#(tab)  ,gloucester_local_events = g.local_event_glos#(lf)#(tab)  ,gloucester_local_population =g.local_population_glos#(lf)#(tab)  ,[gloucester_local_expected_events] = cast(local_population_glos * reference_rate as float)#(lf)#(lf)#(tab)  ,cheltenham_local_events = local_event_chelt#(lf)#(tab)  ,cheltenham_local_population = local_population_chelt#(lf)#(tab)  ,[cheltenham_local_expected_events] = cast(local_population_chelt * reference_rate as float)#(lf)#(lf)#(tab)  ,cotswolds_local_events = local_event_cots#(lf)#(tab)  ,cotswolds_local_population = local_population_cots#(lf)#(tab)  ,[cotswolds_local_expected_events] = cast(local_population_cots * reference_rate as float)#(lf)#(lf)#(tab)  ,FOD_local_events = local_event_FOD#(lf)#(tab)  ,FOD_local_population = local_population_FOD#(lf)#(tab)  ,[FOD_local_expected_events] = cast(local_population_FOD * reference_rate as float)#(lf)#(lf)#(tab)  ,SBV_local_events = local_event_SBV#(lf)#(tab)  ,SBV_local_population = local_population_SBV#(lf)#(tab)  ,[SBV_local_expected_events] = cast(local_population_SBV * reference_rate as float)#(lf)#(lf)#(tab)  ,TWNS_local_events = local_event_TWNS#(lf)#(tab)  ,TWNS_local_population = local_population_TWNS#(lf)#(tab)  ,[TWNS_local_expected_events] = cast(local_population_TWNS * reference_rate as float)#(lf)#(lf)#(lf)#(tab)  into #combined#(lf)#(tab)  from #reference r#(lf)#(lf)#(tab)  LEFT JOIN #deprived d on d.[5YR_Age_Band] = r.[5YR_Age_Band] and d.[cancer_type] = r.Cancer_type#(lf)#(tab)  LEFT JOIN #ethnicity e on e.[5YR_Age_Band] = r.[5YR_Age_Band] and e.[Cancer_type] = r.Cancer_type#(lf)#(tab)  LEFT JOIN #mental_health m on m.[5YR_Age_Band] = r.[5YR_Age_Band] and m.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #LD ld on ld.[5YR_Age_Band] = r.[5YR_Age_Band] and ld.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #gloucester g on g.[5YR_Age_Band] = r.[5YR_Age_Band] and g.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #cheltenham che on [che].[5YR_Age_Band] = r.[5YR_Age_Band] and [che].Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #Cotswolds [cot] on [cot].[5YR_Age_Band] = r.[5YR_Age_Band] and [cot].Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #FOD fod on fod.[5YR_Age_Band] = r.[5YR_Age_Band] and fod.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #SBV SBV on SBV.[5YR_Age_Band] = r.[5YR_Age_Band] and SBV.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #TWNS TWNS on TWNS.[5YR_Age_Band] = r.[5YR_Age_Band] and TWNS.Cancer_type = r.Cancer_type#(lf)#(lf)#(tab)  order by r.[cancer_type], r.[5YR_Age_Band]#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [cancer_type]#(lf)#(tab)  ,[reference_rate_per_1000] = sum(reference_events) / sum(reference_population) * 1000#(lf)#(lf)#(tab)  ,[core_20_AS_rate_per_1000] = #(lf)#(tab)  sum(core_20_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum([core_20_local_expected_events])#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[ethnic_minority_AS_rate_per_1000] = #(lf)#(tab)  sum(ethnic_minority_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum([ethnic_minority_local_expected_events])#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(tab)  #(lf)#(lf)#(tab)  ,[MH_AS_rate_per_1000] = #(lf)#(tab)  sum(MH_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum([MH_local_expected_events])#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(tab)  #(lf)#(lf)#(tab)  ,[LD_AS_rate_per_1000] = #(lf)#(tab)  sum(LD_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(LD_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(tab)#(lf)#(lf)#(tab)  ,[Gloucester_AS_rate_per_1000] =#(lf)#(tab)  sum(gloucester_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(gloucester_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[Cheltenham_AS_rate_per_1000] =#(lf)#(tab)  sum(cheltenham_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(cheltenham_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[Cotswolds_AS_rate_per_1000] =#(lf)#(tab)  sum(cotswolds_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(cotswolds_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[FoD_AS_rate_per_1000] =#(lf)#(tab)  sum(FOD_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(FOD_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[SBV_AS_rate_per_1000] =#(lf)#(tab)  sum(SBV_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(SBV_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[TWNS_AS_rate_per_1000] =#(lf)#(tab)  sum(TWNS_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(TWNS_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  from #combined#(lf)#(lf)#(tab)  group by [cancer_type]#(lf)#(tab)  #(lf)#(lf)#(lf)#(tab)  -------------------#(lf)#(tab)  -------------------#(lf)"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Cheltenham_AS_rate_per_1000", "Cheltenham"}, {"core_20_AS_rate_per_1000", "Core 20"}, {"Cotswolds_AS_rate_per_1000", "Cotswolds"}, {"ethnic_minority_AS_rate_per_1000", "Ethnic Minority"}, {"FoD_AS_rate_per_1000", "Forest of Dean"}, {"Gloucester_AS_rate_per_1000", "Gloucester City"}, {"LD_AS_rate_per_1000", "Learning Disability"}, {"MH_AS_rate_per_1000", "Mental Health"}, {"reference_rate_per_1000", "Gloucestershire"}, {"SBV_AS_rate_per_1000", "Stroud & Berkeley Vale"}, {"TWNS_AS_rate_per_1000", "TWNS"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

