table 'Death incidence'
	lineageTag: 90986d05-d856-491b-bee3-8a25baf6a1ac

	column cancer_type
		dataType: string
		lineageTag: a28453de-7e06-4e07-b931-732284652bf5
		summarizeBy: none
		sourceColumn: cancer_type

		annotation SummarizationSetBy = Automatic

	column Gloucestershire
		dataType: double
		lineageTag: 93eb30fd-c2eb-451c-8bcf-6438c901ae99
		summarizeBy: sum
		sourceColumn: Gloucestershire

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Core 20'
		dataType: double
		lineageTag: f030a71e-efbc-4170-adc1-a71f652d07af
		summarizeBy: sum
		sourceColumn: Core 20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ethnic Minority'
		dataType: double
		lineageTag: 8f6b4eb6-8662-405b-a7e8-c52f7f2b8eb7
		summarizeBy: sum
		sourceColumn: Ethnic Minority

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mental Health'
		dataType: double
		lineageTag: 04937440-9a63-4672-ae6f-ecb6555cfc73
		summarizeBy: sum
		sourceColumn: Mental Health

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Learning Disability'
		dataType: double
		lineageTag: 195d7f4c-55b0-4196-8218-5d65937927f9
		summarizeBy: sum
		sourceColumn: Learning Disability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gloucester City'
		dataType: double
		lineageTag: a35fd933-494d-43e5-af08-91e35703c9a1
		summarizeBy: sum
		sourceColumn: Gloucester City

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cheltenham
		dataType: double
		lineageTag: b85f5976-7f7b-4390-bd93-a612d4379b7a
		summarizeBy: sum
		sourceColumn: Cheltenham

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cotswold
		dataType: double
		lineageTag: 926df533-ea2f-4af6-826a-925253db8152
		summarizeBy: sum
		sourceColumn: Cotswold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forest of Dean'
		dataType: double
		lineageTag: 60ec8795-13c2-4659-8ad8-05838cf3f53c
		summarizeBy: sum
		sourceColumn: Forest of Dean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stroud & Berkeley Vale'
		dataType: double
		lineageTag: ac977c81-3bda-41f2-ab51-78bf6613af7e
		summarizeBy: sum
		sourceColumn: Stroud & Berkeley Vale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TWNS
		dataType: double
		lineageTag: 81e47a60-9a01-483f-95c1-8e076a1e2061
		summarizeBy: sum
		sourceColumn: TWNS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Death incidence' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "data_mart_performance", [Query="#(tab)#(lf)#(tab)SET NOCOUNT ON#(lf)#(tab)IF OBJECT_ID ('TEMPDB..#table1') IS NOT NULL DROP TABLE #table1#(lf)#(tab)#(lf)#(tab)SELECT DISTINCT [B].[FinancialYear]#(lf)#(tab),[Primary_Diagnosis_ICD]#(lf)#(tab),[ICD10CodeDescription]#(lf)#(lf)#(tab),[Cancer_type] = CASE#(lf)#(tab)WHEN [Primary_Diagnosis_ICD] LIKE '%C3[3-9]%' then 'Lung Cancer'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C4[3-4]%' then 'Skin Cancer'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C5[1-8]%' then 'Gynaecological Cancers'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C50%' then 'Breast Cancer'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C1[7-9]%' then 'Lower-Gastrointestinal Cancers'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C2[0-1]%' then 'Lower-Gastrointestinal Cancers'#(lf)#(tab)WHEN  [Primary_Diagnosis_ICD] LIKE '%C26%' then 'Lower-Gastrointestinal Cancers'#(lf)#(lf)#(tab)END#(lf)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[B].MonthName#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[B].YearMonth#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[Record_ID]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[A].[Pseudo_NHS_Number]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[Referral_Type] = CASE WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '01' THEN 'Suspected breast cancer'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '02' THEN 'Suspected childrens cancer' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '03' THEN 'Suspected lung cancer'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '04' THEN 'Suspected haematological malignancies excluding acute leukaemia'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '05' THEN 'Suspected acute leukaemia'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '06' THEN 'Suspected upper gastrointestinal cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '07' THEN 'Suspected lower gastrointestinal cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '08' THEN 'Suspected skin cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '09' THEN 'Suspected gynaecological cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '10' THEN 'Suspected brain or central nervous system tumours'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '11' THEN 'Suspected urological cancers (excluding testicular)'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '12' THEN 'Suspected testicular cancer'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '13' THEN 'Suspected head and neck cancers'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '14' THEN 'Suspected sarcomas'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '16' THEN 'Exhibited (non-cancer) breast symptoms - cancer not initially suspected'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '17' THEN 'Suspected cancer- non-specific symptoms'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) WHEN [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] LIKE '18' THEN 'Other suspected cancer (not listed)'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) ELSE [Two_Week_Wait_Cancer_Or_Symptomatic_Breast_Referral_Type] END#(lf) #(lf)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[Counter] = 1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[A].Cancer_Treatment_Period_Start_Date#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,[A].Cancer_Referral_To_Treatment_Period_Start_Date#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,Patient_ODS_Code_Of_GP_Practice#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[GP].OrganisationName#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[GP].[PrimaryCareNetwork]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[locality] = case when [GP].Locality like '%cotswold%' then 'Cotswolds' else [GP].[locality] end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[PD].[DateOfDeath]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment] = datediff(day, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath])#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment_within_one_year] = case when datediff(day, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath]) <= 365 then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment_within_sixth_month] = case when datediff(month, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath]) <= 6 then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_from_treatment_within_four_weeks] = case when datediff(week, [A].Cancer_Treatment_Period_Start_Date, [PD].[DateOfDeath]) <= 4 then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[a].Patient_Gender#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[age_at_treatment] = DATEDIFF(year, [P].[Derived_Year_Month_Of_Birth], [A].Cancer_Treatment_Period_Start_Date)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[age].[5YR_Age_Band]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[sex] = case when [a].Patient_Gender like 1 then 'Male' when [a].Patient_Gender like 2 then 'Female' END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[A].[Local_Area_District_Of_Residence]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[A].Lowest_Geographical_Area_Of_Residence#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[IMD].[Derived_IMDGloucestershireDecile]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Death_flag] = CASE WHEN [PD].[Derived_NHS_Number] IS NULL THEN 0 ELSE 1 END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),Core20Flag = case when Lowest_Geographical_Area_Of_Residence in ('E01022120','E01022122','E01022131','E01022133','E01022147','E01022152','E01022160','E01022164','E01022238','E01022284','E01022285','E01022288','E01022289','E01022290','E01022291','E01022292','E01022311','E01022319','E01022320','E01022322','E01022323','E01022324','E01022328','E01022329','E01022332','E01022333','E01022346','E01022347','E01022458','E01032932','E01032937') then 1 else 0 end#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[Eth].[Ethnic Origin Grouped]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[MH_flag] = CASE WHEN [LTC_CODE] = 'QOF48_MH_COD' THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),[LD_flag] = CASE WHEN [LTC_CODE] = 'QOF48_LD_COD' THEN 1 ELSE 0 END #(lf)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(lf)#(tab)  INTO #table1#(lf)#(lf)#(tab)  FROM [Data_Mart_Performance].[dbo].[Cancer_Waits_v2] AS [A]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_DateLookup] AS [B] ON [B].[date] = [A].[Cancer_Treatment_Period_Start_Date]#(lf) #(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_ICD10] AS [ICD10] ON [ICD10].[ICD10Code] = [A].[Primary_Diagnosis_ICD]#(lf) #(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_GPPractice] AS [GP] ON [GP].[OrganisationCode] = Patient_ODS_Code_Of_GP_Practice#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Population].[vw_PDS_Deaths] [PD] ON [PD].[Derived_NHS_Number] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Population].[vw_PDS_All] [P] ON [P].[Derived_NHS_Number] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_AgeBand] [Age] ON [Age].Age = DATEDIFF(year, [P].[Derived_Year_Month_Of_Birth], [A].Cancer_Treatment_Period_Start_Date)#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_GeographyMapping] [G] ON [G].[LSOACode] = [A].[Lowest_Geographical_Area_Of_Residence]#(lf)#(tab)  LEFT JOIN [CCG_Reference].[Reference].[vw_LSOA_IMD] [IMD] ON [IMD].[LSOACode] = [A].[Lowest_Geographical_Area_Of_Residence]#(lf)#(tab)  #(lf)#(tab)  LEFT JOIN [BIReports].[MPI].[Ethnicity_Table] [Eth] ON [Eth].[PseudoNHSNo] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  LEFT JOIN [CCG_Current].[PrimaryCare].[vw_LongTermConditionsEvents] [PC] ON [PC].[Pseudo_NHS_Number] = [A].[Pseudo_NHS_Number]#(lf)#(lf)#(tab)  WHERE #(lf)#(tab)  [A].[Primary_Diagnosis_ICD] IS NOT NULL#(lf)#(tab)  AND #(lf)#(tab)  (#(lf)#(tab) [Primary_Diagnosis_ICD] LIKE '%C3[3-9]%' #(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C4[3-4]%' #(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C5[1-8]%'#(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C50%' #(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C1[7-9]%'#(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C2[0-1]%'#(lf)#(tab)OR  [Primary_Diagnosis_ICD] LIKE '%C26%'#(lf)#(tab)  )#(lf)#(lf)#(tab)  AND #(lf)#(tab)  [yearmonth] >= '201804'#(lf)#(lf)#(tab)  ORDER BY [Patient_ODS_Code_Of_GP_Practice]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#reference') IS NOT NULL DROP TABLE #reference#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [reference_events] = sum([Death_from_treatment_within_one_year]) #(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[reference_population] = sum([counter])#(lf)#(tab)  ,[reference_rate] = (cast(sum([Death_from_treatment_within_one_year]) as float)) / (cast(sum([counter]) as float))#(lf)#(tab)  ,[cancer_type] #(lf)#(lf)#(tab)  into #reference#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where #(lf)#(tab)  [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  order by [cancer_type], [5YR_Age_Band]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#deprived') IS NOT NULL DROP TABLE #deprived#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #deprived#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where Core20Flag like 1#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  order by [cancer_type], [5YR_Age_Band]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#ethnicity') IS NOT NULL DROP TABLE #ethnicity#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #ethnicity#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [Ethnic Origin Grouped] in ('Black or Black British', 'Mixed', 'Asian or Asian British', 'Other Ethnic Groups')#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  order by [cancer_type], [5YR_Age_Band]#(lf)#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#mental_health') IS NOT NULL DROP TABLE #mental_health#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #mental_health#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [MH_flag] like 1#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  order by [cancer_type], [5YR_Age_Band]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#LD') IS NOT NULL DROP TABLE #LD#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [LD_local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[LD_local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #LD#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [LD_flag] like 1#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  order by [cancer_type], [5YR_Age_Band]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#gloucester') IS NOT NULL DROP TABLE #gloucester#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [gloucester_local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[gloucester_local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #gloucester#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [locality] like 'Gloucester City'#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  ,locality#(lf)#(lf)#(tab)  order by [cancer_type], [5YR_Age_Band]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#cheltenham') IS NOT NULL DROP TABLE #cheltenham#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [cheltenham_local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[cheltenham_local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #cheltenham#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [locality] like 'Cheltenham'#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  ,locality#(lf)#(lf)#(tab)  order by [cancer_type], [5YR_Age_Band]#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#TWNS') IS NOT NULL DROP TABLE #TWNS#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [TWNS_local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[TWNS_local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #TWNS#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [locality] like 'Tewkesbury Newent and Staunton'#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  ,locality#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#SBV') IS NOT NULL DROP TABLE #SBV#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [SBV_local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[SBV_local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #SBV#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [locality] like 'Stroud and Berkeley Vale'#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  ,locality#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#FOD') IS NOT NULL DROP TABLE #FOD#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [FOD_local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[FOD_local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #FOD#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [locality] like 'The Forest of Dean'#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  ,locality#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#Cotswolds') IS NOT NULL DROP TABLE #Cotswolds#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [cotswolds_local_events] =  sum([Death_from_treatment_within_one_year])#(lf)#(tab)  ,[cotswolds_local_population] = sum([counter])#(lf)#(tab)  ,[5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(lf)#(tab)  into #Cotswolds#(lf)#(lf)#(tab)  from #table1#(lf)#(lf)#(tab)  where [locality] like 'Cotswolds'#(lf)#(tab)  and [5YR_Age_Band] is not null#(lf)#(lf)#(tab)  group by [5YR_Age_Band]#(lf)#(tab)  ,[cancer_type]#(lf)#(tab)  ,locality#(lf)#(lf)#(tab)  SET NOCOUNT ON#(lf)#(tab)  IF OBJECT_ID ('TEMPDB..#combined') IS NOT NULL DROP TABLE #combined#(lf)#(lf)#(tab)  SELECT #(lf)#(tab)  r.[5YR_Age_Band]#(lf)#(tab)  ,r.[cancer_type]#(lf)#(tab)  ,reference_events = cast(r.reference_events as float)#(lf)#(tab)  ,reference_population = cast(r.reference_population as float)#(lf)#(tab)  ,reference_rate = cast(r.reference_rate as float)#(lf)#(lf)#(tab)  ,core_20_local_events = cast(d.local_events as float)#(lf)#(tab)  ,core_20_local_population = cast(d.local_population as float)#(lf)#(tab)  ,[core_20_local_expected_events] = cast(d.local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,ethnic_minority_local_events = cast(e.local_events as float)#(lf)#(tab)  ,ethnic_minority_local_population = cast(e.local_population as float)#(lf)#(tab)  ,[ethnic_minority_local_expected_events] = cast(e.local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,MH_local_events = cast(m.local_events as float)#(lf)#(tab)  ,MH_local_population = cast(m.local_population as float)#(lf)#(tab)  ,[MH_local_expected_events] = cast(m.local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,LD_local_events#(lf)#(tab)  ,LD_local_population#(lf)#(tab)  ,[LD_local_expected_events] = cast(LD_local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,gloucester_local_events#(lf)#(tab)  ,gloucester_local_population#(lf)#(tab)  ,[gloucester_local_expected_events] = cast(gloucester_local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,cheltenham_local_events#(lf)#(tab)  ,cheltenham_local_population#(lf)#(tab)  ,[cheltenham_local_expected_events] = cast(cheltenham_local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,cotswolds_local_events#(lf)#(tab)  ,cotswolds_local_population#(lf)#(tab)  ,[cotswolds_local_expected_events] = cast(cotswolds_local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,FOD_local_events#(lf)#(tab)  ,FOD_local_population#(lf)#(tab)  ,[FOD_local_expected_events] = cast(FOD_local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,SBV_local_events#(lf)#(tab)  ,SBV_local_population#(lf)#(tab)  ,[SBV_local_expected_events] = cast(SBV_local_population * reference_rate as float)#(lf)#(lf)#(tab)  ,TWNS_local_events#(lf)#(tab)  ,TWNS_local_population#(lf)#(tab)  ,[TWNS_local_expected_events] = cast(TWNS_local_population * reference_rate as float)#(lf)#(lf)#(lf)#(tab)  into #combined#(lf)#(tab)  from #reference r#(lf)#(lf)#(tab)  LEFT JOIN #deprived d on d.[5YR_Age_Band] = r.[5YR_Age_Band] and d.[cancer_type] = r.Cancer_type#(lf)#(tab)  LEFT JOIN #ethnicity e on e.[5YR_Age_Band] = r.[5YR_Age_Band] and e.[Cancer_type] = r.Cancer_type#(lf)#(tab)  LEFT JOIN #mental_health m on m.[5YR_Age_Band] = r.[5YR_Age_Band] and m.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #LD ld on ld.[5YR_Age_Band] = r.[5YR_Age_Band] and ld.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #gloucester g on g.[5YR_Age_Band] = r.[5YR_Age_Band] and g.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #cheltenham che on [che].[5YR_Age_Band] = r.[5YR_Age_Band] and [che].Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #Cotswolds [cot] on [cot].[5YR_Age_Band] = r.[5YR_Age_Band] and [cot].Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #FOD fod on fod.[5YR_Age_Band] = r.[5YR_Age_Band] and fod.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #SBV SBV on SBV.[5YR_Age_Band] = r.[5YR_Age_Band] and SBV.Cancer_type = r.Cancer_type#(lf)#(tab)  LEFT JOIN #TWNS TWNS on TWNS.[5YR_Age_Band] = r.[5YR_Age_Band] and TWNS.Cancer_type = r.Cancer_type#(lf)#(lf)#(tab)  order by r.[cancer_type], r.[5YR_Age_Band]#(lf)#(lf)#(tab)  SELECT#(lf)#(tab)  [cancer_type]#(lf)#(tab)  ,[reference_rate_per_1000] = sum(reference_events) / sum(reference_population) * 1000#(lf)#(lf)#(tab)  ,[core_20_AS_rate_per_1000] = #(lf)#(tab)  sum(core_20_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum([core_20_local_expected_events])#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[ethnic_minority_AS_rate_per_1000] = #(lf)#(tab)  sum(ethnic_minority_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum([ethnic_minority_local_expected_events])#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(tab)  #(lf)#(lf)#(tab)  ,[MH_AS_rate_per_1000] = #(lf)#(tab)  sum(MH_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum([MH_local_expected_events])#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(tab)  #(lf)#(lf)#(tab)  ,[LD_AS_rate_per_1000] = #(lf)#(tab)  sum(LD_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(LD_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(tab)#(lf)#(lf)#(tab)  ,[Gloucester_AS_rate_per_1000] =#(lf)#(tab)  sum(gloucester_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(gloucester_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[Cheltenham_AS_rate_per_1000] =#(lf)#(tab)  sum(cheltenham_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(cheltenham_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[Cotswolds_AS_rate_per_1000] =#(lf)#(tab)  sum(cotswolds_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(cotswolds_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[FoD_AS_rate_per_1000] =#(lf)#(tab)  sum(FOD_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(FOD_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[SBV_AS_rate_per_1000] =#(lf)#(tab)  sum(SBV_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(SBV_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  ,[TWNS_AS_rate_per_1000] =#(lf)#(tab)  sum(TWNS_local_events) #(lf)#(tab)  / #(lf)#(tab)  sum(TWNS_local_expected_events)#(lf)#(tab)  *#(lf)#(tab)  (sum(reference_events) / sum(reference_population) * 1000)#(lf)#(lf)#(tab)  from #combined#(lf)#(lf)#(tab)  group by [cancer_type]#(lf)#(tab)  #(lf)#(lf)#(lf)#(tab)  -------------------#(lf)#(tab)  -------------------#(lf)"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Cheltenham_AS_rate_per_1000", "Cheltenham"}, {"core_20_AS_rate_per_1000", "Core 20"}, {"Cotswolds_AS_rate_per_1000", "Cotswold"}, {"ethnic_minority_AS_rate_per_1000", "Ethnic Minority"}, {"FoD_AS_rate_per_1000", "Forest of Dean"}, {"Gloucester_AS_rate_per_1000", "Gloucester City"}, {"LD_AS_rate_per_1000", "Learning Disability"}, {"MH_AS_rate_per_1000", "Mental Health"}, {"reference_rate_per_1000", "Gloucestershire"}, {"SBV_AS_rate_per_1000", "Stroud & Berkeley Vale"}, {"TWNS_AS_rate_per_1000", "TWNS"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

