table 'Admission Date Table'
	lineageTag: b441ac5b-182f-488e-8a76-973cac234379

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: b3175b5f-c10a-4196-b9c6-9b9bc0fd845e
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column day_month_year
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1ec919a1-9033-4cc0-b51c-cce285a9f8f5
		summarizeBy: none
		sourceColumn: day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day
		dataType: int64
		formatString: 0
		lineageTag: 26a078a0-ae7f-41d3-aae1-7aaca11aa964
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column weekday
		dataType: int64
		formatString: 0
		lineageTag: d7a1bc3b-d275-4689-b920-600e4a2aa1c5
		summarizeBy: none
		sourceColumn: weekday

		annotation SummarizationSetBy = Automatic

	column weekday_name
		dataType: string
		lineageTag: ee8000ae-6d8d-4a3f-a03d-5ba6599afa9c
		summarizeBy: none
		sourceColumn: weekday_name
		sortByColumn: weekday

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 715faa88-7396-46ba-883a-6def0b1e8952
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 713d1535-b122-496b-bf25-90677cc5b425
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 214fb764-547d-41a3-9c46-570323368915
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: int64
		formatString: 0
		lineageTag: 4a158e8c-aaba-4d2d-8cb9-66798a797654
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 8b5275f5-ecda-431b-9aef-35ad4e3f2bd4
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 8639956d-6547-42b4-a616-f2a468794443
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: 53331ce9-ac1a-4337-8668-29854286f2ab
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column is_working_day
		dataType: int64
		formatString: 0
		lineageTag: 88c0951b-c728-41b9-be26-9e4344731485
		summarizeBy: none
		sourceColumn: is_working_day

		annotation SummarizationSetBy = Automatic

	column financial_week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 24d437a1-32b4-4220-9795-8999c3c8721d
		summarizeBy: none
		sourceColumn: financial_week_of_year

		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: b06d8d7f-caf4-46fc-a246-aee3787eb915
		summarizeBy: none
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_quarter
		dataType: int64
		formatString: 0
		lineageTag: 618116eb-bb5a-4237-a336-409b908e483a
		summarizeBy: none
		sourceColumn: financial_quarter

		annotation SummarizationSetBy = Automatic

	column day_of_quarter
		dataType: int64
		formatString: 0
		lineageTag: 09b44d0a-592d-4b24-ac93-11c0fd14d455
		summarizeBy: none
		sourceColumn: day_of_quarter

		annotation SummarizationSetBy = Automatic

	column quarter_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f4646bce-256d-4006-aaa0-3edd4aba9947
		summarizeBy: none
		sourceColumn: quarter_start_date

		annotation SummarizationSetBy = Automatic

	column quarter_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c892ca79-039e-4f66-90cb-a38f728094d2
		summarizeBy: none
		sourceColumn: quarter_end_date

		annotation SummarizationSetBy = Automatic

	column month_day_no
		dataType: int64
		formatString: 0
		lineageTag: 226b8ec4-70e3-411d-a269-78453575377b
		summarizeBy: none
		sourceColumn: month_day_no

		annotation SummarizationSetBy = Automatic

	column financial_month
		dataType: int64
		formatString: 0
		lineageTag: 945f6eb5-2b67-4931-8d16-8415a3297ddf
		summarizeBy: none
		sourceColumn: financial_month

		annotation SummarizationSetBy = Automatic

	column month_year_name
		dataType: string
		lineageTag: 466fdb4c-bb63-412c-a602-acff0a0c2f7f
		summarizeBy: none
		sourceColumn: month_year_name

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 22135df6-0216-4d20-84d7-114722b33e6e
		summarizeBy: none
		sourceColumn: month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ytd_flag
		dataType: int64
		formatString: 0
		lineageTag: d8a3fef1-560e-49a3-8bb1-23752771b6b4
		summarizeBy: none
		sourceColumn: ytd_flag

		annotation SummarizationSetBy = Automatic

	column latest_month_flag
		dataType: int64
		formatString: 0
		lineageTag: b13d98ba-0068-465d-b006-984239df34fc
		summarizeBy: none
		sourceColumn: latest_month_flag

		annotation SummarizationSetBy = Automatic

	column previous_month_flag
		dataType: int64
		formatString: 0
		lineageTag: 0fc194c2-bd81-4393-ad9f-134bee06e5e1
		summarizeBy: none
		sourceColumn: previous_month_flag

		annotation SummarizationSetBy = Automatic

	column latest_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: f8e286e4-af51-495b-b463-4717967b8595
		summarizeBy: none
		sourceColumn: latest_12_months_flag

		annotation SummarizationSetBy = Automatic

	column previous_12_months_flag
		dataType: int64
		formatString: 0
		lineageTag: 0ef64cd5-8642-4251-9e27-6bd09640a44b
		summarizeBy: none
		sourceColumn: previous_12_months_flag

		annotation SummarizationSetBy = Automatic

	column same_month_last_year_flag
		dataType: int64
		formatString: 0
		lineageTag: 37c69b43-3811-46d7-a028-9ad796311f83
		summarizeBy: none
		sourceColumn: same_month_last_year_flag

		annotation SummarizationSetBy = Automatic

	column Week_Ending_Sunday = ```
			
			VAR _CURRENT = 'Admission Date Table'[date]
			RETURN 
			    _CURRENT + (7 - weekday(_CURRENT, 2) ) 
			```
		formatString: Long Date
		lineageTag: d881faab-14f6-4726-a334-8544137bc297
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	hierarchy 'day_month_year Hierarchy'
		lineageTag: 74bbc7dd-63ac-4c64-b90a-a72766eee7cf

		level day_month_year
			lineageTag: af2c7434-217c-467a-b465-1e16e9afda43
			column: day_month_year

		level month_year
			lineageTag: 63c8ea5e-6bb4-4a7d-8daf-571f37772f01
			column: month_year

		level Week_Ending_Sunday
			lineageTag: 3eb312c6-e676-4974-9b4a-cc72ccc47bb5
			column: Week_Ending_Sunday

	hierarchy 'month_year Hierarchy'
		lineageTag: 92ca57a0-870f-47e4-8919-7c821c2c4c7a

		level month_year
			lineageTag: e366a3a4-49a0-4a8b-bcf9-c06aaf40d241
			column: month_year

		level Week_Ending_Sunday
			lineageTag: 3304cf0b-bf06-4e52-b661-e9e3d2d4ee93
			column: Week_Ending_Sunday

		level day_month_year
			lineageTag: 6df9b8c1-d8c6-4520-9883-8a9041a99162
			column: day_month_year

	hierarchy 'financial_year Hierarchy'
		lineageTag: b5c51418-4bdc-49b9-b082-a0a21466505a

		level financial_year
			lineageTag: ea74e3c8-511f-4d39-bc85-2f2b6a6dd7b1
			column: financial_year

		level month_year
			lineageTag: 4e167e2f-2c70-4cd0-9a85-79674a6e6238
			column: month_year

	partition 'Admission Date Table' = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "ccg_reference", [Query="/*===============================================================================================================#(lf)New Date Reference Script#(lf)Created by: Ben Adams#(lf)Created Date: 27/12/2023#(lf)===============================================================================================================*/#(lf)SELECT DISTINCT [date] = CAST([Full_Date] AS DATE)#(lf)               ,[day_month_year] = CONVERT(VARCHAR, [Full_Date], 103) --> 103 converts to DD/MM/YYYY format#(lf)#(tab)#(tab)#(tab)   ,[day] = [Day_Of_Fin_Year]#(lf)#(tab)#(tab)#(tab)   ,[weekday] = [Weekday_No]#(lf)#(tab)#(tab)#(tab)   ,[weekday_name] = [Weekday_Name]#(lf)#(tab)#(tab)#(tab)   ,[month] = [Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_name] = [Month_Short_Name]#(lf)#(tab)#(tab)#(tab)   ,[quarter] = [Cal_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[year_month] = [Year_Month]#(lf)#(tab)#(tab)#(tab)   ,[is_weekend] = CASE WHEN [Weekday_No] IN (6,7) THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[is_holiday] = CASE WHEN [Bank_Holiday_Desc] IS NOT NULL THEN 1 ELSE 0 END#(lf)#(tab)#(tab)#(tab)   ,[holiday_description] = [Bank_Holiday_Desc] --> Description of holiday type i.e., 'Bank Holiday'#(lf)#(tab)#(tab)#(tab)   ,[is_working_day] = [Working_Day_Calc]#(lf)#(tab)#(tab)#(tab)   ,[financial_week_of_year] = [Fin_Week_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_year] = REPLACE([Fin_Year_YYYY_dash_YY], ' - ', '/')#(lf)#(tab)#(tab)#(tab)   ,[financial_quarter] = [Fin_Quarter_No]#(lf)#(tab)#(tab)#(tab)   ,[day_of_quarter] = [Day_Of_Quarter]#(lf)#(tab)#(tab)#(tab)   ,[quarter_start_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[quarter_end_date] = CAST([Quarter_Start] AS DATE)#(lf)#(tab)#(tab)#(tab)   ,[month_day_no] = [Month_Day_No]#(lf)#(tab)#(tab)#(tab)   ,[financial_month] = [Fin_Month_No]#(lf)#(tab)#(tab)#(tab)   ,[month_year_name] = CONCAT([Month_Short_Name], '-', LEFT([Date_112], 4))#(lf)#(tab)#(tab)#(tab)   ,[month_year] = [MonthYear_MMMM_YYYYY]#(lf)#(tab)#(tab)#(tab)   ,[ytd_flag] = CASE WHEN [Fin_Month_No] <= (#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               SELECT#(lf)                                           CAST([Fin_Month_No] AS INT)#(lf)                                           FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               WHERE [Full_Date] = EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)               )#(lf)                                           THEN 1 ELSE 0 END --> Establishes whether the month is included in year to date calculations and reflects across all years#(lf)#(tab)#(tab)#(tab)   ,[latest_month_flag] = CASE WHEN [Year_Month] IN #(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_month_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                         (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                          FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -2, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  THEN 1 ELSE 0 END --> The month before the latest month available within your date range#(lf)#(tab)#(tab)#(tab)   ,[latest_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                             (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                              FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -12, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)  AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)      THEN 1 ELSE 0 END --> The latest 12 months within your date range#(lf)#(tab)#(tab)#(tab)   ,[previous_12_months_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                               (SELECT DISTINCT [Year_Month]#(lf)#(tab)#(tab)#(tab)                                FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        WHERE [Full_Date] BETWEEN EOMONTH ( DATEADD ( MONTH, -24, GETDATE() ) ) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)    AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)        THEN 1 ELSE 0 END --> The 12 months before the latest 12 months within your date range - allows comparing current to previous#(lf)#(tab)#(tab)#(tab)   ,[same_month_last_year_flag] = CASE WHEN [Year_Month] IN#(lf)#(tab)#(tab)#(tab)                                 (SELECT DISTINCT MAX([Year_Month]) #(lf)#(tab)#(tab)#(tab)                                 FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         WHERE [Full_Date] BETWEEN '20190401' AND EOMONTH ( DATEADD ( MONTH, -13, GETDATE() ) )) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)         THEN 1 ELSE 0 END --> Same month last year as the latest month within the date range i.e., Nov-22 and Nov-23#(lf) #(lf)FROM [DSCRO_NATIONAL_LOOKUPS].[dbo].[ref_Dates]#(lf) #(lf)--WHERE [Full_Date] BETWEEN '20180401' AND EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) ) --> This can be changed to meet your date range need. #(lf)                                                                                      --  The EOMONTH function finds the latest complete month.#(lf)#(lf)WHERE [Full_Date] BETWEEN '20180401' AND GETDATE() #(lf) #(lf)ORDER BY CAST([Full_Date] AS DATE) desc"]),
				    #"Sorted Rows" = Table.Sort(Source,{{"date", Order.Descending}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Sorted Rows",{{"day_month_year", type date}, {"month_year", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

