table 'Hospital @ Home'
	lineageTag: 749ce3c2-c895-47d8-8a7b-01a9165c8aee

	measure H@H_LATEST_WEEK =
			
			CALCULATE(SUM('Hospital @ Home'[Counter]), 'Hospital @ Home'[Latest_week_discharge_flag] = 1)
		formatString: 0
		lineageTag: 5035af32-55c9-418b-bb23-02c6bf1600a5

	measure 'Latest Week End H@H' = ```
			
			VAR LatestWeek = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact]), ALL('Hospital @ Home'))
			RETURN 
			FORMAT(LatestWeek, "dd mmmm yyyy")
			
			```
		lineageTag: bc365132-d4ba-4741-ae7d-53925ec48789

	measure H@H_PREVIOUS_WEEK =
			
			CALCULATE(SUM('Hospital @ Home'[Counter]), 'Hospital @ Home'[Previous_week_discharge_flag] = 1)
		formatString: 0
		lineageTag: a500eb78-0493-4118-9d31-82d4f8dae263

	measure H@H_LATEST_4WEEK =
			
			CALCULATE(SUM('Hospital @ Home'[Counter]) /4 , 'Hospital @ Home'[Latest_discharge_4week_flag] = 1)
		formatString: 0
		lineageTag: 815179de-b21b-4629-bf92-b566db89b3b7

	measure H@H_PREVIOUS_4WEEK =
			
			CALCULATE(SUM('Hospital @ Home'[Counter])/4, 'Hospital @ Home'[Previous_discharge_4week_flag] = 1)
		formatString: 0
		lineageTag: 473e7a68-1aa7-40c4-b5f7-477afaf08a90

	column UniqueServiceRequestID
		dataType: string
		lineageTag: c9f39ec4-860c-4d0f-86dd-7001c94710dc
		summarizeBy: none
		sourceColumn: UniqueServiceRequestID

		annotation SummarizationSetBy = Automatic

	column Visitcount
		dataType: int64
		formatString: 0
		lineageTag: 48044975-8a2b-47d3-a97e-51b0e4861c58
		summarizeBy: sum
		sourceColumn: Visitcount

		annotation SummarizationSetBy = Automatic

	column UniqueCareContactID
		dataType: string
		lineageTag: 634ad240-c294-4e8d-82b0-b816c4179e76
		summarizeBy: none
		sourceColumn: UniqueCareContactID

		annotation SummarizationSetBy = Automatic

	column Derived_Pseudo_NHS
		dataType: string
		lineageTag: da20b36f-3b81-4fb6-82af-b4d98fa8ee72
		summarizeBy: none
		sourceColumn: Derived_Pseudo_NHS

		annotation SummarizationSetBy = Automatic

	column AgeYrContactDate
		dataType: string
		lineageTag: 7e5a9637-e707-48f4-a18e-14465267ffda
		summarizeBy: none
		sourceColumn: AgeYrContactDate

		annotation SummarizationSetBy = Automatic

	column OrgIDCommissioner
		dataType: string
		lineageTag: e0789ea1-13db-423b-ab8d-58ea3db0c706
		summarizeBy: none
		sourceColumn: OrgIDCommissioner

		annotation SummarizationSetBy = Automatic

	column OrgIDCommissionerDescription
		dataType: string
		lineageTag: 3685195c-c2cb-4da2-ae14-e5cbb9aee5ff
		summarizeBy: none
		sourceColumn: OrgIDCommissionerDescription

		annotation SummarizationSetBy = Automatic

	column OrgIDProvider
		dataType: string
		lineageTag: 83f1b840-9575-4313-a05c-4b818e729410
		summarizeBy: none
		sourceColumn: OrgIDProvider

		annotation SummarizationSetBy = Automatic

	column OrgIDProviderDescription
		dataType: string
		lineageTag: ee846f88-6a4f-413c-8423-a3a0f72e1e92
		summarizeBy: none
		sourceColumn: OrgIDProviderDescription

		annotation SummarizationSetBy = Automatic

	column ContactDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc9902be-fd22-4e6a-b558-2d68158303ef
		summarizeBy: none
		sourceColumn: ContactDate

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ContactTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0d82d471-f30b-4e95-86ef-fe7e7fbd33d0
		summarizeBy: none
		sourceColumn: ContactTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column AdminCategory
		dataType: string
		lineageTag: 5fa0689b-21eb-496a-87a5-3bc7ef4f0313
		summarizeBy: none
		sourceColumn: AdminCategory

		annotation SummarizationSetBy = Automatic

	column AdminCategoryDescription
		dataType: string
		lineageTag: 240bc529-74cf-44c7-bb39-4129d9a5eb98
		summarizeBy: none
		sourceColumn: AdminCategoryDescription

		annotation SummarizationSetBy = Automatic

	column CareContactDuration
		dataType: string
		lineageTag: 180f857f-3723-4051-9368-b18f0b92fe99
		summarizeBy: none
		sourceColumn: CareContactDuration

		annotation SummarizationSetBy = Automatic

	column ConsultationType
		dataType: string
		lineageTag: 9289a6c7-5879-4368-99b9-f1661be8d515
		summarizeBy: none
		sourceColumn: ConsultationType

		annotation SummarizationSetBy = Automatic

	column ConsultationTypeDescription
		dataType: string
		lineageTag: 5429f4ed-eded-4e07-a65a-9415b7b8f35e
		summarizeBy: none
		sourceColumn: ConsultationTypeDescription

		annotation SummarizationSetBy = Automatic

	column CareContactSubject
		dataType: string
		lineageTag: ca5ca2d1-6947-4a50-97fb-b80f502ae0bb
		summarizeBy: none
		sourceColumn: CareContactSubject

		annotation SummarizationSetBy = Automatic

	column CareContactSubjectDescription
		dataType: string
		lineageTag: bb55cc97-ccbc-4d01-b133-efe5ec33bc16
		summarizeBy: none
		sourceColumn: CareContactSubjectDescription

		annotation SummarizationSetBy = Automatic

	column ConsultationMediumUsed
		dataType: string
		lineageTag: eea5e3da-a2d3-4b75-ab50-0c354a307401
		summarizeBy: none
		sourceColumn: ConsultationMediumUsed

		annotation SummarizationSetBy = Automatic

	column ConsultationMediumUsedDescription
		dataType: string
		lineageTag: fb51a526-2523-4c38-9201-9c2be1ad7e04
		summarizeBy: none
		sourceColumn: ConsultationMediumUsedDescription

		annotation SummarizationSetBy = Automatic

	column ActivityLocationType
		dataType: string
		lineageTag: 58287a22-d635-4825-811b-72cb4f32cec3
		summarizeBy: none
		sourceColumn: ActivityLocationType

		annotation SummarizationSetBy = Automatic

	column ActivityLocationTypeDescription
		dataType: string
		lineageTag: 330576e0-ce97-46c9-951d-863d3b22999e
		summarizeBy: none
		sourceColumn: ActivityLocationTypeDescription

		annotation SummarizationSetBy = Automatic

	column TreatmentOrgSiteID
		dataType: string
		lineageTag: 8a649439-3d78-4a11-b60c-4220c41f390e
		summarizeBy: none
		sourceColumn: TreatmentOrgSiteID

		annotation SummarizationSetBy = Automatic

	column TreatmentOrgSiteIDDescription
		dataType: string
		lineageTag: 0bb211ec-2498-46be-86a4-009cc952c623
		summarizeBy: none
		sourceColumn: TreatmentOrgSiteIDDescription

		annotation SummarizationSetBy = Automatic

	column ReferralCostCentre
		dataType: string
		lineageTag: 8414cc26-dbfe-410f-91df-08737752d665
		summarizeBy: none
		sourceColumn: ReferralCostCentre

		annotation SummarizationSetBy = Automatic

	column AllCostCentresOnReferral
		dataType: string
		lineageTag: 97b1cc80-dce4-48d7-a879-c939b47355d8
		summarizeBy: none
		sourceColumn: AllCostCentresOnReferral

		annotation SummarizationSetBy = Automatic

	column ReferralRequestReceivedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: e2e78656-8106-4487-a369-d3c17603630b
		summarizeBy: none
		sourceColumn: ReferralRequestReceivedDate

		annotation SummarizationSetBy = Automatic

	column ClinicalContactFlag
		dataType: int64
		formatString: 0
		lineageTag: f2a04657-c6e0-4ce7-bd33-912d9ca9a11e
		summarizeBy: sum
		sourceColumn: ClinicalContactFlag

		annotation SummarizationSetBy = Automatic

	column AttendOrNot
		dataType: string
		lineageTag: 8cf50cf8-42d3-46be-b5be-9086ffafa9b6
		summarizeBy: none
		sourceColumn: AttendOrNot

		annotation SummarizationSetBy = Automatic

	column AttendOrNotDescription
		dataType: string
		lineageTag: ab889c08-2ffd-4455-9669-a3acb04ea10a
		summarizeBy: none
		sourceColumn: AttendOrNotDescription

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 18a9b184-52ed-4baf-aef9-a09e978044b7
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FinancialMonth
		dataType: int64
		formatString: 0
		lineageTag: 1c270e76-bc1c-411e-8c29-7e590c44a14d
		summarizeBy: sum
		sourceColumn: FinancialMonth

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 97b811e5-5acc-4220-9ec7-497919930e29
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: FinancialMonth

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: 84cd6045-724a-4df4-80f3-24318d0501c0
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Service
		dataType: string
		lineageTag: 4d91cd24-a4bc-4949-bd3d-480976e98a83
		summarizeBy: none
		sourceColumn: Service

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: int64
		formatString: 0
		lineageTag: 288e2cf4-81c0-4577-8f37-3496005613be
		summarizeBy: sum
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	column admitting_ward
		dataType: string
		lineageTag: df2c8115-db0f-4534-8b83-6594cbc2db07
		summarizeBy: none
		sourceColumn: admitting_ward

		annotation SummarizationSetBy = Automatic

	column Week_Ending_Sunday_Contact = ```
			
			VAR _CURRENT = 'Hospital @ Home'[ContactDate]
			RETURN 
			    _CURRENT + (7 - weekday(_CURRENT, 2) ) 
			```
		formatString: Long Date
		lineageTag: d3b4339b-03b9-4b40-9a75-adfd9e7cda09
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Latest_week_discharge_flag = ```
			
			IF('Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact]), ALL('Hospital @ Home')), 1,0)
			
			```
		formatString: 0
		lineageTag: b0e39c1d-28a1-4654-85d1-6ef2311c2f22
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.day'
		dataType: int64
		formatString: 0
		lineageTag: 31ca3e19-d8f1-4cfe-9efd-e570ae2e6631
		summarizeBy: sum
		sourceColumn: Discharge Date Table.day

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.weekday'
		dataType: int64
		formatString: 0
		lineageTag: 26093440-7d00-4b75-9aa8-8d13ac313aa7
		summarizeBy: sum
		sourceColumn: Discharge Date Table.weekday

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.weekday_name'
		dataType: string
		lineageTag: 520d5a2b-2f81-4e3c-85a1-bd15ae211849
		summarizeBy: none
		sourceColumn: Discharge Date Table.weekday_name
		sortByColumn: 'Discharge Date Table.weekday'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.month'
		dataType: int64
		formatString: 0
		lineageTag: 06a3fea4-40e8-4975-a162-f5080e4a5c63
		summarizeBy: sum
		sourceColumn: Discharge Date Table.month

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.month_name'
		dataType: string
		lineageTag: 0e8898ab-1edb-4c0b-846b-aa4b5d71d721
		summarizeBy: none
		sourceColumn: Discharge Date Table.month_name

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.year_month'
		dataType: int64
		formatString: 0
		lineageTag: cb423817-8239-45d2-8742-5946b34a4237
		summarizeBy: sum
		sourceColumn: Discharge Date Table.year_month

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.financial_year'
		dataType: string
		lineageTag: 25aaf5d7-b54f-4524-b636-ec0106d5d9ec
		summarizeBy: none
		sourceColumn: Discharge Date Table.financial_year

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.financial_month'
		dataType: int64
		formatString: 0
		lineageTag: 628aec2d-4e1b-4db8-9bad-ffbdd76ed0e4
		summarizeBy: sum
		sourceColumn: Discharge Date Table.financial_month

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.month_year'
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 0b7ac3b0-050b-4655-afa5-0b440755851e
		summarizeBy: none
		sourceColumn: Discharge Date Table.month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column VW_Admitted
		dataType: int64
		formatString: 0
		lineageTag: fd9bbb7e-710c-4e5e-941e-afe68bc44947
		summarizeBy: sum
		sourceColumn: VW_Admitted

		annotation SummarizationSetBy = Automatic

	column AgeBand5yr
		dataType: string
		lineageTag: 46111251-a990-42e6-ba30-a09538df0c80
		summarizeBy: none
		sourceColumn: AgeBand5yr

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: bac2c35a-4dd7-4573-bab3-9ab848726e82
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column LocalityName
		dataType: string
		lineageTag: d656106f-ac63-454f-b291-b5d5d5b4a377
		summarizeBy: none
		sourceColumn: LocalityName

		annotation SummarizationSetBy = Automatic

	column EthnicOriginDescription
		dataType: string
		lineageTag: df9bdb75-1bd1-445f-8790-9faec4c0e7fc
		summarizeBy: none
		sourceColumn: EthnicOriginDescription

		annotation SummarizationSetBy = Automatic

	column RuralUrbanClass
		dataType: int64
		formatString: 0
		lineageTag: e1755c9f-7f10-4e69-ab74-7a16f3c16d4d
		summarizeBy: sum
		sourceColumn: RuralUrbanClass

		annotation SummarizationSetBy = Automatic

	column eFI_Catgory_derived
		dataType: string
		lineageTag: 73041cd0-809a-40b2-a8f3-bb2233973364
		summarizeBy: none
		sourceColumn: eFI_Catgory_derived

		annotation SummarizationSetBy = Automatic

	column IMDcountyDecile
		dataType: int64
		formatString: 0
		lineageTag: 7296e61e-89ab-4710-9b6c-de6f25eeef1d
		summarizeBy: sum
		sourceColumn: IMDcountyDecile

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date Table.day_month_year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9ce1644f-5e4e-462a-ba25-c96898e20070
		summarizeBy: none
		sourceColumn: Discharge Date Table.day_month_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ContactHour = ```
			HOUR('Hospital @ Home'[ContactTime]) 
			```
		formatString: 0
		lineageTag: 58bed96e-58fe-4a80-b9f1-ba9655d49034
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SeenorNotSeen
		dataType: string
		lineageTag: 9f797957-5eac-4c31-913e-eaa93c83fb65
		summarizeBy: none
		sourceColumn: SeenorNotSeen

		annotation SummarizationSetBy = Automatic

	column Previous_week_discharge_flag = ```
			
			IF('Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact]), ALL('Hospital @ Home')) -7, 1,0)
			
			```
		formatString: 0
		lineageTag: cbda7aeb-77a0-4744-9892-dc90c247d1a8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Latest_discharge_4week_flag = ```
			
			IF( 'Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact]), ALL('Hospital @ Home')) -7
			    || 'Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact] ), ALL('Hospital @ Home')) -14
			    ||'Hospital @ Home'[Week_Ending_Sunday_Contact]  = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact] ), ALL('Hospital @ Home')) -21
			    || 'Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact] ), ALL('Hospital @ Home')),
			    1, 0 ) 
			```
		formatString: 0
		lineageTag: eddb0d1f-bf30-46ac-a755-013638bdb0f7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Previous_discharge_4week_flag = ```
			
			IF( 'Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact]), ALL('Hospital @ Home')) -28
			    || 'Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact] ), ALL('Hospital @ Home')) -35
			    ||'Hospital @ Home'[Week_Ending_Sunday_Contact]  = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact] ), ALL('Hospital @ Home')) -42
			    || 'Hospital @ Home'[Week_Ending_Sunday_Contact] = CALCULATE(MAX('Hospital @ Home'[Week_Ending_Sunday_Contact] ), ALL('Hospital @ Home')) -48,
			    1, 0 ) 
			```
		formatString: 0
		lineageTag: 3044d004-4044-4932-b118-e603be9c7428
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Week_Ending_Sunday
		dataType: dateTime
		formatString: General Date
		lineageTag: f17249e8-bf60-43c2-825b-2d2c9939f20c
		summarizeBy: none
		sourceColumn: Week_Ending_Sunday

		annotation SummarizationSetBy = Automatic

	column Week_Ending_Sunday2
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ee68b77-e71b-4c8b-9f70-d43355c332a9
		summarizeBy: none
		sourceColumn: Week_Ending_Sunday2

		annotation SummarizationSetBy = Automatic

	column 'LSOA Code'
		dataType: string
		lineageTag: 41b8da97-7f39-42ab-b2df-b8637ba841eb
		summarizeBy: none
		sourceColumn: LSOA Code

		annotation SummarizationSetBy = Automatic

	column LSOACode
		dataType: string
		lineageTag: a61f1954-3b5f-4a24-9c19-987091470ce0
		summarizeBy: none
		sourceColumn: LSOACode

		annotation SummarizationSetBy = Automatic

	column RUC11Code
		dataType: string
		lineageTag: a9137b15-845e-4ad6-8ce7-a84ef16d488f
		summarizeBy: none
		sourceColumn: RUC11Code

		annotation SummarizationSetBy = Automatic

	column RUC11Desc
		dataType: string
		lineageTag: bf80e114-1dcb-4d62-98b0-bebf8409754d
		summarizeBy: none
		sourceColumn: RUC11Desc

		annotation SummarizationSetBy = Automatic

	column Rural_Urban
		dataType: string
		lineageTag: 2a1186b9-566d-42ed-9d1d-0b551e31bd44
		summarizeBy: none
		sourceColumn: Rural_Urban

		annotation SummarizationSetBy = Automatic

	hierarchy 'Discharge Date Table.day_month_year Hierarchy'
		lineageTag: 4b295feb-564b-4a82-8740-96ea95b53483

		level 'Discharge Date Table.day_month_year'
			lineageTag: 88bf4dab-4abf-403b-8afb-25bff3cef6e1
			column: 'Discharge Date Table.day_month_year'

		level 'Discharge Date Table.month_year'
			lineageTag: 62c4b70f-4b82-4404-891c-212e11ce684c
			column: 'Discharge Date Table.month_year'

		level Week_Ending_Sunday_Contact
			lineageTag: 0294c8b3-121c-4551-9dd2-54cb06ba76da
			column: Week_Ending_Sunday_Contact

	partition 'Hospital @ Home' = m
		mode: import
		source =
				let
				    Source = Sql.Database("GRH-CCG-SQL", "CCG_CURRENT", [Query="---NOTE - PLEASE don't query date before 01/04/2022 as  we are unable to obtain the team associated with the activity.#(lf)#(tab)--double check the figures using GHC tableau. #(lf)#(lf)#(tab)IF OBJECT_ID ('tempdb..#HAH') IS NOT NULL DROP TABLE #HAH#(lf)#(tab)SELECT #(lf)#(tab)c.UniqueServiceRequestID#(lf)#(tab),ROW_NUMBER() OVER (PARTITION BY c.UniqueServiceRequestID ORDER BY ContactDate ASC) AS Visitcount #(lf)#(tab),c.UniqueCareContactID#(lf)#(tab),c.Derived_Pseudo_NHS#(lf)#(tab),c.AgeYrContactDate#(lf)#(tab),c.OrgIDCommissioner#(lf)#(tab),c.OrgIDCommissionerDescription#(lf)#(tab),c.OrgIDProvider#(lf)#(tab),c.OrgIDProviderDescription#(lf)#(tab),VW.admitting_ward#(lf)#(tab),[VW_Admitted] = CASE WHEN VW.administrative_category_code ='01' THEN 1 ELSE 0 END #(lf)#(tab),c.ContactDate#(lf)#(tab),c.ContactTime#(lf)#(tab),c.AdminCategory#(lf)#(tab),c.AdminCategoryDescription#(lf)#(tab),c.CareContactDuration#(lf)#(tab),c.ConsultationType#(lf)#(tab),ConsultationTypeDescription#(lf)#(tab),c.CareContactSubject#(lf)#(tab),c.CareContactSubjectDescription#(lf)#(tab),c.ConsultationMediumUsed#(lf)#(tab),c.ConsultationMediumUsedDescription#(lf)#(tab),c.ActivityLocationType#(lf)#(tab),c.ActivityLocationTypeDescription#(lf)#(tab),c.TreatmentOrgSiteID#(lf)#(tab),c.TreatmentOrgSiteIDDescription#(lf)#(tab),r.ReferralCostCentre#(lf)#(tab),r.AllCostCentresOnReferral#(lf)#(tab),r.ReferralRequestReceivedDate#(lf)#(tab),c.ClinicalContactFlag#(lf)#(tab),AttendOrNot#(lf)#(tab),AttendOrNotDescription#(lf)#(tab),d.FinancialYear#(lf)#(tab),d.FinancialMonth#(lf)#(tab),d.[MonthName]#(lf)#(tab),DATEADD(DAY, 7 - DATEPART(WEEKDAY, ContactDate), CAST(ContactDate AS DATE)) AS Week_Ending_Sunday#(lf)#(tab),h.Team#(lf)#(tab),h.Service#(lf)#(tab),[Counter] = 1#(lf)#(lf)#(tab),MPI.AgeBand5yr#(lf)#(tab),MPI.Gender#(lf)#(tab),MPI.LocalityName#(lf)#(tab),MPI.EthnicOriginDescription#(lf)#(tab),MPI.RuralUrbanClass#(lf)#(tab),MPI.eFI_Catgory_derived#(lf)#(tab),MPI.IMDcountyDecile#(lf)#(tab),MPI.[LSOA Code]#(lf)#(tab)  #(lf)#(tab)  INTO #HAH#(lf)#(tab)  FROM [CCG_Current].[CSDS].[vw_302_CareContact] as c#(lf)#(lf)#(tab)  left join CCG_Reference.Reference.vw_DateLookup as d on d.Date = cast(c.ContactDate as date)#(lf)#(lf)#(tab)  LEFT join CCG_Current.CSDS.vw_301_Referral as r on c.UniqueServiceRequestID = r.UniqueServiceRequestID#(lf)#(tab)  --Due to configuration issues in systmOne GHC are unable to identify the team at contact ; as a proxy the contact uses the referral cost centre. #(lf)#(tab)  left join CCG_Reference.GHC.vw_Hierarchy as h on r.ReferralCostCentre = h.Cost_Centre -- hierarchy is a reference to GHC #(lf)#(lf)#(tab) LEFT JOIN [CCG_Current].GHFT.vw_IPVirtualWard AS VW   ON VW.nhs_number = c.Derived_Pseudo_NHS#(lf)#(lf) ----------- Joining for demographic data --------------#(lf)#(tab)LEFT JOIN [BIReports].[MPI].[MPI_current] as MPI#(lf)    ON MPI.Derived_Pseudo_NHS = C.Derived_Pseudo_NHS #(lf)#(lf)#(tab)where #(lf)#(tab)c.OrgIDProvider  like 'RTQ%' -- GHC #(lf)#(tab)and c.OrgIDCommissioner like '11M%' -- glos patients only#(lf)#(tab)and c.ContactDate>= '20220401' #(lf)#(tab)and (c.ClinicalContactFlag = 1 or c.ClinicalContactFlag is null)   -- added 20/01/2025 due to GHC logic. If the consultation mechanism is null then this is classed as an admin event i.e. not clinical . Assuming all other providers provide non clinical events only. #(lf)#(tab)  #(lf)#(tab)AND  ( r.ReferralCostCentre in ('G15503', --Rapid Response#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)'G15503a', --Rapid Response - RR - ENDNS#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)'G15503b', --Rapid Response - RR - District Nursing   #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)'G15501') -- IV Therapy ---- change teams as required #(lf)#(lf)#(tab) ---- change teams below as required , accounts for DQ issues whereby multiple teams are assigned at the point of referral and can't distinguish the first. #(lf)#(tab) OR r.AllCostCentresOnReferral like  ('%G15503%') --Rapid Response#(lf)#(tab) OR r.AllCostCentresOnReferral like  ('%G15503a%') --Rapid Response - RR - ENDNS#(lf)#(tab) OR r.AllCostCentresOnReferral like  ('%G15503b%')--Rapid Response - RR - District Nursing   #(lf)#(tab) OR r.AllCostCentresOnReferral like  ('G15501')) -- IV Therapy#(lf)#(lf)#(lf)#(tab)and (AttendOrNot in ('5','6') -- attended contacts only  -- there are known to be a number of nulls in this field but may not apply to the teams you need so please check this#(lf)#(tab)OR AttendOrNot IS NULL )#(lf)#(lf)#(tab)AND ConsultationMediumUsed = '01'#(lf)#(lf)#(tab)AND C.Derived_Pseudo_NHS IS NOT NULL#(lf)#(lf)#(tab)order by c.ContactDate asc ;#(lf)#(lf)#(lf)#(lf)-- Ensuring that only full weeks are pulled through --#(lf)#(tab)#(lf)#(tab)SELECT *,#(lf)#(tab)CASE WHEN RU.RUC11Desc LIKE '%urban%' THEN 'Urban' #(lf)#(tab)#(tab) WHEN RU.RUC11Desc LIKE '%rural%' THEN 'Rural' #(lf)#(tab)     ELSE 'Unknown' END AS 'Rural_Urban'#(lf)#(tab)#(lf)#(tab)FROM #HAH#(lf)#(lf)#(tab)INNER JOIN (#(lf)#(tab)#(tab)SELECT [Week_Ending_Sunday]#(lf)#(tab)#(tab)FROM #HAH #(lf)#(tab)#(tab)WHERE [Week_Ending_Sunday] = (SELECT MAX([Week_Ending_Sunday]) FROM #HAH) -- checking the latest week end only#(lf)#(tab)#(tab)GROUP BY [Week_Ending_Sunday]#(lf)#(tab)#(tab)HAVING COUNT(DISTINCT CAST(ContactDate AS DATE)) = 7 -- checking to see if 7 individual days have been included across to week #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  #(tab)   #(lf)#(tab)#(tab)UNION ALL#(lf)    #(lf)#(tab)#(tab)-- Include all previous weeks (those before the latest Sunday) regardless of completeness#(lf)#(tab)#(tab)SELECT [Week_Ending_Sunday]#(lf)#(tab)#(tab)FROM #HAH#(lf)#(tab)#(tab)WHERE [Week_Ending_Sunday] < (SELECT MAX([Week_Ending_Sunday]) FROM #HAH)  -- Prior weeks#(lf)#(tab)#(tab)GROUP BY [Week_Ending_Sunday]) AS FULLWEEKS#(lf)#(tab)#(tab)ON #HAH.Week_Ending_Sunday = FULLWEEKS.Week_Ending_Sunday#(lf)#(lf)LEFT JOIN [CCG_Reference].[Reference].[vw_rural_urban] AS RU#(lf)ON RU.[LSOACode] = #HAH.[LSOA Code] #(lf)#(lf)#(tab)--WHERE ContactDate <= EOMONTH ( DATEADD ( MONTH, -1, GETDATE() ) )#(lf)#(tab)ORDER BY ContactDate DESC #(lf)#(lf)#(tab)-- WHERE Visitcount = '1'#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)------- Joined to Virtual Wards table via NHS Number and searched for contacts during the VW stay --------#(lf)#(lf)#(lf)#(lf)#(tab)#(lf)#(tab)--WHERE nhs_number IS NOT NULL #(lf)#(tab)--AND #HAH.ContactDate BETWEEN VW.admission_datetime AND VW.discharge_datetime"]),
				    #"Merged Queries" = Table.NestedJoin(Source, {"ContactDate"}, #"Discharge Date Table", {"date"}, "Discharge Date Table", JoinKind.LeftOuter),
				    #"Expanded Discharge Date Table" = Table.ExpandTableColumn(#"Merged Queries", "Discharge Date Table", {"day_month_year", "day", "weekday", "weekday_name", "month", "month_name", "year_month", "financial_year", "financial_month", "month_year"}, {"Discharge Date Table.day_month_year", "Discharge Date Table.day", "Discharge Date Table.weekday", "Discharge Date Table.weekday_name", "Discharge Date Table.month", "Discharge Date Table.month_name", "Discharge Date Table.year_month", "Discharge Date Table.financial_year", "Discharge Date Table.financial_month", "Discharge Date Table.month_year"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Discharge Date Table",null,"Unknown",Replacer.ReplaceValue,{"ConsultationTypeDescription"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"Unknown",Replacer.ReplaceValue,{"ActivityLocationTypeDescription"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value1", "SeenorNotSeen", each if [AttendOrNot] = "5" then "Seen" else if [AttendOrNot] = "6" then "Not Seen" else "Unknown"),
				    #"Replaced Value2" = Table.ReplaceValue(#"Added Conditional Column","Other locations not elsewhere classified","Unknown",Replacer.ReplaceText,{"ActivityLocationTypeDescription"})
				in
				    #"Replaced Value2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

