table Acute_Admissions
	lineageTag: fb076462-bc17-4000-a78c-fd26c579a0cc

	measure 'Rate per 1000 Population Acute Admissions' = ```
			
			VAR Latest_GP_Population_date = MAX(GP_Practice_Population[first_date_of_month])
			 
			--Below calculates the rate per 1000 with the filter on the latest GP population date 
			RETURN
			IFERROR(Calculate((sum('Acute_Admissions'[Counter])/sum(GP_Practice_Population[Total_Population]))*1000,GP_Practice_Population[first_date_of_month] = Latest_GP_Population_date),BLANK())
			```
		lineageTag: 5089db6c-b0b0-4272-922b-2a2063f6b4b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pseudo_nhs_number
		dataType: string
		lineageTag: b738f8fa-4bfc-4e20-a60c-675f801ff880
		summarizeBy: none
		sourceColumn: pseudo_nhs_number

		annotation SummarizationSetBy = Automatic

	column gppractice_derived_name
		dataType: string
		lineageTag: 0cceee31-9ba0-49cb-8fff-e9fa85838a2f
		summarizeBy: none
		sourceColumn: gppractice_derived_name

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: ef309cfa-2bd7-4b42-956e-e34286bf4e1e
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column hospitalproviderspellnumber
		dataType: string
		lineageTag: c4e99132-1f88-479b-b6b9-2034a3506f41
		summarizeBy: none
		sourceColumn: hospitalproviderspellnumber

		annotation SummarizationSetBy = Automatic

	column spell_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b15dc3a-a2da-40d7-80a5-6ab76f4cc2ef
		summarizeBy: none
		sourceColumn: spell_start_date

		annotation SummarizationSetBy = Automatic

	column spell_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d6a07756-318e-4258-87c0-ff5062de8e49
		summarizeBy: none
		sourceColumn: spell_end_date

		variation Variation
			isDefault
			relationship: 6ad492ef-19ae-432e-8ecd-9cb85773d60d
			defaultHierarchy: LocalDateTable_45a12a20-3d6f-4a22-a70f-d17fbea2919e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column los_in_days
		dataType: double
		formatString: 0.000000000
		lineageTag: a36aeb3a-42b4-4e0d-872c-f9d2944ad519
		summarizeBy: sum
		sourceColumn: los_in_days

		annotation SummarizationSetBy = Automatic

	column los_bands
		dataType: string
		lineageTag: 256f04a3-4fcb-4122-80f5-0716273e57d6
		summarizeBy: none
		sourceColumn: los_bands

		annotation SummarizationSetBy = Automatic

	column primary_diagnosis
		dataType: string
		lineageTag: 4d01612c-bb23-41ab-b7d3-a9084e1cb3f7
		summarizeBy: none
		sourceColumn: primary_diagnosis

		annotation SummarizationSetBy = Automatic

	column diagnosisprimary_icd
		dataType: string
		lineageTag: fcf53da8-10e6-45ce-a6ba-b3a2beb73125
		summarizeBy: none
		sourceColumn: diagnosisprimary_icd

		annotation SummarizationSetBy = Automatic

	column keyrespiratoryconditionflag
		dataType: string
		lineageTag: 0d29e742-aa2c-4786-82cf-a9afaec7466d
		summarizeBy: none
		sourceColumn: keyrespiratoryconditionflag

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: #,0
		lineageTag: 62a97a0f-727c-4727-88d4-874ad2d6207c
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column derived_current_totalplusmff
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: fa594b09-c783-45ae-aa85-a7987284b57e
		summarizeBy: sum
		sourceColumn: derived_current_totalplusmff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column los_group
		dataType: string
		lineageTag: f34e5465-9ba9-46d2-b4c4-234ceabe06cd
		summarizeBy: none
		sourceColumn: los_group

		annotation SummarizationSetBy = Automatic

	column admissionmethod_category
		dataType: string
		lineageTag: a6395ec3-44e8-4d8c-b1c2-9d8bf69e86f3
		summarizeBy: none
		sourceColumn: admissionmethod_category

		annotation SummarizationSetBy = Automatic

	column admission_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: ca8b5de0-b832-4f49-8e4a-45060b861e2c
		summarizeBy: none
		sourceColumn: admission_datetime

		variation Variation
			isDefault
			relationship: 94f4aee7-8d95-49ab-a3d8-66eddee75522
			defaultHierarchy: LocalDateTable_a38e54c8-d949-4845-9cb2-6f7567c458a0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column discharge_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 8ac08d70-c2d6-4fd0-877d-e749dacda446
		summarizeBy: none
		sourceColumn: discharge_datetime

		variation Variation
			isDefault
			relationship: ca43e72a-2414-43ad-bd12-3b10fa434f20
			defaultHierarchy: LocalDateTable_f0cf7612-f15b-4a61-af47-7a82e8e9d6c7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column admitting_ward
		dataType: string
		lineageTag: ee738531-8781-4b11-9b54-7614b753b04b
		summarizeBy: none
		sourceColumn: admitting_ward

		annotation SummarizationSetBy = Automatic

	column admitting_ward_code
		dataType: string
		lineageTag: 7f114a78-1d40-4da3-8f5d-f227e9de5019
		summarizeBy: none
		sourceColumn: admitting_ward_code

		annotation SummarizationSetBy = Automatic

	column discharging_ward
		dataType: string
		lineageTag: 01b6a54d-4451-41bb-98fb-9a951add0ae7
		summarizeBy: none
		sourceColumn: discharging_ward

		annotation SummarizationSetBy = Automatic

	column discharging_ward_code
		dataType: string
		lineageTag: 778d52d5-e20c-4440-a157-4e4781706cd6
		summarizeBy: none
		sourceColumn: discharging_ward_code

		annotation SummarizationSetBy = Automatic

	column all_wards
		dataType: string
		lineageTag: 12991bec-0861-453f-a3d4-db793ffd88f5
		summarizeBy: none
		sourceColumn: all_wards

		annotation SummarizationSetBy = Automatic

	column all_ward_codes
		dataType: string
		lineageTag: 6923749d-e624-4fdf-a599-a5612addfa25
		summarizeBy: none
		sourceColumn: all_ward_codes

		annotation SummarizationSetBy = Automatic

	column admit_to_non_ward_area_or_ward
		dataType: string
		lineageTag: 0c4a2318-1ea7-4a32-8feb-40bb4225401c
		summarizeBy: none
		sourceColumn: admit_to_non_ward_area_or_ward

		annotation SummarizationSetBy = Automatic

	column discharge_from_non_ward_or_ward
		dataType: string
		lineageTag: f484aea2-9bfb-4646-b1b3-ecc318bb2482
		summarizeBy: none
		sourceColumn: discharge_from_non_ward_or_ward

		annotation SummarizationSetBy = Automatic

	column PracticeCodeOfRegisteredGP
		dataType: string
		lineageTag: 3e428f78-5d0d-4010-989e-feae5cbb3cc9
		summarizeBy: none
		sourceColumn: PracticeCodeOfRegisteredGP

		annotation SummarizationSetBy = Automatic

	column Diagnosis_1st_Secondary_ICD
		dataType: string
		lineageTag: 6404b255-10e6-40c2-8d98-0872da43e278
		summarizeBy: none
		sourceColumn: Diagnosis_1st_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_2nd_Secondary_ICD
		dataType: string
		lineageTag: 2e5b1fd6-6d46-4fdf-a2ec-adc8eb25dbb6
		summarizeBy: none
		sourceColumn: Diagnosis_2nd_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_3rd_Secondary_ICD
		dataType: string
		lineageTag: fb607a4b-970e-444f-b71f-98afba514468
		summarizeBy: none
		sourceColumn: Diagnosis_3rd_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_4th_Secondary_ICD
		dataType: string
		lineageTag: 5c1348f1-3581-463c-a44f-5078de1d281c
		summarizeBy: none
		sourceColumn: Diagnosis_4th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_5th_Secondary_ICD
		dataType: string
		lineageTag: d5aad38d-0fe4-4607-bddd-32d44110ec48
		summarizeBy: none
		sourceColumn: Diagnosis_5th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_6th_Secondary_ICD
		dataType: string
		lineageTag: 0de3c8c1-8388-4620-88a5-bccc8f27976b
		summarizeBy: none
		sourceColumn: Diagnosis_6th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_7th_Secondary_ICD
		dataType: string
		lineageTag: a76054a3-daeb-4933-ac2c-f122831573d5
		summarizeBy: none
		sourceColumn: Diagnosis_7th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_8th_Secondary_ICD
		dataType: string
		lineageTag: a9fff7d2-129b-448f-9a0d-850a2eefe673
		summarizeBy: none
		sourceColumn: Diagnosis_8th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_9th_Secondary_ICD
		dataType: string
		lineageTag: 041ceb1a-7cfd-4cd9-8a0b-878ae1a8d57b
		summarizeBy: none
		sourceColumn: Diagnosis_9th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_10th_Secondary_ICD
		dataType: string
		lineageTag: 32721a6b-03ba-4709-80bc-93588ca21a0c
		summarizeBy: none
		sourceColumn: Diagnosis_10th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_11th_Secondary_ICD
		dataType: string
		lineageTag: 0abb4fff-4b6e-41e0-ac4d-104be8ca1bbe
		summarizeBy: none
		sourceColumn: Diagnosis_11th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_12th_Secondary_ICD
		dataType: string
		lineageTag: 8ee56eeb-912a-4f44-9650-9cef445f9f45
		summarizeBy: none
		sourceColumn: Diagnosis_12th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	partition Acute_Admissions-21b6481c-3777-4d62-b61b-35c26c2c5ba4 = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select pseudo_nhs_number, gppractice_derived_name, locality, hospitalproviderspellnumber, spell_start_date, spell_end_date, los_in_days, los_bands, primary_diagnosis, diagnosisprimary_icd, keyrespiratoryconditionflag, counter, derived_current_totalplusmff, los_group, admissionmethod_category, admission_datetime, discharge_datetime, admitting_ward, admitting_ward_code, discharging_ward, discharging_ward_code, all_wards, all_ward_codes, admit_to_non_ward_area_or_ward, discharge_from_non_ward_or_ward, practicecodeofregisteredgp as ""PracticeCodeOfRegisteredGP"", diagnosis_1st_secondary_icd as ""Diagnosis_1st_Secondary_ICD"", diagnosis_2nd_secondary_icd as ""Diagnosis_2nd_Secondary_ICD"", diagnosis_3rd_secondary_icd as ""Diagnosis_3rd_Secondary_ICD"", diagnosis_4th_secondary_icd as ""Diagnosis_4th_Secondary_ICD"", diagnosis_5th_secondary_icd as ""Diagnosis_5th_Secondary_ICD"", diagnosis_6th_secondary_icd as ""Diagnosis_6th_Secondary_ICD"", diagnosis_7th_secondary_icd as ""Diagnosis_7th_Secondary_ICD"", diagnosis_8th_secondary_icd as ""Diagnosis_8th_Secondary_ICD"", diagnosis_9th_secondary_icd as ""Diagnosis_9th_Secondary_ICD"", diagnosis_10th_secondary_icd as ""Diagnosis_10th_Secondary_ICD"", diagnosis_11th_secondary_icd as ""Diagnosis_11th_Secondary_ICD"", diagnosis_12th_secondary_icd as ""Diagnosis_12th_Secondary_ICD"" from data_mart_powerbi_respiratory.tbl17_resp_emerg_admissions", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"counter", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

