table 'Multiple Admissions'
	lineageTag: ef65359d-6d31-426f-a3d1-3d9371b27ce3

	column pseudo_nhs_number
		dataType: string
		lineageTag: 20f841f9-1938-42aa-a475-1161846f979b
		summarizeBy: none
		sourceColumn: pseudo_nhs_number

		annotation SummarizationSetBy = Automatic

	column hospitalproviderspellnumber
		dataType: string
		lineageTag: 47e427c1-c154-458d-8dce-6e836d7ce3a6
		summarizeBy: none
		sourceColumn: hospitalproviderspellnumber

		annotation SummarizationSetBy = Automatic

	column spell_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9ddeddd9-462a-4a32-af63-4d891e4632c9
		summarizeBy: none
		sourceColumn: spell_end_date

		variation Variation
			isDefault
			relationship: 021028c0-0249-46fd-96f9-322d93ed53ec
			defaultHierarchy: LocalDateTable_189afaf5-bfed-490c-9354-fc9d4b7b1339.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column los_in_days
		dataType: double
		formatString: 0.000000000
		lineageTag: d1906583-d266-437f-8869-6b5fbcd32d13
		summarizeBy: sum
		sourceColumn: los_in_days

		annotation SummarizationSetBy = Automatic

	column los_bands
		dataType: string
		lineageTag: 81f70c0b-8e06-4bb8-b776-3e57b8654a27
		summarizeBy: none
		sourceColumn: los_bands

		annotation SummarizationSetBy = Automatic

	column derived_current_totalplusmff
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 5de66d97-2fcb-4283-8097-574de3252a7f
		summarizeBy: sum
		sourceColumn: derived_current_totalplusmff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column primary_diagnosis
		dataType: string
		lineageTag: 52920d3c-1790-4f2a-b86c-41a4620f71ed
		summarizeBy: none
		sourceColumn: primary_diagnosis

		annotation SummarizationSetBy = Automatic

	column diagnosisprimary_icd
		dataType: string
		lineageTag: 9f442a3b-258c-4d65-9d1d-388b057f7012
		summarizeBy: none
		sourceColumn: diagnosisprimary_icd

		annotation SummarizationSetBy = Automatic

	column keyrespiratoryconditionflag
		dataType: string
		lineageTag: 2e0410ae-17ed-4852-b228-2e66bb9e78f4
		summarizeBy: none
		sourceColumn: keyrespiratoryconditionflag

		annotation SummarizationSetBy = Automatic

	column counter
		dataType: int64
		formatString: #,0
		lineageTag: 9eebd8f9-2c9f-4695-b85b-132192e44f0d
		summarizeBy: sum
		sourceColumn: counter

		annotation SummarizationSetBy = Automatic

	column los_group
		dataType: string
		lineageTag: cdc6183d-e6dc-427b-8518-58514b03693b
		summarizeBy: none
		sourceColumn: los_group

		annotation SummarizationSetBy = Automatic

	column admission_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: f3286a87-e701-40af-b43a-1203db53a5bc
		summarizeBy: none
		sourceColumn: admission_datetime

		variation Variation
			isDefault
			relationship: da801736-3b3c-4898-85fd-59991c4ad34c
			defaultHierarchy: LocalDateTable_3fffde10-32dd-4b89-bd5c-1f102d957427.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column discharge_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: cbb8db80-d580-4086-902b-04a218063480
		summarizeBy: none
		sourceColumn: discharge_datetime

		variation Variation
			isDefault
			relationship: b91dd036-276b-42f9-9b3d-372fa6fe7fb9
			defaultHierarchy: LocalDateTable_f8d0394b-17d0-4ef5-9908-9a13b7dfe718.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column admitting_ward
		dataType: string
		lineageTag: 1353826c-2252-4b50-960a-bc9f37e586ae
		summarizeBy: none
		sourceColumn: admitting_ward

		annotation SummarizationSetBy = Automatic

	column admitting_ward_code
		dataType: string
		lineageTag: 48e71132-d4dd-4814-9de8-3a1bfa31ef1a
		summarizeBy: none
		sourceColumn: admitting_ward_code

		annotation SummarizationSetBy = Automatic

	column discharging_ward
		dataType: string
		lineageTag: bb73b214-c550-494d-800c-e5930ae0758d
		summarizeBy: none
		sourceColumn: discharging_ward

		annotation SummarizationSetBy = Automatic

	column discharging_ward_code
		dataType: string
		lineageTag: 04cc125a-dc91-4529-a297-b817b33b3e4b
		summarizeBy: none
		sourceColumn: discharging_ward_code

		annotation SummarizationSetBy = Automatic

	column all_wards
		dataType: string
		lineageTag: bcfd7ae3-77f8-42d4-adac-317413073d79
		summarizeBy: none
		sourceColumn: all_wards

		annotation SummarizationSetBy = Automatic

	column all_ward_codes
		dataType: string
		lineageTag: e3f2bb81-0652-4b62-bd29-26106e303da7
		summarizeBy: none
		sourceColumn: all_ward_codes

		annotation SummarizationSetBy = Automatic

	column admit_to_non_ward_area_or_ward
		dataType: string
		lineageTag: 3061943f-90bd-48e3-94a5-fbca1804efd2
		summarizeBy: none
		sourceColumn: admit_to_non_ward_area_or_ward

		annotation SummarizationSetBy = Automatic

	column discharge_from_non_ward_or_ward
		dataType: string
		lineageTag: de5e9090-7d67-498b-a8dd-665a31698da2
		summarizeBy: none
		sourceColumn: discharge_from_non_ward_or_ward

		annotation SummarizationSetBy = Automatic

	column GP_Practice_Code
		dataType: string
		lineageTag: 263892ff-887b-4b51-aa98-7593b665b612
		summarizeBy: none
		sourceColumn: GP_Practice_Code

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: 5bf16d94-edfc-495e-8017-6d9d00681c34
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column admissionmethod_category
		dataType: string
		lineageTag: c6233508-8d44-496f-9cd3-b3280f67a667
		summarizeBy: none
		sourceColumn: admissionmethod_category

		annotation SummarizationSetBy = Automatic

	column spell_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b4578d40-daef-49b0-a5d9-a17fe37025e2
		summarizeBy: none
		sourceColumn: spell_start_date

		annotation SummarizationSetBy = Automatic

	column Diagnosis_1st_Secondary_ICD
		dataType: string
		lineageTag: 765ca668-b0a0-4304-90c6-d7c68c991a0f
		summarizeBy: none
		sourceColumn: Diagnosis_1st_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_2nd_Secondary_ICD
		dataType: string
		lineageTag: a5812ebe-662e-4f8e-bb5c-cbaea16280a3
		summarizeBy: none
		sourceColumn: Diagnosis_2nd_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_3rd_Secondary_ICD
		dataType: string
		lineageTag: e8b2bfbd-61e5-4b72-b005-387c427e5113
		summarizeBy: none
		sourceColumn: Diagnosis_3rd_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_4th_Secondary_ICD
		dataType: string
		lineageTag: 06c6d4ec-403d-4bd4-a6e3-bd36169ce504
		summarizeBy: none
		sourceColumn: Diagnosis_4th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_5th_Secondary_ICD
		dataType: string
		lineageTag: b23241af-ed43-45dc-bf1f-a642c12f4649
		summarizeBy: none
		sourceColumn: Diagnosis_5th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_6th_Secondary_ICD
		dataType: string
		lineageTag: f4bef53f-89b3-4f1b-b841-3894522eb95c
		summarizeBy: none
		sourceColumn: Diagnosis_6th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_7th_Secondary_ICD
		dataType: string
		lineageTag: 0dfa2448-b6c3-4222-9a9c-cb5b4511befc
		summarizeBy: none
		sourceColumn: Diagnosis_7th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_8th_Secondary_ICD
		dataType: string
		lineageTag: f2fd8b59-fa24-4d18-acaf-6fff09900ccf
		summarizeBy: none
		sourceColumn: Diagnosis_8th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_9th_Secondary_ICD
		dataType: string
		lineageTag: f19b0b91-ac69-417a-9ffa-3703e61cd52b
		summarizeBy: none
		sourceColumn: Diagnosis_9th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_10th_Secondary_ICD
		dataType: string
		lineageTag: 7ee92929-0773-4c63-ba7e-788857a93549
		summarizeBy: none
		sourceColumn: Diagnosis_10th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_11th_Secondary_ICD
		dataType: string
		lineageTag: 675d9228-407f-4144-86ef-788b81076fcd
		summarizeBy: none
		sourceColumn: Diagnosis_11th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Diagnosis_12th_Secondary_ICD
		dataType: string
		lineageTag: e98b2c52-ae27-47e6-8d34-ba7c5a7d8ee3
		summarizeBy: none
		sourceColumn: Diagnosis_12th_Secondary_ICD

		annotation SummarizationSetBy = Automatic

	column Readmission_365_Day
		dataType: int64
		formatString: 0
		lineageTag: e722d7c0-3386-4522-b8e3-ede23dd82ce2
		summarizeBy: sum
		sourceColumn: Readmission_365_Day

		annotation SummarizationSetBy = Automatic

	partition 'Multiple Admissions-6559f721-b027-43c4-abbb-32e08a08d84a' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonRedshift.Database("ics-glos-reporting.cw0unw24a7tv.eu-west-2.redshift.amazonaws.com:5444","db02_nopid"), "select pseudo_nhs_number, hospitalproviderspellnumber, spell_end_date, los_in_days, los_bands, derived_current_totalplusmff, primary_diagnosis, diagnosisprimary_icd, keyrespiratoryconditionflag, counter, los_group, admission_datetime, discharge_datetime, admitting_ward, admitting_ward_code, discharging_ward, discharging_ward_code, all_wards, all_ward_codes, admit_to_non_ward_area_or_ward, discharge_from_non_ward_or_ward, gp_practice_code as ""GP_Practice_Code"", locality, admissionmethod_category, spell_start_date, diagnosis_1st_secondary_icd as ""Diagnosis_1st_Secondary_ICD"", diagnosis_2nd_secondary_icd as ""Diagnosis_2nd_Secondary_ICD"", diagnosis_3rd_secondary_icd as ""Diagnosis_3rd_Secondary_ICD"", diagnosis_4th_secondary_icd as ""Diagnosis_4th_Secondary_ICD"", diagnosis_5th_secondary_icd as ""Diagnosis_5th_Secondary_ICD"", diagnosis_6th_secondary_icd as ""Diagnosis_6th_Secondary_ICD"", diagnosis_7th_secondary_icd as ""Diagnosis_7th_Secondary_ICD"", diagnosis_8th_secondary_icd as ""Diagnosis_8th_Secondary_ICD"", diagnosis_9th_secondary_icd as ""Diagnosis_9th_Secondary_ICD"", diagnosis_10th_secondary_icd as ""Diagnosis_10th_Secondary_ICD"", diagnosis_11th_secondary_icd as ""Diagnosis_11th_Secondary_ICD"", diagnosis_12th_secondary_icd as ""Diagnosis_12th_Secondary_ICD"", readmission_365_day as ""Readmission_365_Day"" from data_mart_powerbi_respiratory.tbl18_resp_multiple_admissions", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"counter", Int64.Type}, {"los_in_days", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

