table vw_Gynae_APC
	lineageTag: c8a3d660-737d-4f67-a27b-2e6269a63274

	column NHSNumber
		dataType: string
		lineageTag: cdb2bf1d-f15e-4fb3-8132-ef74553836cf
		summarizeBy: none
		sourceColumn: NHSNumber

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: ce7e5190-16d1-4d6d-a37a-ad1d27519b22
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column HospitalProviderSpellNumber
		dataType: string
		lineageTag: 687bb962-18a5-487f-a35d-415992efd199
		summarizeBy: none
		sourceColumn: HospitalProviderSpellNumber

		annotation SummarizationSetBy = Automatic

	column Procedure_OPCS_Description
		dataType: string
		lineageTag: e6dd8c38-87e2-47a8-9557-cb76b054f7ad
		summarizeBy: none
		sourceColumn: Procedure_OPCS_Description

		annotation SummarizationSetBy = Automatic

	column ProcedureDate_OPCS
		dataType: dateTime
		formatString: Long Date
		lineageTag: 37840dc1-1968-46f0-819e-182f98ae52a6
		summarizeBy: none
		sourceColumn: ProcedureDate_OPCS

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProcedureDate_OPCS_MonthYear
		dataType: string
		lineageTag: 46b1181c-8d2d-4dc3-badd-8e43e3c9c505
		summarizeBy: none
		sourceColumn: ProcedureDate_OPCS_MonthYear
		sortByColumn: ProcedureDate_OPCS_YearMonth_Num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ProcedureDate_OPCS_FinancialYear
		dataType: string
		lineageTag: 36ff2f7c-d364-4915-bb3f-0a09b16fc0a1
		summarizeBy: none
		sourceColumn: ProcedureDate_OPCS_FinancialYear

		annotation SummarizationSetBy = Automatic

	column Procedure_Type
		dataType: string
		lineageTag: efe55e40-b57a-4fc0-9ebb-9d3b0ee1731a
		summarizeBy: none
		sourceColumn: Procedure_Type

		annotation SummarizationSetBy = Automatic

	column ProviderCode
		dataType: string
		lineageTag: 595e1f1d-7ec6-426b-a814-d3713013d2e4
		summarizeBy: none
		sourceColumn: ProviderCode

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: 35d36a2c-f2b2-4afb-8e94-1982bae9726f
		summarizeBy: none
		sourceColumn: PracticeCode

		annotation SummarizationSetBy = Automatic

	column PracticeNameOfRegisteredGP
		dataType: string
		lineageTag: 821f60d7-d687-42bd-a4ee-113b06c0ad56
		summarizeBy: none
		sourceColumn: PracticeNameOfRegisteredGP

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 63b020cc-83e2-4f4a-8252-b3502a98d1e4
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 10YR_Age_Band
		dataType: string
		lineageTag: 2b7b964e-90e3-4ab0-a9f6-8dda3a5fac22
		summarizeBy: none
		sourceColumn: 10YR_Age_Band

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 509571d0-4687-48f0-897a-0c81d6b8e880
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EthnicCategory
		dataType: string
		lineageTag: 589cd1be-3056-4c7d-88ce-5f2274c16ea8
		summarizeBy: none
		sourceColumn: EthnicCategory

		annotation SummarizationSetBy = Automatic

	column EthnicCategory_Description
		dataType: string
		lineageTag: 7b388e17-60d1-4663-a7e2-dcf2f1f1605b
		summarizeBy: none
		sourceColumn: EthnicCategory_Description

		annotation SummarizationSetBy = Automatic

	column Postcode
		dataType: int64
		formatString: 0
		lineageTag: f9fb25c6-85be-4794-912b-528bb306b476
		summarizeBy: none
		sourceColumn: Postcode

		annotation SummarizationSetBy = User

	column TreatmentFunctionCode
		dataType: string
		lineageTag: ef465856-40ad-463f-81ee-324457eecace
		summarizeBy: none
		sourceColumn: TreatmentFunctionCode

		annotation SummarizationSetBy = Automatic

	column TreatmentFunction_Description
		dataType: string
		lineageTag: e93d4865-75af-49c3-ba06-9d68ae5882af
		summarizeBy: none
		sourceColumn: TreatmentFunction_Description

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: 0
		lineageTag: 7062896c-8623-4a4e-a8a6-63bb2d7de867
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	column Programme_Outcome
		dataType: string
		lineageTag: 6c9d8ba9-bf5e-4d40-bbc3-6f18637c776b
		summarizeBy: none
		sourceColumn: Programme_Outcome

		annotation SummarizationSetBy = Automatic

	column ProcedureDate_OPCS_YearMonth_Num
		dataType: string
		lineageTag: 2eff55c0-7d6a-4722-803a-dbdca9c97c77
		summarizeBy: none
		sourceColumn: ProcedureDate_OPCS_YearMonth_Num

		annotation SummarizationSetBy = Automatic

	column PCN
		dataType: string
		lineageTag: 0ceea2ff-7a8c-48b6-89c7-071f2da86cc4
		summarizeBy: none
		sourceColumn: PCN

		annotation SummarizationSetBy = Automatic

	partition vw_Gynae_APC = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Processing"),
				    dbo_vw_Gynae_APC = Source{[Schema="dbo",Item="vw_Gynae_APC"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vw_Gynae_APC,{{"ProcedureDate_OPCS", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

