table vw_Gynae_OPA
	lineageTag: e3f006c1-6704-4bdd-873b-bc4f072594f4

	column NHSNumber
		dataType: string
		lineageTag: 4c2190d1-a583-477f-937c-b68941328b7d
		summarizeBy: none
		sourceColumn: NHSNumber

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 6efba897-3bb4-4046-96aa-cc8975b213f3
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column AppointmentDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 49bc94b3-9844-4c46-8c31-817448253af7
		summarizeBy: none
		sourceColumn: AppointmentDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AppointmentDate_MonthYear
		dataType: string
		lineageTag: 56ef096e-3902-4c0b-979e-f959815e66a9
		summarizeBy: none
		sourceColumn: AppointmentDate_MonthYear
		sortByColumn: AppointmentDate_YearMonth_Num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column AppointmentDate_FinancialYear
		dataType: string
		lineageTag: 8b2db928-1ec7-4839-854e-e5b08de83b38
		summarizeBy: none
		sourceColumn: AppointmentDate_FinancialYear

		annotation SummarizationSetBy = Automatic

	column ProviderCode
		dataType: string
		lineageTag: c978537b-e5f1-431e-9b81-631338984cba
		summarizeBy: none
		sourceColumn: ProviderCode

		annotation SummarizationSetBy = Automatic

	column PracticeCode
		dataType: string
		lineageTag: 3f7b2818-c1f8-4850-8786-739963decb8d
		summarizeBy: none
		sourceColumn: PracticeCode

		annotation SummarizationSetBy = Automatic

	column PracticeNameOfRegisteredGP
		dataType: string
		lineageTag: 8536f7d9-bd72-437a-8013-653b9aeb021d
		summarizeBy: none
		sourceColumn: PracticeNameOfRegisteredGP

		annotation SummarizationSetBy = Automatic

	column AttendedOrDidNotAttend
		dataType: string
		lineageTag: 8e6785d3-21af-47fe-9659-9beeafbc85c1
		summarizeBy: none
		sourceColumn: AttendedOrDidNotAttend

		annotation SummarizationSetBy = Automatic

	column AttendedOrDidNotAttend_Description
		dataType: string
		lineageTag: 3598ac2c-df86-4074-8c43-a0f207a345e9
		summarizeBy: none
		sourceColumn: AttendedOrDidNotAttend_Description

		annotation SummarizationSetBy = Automatic

	column FirstAttendance
		dataType: string
		lineageTag: f8016ad6-9eb6-4d01-8d05-ab55bb64cabd
		summarizeBy: none
		sourceColumn: FirstAttendance

		annotation SummarizationSetBy = Automatic

	column FirstAttendance_Description
		dataType: string
		lineageTag: e1da72fa-4640-488c-975a-afeb2772a1c0
		summarizeBy: none
		sourceColumn: FirstAttendance_Description

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: b322c468-4fdf-4fb9-8980-f1a2cd7146ce
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = User

	column 10YR_Age_Band
		dataType: string
		lineageTag: df1ce948-81ed-4ca0-b3e6-d1aabde2ad7f
		summarizeBy: none
		sourceColumn: 10YR_Age_Band

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 0902ed80-d923-4f5d-aa8e-42752517d348
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EthnicCategory
		dataType: string
		lineageTag: e74bb069-2d9b-426e-93e4-6a4aaeed8893
		summarizeBy: none
		sourceColumn: EthnicCategory

		annotation SummarizationSetBy = Automatic

	column EthnicCategory_Description
		dataType: string
		lineageTag: ccc2a753-218d-487c-bb70-cff2fae3910f
		summarizeBy: none
		sourceColumn: EthnicCategory_Description

		annotation SummarizationSetBy = Automatic

	column Postcode
		dataType: int64
		formatString: 0
		lineageTag: 35ac29e3-59d1-4480-a089-89bcacfdb9cc
		summarizeBy: none
		sourceColumn: Postcode

		annotation SummarizationSetBy = User

	column DeprivationDecile
		dataType: double
		lineageTag: 97c238ab-9060-4de9-a635-189682268a52
		summarizeBy: none
		sourceColumn: DeprivationDecile

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TreatmentFunctionCode
		dataType: string
		lineageTag: 54131334-806d-4cfb-a93a-30a69727d936
		summarizeBy: none
		sourceColumn: TreatmentFunctionCode

		annotation SummarizationSetBy = Automatic

	column TreatmentFunction_Description
		dataType: string
		lineageTag: b06c2bc5-6f69-46fe-98e8-87ef8db9c097
		summarizeBy: none
		sourceColumn: TreatmentFunction_Description

		annotation SummarizationSetBy = Automatic

	column SourceofReferralCode
		dataType: string
		lineageTag: 6a742cab-796e-41c5-af8c-1e13aa6c4e71
		summarizeBy: none
		sourceColumn: SourceofReferralCode

		annotation SummarizationSetBy = Automatic

	column AppointmentDate_YearMonth_Num
		dataType: string
		lineageTag: 14e1d6b8-214b-4fc3-a99c-2a5adeb3cbcd
		summarizeBy: none
		sourceColumn: AppointmentDate_YearMonth_Num

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: #,0
		lineageTag: d5061fae-400c-4412-b84f-42a46a1d1ab2
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	column LARC_Pres_Flag
		dataType: int64
		formatString: 0
		lineageTag: 634a84f8-2ee9-4b16-928f-905fbb3a63b7
		summarizeBy: none
		sourceColumn: LARC_Pres_Flag

		annotation SummarizationSetBy = User

	column Procedure_Type
		dataType: string
		lineageTag: 9998adea-4403-4f64-8b01-abdf28da5158
		summarizeBy: none
		sourceColumn: Procedure_Type

		annotation SummarizationSetBy = Automatic

	column PrimaryProcedure_OPCS_Description
		dataType: string
		lineageTag: d548ecf8-da90-48e2-852e-cfe2a767a675
		summarizeBy: none
		sourceColumn: PrimaryProcedure_OPCS_Description

		annotation SummarizationSetBy = Automatic

	column Procedure2nd_OPCS_Description
		dataType: string
		lineageTag: 14db185e-ae7a-4174-a928-b1d93c7da29b
		summarizeBy: none
		sourceColumn: Procedure2nd_OPCS_Description

		annotation SummarizationSetBy = Automatic

	column Programme_Outcome
		dataType: string
		lineageTag: a55e0c42-c4d6-4ebf-bfea-cf830d803a57
		summarizeBy: none
		sourceColumn: Programme_Outcome

		annotation SummarizationSetBy = Automatic

	column PCN
		dataType: string
		lineageTag: 6ca14a88-742b-4ce9-83cb-8e64796bd3c5
		summarizeBy: none
		sourceColumn: PCN

		annotation SummarizationSetBy = Automatic

	partition vw_Gynae_OPA = m
		mode: import
		source =
				let
				    Source = Sql.Database("grh-ccg-sql", "PowerBI_Processing"),
				    dbo_vw_Gynae_OPA = Source{[Schema="dbo",Item="vw_Gynae_OPA"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vw_Gynae_OPA,{{"AppointmentDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

